export interface ConCentroCosto {
	CORR_EMPRESA: number;
	CORR_CENTRO_COSTO: number;
	NOMBRE_CENTRO: string;
	CUENTA_CONTABLE: string;
	CODIGO_CENTRO_COSTO: string;
	CORR_TIPO_CENTRO_COSTO: number;
	NOMBRE_TIPO_CENTRO_COSTO: string;
	CLASE_CENTRO_COSTO: string;
	ESTADO_CENTRO_COSTO: string;
	NOMBRE_ESTADO_CENTRO_COSTO: string;
	CORR_CENTRO_COSTO_REPLICADO: string;
	CORR_UNIDAD_NEGOCIO: number;
	NOMBRE_UNIDAD_NEGOCIO: string;
	CODIGO_UNIDAD_NEGOCIO: string;
	CORR_AREA_FUNCIONAL: number;
	NOMBRE_AREA_FUNCIONAL: string;
	CODIGO_TERMINACION: string;
	CORR_EMPLEADO_JEFE: number;
	NOMBRE_EMPLEADO: string;
	CORR_CLIENTE: number;
	FECHA_INICIAL: Date;
	FECHA_FINAL: Date;
}
