SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[FN_CON_SALDO_HISTORICO]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_MONEDA INT=NULL,
	@CUENTA_CONTABLE_INICIAL VARCHAR(30)=NULL,
	@CUENTA_CONTABLE_FINAL VARCHAR(30)=NULL,
	@CORR_AUXILIAR INT=NULL,
	@CORR_CENTRO_COSTO INT=NULL,
	@CORR_CONFI_REPORTE INT=NULL,
	@NIVEL SMALLINT=3,
	@POR_CUENTA_CONTABLE BIT=0,
	@POR_AUXILIAR BIT=0,
	@POR_CENTRO_COSTO BIT=0,
	@OPCION_CONSULTA INT=0
)
RETURNS 
@SALDO TABLE 
(				
		CORR_EMPRESA INT,
		CORR_MONEDA INT,		
		CUENTA_CONTABLE varchar(30),
		CORR_AUXILIAR INT,
		CORR_CENTRO_COSTO INT,		
		CUENTA_MAYOR varchar(30),
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(12,2),			
		EXISTE_PARTIDA_INI INT
)
AS	
BEGIN
	
	--Obtener el saldo inicial de todas las cuentas hasta un nivel y hasta la fecha de consulta
	IF @OPCION_CONSULTA=0
	BEGIN		
		INSERT INTO @SALDO
		(
		CORR_EMPRESA,
		CORR_MONEDA,
		CUENTA_CONTABLE,
		CORR_AUXILIAR,
		CORR_CENTRO_COSTO,
		CUENTA_MAYOR,
		ES_DEBE,
		ES_HABER,
		SALDO_INICIAL,	
		EXISTE_PARTIDA_INI)    
		SELECT A.CORR_EMPRESA
		,B.CORR_MONEDA
		,CASE WHEN @POR_CUENTA_CONTABLE=0 THEN NULL ELSE A.CUENTA_CONTABLE END CUENTA_CONTABLE
		,CASE WHEN @POR_AUXILIAR=0 THEN NULL ELSE AU.CORR_AUXILIAR END CORR_AUXILIAR
		,CASE WHEN @POR_CENTRO_COSTO=0 THEN NULL ELSE CC.CORR_CENTRO_COSTO END CORR_CENTRO_COSTO
		,A.CUENTA_MAYOR
		,A.ES_DEBE
		,A.ES_HABER
		,SUM(CASE @MES_PERIODO 
		WHEN 1 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL1,0))
		WHEN 2 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL2,0))
		WHEN 3 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL3,0))
		WHEN 4 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL4,0))
		WHEN 5 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL5,0))
		WHEN 6 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL6,0))
		WHEN 7 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL7,0))
		WHEN 8 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL8,0))
		WHEN 9 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL9,0))
		WHEN 10 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL10,0))
		WHEN 11 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL11,0))
		WHEN 12 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL12,0))
		ELSE 0 END) MES_PERIODO
		,ISNULL(C.MES_PERIODO,0)
		FROM CON_CATALOGO_CUENTA A
		LEFT OUTER JOIN CON_CATALOGO_CUENTA_AUXI AU ON A.CORR_EMPRESA=AU.CORR_EMPRESA AND A.CUENTA_CONTABLE=AU.CUENTA_CONTABLE
		LEFT OUTER JOIN CON_CATALOGO_CUENTA_CENTRO_COSTO CC ON A.CORR_EMPRESA=CC.CORR_EMPRESA AND A.CUENTA_CONTABLE=CC.CUENTA_CONTABLE		
		LEFT OUTER JOIN CON_CATALOGO_SALDO_HIS_CENTRO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE 
					AND (B.CORR_MONEDA=@CORR_MONEDA OR ISNULL(@CORR_MONEDA,0)=0) AND B.ANIO_PERIODO=@ANIO_PERIODO AND ISNULL(AU.CORR_AUXILIAR,0)=ISNULL(B.CORR_AUXILIAR,0) AND ISNULL(CC.CORR_CENTRO_COSTO,0)=ISNULL(B.CORR_CENTRO_COSTO,0)		
		LEFT OUTER JOIN (
						SELECT  A.CORR_EMPRESA, A.ANIO_PERIODO,A.MES_PERIODO
						,SUBSTRING(A.CUENTA_CONTABLE,1,B.NUMERO_CARACTERES) CUENTA_CONTABLE
						,A.CORR_AUXILIAR
						,A.CORR_CENTRO_COSTO
						,SUM(A.SALDO_INICIAL) SALDO_INICIAL
						,SUM(A.SALDO_INICIAL_FORANEA) SALDO_INICIAL_FORANEA
						FROM V_CON_PARTIDA_INICIAL A
						INNER JOIN CON_CATALOGO_CUENTA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_CONTABLE
						INNER JOIN V_CON_RUBRO_NIVEL_MAX D ON C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CODIGO_RUBRO=D.CODIGO_RUBRO						
						INNER JOIN CON_RUBRO_NIVEL B ON C.CORR_EMPRESA=B.CORR_EMPRESA AND C.CODIGO_RUBRO=B.CODIGO_RUBRO AND B.NIVEL=CASE WHEN @NIVEL=0 THEN D.NIVEL_MAX ELSE @NIVEL END
						GROUP BY  A.CORR_EMPRESA, A.ANIO_PERIODO,A.MES_PERIODO
						,SUBSTRING(A.CUENTA_CONTABLE,1,B.NUMERO_CARACTERES)
						,A.CORR_AUXILIAR
						,A.CORR_CENTRO_COSTO
						) C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_CONTABLE
						AND C.ANIO_PERIODO=@ANIO_PERIODO AND C.MES_PERIODO=@MES_PERIODO AND AU.CORR_AUXILIAR=C.CORR_AUXILIAR AND CC.CORR_CENTRO_COSTO=C.CORR_CENTRO_COSTO
		
		
		--LEFT OUTER JOIN CON_CONFI_REPORTE_DETA D ON A.CORR_EMPRESA=D.CORR_EMPRESA
		--AND (A.CUENTA_CONTABLE>=D.CUENTA_CONTABLE_INI OR ISNULL(D.CUENTA_CONTABLE_INI,'')='')
		--AND (A.CUENTA_CONTABLE<=D.CUENTA_CONTABLE_FINA OR ISNULL(D.CUENTA_CONTABLE_FINA,'')='')
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND ((@OPCION_CONSULTA=0 AND A.NIVEL<=@NIVEL) --@OPCION_CONSULTA=0 Hasta un nivel
			OR (@OPCION_CONSULTA IN(1,2) AND A.NIVEL=@NIVEL) --@OPCION_CONSULTA=1 Un nivel especifico			
			OR @NIVEL=0 --Todos los niveles
			)
		AND ((@OPCION_CONSULTA=2 AND A.CLASE_RUBRO IN('IN','GA')) OR @OPCION_CONSULTA<>2) --@OPCION_CONSULTA=2 Un nivel especifico, solo cuentas de ingresos y gastos		
		AND (A.CUENTA_CONTABLE>=@CUENTA_CONTABLE_INICIAL OR ISNULL(@CUENTA_CONTABLE_INICIAL,'')='')
		AND (A.CUENTA_CONTABLE<=@CUENTA_CONTABLE_FINAL OR ISNULL(@CUENTA_CONTABLE_FINAL,'')='')
		AND (AU.CORR_AUXILIAR=@CORR_AUXILIAR OR ISNULL(@CORR_AUXILIAR,0)=0)
		AND (CC.CORR_CENTRO_COSTO=@CORR_CENTRO_COSTO OR ISNULL(@CORR_CENTRO_COSTO,0)=0)
		--AND (D.CORR_CONFI_REPORTE=@CORR_CONFI_REPORTE OR @CORR_CONFI_REPORTE IS NULL)
		GROUP BY A.CORR_EMPRESA
		,B.CORR_MONEDA
		,CASE WHEN @POR_CUENTA_CONTABLE=0 THEN NULL ELSE A.CUENTA_CONTABLE END
		,CASE WHEN @POR_AUXILIAR=0 THEN NULL ELSE AU.CORR_AUXILIAR END
		,CASE WHEN @POR_CENTRO_COSTO=0 THEN NULL ELSE CC.CORR_CENTRO_COSTO END
		,A.CUENTA_MAYOR
		,A.ES_DEBE
		,A.ES_HABER		
		,ISNULL(C.MES_PERIODO,0)
		
	END	
	
	
	RETURN
END
GO
