SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[FN_UNIDAD]
(
	@NOMBRE_ITEM VARCHAR(100)
)
RETURNS VARCHAR(100)
AS	
BEGIN	
	DECLARE @UNIDAD VARCHAR(100)

	SELECT @UNIDAD=@NOMBRE_ITEM
	
	IF (CHARINDEX('(',@UNIDAD)>0)
	BEGIN
		WHILE (CHARINDEX('(',@UNIDAD)>0 AND LEN(@UNIDAD)>0)
		BEGIN	
			SELECT @UNIDAD=SUBSTRING(@UNIDAD,CHARINDEX('(',@UNIDAD)+1,LEN(@UNIDAD) - CHARINDEX('(',@UNIDAD))
		END

		IF CHARINDEX(')', @UNIDAD)>0
		BEGIN
			SELECT @UNIDAD=SUBSTRING(@UNIDAD,1,(CHARINDEX(')', @UNIDAD) - CHARINDEX('(',@UNIDAD)) - 1)
		END
	END ELSE
	BEGIN
		SELECT @UNIDAD=''
	END
	
	RETURN LTRIM(RTRIM(@UNIDAD))

END
GO
