SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[DIVIDIR]
(
	@DIVIDENDO DECIMAL(18,8),
	@DIVISOR DECIMAL(18,8)
)
RETURNS DECIMAL(18,8)
AS	
BEGIN	
	DECLARE @COCIENTE DECIMAL(18,8)
	
	SELECT @COCIENTE=CASE WHEN @DIVISOR<>0 THEN @DIVIDENDO/@DIVISOR ELSE 0 END
	
	RETURN @COCIENTE

END
GO
