SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[FN_CON_SALDO_MOV]
(
	@CORR_EMPRESA INT,
	@FECHA_INICIAL Date,
	@FECHA_FINAL Date,
	@CORR_MONEDA INT=NULL,
	@CUENTA_CONTABLE_INICIAL VARCHAR(30)=NULL,
	@CUENTA_CONTABLE_FINAL VARCHAR(30)=NULL,
	@CORR_AUXILIAR INT=NULL,	
	@CORR_CENTRO_COSTO INT=NULL,
	@CORR_CONFI_REPORTE INT=NULL,
	@NIVEL SMALLINT=3,
	@PARTIDA_CIERRE BIT=0,
	@PARTIDA_LIQUIDACION BIT=0,	
	@POR_CUENTA_CONTABLE BIT=0,
	@POR_AUXILIAR BIT=0,
	@POR_CENTRO_COSTO BIT=0,
	@OPCION_CONSULTA INT=0
)
RETURNS 
@SALDO_MOV TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE VARCHAR(30),
		CORR_AUXILIAR INT,
		CORR_CENTRO_COSTO INT,
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),
		CARGO_PERIODO_FORANEA DECIMAL(12,2),
		ABONO_PERIODO_FORANEA DECIMAL(12,2)
	)
AS	
BEGIN		
	
	IF @OPCION_CONSULTA=0
	BEGIN
		INSERT INTO @SALDO_MOV
		(CORR_EMPRESA,CUENTA_CONTABLE,CORR_AUXILIAR,CORR_CENTRO_COSTO,CARGO_PERIODO,ABONO_PERIODO,CARGO_PERIODO_FORANEA,ABONO_PERIODO_FORANEA)
		SELECT A.CORR_EMPRESA,
		CASE WHEN @POR_CUENTA_CONTABLE=0 THEN NULL ELSE SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END) END CUENTA_CONTABLE,
		CASE WHEN @POR_AUXILIAR=0 THEN NULL ELSE A.CORR_AUXILIAR END CORR_AUXILIAR,
		CASE WHEN @POR_CENTRO_COSTO=0 THEN NULL ELSE A.CORR_CENTRO_COSTO END CORR_CENTRO_COSTO,
		SUM(A.MONTO_CARGO) MONTO_CARGO,SUM(A.MONTO_ABONO) MONTO_ABONO,
		SUM(A.MONTO_CARGO_FORANEA) MONTO_CARGO_FORANEA,SUM(A.MONTO_ABONO_FORANEA) MONTO_ABONO_FORANEA
		FROM V_CON_PARTIDA_CUENTA A
		INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
		INNER JOIN CON_RUBRO_NIVEL C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CODIGO_RUBRO=C.CODIGO_RUBRO AND C.NIVEL=CASE WHEN @NIVEL=0 THEN 1 ELSE @NIVEL END
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA				
		AND A.FECHA_PARTIDA>=@FECHA_INICIAL
		AND A.FECHA_PARTIDA<=@FECHA_FINAL
		AND (A.CUENTA_CONTABLE>=@CUENTA_CONTABLE_INICIAL OR ISNULL(@CUENTA_CONTABLE_INICIAL,'')='')
		AND (A.CUENTA_CONTABLE<=@CUENTA_CONTABLE_FINAL OR ISNULL(@CUENTA_CONTABLE_FINAL,'')='')
		AND (A.CORR_AUXILIAR=@CORR_AUXILIAR OR ISNULL(@CORR_AUXILIAR,0)=0)
		AND (A.CORR_CENTRO_COSTO=@CORR_CENTRO_COSTO OR ISNULL(@CORR_CENTRO_COSTO,0)=0)
		AND (A.PARTIDA_CIERRE=@PARTIDA_CIERRE OR @PARTIDA_CIERRE=1)
		AND (A.PARTIDA_LIQUIDACION=@PARTIDA_LIQUIDACION OR @PARTIDA_LIQUIDACION=1)		
		GROUP BY A.CORR_EMPRESA,
		CASE WHEN @POR_CUENTA_CONTABLE=0 THEN NULL ELSE SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END) END,
		CASE WHEN @POR_AUXILIAR=0 THEN NULL ELSE A.CORR_AUXILIAR END,
		CASE WHEN @POR_CENTRO_COSTO=0 THEN NULL ELSE A.CORR_CENTRO_COSTO END
	END
	
	RETURN
END
GO
