SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[FN_CON_SALDO_INICIAL_CENTRO_COSTO]
(
	@CORR_EMPRESA INT,
	@FECHA_CONSULTA Date,
	@CORR_MONEDA INT=NULL,
	@CUENTA_CONTABLE_INICIAL VARCHAR(30)=NULL,
	@CUENTA_CONTABLE_FINAL VARCHAR(30)=NULL,
	@CORR_AUXILIAR INT=NULL,
	@CORR_CENTRO_COSTO INT=NULL,
	@CORR_CONFI_REPORTE INT=NULL,
	@NIVEL SMALLINT=3,
	@MAYORIZA BIT=0,
	@APLICA_DEBE_HABE BIT=0,
	@PARTIDA_CIERRE BIT=0,
	@PARTIDA_LIQUIDACION BIT=0,	
	@POR_CUENTA_CONTABLE BIT=0,
	@POR_AUXILIAR BIT=0,
	@POR_CENTRO_COSTO BIT=0,
	@OPCION_CONSULTA INT=0
)
RETURNS 
@SALDO TABLE 
(				
		CORR_EMPRESA INT,
		CORR_MONEDA INT,		
		CUENTA_CONTABLE VARCHAR(30),
		CORR_AUXILIAR INT,
		CORR_CENTRO_COSTO INT,		
		CUENTA_MAYOR varchar(30),
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(12,2),
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),		
		SALDO_FINAL	DECIMAL(12,2),
		CARGO_PERIODO_MES DECIMAL(12,2),
		ABONO_PERIODO_MES DECIMAL(12,2),
		EXISTE_PARTIDA_INI INT
)
AS	
BEGIN
	DECLARE
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@ANIO_PERIODO_ANTE INT,
	@MES_PERIODO_ANTE INT,
	@FECHA_INICIAL DATE,
	@CUENTA_CONTABLE VARCHAR(30),
	@CUENTA_MAYOR varchar(30),
	@SALDO_INICIAL DECIMAL(12,2),
	@CARGO_PERIODO DECIMAL(12,2),
	@ABONO_PERIODO DECIMAL(12,2),
	@CARGO_PERIODO_MES DECIMAL(12,2),
	@ABONO_PERIODO_MES DECIMAL(12,2),
	@NIVEL_MAX SMALLINT,
	@EXISTE_PARTIDA_INI INT
	
	DECLARE @CARGO_ABONO TABLE
	(		
		CUENTA_CONTABLE varchar(30),
		SALDO_INICIAL DECIMAL(12,2),			
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),
		CARGO_PERIODO_MES DECIMAL(12,2),
		ABONO_PERIODO_MES DECIMAL(12,2)		
	)
	
	--Obteniendo el periodo inicial
	-----------------------------------------------------------------------------------------
	SELECT @ANIO_PERIODO=A.ANIO_PERIODO, @MES_PERIODO=A.MES_PERIODO
	FROM FN_CON_PERIODO_INICIAL(
	@CORR_EMPRESA,	
	@FECHA_CONSULTA) A
	
	--Obteniendo Saldo Inicial Historico
	-----------------------------------------------------------------------------------------
	INSERT INTO @SALDO
	(
	CORR_EMPRESA,
	CORR_MONEDA,		
	CUENTA_CONTABLE,
	CORR_AUXILIAR,
	CORR_CENTRO_COSTO,
	CUENTA_MAYOR,
	ES_DEBE,
	ES_HABER,
	SALDO_INICIAL,
	CARGO_PERIODO,
	ABONO_PERIODO,
	SALDO_FINAL,
	CARGO_PERIODO_MES,
	ABONO_PERIODO_MES,
	EXISTE_PARTIDA_INI)
	SELECT 
	A.CORR_EMPRESA,
	A.CORR_MONEDA,		
	A.CUENTA_CONTABLE,
	A.CORR_AUXILIAR,
	A.CORR_CENTRO_COSTO,
	A.CUENTA_MAYOR,
	A.ES_DEBE,
	A.ES_HABER,
	A.SALDO_INICIAL,
	0 CARGO_PERIODO,
	0 ABONO_PERIODO,
	0 SALDO_FINAL,
	0 CARGO_PERIODO_MES,
	0 ABONO_PERIODO_MES,
	A.EXISTE_PARTIDA_INI
	FROM FN_CON_SALDO_HISTORICO(
	@CORR_EMPRESA,
	@ANIO_PERIODO,
	@MES_PERIODO,
	@CORR_MONEDA,
	@CUENTA_CONTABLE_INICIAL,
	@CUENTA_CONTABLE_FINAL,
	@CORR_AUXILIAR,
	@CORR_CENTRO_COSTO,
	@CORR_CONFI_REPORTE,
	@NIVEL,
	@POR_CUENTA_CONTABLE,
	@POR_AUXILIAR,
	@POR_CENTRO_COSTO,
	@OPCION_CONSULTA
	) A
	
	--Obteniendo Cargos y Abonos del periodo selecionado
	-----------------------------------------------------------------------------------------
	SELECT @FECHA_INICIAL=CONVERT(DATE,CONVERT(VARCHAR,@ANIO_PERIODO)+'-'+CONVERT(VARCHAR,@MES_PERIODO)+'-1')
	
	UPDATE A SET
	A.CARGO_PERIODO=CASE WHEN A.CORR_MONEDA=C.CORR_MONEDA THEN ISNULL(B.CARGO_PERIODO,0) ELSE ISNULL(B.CARGO_PERIODO_FORANEA,0) END,
	A.ABONO_PERIODO=CASE WHEN A.CORR_MONEDA=C.CORR_MONEDA THEN ISNULL(B.ABONO_PERIODO,0) ELSE ISNULL(B.ABONO_PERIODO,0) END
	FROM @SALDO A
	INNER JOIN GEN_EMPRESA C ON A.CORR_EMPRESA=C.CORR_EMPRESA
	INNER JOIN (
		SELECT CORR_EMPRESA,CUENTA_CONTABLE,CORR_AUXILIAR,CORR_CENTRO_COSTO,CARGO_PERIODO,ABONO_PERIODO,CARGO_PERIODO_FORANEA,ABONO_PERIODO_FORANEA
		FROM FN_CON_SALDO_MOV(
		@CORR_EMPRESA,
		@FECHA_INICIAL,
		@FECHA_CONSULTA,
		@CORR_MONEDA,
		@CUENTA_CONTABLE_INICIAL,
		@CUENTA_CONTABLE_FINAL,
		@CORR_AUXILIAR,	
		@CORR_CENTRO_COSTO,
		@CORR_CONFI_REPORTE,
		@NIVEL,
		@PARTIDA_CIERRE,
		@PARTIDA_LIQUIDACION,
		@POR_CUENTA_CONTABLE,
		@POR_AUXILIAR,
		@POR_CENTRO_COSTO,
		@OPCION_CONSULTA
		)
	) B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE AND ISNULL(A.CORR_AUXILIAR,0)=ISNULL(B.CORR_AUXILIAR,0) AND ISNULL(A.CORR_CENTRO_COSTO,0)=ISNULL(B.CORR_CENTRO_COSTO,0)
		
	
	--Obteniendo Cargos y Abonos del mes
	-----------------------------------------------------------------------------------------
	SELECT @FECHA_INICIAL=CONVERT(DATE,CONVERT(VARCHAR,YEAR(@FECHA_CONSULTA))+'-'+CONVERT(VARCHAR,MONTH(@FECHA_CONSULTA))+'-1')
	
	UPDATE A SET
	A.CARGO_PERIODO=CASE WHEN A.CORR_MONEDA=C.CORR_MONEDA THEN ISNULL(B.CARGO_PERIODO,0) ELSE ISNULL(B.CARGO_PERIODO_FORANEA,0) END,
	A.ABONO_PERIODO=CASE WHEN A.CORR_MONEDA=C.CORR_MONEDA THEN ISNULL(B.ABONO_PERIODO,0) ELSE ISNULL(B.ABONO_PERIODO,0) END
	FROM @SALDO A
	INNER JOIN GEN_EMPRESA C ON A.CORR_EMPRESA=C.CORR_EMPRESA
	INNER JOIN (
		SELECT CORR_EMPRESA,CUENTA_CONTABLE,CORR_AUXILIAR,CORR_CENTRO_COSTO,CARGO_PERIODO,ABONO_PERIODO,CARGO_PERIODO_FORANEA,ABONO_PERIODO_FORANEA
		FROM FN_CON_SALDO_MOV(
		@CORR_EMPRESA,
		@FECHA_INICIAL,
		@FECHA_CONSULTA,
		@CORR_MONEDA,
		@CUENTA_CONTABLE_INICIAL,
		@CUENTA_CONTABLE_FINAL,
		@CORR_AUXILIAR,	
		@CORR_CENTRO_COSTO,
		@CORR_CONFI_REPORTE,
		@NIVEL,
		@PARTIDA_CIERRE,
		@PARTIDA_LIQUIDACION,
		@POR_CUENTA_CONTABLE,
		@POR_AUXILIAR,
		@POR_CENTRO_COSTO,
		@OPCION_CONSULTA
		)
	) B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE AND ISNULL(A.CORR_AUXILIAR,0)=ISNULL(B.CORR_AUXILIAR,0) AND ISNULL(A.CORR_CENTRO_COSTO,0)=ISNULL(B.CORR_CENTRO_COSTO,0)
			
	
	--Mayorizar movimientos
	-----------------------------------------------------------------------------------------
	IF @MAYORIZA=1
	BEGIN
		IF EXISTS(SELECT 1 FROM @SALDO WHERE EXISTE_PARTIDA_INI<>0)
		BEGIN
			SELECT @EXISTE_PARTIDA_INI=1
		END ELSE
		BEGIN
			SELECT @EXISTE_PARTIDA_INI=0
		END
	
		INSERT INTO @CARGO_ABONO
		(CUENTA_CONTABLE,SALDO_INICIAL,CARGO_PERIODO,ABONO_PERIODO,CARGO_PERIODO_MES,ABONO_PERIODO_MES) 
		SELECT ISNULL(CUENTA_MAYOR,''),SUM(SALDO_INICIAL), SUM(CARGO_PERIODO), SUM(ABONO_PERIODO), SUM(ISNULL(CARGO_PERIODO_MES,0)), SUM(ISNULL(ABONO_PERIODO_MES,0))
		FROM @SALDO
		GROUP BY CUENTA_MAYOR HAVING (SUM(CARGO_PERIODO)>0 OR SUM(ABONO_PERIODO)>0 OR SUM(SALDO_INICIAL)<>0)
		
		WHILE EXISTS(SELECT 1 FROM @CARGO_ABONO)
		BEGIN
			SELECT TOP 1 @CUENTA_CONTABLE=CUENTA_CONTABLE,@SALDO_INICIAL=SALDO_INICIAL
			,@CARGO_PERIODO=CARGO_PERIODO, @ABONO_PERIODO=ABONO_PERIODO
			, @CARGO_PERIODO_MES=CARGO_PERIODO_MES, @ABONO_PERIODO_MES=ABONO_PERIODO_MES
			FROM @CARGO_ABONO
			ORDER BY CUENTA_CONTABLE
			
			SELECT @CUENTA_MAYOR=@CUENTA_CONTABLE
			WHILE (@CUENTA_MAYOR<>'')
			BEGIN
				UPDATE @SALDO SET
				SALDO_INICIAL=ISNULL(SALDO_INICIAL,0)+CASE WHEN ISNULL(@EXISTE_PARTIDA_INI,0)<>0 THEN ISNULL(@SALDO_INICIAL,0) ELSE 0 END, --Mayorizando la partida inicial				
				--SALDO_INICIAL=ISNULL(SALDO_INICIAL,0)+CASE WHEN @MES_PERIODO=1 THEN ISNULL(@SALDO_INICIAL,0) ELSE 0 END, --Mayorizando la partida inicial				
				CARGO_PERIODO=ISNULL(CARGO_PERIODO,0)+ISNULL(@CARGO_PERIODO,0),
				ABONO_PERIODO=ISNULL(ABONO_PERIODO,0)+ISNULL(@ABONO_PERIODO,0),
				CARGO_PERIODO_MES=ISNULL(CARGO_PERIODO_MES,0)+ISNULL(@CARGO_PERIODO_MES,0),
				ABONO_PERIODO_MES=ISNULL(ABONO_PERIODO_MES,0)+ISNULL(@ABONO_PERIODO_MES,0)
				WHERE CUENTA_CONTABLE=@CUENTA_MAYOR

				SELECT @CUENTA_MAYOR=CUENTA_MAYOR 
				FROM @SALDO
				WHERE CUENTA_CONTABLE=@CUENTA_MAYOR
				
				SELECT @CUENTA_MAYOR=ISNULL(@CUENTA_MAYOR,'')		    
			END			
			
			DELETE FROM @CARGO_ABONO
			WHERE CUENTA_CONTABLE=@CUENTA_CONTABLE
		END
	END
		
	--Aplicar Debe y Haber
	-----------------------------------------------------------------------------------------
	IF @APLICA_DEBE_HABE=1
	BEGIN			
		UPDATE @SALDO SET
		SALDO_FINAL=(ISNULL(SALDO_INICIAL,0)+ISNULL(CARGO_PERIODO,0)-ISNULL(ABONO_PERIODO ,0))*(CASE WHEN ES_DEBE=1 THEN 1 ELSE CASE WHEN ES_HABER =1 THEN -1 ELSE 0 END END)

		UPDATE @SALDO SET 
		SALDO_INICIAL=ISNULL(SALDO_INICIAL,0)*(CASE WHEN ES_DEBE=1 THEN 1 ELSE CASE WHEN ES_HABER=1 THEN -1 ELSE 0 END END)
	END ELSE
	BEGIN
		UPDATE @SALDO SET
		SALDO_FINAL=ISNULL(SALDO_INICIAL,0)+(ISNULL(CARGO_PERIODO,0)-ISNULL(ABONO_PERIODO ,0))
	END
	
	
	RETURN
END
GO
