SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[FN_CON_PERIODO_INICIAL]
(
	@CORR_EMPRESA INT,	
	@FECHA_CONSULTA Date
)
RETURNS 
@PERIODO TABLE 
(				
		CORR_EMPRESA INT,
		ANIO_PERIODO INT,
		MES_PERIODO INT
)
AS	
BEGIN
	DECLARE @ANIO_PERIODO INT, @MES_PERIODO INT, @ANIO_PERIODO_ANTE INT, @MES_PERIODO_ANTE INT
			
	--Obtener el periodo
	SELECT @ANIO_PERIODO=YEAR(@FECHA_CONSULTA), @MES_PERIODO=MONTH(@FECHA_CONSULTA)
	
	IF @MES_PERIODO=1
	BEGIN
		SELECT @ANIO_PERIODO_ANTE=@ANIO_PERIODO-1,@MES_PERIODO_ANTE=12
	END ELSE
	BEGIN
		SELECT @ANIO_PERIODO_ANTE=@ANIO_PERIODO,@MES_PERIODO_ANTE=@MES_PERIODO-1
	END
	
	IF NOT EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
			  WHERE CORR_EMPRESA=@CORR_EMPRESA
			  AND ANIO_PERIODO=@ANIO_PERIODO_ANTE
			  AND MES_PERIODO=@MES_PERIODO_ANTE
			  AND ESTADO_PERIODO_CON='CE')
	BEGIN
		IF EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
			  WHERE CORR_EMPRESA=@CORR_EMPRESA			  
			  AND ESTADO_PERIODO_CON='CE'
			  AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO)
		BEGIN
			SELECT TOP 1 @ANIO_PERIODO=ANIO_PERIODO
			,@MES_PERIODO=MES_PERIODO
			FROM CON_PERIODO_CONTABLE
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ESTADO_PERIODO_CON='CE'
			AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO
			ORDER BY ANIO_PERIODO DESC, MES_PERIODO DESC
			
			IF @MES_PERIODO=12
			BEGIN
				SELECT @ANIO_PERIODO=@ANIO_PERIODO+1,@MES_PERIODO=1
			END ELSE
			BEGIN
				SELECT @ANIO_PERIODO=@ANIO_PERIODO,@MES_PERIODO=@MES_PERIODO+1
			END
		END ELSE
		BEGIN
			IF EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
			  WHERE CORR_EMPRESA=@CORR_EMPRESA  
			  AND ESTADO_PERIODO_CON='AB'
			  AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO)
		    BEGIN		    		    
				SELECT TOP 1 @ANIO_PERIODO=ANIO_PERIODO,@MES_PERIODO=MES_PERIODO			
				FROM CON_PERIODO_CONTABLE
				WHERE CORR_EMPRESA=@CORR_EMPRESA  
				AND ESTADO_PERIODO_CON='AB'
				AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO
				ORDER BY ANIO_PERIODO ASC, MES_PERIODO ASC
			END ELSE
			BEGIN
			    SELECT TOP 1 @ANIO_PERIODO=ANIO_PERIODO,@MES_PERIODO=MES_PERIODO
				FROM CON_PARTIDA
				WHERE CORR_EMPRESA=@CORR_EMPRESA
				AND ESTADO_PARTIDA='AP'
				AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO
				ORDER BY ANIO_PERIODO ASC, MES_PERIODO ASC
			END
		END
	END
	
	INSERT INTO @PERIODO
	(CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO)
	VALUES(@CORR_EMPRESA,@ANIO_PERIODO,@MES_PERIODO)
	
	RETURN
END
GO
