using System;

namespace scuees.Models
{
	public class COM_JSONView
	{
		public int CORR_EMPRESA { get; set; }
		public int CORR_DOCUMENTO { get; set; }
		public string NUMERO_DOCUMENTO { get; set; }
		public string VERSION { get; set; }
		public int CORR_TIPO_AMBIENTE { get; set; }
		public string CODIGO_AMBIENTE_DESTINO { get; set; }
		public string NOMBRE_AMBIENTE_DESTINO { get; set; }
		public int CORR_TIPO_DOC { get; set; }
		public string CODIGO_TIPO_DOC { get; set; }
		public string NOMBRE_TIPO_DOC { get; set; }
		public string NUMERO_CONTROL { get; set; }
		public string CODIGO_GENERACION { get; set; }
		public string SELLO_RECEPCION { get; set; }
		public int NUMERO_SECUENCIA { get; set; }
		public int CORR_MODELO_FACTURACION { get; set; }
		public string CODIGO_MODELO_FACTURACION { get; set; }
		public string NOMBRE_MODELO_FACTURACION { get; set; }
		public string CLASE_MODELO_FACTURACION { get; set; }
		public string NOMBRE_CLASE_MODELO_FACTURACION { get; set; }
		public int CORR_TIPO_TRANSMISION { get; set; }
		public string CODIGO_TIPO_TRANSMISION { get; set; }
		public string NOMBRE_TIPO_TRANSMISION { get; set; }
		public string CLASE_TIPO_TRANSMICION { get; set; }
		public string NOMBRE_CLASE_TIPO_TRANSMICION { get; set; }
		public DateTime FECHA_GENERACION { get; set; }
		public DateTime HORA_GENERACION { get; set; }
		public int CORR_MONEDA { get; set; }
		public string NOMBRE_MONEDA { get; set; }
		public int CORR_TIPO_DIP_REC { get; set; }
		public string NUMERO_DOC_REC { get; set; }
		public string NUMERO_NCR_REC { get; set; }
		public string NOMBRE_REC { get; set; }
		public int CORR_ACTIVIDAD_ECONOMICA_REC { get; set; }
		public string CODIGO_ACTIVIDAD_ECONOMICA_REC { get; set; }
		public string NOMBRE_ACTIVIDAD_ECONOMICA_REC { get; set; }
		public string NOMBRE_COMERCIAL_REC { get; set; }
		public string DIRECCION_REC { get; set; }
		public int CORR_DEPTO_REC { get; set; }
		public string NOMBRE_DEPTO_REC { get; set; }
		public int CORR_MUNICIPIO_REC { get; set; }
		public string NOMBRE_MUNICIPIO_REC { get; set; }
		public string TELEFONO_REC { get; set; }
		public string CORREO_ELECTRONICO_REC { get; set; }
		public string NUMERO_NIT_EMI { get; set; }
		public string NUMERO_NRC_EMI { get; set; }
		public string NOMBRE_EMISOR { get; set; }
		public int CORR_ACTIVIDAD_ECONOMICA_EMI { get; set; }
		public string CODIGO_ACTIVIDAD_ECONOMICA_EMI { get; set; }
		public string NOMBRE_ACTIVIDAD_ECONOMICA_EMI { get; set; }
		public string NOMBRE_COMERCIAL_EMI { get; set; }
		public int CORR_TIPO_ESTABLECIMIENTO_EMI { get; set; }
		public string CODIGO_TIPO_ESTABLECIMIENTO { get; set; }
		public string NOMBRE_TIPO_ESTABLECIMIENTO { get; set; }
		public string DIRECCION_EMI { get; set; }
		public int CORR_DEPTO_EMI { get; set; }
		public string NOMBRE_DEPTO_EMI { get; set; }
		public int CORR_MUNICIPIO_EMI { get; set; }
		public string NOMBRE_MUNICIPIO_EMI { get; set; }
		public string TELEFONO_EMI { get; set; }
		public string CORREO_ELECTRONICO_EMI { get; set; }
		public string CODIGO_ESTABLECIMIENTO_MH { get; set; }
		public string CODIGO_ESTABLECIMIENTO { get; set; }
		public string CODIGO_PUNTO_VENTA_MH { get; set; }
		public string CODIGO_PUNTO_VENTA { get; set; }
		public string NIT_VENTA_TERCERO { get; set; }
		public string NOMBRE_VENTA_TERCERO { get; set; }
		public string ESTADO_DOCUMENTO { get; set; }
		public string NOMBRE_ESTADO_DOCUMENTO { get; set; }
		public decimal MONTO_TOTAL_NO_SUJETO { get; set; }
		public decimal MONTO_TOTAL_EXENTO { get; set; }
		public decimal MONTO_TOTAL_GRAVADO { get; set; }
		public decimal MONTO_SUB_TOTAL_VENTA { get; set; }
		public decimal MONTO_DESCUENTO_NO_SUJETO { get; set; }
		public decimal MONTO_DESCUENTO_EXENTO { get; set; }
		public decimal MONTO_DESCUENTO_GRAVADO { get; set; }
		public decimal PORCENTAJE_DESCUENTO { get; set; }
		public decimal MONTO_TOTAL_DESCUENTO { get; set; }
		public decimal MONTO_SUB_TOTAL { get; set; }
		public decimal MONTO_IVA_PERCIBIDO { get; set; }
		public decimal MONTO_IVA_RETENIDO { get; set; }
		public decimal MONTO_TOTAL_IVA { get; set; }
		public decimal MONTO_RENTA { get; set; }
		public decimal MONTO_TOTAL_OPERACION { get; set; }
		public decimal MONTO_TOTAL_NO_GRAVADO { get; set; }
		public decimal MONTO_TOTAL_PAGAR { get; set; }
		public string CANTIDAD_LETRA { get; set; }
		public decimal MONTO_SALDO_FAVOR { get; set; }
		public int CORR_CONDICION_OPERACION { get; set; }
		public string NUMERO_PAGO_ELECTRONICO { get; set; }
		public string NOMBRE_ENTREGA { get; set; }
		public string NUMERO_DIP_ENTREGA { get; set; }
		public string NOMBRE_RECIBE { get; set; }
		public string NUMERO_DIP_RECIBE { get; set; }
		public string OBSERVACION { get; set; }
		public string NUMERO_PLACA { get; set; }
		public int CORR_PERSONERIA_REC { get; set; }
		public string USUARIO_CREA { get; set; }
		public DateTime FECHA_CREA { get; set; }
		public string ESTACION_CREA { get; set; }
		public string USUARIO_ACTU { get; set; }
		public DateTime FECHA_ACTU { get; set; }
		public string ESTACION_ACTU { get; set; }
		public string CODIGO_CLIENTE { get; set; }
		public string USUARIO_CAJERO { get; set; }
		public int CORR_TIPO_GENERACION { get; set; }
	}
}
