import { ScBandejaItem } from './models/sc-bandeja-th-item';

/**
 * Data mock — bandeja TH (3 ciclos).
 *
 * a) Requisiciones: borrador → enviada → aprobada/rechazada (+ etapas posteriores).
 * b) Candidatos: Postulante (persona sin expediente) → expediente → selección → dictamen.
 * c) Contrataciones: desde Aplica → movimiento personal (standby).
 *
 * Standby API:
 * - Aprobación de requisición (unidad envía → jefe inmediato)
 * - Movimiento personal / contrato
 * - PLAZAS_CUBIERTAS automático
 * - Cierre / parcial cubierta
 */
export const SC_BANDEJA_TH_MOCK: ScBandejaItem[] = [
	// —— Requisiciones ——
	{
		ID: 'REQ-34',
		TIPO: 'REQUISICION',
		CODIGO: 'REQ-34',
		DESCRIPCION: 'Analista Financiero',
		SUBTITULO: 'Gerencia Financiera',
		SOLICITANTE: 'María López',
		CARGO_SOLICITANTE: 'Gerente Financiero',
		FECHA: '2025-09-08T09:42:00',
		ESTADO: 'En Aprobación',
		ESTADO_TONE: 'aprobacion',
		CORR_REQUISICION_PERSONAL: 34,
		NOMBRE_UNIDAD: 'Gerencia Financiera',
		NOMBRE_PUESTO: 'Analista Financiero',
		NOMBRE_TIPO_VACANTE: 'Nueva plaza',
		NOMBRE_TIPO_MODALIDAD: 'Presencial',
		NOMBRE_TIPO_CONTRATACION: 'Tiempo completo',
		CANTIDAD_PLAZAS: 1,
		PLAZAS_CUBIERTAS: 0,
		SALARIO: 1350,
		HORARIO: 'Lunes a viernes 8:00–17:00',
		JUSTIFICACION:
			'Se requiere refuerzo en análisis presupuestario y control de gastos para el cierre del ejercicio fiscal.',
		CANTIDAD_CANDIDATOS: 0,
		CANTIDAD_PENDIENTES: 0,
		REQUIERE_ATENCION: true,
		HISTORIAL: [
			{ FECHA: '2025-09-08T09:42:00', USUARIO: 'mlopez', ACCION: 'Creada por unidad' },
			{ FECHA: '2025-09-08T10:15:00', USUARIO: 'mlopez', ACCION: 'Enviada a aprobación', COMENTARIO: 'Pendiente jefe inmediato.' },
		],
	},
	{
		ID: 'REQ-33',
		TIPO: 'REQUISICION',
		CODIGO: 'REQ-33',
		DESCRIPCION: 'Coordinador de Calidad',
		SUBTITULO: 'Aseguramiento de la Calidad',
		SOLICITANTE: 'Roberto Díaz',
		CARGO_SOLICITANTE: 'Jefe de Calidad',
		FECHA: '2025-09-07T08:20:00',
		ESTADO: 'Borrador',
		ESTADO_TONE: 'borrador',
		CORR_REQUISICION_PERSONAL: 33,
		NOMBRE_UNIDAD: 'Aseguramiento de la Calidad',
		NOMBRE_PUESTO: 'Coordinador de Calidad',
		NOMBRE_TIPO_VACANTE: 'Nueva plaza',
		NOMBRE_TIPO_MODALIDAD: 'Híbrido',
		NOMBRE_TIPO_CONTRATACION: 'Tiempo completo',
		CANTIDAD_PLAZAS: 1,
		PLAZAS_CUBIERTAS: 0,
		SALARIO: 1400,
		HORARIO: 'Lunes a viernes 8:00–17:00',
		JUSTIFICACION: 'Fortalecer el sistema de gestión de calidad institucional.',
		CANTIDAD_CANDIDATOS: 0,
		HISTORIAL: [
			{ FECHA: '2025-09-07T08:20:00', USUARIO: 'rdiaz', ACCION: 'Creada por unidad', COMENTARIO: 'Aún no enviada.' },
		],
	},
	{
		ID: 'REQ-31',
		TIPO: 'REQUISICION',
		CODIGO: 'REQ-31',
		DESCRIPCION: 'Asistente Administrativo',
		SUBTITULO: 'Dirección Académica',
		SOLICITANTE: 'Carlos Méndez',
		CARGO_SOLICITANTE: 'Director Académico',
		FECHA: '2025-09-05T11:20:00',
		ESTADO: 'Aprobada',
		ESTADO_TONE: 'aprobada',
		CORR_REQUISICION_PERSONAL: 31,
		NOMBRE_UNIDAD: 'Dirección Académica',
		NOMBRE_PUESTO: 'Asistente Administrativo',
		NOMBRE_TIPO_VACANTE: 'Sustitución',
		NOMBRE_TIPO_MODALIDAD: 'Híbrido',
		NOMBRE_TIPO_CONTRATACION: 'Tiempo completo',
		CANTIDAD_PLAZAS: 1,
		PLAZAS_CUBIERTAS: 0,
		SALARIO: 950,
		HORARIO: 'Lunes a viernes 7:30–16:30',
		JUSTIFICACION: 'Cobertura por renuncia del titular.',
		CANTIDAD_CANDIDATOS: 3,
		CANTIDAD_PENDIENTES: 1,
		HISTORIAL: [
			{ FECHA: '2025-09-05T11:20:00', USUARIO: 'cmendez', ACCION: 'Creada por unidad' },
			{ FECHA: '2025-09-05T14:00:00', USUARIO: 'cmendez', ACCION: 'Enviada a aprobación' },
			{ FECHA: '2025-09-06T09:10:00', USUARIO: 'jrojas', ACCION: 'Aprobada', COMENTARIO: 'Jefe inmediato autoriza.' },
		],
	},
	{
		ID: 'REQ-28',
		TIPO: 'REQUISICION',
		CODIGO: 'REQ-28',
		DESCRIPCION: 'Desarrollador Full Stack',
		SUBTITULO: 'Dirección de TI',
		SOLICITANTE: 'Ana Rivera',
		CARGO_SOLICITANTE: 'Jefa de Sistemas',
		FECHA: '2025-08-28T08:05:00',
		ESTADO: 'En Selección',
		ESTADO_TONE: 'proceso',
		CORR_REQUISICION_PERSONAL: 28,
		NOMBRE_UNIDAD: 'Dirección de TI',
		NOMBRE_PUESTO: 'Desarrollador Full Stack',
		NOMBRE_TIPO_VACANTE: 'Nueva plaza',
		NOMBRE_TIPO_MODALIDAD: 'Remoto',
		NOMBRE_TIPO_CONTRATACION: 'Contrato temporal',
		CANTIDAD_PLAZAS: 2,
		PLAZAS_CUBIERTAS: 0,
		SALARIO: 1800,
		TIEMPO_CONTRATO: 12,
		HORARIO: 'Lunes a viernes 9:00–18:00',
		JUSTIFICACION: 'Refuerzo para modernización SGUEES.',
		CANTIDAD_CANDIDATOS: 4,
		CANTIDAD_PENDIENTES: 1,
		HISTORIAL: [
			{ FECHA: '2025-08-28T08:05:00', USUARIO: 'arivera', ACCION: 'Creada por unidad' },
			{ FECHA: '2025-08-29T16:40:00', USUARIO: 'pgomez', ACCION: 'Aprobada' },
			{ FECHA: '2025-09-01T10:00:00', USUARIO: 'th.admin', ACCION: 'En reclutamiento' },
			{ FECHA: '2025-09-04T12:30:00', USUARIO: 'th.admin', ACCION: 'En selección' },
		],
	},
	{
		ID: 'REQ-22',
		TIPO: 'REQUISICION',
		CODIGO: 'REQ-22',
		DESCRIPCION: 'Auxiliar de Contabilidad',
		SUBTITULO: 'Contabilidad',
		SOLICITANTE: 'Pedro Campos',
		CARGO_SOLICITANTE: 'Jefe de Contabilidad',
		FECHA: '2025-08-12T15:40:00',
		ESTADO: 'Rechazada',
		ESTADO_TONE: 'rechazada',
		CORR_REQUISICION_PERSONAL: 22,
		NOMBRE_UNIDAD: 'Contabilidad',
		NOMBRE_PUESTO: 'Auxiliar de Contabilidad',
		NOMBRE_TIPO_VACANTE: 'Nueva plaza',
		NOMBRE_TIPO_MODALIDAD: 'Presencial',
		NOMBRE_TIPO_CONTRATACION: 'Tiempo completo',
		CANTIDAD_PLAZAS: 1,
		PLAZAS_CUBIERTAS: 0,
		SALARIO: 800,
		JUSTIFICACION: 'Apoyo en conciliaciones.',
		CANTIDAD_CANDIDATOS: 0,
		HISTORIAL: [
			{ FECHA: '2025-08-12T15:40:00', USUARIO: 'pcampos', ACCION: 'Creada por unidad' },
			{ FECHA: '2025-08-13T09:00:00', USUARIO: 'pcampos', ACCION: 'Enviada a aprobación' },
			{ FECHA: '2025-08-14T11:25:00', USUARIO: 'lvalle', ACCION: 'Rechazada', COMENTARIO: 'Sin presupuesto.' },
		],
	},

	// —— Candidatos (ciclo Postulante → … → dictamen) ——
	{
		ID: 'SOL-102',
		TIPO: 'CANDIDATO',
		CODIGO: 'SOL-102',
		DESCRIPCION: 'Andrea Pineda',
		SUBTITULO: 'Postulante · solicitud con datos de persona · sin expediente',
		SOLICITANTE: 'TH · Gestión',
		CARGO_SOLICITANTE: 'Talento Humano',
		FECHA: '2025-09-08T11:00:00',
		ESTADO: 'Postulante',
		ESTADO_TONE: 'borrador',
		ESTADO_CICLO_CANDIDATO: 'POSTULANTE',
		CORR_SOLICITUD_EMPLEO: 102,
		CORR_PERSONA_DATOS: 501,
		CORR_EXPEDIENTE_CANDIDATO: undefined,
		NOMBRE_CANDIDATO: 'Andrea Pineda',
		DUI_CANDIDATO: '06789012-3',
		NOMBRE_UNIDAD: 'Dirección Académica',
		NOMBRE_PUESTO: 'Asistente Administrativo',
		CORR_REQUISICION_PERSONAL: 31,
		REQUIERE_ATENCION: true,
		HISTORIAL: [
			{
				FECHA: '2025-09-08T11:00:00',
				USUARIO: 'sistema',
				ACCION: 'Formulario completado',
				COMENTARIO: 'CORR_PERSONA_DATOS asignado. Pendiente asociar expediente.',
			},
		],
	},
	{
		ID: 'CAN-190',
		TIPO: 'CANDIDATO',
		CODIGO: 'CAN-190',
		DESCRIPCION: 'Miguel Torres',
		SUBTITULO: 'Expediente asociado · pendiente activar selección · REQ-31',
		SOLICITANTE: 'TH · Gestión',
		CARGO_SOLICITANTE: 'Talento Humano',
		FECHA: '2025-09-07T15:40:00',
		ESTADO: 'Con expediente',
		ESTADO_TONE: 'aprobacion',
		ESTADO_CICLO_CANDIDATO: 'CON_EXPEDIENTE',
		CORR_SOLICITUD_EMPLEO: 95,
		CORR_PERSONA_DATOS: 488,
		CORR_EXPEDIENTE_CANDIDATO: 190,
		CORR_REQUISICION_PERSONAL: 31,
		NOMBRE_CANDIDATO: 'Miguel Torres',
		DUI_CANDIDATO: '03456789-0',
		NOMBRE_UNIDAD: 'Dirección Académica',
		NOMBRE_PUESTO: 'Asistente Administrativo',
		NOMBRE_TIPO_MODALIDAD: 'Híbrido',
		NOMBRE_TIPO_CONTRATACION: 'Tiempo completo',
		SALARIO: 950,
		REQUIERE_ATENCION: true,
		HISTORIAL: [
			{ FECHA: '2025-09-07T14:00:00', USUARIO: 'sistema', ACCION: 'Postulante (persona registrada)' },
			{ FECHA: '2025-09-07T15:40:00', USUARIO: 'th.admin', ACCION: 'Expediente asociado', COMENTARIO: 'Pendiente activar proceso de selección.' },
		],
	},
	{
		ID: 'CAN-178',
		TIPO: 'CANDIDATO',
		CODIGO: 'CAN-178',
		DESCRIPCION: 'Sofía Hernández',
		SUBTITULO: 'En selección · dictamen pendiente · REQ-28',
		SOLICITANTE: 'Ana Rivera',
		CARGO_SOLICITANTE: 'Jefa de Sistemas',
		FECHA: '2025-09-03T13:10:00',
		ESTADO: 'En proceso de selección',
		ESTADO_TONE: 'proceso',
		ESTADO_CICLO_CANDIDATO: 'EN_SELECCION',
		CORR_EXPEDIENTE_CANDIDATO: 178,
		CORR_SOLICITUD_EMPLEO: 90,
		CORR_PERSONA_DATOS: 410,
		CORR_REQUISICION_PERSONAL: 28,
		NOMBRE_CANDIDATO: 'Sofía Hernández',
		DUI_CANDIDATO: '04567890-1',
		NOMBRE_UNIDAD: 'Dirección de TI',
		NOMBRE_PUESTO: 'Desarrollador Full Stack',
		NOMBRE_TIPO_MODALIDAD: 'Remoto',
		NOMBRE_TIPO_CONTRATACION: 'Contrato temporal',
		SALARIO: 1800,
		ESTADO_DECISION: 'PENDIENTE',
		CANTIDAD_ENTREVISTAS: 2,
		ULTIMA_ENTREVISTA: '2025-09-07 — Técnica (Favorable)',
		REQUIERE_ATENCION: true,
		HISTORIAL: [
			{ FECHA: '2025-09-02T10:00:00', USUARIO: 'sistema', ACCION: 'Postulante' },
			{ FECHA: '2025-09-03T12:00:00', USUARIO: 'th.admin', ACCION: 'Expediente asociado' },
			{ FECHA: '2025-09-03T13:10:00', USUARIO: 'th.admin', ACCION: 'Proceso de selección activado' },
			{ FECHA: '2025-09-07T11:00:00', USUARIO: 'arivera', ACCION: 'Entrevista realizada', COMENTARIO: 'Favorable. Pendiente dictamen jefatura.' },
		],
	},
	{
		ID: 'CAN-165',
		TIPO: 'CANDIDATO',
		CODIGO: 'CAN-165',
		DESCRIPCION: 'Luis Martínez',
		SUBTITULO: 'En selección · dictamen pendiente · REQ-31',
		SOLICITANTE: 'Carlos Méndez',
		CARGO_SOLICITANTE: 'Director Académico',
		FECHA: '2025-09-06T09:30:00',
		ESTADO: 'En proceso de selección',
		ESTADO_TONE: 'proceso',
		ESTADO_CICLO_CANDIDATO: 'EN_SELECCION',
		CORR_EXPEDIENTE_CANDIDATO: 165,
		CORR_SOLICITUD_EMPLEO: 81,
		CORR_PERSONA_DATOS: 401,
		CORR_REQUISICION_PERSONAL: 31,
		NOMBRE_CANDIDATO: 'Luis Martínez',
		DUI_CANDIDATO: '01234567-8',
		NOMBRE_UNIDAD: 'Dirección Académica',
		NOMBRE_PUESTO: 'Asistente Administrativo',
		NOMBRE_TIPO_MODALIDAD: 'Híbrido',
		NOMBRE_TIPO_CONTRATACION: 'Tiempo completo',
		SALARIO: 950,
		ESTADO_DECISION: 'PENDIENTE',
		CANTIDAD_ENTREVISTAS: 1,
		ULTIMA_ENTREVISTA: '2025-09-08 — Jefatura (Programada)',
		REQUIERE_ATENCION: true,
		HISTORIAL: [
			{ FECHA: '2025-09-06T09:30:00', USUARIO: 'th.admin', ACCION: 'Proceso de selección activado' },
		],
	},
	{
		ID: 'CAN-152',
		TIPO: 'CANDIDATO',
		CODIGO: 'CAN-152',
		DESCRIPCION: 'Elena Ruiz',
		SUBTITULO: 'Dictamen Aplica · listo para contratación · REQ-28',
		SOLICITANTE: 'Ana Rivera',
		CARGO_SOLICITANTE: 'Jefa de Sistemas',
		FECHA: '2025-09-01T16:00:00',
		ESTADO: 'Aplica',
		ESTADO_TONE: 'aprobada',
		ESTADO_CICLO_CANDIDATO: 'APLICA',
		CORR_EXPEDIENTE_CANDIDATO: 152,
		CORR_SOLICITUD_EMPLEO: 75,
		CORR_PERSONA_DATOS: 390,
		CORR_REQUISICION_PERSONAL: 28,
		NOMBRE_CANDIDATO: 'Elena Ruiz',
		DUI_CANDIDATO: '05678901-2',
		NOMBRE_UNIDAD: 'Dirección de TI',
		NOMBRE_PUESTO: 'Desarrollador Full Stack',
		NOMBRE_TIPO_MODALIDAD: 'Remoto',
		NOMBRE_TIPO_CONTRATACION: 'Contrato temporal',
		SALARIO: 1800,
		ESTADO_DECISION: 'APLICA',
		OBSERVACION_DECISION: 'Perfil alineado al stack y experiencia institucional.',
		CANTIDAD_ENTREVISTAS: 3,
		ULTIMA_ENTREVISTA: '2025-09-04 — Jefatura (Favorable)',
		LISTO_CONTRATACION: true,
		HISTORIAL: [
			{ FECHA: '2025-09-01T16:00:00', USUARIO: 'th.admin', ACCION: 'Proceso de selección' },
			{ FECHA: '2025-09-04T15:20:00', USUARIO: 'arivera', ACCION: 'Dictamen APLICA', COMENTARIO: 'Pasa a ciclo Contrataciones.' },
		],
	},
	{
		ID: 'CAN-140',
		TIPO: 'CANDIDATO',
		CODIGO: 'CAN-140',
		DESCRIPCION: 'Jorge Castillo',
		SUBTITULO: 'Dictamen No aplica · REQ-31',
		SOLICITANTE: 'Carlos Méndez',
		CARGO_SOLICITANTE: 'Director Académico',
		FECHA: '2025-08-30T10:45:00',
		ESTADO: 'No aplica',
		ESTADO_TONE: 'rechazada',
		ESTADO_CICLO_CANDIDATO: 'NO_APLICA',
		CORR_EXPEDIENTE_CANDIDATO: 140,
		CORR_SOLICITUD_EMPLEO: 70,
		CORR_PERSONA_DATOS: 355,
		CORR_REQUISICION_PERSONAL: 31,
		NOMBRE_CANDIDATO: 'Jorge Castillo',
		DUI_CANDIDATO: '02345678-9',
		NOMBRE_UNIDAD: 'Dirección Académica',
		NOMBRE_PUESTO: 'Asistente Administrativo',
		NOMBRE_TIPO_MODALIDAD: 'Híbrido',
		NOMBRE_TIPO_CONTRATACION: 'Tiempo completo',
		SALARIO: 950,
		ESTADO_DECISION: 'NO_APLICA',
		OBSERVACION_DECISION: 'Experiencia insuficiente para el perfil solicitado.',
		CANTIDAD_ENTREVISTAS: 2,
		ULTIMA_ENTREVISTA: '2025-09-02 — Jefatura (No favorable)',
		HISTORIAL: [
			{ FECHA: '2025-08-30T10:45:00', USUARIO: 'th.admin', ACCION: 'Proceso de selección' },
			{ FECHA: '2025-09-02T17:00:00', USUARIO: 'cmendez', ACCION: 'Dictamen NO_APLICA' },
		],
	},

	// —— Contrataciones (desde Aplica; movimiento en standby) ——
	{
		ID: 'CON-152',
		TIPO: 'CONTRATACION',
		CODIGO: 'CON-152',
		DESCRIPCION: 'Elena Ruiz',
		SUBTITULO: 'Listo para movimiento personal · REQ-28',
		SOLICITANTE: 'TH · Gestión',
		CARGO_SOLICITANTE: 'Talento Humano',
		FECHA: '2025-09-04T15:20:00',
		ESTADO: 'Listo para contratación',
		ESTADO_TONE: 'proceso',
		CORR_EXPEDIENTE_CANDIDATO: 152,
		CORR_REQUISICION_PERSONAL: 28,
		CORR_PERSONA_DATOS: 390,
		NOMBRE_CANDIDATO: 'Elena Ruiz',
		DUI_CANDIDATO: '05678901-2',
		NOMBRE_UNIDAD: 'Dirección de TI',
		NOMBRE_PUESTO: 'Desarrollador Full Stack',
		NOMBRE_TIPO_MODALIDAD: 'Remoto',
		NOMBRE_TIPO_CONTRATACION: 'Contrato temporal',
		SALARIO: 1800,
		TIEMPO_CONTRATO: 12,
		HORARIO: 'Lunes a viernes 9:00–18:00',
		ESTADO_DECISION: 'APLICA',
		LISTO_CONTRATACION: true,
		REQUIERE_ATENCION: true,
		HISTORIAL: [
			{ FECHA: '2025-09-04T15:20:00', USUARIO: 'arivera', ACCION: 'Dictamen APLICA' },
			{
				FECHA: '2025-09-04T15:21:00',
				USUARIO: 'sistema',
				ACCION: 'Pendiente movimiento personal',
				COMENTARIO: 'Standby: endpoints de contrato / movimiento personal aún no conectados.',
			},
		],
	},
];
