/** Modelo de SC_MOVIMIENTO_PERSONAL / V_SC_MOVIMIENTO_PERSONAL. */
export interface ScMovimientoPersonal {
	CORR_EMPRESA: number;
	CORR_MOVIMIENTO_PERSONAL: number;
	FECHA_ELABORACION: Date;
	/** DIRECTO | REQUISICION */
	ORIGEN_MOVIMIENTO: string;
	/** PERMANENTE | EVENTUAL | ASCENSO | TRASLADO */
	TIPO_MOVIMIENTO: string;
	/** DI SO OB AP DE AN */
	ESTADO_MOVIMIENTO: string;
	NOMBRE_ESTADO_MOVIMIENTO?: string;
	NOMBRE_TIPO_MOVIMIENTO?: string;
	NOMBRE_ORIGEN_MOVIMIENTO?: string;
	/** Referencia empleado (DIRECTO); sin FK. */
	CORR_EMPLEADO?: number | null;
	NOMBRE_COMPLETO: string;
	NUMERO_ID: string;
	FECHA_INGRESO_PROPUESTA?: Date | null;
	FECHA_FINALIZACION?: Date | null;
	GERENCIA_ACTUAL: string;
	CORR_UNIDAD_ACTUAL: number;
	NOMBRE_UNIDAD_ACTUAL?: string;
	CORR_PUESTO_ACTUAL: number;
	NOMBRE_PUESTO_ACTUAL?: string;
	SALARIO_ACTUAL: number;
	CORR_TIPO_MODALIDAD_ACTUAL: number;
	NOMBRE_MODALIDAD_ACTUAL?: string;
	HORARIO_ACTUAL: string;
	GERENCIA_PROPUESTA: string;
	CORR_UNIDAD_PROPUESTA: number;
	NOMBRE_UNIDAD_PROPUESTA?: string;
	CORR_PUESTO_PROPUESTO: number;
	NOMBRE_PUESTO_PROPUESTO?: string;
	SALARIO_PROPUESTO: number;
	CORR_TIPO_MODALIDAD_PROPUESTA: number;
	NOMBRE_MODALIDAD_PROPUESTA?: string;
	HORARIO_PROPUESTO: string;
	JUSTIFICACION: string;
	FECHA_EFECTIVA?: Date | null;
	/** Confirmación TH (0 = En Evaluación, 1 = Confirmado). */
	CONFIRMADO?: boolean | number;
	NOMBRE_CONFIRMACION?: string;
	/** LOGIN_SISTEMA de quien confirmó. */
	USUARIO_CONFIRMA?: string | null;
	FECHA_CONFIRMA?: Date | null;
	USUARIO_CREA: string;
	ESTACION_CREA: string;
	FECHA_CREA: Date;
	USUARIO_ACTU: string;
	ESTACION_ACTU: string;
	FECHA_ACTU: Date;
}

/** Catálogo OPERACION del SP PRAL_MTTO_SC_MOVIMIENTO_PERSONAL_AUTORIZA. */
export const OPERACION_FLUJO_MOVIMIENTO = {
	GUARDAR: 1,
	ENVIAR: 2,
	APROBAR: 3,
	DEVOLVER: 4,
	RECHAZAR: 5,
} as const;
