SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DESCRIPTOR_PUESTO_RIESGO_PUESTO]
AS
SELECT
  D.[CORR_EMPRESA],
  D.[CORR_DESCRIPTOR_RIESGO],
  D.[NOMBRE_RIESGO_PUESTO],
  D.[INFORMACION],
  D.[ES_LISTA],
  D.[CORR_DESCRIPTOR_PUESTO],
  D.[CORR_RIESGO_PUESTO],
  D.[USUARIO_CREA],
  D.[ESTACION_CREA],
  D.[FECHA_CREA],
  D.[USUARIO_ACTU],
  D.[ESTACION_ACTU],
  D.[FECHA_ACTU]
FROM [dbo].[SC_DESCRIPTOR_PUESTO_RIESGO_PUESTO] D
GO
