SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_DOC]
AS
SELECT DISTINCT A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.CORR_CUADRO_COMPARATIVO 
,B.CORR_DOCUMENTO
,C.NOMBRE_DOCUMENTO
,C.DESCRIPCION_DOCUMENTO
,C.CORR_TIPO_DOCUMENTO
,D.NOMBRE_TIPO_DOCUMENTO
,C.RUTA_DOCUMENTO
,C.NOMBRE_ARCHIVO
,'CU' CLASE_ORIGEN_DOCUMENTO
,'Cuadro Comparativo' NOMBRE_CLASE_ORIGEN_DOCUMENTO
,'' NOMBRE_PROVEEDOR
FROM COM_CUADRO_COMPARATIVO_DETA A
INNER JOIN COM_CUADRO_COMPARATIVO_DOC B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = B.CORR_CUADRO_COMPARATIVO
INNER JOIN COM_DOCUMENTO_FISICO C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.CORR_DOCUMENTO = C.CORR_DOCUMENTO
INNER JOIN COM_TIPO_DOC_FISICO D ON C.CORR_EMPRESA = D.CORR_EMPRESA AND C.CORR_TIPO_DOCUMENTO = D.CORR_TIPO_DOCUMENTO
UNION ALL
SELECT DISTINCT A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.CORR_CUADRO_COMPARATIVO
,C.CORR_DOCUMENTO
,C.NOMBRE_DOCUMENTO
,C.DESCRIPCION_DOCUMENTO
,C.CORR_TIPO_DOCUMENTO
,C.NOMBRE_TIPO_DOCUMENTO
,C.RUTA_DOCUMENTO
,C.NOMBRE_ARCHIVO
,'CO' CLASE_ORIGEN_DOCUMENTO
,'Cotización' NOMBRE_CLASE_ORIGEN_DOCUMENTO
,D.CLINAM NOMBRE_PROVEEDOR
FROM COM_CUADRO_COMPARATIVO_DETA A
INNER JOIN COM_COTIZACION B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO_COTIZACION = B.ANIO_PERIODO AND A.CORR_COTIZACION = B.CORR_COTIZACION
INNER JOIN V_COM_COTIZACION_DOC C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO = C.ANIO_PERIODO AND B.CORR_COTIZACION = C.CORR_COTIZACION
INNER JOIN [CLASS_UEES].dbo.CLIENTES D ON B.CORR_PROVEEDOR=D.CLIIDU
UNION ALL
SELECT DISTINCT A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.CORR_CUADRO_COMPARATIVO
,C.CORR_DOCUMENTO
,C.NOMBRE_DOCUMENTO
,C.DESCRIPCION_DOCUMENTO
,C.CORR_TIPO_DOCUMENTO
,C.NOMBRE_TIPO_DOCUMENTO
,C.RUTA_DOCUMENTO
,C.NOMBRE_ARCHIVO
,'SC' CLASE_ORIGEN_DOCUMENTO
,'Soli Cotización' NOMBRE_CLASE_ORIGEN_DOCUMENTO
,D.CLINAM NOMBRE_PROVEEDOR
FROM COM_CUADRO_COMPARATIVO_DETA A
INNER JOIN COM_COTIZACION B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO_COTIZACION = B.ANIO_PERIODO AND A.CORR_COTIZACION = B.CORR_COTIZACION
INNER JOIN V_COM_SOLI_COTIZACION_DOC C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO_SOLI_COTI = C.ANIO_PERIODO AND B.CORR_SOLI_COTIZACION = C.CORR_SOLI_COTIZACION
INNER JOIN [CLASS_UEES].dbo.CLIENTES D ON B.CORR_PROVEEDOR=D.CLIIDU
GO
