SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_TIPO_SOLI_COTIZA]
AS
SELECT A.CORR_EMPRESA
	,A.CORR_TIPO_SOLI_COTIZA
	,A.NOMBRE_TIPO_SOLI_COTIZA
	,A.CLASE_SOLI_COTIZA
	,CASE A.CLASE_SOLI_COTIZA
	WHEN 'NO' THEN 'NORMAL'
	WHEN 'EX' THEN 'EXPRESS'
	ELSE '' END NOMBRE_CLASE_SOLI_COTIZA
	,A.USUARIO_CREA
	,A.FECHA_CREA
	,A.ESTACION_CREA
	,A.USUARIO_ACTU
	,A.FECHA_ACTU
	,A.ESTACION_ACTU
FROM COM_TIPO_SOLI_COTIZA A

GO
