SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_PLA_TIPO_PUESTO]
AS
SELECT CORR_EMPRESA
      ,CORR_TIPO_PUESTO
      ,NOMBRE_TIPO_PUESTO
      ,ESTADO_TIPO_PUESTO
      ,USUARIO_CREA
      ,FECHA_CREA
      ,ESTACION_CREA
      ,USUARIO_ACTU
      ,FECHA_ACTU
      ,ESTACION_ACTU
  FROM PLA_TIPO_PUESTO

GO
