SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_SC_DESCRIPTOR_PUESTO_EMPLEADO]
AS
SELECT
  X.[CORR_EMPRESA],
  X.[CORR_DESCRIPTOR_PUESTO],
  X.[CORR_EMPLEADO],
  E.[NOMBRE_EMPLEADO],
  E.[DUI],
  E.[FECHA_INGRESO],
  E.[CORREO_INSTITUCIONAL],
  E.[TELEFONO_INSTITUCIONAL],
  E.[LOGIN_SISTEMA_WEB],
  E.[ACTIVO_EMPLEADO],
  ISNULL(X.[ACTIVO_DESCRIPTOR_PUESTO_EMPLEADO], 1) AS [ACTIVO_DESCRIPTOR_PUESTO_EMPLEADO],
  X.[USUARIO_CREA],
  X.[ESTACION_CREA],
  X.[FECHA_CREA],
  X.[USUARIO_ACTU],
  X.[ESTACION_ACTU],
  X.[FECHA_ACTU]
FROM [dbo].[SC_DESCRIPTOR_PUESTO_EMPLEADO] X
INNER JOIN [dbo].[V_GEN_EMPLEADO] E
  ON E.[CORR_EMPRESA] = X.[CORR_EMPRESA]
 AND E.[CORR_EMPLEADO] = X.[CORR_EMPLEADO]
GO
