-- Qué hace: vista de domicilios de persona (tab Direcciones de gen-empleado).
-- Cómo lo hace: une GEN_PERSONA_DOMICILIO con país/depto/municipio/distrito para nombres.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_DOMICILIO]
AS
SELECT
	D.CORR_EMPRESA,
	D.CORR_PERSONA,
	D.CORR_DOMICILIO,
	D.DIRECCION,
	D.CORR_PAIS,
	ISNULL(P.NOMBRE_PAIS, N'') AS NOMBRE_PAIS,
	D.CORR_DEPTO,
	ISNULL(DP.NOMBRE_DEPTO, N'') AS NOMBRE_DEPTO,
	D.CORR_MUNICIPIO,
	ISNULL(M.NOMBRE_MUNICIPIO, N'') AS NOMBRE_MUNICIPIO,
	D.CORR_DISTRITO,
	ISNULL(DI.NOMBRE_DISTRITO, N'') AS NOMBRE_DISTRITO,
	D.ACTIVO_DOMICILIO,
	D.USUARIO_CREA,
	D.ESTACION_CREA,
	D.FECHA_CREA,
	D.USUARIO_ACTU,
	D.ESTACION_ACTU,
	D.FECHA_ACTU
FROM dbo.GEN_PERSONA_DOMICILIO AS D
LEFT JOIN dbo.GEN_PAIS AS P
	ON P.CORR_PAIS = D.CORR_PAIS
LEFT JOIN dbo.GEN_DEPTO AS DP
	ON DP.CORR_PAIS = D.CORR_PAIS
	AND DP.CORR_DEPTO = D.CORR_DEPTO
LEFT JOIN dbo.GEN_MUNICIPIO AS M
	ON M.CORR_PAIS = D.CORR_PAIS
	AND M.CORR_DEPTO = D.CORR_DEPTO
	AND M.CORR_MUNICIPIO = D.CORR_MUNICIPIO
LEFT JOIN dbo.GEN_DISTRITO AS DI
	ON DI.CORR_PAIS = D.CORR_PAIS
	AND DI.CORR_DEPTO = D.CORR_DEPTO
	AND DI.CORR_MUNICIPIO = D.CORR_MUNICIPIO
	AND DI.CORR_DISTRITO = D.CORR_DISTRITO;
GO
