SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_COTIZACION_APLICA_CORREO]
AS
SELECT A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.CORR_COTIZACION
,A.FECHA_COTIZACION
,A.OBSERVACIONES
,BB.NOMBRE_PROVEEDOR
,ISNULL(B.CORREO_ELECTRONICO,ISNULL(BC.CORREO_ELECTRONICO,'')) CORREO_ELECTRONICO --B.CORREO_ELECTRONICO
--,D.CORREO_ELECTRONICO_COPIAR CORREO_ELECTRONICO_CCO
,'' CORREO_ELECTRONICO_CCO
,D.CORREO_REMITENTE
,D.USUARIO_REMITENTE
,D.CONTRASENA_REMITENTE
,D.SERVIDOR_CORREO
,D.PUERTO_CORREO
,D.USA_SSL_CORREO
,E.NOMBRE_EMPRESA
FROM COM_COTIZACION A
INNER JOIN COM_PROVEEDOR BB ON A.CORR_PROVEEDOR = BB.CORR_PROVEEDOR
INNER JOIN COM_SOLI_COTIZACION C ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.ANIO_PERIODO_SOLI_COTI = C.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION = C.CORR_SOLI_COTIZACION
LEFT OUTER JOIN V_SEG_USUARIO_CLASS B ON C.USUARIO_SOLI COLLATE DATABASE_DEFAULT = B.LOGIN_SISTEMA COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN SEG_USUARIO BC ON C.USUARIO_SOLI=BC.LOGIN_SISTEMA
INNER JOIN COM_PARAMETRO D ON A.CORR_EMPRESA=D.CORR_EMPRESA
INNER JOIN GEN_EMPRESA E ON A.CORR_EMPRESA=E.CORR_EMPRESA
GO
