SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_BITACORA]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_BITACORA
      ,A.FECHA_BITACORA
      ,A.CODIGO_OPCION
	  ,CASE A.CODIGO_OPCION
	  WHEN 'COM_SOLICITUD_COMPRA' THEN 'Solicitud de Compra'
	  WHEN 'COM_SOLI_COTIZACION' THEN 'Solicitud de Cotización'
	  WHEN 'COM_COTIZACION' THEN 'Cotización'
	  WHEN 'COM_CUADRO_COMPARATIVO' THEN 'Cuadro Comparativo'
	  WHEN 'COM_ORDEN_COMPRA' THEN 'Orden de Compra'
	  ELSE ''
	  END NOMBRE_CODIGO_OPCION
      ,A.CLASE_BITACORA
	  ,CASE A.CLASE_BITACORA
	   WHEN 'AP' THEN 'Aplicar'
	   WHEN 'DP' THEN 'Despacho Parcial'
	   WHEN 'DA' THEN 'Des-Aplicar'
	   WHEN 'AN' THEN 'Anular'
	   WHEN 'EL' THEN 'Eliminar'
	   WHEN 'SO' THEN 'Solicitar'
	   WHEN	'DE' THEN 'Denegar'
	   WHEN	'AU' THEN 'Autorizar'
	   WHEN 'EN' THEN 'Entregar'
	   WHEN 'RE' THEN 'Rechazar'
	   WHEN 'RV' THEN 'Revisar'
	   WHEN 'SR' THEN 'Solicita Revision'
	   ELSE ''
	   END NOMBRE_CLASE_BITACORA
      ,A.LLAVE_TRANSACCION
      ,A.REFERENCIA_TRANSACCION
      ,A.USUARIO_CREA_TRANS
      ,A.ESTACION_CREA_TRANS
      ,A.FECHA_CREA_TRANS
      ,A.USUARIO_ACTU_TRANS
      ,A.ESTACION_ACTU_TRANS
      ,A.FECHA_ACTU_TRANS
      ,A.USUARIO_CREA_BITACORA
      ,A.ESTACION_CREA_BITACORA
      ,A.FECHA_CREA_BITACORA
FROM COM_BITACORA A
GO
