CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_SOLICITUD
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_SOLICITUD,
    X.CORR_SOLICITUD_EMPLEO,
    S.FECHA_GENERACION AS FECHA_SOLICITUD,
    S.CORREO_INVITACION,
    S.DUI AS DUI_SOLICITUD,
    S.NOMBRE AS NOMBRE_SOLICITUD,
    S.CORR_TIPO_CONTRATACION,
    T.NOMBRE_TIPO_CONTRATACION,
    S.CORR_PERSONA_DATOS,
    S.ACTIVO AS ACTIVO_SOLICITUD,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_SOLICITUD AS X
INNER JOIN dbo.SC_SOLICITUD_EMPLEO AS S
    ON S.CORR_EMPRESA = X.CORR_EMPRESA
   AND S.CORR_SOLICITUD_EMPLEO = X.CORR_SOLICITUD_EMPLEO
LEFT JOIN dbo.SC_TIPO_CONTRATACION AS T
    ON T.CORR_EMPRESA = S.CORR_EMPRESA
   AND T.CORR_TIPO_CONTRATACION = S.CORR_TIPO_CONTRATACION;
GO
