SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_AREA_FUNCIONAL]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_AREA_FUNCIONAL
      ,A.NOMBRE_AREA_FUNCIONAL
      ,A.CODIGO_AREA_FUNCIONAL
  FROM CON_AREA_FUNCIONAL A

GO