-- Qué hace: vista de mantenimiento del catálogo GEN_TIPO_CONTACTO.
-- Cómo lo hace: proyecta la tabla con ISNULL en campos bit (1/0 por defecto).
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_TIPO_CONTACTO]
AS
SELECT
	T.CORR_TIPO_CONTACTO,
	T.NOMBRE_TIPO_CONTACTO,
	T.NOMBRE_CORTO,
	ISNULL(T.ACTIVO_TIPO_CONTACTO, 1) AS ACTIVO_TIPO_CONTACTO,
	T.NUMERO_CARACTERES,
	ISNULL(T.ACTIVO_CARACTERES, 0) AS ACTIVO_CARACTERES,
	T.USUARIO_CREA,
	T.ESTACION_CREA,
	T.FECHA_CREA,
	T.USUARIO_ACTU,
	T.ESTACION_ACTU,
	T.FECHA_ACTU
FROM dbo.GEN_TIPO_CONTACTO AS T;
GO
