SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DESCRIPTOR_RELACION_LABORAL]
AS
SELECT
  R.[CORR_EMPRESA],
  R.[CORR_DESCRIPTOR_PUESTO],
  R.[CORR_RELACION_LABORAL],
  RTRIM(R.[TIPO_RELACION]) AS [TIPO_RELACION],
  R.[PUESTO_AREA],
  R.[MOTIVO_RELACION],
  R.[USUARIO_CREA],
  R.[ESTACION_CREA],
  R.[FECHA_CREA],
  R.[USUARIO_ACTU],
  R.[ESTACION_ACTU],
  R.[FECHA_ACTU]
FROM [dbo].[SC_DESCRIPTOR_RELACION_LABORAL] R
GO
