-- Qué hace: vista de GEN_PERSONA para API anidada en gen-empleado.
-- Cómo lo hace: proyecta correlativo, código, activo y auditoría.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA]
AS
SELECT
	A.CORR_PERSONA,
	A.CODIGO_PERSONA,
	ISNULL(A.ACTIVO_PERSONA, 1) AS ACTIVO_PERSONA,
	A.USUARIO_CREA,
	A.ESTACION_CREA,
	A.FECHA_CREA,
	A.USUARIO_ACTU,
	A.ESTACION_ACTU,
	A.FECHA_ACTU
FROM dbo.GEN_PERSONA AS A;
GO
