-- Qué hace: vista de competencias de una persona (tab Formación de gen-empleado).
-- Cómo lo hace: proyecta GEN_PERSONA_COMPETENCIA con los campos del tab.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_COMPETENCIA]
AS
SELECT
	C.CORR_EMPRESA,
	C.CORR_PERSONA,
	C.CORR_COMPETENCIA,
	C.NOMBRE_COMPETENCIA,
	C.NIVEL_DOMINIO,
	C.USUARIO_CREA,
	C.ESTACION_CREA,
	C.FECHA_CREA,
	C.USUARIO_ACTU,
	C.ESTACION_ACTU,
	C.FECHA_ACTU
FROM dbo.GEN_PERSONA_COMPETENCIA AS C;
GO
