SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_ORDEN_COMPRA_SUM]
AS
SELECT A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.CORR_CUADRO_COMPARATIVO
	  ,dbo.StrConcat(CONVERT(VARCHAR(50),A.NUMERO_ORDEN)+', ') NUMERO_ORDEN
FROM COM_CUADRO_COMPARATIVO_ORDEN_COMPRA A
GROUP BY A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.CORR_CUADRO_COMPARATIVO
GO
