SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_SC_PERFIL_PUESTO]
AS
SELECT
  P.[CORR_EMPRESA],
  P.[CORR_DESCRIPTOR_PUESTO],
  P.[CORR_PERFIL_PUESTO],
  P.[EDAD_MINIMA],
  P.[EDAD_MAXIMA],
  P.[SEXO],
  P.[ESTADO_FAMILIAR],
  P.[CORR_DISPONIBILIDAD_HORARIO],
  P.[NOMBRE_DISPONIBILIDAD_HORARIO],
  P.[CORR_TIPO_MODALIDAD],
  P.[NOMBRE_MODALIDAD],
  P.[LICENCIA],
  P.[OTROS],
  P.[USUARIO_CREA],
  P.[ESTACION_CREA],
  P.[FECHA_CREA],
  P.[USUARIO_ACTU],
  P.[ESTACION_ACTU],
  P.[FECHA_ACTU]
FROM [dbo].[SC_PERFIL_PUESTO] P
GO
