
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_PARTIDA_DETA]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA      
      ,A.CORR_PARTIDA
      ,A.CORR_PARTIDA_DETA
      ,A.CUENTA_CONTABLE
      ,B.NOMBRE_CUENTA
      ,ISNULL(A.CORR_CENTRO_COSTO,0) CORR_CENTRO_COSTO
      ,ISNULL(C.NOMBRE_CENTRO,'') NOMBRE_CENTRO
      ,A.MONTO_CARGO
      ,A.MONTO_ABONO
      ,A.NOMBRE_TRAN
      ,ISNULL(ESTA_CONCILIA,0) ESTA_CONCILIA  
      ,A.CUENTA_CONTABLE + '-' + CONVERT(VARCHAR,ISNULL(A.CORR_AUXILIAR,0)) CORR_AUXILIAR_UNICO
      ,ISNULL(A.CORR_AUXILIAR,0) CORR_AUXILIAR
      ,ISNULL(A.MONTO_CARGO_FORANEA,0) MONTO_CARGO_FORANEA
      ,ISNULL(A.MONTO_ABONO_FORANEA,0) MONTO_ABONO_FORANEA
      ,ISNULL(D.NOMBRE_AUXILIAR,'') NOMBRE_AUXILIAR
FROM CON_PARTIDA_DETA A
INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
LEFT OUTER JOIN CON_CENTRO_COSTO C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_CENTRO_COSTO=C.CORR_CENTRO_COSTO
LEFT OUTER JOIN CON_CATALOGO_CUENTA_AUXI D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.CUENTA_CONTABLE=D.CUENTA_CONTABLE AND A.CORR_AUXILIAR=D.CORR_AUXILIAR
GO
