SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_CATALOGO_CUENTA_AUXI]
AS
SELECT A.CORR_EMPRESA
      ,A.CUENTA_CONTABLE
      ,A.CORR_AUXILIAR
      ,A.CUENTA_CONTABLE + '-' + CONVERT(VARCHAR,ISNULL(A.CORR_AUXILIAR,0)) CORR_AUXILIAR_UNICO
      ,A.NOMBRE_AUXILIAR
      ,A.CLASE_AUXILIAR
      ,CASE A.CLASE_AUXILIAR
       WHEN 'VA' THEN 'Varios'
       WHEN 'CB' THEN 'Cuentas Bancarias'
       WHEN 'CL' THEN 'Clientes'
       WHEN 'PR' THEN 'Proveedores'
       WHEN 'EM' THEN 'Empleados'
       WHEN 'CA' THEN 'Cajas'
       WHEN 'EP' THEN 'Empresas'
	   WHEN 'IN' THEN 'Inversiones'
	   WHEN 'RU' THEN 'Rutas'
       ELSE '' END NOMBRE_CLASE_AUXILIAR
      ,ISNULL(A.CORR_CUENTA_BANCO,0) CORR_CUENTA_BANCO
      ,ISNULL(A.CORR_CLIENTE,0) CORR_CLIENTE
      ,ISNULL(A.CORR_PROVEEDOR,0) CORR_PROVEEDOR
      ,ISNULL(A.CORR_EMPLEADO,0) CORR_EMPLEADO
      ,ISNULL(A.CORR_CAJA,0) CORR_CAJA
      ,ISNULL(A.CORR_EMPRESA_INTER,0) CORR_EMPRESA_INTER
      ,ISNULL(A.CORR_CONFI_PAIS_INTER,0) CORR_CONFI_PAIS_INTER
      ,ISNULL(B.CORR_EMPRESA_UNICO,'') CORR_EMPRESA_INTER_UNICO
	  ,ISNULL(A.CORR_INVERSION,0)CORR_INVERSION
	  ,ISNULL(A.CORR_RUTA_VENTA,0) CORR_RUTA_VENTA
      ,CASE A.CLASE_AUXILIAR
	   WHEN 'VA' THEN CONVERT(VARCHAR,A.CORR_AUXILIAR)
	   WHEN 'CB' THEN CONVERT(VARCHAR,A.CORR_CUENTA_BANCO)
	   WHEN 'CL' THEN CONVERT(VARCHAR,A.CORR_CLIENTE)
	   WHEN 'PR' THEN CONVERT(VARCHAR,A.CORR_PROVEEDOR)
	   WHEN 'EM' THEN CONVERT(VARCHAR,A.CORR_EMPLEADO)
	   WHEN 'CA' THEN CONVERT(VARCHAR,A.CORR_CAJA)
	   WHEN 'EP' THEN B.CORR_EMPRESA_UNICO
	   WHEN 'IN' THEN CONVERT(VARCHAR,ISNULL(A.CORR_INVERSION,0))
	   WHEN 'RU' THEN CONVERT(VARCHAR,A.CORR_RUTA_VENTA)
	   ELSE '' END CORR_AUXILIAR_REFERENCIA
	  ,CASE WHEN A.CORR_AUXILIAR=0 THEN '' ELSE REPLICATE('0',CASE WHEN LEN(A.CORR_AUXILIAR)<=4 THEN 4-LEN(A.CORR_AUXILIAR) ELSE 0 END)+CONVERT(VARCHAR,A.CORR_AUXILIAR) END CORR_AUXILIAR_REPLICADO
FROM CON_CATALOGO_CUENTA_AUXI A
LEFT OUTER JOIN V_GEN_EMPRESA B ON A.CORR_EMPRESA_INTER=B.CORR_EMPRESA

GO
