SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: vista de lectura de la bitácora de partidas contables.
-- Cómo lo hace: proyecta CON_PARTIDA_BITACORA y traduce códigos de estado a nombre corto.
CREATE OR ALTER VIEW [dbo].[V_CON_PARTIDA_BITACORA]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_PARTIDA_BITACORA,
	A.ANIO_PERIODO,
	A.MES_PERIODO,
	A.CORR_CLASE_PARTIDA,
	A.CORR_PARTIDA,
	A.TIPO_EVENTO,
	A.FECHA_EVENTO,
	A.ESTADO_ANTERIOR,
	CASE A.ESTADO_ANTERIOR
		WHEN 'DI' THEN 'Digitada'
		WHEN 'AP' THEN 'Aplicada'
		WHEN 'AN' THEN 'Anulada'
		ELSE ISNULL(A.ESTADO_ANTERIOR, '')
	END AS NOMBRE_ESTADO_ANTERIOR,
	A.ESTADO_NUEVO,
	CASE A.ESTADO_NUEVO
		WHEN 'DI' THEN 'Digitada'
		WHEN 'AP' THEN 'Aplicada'
		WHEN 'AN' THEN 'Anulada'
		ELSE ISNULL(A.ESTADO_NUEVO, '')
	END AS NOMBRE_ESTADO_NUEVO,
	A.OBSERVACION,
	A.USUARIO_CREA,
	A.ESTACION_CREA
FROM dbo.CON_PARTIDA_BITACORA A
GO
