SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CONDICION_PAGO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CONDICION_PAGO
      ,A.NOMBRE_CONDICION_PAGO
      ,A.DIAS_CREDITO
FROM COM_CONDICION_PAGO A
GO
