
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_CON_CATALOGO_CUENTA_ODS]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_ODS
      ,A.CUENTA_CONTABLE
      ,A.CORR_AUXILIAR
      ,A.CORR_CENTRO_COSTO
      ,A.CUENTA_CONTABLE_ODS	
      ,A.NOMBRE_CUENTA_ODS
      ,A.CORR_AUXILIAR_ODS
      ,A.NOMBRE_AUXILIAR_ODS
      ,A.CORR_CENTRO_COSTO_ODS
      ,A.NOMBRE_CENTRO_COSTO_ODS
      ,A.CUENTA_CONTABLE + '-' + CONVERT(VARCHAR,ISNULL(A.CORR_AUXILIAR,0)) CORR_AUXILIAR_UNICO
      
FROM CON_CATALOGO_CUENTA_ODS A

GO
