SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SEG_TIPO_USUARIO_OPCION]
AS
SELECT A.TIPO_USUARIO
	  ,A.CODIGO_SISTEMA
      ,B.NOMBRE_SISTEMA	  
	  ,B.IMAGEN_SISTEMA
      ,A.CODIGO_MENU
      ,B.NOMBRE_MENU
	  ,B.IMAGEN_MENU  
      ,A.CODIGO_OPCION
      ,B.NOMBRE_OPCION	 
	  ,B.IMAGEN_OPCION 
	  ,B.URL_OPCION
      ,A.NUEVO
      ,A.MODIFICAR
      ,A.ELIMINAR
      ,A.IMPRIMIR
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU	        
      ,B.ORDEN_SISTEMA
      ,B.ORDEN_MENU
      ,B.ORDEN_OPCION
	  ,CASE WHEN A.NUEVO=1 THEN 'C' ELSE '' END +
	   'R'+
	   CASE WHEN A.MODIFICAR=1 THEN 'U' ELSE '' END +
	   CASE WHEN A.ELIMINAR=1 THEN 'D' ELSE '' END + 
	   CASE WHEN A.IMPRIMIR=1 THEN 'P' ELSE '' END PERMISO
FROM SEG_TIPO_USUARIO_OPCION A
INNER JOIN V_SEG_CONFIG_OPCION B ON A.CODIGO_SISTEMA=B.CODIGO_SISTEMA AND A.CODIGO_MENU=B.CODIGO_MENU AND A.CODIGO_OPCION=B.CODIGO_OPCION
GO
