CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_ENTREVISTA
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_ENTREVISTA,
    X.CORR_SOLICITUD_EMPLEO,
    X.TIPO_ENTREVISTA,
    X.FECHA_ENTREVISTA,
    X.ENTREVISTADOR,
    X.ESTADO_ENTREVISTA,
    X.RESULTADO_ENTREVISTA,
    X.RESUMEN_ENTREVISTA,
    S.CORREO_INVITACION,
    S.NOMBRE AS NOMBRE_SOLICITUD,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_ENTREVISTA AS X
INNER JOIN dbo.SC_SOLICITUD_EMPLEO AS S
    ON S.CORR_EMPRESA = X.CORR_EMPRESA
   AND S.CORR_SOLICITUD_EMPLEO = X.CORR_SOLICITUD_EMPLEO;
GO
