SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_CON_PARTIDA_CUENTA]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.FECHA_PARTIDA
      ,CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='CIE' THEN 1 ELSE 0 END) PARTIDA_CIERRE
      ,CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='LIQ' THEN 1 ELSE 0 END) PARTIDA_LIQUIDACION
	  ,CONVERT(BIT,CASE WHEN C.NOMBRE_CORTO_CLASE='APE' THEN 1 ELSE 0 END) PARTIDA_APERTURA
      ,B.CUENTA_CONTABLE
      ,B.CORR_AUXILIAR
	  ,B.CORR_CENTRO_COSTO
      ,SUM(ISNULL(B.MONTO_CARGO,0)) MONTO_CARGO
      ,SUM(ISNULL(B.MONTO_ABONO,0)) MONTO_ABONO
      ,SUM(ISNULL(B.MONTO_CARGO_FORANEA,0)) MONTO_CARGO_FORANEA
      ,SUM(ISNULL(B.MONTO_ABONO_FORANEA,0)) MONTO_ABONO_FORANEA
FROM CON_PARTIDA A
INNER JOIN CON_PARTIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
INNER JOIN CON_CLASE_PARTIDA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_CLASE_PARTIDA=C.CORR_CLASE_PARTIDA
WHERE A.ESTADO_PARTIDA='AP'
--AND C.NOMBRE_CORTO_CLASE<>'APE'
GROUP BY A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO    
      ,A.FECHA_PARTIDA  
      ,CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='CIE' THEN 1 ELSE 0 END)
      ,CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='LIQ' THEN 1 ELSE 0 END)
	  ,CONVERT(BIT,CASE WHEN C.NOMBRE_CORTO_CLASE='APE' THEN 1 ELSE 0 END)
      ,B.CUENTA_CONTABLE
      ,B.CORR_AUXILIAR
	  ,B.CORR_CENTRO_COSTO

GO
