SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_UNIDAD_MEDIDA]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_UNIDAD_MEDIDA
      ,A.NOMBRE_UNIDAD_MEDIDA
      ,A.NOMBRE_CORTO
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
FROM COM_UNIDAD_MEDIDA A
GO
