SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_GEN_EMPLEADO]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_EMPLEADO,
	A.NOMBRE_EMPLEADO,
	ISNULL(A.NOMBRE_1, N'') AS NOMBRE_1,
	ISNULL(A.NOMBRE_2, N'') AS NOMBRE_2,
	ISNULL(A.APELLIDO_1, N'') AS APELLIDO_1,
	ISNULL(A.APELLIDO_2, N'') AS APELLIDO_2,
	ISNULL(A.APELLIDO_3, N'') AS APELLIDO_3,
	ISNULL(A.DUI, N'') AS DUI,
	ISNULL(A.NIT, N'') AS NIT,
	ISNULL(A.CORREO_ELECTRONICO, N'') AS CORREO_ELECTRONICO,
	ISNULL(A.TELEFONO_1, N'') AS TELEFONO_1,
	ISNULL(A.CORR_CENTRO_COSTO, 0) AS CORR_CENTRO_COSTO,
	ISNULL(A.CORR_DEPARTAMENTO, 0) AS CORR_DEPARTAMENTO,
	ISNULL(A.CORR_PUESTO, 0) AS CORR_PUESTO,
	A.ESTADO_EMPLEADO,
	CASE A.ESTADO_EMPLEADO
		WHEN N'1' THEN N'Activo'
		WHEN N'0' THEN N'Inactivo'
		WHEN N'AC' THEN N'Activo'
		WHEN N'IN' THEN N'Inactivo'
		ELSE N''
	END AS NOMBRE_ESTADO_EMPLEADO,
	ISNULL(A.LOGIN_SISTEMA, N'') AS LOGIN_SISTEMA,
	ISNULL(A.LOGIN_SISTEMA_WEB, N'') AS LOGIN_SISTEMA_WEB,
	A.USUARIO_CREA,
	A.FECHA_CREA,
	A.ESTACION_CREA,
	A.USUARIO_ACTU,
	A.FECHA_ACTU,
	A.ESTACION_ACTU
FROM dbo.GEN_EMPLEADO A
GO
