SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_SEG_OPCION_SISTEMA_SUITE]
AS
SELECT A.CODIGO_OPCION      
	  ,A.CODIGO_SUITE
      ,C.NOMBRE_SUITE
FROM SEG_OPCION_SISTEMA_SUITE A
INNER JOIN SEG_SUITE C ON A.CODIGO_SUITE=C.CODIGO_SUITE
GO
