
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_PARTIDA]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,B.NOMBRE_CLASE_PARTIDA
      ,B.NOMBRE_CORTO_CLASE
      ,A.CORR_PARTIDA
      ,A.FECHA_PARTIDA
      ,ISNULL(A.NUMERO_DOCUMENTO,'') NUMERO_DOCUMENTO
      ,A.NOMBRE_PARTIDA
      ,A.ESTADO_PARTIDA
      ,CASE A.ESTADO_PARTIDA
      WHEN 'DI' THEN 'DIGITADO' 
      WHEN 'AP' THEN 'APLICADO'
      WHEN 'AN' THEN 'ANULADO'            
      ELSE '' END NOMBRE_ESTADO_PARTIDA
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
      ,A.CLASE_PARTIDA
      ,CASE A.CLASE_PARTIDA
      WHEN 'NOR' THEN 'Normal'
      WHEN 'LIQ' THEN 'LiquidaciÃ³n'
      WHEN 'CIE' THEN 'Cierre'
      ELSE '' END NOMBRE_CLASE_PARTIDA2
      ,SUM(C.MONTO_CARGO) MONTO_CARGO
      ,SUM(C.MONTO_ABONO) MONTO_ABONO
      ,ISNULL(A.CORR_MONEDA,0) CORR_MONEDA
      ,CAST('' AS VARCHAR(50)) NOMBRE_MONEDA
      ,ISNULL(A.FACTOR_CAMBIO,0) FACTOR_CAMBIO
      ,ISNULL(A.OPERADOR,'*') OPERADOR
      ,CAST('' AS VARCHAR(100)) DESCRIPCION_MONEDA
FROM CON_PARTIDA A
INNER JOIN CON_CLASE_PARTIDA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA
LEFT OUTER JOIN CON_PARTIDA_DETA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.ANIO_PERIODO=C.ANIO_PERIODO AND A.MES_PERIODO=C.MES_PERIODO AND A.CORR_CLASE_PARTIDA=C.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=C.CORR_PARTIDA
GROUP BY A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,B.NOMBRE_CLASE_PARTIDA
      ,B.NOMBRE_CORTO_CLASE
      ,A.CORR_PARTIDA
      ,A.FECHA_PARTIDA
      ,ISNULL(A.NUMERO_DOCUMENTO,'')
      ,A.NOMBRE_PARTIDA
      ,A.ESTADO_PARTIDA
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
      ,A.CLASE_PARTIDA
      ,ISNULL(A.CORR_MONEDA,0)
      ,ISNULL(A.FACTOR_CAMBIO,0)
      ,ISNULL(A.OPERADOR,'*')
GO
