SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_ORDEN_COMPRA]
AS
SELECT DISTINCT
	 A.CORR_EMPRESA
	 ,A.ANIO_PERIODO
	 ,A.CORR_CUADRO_COMPARATIVO
	,B.ORDFAP FECHA_ORDEN_COMPRA
	,CONVERT(INT,B.ORDNUM) NUMERO_ORDEN_COMPRA
	,C.CODIGO_PROVEEDOR
	,C.NOMBRE_PROVEEDOR
	,H.AUTORIZACIONES_REALIZADAS
	,C.DIRECCION_PROVEEDOR
	,C.NOMBRE_COMERCIAL
	,C.NOMBRE_ACTIVIDAD_ECONOMICA ACTIVIDAD_ECONOMICA
	,C.NOMBRE_CONTACTO
	,C.CORREO_ELECTRONICO_1 CORREO_ELECTRONICO_PROVEEDOR
	,C.TELEFONO_FIJO TELEFONO_PROVEEDOR
	,B.ORDCPG CONDICION_PAGO
	,F.NUMERO_COTIZACION NUMERO_SOLI_COTIZACION
	,F.NOMBRE_DEPTO NOMBRE_DEPARTAMENTO
	,G.OBSERVACIONES
	,G.TOTAL_EN_LETRAS
	,G.SUB_TOTAL
	,G.TOTAL_IMPUESTO
	,G.TOTAL_ORDEN
	,A.CORR_CONDICION_PAGO
	,I.NOMBRE_CONDICION_PAGO
	,A.CORR_FORMA_PAGO
	,J.NOMBRE_FORMA_PAGO
	,A.DETALLE_FORMA_PAGO
	,B.ORDSTO ESTADO_ORDEN_COMPRA
	,CASE B.ORDSTO 
	WHEN 'P' THEN 'Pendiente de Compra'
	WHEN 'A' THEN 'Anulado'
	ELSE '' END NOMBRE_ESTADO_ORDEN_COMPRA
	FROM COM_CUADRO_COMPARATIVO_ORDEN_COMPRA A
	INNER JOIN CLASS_UEES.dbo.ORDENCOMPRA B ON A.NUMERO_ORDEN=B.ORDNUM
	INNER JOIN V_COM_PROVEEDOR C ON A.CORR_PROVEEDOR = C.CORR_PROVEEDOR
	INNER JOIN V_COM_CUADRO_COMPARATIVO_COTIZACION_SUM F ON A.CORR_EMPRESA = F.CORR_EMPRESA AND A.ANIO_PERIODO = F.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = F.CORR_CUADRO_COMPARATIVO
	INNER JOIN V_COM_ORDEN_COMPRA_TOTALES G ON A.NUMERO_ORDEN = G.NUMERO_ORDEN
	INNER JOIN V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_CONSOLIDADAS H ON A.CORR_EMPRESA = H.CORR_EMPRESA AND A.ANIO_PERIODO = H.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = H.CORR_CUADRO_COMPARATIVO
	LEFT OUTER JOIN COM_CONDICION_PAGO I ON A.CORR_CONDICION_PAGO = I.CORR_CONDICION_PAGO
	LEFT OUTER JOIN V_GEN_FORMA_PAGO J ON A.CORR_FORMA_PAGO = J.CORR_FORMA_PAGO
GO
