SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_DOCUMENTO_FISICO]
AS
SELECT A.CORR_SUSCRIPCION
      ,A.CORR_CONFI_PAIS
      ,A.CORR_EMPRESA
      ,A.CORR_DOCUMENTO
      ,A.NOMBRE_DOCUMENTO
      ,ISNULL(A.DESCRIPCION_DOCUMENTO,'') DESCRIPCION_DOCUMENTO
      ,A.CORR_TIPO_DOCUMENTO
      ,B.NOMBRE_TIPO_DOCUMENTO
      ,A.RUTA_DOCUMENTO
      ,A.NOMBRE_ARCHIVO      
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
      ,ISNULL(A.CODIGO_SUITE,'') CODIGO_SUITE
      ,ISNULL(A.CORR_DOCUMENTO_DOC,0) CORR_DOCUMENTO_DOC
	  ,ISNULL(C.CORR_DOCUMENTO,0) CORR_DOCUMENTO_FE
FROM [e-AdminFE].dbo.GEN_DOCUMENTO_FISICO A
INNER JOIN [e-AdminFE].dbo.GEN_TIPO_DOC_FISICO B ON A.CORR_SUSCRIPCION=B.CORR_SUSCRIPCION AND A.CORR_CONFI_PAIS=B.CORR_CONFI_PAIS AND A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIPO_DOCUMENTO=B.CORR_TIPO_DOCUMENTO
LEFT OUTER JOIN [e-AdminFE].dbo.COM_JSON_DOC C ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CORR_DOCUMENTO = C.CORR_DOCUMENTO_DOC
GO
