SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_CONSOLIDADAS]
AS
SELECT A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.CORR_CUADRO_COMPARATIVO
,dbo.StrConcat(CASE WHEN A.ESTADO_AUTORIZACION='SO' THEN A.LOGIN_SISTEMA ELSE '' END+',') AUTORIZACIONES_PENDIENTES 
,dbo.StrConcat(CASE WHEN A.ESTADO_AUTORIZACION='AP' THEN A.LOGIN_SISTEMA ELSE '' END+',') AUTORIZACIONES_REALIZADAS
FROM COM_CUADRO_COMPARATIVO_AUTORIZACIONES A
GROUP BY A.CORR_EMPRESA,A.ANIO_PERIODO,A.CORR_CUADRO_COMPARATIVO
GO
