SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_SC_UNIDADES_USUARIO]
AS
SELECT
  U.[CORR_EMPRESA],
  U.[CORR_UNIDAD],
  O.[CODIGO_UNIDAD],
  O.[NOMBRE_UNIDAD],
  U.[LOGIN_SISTEMA],
  S.[NOMBRE_USUARIO],
  U.[USUARIO_CREA],
  U.[ESTACION_CREA],
  U.[FECHA_CREA],
  U.[USUARIO_ACTU],
  U.[ESTACION_ACTU],
  U.[FECHA_ACTU]
FROM [dbo].[SC_UNIDADES_USUARIO] U
LEFT JOIN [dbo].[SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES] O
  ON O.[CORR_EMPRESA] = U.[CORR_EMPRESA]
 AND O.[CORR_UNIDAD] = U.[CORR_UNIDAD]
LEFT JOIN [dbo].[SEG_USUARIO] S
  ON S.[LOGIN_SISTEMA] = U.[LOGIN_SISTEMA]
GO
