SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_ADM_COM_JSON]
AS
SELECT A.CORR_SUSCRIPCION
      ,A.CORR_CONFI_PAIS
      ,A.CORR_EMPRESA
      ,A.CORR_TIENDA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_DOCUMENTO
      ,A.CORR_EMPRESA_FE
      ,A.CORR_DOCUMENTO_FE 
FROM [e-AdminFE].dbo.V_ADM_COM_JSON A
GO
