-- Qué hace: vista de mantenimiento del catálogo GEN_RELIGION.
-- Cómo lo hace: proyecta la tabla con ISNULL en ACTIVO_RELIGION (1 por defecto).
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_RELIGION]
AS
SELECT
	R.CORR_RELIGION,
	R.NOMBRE_RELIGION,
	R.DESCRIPCION,
	ISNULL(R.ACTIVO_RELIGION, 1) AS ACTIVO_RELIGION,
	R.USUARIO_CREA,
	R.ESTACION_CREA,
	R.FECHA_CREA,
	R.USUARIO_ACTU,
	R.ESTACION_ACTU,
	R.FECHA_ACTU
FROM dbo.GEN_RELIGION AS R;
GO
