SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_PARAMETRO_SMTP]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_PARAMETRO_SMTP,
	A.CORREO_REMITENTE,
	A.USUARIO_REMITENTE,
	A.CONTRASENA_REMITENTE,
	A.SERVIDOR_CORREO,
	A.PUERTO_CORREO,
	A.USA_SSL_CORREO,
	A.USUARIO_CREA,
	A.ESTACION_CREA,
	A.FECHA_CREA,
	A.USUARIO_ACTU,
	A.ESTACION_ACTU,
	A.FECHA_ACTU
FROM dbo.GEN_PARAMETRO_SMTP A
GO
