SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_PERSONA_EXPERIENCIA_LABORAL]
AS
SELECT [CORR_EMPRESA], [CORR_PERSONA_DATOS], [CORR_EXPERIENCIA_LABORAL],
       [EMPRESA], [TELEFONO], [CARGO], [JEFE_INMEDIATO], [FECHA_INICIO], [FECHA_FIN],
       [SALARIO_INICIAL], [SALARIO_FINAL], [MOTIVO_SALIDA], [USUARIO_CREA],
       [ESTACION_CREA], [FECHA_CREA], [USUARIO_ACTU], [ESTACION_ACTU], [FECHA_ACTU]
FROM [dbo].[SC_PERSONA_EXPERIENCIA_LABORAL]
GO
