-- Qué hace: vista de referencias laborales (tab Referencias de gen-empleado).
-- Cómo lo hace: proyecta GEN_PERSONA_REFERENCIA_LABORAL para lectura GetAll.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_REFERENCIA_LABORAL]
AS
SELECT
	R.CORR_EMPRESA,
	R.CORR_PERSONA,
	R.CORR_REFERENCIA_LABORAL,
	R.NOMBRE_COMPLETO,
	R.LUGAR_TRABAJO,
	R.TELEFONO,
	R.USUARIO_CREA,
	R.ESTACION_CREA,
	R.FECHA_CREA,
	R.USUARIO_ACTU,
	R.ESTACION_ACTU,
	R.FECHA_ACTU
FROM dbo.GEN_PERSONA_REFERENCIA_LABORAL AS R;
GO
