CREATE OR ALTER VIEW dbo.V_SC_REQUISICION_PERSONAL_CANDIDATO
AS
SELECT
    SR.CORR_EMPRESA,
    SR.CORR_REQUISICION_PERSONAL,
    SR.CORR_SOLICITUD_EMPLEO,
    EC.CORR_EXPEDIENTE_CANDIDATO,
    EC.CORR_PERSONA_DATOS,
    EC.NOMBRE_PERSONA,
    EC.DUI_PERSONA,
    EC.FECHA_GENERACION,
    EC.CORR_ESTADO_EXPEDIENTE,
    RC.CORR_REQUISICION_CANDIDATO,
    CAST(ISNULL(RC.ESTADO_DECISION, N'PENDIENTE') AS VARCHAR(20)) AS ESTADO_DECISION,
    RC.OBSERVACION_DECISION,
    RC.FECHA_DECISION,
    RC.USUARIO_DECISION
FROM dbo.SC_SOLICITUD_REQUISICION AS SR
INNER JOIN dbo.SC_SOLICITUD_EMPLEO AS S
    ON S.CORR_EMPRESA = SR.CORR_EMPRESA
   AND S.CORR_SOLICITUD_EMPLEO = SR.CORR_SOLICITUD_EMPLEO
INNER JOIN dbo.SC_EXPEDIENTE_SOLICITUD AS ES
    ON ES.CORR_EMPRESA = S.CORR_EMPRESA
   AND ES.CORR_SOLICITUD_EMPLEO = S.CORR_SOLICITUD_EMPLEO
INNER JOIN dbo.V_SC_EXPEDIENTE_CANDIDATO AS EC
    ON EC.CORR_EMPRESA = ES.CORR_EMPRESA
   AND EC.CORR_EXPEDIENTE_CANDIDATO = ES.CORR_EXPEDIENTE_CANDIDATO
LEFT JOIN dbo.SC_REQUISICION_CANDIDATO AS RC
    ON RC.CORR_EMPRESA = SR.CORR_EMPRESA
   AND RC.CORR_REQUISICION_PERSONAL = SR.CORR_REQUISICION_PERSONAL
   AND RC.CORR_EXPEDIENTE_CANDIDATO = EC.CORR_EXPEDIENTE_CANDIDATO
   AND RC.CORR_SOLICITUD_EMPLEO = SR.CORR_SOLICITUD_EMPLEO
WHERE EC.CORR_ESTADO_EXPEDIENTE = 2
  AND EC.ACTIVO = 1
  AND S.ACTIVO = 1;
GO
