SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES]
AS
SELECT
  CC.[CORR_EMPRESA],
  CC.[CORR_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES],
  CC.[NOMBRE_COMPETENCIAS_CONDUCTUALES],
  CC.[DESCRIPCION],
  CC.[CORR_DESCRIPTOR_PUESTO],
  CC.[CORR_PERFIL_PUESTO],
  CC.[CORR_COMPETENCIAS_CONDUCTUALES],
  CC.[USUARIO_CREA],
  CC.[ESTACION_CREA],
  CC.[FECHA_CREA],
  CC.[USUARIO_ACTU],
  CC.[ESTACION_ACTU],
  CC.[FECHA_ACTU],
  P.[CODIGO_TIPO_PUESTO]
FROM [dbo].[SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES] CC
LEFT JOIN [dbo].[SC_COMPETENCIAS_CONDUCTUALES] C
  ON CC.[CORR_EMPRESA] = C.[CORR_EMPRESA]
 AND CC.[CORR_COMPETENCIAS_CONDUCTUALES] = C.[CORR_COMPETENCIAS_CONDUCTUALES]
LEFT JOIN [dbo].[PLA_TIPO_PUESTO] P
  ON C.[CORR_EMPRESA] = P.[CORR_EMPRESA]
 AND C.[CORR_TIPO_PUESTO] = P.[CORR_TIPO_PUESTO]
GO
