SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_SC_BANDEJA_REQUISICION]
AS
SELECT
    R.CORR_EMPRESA,
    R.CORR_REQUISICION_PERSONAL,
    R.CORR_DESCRIPTOR_PUESTO,
    R.CORR_UNIDAD,
    R.NOMBRE_UNIDAD,
    R.CORR_PUESTO,
    R.NOMBRE_PUESTO,
    R.CORR_TIPO_MODALIDAD,
    R.MODALIDAD_NOMBRE,
    R.CORR_TIPO_CONTRATACION,
    R.NOMBRE_TIPO_CONTRATACION,
    R.CORR_TIPO_VACANTE,
    R.NOMBRE_TIPO_VACANTE,
    R.CANTIDAD_PLAZAS,
    R.PLAZAS_CUBIERTAS,
    R.FECHA_REQUISICION,
    R.JUSTIFICACION,
    R.CORR_EMPLEADO_SUSTITUTO,
    R.SALARIO,
    R.CORR_ESTADO_REQUISICION,
    R.FECHA_APROBACION,
    R.FECHA_CIERRE,
    R.TIEMPO_CONTRATO,
    R.HORARIO,
    R.USUARIO_CREA,
    CAST(ISNULL(U.NOMBRE_USUARIO, R.USUARIO_CREA) AS NVARCHAR(120)) AS NOMBRE_SOLICITANTE,
    R.ESTACION_CREA,
    R.FECHA_CREA,
    R.USUARIO_ACTU,
    R.ESTACION_ACTU,
    R.FECHA_ACTU
FROM dbo.V_SC_REQUISICION_PERSONAL AS R
LEFT JOIN dbo.SEG_USUARIO AS U
    ON U.LOGIN_SISTEMA = R.USUARIO_CREA;
GO
