SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_IMPUESTO_DETALLE_COMPRAS]
AS
SELECT  CONVERT(DATE, '') FECHA_EMISION,
	CONVERT(VARCHAR, '') CLASE_DOCUMENTO,
	CONVERT(INT, 0) TIPO_DOCUMENTO,
	CONVERT(BIGINT, 0) NUMERO_DOCUMENTO,
	CONVERT(VARCHAR, '') NIT_PROVEEDOR,
	CONVERT(VARCHAR,'') NOMBRE_PROVEEDOR,
	CONVERT(DECIMAL(18,2), 0) COMPRAS_INTERNAS_EXENTAS,
	CONVERT(DECIMAL(18,2), 0) INTERNACIONES_EXENTAS,
	CONVERT(DECIMAL(18,2), 0) IMPORTACIONES_EXENTAS,
	CONVERT(DECIMAL(18,2), 0) COMPRAS_INTERNAS_GRAVADAS,
	CONVERT(DECIMAL(18,2), 0) INTERNACIONES_GRAVADAS,
	CONVERT(DECIMAL(18,2), 0) IMPORTACIONES_GRAVADAS,
	CONVERT(VARCHAR, '') IMPORTACIONES_GRAVADAS_SERVICIO,
	CONVERT(DECIMAL(18,2), 0) CREDITO_FISCAL,
	CONVERT(DECIMAL(18,2), 0) TOTAL_COMPRAS,
	CONVERT(INT, 0) NUMERO_ANEXO
FROM COM_DOCUMENTO
GO
