SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DESCRIPTOR_KPI_FUNCION]
AS
SELECT
  K.[CORR_EMPRESA],
  K.[CORR_DESCRIPTOR_PUESTO],
  K.[CORR_KPI_FUNCION],
  K.[NOMBRE_INDICADOR],
  K.[CORR_FRECUENCIA],
  F.[NOMBRE_FRECUENCIA],
  K.[META],
  K.[USUARIO_CREA],
  K.[ESTACION_CREA],
  K.[FECHA_CREA],
  K.[USUARIO_ACTU],
  K.[ESTACION_ACTU],
  K.[FECHA_ACTU]
FROM [dbo].[SC_DESCRIPTOR_KPI_FUNCION] K
LEFT JOIN [dbo].[SC_FRECUENCIA] F
  ON K.[CORR_EMPRESA] = F.[CORR_EMPRESA]
 AND K.[CORR_FRECUENCIA] = F.[CORR_FRECUENCIA]
GO
