SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_DETA_SUM]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_CUADRO_COMPARATIVO
	  ,B.CODIGO_ITEM
	  ,E.INVDSC NOMBRE_ITEM 
	  ,F.NOMBRE_UNIDAD_MEDIDA
      ,B.CANTIDAD
	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=1 THEN B.PRECIO_UNITARIO ELSE 0 END) PRECIO_UNITARIO_1
	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=1 THEN B.MONTO_SUBTOTAL ELSE 0 END) MONTO_SUBTOTAL_1
	  ,CONVERT(VARCHAR(250),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=1 THEN B.MARCA ELSE '' END)) MARCA_1
	  ,CONVERT(BIT,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=1 THEN A.SELECCION ELSE 0 END))  SELECCION_1
	  ,CONVERT(VARCHAR(1000),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=1 THEN ISNULL(A.OBSERVACIONES,'') ELSE '' END))  OBSERVACIONES_1

	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=2 THEN B.PRECIO_UNITARIO ELSE 0 END) PRECIO_UNITARIO_2
	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=2 THEN B.MONTO_SUBTOTAL ELSE 0 END) MONTO_SUBTOTAL_2
	  ,CONVERT(VARCHAR(250),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=2 THEN B.MARCA ELSE '' END)) MARCA_2
	  ,CONVERT(BIT,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=2 THEN A.SELECCION ELSE 0 END))  SELECCION_2
	  ,CONVERT(VARCHAR(1000),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=2 THEN ISNULL(A.OBSERVACIONES,'') ELSE '' END))  OBSERVACIONES_2

	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=3 THEN B.PRECIO_UNITARIO ELSE 0 END) PRECIO_UNITARIO_3
	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=3 THEN B.MONTO_SUBTOTAL ELSE 0 END) MONTO_SUBTOTAL_3
	  ,CONVERT(VARCHAR(250),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=3 THEN B.MARCA ELSE '' END)) MARCA_3
	  ,CONVERT(BIT,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=3 THEN A.SELECCION ELSE 0 END))  SELECCION_3
	  ,CONVERT(VARCHAR(1000),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=3 THEN ISNULL(A.OBSERVACIONES,'') ELSE '' END))  OBSERVACIONES_3

	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=4 THEN B.PRECIO_UNITARIO ELSE 0 END) PRECIO_UNITARIO_4
	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=4 THEN B.MONTO_SUBTOTAL ELSE 0 END) MONTO_SUBTOTAL_4
	  ,CONVERT(VARCHAR(250),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=4 THEN B.MARCA ELSE '' END)) MARCA_4
	  ,CONVERT(BIT,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=4 THEN A.SELECCION ELSE 0 END))  SELECCION_4
	  ,CONVERT(VARCHAR(1000),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=4 THEN ISNULL(A.OBSERVACIONES,'') ELSE '' END))  OBSERVACIONES_4

	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=5 THEN B.PRECIO_UNITARIO ELSE 0 END) PRECIO_UNITARIO_5
	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=5 THEN B.MONTO_SUBTOTAL ELSE 0 END) MONTO_SUBTOTAL_5
	  ,CONVERT(VARCHAR(250),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=5 THEN B.MARCA ELSE '' END)) MARCA_5
	  ,CONVERT(BIT,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=5 THEN A.SELECCION ELSE 0 END))  SELECCION_5
	  ,CONVERT(VARCHAR(1000),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=5 THEN ISNULL(A.OBSERVACIONES,'') ELSE '' END))  OBSERVACIONES_5

	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=6 THEN B.PRECIO_UNITARIO ELSE 0 END) PRECIO_UNITARIO_6
	  ,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=6 THEN B.MONTO_SUBTOTAL ELSE 0 END) MONTO_SUBTOTAL_6
	  ,CONVERT(VARCHAR(250),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=6 THEN B.MARCA ELSE '' END)) MARCA_6
	  ,CONVERT(BIT,MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=6 THEN A.SELECCION ELSE 0 END))  SELECCION_6
	  ,CONVERT(VARCHAR(1000),MAX(CASE WHEN D.CORR_PROVEEDOR_FILA=6 THEN ISNULL(A.OBSERVACIONES,'') ELSE '' END))  OBSERVACIONES_6
FROM COM_CUADRO_COMPARATIVO_DETA A
INNER JOIN COM_COTIZACION_DETA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO_COTIZACION = B.ANIO_PERIODO AND A.CORR_COTIZACION = B.CORR_COTIZACION AND A.CORR_COTIZACION_DETA = B.CORR_COTIZACION_DETA
INNER JOIN COM_COTIZACION C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO = C.ANIO_PERIODO AND B.CORR_COTIZACION = C.CORR_COTIZACION
INNER JOIN V_COM_CUADRO_COMPARATIVO_PROVEEDOR D ON A.CORR_EMPRESA = D.CORR_EMPRESA AND A.CORR_CUADRO_COMPARATIVO = D.CORR_CUADRO_COMPARATIVO AND C.CORR_PROVEEDOR = D.CORR_PROVEEDOR
INNER JOIN [CLASS_UEES].dbo.INVENTARIOS E ON B.CODIGO_ITEM COLLATE Modern_Spanish_CI_AS = E.INVCOD AND E.INVREG = 'E' AND E.INVSUC='001'
LEFT OUTER JOIN COM_UNIDAD_MEDIDA F ON B.CORR_EMPRESA = F.CORR_EMPRESA AND B.CORR_UNIDAD_MEDIDA = F.CORR_UNIDAD_MEDIDA
GROUP BY A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_CUADRO_COMPARATIVO
	  ,B.CODIGO_ITEM
	  ,E.INVDSC 
	  ,F.NOMBRE_UNIDAD_MEDIDA
      ,B.CANTIDAD
GO
