SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- View

CREATE VIEW [dbo].[V_COM_COTIZACION_CORREO]
AS
SELECT A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.CORR_COTIZACION
,A.FECHA_COTIZACION
,A.OBSERVACIONES
,BB.NOMBRE_PROVEEDOR
,B.CORREO_ELECTRONICO
,G.USREML CORREO_ELECTRONICO_CCO
--,'jonathan.avalos@uees.edu.sv' CORREO_ELECTRONICO
--,'jjonathanavalos@gmail.com' CORREO_ELECTRONICO_CCO
,D.CORREO_REMITENTE
,D.USUARIO_REMITENTE
,D.CONTRASENA_REMITENTE
,D.SERVIDOR_CORREO
,D.PUERTO_CORREO
,D.USA_SSL_CORREO
,E.NOMBRE_EMPRESA
FROM COM_COTIZACION A
INNER JOIN COM_PROVEEDOR BB ON A.CORR_PROVEEDOR = BB.CORR_PROVEEDOR
INNER JOIN V_COM_PROVEEDOR_USUARIO_SUM B ON A.CORR_PROVEEDOR = B.CORR_PROVEEDOR
INNER JOIN COM_PARAMETRO D ON A.CORR_EMPRESA=D.CORR_EMPRESA
INNER JOIN GEN_EMPRESA E ON A.CORR_EMPRESA=E.CORR_EMPRESA
INNER JOIN dbo.COM_SOLI_COTIZACION F ON F.CORR_EMPRESA = A.CORR_EMPRESA AND F.ANIO_PERIODO = A.ANIO_PERIODO_SOLI_COTI AND F.CORR_SOLI_COTIZACION = A.CORR_SOLI_COTIZACION
INNER JOIN CLASS_UEES.dbo.USUARIOS G ON F.USUARIO_CREA=G.USRUID COLLATE SQL_Latin1_General_CP1_CI_AS
GO
