SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/*
  Lookup documentos compras — proveedores + empleados (P) con prefijo en nombre.
  Basado en V_COM_PROVEEDOR (linked server CLASS ya resuelto).
*/
CREATE VIEW [dbo].[V_COM_PROVEEDOR_COMPRAS]
AS
SELECT
	P.CORR_PROVEEDOR,
	P.CODIGO_PROVEEDOR,
	P.TIPO_PERSONERIA,
	P.NOMBRE_TIPO_PERSONERIA,
	CASE
		WHEN C.CLITIP = 'V' THEN N'(PRV)  '
		ELSE N'(DOC)  '
	END
	+ LTRIM(RTRIM(P.CODIGO_PROVEEDOR COLLATE DATABASE_DEFAULT))
	+ N' - '
	+ LTRIM(RTRIM(P.NOMBRE_PROVEEDOR COLLATE DATABASE_DEFAULT)) AS NOMBRE_PROVEEDOR,
	P.PRIMER_NOMBRE,
	P.SEGUNDO_NOMBRE,
	P.PRIMER_APELLIDO,
	P.SEGUNDO_APELLIDO,
	P.NOMBRE_COMERCIAL,
	P.CORR_TIPO_DIP,
	P.NOMBRE_TIPO_DIP,
	P.NUMERO_DIP,
	P.NUMERO_NRC,
	P.NUMERO_NIT,
	CONVERT(VARCHAR(10), P.CORR_ACTIVIDAD_ECONOMICA) AS CORR_ACTIVIDAD_ECONOMICA,
	P.NOMBRE_ACTIVIDAD_ECONOMICA,
	P.DIRECCION_PROVEEDOR,
	P.CODIGO_PAIS,
	P.NOMBRE_PAIS,
	P.CODIGO_DEPTO,
	P.NOMBRE_DEPTO,
	P.CODIGO_MUNICIPIO,
	P.NOMBRE_MUNICIPIO,
	P.NOMBRE_CONTACTO,
	P.TELEFONO_FIJO,
	P.TELEFONO_MOVIL,
	P.CORREO_ELECTRONICO_1,
	P.CORREO_ELECTRONICO_2,
	P.CORR_FORMA_PAGO,
	P.NOMBRE_FORMA_PAGO,
	P.CUENTA_BANCARIA,
	P.CORR_BANCO,
	P.NOMBRE_BANCO,
	P.ESTADO_PROVEEDOR,
	P.NOMBRE_ESTADO_PROVEEDOR,
	P.ESTADO_PROVEEDOR_WEB,
	P.NOMBRE_ESTADO_PROVEEDOR_WEB,
	P.USUARIO_CREA,
	P.FECHA_CREA,
	P.ESTACION_CREA,
	P.USUARIO_ACTU,
	P.FECHA_ACTU,
	P.ESTACION_ACTU,
	P.CORR_CONDICION_PAGO,
	P.NOMBRE_CONDICION_PAGO
FROM dbo.V_COM_PROVEEDOR P
INNER JOIN [CLASS_UEES].[CLASS_UEES].dbo.CLIENTES C ON P.CORR_PROVEEDOR = C.CLIIDU
WHERE C.CLITIP IN ('V', 'P')
GO
