SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_PROVEEDOR_SUM]
AS
SELECT A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.CORR_CUADRO_COMPARATIVO
	  ,dbo.StrConcat(A.NOMBRE_PROVEEDOR+', ') NOMBRE_PROVEEDOR
FROM V_COM_CUADRO_COMPARATIVO_PROVEEDOR A
GROUP BY A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.CORR_CUADRO_COMPARATIVO
GO
