SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
-- =============================================================================
-- Vista: dbo.V_SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES_FORMATO_CORTO_IMPR
-- Qué hace: competencias conductuales del perfil para impresión Formato corto (tabla 2 columnas).
-- Cómo: numera por perfil y agrupa de a pares; todas las competencias quedan en
--       NOMBRE_COMPETENCIA_COLUMNA_1 / NOMBRE_COMPETENCIA_COLUMNA_2 (impar a la izq.).
-- Uso: PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO (result set 11).
-- =============================================================================
CREATE OR ALTER VIEW [dbo].[V_SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES_FORMATO_CORTO_IMPR]
AS
WITH numbered AS (
  SELECT
    CC.[CORR_EMPRESA],
    CC.[CORR_DESCRIPTOR_PUESTO],
    CC.[CORR_PERFIL_PUESTO],
    CC.[NOMBRE_COMPETENCIAS_CONDUCTUALES],
    ROW_NUMBER() OVER (
      PARTITION BY CC.[CORR_EMPRESA], CC.[CORR_DESCRIPTOR_PUESTO], CC.[CORR_PERFIL_PUESTO]
      ORDER BY CC.[CORR_COMPETENCIAS_CONDUCTUALES]
    ) AS RN
  FROM [dbo].[SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES] CC
)
SELECT
  N.[CORR_EMPRESA],
  N.[CORR_DESCRIPTOR_PUESTO],
  N.[CORR_PERFIL_PUESTO],
  CAST((N.RN + 1) / 2 AS INT) AS CORR_FILA,
  MAX(CASE WHEN N.RN % 2 = 1 THEN N.[NOMBRE_COMPETENCIAS_CONDUCTUALES] END) AS NOMBRE_COMPETENCIA_COLUMNA_1,
  MAX(CASE WHEN N.RN % 2 = 0 THEN N.[NOMBRE_COMPETENCIAS_CONDUCTUALES] END) AS NOMBRE_COMPETENCIA_COLUMNA_2
FROM numbered N
GROUP BY
  N.[CORR_EMPRESA],
  N.[CORR_DESCRIPTOR_PUESTO],
  N.[CORR_PERFIL_PUESTO],
  CAST((N.RN + 1) / 2 AS INT)
GO
