SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_MOVIMIENTO_CONTA]
AS
SELECT A.CORR_EMPRESA
      ,D.NOMBRE_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,A.NOMBRE_CLASE_PARTIDA
      ,A.CORR_PARTIDA
      ,A.FECHA_PARTIDA
      ,A.NUMERO_DOCUMENTO
      ,A.NOMBRE_PARTIDA
      ,A.ESTADO_PARTIDA
      ,A.NOMBRE_ESTADO_PARTIDA
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU      
      ,A.FACTOR_CAMBIO
      ,A.CORR_MONEDA
      ,A.NOMBRE_MONEDA
      ,A.OPERADOR
      ,B.CORR_PARTIDA_DETA
      ,B.CUENTA_CONTABLE
      ,B.NOMBRE_CUENTA
      ,B.CORR_CENTRO_COSTO
      ,B.NOMBRE_CENTRO      
      ,B.MONTO_CARGO
      ,B.MONTO_ABONO            
      ,((B.MONTO_CARGO-B.MONTO_ABONO)* CASE WHEN C.CLASE_RUBRO IN('IN','GA') THEN -1 ELSE (CASE WHEN ISNULL(C.ES_DEBE,1)=1 THEN 1 ELSE CASE WHEN ISNULL(C.ES_HABER,0)=1 THEN -1 ELSE 0 END END) END) SALDO_FINAL
      ,B.MONTO_CARGO_FORANEA
      ,B.MONTO_ABONO_FORANEA          
      ,((B.MONTO_CARGO_FORANEA-B.MONTO_ABONO_FORANEA)*(CASE WHEN ISNULL(C.ES_DEBE,1)=1 THEN 1 ELSE CASE WHEN ISNULL(C.ES_HABER,0)=1 THEN -1 ELSE 0 END END)) SALDO_FINAL_FORANEA     
      ,B.NOMBRE_TRAN       
      ,C.ES_DEBE
      ,C.ES_HABER
      ,C.ES_DETALLE
      ,C.NIVEL
      ,C.CUENTA_MAYOR
      ,C.NOMBRE_CUENTA_MAYOR
      ,C.CODIGO_RUBRO
      ,C.NOMBRE_RUBRO
      ,C.NO_HABILITADA
      ,'' BENEFICIARIO
      --,ISNULL(E.NOMBRE_BENEFICIARIO,'') BENEFICIARIO
      ,ISNULL(F.CUENTA_CONTABLE_ODS,'') CUENTA_CONTABLE_ODS
      ,ISNULL(F.NOMBRE_CUENTA_ODS,'') NOMBRE_CUENTA_CONTABLE_ODS
     ,''AUXILIAR
      --,ISNULL(H.NOMBRE_AUXILIAR,CASE WHEN E.CLASE_MOVIMIENTO='TPR' AND B.MONTO_CARGO>0 AND ISNULL(E.CUENTA_CONTABLE_BANCO_DESTINO,'')=B.CUENTA_CONTABLE 
						--			 THEN ISNULL(E.NOMBRE_CUENTA_BANCO_DESTINO,'') 
						--			 WHEN E.CLASE_MOVIMIENTO='TPR' AND B.MONTO_ABONO>0 AND ISNULL(E.CUENTA_CONTABLE_BANCO,'')=B.CUENTA_CONTABLE 
						--			 THEN ISNULL(E.NOMBRE_CUENTA_BANCO,'') 									 
						--			 ELSE CASE WHEN ISNULL(E.CUENTA_CONTABLE_BANCO,ISNULL(G.CUENTA_CONTABLE_BANCO,''))=B.CUENTA_CONTABLE 
						--					   THEN ISNULL(ISNULL(E.NOMBRE_CUENTA_BANCO,G.NOMBRE_CUENTA_BANCO),'') 
						--					   ELSE CASE WHEN ISNULL(E.CUENTA_CONTABLE_BANCO_DESTINO,'')=B.CUENTA_CONTABLE 
						--								 THEN ISNULL(E.NOMBRE_CUENTA_BANCO_DESTINO,'') 
						--								 ELSE '' 
						--						    END
						--				  END 
						--		 END) AUXILIAR
      --,ISNULL(E.NOMBRE_TIPO_CHEQUE ,'') NOMBRE_TIPO_CHEQUE
	  ,''NOMBRE_TIPO_CHEQUE
      ,I.ESTADO_PERIODO_CON
      ,CASE I.ESTADO_PERIODO_CON
		WHEN 'CE' THEN 'Cerrado'
		ELSE 'Abierto' END AS NOMBRE_ESTADO_PERIODO_CON
      ,I.FECHA_CIERRE_CON      
FROM V_CON_PARTIDA A
INNER JOIN V_CON_PARTIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
INNER JOIN V_CON_CATALOGO_CUENTA C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CUENTA_CONTABLE=C.CUENTA_CONTABLE
INNER JOIN GEN_EMPRESA D ON A.CORR_EMPRESA=D.CORR_EMPRESA
--LEFT OUTER JOIN V_BAN_PARTIDA_DETA E ON B.CORR_EMPRESA=E.CORR_EMPRESA AND B.ANIO_PERIODO=E.ANIO_PERIODO AND B.MES_PERIODO=E.MES_PERIODO AND B.CORR_CLASE_PARTIDA=E.CORR_CLASE_PARTIDA AND B.CORR_PARTIDA=E.CORR_PARTIDA AND B.CORR_PARTIDA_DETA=E.CORR_PARTIDA_DETA
LEFT OUTER JOIN CON_CATALOGO_CUENTA_ODS F ON B.CORR_EMPRESA=F.CORR_EMPRESA AND B.CUENTA_CONTABLE=F.CUENTA_CONTABLE
--LEFT OUTER JOIN V_VEN_PARTIDA_DETA G ON B.CORR_EMPRESA=G.CORR_EMPRESA AND B.ANIO_PERIODO=G.ANIO_PERIODO AND B.MES_PERIODO=G.MES_PERIODO AND B.CORR_CLASE_PARTIDA=G.CORR_CLASE_PARTIDA AND B.CORR_PARTIDA=G.CORR_PARTIDA AND B.CORR_PARTIDA_DETA=G.CORR_PARTIDA_DETA
LEFT OUTER JOIN CON_CATALOGO_CUENTA_AUXI H ON B.CORR_EMPRESA=H.CORR_EMPRESA AND B.CUENTA_CONTABLE=H.CUENTA_CONTABLE AND B.CORR_AUXILIAR=H.CORR_AUXILIAR
INNER JOIN CON_PERIODO_CONTABLE I ON A.CORR_EMPRESA=I.CORR_EMPRESA AND A.ANIO_PERIODO=I.ANIO_PERIODO AND A.MES_PERIODO=I.MES_PERIODO

GO
