
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_BAN_CONCILIA_BANCARIA]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CUENTA_BANCO
      ,B.NUMERO_CUENTA_BANCO 
      ,B.NOMBRE_CUENTA_BANCO 
      ,B.NOMBRE_TIPO_CUENTA_BANCO 
      ,B.CUENTA_CONTABLE 
      ,A.CORR_CONCILIACION
      ,A.FECHA_CONCILIACION      
      ,A.SALDO_CUENTA_CONTA
      ,A.SALDO_CUENTA_BANCO
      ,ISNULL(C.MONTO_AUMENTA,0) MONTO_AUMENTA
      ,ISNULL(C.MONTO_DISMINUYE,0) MONTO_DISMINUYE
      ,A.SALDO_CUENTA_BANCO+ISNULL(C.MONTO_AUMENTA,0)-ISNULL(C.MONTO_DISMINUYE,0) SEGUN_LIBROS
      ,A.ESTADO_CONCILIACION
      ,CASE A.ESTADO_CONCILIACION 
		  WHEN 'DI' THEN 'Digitada'
		  WHEN 'AP' THEN 'Aplicada'
		  WHEN 'AN' THEN 'Anulada'
		  END NOMBRE_ESTADO_CONCILIACION
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
FROM BAN_CONCILIA_BANCARIA A
INNER JOIN V_BAN_CUENTA_BANCARIA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=B.CORR_CUENTA_BANCO
LEFT OUTER JOIN V_BAN_CONCILIA_BANCARIA_MOVI_SUM C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=C.CORR_CUENTA_BANCO AND A.CORR_CONCILIACION=C.CORR_CONCILIACION
GO

