SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_SOLI_COTIZACION_PROVEEDOR]
AS
SELECT A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.CORR_SOLI_COTIZACION
      ,A.CORR_PROVEEDOR
	  ,B.CLICUN CODIGO_PROVEEDOR
	  ,B.CLINAM NOMBRE_PROVEEDOR
      ,A.USUARIO_CREA
      ,A.ESTACION_CREA
      ,A.FECHA_CREA
	  ,C.ESTADO_COTIZACION
	  ,CASE	C.ESTADO_COTIZACION 
	  WHEN 'DI' THEN 'DIGITADO'
	  WHEN 'SO' THEN 'SOLICITADO'
	  WHEN 'AP' THEN 'APLICADO'
	  WHEN 'AN' THEN 'ANULADO'
	  ELSE '' END NOMBRE_ESTADO_COTIZACION
	  ,C.FECHA_COTIZACION
	  ,C.USUARIO_COTIZA
	  ,C.PLAZO_ENTREGA
	  ,C.OBSERVACIONES
	  ,A.CORR_CONDICION_PAGO
	  ,D.NOMBRE_CONDICION_PAGO
	  ,A.CORR_FORMA_PAGO
	  ,E.NOMBRE_FORMA_PAGO
	  ,A.DETALLE_FORMA_PAGO
FROM COM_SOLI_COTIZACION_PROVEEDOR A
INNER JOIN [CLASS_UEES].dbo.CLIENTES B ON A.CORR_PROVEEDOR=B.CLIIDU
LEFT OUTER JOIN dbo.COM_COTIZACION C ON A.ANIO_PERIODO=C.ANIO_PERIODO_SOLI_COTI AND A.CORR_SOLI_COTIZACION=C.CORR_SOLI_COTIZACION AND A.CORR_PROVEEDOR=C.CORR_PROVEEDOR
LEFT OUTER JOIN COM_CONDICION_PAGO D ON A.CORR_EMPRESA = D.CORR_EMPRESA AND A.CORR_CONDICION_PAGO = D.CORR_CONDICION_PAGO
LEFT OUTER JOIN V_GEN_FORMA_PAGO E ON A.CORR_FORMA_PAGO = E.CORR_FORMA_PAGO
GO
