SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_CONFI_REPORTE_DETA]
AS
SELECT CORR_EMPRESA
      ,CORR_CONFI_REPORTE
      ,CORR_CONFI_DETA
      ,CUENTA_CONTABLE_INI
      ,CUENTA_CONTABLE_FINA
  FROM CON_CONFI_REPORTE_DETA
  
GO
