-- Qué hace: vista de formación académica de una persona (tab Formación de gen-empleado).
-- Cómo lo hace: proyecta GEN_PERSONA_FORMACION_ACADEMICA con los campos del tab.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_FORMACION_ACADEMICA]
AS
SELECT
	F.CORR_EMPRESA,
	F.CORR_PERSONA,
	F.CORR_FORMACION_ACADEMICA,
	F.TITULO,
	F.CENTRO_EDUCATIVO,
	F.NIVEL,
	F.DESDE,
	F.HASTA,
	F.PERIODO_INICIAL,
	F.PERIODO_FINAL,
	F.PERIODO,
	F.USUARIO_CREA,
	F.ESTACION_CREA,
	F.FECHA_CREA,
	F.USUARIO_ACTU,
	F.ESTACION_ACTU,
	F.FECHA_ACTU
FROM dbo.GEN_PERSONA_FORMACION_ACADEMICA AS F;
GO
