SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: vista de lectura del mtto de centros de costo.
-- Cómo lo hace: proyecta CON_CENTRO_COSTO con tipo, estado, unidad, área, nivel y centro mayor.
CREATE OR ALTER VIEW [dbo].[V_CON_CENTRO_COSTO]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_CENTRO_COSTO,
	A.NOMBRE_CENTRO,
	ISNULL(A.CUENTA_CONTABLE, '') AS CUENTA_CONTABLE,
	CASE
		WHEN RTRIM(LTRIM(ISNULL(A.CODIGO_CENTRO_COSTO, ''))) = '' THEN CONVERT(VARCHAR(30), A.CORR_CENTRO_COSTO)
		ELSE ISNULL(A.CODIGO_CENTRO_COSTO, '')
	END AS CODIGO_CENTRO_COSTO,
	ISNULL(A.CORR_CENTRO_COSTO_MAYOR, 0) AS CORR_CENTRO_COSTO_MAYOR,
	ISNULL(M.NOMBRE_CENTRO, '') AS NOMBRE_CENTRO_COSTO_MAYOR,
	ISNULL(M.CODIGO_CENTRO_COSTO, '') AS CODIGO_CENTRO_COSTO_MAYOR,
	ISNULL(A.CORR_CENTRO_COSTO_NIVEL, 0) AS CORR_CENTRO_COSTO_NIVEL,
	ISNULL(N.NOMBRE_NIVEL, '') AS NOMBRE_NIVEL,
	ISNULL(N.NIVEL, 0) AS NIVEL,
	ISNULL(A.CORR_TIPO_CENTRO_COSTO, 0) AS CORR_TIPO_CENTRO_COSTO,
	ISNULL(C.NOMBRE_TIPO_CENTRO_COSTO, '') AS NOMBRE_TIPO_CENTRO_COSTO,
	ISNULL(C.CLASE_CENTRO_COSTO, 'CO') AS CLASE_CENTRO_COSTO,
	ISNULL(A.ESTADO_CENTRO_COSTO, '') AS ESTADO_CENTRO_COSTO,
	CASE A.ESTADO_CENTRO_COSTO
		WHEN 'AC' THEN 'Activo'
		ELSE ''
	END AS NOMBRE_ESTADO_CENTRO_COSTO,
	CASE
		WHEN A.CORR_CENTRO_COSTO = 0 THEN ''
		ELSE REPLICATE('0', CASE WHEN LEN(A.CORR_CENTRO_COSTO) <= 4 THEN 4 - LEN(A.CORR_CENTRO_COSTO) ELSE 0 END)
			+ CONVERT(VARCHAR(30), A.CORR_CENTRO_COSTO)
	END AS CORR_CENTRO_COSTO_REPLICADO,
	ISNULL(A.CORR_UNIDAD_NEGOCIO, 0) AS CORR_UNIDAD_NEGOCIO,
	ISNULL(D.NOMBRE_UNIDAD_NEGOCIO, '') AS NOMBRE_UNIDAD_NEGOCIO,
	CASE
		WHEN LEN(ISNULL(A.CODIGO_TERMINACION, '')) <= LEN(ISNULL(A.CODIGO_CENTRO_COSTO, ''))
			THEN SUBSTRING(A.CODIGO_CENTRO_COSTO, 1, LEN(A.CODIGO_CENTRO_COSTO) - LEN(A.CODIGO_TERMINACION))
		ELSE ''
	END AS CODIGO_UNIDAD_NEGOCIO,
	ISNULL(A.CORR_AREA_FUNCIONAL, 0) AS CORR_AREA_FUNCIONAL,
	ISNULL(E.NOMBRE_AREA_FUNCIONAL, '') AS NOMBRE_AREA_FUNCIONAL,
	ISNULL(A.CODIGO_TERMINACION, '') AS CODIGO_TERMINACION,
	ISNULL(A.CORR_EMPLEADO_JEFE, 0) AS CORR_EMPLEADO_JEFE,
	ISNULL(F.NOMBRE_EMPLEADO, '') AS NOMBRE_EMPLEADO,
	ISNULL(A.CORR_CLIENTE, 0) AS CORR_CLIENTE,
	A.FECHA_INICIAL,
	A.FECHA_FINAL
FROM dbo.CON_CENTRO_COSTO A
LEFT OUTER JOIN dbo.CON_TIPO_CENTRO_COSTO C
	ON A.CORR_EMPRESA = C.CORR_EMPRESA
	AND A.CORR_TIPO_CENTRO_COSTO = C.CORR_TIPO_CENTRO_COSTO
LEFT OUTER JOIN dbo.CON_UNIDAD_NEGOCIO D
	ON A.CORR_EMPRESA = D.CORR_EMPRESA
	AND A.CORR_UNIDAD_NEGOCIO = D.CORR_UNIDAD_NEGOCIO
LEFT OUTER JOIN dbo.CON_AREA_FUNCIONAL E
	ON A.CORR_EMPRESA = E.CORR_EMPRESA
	AND A.CORR_AREA_FUNCIONAL = E.CORR_AREA_FUNCIONAL
LEFT OUTER JOIN dbo.GEN_EMPLEADO F
	ON A.CORR_EMPRESA = F.CORR_EMPRESA
	AND A.CORR_EMPLEADO_JEFE = F.CORR_EMPLEADO
LEFT OUTER JOIN dbo.CON_CENTRO_COSTO_NIVEL N
	ON A.CORR_EMPRESA = N.CORR_EMPRESA
	AND A.CORR_CENTRO_COSTO_NIVEL = N.CORR_CENTRO_COSTO_NIVEL
LEFT OUTER JOIN dbo.CON_CENTRO_COSTO M
	ON A.CORR_EMPRESA = M.CORR_EMPRESA
	AND A.CORR_CENTRO_COSTO_MAYOR = M.CORR_CENTRO_COSTO
GO
