SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_IMPUESTO_RET_IVA_13_TERCEROS_DOMICILIADOS_POR_DECLARANTE]
AS
SELECT	CONVERT(VARCHAR, '') NIT_SUJETO,
	CONVERT(DATE, '') FECHA_EMISION,
	CONVERT(INT, 0) TIPO_DOCUMENTO,
	CONVERT(VARCHAR, '') NUMERO_SERIE_DOCUMENTO,
	CONVERT(VARCHAR, '') NUMERO_RESOLUCION,
	CONVERT(INT, 0) NUMERO_DOCUMENTO,
	CONVERT(DECIMAL(18,2), 0) MONTO_SUJETO,
	CONVERT(DECIMAL(18,2), 0) MONTO_RETENCION,
	CONVERT(INT, 0) NUMERO_ANEXO
FROM VEN_DOCUMENTO
GO
