SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_SEG_OPCION_SISTEMA]
AS
SELECT A.CODIGO_OPCION
      ,A.NOMBRE_OPCION	        
      ,A.URL_OPCION
	  ,A.IMAGEN_OPCION
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU    
FROM SEG_OPCION_SISTEMA A
GO
