SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES]
AS
SELECT
  CC.[CORR_EMPRESA],
  CC.[CORR_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES],
  CC.[CODIGO_TIPO_PUESTO],
  CC.[NOMBRE_COMPETENCIAS_CONDUCTUALES],
  CC.[DESCRIPCION],
  CC.[CORR_DESCRIPTOR_PUESTO],
  CC.[CORR_PERFIL_PUESTO],
  CC.[CORR_COMPETENCIAS_CONDUCTUALES],
  CC.[USUARIO_CREA],
  CC.[ESTACION_CREA],
  CC.[FECHA_CREA],
  CC.[USUARIO_ACTU],
  CC.[ESTACION_ACTU],
  CC.[FECHA_ACTU]
FROM [dbo].[SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES] CC
GO
