-- Qué hace: vista de mantenimiento del catálogo GEN_ORIGEN_INGRESO.
-- Cómo lo hace: proyecta la tabla con ISNULL en ACTIVO_ORIGEN_INGRESO (1 por defecto).
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_ORIGEN_INGRESO]
AS
SELECT
	O.CORR_ORIGEN_INGRESO,
	O.NOMBRE_ORIGEN_INGRESO,
	ISNULL(O.ACTIVO_ORIGEN_INGRESO, 1) AS ACTIVO_ORIGEN_INGRESO,
	O.USUARIO_CREA,
	O.ESTACION_CREA,
	O.FECHA_CREA,
	O.USUARIO_ACTU,
	O.ESTACION_ACTU,
	O.FECHA_ACTU
FROM dbo.GEN_ORIGEN_INGRESO AS O;
GO
