-- Qué hace: vista de familiares que trabajan en UEES (tab Adicional de gen-empleado).
-- Cómo lo hace: une GEN_PERSONA_FAMILIAR_UEES con GEN_PARENTESCO para nombre del parentesco.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_FAMILIAR_UEES]
AS
SELECT
	F.CORR_EMPRESA,
	F.CORR_PERSONA,
	F.CORR_FAMILIAR_UEES,
	F.NOMBRE_COMPLETO,
	F.CORR_PARENTESCO,
	ISNULL(P.NOMBRE_PARENTESCO, N'') AS NOMBRE_PARENTESCO,
	F.TELEFONO,
	F.CARGO,
	F.LUGAR_TRABAJO,
	F.USUARIO_CREA,
	F.ESTACION_CREA,
	F.FECHA_CREA,
	F.USUARIO_ACTU,
	F.ESTACION_ACTU,
	F.FECHA_ACTU
FROM dbo.GEN_PERSONA_FAMILIAR_UEES AS F
LEFT JOIN dbo.GEN_PARENTESCO AS P
	ON P.CORR_PARENTESCO = F.CORR_PARENTESCO;
GO
