SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_DOCUMENTO_TOTAL_RESUMEN_CONSOLIDADO]
AS
SELECT A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.MES_PERIODO
,A.CORR_DOCUMENTO
,B.CORR_TIPO_DOC
,B.NOMBRE_CORTO_TIPO_DOC
,A.FECHA_DOCUMENTO
,A.NUMERO_DOCUMENTO
,A.CORR_PROVEEDOR
,A.NOMBRE_PROVEEDOR
,SUM(CASE WHEN C.CLASE_RUBRO='EXE' THEN C.MONTO_RUBRO ELSE 0 END) MONTO_EXENTO
,SUM(CASE WHEN C.CLASE_RUBRO='GRA' THEN C.MONTO_RUBRO ELSE 0 END) MONTO_GRAVADO
,SUM(CASE WHEN C.CLASE_RUBRO='IVA' THEN C.MONTO_RUBRO ELSE 0 END) MONTO_IVA
,SUM(CASE WHEN C.CLASE_RUBRO IN('RET','PER') THEN C.MONTO_RUBRO ELSE 0 END) MONTO_RETENCION
,SUM(CASE WHEN C.CLASE_RUBRO='VTO' THEN C.MONTO_RUBRO ELSE 0 END) MONTO_TOTAL
,SUM(CASE WHEN C.CLASE_RUBRO='ISR' THEN C.MONTO_RUBRO ELSE 0 END) ANTICIPO_A_CUENTA
,MAX(C.IMPUESTO_INCLUIDO) IMPUESTO_INCLUIDO
FROM COM_DOCUMENTO A
INNER JOIN GEN_TIPO_DOCUMENTO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIPO_DOC=B.CORR_TIPO_DOC 
INNER JOIN V_COM_DOCUMENTO_TOTAL C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.ANIO_PERIODO=C.ANIO_PERIODO AND A.MES_PERIODO=C.MES_PERIODO AND A.CORR_DOCUMENTO=C.CORR_DOCUMENTO 
INNER JOIN V_COM_PROVEEDOR D ON  A.CORR_PROVEEDOR=D.CORR_PROVEEDOR
WHERE A.ESTADO_DOCUMENTO='AP'
GROUP BY A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.MES_PERIODO
,A.CORR_DOCUMENTO
,B.CORR_TIPO_DOC
,B.NOMBRE_CORTO_TIPO_DOC
,A.FECHA_DOCUMENTO
,A.NUMERO_DOCUMENTO
,A.CORR_PROVEEDOR
,A.NOMBRE_PROVEEDOR
GO