SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO



CREATE VIEW [dbo].[V_COM_PROVEEDOR_COMPRAS]
AS
SELECT AA.CLIIDU CORR_PROVEEDOR
	  ,AA.CLICUN CODIGO_PROVEEDOR
      ,CASE WHEN ISNULL(AA.CLITID,'J')<>'J' THEN 
		ISNULL(A.TIPO_PERSONERIA,'N')
	   ELSE ISNULL(AA.CLITID,'J') COLLATE DATABASE_DEFAULT END TIPO_PERSONERIA
	  ,CASE CASE WHEN ISNULL(AA.CLITID,'J') COLLATE DATABASE_DEFAULT<>'J' THEN 
		ISNULL(A.TIPO_PERSONERIA,'N')
	   ELSE ISNULL(AA.CLITID,'J') COLLATE DATABASE_DEFAULT END
	  WHEN 'N' THEN 'Natural'
	  WHEN 'J' THEN 'Jurídico'
	  ELSE 'N' END NOMBRE_TIPO_PERSONERIA
      ,CASE WHEN AA.CLITIP='V' THEN '(PRV)' ELSE '(DOC)' END +'  '+ ISNULL(LTRIM(RTRIM(AA.CLICUN COLLATE DATABASE_DEFAULT)) + ' - ' + LTRIM(RTRIM(A.NOMBRE_PROVEEDOR)),LTRIM(RTRIM(AA.CLICUN COLLATE DATABASE_DEFAULT)) + ' - ' + LTRIM(RTRIM(AA.CLINAM)) COLLATE DATABASE_DEFAULT) NOMBRE_PROVEEDOR
      ,ISNULL(A.PRIMER_NOMBRE,CASE WHEN LEN(LTRIM(RTRIM(CLINOM)))>0 AND CHARINDEX(' ',LTRIM(RTRIM(CLINOM)))>0 THEN 
								SUBSTRING(LTRIM(RTRIM(CLINOM)),1,CHARINDEX(' ',LTRIM(RTRIM(CLINOM))) - 1) 
							 ELSE LTRIM(RTRIM(CLINOM)) END) PRIMER_NOMBRE
      ,ISNULL(A.SEGUNDO_NOMBRE,CASE WHEN LEN(LTRIM(RTRIM(CLINOM)))>0 AND CHARINDEX(' ',LTRIM(RTRIM(CLINOM)))>0 THEN 
								SUBSTRING(LTRIM(RTRIM(CLINOM)),CHARINDEX(' ',LTRIM(RTRIM(CLINOM))), LEN(LTRIM(RTRIM(CLINOM)))) 
							 ELSE '' END) SEGUNDO_NOMBRE
      ,ISNULL(A.PRIMER_APELLIDO,AA.CLIAP1) PRIMER_APELLIDO
      ,ISNULL(A.SEGUNDO_APELLIDO,AA.CLIAP2) SEGUNDO_APELLIDO
      ,ISNULL(A.NOMBRE_COMERCIAL,'') NOMBRE_COMERCIAL
      ,ISNULL(A.CORR_TIPO_DIP,2) CORR_TIPO_DIP
	  ,ISNULL(B.NOMBRE_TIPO_DIP,'') NOMBRE_TIPO_DIP
      ,ISNULL(A.NUMERO_DIP,CASE WHEN AA.CLITID='C' THEN AA.CLIIDE ELSE '' END) NUMERO_DIP
      ,ISNULL(A.NUMERO_NRC,ISNULL(AA.CLIRCT,'')) NUMERO_NRC
      --,ISNULL(A.NUMERO_NIT,CASE WHEN AA.CLITID NOT IN ('C','P') THEN AA.CLIIDE ELSE '' END) NUMERO_NIT
	  ,ISNULL(A.NUMERO_NIT,CASE WHEN LEN(REPLACE(REPLACE(CLIIDE,'-',''),' ',''))>10 THEN CLIIDE ELSE ISNULL(M.NIT, '') END COLLATE SQL_Latin1_General_CP1_CI_AS) NUMERO_NIT 
      ,ISNULL(A.CORR_ACTIVIDAD_ECONOMICA,'') CORR_ACTIVIDAD_ECONOMICA
	  ,ISNULL(LTRIM(RTRIM(C.CODDSC)),'') NOMBRE_ACTIVIDAD_ECONOMICA
      ,ISNULL(A.DIRECCION_PROVEEDOR,LTRIM(RTRIM(ISNULL(AA.CLIDIR,'')))) DIRECCION_PROVEEDOR
      ,RTRIM(LTRIM(ISNULL(A.CODIGO_PAIS,'SLV'))) CODIGO_PAIS
	  ,RTRIM(LTRIM(D.PAIDSC)) NOMBRE_PAIS
      ,ISNULL(RTRIM(LTRIM(A.CODIGO_DEPTO)),ISNULL(AA.CLIPRO,'')) CODIGO_DEPTO
	  ,ISNULL(RTRIM(LTRIM(E.PRODSC)),'') NOMBRE_DEPTO
      ,ISNULL(RTRIM(LTRIM(A.CODIGO_MUNICIPIO)),ISNULL(AA.CLICAN,'')) CODIGO_MUNICIPIO
	  ,ISNULL(RTRIM(LTRIM(F.PRODSC)),'') NOMBRE_MUNICIPIO
      ,ISNULL(A.NOMBRE_CONTACTO, LTRIM(RTRIM(ISNULL(AA.CLICTO,'')))) NOMBRE_CONTACTO
      ,ISNULL(A.TELEFONO_FIJO, LTRIM(RTRIM(ISNULL(CONVERT(VARCHAR,AA.CLITE1),'')))) TELEFONO_FIJO
      ,ISNULL(A.TELEFONO_MOVIL, LTRIM(RTRIM(ISNULL(CONVERT(VARCHAR,AA.CLITE2),'')))) TELEFONO_MOVIL
      ,ISNULL(A.CORREO_ELECTRONICO_1,LTRIM(RTRIM(ISNULL(AA.CLIEM1,'')))) CORREO_ELECTRONICO_1
      ,ISNULL(A.CORREO_ELECTRONICO_2,LTRIM(RTRIM(ISNULL(AA.CLIEM2,'')))) CORREO_ELECTRONICO_2
      ,ISNULL(A.CORR_FORMA_PAGO,4) CORR_FORMA_PAGO
	  ,ISNULL(G.NOMBRE_FORMA_PAGO,'') NOMBRE_FORMA_PAGO
      ,ISNULL(A.CUENTA_BANCARIA,'') CUENTA_BANCARIA
      ,ISNULL(A.CORR_BANCO,0) CORR_BANCO
	  ,ISNULL(H.NOMBRE_BANCO,'') NOMBRE_BANCO
      ,ISNULL(A.ESTADO_PROVEEDOR,ISNULL(AA.CLISTS,'I')) ESTADO_PROVEEDOR
	  ,CASE ISNULL(A.ESTADO_PROVEEDOR,ISNULL(AA.CLISTS,'I'))
	  WHEN 'A' THEN 'Activo'
	  WHEN 'I' THEN 'Inactivo'
	  ELSE '' END NOMBRE_ESTADO_PROVEEDOR
	  ,ISNULL(A.ESTADO_PROVEEDOR_WEB,'D') ESTADO_PROVEEDOR_WEB
	  ,CASE ISNULL(A.ESTADO_PROVEEDOR_WEB,'D')
	  WHEN 'D' THEN 'Digitado'
	  WHEN 'A' THEN 'Activo'
	  WHEN 'I' THEN 'Inactivo'
	  ELSE '' END NOMBRE_ESTADO_PROVEEDOR_WEB
	  ,ISNULL(A.CORR_CONDICION_PAGO,1)CORR_CONDICION_PAGO
	  ,ISNULL(I.NOMBRE_CONDICION_PAGO,'')NOMBRE_CONDICION_PAGO
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
	  ,ISNULL(AA.CLITCB,'') CLASE_TAMANIO
	  ,ISNULL(J.CODDSC,'') NOMBRE_CLASE_TAMANIO
FROM [CLASS_UEES].dbo.CLIENTES AA
LEFT OUTER JOIN COM_PROVEEDOR A ON AA.CLIIDU=A.CORR_PROVEEDOR
LEFT OUTER JOIN [e-AdminFE].dbo.GEN_TIPO_DIP B ON ISNULL(A.CORR_TIPO_DIP,2) = B.CORR_TIPO_DIP
LEFT OUTER JOIN [CLASS_UEES].dbo.CODIGOS C ON A.CORR_ACTIVIDAD_ECONOMICA=C.CODCOD COLLATE DATABASE_DEFAULT AND RTRIM(LTRIM(C.CODREL))='ACT_EMP' --AND LEN(C.CODCOD)<6
LEFT OUTER JOIN [CLASS_UEES].dbo.PAISES D ON RTRIM(LTRIM(ISNULL(A.CODIGO_PAIS,'SLV'))) COLLATE DATABASE_DEFAULT = RTRIM(LTRIM(D.PAICOD)) COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN [CLASS_UEES].dbo.PROVINCIAS E ON ISNULL(RTRIM(LTRIM(A.CODIGO_DEPTO)),AA.CLIPRO) COLLATE DATABASE_DEFAULT = RTRIM(LTRIM(E.PROCOD)) AND E.PROREG='P' COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN [CLASS_UEES].dbo.PROVINCIAS F ON ISNULL(RTRIM(LTRIM(A.CODIGO_DEPTO)),AA.CLIPRO) COLLATE DATABASE_DEFAULT = RTRIM(LTRIM(F.PROREL)) COLLATE DATABASE_DEFAULT AND ISNULL(RTRIM(LTRIM(A.CODIGO_MUNICIPIO)),AA.CLICAN) COLLATE DATABASE_DEFAULT = RTRIM(LTRIM(F.PROCOD)) COLLATE DATABASE_DEFAULT AND F.PROREG='C'
LEFT OUTER JOIN [e-AdminFE].dbo.GEN_FORMA_PAGO G ON ISNULL(A.CORR_FORMA_PAGO,4) = G.CORR_FORMA_PAGO
LEFT OUTER JOIN COM_BANCO H ON A.CORR_BANCO = H.CORR_BANCO
LEFT OUTER JOIN COM_CONDICION_PAGO I ON A.CORR_CONDICION_PAGO = I.CORR_CONDICION_PAGO
LEFT outer JOIN [E-ADMINFE].dbo.CLA_ACTIVIDAD_ECONOMICA k on a.CORR_ACTIVIDAD_ECONOMICA=k.CODIGO_ACTIVIDAD_ECONOMICA COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN PEM_TRABAJADORES_OTROS_DATOS M ON REPLACE(M.TRBCUN, '-', '') COLLATE SQL_Latin1_General_CP1_CI_AS = REPLACE(CLICUN, '-', '') COLLATE SQL_Latin1_General_CP1_CI_AS
INNER JOIN [CLASS_UEES].dbo.CODIGOS J ON AA.CLITCB=J.CODCOD AND J.CODREL='ACT_TCB'
WHERE AA.CLITIP='V'
--AND AA.CLICAT IN('PN-','PE-','PG-','PP-','PM-','PR-')
UNION ALL 
SELECT AA.CLIIDU CORR_PROVEEDOR
	  ,AA.CLICUN CODIGO_PROVEEDOR
      ,CASE WHEN ISNULL(AA.CLITID,'J')<>'J' THEN 
		ISNULL(A.TIPO_PERSONERIA,'N')
	   ELSE ISNULL(AA.CLITID,'J') COLLATE DATABASE_DEFAULT END TIPO_PERSONERIA
	  ,CASE CASE WHEN ISNULL(AA.CLITID,'J') COLLATE DATABASE_DEFAULT<>'J' THEN 
		ISNULL(A.TIPO_PERSONERIA,'N')
	   ELSE ISNULL(AA.CLITID,'J') COLLATE DATABASE_DEFAULT END
	  WHEN 'N' THEN 'Natural'
	  WHEN 'J' THEN 'Jurídico'
	  ELSE 'N' END NOMBRE_TIPO_PERSONERIA
      ,CASE WHEN AA.CLITIP='V' THEN '(PRV)' ELSE '(DOC)' END +'  '+ ISNULL(LTRIM(RTRIM(AA.CLICUN COLLATE DATABASE_DEFAULT)) + ' - ' + LTRIM(RTRIM(A.NOMBRE_PROVEEDOR)),LTRIM(RTRIM(AA.CLICUN COLLATE DATABASE_DEFAULT)) + ' - ' + LTRIM(RTRIM(AA.CLINAM)) COLLATE DATABASE_DEFAULT) NOMBRE_PROVEEDOR
      ,ISNULL(A.PRIMER_NOMBRE,CASE WHEN LEN(LTRIM(RTRIM(CLINOM)))>0 AND CHARINDEX(' ',LTRIM(RTRIM(CLINOM)))>0 THEN 
								SUBSTRING(LTRIM(RTRIM(CLINOM)),1,CHARINDEX(' ',LTRIM(RTRIM(CLINOM))) - 1) 
							 ELSE LTRIM(RTRIM(CLINOM)) END) PRIMER_NOMBRE
      ,ISNULL(A.SEGUNDO_NOMBRE,CASE WHEN LEN(LTRIM(RTRIM(CLINOM)))>0 AND CHARINDEX(' ',LTRIM(RTRIM(CLINOM)))>0 THEN 
								SUBSTRING(LTRIM(RTRIM(CLINOM)),CHARINDEX(' ',LTRIM(RTRIM(CLINOM))), LEN(LTRIM(RTRIM(CLINOM)))) 
							 ELSE '' END) SEGUNDO_NOMBRE
      ,ISNULL(A.PRIMER_APELLIDO,AA.CLIAP1) PRIMER_APELLIDO
      ,ISNULL(A.SEGUNDO_APELLIDO,AA.CLIAP2) SEGUNDO_APELLIDO
      ,ISNULL(A.NOMBRE_COMERCIAL,'') NOMBRE_COMERCIAL
      ,ISNULL(A.CORR_TIPO_DIP,2) CORR_TIPO_DIP
	  ,ISNULL(B.NOMBRE_TIPO_DIP,'') NOMBRE_TIPO_DIP
      ,ISNULL(A.NUMERO_DIP,CASE WHEN AA.CLITID='C' THEN AA.CLIIDE ELSE '' END) NUMERO_DIP
      ,ISNULL(A.NUMERO_NRC,ISNULL(AA.CLIRCT,'')) NUMERO_NRC
      --,ISNULL(A.NUMERO_NIT,CASE WHEN AA.CLITID NOT IN ('C','P') THEN AA.CLIIDE ELSE '' END) NUMERO_NIT
	  ,ISNULL(A.NUMERO_NIT,CASE WHEN LEN(REPLACE(REPLACE(CLIIDE,'-',''),' ',''))>10 THEN CLIIDE ELSE ISNULL(M.NIT, '') END COLLATE SQL_Latin1_General_CP1_CI_AS) NUMERO_NIT
      ,ISNULL(A.CORR_ACTIVIDAD_ECONOMICA,'') CORR_ACTIVIDAD_ECONOMICA
	  --,ISNULL(LTRIM(RTRIM(C.CODDSC)),'') NOMBRE_ACTIVIDAD_ECONOMICA
	  ,ISNULL(LTRIM(RTRIM(C.CODDSC)),'') NOMBRE_ACTIVIDAD_ECONOMICA
      ,ISNULL(A.DIRECCION_PROVEEDOR,LTRIM(RTRIM(ISNULL(AA.CLIDIR,'')))) DIRECCION_PROVEEDOR
      ,RTRIM(LTRIM(ISNULL(A.CODIGO_PAIS,'SLV'))) CODIGO_PAIS
	  ,RTRIM(LTRIM(D.PAIDSC)) NOMBRE_PAIS
      ,ISNULL(RTRIM(LTRIM(A.CODIGO_DEPTO)),ISNULL(AA.CLIPRO,'')) CODIGO_DEPTO
	  ,ISNULL(RTRIM(LTRIM(E.PRODSC)),'') NOMBRE_DEPTO
      ,ISNULL(RTRIM(LTRIM(A.CODIGO_MUNICIPIO)),ISNULL(AA.CLICAN,'')) CODIGO_MUNICIPIO
	  ,ISNULL(RTRIM(LTRIM(F.PRODSC)),'') NOMBRE_MUNICIPIO
      ,ISNULL(A.NOMBRE_CONTACTO, LTRIM(RTRIM(ISNULL(AA.CLICTO,'')))) NOMBRE_CONTACTO
      ,ISNULL(A.TELEFONO_FIJO, LTRIM(RTRIM(ISNULL(CONVERT(VARCHAR,AA.CLITE1),'')))) TELEFONO_FIJO
      ,ISNULL(A.TELEFONO_MOVIL, LTRIM(RTRIM(ISNULL(CONVERT(VARCHAR,AA.CLITE2),'')))) TELEFONO_MOVIL
      ,ISNULL(A.CORREO_ELECTRONICO_1,LTRIM(RTRIM(ISNULL(AA.CLIEM1,'')))) CORREO_ELECTRONICO_1
      ,ISNULL(A.CORREO_ELECTRONICO_2,LTRIM(RTRIM(ISNULL(AA.CLIEM2,'')))) CORREO_ELECTRONICO_2
      ,ISNULL(A.CORR_FORMA_PAGO,4) CORR_FORMA_PAGO
	  ,ISNULL(G.NOMBRE_FORMA_PAGO,'') NOMBRE_FORMA_PAGO
      ,ISNULL(A.CUENTA_BANCARIA,'') CUENTA_BANCARIA
      ,ISNULL(A.CORR_BANCO,0) CORR_BANCO
	  ,ISNULL(H.NOMBRE_BANCO,'') NOMBRE_BANCO
      ,ISNULL(A.ESTADO_PROVEEDOR,ISNULL(AA.CLISTS,'I')) ESTADO_PROVEEDOR
	  ,CASE ISNULL(A.ESTADO_PROVEEDOR,ISNULL(AA.CLISTS,'I'))
	  WHEN 'A' THEN 'Activo'
	  WHEN 'I' THEN 'Inactivo'
	  ELSE '' END NOMBRE_ESTADO_PROVEEDOR
	  ,ISNULL(A.ESTADO_PROVEEDOR_WEB,'D') ESTADO_PROVEEDOR_WEB
	  ,CASE ISNULL(A.ESTADO_PROVEEDOR_WEB,'D')
	  WHEN 'D' THEN 'Digitado'
	  WHEN 'A' THEN 'Activo'
	  WHEN 'I' THEN 'Inactivo'
	  ELSE '' END NOMBRE_ESTADO_PROVEEDOR_WEB
	  ,ISNULL(A.CORR_CONDICION_PAGO,1)CORR_CONDICION_PAGO
	  ,ISNULL(I.NOMBRE_CONDICION_PAGO,'')NOMBRE_CONDICION_PAGO
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
	  ,ISNULL(AA.CLITCB,'') CLASE_TAMANIO
	  ,ISNULL(J.CODDSC,'') NOMBRE_CLASE_TAMANIO
FROM [CLASS_UEES].dbo.CLIENTES AA
LEFT OUTER JOIN COM_PROVEEDOR A ON AA.CLIIDU=A.CORR_PROVEEDOR
LEFT OUTER JOIN [e-AdminFE].dbo.GEN_TIPO_DIP B ON ISNULL(A.CORR_TIPO_DIP,2) = B.CORR_TIPO_DIP
LEFT OUTER JOIN [CLASS_UEES].dbo.CODIGOS C ON A.CORR_ACTIVIDAD_ECONOMICA=C.CODCOD COLLATE DATABASE_DEFAULT AND RTRIM(LTRIM(C.CODREL))='ACT_EMP' --AND LEN(C.CODCOD)<6
LEFT OUTER JOIN [CLASS_UEES].dbo.PAISES D ON RTRIM(LTRIM(ISNULL(A.CODIGO_PAIS,'SLV'))) COLLATE DATABASE_DEFAULT = RTRIM(LTRIM(D.PAICOD)) COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN [CLASS_UEES].dbo.PROVINCIAS E ON ISNULL(RTRIM(LTRIM(A.CODIGO_DEPTO)),AA.CLIPRO) COLLATE DATABASE_DEFAULT = RTRIM(LTRIM(E.PROCOD)) AND E.PROREG='P' COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN [CLASS_UEES].dbo.PROVINCIAS F ON ISNULL(RTRIM(LTRIM(A.CODIGO_DEPTO)),AA.CLIPRO) COLLATE DATABASE_DEFAULT = RTRIM(LTRIM(F.PROREL)) COLLATE DATABASE_DEFAULT AND ISNULL(RTRIM(LTRIM(A.CODIGO_MUNICIPIO)),AA.CLICAN) COLLATE DATABASE_DEFAULT = RTRIM(LTRIM(F.PROCOD)) COLLATE DATABASE_DEFAULT AND F.PROREG='C'
LEFT OUTER JOIN [e-AdminFE].dbo.GEN_FORMA_PAGO G ON ISNULL(A.CORR_FORMA_PAGO,4) = G.CORR_FORMA_PAGO
LEFT OUTER JOIN COM_BANCO H ON A.CORR_BANCO = H.CORR_BANCO
LEFT OUTER JOIN COM_CONDICION_PAGO I ON A.CORR_CONDICION_PAGO = I.CORR_CONDICION_PAGO
LEFT OUTER JOIN [CLASS_UEES].dbo.CODIGOS J ON AA.CLITCB=J.CODCOD AND J.CODREL='ACT_TCB'
LEFT outer JOIN [E-ADMINFE].dbo.CLA_ACTIVIDAD_ECONOMICA k on a.CORR_ACTIVIDAD_ECONOMICA=k.CODIGO_ACTIVIDAD_ECONOMICA COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN PEM_TRABAJADORES_OTROS_DATOS M ON REPLACE(M.TRBCUN, '-', '') COLLATE SQL_Latin1_General_CP1_CI_AS = REPLACE(CLICUN, '-', '') COLLATE SQL_Latin1_General_CP1_CI_AS
WHERE AA.CLITIP IN ('P')
GO