SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[V_COM_DOCUMENTO_TOTAL]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_DOCUMENTO
      ,A.CORR_RUBRO
      ,D.ES_IMPUESTO 
      ,D.CLASE_RUBRO
      ,D.NOMBRE_RUBRO        
      ,A.MONTO_RUBRO*D.SUMA_RESTA MONTO_RUBRO
      ,A.PERMITE_EDITAR
      ,ISNULL(A.IMPUESTO_INCLUIDO,0)IMPUESTO_INCLUIDO
      ,D.TIPO_APLICACION 
      ,D.POR_IMPUESTO 
      ,A.ORDEN_TOTAL      
  FROM COM_DOCUMENTO_TOTAL A
  INNER JOIN GEN_RUBRO D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.CORR_RUBRO=D.CORR_RUBRO
GO
