SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_GEN_GERENCIA]
AS
SELECT G.CORR_EMPRESA
      ,G.CORR_GERENCIA
      ,G.NOMBRE_GERENCIA
      ,G.CODIGO_GERENCIA
      ,G.CORR_DIVISION
      ,D.NOMBRE_DIVISION
      ,D.CODIGO_DIVISION
      ,G.USUARIO_CREA
      ,G.ESTACION_CREA
      ,G.FECHA_CREA
      ,G.USUARIO_ACTU
      ,G.ESTACION_ACTU
      ,G.FECHA_ACTU
  FROM GEN_GERENCIA G
  LEFT JOIN GEN_DIVISION D
    ON G.CORR_EMPRESA = D.CORR_EMPRESA
   AND G.CORR_DIVISION = D.CORR_DIVISION
GO
