
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_CATALOGO_PRESUPUESTO]
AS
SELECT A.CORR_EMPRESA
      ,A.CUENTA_CONTABLE
      ,B.NOMBRE_CUENTA
      ,A.ANIO_PERIODO
      ,A.MONTO_PRESUPUESTO_1
      ,A.MONTO_PRESUPUESTO_2
      ,A.MONTO_PRESUPUESTO_3
      ,A.MONTO_PRESUPUESTO_4
      ,A.MONTO_PRESUPUESTO_5
      ,A.MONTO_PRESUPUESTO_6
      ,A.MONTO_PRESUPUESTO_7
      ,A.MONTO_PRESUPUESTO_8
      ,A.MONTO_PRESUPUESTO_9
      ,A.MONTO_PRESUPUESTO_10
      ,A.MONTO_PRESUPUESTO_11
      ,A.MONTO_PRESUPUESTO_12
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
      ,B.CUENTA_MAYOR
FROM CON_CATALOGO_PRESUPUESTO A
INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
GO
