SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DESCRIPTOR_IMPACTO_ECONOMICO]
AS
SELECT CORR_EMPRESA
      ,CORR_IMPACTO_ECONOMICO
      ,DESCRIPCION
      ,ESTADO_IMPACTO_ECONOMICO
      ,USUARIO_CREA
      ,FECHA_CREA
      ,ESTACION_CREA
      ,USUARIO_ACTU
      ,FECHA_ACTU
      ,ESTACION_ACTU
  FROM SC_DESCRIPTOR_IMPACTO_ECONOMICO

GO
