SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_COMPETENCIAS_TECNICAS]
AS
SELECT
  A.[CORR_EMPRESA],
  A.[CORR_COMPETENCIAS_TECNICAS],
  A.[CORR_COMPETENCIAS_TECNICAS_PADRE],
  A.[CODIGO_COMPETENCIAS_TECNICAS],
  A.[NOMBRE_COMPETENCIAS_TECNICAS],
  A.[DESCRIPCION],
  A.[NIVEL],
  A.[ESTADO_COMPETENCIAS_TECNICAS],
  A.[USUARIO_CREA],
  A.[FECHA_CREA],
  A.[ESTACION_CREA],
  A.[USUARIO_ACTU],
  A.[FECHA_ACTU],
  A.[ESTACION_ACTU],
  P.[CODIGO_COMPETENCIAS_TECNICAS] AS [CODIGO_PADRE],
  P.[NOMBRE_COMPETENCIAS_TECNICAS] AS [NOMBRE_PADRE],
  P.[DESCRIPCION] AS [DESCRIPCION_PADRE],
  P.[NIVEL] AS [NIVEL_PADRE]
FROM [dbo].[SC_COMPETENCIAS_TECNICAS] A
LEFT JOIN [dbo].[SC_COMPETENCIAS_TECNICAS] P
  ON A.[CORR_EMPRESA] = P.[CORR_EMPRESA]
 AND A.[CORR_COMPETENCIAS_TECNICAS_PADRE] = P.[CORR_COMPETENCIAS_TECNICAS]
GO
