SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[V_CON_PERIODO_CONTABLE]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,CASE A.MES_PERIODO
      WHEN 1 THEN 'Enero'
      WHEN 2 THEN 'Febrero'
      WHEN 3 THEN 'Marzo'
      WHEN 4 THEN 'Abril'
      WHEN 5 THEN 'Mayo'
      WHEN 6 THEN 'Junio'
      WHEN 7 THEN 'Julio'
      WHEN 8 THEN 'Agosto'
      WHEN 9 THEN 'Septiembre'
      WHEN 10 THEN 'Octubre'
      WHEN 11 THEN 'Noviembre'
      WHEN 12 THEN 'Diciembre'
      ELSE '' END NOMBRE_MES_PERIODO
      ,ISNULL(A.ESTADO_PERIODO_CON,'AB') ESTADO_PERIODO_CON
      ,CASE ISNULL(A.ESTADO_PERIODO_CON,'AB')
      WHEN 'AB' THEN 'Abierto'
      WHEN 'PC' THEN 'Proceso de Cierre'
      WHEN 'CE' THEN 'Cerrado'
      ELSE '' END NOMBRE_ESTADO_PERIODO_CON
      ,ISNULL(A.ESTADO_PERIODO_BAN,'AB') ESTADO_PERIODO_BAN
      ,CASE ISNULL(A.ESTADO_PERIODO_BAN,'AB')
      WHEN 'AB' THEN 'Abierto'
      WHEN 'PC' THEN 'Proceso de Cierre'
      WHEN 'CE' THEN 'Cerrado'
      ELSE '' END NOMBRE_ESTADO_PERIODO_BAN
      ,ISNULL(A.ESTADO_PERIODO_VEN,'AB') ESTADO_PERIODO_VEN
      ,CASE ISNULL(A.ESTADO_PERIODO_VEN,'AB')
      WHEN 'AB' THEN 'Abierto'
      WHEN 'PC' THEN 'Proceso de Cierre'
      WHEN 'CE' THEN 'Cerrado'
      ELSE '' END NOMBRE_ESTADO_PERIODO_VEN
      ,ISNULL(A.ESTADO_PERIODO_ACT,'AB') ESTADO_PERIODO_ACT
      ,CASE ISNULL(A.ESTADO_PERIODO_ACT,'AB')
      WHEN 'AB' THEN 'Abierto'
      WHEN 'PC' THEN 'Proceso de Cierre'
      WHEN 'CE' THEN 'Cerrado'
      ELSE '' END NOMBRE_ESTADO_PERIODO_ACT
      ,ISNULL(A.ESTADO_PERIODO_INV,'AB') ESTADO_PERIODO_INV
      ,CASE ISNULL(A.ESTADO_PERIODO_INV,'AB')
      WHEN 'AB' THEN 'Abierto'
      WHEN 'PC' THEN 'Proceso de Cierre'
      WHEN 'CE' THEN 'Cerrado'
      ELSE '' END NOMBRE_ESTADO_PERIODO_INV
      ,ISNULL(A.ESTADO_PERIODO_PLA,'AB') ESTADO_PERIODO_PLA
      ,CASE ISNULL(A.ESTADO_PERIODO_PLA,'AB')
      WHEN 'AB' THEN 'Abierto'
      WHEN 'PC' THEN 'Proceso de Cierre'
      WHEN 'CE' THEN 'Cerrado'
      ELSE '' END NOMBRE_ESTADO_PERIODO_PLA
      ,ISNULL(A.ESTADO_PERIODO_COM,'AB') ESTADO_PERIODO_COM
      ,CASE ISNULL(A.ESTADO_PERIODO_COM,'AB')
      WHEN 'AB' THEN 'Abierto'
      WHEN 'PC' THEN 'Proceso de Cierre'
      WHEN 'CE' THEN 'Cerrado'
      ELSE '' END NOMBRE_ESTADO_PERIODO_COM
      ,A.FECHA_CIERRE_CON
      ,A.FECHA_CIERRE_BAN
      ,A.FECHA_CIERRE_VEN
      ,A.FECHA_CIERRE_ACT
      ,A.FECHA_CIERRE_INV
      ,A.FECHA_CIERRE_PLA
      ,A.FECHA_CIERRE_COM
  FROM CON_PERIODO_CONTABLE A
GO
