-- Qué hace: vista de mantenimiento del catálogo GEN_ACTIVIDAD_ECONOMICA.
-- Cómo lo hace: proyecta la tabla con ISNULL en ACTIVO_ACTIVIDAD_ECONOMICA (1 por defecto).
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_ACTIVIDAD_ECONOMICA]
AS
SELECT
	A.CORR_ACTIVIDAD_ECONOMICA,
	A.CODIGO_ACTIVIDAD_ECONOMICA,
	A.NOMBRE_ACTIVIDAD_ECONOMICA,
	ISNULL(A.ACTIVO_ACTIVIDAD_ECONOMICA, 1) AS ACTIVO_ACTIVIDAD_ECONOMICA,
	A.USUARIO_CREA,
	A.ESTACION_CREA,
	A.FECHA_CREA,
	A.USUARIO_ACTU,
	A.ESTACION_ACTU,
	A.FECHA_ACTU
FROM dbo.GEN_ACTIVIDAD_ECONOMICA AS A;
GO
