-- Qué hace: vista de referencias personales (tab Referencias personales de gen-empleado).
-- Cómo lo hace: proyecta GEN_PERSONA_REFERENCIA_PERSONAL para lectura GetAll.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_REFERENCIA_PERSONAL]
AS
SELECT
	R.CORR_EMPRESA,
	R.CORR_PERSONA,
	R.CORR_REFERENCIA_PERSONAL,
	R.NOMBRE_COMPLETO,
	R.DIRECCION,
	R.TELEFONO,
	R.USUARIO_CREA,
	R.ESTACION_CREA,
	R.FECHA_CREA,
	R.USUARIO_ACTU,
	R.ESTACION_ACTU,
	R.FECHA_ACTU
FROM dbo.GEN_PERSONA_REFERENCIA_PERSONAL AS R;
GO
