SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_TIPO_VACANTE]
AS
SELECT CORR_EMPRESA
      ,CORR_TIPO_VACANTE
      ,NOMBRE_TIPO_VACANTE
      ,USUARIO_CREA
      ,ESTACION_CREA
      ,FECHA_CREA
      ,USUARIO_ACTU
      ,ESTACION_ACTU
      ,FECHA_ACTU
  FROM SC_TIPO_VACANTE

GO