SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_BAN_CONCILIA_BANCARIA_DETA]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CUENTA_BANCO
      ,A.CORR_CONCILIACION
      ,A.CORR_CONCILIACION_DETA
      ,A.FECHA_MOVIMIENTO
      ,A.CORR_TIPO_MOVIMIENTO
      ,ISNULL(B.NOMBRE_TIPO_MOVIMIENTO,'') NOMBRE_TIPO_MOVIMIENTO
      ,A.NUMERO_REFERENCIA_BANCO
      ,A.MONTO_CARGO
      ,A.MONTO_ABONO
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,A.CORR_PARTIDA
      ,ISNULL(D.NUMERO_DOCUMENTO,'') NUMERO_DOCUMENTO
      ,ISNULL(D.NOMBRE_CORTO_CLASE,'') NOMBRE_CORTO_CLASE
      ,A.CORR_PARTIDA_DETA
      ,ISNULL(C.NOMBRE_TRAN,'') NOMBRE_TRAN
	  ,ISNULL(C.MONTO_CARGO,0) MONTO_CARGO_CONTA
	  ,ISNULL(C.MONTO_ABONO,0) MONTO_ABONO_CONTA
	  ,ISNULL(A.CODIGO_TRANSACCION,'')CODIGO_TRANSACCION
	  ,ISNULL(A.DESCRIPCION_TRANSACCION,'')DESCRIPCION_TRANSACCION
  FROM BAN_CONCILIA_BANCARIA_DETA A
  LEFT OUTER JOIN BAN_TIPO_MOVI_BANCARIO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO=B.CORR_TIPO_MOVIMIENTO 
  LEFT OUTER JOIN CON_PARTIDA_DETA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.ANIO_PERIODO=C.ANIO_PERIODO AND A.MES_PERIODO=C.MES_PERIODO AND A.CORR_CLASE_PARTIDA=C.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=C.CORR_PARTIDA AND A.CORR_PARTIDA_DETA=C.CORR_PARTIDA_DETA 
  LEFT OUTER JOIN V_CON_PARTIDA D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.ANIO_PERIODO=D.ANIO_PERIODO AND A.MES_PERIODO=D.MES_PERIODO AND A.CORR_CLASE_PARTIDA=D.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=D.CORR_PARTIDA
GO

