SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_CENTRO_COSTO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CENTRO_COSTO
      ,A.NOMBRE_CENTRO
      ,ISNULL(A.CUENTA_CONTABLE,'') CUENTA_CONTABLE
      ,ISNULL(B.CANTIDAD_MAXIMA_EMPLEADOS,0) CANTIDAD_MAXIMA_EMPLEADOS
      ,ISNULL(A.CODIGO_CENTRO_COSTO,'') CODIGO_CENTRO_COSTO
      ,ISNULL(A.CORR_TIPO_CENTRO_COSTO,0) CORR_TIPO_CENTRO_COSTO
      ,ISNULL(C.NOMBRE_TIPO_CENTRO_COSTO,'') NOMBRE_TIPO_CENTRO_COSTO
      ,ISNULL(A.ESTADO_CENTRO_COSTO,'') ESTADO_CENTRO_COSTO
      ,CASE A.ESTADO_CENTRO_COSTO
		WHEN 'AC' THEN 'Activo'
		ELSE '' END NOMBRE_ESTADO_CENTRO_COSTO
	  ,CASE WHEN A.CORR_CENTRO_COSTO=0 THEN '' ELSE REPLICATE('0',CASE WHEN LEN(A.CORR_CENTRO_COSTO)<=4 THEN 4-LEN(A.CORR_CENTRO_COSTO) ELSE 0 END)+CONVERT(VARCHAR,A.CORR_CENTRO_COSTO) END CORR_CENTRO_COSTO_REPLICADO
	  ,ISNULL(A.CORR_TIPO_OPERACION,0)CORR_TIPO_OPERACION
	  ,D.NOMBRE_TIPO_OPERACION
	  ,ISNULL(A.CORR_TIPO_GASTO,0)CORR_TIPO_GASTO
	  ,E.NOMBRE_TIPO_GASTO
	  ,E.NOMBRE_CLASE_TIPO_GASTO
	  ,E.CODIGO_ISR
	  ,ISNULL(A.CORR_TIPO_GASTO_ISR,0)CORR_TIPO_GASTO_ISR
	  ,F.NOMBRE_TIPO_GASTO_ISR
FROM CON_CENTRO_COSTO A
LEFT OUTER JOIN V_CON_CENTRO_COSTO_CANTIDAD_MAX_EMPLEADO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CENTRO_COSTO=B.CORR_CENTRO_COSTO
LEFT OUTER JOIN CON_TIPO_CENTRO_COSTO C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_TIPO_CENTRO_COSTO=C.CORR_TIPO_CENTRO_COSTO
LEFT OUTER JOIN GEN_TIPO_OPERACION D ON A.CORR_EMPRESA = D.CORR_EMPRESA AND A.CORR_TIPO_OPERACION = D.CORR_TIPO_OPERACION
LEFT OUTER JOIN V_GEN_TIPO_GASTO E ON A.CORR_EMPRESA = E.CORR_EMPRESA AND A.CORR_TIPO_GASTO = E.CORR_TIPO_GASTO
LEFT OUTER JOIN GEN_TIPO_GASTO_ISR F ON A.CORR_EMPRESA = F.CORR_EMPRESA AND A.CORR_TIPO_GASTO_ISR = F.CORR_TIPO_GASTO_ISR
GO
