-- Qué hace: vista de mantenimiento del catálogo PLA_AFP.
-- Cómo lo hace: proyecta Activo (ISNULL 1) + auditoríaía para browse/CRUD.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_PLA_AFP]
AS
SELECT
	A.CORR_AFP,
	A.NOMBRE_AFP,
	A.NOMBRE_CORTO_AFP,
	A.CODIGO_SGVPP,
	ISNULL(A.INCLUYE_SEPP, 0) AS INCLUYE_SEPP,
	ISNULL(A.ACTIVO_AFP, 1) AS ACTIVO_AFP,
	A.USUARIO_CREA,
	A.ESTACION_CREA,
	A.FECHA_CREA,
	A.USUARIO_ACTU,
	A.ESTACION_ACTU,
	A.FECHA_ACTU
FROM dbo.PLA_AFP AS A;
GO
