SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_MUNICIPIO]
AS
SELECT M.CORR_PAIS
      ,M.CORR_DEPTO
      ,M.CORR_MUNICIPIO
      ,M.NOMBRE_MUNICIPIO
      ,M.CODIGO_MUNICIPIO
      ,M.USUARIO_CREA
      ,M.ESTACION_CREA
      ,M.FECHA_CREA
      ,M.USUARIO_ACTU
      ,M.ESTACION_ACTU
      ,M.FECHA_ACTU
      ,D.NOMBRE_DEPTO
      ,P.NOMBRE_PAIS
  FROM GEN_MUNICIPIO M
  LEFT JOIN GEN_DEPTO D
    ON D.CORR_PAIS = M.CORR_PAIS
   AND D.CORR_DEPTO = M.CORR_DEPTO
  LEFT JOIN GEN_PAIS P
    ON P.CORR_PAIS = M.CORR_PAIS
GO
