SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_SC_PERFIL_PUESTO_EDUCACION]
AS
SELECT
  E.[CORR_EMPRESA],
  E.[CORR_DESCRIPTOR_PUESTO],
  E.[CORR_PERFIL_PUESTO],
  E.[CORR_EDUCACION],
  E.[REQUISITO],
  E.[ESPECIFICACIONES],
  E.[TIPO_REQUERIDO],
  E.[USUARIO_CREA],
  E.[ESTACION_CREA],
  E.[FECHA_CREA],
  E.[USUARIO_ACTU],
  E.[ESTACION_ACTU],
  E.[FECHA_ACTU]
FROM [dbo].[SC_PERFIL_PUESTO_EDUCACION] E
GO
