SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_PERFIL_PUESTO]
AS
SELECT
  P.[CORR_EMPRESA],
  P.[CORR_DESCRIPTOR_PUESTO],
  P.[CORR_PERFIL_PUESTO],
  P.[EDAD_MINIMA],
  P.[EDAD_MAXIMA],
  P.[SEXO],
  P.[ESTADO_FAMILIAR],
  P.[CORR_DISPONIBILIDAD_HORARIO],
  D.[NOMBRE_DISPONIBILIDAD_HORARIO],
  P.[CORR_TIPO_MODALIDAD],
  M.[MODALIDAD_NOMBRE],
  P.[LICENCIA],
  P.[USUARIO_CREA],
  P.[ESTACION_CREA],
  P.[FECHA_CREA],
  P.[USUARIO_ACTU],
  P.[ESTACION_ACTU],
  P.[FECHA_ACTU]
FROM [dbo].[SC_PERFIL_PUESTO] P
LEFT JOIN [dbo].[SC_DISPONIBILIDAD_HORARIO] D
  ON P.[CORR_EMPRESA] = D.[CORR_EMPRESA]
 AND P.[CORR_DISPONIBILIDAD_HORARIO] = D.[CORR_DISPONIBILIDAD_HORARIO]
LEFT JOIN [dbo].[SC_TIPO_MODALIDAD] M
  ON P.[CORR_EMPRESA] = M.[CORR_EMPRESA]
 AND P.[CORR_TIPO_MODALIDAD] = M.[CORR_TIPO_MODALIDAD]
GO
