CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_CANDIDATO
AS
SELECT
    E.CORR_EMPRESA,
    E.CORR_EXPEDIENTE_CANDIDATO,
    E.CORR_PERSONA_DATOS,
    E.FECHA_GENERACION,
    E.ACTIVO,
    P.DUI AS DUI_PERSONA,
    LTRIM(RTRIM(
        CONCAT(
            ISNULL(P.NOMBRE1, ''),
            CASE WHEN NULLIF(LTRIM(RTRIM(P.NOMBRE2)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.NOMBRE2)) END,
            CASE WHEN NULLIF(LTRIM(RTRIM(P.APELLIDO1)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.APELLIDO1)) END,
            CASE WHEN NULLIF(LTRIM(RTRIM(P.APELLIDO2)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.APELLIDO2)) END
        )
    )) AS NOMBRE_PERSONA,
    E.USUARIO_CREA,
    E.ESTACION_CREA,
    E.FECHA_CREA,
    E.USUARIO_ACTU,
    E.ESTACION_ACTU,
    E.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_CANDIDATO AS E
LEFT JOIN dbo.SC_PERSONA_DATOS AS P
    ON P.CORR_EMPRESA = E.CORR_EMPRESA
   AND P.CORR_PERSONA_DATOS = E.CORR_PERSONA_DATOS;
GO
