SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_MOVIMIENTO_CONTA_ODS]
AS
SELECT A.NOMBRE_EMPRESA [Empresa]
      ,A.NOMBRE_CLASE_PARTIDA [Transaccion]
      ,A.CORR_PARTIDA [Partida No.]
      ,CASE WHEN ISNULL(A.NUMERO_DOCUMENTO,'0')='0' THEN CONVERT(VARCHAR,A.CORR_PARTIDA) ELSE A.NUMERO_DOCUMENTO END [Documento]
      ,CONVERT(DATETIME,A.FECHA_PARTIDA) [Fecha]
      ,A.BENEFICIARIO [Anombre]
      ,A.NOMBRE_TRAN [Descripcion]
      ,A.CUENTA_CONTABLE [Cuenta]
      ,A.NOMBRE_CUENTA [NombreCta]
      ,A.CUENTA_CONTABLE_ODS [Cuenta Century]
      ,A.NOMBRE_CUENTA_CONTABLE_ODS [NombreCtaCentury]
      ,A.AUXILIAR [Auxiliar]
      ,CASE WHEN ISNULL(A.MONTO_ABONO,0)>0 THEN 'A' ELSE 'C' END [C / A]
      ,ISNULL(A.MONTO_CARGO,0)+ISNULL(A.MONTO_ABONO,0) [Valor]
      ,A.NOMBRE_TIPO_CHEQUE [Tipo Cheque]
      ,'SALVA' rol
FROM V_CON_MOVIMIENTO_CONTA A
GO
