CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_ENTREVISTA,
    X.CORR_ENTREVISTA_DOCUMENTO,
    X.FECHA_CARGA,
    X.NOMBRE_ARCHIVO,
    X.RUTA_ARCHIVO,
    X.NOTAS,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO AS X;
GO
