SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: empleados disponibles para asignar a actores de flujo (por unidad).
-- Cómo lo hace: empleado activo con login en GEN_PERSONA_USUARIO + puesto/unidad;
--               CROSS JOIN actores que requieren unidad y aún no tienen asignación.
CREATE OR ALTER VIEW [dbo].[V_GEN_EMPLEADO_DISPONIBLE_ACTOR]
AS
SELECT
	GE.CORR_EMPLEADO,
	ISNULL(PN.NOMBRE_COMPLETO, N'') AS NOMBRE_EMPLEADO,
	PU.LOGIN_SISTEMA AS LOGIN_SISTEMA_WEB,
	EP.CORR_PUESTO,
	PP.NOMBRE_PUESTO,
	U.CORR_UNIDAD AS CORR_UNIDAD_EMPLEADO,
	U.NOMBRE_UNIDAD AS UNIDAD_EMPLEADO,
	U.CODIGO_UNIDAD AS CODIGO_UNIDAD_EMPLEADO,
	A.CORR_ACTOR,
	A.NOMBRE_ACTOR
FROM dbo.GEN_EMPLEADO GE
INNER JOIN dbo.GEN_EMPLEADO_PUESTO EP
	ON EP.CORR_EMPLEADO = GE.CORR_EMPLEADO
   AND EP.CORR_EMPRESA = GE.CORR_EMPRESA
INNER JOIN dbo.PLA_PUESTO PP
	ON PP.CORR_PUESTO = EP.CORR_PUESTO
   AND PP.CORR_EMPRESA = EP.CORR_EMPRESA
INNER JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES U
	ON U.CORR_UNIDAD = EP.CORR_UNIDAD
   AND U.CORR_EMPRESA = EP.CORR_EMPRESA
INNER JOIN dbo.GEN_PERSONA_USUARIO PU
	ON PU.CORR_PERSONA = GE.CORR_PERSONA
LEFT JOIN dbo.GEN_PERSONA_NATURAL PN
	ON PN.CORR_PERSONA = GE.CORR_PERSONA
CROSS JOIN dbo.SEG_FLUJO_ACTOR A
WHERE GE.CORR_EMPRESA = 1
  AND ISNULL(GE.ACTIVO_EMPLEADO, 0) = 1
  AND A.CORR_EMPRESA = 1
  AND A.ACTIVO = 1
  AND A.REQUIERE_UNIDAD = 1
  AND NOT EXISTS
  (
	SELECT 1
	FROM dbo.SEG_FLUJO_ACTOR_ASIGNACION ASIG
	WHERE ASIG.LOGIN_SISTEMA = PU.LOGIN_SISTEMA
	  AND ASIG.CORR_EMPRESA = GE.CORR_EMPRESA
	  AND ASIG.CORR_ACTOR = A.CORR_ACTOR
	  AND ASIG.CORR_UNIDAD = EP.CORR_UNIDAD
	  AND ASIG.ACTIVO = 1
  );
GO
