SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_SOLI_COTIZACION_DOC]
AS
SELECT A.CORR_EMPRESA
     ,A.ANIO_PERIODO
     ,A.CORR_SOLI_COTIZACION
     ,A.CORR_DOCUMENTO
	 ,B.NOMBRE_DOCUMENTO
	 ,B.DESCRIPCION_DOCUMENTO
	 ,B.CORR_TIPO_DOCUMENTO
	 ,C.NOMBRE_TIPO_DOCUMENTO
	 ,B.RUTA_DOCUMENTO 
	 ,B.NOMBRE_ARCHIVO
FROM COM_SOLI_COTIZACION_DOC A
INNER JOIN COM_DOCUMENTO_FISICO B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_DOCUMENTO = B.CORR_DOCUMENTO
INNER JOIN COM_TIPO_DOC_FISICO C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.CORR_TIPO_DOCUMENTO = C.CORR_TIPO_DOCUMENTO
GO
