CREATE OR ALTER VIEW dbo.V_SC_TIPO_ENTREVISTA
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_TIPO_ENTREVISTA,
    X.TIPO_ENTREVISTA,
    X.DESCRIPCION_ENTREVISTA,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_TIPO_ENTREVISTA AS X;
GO
