SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_SOLI_COTIZACION_IMPR]
AS
SELECT A.CORR_EMPRESA
	,E.NOMBRE_EMPRESA
	,A.ANIO_PERIODO
	,A.CORR_SOLI_COTIZACION
	,CONVERT(VARCHAR,A.ANIO_PERIODO)+'-'+CONVERT(VARCHAR,A.CORR_SOLI_COTIZACION) NUMERO_SOLI_COTIZACION
	,A.FECHA_SOLI_COTIZACION
	,A.FECHA_LIMITE_COTIZACION
	,A.CODIGO_DEPTO
	,B.CODDSC NOMBRE_DEPARTAMENTO
	,A.ANIO_PERIODO_SOLI_COMPRA
	,A.CORR_SOLI_COMPRA
	,A.USUARIO_SOLI
	,A.OBSERVACIONES
	,A.ESTADO_SOLI_COTIZACION
	,CASE A.ESTADO_SOLI_COTIZACION 
	WHEN 'DI' THEN 'DIGITADO'
	WHEN 'SO' THEN 'SOLICITADO'
	WHEN 'AP' THEN 'APLICADO'
	ELSE '' END NOMBRE_ESTADO_SOLI_COTIZACION
	,C.CORR_SOLI_COTIZACION_DETA
	,C.CODIGO_ITEM
	,D.INVDSC NOMBRE_ITEM 
	,C.CANTIDAD
	,C.CORR_UNIDAD_MEDIDA
	,CONVERT(VARCHAR(50),'')NOMBRE_UNIDAD_MEDIDA
	,C.OBSERVACIONES OBSERVACIONES_DETA
	,C.ESTADO_SOLI_COTIZACION ESTADO_SOLI_COTIZACION_DETA
	,CASE C.ESTADO_SOLI_COTIZACION 
	WHEN 'DI' THEN 'DIGITADO'
	WHEN 'SO' THEN 'SOLICITADO'
	WHEN 'AP' THEN 'APLICADO'
	ELSE '' END NOMBRE_ESTADO_SOLI_COTIZACION_DETA
	,CONVERT(VARCHAR(55),'') PERIODO
	,E.LOGO_1 LOGO1
	,E.LOGO_2 LOGO2
	,CONVERT(VARCHAR(255),'SOLICITUD DE COTIZACIÓN') TITULO_REPORTE
	,CONVERT(VARCHAR(255),'e-Admin FE Ver. 1.0') NOMBRE_SISTEMA
	,CONVERT(DATETIME,GETDATE()) FECHA_IMPRESION
FROM COM_SOLI_COTIZACION A
INNER JOIN [CLASS_UEES].dbo.CODIGOS B ON B.CODCOD = A.CODIGO_DEPTO COLLATE Modern_Spanish_CI_AS AND B.CODREL = 'DPTOS'
INNER JOIN COM_SOLI_COTIZACION_DETA C ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.ANIO_PERIODO = C.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION = C.CORR_SOLI_COTIZACION
INNER JOIN [CLASS_UEES].dbo.INVENTARIOS D ON D.INVCOD = C.CODIGO_ITEM COLLATE Modern_Spanish_CI_AS AND D.INVREG = 'E' AND D.INVSUC='001'
INNER JOIN GEN_EMPRESA E ON A.CORR_EMPRESA = E.CORR_EMPRESA
GO
