SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_RUBRO_NIVEL_MAX]
AS
SELECT A.CORR_EMPRESA
,A.CODIGO_RUBRO
,MAX(A.NIVEL) NIVEL_MAX
FROM CON_RUBRO_NIVEL A
GROUP BY A.CORR_EMPRESA
,A.CODIGO_RUBRO
GO
