SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_PROVEEDOR_DISPONIBLE]
AS
SELECT CONVERT(BIT,0) SELECCION
,A.CLIIDU AS CORR_PROVEEDOR
,A.CLICUN AS CODIGO_PROVEEDOR
,A.CLINAM AS NOMBRE_PROVEEDOR
,ISNULL(B.CORR_FORMA_PAGO,4) CORR_FORMA_PAGO
,ISNULL(B.CORR_CONDICION_PAGO,0)CORR_CONDICION_PAGO
,''DETALLE_FORMA_PAGO
FROM [CLASS_UEES].dbo.CLIENTES A
LEFT OUTER JOIN COM_PROVEEDOR B ON A.CLIIDU=B.CORR_PROVEEDOR
WHERE A.CLITIP='V' 
AND A.CLISTS='A' 
AND A.CLICAT IN('PN-','PE-','PG-','PP-','PM-','PR-')
--AND B.ESTADO_PROVEEDOR_WEB='A'
GO
