SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_BAN_LINEA_TRABAJO_CONCILIACION]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_LINEA
      ,A.NOMBRE_LINEA_TRABAJO
      ,A.AUMENTA_DISMINUYE
      ,CASE A.AUMENTA_DISMINUYE
       WHEN 1  THEN 'Aumenta'
       WHEN -1 THEN 'Disminuye'
       ELSE '' END NOMBRE_AUMENTA_DISMINUYE
      ,ISNULL(A.ESTADO_LINEA, 1) ESTADO_LINEA
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
FROM BAN_LINEA_TRABAJO_CONCILIACION A
GO
