SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_SUM]
AS
SELECT A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
      ,A.CORR_CUADRO_COMPARATIVO
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=1 THEN ISNULL(B.NOMBRE_USUARIO,'') COLLATE DATABASE_DEFAULT ELSE '' END) FIRMA1
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=1 THEN ISNULL(A.NOMBRE_CARGO,'') ELSE '' END) NOMBRE_FIRMA1
	  ,MIN(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=1 THEN A.FECHA_AUTORIZACION ELSE NULL END) FECHA_FIRMA1
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=2 THEN ISNULL(B.NOMBRE_USUARIO,'') COLLATE DATABASE_DEFAULT ELSE '' END) FIRMA2
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=2 THEN ISNULL(A.NOMBRE_CARGO,'') ELSE '' END) NOMBRE_FIRMA2
	  ,MIN(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=2 THEN A.FECHA_AUTORIZACION ELSE NULL END) FECHA_FIRMA2
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=3 THEN ISNULL(B.NOMBRE_USUARIO,'') COLLATE DATABASE_DEFAULT ELSE '' END) FIRMA3
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=3 THEN ISNULL(A.NOMBRE_CARGO,'') ELSE '' END) NOMBRE_FIRMA3
	  ,MIN(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=3 THEN A.FECHA_AUTORIZACION ELSE NULL END) FECHA_FIRMA3
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=4 THEN ISNULL(B.NOMBRE_USUARIO,'') COLLATE DATABASE_DEFAULT ELSE '' END) FIRMA4
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=4 THEN ISNULL(A.NOMBRE_CARGO,'') ELSE '' END) NOMBRE_FIRMA4
	  ,MIN(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=4 THEN A.FECHA_AUTORIZACION ELSE NULL END) FECHA_FIRMA4
FROM COM_CUADRO_COMPARATIVO_AUTORIZACIONES A
INNER JOIN SEG_USUARIO B ON A.LOGIN_SISTEMA = B.LOGIN_SISTEMA
GROUP BY A.CORR_EMPRESA
        ,A.ANIO_PERIODO
        ,A.CORR_CUADRO_COMPARATIVO
UNION ALL
SELECT A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
      ,A.CORR_CUADRO_COMPARATIVO
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=1 THEN ISNULL(B.USRDSC,'') COLLATE DATABASE_DEFAULT ELSE '' END) FIRMA1
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=1 THEN ISNULL(A.NOMBRE_CARGO,'') ELSE '' END) NOMBRE_FIRMA1
	  ,MIN(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=1 THEN A.FECHA_AUTORIZACION ELSE NULL END) FECHA_FIRMA1
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=2 THEN ISNULL(B.USRDSC,'') COLLATE DATABASE_DEFAULT ELSE '' END) FIRMA2
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=2 THEN ISNULL(A.NOMBRE_CARGO,'') ELSE '' END) NOMBRE_FIRMA2
	  ,MIN(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=2 THEN A.FECHA_AUTORIZACION ELSE NULL END) FECHA_FIRMA2
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=3 THEN ISNULL(B.USRDSC,'') COLLATE DATABASE_DEFAULT ELSE '' END) FIRMA3
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=3 THEN ISNULL(A.NOMBRE_CARGO,'') ELSE '' END) NOMBRE_FIRMA3
	  ,MIN(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=3 THEN A.FECHA_AUTORIZACION ELSE NULL END) FECHA_FIRMA3
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=4 THEN ISNULL(B.USRDSC,'') COLLATE DATABASE_DEFAULT ELSE '' END) FIRMA4
	  ,dbo.StrConcat(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=4 THEN ISNULL(A.NOMBRE_CARGO,'') ELSE '' END) NOMBRE_FIRMA4
	  ,MIN(CASE WHEN ISNULL(A.ORDEN_REVISION,0)=4 THEN A.FECHA_AUTORIZACION ELSE NULL END) FECHA_FIRMA4
FROM COM_CUADRO_COMPARATIVO_AUTORIZACIONES A
INNER JOIN [CLASS_UEES].dbo.USUARIOS B ON A.LOGIN_SISTEMA COLLATE DATABASE_DEFAULT = LTRIM(RTRIM(B.USRUID)) COLLATE DATABASE_DEFAULT
GROUP BY A.CORR_EMPRESA
        ,A.ANIO_PERIODO
        ,A.CORR_CUADRO_COMPARATIVO
GO
