SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_PERSONA_FAMILIAR]
AS
SELECT [CORR_EMPRESA], [CORR_PERSONA_DATOS], [CORR_FAMILIAR], [TIPO], [NOMBRE],
       [DOMICILIO], [FECHA_NACIMIENTO], [OCUPACION], [USUARIO_CREA], [ESTACION_CREA],
       [FECHA_CREA], [USUARIO_ACTU], [ESTACION_ACTU], [FECHA_ACTU]
FROM [dbo].[SC_PERSONA_FAMILIAR]
GO
