SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_FORMA_PAGO]
AS
SELECT A.CORR_FORMA_PAGO
,A.NOMBRE_FORMA_PAGO
FROM [e-AdminFE].dbo.GEN_FORMA_PAGO A
WHERE A.CLASE_FORMA_PAGO IN('CHE','TDB')
GO
