SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_BAN_TIPO_MOVI_BANCARIO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_TIPO_MOVIMIENTO
      ,A.NOMBRE_TIPO_MOVIMIENTO
      ,A.NOMBRE_TIPO_CORTO
      ,A.CORR_LINEA
      ,B.NOMBRE_LINEA_TRABAJO
      ,A.CORR_CLASE_PARTIDA
      ,C.NOMBRE_CLASE_PARTIDA
      ,A.USA_CHEQUE_PROPIO
      ,A.SUMA_RESTA
      ,CASE A.SUMA_RESTA
       WHEN 1  THEN 'SUMA'
       WHEN -1 THEN 'RESTA'
       ELSE '' END NOMBRE_SUMA_RESTA
      ,A.CLASE_MOVIMIENTO
      ,CASE A.CLASE_MOVIMIENTO
       WHEN 'CHQ' THEN 'Cheque'
       WHEN 'TTE' THEN 'Transferencia Tercero'
       WHEN 'TPR' THEN 'Transferencia Propio'
       WHEN 'RCA' THEN 'Remesa de Caja'
       WHEN 'RCL' THEN 'Remesa Cliente'
       WHEN 'NCR' THEN 'Nota de Crédito'
       WHEN 'NDE' THEN 'Nota de Debito'
       WHEN 'TIC' THEN 'Transferencia Intercompañía'
       ELSE '' END NOMBRE_CLASE_MOVIMIENTO
      ,ISNULL(A.CUENTA_CONTABLE_GASTO, '') CUENTA_CONTABLE_GASTO
      ,ISNULL(A.NOMBRE_REPORTE, '') NOMBRE_REPORTE
FROM BAN_TIPO_MOVI_BANCARIO A
LEFT OUTER JOIN BAN_LINEA_TRABAJO_CONCILIACION B
  ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_LINEA = B.CORR_LINEA
LEFT OUTER JOIN CON_CLASE_PARTIDA C
  ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CORR_CLASE_PARTIDA = C.CORR_CLASE_PARTIDA
GO
