SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: lectura de salarios del puesto para el tab de PLA_PUESTO.
-- Cómo lo hace: PLA_PUESTO_SALARIO con el nombre de la unidad y del puesto.
CREATE OR ALTER VIEW [dbo].[V_PLA_PUESTO_SALARIO]
AS
SELECT
	S.CORR_EMPRESA,
	S.CORR_PUESTO_SALARIO,
	S.SALARIO_INICIAL,
	S.SALARIO_FINAL,
	S.CORR_UNIDAD,
	U.CODIGO_UNIDAD,
	U.NOMBRE_UNIDAD,
	S.CORR_PUESTO,
	P.CODIGO_PUESTO,
	P.NOMBRE_PUESTO,
	S.ACTIVO_PUESTO_SALARIO,
	S.FECHA_INGRESO,
	S.FECHA_FINALIZACION,
	S.USUARIO_CREA,
	S.ESTACION_CREA,
	S.FECHA_CREA,
	S.USUARIO_ACTU,
	S.ESTACION_ACTU,
	S.FECHA_ACTU
FROM dbo.PLA_PUESTO_SALARIO S
LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES U
	ON U.CORR_EMPRESA = S.CORR_EMPRESA
	AND U.CORR_UNIDAD = S.CORR_UNIDAD
LEFT JOIN dbo.PLA_PUESTO P
	ON P.CORR_EMPRESA = S.CORR_EMPRESA
	AND P.CORR_PUESTO = S.CORR_PUESTO
GO
