SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW dbo.V_CON_CENTRO_COSTO_PRESUPUESTO
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CENTRO_COSTO
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.MONTO_PRESUPUESTO
  FROM CON_CENTRO_COSTO_PRESUPUESTO A
GO
