SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DESCRIPTOR_RIESGO_PUESTO]
AS
SELECT CORR_EMPRESA
      ,CORR_RIESGO_PUESTO
      ,NOMBRE_RIESGO_PUESTO
      ,ESTADO_RIESGO_PUESTO
      ,USUARIO_CREA
      ,ESTACION_CREA
      ,FECHA_CREA
      ,USUARIO_ACTU
      ,ESTACION_ACTU
      ,FECHA_ACTU
  FROM SC_DESCRIPTOR_RIESGO_PUESTO

GO
