SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_COTIZACION_COMENTARIO]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_COTIZACION
      ,A.CORR_COMENTARIO
      ,A.CLASE_COMENTARIO
	  ,CASE A.CLASE_COMENTARIO
	  WHEN 'IN' THEN 'INTERNO'
	  WHEN 'EX' THEN 'EXTERNO'
	  ELSE '' END NOMBRE_CLASE_COMENTARIO
      ,A.COMENTARIO
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
FROM COM_COTIZACION_COMENTARIO A
GO
