SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_RUBRO_NIVEL] 
AS
SELECT A.CORR_EMPRESA
      ,A.CODIGO_RUBRO
      ,B.NOMBRE_RUBRO
      ,A.NIVEL
      ,A.NUMERO_CARACTERES
FROM CON_RUBRO_NIVEL A 
INNER JOIN CON_RUBRO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CODIGO_RUBRO=B.CODIGO_RUBRO
GO
