SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[V_GEN_RUBRO_SUMA] 
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_RUBRO   
      ,A.CORR_SUMA
      ,B.NOMBRE_RUBRO NOMBRE_SUMA
FROM GEN_RUBRO_SUMA A 
INNER JOIN GEN_RUBRO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_SUMA=B.CORR_RUBRO
GO
