-- Qué hace: vista de experiencia laboral de una persona (tab Experiencia de gen-empleado).
-- Cómo lo hace: proyecta GEN_PERSONA_EXPERIENCIA_LABORAL con los campos del tab.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_EXPERIENCIA_LABORAL]
AS
SELECT
	E.CORR_EMPRESA,
	E.CORR_PERSONA,
	E.CORR_EXPERIENCIA_LABORAL,
	E.LUGAR_TRABAJO,
	E.CARGO_DESEMPENADO,
	E.TELEFONO,
	E.JEFE_INMEDIATO,
	E.SALARIO_INICIAL,
	E.SALARIO_FINAL,
	E.FECHA_INICIO,
	E.FECHA_FIN,
	E.PERIODO_INICIAL,
	E.PERIODO_FINAL,
	E.PERIODO,
	E.MOTIVO_SALIDA,
	E.USUARIO_CREA,
	E.ESTACION_CREA,
	E.FECHA_CREA,
	E.USUARIO_ACTU,
	E.ESTACION_ACTU,
	E.FECHA_ACTU
FROM dbo.GEN_PERSONA_EXPERIENCIA_LABORAL AS E;
GO
