SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_DIVISION]
AS
SELECT CORR_EMPRESA
      ,CORR_DIVISION
      ,NOMBRE_DIVISION
      ,CODIGO_DIVISION
      ,USUARIO_CREA
      ,ESTACION_CREA
      ,FECHA_CREA
      ,USUARIO_ACTU
      ,ESTACION_ACTU
      ,FECHA_ACTU
  FROM GEN_DIVISION
GO
