SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_CON_PARTIDA_IMPR]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,A.NOMBRE_CLASE_PARTIDA
      ,A.NOMBRE_CORTO_CLASE
      ,A.CORR_PARTIDA
      ,A.FECHA_PARTIDA
      ,A.NUMERO_DOCUMENTO
      ,A.NOMBRE_PARTIDA
      ,A.ESTADO_PARTIDA
      ,A.NOMBRE_ESTADO_PARTIDA
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
      ,A.CLASE_PARTIDA
      ,A.NOMBRE_CLASE_PARTIDA2
      ,B.CORR_PARTIDA_DETA
      ,B.CUENTA_CONTABLE
      ,B.NOMBRE_CUENTA
      ,B.CORR_CENTRO_COSTO
      ,B.NOMBRE_CENTRO
      ,B.MONTO_CARGO
      ,B.MONTO_ABONO
      ,CASE WHEN ISNULL(C.NUMERO_DOCUMENTO,'')<>'' THEN LTRIM(RTRIM(LTRIM(RTRIM(ISNULL(C.TIPO_DOCUMENTO,'')))+' '+CONVERT(VARCHAR,ISNULL(C.NUMERO_DOCUMENTO,0))))+' ' ELSE '' END+B.NOMBRE_TRAN NOMBRE_TRAN
      --,C.FECHA_DOCUMENTO
      --,C.TIPO_DOCUMENTO
      ,C.NUMERO_DOCUMENTO NUMERO_DOCUMENTO_DETA
      ,B.CORR_AUXILIAR
      ,F.CORR_AUXILIAR_REPLICADO
      ,H.CORR_CENTRO_COSTO_REPLICADO
      ,A.DESCRIPCION_MONEDA
	  ,A.NOMBRE_MONEDA
FROM V_CON_PARTIDA A
INNER JOIN V_CON_PARTIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
LEFT OUTER JOIN V_CON_PARTIDA_DETA_DOC_SUM C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.ANIO_PERIODO=C.ANIO_PERIODO AND B.MES_PERIODO=C.MES_PERIODO AND B.CORR_CLASE_PARTIDA=C.CORR_CLASE_PARTIDA AND B.CORR_PARTIDA=C.CORR_PARTIDA AND B.CORR_PARTIDA_DETA=C.CORR_PARTIDA_DETA
LEFT OUTER JOIN V_CON_CATALOGO_CUENTA_AUXI F ON A.CORR_EMPRESA=F.CORR_EMPRESA AND B.CUENTA_CONTABLE=F.CUENTA_CONTABLE AND B.CORR_AUXILIAR=F.CORR_AUXILIAR
LEFT OUTER JOIN V_CON_CENTRO_COSTO H ON B.CORR_EMPRESA=H.CORR_EMPRESA AND B.CORR_CENTRO_COSTO=H.CORR_CENTRO_COSTO
GO
