-- Qué hace: vista de mantenimiento del catálogo GEN_TIPO_DOCUMENTO_IDENTIDAD.
-- Cómo lo hace: proyecta la tabla + nombres de listas FORMATO_CARACTERES / APLICA_PARA.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_TIPO_DOCUMENTO_IDENTIDAD]
AS
SELECT
	T.CORR_TIPO_DOCUMENTO_IDENTIDAD,
	T.NOMBRE_TIPO_DOCUMENTO_IDENTIDAD,
	T.NOMBRE_CORTO,
	ISNULL(T.ACTIVO_TIPO_DOCUMENTO_IDENTIDAD, 1) AS ACTIVO_TIPO_DOCUMENTO_IDENTIDAD,
	T.NUMERO_CARACTERES,
	ISNULL(T.ACTIVO_CARACTERES, 0) AS ACTIVO_CARACTERES,
	ISNULL(T.FORMATO_CARACTERES, N'') AS FORMATO_CARACTERES,
	CASE UPPER(LTRIM(RTRIM(ISNULL(T.FORMATO_CARACTERES, N''))))
		WHEN N'NUMEROS' THEN N'Solo números'
		WHEN N'LETRAS' THEN N'Solo letras'
		WHEN N'AMBOS' THEN N'Letras y números'
		ELSE ISNULL(T.FORMATO_CARACTERES, N'')
	END AS NOMBRE_FORMATO_CARACTERES,
	ISNULL(T.APLICA_PARA, N'') AS APLICA_PARA,
	CASE UPPER(LTRIM(RTRIM(ISNULL(T.APLICA_PARA, N''))))
		WHEN N'NACIONALES' THEN N'Nacionales'
		WHEN N'EXTRANJEROS' THEN N'Extranjeros'
		WHEN N'AMBOS' THEN N'Ambos'
		ELSE ISNULL(T.APLICA_PARA, N'')
	END AS NOMBRE_APLICA_PARA,
	T.USUARIO_CREA,
	T.ESTACION_CREA,
	T.FECHA_CREA,
	T.USUARIO_ACTU,
	T.ESTACION_ACTU,
	T.FECHA_ACTU
FROM dbo.GEN_TIPO_DOCUMENTO_IDENTIDAD AS T;
GO
