SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_BAN_TIPO_CHEQUE]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_TIPO_CHEQUE
      ,A.NOMBRE_TIPO_CHEQUE
      ,ISNULL(A.CUENTA_CONTABLE, '') CUENTA_CONTABLE
      ,A.CLASE_TIPO_CHEQUE
      ,CASE A.CLASE_TIPO_CHEQUE
       WHEN 'PR' THEN 'Pago Proveedor'
       WHEN 'EM' THEN 'Pago Empleado'
       WHEN 'RC' THEN 'Reintegro de Caja'
       WHEN 'CL' THEN 'Pago Cliente'
       WHEN 'OT' THEN 'Otro'
       WHEN 'PV' THEN 'Provisionado'
       WHEN 'IC' THEN 'Intercompañía'
       ELSE '' END NOMBRE_CLASE_TIPO_CHEQUE
      ,ISNULL(A.CONTABILIZAR_LUEGO_DE_IMPRIMIR, 1) CONTABILIZAR_LUEGO_DE_IMPRIMIR
      ,ISNULL(A.ESTADO_TIPO_CHEQUE, 1) ESTADO_TIPO_CHEQUE
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
FROM BAN_TIPO_CHEQUE A
GO
