SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DESCRIPTOR_PUESTO]
AS
SELECT
  A.[CORR_EMPRESA],
  A.[CORR_DESCRIPTOR_PUESTO],
  A.[CORR_PUESTO],
  A.[CORR_UNIDAD],
  A.[FECHA_EMISION],
  A.[CORR_PUESTO_REPORTA],
  A.[FECHA_REVISION],
  A.[NUM_PERSONAL_CARGO],
  A.[OBJETIVO_PUESTO],
  A.[CORR_IMPACTO_ECONOMICO],
  A.[CORR_INDUCCION],
  A.[RESPONSABLE],
  A.[FORMATO],
  A.[VERSION],
  A.[ESTADO_DESCRIPTOR],
  A.[USUARIO_CREA],
  A.[ESTACION_CREA],
  A.[FECHA_CREA],
  A.[USUARIO_ACTU],
  A.[ESTACION_ACTU],
  A.[FECHA_ACTU],
  P.[NOMBRE_PUESTO]
FROM [dbo].[SC_DESCRIPTOR_PUESTO] A
LEFT JOIN [dbo].[PLA_PUESTO] P
  ON A.[CORR_EMPRESA] = P.[CORR_EMPRESA]
 AND A.[CORR_PUESTO] = P.[CORR_PUESTO]
GO
