SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_INDUCCION]
AS
SELECT CORR_EMPRESA
      ,CORR_INDUCCION
      ,NOMBRE_INDUCCION
      ,SEMANAS_INDUCCION
      ,ESTADO_INDUCCION
      ,USUARIO_CREA
      ,ESTACION_CREA
      ,FECHA_CREA
      ,USUARIO_ACTU
      ,ESTACION_ACTU
      ,FECHA_ACTU
  FROM SC_INDUCCION
GO
