SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
-- =============================================================================
-- Vista: dbo.V_SC_DESCRIPTOR_PUESTO_IMPR
-- Qué hace: forma de datos para impresión Formato corto (descriptor + funciones).
-- Cómo: LEFT JOIN a SC_DESCRIPTOR_PUESTO_FUNCION (CLAVE y SECUNDARIA);
--       1 fila por función; si no hay funciones, 1 fila del descriptor.
--       NOMBRE_FUNCION_NUM antepone el correlativo, reiniciando por TIPO_FUNCION.
-- Uso: SP PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO / Crystal SGUEES-RPT.
-- =============================================================================
CREATE OR ALTER VIEW [dbo].[V_SC_DESCRIPTOR_PUESTO_IMPR]
AS
SELECT
  A.[CORR_EMPRESA],
  A.[CORR_DESCRIPTOR_PUESTO],
  A.[FECHA_EMISION],
  A.[FECHA_REVISION],
  A.[OBJETIVO_PUESTO],
  A.[NUM_PERSONAL_CARGO],
  A.[CORR_PUESTO],
  A.[NOMBRE_PUESTO],
  A.[CORR_UNIDAD],
  A.[NOMBRE_UNIDAD],
  A.[CORR_PUESTO_REPORTA],
  -- CORR_PUESTO_REPORTA guarda CORR_EMPLEADO del jefe (GEN_EMPLEADO).
  E.[NOMBRE_EMPLEADO] AS [NOMBRE_EMPLEADO_REPORTA],
  A.[CORR_IMPACTO_ECONOMICO],
  A.[DESCRIPCION_IMPACTO_ECONOMICO],
  A.[RESPONSABLE],
  A.[FORMATO],
  A.[VERSION],
  A.[CORR_ESTADO],
  A.[NOMBRE_ESTADO],
  A.[USUARIO_CREA],
  A.[ESTACION_CREA],
  A.[FECHA_CREA],
  A.[USUARIO_ACTU],
  A.[ESTACION_ACTU],
  A.[FECHA_ACTU],
  F.[CORR_FUNCION],
  F.[NOMBRE_FUNCION],
  RTRIM(F.[TIPO_FUNCION]) AS [TIPO_FUNCION],
  -- Nombre con correlativo listo para imprimir ("1. Nombre"); reinicia por TIPO_FUNCION.
  -- Se deja NOMBRE_FUNCION sin numerar para los reportes que no lo necesiten.
  CASE
    WHEN F.[CORR_FUNCION] IS NULL THEN NULL
    ELSE CAST(
      ROW_NUMBER() OVER (
        PARTITION BY A.[CORR_EMPRESA], A.[CORR_DESCRIPTOR_PUESTO], RTRIM(F.[TIPO_FUNCION])
        ORDER BY F.[CORR_FUNCION]
      ) AS NVARCHAR(10)) + N'. ' + F.[NOMBRE_FUNCION]
  END AS [NOMBRE_FUNCION_NUM]
FROM [dbo].[SC_DESCRIPTOR_PUESTO] A
LEFT JOIN [dbo].[GEN_EMPLEADO] E
  ON E.[CORR_EMPRESA] = A.[CORR_EMPRESA]
 AND E.[CORR_EMPLEADO] = A.[CORR_PUESTO_REPORTA]
LEFT JOIN [dbo].[SC_DESCRIPTOR_PUESTO_FUNCION] F
  ON F.[CORR_EMPRESA] = A.[CORR_EMPRESA]
 AND F.[CORR_DESCRIPTOR_PUESTO] = A.[CORR_DESCRIPTOR_PUESTO]
 AND RTRIM(F.[TIPO_FUNCION]) IN (N'CLAVE', N'SECUNDARIA')
GO
