SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_SOLI_COTIZACION_SOLI_COMPRA_SUM]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_SOLI_COTIZACION
	  ,SUBSTRING(dbo.StrConcat(DISTINCT CONVERT(VARCHAR,ISNULL(A.ANIO_PERIODO_SOLI_COMPRA,0)) + '-' + CONVERT(VARCHAR,ISNULL(A.CORR_SOLI_COMPRA,0))+','),1,LEN(dbo.StrConcat(DISTINCT CONVERT(VARCHAR,ISNULL(A.ANIO_PERIODO_SOLI_COMPRA,0)) + '-' + CONVERT(VARCHAR,ISNULL(A.CORR_SOLI_COMPRA,0))+','))-1) NUMERO_SOLI_COMPRA
FROM COM_SOLI_COTIZACION_DETA A
GROUP BY A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_SOLI_COTIZACION
GO
