SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: catálogo de empleados para lookups (misma forma que antes para API/SPA).
-- Cómo lo hace: lee GEN_EMPLEADO nuevo + GEN_PERSONA_NATURAL (nombre) + GEN_PERSONA_USUARIO (login)
--               + puesto vigente desde GEN_EMPLEADO_PUESTO. Expone alias legacy
--               (NOMBRE_EMPLEADO, ESTADO_EMPLEADO, LOGIN_SISTEMA_WEB, etc.).
CREATE OR ALTER VIEW [dbo].[V_GEN_EMPLEADO]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_EMPLEADO,
	A.CORR_PERSONA,
	A.CODIGO_EMPLEADO,
	ISNULL(PN.NOMBRE_COMPLETO, N'') AS NOMBRE_EMPLEADO,
	ISNULL(PN.PRIMER_NOMBRE, N'') AS NOMBRE_1,
	ISNULL(PN.SEGUNDO_NOMBRE, N'') AS NOMBRE_2,
	ISNULL(PN.PRIMER_APELLIDO, N'') AS APELLIDO_1,
	ISNULL(PN.SEGUNDO_APELLIDO, N'') AS APELLIDO_2,
	ISNULL(PN.APELLIDO_CASADA, N'') AS APELLIDO_3,
	CAST(N'' AS VARCHAR(25)) AS DUI,
	CAST(N'' AS VARCHAR(25)) AS NIT,
	ISNULL(A.CORREO_INSTITUCIONAL, N'') AS CORREO_ELECTRONICO,
	ISNULL(A.TELEFONO_INSTITUCIONAL, N'') AS TELEFONO_1,
	CAST(0 AS INT) AS CORR_CENTRO_COSTO,
	CAST(0 AS INT) AS CORR_DEPARTAMENTO,
	ISNULL(EP.CORR_PUESTO, 0) AS CORR_PUESTO,
	CAST(CASE WHEN ISNULL(A.ACTIVO_EMPLEADO, 0) = 1 THEN N'1' ELSE N'0' END AS VARCHAR(2)) AS ESTADO_EMPLEADO,
	CASE WHEN ISNULL(A.ACTIVO_EMPLEADO, 0) = 1 THEN N'Activo' ELSE N'Inactivo' END AS NOMBRE_ESTADO_EMPLEADO,
	ISNULL(PU.LOGIN_SISTEMA, N'') AS LOGIN_SISTEMA,
	ISNULL(PU.LOGIN_SISTEMA, N'') AS LOGIN_SISTEMA_WEB,
	A.USUARIO_CREA,
	A.FECHA_CREA,
	A.ESTACION_CREA,
	A.USUARIO_ACTU,
	A.FECHA_ACTU,
	A.ESTACION_ACTU
FROM dbo.GEN_EMPLEADO A
LEFT JOIN dbo.GEN_PERSONA_NATURAL PN
	ON PN.CORR_PERSONA = A.CORR_PERSONA
OUTER APPLY
(
	SELECT TOP (1) U.LOGIN_SISTEMA
	FROM dbo.GEN_PERSONA_USUARIO U
	WHERE U.CORR_PERSONA = A.CORR_PERSONA
	ORDER BY U.LOGIN_SISTEMA
) PU
OUTER APPLY
(
	SELECT TOP (1) P.CORR_PUESTO
	FROM dbo.GEN_EMPLEADO_PUESTO P
	WHERE P.CORR_EMPRESA = A.CORR_EMPRESA
	  AND P.CORR_EMPLEADO = A.CORR_EMPLEADO
	ORDER BY
		P.FECHA_INGRESO DESC,
		P.FECHA_CREA DESC,
		P.CORR_PUESTO DESC
) EP
GO
