SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- View
CREATE VIEW [dbo].[V_CON_PARTIDA_EXCEL]
AS
SELECT A.FECHA_PARTIDA
      ,A.NUMERO_DOCUMENTO
      ,A.NOMBRE_PARTIDA
      ,B.CUENTA_CONTABLE
      ,B.CORR_CENTRO_COSTO
      ,B.NOMBRE_TRAN
      ,B.MONTO_CARGO
      ,B.MONTO_ABONO
FROM CON_PARTIDA A 
INNER JOIN CON_PARTIDA_DETA B ON 1=1
GO
