SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_GEN_TIPO_GASTO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_TIPO_GASTO
      ,A.NOMBRE_TIPO_GASTO
      ,A.ES_SERVICIO
      ,A.ES_INTANGIBLE
  FROM GEN_TIPO_GASTO A
GO
