SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_BAN_CUENTA_BANCARIA]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CUENTA_BANCO
      ,A.NUMERO_CUENTA_BANCO
      ,CASE WHEN LEN(ISNULL(A.NOMBRE_CUENTA, '')) > 0
            THEN A.NOMBRE_CUENTA
            ELSE LTRIM(RTRIM(B.NOMBRE_BANCO + ' ' + ISNULL(A.NUMERO_CUENTA_BANCO, '')))
       END NOMBRE_CUENTA_BANCO
      ,A.CORR_BANCO
      ,B.NOMBRE_BANCO
      ,B.NOMBRE_BANCO_CORTO
      ,A.CUENTA_CONTABLE
      ,A.NOMBRE_REPORTE
      ,A.TIPO_CUENTA_BANCO
      ,CASE A.TIPO_CUENTA_BANCO
       WHEN 'AH' THEN 'Ahorro'
       WHEN 'CO' THEN 'Corriente'
       WHEN 'OT' THEN 'Otro'
       ELSE '' END NOMBRE_TIPO_CUENTA_BANCO
      ,ISNULL(A.CORR_CENTRO_COSTO, 0) CORR_CENTRO_COSTO
      ,ISNULL(C.NOMBRE_CENTRO, '') NOMBRE_CENTRO
      ,A.CORR_MONEDA
      ,ISNULL(P.NOMBRE_MONEDA, '') NOMBRE_MONEDA
      ,ISNULL(A.CODIGO_EMPRESARIAL, '') CODIGO_EMPRESARIAL
      ,ISNULL(A.CODIGO_EMPRESARIAL_PROV, '') CODIGO_EMPRESARIAL_PROV
      ,ISNULL(A.NO_PERMITE_MODIFICAR, 0) NO_PERMITE_MODIFICAR
      ,ISNULL(A.VALIDAR_SALDO, 0) VALIDAR_SALDO
      ,ISNULL(A.PAGA_PLANILLA, 0) PAGA_PLANILLA
      ,ISNULL(A.NOMBRE_CUENTA, '') NOMBRE_CUENTA
      ,E.NOMBRE_EMPRESA
      ,ISNULL(A.NO_PERMITE_CHEQUES, 0) NO_PERMITE_CHEQUES
      ,ISNULL(B.CLASE_BANCO, '') CLASE_BANCO
      ,ISNULL(A.ESTADO_CUENTA, 'AC') ESTADO_CUENTA
      ,CASE ISNULL(A.ESTADO_CUENTA, 'AC')
       WHEN 'AC' THEN 'Activa'
       WHEN 'IN' THEN 'Inactiva'
       ELSE 'Activa' END NOMBRE_ESTADO_CUENTA
      ,ISNULL(A.VALIDA_FECHA, 0) VALIDA_FECHA
      ,ISNULL(A.USA_TRANSACIONES_UNI, 0) USA_TRANSACIONES_UNI
      ,ISNULL(B.CODIGO_TRANSACION_UNI, '') CODIGO_TRANSACION_UNI
      ,ISNULL(A.CLASE_CHEQUE, '') CLASE_CHEQUE
      ,CASE A.CLASE_CHEQUE
       WHEN 'VO' THEN 'Voucher'
       WHEN 'PE' THEN 'Personal'
       ELSE '' END NOMBRE_CLASE_CHEQUE
FROM BAN_CUENTA_BANCARIA A
INNER JOIN GEN_BANCO B
  ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_BANCO = B.CORR_BANCO
LEFT OUTER JOIN CON_CENTRO_COSTO C
  ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CORR_CENTRO_COSTO = C.CORR_CENTRO_COSTO
LEFT OUTER JOIN V_CON_PARAMETRO P
  ON A.CORR_EMPRESA = P.CORR_EMPRESA AND A.CORR_MONEDA = P.CORR_MONEDA
INNER JOIN V_GEN_EMPRESA E
  ON A.CORR_EMPRESA = E.CORR_EMPRESA
GO
