SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_SC_INDUCCION]
AS
SELECT
  [CORR_EMPRESA],
  [CORR_INDUCCION],
  [NOMBRE_INDUCCION],
  [TIEMPO_INDUCCION],
  [UNIDAD_TIEMPO],
  [ESTADO_INDUCCION],
  [USUARIO_CREA],
  [ESTACION_CREA],
  [FECHA_CREA],
  [USUARIO_ACTU],
  [ESTACION_ACTU],
  [FECHA_ACTU]
FROM [dbo].[SC_INDUCCION]
GO
