
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_CON_PARTIDA_CUENTA_MAYOR]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO 
      ,A.FECHA_PARTIDA
      ,CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='CIE' THEN 1 ELSE 0 END) PARTIDA_CIERRE
      ,CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='LIQ' THEN 1 ELSE 0 END) PARTIDA_LIQUIDACION
      ,SUBSTRING(B.CUENTA_CONTABLE,1,E.NUMERO_CARACTERES) CUENTA_CONTABLE
      ,SUM(ISNULL(B.MONTO_CARGO,0)) MONTO_CARGO
      ,SUM(ISNULL(B.MONTO_ABONO,0)) MONTO_ABONO
      ,SUM(ISNULL(B.MONTO_CARGO_FORANEA,0)) MONTO_CARGO_FORANEA
      ,SUM(ISNULL(B.MONTO_ABONO_FORANEA,0)) MONTO_ABONO_FORANEA
FROM CON_PARTIDA A
INNER JOIN CON_PARTIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
INNER JOIN CON_CATALOGO_CUENTA C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CUENTA_CONTABLE=C.CUENTA_CONTABLE
INNER JOIN CON_PARAMETRO D ON C.CORR_EMPRESA=D.CORR_EMPRESA
INNER JOIN CON_RUBRO_NIVEL E ON C.CORR_EMPRESA=E.CORR_EMPRESA AND C.CODIGO_RUBRO=E.CODIGO_RUBRO AND E.NIVEL=D.NIVEL_CUENTA_MAYOR
WHERE A.ESTADO_PARTIDA='AP'
GROUP BY A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.FECHA_PARTIDA
      ,CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='CIE' THEN 1 ELSE 0 END)
      ,CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='LIQ' THEN 1 ELSE 0 END)
      ,SUBSTRING(B.CUENTA_CONTABLE,1,E.NUMERO_CARACTERES)

GO
