SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COLUMNAS]
AS
SELECT *,
CASE UPPER(DATA_TYPE)
WHEN 'DATE' THEN 'DateEdit' 
WHEN 'DATETIME' THEN 'DateEdit' 
WHEN 'BIT' THEN 'CheckEdit'
WHEN 'MONEY' THEN 'CalcEdit'
WHEN 'DECIMAL' THEN 'CalcEdit'
WHEN 'NUMERIC' THEN 'CalcEdit'
WHEN 'INT' THEN 'SpinEdit'
WHEN 'SMALLINT' THEN 'SpinEdit'
WHEN 'TINYINT' THEN 'SpinEdit'
WHEN 'VARCHAR' THEN 'TextEdit'
WHEN 'NVARCHAR' THEN 'TextEdit'
ELSE 'TextEdit' END COMPONENTE
FROM INFORMATION_SCHEMA.COLUMNS
GO
