SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO]
AS
SELECT
  A.CORR_EMPRESA
 ,A.ANIO_PERIODO
 ,A.CORR_CUADRO_COMPARATIVO
 ,CONVERT(VARCHAR(4),A.ANIO_PERIODO)+'-'+CONVERT(VARCHAR(15),A.CORR_CUADRO_COMPARATIVO) NUMERO_CUADRO_COMPARA
 ,A.FECHA_CUADRO_COMPARATIVO
 ,CASE A.ESTADO_CUADRO_COMPARATIVO
    WHEN 'DI' THEN 'DIGITADO'
    WHEN 'SO' THEN 'SOLICITADO'
    WHEN 'AP' THEN 'APLICADO'
    WHEN 'AN' THEN 'ANULADO'
    ELSE ''
  END NOMBRE_ESTADO_CUADRO_COMPARATIVO
 ,A.ESTADO_CUADRO_COMPARATIVO
 ,A.USUARIO_CUADRO_COMPARATIVO
 ,A.OBSERVACIONES
 ,A.ES_MEJOR_PRECIO
 ,A.TIENE_CREDITO_30_DIAS
 ,A.TIENE_BUEN_SOPORTE_TECNICO
 ,A.TIENE_BUENA_CALIDAD_PRODUCTO
 ,A.TIENE_MEJOR_TIEMPO_ENTREGA
 ,A.BRINDA_BUENA_EXPERIENCIA_PROVEEDOR
 ,A.ES_PROVEEDOR_UNICO
 ,A.EXISTE_OTRA_RAZON
 ,A.NOMBRE_OTRA_RAZON
 ,A.USUARIO_CREA
 ,A.FECHA_CREA
 ,A.ESTACION_CREA
 ,A.USUARIO_ACTU
 ,A.FECHA_ACTU
 ,A.ESTACION_ACTU
 ,B.NOMBRE_PROVEEDOR
 ,C.NUMERO_SOLI_COTIZACION
 ,C.NUMERO_SOLI_COMPRA
 ,D.NUMERO_COTIZACION
 ,ISNULL(E.AUTORIZACIONES_PENDIENTES,'')AUTORIZACIONES_PENDIENTES
 ,ISNULL(E.AUTORIZACIONES_REALIZADAS,'')AUTORIZACIONES_REALIZADAS
 ,ISNULL(F.NUMERO_ORDEN,'')NUMERO_ORDEN
FROM COM_CUADRO_COMPARATIVO A
LEFT OUTER JOIN V_COM_CUADRO_COMPARATIVO_PROVEEDOR_SUM B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO=B.CORR_CUADRO_COMPARATIVO
LEFT OUTER JOIN V_COM_CUADRO_COMPARATIVO_SOLI_COTIZACION_SUM C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.ANIO_PERIODO=C.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO=C.CORR_CUADRO_COMPARATIVO
LEFT OUTER JOIN V_COM_CUADRO_COMPARATIVO_COTIZACION_SUM D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.ANIO_PERIODO=D.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO=D.CORR_CUADRO_COMPARATIVO
LEFT OUTER JOIN V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_CONSOLIDADAS E ON A.CORR_EMPRESA = E.CORR_EMPRESA AND A.ANIO_PERIODO = E.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = E.CORR_CUADRO_COMPARATIVO
LEFT OUTER JOIN V_COM_CUADRO_COMPARATIVO_ORDEN_COMPRA_SUM F ON A.CORR_EMPRESA = F.CORR_EMPRESA AND A.ANIO_PERIODO = F.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = F.CORR_CUADRO_COMPARATIVO
GO
