SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_IMPUESTO_F910]
AS
SELECT  CONVERT(VARCHAR, '') NOMBRE_PERSONA
		,CONVERT(VARCHAR, '') NIT
		,CONVERT(VARCHAR, '') DUI
		,CONVERT(VARCHAR, '') CODIGO_INGRESO
		,CONVERT(DECIMAL(18,2), 0) MONTO_DEVENGADO
		,CONVERT(DECIMAL(18,2), 0) MONTO_BONIFICACION
		,CONVERT(DECIMAL(18,2), 0) IMPUESTO_RENTA
		,CONVERT(DECIMAL(18,2), 0) MONTO_AGUINALDO_EXCENTO
		,CONVERT(DECIMAL(18,2), 0) MONTO_AGUINALDO_GRAVADO
		,CONVERT(DECIMAL(18,2), 0) MONTO_AFP
		,CONVERT(DECIMAL(18,2), 0) MONTO_ISSS
		,CONVERT(DECIMAL(18,2), 0) MONTO_INPEP
		,CONVERT(DECIMAL(18,2), 0) MONTO_IPSFA
		,CONVERT(DECIMAL(18,2), 0) MONTO_CEFAFA
		,CONVERT(DECIMAL(18,2), 0) MONTO_BM
		,CONVERT(DECIMAL(18,2), 0) ISSS_IVM
		,CONVERT(DECIMAL(18,2), 0) MONTO_ENERO
		,CONVERT(DECIMAL(18,2), 0) RENTA_ENERO
		,CONVERT(DECIMAL(18,2), 0) AFP_ENERO
		,CONVERT(DECIMAL(18,2), 0) MONTO_FEBRERO
		,CONVERT(DECIMAL(18,2), 0) RENTA_FEBRERO
		,CONVERT(DECIMAL(18,2), 0) AFP_FEBRERO
		,CONVERT(DECIMAL(18,2), 0) MONTO_MARZO
		,CONVERT(DECIMAL(18,2), 0) RENTA_MARZO
		,CONVERT(DECIMAL(18,2), 0) AFP_MARZO
		,CONVERT(DECIMAL(18,2), 0) MONTO_ABRIL
		,CONVERT(DECIMAL(18,2), 0) RENTA_ABRIL
		,CONVERT(DECIMAL(18,2), 0) AFP_ABRIL
		,CONVERT(DECIMAL(18,2), 0) MONTO_MAYO
		,CONVERT(DECIMAL(18,2), 0) RENTA_MAYO
		,CONVERT(DECIMAL(18,2), 0) AFP_MAYO
		,CONVERT(DECIMAL(18,2), 0) MONTO_JUNIO
		,CONVERT(DECIMAL(18,2), 0) RENTA_JUNIO
		,CONVERT(DECIMAL(18,2), 0) AFP_JUNIO
		,CONVERT(DECIMAL(18,2), 0) MONTO_JULIO
		,CONVERT(DECIMAL(18,2), 0) RENTA_JULIO
		,CONVERT(DECIMAL(18,2), 0) AFP_JULIO
		,CONVERT(DECIMAL(18,2), 0) MONTO_AGOSTO
		,CONVERT(DECIMAL(18,2), 0) RENTA_AGOSTO
		,CONVERT(DECIMAL(18,2), 0) AFP_AGOSTO
		,CONVERT(DECIMAL(18,2), 0) MONTO_SEPTIEMBRE
		,CONVERT(DECIMAL(18,2), 0) RENTA_SEPTIEMBRE
		,CONVERT(DECIMAL(18,2), 0) AFP_SEPTIEMBRE
		,CONVERT(DECIMAL(18,2), 0) MONTO_OCTUBRE
		,CONVERT(DECIMAL(18,2), 0) RENTA_OCTUBRE
		,CONVERT(DECIMAL(18,2), 0) AFP_OCTUBRE
		,CONVERT(DECIMAL(18,2), 0) MONTO_NOVIEMBRE
		,CONVERT(DECIMAL(18,2), 0) RENTA_NOVIEMBRE
		,CONVERT(DECIMAL(18,2), 0) AFP_NOVIEMBRE
		,CONVERT(DECIMAL(18,2), 0) MONTO_DICIEMBRE
		,CONVERT(DECIMAL(18,2), 0) RENTA_DICIEMBRE
		,CONVERT(DECIMAL(18,2), 0) AFP_DICIEMBRE
		,CONVERT(INT, 0) ANIO_PERIODO
FROM PLA_DOCUMENTO
GO
