SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_TIPO_GASTO_IMPUESTO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_TIPO_GASTO
      ,A.CORR_RUBRO
      ,A.IMPUESTO_INCLUIDO
      ,A.ORDEN_TOTAL
      ,ISNULL(A.PERMITE_EDITAR,CONVERT(BIT,1)) PERMITE_EDITAR
      ,B.NOMBRE_RUBRO 
      ,B.POR_IMPUESTO 
      ,B.MUESTRA_TOTAL 
      ,B.CLASE_RUBRO 
  FROM GEN_TIPO_GASTO_IMPUESTO A
  INNER JOIN GEN_RUBRO B ON A.CORR_EMPRESA=B.CORR_EMPRESA  AND A.CORR_RUBRO=B.CORR_RUBRO

GO
