SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW dbo.V_CON_CATALOGO_PRESUPUESTO_COMPARACION
AS
SELECT  A.CORR_EMPRESA
	 , A.CUENTA_CONTABLE
	 , B.NOMBRE_CUENTA
	 , B.CLASE_RUBRO
	 , B.CUENTA_MAYOR
	 , C.NOMBRE_CUENTA NOMBRE_CUENTA_MAYOR
	 , A.ANIO_PERIODO
	 , A.MONTO_PRESUPUESTO_1
	 , ISNULL(SUM(CASE WHEN D.MES_PERIODO=1 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_1
     , A.MONTO_PRESUPUESTO_2
     , ISNULL(SUM(CASE WHEN D.MES_PERIODO=2 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_2
     , A.MONTO_PRESUPUESTO_3
     , ISNULL(SUM(CASE WHEN D.MES_PERIODO=3 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_3
     , A.MONTO_PRESUPUESTO_4
     , ISNULL(SUM(CASE WHEN D.MES_PERIODO=4 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_4
     , A.MONTO_PRESUPUESTO_5
     , ISNULL(SUM(CASE WHEN D.MES_PERIODO=5 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_5
     , A.MONTO_PRESUPUESTO_6
     , ISNULL(SUM(CASE WHEN D.MES_PERIODO=6 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_6
     , A.MONTO_PRESUPUESTO_7
     , ISNULL(SUM(CASE WHEN D.MES_PERIODO=7 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_7
     , A.MONTO_PRESUPUESTO_8
     , ISNULL(SUM(CASE WHEN D.MES_PERIODO=8 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_8
     , A.MONTO_PRESUPUESTO_9
     , ISNULL(SUM(CASE WHEN D.MES_PERIODO=9 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_9
     , A.MONTO_PRESUPUESTO_10
     , ISNULL(SUM(CASE WHEN D.MES_PERIODO=10 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_10
     , A.MONTO_PRESUPUESTO_11
     , ISNULL(SUM(CASE WHEN D.MES_PERIODO=11 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_11
     , A.MONTO_PRESUPUESTO_12
	 , ISNULL(SUM(CASE WHEN D.MES_PERIODO=12 THEN D.MONTO_CARGO-D.MONTO_ABONO ELSE 0 END),0) MONTO_REAL_12
     , A.MONTO_PRESUPUESTO_1+A.MONTO_PRESUPUESTO_2+A.MONTO_PRESUPUESTO_3+A.MONTO_PRESUPUESTO_4+A.MONTO_PRESUPUESTO_5+A.MONTO_PRESUPUESTO_6+A.MONTO_PRESUPUESTO_7+A.MONTO_PRESUPUESTO_8+A.MONTO_PRESUPUESTO_9+A.MONTO_PRESUPUESTO_10+A.MONTO_PRESUPUESTO_11+A.MONTO_PRESUPUESTO_12 MONTO_PRESUPUESTO_TOTAL
     , ISNULL(SUM(D.MONTO_CARGO-D.MONTO_ABONO),0) MONTO_REAL_TOTAL
FROM CON_CATALOGO_PRESUPUESTO A
INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
LEFT OUTER JOIN CON_CATALOGO_CUENTA C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CUENTA_MAYOR=C.CUENTA_CONTABLE
LEFT OUTER JOIN CON_PARTIDA_DETA D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.ANIO_PERIODO=D.ANIO_PERIODO AND A.CUENTA_CONTABLE=D.CUENTA_CONTABLE
LEFT OUTER JOIN CON_PARTIDA E ON D.CORR_EMPRESA=E.CORR_EMPRESA AND D.ANIO_PERIODO=E.ANIO_PERIODO AND D.MES_PERIODO=E.MES_PERIODO AND D.CORR_CLASE_PARTIDA=E.CORR_CLASE_PARTIDA AND D.CORR_PARTIDA=E.CORR_PARTIDA
WHERE B.CLASE_RUBRO='GA'
AND E.ESTADO_PARTIDA='AP'
GROUP BY  A.CORR_EMPRESA
	 , A.CUENTA_CONTABLE
	 , B.NOMBRE_CUENTA
	 , B.CLASE_RUBRO
	 , B.CUENTA_MAYOR
	 , C.NOMBRE_CUENTA
	 , A.ANIO_PERIODO
	 , A.MONTO_PRESUPUESTO_1
	 , A.MONTO_PRESUPUESTO_2
	 , A.MONTO_PRESUPUESTO_3
	 , A.MONTO_PRESUPUESTO_4
	 , A.MONTO_PRESUPUESTO_5
	 , A.MONTO_PRESUPUESTO_6
	 , A.MONTO_PRESUPUESTO_7
	 , A.MONTO_PRESUPUESTO_8
	 , A.MONTO_PRESUPUESTO_9
	 , A.MONTO_PRESUPUESTO_10
	 , A.MONTO_PRESUPUESTO_11
	 , A.MONTO_PRESUPUESTO_12
GO
