SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_IMPUESTO_VENTAS_GRAVADAS_TERCEROS_DOMICILIADOS]
AS
SELECT CONVERT(VARCHAR, '') NIT_MANDANTE,
	CONVERT(VARCHAR, '') NOMBRE_CLIENTE,
	CONVERT(DATE, '') FECHA_EMISION,
	CONVERT(INT, 0) TIPO_DOCUMENTO,
	CONVERT(VARCHAR, '') NUMERO_SERIE_DOCUMENTO,
	CONVERT(VARCHAR, '') NUMERO_RESOLUCION,
	CONVERT(INT, 0) NUMERO_DOCUMENTO,
	CONVERT(DECIMAL(18,2), 0) MONTO_OPERACION,
	CONVERT(DECIMAL(18,2), 0) IVA_OPERACION,
	CONVERT(VARCHAR, '') NUMERO_SERIE_COMPRO_LIQUIDACION,
	CONVERT(VARCHAR, '') NUMERO_RESOLUCION_COMPRO_LIQUIDA,
	CONVERT(INT, 0) NUMERO_COMPRO_LIQUIDA,
	CONVERT(VARCHAR, '') FECHA_EMISION_COMPRO_LIQUIDA,
	CONVERT(INT, 0) NUMERO_ANEXO
FROM COM_DOCUMENTO
GO
