SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SEG_TIPO_USUARIO]
AS
SELECT A.TIPO_USUARIO
,A.NOMBRE_TIPO_USUARIO
,A.USUARIO_CREA
,A.FECHA_CREA
,A.ESTACION_CREA
,A.USUARIO_ACTU
,A.FECHA_ACTU
,A.ESTACION_ACTU 
FROM SEG_TIPO_USUARIO A
GO
