SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_BAN_CONCILIA_PENDIENTE]
AS
SELECT    A.CORR_EMPRESA 
		, A.ANIO_PERIODO 
		, A.MES_PERIODO 
		, A.CORR_CLASE_PARTIDA 
		, A.CORR_PARTIDA 
		, B.NUMERO_DOCUMENTO 
		, B.FECHA_PARTIDA 
		, C.NOMBRE_CLASE_PARTIDA 
		, B.ESTADO_PARTIDA 
		, A.CORR_PARTIDA_DETA 
		, A.CUENTA_CONTABLE
		, A.MONTO_CARGO 
		, A.MONTO_ABONO 
		, A.MONTO_CARGO_FORANEA
		, A.MONTO_ABONO_FORANEA
		, A.NOMBRE_TRAN 
		, A.ESTA_CONCILIA 
		, A.CORR_AUXILIAR 		
FROM CON_PARTIDA_DETA A
INNER JOIN CON_PARTIDA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
INNER JOIN CON_CLASE_PARTIDA C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_CLASE_PARTIDA=C.CORR_CLASE_PARTIDA
WHERE C.NOMBRE_CORTO_CLASE<>'APE'
AND ISNULL(C.PARTIDA_CIERRE,0)<>1
GO

