SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_ACTIVIDAD_ECONOMICA]
AS
SELECT CONVERT(INT,A.CODCOD) CORR_ACTIVIDAD_ECONOMICA
,LTRIM(RTRIM(A.CODDSC)) NOMBRE_ACTIVIDAD_ECONOMICA
FROM [CLASS_UEES].dbo.CODIGOS A 
WHERE RTRIM(LTRIM(A.CODREL))='ACT_EMP'
AND LEN(A.CODCOD)<6
GO
