CREATE OR ALTER VIEW dbo.V_PLA_TIPO_DOCUMENTO_ADJUNTO
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_TIPO_DOCUMENTO_ADJUNTO,
    X.TIPO_DOCUMENTO,
    X.DESCRIPCION_DOCUMENTO,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.PLA_TIPO_DOCUMENTO_ADJUNTO AS X;
GO
