SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_GEN_TIPO_DOCUMENTO_RUBRO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_TIPO_DOC
      ,B.NOMBRE_TIPO_DOC 
      ,A.CORR_RUBRO
      ,C.NOMBRE_RUBRO
      ,C.CLASE_RUBRO 
      ,A.ORDEN_TOTAL
      ,A.PERMITE_EDITAR 
	  ,ISNULL(A.ES_PRINCIPAL,0) ES_PRINCIPAL
	  ,B.CLASE_DOCUMENTO
	  ,ISNULL(C.POR_IMPUESTO,0) POR_IMPUESTO
FROM GEN_TIPO_DOCUMENTO_RUBRO A 
INNER JOIN GEN_TIPO_DOCUMENTO B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_DOC = B.CORR_TIPO_DOC
INNER JOIN GEN_RUBRO C ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CORR_RUBRO = C.CORR_RUBRO
GO
