SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_SOLI_COTIZACION_PROVEEDOR_SUM]
AS
SELECT A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.CORR_SOLI_COTIZACION
	  ,dbo.StrConcat(B.CLINAM+', ') NOMBRE_PROVEEDOR
FROM COM_SOLI_COTIZACION_PROVEEDOR A
INNER JOIN [CLASS_UEES].dbo.CLIENTES B ON A.CORR_PROVEEDOR=B.CLIIDU
GROUP BY A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.CORR_SOLI_COTIZACION
GO
