SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_MOVI_CONTA_AUDI]
AS
SELECT A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.MES_PERIODO
,A.CORR_CLASE_PARTIDA
,A.USUARIO_CREA
,C.NOMBRE_USUARIO
,A.FECHA_CREA
,A.NOMBRE_CLASE_PARTIDA
,A.CORR_PARTIDA
,A.FECHA_PARTIDA
,B.NOMBRE_TRAN
,ISNULL(D.CLASE_AUXILIAR,'') CLASE_AUXILIAR
,B.CORR_AUXILIAR
,B.CUENTA_CONTABLE
,B.NOMBRE_CUENTA
,B.CORR_PARTIDA_DETA
,B.MONTO_CARGO+B.MONTO_ABONO MONTO
,CASE WHEN B.MONTO_CARGO<>0 THEN 'C' ELSE 'A' END CARGO_ABONO
FROM V_CON_PARTIDA A
INNER JOIN V_CON_PARTIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
LEFT OUTER JOIN SEG_USUARIO C ON A.USUARIO_CREA=C.LOGIN_SISTEMA
LEFT OUTER JOIN CON_CATALOGO_CUENTA_AUXI D ON B.CORR_EMPRESA=D.CORR_EMPRESA AND B.CUENTA_CONTABLE=D.CUENTA_CONTABLE AND B.CORR_AUXILIAR=D.CORR_AUXILIAR
GO
