SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DESCRIPTOR_FUNCION]
AS
SELECT
  F.[CORR_EMPRESA],
  F.[CORR_DESCRIPTOR_PUESTO],
  F.[CORR_FUNCION],
  F.[NOMBRE_FUNCION],
  F.[TIPO_FUNCION],
  F.[USUARIO_CREA],
  F.[ESTACION_CREA],
  F.[FECHA_CREA],
  F.[USUARIO_ACTU],
  F.[ESTACION_ACTU],
  F.[FECHA_ACTU],
  ISNULL(A.[CANT_ACTIVIDADES], 0) AS [CANT_ACTIVIDADES]
FROM [dbo].[SC_DESCRIPTOR_FUNCION] F
LEFT JOIN (
  SELECT
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_FUNCION],
    COUNT(*) AS [CANT_ACTIVIDADES]
  FROM [dbo].[SC_DESCRIPTOR_FUNCION_ACTIVIDAD]
  GROUP BY [CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO], [CORR_FUNCION]
) A
  ON F.[CORR_EMPRESA] = A.[CORR_EMPRESA]
 AND F.[CORR_DESCRIPTOR_PUESTO] = A.[CORR_DESCRIPTOR_PUESTO]
 AND F.[CORR_FUNCION] = A.[CORR_FUNCION]
GO
