CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_DOCUMENTO
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_DOCUMENTO,
    X.CORR_SOLICITUD_EMPLEO,
    X.FECHA_CARGA,
    X.TIPO_DOCUMENTO,
    X.NOMBRE_ARCHIVO,
    X.RUTA_ARCHIVO,
    X.NOTAS,
    S.CORREO_INVITACION,
    S.NOMBRE AS NOMBRE_SOLICITUD,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_DOCUMENTO AS X
INNER JOIN dbo.SC_SOLICITUD_EMPLEO AS S
    ON S.CORR_EMPRESA = X.CORR_EMPRESA
   AND S.CORR_SOLICITUD_EMPLEO = X.CORR_SOLICITUD_EMPLEO;
GO
