SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_SC_DESCRIPTOR_PUESTO_INDUCCION]
AS
SELECT
  D.[CORR_EMPRESA],
  D.[CORR_DESCRIPTOR_PUESTO],
  D.[CORR_INDUCCION],
  D.[NOMBRE_INDUCCION],
  D.[TIEMPO_INDUCCION],
  D.[USUARIO_CREA],
  D.[ESTACION_CREA],
  D.[FECHA_CREA],
  D.[USUARIO_ACTU],
  D.[ESTACION_ACTU],
  D.[FECHA_ACTU]
FROM [dbo].[SC_DESCRIPTOR_PUESTO_INDUCCION] D
GO
