
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_BAN_PARAMETRO]
AS
SELECT A.CORR_EMPRESA
      ,E.NOMBRE_EMPRESA
      ,A.CONTABILIZAR_LUEGO_DE_APLICAR
      ,A.CONTABILIZAR_LUEGO_DE_IMPRIMIR
FROM dbo.BAN_PARAMETRO A
INNER JOIN dbo.GEN_EMPRESA E ON E.CORR_EMPRESA = A.CORR_EMPRESA
GO
