SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_ORDEN_COMPRA_DETA]
AS
SELECT A.CORR_EMPRESA
	,A.ANIO_PERIODO
	,A.CORR_CUADRO_COMPARATIVO
	,B.ORDFAP FECHA_ORDEN_COMPRA
	,B.ORDNUM NUMERO_ORDEN_COMPRA
	,B.ORDCAN CANTIDAD
	,''NOMBRE_UNIDAD_MEDIDA
	,E.INVDSC NOMBRE_ITEM
	,B.ORDMUN PRECIO_UNITARIO
	,B.ORDAMT MONTO_SUBTOTAL
FROM COM_CUADRO_COMPARATIVO_ORDEN_COMPRA A
INNER JOIN [CLASS_UEES].dbo.ORDENCOMPRA B ON A.NUMERO_ORDEN=B.ORDNUM
INNER JOIN [CLASS_UEES].dbo.INVENTARIOS E ON E.INVCOD = B.ORDCOD AND E.INVREG = 'E' AND E.INVSUC='001'
GO
