SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_COTIZACION_NORMAL_SUM]
AS
SELECT A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.CORR_CUADRO_COMPARATIVO
	  ,dbo.StrConcat(CONVERT(VARCHAR(100),C.ANIO_PERIODO)+'-'+CONVERT(VARCHAR(100),C.CORR_COTIZACION)+', ') NUMERO_COTIZACION
	  ,dbo.StrConcat(DISTINCT D.CODCOD+' '+D.CODDSC) NOMBRE_DEPTO
	  ,RTRIM(dbo.StrConcat(DISTINCT B.USUARIO_CREA+' '))USUARIO_CREA
FROM COM_CUADRO_COMPARATIVO_SOLI_COTIZACION A
INNER JOIN COM_SOLI_COTIZACION B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO_SOLI_COTI=B.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION=B.CORR_SOLI_COTIZACION
INNER JOIN COM_COTIZACION C ON C.CORR_EMPRESA = B.CORR_EMPRESA AND C.ANIO_PERIODO_SOLI_COTI = B.ANIO_PERIODO AND C.CORR_SOLI_COTIZACION = B.CORR_SOLI_COTIZACION
INNER JOIN [CLASS_UEES].dbo.CODIGOS D ON D.CODCOD = B.CODIGO_DEPTO COLLATE Modern_Spanish_CI_AS AND D.CODREL = 'DPTOS'
INNER JOIN COM_TIPO_SOLI_COTIZA E ON B.CORR_EMPRESA = E.CORR_EMPRESA AND B.CORR_TIPO_SOLI_COTIZA = E.CORR_TIPO_SOLI_COTIZA
WHERE E.CLASE_SOLI_COTIZA='NO'
GROUP BY A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.CORR_CUADRO_COMPARATIVO
GO
