-- Qué hace: vista de mantenimiento del catálogo GEN_PARENTESCO.
-- Cómo lo hace: proyecta la tabla con ISNULL en ACTIVO_PARENTESCO (1 por defecto).
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PARENTESCO]
AS
SELECT
	P.CORR_PARENTESCO,
	P.NOMBRE_PARENTESCO,
	P.DESCRIPCION,
	ISNULL(P.ACTIVO_PARENTESCO, 1) AS ACTIVO_PARENTESCO,
	P.USUARIO_CREA,
	P.ESTACION_CREA,
	P.FECHA_CREA,
	P.USUARIO_ACTU,
	P.ESTACION_ACTU,
	P.FECHA_ACTU
FROM dbo.GEN_PARENTESCO AS P;
GO
