SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS]
AS
SELECT
  CT.[CORR_EMPRESA],
  CT.[CORR_PERFIL_PUESTO_COMPETENCIAS_TECNICAS],
  CT.[NOMBRE_COMPETENCIAS_TECNICAS],
  CT.[DESCRIPCION],
  CT.[NIVEL_DOMINIO],
  CT.[CORR_DESCRIPTOR_PUESTO],
  CT.[CORR_PERFIL_PUESTO],
  CT.[CORR_COMPETENCIAS_TECNICAS],
  CT.[USUARIO_CREA],
  CT.[ESTACION_CREA],
  CT.[FECHA_CREA],
  CT.[USUARIO_ACTU],
  CT.[ESTACION_ACTU],
  CT.[FECHA_ACTU],
  C.[CODIGO_COMPETENCIAS_TECNICAS]
FROM [dbo].[SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS] CT
LEFT JOIN [dbo].[SC_COMPETENCIAS_TECNICAS] C
  ON CT.[CORR_EMPRESA] = C.[CORR_EMPRESA]
 AND CT.[CORR_COMPETENCIAS_TECNICAS] = C.[CORR_COMPETENCIAS_TECNICAS]
GO
