SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_BANCO]
AS
SELECT A.CORR_BANCO
      ,A.NOMBRE_BANCO
      ,A.NOMBRE_BANCO_CORTO
      ,A.CLASE_BANCO
	  ,CASE A.CLASE_BANCO
	  WHEN 'CREDO'  THEN 'Credomatic'
	  WHEN 'CUSCA'  THEN 'Cuscatlan'
	  WHEN 'BAG'  THEN 'Agricola'
	  WHEN 'BDV'  THEN 'Davivienda'
	  WHEN 'BPM'  THEN 'Promerica'END	NOMBRE_CLASE_BANCO
      ,A.CODIGO_TRANSACION_UNI
      ,ISNULL(A.ESTADO_BANCO, 1) ESTADO_BANCO
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
FROM COM_BANCO A
GO
