SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SEG_USUARIO_CLASS]
AS
SELECT LTRIM(RTRIM(A.USRUID)) LOGIN_SISTEMA
      ,LTRIM(RTRIM(A.USRDSC)) NOMBRE_USUARIO
      ,NULL CLAVE_USUARIO
	  ,NULL CLAVE_USUARIO_SAL
      ,LTRIM(RTRIM(A.USREML)) CORREO_ELECTRONICO
      ,2 TIPO_USUARIO
      ,'Normal' NOMBRE_TIPO_USUARIO
      ,CASE WHEN A.USRSTS='A' THEN 1 ELSE 3 END ESTADO_USUARIO
      ,CASE WHEN A.USRSTS='A' THEN 'Usuario Activo' ELSE 'Usuario Cancelado' END NOMBRE_ESTADO_USUARIO
	  ,'' IDIOMA	    
      ,'Admin' USUARIO_CREA
      ,GETDATE() FECHA_CREA
      ,'e-Coffee' ESTACION_CREA
      ,'Admin' USUARIO_ACTU
      ,GETDATE() FECHA_ACTU
      ,'e-Coffee' ESTACION_ACTU
      ,ISNULL(B.CORR_EMPRESA,0) CORR_EMPRESA
      ,ISNULL(B.NOMBRE_EMPRESA,'') NOMBRE_EMPRESA      
	  ,NULL FOTO_PERFIL
	  ,NULL FOTO_FIRMA
FROM [CLASS_UEES].dbo.USUARIOS A
INNER JOIN GEN_EMPRESA B ON 1=B.CORR_EMPRESA
GO
