SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_DECLARACION_MENS_HACIENDA_CFF_FAC]
AS 
SELECT A.CORR_EMPRESA
	  ,A.CORR_TIENDA
	  ,A.ANIO_PERIODO
	  ,A.MES_PERIODO
	  ,CONVERT(VARCHAR(100), '') NOMBRE_TIPO_DOCUMENTO
	  ,CONVERT(VARCHAR(2), '') ESTADO_DOCUMENTO
	  ,CONVERT(VARCHAR(25), '') SERIE
	  ,CONVERT(INT, 0) DESDE
	  ,CONVERT(INT, 0) HASTA
	  FROM V_VEN_DOCUMENTO A
GO
