SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_COMENTARIO]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_CUADRO_COMPARATIVO
      ,A.CORR_COMENTARIO
      ,A.COMENTARIO
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
FROM COM_CUADRO_COMPARATIVO_COMENTARIO A
GO
