SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_SOLI_COTIZACION_DETA]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_SOLI_COTIZACION
      ,A.CORR_SOLI_COTIZACION_DETA
	  ,ISNULL(A.ANIO_PERIODO_SOLI_COMPRA,0) ANIO_PERIODO_SOLI_COMPRA
	  ,ISNULL(A.CORR_SOLI_COMPRA,0) CORR_SOLI_COMPRA
      ,A.CODIGO_ITEM
	  ,B.INVDSC NOMBRE_ITEM 
      ,A.CANTIDAD
      ,A.CORR_UNIDAD_MEDIDA
	  ,C.NOMBRE_UNIDAD_MEDIDA
      ,A.OBSERVACIONES
      ,A.ESTADO_SOLI_COTIZACION
	  ,CASE A.ESTADO_SOLI_COTIZACION 
	   WHEN 'DI' THEN 'DIGITADO'
	   WHEN 'SO' THEN 'SOLICITADO'
	   WHEN 'AP' THEN 'APLICADO'
	   WHEN 'AN' THEN 'ANULADO'
	   ELSE '' END NOMBRE_ESTADO_SOLI_COTIZACION
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
	  ,ISNULL(D.CORR_DOCUMENTO,0) CORR_DOCUMENTO
	  ,CASE	WHEN ISNULL(D.CORR_DOCUMENTO,0)<>0 THEN 'assets/img/adjunto.png' ELSE 'assets/img/noadjunto1.png' END IMAGEN_DOCUMENTO
	  ,ISNULL(E.NOMBRE_ARCHIVO,'')NOMBRE_ARCHIVO
	  ,CONVERT(VARCHAR,ISNULL(A.ANIO_PERIODO_SOLI_COMPRA,0)) + '-' + CONVERT(VARCHAR,ISNULL(A.CORR_SOLI_COMPRA,0)) NUMERO_SOLI_COMPRA
	  ,ISNULL(A.PRECIO_UNITARIO,0) PRECIO_UNITARIO
	  ,ISNULL(A.MONTO_SUBTOTAL,0) MONTO_SUBTOTAL
FROM COM_SOLI_COTIZACION_DETA A
INNER JOIN [CLASS_UEES].dbo.INVENTARIOS B ON B.INVCOD = A.CODIGO_ITEM COLLATE Modern_Spanish_CI_AS AND B.INVREG = 'E' AND B.INVSUC='001'
LEFT OUTER JOIN COM_UNIDAD_MEDIDA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_UNIDAD_MEDIDA=C.CORR_UNIDAD_MEDIDA
LEFT OUTER JOIN COM_SOLI_COTIZACION_DETA_DOC D ON A.CORR_EMPRESA = D.CORR_EMPRESA AND A.ANIO_PERIODO = D.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION = D.CORR_SOLI_COTIZACION AND A.CORR_SOLI_COTIZACION_DETA = D.CORR_SOLI_COTIZACION_DETA
LEFT OUTER JOIN COM_DOCUMENTO_FISICO E ON D.CORR_EMPRESA = E.CORR_EMPRESA AND D.CORR_DOCUMENTO = E.CORR_DOCUMENTO
GO
