-- Qué hace: vista de mantenimiento del catálogo GEN_TIPO_CONTRIBUYENTE.
-- Cómo lo hace: proyecta la tabla con ISNULL en ACTIVO_TIPO_CONTRIBUYENTE (1 por defecto).
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_TIPO_CONTRIBUYENTE]
AS
SELECT
	T.CORR_TIPO_CONTRIBUYENTE,
	T.NOMBRE_TIPO_CONTRIBUYENTE,
	ISNULL(T.ACTIVO_TIPO_CONTRIBUYENTE, 1) AS ACTIVO_TIPO_CONTRIBUYENTE,
	T.USUARIO_CREA,
	T.ESTACION_CREA,
	T.FECHA_CREA,
	T.USUARIO_ACTU,
	T.ESTACION_ACTU,
	T.FECHA_ACTU
FROM dbo.GEN_TIPO_CONTRIBUYENTE AS T;
GO
