SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_TIPO_DOC_FISICO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_TIPO_DOCUMENTO
      ,A.NOMBRE_TIPO_DOCUMENTO
      ,A.NOMBRE_CORTO_TIPO_DOC
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
FROM COM_TIPO_DOC_FISICO A
GO
