SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_BAN_CONCILIA_BANCARIA_MOVI_SUM]
AS
SELECT A.CORR_EMPRESA
	,A.CORR_CUENTA_BANCO
	,A.CORR_CONCILIACION		
	,SUM(CASE WHEN B.AUMENTA_DISMINUYE=1 THEN ISNULL(A.MONTO_CARGO,0)+ISNULL(A.MONTO_ABONO,0) ELSE 0 END) MONTO_AUMENTA
	,SUM(CASE WHEN B.AUMENTA_DISMINUYE=-1 THEN ISNULL(A.MONTO_CARGO,0)+ISNULL(A.MONTO_ABONO,0) ELSE 0 END) MONTO_DISMINUYE
FROM BAN_CONCILIA_BANCARIA_MOVI A
INNER JOIN BAN_LINEA_TRABAJO_CONCILIACION B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_LINEA=B.CORR_LINEA		
GROUP BY A.CORR_EMPRESA
	,A.CORR_CUENTA_BANCO
	,A.CORR_CONCILIACION
GO

