SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_PROVEEDOR_USUARIO]
AS
SELECT A.CORR_PROVEEDOR
      ,A.LOGIN_SISTEMA
	  ,B.NOMBRE_USUARIO
	  ,B.CORREO_ELECTRONICO
	  ,B.ESTADO_USUARIO
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
FROM COM_PROVEEDOR_USUARIO A
INNER JOIN SEG_USUARIO B ON A.LOGIN_SISTEMA = B.LOGIN_SISTEMA
WHERE B.TIPO_USUARIO=6
GO
