SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_GEN_PROVEEDOR]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_PROVEEDOR,
	A.CODIGO_PROVEEDOR,
	A.TIPO_PERSONERIA,
	CASE A.TIPO_PERSONERIA
		WHEN N'N' THEN N'Natural'
		WHEN N'J' THEN N'Jurídico'
		ELSE N''
	END AS NOMBRE_TIPO_PERSONERIA,
	A.NOMBRE_PROVEEDOR,
	ISNULL(A.PRIMER_NOMBRE, N'') AS PRIMER_NOMBRE,
	ISNULL(A.SEGUNDO_NOMBRE, N'') AS SEGUNDO_NOMBRE,
	ISNULL(A.PRIMER_APELLIDO, N'') AS PRIMER_APELLIDO,
	ISNULL(A.SEGUNDO_APELLIDO, N'') AS SEGUNDO_APELLIDO,
	ISNULL(A.NOMBRE_COMERCIAL, N'') AS NOMBRE_COMERCIAL,
	A.CORR_TIPO_DIP,
	A.NUMERO_DIP,
	A.NUMERO_NRC,
	A.NUMERO_NIT,
	A.CORR_ACTIVIDAD_ECONOMICA,
	A.DIRECCION_PROVEEDOR,
	A.CORR_PAIS,
	A.CORR_DEPTO,
	A.CORR_MUNICIPIO,
	A.NOMBRE_CONTACTO,
	A.TELEFONO_FIJO,
	A.TELEFONO_MOVIL,
	A.CORREO_ELECTRONICO_1,
	A.CORREO_ELECTRONICO_2,
	A.CORR_FORMA_PAGO,
	A.CUENTA_BANCARIA,
	A.CORR_BANCO,
	A.ESTADO_PROVEEDOR,
	CASE A.ESTADO_PROVEEDOR
		WHEN N'AC' THEN N'Activo'
		WHEN N'IN' THEN N'Inactivo'
		WHEN N'DI' THEN N'Digitado'
		WHEN N'SO' THEN N'Solicitado'
		ELSE N''
	END AS NOMBRE_ESTADO_PROVEEDOR,
	A.ESTADO_PROVEEDOR_WEB,
	A.CORR_CONDICION_PAGO,
	A.USUARIO_CREA,
	A.FECHA_CREA,
	A.ESTACION_CREA,
	A.USUARIO_ACTU,
	A.FECHA_ACTU,
	A.ESTACION_ACTU
FROM dbo.GEN_PROVEEDOR A
GO
