CREATE OR ALTER VIEW dbo.V_SC_REQUISICION_CANDIDATO
AS
SELECT
    RC.CORR_EMPRESA,
    RC.CORR_REQUISICION_CANDIDATO,
    RC.CORR_REQUISICION_PERSONAL,
    RC.CORR_SOLICITUD_EMPLEO,
    RC.CORR_EXPEDIENTE_CANDIDATO,
    RC.ESTADO_DECISION,
    RC.OBSERVACION_DECISION,
    RC.FECHA_DECISION,
    RC.USUARIO_DECISION,
    R.NOMBRE_UNIDAD,
    R.NOMBRE_PUESTO,
    R.MODALIDAD_NOMBRE,
    R.CORR_ESTADO_REQUISICION,
    RC.USUARIO_CREA,
    RC.ESTACION_CREA,
    RC.FECHA_CREA,
    RC.USUARIO_ACTU,
    RC.ESTACION_ACTU,
    RC.FECHA_ACTU
FROM dbo.SC_REQUISICION_CANDIDATO AS RC
INNER JOIN dbo.V_SC_REQUISICION_PERSONAL AS R
    ON R.CORR_EMPRESA = RC.CORR_EMPRESA
   AND R.CORR_REQUISICION_PERSONAL = RC.CORR_REQUISICION_PERSONAL;
GO
