SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_DECLARACION_MENS_HACIENDA_COMPRO_LIQUI]
AS
		SELECT B.SERIE
			,A.NUMERO_COMPRO_LIQUIDA    
			,A.FECHA_COMPRO_LIQUIDA
			,B.NOMBRE_DETALLE DESCRIPCION
			,B.NUMERO_INICIAL DESDE
			,B.NUMERO_FINAL HASTA
			,CONVERT(VARCHAR(50), '') TIPO_FAC
			,CONVERT(VARCHAR, '') CODI_RUT
			,B.CANTIDAD UNIDADES
			,CONVERT(DECIMAL(18,2),ROUND(B.MONTO_TOTAL,2)) TOTAL_NETO
			,dbo.DIVIDIR(B.MONTO_TOTAL,B.CANTIDAD) PROMEDIO
			,CONVERT(VARCHAR, '') GRUPO
			,C.CLASE_PRODUCTORA PRODUCTORA
			,CONVERT(INT, 0) LIQUIDADA
			,CONVERT(DATE, '') FECHA_MOV
			,CONVERT(INT, 0) AS PERCEPCION
			,'No' ANULADA
		FROM VEN_COMPRO_LIQUIDA A
		INNER JOIN VEN_COMPRO_LIQUIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND  A.MES_PERIODO=B.MES_PERIODO AND A.CORR_COMPRO_LIQUIDA=B.CORR_COMPRO_LIQUIDA
		INNER JOIN GEN_PRODUCTORA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_PRODUCTORA=C.CORR_PRODUCTORA AND A.CORR_PRODUCTORA=1
GO
