-- Qué hace: vista de personas de contacto del empleado (nombre, parentesco, tipo y valor).
-- Cómo lo hace: une GEN_PERSONA_PARENTESCO_CONTACTO con parentesco y tipo de contacto.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_PARENTESCO_CONTACTO]
AS
SELECT
	P.CORR_EMPRESA,
	P.CORR_PERSONA,
	P.CORR_PARENTESCO_CONTACTO,
	P.NOMBRE_COMPLETO,
	P.CORR_PARENTESCO,
	PA.NOMBRE_PARENTESCO,
	P.CORR_TIPO_CONTACTO,
	T.NOMBRE_TIPO_CONTACTO,
	T.NOMBRE_CORTO,
	T.NUMERO_CARACTERES,
	ISNULL(T.ACTIVO_CARACTERES, 0) AS ACTIVO_CARACTERES,
	ISNULL(T.FORMATO_CARACTERES, N'') AS FORMATO_CARACTERES,
	ISNULL(T.APLICA_PARA, N'') AS APLICA_PARA,
	P.VALOR_CONTACTO,
	P.DIRECCION,
	ISNULL(P.ES_EXTRANJERO, 0) AS ES_EXTRANJERO,
	ISNULL(P.PARENTESCO_CONTACTO_EMERGENCIA, 0) AS PARENTESCO_CONTACTO_EMERGENCIA,
	ISNULL(P.ACTIVO_PARENTESCO_CONTACTO, 1) AS ACTIVO_PARENTESCO_CONTACTO,
	P.USUARIO_CREA,
	P.ESTACION_CREA,
	P.FECHA_CREA,
	P.USUARIO_ACTU,
	P.ESTACION_ACTU,
	P.FECHA_ACTU
FROM dbo.GEN_PERSONA_PARENTESCO_CONTACTO AS P
LEFT JOIN dbo.GEN_PARENTESCO AS PA
	ON PA.CORR_PARENTESCO = P.CORR_PARENTESCO
LEFT JOIN dbo.GEN_TIPO_CONTACTO AS T
	ON T.CORR_TIPO_CONTACTO = P.CORR_TIPO_CONTACTO;
GO
