SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_PLA_DEPARTAMENTO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_DEPARTAMENTO
      ,A.NOMBRE_DEPARTAMENTO
      ,A.CORR_CENTRO_COSTO
      ,ISNULL(B.NOMBRE_CENTRO,'')  NOMBRE_CENTRO
	  ,A.CODIGO_DEPARTAMENTO
	  ,ISNULL(A.CLASE_DEPARTAMENTO,'') CLASE_DEPARTAMENTO
	  ,CASE ISNULL(A.CLASE_DEPARTAMENTO,'OT') 
	   WHEN 'AD' THEN 'Administrativo'
	   WHEN 'OP' THEN 'Operativo'
	   WHEN 'OT' THEN 'Otro'
	   ELSE 'Otro' END NOMBRE_CLASE_DEPARTAMENTO
FROM PLA_DEPARTAMENTO A
LEFT JOIN CON_CENTRO_COSTO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CENTRO_COSTO=B.CORR_CENTRO_COSTO
GO