SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_CON_DEPARTAMENTO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_DIVISION
      ,A.CORR_GERENCIA
      ,A.CORR_DEPARTAMENTO
      ,A.NOMBRE_DEPARTAMENTO
      ,A.CODIGO_DEPARTAMENTO

  FROM GEN_DEPARTAMENTO A

GO
