SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_PERSONA_COMPETENCIAS_TECNICAS]
AS
SELECT [CORR_EMPRESA], [CORR_PERSONA_DATOS], [CORR_COMPETENCIA_TECNICA],
       [HERRAMIENTA], [NIVEL], [USUARIO_CREA], [ESTACION_CREA], [FECHA_CREA],
       [USUARIO_ACTU], [ESTACION_ACTU], [FECHA_ACTU]
FROM [dbo].[SC_PERSONA_COMPETENCIAS_TECNICAS]
GO
