SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: empleados con puesto/unidad para combos (organigrama / jefes).
-- Cómo lo hace: GEN_EMPLEADO + GEN_EMPLEADO_PUESTO + unidad + PLA_PUESTO;
--               nombre y login desde persona (misma forma que V_GEN_EMPLEADO).
CREATE OR ALTER VIEW [dbo].[V_GEN_EMPLEADO_DISPONIBLE]
AS
SELECT
	GE.CORR_EMPRESA,
	GE.CORR_EMPLEADO,
	ISNULL(PN.NOMBRE_COMPLETO, N'') AS NOMBRE_EMPLEADO,
	PU.LOGIN_SISTEMA AS LOGIN_SISTEMA_WEB,
	EP.CORR_PUESTO,
	PP.NOMBRE_PUESTO,
	EP.CORR_UNIDAD AS CORR_UNIDAD_EMPLEADO,
	U.NOMBRE_UNIDAD AS UNIDAD_EMPLEADO,
	U.CODIGO_UNIDAD AS CODIGO_UNIDAD_EMPLEADO
FROM dbo.GEN_EMPLEADO GE
INNER JOIN dbo.GEN_EMPLEADO_PUESTO EP
	ON EP.CORR_EMPLEADO = GE.CORR_EMPLEADO
   AND EP.CORR_EMPRESA = GE.CORR_EMPRESA
INNER JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES U
	ON U.CORR_UNIDAD = EP.CORR_UNIDAD
   AND U.CORR_EMPRESA = EP.CORR_EMPRESA
LEFT JOIN dbo.PLA_PUESTO PP
	ON PP.CORR_PUESTO = EP.CORR_PUESTO
   AND PP.CORR_EMPRESA = EP.CORR_EMPRESA
LEFT JOIN dbo.GEN_PERSONA_NATURAL PN
	ON PN.CORR_PERSONA = GE.CORR_PERSONA
OUTER APPLY
(
	SELECT TOP (1) X.LOGIN_SISTEMA
	FROM dbo.GEN_PERSONA_USUARIO X
	WHERE X.CORR_PERSONA = GE.CORR_PERSONA
	ORDER BY X.LOGIN_SISTEMA
) PU
GO
