
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_PARAMETRO]
AS
SELECT A.CORR_EMPRESA
      ,A.NOMBRE_PUESTO1
      ,A.DESCRIPCION_PUESTO1
      ,A.NOMBRE_PUESTO2
      ,A.DESCRIPCION_PUESTO2
      ,A.NOMBRE_PUESTO3
      ,A.DESCRIPCION_PUESTO3
      ,A.NIVEL_CUENTA_MAYOR
      ,A.CORR_CENTRO_COSTO_DEF
      ,A.CORR_MONEDA
      ,B.NOMBRE_MONEDA        
      ,A.CUENTA_CONTABLE_PERDIDA
      ,A.CUENTA_CONTABLE_GANANCIA
      ,A.CUENTA_CONTABLE_IVA_DEBITO
      ,A.CUENTA_CONTABLE_IVA_CREDITO
      ,A.CUENTA_CONTABLE_IVA_RETENIDO
      ,A.CUENTA_CONTABLE_IVA_PERCIBIDO
      ,A.CUENTA_CONTABLE_RENTA
      ,A.CUENTA_CONTABLE_CAJA
      ,A.CUENTA_CONTABLE_CAJA_CHICA
      ,A.APLICAR_DOC_CONTA
      ,A.PERIODO_MOSTRAR
      ,A.CARACTER_SEPARADOR
      ,A.CUENTA_CONTABLE_CAMBIO_DIFERENCIAL      
      ,A.CORR_CLASE_PARTIDA_DEFAULT
      ,A.OCULTA_CLASE_PARTIDA_BANCOS
      ,A.INCLUIR_PARTIDA_LIQUIDACION
      ,A.INCLUIR_PARTIDA_CIERRE      
      ,A.USA_AUXILIARES
      ,A.MOSTRAR_FECHA_IMPRESION
      ,A.PREFIJO
      ,A.CUENTA_CONTABLE_CAMBIO_DIF_GASTO      
FROM CON_PARAMETRO A 
JOIN GEN_TIPO_MONEDA B ON A.CORR_MONEDA=B.CORR_MONEDA
GO
