SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_SOLI_COTIZACION]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_CUADRO_COMPARATIVO
      ,A.ANIO_PERIODO_SOLI_COTI
      ,A.CORR_SOLI_COTIZACION
	  ,ISNULL(E.CLASE_SOLI_COTIZA,'')CLASE_SOLI_COTIZA
FROM COM_CUADRO_COMPARATIVO_SOLI_COTIZACION A
INNER JOIN COM_SOLI_COTIZACION B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO_SOLI_COTI = B.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION = B.CORR_SOLI_COTIZACION
LEFT OUTER JOIN COM_TIPO_SOLI_COTIZA E ON B.CORR_EMPRESA=E.CORR_EMPRESA AND B.CORR_TIPO_SOLI_COTIZA=E.CORR_TIPO_SOLI_COTIZA
GO
