CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_DOCUMENTO
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_DOCUMENTO,
    X.FECHA_CARGA,
    X.CORR_TIPO_DOCUMENTO_ADJUNTO,
    T.TIPO_DOCUMENTO,
    T.DESCRIPCION_DOCUMENTO,
    X.NOMBRE_ARCHIVO,
    X.RUTA_ARCHIVO,
    X.NOTAS,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_DOCUMENTO AS X
LEFT JOIN dbo.PLA_TIPO_DOCUMENTO_ADJUNTO AS T
    ON T.CORR_EMPRESA = X.CORR_EMPRESA
   AND T.CORR_TIPO_DOCUMENTO_ADJUNTO = X.CORR_TIPO_DOCUMENTO_ADJUNTO;
GO
