SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_TIPO_DIP]
AS
SELECT A.CORR_TIPO_DIP
,A.NOMBRE_TIPO_DIP
FROM [e-AdminFE].dbo.GEN_TIPO_DIP A
WHERE A.CLASE_TIPO_DIP NOT IN('NIT')
GO
