SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_PARTIDA_DETA_DOC]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,A.CORR_PARTIDA
      ,A.CORR_PARTIDA_DETA
      ,C.NOMBRE_TIPO_CORTO TIPO_DOCUMENTO
      ,B.FECHA_EMISION FECHA_DOCUMENTO
      ,B.NUMERO_DOCUMENTO      
      ,A.ANIO_PERIODO_DOC 
      ,A.MES_PERIODO_DOC
      ,A.CORR_DOCUMENTO
      ,CASE C.CLASE_MOVIMIENTO
      WHEN 'CHQ' THEN 'BAN_DOCUMENTO'
      ELSE 'BAN_DOCUMENTO_OTRO' END  FORMA
      ,LTRIM(RTRIM(CONVERT(VARCHAR,A.CORR_TIPO_MOVIMIENTO)))+'-'+LTRIM(RTRIM(CONVERT(VARCHAR,A.CORR_DOCUMENTO))) ID_DOCUMENTO
FROM BAN_PARTIDA_DETA A
INNER JOIN BAN_DOCUMENTO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO_DOC=B.ANIO_PERIODO AND A.MES_PERIODO_DOC=B.MES_PERIODO AND A.CORR_TIPO_MOVIMIENTO=B.CORR_TIPO_MOVIMIENTO AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO
INNER JOIN BAN_TIPO_MOVI_BANCARIO C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_TIPO_MOVIMIENTO=C.CORR_TIPO_MOVIMIENTO
UNION
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,A.CORR_PARTIDA
      ,A.CORR_PARTIDA_DETA
      ,C.NOMBRE_CORTO_TIPO_DOC TIPO_DOCUMENTO      
      ,B.FECHA_DOCUMENTO
      ,B.NUMERO_DOCUMENTO 
      ,A.ANIO_PERIODO_DOC 
      ,A.MES_PERIODO_DOC
      ,A.CORR_DOCUMENTO
      ,'VEN_DOCUMENTO' FORMA
      ,LTRIM(RTRIM(CONVERT(VARCHAR,A.CORR_TIENDA)))+'-'+LTRIM(RTRIM(CONVERT(VARCHAR,A.CORR_DOCUMENTO))) ID_DOCUMENTO      
FROM VEN_PARTIDA_DETA A
INNER JOIN VEN_DOCUMENTO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIENDA=B.CORR_TIENDA AND A.ANIO_PERIODO_DOC=B.ANIO_PERIODO AND A.MES_PERIODO_DOC=B.MES_PERIODO AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO
INNER JOIN GEN_TIPO_DOCUMENTO C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_TIPO_DOC=C.CORR_TIPO_DOC
UNION
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA      
      ,A.CORR_PARTIDA
      ,A.CORR_PARTIDA_DETA
      ,C.NOMBRE_CORTO_TIPO_DOC TIPO_DOCUMENTO      
      ,B.FECHA_DOCUMENTO
      ,B.NUMERO_DOCUMENTO 
      ,A.ANIO_PERIODO_DOC 
      ,A.MES_PERIODO_DOC
      ,A.CORR_DOCUMENTO
      ,'COM_DOCUMENTO' FORMA
      ,LTRIM(RTRIM(CONVERT(VARCHAR,A.CORR_DOCUMENTO))) ID_DOCUMENTO      
FROM COM_PARTIDA_DETA A
INNER JOIN COM_DOCUMENTO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO_DOC=B.ANIO_PERIODO AND A.MES_PERIODO_DOC=B.MES_PERIODO AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO
INNER JOIN GEN_TIPO_DOCUMENTO C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_TIPO_DOC=C.CORR_TIPO_DOC
GO
