CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_CANDIDATO_POSTULACION
AS
SELECT
    ES.CORR_EMPRESA,
    ES.CORR_EXPEDIENTE_CANDIDATO,
    ES.CORR_EXPEDIENTE_SOLICITUD,
    ES.CORR_SOLICITUD_EMPLEO,
    SR.CORR_SOLICITUD_REQUISICION,
    SR.CORR_REQUISICION_PERSONAL,
    R.NOMBRE_UNIDAD,
    R.NOMBRE_PUESTO,
    R.MODALIDAD_NOMBRE,
    R.CORR_ESTADO_REQUISICION,
    RC.CORR_REQUISICION_CANDIDATO,
    CAST(ISNULL(RC.ESTADO_DECISION, N'PENDIENTE') AS VARCHAR(20)) AS ESTADO_DECISION,
    RC.OBSERVACION_DECISION,
    RC.FECHA_DECISION,
    RC.USUARIO_DECISION
FROM dbo.SC_EXPEDIENTE_SOLICITUD AS ES
INNER JOIN dbo.SC_SOLICITUD_REQUISICION AS SR
    ON SR.CORR_EMPRESA = ES.CORR_EMPRESA
   AND SR.CORR_SOLICITUD_EMPLEO = ES.CORR_SOLICITUD_EMPLEO
INNER JOIN dbo.V_SC_REQUISICION_PERSONAL AS R
    ON R.CORR_EMPRESA = SR.CORR_EMPRESA
   AND R.CORR_REQUISICION_PERSONAL = SR.CORR_REQUISICION_PERSONAL
LEFT JOIN dbo.SC_REQUISICION_CANDIDATO AS RC
    ON RC.CORR_EMPRESA = ES.CORR_EMPRESA
   AND RC.CORR_REQUISICION_PERSONAL = SR.CORR_REQUISICION_PERSONAL
   AND RC.CORR_EXPEDIENTE_CANDIDATO = ES.CORR_EXPEDIENTE_CANDIDATO
   AND RC.CORR_SOLICITUD_EMPLEO = ES.CORR_SOLICITUD_EMPLEO;
GO
