SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_PARAMETRO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_AMBIENTE
      ,A.URL_CONSULTA
      ,ISNULL(A.CORREO_REMITENTE,'') CORREO_REMITENTE
      ,ISNULL(A.USUARIO_REMITENTE,'') USUARIO_REMITENTE
      ,ISNULL(A.CONTRASENA_REMITENTE,'') CONTRASENA_REMITENTE
      ,ISNULL(A.SERVIDOR_CORREO,'') SERVIDOR_CORREO
      ,ISNULL(A.PUERTO_CORREO,'') PUERTO_CORREO
      ,ISNULL(A.USA_SSL_CORREO,'') USA_SSL_CORREO
	  ,ISNULL(A.HABILITAR_IMPRESION_TICKET,0)HABILITAR_IMPRESION_TICKET
	  ,ISNULL(A.URL_DOCUMENTO,'') URL_DOCUMENTO
FROM [e-AdminFE].dbo.GEN_PARAMETRO A
GO
