SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_SOLI_COTIZACION]
AS
SELECT A.CORR_EMPRESA
     ,A.ANIO_PERIODO
     ,A.CORR_SOLI_COTIZACION
	 ,CONVERT(VARCHAR(4),A.ANIO_PERIODO)+'-'+CONVERT(VARCHAR(15),A.CORR_SOLI_COTIZACION) NUMERO_SOLI_COTIZACION
     ,A.FECHA_SOLI_COTIZACION
     ,A.FECHA_LIMITE_COTIZACION
     ,A.CODIGO_DEPTO
	 ,B.CODDSC NOMBRE_DEPTO
     ,A.USUARIO_SOLI
     ,A.OBSERVACIONES
     ,A.ESTADO_SOLI_COTIZACION
	 ,CASE A.ESTADO_SOLI_COTIZACION 
	  WHEN 'DI' THEN 'DIGITADO'
	  WHEN 'SO' THEN 'SOLICITADO'
	  WHEN 'AP' THEN 'APLICADO'
	  WHEN 'AN' THEN 'ANULADO'
	  ELSE '' END NOMBRE_ESTADO_SOLI_COTIZACION
     ,A.USUARIO_CREA
     ,A.FECHA_CREA
     ,A.ESTACION_CREA
     ,A.USUARIO_ACTU
     ,A.FECHA_ACTU
     ,A.ESTACION_ACTU
	 ,D.NUMERO_SOLI_COMPRA
	 ,C.NOMBRE_PROVEEDOR
	 ,ISNULL(A.CORR_TIPO_SOLI_COTIZA,0) CORR_TIPO_SOLI_COTIZA
	 ,ISNULL(E.NOMBRE_TIPO_SOLI_COTIZA,'') NOMBRE_TIPO_SOLI_COTIZA
	 ,ISNULL(E.CLASE_SOLI_COTIZA,'') CLASE_SOLI_COTIZA
FROM COM_SOLI_COTIZACION A
INNER JOIN [CLASS_UEES].dbo.CODIGOS B ON B.CODCOD = A.CODIGO_DEPTO COLLATE Modern_Spanish_CI_AS AND B.CODREL = 'DPTOS'
LEFT OUTER JOIN V_COM_SOLI_COTIZACION_PROVEEDOR_SUM C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.ANIO_PERIODO=C.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION=C.CORR_SOLI_COTIZACION
LEFT OUTER JOIN V_COM_SOLI_COTIZACION_SOLI_COMPRA_SUM D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.ANIO_PERIODO=D.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION=D.CORR_SOLI_COTIZACION
LEFT OUTER JOIN COM_TIPO_SOLI_COTIZA E ON A.CORR_EMPRESA=E.CORR_EMPRESA AND A.CORR_TIPO_SOLI_COTIZA=E.CORR_TIPO_SOLI_COTIZA
GO
