SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_GEN_UNIDADES_PUESTO]
AS
SELECT
  up.[CORR_EMPRESA],
  up.[CORR_UNIDAD],
  u.[CODIGO_UNIDAD],
  u.[NOMBRE_UNIDAD],
  up.[CORR_PUESTO],
  p.[CODIGO_PUESTO],
  p.[NOMBRE_PUESTO],
  up.[USUARIO_CREA],
  up.[ESTACION_CREA],
  up.[FECHA_CREA],
  up.[USUARIO_ACTU],
  up.[ESTACION_ACTU],
  up.[FECHA_ACTU]
FROM [dbo].[GEN_UNIDADES_PUESTO] up
LEFT JOIN [dbo].[SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES] u
  ON u.[CORR_EMPRESA] = up.[CORR_EMPRESA]
 AND u.[CORR_UNIDAD] = up.[CORR_UNIDAD]
LEFT JOIN [dbo].[PLA_PUESTO] p
  ON p.[CORR_EMPRESA] = up.[CORR_EMPRESA]
 AND p.[CORR_PUESTO] = up.[CORR_PUESTO]
GO
