-- Qué hace: vista de contactos de una persona (valor + metadatos del catálogo).
-- Cómo lo hace: une GEN_PERSONA_CONTACTO con GEN_TIPO_CONTACTO (formato, aplica para y tope de caracteres).
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_CONTACTO]
AS
SELECT
	P.CORR_EMPRESA,
	P.CORR_PERSONA,
	P.CORR_CONTACTO,
	P.VALOR_CONTACTO,
	ISNULL(P.ACTIVO_CONTACTO, 1) AS ACTIVO_CONTACTO,
	P.CORR_TIPO_CONTACTO,
	T.NOMBRE_TIPO_CONTACTO,
	T.NOMBRE_CORTO,
	T.NUMERO_CARACTERES,
	ISNULL(T.ACTIVO_CARACTERES, 0) AS ACTIVO_CARACTERES,
	ISNULL(T.FORMATO_CARACTERES, N'') AS FORMATO_CARACTERES,
	ISNULL(T.APLICA_PARA, N'') AS APLICA_PARA,
	ISNULL(T.ACTIVO_TIPO_CONTACTO, 1) AS ACTIVO_TIPO_CONTACTO,
	P.USUARIO_CREA,
	P.ESTACION_CREA,
	P.FECHA_CREA,
	P.USUARIO_ACTU,
	P.ESTACION_ACTU,
	P.FECHA_ACTU
FROM dbo.GEN_PERSONA_CONTACTO AS P
INNER JOIN dbo.GEN_TIPO_CONTACTO AS T
	ON T.CORR_TIPO_CONTACTO = P.CORR_TIPO_CONTACTO;
GO
