SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_GEN_RUBRO_IMPUESTO] 
AS 
SELECT A.CORR_EMPRESA
      ,A.CORR_RUBRO      
      ,A.CORR_IMPUESTO
      ,B.NOMBRE_RUBRO NOMBRE_IMPUESTO
      ,A.IMPUESTO_INCLUIDO
FROM GEN_RUBRO_IMPUESTO A 
INNER JOIN GEN_RUBRO B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_IMPUESTO = B.CORR_RUBRO
GO
