SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_PARAMETRO]
AS
SELECT A.CORR_EMPRESA
,A.URL_DOCUMENTO
,A.GERENTE_COMPRAS
,A.GERENTE_CONTABILIDAD
,A.GERENTE_GENERAL
,A.RECTOR
,A.CORREO_REMITENTE
,A.USUARIO_REMITENTE
,A.CONTRASENA_REMITENTE
,A.SERVIDOR_CORREO
,A.PUERTO_CORREO
,A.USA_SSL_CORREO
,A.NOMBRE_USUARIO_COPIAR
,A.CORREO_ELECTRONICO_COPIAR
,A.USUARIO_FE
,A.CLAVE_FE
,A.CODIGO_SUITE_FE
FROM COM_PARAMETRO A
GO
