SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_DEPTO]
AS
SELECT D.CORR_PAIS
      ,D.CORR_DEPTO
      ,D.NOMBRE_DEPTO
      ,D.CODIGO_DEPTO
      ,D.USUARIO_CREA
      ,D.ESTACION_CREA
      ,D.FECHA_CREA
      ,D.USUARIO_ACTU
      ,D.ESTACION_ACTU
      ,D.FECHA_ACTU
      ,P.NOMBRE_PAIS
  FROM GEN_DEPTO D
  LEFT JOIN GEN_PAIS P ON P.CORR_PAIS = D.CORR_PAIS
GO
