SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_SOLI_COTIZACION_SUM]
AS
SELECT A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.CORR_CUADRO_COMPARATIVO
	  ,dbo.StrConcat(CONVERT(VARCHAR(100),ISNULL(A.ANIO_PERIODO_SOLI_COTI,''))+'-'+CONVERT(VARCHAR(100),ISNULL(A.CORR_SOLI_COTIZACION,''))+', ') NUMERO_SOLI_COTIZACION
	  ,MAX(C.NUMERO_SOLI_COMPRA) NUMERO_SOLI_COMPRA
FROM COM_CUADRO_COMPARATIVO_SOLI_COTIZACION A
INNER JOIN COM_SOLI_COTIZACION B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO_SOLI_COTI=B.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION=B.CORR_SOLI_COTIZACION
INNER JOIN V_COM_SOLI_COTIZACION_SOLI_COMPRA_SUM C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.ANIO_PERIODO=C.ANIO_PERIODO AND B.CORR_SOLI_COTIZACION=C.CORR_SOLI_COTIZACION
GROUP BY A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.CORR_CUADRO_COMPARATIVO
GO
