SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_IMPUESTO_DETALLE_VENTAS_CONTRIBUYENTES]
AS
SELECT CONVERT(DATE, '') FECHA_EMISION,
	CONVERT(INT, 0) CLASE_DOCUMENTO,
	CONVERT(INT, 0) TIPO_DOCUMENTO,
	CONVERT(VARCHAR, '') NUMERO_RESOLUCION,
	CONVERT(VARCHAR, '') NUMERO_SERIE,
	CONVERT(BIGINT, 0) NUMERO_DOCUMENTO,
	CONVERT(BIGINT, 0) NUMERO_CONTROL_INTERNO,
	CONVERT(VARCHAR, '') NIT,
	CONVERT(VARCHAR, '') NOMBRE_CLIENTE,
	CONVERT(DECIMAL(18,2), 0) VENTAS_EXENTAS,
	CONVERT(DECIMAL(18,2), 0) VENTAS_NO_SUJETAS,
	CONVERT(DECIMAL(18,2), 0) VENTAS_GRAVADAS,
	CONVERT(DECIMAL(18,2), 0) DEBITO_FISCAL,
	CONVERT(DECIMAL(18,2), 0) VENTAS_TERCERO,
	CONVERT(DECIMAL(18,2), 0) DEBITO_FISCAL_TERCERO,
	CONVERT(DECIMAL(18,2), 0) TOTAL_VENTAS,
	CONVERT(INT, 0) NUMERO_ANEXO
FROM COM_DOCUMENTO
GO
