SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_UNIDAD_NEGOCIO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_UNIDAD_NEGOCIO
      ,A.NOMBRE_UNIDAD_NEGOCIO
      ,A.CODIGO_UNIDAD_NEGOCIO
      ,A.CLASE_UNIDAD_NEGOCIO
  FROM CON_UNIDAD_NEGOCIO A

GO