SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_SC_REQUISICION_PERSONAL]
AS
SELECT
    R.CORR_EMPRESA,
    R.CORR_REQUISICION_PERSONAL,
    R.CORR_DESCRIPTOR_PUESTO,
    R.CORR_UNIDAD,
    U.NOMBRE_UNIDAD,
    R.CORR_PUESTO,
    P.NOMBRE_PUESTO,
    R.CORR_TIPO_MODALIDAD,
    M.MODALIDAD_NOMBRE,
    R.CORR_TIPO_CONTRATACION,
    TC.NOMBRE_TIPO_CONTRATACION,
    R.CORR_TIPO_VACANTE,
    TV.NOMBRE_TIPO_VACANTE,
    R.CANTIDAD_PLAZAS,
    R.PLAZAS_CUBIERTAS,
    R.FECHA_REQUISICION,
    R.JUSTIFICACION,
    R.CORR_EMPLEADO_SUSTITUTO,
    R.SALARIO,
    R.CORR_ESTADO_REQUISICION,
    R.FECHA_APROBACION,
    R.FECHA_CIERRE,
    R.TIEMPO_CONTRATO,
    R.HORARIO,
    R.USUARIO_CREA,
    R.ESTACION_CREA,
    R.FECHA_CREA,
    R.USUARIO_ACTU,
    R.ESTACION_ACTU,
    R.FECHA_ACTU
FROM dbo.SC_REQUISICION_PERSONAL AS R
LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES AS U
    ON U.CORR_EMPRESA = R.CORR_EMPRESA
   AND U.CORR_UNIDAD = R.CORR_UNIDAD
LEFT JOIN dbo.PLA_PUESTO AS P
    ON P.CORR_EMPRESA = R.CORR_EMPRESA
   AND P.CORR_PUESTO = R.CORR_PUESTO
LEFT JOIN dbo.SC_TIPO_MODALIDAD AS M
    ON M.CORR_EMPRESA = R.CORR_EMPRESA
   AND M.CORR_TIPO_MODALIDAD = R.CORR_TIPO_MODALIDAD
LEFT JOIN dbo.SC_TIPO_CONTRATACION AS TC
    ON TC.CORR_EMPRESA = R.CORR_EMPRESA
   AND TC.CORR_TIPO_CONTRATACION = R.CORR_TIPO_CONTRATACION
LEFT JOIN dbo.SC_TIPO_VACANTE AS TV
    ON TV.CORR_EMPRESA = R.CORR_EMPRESA
   AND TV.CORR_TIPO_VACANTE = R.CORR_TIPO_VACANTE
GO
