SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_DOCUMENTO]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_TIPO_DOC
      ,B.NOMBRE_TIPO_DOC
      ,B.NOMBRE_CORTO_TIPO_DOC
      ,B.CLASE_DOCUMENTO
      ,B.SUMA_RESTA 
      ,A.CORR_DOCUMENTO
	  ,dbo.FN_NUMERO_DOC(A.ANIO_PERIODO,A.MES_PERIODO,A.CORR_DOCUMENTO,4) NUMERO_DOCUMENTO_CORR
      ,A.NUMERO_DOCUMENTO
      ,A.FECHA_DOCUMENTO
      ,A.FECHA_VENCIMIENTO --para antiguedad de saldos
      ,A.CORR_TIENDA
      --,C.NOMBRE_TIENDA
      ,ISNULL(A.CORR_PROVEEDOR,0) CORR_PROVEEDOR
	  ,F.NOMBRE_PROVEEDOR
      --,F.NOMBRE_PROVEEDOR
	  --,F.REGISTRO_FISCAL
	  --,F.CORR_PAIS
      ,A.DESCRIPCION_PARTIDA
      ,A.CORR_CONDICION_PAGO
      ,D.NOMBRE_CONDICION_PAGO
      ,A.DIAS_CREDITO
      ,A.ESTADO_DOCUMENTO 
      ,CASE A.ESTADO_DOCUMENTO
      WHEN 'DI' THEN 'Digitado'
      WHEN 'AP' THEN 'Aplicado'
      WHEN 'AN' THEN 'Anulado'
      ELSE '' END NOMBRE_ESTADO_DOCUMENTO
      ,A.ESTA_CONTABILIZADO
      ,A.TOTAL_DOCUMENTO
      ,A.TOTAL_NETO
      ,A.SALDO_DOCUMENTO
      ,A.CORR_TIPO_GASTO 
      ,E.NOMBRE_TIPO_GASTO 
      ,ISNULL(A.CANTIDAD,0) CANTIDAD
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
      ,A.CORR_MOVIMIENTO
      ,ISNULL(A.CORR_MONEDA,0) CORR_MONEDA
      --,ISNULL(G.NOMBRE_MONEDA,'') NOMBRE_MONEDA
      ,ISNULL(A.FACTOR_CAMBIO,0) FACTOR_CAMBIO
      ,ISNULL(A.OPERADOR,'*') OPERADOR
	  ,ISNULL(A.SERIE,'') SERIE
	  ,ISNULL(A.NUMERO_UNICO, 0) NUMERO_UNICO
	  ,A.ESTADO_ADMINISTRATIVO
	  ,CASE A.ESTADO_ADMINISTRATIVO
      WHEN 'AP' THEN 'Aplicado'
      WHEN 'LI' THEN 'Liquidado'
	  WHEN 'PR' THEN 'Provisionado'
	  WHEN 'SO' THEN 'Soli Pago'
	  WHEN 'RE' THEN 'Rev. Conta'
	  WHEN 'PG' THEN 'Programado'
	  WHEN 'AU' THEN 'Autorizado'
	  WHEN 'PA' THEN 'Pagado'
	  WHEN 'AB' THEN 'Abonado'
	  WHEN 'AN' THEN 'Anulado' 
      ELSE '' END NOMBRE_ESTADO_ADMINISTRATIVO
	  --,H.NUMERO_ORDEN_COMPRA
	  ,ISNULL(A.CODIGO_GENERACION,'')CODIGO_GENERACION
	  ,ISNULL(A.NUMERO_CONTROL,'')NUMERO_CONTROL
	  ,ISNULL(A.SELLO_RECEPCION,'')SELLO_RECEPCION
	  ,A.ANIO_PERIODO_IVA
	  ,A.MES_PERIODO_IVA
	  ,CASE A.MES_PERIODO_IVA
	  WHEN 1 THEN 'Enero'
	  WHEN 2 THEN 'Febrero'
	  WHEN 3 THEN 'Marzo'
	  WHEN 4 THEN 'Abril'
	  WHEN 5 THEN 'Mayo'
	  WHEN 6 THEN 'Junio'
	  WHEN 7 THEN 'Julio'
	  WHEN 8 THEN 'Agosto'
	  WHEN 9 THEN 'Septiembre'
	  WHEN 10 THEN 'Octubre'
	  WHEN 11 THEN 'Noviembre'
	  WHEN 12 THEN 'Diciembre'
	  END NOMBRE_MES_PERIODO_IVA
	  ,B.ES_ELECTRONICO
	  ,G.CORR_EMPRESA_FE
	  ,G.CORR_DOCUMENTO_FE
FROM COM_DOCUMENTO A 
INNER JOIN GEN_TIPO_DOCUMENTO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIPO_DOC=B.CORR_TIPO_DOC
--INNER JOIN GEN_TIENDA C ON A.CORR_SUSCRIPCION=C.CORR_SUSCRIPCION AND A.CORR_CONFI_PAIS=C.CORR_CONFI_PAIS AND A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_TIENDA=C.CORR_TIENDA
INNER JOIN COM_CONDICION_PAGO D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.CORR_CONDICION_PAGO=D.CORR_CONDICION_PAGO
INNER JOIN GEN_TIPO_GASTO E ON A.CORR_EMPRESA=E.CORR_EMPRESA AND A.CORR_TIPO_GASTO=E.CORR_TIPO_GASTO
INNER JOIN V_COM_PROVEEDOR F ON A.CORR_PROVEEDOR=F.CORR_PROVEEDOR
LEFT OUTER JOIN V_ADM_COM_JSON G ON A.CORR_EMPRESA = G.CORR_EMPRESA AND A.ANIO_PERIODO = G.ANIO_PERIODO AND A.MES_PERIODO = G.MES_PERIODO AND A.CORR_DOCUMENTO = G.CORR_DOCUMENTO
GO
