SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_CON_LIBRO_IVA_VENTAS_CONTRIBUYENTES]
AS
SELECT  
A.CORR_EMPRESA,
A.CORR_TIENDA,
'' NIT_TIENDA,
'' REGISTRO_FISCAL_TIENDA,
A.ANIO_PERIODO,
A.MES_PERIODO,
A.CORR_DOCUMENTO,
0 NUMERO_FILA,
A.FECHA_DOCUMENTO,
'' N_DOCUMENTO,
'' DIA,
A.NUMERO_DOCUMENTO,
A.CLASE_DOCUMENTO,
A.SUMA_RESTA,
A.NOMBRE_CLIENTE,
A.REGISTRO_FISCAL,
0 VENTAS_PROPIAS_NO_SUJETAS,	
0 VENTAS_PROPIAS_EXENTA,		
0 VENTAS_PROPIAS_GRAVADA,		
0 VENTAS_PROPIAS_IVA,			
0 VENTAS_PROPIAS_IVA_RETENIDO,	
0 VENTAS_PROPIAS_PERCIBIDO,
0 VENTAS_TERCEROS_NO_SUJETAS,
0 VENTAS_TERCEROS_EXENTA,
0 VENTAS_TERCEROS_GRAVADA,
0 VENTAS_TERCEROS_IVA,
0 VENTAS_TERCEROS_IVA_RETENIDO,
0 VENTAS_TERCEROS_PERCIBIDO,
0 VENTAS_TOTAL,
A.CORR_RUTA_VENTA,
'' NOMBRE_RUTA_VENTA,
'' NOMBRE_MANDANTE,
'' NUMERO_COMPROBANTE,
'' NOMBRE_PUESTO2
FROM V_VEN_DOCUMENTO A
GO
