SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_COTIZACION_CONSULTA]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_SOLI_COTIZACION
      ,A.FECHA_SOLI_COTIZACION
      ,A.FECHA_LIMITE_COTIZACION
      ,A.CODIGO_DEPTO
      ,A.ANIO_PERIODO_SOLI_COMPRA
      ,A.CORR_SOLI_COMPRA
      ,A.USUARIO_SOLI
      ,A.OBSERVACIONES OBSERVACIONES_SOLI_COTIZA
      ,A.ESTADO_SOLI_COTIZACION
	  ,CASE A.ESTADO_SOLI_COTIZACION 
	  WHEN 'DI' THEN 'DIGITADO'
	  WHEN 'SO' THEN 'SOLICITADO'
	  WHEN 'AP' THEN 'APLICADO'
	  WHEN 'AN' THEN 'ANULADO'
	  ELSE '' END NOMBRE_ESTADO_SOLI_COTIZACION
	  ,ISNULL(H.NUMERO_SOLI_COMPRA,'') NUMERO_SOLI_COMPRA
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
      ,B.CORR_COTIZACION
      ,B.FECHA_COTIZACION
      ,B.CORR_PROVEEDOR
	  ,E.CLINAM NOMBRE_PROVEEDOR
      ,B.USUARIO_COTIZA
      ,B.OBSERVACIONES OBSERVACIONES_COTIZA
      ,B.OBSERVACIONES_PROVEEDOR
      ,B.PLAZO_ENTREGA
      ,B.ESTADO_COTIZACION
	  ,CASE B.ESTADO_COTIZACION
	   WHEN 'DI' THEN 'DIGITADO'
	   WHEN 'SO' THEN 'SOLICITADO'
	   WHEN 'AP' THEN 'APLICADO'
	   WHEN 'AN' THEN 'ANULADO'
	   ELSE '' END NOMBRE_ESTADO_COTIZACION
      ,B.USUARIO_CREA USUARIO_CREA_COTIZA
      ,B.FECHA_CREA FECHA_CREA_COTIZA
      ,B.ESTACION_CREA ESTACION_CREA_COTIZA
      ,B.USUARIO_ACTU USUARIO_ACTU_COTIZA
      ,B.FECHA_ACTU FECHA_ACTU_COTIZA
      ,B.ESTACION_ACTU ESTACION_ACTU_COTIZA
	  ,C.CORR_COTIZACION_DETA
      ,C.CODIGO_ITEM
	  ,G.INVDSC NOMBRE_ITEM
      ,C.CANTIDAD
      ,C.CORR_UNIDAD_MEDIDA
	  ,F.NOMBRE_UNIDAD_MEDIDA
      ,C.PRECIO_UNITARIO
      ,C.MONTO_SUBTOTAL
      ,C.OBSERVACIONES
      ,C.MARCA
      ,C.ESTADO_SOLI_COTIZACION ESTADO_COTIZACION_DETA
	  ,CASE C.ESTADO_SOLI_COTIZACION
	   WHEN 'DI' THEN 'DIGITADO'
	   WHEN 'SO' THEN 'SOLICITADO'
	   WHEN 'AP' THEN 'APLICADO'
	   WHEN 'AN' THEN 'ANULADO'
	   ELSE '' END NOMBRE_ESTADO_COTIZACION_DETA
      ,C.USUARIO_CREA USUARIO_CREA_COTIZA_DETA
      ,C.FECHA_CREA FECHA_CREA_COTIZA_DETA
      ,C.ESTACION_CREA ESTACION_CREA_COTIZA_DETA
      ,C.USUARIO_ACTU USUARIO_ACTU_COTIZA_DETA
      ,C.FECHA_ACTU FECHA_ACTU_COTIZA_DETA
      ,C.ESTACION_ACTU ESTACION_ACTU_DETA 
	  ,D.SELECCION
FROM COM_SOLI_COTIZACION A
INNER JOIN COM_COTIZACION B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO_SOLI_COTI AND A.CORR_SOLI_COTIZACION = B.CORR_SOLI_COTIZACION
INNER JOIN COM_COTIZACION_DETA C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO = C.ANIO_PERIODO AND B.CORR_COTIZACION = C.CORR_COTIZACION
INNER JOIN COM_CUADRO_COMPARATIVO_DETA D ON C.CORR_EMPRESA = D.CORR_EMPRESA AND C.ANIO_PERIODO = D.ANIO_PERIODO_COTIZACION AND C.CORR_COTIZACION = D.CORR_COTIZACION AND C.CORR_COTIZACION_DETA = D.CORR_COTIZACION_DETA
INNER JOIN [CLASS_UEES].dbo.CLIENTES E ON B.CORR_PROVEEDOR=E.CLIIDU AND E.CLITIP='V' AND E.CLISTS='A' AND E.CLICAT IN('PN-','PE-','PG-','PP-','PM-','PR-')
INNER JOIN COM_UNIDAD_MEDIDA F ON C.CORR_EMPRESA=F.CORR_EMPRESA AND C.CORR_UNIDAD_MEDIDA=F.CORR_UNIDAD_MEDIDA
INNER JOIN [CLASS_UEES].dbo.INVENTARIOS G ON C.CODIGO_ITEM COLLATE Modern_Spanish_CI_AS=G.INVCOD AND G.INVREG = 'E' AND G.INVSUC='001'
LEFT OUTER JOIN V_COM_SOLI_COTIZACION_SOLI_COMPRA_SUM H ON A.CORR_EMPRESA=H.CORR_EMPRESA AND A.ANIO_PERIODO = H.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION = H.CORR_SOLI_COTIZACION 
GO
