SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_ORDEN_COMPRA]
AS
SELECT DISTINCT 
A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.CORR_CUADRO_COMPARATIVO
,A.NUMERO_ORDEN
,A.CORR_PROVEEDOR
,B.CLINAM NOMBRE_PROVEEDOR
,A.MONTO_TOTAL_ORDEN
,LTRIM(RTRIM(ISNULL(B.CLICTO,''))) NOMBRE_CONTACTO
,A.CORR_CONDICION_PAGO
,C.NOMBRE_CONDICION_PAGO
,D.CORR_FORMA_PAGO
,D.NOMBRE_FORMA_PAGO
,A.DETALLE_FORMA_PAGO
,E.ORDSTO ESTADO_ORDEN_COMPRA
,CASE E.ORDSTS 
WHEN 'P' THEN 'Pendiente de Compra'
WHEN 'A' THEN 'Anulado'
ELSE '' END NOMBRE_ESTADO_ORDEN_COMPRA
FROM COM_CUADRO_COMPARATIVO_ORDEN_COMPRA A
INNER JOIN [CLASS_UEES].dbo.CLIENTES B ON A.CORR_PROVEEDOR=B.CLIIDU
LEFT OUTER JOIN COM_CONDICION_PAGO C ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CORR_CONDICION_PAGO = C.CORR_CONDICION_PAGO
LEFT OUTER JOIN V_GEN_FORMA_PAGO D ON A.CORR_FORMA_PAGO = D.CORR_FORMA_PAGO
INNER JOIN CLASS_UEES.dbo.ORDENCOMPRA E ON A.NUMERO_ORDEN=E.ORDNUM
GO
