SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_TABLAS]
AS
SELECT DISTINCT A.*,B.NOMBRE_MODULO,B.PREFIJO,0 Seleccion
FROM INFORMATION_SCHEMA.TABLES A
INNER JOIN SEG_SISTEMA B ON CASE WHEN CHARINDEX('_',TABLE_NAME)>0 THEN SUBSTRING(TABLE_NAME,1,CHARINDEX('_',TABLE_NAME)-1) ELSE '' END COLLATE Latin1_General_CS_AS=B.PREFIJO COLLATE Latin1_General_CS_AS
WHERE TABLE_TYPE='BASE TABLE'
GO
