SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_PLA_PUESTO]
AS
SELECT
    p.CORR_EMPRESA,
    p.CORR_PUESTO,
    p.NOMBRE_PUESTO,
    p.CORR_GERENCIA,
    g.NOMBRE_GERENCIA,
    gpu.CORR_UNIDAD,
    u.NOMBRE_UNIDAD,
    p.CORR_NIVEL_ACADEMICO,
    na.NOMBRE_NIVEL_ACADEMICO,
    p.CORR_TIPO_PUESTO,
    tp.NOMBRE_TIPO_PUESTO,
    p.ESTADO_PUESTO,
    p.APROBACION_PUESTO,
    p.SALARIO_INICIAL,
    p.SALARIO_FINAL,
    p.USUARIO_VALIDA,
    p.USUARIO_AUTORIZA,
    p.MISION_PUESTO,
    p.OTROS_ASPECTOS,
    p.CODIGO_PUESTO,
    p.CODIGO_FORMATO,
    p.VERSION_FORMATO,
    p.USUARIO_CREA,
    p.ESTACION_CREA,
    p.FECHA_CREA,
    p.USUARIO_ACTU,
    p.ESTACION_ACTU,
    p.FECHA_ACTU
FROM dbo.PLA_PUESTO p
LEFT JOIN dbo.GEN_UNIDADES_PUESTO gpu
    ON gpu.CORR_EMPRESA = p.CORR_EMPRESA
    AND gpu.CORR_PUESTO = p.CORR_PUESTO
LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES u
    ON u.CORR_EMPRESA = gpu.CORR_EMPRESA
    AND u.CORR_UNIDAD = gpu.CORR_UNIDAD
LEFT JOIN dbo.GEN_GERENCIA g
    ON g.CORR_EMPRESA = p.CORR_EMPRESA
    AND g.CORR_GERENCIA = p.CORR_GERENCIA
LEFT JOIN dbo.PLA_NIVEL_ACADEMICO na
    ON na.CORR_EMPRESA = p.CORR_EMPRESA
    AND na.CORR_NIVEL_ACADEMICO = p.CORR_NIVEL_ACADEMICO
LEFT JOIN dbo.PLA_TIPO_PUESTO tp
    ON tp.CORR_EMPRESA = p.CORR_EMPRESA
    AND tp.CORR_TIPO_PUESTO = p.CORR_TIPO_PUESTO
GO
