-- Qué hace: vista de idiomas de una persona (tab Formación de gen-empleado).
-- Cómo lo hace: proyecta GEN_PERSONA_IDIOMAS con los campos del tab.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_IDIOMAS]
AS
SELECT
	I.CORR_EMPRESA,
	I.CORR_PERSONA,
	I.CORR_IDIOMA,
	I.NOMBRE_IDIOMA,
	I.NIVEL_DOMINIO,
	I.USUARIO_CREA,
	I.ESTACION_CREA,
	I.FECHA_CREA,
	I.USUARIO_ACTU,
	I.ESTACION_ACTU,
	I.FECHA_ACTU
FROM dbo.GEN_PERSONA_IDIOMAS AS I;
GO
