SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: lectura de periodos cerrados del puesto del empleado.
-- Cómo lo hace: GEN_EMPLEADO_PUESTO_HISTORIAL con nombres de unidad, puesto, contratación y modalidad.
CREATE OR ALTER VIEW [dbo].[V_GEN_EMPLEADO_PUESTO_HISTORIAL]
AS
SELECT
	H.CORR_EMPRESA,
	H.CORR_EMPLEADO_PUESTO_HISTORIAL,
	H.FECHA_INICIO,
	H.FECHA_FIN,
	H.CORR_EMPLEADO,
	H.CORR_UNIDAD,
	U.CODIGO_UNIDAD,
	U.NOMBRE_UNIDAD,
	H.CORR_PUESTO,
	P.CODIGO_PUESTO,
	P.NOMBRE_PUESTO,
	H.SUELDO,
	H.HORARIO_LABORAL,
	H.CORR_TIPO_CONTRATACION,
	TC.NOMBRE_TIPO_CONTRATACION,
	H.CORR_TIPO_MODALIDAD,
	TM.MODALIDAD_NOMBRE,
	H.USUARIO_CREA,
	H.ESTACION_CREA,
	H.FECHA_CREA,
	H.USUARIO_ACTU,
	H.ESTACION_ACTU,
	H.FECHA_ACTU
FROM dbo.GEN_EMPLEADO_PUESTO_HISTORIAL H
LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES U
	ON U.CORR_EMPRESA = H.CORR_EMPRESA
	AND U.CORR_UNIDAD = H.CORR_UNIDAD
LEFT JOIN dbo.PLA_PUESTO P
	ON P.CORR_EMPRESA = H.CORR_EMPRESA
	AND P.CORR_PUESTO = H.CORR_PUESTO
LEFT JOIN dbo.SC_TIPO_CONTRATACION TC
	ON TC.CORR_EMPRESA = H.CORR_EMPRESA
	AND TC.CORR_TIPO_CONTRATACION = H.CORR_TIPO_CONTRATACION
LEFT JOIN dbo.SC_TIPO_MODALIDAD TM
	ON TM.CORR_EMPRESA = H.CORR_EMPRESA
	AND TM.CORR_TIPO_MODALIDAD = H.CORR_TIPO_MODALIDAD
GO
