-- Qué hace: vista de mantenimiento del catálogo PLA_SEGURO_SOCIAL.
-- Cómo lo hace: proyecta Activo (ISNULL 1) + auditoríaía para browse/CRUD.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_PLA_SEGURO_SOCIAL]
AS
SELECT
	S.CORR_SEGURO_SOCIAL,
	S.NOMBRE_SEGURO_SOCIAL,
	S.NOMBRE_CORTO_SEGURO,
	ISNULL(S.ACTIVO_SEGURO_SOCIAL, 1) AS ACTIVO_SEGURO_SOCIAL,
	S.USUARIO_CREA,
	S.ESTACION_CREA,
	S.FECHA_CREA,
	S.USUARIO_ACTU,
	S.ESTACION_ACTU,
	S.FECHA_ACTU
FROM dbo.PLA_SEGURO_SOCIAL AS S;
GO
