SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: lectura de las firmas guardadas del descriptor de puesto.
-- Cómo lo hace: expone SC_DESCRIPTOR_PUESTO_FIRMAS; el nombre, el actor y la unidad ya van en texto.
CREATE OR ALTER VIEW [dbo].[V_SC_DESCRIPTOR_PUESTO_FIRMAS]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_FIRMAS,
	A.CORR_DESCRIPTOR_PUESTO,
	A.NOMBRE_COMPLETO,
	A.TIPO_JEFE,
	A.TIPO_ACTOR,
	A.FECHA_FIRMA,
	A.USUARIO_CREA,
	A.ESTACION_CREA,
	A.FECHA_CREA,
	A.USUARIO_ACTU,
	A.ESTACION_ACTU,
	A.FECHA_ACTU
FROM dbo.SC_DESCRIPTOR_PUESTO_FIRMAS A;
GO
