SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_PROVEEDOR_USUARIO_SUM]
AS
SELECT A.CORR_PROVEEDOR
,dbo.StrConcat(B.CORREO_ELECTRONICO+',') CORREO_ELECTRONICO
FROM COM_PROVEEDOR_USUARIO A
INNER JOIN SEG_USUARIO B ON A.LOGIN_SISTEMA=B.LOGIN_SISTEMA
GROUP BY A.CORR_PROVEEDOR
GO
