SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_DOCUMENTO_DETA_DOC]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_DOCUMENTO
      ,A.ANIO_PERIODO_DOC
      ,A.MES_PERIODO_DOC
      ,A.CORR_DOCUMENTO_DOC
	  ,CASE WHEN ISNULL(B.NUMERO_CONTROL,'')=''THEN B.NUMERO_DOCUMENTO ELSE B.NUMERO_CONTROL END NUMERO_DOCUMENTO
	  ,C.NOMBRE_TIPO_DOC
	  ,B.FECHA_DOCUMENTO
      ,A.MONTO_DOCUMENTO
      ,A.MONTO_INICIAL
      ,A.MONTO_INGRESO
      ,A.MONTO_FINAL
FROM COM_DOCUMENTO_DETA_DOC A
INNER JOIN COM_DOCUMENTO B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO_DOC=B.ANIO_PERIODO AND A.MES_PERIODO_DOC = B.MES_PERIODO AND A.CORR_DOCUMENTO_DOC = B.CORR_DOCUMENTO
INNER JOIN GEN_TIPO_DOCUMENTO C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.CORR_TIPO_DOC = C.CORR_TIPO_DOC
GO
