-- Qué hace: vista de hijos de una persona (tab Familiares de gen-empleado).
-- Cómo lo hace: proyecta GEN_PERSONA_HIJOS con los campos del tab.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_HIJOS]
AS
SELECT
	H.CORR_EMPRESA,
	H.CORR_PERSONA,
	H.CORR_HIJO,
	H.NOMBRE_COMPLETO,
	H.EDAD,
	H.SEXO,
	H.FECHA_NACIMIENTO,
	H.USUARIO_CREA,
	H.ESTACION_CREA,
	H.FECHA_CREA,
	H.USUARIO_ACTU,
	H.ESTACION_ACTU,
	H.FECHA_ACTU
FROM dbo.GEN_PERSONA_HIJOS AS H;
GO
