SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_SEG_CONFIG_OPCION]
AS
SELECT A.CODIGO_SISTEMA
	  ,B.NOMBRE_SISTEMA
	  ,B.IMAGEN_SISTEMA
      ,A.CODIGO_MENU
      ,C.NOMBRE_MENU
	  ,C.IMAGEN_MENU
      ,A.CODIGO_OPCION
      ,D.NOMBRE_OPCION
	  ,D.IMAGEN_OPCION
	  ,D.URL_OPCION
      ,A.ORDEN_SISTEMA
      ,A.ORDEN_MENU
      ,A.ORDEN_OPCION
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU    
FROM SEG_CONFIG_OPCION A
INNER JOIN SEG_SISTEMA B ON A.CODIGO_SISTEMA=B.CODIGO_SISTEMA
INNER JOIN SEG_MENU_SISTEMA C ON A.CODIGO_MENU=C.CODIGO_MENU
INNER JOIN SEG_OPCION_SISTEMA D ON A.CODIGO_OPCION=D.CODIGO_OPCION
GO
