SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_PAIS]
AS
SELECT CORR_PAIS
      ,NOMBRE_PAIS
      ,CODIGO_PAIS
      ,NACIONALIDAD
      ,NOMBRE_CORTO
      ,USUARIO_CREA
      ,ESTACION_CREA
      ,FECHA_CREA
      ,USUARIO_ACTU
      ,ESTACION_ACTU
      ,FECHA_ACTU
  FROM GEN_PAIS
GO
