SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_BAN_CONCILIA_BANCARIA_MOVI]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CUENTA_BANCO
      ,A.CORR_CONCILIACION
      ,A.CORR_MOVIMIENTO
      ,A.CORR_LINEA
      ,B.NOMBRE_LINEA_TRABAJO 
      ,B.AUMENTA_DISMINUYE 
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,A.CORR_PARTIDA
      ,A.CORR_PARTIDA_DETA
      ,ISNULL(D.NOMBRE_TRAN,'') NOMBRE_TRAN
      ,ISNULL(E.NOMBRE_CLASE_PARTIDA,'') NOMBRE_CLASE_PARTIDA
      ,ISNULL(E.NUMERO_DOCUMENTO,'') NUMERO_DOCUMENTO
      ,A.CORR_TIPO_MOVIMIENTO
      ,ISNULL(C.NOMBRE_TIPO_MOVIMIENTO,'') NOMBRE_TIPO_MOVIMIENTO
      ,A.CORR_CONCILIACION_DETA
      ,A.MONTO_CARGO
      ,A.MONTO_ABONO
      ,ISNULL(F.NUMERO_REFERENCIA_BANCO,'') NUMERO_REFERENCIA_BANCO
      ,ISNULL(F.FECHA_MOVIMIENTO,E.FECHA_PARTIDA) FECHA_MOVIMIENTO
      ,A.MONTO_CARGO+A.MONTO_ABONO MONTO
  FROM BAN_CONCILIA_BANCARIA_MOVI A
  INNER JOIN BAN_LINEA_TRABAJO_CONCILIACION B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_LINEA=B.CORR_LINEA 
  LEFT OUTER JOIN V_BAN_TIPO_MOVI_BANCARIO C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO=C.CORR_TIPO_MOVIMIENTO 
  LEFT OUTER JOIN V_CON_PARTIDA_DETA D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.ANIO_PERIODO=D.ANIO_PERIODO AND A.MES_PERIODO=D.MES_PERIODO AND A.CORR_CLASE_PARTIDA=D.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=D.CORR_PARTIDA AND A.CORR_PARTIDA_DETA=D.CORR_PARTIDA_DETA 
  LEFT OUTER JOIN V_CON_PARTIDA E ON D.CORR_EMPRESA=E.CORR_EMPRESA AND D.ANIO_PERIODO=E.ANIO_PERIODO AND D.MES_PERIODO=E.MES_PERIODO AND D.CORR_CLASE_PARTIDA=E.CORR_CLASE_PARTIDA AND D.CORR_PARTIDA=E.CORR_PARTIDA 
  LEFT OUTER JOIN BAN_CONCILIA_BANCARIA_DETA F ON A.CORR_EMPRESA=F.CORR_EMPRESA AND A.CORR_CONCILIACION=F.CORR_CONCILIACION AND A.CORR_CONCILIACION_DETA=F.CORR_CONCILIACION_DETA
GO

