
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_PARTIDA_INICIAL]
AS
SELECT A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.MES_PERIODO
,B.CUENTA_CONTABLE
,B.CORR_AUXILIAR
,B.CORR_CENTRO_COSTO
,SUM(B.MONTO_CARGO)-SUM(B.MONTO_ABONO) SALDO_INICIAL
,SUM(B.MONTO_CARGO_FORANEA)-SUM(B.MONTO_ABONO_FORANEA) SALDO_INICIAL_FORANEA
,(CASE WHEN D.ES_DEBE=1 THEN 1 ELSE CASE WHEN D.ES_HABER=1 THEN -1 ELSE 0 END END) ES_DEBE_HABER
FROM CON_PARTIDA A
INNER JOIN CON_PARTIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
INNER JOIN CON_CLASE_PARTIDA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_CLASE_PARTIDA=C.CORR_CLASE_PARTIDA
INNER JOIN CON_CATALOGO_CUENTA D ON B.CORR_EMPRESA=D.CORR_EMPRESA AND B.CUENTA_CONTABLE=D.CUENTA_CONTABLE
WHERE C.NOMBRE_CORTO_CLASE='APE'
AND A.ESTADO_PARTIDA='AP'
--AND A.MES_PERIODO=1 --No solo en enero puede haber una partida de apertura
GROUP BY A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.MES_PERIODO
,B.CUENTA_CONTABLE
,B.CORR_AUXILIAR
,B.CORR_CENTRO_COSTO
,CASE WHEN D.ES_DEBE=1 THEN 1 ELSE CASE WHEN D.ES_HABER=1 THEN -1 ELSE 0 END END
GO
