SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SEG_USUARIO_EMPRESA]
AS
SELECT A.LOGIN_SISTEMA
      ,B.CORR_EMPRESA
      ,B.NOMBRE_EMPRESA
      ,A.POR_DEFECTO
FROM SEG_USUARIO_EMPRESA A
INNER JOIN GEN_EMPRESA B ON A.CORR_EMPRESA=B.CORR_EMPRESA
GO
