SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_DOCUMENTO_ELECTRONICO]
AS
SELECT 
       CORR_EMPRESA,
       ANIO_PERIODO,
       MES_PERIODO,
       CORR_DOCUMENTO,
       CORR_TIPO_DOC,
       NUMERO_DOCUMENTO,
       FECHA_DOCUMENTO,
       FECHA_VENCIMIENTO,
       CORR_TIENDA,
       CORR_PROVEEDOR,
       NOMBRE_PROVEEDOR,
       DESCRIPCION_PARTIDA,
       CORR_CONDICION_PAGO,
       DIAS_CREDITO,
       ESTADO_DOCUMENTO,
       ESTA_CONTABILIZADO,
       TOTAL_DOCUMENTO,
       TOTAL_NETO,
       SALDO_DOCUMENTO,
       USUARIO_CREA,
       FECHA_CREA,
       ESTACION_CREA,
       USUARIO_ACTU,
       FECHA_ACTU,
       ESTACION_ACTU,
       CORR_TIPO_GASTO,
       CORR_TIPO_PAGO,
       CANTIDAD,
       CORR_MOVIMIENTO,
       ESTA_PROVISIONADO,
       CORR_MONEDA,
       FACTOR_CAMBIO,
       OPERADOR,
       SERIE,
       NUMERO_UNICO,
       CODIGO_GENERACION,
       NUMERO_CONTROL,
       SELLO_RECEPCION,
	   CONVERT(BIT,0)SELECCION,
	   CONVERT(INT,0)CORR_EMPRESA_FE,
	   CONVERT(INT,0)CORR_DOCUMENTO_FE
FROM COM_DOCUMENTO

GO
