SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DISPONIBILIDAD_HORARIO]
AS
SELECT CORR_EMPRESA
      ,CORR_DISPONIBILIDAD_HORARIO
      ,NOMBRE_DISPONIBILIDAD_HORARIO
      ,ESTADO_DISPONIBILIDAD_HORARIO
      ,USUARIO_CREA
      ,FECHA_CREA
      ,ESTACION_CREA
      ,USUARIO_ACTU
      ,FECHA_ACTU
      ,ESTACION_ACTU
  FROM SC_DISPONIBILIDAD_HORARIO

GO
