SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_DOCUMENTO_FISICO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_DOCUMENTO
      ,A.NOMBRE_DOCUMENTO
      ,A.DESCRIPCION_DOCUMENTO
      ,A.CORR_TIPO_DOCUMENTO
	  ,B.NOMBRE_TIPO_DOCUMENTO
      ,A.RUTA_DOCUMENTO
      ,A.NOMBRE_ARCHIVO
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
FROM COM_DOCUMENTO_FISICO A
INNER JOIN COM_TIPO_DOC_FISICO B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_DOCUMENTO = B.CORR_TIPO_DOCUMENTO
GO
