SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_BAN_ENTREGA_CHEQUES]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_TIPO_MOVIMIENTO
      ,A.CORR_DOCUMENTO
      ,A.FECHA_EMISION
      ,C.CORR_BANCO
      ,C.NOMBRE_BANCO
      ,A.NUMERO_DOCUMENTO
      ,A.MONTO_DOCUMENTO
      ,A.NOMBRE_BENEFICIARIO
      ,ISNULL(A.ESTADO_ENTREGA,'EF') ESTADO_ENTREGA
      ,CASE ISNULL(A.ESTADO_ENTREGA,'EF')
       WHEN 'AC' THEN 'Activo'
       WHEN 'EF' THEN 'En Firma'
       WHEN 'EN' THEN 'Entregado'
       ELSE '' END NOMBRE_ESTADO_ENTREGA
      ,A.FECHA_ENTREGA
      ,ISNULL(A.NOMBRE_RECIBE,'') NOMBRE_RECIBE
FROM dbo.BAN_DOCUMENTO A
INNER JOIN dbo.BAN_CUENTA_BANCARIA B
  ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_CUENTA_BANCO = B.CORR_CUENTA_BANCO
INNER JOIN dbo.GEN_BANCO C
  ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.CORR_BANCO = C.CORR_BANCO
INNER JOIN dbo.BAN_TIPO_MOVI_BANCARIO D
  ON A.CORR_EMPRESA = D.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO = D.CORR_TIPO_MOVIMIENTO
WHERE D.CLASE_MOVIMIENTO = 'CHQ'
GO
