SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_COMPETENCIAS_CONDUCTUALES]
AS
SELECT
  A.[CORR_EMPRESA],
  A.[CORR_COMPETENCIAS_CONDUCTUALES],
  A.[CORR_TIPO_PUESTO],
  A.[CODIGO_COMPETENCIAS_TECNICAS],
  A.[NOMBRE_COMPETENCIAS_TECNICAS],
  A.[DESCRIPCION],
  A.[ESTADO_COMPETENCIAS_CONDUCTUALES],
  A.[USUARIO_CREA],
  A.[ESTACION_CREA],
  A.[FECHA_CREA],
  A.[USUARIO_ACTU],
  A.[ESTACION_ACTU],
  A.[FECHA_ACTU],
  P.[NOMBRE_TIPO_PUESTO]
FROM [dbo].[SC_COMPETENCIAS_CONDUCTUALES] A
LEFT JOIN [dbo].[PLA_TIPO_PUESTO] P
  ON A.[CORR_EMPRESA] = P.[CORR_EMPRESA]
 AND A.[CORR_TIPO_PUESTO] = P.[CORR_TIPO_PUESTO]
GO
