SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: jefes activos por unidad con nombre, login y puesto vigente.
-- Cómo lo hace: SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES + GEN_EMPLEADO +
--               GEN_PERSONA_NATURAL / GEN_PERSONA_USUARIO + puesto más reciente.
CREATE OR ALTER VIEW [dbo].[V_SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES]
AS
SELECT
	J.CORR_EMPRESA,
	J.CORR_JEFE,
	J.CORR_UNIDAD,
	U.NOMBRE_UNIDAD,
	J.CORR_EMPLEADO,
	ISNULL(PN.NOMBRE_COMPLETO, N'') AS NOMBRE_EMPLEADO,
	PU.LOGIN_SISTEMA AS LOGIN_SISTEMA_WEB,
	J.FECHA_INICIO,
	J.FECHA_FIN,
	J.ACTIVO,
	EP.CORR_PUESTO,
	PP.NOMBRE_PUESTO
FROM dbo.SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES J
INNER JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES U
	ON U.CORR_UNIDAD = J.CORR_UNIDAD
   AND U.CORR_EMPRESA = J.CORR_EMPRESA
INNER JOIN dbo.GEN_EMPLEADO GE
	ON GE.CORR_EMPLEADO = J.CORR_EMPLEADO
   AND GE.CORR_EMPRESA = J.CORR_EMPRESA
LEFT JOIN dbo.GEN_PERSONA_NATURAL PN
	ON PN.CORR_PERSONA = GE.CORR_PERSONA
OUTER APPLY
(
	SELECT TOP (1) X.LOGIN_SISTEMA
	FROM dbo.GEN_PERSONA_USUARIO X
	WHERE X.CORR_PERSONA = GE.CORR_PERSONA
	ORDER BY X.LOGIN_SISTEMA
) PU
OUTER APPLY
(
	SELECT TOP (1) EPP.CORR_PUESTO
	FROM dbo.GEN_EMPLEADO_PUESTO EPP
	WHERE EPP.CORR_EMPRESA = J.CORR_EMPRESA
	  AND EPP.CORR_EMPLEADO = J.CORR_EMPLEADO
	ORDER BY
		EPP.FECHA_INGRESO DESC,
		EPP.FECHA_CREA DESC,
		EPP.CORR_PUESTO DESC
) EP
LEFT JOIN dbo.PLA_PUESTO PP
	ON PP.CORR_EMPRESA = J.CORR_EMPRESA
   AND PP.CORR_PUESTO = EP.CORR_PUESTO
WHERE J.ACTIVO = 1;
GO
