SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_IMPR]
AS
SELECT A.CORR_EMPRESA
	   ,I.NOMBRE_EMPRESA
       ,A.ANIO_PERIODO
       ,A.CORR_CUADRO_COMPARATIVO
       ,A.FECHA_CUADRO_COMPARATIVO
       ,A.ESTADO_CUADRO_COMPARATIVO
       ,A.USUARIO_CUADRO_COMPARATIVO
       ,A.OBSERVACIONES
       ,A.ES_MEJOR_PRECIO
       ,A.TIENE_CREDITO_30_DIAS
       ,A.TIENE_BUEN_SOPORTE_TECNICO
       ,A.TIENE_BUENA_CALIDAD_PRODUCTO
       ,A.TIENE_MEJOR_TIEMPO_ENTREGA
       ,A.BRINDA_BUENA_EXPERIENCIA_PROVEEDOR
       ,A.ES_PROVEEDOR_UNICO
       ,A.EXISTE_OTRA_RAZON
       ,A.NOMBRE_OTRA_RAZON
       ,0 ANIO_PERIODO_SOLI_COTI
       ,0 CORR_SOLI_COTIZACION
	   ,'' NOMBRE_DEPARTAMENTO
       ,A.USUARIO_CREA
       ,B.ANIO_PERIODO_COTIZACION
       ,B.CORR_COTIZACION
       ,B.CORR_COTIZACION_DETA
       ,B.SELECCION 
	   ,F.CODIGO_ITEM
	   ,G.INVDSC NOMBRE_ITEM
	   ,F.CORR_UNIDAD_MEDIDA
	   ,H.NOMBRE_UNIDAD_MEDIDA
	   ,F.CANTIDAD
	   ,F.PRECIO_UNITARIO
	   ,F.MONTO_SUBTOTAL
	   ,F.MARCA
	   ,CONVERT(VARCHAR(55),'') PERIODO
	   ,I.LOGO_1 LOGO1
	   ,I.LOGO_2 LOGO2
	   ,CONVERT(VARCHAR(255),'CUADRO RESUMEN COMPARATIVO DE PRECIOS') TITULO_REPORTE
	   ,CONVERT(VARCHAR(255),'e-Admin FE Ver. 1.0') NOMBRE_SISTEMA
	   ,CONVERT(DATETIME,GETDATE()) FECHA_IMPRESION
	   ,CONVERT(DECIMAL,0)MONTO_ASIGNADO_PROVEEDOR1
	   ,CONVERT(DECIMAL,0)MONTO_ASIGNADO_PROVEEDOR2
	   ,CONVERT(DECIMAL,0)MONTO_ASIGNADO_PROVEEDOR3
	   ,CONVERT(VARCHAR,'') USUARIO_REVISA
	   ,CONVERT(VARCHAR,'') GERENTE_CONTABILIDAD
	   ,CONVERT(VARCHAR,'') GERENTE_GENERAL
	   ,CONVERT(VARCHAR,'') RECTOR
FROM COM_CUADRO_COMPARATIVO A
INNER JOIN COM_CUADRO_COMPARATIVO_DETA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = B.CORR_CUADRO_COMPARATIVO
--INNER JOIN CLASS_UEES.dbo.CODIGOS E ON E.CODCOD = D.CODIGO_DEPTO COLLATE Modern_Spanish_CI_AS AND E.CODREL = 'DPTOS'
INNER JOIN COM_COTIZACION_DETA F ON B.CORR_EMPRESA = F.CORR_EMPRESA AND B.ANIO_PERIODO_COTIZACION = F.ANIO_PERIODO AND B.CORR_COTIZACION = F.CORR_COTIZACION AND B.CORR_COTIZACION_DETA = F.CORR_COTIZACION_DETA
INNER JOIN [CLASS_UEES].dbo.INVENTARIOS G ON G.INVCOD = F.CODIGO_ITEM COLLATE Modern_Spanish_CI_AS AND G.INVREG = 'E' AND G.INVSUC='001'
INNER JOIN COM_UNIDAD_MEDIDA H ON F.CORR_EMPRESA = H.CORR_EMPRESA AND F.CORR_UNIDAD_MEDIDA = H.CORR_UNIDAD_MEDIDA
INNER JOIN GEN_EMPRESA I ON A.CORR_EMPRESA = I.CORR_EMPRESA
GO
