SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_GEN_CLIENTE]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_CLIENTE,
	A.CODIGO_CLIENTE,
	A.NOMBRE_CLIENTE,
	ISNULL(A.NOMBRE_CONTACTO, N'') AS NOMBRE_CONTACTO,
	ISNULL(A.DUI, N'') AS DUI,
	ISNULL(A.NIT, N'') AS NIT,
	ISNULL(A.TELEFONO_1, N'') AS TELEFONO_1,
	ISNULL(A.CORREO_ELECTRONICO, N'') AS CORREO_ELECTRONICO,
	ISNULL(A.ESTA_ACTIVO, 1) AS ESTA_ACTIVO,
	CASE ISNULL(A.ESTA_ACTIVO, 1)
		WHEN 1 THEN N'Activo'
		ELSE N'Inactivo'
	END AS NOMBRE_ESTADO_CLIENTE,
	A.USUARIO_CREA,
	A.FECHA_CREA,
	A.ESTACION_CREA,
	A.USUARIO_ACTU,
	A.FECHA_ACTU,
	A.ESTACION_ACTU
FROM dbo.GEN_CLIENTE A
GO
