
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_BAN_MOVIMIENTO]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CUENTA_BANCO
      ,B.NOMBRE_CUENTA_BANCO NUMERO_CUENTA_BANCO
      ,A.CORR_MOVIMIENTO
      ,A.FECHA_MOVIMIENTO
      ,A.CORR_TIPO_MOVIMIENTO
      ,C.NOMBRE_TIPO_MOVIMIENTO 
      ,C.CLASE_MOVIMIENTO
      ,A.REFERENCIA
      ,A.NOMBRE_BENEFICIARIO
      ,A.DESCRIPCION_MOVIMIENTO
      ,A.MONTO_CARGO
      ,A.MONTO_ABONO
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
	  ,ISNULL(A.ANIO_PERIODO_DOC,A.ANIO_PERIODO) ANIO_PERIODO_DOC
	  ,ISNULL(A.MES_PERIODO_DOC,A.MES_PERIODO) MES_PERIODO_DOC
      ,A.CORR_DOCUMENTO
      ,D.NUMERO_DOCUMENTO
FROM BAN_MOVIMIENTO A 
INNER JOIN V_BAN_CUENTA_BANCARIA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=B.CORR_CUENTA_BANCO
INNER JOIN BAN_TIPO_MOVI_BANCARIO C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO=C.CORR_TIPO_MOVIMIENTO
LEFT OUTER JOIN BAN_DOCUMENTO D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND ISNULL(A.ANIO_PERIODO_DOC,A.ANIO_PERIODO)=D.ANIO_PERIODO AND ISNULL(A.MES_PERIODO_DOC,A.MES_PERIODO)=D.MES_PERIODO AND A.CORR_TIPO_MOVIMIENTO=D.CORR_TIPO_MOVIMIENTO AND A.CORR_DOCUMENTO=D.CORR_DOCUMENTO
GO

