SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_PARTIDA_DETA_DOC_SUM]
AS
SELECT A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.MES_PERIODO
,A.CORR_CLASE_PARTIDA
,A.CORR_PARTIDA
,A.CORR_PARTIDA_DETA
,RTRIM(dbo.StrConcat(DISTINCT A.TIPO_DOCUMENTO)+' ') TIPO_DOCUMENTO
,RTRIM(dbo.StrConcat(DISTINCT CONVERT(VARCHAR,A.NUMERO_DOCUMENTO)+' ')) NUMERO_DOCUMENTO
FROM V_CON_PARTIDA_DETA_DOC A
GROUP BY A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.MES_PERIODO
,A.CORR_CLASE_PARTIDA
,A.CORR_PARTIDA
,A.CORR_PARTIDA_DETA

GO
