
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_BAN_CONCILIA_BANCARIA_IMPRIME]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CUENTA_BANCO
      ,B.NUMERO_CUENTA_BANCO 
      ,B.NOMBRE_CUENTA_BANCO 
      ,B.NOMBRE_TIPO_CUENTA_BANCO 
      ,B.CUENTA_CONTABLE 
      ,A.CORR_CONCILIACION
      ,A.FECHA_CONCILIACION
      ,A.SALDO_CUENTA_BANCO
      ,A.SALDO_CUENTA_CONTA
      ,A.ESTADO_CONCILIACION
      ,CASE A.ESTADO_CONCILIACION 
		  WHEN 'DI' THEN 'Digitada'
		  WHEN 'AP' THEN 'Aplicada'
		  WHEN 'AN' THEN 'Anulada'
		  END NOMBRE_ESTADO_CONCILIACION
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
	  ,dbo.NOMBRE_MES(MONTH(A.FECHA_CONCILIACION)) MES
	  ,MONTH(A.FECHA_CONCILIACION) MES_PERIODO
  FROM BAN_CONCILIA_BANCARIA A
  INNER JOIN V_BAN_CUENTA_BANCARIA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=B.CORR_CUENTA_BANCO

GO

