
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[V_CON_PARTIDA_APLICAR]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,B.NOMBRE_CORTO_CLASE 
      ,A.CORR_PARTIDA
      ,A.NUMERO_DOCUMENTO
      ,A.FECHA_PARTIDA
      ,A.NOMBRE_PARTIDA
      ,A.ESTADO_PARTIDA
      ,A.NOMBRE_ESTADO_PARTIDA
      ,ISNULL(SUM(C.MONTO_CARGO),0) MONTO_CARGO
      ,ISNULL(SUM(C.MONTO_ABONO),0) MONTO_ABONO
      ,CONVERT(bit,0) APLICAR
FROM V_CON_PARTIDA A
INNER JOIN CON_CLASE_PARTIDA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA 
LEFT OUTER JOIN CON_PARTIDA_DETA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.ANIO_PERIODO=C.ANIO_PERIODO AND A.MES_PERIODO=C.MES_PERIODO AND A.CORR_CLASE_PARTIDA=C.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=C.CORR_PARTIDA 
GROUP BY A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,B.NOMBRE_CORTO_CLASE 
      ,A.CORR_PARTIDA
      ,A.NUMERO_DOCUMENTO
      ,A.FECHA_PARTIDA
      ,A.NOMBRE_PARTIDA
      ,A.ESTADO_PARTIDA
      ,A.NOMBRE_ESTADO_PARTIDA

GO
