
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[V_CON_CATALOGO_CUENTA_CENTRO_COSTO]
AS
SELECT A.CORR_EMPRESA
      ,A.CUENTA_CONTABLE
      ,A.CORR_CENTRO_COSTO
      ,B.NOMBRE_CENTRO
      ,C.NOMBRE_TIPO_CENTRO_COSTO
  FROM CON_CATALOGO_CUENTA_CENTRO_COSTO A
  INNER JOIN CON_CENTRO_COSTO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CENTRO_COSTO=B.CORR_CENTRO_COSTO
  LEFT OUTER JOIN CON_TIPO_CENTRO_COSTO C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_TIPO_CENTRO_COSTO=C.CORR_TIPO_CENTRO_COSTO


GO
