SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_IMPUESTO_DETALLE_VENTAS_CF]
AS
SELECT CONVERT(DATE, '') FECHA_EMISION,
	CONVERT(INT, 0) CLASE_DOCUMENTO,
	CONVERT(INT, 0) TIPO_DOCUMENTO,
	CONVERT(VARCHAR, '') NUMERO_RESOLUCION,
	CONVERT(VARCHAR, '') NUMERO_SERIE,
	CONVERT(INT, 0) NUMERO_CONTROL_INTERNO_DEL,
	CONVERT(INT, 0) NUMERO_CONTROL_INTERNO_AL,
	CONVERT(INT, 0) NUMERO_DOCUMENTO_DEL,
	CONVERT(INT, 0) NUMERO_DOCUMENTO_AL,
	CONVERT(VARCHAR, '') NUMERO_MAQUINA_REG,
	CONVERT(DECIMAL(18,2), 0) VENTAS_EXENTAS,
	CONVERT(DECIMAL(18,2), 0) VENTAS_INTERNAS_EXENTAS_NO_SUJETAS,
	CONVERT(DECIMAL(18,2), 0) VENTAS_NO_SUJETAS,
	CONVERT(DECIMAL(18,2), 0) VENTAS_GRAVADAS,
	CONVERT(DECIMAL(18,2), 0) EXPORTACIONES_DENTRO_CA,
	CONVERT(DECIMAL(18,2), 0) EXPORTACIONES_FUERA_CA,
	CONVERT(DECIMAL(18,2), 0) EXPORTACIONES_SERVICIOS,
	CONVERT(DECIMAL(18,2), 0) VENTA_ZONA_FRANCA_DPA,
	CONVERT(DECIMAL(18,2), 0) VENTA_TERCERO_NO_DOMICILIADOS,
	CONVERT(DECIMAL(18,2), 0) TOTAL_VENTAS,
	CONVERT(INT, 0) NUMERO_ANEXO
FROM VEN_DOCUMENTO
GO
