SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SYS_INSTANCIA_REMOTA]
AS
SELECT
	A.CODIGO_INSTANCIA,
	A.NOMBRE_LINKED_SERVER,
	A.DESCRIPCION,
	A.SERVIDOR,
	A.NOMBRE_BASE_DATOS,
	A.USUARIO_SQL,
	A.PROVEEDOR_OLEDB,
	A.TRUST_SERVER_CERTIFICATE,
	A.RPC_HABILITADO,
	A.ACTIVO,
	A.USUARIO_ACTU,
	A.FECHA_ACTU,
	A.ESTACION_ACTU
FROM dbo.SYS_INSTANCIA_REMOTA A
GO
