SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_JSON_DOC]
AS
SELECT A.CORR_EMPRESA,
A.CORR_DOCUMENTO,
A.CORR_DOCUMENTO_DOC,
NULL FOTO_DOCUMENTO
FROM [e-AdminFE].dbo.COM_JSON_DOC A
INNER JOIN [e-AdminFE].dbo.GEN_DOCUMENTO_FISICO B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_DOCUMENTO_DOC=B.CORR_DOCUMENTO
GO
