SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_DEPTO]
AS
SELECT RTRIM(LTRIM(A.PROCOD)) CODIGO_DEPTO
,RTRIM(LTRIM(A.PRODSC)) NOMBRE_DEPTO
FROM [CLASS_UEES].dbo.PROVINCIAS A
WHERE PROREG='P' 

GO
