SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: catálogo de puestos para API y SPA (V_PLA_PUESTO).
-- Cómo lo hace: PLA_PUESTO + nombre del tipo de puesto. Sin gerencia, unidad, nivel ni salarios.
CREATE OR ALTER VIEW [dbo].[V_PLA_PUESTO]
AS
SELECT
	p.CORR_EMPRESA,
	p.CORR_PUESTO,
	p.CODIGO_PUESTO,
	p.NOMBRE_PUESTO,
	p.CORR_TIPO_PUESTO,
	tp.NOMBRE_TIPO_PUESTO,
	p.ACTIVO_PUESTO,
	p.APROBACION_PUESTO,
	p.MISION_PUESTO,
	p.OTROS_ASPECTOS,
	p.USUARIO_CREA,
	p.ESTACION_CREA,
	p.FECHA_CREA,
	p.USUARIO_ACTU,
	p.ESTACION_ACTU,
	p.FECHA_ACTU
FROM dbo.PLA_PUESTO p
LEFT JOIN dbo.PLA_TIPO_PUESTO tp
	ON tp.CORR_EMPRESA = p.CORR_EMPRESA
	AND tp.CORR_TIPO_PUESTO = p.CORR_TIPO_PUESTO
GO
