SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SEG_USUARIO_FOTO]
AS
SELECT A.LOGIN_SISTEMA	  
      ,A.CLASE_FOTO
	  ,CASE A.CLASE_FOTO
	  WHEN 'PE' THEN 'PERFIL'
	  WHEN 'FI' THEN 'FIRMA'
	  ELSE '' END NOMBRE_CLASE_FOTO
	  ,A.FOTO
FROM SEG_USUARIO_FOTO A
GO
