SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COLUMNAS_UPD]
AS
SELECT T1.* FROM INFORMATION_SCHEMA.COLUMNS T1
WHERE NOT EXISTS(SELECT 1 FROM V_LLAVES T2
WHERE T1.TABLE_SCHEMA=T2.TABLE_SCHEMA 
AND T1.TABLE_CATALOG=T2.TABLE_CATALOG 
AND T1.TABLE_NAME=T2.TABLE_NAME 
AND T1.COLUMN_NAME=T2.COLUMN_NAME)
AND T1.COLUMN_NAME NOT IN('USUARIO_CREA','FECHA_CREA','ESTACION_CREA')
GO
