
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_CATALOGO_CUENTA]
AS
SELECT A.CORR_EMPRESA
      ,A.CUENTA_CONTABLE
      ,A.NOMBRE_CUENTA
      ,A.ES_DEBE
      ,A.ES_HABER
      ,A.ES_DETALLE
      ,A.NIVEL
      ,ISNULL(A.CUENTA_MAYOR,'') CUENTA_MAYOR
      ,ISNULL(C.NOMBRE_CUENTA,'') NOMBRE_CUENTA_MAYOR
      ,A.CODIGO_RUBRO
      ,B.NOMBRE_RUBRO
      ,A.NO_HABILITADA
      ,ISNULL(A.CLASE_RUBRO,'') CLASE_RUBRO
      ,CASE ISNULL(A.CLASE_RUBRO,'')
      WHEN 'AC' THEN 'Activo'
      WHEN 'PA' THEN 'Pasivo'
      WHEN 'PT' THEN 'Patrimonio'
      WHEN 'IN' THEN 'Ingreso'
      WHEN 'GA' THEN 'Gasto'
      WHEN 'LI' THEN 'Liquidadora'
      WHEN 'OT' THEN 'Otra'
      ELSE '' END NOMBRE_CLASE_RUBRO
      ,ISNULL(A.ES_LIQUIDADORA,0) ES_LIQUIDADORA
      ,ISNULL(A.CLASE_VALUACION,'') CLASE_VALUACION
      ,CASE ISNULL(A.CLASE_VALUACION,'')
      WHEN 'HIS' THEN 'Historica'
      WHEN 'PRO' THEN 'Promedio'
      WHEN 'CIE' THEN 'Cierre Mes'
      WHEN 'INT' THEN 'Moneda Internacional'
	  WHEN 'SVA' THEN 'Sin ValuaciÃ³n'
      ELSE '' END NOMBRE_CLASE_VALUACION
FROM CON_CATALOGO_CUENTA A 
INNER JOIN CON_RUBRO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CODIGO_RUBRO=B.CODIGO_RUBRO
LEFT OUTER JOIN CON_CATALOGO_CUENTA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_MAYOR=C.CUENTA_CONTABLE
GO
