SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_IMPUESTO_F14]
AS
SELECT CONVERT(INT, 0) DOMICILIADO,
	CONVERT(INT, 0) CODIGO_PAIS,
	CONVERT(VARCHAR, '') NOMBRE_PERSONA,
	CONVERT(VARCHAR, '') NIT,
	CONVERT(VARCHAR, '') DUI,
	CONVERT(INT, 0) CODIGO_INGRESO,
	CONVERT(DECIMAL(18,2), 0) MONTO_DEVENGADO,
	CONVERT(DECIMAL(18,2), 0) MONTO_BONIFICACION,
	CONVERT(DECIMAL(18,2), 0) IMPUESTO_RENTA,
	CONVERT(DECIMAL(18,2), 0) MONTO_AGUINALDO_EXCENTO,
	CONVERT(DECIMAL(18,2), 0) MONTO_AGUINALDO_GRAVADO,
	CONVERT(DECIMAL(18,2), 0) MONTO_AFP,
	CONVERT(DECIMAL(18,2), 0) MONTO_ISSS,
	CONVERT(DECIMAL(18,2), 0) MONTO_INPEP,
	CONVERT(DECIMAL(18,2), 0) MONTO_IPSFA,
	CONVERT(DECIMAL(18,2), 0) MONTO_CEFAFA,
	CONVERT(DECIMAL(18,2), 0) MONTO_BM,
	CONVERT(DECIMAL(18,2), 0) ISSS_IVM,
	CONVERT(DATE, '') PERIODO
FROM PLA_DOCUMENTO
GO
