-- Qué hace: vista de persona natural para tab Personales de gen-empleado.
-- Cómo lo hace: proyecta GEN_PERSONA_NATURAL + nombres de catálogos asociados.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_NATURAL]
AS
SELECT
	A.CORR_PERSONA,
	A.CORR_PERSONA_NATURAL,
	A.PRIMER_NOMBRE,
	A.SEGUNDO_NOMBRE,
	A.PRIMER_APELLIDO,
	A.SEGUNDO_APELLIDO,
	A.APELLIDO_CASADA,
	A.NOMBRE_COMPLETO,
	A.FOTO_URL,
	A.SEXO,
	A.ESTADO_CIVIL,
	A.NACIONALIDAD,
	A.EDAD,
	A.FECHA_NACIMIENTO,
	A.ES_JUBILADO,
	A.POSEE_DISCAPACIDAD,
	A.TIPO_DISCAPACIDAD,
	A.CORR_RELIGION,
	R.NOMBRE_RELIGION,
	A.IGLESIA_CONGREGA,
	A.CARTA_PASTORAL,
	A.ES_EXTRANJERO,
	A.DOMICILIADO,
	A.CORR_PAIS_NACIMIENTO,
	P.NOMBRE_PAIS AS NOMBRE_PAIS_NACIMIENTO,
	A.CORR_DEPTO_NACIMIENTO,
	D.NOMBRE_DEPTO AS NOMBRE_DEPTO_NACIMIENTO,
	A.CORR_MUNICIPIO_NACIMIENTO,
	M.NOMBRE_MUNICIPIO AS NOMBRE_MUNICIPIO_NACIMIENTO,
	A.CORR_DISTRITO_NACIMIENTO,
	DI.NOMBRE_DISTRITO AS NOMBRE_DISTRITO_NACIMIENTO,
	A.CORR_ORIGEN_INGRESO,
	OI.NOMBRE_ORIGEN_INGRESO,
	A.CORR_TIPO_CONTRIBUYENTE,
	TC.NOMBRE_TIPO_CONTRIBUYENTE,
	A.CORR_ACTIVIDAD_ECONOMICA,
	AE.NOMBRE_ACTIVIDAD_ECONOMICA,
	A.USUARIO_CREA,
	A.ESTACION_CREA,
	A.FECHA_CREA,
	A.USUARIO_ACTU,
	A.ESTACION_ACTU,
	A.FECHA_ACTU
FROM dbo.GEN_PERSONA_NATURAL AS A
LEFT JOIN dbo.GEN_RELIGION AS R
	ON R.CORR_RELIGION = A.CORR_RELIGION
LEFT JOIN dbo.GEN_PAIS AS P
	ON P.CORR_PAIS = A.CORR_PAIS_NACIMIENTO
LEFT JOIN dbo.GEN_DEPTO AS D
	ON D.CORR_PAIS = A.CORR_PAIS_NACIMIENTO
	AND D.CORR_DEPTO = A.CORR_DEPTO_NACIMIENTO
LEFT JOIN dbo.GEN_MUNICIPIO AS M
	ON M.CORR_PAIS = A.CORR_PAIS_NACIMIENTO
	AND M.CORR_DEPTO = A.CORR_DEPTO_NACIMIENTO
	AND M.CORR_MUNICIPIO = A.CORR_MUNICIPIO_NACIMIENTO
LEFT JOIN dbo.GEN_DISTRITO AS DI
	ON DI.CORR_PAIS = A.CORR_PAIS_NACIMIENTO
	AND DI.CORR_DEPTO = A.CORR_DEPTO_NACIMIENTO
	AND DI.CORR_MUNICIPIO = A.CORR_MUNICIPIO_NACIMIENTO
	AND DI.CORR_DISTRITO = A.CORR_DISTRITO_NACIMIENTO
LEFT JOIN dbo.GEN_ORIGEN_INGRESO AS OI
	ON OI.CORR_ORIGEN_INGRESO = A.CORR_ORIGEN_INGRESO
LEFT JOIN dbo.GEN_TIPO_CONTRIBUYENTE AS TC
	ON TC.CORR_TIPO_CONTRIBUYENTE = A.CORR_TIPO_CONTRIBUYENTE
LEFT JOIN dbo.GEN_ACTIVIDAD_ECONOMICA AS AE
	ON AE.CORR_ACTIVIDAD_ECONOMICA = A.CORR_ACTIVIDAD_ECONOMICA;
GO
