SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_CENTRO_COSTO_CONFIG_REVISION]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CENTRO_COSTO
      ,A.LOGIN_SISTEMA
	  ,B.NOMBRE_USUARIO
      ,A.ORDEN_REVISION
      ,A.PERMITE_APLICAR
  FROM CON_CENTRO_COSTO_CONFIG_REVISION A
  INNER JOIN SEG_USUARIO B ON A.LOGIN_SISTEMA=B.LOGIN_SISTEMA
GO
