SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DESCRIPTOR_PUESTO]
AS
SELECT
  A.[CORR_EMPRESA],
  A.[CORR_DESCRIPTOR_PUESTO],
  A.[FECHA_EMISION],
  A.[FECHA_REVISION],
  A.[OBJETIVO_PUESTO],
  A.[NUM_PERSONAL_CARGO],
  A.[CORR_PUESTO],
  A.[NOMBRE_PUESTO],
  A.[CORR_UNIDAD],
  A.[NOMBRE_UNIDAD],
  A.[CORR_PUESTO_REPORTA],
  A.[CORR_IMPACTO_ECONOMICO],
  A.[DESCRIPCION_IMPACTO_ECONOMICO],
  A.[CORR_INDUCCION],
  A.[NOMBRE_INDUCCION],
  A.[SEMANAS_INDUCCION],
  A.[RESPONSABLE],
  A.[FORMATO],
  A.[VERSION],
  A.[ESTADO_DESCRIPTOR],
  A.[USUARIO_CREA],
  A.[ESTACION_CREA],
  A.[FECHA_CREA],
  A.[USUARIO_ACTU],
  A.[ESTACION_ACTU],
  A.[FECHA_ACTU]
FROM [dbo].[SC_DESCRIPTOR_PUESTO] A
GO
