SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_IMPUESTO_COMPRAS_SUJETOS_EXCLUIDOS]
AS
SELECT CONVERT(INT, 0) TIPO_DOCUMENTO,
	CONVERT(VARCHAR, '') NUMERO_IDENTIFICACION,
	CONVERT(VARCHAR, '') NOMBRE_CLIENTE,
	CONVERT(DATE, '') FECHA_EMISION,
	CONVERT(VARCHAR, '') NUMERO_SERIE,
	CONVERT(INT, 0) NUMERO_DOCUMENTO,
	CONVERT(DECIMAL(18,2), 0) MONTO_OPERACION,
	CONVERT(DECIMAL(18,2), 0) MONTO_RETENCION_IVA,
	CONVERT(INT, 0) NUMERO_ANEXO
FROM COM_DOCUMENTO
GO
