SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DESCRIPTOR_PUESTO_RESPONSABILIDAD_CARGO]
AS
SELECT
  D.[CORR_EMPRESA],
  D.[CORR_DESCRIPTOR_RESPONSABILIDAD],
  D.[NOMBRE_RESPONSABILIDAD],
  D.[INFORMACION],
  D.[CORR_DESCRIPTOR_PUESTO],
  D.[CORR_RESPONSABILIDAD],
  D.[USUARIO_CREA],
  D.[ESTACION_CREA],
  D.[FECHA_CREA],
  D.[USUARIO_ACTU],
  D.[ESTACION_ACTU],
  D.[FECHA_ACTU]
FROM [dbo].[SC_DESCRIPTOR_PUESTO_RESPONSABILIDAD_CARGO] D
GO
