SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_EMPRESA]
AS 
SELECT A.CORR_EMPRESA
      ,A.NOMBRE_EMPRESA
      ,A.LOGO_1
      ,A.LOGO_2
	  ,A.TAMANIO_EMPRESA FROM GEN_EMPRESA A
GO
