SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_FRECUENCIA]
AS
SELECT CORR_EMPRESA
      ,CORR_FRECUENCIA
      ,NOMBRE_FRECUENCIA
      ,ESTADO_FRECUENCIA
      ,USUARIO_CREA
      ,ESTACION_CREA
      ,FECHA_CREA
      ,USUARIO_ACTU
      ,ESTACION_ACTU
      ,FECHA_ACTU
  FROM SC_FRECUENCIA

GO
