SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_CONFIG_AUTORIZACIONES]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CONFIGURACION
      ,A.LOGIN_SISTEMA
      ,A.NOMBRE_CARGO
      ,A.MONTO_INICIAL
      ,A.MONTO_FINAL
      ,A.CLASE_AUTORIZACION
	  ,CASE A.CLASE_AUTORIZACION
	  WHEN 'CC' THEN 'Coordinador Compra'
	  WHEN 'GC' THEN 'Gerencia Compra'
	  WHEN 'GG' THEN 'Gerencia General'
	  WHEN 'RE' THEN 'Rectoría'
	  ELSE '' END NOMBRE_CLASE_AUTORIZACION
      ,A.ORDEN_REVISION
      ,A.PERMITE_MODIFICAR
	  ,ISNULL(A.ESTADO_AUTORIZA,'AC') ESTADO_AUTORIZA
	  ,CASE ISNULL(A.ESTADO_AUTORIZA,'AC')
	  WHEN 'AC' THEN 'Activo'
	  WHEN 'IN' THEN 'Inactivo'
	  ELSE '' END NOMBRE_ESTADO_AUTORIZA
FROM COM_CUADRO_COMPARATIVO_CONFIG_AUTORIZACIONES A
GO
