SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_DISTRITO]
AS
SELECT T.CORR_PAIS
      ,T.CORR_DEPTO
      ,T.CORR_MUNICIPIO
      ,T.CORR_DISTRITO
      ,T.NOMBRE_DISTRITO
      ,T.USUARIO_CREA
      ,T.ESTACION_CREA
      ,T.FECHA_CREA
      ,T.USUARIO_ACTU
      ,T.ESTACION_ACTU
      ,T.FECHA_ACTU
      ,M.NOMBRE_MUNICIPIO
      ,D.NOMBRE_DEPTO
      ,P.NOMBRE_PAIS
  FROM GEN_DISTRITO T
  LEFT JOIN GEN_MUNICIPIO M
    ON M.CORR_PAIS = T.CORR_PAIS
   AND M.CORR_DEPTO = T.CORR_DEPTO
   AND M.CORR_MUNICIPIO = T.CORR_MUNICIPIO
  LEFT JOIN GEN_DEPTO D
    ON D.CORR_PAIS = T.CORR_PAIS
   AND D.CORR_DEPTO = T.CORR_DEPTO
  LEFT JOIN GEN_PAIS P
    ON P.CORR_PAIS = T.CORR_PAIS
GO
