SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_REPORTE_GASTOS]
AS
SELECT   CORR_EMPRESA
, CUENTA_CONTABLE CUENTA_DEPARTAMENTO
, NOMBRE_CUENTA NOMBRE_CUENTA_DEPARTAMENTO
, CUENTA_CONTABLE
, NOMBRE_CUENTA
,CONVERT(INT,2015) ANIO_PERIODO
,CONVERT(DECIMAL(12,2),0) ENERO
,CONVERT(DECIMAL(12,2),0) FEBRERO
,CONVERT(DECIMAL(12,2),0) MARZO
,CONVERT(DECIMAL(12,2),0) ABRL
,CONVERT(DECIMAL(12,2),0) MAYO
,CONVERT(DECIMAL(12,2),0) JUINIO
,CONVERT(DECIMAL(12,2),0) JULIO
,CONVERT(DECIMAL(12,2),0) AGOSTO
,CONVERT(DECIMAL(12,2),0) SEPTIEMBRE
,CONVERT(DECIMAL(12,2),0) OCTUBRE
,CONVERT(DECIMAL(12,2),0) NOVIEMBRE
,CONVERT(DECIMAL(12,2),0) DICIEMBRE
,CONVERT(DECIMAL(12,2),0) TOTAL
FROM CON_CATALOGO_CUENTA 
GO
