SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DESCRIPTOR_PUESTO_REQUERIMIENTO_ORGANIZACIONAL]
AS
SELECT
  D.[CORR_EMPRESA],
  D.[CORR_DESCRIPTOR_REQUERIMIENTO_ORGANIZACIONAL],
  D.[DESCRIPCION],
  D.[CORR_DESCRIPTOR_PUESTO],
  D.[CORR_REQUERIMIENTO_ORGANIZACIONAL],
  D.[USUARIO_CREA],
  D.[ESTACION_CREA],
  D.[FECHA_CREA],
  D.[USUARIO_ACTU],
  D.[ESTACION_ACTU],
  D.[FECHA_ACTU]
FROM [dbo].[SC_DESCRIPTOR_PUESTO_REQUERIMIENTO_ORGANIZACIONAL] D
GO
