SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_DESCRIPTOR_RESPONSABILIDAD_CARGO]
AS
SELECT CORR_EMPRESA
      ,CORR_RESPONSABILIDAD
      ,NOMBRE_RESPONSABILIDAD
      ,ESTADO_RESPONSABILIDAD
      ,USUARIO_CREA
      ,ESTACION_CREA
      ,FECHA_CREA
      ,USUARIO_ACTU
      ,ESTACION_ACTU
      ,FECHA_ACTU
  FROM SC_DESCRIPTOR_RESPONSABILIDAD_CARGO

GO
