SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_GEN_MUNICIPIO]
AS
SELECT RTRIM(LTRIM(A.PROCOD)) CODIGO_MUNICIPIO
,RTRIM(LTRIM(A.PRODSC)) NOMBRE_MUNICIPIO
,RTRIM(LTRIM(PROREL)) CODIGO_DEPTO
FROM [CLASS_UEES].dbo.PROVINCIAS A
WHERE PROREG='C'
GO
