SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_ORDEN_COMPRA_TOTALES]
AS
SELECT A.ORDNUM NUMERO_ORDEN
,SUM(A.ORDAMT) SUB_TOTAL
,SUM(A.ORDIMP) TOTAL_IMPUESTO
,SUM(A.ORDMIV) TOTAL_ORDEN
,dbo.FN_NUMEROS_A_LETRAS(SUM(A.ORDMIV),0)TOTAL_EN_LETRAS
,dbo.StrConcat(DISTINCT A.ORDOB1+'')OBSERVACIONES
FROM [CLASS_UEES].dbo.ORDENCOMPRA A
GROUP BY A.ORDNUM
GO
