SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_DETA]
AS
SELECT CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_CUADRO_COMPARATIVO
      ,A.ANIO_PERIODO_COTIZACION
      ,A.CORR_COTIZACION
      ,A.CORR_COTIZACION_DETA
      ,A.SELECCION
	  ,A.OBSERVACIONES
  FROM COM_CUADRO_COMPARATIVO_DETA A

GO
