SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_DECLARACION_MENS_HACIENDA_DOC_NETEADOS]
AS 
SELECT A.CORR_EMPRESA
	,A.CORR_TIENDA
	,A.ANIO_PERIODO
	,A.MES_PERIODO
	,A.CORR_DOCUMENTO
	,ROW_NUMBER() OVER(PARTITION BY A.CORR_EMPRESA
	,A.CORR_TIENDA
	,A.ANIO_PERIODO
	,A.MES_PERIODO
	,A.CORR_DOCUMENTO ORDER BY A.CORR_EMPRESA
	,A.CORR_TIENDA
	,A.ANIO_PERIODO
	,A.MES_PERIODO
	,A.CORR_DOCUMENTO)+1 CORR_DETA
	,CONVERT(VARCHAR(25),'') NIT_MANDANTE
	,CONVERT(VARCHAR(150),'') NOMBRE_CLIENTE
	,GETDATE() FECHA_EMISION
	,03 TIPO_DOCUMENTO --B.CODIGO_FEL
	,CONVERT(VARCHAR(50),'') NUMERO_SERIE_DOCUMENTO
	,CONVERT(VARCHAR(25),'') NUMERO_RESOLUCION
	,CONVERT(INT, 0) NUMERO_DOCUMENTO
	,CONVERT(DECIMAL(16,2), 0) MONTO_OPERACION
	,CONVERT(DECIMAL(16,2), 0) IVA_OPERACION
	,'' NUMERO_SERIE_COMPRO_LIQUIDACION
	,'' NUMERO_RESOLUCION_COMPRO_LIQUIDA
	,CONVERT(INT, 0) NUMERO_COMPRO_LIQUIDA
	,GETDATE() FECHA_EMISION_COMPRO_LIQUIDA
	,4 NUMERO_ANEXO
	,CONVERT(VARCHAR(250),'') NOMBRE_MANDANTE
	,CONVERT(VARCHAR(50),'') NUMERO_CONTROL
	,CONVERT(VARCHAR(50),'') CODIGO_GENERACION
	,CONVERT(VARCHAR(50),'') SELLO_RECEPCION
	,CONVERT(VARCHAR(50),'') NUMERO_CONTROL_COMPRO_LIQUIDACION
	,CONVERT(VARCHAR(50),'') CODIGO_GENERACION_COMPRO_LIQUIDACION
	,CONVERT(VARCHAR(50),'') SELLO_RECEPCION_COMPRO_LIQUIDACION
	FROM VEN_DOCUMENTO A
GO
