
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_CON_TIPO_CENTRO_COSTO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_TIPO_CENTRO_COSTO
      ,A.NOMBRE_TIPO_CENTRO_COSTO
      ,A.CLASE_CENTRO_COSTO
      ,CASE A.CLASE_CENTRO_COSTO
      WHEN 'PR' THEN 'Proyecto '
      WHEN 'GA' THEN 'Gasto '
      WHEN 'CO' THEN 'Costo '
      ELSE '' END NOMBRE_CLASE_CENTRO_COSTO
      
  FROM CON_TIPO_CENTRO_COSTO A

GO
