SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES]
AS
SELECT A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
      ,A.CORR_CUADRO_COMPARATIVO
      ,A.LOGIN_SISTEMA
	  ,B.NOMBRE_USUARIO COLLATE DATABASE_DEFAULT NOMBRE_USUARIO
	  ,A.NOMBRE_CARGO
	  ,A.MONTO_INICIAL
	  ,A.MONTO_FINAL
	  ,A.CLASE_AUTORIZACION
	  ,A.ORDEN_REVISION
	  ,A.PERMITE_MODIFICAR
      ,A.FECHA_AUTORIZACION
      ,A.ESTADO_AUTORIZACION
	  ,CASE A.ESTADO_AUTORIZACION
	   WHEN 'DI' THEN 'DIGITADO'
	   WHEN 'SO' THEN 'SOLICITADO'
	   WHEN 'AP' THEN 'APLICADO'
	   WHEN 'AN' THEN 'ANULADO'
	   ELSE '' END NOMBRE_ESTADO_AUTORIZACION
FROM COM_CUADRO_COMPARATIVO_AUTORIZACIONES A
INNER JOIN SEG_USUARIO B ON A.LOGIN_SISTEMA = B.LOGIN_SISTEMA
UNION ALL
SELECT A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
      ,A.CORR_CUADRO_COMPARATIVO
      ,A.LOGIN_SISTEMA
	  ,B.USRDSC  COLLATE DATABASE_DEFAULT NOMBRE_USUARIO
	  ,A.NOMBRE_CARGO
	  ,A.MONTO_INICIAL
	  ,A.MONTO_FINAL
	  ,A.CLASE_AUTORIZACION
	  ,A.ORDEN_REVISION
	  ,A.PERMITE_MODIFICAR
      ,A.FECHA_AUTORIZACION
      ,A.ESTADO_AUTORIZACION
	  ,CASE A.ESTADO_AUTORIZACION
	   WHEN 'DI' THEN 'DIGITADO'
	   WHEN 'SO' THEN 'SOLICITADO'
	   WHEN 'AP' THEN 'APLICADO'
	   WHEN 'AN' THEN 'ANULADO'
	   ELSE '' END NOMBRE_ESTADO_AUTORIZACION
FROM COM_CUADRO_COMPARATIVO_AUTORIZACIONES A
INNER JOIN [CLASS_UEES].dbo.USUARIOS B ON A.LOGIN_SISTEMA COLLATE DATABASE_DEFAULT = LTRIM(RTRIM(B.USRUID)) COLLATE DATABASE_DEFAULT
GO
