SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_CON_SECCION]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_DIVISION
      ,A.CORR_GERENCIA
      ,A.CORR_DEPARTAMENTO
      ,A.CORR_SECCION
      ,A.NOMBRE_SECCION
      ,A.CODIGO_SECCION

  FROM GEN_SECCION A

GO
