-- Qué hace: vista de documentos de identidad de una persona (valor + metadatos del catálogo).
-- Cómo lo hace: une GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD con GEN_TIPO_DOCUMENTO_IDENTIDAD.
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [dbo].[V_GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD]
AS
SELECT
	P.CORR_EMPRESA,
	P.CORR_PERSONA,
	P.CORR_TIPO_DOCUMENTO_IDENTIDAD,
	P.VALOR_DOCUMENTO,
	T.NOMBRE_TIPO_DOCUMENTO_IDENTIDAD,
	T.NOMBRE_CORTO,
	T.NUMERO_CARACTERES,
	ISNULL(T.ACTIVO_CARACTERES, 0) AS ACTIVO_CARACTERES,
	ISNULL(T.ACTIVO_TIPO_DOCUMENTO_IDENTIDAD, 1) AS ACTIVO_TIPO_DOCUMENTO_IDENTIDAD,
	P.USUARIO_CREA,
	P.ESTACION_CREA,
	P.FECHA_CREA,
	P.USUARIO_ACTU,
	P.ESTACION_ACTU,
	P.FECHA_ACTU
FROM dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD AS P
INNER JOIN dbo.GEN_TIPO_DOCUMENTO_IDENTIDAD AS T
	ON T.CORR_TIPO_DOCUMENTO_IDENTIDAD = P.CORR_TIPO_DOCUMENTO_IDENTIDAD;
GO
