SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_REQUERIMIENTO_ORGANIZACIONAL]
AS
SELECT CORR_EMPRESA
      ,CORR_REQUERIMIENTO_ORGANIZACIONAL
      ,DESCRIPCION
      ,ESTADO_REQUERIMIENTO_ORGANIZACIONAL
      ,USUARIO_CREA
      ,ESTACION_CREA
      ,FECHA_CREA
      ,USUARIO_ACTU
      ,ESTACION_ACTU
      ,FECHA_ACTU
  FROM SC_REQUERIMIENTO_ORGANIZACIONAL

GO
