SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_COTIZACION]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_COTIZACION
	  ,CONVERT(VARCHAR(4),A.ANIO_PERIODO) + '-' + CONVERT(VARCHAR(15),A.CORR_COTIZACION) NUMERO_COTIZACION
      ,A.FECHA_COTIZACION
      ,A.CORR_PROVEEDOR
	  ,B.CLINAM NOMBRE_PROVEEDOR
      ,A.USUARIO_COTIZA
      ,A.OBSERVACIONES
      ,A.OBSERVACIONES_PROVEEDOR
      ,A.PLAZO_ENTREGA
      ,A.ESTADO_COTIZACION
	  ,CASE A.ESTADO_COTIZACION
	   WHEN 'DI' THEN 'DIGITADO'
	   WHEN 'SO' THEN 'SOLICITADO'
	   WHEN 'AP' THEN 'APLICADO'
	   WHEN 'AN' THEN 'ANULADO'
	   ELSE '' END NOMBRE_ESTADO_COTIZACION
      ,A.ANIO_PERIODO_SOLI_COTI
      ,A.CORR_SOLI_COTIZACION
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
	  ,CONVERT(VARCHAR(4),ISNULL(A.ANIO_PERIODO_SOLI_COTI,0)) + '-' + CONVERT(VARCHAR(15),ISNULL(A.CORR_SOLI_COTIZACION,0)) NUMERO_SOLI_COTIZACION
	  ,C.NUMERO_SOLI_COMPRA
	  ,ISNULL(A.CORR_CONDICION_PAGO,0)CORR_CONDICION_PAGO
	  ,ISNULL(D.NOMBRE_CONDICION_PAGO,'')NOMBRE_CONDICION_PAGO
	  ,ISNULL(A.CORR_FORMA_PAGO,4)CORR_FORMA_PAGO
	  ,ISNULL(E.NOMBRE_FORMA_PAGO,'')NOMBRE_FORMA_PAGO
	  ,ISNULL(A.DETALLE_FORMA_PAGO,'')DETALLE_FORMA_PAGO
FROM COM_COTIZACION A
INNER JOIN [CLASS_UEES].dbo.CLIENTES B ON A.CORR_PROVEEDOR=B.CLIIDU
INNER JOIN V_COM_SOLI_COTIZACION_SOLI_COMPRA_SUM C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.ANIO_PERIODO_SOLI_COTI=C.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION=C.CORR_SOLI_COTIZACION
LEFT OUTER JOIN COM_CONDICION_PAGO D ON A.CORR_EMPRESA = D.CORR_EMPRESA AND A.CORR_CONDICION_PAGO = D.CORR_CONDICION_PAGO
LEFT OUTER JOIN V_GEN_FORMA_PAGO E ON A.CORR_FORMA_PAGO = E.CORR_FORMA_PAGO
GO
