SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_CON_PARTIDA_DOC]
AS
SELECT DISTINCT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,A.CORR_PARTIDA      
      ,A.TIPO_DOCUMENTO
      ,A.FECHA_DOCUMENTO
      ,A.NUMERO_DOCUMENTO
      ,A.CORR_DOCUMENTO
      ,A.FORMA
      ,A.ID_DOCUMENTO
FROM V_CON_PARTIDA_DETA_DOC A
GO
