SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_BAN_TIPO_MOVI_SEGUN_BANCO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_TIPO_MOVIMIENTO
      ,A.CORR_BANCO
      ,B.NOMBRE_BANCO
      ,A.CODIGO_MOVIMIENTO
      ,A.NOMBRE_MOVIMIENTO_SEGUN_BANCO
FROM dbo.BAN_TIPO_MOVI_SEGUN_BANCO A
INNER JOIN dbo.GEN_BANCO B
  ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_BANCO = B.CORR_BANCO
GO
