SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_CON_CENTRO_COSTO_GENERAR_SOLICITUD]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CENTRO_COSTO
      ,A.NOMBRE_CENTRO
      ,ISNULL(A.CUENTA_CONTABLE,'') CUENTA_CONTABLE
      ,ISNULL(B.CANTIDAD_MAXIMA_EMPLEADOS,0) CANTIDAD_MAXIMA_EMPLEADOS
      ,ISNULL(A.CODIGO_CENTRO_COSTO,'') CODIGO_CENTRO_COSTO
      ,ISNULL(A.CORR_TIPO_CENTRO_COSTO,0) CORR_TIPO_CENTRO_COSTO
      ,ISNULL(C.NOMBRE_TIPO_CENTRO_COSTO,'') NOMBRE_TIPO_CENTRO_COSTO
      ,ISNULL(A.ESTADO_CENTRO_COSTO,'') ESTADO_CENTRO_COSTO
      ,CONVERT(BIT,0) SELECCION
FROM CON_CENTRO_COSTO A
LEFT OUTER JOIN V_CON_CENTRO_COSTO_CANTIDAD_MAX_EMPLEADO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CENTRO_COSTO=B.CORR_CENTRO_COSTO
LEFT OUTER JOIN CON_TIPO_CENTRO_COSTO C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_TIPO_CENTRO_COSTO=C.CORR_TIPO_CENTRO_COSTO
GO
