SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_LIBRO_IVA_VENTAS_CONSU_FINALES]   
AS
SELECT  A.CORR_EMPRESA
	, A.CORR_TIENDA
	, '' NUMERO_NIT
	, '' NUMERO_NRC
	, A.ANIO_PERIODO
	, A.MES_PERIODO
	, A.FECHA_DOCUMENTO
	, '' DESDE
	, '' HASTA
	, '' COMPROBANTE_LIQUIDACION
	, '' MANDANTE
    ,  CONVERT(DECIMAL(12,2), 0)	VENTAS_PROPIAS_EXENTA
    ,  CONVERT(DECIMAL(12,2), 0)	NO_SUJETO_VENTAS_PROPIAS
    ,  CONVERT(DECIMAL(12,2), 0)  VENTAS_PROPIAS_GRAVADA
	,  CONVERT(DECIMAL(12,2), 0)  VENTAS_PROPIAS_GRAVADAS_EXPORTACION
    ,  CONVERT(DECIMAL(12,2), 0)  VENTAS_PROPIAS_IVA
	,  CONVERT(DECIMAL(12,2), 0)	VENTAS_TERCEROS_EXE
	,  CONVERT(DECIMAL(12,2), 0)	NO_SUJETO_VENTAS_TE
	,  CONVERT(DECIMAL(12,2), 0)	VENTAS_TERCEROS_GRA
	,  CONVERT(DECIMAL(12,2), 0)  VENTAS_TERCEROS_GRAVADAS_EXPORTACION
	,  CONVERT(DECIMAL(12,2), 0)	VENTAS_TERCEROS_IVA
    ,  CONVERT(DECIMAL(12,2), 0)  VENTAS_TOTAL
	, A.CORR_RUTA_VENTA
	, '' NOMBRE_RUTA_VENTA
    FROM V_VEN_DOCUMENTO A
GO
