SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_PLA_CARGO_CON_CENTRO_COSTO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CARGO
      ,A.CORR_CENTRO_COSTO
      ,A.CANTIDAD_MAXIMA_EMPLEADOS
  FROM PLA_CARGO_CON_CENTRO_COSTO A
GO
