SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_PLA_NIVEL_ACADEMICO]
AS
SELECT CORR_EMPRESA
      ,CORR_NIVEL_ACADEMICO
      ,NOMBRE_NIVEL_ACADEMICO
      ,ESTADO_NIVEL_ACADEMICO
      ,USUARIO_CREA
      ,FECHA_CREA
      ,ESTACION_CREA
      ,USUARIO_ACTU
      ,FECHA_ACTU
      ,ESTACION_ACTU
  FROM PLA_NIVEL_ACADEMICO

GO
