SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_BAN_CHEQUES_EMITIDOS]
AS
SELECT A.CORR_EMPRESA
	  ,A.ANIO_PERIODO
	  ,A.MES_PERIODO
	  ,A.CORR_TIPO_MOVIMIENTO
	  ,A.NOMBRE_TIPO_MOVIMIENTO
	  ,A.CLASE_MOVIMIENTO
	  ,A.CORR_DOCUMENTO
	  ,A.CORR_CUENTA_BANCO
	  ,A.NOMBRE_CUENTA_BANCO
	  ,A.NUMERO_DOCUMENTO
	  ,A.FECHA_EMISION
	  ,CASE WHEN A.ESTADO_DOCUMENTO = 'AN' THEN '***ANULADO***' ELSE A.NOMBRE_PARTIDA END AS NOMBRE_PARTIDA
	  ,A.CORR_PROVEEDOR
	  ,CAST('' AS VARCHAR(255)) AS NOMBRE_PROVEEDOR
	  ,A.CORR_EMPLEADO
	  ,A.CORR_CLIENTE
	  ,A.NOMBRE_BENEFICIARIO
	  ,A.MONTO_DOCUMENTO
	  ,A.ESTADO_DOCUMENTO
	  ,A.NOMBRE_ESTADO_DOCUMENTO
	  ,A.ESTA_CONTABILIZADO
	  ,CAST('' AS VARCHAR(255)) AS HECHO_POR
	  ,CAST('' AS VARCHAR(255)) AS REVISADO_POR
	  ,CAST('' AS VARCHAR(255)) AS APROBADO_POR
	  ,CAST('' AS VARCHAR(255)) AS CONTADOR_REVISO
	  ,CAST('' AS VARCHAR(255)) AS AUDITOR_REVISO
	  ,CAST(NULL AS DATETIME) AS FECHA_GENERACION
	  ,CAST(NULL AS DATETIME) AS FECHA_APROBADO
	  ,A.FECHA_IMPRESO
	  ,A.CANTIDAD_LETRAS
	  ,A.USUARIO_CREA
	  ,A.FECHA_CREA
	  ,A.ESTACION_CREA
	  ,A.USUARIO_ACTU
	  ,A.FECHA_ACTU
	  ,A.ESTACION_ACTU
	  ,ISNULL(D.CORR_MOVIMIENTO, 0) AS CORR_MOVIMIENTO
	  ,ISNULL(D.CORR_MOVIMIENTO_DESTINO, 0) AS CORR_MOVIMIENTO_DESTINO
	  ,A.CORR_TIPO_CHEQUE
	  ,A.NOMBRE_TIPO_CHEQUE
	  ,A.CLASE_TIPO_CHEQUE
	  ,A.CORR_CHEQUERA
	  ,A.SERIE_CHEQUE
	  ,CAST(0 AS INT) AS CORR_CUENTA_BANCO_DESTINO
	  ,CAST('' AS VARCHAR(50)) AS NUMERO_CUENTA_BANCO_DESTINO
	  ,CAST('' AS VARCHAR(50)) AS NUMERO_CUENTA_DESTINO_TERCERO
	  ,CAST(0 AS DECIMAL(18,2)) AS MONTO_DESTINO
	  ,CAST(NULL AS INT) AS ANIO_PERIODO_CHEQUE
	  ,CAST(NULL AS INT) AS MES_PERIODO_CHEQUE
	  ,CAST(NULL AS INT) AS CORR_TIPO_MOVIMIENTO_CHEQUE
	  ,CAST(NULL AS INT) AS CORR_DOCUMENTO_CHEQUE
	  ,A.FECHA_ANULACION
	  ,A.CORR_MONEDA
	  ,ISNULL(M.NOMBRE_MONEDA, '') AS NOMBRE_MONEDA
	  ,ISNULL(M.SIMBOLO, '') AS SIMBOLO
	  ,A.FACTOR_CAMBIO
	  ,A.OPERADOR
FROM dbo.V_BAN_DOCUMENTO AS A
INNER JOIN dbo.BAN_DOCUMENTO D
  ON A.CORR_EMPRESA = D.CORR_EMPRESA
 AND A.ANIO_PERIODO = D.ANIO_PERIODO
 AND A.MES_PERIODO = D.MES_PERIODO
 AND A.CORR_TIPO_MOVIMIENTO = D.CORR_TIPO_MOVIMIENTO
 AND A.CORR_DOCUMENTO = D.CORR_DOCUMENTO
LEFT JOIN dbo.GEN_TIPO_MONEDA M
  ON A.CORR_MONEDA = M.CORR_MONEDA
GO
