SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_BAN_CHEQUERA]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_CUENTA_BANCO,
	B.NUMERO_CUENTA_BANCO,
	A.CORR_CHEQUERA,
	A.NUMERO_CHEQUE_INICIAL,
	A.NUMERO_CHEQUE_FINAL,
	A.NUMERO_CHEQUE_ACTUAL,
	A.SERIE_CHEQUE,
	A.ESTADO_CHEQUERA,
	B.CLASE_CHEQUE
FROM dbo.BAN_CHEQUERA A
INNER JOIN dbo.BAN_CUENTA_BANCARIA B
	ON A.CORR_EMPRESA = B.CORR_EMPRESA
	AND A.CORR_CUENTA_BANCO = B.CORR_CUENTA_BANCO
GO
