SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SC_PERSONA_DATOS]
AS
SELECT [CORR_EMPRESA], [CORR_PERSONA_DATOS], [NOMBRE1], [NOMBRE2], [APELLIDO1], [APELLIDO2],
       [FECHA_NACIMIENTO], [EDAD], [ESTADO_CIVIL], [NACIONALIDAD], [CORREO], [CELULAR],
       [TELEFONO], [DIRECCION], [DUI], [PASAPORTE], [ISSS], [AFP], [NOMBRE_AFP], [LICENCIA],
       [PLAZA_SOLICITADA], [PRETENSION_SALARIAL], [DISPONIBILIDAD], [RELIGION], [IGLESIA],
       [DIRECCION_IGLESIA], [ES_CONTRIBUYENTE_CCF], [ES_JUBILADO], [POSEE_DISCAPACIDAD],
       [TIPO_DISCAPACIDAD], [EMERGENCIA_NOMBRE], [EMERGENCIA_PARENTESCO],
       [EMERGENCIA_TELEFONO], [TIENE_FAMILIARES_UEES], [DECLARA_VERDAD],
       [AUTORIZA_VERIFICACION], [FECHA_DECLARACION], [FIRMA_ELECTRONICA]
FROM [dbo].[SC_PERSONA_DATOS]
GO
