SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_GEN_BANCO]
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_BANCO
      ,A.NOMBRE_BANCO
      ,A.NOMBRE_BANCO_CORTO
      ,ISNULL(A.CLASE_BANCO, '') CLASE_BANCO
      ,CASE A.CLASE_BANCO
       WHEN 'CREDO' THEN 'Credomatic'
       WHEN 'CUSCA' THEN 'Cuscatlan'
       WHEN 'BAG'   THEN 'Agricola'
       WHEN 'BDV'   THEN 'Davivienda'
       WHEN 'BPM'   THEN 'Promerica'
       ELSE '' END NOMBRE_CLASE_BANCO
      ,ISNULL(A.CODIGO_TRANSACION_UNI, '') CODIGO_TRANSACION_UNI
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
FROM GEN_BANCO A
GO
