SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_COTIZACION_DETA]
AS
SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.CORR_COTIZACION
      ,A.CORR_COTIZACION_DETA
      ,A.CODIGO_ITEM
	  ,C.INVDSC NOMBRE_ITEM
      ,A.CANTIDAD
      ,A.CORR_UNIDAD_MEDIDA
      ,A.PRECIO_UNITARIO
      ,A.MONTO_SUBTOTAL
      ,A.OBSERVACIONES
      ,A.MARCA
      ,A.ESTADO_SOLI_COTIZACION
	  ,CASE A.ESTADO_SOLI_COTIZACION
	   WHEN 'DI' THEN 'DIGITADO'
	   WHEN 'SO' THEN 'SOLICITADO'
	   WHEN 'AP' THEN 'APLICADO'
	   WHEN 'AN' THEN 'ANULADO'
	   ELSE '' END NOMBRE_ESTADO_SOLI_COTIZACION
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
	  ,ISNULL(D.CORR_DOCUMENTO,0) CORR_DOCUMENTO
	  ,CASE	WHEN ISNULL(D.CORR_DOCUMENTO,0)<>0 THEN 'assets/img/adjunto.png' ELSE 'assets/img/noadjunto1.png' END IMAGEN_DOCUMENTO
	  ,ISNULL(E.NOMBRE_ARCHIVO,'')NOMBRE_ARCHIVO
FROM COM_COTIZACION_DETA A
LEFT OUTER JOIN COM_UNIDAD_MEDIDA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_UNIDAD_MEDIDA=B.CORR_UNIDAD_MEDIDA
INNER JOIN [CLASS_UEES].dbo.INVENTARIOS C ON A.CODIGO_ITEM COLLATE Modern_Spanish_CI_AS=C.INVCOD AND C.INVREG = 'E' AND C.INVSUC='001'
LEFT OUTER JOIN COM_COTIZACION_DETA_DOC D ON A.CORR_EMPRESA = D.CORR_EMPRESA AND A.ANIO_PERIODO = D.ANIO_PERIODO AND A.CORR_COTIZACION = D.CORR_COTIZACION AND A.CORR_COTIZACION_DETA = D.CORR_COTIZACION_DETA
LEFT OUTER JOIN COM_DOCUMENTO_FISICO E ON D.CORR_EMPRESA = E.CORR_EMPRESA AND D.CORR_DOCUMENTO = E.CORR_DOCUMENTO


GO
