SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_CON_CENTRO_COSTO_CANTIDAD_MAX_EMPLEADO]
AS
SELECT A.CORR_EMPRESA      
      ,A.CORR_CENTRO_COSTO
      ,SUM(A.CANTIDAD_MAXIMA_EMPLEADOS) CANTIDAD_MAXIMA_EMPLEADOS
FROM PLA_CARGO_CON_CENTRO_COSTO A
GROUP BY A.CORR_EMPRESA      
      ,A.CORR_CENTRO_COSTO
GO
