
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_CON_CLASE_PARTIDA] 
AS
SELECT A.CORR_EMPRESA
      ,A.CORR_CLASE_PARTIDA
      ,A.NOMBRE_CLASE_PARTIDA
      ,A.NOMBRE_CORTO_CLASE
      ,A.CORR_LINEA_AUMENTA
      ,B.NOMBRE_LINEA_TRABAJO NOMBRE_LINEA_AUMENTA
      ,A.CORR_LINEA_DISMINUYE
      ,C.NOMBRE_LINEA_TRABAJO NOMBRE_LINEA_DISMINUYE
      ,A.ACEPTA_MODIFICACION
      ,ISNULL(A.PARTIDA_CIERRE,0) PARTIDA_CIERRE
      ,ISNULL(A.NOMBRE_REPORTE,'PARTIDA_CONTABLE') NOMBRE_REPORTE
FROM CON_CLASE_PARTIDA A
LEFT OUTER JOIN BAN_LINEA_TRABAJO_CONCILIACION B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_LINEA_AUMENTA=B.CORR_LINEA
LEFT OUTER JOIN BAN_LINEA_TRABAJO_CONCILIACION C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_LINEA_AUMENTA=C.CORR_LINEA

GO
