SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: lectura de puestos asignados al empleado para el tab de gen-empleado.
-- Cómo lo hace: GEN_EMPLEADO_PUESTO con nombres de unidad, puesto, tipo de contratación y modalidad.
CREATE OR ALTER VIEW [dbo].[V_GEN_EMPLEADO_PUESTO]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_EMPLEADO,
	A.CORR_UNIDAD,
	U.CODIGO_UNIDAD,
	U.NOMBRE_UNIDAD,
	A.CORR_PUESTO,
	P.CODIGO_PUESTO,
	P.NOMBRE_PUESTO,
	A.FECHA_INGRESO,
	A.SUELDO,
	A.HORARIO_LABORAL,
	A.CORR_TIPO_CONTRATACION,
	TC.NOMBRE_TIPO_CONTRATACION,
	A.CORR_TIPO_MODALIDAD,
	TM.MODALIDAD_NOMBRE,
	A.USUARIO_CREA,
	A.ESTACION_CREA,
	A.FECHA_CREA,
	A.USUARIO_ACTU,
	A.ESTACION_ACTU,
	A.FECHA_ACTU
FROM dbo.GEN_EMPLEADO_PUESTO A
LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES U
	ON U.CORR_EMPRESA = A.CORR_EMPRESA
	AND U.CORR_UNIDAD = A.CORR_UNIDAD
LEFT JOIN dbo.PLA_PUESTO P
	ON P.CORR_EMPRESA = A.CORR_EMPRESA
	AND P.CORR_PUESTO = A.CORR_PUESTO
LEFT JOIN dbo.SC_TIPO_CONTRATACION TC
	ON TC.CORR_EMPRESA = A.CORR_EMPRESA
	AND TC.CORR_TIPO_CONTRATACION = A.CORR_TIPO_CONTRATACION
LEFT JOIN dbo.SC_TIPO_MODALIDAD TM
	ON TM.CORR_EMPRESA = A.CORR_EMPRESA
	AND TM.CORR_TIPO_MODALIDAD = A.CORR_TIPO_MODALIDAD
GO
