SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_COM_CUADRO_COMPARATIVO_PROVEEDOR]
AS
WITH CTE_COM_CUADRO_COMPARATIVO_PROVEEDOR
AS
(
	SELECT DISTINCT A.CORR_EMPRESA,A.ANIO_PERIODO, A.CORR_CUADRO_COMPARATIVO, C.CORR_PROVEEDOR, D.CLINAM NOMBRE_PROVEEDOR
	FROM COM_CUADRO_COMPARATIVO_DETA A
	INNER JOIN COM_COTIZACION_DETA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO_COTIZACION = B.ANIO_PERIODO AND A.CORR_COTIZACION = B.CORR_COTIZACION AND A.CORR_COTIZACION_DETA = B.CORR_COTIZACION_DETA
	INNER JOIN COM_COTIZACION C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO = C.ANIO_PERIODO AND B.CORR_COTIZACION = C.CORR_COTIZACION
	INNER JOIN [CLASS_UEES].dbo.CLIENTES D ON C.CORR_PROVEEDOR=D.CLIIDU
)
SELECT A.CORR_EMPRESA
,A.ANIO_PERIODO
,A.CORR_CUADRO_COMPARATIVO
,A.CORR_PROVEEDOR
,A.NOMBRE_PROVEEDOR
,ROW_NUMBER() OVER(PARTITION BY A.CORR_EMPRESA,A.ANIO_PERIODO,A.CORR_CUADRO_COMPARATIVO ORDER BY A.CORR_PROVEEDOR) CORR_PROVEEDOR_FILA
FROM CTE_COM_CUADRO_COMPARATIVO_PROVEEDOR A
GO
