# Reorganiza Reports/Accounting/*.rpt al patron Shop (carpeta por reporte + *Report.rpt embebido).
param(
	[string]$AccountingRoot = "$PSScriptRoot\..\sguees-rpt\Reports\Accounting"
)

$moves = @{
	'BALANCE_COMPROBACION.rpt' = 'BALANCE_COMPROBACION\BALANCE_COMPROBACIONReport.rpt'
	'BALANCE_COMPROBACION_MES.rpt' = 'BALANCE_COMPROBACION_MES\BALANCE_COMPROBACION_MESReport.rpt'
	'BALANCE_GENERAL.rpt' = 'BALANCE_GENERAL\BALANCE_GENERALReport.rpt'
	'BALANCE_GENERAL_VERTICAL.rpt' = 'BALANCE_GENERAL_VERTICAL\BALANCE_GENERAL_VERTICALReport.rpt'
	'ESTADO_RESULTADOS.rpt' = 'ESTADO_RESULTADOS\ESTADO_RESULTADOSReport.rpt'
	'LIBRO_DIARIO_AUXILIAR.rpt' = 'LIBRO_DIARIO_AUXILIAR\LIBRO_DIARIO_AUXILIARReport.rpt'
	'LIBRO_DIARIO_AUXILIAR_MES.rpt' = 'LIBRO_DIARIO_AUXILIAR_MES\LIBRO_DIARIO_AUXILIAR_MESReport.rpt'
	'LIBRO_DIARIO_MAYOR.rpt' = 'LIBRO_DIARIO_MAYOR\LIBRO_DIARIO_MAYORReport.rpt'
	'LIBRO_DIARIO_AUXILIAR_HORIZONTAL.rpt' = 'LIBRO_DIARIO_AUXILIAR_HORIZONTAL\LIBRO_DIARIO_AUXILIAR_HORIZONTALReport.rpt'
	'LIBRO_DIARIO_MAYOR_H.rpt' = 'LIBRO_DIARIO_MAYOR_H\LIBRO_DIARIO_MAYOR_HReport.rpt'
	'CON_REPORTE_GASTOS.rpt' = 'CON_GASTOS\CON_REPORTE_GASTOSReport.rpt'
	'PARTIDA_CONTABLE.rpt' = 'CON_PARTIDA\PARTIDA_CONTABLEReport.rpt'
	'CON_LIBRO_DIARIO.rpt' = 'CON_LIBRO_DIARIO\CON_LIBRO_DIARIOReport.rpt'
	'CON_LIBRO_INVENTARIO.rpt' = 'CON_LIBRO_INVENTARIO\CON_LIBRO_INVENTARIOReport.rpt'
	'CON_REPORTE_CATALOGO_PRESUPUESTO.rpt' = 'CON_REPORTE_CATALOGO_PRESUPUESTO\CON_REPORTE_CATALOGO_PRESUPUESTOReport.rpt'
	'CON_REPORTE_GASTOS_PRESUPUESTO.rpt' = 'CON_REPORTE_GASTOS_PRESUPUESTO\CON_REPORTE_GASTOS_PRESUPUESTOReport.rpt'
	'LIBRO_INTEGRACION_CONTABLE.rpt' = 'LIBRO_INTEGRACION_CONTABLE\LIBRO_INTEGRACION_CONTABLEReport.rpt'
	'LIBRO_INTEGRACION_CONTABLE_CC.rpt' = 'LIBRO_INTEGRACION_CONTABLE_CC\LIBRO_INTEGRACION_CONTABLE_CCReport.rpt'
	'R_CON_BALANCE_GENERAL_PORCENTAJE.rpt' = 'R_CON_BALANCE_GENERAL_PORCENTAJE\R_CON_BALANCE_GENERAL_PORCENTAJEReport.rpt'
	'R_CON_BALANCE_GENERAL_PORCENTAJE_AC.rpt' = 'R_CON_BALANCE_GENERAL_PORCENTAJE_AC\R_CON_BALANCE_GENERAL_PORCENTAJE_ACReport.rpt'
	'R_CON_BALANCE_GENERAL_PORCENTAJE_PA_CP.rpt' = 'R_CON_BALANCE_GENERAL_PORCENTAJE_PA_CP\R_CON_BALANCE_GENERAL_PORCENTAJE_PA_CPReport.rpt'
	'R_CON_BALANCE_SALDOS_AUXI.rpt' = 'R_CON_BALANCE_SALDOS_AUXI\R_CON_BALANCE_SALDOS_AUXIReport.rpt'
	'R_CON_IMPUESTO_F14.rpt' = 'R_CON_IMPUESTO_F14\R_CON_IMPUESTO_F14Report.rpt'
	'R_CON_LIBRO_MAYOR.rpt' = 'R_CON_LIBRO_MAYOR\R_CON_LIBRO_MAYORReport.rpt'
}

$moved = 0
foreach ($entry in $moves.GetEnumerator()) {
	$src = Join-Path $AccountingRoot $entry.Key
	$dest = Join-Path $AccountingRoot $entry.Value
	if (-not (Test-Path $src)) {
		continue
	}
	New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
	if (-not (Test-Path $dest)) {
		Move-Item -Force $src $dest
		Write-Host "Movido $($entry.Key) -> $($entry.Value)"
		$moved++
	}
}

Write-Host "Reorganizados: $moved | Raiz: $AccountingRoot"
