SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_PLA_CARGO_CON_CENTRO_COSTO]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA int,
	@CORR_CARGO int,
	@CORR_CENTRO_COSTO int OUTPUT,
	@CANTIDAD_MAXIMA_EMPLEADOS int,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1, 2)
		BEGIN
			IF NOT EXISTS ( SELECT 1 FROM PLA_CARGO 
							WHERE CORR_EMPRESA=@CORR_EMPRESA 
							AND CORR_CARGO=@CORR_CARGO )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe el cargo seleccionado.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
			IF NOT EXISTS ( SELECT 1 FROM CON_CENTRO_COSTO 
							WHERE CORR_EMPRESA=@CORR_EMPRESA 
							AND CORR_CENTRO_COSTO=@CORR_CENTRO_COSTO )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe el centro de costo seleccionado.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
			IF NOT EXISTS ( SELECT 1 FROM PLA_CARGO_CON_CENTRO_COSTO 
							WHERE CORR_EMPRESA=@CORR_EMPRESA 
							AND CORR_CARGO=@CORR_CARGO
							AND CORR_CENTRO_COSTO=@CORR_CENTRO_COSTO )
			BEGIN
				SELECT @TIPO_ACTUALIZA=1
			END ELSE
			BEGIN
				SELECT @TIPO_ACTUALIZA=2
			END
		
		END
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN			
			INSERT INTO PLA_CARGO_CON_CENTRO_COSTO
			(CORR_EMPRESA,CORR_CARGO,CORR_CENTRO_COSTO,CANTIDAD_MAXIMA_EMPLEADOS)
			VALUES
			(@CORR_EMPRESA,@CORR_CARGO,@CORR_CENTRO_COSTO,@CANTIDAD_MAXIMA_EMPLEADOS)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE PLA_CARGO_CON_CENTRO_COSTO SET
			CANTIDAD_MAXIMA_EMPLEADOS=@CANTIDAD_MAXIMA_EMPLEADOS
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CARGO=@CORR_CARGO
			AND CORR_CENTRO_COSTO=@CORR_CENTRO_COSTO
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM PLA_CARGO_CON_CENTRO_COSTO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CARGO=@CORR_CARGO
			AND CORR_CENTRO_COSTO=@CORR_CENTRO_COSTO
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
