
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_CON_PARTIDA_MONTO_LOCAL_FORANEA] (
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_CLASE_PARTIDA INT,
	@CORR_PARTIDA INT,
	@CORR_PARTIDA_DETA INT=NULL,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	SET NOCOUNT ON
	
	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
	
		DECLARE @DETA TABLE
		(
			CORR_DETA INT,
			MONTO_CARGO FLOAT,   
			MONTO_ABONO FLOAT,
			MONTO_CARGO_FORANEA FLOAT,
			MONTO_ABONO_FORANEA FLOAT
		)
		
		--Se convierte a moneda local o a moneda foranea
		DECLARE @CORR_MONEDA_PARTIDA INT, @FACTOR_CAMBIO FLOAT, @OPERADOR VARCHAR(2), @CORR_MONEDA_LOCAL INT, @CORR_MONEDA_FORANEA INT
		DECLARE @CORR_DETA INT, @MONTO_CARGO FLOAT, @MONTO_ABONO FLOAT, @MONTO_CARGO_FORANEA FLOAT, @MONTO_ABONO_FORANEA FLOAT
		
		SELECT @CORR_MONEDA_PARTIDA=A.CORR_MONEDA, @FACTOR_CAMBIO=A.FACTOR_CAMBIO, @OPERADOR=A.OPERADOR, @CORR_MONEDA_LOCAL=B.CORR_MONEDA, @CORR_MONEDA_FORANEA=ISNULL(C.CORR_MONEDA_INTER,B.CORR_MONEDA)
		FROM CON_PARTIDA A
		INNER JOIN GEN_EMPRESA B ON A.CORR_EMPRESA=B.CORR_EMPRESA
		LEFT OUTER JOIN GEN_PARAMETRO C ON B.CORR_EMPRESA=C.CORR_EMPRESA
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
		AND CORR_PARTIDA=@CORR_PARTIDA
		
		INSERT INTO @DETA
		SELECT CORR_PARTIDA_DETA, MONTO_CARGO, MONTO_ABONO, MONTO_CARGO_FORANEA, MONTO_ABONO_FORANEA
		FROM CON_PARTIDA_DETA A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
		AND CORR_PARTIDA=@CORR_PARTIDA
		AND (CORR_PARTIDA_DETA=@CORR_PARTIDA_DETA OR @CORR_PARTIDA_DETA IS NULL)
		
		WHILE EXISTS ( SELECT 1 FROM @DETA )
		BEGIN		
			SELECT TOP 1 @CORR_DETA=CORR_DETA, @MONTO_CARGO=MONTO_CARGO, @MONTO_ABONO=MONTO_ABONO, @MONTO_CARGO_FORANEA=MONTO_CARGO_FORANEA, @MONTO_ABONO_FORANEA=MONTO_ABONO_FORANEA
			FROM @DETA
			
			IF @CORR_MONEDA_FORANEA<>@CORR_MONEDA_PARTIDA AND @CORR_MONEDA_LOCAL=@CORR_MONEDA_PARTIDA
			BEGIN
				--Calculamos los montos foraneos
				SELECT  @MONTO_CARGO_FORANEA=CASE @FACTOR_CAMBIO WHEN 0 THEN @MONTO_CARGO ELSE CASE @OPERADOR WHEN '*' THEN @MONTO_CARGO*@FACTOR_CAMBIO ELSE @MONTO_CARGO/@FACTOR_CAMBIO END END,
						@MONTO_ABONO_FORANEA=CASE @FACTOR_CAMBIO WHEN 0 THEN @MONTO_ABONO ELSE CASE @OPERADOR WHEN '*' THEN @MONTO_ABONO*@FACTOR_CAMBIO ELSE @MONTO_ABONO/@FACTOR_CAMBIO END END
			END ELSE
			IF @CORR_MONEDA_FORANEA=@CORR_MONEDA_PARTIDA AND @CORR_MONEDA_LOCAL<>@CORR_MONEDA_PARTIDA
			BEGIN
				--Calculamos los montos locales
				SELECT  @MONTO_CARGO=CASE @FACTOR_CAMBIO WHEN 0 THEN @MONTO_CARGO_FORANEA ELSE CASE @OPERADOR WHEN '*' THEN @MONTO_CARGO_FORANEA*@FACTOR_CAMBIO ELSE @MONTO_CARGO_FORANEA/@FACTOR_CAMBIO END END,
						@MONTO_ABONO=CASE @FACTOR_CAMBIO WHEN 0 THEN @MONTO_ABONO_FORANEA ELSE CASE @OPERADOR WHEN '*' THEN @MONTO_ABONO_FORANEA*@FACTOR_CAMBIO ELSE @MONTO_ABONO_FORANEA/@FACTOR_CAMBIO END END
			END ELSE
			BEGIN
				SELECT  @MONTO_CARGO_FORANEA=@MONTO_CARGO,
						@MONTO_ABONO_FORANEA=@MONTO_ABONO
			END
			
			UPDATE CON_PARTIDA_DETA SET
			MONTO_CARGO=ROUND(@MONTO_CARGO,2),
			MONTO_ABONO=ROUND(@MONTO_ABONO,2),
			MONTO_CARGO_FORANEA=ROUND(@MONTO_CARGO_FORANEA,2),
			MONTO_ABONO_FORANEA=ROUND(@MONTO_ABONO_FORANEA,2)
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
			AND CORR_PARTIDA=@CORR_PARTIDA
			AND CORR_PARTIDA_DETA=@CORR_DETA
			
			DELETE FROM @DETA
			WHERE CORR_DETA=@CORR_DETA
		
		END
			
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
			
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
