SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_CON_PARTIDA]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_CLASE_PARTIDA INT,
	@CORR_PARTIDA INT OUTPUT,
	@FECHA_PARTIDA DATE,
	@NUMERO_DOCUMENTO VARCHAR(25),
	@NOMBRE_PARTIDA VARCHAR(1000),
	@ESTADO_PARTIDA VARCHAR(2),
	@CLASE_PARTIDA VARCHAR(3) = 'NOR',
	@CORR_MONEDA INT = NULL,
	@FACTOR_CAMBIO DECIMAL(16,6) = NULL,
	@OPERADOR VARCHAR(2) = NULL,
	@USUARIO_CREA VARCHAR(30),
	@FECHA_CREA DATETIME,
	@ESTACION_CREA VARCHAR(50),
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT,
	@APLICAR_DOC_CONTA BIT = NULL
)
AS
BEGIN
	SET NOCOUNT ON
	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = '', @SYS_FILAS_AFECTADAS = 0

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1, 2)
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM CON_PERIODO_CONTABLE
				WHERE CORR_EMPRESA = @CORR_EMPRESA
				  AND ANIO_PERIODO = @ANIO_PERIODO
				  AND MES_PERIODO = @MES_PERIODO
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30001, @SYS_MENSAJE_ERROR = 'No existe el periodo contable', @SYS_FILAS_AFECTADAS = 0
				GOTO FINA
			END

			IF NOT EXISTS (
				SELECT 1 FROM CON_PERIODO_CONTABLE
				WHERE CORR_EMPRESA = @CORR_EMPRESA
				  AND ANIO_PERIODO = @ANIO_PERIODO
				  AND MES_PERIODO = @MES_PERIODO
				  AND ESTADO_PERIODO_CON = 'AB'
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30002, @SYS_MENSAJE_ERROR = 'El periodo contable no esta abierto', @SYS_FILAS_AFECTADAS = 0
				GOTO FINA
			END

			IF NOT EXISTS (
				SELECT 1 FROM CON_CLASE_PARTIDA
				WHERE CORR_EMPRESA = @CORR_EMPRESA
				  AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30002, @SYS_MENSAJE_ERROR = 'La clase de partida no se ha seleccionado correctamente', @SYS_FILAS_AFECTADAS = 0
				GOTO FINA
			END
		END

		IF @TIPO_ACTUALIZA = 1
		BEGIN
			SELECT @CLASE_PARTIDA = ISNULL(@CLASE_PARTIDA, 'NOR')

			IF @CORR_MONEDA IS NULL
				SELECT TOP 1 @CORR_MONEDA = CORR_MONEDA FROM CON_PARAMETRO WHERE CORR_EMPRESA = @CORR_EMPRESA

			SELECT @CORR_PARTIDA = ISNULL(MAX(CORR_PARTIDA), 0) + 1
			FROM CON_PARTIDA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
			  AND ANIO_PERIODO = @ANIO_PERIODO
			  AND MES_PERIODO = @MES_PERIODO
			  AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA

			INSERT INTO CON_PARTIDA
			(CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_CLASE_PARTIDA, CORR_PARTIDA, FECHA_PARTIDA, NUMERO_DOCUMENTO, NOMBRE_PARTIDA, ESTADO_PARTIDA, USUARIO_CREA, FECHA_CREA, ESTACION_CREA, USUARIO_ACTU, FECHA_ACTU, ESTACION_ACTU, CLASE_PARTIDA, CORR_MONEDA, FACTOR_CAMBIO, OPERADOR)
			VALUES
			(@CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, @CORR_CLASE_PARTIDA, @CORR_PARTIDA, @FECHA_PARTIDA, @NUMERO_DOCUMENTO, @NOMBRE_PARTIDA, @ESTADO_PARTIDA, @USUARIO_CREA, @FECHA_CREA, @ESTACION_CREA, @USUARIO_ACTU, @FECHA_ACTU, @ESTACION_ACTU, @CLASE_PARTIDA, @CORR_MONEDA, ISNULL(@FACTOR_CAMBIO, 1), ISNULL(@OPERADOR, '*'))
		END

		SELECT @SYS_FILAS_AFECTADAS = @@ROWCOUNT
	END TRY
	BEGIN CATCH
		DECLARE @CORR_BITACORA INT, @SEVERITY_ERROR INT, @ESTADO_ERROR INT,
		        @ORIGEN_ERROR NVARCHAR(126), @LINEA_ERROR INT, @SYS_FECHA DATETIME
		SELECT @CORR_BITACORA = 0, @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SEVERITY_ERROR = ERROR_SEVERITY(),
		       @ESTADO_ERROR = ERROR_STATE(), @ORIGEN_ERROR = ERROR_PROCEDURE(), @LINEA_ERROR = ERROR_LINE(),
		       @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FECHA = GETDATE()
		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1, @CORR_BITACORA OUTPUT, 'PM', @SYS_NUMERO_ERROR, @SEVERITY_ERROR, @ESTADO_ERROR, @ORIGEN_ERROR, @LINEA_ERROR, @SYS_MENSAJE_ERROR, @SYS_LOGIN_USUARIO, @SYS_FECHA, @SYS_ESTACION
	END CATCH
FINA:
END
GO
