SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================================================
-- Procedimiento: dbo.PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO
-- Qué hace: entrega datos para PDF Formato corto del Descriptor de puesto.
-- Cómo:
--   1) Result set 1: descriptor + funciones CLAVE/SECUNDARIA (1 fila por función;
--      NOMBRE_FUNCION_NUM viene de la vista ya numerado por TIPO_FUNCION).
--   2) Result set 2: encabezado/logos desde GEN_EMPRESA (mismo patrón partida).
-- Uso API: SC_DESCRIPTOR_PUESTO/getPDF → SGUEES-RPT SelectionHiring.
-- =============================================================================
IF OBJECT_ID(N'dbo.PRAL_IMPR_SC_DESCRIPTOR_PUESTO_VERSION_CORTA', N'P') IS NOT NULL
	DROP PROCEDURE dbo.PRAL_IMPR_SC_DESCRIPTOR_PUESTO_VERSION_CORTA;
GO
CREATE OR ALTER PROCEDURE [dbo].[PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO]
(
	@CORR_EMPRESA INT,
	@CORR_DESCRIPTOR_PUESTO INT
)
AS
BEGIN
	SET NOCOUNT ON;

	-- Detalle: encabezado del descriptor repetido + lista de funciones.
	SELECT
		A.CORR_EMPRESA,
		A.CORR_DESCRIPTOR_PUESTO,
		A.FECHA_EMISION,
		A.FECHA_REVISION,
		A.OBJETIVO_PUESTO,
		A.NUM_PERSONAL_CARGO,
		A.CORR_PUESTO,
		A.NOMBRE_PUESTO,
		A.CORR_UNIDAD,
		A.NOMBRE_UNIDAD,
		A.CORR_PUESTO_REPORTA,
		A.NOMBRE_EMPLEADO_REPORTA,
		A.CORR_IMPACTO_ECONOMICO,
		A.DESCRIPCION_IMPACTO_ECONOMICO,
		A.RESPONSABLE,
		A.FORMATO,
		A.VERSION,
		A.CORR_ESTADO,
		A.NOMBRE_ESTADO,
		A.USUARIO_CREA,
		A.ESTACION_CREA,
		A.FECHA_CREA,
		A.USUARIO_ACTU,
		A.ESTACION_ACTU,
		A.FECHA_ACTU,
		A.CORR_FUNCION,
		A.NOMBRE_FUNCION,
		A.TIPO_FUNCION,
		A.NOMBRE_FUNCION_NUM
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_IMPR A
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA
	  AND A.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY
		CASE A.TIPO_FUNCION
			WHEN N'CLAVE' THEN 1
			WHEN N'SECUNDARIA' THEN 2
			ELSE 3
		END,
		A.CORR_FUNCION;

	-- Encabezado / logos (GEN_PARAMETRO en Crystal).
	SELECT
		A.CORR_EMPRESA,
		A.NOMBRE_EMPRESA,
		CAST('' AS VARCHAR(100)) AS PERIODO,
		A.LOGO_1 AS LOGO1,
		A.LOGO_2 AS LOGO2,
		CAST(N'Descriptor de Puesto - Formato corto' AS VARCHAR(150)) AS TITULO_REPORTE,
		CAST('' AS VARCHAR(100)) AS NOMBRE_SISTEMA,
		GETDATE() AS FECHA_IMPRESION
	FROM dbo.GEN_EMPRESA A
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA;
END
GO
