SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_PLA_CARGO_CON_CENTRO_COSTO]
(
	@TIPO_CONSULTA int,
	@CORR_EMPRESA int=NULL,
	@CORR_CARGO int=NULL,
	@CORR_CENTRO_COSTO int=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT * FROM V_PLA_CARGO_CON_CENTRO_COSTO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CARGO=@CORR_CARGO
		END ELSE
		IF @OPCION_CONSULTA=1
		BEGIN
			SELECT * FROM V_PLA_CARGO_CON_CENTRO_COSTO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CENTRO_COSTO=@CORR_CENTRO_COSTO
		END
		
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		SELECT * FROM V_PLA_CARGO_CON_CENTRO_COSTO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_CARGO=@CORR_CARGO
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_PLA_CARGO_CON_CENTRO_COSTO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_CARGO=@CORR_CARGO
		AND CORR_CENTRO_COSTO=@CORR_CENTRO_COSTO
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT CORR_EMPRESA FROM V_PLA_CARGO_CON_CENTRO_COSTO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CARGO=@CORR_CARGO
			AND CORR_CENTRO_COSTO=@CORR_CENTRO_COSTO
		END
	END

END
GO
