
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_LIBRO_DIARIO_MAYOR]
( 
  @CORR_EMPRESA INT,
  @FECHA_INICIAL DATE,
  @FECHA_FINAL DATE,
  @CUENTA_CONTABLE_INICIAL varchar(30)=NULL,
  @CUENTA_CONTABLE_FINAL varchar(30)=NULL,
  @PARTIDA_CIERRE BIT=0,
  @PARTIDA_LIQUIDACION BIT=0,
  @CUENTA_A_CERO BIT=0,
  @CORR_MONEDA INT=NULL,
  @FECHA_IMPRESION DATE,
  @FOLIADO BIT=0,
  @NUMERO_FOLIO INT=0
)
AS	
	DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),
		CUENTA_MAYOR varchar(30),
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(12,2),
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),
		SALDO_FINAL	DECIMAL(12,2)
	)
	DECLARE @NIVEL_CUENTA_MAYOR SMALLINT
	
	DECLARE @CORR_MONEDA_LOCAL INT, @CORR_MONEDA_FORANEA INT
	 DECLARE @MOSTRAR_FECHA_IMPRESION BIT
BEGIN
    
    SET NOCOUNT ON
     
    
    
    
    SELECT 
    @NIVEL_CUENTA_MAYOR=NIVEL_CUENTA_MAYOR,
    @MOSTRAR_FECHA_IMPRESION=MOSTRAR_FECHA_IMPRESION
	FROM CON_PARAMETRO A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	
	SELECT @FECHA_INICIAL=DATEADD(DAY,-1,@FECHA_INICIAL)
	
	SELECT @CORR_MONEDA_LOCAL=CORR_MONEDA
	FROM CON_PARAMETRO
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	
	SET @CORR_MONEDA_FORANEA = NULL
	
	IF @CORR_MONEDA IS NULL
		SELECT @CORR_MONEDA=@CORR_MONEDA_LOCAL	
        
	IF @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL
	BEGIN
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL 
		@CORR_EMPRESA,
		@FECHA_INICIAL,
		1,--OPCION_CONSULTA=Saldo de todas las cuentas de un nivel hasta la fecha de consulta
		0,--MAYORIZA=Mayoriza los saldo
		@CUENTA_CONTABLE_INICIAL,
		@CUENTA_CONTABLE_FINAL,
		1, --Aplicar el debe o haber de la cuenta
		@PARTIDA_CIERRE, --Incluir partidas de cierre
		@PARTIDA_LIQUIDACION, --Incluir partidas de liquidación
		@NIVEL_CUENTA_MAYOR -- Solo cuentas de Mayor 
	END ELSE
	IF @CORR_MONEDA=@CORR_MONEDA_FORANEA
	BEGIN
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL_FORANEA
		@CORR_EMPRESA,
		@FECHA_INICIAL,
		1,--OPCION_CONSULTA=Saldo de todas las cuentas de un nivel hasta la fecha de consulta
		0,--MAYORIZA=Mayoriza los saldo
		@CUENTA_CONTABLE_INICIAL,
		@CUENTA_CONTABLE_FINAL,
		1, --Aplicar el debe o haber de la cuenta
		@PARTIDA_CIERRE, --Incluir partidas de cierre
		@PARTIDA_LIQUIDACION, --Incluir partidas de liquidación
		@NIVEL_CUENTA_MAYOR -- Solo cuentas de Mayor 
	END
    SELECT A.CORR_EMPRESA
        ,B.CODIGO_RUBRO
        ,B.NIVEL
        ,@NIVEL_CUENTA_MAYOR NIVEL_CUENTA_MAYOR
        ,ISNULL (K.PREFIJO,'')+ N1.CUENTA_CONTABLE CUENTA_CONTABLE_N1
        ,N1.NOMBRE_CUENTA NOMBRE_CUENTA_N1
        ,ISNULL (K.PREFIJO,'')+N2.CUENTA_CONTABLE CUENTA_CONTABLE_N2
        ,N2.NOMBRE_CUENTA NOMBRE_CUENTA_N2
        ,ISNULL (K.PREFIJO,'')+N3.CUENTA_CONTABLE CUENTA_CONTABLE_N3
        ,N3.NOMBRE_CUENTA NOMBRE_CUENTA_N3
        ,ISNULL (K.PREFIJO,'')+N4.CUENTA_CONTABLE CUENTA_CONTABLE_N4
        ,N4.NOMBRE_CUENTA NOMBRE_CUENTA_N4
        ,ISNULL (K.PREFIJO,'')+N5.CUENTA_CONTABLE CUENTA_CONTABLE_N5
        ,N5.NOMBRE_CUENTA NOMBRE_CUENTA_N5
		,ISNULL (K.PREFIJO,'')+A.CUENTA_CONTABLE CUENTA_CONTABLE
		,B.NOMBRE_CUENTA
		,C.FECHA_PARTIDA
		,ISNULL(C.MONTO_CARGO,0) MONTO_CARGO
		,ISNULL(C.MONTO_ABONO,0) MONTO_ABONO
		,'Movimiento del Dia' NOMBRE_TRAN
		,ISNULL(A.SALDO_FINAL,0) SALDO_INICIAL		
		,(CASE WHEN ROW_NUMBER() OVER(PARTITION BY A.CORR_EMPRESA,B.CUENTA_CONTABLE
		                              ORDER BY A.CORR_EMPRESA,B.CUENTA_CONTABLE,C.FECHA_PARTIDA, ISNULL(C.MONTO_ABONO,0),ISNULL(C.MONTO_ABONO,0))=1 THEN ISNULL(A.SALDO_FINAL,0) ELSE 0 END)
		+((ISNULL(C.MONTO_CARGO,0)-ISNULL(C.MONTO_ABONO,0))*(CASE WHEN B.ES_DEBE=1 THEN 1 ELSE CASE WHEN B.ES_HABER=1 THEN -1 ELSE 0 END END)) SALDO_FINAL
		,'' NOMBRE_MONEDA
		,'' DESCRIPCION_MONEDA
		,'' SIMBOLO_MONEDA
		,CONVERT(BIT,ISNULL(@MOSTRAR_FECHA_IMPRESION,0)) MOSTRAR_FECHA_IMPRESION
		,ISNULL(@FECHA_IMPRESION,GETDATE()) FECHA_IMPRESION
		,@FOLIADO FOLIADO
		,@NUMERO_FOLIO NUMERO_FOLIO
	FROM @SALDO A
	INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE		
	LEFT OUTER JOIN (SELECT A.CORR_EMPRESA,A.CUENTA_CONTABLE,A.FECHA_PARTIDA
					 ,CASE WHEN @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL THEN SUM(A.MONTO_CARGO) ELSE SUM(A.MONTO_CARGO_FORANEA) END MONTO_CARGO
					 ,CASE WHEN @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL THEN SUM(A.MONTO_ABONO) ELSE SUM(A.MONTO_ABONO_FORANEA) END MONTO_ABONO
					 
					 FROM V_CON_PARTIDA_CUENTA_MAYOR A					 
					 WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					 AND A.FECHA_PARTIDA>@FECHA_INICIAL
					 AND A.FECHA_PARTIDA<=@FECHA_FINAL
					 AND (A.CUENTA_CONTABLE>=@CUENTA_CONTABLE_INICIAL OR ISNULL(@CUENTA_CONTABLE_INICIAL,'')='')
					 AND (A.CUENTA_CONTABLE<=@CUENTA_CONTABLE_FINAL OR ISNULL(@CUENTA_CONTABLE_FINAL,'')='')
					 AND (ISNULL(A.PARTIDA_CIERRE,0)=@PARTIDA_CIERRE OR @PARTIDA_CIERRE=1)
					 AND (ISNULL(A.PARTIDA_LIQUIDACION,0)=@PARTIDA_LIQUIDACION OR @PARTIDA_LIQUIDACION=1)
					 GROUP BY A.CORR_EMPRESA,A.CUENTA_CONTABLE,A.FECHA_PARTIDA)C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA N1 ON B.CORR_EMPRESA=N1.CORR_EMPRESA AND SUBSTRING(B.CUENTA_CONTABLE,1,LEN(N1.CUENTA_CONTABLE))=N1.CUENTA_CONTABLE AND N1.NIVEL=1
	LEFT OUTER JOIN CON_CATALOGO_CUENTA N2 ON B.CORR_EMPRESA=N2.CORR_EMPRESA AND SUBSTRING(B.CUENTA_CONTABLE,1,LEN(N2.CUENTA_CONTABLE))=N2.CUENTA_CONTABLE AND N2.NIVEL=2
	LEFT OUTER JOIN CON_CATALOGO_CUENTA N3 ON B.CORR_EMPRESA=N3.CORR_EMPRESA AND SUBSTRING(B.CUENTA_CONTABLE,1,LEN(N3.CUENTA_CONTABLE))=N3.CUENTA_CONTABLE AND N3.NIVEL=3
	LEFT OUTER JOIN CON_CATALOGO_CUENTA N4 ON B.CORR_EMPRESA=N4.CORR_EMPRESA AND SUBSTRING(B.CUENTA_CONTABLE,1,LEN(N4.CUENTA_CONTABLE))=N4.CUENTA_CONTABLE AND N4.NIVEL=4
	LEFT OUTER JOIN CON_CATALOGO_CUENTA N5 ON B.CORR_EMPRESA=N5.CORR_EMPRESA AND SUBSTRING(B.CUENTA_CONTABLE,1,LEN(N5.CUENTA_CONTABLE))=N5.CUENTA_CONTABLE AND N5.NIVEL=5
	INNER JOIN CON_PARAMETRO  K  ON B.CORR_EMPRESA=K.CORR_EMPRESA 
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	AND (@CUENTA_A_CERO=1 OR (@CUENTA_A_CERO<>1 AND (A.SALDO_FINAL<>0 OR C.MONTO_CARGO<>0 OR C.MONTO_ABONO<>0)))
	ORDER BY A.CORR_EMPRESA, A.CUENTA_CONTABLE, C.FECHA_PARTIDA,C.MONTO_CARGO,C.MONTO_ABONO
	
	SELECT A.CORR_EMPRESA
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END			
GO

