SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_BALANCE_GENERAL_VERTICAL]
( 
  @CORR_EMPRESA INT,
  @FECHA_FINAL DATE,
  @NIVEL SMALLINT,
  @PARTIDA_CIERRE BIT=0,
  @PARTIDA_LIQUIDACION BIT=0,
  @CORR_MONEDA INT=NULL,
  @FOLIADO BIT=0,
  @NUMERO_FOLIO INT=0,
  @MUESTRA_FIRMA BIT=0
)
AS	
	DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),
		CUENTA_MAYOR varchar(30),
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(12,2),
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),
		SALDO_FINAL	DECIMAL(12,2),
		PRIMARY KEY (
			CORR_EMPRESA, CUENTA_CONTABLE
		)
	)

	DECLARE @CORR_MONEDA_LOCAL INT, @CORR_MONEDA_FORANEA INT

	DECLARE @PERDIDA_GANA DECIMAL(12,2),@PERDIDA_GANA_MES DECIMAL(12,2), @CUENTA_PERDIDA_GANA VARCHAR(30),
	@NOMBRE_PUESTO1 VARCHAR(100),
	@DESCRIPCION_PUESTO1 VARCHAR(100),
	@NOMBRE_PUESTO2 VARCHAR(100),
	@DESCRIPCION_PUESTO2 VARCHAR(100),
	@NOMBRE_PUESTO3 VARCHAR(100),
	@DESCRIPCION_PUESTO3 VARCHAR(100),
	@DESCRIPCION_MONEDA VARCHAR(255)
BEGIN

    SET NOCOUNT ON
	SELECT @CORR_MONEDA_LOCAL=CORR_MONEDA
	FROM CON_PARAMETRO
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	
	SET @CORR_MONEDA_FORANEA = NULL

	IF @CORR_MONEDA IS NULL
		SELECT @CORR_MONEDA=@CORR_MONEDA_LOCAL	


	IF @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL
	BEGIN
		--Obteniendo el saldo solo de las cuentas de ingresos y gastos
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL 
	@CORR_EMPRESA,
		@FECHA_FINAL,
		1,--OPCION_CONSULTA=Saldo de las cuentas contables de Ingresos y Gastos hasta la fecha de consulta
		0,--MAYORIZA=Mayoriza los saldo
		'',
		'',	
		1, --Aplicar el debe o haber de la cuenta
		@PARTIDA_CIERRE, --Incluir partidas de cierre
		@PARTIDA_LIQUIDACION, --Incluir partidas de liquidación
		@NIVEL --Hasta el nivel indicado	
	END ELSE
	IF @CORR_MONEDA=@CORR_MONEDA_FORANEA
	BEGIN
		--Obteniendo el saldo solo de las cuentas de ingresos y gastos
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL_FORANEA
	@CORR_EMPRESA,
		@FECHA_FINAL,
		1,--OPCION_CONSULTA=Saldo de las cuentas contables de Ingresos y Gastos hasta la fecha de consulta
		0,--MAYORIZA=Mayoriza los saldo
		'',
		'',	
		1, --Aplicar el debe o haber de la cuenta
		@PARTIDA_CIERRE, --Incluir partidas de cierre
		@PARTIDA_LIQUIDACION, --Incluir partidas de liquidación
		@NIVEL --Hasta el nivel indicado	
	END
    --Obteniendo la perdida o ganancia
    -------------------------------------------------------------------------------------------------------------------
    SELECT @PERDIDA_GANA=SUM(CASE WHEN B.CLASE_RUBRO='IN' THEN ISNULL(A.SALDO_FINAL,0) ELSE ISNULL(A.SALDO_FINAL,0)*-1 END),
    @PERDIDA_GANA_MES=SUM(CASE WHEN B.CLASE_RUBRO='IN' THEN CASE WHEN B.ES_DEBE=1 THEN 1 ELSE -1 END * (ISNULL(A.CARGO_PERIODO,0)-ISNULL(A.ABONO_PERIODO,0)) ELSE CASE WHEN B.ES_DEBE=1 THEN 1 ELSE -1 END * (ISNULL(A.CARGO_PERIODO,0)-ISNULL(A.ABONO_PERIODO,0))*-1 END)
    FROM @SALDO A
    INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
    WHERE B.CLASE_RUBRO IN('IN','GA')
    --AND B.NIVEL=1

    IF @PERDIDA_GANA>=0 --Si es Ganancia
    BEGIN
	    SELECT @CUENTA_PERDIDA_GANA=ISNULL(A.CUENTA_CONTABLE_GANANCIA,'')
	    FROM CON_PARAMETRO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
    END ELSE --Si es Perdida
    BEGIN
	    SELECT @CUENTA_PERDIDA_GANA=ISNULL(A.CUENTA_CONTABLE_PERDIDA,'')
	    FROM CON_PARAMETRO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
    END

    --Obteniendo la cuenta según el nivel del reporte
    SELECT @CUENTA_PERDIDA_GANA=SUBSTRING(@CUENTA_PERDIDA_GANA,1,A.NUMERO_CARACTERES)
    FROM CON_RUBRO_NIVEL A
    INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CODIGO_RUBRO=B.CODIGO_RUBRO
    WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	AND A.NIVEL=@NIVEL
	AND B.CUENTA_CONTABLE=@CUENTA_PERDIDA_GANA

    --Actualizando el saldo de la perdida o ganancia
    UPDATE @SALDO SET
    SALDO_FINAL=ISNULL(SALDO_FINAL,0)+@PERDIDA_GANA,
    CARGO_PERIODO=@PERDIDA_GANA_MES,
    ABONO_PERIODO=0
    WHERE CORR_EMPRESA=@CORR_EMPRESA
	AND CUENTA_CONTABLE=@CUENTA_PERDIDA_GANA
	--AND @CUENTA_PERDIDA_GANA LIKE CUENTA_CONTABLE+'%'
	-------------------------------------------------------------------------------------------	

    DECLARE @MOSTRAR_FECHA_IMPRESION BIT

    --Obteniendo las personas que firmarán en balance general
    SELECT @NOMBRE_PUESTO1=A.NOMBRE_PUESTO1,
	@DESCRIPCION_PUESTO1=A.DESCRIPCION_PUESTO1,
	@NOMBRE_PUESTO2=A.NOMBRE_PUESTO2,
	@DESCRIPCION_PUESTO2=A.DESCRIPCION_PUESTO2,
	@NOMBRE_PUESTO3=A.NOMBRE_PUESTO3,
	@DESCRIPCION_PUESTO3=A.DESCRIPCION_PUESTO3,
	@MOSTRAR_FECHA_IMPRESION=MOSTRAR_FECHA_IMPRESION
	FROM CON_PARAMETRO A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA

	--Obteniendo en que moneda esta el balance general
	SET @DESCRIPCION_MONEDA = ''
    SELECT @CORR_EMPRESA CORR_EMPRESA
    ,ISNULL(G.PREFIJO,'')+F.CUENTA_CONTABLE CUENTA_MAYOR_4
    ,F.NOMBRE_CUENTA NOMBRE_CUENTA_MAYOR_4
    ,ISNULL(G.PREFIJO,'')+E.CUENTA_CONTABLE CUENTA_MAYOR_3
    ,E.NOMBRE_CUENTA NOMBRE_CUENTA_MAYOR_3
    ,ISNULL(G.PREFIJO,'')+D.CUENTA_CONTABLE CUENTA_MAYOR_2
    ,D.NOMBRE_CUENTA NOMBRE_CUENTA_MAYOR_2
    ,ISNULL(G.PREFIJO,'')+C.CUENTA_CONTABLE CUENTA_MAYOR_1
    ,C.NOMBRE_CUENTA NOMBRE_CUENTA_MAYOR_1
    ,ISNULL(G.PREFIJO,'')+A.CUENTA_CONTABLE AS CUENTA_CONTABLE
    ,B.NOMBRE_CUENTA
    ,SUM(A.SALDO_INICIAL) SALDO_INICIAL
    ,SUM(CASE WHEN B.ES_DEBE=1 THEN 1 ELSE -1 END * (ISNULL(A.CARGO_PERIODO,0)-ISNULL(A.ABONO_PERIODO,0))) SALDO_MES
    ,SUM(A.SALDO_FINAL) SALDO_FINAL
    ,B.NIVEL
    ,B.CLASE_RUBRO
    ,@NOMBRE_PUESTO1 NOMBRE_PUESTO1
	,@DESCRIPCION_PUESTO1 DESCRIPCION_PUESTO1
	,@NOMBRE_PUESTO2 NOMBRE_PUESTO2
	,@DESCRIPCION_PUESTO2 DESCRIPCION_PUESTO2
	,@NOMBRE_PUESTO3 NOMBRE_PUESTO3
	,@DESCRIPCION_PUESTO3 DESCRIPCION_PUESTO3
	,@DESCRIPCION_MONEDA DESCRIPCION_MONEDA		
	,@FOLIADO FOLIADO
	,@NUMERO_FOLIO NUMERO_FOLIO
	,CONVERT(BIT,ISNULL(@MOSTRAR_FECHA_IMPRESION,0)) MOSTRAR_FECHA_IMPRESION
	,@MUESTRA_FIRMA MUESTRA_FIRMA
    FROM @SALDO A
	INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
	INNER JOIN CON_CATALOGO_CUENTA C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CUENTA_MAYOR=C.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA D ON C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CUENTA_MAYOR=D.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA E ON D.CORR_EMPRESA=E.CORR_EMPRESA AND D.CUENTA_MAYOR=E.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA F ON E.CORR_EMPRESA=F.CORR_EMPRESA AND E.CUENTA_MAYOR=F.CUENTA_CONTABLE		
	INNER JOIN CON_PARAMETRO G ON A.CORR_EMPRESA=G.CORR_EMPRESA
	WHERE B.CLASE_RUBRO IN('AC','PA','PT','LI')
	GROUP BY ISNULL(G.PREFIJO,'')+A.CUENTA_CONTABLE, B.NOMBRE_CUENTA, B.NIVEL, B.CLASE_RUBRO
	,ISNULL(G.PREFIJO,'')+F.CUENTA_CONTABLE,F.NOMBRE_CUENTA
    ,ISNULL(G.PREFIJO,'')+E.CUENTA_CONTABLE,E.NOMBRE_CUENTA
    ,ISNULL(G.PREFIJO,'')+D.CUENTA_CONTABLE,D.NOMBRE_CUENTA
    ,ISNULL(G.PREFIJO,'')+C.CUENTA_CONTABLE,C.NOMBRE_CUENTA
	HAVING SUM(A.SALDO_FINAL)<>0 OR SUM(A.CARGO_PERIODO)<>0 OR SUM(A.ABONO_PERIODO)<>0
	ORDER BY CASE WHEN B.CLASE_RUBRO='AC' THEN 0 
				  WHEN B.CLASE_RUBRO='PA' THEN 1
				  WHEN B.CLASE_RUBRO='PT' THEN 2
				  WHEN B.CLASE_RUBRO='LI' THEN 3
				  ELSE 4 END,
				  CUENTA_CONTABLE



	SELECT A.CORR_EMPRESA 
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END



GO

