
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_IMPR_BAN_CONCILIA_BANCARIA]
(
	@CORR_EMPRESA int=NULL,
	@CORR_CUENTA_BANCO int=NULL,
	@CORR_CONCILIACION int=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @TEMP_TOTAL_AUMENTA TABLE(
		CORR_EMPRESA INT,
		CORR_CUENTA_BANCO INT NULL,
	    CORR_CONCILIACION INT NULL,
		MONTO DECIMAL(12,4)
	)

   DECLARE @TEMP_TOTAL_DESMINUYE TABLE(
		CORR_EMPRESA INT,
		CORR_CUENTA_BANCO INT NULL,
	    CORR_CONCILIACION INT NULL,
		MONTO DECIMAL(12,4)
	)


	INSERT INTO @TEMP_TOTAL_AUMENTA (   
	CORR_EMPRESA ,
	CORR_CUENTA_BANCO ,
	CORR_CONCILIACION ,
	MONTO)
	SELECT A.CORR_EMPRESA,
	@CORR_CUENTA_BANCO,
	@CORR_CONCILIACION,
	SUM(ISNULL(B.MONTO,0)) MONTO
	FROM V_BAN_LINEA_TRABAJO_CONCILIACION A
	LEFT OUTER JOIN V_BAN_CONCILIA_BANCARIA_MOVI B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_LINEA=B.CORR_LINEA
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	AND A.AUMENTA_DISMINUYE=1
	AND B.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
	AND B.CORR_CONCILIACION=@CORR_CONCILIACION	
	GROUP BY A.CORR_EMPRESA
		
    INSERT INTO @TEMP_TOTAL_DESMINUYE(   
	CORR_EMPRESA ,
	CORR_CUENTA_BANCO ,
	CORR_CONCILIACION ,
	MONTO)
	SELECT A.CORR_EMPRESA,
	@CORR_CUENTA_BANCO,
	@CORR_CONCILIACION,
	SUM(ISNULL(B.MONTO,0)) MONTO
	FROM V_BAN_LINEA_TRABAJO_CONCILIACION A
	LEFT OUTER JOIN V_BAN_CONCILIA_BANCARIA_MOVI B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_LINEA=B.CORR_LINEA
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	AND A.AUMENTA_DISMINUYE=-1
	AND B.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
	AND B.CORR_CONCILIACION=@CORR_CONCILIACION	
	GROUP BY A.CORR_EMPRESA
		
	SELECT A.*,
	ISNULL(B.MONTO,0) MONTO_AUMENTA,
	ISNULL(C.MONTO,0) MONTO_DESMINUYE,
	ISNULL((A.SALDO_CUENTA_BANCO+ISNULL(B.MONTO,0))-ISNULL(C.MONTO,0),0) SALDO_CONCILIADO
	FROM V_BAN_CONCILIA_BANCARIA_IMPRIME A
	LEFT OUTER JOIN @TEMP_TOTAL_AUMENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=B.CORR_CUENTA_BANCO AND A.CORR_CONCILIACION=B.CORR_CONCILIACION
	LEFT OUTER JOIN @TEMP_TOTAL_DESMINUYE C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=C.CORR_CUENTA_BANCO AND A.CORR_CONCILIACION=C.CORR_CONCILIACION
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	AND A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
	AND A.CORR_CONCILIACION=@CORR_CONCILIACION
	
	SELECT A.CORR_EMPRESA
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,LOGO_1 LOGO1
	,LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA

END
GO

