SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: inserta un evento en CON_PARTIDA_BITACORA (INGRESAR, ACTUALIZAR, APLICAR, DESAPLICAR, ANULAR).
-- Cómo lo hace: calcula CORR_PARTIDA_BITACORA = MAX+1 por partida, valida TIPO_EVENTO y que exista la partida, luego INSERT.
CREATE OR ALTER PROCEDURE [dbo].[PRAL_MTTO_CON_PARTIDA_BITACORA]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_CLASE_PARTIDA int,
	@CORR_PARTIDA int,
	@CORR_PARTIDA_BITACORA int OUTPUT,
	@TIPO_EVENTO varchar(20),
	@FECHA_EVENTO datetime = NULL,
	@ESTADO_ANTERIOR varchar(2) = NULL,
	@ESTADO_NUEVO varchar(2) = NULL,
	@OBSERVACION varchar(255) = NULL,
	@USUARIO_CREA varchar(30),
	@ESTACION_CREA varchar(50),
	@SYS_LOGIN_USUARIO varchar(30),
	@SYS_ESTACION varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = '', @SYS_FILAS_AFECTADAS = 0, @CORR_PARTIDA_BITACORA = 0

	BEGIN TRY
		-- Qué hace: normaliza fecha del evento si no viene.
		-- Cómo lo hace: usa GETDATE() cuando @FECHA_EVENTO es NULL.
		IF @FECHA_EVENTO IS NULL
			SELECT @FECHA_EVENTO = GETDATE()

		IF @USUARIO_CREA IS NULL OR LTRIM(RTRIM(@USUARIO_CREA)) = ''
			SELECT @USUARIO_CREA = @SYS_LOGIN_USUARIO

		IF @ESTACION_CREA IS NULL OR LTRIM(RTRIM(@ESTACION_CREA)) = ''
			SELECT @ESTACION_CREA = @SYS_ESTACION

		-- Qué hace: valida el tipo de evento permitido por el CHECK de la tabla.
		IF @TIPO_EVENTO NOT IN ('INGRESAR', 'ACTUALIZAR', 'APLICAR', 'DESAPLICAR', 'ANULAR')
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30001,
				@SYS_MENSAJE_ERROR = 'TIPO_EVENTO no válido. Use INGRESAR, ACTUALIZAR, APLICAR, DESAPLICAR o ANULAR.',
				@SYS_FILAS_AFECTADAS = 0
			GOTO FINA
		END

		-- Qué hace: asegura que la partida exista (FK a CON_PARTIDA).
		IF NOT EXISTS (
			SELECT 1
			FROM CON_PARTIDA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA
			AND CORR_PARTIDA = @CORR_PARTIDA
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30002,
				@SYS_MENSAJE_ERROR = 'La partida no existe. No se puede registrar en bitácora.',
				@SYS_FILAS_AFECTADAS = 0
			GOTO FINA
		END

		-- Qué hace: genera el correlativo de bitácora por partida.
		-- Cómo lo hace: MAX(CORR_PARTIDA_BITACORA)+1 filtrado por la PK de la partida.
		SELECT @CORR_PARTIDA_BITACORA = ISNULL(MAX(CORR_PARTIDA_BITACORA), 0) + 1
		FROM CON_PARTIDA_BITACORA
		WHERE CORR_EMPRESA = @CORR_EMPRESA
		AND ANIO_PERIODO = @ANIO_PERIODO
		AND MES_PERIODO = @MES_PERIODO
		AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA
		AND CORR_PARTIDA = @CORR_PARTIDA

		INSERT INTO CON_PARTIDA_BITACORA
		(
			CORR_EMPRESA,
			CORR_PARTIDA_BITACORA,
			ANIO_PERIODO,
			MES_PERIODO,
			CORR_CLASE_PARTIDA,
			CORR_PARTIDA,
			TIPO_EVENTO,
			FECHA_EVENTO,
			ESTADO_ANTERIOR,
			ESTADO_NUEVO,
			OBSERVACION,
			USUARIO_CREA,
			ESTACION_CREA
		)
		VALUES
		(
			@CORR_EMPRESA,
			@CORR_PARTIDA_BITACORA,
			@ANIO_PERIODO,
			@MES_PERIODO,
			@CORR_CLASE_PARTIDA,
			@CORR_PARTIDA,
			@TIPO_EVENTO,
			@FECHA_EVENTO,
			@ESTADO_ANTERIOR,
			@ESTADO_NUEVO,
			@OBSERVACION,
			@USUARIO_CREA,
			@ESTACION_CREA
		)

		SELECT @SYS_FILAS_AFECTADAS = @@ROWCOUNT
	END TRY
	BEGIN CATCH
		DECLARE
			@CORR_BITACORA int,
			@SEVERITY_ERROR int,
			@ESTADO_ERROR int,
			@ORIGEN_ERROR nvarchar(126),
			@LINEA_ERROR int,
			@SYS_FECHA datetime

		SELECT @CORR_PARTIDA_BITACORA = 0,
			@CORR_BITACORA = 0,
			@SYS_NUMERO_ERROR = ERROR_NUMBER(),
			@SEVERITY_ERROR = ERROR_SEVERITY(),
			@ESTADO_ERROR = ERROR_STATE(),
			@ORIGEN_ERROR = ERROR_PROCEDURE(),
			@LINEA_ERROR = ERROR_LINE(),
			@SYS_MENSAJE_ERROR = ERROR_MESSAGE(),
			@SYS_FECHA = GETDATE(),
			@SYS_FILAS_AFECTADAS = 0

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA
			1,
			@CORR_BITACORA OUTPUT,
			'PM',
			@SYS_NUMERO_ERROR,
			@SEVERITY_ERROR,
			@ESTADO_ERROR,
			@ORIGEN_ERROR,
			@LINEA_ERROR,
			@SYS_MENSAJE_ERROR,
			@SYS_LOGIN_USUARIO,
			@SYS_FECHA,
			@SYS_ESTACION
	END CATCH
FINA:
END
GO
