SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_CONCILIA_BANCARIA]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA int,
	@CORR_CUENTA_BANCO int,
	@CORR_CONCILIACION int OUTPUT,
	@FECHA_CONCILIACION date,
	@SALDO_CUENTA_BANCO decimal(18,2),
	@SALDO_CUENTA_CONTA decimal(18,2),
	@ESTADO_CONCILIACION varchar(2),
	@USUARIO_CREA varchar(30),
	@FECHA_CREA datetime,
	@ESTACION_CREA varchar(50),
	@USUARIO_ACTU varchar(30),
	@FECHA_ACTU datetime,
	@ESTACION_ACTU varchar(50),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
	DECLARE @CONCILIACION_DETA TABLE (
		CORR_CONCILIACION_DETA INT
	)
	DECLARE @CORR_CONCILIACION_DETA INT
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1,2)
		BEGIN
			--Verificando la cuenta bancaria
			IF (@CORR_CUENTA_BANCO IS NULL
			   OR NOT EXISTS(SELECT 1 FROM BAN_CUENTA_BANCARIA
			                 WHERE CORR_EMPRESA=@CORR_EMPRESA
			                 AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO))
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe la cuenta bancaria seleccionada',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END
		IF @TIPO_ACTUALIZA IN (2,3)
		BEGIN
			--Verificando el estado
			SELECT @ESTADO_CONCILIACION=ESTADO_CONCILIACION
			FROM BAN_CONCILIA_BANCARIA 
			WHERE CORR_EMPRESA=@CORR_EMPRESA 
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
			AND CORR_CONCILIACION=@CORR_CONCILIACION 
			
			IF @ESTADO_CONCILIACION<>'DI'
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Esta conciliacion no puede ser modificada o eliminada.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @CORR_CONCILIACION=ISNULL(MAX(CORR_CONCILIACION),0)+1, @ESTADO_CONCILIACION='DI'
			FROM BAN_CONCILIA_BANCARIA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO

			INSERT INTO BAN_CONCILIA_BANCARIA
			(CORR_EMPRESA,CORR_CUENTA_BANCO,CORR_CONCILIACION,FECHA_CONCILIACION,SALDO_CUENTA_BANCO,SALDO_CUENTA_CONTA,ESTADO_CONCILIACION,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU)
			VALUES
			(@CORR_EMPRESA,@CORR_CUENTA_BANCO,@CORR_CONCILIACION,@FECHA_CONCILIACION,@SALDO_CUENTA_BANCO,@SALDO_CUENTA_CONTA,@ESTADO_CONCILIACION,@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN			
			UPDATE BAN_CONCILIA_BANCARIA SET
			FECHA_CONCILIACION=@FECHA_CONCILIACION,
			SALDO_CUENTA_BANCO=@SALDO_CUENTA_BANCO,
			SALDO_CUENTA_CONTA=@SALDO_CUENTA_CONTA,
			ESTADO_CONCILIACION=@ESTADO_CONCILIACION,
			--USUARIO_CREA=@USUARIO_CREA,
			--FECHA_CREA=@FECHA_CREA,
			--ESTACION_CREA=@ESTACION_CREA,
			USUARIO_ACTU=@USUARIO_ACTU,
			FECHA_ACTU=@FECHA_ACTU,
			ESTACION_ACTU=@ESTACION_ACTU
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			INSERT INTO @CONCILIACION_DETA (CORR_CONCILIACION_DETA)
			SELECT CORR_CONCILIACION_DETA
			FROM BAN_CONCILIA_BANCARIA_DETA 
			WHERE CORR_EMPRESA=@CORR_EMPRESA 
			AND CORR_CONCILIACION=@CORR_CONCILIACION 
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
			AND NOT ANIO_PERIODO IS NULL
			AND NOT MES_PERIODO IS NULL
			AND NOT CORR_CLASE_PARTIDA IS NULL
			AND NOT CORR_PARTIDA IS NULL 
			AND NOT CORR_PARTIDA IS NULL

			WHILE EXISTS(SELECT 1 FROM @CONCILIACION_DETA)
			BEGIN
				SELECT TOP 1 @CORR_CONCILIACION_DETA=CORR_CONCILIACION_DETA
				FROM @CONCILIACION_DETA
				ORDER BY CORR_CONCILIACION_DETA

				EXEC PRAL_GENE_BAN_CONCILIACION_REVERTIR
				@CORR_EMPRESA,
				@CORR_CUENTA_BANCO,
				@CORR_CONCILIACION,
				@CORR_CONCILIACION_DETA,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@SYS_FILAS_AFECTADAS output,
				@SYS_NUMERO_ERROR output,
				@SYS_MENSAJE_ERROR output
				
				DELETE FROM @CONCILIACION_DETA
				WHERE CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA
			END

			DELETE FROM BAN_CONCILIA_BANCARIA_DETA 
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
			
			DELETE FROM BAN_CONCILIA_BANCARIA_MOVI
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
			
			DELETE FROM BAN_CONCILIA_BANCARIA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO

