SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_CONCILIA_BANCARIA_DETA]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA int,
	@CORR_CUENTA_BANCO int,
	@CORR_CONCILIACION int,
	@CORR_CONCILIACION_DETA int OUTPUT,
	@FECHA_MOVIMIENTO date,
	@CORR_TIPO_MOVIMIENTO int,
	@NUMERO_REFERENCIA_BANCO varchar(255),
	@MONTO_CARGO decimal(18,2),
	@MONTO_ABONO decimal(18,2),
	@ANIO_PERIODO int = NULL,
	@MES_PERIODO int = NULL,
	@CORR_CLASE_PARTIDA int = NULL,
	@CORR_PARTIDA int = NULL,
	@CORR_PARTIDA_DETA int = NULL,
	@CODIGO_TRANSACCION VARCHAR(30)='',
	@DESCRIPCION_TRANSACCION VARCHAR(255)='',
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1,2,3)
		BEGIN
			--Verificando el estado
			DECLARE @ESTADO_CONCILIACION VARCHAR(2)
			SELECT @ESTADO_CONCILIACION=ESTADO_CONCILIACION
			FROM BAN_CONCILIA_BANCARIA 
			WHERE CORR_EMPRESA=@CORR_EMPRESA 
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
			AND CORR_CONCILIACION=@CORR_CONCILIACION 
			
			IF @ESTADO_CONCILIACION<>'DI'
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Esta conciliacion no puede ser modificada o eliminada.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END
		IF @TIPO_ACTUALIZA IN (1,2)
		BEGIN
			IF NOT EXISTS ( SELECT 1 FROM BAN_TIPO_MOVI_BANCARIO
							WHERE CORR_EMPRESA=@CORR_EMPRESA 
							AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='No ha seleccionado correctamente el tipo de movimiento bancario. [' + @NUMERO_REFERENCIA_BANCO + ']' ,@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			IF NOT EXISTS ( SELECT 1 FROM CON_PARTIDA_DETA 
							WHERE CORR_EMPRESA=@CORR_EMPRESA 
							AND ANIO_PERIODO=@ANIO_PERIODO 
							AND MES_PERIODO=@MES_PERIODO 
							AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA 
							AND CORR_PARTIDA=@CORR_PARTIDA 
							AND CORR_PARTIDA_DETA=@CORR_CONCILIACION_DETA )
			BEGIN
				SELECT @ANIO_PERIODO=NULL, @MES_PERIODO=NULL, @CORR_CLASE_PARTIDA=NULL, @CORR_PARTIDA=NULL, @CORR_PARTIDA_DETA=NULL
			END
			IF @MONTO_ABONO<0 OR @MONTO_CARGO<0
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No introduzca montos negativos',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			IF @MONTO_ABONO>0 AND @MONTO_CARGO>0
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Escriba al menos un monto igual que cero',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			IF @MONTO_ABONO=0 AND @MONTO_CARGO=0
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Escriba al menos un monto mayor que cero',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
		END
		IF @TIPO_ACTUALIZA IN (2,3)
		BEGIN
			--Se verifica que no exista vinculacion con una partida de contabilidad
			IF NOT EXISTS ( SELECT 1 FROM BAN_CONCILIA_BANCARIA_DETA
						WHERE CORR_EMPRESA=@CORR_EMPRESA
						AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
						AND CORR_CONCILIACION=@CORR_CONCILIACION
						AND CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA
						AND ANIO_PERIODO IS NULL
						AND MES_PERIODO IS NULL
						AND CORR_CLASE_PARTIDA IS NULL
						AND CORR_PARTIDA IS NULL
						AND CORR_PARTIDA_DETA IS NULL )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No se puede modificar ni eliminar porque ya esta vinculado a una partida.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
		END
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @CORR_CONCILIACION_DETA=ISNULL(MAX(CORR_CONCILIACION_DETA),0)+1
			FROM BAN_CONCILIA_BANCARIA_DETA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
			
			--Inicialmente no estara vinculado a una partida contable
			SELECT @ANIO_PERIODO=NULL, @MES_PERIODO=NULL, @CORR_CLASE_PARTIDA=NULL, @CORR_PARTIDA=NULL, @CORR_PARTIDA_DETA=NULL
			
			INSERT INTO BAN_CONCILIA_BANCARIA_DETA
			(CORR_EMPRESA,CORR_CUENTA_BANCO,CORR_CONCILIACION,CORR_CONCILIACION_DETA,FECHA_MOVIMIENTO,CORR_TIPO_MOVIMIENTO,NUMERO_REFERENCIA_BANCO,MONTO_CARGO,MONTO_ABONO,ANIO_PERIODO,MES_PERIODO,CORR_CLASE_PARTIDA,CORR_PARTIDA,CORR_PARTIDA_DETA,CODIGO_TRANSACCION,DESCRIPCION_TRANSACCION)
			VALUES
			(@CORR_EMPRESA,@CORR_CUENTA_BANCO,@CORR_CONCILIACION,@CORR_CONCILIACION_DETA,@FECHA_MOVIMIENTO,@CORR_TIPO_MOVIMIENTO,@NUMERO_REFERENCIA_BANCO,@MONTO_CARGO,@MONTO_ABONO,@ANIO_PERIODO,@MES_PERIODO,@CORR_CLASE_PARTIDA,@CORR_PARTIDA,@CORR_PARTIDA_DETA,@CODIGO_TRANSACCION,@DESCRIPCION_TRANSACCION)
		
			DECLARE @MAXIMO int
			--Se inserta el concilia_deta en concilia_movi, ya que deja no esta conciliado inicialmente
			SELECT @MAXIMO=ISNULL(MAX(CORR_MOVIMIENTO),0)+1
			FROM BAN_CONCILIA_BANCARIA_MOVI
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
			
			INSERT INTO BAN_CONCILIA_BANCARIA_MOVI
			(CORR_EMPRESA,CORR_CUENTA_BANCO,CORR_CONCILIACION,CORR_MOVIMIENTO,CORR_LINEA,ANIO_PERIODO,MES_PERIODO,CORR_CLASE_PARTIDA,CORR_PARTIDA,CORR_PARTIDA_DETA,CORR_TIPO_MOVIMIENTO,CORR_CONCILIACION_DETA,MONTO_CARGO,MONTO_ABONO)
			SELECT @CORR_EMPRESA,@CORR_CUENTA_BANCO,@CORR_CONCILIACION,@MAXIMO,B.CORR_LINEA,NULL ANIO_PERIODO,NULL MES_PERIODO,NULL CORR_CLASE_PARTIDA,NULL CORR_PARTIDA,NULL CORR_PARTIDA_DETA,A.CORR_TIPO_MOVIMIENTO,A.CORR_CONCILIACION_DETA,A.MONTO_CARGO,A.MONTO_ABONO 
			FROM BAN_CONCILIA_BANCARIA_DETA A
			INNER JOIN BAN_TIPO_MOVI_BANCARIO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO=B.CORR_TIPO_MOVIMIENTO
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA 
			AND A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
			AND A.CORR_CONCILIACION=@CORR_CONCILIACION 
			AND A.CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA
		
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE BAN_CONCILIA_BANCARIA_DETA SET
			FECHA_MOVIMIENTO=@FECHA_MOVIMIENTO,
			CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO,
			NUMERO_REFERENCIA_BANCO=@NUMERO_REFERENCIA_BANCO,
			MONTO_CARGO=@MONTO_CARGO,
			MONTO_ABONO=@MONTO_ABONO,
			ANIO_PERIODO=@ANIO_PERIODO,
			MES_PERIODO=@MES_PERIODO,
			CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA,
			CORR_PARTIDA=@CORR_PARTIDA,
			CORR_PARTIDA_DETA=@CORR_PARTIDA_DETA,
			CODIGO_TRANSACCION=@CODIGO_TRANSACCION,
			DESCRIPCION_TRANSACCION=@DESCRIPCION_TRANSACCION
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
			AND CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			--Se borra el correspondiente concilia_movi
			DELETE FROM BAN_CONCILIA_BANCARIA_MOVI 
			WHERE CORR_EMPRESA=@CORR_EMPRESA 
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
			AND CORR_CONCILIACION=@CORR_CONCILIACION 
			AND CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA
			
			SELECT @ANIO_PERIODO=ANIO_PERIODO, @MES_PERIODO=MES_PERIODO,@CORR_CLASE_PARTIDA=CORR_CLASE_PARTIDA,@CORR_PARTIDA=CORR_PARTIDA,@CORR_PARTIDA_DETA=CORR_PARTIDA_DETA 
			FROM BAN_CONCILIA_BANCARIA_DETA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
			AND CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA
			--Se marca la partida contable que ya no esta conciliada
			UPDATE CON_PARTIDA_DETA SET ESTA_CONCILIA=0
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO 
			AND MES_PERIODO=@MES_PERIODO 
			AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA 
			AND CORR_PARTIDA=@CORR_PARTIDA 
			AND CORR_PARTIDA_DETA=@CORR_PARTIDA_DETA 
			
			--Por ultimo se borra el registro
			DELETE FROM BAN_CONCILIA_BANCARIA_DETA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
			AND CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO

