SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_GENE_CON_PERIODO_CIERRE]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@TIPO_PERIODO VARCHAR(3),
	--@ESTADO_PERIDO VARCHAR(3) OUTPUT,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
			
		IF @TIPO_PERIODO='CON' --CONTBILIDAD
		BEGIN
			EXEC PRAL_GENE_CIERRE_CONTA
			@CORR_EMPRESA,
			@ANIO_PERIODO,
			@MES_PERIODO,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS output,
			@SYS_NUMERO_ERROR output,
			@SYS_MENSAJE_ERROR output				
		END ELSE
		IF @TIPO_PERIODO='BAN' --BANCOS
		BEGIN						
			EXEC PRAL_GENE_CIERRE_BANCOS
			@CORR_EMPRESA,
			@ANIO_PERIODO,
			@MES_PERIODO,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS output,
			@SYS_NUMERO_ERROR output,
			@SYS_MENSAJE_ERROR output
		END ELSE
		IF @TIPO_PERIODO='VEN' --VENTAS
		BEGIN
			EXEC PRAL_GENE_CIERRE_VENTAS
			@CORR_EMPRESA,
			@ANIO_PERIODO,
			@MES_PERIODO,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS output,
			@SYS_NUMERO_ERROR output,
			@SYS_MENSAJE_ERROR output
		END ELSE
		IF @TIPO_PERIODO='ACT' --ACTIVO FIJO
		BEGIN
			UPDATE CON_PERIODO_CONTABLE
			SET ESTADO_PERIODO_ACT = 'CE'      
			,FECHA_CIERRE_ACT = GETDATE() 
			WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
		END ELSE
		IF @TIPO_PERIODO='INV' --INVENTARIOS
		BEGIN
			EXEC PRAL_GENE_CIERRE_INVENTARIOS
			@CORR_EMPRESA,
			@ANIO_PERIODO,
			@MES_PERIODO,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS output,
			@SYS_NUMERO_ERROR output,
			@SYS_MENSAJE_ERROR output
		END ELSE
		IF @TIPO_PERIODO='PLA' --PLANILLAS
		BEGIN
			UPDATE CON_PERIODO_CONTABLE
			SET ESTADO_PERIODO_PLA = 'CE'      
			,FECHA_CIERRE_PLA = GETDATE() 
			WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
		END ELSE
		IF @TIPO_PERIODO='COM' --COMPRAS
		BEGIN
			UPDATE CON_PERIODO_CONTABLE
			SET ESTADO_PERIODO_COM = 'CE'      
			,FECHA_CIERRE_COM = GETDATE() 
			WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
		END 
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
