SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_ENVIAR_SOLICITUD]
(
		@CORR_EMPRESA int,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_TIPO_MOVIMIENTO int,
	@CORR_DOCUMENTO int OUTPUT,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output,
	@GENERA_DETALLE BIT = 1
)
AS
	DECLARE @MONTO_CARGO DECIMAL(12,2), @MONTO_ABONO DECIMAL(12,2),@CUENTA_CONTABLE_BANCO VARCHAR(30)
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		DECLARE @CLASE_TIPO_CHEQUE VARCHAR(3), @ESTADO_DOCUMENTO varchar(2), @CORR_CUENTA_BANCO int, @SOLICITADO_POR varchar(30), @FECHA_SOLICITADO date
	
		SELECT @ESTADO_DOCUMENTO=ESTADO_DOCUMENTO, @CORR_CUENTA_BANCO=CORR_CUENTA_BANCO
		FROM BAN_SOLI_CHEQUE 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND ANIO_PERIODO=@ANIO_PERIODO 
		AND MES_PERIODO=@MES_PERIODO 
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO
		
		IF @ESTADO_DOCUMENTO <> 'DI'
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='No se puede enviar esta solicitud.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END						
		
		IF NOT EXISTS(SELECT 1 FROM BAN_SOLI_CHEQUE_DETA
					  WHERE CORR_EMPRESA=@CORR_EMPRESA
					  AND ANIO_PERIODO=@ANIO_PERIODO
					  AND MES_PERIODO=@MES_PERIODO
					  AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
					  AND CORR_DOCUMENTO=@CORR_DOCUMENTO)
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30004,@SYS_MENSAJE_ERROR='El Documento NO tiene detalle. No se puede Solicitar.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END
		
		SELECT @MONTO_CARGO=SUM(A.MONTO_CARGO),
		@MONTO_ABONO=SUM(A.MONTO_ABONO)
		FROM BAN_SOLI_CHEQUE_DETA A
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO
		
		IF @MONTO_CARGO<>@MONTO_ABONO
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Documento NO cuadrada. No se puede Solicitar.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END
							
		SELECT @CUENTA_CONTABLE_BANCO=A.CUENTA_CONTABLE
		FROM BAN_CUENTA_BANCARIA A
		WHERE A.CORR_SUSCRIPCION=@CORR_SUSCRIPCION
		AND A.CORR_CONFI_PAIS=@CORR_CONFI_PAIS
		AND A.CORR_EMPRESA=@CORR_EMPRESA			
		AND A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO	
		
		--IF NOT EXISTS(SELECT 1 FROM BAN_SOLI_CHEQUE_DETA
		--			  WHERE CORR_SUSCRIPCION=@CORR_SUSCRIPCION						  
		--			  AND CORR_CONFI_PAIS=@CORR_CONFI_PAIS
		--			  AND CORR_EMPRESA=@CORR_EMPRESA
		--			  AND ANIO_PERIODO=@ANIO_PERIODO
		--			  AND MES_PERIODO=@MES_PERIODO
		--			  AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
		--			  AND CORR_DOCUMENTO=@CORR_DOCUMENTO
		--			  AND CUENTA_CONTABLE=@CUENTA_CONTABLE_BANCO)
		--BEGIN
		--	SELECT @SYS_NUMERO_ERROR=30005,@SYS_MENSAJE_ERROR='El Documento NO contiene la cuenta del banco. No se puede Solicitar.',@SYS_FILAS_AFECTADAS=0
		--	GOTO FINA
		--END
		
		SELECT @SOLICITADO_POR=@SYS_LOGIN_USUARIO, @FECHA_SOLICITADO=GETDATE()
		
		UPDATE BAN_SOLI_CHEQUE SET
		ESTADO_DOCUMENTO='SO', FECHA_SOLICITADO=@FECHA_SOLICITADO, SOLICITADO_POR=@SOLICITADO_POR 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND ANIO_PERIODO=@ANIO_PERIODO 
		AND MES_PERIODO=@MES_PERIODO 
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO 
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()
		
		-- bitacora omitida
FINA:
END
GO
