SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================================================
-- Procedimiento: dbo.PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO
-- Qué hace: entrega datos para PDF Formato corto del Descriptor de puesto.
-- Cómo:
--   1) Result set 1: encabezado (V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_IMPR).
--   2) Result set 2: encabezado/logos desde GEN_EMPRESA (GEN_PARAMETRO en Crystal).
--   3) Result set 3: funciones agregadas (V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_FUNCIONES_IMPR).
--   4) Result set 4: indicadores (V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_KPI_IMPR).
--   5) Result set 5: responsabilidades (V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_RESPONSABILIDAD_CARGO_IMPR;
--      vista filtra APLICA_DESCRIPTOR CORTO/AMBOS; SP filtra por descriptor).
--   6) Result set 6: inducciones (V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_INDUCCION_IMPR).
--   7) Result set 7: perfil del puesto (V_SC_PERFIL_PUESTO_FORMATO_CORTO_IMPR).
--   8) Result set 8: educación del perfil (V_SC_PERFIL_PUESTO_EDUCACION_FORMATO_CORTO_IMPR).
--   9) Result set 9: experiencia del perfil (V_SC_PERFIL_PUESTO_EXPERIENCIA_FORMATO_CORTO_IMPR).
--  10) Result set 10: competencias técnicas (V_SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS_FORMATO_CORTO_IMPR).
-- Alcance: solo Formato corto. El Formato extenso tiene su propio SP y vistas _IMPR.
-- Uso API: SC_DESCRIPTOR_PUESTO/getPDFFormatoCorto → SGUEES-RPT SelectionHiring.
-- =============================================================================
CREATE OR ALTER PROCEDURE [dbo].[PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO]
(
	@CORR_EMPRESA INT,
	@CORR_DESCRIPTOR_PUESTO INT
)
AS
BEGIN
	SET NOCOUNT ON;

	-- Result set 1: encabezado del descriptor (1 fila).
	SELECT
		A.CORR_EMPRESA,
		A.CORR_DESCRIPTOR_PUESTO,
		A.CODIGO_DESCRIPTOR_PUESTO,
		A.FECHA_EMISION,
		A.FECHA_REVISION,
		A.OBJETIVO_PUESTO,
		A.NUM_PERSONAL_CARGO,
		A.CORR_PUESTO,
		A.NOMBRE_PUESTO,
		A.CORR_UNIDAD,
		A.NOMBRE_UNIDAD,
		A.CORR_PUESTO_REPORTA,
		A.NOMBRE_EMPLEADO_REPORTA,
		A.CORR_IMPACTO_ECONOMICO,
		A.DESCRIPCION_IMPACTO_ECONOMICO,
		A.RESPONSABLE,
		A.FORMATO,
		A.VERSION,
		A.CORR_ESTADO,
		A.NOMBRE_ESTADO,
		A.USUARIO_CREA,
		A.ESTACION_CREA,
		A.FECHA_CREA,
		A.USUARIO_ACTU,
		A.ESTACION_ACTU,
		A.FECHA_ACTU
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_IMPR A
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA
	  AND A.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO;

	-- Result set 2: logos (GEN_PARAMETRO en Crystal).
	SELECT
		A.CORR_EMPRESA,
		A.NOMBRE_EMPRESA,
		CAST('' AS VARCHAR(100)) AS PERIODO,
		A.LOGO_1 AS LOGO1,
		A.LOGO_2 AS LOGO2,
		CAST(N'Descriptor de Puesto - Formato corto' AS VARCHAR(150)) AS TITULO_REPORTE,
		CAST('' AS VARCHAR(100)) AS NOMBRE_SISTEMA,
		GETDATE() AS FECHA_IMPRESION
	FROM dbo.GEN_EMPRESA A
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA;

	-- Result set 3: funciones CLAVE y SECUNDARIA agregadas (1 fila).
	SELECT
		F.CORR_EMPRESA,
		F.CORR_DESCRIPTOR_PUESTO,
		F.LISTA_FUNCIONES_CLAVE,
		F.LISTA_FUNCIONES_SECUNDARIA
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_FUNCIONES_IMPR F
	WHERE F.CORR_EMPRESA = @CORR_EMPRESA
	  AND F.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO;

	-- Result set 4: indicadores de desempeño (1 fila por KPI).
	SELECT
		K.CORR_EMPRESA,
		K.CORR_DESCRIPTOR_PUESTO,
		K.CORR_KPI_FUNCION,
		K.NOMBRE_INDICADOR,
		K.META,
		K.CORR_FRECUENCIA,
		K.NOMBRE_FRECUENCIA
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_KPI_IMPR K
	WHERE K.CORR_EMPRESA = @CORR_EMPRESA
	  AND K.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY K.CORR_KPI_FUNCION;

	-- Result set 5: responsabilidades del cargo (subinforme; vista ya filtra CORTO/AMBOS).
	SELECT
		R.CORR_EMPRESA,
		R.CORR_DESCRIPTOR_PUESTO,
		R.CORR_RESPONSABILIDAD,
		R.NOMBRE_RESPONSABILIDAD,
		R.INFORMACION,
		R.APLICA_DESCRIPTOR
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_RESPONSABILIDAD_CARGO_IMPR R
	WHERE R.CORR_EMPRESA = @CORR_EMPRESA
	  AND R.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY R.CORR_RESPONSABILIDAD;

	-- Result set 6: inducciones del descriptor (1 fila por inducción).
	SELECT
		I.CORR_EMPRESA,
		I.CORR_DESCRIPTOR_PUESTO,
		I.CORR_INDUCCION,
		I.NOMBRE_INDUCCION,
		I.TIEMPO_INDUCCION
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_INDUCCION_IMPR I
	WHERE I.CORR_EMPRESA = @CORR_EMPRESA
	  AND I.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY I.CORR_INDUCCION;

	-- Result set 7: perfil del puesto (encabezado del apartado; 0 o 1 fila típica).
	SELECT
		P.CORR_EMPRESA,
		P.CORR_DESCRIPTOR_PUESTO,
		P.CORR_PERFIL_PUESTO,
		P.EDAD_MINIMA,
		P.EDAD_MAXIMA,
		P.SEXO,
		P.ESTADO_FAMILIAR,
		P.LICENCIA,
		P.CORR_DISPONIBILIDAD_HORARIO,
		P.NOMBRE_DISPONIBILIDAD_HORARIO,
		P.CORR_TIPO_MODALIDAD,
		P.NOMBRE_MODALIDAD,
		P.OTROS
	FROM dbo.V_SC_PERFIL_PUESTO_FORMATO_CORTO_IMPR P
	WHERE P.CORR_EMPRESA = @CORR_EMPRESA
	  AND P.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY P.CORR_PERFIL_PUESTO;

	-- Result set 8: educación del perfil de puesto (1 fila por requisito).
	SELECT
		E.CORR_EMPRESA,
		E.CORR_DESCRIPTOR_PUESTO,
		E.CORR_PERFIL_PUESTO,
		E.CORR_EDUCACION,
		E.REQUISITO,
		E.ESPECIFICACIONES,
		E.TIPO_REQUERIDO
	FROM dbo.V_SC_PERFIL_PUESTO_EDUCACION_FORMATO_CORTO_IMPR E
	WHERE E.CORR_EMPRESA = @CORR_EMPRESA
	  AND E.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY E.CORR_EDUCACION;

	-- Result set 9: experiencia del perfil de puesto (1 fila por requisito).
	SELECT
		X.CORR_EMPRESA,
		X.CORR_DESCRIPTOR_PUESTO,
		X.CORR_PERFIL_PUESTO,
		X.CORR_EXPERIENCIA,
		X.REQUISITO,
		X.TIPO_REQUERIDO
	FROM dbo.V_SC_PERFIL_PUESTO_EXPERIENCIA_FORMATO_CORTO_IMPR X
	WHERE X.CORR_EMPRESA = @CORR_EMPRESA
	  AND X.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY X.CORR_EXPERIENCIA;

	-- Result set 10: competencias técnicas del perfil (1 fila por competencia).
	SELECT
		CT.CORR_EMPRESA,
		CT.CORR_DESCRIPTOR_PUESTO,
		CT.CORR_PERFIL_PUESTO,
		CT.CORR_COMPETENCIAS_TECNICAS,
		CT.CODIGO_COMPETENCIAS_TECNICAS,
		CT.NOMBRE_COMPETENCIAS_TECNICAS,
		CT.DESCRIPCION,
		CT.NIVEL_DOMINIO
	FROM dbo.V_SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS_FORMATO_CORTO_IMPR CT
	WHERE CT.CORR_EMPRESA = @CORR_EMPRESA
	  AND CT.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY CT.CORR_COMPETENCIAS_TECNICAS;
END
GO
