SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_DATA_SEG_USUARIO_FOTO]
(
	@TIPO_CONSULTA int,
	@LOGIN_SISTEMA varchar(30)=NULL,
	@CORR_EMPRESA int=NULL,
	@CORR_FOTO int=NULL,
	@CLASE_FOTO varchar(2)=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		SELECT * FROM V_SEG_USUARIO_FOTO
		WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA		
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN		
		SELECT * FROM V_SEG_USUARIO_FOTO
		WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA		
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN		
			SELECT * FROM V_SEG_USUARIO_FOTO
			WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA
			AND CLASE_FOTO=@CLASE_FOTO
		END
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT CLASE_FOTO FROM V_SEG_USUARIO_FOTO
			WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA
			AND CLASE_FOTO=@CLASE_FOTO
		END
	END

END
GO
