
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_CON_GASTOS]
( 
  @CORR_EMPRESA INT,
  @FECHA_INICIAL DATE,
  @FECHA_FINAL DATE,
  @CUENTA_DEPARTAMENTO VARCHAR(30)='',
  @CONSOLIDADO BIT,
  @CORR_CONFI_REPORTE INT=NULL,
  @PARTIDA_CIERRE BIT=0,
  @PARTIDA_LIQUIDACION BIT=0
)
AS
BEGIN
    
    SET NOCOUNT ON  
    
    
    DECLARE @NOMBRE_CUENTA_DEPARTAMENTO VARCHAR(150)
    SELECT @NOMBRE_CUENTA_DEPARTAMENTO=NOMBRE_CUENTA
    FROM CON_CATALOGO_CUENTA
    WHERE CORR_EMPRESA=@CORR_EMPRESA
    AND CUENTA_CONTABLE=@CUENTA_DEPARTAMENTO
    SELECT @NOMBRE_CUENTA_DEPARTAMENTO=ISNULL(@NOMBRE_CUENTA_DEPARTAMENTO,'')
	
	DECLARE @DATA  TABLE( 
		CORR_EMPRESA INT,
		CUENTA_MAYOR_2 VARCHAR(100),
	    CUENTA_MAYOR_3 VARCHAR(100),
	    CUENTA_MAYOR_4 VARCHAR(100),
	    CUENTA_DEPARTAMENTO VARCHAR(200),
	    CUENTA_CONTABLE VARCHAR(200),
	    CUENTA_CONTABLE_RANGO VARCHAR(50),
	    ANIO_PERIODO INT,
        ENERO DECIMAL(18,2),
        FEBRERO DECIMAL(18,2),
        MARZO DECIMAL(18,2),
        ABRIL DECIMAL(18,2),
        MAYO DECIMAL(18,2),
        JUINIO DECIMAL(18,2),
        JULIO DECIMAL(18,2),
        AGOSTO DECIMAL(18,2),
        SEPTIEMBRE DECIMAL(18,2),
        OCTUBRE DECIMAL(18,2),
        NOVIEMBRE DECIMAL(18,2),
        DICIEMBRE DECIMAL(18,2),
	    TOTAL DECIMAL(18,2)) 
	    
	;WITH CTE_CUENTAS AS (
		SELECT A.CORR_EMPRESA
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE E.CUENTA_CONTABLE+' '+E.NOMBRE_CUENTA END CUENTA_MAYOR_2
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE F.CUENTA_CONTABLE+' '+F.NOMBRE_CUENTA END CUENTA_MAYOR_3
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE G.CUENTA_CONTABLE+' '+G.NOMBRE_CUENTA END CUENTA_MAYOR_4
		,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO+' '+@NOMBRE_CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE+' '+D.NOMBRE_CUENTA END CUENTA_DEPARTAMENTO
		--, D.CUENTA_CONTABLE+' '+D.NOMBRE_CUENTA  CUENTA_DEPARTAMENTO
		,REPLACE(B.CUENTA_CONTABLE, D.CUENTA_CONTABLE,'')+' '+C.NOMBRE_CUENTA CUENTA_CONTABLE
		,B.CUENTA_CONTABLE CUENTA_CONTABLE_RANGO
		--,REPLACE(B.CUENTA_CONTABLE,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE END,'')+' '+C.NOMBRE_CUENTA CUENTA_CONTABLE
	
		,A.ANIO_PERIODO
		,SUM(CASE WHEN A.MES_PERIODO=1 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) ENERO
		,SUM(CASE WHEN A.MES_PERIODO=2 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) FEBRERO
		,SUM(CASE WHEN A.MES_PERIODO=3 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) MARZO
		,SUM(CASE WHEN A.MES_PERIODO=4 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) ABRIL
		,SUM(CASE WHEN A.MES_PERIODO=5 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) MAYO
		,SUM(CASE WHEN A.MES_PERIODO=6 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) JUINIO
		,SUM(CASE WHEN A.MES_PERIODO=7 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) JULIO
		,SUM(CASE WHEN A.MES_PERIODO=8 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) AGOSTO
		,SUM(CASE WHEN A.MES_PERIODO=9 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) SEPTIEMBRE
		,SUM(CASE WHEN A.MES_PERIODO=10 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) OCTUBRE
		,SUM(CASE WHEN A.MES_PERIODO=11 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) NOVIEMBRE
		,SUM(CASE WHEN A.MES_PERIODO=12 THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) DICIEMBRE
		,SUM(B.MONTO_CARGO-B.MONTO_ABONO) TOTAL
		FROM CON_PARTIDA A
		INNER JOIN CON_PARTIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
		INNER JOIN CON_CATALOGO_CUENTA C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CUENTA_CONTABLE=C.CUENTA_CONTABLE
		INNER JOIN CON_CATALOGO_CUENTA D ON C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CUENTA_MAYOR=D.CUENTA_CONTABLE
		LEFT OUTER JOIN CON_CATALOGO_CUENTA E ON D.CORR_EMPRESA=E.CORR_EMPRESA AND D.CUENTA_MAYOR=E.CUENTA_CONTABLE
		LEFT OUTER JOIN CON_CATALOGO_CUENTA F ON E.CORR_EMPRESA=F.CORR_EMPRESA AND E.CUENTA_MAYOR=F.CUENTA_CONTABLE
		LEFT OUTER JOIN CON_CATALOGO_CUENTA G ON F.CORR_EMPRESA=G.CORR_EMPRESA AND F.CUENTA_MAYOR=G.CUENTA_CONTABLE
		WHERE A.ESTADO_PARTIDA='AP'
		--AND C.CLASE_RUBRO='GA'
		AND A.FECHA_PARTIDA>=@FECHA_INICIAL
		AND A.FECHA_PARTIDA<=@FECHA_FINAL
		AND (B.CUENTA_CONTABLE LIKE @CUENTA_DEPARTAMENTO+'%' OR ISNULL(@CUENTA_DEPARTAMENTO,'')='')	
		--AND (C.CUENTA_CONTABLE>=H.CUENTA_CONTABLE_INI OR ISNULL(H.CUENTA_CONTABLE_INI,'')='')
		--AND (C.CUENTA_CONTABLE<=H.CUENTA_CONTABLE_FINA OR ISNULL(H.CUENTA_CONTABLE_FINA,'')='')
		AND ((CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='CIE' THEN 1 ELSE 0 END)=1 AND @PARTIDA_CIERRE=1) OR A.CLASE_PARTIDA<>'CIE')
        AND ((CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='LIQ' THEN 1 ELSE 0 END)=1 AND @PARTIDA_LIQUIDACION=1) OR A.CLASE_PARTIDA<>'LIQ')
		GROUP BY A.CORR_EMPRESA
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE E.CUENTA_CONTABLE+' '+E.NOMBRE_CUENTA END
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE F.CUENTA_CONTABLE+' '+F.NOMBRE_CUENTA END
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE G.CUENTA_CONTABLE+' '+G.NOMBRE_CUENTA END
		,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO+' '+@NOMBRE_CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE+' '+D.NOMBRE_CUENTA END
		--,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE D.NOMBRE_CUENTA END
		,REPLACE(B.CUENTA_CONTABLE,D.CUENTA_CONTABLE,'')+' '+C.NOMBRE_CUENTA
		--,REPLACE(B.CUENTA_CONTABLE,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE END,'')+' '+C.NOMBRE_CUENTA
		--,C.NOMBRE_CUENTA
		,A.ANIO_PERIODO
		,B.CUENTA_CONTABLE
		
		--,A.MES_PERIODO
		--ORDER BY REPLACE(B.CUENTA_CONTABLE,D.CUENTA_CONTABLE,'')+' '+C.NOMBRE_CUENTA
		--REPLACE(B.CUENTA_CONTABLE,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE END,'')+' '+C.NOMBRE_CUENTA
    )
   
    INSERT INTO @DATA
	SELECT C.* FROM CTE_CUENTAS C
	LEFT OUTER JOIN CON_CONFI_REPORTE_DETA H ON C.CORR_EMPRESA=H.CORR_EMPRESA 
	AND H.CORR_CONFI_REPORTE=@CORR_CONFI_REPORTE
	WHERE (C.CUENTA_CONTABLE_RANGO>=H.CUENTA_CONTABLE_INI OR ISNULL(H.CUENTA_CONTABLE_INI,'')='')
	AND (C.CUENTA_CONTABLE_RANGO<=H.CUENTA_CONTABLE_FINA OR ISNULL(H.CUENTA_CONTABLE_FINA,'')='')
	ORDER BY C.CUENTA_CONTABLE

    IF @CONSOLIDADO=1
    BEGIN
	SELECT  CORR_EMPRESA
        ,CUENTA_MAYOR_2
        ,CUENTA_MAYOR_3
        ,CUENTA_MAYOR_4		
	    ,CUENTA_DEPARTAMENTO
	    ,CUENTA_CONTABLE
	    ,SUM(ENERO) ENERO
	    ,SUM(FEBRERO) FEBRERO
	    ,SUM(MARZO) MARZO
	    ,SUM(ABRIL) ABRIL
	    ,SUM(MAYO) MAYO
	    ,SUM(JUINIO) JUINIO
	    ,SUM(JULIO) JULIO
	    ,SUM(AGOSTO) AGOSTO
	    ,SUM(SEPTIEMBRE) SEPTIEMBRE
	    ,SUM(OCTUBRE) OCTUBRE
	    ,SUM(NOVIEMBRE) NOVIEMBRE
	    ,SUM(DICIEMBRE) DICIEMBRE
	    ,ANIO_PERIODO
	    ,SUM(TOTAL) TOTAL
	    FROM @DATA
	    GROUP BY  CORR_EMPRESA
		,CUENTA_MAYOR_2
        ,CUENTA_MAYOR_3
        ,CUENTA_MAYOR_4	
	    ,CUENTA_DEPARTAMENTO
	    ,CUENTA_CONTABLE
	    ,ANIO_PERIODO
	   -- ,TOTAL
	END ELSE
	BEGIN
	    SELECT * FROM @DATA
	END
	
	SELECT A.CORR_EMPRESA
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO
