SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_BAN_CONCILIA_BANCARIA_DETA]
(
	@TIPO_CONSULTA int,
	@CORR_EMPRESA int=NULL,
	@CORR_CUENTA_BANCO int=NULL,
	@CORR_CONCILIACION int=NULL,
	@CORR_CONCILIACION_DETA int=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		SELECT * FROM V_BAN_CONCILIA_BANCARIA_DETA
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
		AND CORR_CONCILIACION=@CORR_CONCILIACION
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		SELECT * FROM V_BAN_CONCILIA_BANCARIA_DETA
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
		AND CORR_CONCILIACION=@CORR_CONCILIACION
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_BAN_CONCILIA_BANCARIA_DETA
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
		AND CORR_CONCILIACION=@CORR_CONCILIACION
		AND CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT CORR_EMPRESA FROM V_BAN_CONCILIA_BANCARIA_DETA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
			AND CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA
		END
	END

END
GO

