SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_CUADRO_COMPARATIVO_AUTORIZAR]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO INT,
	@CORR_CUADRO_COMPARATIVO int OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY

		IF EXISTS(SELECT 1 FROM COM_CUADRO_COMPARATIVO A 
				  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
				  AND A.ANIO_PERIODO=@ANIO_PERIODO
				  AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
				  AND A.ESTADO_CUADRO_COMPARATIVO<>'SO'
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='El cuadro comparativo debe estar en solicitado. no se permite autorizar cuadro comparativo.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF NOT EXISTS(SELECT 1 FROM COM_CUADRO_COMPARATIVO_DETA A 
				  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
				  AND A.ANIO_PERIODO=@ANIO_PERIODO
				  AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='No existen item en el detalle del cuadro comparativo. no se permite autorizar cuadro comparativo.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF NOT EXISTS(SELECT 1 FROM COM_CUADRO_COMPARATIVO_DETA A 
					  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					  AND A.ANIO_PERIODO=@ANIO_PERIODO
					  AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
					  AND ISNULL(A.SELECCION,0)=1
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='No existen item seleccionados en el detalle del cuadro comparativo. no se permite autorizar cuadro comparativo.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		UPDATE COM_CUADRO_COMPARATIVO_AUTORIZACIONES SET 
		FECHA_AUTORIZACION=GETDATE(),
		ESTADO_AUTORIZACION='AP'
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND	LOGIN_SISTEMA=@SYS_LOGIN_USUARIO
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO

		IF NOT EXISTS(SELECT 1 FROM COM_CUADRO_COMPARATIVO_AUTORIZACIONES
					 WHERE CORR_EMPRESA=@CORR_EMPRESA
					 AND ANIO_PERIODO=@ANIO_PERIODO
					 AND CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
					 AND PERMITE_MODIFICAR=1
					 AND ESTADO_AUTORIZACION='SO')
		 AND NOT EXISTS(SELECT 1 FROM COM_CUADRO_COMPARATIVO_ORDEN_COMPRA A
					WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					AND A.ANIO_PERIODO=@ANIO_PERIODO
					AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO)
		BEGIN

			EXECUTE PRAL_GENE_COM_ORDEN_COMPRA
			@CORR_EMPRESA,
			@ANIO_PERIODO,
			@CORR_CUADRO_COMPARATIVO OUTPUT,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS OUTPUT,
			@SYS_NUMERO_ERROR OUTPUT,
			@SYS_MENSAJE_ERROR OUTPUT

		END

		IF NOT EXISTS(SELECT 1 FROM COM_CUADRO_COMPARATIVO_AUTORIZACIONES
					 WHERE CORR_EMPRESA=@CORR_EMPRESA
					 AND ANIO_PERIODO=@ANIO_PERIODO
					 AND CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
					 AND ESTADO_AUTORIZACION='SO')
		BEGIN

			EXECUTE PRAL_MTTO_COM_CUADRO_COMPARATIVO_APLICAR
			@CORR_EMPRESA,
			@ANIO_PERIODO,
			@CORR_CUADRO_COMPARATIVO OUTPUT,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS OUTPUT,
			@SYS_NUMERO_ERROR OUTPUT,
			@SYS_MENSAJE_ERROR OUTPUT            

		END

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DATETIME,
		@CORR_SUSCRIPCION INT=3,
		@CORR_CONFI_PAIS INT=1

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		--EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
