SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_IMPR_CON_CATALOGO_PRESUPUESTO]
( 
  @CORR_EMPRESA INT,
  @ANIO_PERIODO INT,
  @CUENTA_DEPARTAMENTO VARCHAR(30)='',
  @CONSOLIDADO BIT,
  @CORR_CONFI_REPORTE INT=NULL,
  @PARTIDA_CIERRE BIT=0,
  @PARTIDA_LIQUIDACION BIT=0
)
AS
BEGIN
    
    SET NOCOUNT ON  
    
    
    DECLARE @NOMBRE_CUENTA_DEPARTAMENTO VARCHAR(150)
    SELECT @NOMBRE_CUENTA_DEPARTAMENTO=NOMBRE_CUENTA
    FROM CON_CATALOGO_CUENTA
    WHERE CORR_EMPRESA=@CORR_EMPRESA
    AND CUENTA_CONTABLE=@CUENTA_DEPARTAMENTO
    SELECT @NOMBRE_CUENTA_DEPARTAMENTO=ISNULL(@NOMBRE_CUENTA_DEPARTAMENTO,'')
	
	DECLARE @DATA  TABLE( 
		CORR_EMPRESA INT,
		CUENTA_MAYOR_2 VARCHAR(100),
	    CUENTA_MAYOR_3 VARCHAR(100),
	    CUENTA_MAYOR_4 VARCHAR(100),
	    CUENTA_DEPARTAMENTO VARCHAR(200),
	    CUENTA_CONTABLE VARCHAR(200),
	    CUENTA_CONTABLE_RANGO VARCHAR(50),
	    ANIO_PERIODO INT,
        ENERO DECIMAL(18,2),
        FEBRERO DECIMAL(18,2),
        MARZO DECIMAL(18,2),
        ABRIL DECIMAL(18,2),
        MAYO DECIMAL(18,2),
        JUINIO DECIMAL(18,2),
        JULIO DECIMAL(18,2),
        AGOSTO DECIMAL(18,2),
        SEPTIEMBRE DECIMAL(18,2),
        OCTUBRE DECIMAL(18,2),
        NOVIEMBRE DECIMAL(18,2),
        DICIEMBRE DECIMAL(18,2),
	    TOTAL DECIMAL(18,2)) 
	    
	;WITH CTE_CUENTAS AS (
		SELECT A.CORR_EMPRESA
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE E.CUENTA_CONTABLE+' '+E.NOMBRE_CUENTA END CUENTA_MAYOR_2
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE F.CUENTA_CONTABLE+' '+F.NOMBRE_CUENTA END CUENTA_MAYOR_3
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE G.CUENTA_CONTABLE+' '+G.NOMBRE_CUENTA END CUENTA_MAYOR_4
		,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO+' '+@NOMBRE_CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE+' '+D.NOMBRE_CUENTA END CUENTA_DEPARTAMENTO
		--, D.CUENTA_CONTABLE+' '+D.NOMBRE_CUENTA  CUENTA_DEPARTAMENTO
		,REPLACE(A.CUENTA_CONTABLE, D.CUENTA_CONTABLE,'')+' '+C.NOMBRE_CUENTA CUENTA_CONTABLE
		,A.CUENTA_CONTABLE CUENTA_CONTABLE_RANGO
		--,REPLACE(B.CUENTA_CONTABLE,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE END,'')+' '+C.NOMBRE_CUENTA CUENTA_CONTABLE
		,A.ANIO_PERIODO
		,A.MONTO_PRESUPUESTO_1 ENERO
		,A.MONTO_PRESUPUESTO_2 FEBRERO
		,A.MONTO_PRESUPUESTO_3 MARZO
		,A.MONTO_PRESUPUESTO_4 ABRIL
		,A.MONTO_PRESUPUESTO_5 MAYO
		,A.MONTO_PRESUPUESTO_6 JUINIO
		,A.MONTO_PRESUPUESTO_7 JULIO
		,A.MONTO_PRESUPUESTO_8 AGOSTO
		,A.MONTO_PRESUPUESTO_9 SEPTIEMBRE
		,A.MONTO_PRESUPUESTO_10 OCTUBRE
		,A.MONTO_PRESUPUESTO_11 NOVIEMBRE
		,A.MONTO_PRESUPUESTO_12 DICIEMBRE
		,A.MONTO_PRESUPUESTO_1 +A.MONTO_PRESUPUESTO_2 +A.MONTO_PRESUPUESTO_3 +A.MONTO_PRESUPUESTO_4 +A.MONTO_PRESUPUESTO_5 +A.MONTO_PRESUPUESTO_6 +A.MONTO_PRESUPUESTO_7 +A.MONTO_PRESUPUESTO_8 +A.MONTO_PRESUPUESTO_9 +A.MONTO_PRESUPUESTO_10 +A.MONTO_PRESUPUESTO_11 +A.MONTO_PRESUPUESTO_12 TOTAL
		FROM CON_CATALOGO_PRESUPUESTO A
		INNER JOIN CON_CATALOGO_CUENTA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_CONTABLE
		INNER JOIN CON_CATALOGO_CUENTA D ON C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CUENTA_MAYOR=D.CUENTA_CONTABLE
		LEFT OUTER JOIN CON_CATALOGO_CUENTA E ON D.CORR_EMPRESA=E.CORR_EMPRESA AND D.CUENTA_MAYOR=E.CUENTA_CONTABLE
		LEFT OUTER JOIN CON_CATALOGO_CUENTA F ON E.CORR_EMPRESA=F.CORR_EMPRESA AND E.CUENTA_MAYOR=F.CUENTA_CONTABLE
		LEFT OUTER JOIN CON_CATALOGO_CUENTA G ON F.CORR_EMPRESA=G.CORR_EMPRESA AND F.CUENTA_MAYOR=G.CUENTA_CONTABLE
		WHERE A.ANIO_PERIODO=@ANIO_PERIODO
		--A.ESTADO_PARTIDA='AP'
		----AND C.CLASE_RUBRO='GA'
		--AND A.FECHA_PARTIDA>=@FECHA_INICIAL
		--AND A.FECHA_PARTIDA<=@FECHA_FINAL
		AND (A.CUENTA_CONTABLE LIKE @CUENTA_DEPARTAMENTO+'%' OR ISNULL(@CUENTA_DEPARTAMENTO,'')='')	
		--AND (C.CUENTA_CONTABLE>=H.CUENTA_CONTABLE_INI OR ISNULL(H.CUENTA_CONTABLE_INI,'')='')
		--AND (C.CUENTA_CONTABLE<=H.CUENTA_CONTABLE_FINA OR ISNULL(H.CUENTA_CONTABLE_FINA,'')='')
		--AND ((CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='CIE' THEN 1 ELSE 0 END)=1 AND @PARTIDA_CIERRE=1) OR A.CLASE_PARTIDA<>'CIE')
  --      AND ((CONVERT(BIT,CASE WHEN ISNULL(A.CLASE_PARTIDA,'NOR')='LIQ' THEN 1 ELSE 0 END)=1 AND @PARTIDA_LIQUIDACION=1) OR A.CLASE_PARTIDA<>'LIQ')
		GROUP BY CASE
                 WHEN @CONSOLIDADO = 1 THEN
                 ''
                 ELSE
                 E.CUENTA_CONTABLE + ' ' + E.NOMBRE_CUENTA
                 END,
                 CASE
                 WHEN @CONSOLIDADO = 1 THEN
                 ''
                 ELSE
                 F.CUENTA_CONTABLE + ' ' + F.NOMBRE_CUENTA
                 END,
                 CASE
                 WHEN @CONSOLIDADO = 1 THEN
                 ''
                 ELSE
                 G.CUENTA_CONTABLE + ' ' + G.NOMBRE_CUENTA
                 END,
                 CASE
                 WHEN @CONSOLIDADO = 1 THEN
                 @CUENTA_DEPARTAMENTO + ' ' + @NOMBRE_CUENTA_DEPARTAMENTO
                 ELSE
                 D.CUENTA_CONTABLE + ' ' + D.NOMBRE_CUENTA
                 END,
                 REPLACE(A.CUENTA_CONTABLE, D.CUENTA_CONTABLE, '') + ' ' + C.NOMBRE_CUENTA,
                 A.CORR_EMPRESA,
                 A.CUENTA_CONTABLE,
                 A.ANIO_PERIODO,
                 A.MONTO_PRESUPUESTO_1,
                 A.MONTO_PRESUPUESTO_2,
                 A.MONTO_PRESUPUESTO_3,
                 A.MONTO_PRESUPUESTO_4,
                 A.MONTO_PRESUPUESTO_5,
                 A.MONTO_PRESUPUESTO_6,
                 A.MONTO_PRESUPUESTO_7,
                 A.MONTO_PRESUPUESTO_8,
                 A.MONTO_PRESUPUESTO_9,
                 A.MONTO_PRESUPUESTO_10,
                 A.MONTO_PRESUPUESTO_11,
                 A.MONTO_PRESUPUESTO_12
		
		--,A.MES_PERIODO
		--ORDER BY REPLACE(B.CUENTA_CONTABLE,D.CUENTA_CONTABLE,'')+' '+C.NOMBRE_CUENTA
		--REPLACE(B.CUENTA_CONTABLE,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE END,'')+' '+C.NOMBRE_CUENTA
    )
   
    INSERT INTO @DATA
	SELECT C.* FROM CTE_CUENTAS C
	LEFT OUTER JOIN CON_CONFI_REPORTE_DETA H ON C.CORR_EMPRESA=H.CORR_EMPRESA 
	AND H.CORR_CONFI_REPORTE=@CORR_CONFI_REPORTE
	WHERE (C.CUENTA_CONTABLE_RANGO>=H.CUENTA_CONTABLE_INI OR ISNULL(H.CUENTA_CONTABLE_INI,'')='')
	AND (C.CUENTA_CONTABLE_RANGO<=H.CUENTA_CONTABLE_FINA OR ISNULL(H.CUENTA_CONTABLE_FINA,'')='')
	ORDER BY C.CUENTA_CONTABLE

    IF @CONSOLIDADO=1
    BEGIN
	SELECT  CORR_EMPRESA
        ,CUENTA_MAYOR_2
        ,CUENTA_MAYOR_3
        ,CUENTA_MAYOR_4		
	    ,CUENTA_DEPARTAMENTO
	    ,CUENTA_CONTABLE
	    ,SUM(ENERO) ENERO
	    ,SUM(FEBRERO) FEBRERO
	    ,SUM(MARZO) MARZO
	    ,SUM(ABRIL) ABRIL
	    ,SUM(MAYO) MAYO
	    ,SUM(JUINIO) JUINIO
	    ,SUM(JULIO) JULIO
	    ,SUM(AGOSTO) AGOSTO
	    ,SUM(SEPTIEMBRE) SEPTIEMBRE
	    ,SUM(OCTUBRE) OCTUBRE
	    ,SUM(NOVIEMBRE) NOVIEMBRE
	    ,SUM(DICIEMBRE) DICIEMBRE
	    ,ANIO_PERIODO
	    ,SUM(ENERO)+SUM(FEBRERO)+SUM(MARZO)+SUM(ABRIL)+SUM(MAYO)+SUM(JUINIO)+SUM(JULIO)+SUM(AGOSTO)+SUM(SEPTIEMBRE)+SUM(OCTUBRE)+SUM(NOVIEMBRE)+SUM(DICIEMBRE) TOTAL
	    FROM @DATA
	    GROUP BY  CORR_EMPRESA
		,CUENTA_MAYOR_2
        ,CUENTA_MAYOR_3
        ,CUENTA_MAYOR_4	
	    ,CUENTA_DEPARTAMENTO
	    ,CUENTA_CONTABLE
	    ,ANIO_PERIODO
	   -- ,TOTAL
	END ELSE
	BEGIN
	    SELECT * FROM @DATA
	END
	
	SELECT A.CORR_EMPRESA
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO
