SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_CON_SALDO_INICIAL]
(
 @CORR_EMPRESA INT,
 @FECHA_CONSULTA Date,
 @OPCION_CONSULTA INT=0,
 @MAYORIZA INT=0,
 @CUENTA_CONTABLE_INICIAL varchar(30)=NULL,
 @CUENTA_CONTABLE_FINAL varchar(30)=NULL,
 @APLICA_DEBE_HABE INT=1,
 @PARTIDA_CIERRE BIT=0,
 @PARTIDA_LIQUIDACION BIT=0,
 @NIVEL SMALLINT=3,
 @CORR_CONFI_REPORTE INT=NULL
)
AS
DECLARE
    @ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@ANIO_PERIODO_ANTE INT,
	@MES_PERIODO_ANTE INT,
	@FECHA_INICIAL DATE,
	@CUENTA_CONTABLE VARCHAR(30),
	@CUENTA_MAYOR varchar(30),
	@SALDO_INICIAL DECIMAL(18,2),
	@CARGO_PERIODO DECIMAL(18,2),
	@ABONO_PERIODO DECIMAL(18,2),
	@CARGO_PERIODO_MES DECIMAL(18,2),
	@ABONO_PERIODO_MES DECIMAL(18,2),
	@NIVEL_MAX SMALLINT,
	@EXISTE_PARTIDA_INI INT
	
	DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),
		CUENTA_MAYOR varchar(30),
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(18,2),
		CARGO_PERIODO DECIMAL(18,2),
		ABONO_PERIODO DECIMAL(18,2),
		CARGO_PERIODO_MES DECIMAL(18,2),
		ABONO_PERIODO_MES DECIMAL(18,2),
		SALDO_FINAL	DECIMAL(18,2),
		EXISTE_PARTIDA_INI INT,

		PRIMARY KEY (
			 CORR_EMPRESA, CUENTA_CONTABLE
		)
	)
	
	DECLARE @SALDO_MOV TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),		
		CARGO_PERIODO DECIMAL(18,2),
		ABONO_PERIODO DECIMAL(18,2),

		PRIMARY KEY (
			 CORR_EMPRESA, CUENTA_CONTABLE
		)
	)
	
	DECLARE @CARGO_ABONO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),
		SALDO_INICIAL DECIMAL(18,2),			
		CARGO_PERIODO DECIMAL(18,2),
		ABONO_PERIODO DECIMAL(18,2),
		CARGO_PERIODO_MES DECIMAL(18,2),
		ABONO_PERIODO_MES DECIMAL(18,2),
		
		PRIMARY KEY (
			 CORR_EMPRESA, CUENTA_CONTABLE
		)			
	)	
BEGIN

    SET NOCOUNT ON
	
	--Obtener el periodo
	SELECT @ANIO_PERIODO=YEAR(@FECHA_CONSULTA), @MES_PERIODO=MONTH(@FECHA_CONSULTA), @EXISTE_PARTIDA_INI=0	    
		
	IF @MES_PERIODO=1
	BEGIN
		SELECT @ANIO_PERIODO_ANTE=@ANIO_PERIODO-1,@MES_PERIODO_ANTE=12
	END ELSE
	BEGIN
		SELECT @ANIO_PERIODO_ANTE=@ANIO_PERIODO,@MES_PERIODO_ANTE=@MES_PERIODO-1
	END
	
	IF NOT EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
			  WHERE CORR_EMPRESA=@CORR_EMPRESA
			  AND ANIO_PERIODO=@ANIO_PERIODO_ANTE
			  AND MES_PERIODO=@MES_PERIODO_ANTE
			  AND ESTADO_PERIODO_CON='CE')
	BEGIN
		IF EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
			  WHERE CORR_EMPRESA=@CORR_EMPRESA			  
			  AND ESTADO_PERIODO_CON='CE'
			  AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO)
		BEGIN
			SELECT TOP 1 @ANIO_PERIODO=ANIO_PERIODO
			,@MES_PERIODO=MES_PERIODO
			FROM CON_PERIODO_CONTABLE
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ESTADO_PERIODO_CON='CE'
			AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO
			ORDER BY ANIO_PERIODO DESC, MES_PERIODO DESC
			
			IF @MES_PERIODO=12
			BEGIN
				SELECT @ANIO_PERIODO=@ANIO_PERIODO+1,@MES_PERIODO=1
			END ELSE
			BEGIN
				SELECT @ANIO_PERIODO=@ANIO_PERIODO,@MES_PERIODO=@MES_PERIODO+1
			END
		END ELSE
		BEGIN
			IF EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
			  WHERE CORR_EMPRESA=@CORR_EMPRESA  
			  AND ESTADO_PERIODO_CON='AB'
			  AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO)
		    BEGIN		    		    
				SELECT TOP 1 @ANIO_PERIODO=ANIO_PERIODO,@MES_PERIODO=MES_PERIODO			
				FROM CON_PERIODO_CONTABLE
				WHERE CORR_EMPRESA=@CORR_EMPRESA  
				AND ESTADO_PERIODO_CON='AB'
				AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO
				ORDER BY ANIO_PERIODO ASC, MES_PERIODO ASC
			END ELSE
			BEGIN
			    SELECT TOP 1 @ANIO_PERIODO=ANIO_PERIODO,@MES_PERIODO=MES_PERIODO
				FROM CON_PARTIDA
				WHERE CORR_EMPRESA=@CORR_EMPRESA
				AND ESTADO_PARTIDA='AP'
				AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO
				ORDER BY ANIO_PERIODO ASC, MES_PERIODO ASC
			END
		END
	END	

	--Obtener el saldo inicial de todas las cuentas hasta un nivel y hasta la fecha de consulta
	IF @OPCION_CONSULTA=0
	BEGIN	    	    
		--Carga el saldo historico segun el periodo
		INSERT INTO @SALDO
		(
		CORR_EMPRESA,
		CUENTA_CONTABLE,
		CUENTA_MAYOR,
		ES_DEBE,
		ES_HABER,
		SALDO_INICIAL,
		CARGO_PERIODO,
		ABONO_PERIODO,
		SALDO_FINAL,
		EXISTE_PARTIDA_INI)    
		SELECT DISTINCT 
		A.CORR_EMPRESA,
		A.CUENTA_CONTABLE,
		A.CUENTA_MAYOR,
		A.ES_DEBE,
		A.ES_HABER,
		CASE @MES_PERIODO 
		WHEN 1 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL1,0))
		WHEN 2 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL2,0))
		WHEN 3 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL3,0))
		WHEN 4 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL4,0))
		WHEN 5 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL5,0))
		WHEN 6 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL6,0))
		WHEN 7 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL7,0))
		WHEN 8 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL8,0))
		WHEN 9 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL9,0))
		WHEN 10 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL10,0))
		WHEN 11 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL11,0))
		WHEN 12 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL12,0))
		ELSE 0 END,
		0,0,0,ISNULL(C.MES_PERIODO,0)
		FROM CON_CATALOGO_CUENTA A
		LEFT OUTER JOIN CON_CATALOGO_SALDO_HIS B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE AND B.ANIO_PERIODO=@ANIO_PERIODO		
		LEFT OUTER JOIN (
						SELECT  A.CORR_EMPRESA, A.ANIO_PERIODO,A.MES_PERIODO, SUBSTRING(A.CUENTA_CONTABLE,1,B.NUMERO_CARACTERES) CUENTA_CONTABLE, SUM(A.SALDO_INICIAL) SALDO_INICIAL
						FROM V_CON_PARTIDA_INICIAL A
						INNER JOIN CON_CATALOGO_CUENTA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_CONTABLE
						INNER JOIN V_CON_RUBRO_NIVEL_MAX D ON C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CODIGO_RUBRO=D.CODIGO_RUBRO						
						INNER JOIN CON_RUBRO_NIVEL B ON C.CORR_EMPRESA=B.CORR_EMPRESA AND C.CODIGO_RUBRO=B.CODIGO_RUBRO AND B.NIVEL=CASE WHEN @NIVEL=0 THEN D.NIVEL_MAX ELSE @NIVEL END
						GROUP BY  A.CORR_EMPRESA, A.ANIO_PERIODO,A.MES_PERIODO, SUBSTRING(A.CUENTA_CONTABLE,1,B.NUMERO_CARACTERES)
						) C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_CONTABLE AND C.ANIO_PERIODO=@ANIO_PERIODO AND C.MES_PERIODO=@MES_PERIODO		
		LEFT OUTER JOIN CON_CONFI_REPORTE_DETA D ON A.CORR_EMPRESA=D.CORR_EMPRESA 
		AND (A.CUENTA_CONTABLE>=D.CUENTA_CONTABLE_INI OR ISNULL(D.CUENTA_CONTABLE_INI,'')='')
		AND (A.CUENTA_CONTABLE<=D.CUENTA_CONTABLE_FINA OR ISNULL(D.CUENTA_CONTABLE_FINA,'')='')
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA		
		AND (A.NIVEL<=@NIVEL OR @NIVEL=0)
		AND (A.CUENTA_CONTABLE>=@CUENTA_CONTABLE_INICIAL OR ISNULL(@CUENTA_CONTABLE_INICIAL,'')='')
		AND (A.CUENTA_CONTABLE<=@CUENTA_CONTABLE_FINAL OR ISNULL(@CUENTA_CONTABLE_FINAL,'')='')
		AND (D.CORR_CONFI_REPORTE=@CORR_CONFI_REPORTE OR @CORR_CONFI_REPORTE IS NULL)
		
		SELECT @FECHA_INICIAL=CONVERT(DATE,CONVERT(VARCHAR,@ANIO_PERIODO)+'-'+CONVERT(VARCHAR,@MES_PERIODO)+'-1')
		
		INSERT INTO @SALDO_MOV
		(CORR_EMPRESA,CUENTA_CONTABLE,CARGO_PERIODO,ABONO_PERIODO)
		SELECT A.CORR_EMPRESA,
        SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END) CUENTA_CONTABLE,
		SUM(A.MONTO_CARGO) MONTO_CARGO,SUM(A.MONTO_ABONO) MONTO_ABONO
		FROM V_CON_PARTIDA_CUENTA A
		INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
		INNER JOIN CON_RUBRO_NIVEL C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CODIGO_RUBRO=C.CODIGO_RUBRO AND C.NIVEL=CASE WHEN @NIVEL=0 THEN 1 ELSE @NIVEL END
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA					
		AND A.FECHA_PARTIDA>=@FECHA_INICIAL					
		AND A.FECHA_PARTIDA<=@FECHA_CONSULTA
		AND (A.PARTIDA_CIERRE=@PARTIDA_CIERRE OR @PARTIDA_CIERRE=1)
		AND (A.PARTIDA_LIQUIDACION=@PARTIDA_LIQUIDACION OR @PARTIDA_LIQUIDACION=1)	
		AND ((A.PARTIDA_APERTURA=1 AND (A.ANIO_PERIODO*100)+A.MES_PERIODO<>(@ANIO_PERIODO*100)+@MES_PERIODO) OR A.PARTIDA_APERTURA=0)	
		GROUP BY A.CORR_EMPRESA,SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END)
		
		--Actualizar cargos y abonos del periodo
		UPDATE A SET
		A.CARGO_PERIODO=ISNULL(B.CARGO_PERIODO,0),
		A.ABONO_PERIODO=ISNULL(B.ABONO_PERIODO,0)
		FROM @SALDO A
		INNER JOIN @SALDO_MOV B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
		
		--Actualizando saldo solo del ultimo mes
		DELETE FROM @SALDO_MOV
		
		SELECT @FECHA_INICIAL=CONVERT(DATE,CONVERT(VARCHAR,YEAR(@FECHA_CONSULTA))+'-'+CONVERT(VARCHAR,MONTH(@FECHA_CONSULTA))+'-1')
		
		--Actualizar cargos y abonos del periodo
		INSERT INTO @SALDO_MOV
		(CORR_EMPRESA,CUENTA_CONTABLE,CARGO_PERIODO,ABONO_PERIODO)
		SELECT A.CORR_EMPRESA,
        SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END) CUENTA_CONTABLE,
		SUM(A.MONTO_CARGO) MONTO_CARGO,SUM(A.MONTO_ABONO) MONTO_ABONO
		FROM V_CON_PARTIDA_CUENTA A
		INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
		INNER JOIN CON_RUBRO_NIVEL C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CODIGO_RUBRO=C.CODIGO_RUBRO AND C.NIVEL=CASE WHEN @NIVEL=0 THEN 1 ELSE @NIVEL END
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA					
		AND A.FECHA_PARTIDA>=@FECHA_INICIAL
		AND A.FECHA_PARTIDA<=@FECHA_CONSULTA
		AND (A.PARTIDA_CIERRE=@PARTIDA_CIERRE OR @PARTIDA_CIERRE=1)
		AND (A.PARTIDA_LIQUIDACION=@PARTIDA_LIQUIDACION OR @PARTIDA_LIQUIDACION=1)
		AND ((A.PARTIDA_APERTURA=1 AND (A.ANIO_PERIODO*100)+A.MES_PERIODO<>(@ANIO_PERIODO*100)+@MES_PERIODO) OR A.PARTIDA_APERTURA=0)	
		GROUP BY A.CORR_EMPRESA,SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END)
		
		UPDATE A SET
		A.CARGO_PERIODO_MES=ISNULL(B.CARGO_PERIODO,0),
		A.ABONO_PERIODO_MES=ISNULL(B.ABONO_PERIODO,0)
		FROM @SALDO A
		INNER JOIN @SALDO_MOV B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE				
	END ELSE
	IF @OPCION_CONSULTA=1 --Obtener el saldo de todas las cuentas de un nivel hasta antes de la fecha de consulta
	BEGIN	
		--Carga el saldo historico segun el periodo
		INSERT INTO @SALDO
		(
		CORR_EMPRESA,
		CUENTA_CONTABLE,
		CUENTA_MAYOR,
		ES_DEBE,
		ES_HABER,
		SALDO_INICIAL,
		CARGO_PERIODO,
		ABONO_PERIODO,
		SALDO_FINAL,
		EXISTE_PARTIDA_INI)    
		SELECT DISTINCT 
		A.CORR_EMPRESA,
		A.CUENTA_CONTABLE,
		A.CUENTA_MAYOR,
		A.ES_DEBE,
		A.ES_HABER,
		CASE @MES_PERIODO 
		WHEN 1 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL1,0))
		WHEN 2 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL2,0))
		WHEN 3 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL3,0))
		WHEN 4 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL4,0))
		WHEN 5 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL5,0))
		WHEN 6 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL6,0))
		WHEN 7 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL7,0))
		WHEN 8 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL8,0))
		WHEN 9 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL9,0))
		WHEN 10 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL10,0))
		WHEN 11 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL11,0))
		WHEN 12 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL12,0))
		ELSE 0 END,
		0,0,0,ISNULL(C.MES_PERIODO,0)
		FROM CON_CATALOGO_CUENTA A
		LEFT OUTER JOIN CON_CATALOGO_SALDO_HIS B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE AND B.ANIO_PERIODO=@ANIO_PERIODO
		LEFT OUTER JOIN (
						SELECT  A.CORR_EMPRESA, A.ANIO_PERIODO,A.MES_PERIODO, SUBSTRING(A.CUENTA_CONTABLE,1,B.NUMERO_CARACTERES) CUENTA_CONTABLE, SUM(A.SALDO_INICIAL) SALDO_INICIAL
						FROM V_CON_PARTIDA_INICIAL A
						INNER JOIN CON_CATALOGO_CUENTA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_CONTABLE
						INNER JOIN V_CON_RUBRO_NIVEL_MAX D ON C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CODIGO_RUBRO=D.CODIGO_RUBRO						
						INNER JOIN CON_RUBRO_NIVEL B ON C.CORR_EMPRESA=B.CORR_EMPRESA AND C.CODIGO_RUBRO=B.CODIGO_RUBRO AND B.NIVEL=CASE WHEN @NIVEL=0 THEN D.NIVEL_MAX ELSE @NIVEL END						
						GROUP BY  A.CORR_EMPRESA, A.ANIO_PERIODO,A.MES_PERIODO, SUBSTRING(A.CUENTA_CONTABLE,1,B.NUMERO_CARACTERES)
						) C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_CONTABLE AND C.ANIO_PERIODO=@ANIO_PERIODO AND C.MES_PERIODO=@MES_PERIODO
		LEFT OUTER JOIN CON_CONFI_REPORTE_DETA D ON A.CORR_EMPRESA=D.CORR_EMPRESA 
		AND (A.CUENTA_CONTABLE>=D.CUENTA_CONTABLE_INI OR ISNULL(D.CUENTA_CONTABLE_INI,'')='')
		AND (A.CUENTA_CONTABLE<=D.CUENTA_CONTABLE_FINA OR ISNULL(D.CUENTA_CONTABLE_FINA,'')='')
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA		
		AND (A.NIVEL=@NIVEL OR @NIVEL=0)
		AND (A.CUENTA_CONTABLE>=@CUENTA_CONTABLE_INICIAL OR ISNULL(@CUENTA_CONTABLE_INICIAL,'')='')
		AND (A.CUENTA_CONTABLE<=@CUENTA_CONTABLE_FINAL OR ISNULL(@CUENTA_CONTABLE_FINAL,'')='')				
		AND (D.CORR_CONFI_REPORTE=@CORR_CONFI_REPORTE OR @CORR_CONFI_REPORTE IS NULL)
		SELECT @FECHA_INICIAL=CONVERT(DATE,CONVERT(VARCHAR,@ANIO_PERIODO)+'-'+CONVERT(VARCHAR,@MES_PERIODO)+'-1')		
		
		--Actualizar cargos y abonos del periodo
		INSERT INTO @SALDO_MOV
		(CORR_EMPRESA,CUENTA_CONTABLE,CARGO_PERIODO,ABONO_PERIODO)
		SELECT A.CORR_EMPRESA,
        SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END) CUENTA_CONTABLE,
		SUM(A.MONTO_CARGO) MONTO_CARGO,SUM(A.MONTO_ABONO) MONTO_ABONO
		FROM V_CON_PARTIDA_CUENTA A
		INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
		INNER JOIN CON_RUBRO_NIVEL C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CODIGO_RUBRO=C.CODIGO_RUBRO AND C.NIVEL=CASE WHEN @NIVEL=0 THEN 1 ELSE @NIVEL END
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA					
		AND A.FECHA_PARTIDA>=@FECHA_INICIAL
		AND A.FECHA_PARTIDA<=@FECHA_CONSULTA
		AND (A.PARTIDA_CIERRE=@PARTIDA_CIERRE OR @PARTIDA_CIERRE=1)
		AND (A.PARTIDA_LIQUIDACION=@PARTIDA_LIQUIDACION OR @PARTIDA_LIQUIDACION=1)	
		AND ((A.PARTIDA_APERTURA=1 AND (A.ANIO_PERIODO*100)+A.MES_PERIODO<>(@ANIO_PERIODO*100)+@MES_PERIODO) OR A.PARTIDA_APERTURA=0)					
		GROUP BY A.CORR_EMPRESA,SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END)
							
		UPDATE A SET
		A.CARGO_PERIODO=ISNULL(B.CARGO_PERIODO,0),
		A.ABONO_PERIODO=ISNULL(B.ABONO_PERIODO,0)
		FROM @SALDO A
		INNER JOIN @SALDO_MOV B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
		
		--Actualizando saldo solo del ultimo mes
		DELETE FROM @SALDO_MOV
		
		SELECT @FECHA_INICIAL=CONVERT(DATE,CONVERT(VARCHAR,YEAR(@FECHA_CONSULTA))+'-'+CONVERT(VARCHAR,MONTH(@FECHA_CONSULTA))+'-1')
		
		--Actualizar cargos y abonos del periodo
		INSERT INTO @SALDO_MOV
		(CORR_EMPRESA,CUENTA_CONTABLE,CARGO_PERIODO,ABONO_PERIODO)
		SELECT A.CORR_EMPRESA,
        SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END) CUENTA_CONTABLE,
		SUM(A.MONTO_CARGO) MONTO_CARGO,SUM(A.MONTO_ABONO) MONTO_ABONO
		FROM V_CON_PARTIDA_CUENTA A
		INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
		INNER JOIN CON_RUBRO_NIVEL C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CODIGO_RUBRO=C.CODIGO_RUBRO AND C.NIVEL=CASE WHEN @NIVEL=0 THEN 1 ELSE @NIVEL END
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA					
		AND A.FECHA_PARTIDA>=@FECHA_INICIAL
		AND A.FECHA_PARTIDA<=@FECHA_CONSULTA
		AND (A.PARTIDA_CIERRE=@PARTIDA_CIERRE OR @PARTIDA_CIERRE=1)
		AND (A.PARTIDA_LIQUIDACION=@PARTIDA_LIQUIDACION OR @PARTIDA_LIQUIDACION=1)
		AND ((A.PARTIDA_APERTURA=1 AND (A.ANIO_PERIODO*100)+A.MES_PERIODO<>(@ANIO_PERIODO*100)+@MES_PERIODO) OR A.PARTIDA_APERTURA=0)	
		GROUP BY A.CORR_EMPRESA,SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END)
		
		UPDATE A SET
		A.CARGO_PERIODO_MES=ISNULL(B.CARGO_PERIODO,0),
		A.ABONO_PERIODO_MES=ISNULL(B.ABONO_PERIODO,0)
		FROM @SALDO A
		INNER JOIN @SALDO_MOV B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE		
	END ELSE	
	IF @OPCION_CONSULTA=2 --Obtener el saldo inicial de las cuentas de ingresos y gastos hasta un nivel y hasta la fecha de consulta
	BEGIN	    	    
		--Carga el saldo historico segun el periodo
		INSERT INTO @SALDO
		(
		CORR_EMPRESA,
		CUENTA_CONTABLE,
		CUENTA_MAYOR,
		ES_DEBE,
		ES_HABER,
		SALDO_INICIAL,
		CARGO_PERIODO,
		ABONO_PERIODO,
		SALDO_FINAL,
		EXISTE_PARTIDA_INI)    
		SELECT DISTINCT 
		A.CORR_EMPRESA,
		A.CUENTA_CONTABLE,
		A.CUENTA_MAYOR,
		A.ES_DEBE,
		A.ES_HABER,
		CASE @MES_PERIODO 
		WHEN 1 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL1,0))
		WHEN 2 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL2,0))
		WHEN 3 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL3,0))
		WHEN 4 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL4,0))
		WHEN 5 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL5,0))
		WHEN 6 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL6,0))
		WHEN 7 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL7,0))
		WHEN 8 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL8,0))
		WHEN 9 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL9,0))
		WHEN 10 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL10,0))
		WHEN 11 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL11,0))
		WHEN 12 THEN ISNULL(C.SALDO_INICIAL,ISNULL(B.SALDO_INICIAL12,0))
		ELSE 0 END,
		0,0,0,ISNULL(C.MES_PERIODO,0)
		FROM CON_CATALOGO_CUENTA A
		LEFT OUTER JOIN CON_CATALOGO_SALDO_HIS B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE AND B.ANIO_PERIODO=@ANIO_PERIODO
		LEFT OUTER JOIN (
						SELECT  A.CORR_EMPRESA, A.ANIO_PERIODO, A.MES_PERIODO, SUBSTRING(A.CUENTA_CONTABLE,1,B.NUMERO_CARACTERES) CUENTA_CONTABLE, SUM(A.SALDO_INICIAL) SALDO_INICIAL
						FROM V_CON_PARTIDA_INICIAL A
						INNER JOIN CON_CATALOGO_CUENTA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_CONTABLE
						INNER JOIN V_CON_RUBRO_NIVEL_MAX D ON C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CODIGO_RUBRO=D.CODIGO_RUBRO						
						INNER JOIN CON_RUBRO_NIVEL B ON C.CORR_EMPRESA=B.CORR_EMPRESA AND C.CODIGO_RUBRO=B.CODIGO_RUBRO AND B.NIVEL=CASE WHEN @NIVEL=0 THEN D.NIVEL_MAX ELSE @NIVEL END
						GROUP BY  A.CORR_EMPRESA, A.ANIO_PERIODO,A.MES_PERIODO, SUBSTRING(A.CUENTA_CONTABLE,1,B.NUMERO_CARACTERES)
						) C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_CONTABLE AND C.ANIO_PERIODO=@ANIO_PERIODO AND C.MES_PERIODO=@MES_PERIODO
		LEFT OUTER JOIN CON_CONFI_REPORTE_DETA D ON A.CORR_EMPRESA=D.CORR_EMPRESA 
		AND (A.CUENTA_CONTABLE>=D.CUENTA_CONTABLE_INI OR ISNULL(D.CUENTA_CONTABLE_INI,'')='')
		AND (A.CUENTA_CONTABLE<=D.CUENTA_CONTABLE_FINA OR ISNULL(D.CUENTA_CONTABLE_FINA,'')='')
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA		
		--AND (A.NIVEL<=@NIVEL OR @NIVEL=0)
		AND (A.NIVEL=@NIVEL OR @NIVEL=0)
		AND A.CLASE_RUBRO IN('IN','GA')
		AND (A.CUENTA_CONTABLE>=@CUENTA_CONTABLE_INICIAL OR ISNULL(@CUENTA_CONTABLE_INICIAL,'')='')
		AND (A.CUENTA_CONTABLE<=@CUENTA_CONTABLE_FINAL OR ISNULL(@CUENTA_CONTABLE_FINAL,'')='')
		AND (D.CORR_CONFI_REPORTE=@CORR_CONFI_REPORTE OR @CORR_CONFI_REPORTE IS NULL)	
		SELECT @FECHA_INICIAL=CONVERT(DATE,CONVERT(VARCHAR,@ANIO_PERIODO)+'-'+CONVERT(VARCHAR,@MES_PERIODO)+'-1')
		
		--Actualizar cargos y abonos del periodo
		INSERT INTO @SALDO_MOV
		(CORR_EMPRESA,CUENTA_CONTABLE,CARGO_PERIODO,ABONO_PERIODO)
		SELECT A.CORR_EMPRESA,
        SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END) CUENTA_CONTABLE,
		SUM(A.MONTO_CARGO) MONTO_CARGO,SUM(A.MONTO_ABONO) MONTO_ABONO
		FROM V_CON_PARTIDA_CUENTA A
		INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
		INNER JOIN CON_RUBRO_NIVEL C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CODIGO_RUBRO=C.CODIGO_RUBRO AND C.NIVEL=CASE WHEN @NIVEL=0 THEN 1 ELSE @NIVEL END
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA					
		AND A.FECHA_PARTIDA>=@FECHA_INICIAL
		AND A.FECHA_PARTIDA<=@FECHA_CONSULTA
		AND (A.PARTIDA_CIERRE=@PARTIDA_CIERRE OR @PARTIDA_CIERRE=1)
		AND (A.PARTIDA_LIQUIDACION=@PARTIDA_LIQUIDACION OR @PARTIDA_LIQUIDACION=1)
		AND ((A.PARTIDA_APERTURA=1 AND (A.ANIO_PERIODO*100)+A.MES_PERIODO<>(@ANIO_PERIODO*100)+@MES_PERIODO) OR A.PARTIDA_APERTURA=0)	
		GROUP BY A.CORR_EMPRESA,SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END)
		
		UPDATE A SET
		A.CARGO_PERIODO=ISNULL(B.CARGO_PERIODO,0),
		A.ABONO_PERIODO=ISNULL(B.ABONO_PERIODO,0)
		FROM @SALDO A
		INNER JOIN @SALDO_MOV B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
		
		--Actualizando saldo solo del ultimo mes
		DELETE FROM @SALDO_MOV
		
		SELECT @FECHA_INICIAL=CONVERT(DATE,CONVERT(VARCHAR,YEAR(@FECHA_CONSULTA))+'-'+CONVERT(VARCHAR,MONTH(@FECHA_CONSULTA))+'-1')
		
		--Actualizar cargos y abonos del periodo
		INSERT INTO @SALDO_MOV
		(CORR_EMPRESA,CUENTA_CONTABLE,CARGO_PERIODO,ABONO_PERIODO)
		SELECT A.CORR_EMPRESA,
        SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END) CUENTA_CONTABLE,
		SUM(A.MONTO_CARGO) MONTO_CARGO,SUM(A.MONTO_ABONO) MONTO_ABONO
		FROM V_CON_PARTIDA_CUENTA A
		INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
		INNER JOIN CON_RUBRO_NIVEL C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CODIGO_RUBRO=C.CODIGO_RUBRO AND C.NIVEL=CASE WHEN @NIVEL=0 THEN 1 ELSE @NIVEL END
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA					
		AND A.FECHA_PARTIDA>=@FECHA_INICIAL
		AND A.FECHA_PARTIDA<=@FECHA_CONSULTA
		AND (A.PARTIDA_CIERRE=@PARTIDA_CIERRE OR @PARTIDA_CIERRE=1)
		AND (A.PARTIDA_LIQUIDACION=@PARTIDA_LIQUIDACION OR @PARTIDA_LIQUIDACION=1)
		AND ((A.PARTIDA_APERTURA=1 AND (A.ANIO_PERIODO*100)+A.MES_PERIODO<>(@ANIO_PERIODO*100)+@MES_PERIODO) OR A.PARTIDA_APERTURA=0)	
		GROUP BY A.CORR_EMPRESA,SUBSTRING(A.CUENTA_CONTABLE,1,CASE WHEN @NIVEL=0 THEN LEN(A.CUENTA_CONTABLE) ELSE C.NUMERO_CARACTERES END)
		
		UPDATE A SET
		A.CARGO_PERIODO_MES=ISNULL(B.CARGO_PERIODO,0),
		A.ABONO_PERIODO_MES=ISNULL(B.ABONO_PERIODO,0)
		FROM @SALDO A
		INNER JOIN @SALDO_MOV B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE		
	END
	
	--Mayorizar Movimientos
	IF @MAYORIZA<>0
	BEGIN
		IF EXISTS(SELECT 1 FROM @SALDO WHERE EXISTE_PARTIDA_INI<>0)
		BEGIN
			SELECT @EXISTE_PARTIDA_INI=1		
		END ELSE
		BEGIN
			SELECT @EXISTE_PARTIDA_INI=0
		END 
	
		INSERT INTO @CARGO_ABONO
		(CORR_EMPRESA,CUENTA_CONTABLE,SALDO_INICIAL,CARGO_PERIODO,ABONO_PERIODO,CARGO_PERIODO_MES,ABONO_PERIODO_MES) 
		SELECT  CORR_EMPRESA, ISNULL(CUENTA_MAYOR,''),SUM(SALDO_INICIAL), SUM(CARGO_PERIODO), SUM(ABONO_PERIODO), SUM(ISNULL(CARGO_PERIODO_MES,0)), SUM(ISNULL(ABONO_PERIODO_MES,0))
		FROM @SALDO
		GROUP BY  CORR_EMPRESA,CUENTA_MAYOR 
		HAVING (SUM(CARGO_PERIODO)>0 OR SUM(ABONO_PERIODO)>0 OR SUM(SALDO_INICIAL)<>0)	
		
		WHILE EXISTS(SELECT 1 FROM @CARGO_ABONO)
		BEGIN
			SELECT TOP 1 @CUENTA_CONTABLE=CUENTA_CONTABLE,@SALDO_INICIAL=SALDO_INICIAL
			,@CARGO_PERIODO=CARGO_PERIODO, @ABONO_PERIODO=ABONO_PERIODO
			, @CARGO_PERIODO_MES=CARGO_PERIODO_MES, @ABONO_PERIODO_MES=ABONO_PERIODO_MES
			FROM @CARGO_ABONO
			ORDER BY CUENTA_CONTABLE
			
			SELECT @CUENTA_MAYOR=@CUENTA_CONTABLE
			WHILE (@CUENTA_MAYOR<>'')
			BEGIN
				UPDATE @SALDO SET
				SALDO_INICIAL=ISNULL(SALDO_INICIAL,0)+CASE WHEN ISNULL(@EXISTE_PARTIDA_INI,0)<>0 THEN ISNULL(@SALDO_INICIAL,0) ELSE 0 END, --Mayorizando la partida inicial				
				--SALDO_INICIAL=ISNULL(SALDO_INICIAL,0)+CASE WHEN @MES_PERIODO=1 THEN ISNULL(@SALDO_INICIAL,0) ELSE 0 END, --Mayorizando la partida inicial				
				CARGO_PERIODO=ISNULL(CARGO_PERIODO,0)+ISNULL(@CARGO_PERIODO,0),
				ABONO_PERIODO=ISNULL(ABONO_PERIODO,0)+ISNULL(@ABONO_PERIODO,0),
				CARGO_PERIODO_MES=ISNULL(CARGO_PERIODO_MES,0)+ISNULL(@CARGO_PERIODO_MES,0),
				ABONO_PERIODO_MES=ISNULL(ABONO_PERIODO_MES,0)+ISNULL(@ABONO_PERIODO_MES,0)
				WHERE CORR_EMPRESA=@CORR_EMPRESA
				AND CUENTA_CONTABLE=@CUENTA_MAYOR

				SELECT @CUENTA_MAYOR=CUENTA_MAYOR 
				FROM @SALDO
				WHERE CORR_EMPRESA=@CORR_EMPRESA
				AND CUENTA_CONTABLE=@CUENTA_MAYOR
				
				SELECT @CUENTA_MAYOR=ISNULL(@CUENTA_MAYOR,'')		    
			END			
			
			DELETE FROM @CARGO_ABONO
			WHERE CUENTA_CONTABLE=@CUENTA_CONTABLE
		END
	END
	
	IF @APLICA_DEBE_HABE=1
	BEGIN			
		UPDATE @SALDO SET
		SALDO_FINAL=(ISNULL(SALDO_INICIAL,0)+ISNULL(CARGO_PERIODO,0)-ISNULL(ABONO_PERIODO ,0))*(CASE WHEN ES_DEBE=1 THEN 1 ELSE CASE WHEN ES_HABER =1 THEN -1 ELSE 0 END END)

		UPDATE @SALDO SET 
		SALDO_INICIAL=ISNULL(SALDO_INICIAL,0)*(CASE WHEN ES_DEBE=1 THEN 1 ELSE CASE WHEN ES_HABER=1 THEN -1 ELSE 0 END END)
	END ELSE
	BEGIN
		UPDATE @SALDO SET
		SALDO_FINAL=ISNULL(SALDO_INICIAL,0)+(ISNULL(CARGO_PERIODO,0)-ISNULL(ABONO_PERIODO ,0))
	END
	
	SELECT CORR_EMPRESA
	,CUENTA_CONTABLE
	,CUENTA_MAYOR
	,ES_DEBE
	,ES_HABER
	,SALDO_INICIAL
	,ISNULL(CARGO_PERIODO_MES,0) CARGO_PERIODO
	,ISNULL(ABONO_PERIODO_MES,0) ABONO_PERIODO
	,SALDO_FINAL
	FROM @SALDO
END
GO
