SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_BAN_CONCILIACION_BANCARIA_MOVI]
	@CORR_EMPRESA int,
	@CORR_CUENTA_BANCO int,
	@CORR_CONCILIACION int OUTPUT,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
AS
BEGIN
	SET NOCOUNT ON
	
	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0
	
	BEGIN TRY
	
		DECLARE @ESTADO_CONCILIACION VARCHAR(2),				
				@MAXIMO int
		
		DECLARE @TEMP1 TABLE ( --Almacena los registros de la tabla BAN_CONCILIA_DETA que aun no se han conciliado
			CORR_CONCILIACION_DETA INT,
			FECHA_MOVIMIENTO date,
			CORR_TIPO_MOVIMIENTO int,
			NUMERO_REFERENCIA_BANCO varchar(255),
			MONTO_CARGO decimal(18, 2),
			MONTO_ABONO decimal(18, 2),
			ESTA_CONCILIA bit,
			ESTA_PROC bit
		)
		
		DECLARE @TEMP2 TABLE ( --Almacena los registros de la consulta de transacciones pendientes de conciliar por parte de contabilidad 
			CORR_EMPRESA int, 
			ANIO_PERIODO int,
			MES_PERIODO int,
			CORR_CLASE_PARTIDA int,
			CORR_PARTIDA int,
			NUMERO_DOCUMENTO varchar(25),
			FECHA_PARTIDA date,
			NOMBRE_CLASE_PARTIDA varchar(60),
			ESTADO_PARTIDA varchar(2),
			CORR_PARTIDA_DETA int,
			CUENTA_CONTABLE varchar(30),
			MONTO_CARGO decimal(12,2),
			MONTO_ABONO decimal(12,2),
			MONTO_CARGO_FORANEA decimal(12,2),
			MONTO_ABONO_FORANEA decimal(12,2),
			NOMBRE_TRAN varchar(1255),
			ESTA_CONCILIA bit	
		)
		
		SELECT @ESTADO_CONCILIACION=ESTADO_CONCILIACION
		FROM BAN_CONCILIA_BANCARIA 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
		AND CORR_CONCILIACION=@CORR_CONCILIACION 
		
		IF @ESTADO_CONCILIACION IS NULL
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe esta conciliacion.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END ELSE
		IF @ESTADO_CONCILIACION <> 'DI'
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Esta conciliacion ya esta aplicada o anulada y no permite modificaciones.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END
		
		--Se guardan los registros de concilia_deta que aun no se han conciliado con contabilidad
		INSERT INTO @TEMP1(CORR_CONCILIACION_DETA,CORR_TIPO_MOVIMIENTO,FECHA_MOVIMIENTO,NUMERO_REFERENCIA_BANCO,MONTO_CARGO,MONTO_ABONO,ESTA_CONCILIA,ESTA_PROC)
		SELECT CORR_CONCILIACION_DETA,CORR_TIPO_MOVIMIENTO,FECHA_MOVIMIENTO,NUMERO_REFERENCIA_BANCO,MONTO_CARGO,MONTO_ABONO,0 ESTA_CONCILIA,0 ESTA_PROC
		FROM BAN_CONCILIA_BANCARIA_DETA 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
		AND CORR_CONCILIACION=@CORR_CONCILIACION 
		AND (ANIO_PERIODO IS NULL OR MES_PERIODO IS NULL OR CORR_CLASE_PARTIDA IS NULL OR CORR_PARTIDA IS NULL OR CORR_PARTIDA_DETA IS NULL)
		
		--Se guardan los registros de la consulta que devuelve los detalles de partidas contables que no se han conciliado y que son correspondientes a esta cuenta bancaria
		INSERT INTO @TEMP2 
		EXEC PRAL_DATA_BAN_CONCILIA_BANCARIA_PENDIENTE 1, @CORR_EMPRESA, @CORR_CUENTA_BANCO, @CORR_CONCILIACION
		
		--Se borran los registros actuales para generar los nuevos
		DELETE FROM BAN_CONCILIA_BANCARIA_MOVI 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
		AND CORR_CONCILIACION=@CORR_CONCILIACION 
		
		--Se insertan los concilia_deta que no se encontro coincidencia en contabilidad
		INSERT INTO BAN_CONCILIA_BANCARIA_MOVI
        (CORR_EMPRESA,CORR_CUENTA_BANCO,CORR_CONCILIACION,CORR_MOVIMIENTO,CORR_LINEA,ANIO_PERIODO,MES_PERIODO,CORR_CLASE_PARTIDA,CORR_PARTIDA,CORR_PARTIDA_DETA,CORR_TIPO_MOVIMIENTO,CORR_CONCILIACION_DETA,MONTO_CARGO,MONTO_ABONO)
		SELECT @CORR_EMPRESA,@CORR_CUENTA_BANCO,@CORR_CONCILIACION
		,ROW_NUMBER() OVER(PARTITION BY A.CORR_EMPRESA ORDER BY A.CORR_CONCILIACION_DETA) CORR_MOVIMIENTO,
		B.CORR_LINEA,YEAR(A.FECHA_MOVIMIENTO) ANIO_PERIODO,MONTH(A.FECHA_MOVIMIENTO) MES_PERIODO,NULL CORR_CLASE_PARTIDA,NULL CORR_PARTIDA,NULL CORR_PARTIDA_DETA,A.CORR_TIPO_MOVIMIENTO,A.CORR_CONCILIACION_DETA,A.MONTO_CARGO,A.MONTO_ABONO 
		FROM BAN_CONCILIA_BANCARIA_DETA A
		INNER JOIN BAN_TIPO_MOVI_BANCARIO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO=B.CORR_TIPO_MOVIMIENTO 
		INNER JOIN BAN_LINEA_TRABAJO_CONCILIACION C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_LINEA=C.CORR_LINEA
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA 
		AND A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
		AND A.CORR_CONCILIACION=@CORR_CONCILIACION 
		AND (A.ANIO_PERIODO IS NULL OR A.MES_PERIODO IS NULL OR A.CORR_CLASE_PARTIDA IS NULL OR A.CORR_PARTIDA IS NULL OR A.CORR_PARTIDA_DETA IS NULL)
		
		--Se obtiene el ultimo registro
		SELECT @MAXIMO=ISNULL(MAX(CORR_MOVIMIENTO),0)
		FROM BAN_CONCILIA_BANCARIA_MOVI A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA 
		AND A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
		AND A.CORR_CONCILIACION=@CORR_CONCILIACION 

		--Se insertan los registros pendientes de conciliar por parte de contabilidad
		INSERT INTO BAN_CONCILIA_BANCARIA_MOVI
        (CORR_EMPRESA,CORR_CUENTA_BANCO,CORR_CONCILIACION,CORR_MOVIMIENTO,CORR_LINEA,ANIO_PERIODO,MES_PERIODO,CORR_CLASE_PARTIDA,CORR_PARTIDA,CORR_PARTIDA_DETA,CORR_TIPO_MOVIMIENTO,CORR_CONCILIACION_DETA,MONTO_CARGO,MONTO_ABONO)
		SELECT @CORR_EMPRESA,@CORR_CUENTA_BANCO,@CORR_CONCILIACION
		,@MAXIMO+ROW_NUMBER() OVER(ORDER BY A.CORR_EMPRESA,A.ANIO_PERIODO,A.MES_PERIODO,A.CORR_CLASE_PARTIDA,A.CORR_PARTIDA,A.CORR_PARTIDA_DETA) CORR_MOVIMIENTO,
		CASE WHEN (A.MONTO_CARGO>0) THEN B.CORR_LINEA_AUMENTA WHEN (A.MONTO_ABONO>0) THEN B.CORR_LINEA_DISMINUYE END CORR_LINEA
		,A.ANIO_PERIODO,A.MES_PERIODO,A.CORR_CLASE_PARTIDA,A.CORR_PARTIDA,A.CORR_PARTIDA_DETA,NULL CORR_TIPO_MOVIMIENTO,NULL CORR_CONCILIACION_DETA,A.MONTO_CARGO,A.MONTO_ABONO 
		FROM @TEMP2 A
		INNER JOIN CON_CLASE_PARTIDA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA 		
		INNER JOIN BAN_LINEA_TRABAJO_CONCILIACION C ON B.CORR_EMPRESA=C.CORR_EMPRESA 
											AND CASE WHEN (A.MONTO_CARGO>0) THEN B.CORR_LINEA_AUMENTA WHEN (A.MONTO_ABONO>0) THEN B.CORR_LINEA_DISMINUYE END=C.CORR_LINEA
		
		--IF EXISTS(SELECT 1 FROM BAN_CONCILIA_BANCARIA A
		--		LEFT OUTER JOIN V_BAN_CONCILIA_BANCARIA_MOVI_SUM C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=C.CORR_CUENTA_BANCO AND A.CORR_CONCILIACION=C.CORR_CONCILIACION
		--		WHERE A.CORR_SUSCRIPCION=@CORR_SUSCRIPCION
		--		AND A.CORR_CONFI_PAIS=@CORR_CONFI_PAIS
		--		AND A.CORR_EMPRESA=@CORR_EMPRESA
		--		AND A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
		--		AND A.CORR_CONCILIACION=@CORR_CONCILIACION
		--		AND A.SALDO_CUENTA_CONTA=(A.SALDO_CUENTA_BANCO+ISNULL(C.MONTO_AUMENTA,0)-ISNULL(C.MONTO_DISMINUYE,0))
		--) 
		--BEGIN
		--	UPDATE BAN_CONCILIA_BANCARIA SET 
		--	ESTADO_CONCILIACION='AP'
		--	WHERE CORR_SUSCRIPCION=@CORR_SUSCRIPCION
		--	AND CORR_CONFI_PAIS=@CORR_CONFI_PAIS
		--	AND CORR_EMPRESA=@CORR_EMPRESA
		--	AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
		--	AND CORR_CONCILIACION=@CORR_CONCILIACION
		--END

	END TRY
	BEGIN CATCH
		
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO

