SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_GENE_PARTIDA_APERTURA]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
	DECLARE @CORR_MONEDA INT, @FACTOR_CAMBIO DECIMAL(16,6), @OPERADOR VARCHAR(2),
		@CORR_CLASE_PARTIDA INT, @CORR_PARTIDA INT, @FECHA_PARTIDA DATE, @NOMBRE_PARTIDA VARCHAR(255), @FECHA_CREA DATETIME,
		@ANIO_PERIODO_CIERRE INT, @MES_PERIODO_CIERRE INT, @CORR_CLASE_PARTIDA_CIERRE INT, @CORR_PARTIDA_CIERRE INT,
		@CORR_PARTIDA_DETA INT, @CUENTA_CONTABLE VARCHAR(30), @CORR_AUXILIAR INT, @CORR_CENTRO_COSTO INT, @NOMBRE_TRAN VARCHAR(255),
		@MONTO_CARGO DECIMAL(18,2), @MONTO_ABONO DECIMAL(18,2)

	DECLARE @TEMPR TABLE (
		CORR_PARTIDA_DETA INT,
		CUENTA_CONTABLE VARCHAR(30),
		CORR_AUXILIAR INT,
		CORR_CENTRO_COSTO INT,
		NOMBRE_TRAN VARCHAR(255),
		MONTO_CARGO DECIMAL(18,2),
		MONTO_ABONO DECIMAL(18,2)
	)

BEGIN
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = '', @SYS_FILAS_AFECTADAS = 0

	BEGIN TRY
		IF NOT EXISTS (
			SELECT 1 FROM CON_PERIODO_CONTABLE
			WHERE CORR_EMPRESA = @CORR_EMPRESA
			  AND ANIO_PERIODO = @ANIO_PERIODO
			  AND MES_PERIODO = @MES_PERIODO
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = 'El periodo contable NO existe', @SYS_FILAS_AFECTADAS = 0
			GOTO FINA
		END

		IF @MES_PERIODO = 1
			SELECT @ANIO_PERIODO_CIERRE = @ANIO_PERIODO - 1, @MES_PERIODO_CIERRE = 12
		ELSE
			SELECT @ANIO_PERIODO_CIERRE = @ANIO_PERIODO, @MES_PERIODO_CIERRE = @MES_PERIODO - 1

		SELECT TOP 1 @CORR_CLASE_PARTIDA_CIERRE = CORR_CLASE_PARTIDA
		FROM CON_CLASE_PARTIDA A
		WHERE A.CORR_EMPRESA = @CORR_EMPRESA
		  AND A.PARTIDA_CIERRE = 1

		SELECT @FECHA_PARTIDA = CONVERT(DATE, CONVERT(VARCHAR, @ANIO_PERIODO) + '-' + CONVERT(VARCHAR, @MES_PERIODO) + '-01'),
			@NOMBRE_PARTIDA = 'APERTURA ANUAL DE CUENTAS DE BALANCE ' + CONVERT(VARCHAR(4), @ANIO_PERIODO),
			@FECHA_CREA = GETDATE(),
			@FACTOR_CAMBIO = 1,
			@OPERADOR = '*'

		IF NOT EXISTS (
			SELECT 1 FROM CON_PARTIDA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
			  AND ANIO_PERIODO = @ANIO_PERIODO_CIERRE
			  AND MES_PERIODO = @MES_PERIODO_CIERRE
			  AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA_CIERRE
			  AND CLASE_PARTIDA = 'CIE'
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000,
				@SYS_MENSAJE_ERROR = 'No existe una partida de cierre en el periodo contable ' + CONVERT(VARCHAR, @MES_PERIODO_CIERRE) + ' del ' + CONVERT(VARCHAR, @ANIO_PERIODO_CIERRE),
				@SYS_FILAS_AFECTADAS = 0
			GOTO FINA
		END

		SELECT TOP 1 @CORR_CLASE_PARTIDA = CORR_CLASE_PARTIDA
		FROM CON_CLASE_PARTIDA
		WHERE CORR_EMPRESA = @CORR_EMPRESA
		  AND NOMBRE_CORTO_CLASE = 'APE'

		IF EXISTS (
			SELECT 1 FROM CON_PARTIDA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
			  AND ANIO_PERIODO = @ANIO_PERIODO
			  AND MES_PERIODO = @MES_PERIODO
			  AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = 'Ya existe una partida de apertura', @SYS_FILAS_AFECTADAS = 0
			GOTO FINA
		END

		SELECT TOP 1 @CORR_MONEDA = CORR_MONEDA
		FROM CON_PARAMETRO
		WHERE CORR_EMPRESA = @CORR_EMPRESA

		SELECT TOP 1 @CORR_PARTIDA_CIERRE = CORR_PARTIDA
		FROM CON_PARTIDA
		WHERE CORR_EMPRESA = @CORR_EMPRESA
		  AND ANIO_PERIODO = @ANIO_PERIODO_CIERRE
		  AND MES_PERIODO = @MES_PERIODO_CIERRE
		  AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA_CIERRE
		  AND CLASE_PARTIDA = 'CIE'

		BEGIN TRANSACTION

		EXEC PRAL_MTTO_CON_PARTIDA
			1,
			@CORR_EMPRESA,
			@ANIO_PERIODO,
			@MES_PERIODO,
			@CORR_CLASE_PARTIDA,
			@CORR_PARTIDA OUTPUT,
			@FECHA_PARTIDA,
			0,
			@NOMBRE_PARTIDA,
			'DI',
			'NOR',
			@CORR_MONEDA,
			@FACTOR_CAMBIO,
			@OPERADOR,
			@SYS_LOGIN_USUARIO,
			@FECHA_CREA,
			@SYS_ESTACION,
			@SYS_LOGIN_USUARIO,
			@FECHA_CREA,
			@SYS_ESTACION,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS OUTPUT,
			@SYS_NUMERO_ERROR OUTPUT,
			@SYS_MENSAJE_ERROR OUTPUT

		INSERT INTO @TEMPR
		(CORR_PARTIDA_DETA, CUENTA_CONTABLE, CORR_AUXILIAR, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
		SELECT B.CORR_PARTIDA_DETA,
			B.CUENTA_CONTABLE,
			B.CORR_AUXILIAR,
			B.CORR_CENTRO_COSTO,
			@NOMBRE_PARTIDA NOMBRE_TRAN,
			B.MONTO_ABONO MONTO_CARGO,
			B.MONTO_CARGO MONTO_ABONO
		FROM CON_PARTIDA A
		INNER JOIN CON_PARTIDA_DETA B ON A.CORR_EMPRESA = B.CORR_EMPRESA
			AND A.ANIO_PERIODO = B.ANIO_PERIODO
			AND A.MES_PERIODO = B.MES_PERIODO
			AND A.CORR_CLASE_PARTIDA = B.CORR_CLASE_PARTIDA
			AND A.CORR_PARTIDA = B.CORR_PARTIDA
		WHERE A.CORR_EMPRESA = @CORR_EMPRESA
		  AND A.ANIO_PERIODO = @ANIO_PERIODO_CIERRE
		  AND A.MES_PERIODO = @MES_PERIODO_CIERRE
		  AND A.CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA_CIERRE
		  AND A.CORR_PARTIDA = @CORR_PARTIDA_CIERRE
		  AND A.CLASE_PARTIDA = 'CIE'

		WHILE EXISTS (SELECT 1 FROM @TEMPR)
		BEGIN
			SELECT TOP 1 @CORR_PARTIDA_DETA = CORR_PARTIDA_DETA,
				@CUENTA_CONTABLE = CUENTA_CONTABLE,
				@CORR_AUXILIAR = CORR_AUXILIAR,
				@CORR_CENTRO_COSTO = CORR_CENTRO_COSTO,
				@MONTO_CARGO = MONTO_CARGO,
				@MONTO_ABONO = MONTO_ABONO,
				@NOMBRE_TRAN = NOMBRE_TRAN
			FROM @TEMPR

			EXEC PRAL_MTTO_CON_PARTIDA_DETA
				1,
				@CORR_EMPRESA,
				@ANIO_PERIODO,
				@MES_PERIODO,
				@CORR_CLASE_PARTIDA,
				@CORR_PARTIDA,
				@CORR_PARTIDA_DETA OUTPUT,
				@CUENTA_CONTABLE,
				@CORR_CENTRO_COSTO,
				@MONTO_CARGO,
				@MONTO_ABONO,
				@NOMBRE_TRAN,
				0,
				0,
				@FACTOR_CAMBIO,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@SYS_FILAS_AFECTADAS OUTPUT,
				@SYS_NUMERO_ERROR OUTPUT,
				@SYS_MENSAJE_ERROR OUTPUT,
				@CORR_AUXILIAR

			DELETE FROM @TEMPR
			WHERE CORR_PARTIDA_DETA = @CORR_PARTIDA_DETA
		END

		IF @@TRANCOUNT <> 0
			COMMIT TRANSACTION

		SELECT @SYS_FILAS_AFECTADAS = @@ROWCOUNT
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT <> 0
			ROLLBACK TRAN

		DECLARE @CORR_BITACORA INT, @SEVERITY_ERROR INT, @ESTADO_ERROR INT,
		        @ORIGEN_ERROR NVARCHAR(126), @LINEA_ERROR INT, @SYS_FECHA DATETIME

		SELECT @CORR_BITACORA = 0,
			@SYS_NUMERO_ERROR = ERROR_NUMBER(),
			@SEVERITY_ERROR = ERROR_SEVERITY(),
			@ESTADO_ERROR = ERROR_STATE(),
			@ORIGEN_ERROR = ERROR_PROCEDURE(),
			@LINEA_ERROR = ERROR_LINE(),
			@SYS_MENSAJE_ERROR = ERROR_MESSAGE(),
			@SYS_FECHA = GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1, @CORR_BITACORA OUTPUT, 'PM', @SYS_NUMERO_ERROR, @SEVERITY_ERROR, @ESTADO_ERROR, @ORIGEN_ERROR, @LINEA_ERROR, @SYS_MENSAJE_ERROR, @SYS_LOGIN_USUARIO, @SYS_FECHA, @SYS_ESTACION
	END CATCH
FINA:
END
GO
