SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_PROVEEDOR]
(
	@TIPO_ACTUALIZA INT,
	@CORR_PROVEEDOR INT OUTPUT,
	@CODIGO_PROVEEDOR varchar(20),
	@TIPO_PERSONERIA varchar(1),
	@NOMBRE_PROVEEDOR varchar(150),
	@PRIMER_NOMBRE varchar(50),
	@SEGUNDO_NOMBRE varchar(50),
	@PRIMER_APELLIDO varchar(50),
	@SEGUNDO_APELLIDO varchar(50),
	@NOMBRE_COMERCIAL varchar(150),
	@CORR_TIPO_DIP int,
	@NUMERO_DIP varchar(25),
	@NUMERO_NRC varchar(25),
	@NUMERO_NIT varchar(25),
	@CORR_ACTIVIDAD_ECONOMICA int,
	@DIRECCION_PROVEEDOR varchar(50),
	@CODIGO_PAIS VARCHAR(3),
	@CODIGO_DEPTO VARCHAR(20),
	@CODIGO_MUNICIPIO VARCHAR(20),
	@NOMBRE_CONTACTO varchar(150),
	@TELEFONO_FIJO varchar(25),
	@TELEFONO_MOVIL varchar(25),
	@CORREO_ELECTRONICO_1 varchar(255),
	@CORREO_ELECTRONICO_2 varchar(255),
	@CORR_FORMA_PAGO int,
	@CUENTA_BANCARIA varchar(30),
	@CORR_BANCO int,
	@ESTADO_PROVEEDOR varchar(1),
	@ESTADO_PROVEEDOR_WEB varchar(1),
	@CORR_CONDICION_PAGO INT,
	@USUARIO_CREA varchar(30),
	@FECHA_CREA datetime,
	@ESTACION_CREA varchar(50),
	@USUARIO_ACTU varchar(30),
	@FECHA_ACTU datetime,
	@ESTACION_ACTU varchar(50),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF EXISTS(SELECT 1 FROM COM_PROVEEDOR A
				  WHERE A.CORR_PROVEEDOR=@CORR_PROVEEDOR)
		BEGIN
			SET @TIPO_ACTUALIZA=2
		END ELSE
		BEGIN
			SET @TIPO_ACTUALIZA=1
		END

		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			INSERT INTO COM_PROVEEDOR
			(CORR_PROVEEDOR,CODIGO_PROVEEDOR,TIPO_PERSONERIA,NOMBRE_PROVEEDOR,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,NOMBRE_COMERCIAL,CORR_TIPO_DIP,NUMERO_DIP,NUMERO_NRC,NUMERO_NIT,CORR_ACTIVIDAD_ECONOMICA,DIRECCION_PROVEEDOR,CODIGO_PAIS,CODIGO_DEPTO,CODIGO_MUNICIPIO,NOMBRE_CONTACTO,TELEFONO_FIJO,TELEFONO_MOVIL,CORREO_ELECTRONICO_1,CORREO_ELECTRONICO_2,CORR_FORMA_PAGO,CUENTA_BANCARIA,CORR_BANCO,ESTADO_PROVEEDOR,ESTADO_PROVEEDOR_WEB,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU,CORR_CONDICION_PAGO)
			VALUES
			(@CORR_PROVEEDOR,@CODIGO_PROVEEDOR,@TIPO_PERSONERIA,@NOMBRE_PROVEEDOR,@PRIMER_NOMBRE,@SEGUNDO_NOMBRE,@PRIMER_APELLIDO,@SEGUNDO_APELLIDO,@NOMBRE_COMERCIAL,@CORR_TIPO_DIP,@NUMERO_DIP,@NUMERO_NRC,@NUMERO_NIT,@CORR_ACTIVIDAD_ECONOMICA,@DIRECCION_PROVEEDOR,@CODIGO_PAIS,@CODIGO_DEPTO,@CODIGO_MUNICIPIO,@NOMBRE_CONTACTO,@TELEFONO_FIJO,@TELEFONO_MOVIL,@CORREO_ELECTRONICO_1,@CORREO_ELECTRONICO_2,@CORR_FORMA_PAGO,@CUENTA_BANCARIA,@CORR_BANCO,@ESTADO_PROVEEDOR,@ESTADO_PROVEEDOR_WEB,@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU,@CORR_CONDICION_PAGO)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE COM_PROVEEDOR SET
			CODIGO_PROVEEDOR=@CODIGO_PROVEEDOR,
			TIPO_PERSONERIA=@TIPO_PERSONERIA,
			NOMBRE_PROVEEDOR=@NOMBRE_PROVEEDOR,
			PRIMER_NOMBRE=@PRIMER_NOMBRE,
			SEGUNDO_NOMBRE=@SEGUNDO_NOMBRE,
			PRIMER_APELLIDO=@PRIMER_APELLIDO,
			SEGUNDO_APELLIDO=@SEGUNDO_APELLIDO,
			NOMBRE_COMERCIAL=@NOMBRE_COMERCIAL,
			CORR_TIPO_DIP=@CORR_TIPO_DIP,
			NUMERO_DIP=@NUMERO_DIP,
			NUMERO_NRC=@NUMERO_NRC,
			NUMERO_NIT=@NUMERO_NIT,
			CORR_ACTIVIDAD_ECONOMICA=@CORR_ACTIVIDAD_ECONOMICA,
			DIRECCION_PROVEEDOR=@DIRECCION_PROVEEDOR,
			CODIGO_PAIS=@CODIGO_PAIS,
			CODIGO_DEPTO=@CODIGO_DEPTO,
			CODIGO_MUNICIPIO=@CODIGO_MUNICIPIO,
			NOMBRE_CONTACTO=@NOMBRE_CONTACTO,
			TELEFONO_FIJO=@TELEFONO_FIJO,
			TELEFONO_MOVIL=@TELEFONO_MOVIL,
			CORREO_ELECTRONICO_1=@CORREO_ELECTRONICO_1,
			CORREO_ELECTRONICO_2=@CORREO_ELECTRONICO_2,
			CORR_FORMA_PAGO=@CORR_FORMA_PAGO,
			CUENTA_BANCARIA=@CUENTA_BANCARIA,
			CORR_BANCO=@CORR_BANCO,
			ESTADO_PROVEEDOR=@ESTADO_PROVEEDOR,
			ESTADO_PROVEEDOR_WEB=@ESTADO_PROVEEDOR_WEB,
			CORR_CONDICION_PAGO=@CORR_CONDICION_PAGO,
			USUARIO_ACTU=@USUARIO_ACTU,
			FECHA_ACTU=@FECHA_ACTU,
			ESTACION_ACTU=@ESTACION_ACTU
			WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM COM_PROVEEDOR
			WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
