SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_SOLI_COTIZACION_DISPONIBLE]
(
	@TIPO_CONSULTA int,
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT=NULL,
	@CORR_SOLI_COTIZACION INT=NULL,
	@FECHA_INICIAL DATE=null,
	@FECHA_FINAL DATE=null,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT *,CONVERT(BIT,0) SELECCION
			FROM V_COM_SOLI_COTIZACION A
			WHERE A.FECHA_SOLI_COTIZACION >= @FECHA_INICIAL
			AND A.FECHA_SOLI_COTIZACION <= @FECHA_FINAL
			AND A.ESTADO_SOLI_COTIZACION='AP'
			AND NOT EXISTS(SELECT 1
						   FROM COM_CUADRO_COMPARATIVO_SOLI_COTIZACION B
						   WHERE A.CORR_EMPRESA=B.CORR_EMPRESA
						   AND A.ANIO_PERIODO=B.ANIO_PERIODO_SOLI_COTI
						   AND A.CORR_SOLI_COTIZACION=B.CORR_SOLI_COTIZACION)
			ORDER BY A.ANIO_PERIODO, A.CORR_SOLI_COTIZACION DESC
		END ELSE
		IF @OPCION_CONSULTA=1
		BEGIN
			SELECT * 
			FROM COM_SOLI_COTIZACION A 
			INNER JOIN COM_COTIZACION B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO_SOLI_COTI AND A.CORR_SOLI_COTIZACION=B.CORR_SOLI_COTIZACION
			INNER JOIN dbo.COM_COTIZACION_DETA C ON C.CORR_EMPRESA = B.CORR_EMPRESA AND C.ANIO_PERIODO = B.ANIO_PERIODO AND C.CORR_COTIZACION = B.CORR_COTIZACION
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
			ORDER BY A.ANIO_PERIODO, A.CORR_SOLI_COTIZACION DESC
		END
	END 
END
GO
