SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: aplica una partida contable (DI -> AP) y registra el evento en bitácora.
-- Cómo lo hace: valida periodo/estado/cuadre, actualiza ESTADO_PARTIDA y ejecuta PRAL_MTTO_CON_PARTIDA_BITACORA.
CREATE OR ALTER PROCEDURE [dbo].[PRAL_MTTO_CON_PARTIDA_APLICAR]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_CLASE_PARTIDA int,
	@CORR_PARTIDA int OUTPUT,
	@USUARIO_ACTU varchar(30),
	@FECHA_ACTU datetime,
	@ESTACION_ACTU varchar(50),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
	DECLARE @MONTO_CARGO DECIMAL(18,2), @MONTO_ABONO DECIMAL(18,2),
		@DETALLE_PARTIDA VARCHAR(255), @NOMBRE_CORTO_CLASE VARCHAR(10),
		@CORR_PARTIDA_BITACORA INT,
		@SYS_FILAS_BIT INT,
		@SYS_NUM_BIT NUMERIC(38,0),
		@SYS_MSG_BIT NVARCHAR(4000)
BEGIN
	SET NOCOUNT ON
	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		SELECT @NOMBRE_CORTO_CLASE=NOMBRE_CORTO_CLASE
		FROM CON_CLASE_PARTIDA
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA

		SELECT @DETALLE_PARTIDA='Año '+CONVERT(Varchar,@ANIO_PERIODO)+
		' Mes '+CONVERT(Varchar,@MES_PERIODO)+
		' Clase '+ISNULL(@NOMBRE_CORTO_CLASE,'')+
		' Partida No.'+CONVERT(Varchar,@CORR_PARTIDA)

		IF NOT EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND ANIO_PERIODO=@ANIO_PERIODO
				  AND MES_PERIODO=@MES_PERIODO
				  AND ESTADO_PERIODO_CON='AB')
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='El periodo contable NO esta Abierto. La partida '+@DETALLE_PARTIDA+' no se puede aplicar.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF NOT EXISTS(SELECT 1 FROM CON_PARTIDA
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND ANIO_PERIODO=@ANIO_PERIODO
				  AND MES_PERIODO=@MES_PERIODO
				  AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
				  AND CORR_PARTIDA=@CORR_PARTIDA
				  AND ESTADO_PARTIDA='DI')
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='La partida '+@DETALLE_PARTIDA+' no esta en estado DIGITADO.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		SELECT @MONTO_CARGO=SUM(A.MONTO_CARGO),
		@MONTO_ABONO=SUM(A.MONTO_ABONO)
		FROM CON_PARTIDA_DETA A
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
		AND CORR_PARTIDA=@CORR_PARTIDA

		IF @MONTO_CARGO<>@MONTO_ABONO
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Partida NO cuadrada. La partida '+@DETALLE_PARTIDA+' no se puede aplicar.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF ISNULL(@MONTO_CARGO,0)=0 AND ISNULL(@MONTO_ABONO,0)=0
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30003,@SYS_MENSAJE_ERROR='La partida suma cero. La partida '+@DETALLE_PARTIDA+' no se puede aplicar.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF NOT EXISTS(SELECT 1 FROM CON_PARTIDA_DETA
					  WHERE CORR_EMPRESA=@CORR_EMPRESA
					  AND ANIO_PERIODO=@ANIO_PERIODO
					  AND MES_PERIODO=@MES_PERIODO
					  AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
					  AND CORR_PARTIDA=@CORR_PARTIDA)
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30003,@SYS_MENSAJE_ERROR='La partida NO tiene detalle. La partida '+@DETALLE_PARTIDA+' no se puede aplicar.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		UPDATE CON_PARTIDA SET
		ESTADO_PARTIDA='AP',
		USUARIO_ACTU=@USUARIO_ACTU,
		FECHA_ACTU=@FECHA_ACTU,
		ESTACION_ACTU=@ESTACION_ACTU
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
		AND CORR_PARTIDA=@CORR_PARTIDA

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

		-- Qué hace: registra en bitácora el evento APLICAR al terminar la aplicación.
		-- Cómo lo hace: ejecuta PRAL_MTTO_CON_PARTIDA_BITACORA con observación por defecto.
		SELECT @CORR_PARTIDA_BITACORA=0,@SYS_FILAS_BIT=0,@SYS_NUM_BIT=0,@SYS_MSG_BIT=''
		EXEC PRAL_MTTO_CON_PARTIDA_BITACORA
			@CORR_EMPRESA=@CORR_EMPRESA,
			@ANIO_PERIODO=@ANIO_PERIODO,
			@MES_PERIODO=@MES_PERIODO,
			@CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA,
			@CORR_PARTIDA=@CORR_PARTIDA,
			@CORR_PARTIDA_BITACORA=@CORR_PARTIDA_BITACORA OUTPUT,
			@TIPO_EVENTO='APLICAR',
			@FECHA_EVENTO=@FECHA_ACTU,
			@ESTADO_ANTERIOR='DI',
			@ESTADO_NUEVO='AP',
			@OBSERVACION='Partida aplicada.',
			@USUARIO_CREA=@USUARIO_ACTU,
			@ESTACION_CREA=@ESTACION_ACTU,
			@SYS_LOGIN_USUARIO=@SYS_LOGIN_USUARIO,
			@SYS_ESTACION=@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS=@SYS_FILAS_BIT OUTPUT,
			@SYS_NUMERO_ERROR=@SYS_NUM_BIT OUTPUT,
			@SYS_MENSAJE_ERROR=@SYS_MSG_BIT OUTPUT

		IF ISNULL(@SYS_NUM_BIT,0)<>0
		BEGIN
			SELECT @SYS_NUMERO_ERROR=@SYS_NUM_BIT,@SYS_MENSAJE_ERROR=@SYS_MSG_BIT
			GOTO FINA
		END
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR=ERROR_NUMBER(),@SYS_MENSAJE_ERROR=ERROR_MESSAGE()
	END CATCH;
FINA:
END
GO
