SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_BAN_CONCILIA_BANCARIA_RESUMEN]
(
	@TIPO_CONSULTA int,
	@CORR_EMPRESA int=NULL,
	@CORR_CUENTA_BANCO int=NULL,
	@CORR_CONCILIACION int=NULL,
	@AUMENTA_DISMINUYE smallint=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		SELECT  A.CORR_EMPRESA,
		@CORR_CUENTA_BANCO,
		@CORR_CONCILIACION,
		A.CORR_LINEA,
		A.NOMBRE_LINEA_TRABAJO,
		A.AUMENTA_DISMINUYE,
		SUM(ISNULL(B.MONTO,0)) MONTO
		FROM V_BAN_LINEA_TRABAJO_CONCILIACION A
		LEFT OUTER JOIN V_BAN_CONCILIA_BANCARIA_MOVI B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_LINEA=B.CORR_LINEA
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.AUMENTA_DISMINUYE=@AUMENTA_DISMINUYE 
		AND B.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
		AND B.CORR_CONCILIACION=@CORR_CONCILIACION		
		GROUP BY A.CORR_EMPRESA,A.CORR_LINEA,A.NOMBRE_LINEA_TRABAJO,A.AUMENTA_DISMINUYE
		UNION
		SELECT  A.CORR_EMPRESA,
		@CORR_CUENTA_BANCO,
		@CORR_CONCILIACION,
		A.CORR_LINEA,
		A.NOMBRE_LINEA_TRABAJO,
		A.AUMENTA_DISMINUYE,
		0 MONTO
		FROM V_BAN_LINEA_TRABAJO_CONCILIACION A
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND NOT EXISTS (
				SELECT 1 FROM V_BAN_CONCILIA_BANCARIA_MOVI B 
				WHERE B.CORR_EMPRESA=@CORR_EMPRESA 
				AND B.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
				AND B.CORR_CONCILIACION=@CORR_CONCILIACION 
				AND CORR_LINEA=A.CORR_LINEA )
		AND A.AUMENTA_DISMINUYE=@AUMENTA_DISMINUYE 
		

		
	END 

END
GO

