SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_SEG_USUARIO_CAMBIO_CLAVE]
(	
	@LOGIN_SISTEMA varchar(30) output,
	@CLAVE_USUARIO varbinary(max)=NULL,
	@CLAVE_USUARIO_SAL varbinary(max)=NULL,	
	@USUARIO_ACTU varchar(30),
	@FECHA_ACTU datetime,
	@ESTACION_ACTU varchar(50),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON
	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY	

		UPDATE SEG_USUARIO SET 
		CLAVE_USUARIO=@CLAVE_USUARIO,
		CLAVE_USUARIO_SAL=@CLAVE_USUARIO_SAL,
		USUARIO_ACTU=@USUARIO_ACTU,
		FECHA_ACTU=@FECHA_ACTU,
		ESTACION_ACTU=@ESTACION_ACTU,
		REQUIERE_CAMBIO_CLAVE=0
		WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA 
		
		-- Registrar en historial que se hizo un cambio de contraseña
		DECLARE @CORR_LOGIN INT;
		EXEC PRAL_MTTO_SEG_USUARIO_LOGIN_HISTORIAL_INSERT
			@LOGIN_SISTEMA=@LOGIN_SISTEMA,
			@FECHA_LOGIN=@FECHA_ACTU,
			@IP_ADDRESS=NULL,
			@NAVEGADOR=NULL,
			@CODIGO_SUITE=NULL,
			@EXITOSO=1,
			@MENSAJE='Cambio de contraseña exitoso',
			@ES_CAMBIO_CLAVE=1,
			@CORR_LOGIN=@CORR_LOGIN OUTPUT;
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

	END TRY
	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int           ,
		@SEVERITY_ERROR  int           ,
		@ESTADO_ERROR     int           ,
		@ORIGEN_ERROR nvarchar(126) ,
		@LINEA_ERROR      int	     ,
		@SYS_FECHA DateTime   

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION
		

	END CATCH;

FINA:
END

RETURN 0
GO
