SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_COM_BITACORA]
(
	@TIPO_CONSULTA int,
	@CORR_EMPRESA int=NULL,
	@CORR_BITACORA int=NULL,
	@CODIGO_OPCION VARCHAR(30)=NULL,
	@CLASE_BITACORA VARCHAR(2)=NULL,
	@FECHA_INICIAL DATE= NULL,
	@FECHA_FINAL DATE= NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		IF @OPCION_CONSULTA =0
		BEGIN
			SELECT * FROM V_COM_BITACORA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
		END ELSE
		IF @OPCION_CONSULTA =1
		BEGIN
			SELECT * FROM V_COM_BITACORA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND (CODIGO_OPCION=@CODIGO_OPCION OR ISNULL(@CODIGO_OPCION,'')='')
			AND (CLASE_BITACORA=@CLASE_BITACORA OR ISNULL(@CLASE_BITACORA,'')='')
			AND FECHA_BITACORA>=@FECHA_INICIAL
			AND FECHA_BITACORA<=@FECHA_FINAL
			ORDER BY FECHA_BITACORA DESC
		END
		
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		SELECT * FROM V_COM_BITACORA
		WHERE CORR_EMPRESA=@CORR_EMPRESA
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_COM_BITACORA
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_BITACORA=@CORR_BITACORA
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT CORR_EMPRESA FROM V_COM_BITACORA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_BITACORA=@CORR_BITACORA
		END
	END

END
GO
