SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_DOCUMENTO_DETA_DOC]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_DOCUMENTO int,
	@ANIO_PERIODO_DOC int,
	@MES_PERIODO_DOC int,
	@CORR_DOCUMENTO_DOC int OUTPUT,
	@MONTO_DOCUMENTO decimal(14,2),
	@MONTO_INICIAL decimal(14,2),
	@MONTO_INGRESO decimal(14,2),
	@MONTO_FINAL decimal(14,2),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN

			INSERT INTO COM_DOCUMENTO_DETA_DOC
			(CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,CORR_DOCUMENTO,ANIO_PERIODO_DOC,MES_PERIODO_DOC,CORR_DOCUMENTO_DOC,MONTO_DOCUMENTO,MONTO_INICIAL,MONTO_INGRESO,MONTO_FINAL)
			VALUES
			(@CORR_EMPRESA,@ANIO_PERIODO,@MES_PERIODO,@CORR_DOCUMENTO,@ANIO_PERIODO_DOC,@MES_PERIODO_DOC,@CORR_DOCUMENTO_DOC,@MONTO_DOCUMENTO,@MONTO_INICIAL,@MONTO_INGRESO,@MONTO_FINAL)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE COM_DOCUMENTO_DETA_DOC SET
			MONTO_DOCUMENTO=@MONTO_DOCUMENTO,
			MONTO_INICIAL=@MONTO_INICIAL,
			MONTO_INGRESO=@MONTO_INGRESO,
			MONTO_FINAL=@MONTO_FINAL
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			AND ANIO_PERIODO_DOC=@ANIO_PERIODO_DOC
			AND MES_PERIODO_DOC=@MES_PERIODO_DOC
			AND CORR_DOCUMENTO_DOC=@CORR_DOCUMENTO_DOC
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM COM_DOCUMENTO_DETA_DOC
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			AND ANIO_PERIODO_DOC=@ANIO_PERIODO_DOC
			AND MES_PERIODO_DOC=@MES_PERIODO_DOC
			AND CORR_DOCUMENTO_DOC=@CORR_DOCUMENTO_DOC
		END
		
		EXECUTE PRAL_GENE_COM_DOCUMENTO_TOTAL_NCR_NDB
		@CORR_EMPRESA
		,@ANIO_PERIODO
		,@MES_PERIODO 
		,@CORR_DOCUMENTO OUTPUT 
		,@SYS_LOGIN_USUARIO                        
		,@SYS_ESTACION                               
		,@SYS_FILAS_AFECTADAS OUTPUT 
		,@SYS_NUMERO_ERROR OUTPUT       
		,@SYS_MENSAJE_ERROR OUTPUT     
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
