SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

IF OBJECT_ID(N'dbo.PRAL_IMPR_CON_PARTIDA_CONTABLE', N'P') IS NOT NULL
    DROP PROCEDURE dbo.PRAL_IMPR_CON_PARTIDA_CONTABLE
GO

CREATE PROCEDURE [dbo].[PRAL_IMPR_CON_PARTIDA_CONTABLE]
(
  @CORR_EMPRESA INT,
  @FECHA_INICIAL DATE = NULL,
  @FECHA_FINAL DATE = NULL,
  @ANIO_PERIODO INT = 0,
  @MES_PERIODO INT = 0,
  @CORR_CLASE_PARTIDA INT = 0,
  @CORR_PARTIDA INT = 0,
  @CORR_PARTIDA_INICIAL INT = 0,
  @CORR_PARTIDA_FINAL INT = 0,
  @FOLIADO BIT = 0,
  @NUMERO_FOLIO INT = 0,
  @CORR_MONEDA INT = 0,
  @OPCION_CONSULTA INT = 0
)
AS
BEGIN
    SET NOCOUNT ON

    DECLARE @MOSTRAR_FECHA_IMPRESION BIT,
            @CORR_MONEDA_EMPRESA INT

    SELECT @MOSTRAR_FECHA_IMPRESION = A.MOSTRAR_FECHA_IMPRESION,
           @CORR_MONEDA_EMPRESA = A.CORR_MONEDA
    FROM CON_PARAMETRO A
    WHERE A.CORR_EMPRESA = @CORR_EMPRESA

    IF @CORR_MONEDA = 0
        SET @CORR_MONEDA = ISNULL(@CORR_MONEDA_EMPRESA, 0)

    IF @OPCION_CONSULTA = 0
    BEGIN
        SELECT A.CORR_EMPRESA
            ,A.ANIO_PERIODO
            ,A.MES_PERIODO
            ,A.CORR_CLASE_PARTIDA
            ,A.NOMBRE_CLASE_PARTIDA
            ,A.NOMBRE_CORTO_CLASE
            ,A.CORR_PARTIDA
            ,A.CORR_PARTIDA NUMERO_PARTIDA
            ,A.FECHA_PARTIDA
            ,A.NUMERO_DOCUMENTO
            ,A.NOMBRE_PARTIDA
            ,A.ESTADO_PARTIDA
            ,A.NOMBRE_ESTADO_PARTIDA
            ,A.USUARIO_CREA
            ,A.FECHA_CREA
            ,A.ESTACION_CREA
            ,A.USUARIO_ACTU
            ,A.FECHA_ACTU
            ,A.ESTACION_ACTU
            ,A.CLASE_PARTIDA
            ,A.NOMBRE_CLASE_PARTIDA2
            ,B.CORR_PARTIDA_DETA
            ,B.CUENTA_CONTABLE
            ,B.NOMBRE_CUENTA
            ,B.CORR_CENTRO_COSTO
            ,B.NOMBRE_CENTRO
            ,B.MONTO_CARGO
            ,B.MONTO_ABONO
            ,B.NOMBRE_TRAN
            ,CAST(NULL AS VARCHAR(50)) NUMERO_DOCUMENTO_DETA
            ,B.CORR_AUXILIAR
            ,ISNULL(F.CORR_AUXILIAR_REPLICADO, '') CORR_AUXILIAR_REPLICADO
            ,ISNULL(H.CORR_CENTRO_COSTO_REPLICADO, '') CORR_CENTRO_COSTO_REPLICADO
            ,A.DESCRIPCION_MONEDA
            ,CONVERT(BIT, ISNULL(@MOSTRAR_FECHA_IMPRESION, 0)) MOSTRAR_FECHA_IMPRESION
            ,@FOLIADO FOLIADO
            ,@NUMERO_FOLIO NUMERO_FOLIO
            ,ISNULL(A.NOMBRE_MONEDA, '') NOMBRE_MONEDA
            ,ISNULL(E.CUENTA_MAYOR, '') CUENTA_MAYOR
            ,ISNULL(D.NOMBRE_CUENTA, '') NOMBRE_CUENTA_MAYOR
        FROM V_CON_PARTIDA A
        INNER JOIN V_CON_PARTIDA_DETA B
            ON A.CORR_EMPRESA = B.CORR_EMPRESA
           AND A.ANIO_PERIODO = B.ANIO_PERIODO
           AND A.MES_PERIODO = B.MES_PERIODO
           AND A.CORR_CLASE_PARTIDA = B.CORR_CLASE_PARTIDA
           AND A.CORR_PARTIDA = B.CORR_PARTIDA
        LEFT OUTER JOIN CON_CATALOGO_CUENTA E
            ON B.CORR_EMPRESA = E.CORR_EMPRESA
           AND B.CUENTA_CONTABLE = E.CUENTA_CONTABLE
        LEFT OUTER JOIN CON_CATALOGO_CUENTA D
            ON B.CORR_EMPRESA = D.CORR_EMPRESA
           AND E.CUENTA_MAYOR = D.CUENTA_CONTABLE
        LEFT OUTER JOIN V_CON_CATALOGO_CUENTA_AUXI F
            ON B.CORR_EMPRESA = F.CORR_EMPRESA
           AND B.CUENTA_CONTABLE = F.CUENTA_CONTABLE
           AND B.CORR_AUXILIAR = F.CORR_AUXILIAR
        LEFT OUTER JOIN V_CON_CENTRO_COSTO H
            ON B.CORR_EMPRESA = H.CORR_EMPRESA
           AND B.CORR_CENTRO_COSTO = H.CORR_CENTRO_COSTO
        WHERE A.CORR_EMPRESA = @CORR_EMPRESA
          AND (A.FECHA_PARTIDA >= @FECHA_INICIAL OR @FECHA_INICIAL IS NULL)
          AND (A.FECHA_PARTIDA <= @FECHA_FINAL OR @FECHA_FINAL IS NULL)
          AND (A.ANIO_PERIODO = @ANIO_PERIODO OR @ANIO_PERIODO = 0)
          AND (A.MES_PERIODO = @MES_PERIODO OR @MES_PERIODO = 0)
          AND (A.CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA OR @CORR_CLASE_PARTIDA = 0)
          AND (A.CORR_PARTIDA = @CORR_PARTIDA OR @CORR_PARTIDA = 0)
          AND (A.CORR_PARTIDA >= @CORR_PARTIDA_INICIAL OR @CORR_PARTIDA_INICIAL = 0)
          AND (A.CORR_PARTIDA <= @CORR_PARTIDA_FINAL OR @CORR_PARTIDA_FINAL = 0)
        ORDER BY B.CORR_EMPRESA, B.ANIO_PERIODO, B.MES_PERIODO, B.CORR_CLASE_PARTIDA, B.CORR_PARTIDA, B.CORR_PARTIDA_DETA
    END

    SELECT A.CORR_EMPRESA
        ,A.NOMBRE_EMPRESA
        ,'' PERIODO
        ,A.LOGO_1 LOGO1
        ,A.LOGO_2 LOGO2
        ,'' TITULO_REPORTE
        ,'' NOMBRE_SISTEMA
        ,GETDATE() FECHA_IMPRESION
    FROM GEN_EMPRESA A
    WHERE A.CORR_EMPRESA = @CORR_EMPRESA
END
GO
