SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================================================
-- Procedimiento: dbo.PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO
-- Qué hace: entrega datos para PDF Formato extenso del Descriptor de puesto.
-- Cómo:
--   1) Result set 1: encabezado (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_IMPR).
--   2) Result set 2: encabezado/logos desde GEN_EMPRESA (GEN_PARAMETRO en Crystal).
--   3) Result set 3: funciones CLAVE detalle (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_FUNCIONES_IMPR).
--   4) Result set 4: funciones CLAVE + actividades
--      (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_FUNCIONES_ACTIVIDADES_IMPR).
--   5) Result set 5: responsabilidades (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RESPONSABILIDAD_CARGO_IMPR;
--      vista filtra APLICA_DESCRIPTOR EXTENSO/AMBOS).
--   6) Result set 6: relaciones laborales internas
--      (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RELACION_LABORAL_INTERNAS_IMPR).
--   7) Result set 7: relaciones laborales externas
--      (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RELACION_LABORAL_EXTERNAS_IMPR).
--   8) Result set 8: requerimientos organizacionales
--      (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_REQUERIMIENTO_ORGANIZACIONAL_IMPR).
-- Uso API: SC_DESCRIPTOR_PUESTO/getPDFFormatoExtenso → SGUEES-RPT SelectionHiring.
-- =============================================================================
CREATE OR ALTER PROCEDURE [dbo].[PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO]
(
	@CORR_EMPRESA INT,
	@CORR_DESCRIPTOR_PUESTO INT
)
AS
BEGIN
	SET NOCOUNT ON;

	-- Result set 1: encabezado del descriptor (1 fila).
	SELECT
		A.CORR_EMPRESA,
		A.CORR_DESCRIPTOR_PUESTO,
		A.CODIGO_DESCRIPTOR_PUESTO,
		A.FECHA_EMISION,
		A.FECHA_REVISION,
		A.OBJETIVO_PUESTO,
		A.NUM_PERSONAL_CARGO,
		A.CORR_PUESTO,
		A.NOMBRE_PUESTO,
		A.CORR_UNIDAD,
		A.NOMBRE_UNIDAD,
		A.CORR_PUESTO_REPORTA,
		A.NOMBRE_EMPLEADO_REPORTA,
		A.CORR_IMPACTO_ECONOMICO,
		A.DESCRIPCION_IMPACTO_ECONOMICO,
		A.RESPONSABLE,
		A.FORMATO,
		A.VERSION,
		A.CORR_ESTADO,
		A.NOMBRE_ESTADO,
		A.USUARIO_CREA,
		A.ESTACION_CREA,
		A.FECHA_CREA,
		A.USUARIO_ACTU,
		A.ESTACION_ACTU,
		A.FECHA_ACTU
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_IMPR A
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA
	  AND A.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO;

	-- Result set 2: logos (GEN_PARAMETRO en Crystal).
	SELECT
		A.CORR_EMPRESA,
		A.NOMBRE_EMPRESA,
		CAST('' AS VARCHAR(100)) AS PERIODO,
		A.LOGO_1 AS LOGO1,
		A.LOGO_2 AS LOGO2,
		CAST(N'Descriptor de Puesto - Formato extenso' AS VARCHAR(150)) AS TITULO_REPORTE,
		CAST('' AS VARCHAR(100)) AS NOMBRE_SISTEMA,
		GETDATE() AS FECHA_IMPRESION
	FROM dbo.GEN_EMPRESA A
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA;

	-- Result set 3: funciones CLAVE (1 fila por función; sin secundarias ni lista agregada).
	SELECT
		F.CORR_EMPRESA,
		F.CORR_DESCRIPTOR_PUESTO,
		F.CORR_FUNCION,
		F.NOMBRE_FUNCION,
		F.TIPO_FUNCION,
		F.NUM_ORDEN
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_FUNCIONES_IMPR F
	WHERE F.CORR_EMPRESA = @CORR_EMPRESA
	  AND F.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY F.NUM_ORDEN;

	-- Result set 4: funciones CLAVE + actividades (1 fila por actividad; Group Header en Crystal).
	SELECT
		FA.CORR_EMPRESA,
		FA.CORR_DESCRIPTOR_PUESTO,
		FA.CORR_FUNCION,
		FA.NOMBRE_FUNCION,
		FA.TIPO_FUNCION,
		FA.NUM_ORDEN_FUNCION,
		FA.CORR_ACTIVIDAD,
		FA.NOMBRE_ACTIVIDAD,
		FA.NUM_ORDEN_ACTIVIDAD
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_FUNCIONES_ACTIVIDADES_IMPR FA
	WHERE FA.CORR_EMPRESA = @CORR_EMPRESA
	  AND FA.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY FA.NUM_ORDEN_FUNCION, FA.NUM_ORDEN_ACTIVIDAD;

	-- Result set 5: responsabilidades del cargo (vista ya filtra EXTENSO/AMBOS).
	SELECT
		R.CORR_EMPRESA,
		R.CORR_DESCRIPTOR_PUESTO,
		R.CORR_RESPONSABILIDAD,
		R.NOMBRE_RESPONSABILIDAD,
		R.INFORMACION,
		R.APLICA_DESCRIPTOR
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RESPONSABILIDAD_CARGO_IMPR R
	WHERE R.CORR_EMPRESA = @CORR_EMPRESA
	  AND R.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY R.CORR_RESPONSABILIDAD;

	-- Result set 6: relaciones laborales INTERNAS (TIPO_RELACION = I).
	SELECT
		RI.CORR_EMPRESA,
		RI.CORR_DESCRIPTOR_PUESTO,
		RI.CORR_RELACION_LABORAL,
		RI.TIPO_RELACION,
		RI.PUESTO_AREA,
		RI.MOTIVO_RELACION
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RELACION_LABORAL_INTERNAS_IMPR RI
	WHERE RI.CORR_EMPRESA = @CORR_EMPRESA
	  AND RI.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY RI.CORR_RELACION_LABORAL;

	-- Result set 7: relaciones laborales EXTERNAS (TIPO_RELACION = E).
	SELECT
		RE.CORR_EMPRESA,
		RE.CORR_DESCRIPTOR_PUESTO,
		RE.CORR_RELACION_LABORAL,
		RE.TIPO_RELACION,
		RE.PUESTO_AREA,
		RE.MOTIVO_RELACION
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RELACION_LABORAL_EXTERNAS_IMPR RE
	WHERE RE.CORR_EMPRESA = @CORR_EMPRESA
	  AND RE.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY RE.CORR_RELACION_LABORAL;

	-- Result set 8: requerimientos organizacionales (1 fila por requerimiento).
	SELECT
		RO.CORR_EMPRESA,
		RO.CORR_DESCRIPTOR_PUESTO,
		RO.CORR_REQUERIMIENTO_ORGANIZACIONAL,
		RO.DESCRIPCION
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_REQUERIMIENTO_ORGANIZACIONAL_IMPR RO
	WHERE RO.CORR_EMPRESA = @CORR_EMPRESA
	  AND RO.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY RO.CORR_REQUERIMIENTO_ORGANIZACIONAL;
END
GO
