SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_COM_PROVEEDOR_USUARIO]
(
	@TIPO_CONSULTA int,
	@CORR_PROVEEDOR varchar(20)=NULL,
	@LOGIN_SISTEMA varchar(30)=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		SELECT * FROM V_COM_PROVEEDOR_USUARIO
		WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		SELECT * FROM V_COM_PROVEEDOR_USUARIO
		WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_COM_PROVEEDOR_USUARIO
		WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR
		AND LOGIN_SISTEMA=@LOGIN_SISTEMA
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT NOMBRE_USUARIO 
			FROM V_COM_PROVEEDOR_USUARIO
			WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR
			AND LOGIN_SISTEMA=@LOGIN_SISTEMA
		END
	END

END
GO
