SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================================================
-- Procedimiento: dbo.PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO
-- Qué hace: entrega datos para PDF Formato extenso del Descriptor de puesto.
-- Cómo:
--   1) Result set 1: encabezado (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_IMPR).
--   2) Result set 2: encabezado/logos desde GEN_EMPRESA (GEN_PARAMETRO en Crystal).
--   3) Result set 3: funciones CLAVE detalle (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_FUNCIONES_IMPR).
--   4) Result set 4: funciones CLAVE + actividades
--      (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_FUNCIONES_ACTIVIDADES_IMPR).
--   5) Result set 5: responsabilidades (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RESPONSABILIDAD_CARGO_IMPR;
--      vista filtra APLICA_DESCRIPTOR EXTENSO/AMBOS).
--   6) Result set 6: relaciones laborales internas
--      (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RELACION_LABORAL_INTERNAS_IMPR).
--   7) Result set 7: relaciones laborales externas
--      (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RELACION_LABORAL_EXTERNAS_IMPR).
--   8) Result set 8: requerimientos organizacionales
--      (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_REQUERIMIENTO_ORGANIZACIONAL_IMPR;
--      NUM_ITEM = '1.', '2.', ...).
--   9) Result set 9: riesgos del puesto
--      (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RIESGO_PUESTO_IMPR).
--  10) Result set 10: inducciones / entrenamiento
--      (V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_INDUCCION_IMPR).
--  11) Result set 11: perfil del puesto (V_SC_PERFIL_PUESTO_FORMATO_EXTENSO_IMPR).
--  12) Result set 12: educación del perfil
--      (V_SC_PERFIL_PUESTO_EDUCACION_FORMATO_EXTENSO_IMPR).
--  13) Result set 13: experiencia del perfil
--      (V_SC_PERFIL_PUESTO_EXPERIENCIA_FORMATO_EXTENSO_IMPR).
--  14) Result set 14: competencias técnicas del perfil
--      (V_SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS_FORMATO_EXTENSO_IMPR).
--  15) Result set 15: competencias conductuales del perfil
--      (V_SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES_FORMATO_EXTENSO_IMPR).
-- Uso API: SC_DESCRIPTOR_PUESTO/getPDFFormatoExtenso → SGUEES-RPT SelectionHiring.
-- =============================================================================
CREATE OR ALTER PROCEDURE [dbo].[PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO]
(
	@CORR_EMPRESA INT,
	@CORR_DESCRIPTOR_PUESTO INT
)
AS
BEGIN
	SET NOCOUNT ON;

	-- Result set 1: encabezado del descriptor (1 fila).
	SELECT
		A.CORR_EMPRESA,
		A.CORR_DESCRIPTOR_PUESTO,
		A.CODIGO_DESCRIPTOR_PUESTO,
		A.FECHA_EMISION,
		A.FECHA_REVISION,
		A.OBJETIVO_PUESTO,
		A.NUM_PERSONAL_CARGO,
		A.CORR_PUESTO,
		A.NOMBRE_PUESTO,
		A.CORR_UNIDAD,
		A.NOMBRE_UNIDAD,
		A.CORR_PUESTO_REPORTA,
		A.NOMBRE_EMPLEADO_REPORTA,
		A.CORR_IMPACTO_ECONOMICO,
		A.DESCRIPCION_IMPACTO_ECONOMICO,
		A.RESPONSABLE,
		A.FORMATO,
		A.VERSION,
		A.CORR_ESTADO,
		A.NOMBRE_ESTADO,
		A.USUARIO_CREA,
		A.ESTACION_CREA,
		A.FECHA_CREA,
		A.USUARIO_ACTU,
		A.ESTACION_ACTU,
		A.FECHA_ACTU
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_IMPR A
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA
	  AND A.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO;

	-- Result set 2: logos (GEN_PARAMETRO en Crystal).
	SELECT
		A.CORR_EMPRESA,
		A.NOMBRE_EMPRESA,
		CAST('' AS VARCHAR(100)) AS PERIODO,
		A.LOGO_1 AS LOGO1,
		A.LOGO_2 AS LOGO2,
		CAST(N'Descriptor de Puesto - Formato extenso' AS VARCHAR(150)) AS TITULO_REPORTE,
		CAST('' AS VARCHAR(100)) AS NOMBRE_SISTEMA,
		GETDATE() AS FECHA_IMPRESION
	FROM dbo.GEN_EMPRESA A
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA;

	-- Result set 3: funciones CLAVE (1 fila por función; sin secundarias ni lista agregada).
	SELECT
		F.CORR_EMPRESA,
		F.CORR_DESCRIPTOR_PUESTO,
		F.CORR_FUNCION,
		F.NOMBRE_FUNCION,
		F.TIPO_FUNCION,
		F.NUM_ORDEN
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_FUNCIONES_IMPR F
	WHERE F.CORR_EMPRESA = @CORR_EMPRESA
	  AND F.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY F.NUM_ORDEN;

	-- Result set 4: funciones CLAVE + actividades (1 fila por actividad; Group Header en Crystal).
	SELECT
		FA.CORR_EMPRESA,
		FA.CORR_DESCRIPTOR_PUESTO,
		FA.CORR_FUNCION,
		FA.NOMBRE_FUNCION,
		FA.TIPO_FUNCION,
		FA.NUM_ORDEN_FUNCION,
		FA.CORR_ACTIVIDAD,
		FA.NOMBRE_ACTIVIDAD,
		FA.NUM_ORDEN_ACTIVIDAD
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_FUNCIONES_ACTIVIDADES_IMPR FA
	WHERE FA.CORR_EMPRESA = @CORR_EMPRESA
	  AND FA.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY FA.NUM_ORDEN_FUNCION, FA.NUM_ORDEN_ACTIVIDAD;

	-- Result set 5: responsabilidades del cargo (vista ya filtra EXTENSO/AMBOS).
	SELECT
		R.CORR_EMPRESA,
		R.CORR_DESCRIPTOR_PUESTO,
		R.CORR_RESPONSABILIDAD,
		R.NOMBRE_RESPONSABILIDAD,
		R.INFORMACION,
		R.APLICA_DESCRIPTOR
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RESPONSABILIDAD_CARGO_IMPR R
	WHERE R.CORR_EMPRESA = @CORR_EMPRESA
	  AND R.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY R.CORR_RESPONSABILIDAD;

	-- Result set 6: relaciones laborales INTERNAS (TIPO_RELACION = I).
	SELECT
		RI.CORR_EMPRESA,
		RI.CORR_DESCRIPTOR_PUESTO,
		RI.CORR_RELACION_LABORAL,
		RI.TIPO_RELACION,
		RI.PUESTO_AREA,
		RI.MOTIVO_RELACION
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RELACION_LABORAL_INTERNAS_IMPR RI
	WHERE RI.CORR_EMPRESA = @CORR_EMPRESA
	  AND RI.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY RI.CORR_RELACION_LABORAL;

	-- Result set 7: relaciones laborales EXTERNAS (TIPO_RELACION = E).
	SELECT
		RE.CORR_EMPRESA,
		RE.CORR_DESCRIPTOR_PUESTO,
		RE.CORR_RELACION_LABORAL,
		RE.TIPO_RELACION,
		RE.PUESTO_AREA,
		RE.MOTIVO_RELACION
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RELACION_LABORAL_EXTERNAS_IMPR RE
	WHERE RE.CORR_EMPRESA = @CORR_EMPRESA
	  AND RE.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY RE.CORR_RELACION_LABORAL;

	-- Result set 8: requerimientos organizacionales (1 fila; NUM_ITEM = '1.', '2.', ...).
	SELECT
		RO.CORR_EMPRESA,
		RO.CORR_DESCRIPTOR_PUESTO,
		RO.CORR_REQUERIMIENTO_ORGANIZACIONAL,
		RO.NUM_ITEM,
		RO.DESCRIPCION
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_REQUERIMIENTO_ORGANIZACIONAL_IMPR RO
	WHERE RO.CORR_EMPRESA = @CORR_EMPRESA
	  AND RO.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY RO.CORR_REQUERIMIENTO_ORGANIZACIONAL;

	-- Result set 9: riesgos del puesto (1 fila por riesgo).
	SELECT
		RP.CORR_EMPRESA,
		RP.CORR_DESCRIPTOR_PUESTO,
		RP.CORR_RIESGO_PUESTO,
		RP.NOMBRE_RIESGO_PUESTO,
		RP.INFORMACION
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_RIESGO_PUESTO_IMPR RP
	WHERE RP.CORR_EMPRESA = @CORR_EMPRESA
	  AND RP.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY RP.CORR_RIESGO_PUESTO;

	-- Result set 10: inducciones / entrenamiento (1 fila por inducción).
	SELECT
		I.CORR_EMPRESA,
		I.CORR_DESCRIPTOR_PUESTO,
		I.CORR_INDUCCION,
		I.NOMBRE_INDUCCION,
		I.TIEMPO_INDUCCION
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_INDUCCION_IMPR I
	WHERE I.CORR_EMPRESA = @CORR_EMPRESA
	  AND I.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY I.CORR_INDUCCION;

	-- Result set 11: perfil del puesto (0 o 1 fila típica).
	SELECT
		P.CORR_EMPRESA,
		P.CORR_DESCRIPTOR_PUESTO,
		P.CORR_PERFIL_PUESTO,
		P.EDAD_MINIMA,
		P.EDAD_MAXIMA,
		P.SEXO,
		P.ESTADO_FAMILIAR,
		P.LICENCIA,
		P.LICENCIA_TEXTO,
		P.CORR_DISPONIBILIDAD_HORARIO,
		P.NOMBRE_DISPONIBILIDAD_HORARIO,
		P.CORR_TIPO_MODALIDAD,
		P.NOMBRE_MODALIDAD
	FROM dbo.V_SC_PERFIL_PUESTO_FORMATO_EXTENSO_IMPR P
	WHERE P.CORR_EMPRESA = @CORR_EMPRESA
	  AND P.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY P.CORR_PERFIL_PUESTO;

	-- Result set 12: educación del perfil (1 fila por requisito).
	SELECT
		E.CORR_EMPRESA,
		E.CORR_DESCRIPTOR_PUESTO,
		E.CORR_PERFIL_PUESTO,
		E.CORR_EDUCACION,
		E.REQUISITO,
		E.ESPECIFICACIONES,
		E.TIPO_REQUERIDO
	FROM dbo.V_SC_PERFIL_PUESTO_EDUCACION_FORMATO_EXTENSO_IMPR E
	WHERE E.CORR_EMPRESA = @CORR_EMPRESA
	  AND E.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY E.CORR_EDUCACION;

	-- Result set 13: experiencia del perfil (1 fila por requisito).
	SELECT
		X.CORR_EMPRESA,
		X.CORR_DESCRIPTOR_PUESTO,
		X.CORR_PERFIL_PUESTO,
		X.CORR_EXPERIENCIA,
		X.REQUISITO,
		X.TIPO_REQUERIDO
	FROM dbo.V_SC_PERFIL_PUESTO_EXPERIENCIA_FORMATO_EXTENSO_IMPR X
	WHERE X.CORR_EMPRESA = @CORR_EMPRESA
	  AND X.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY X.CORR_EXPERIENCIA;

	-- Result set 14: competencias técnicas del perfil (1 fila por competencia).
	SELECT
		CT.CORR_EMPRESA,
		CT.CORR_DESCRIPTOR_PUESTO,
		CT.CORR_PERFIL_PUESTO,
		CT.CORR_COMPETENCIAS_TECNICAS,
		CT.CODIGO_COMPETENCIAS_TECNICAS,
		CT.NOMBRE_COMPETENCIAS_TECNICAS,
		CT.DESCRIPCION,
		CT.NIVEL_DOMINIO
	FROM dbo.V_SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS_FORMATO_EXTENSO_IMPR CT
	WHERE CT.CORR_EMPRESA = @CORR_EMPRESA
	  AND CT.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY CT.CORR_COMPETENCIAS_TECNICAS;

	-- Result set 15: competencias conductuales del perfil (1 fila por competencia).
	SELECT
		CC.CORR_EMPRESA,
		CC.CORR_DESCRIPTOR_PUESTO,
		CC.CORR_PERFIL_PUESTO,
		CC.CORR_COMPETENCIAS_CONDUCTUALES,
		CC.CODIGO_TIPO_PUESTO,
		CC.NOMBRE_COMPETENCIAS_CONDUCTUALES,
		CC.DESCRIPCION
	FROM dbo.V_SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES_FORMATO_EXTENSO_IMPR CC
	WHERE CC.CORR_EMPRESA = @CORR_EMPRESA
	  AND CC.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY CC.CORR_COMPETENCIAS_CONDUCTUALES;
END
GO
