
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_CON_LIBRO_DIARIO]
( 
  @CORR_EMPRESA INT,
  @FECHA_INICIAL DATE=NULL,
  @FECHA_FINAL DATE=NULL,
  @ANIO_PERIODO INT=0,
  @MES_PERIODO INT=0,
  @CORR_CLASE_PARTIDA INT=0,
  @CORR_PARTIDA INT=0,
  @CORR_PARTIDA_INICIAL INT=0, 
  @CORR_PARTIDA_FINAL INT=0,
  @FOLIADO BIT=0,
  @NUMERO_FOLIO INT=0,
  @CORR_MONEDA INT=0
)
AS		
BEGIN
    
    SET NOCOUNT ON
    DECLARE @DESCRIPCION_MONEDA VARCHAR(150)
  
	SELECT @DESCRIPCION_MONEDA=A.DESCRIPCION_MONEDA
	FROM GEN_TIPO_MONEDA A
	AND A.CORR_MONEDA=@CORR_MONEDA

    SELECT A.CORR_EMPRESA
      ,A.ANIO_PERIODO
      ,A.MES_PERIODO
      ,A.CORR_CLASE_PARTIDA
      ,A.NOMBRE_CLASE_PARTIDA
      ,A.NOMBRE_CORTO_CLASE
      ,A.CORR_PARTIDA
      ,A.FECHA_PARTIDA
      ,A.NUMERO_DOCUMENTO
      ,A.NOMBRE_PARTIDA
      ,A.ESTADO_PARTIDA
      ,A.NOMBRE_ESTADO_PARTIDA
      ,A.USUARIO_CREA
      ,A.FECHA_CREA
      ,A.ESTACION_CREA
      ,A.USUARIO_ACTU
      ,A.FECHA_ACTU
      ,A.ESTACION_ACTU
      ,A.CLASE_PARTIDA
      ,A.NOMBRE_CLASE_PARTIDA2
      ,B.CORR_PARTIDA_DETA
      ,B.CUENTA_CONTABLE
      ,B.NOMBRE_CUENTA
      ,B.CORR_CENTRO_COSTO
      ,B.NOMBRE_CENTRO
      ,CASE WHEN J.CORR_MONEDA=@CORR_MONEDA THEN B.MONTO_CARGO ELSE B.MONTO_CARGO_FORANEA END MONTO_CARGO
      ,CASE WHEN J.CORR_MONEDA=@CORR_MONEDA THEN B.MONTO_ABONO ELSE B.MONTO_ABONO_FORANEA END MONTO_ABONO
      ,CASE WHEN ISNULL(C.NUMERO_DOCUMENTO,'')<>'' THEN LTRIM(RTRIM(LTRIM(RTRIM(ISNULL(C.TIPO_DOCUMENTO,'')))+' '+CONVERT(VARCHAR,ISNULL(C.NUMERO_DOCUMENTO,0))))+' ' ELSE '' END+B.NOMBRE_TRAN NOMBRE_TRAN     
      ,C.NUMERO_DOCUMENTO NUMERO_DOCUMENTO_DETA
      ,B.CORR_AUXILIAR
      ,F.CORR_AUXILIAR_REPLICADO
      ,H.CORR_CENTRO_COSTO_REPLICADO
      ,@DESCRIPCION_MONEDA DESCRIPCION_MONEDA
      ,CONVERT(BIT,ISNULL(K.MOSTRAR_FECHA_IMPRESION,0)) MOSTRAR_FECHA_IMPRESION
      ,@FOLIADO FOLIADO
      ,@NUMERO_FOLIO NUMERO_FOLIO          
	FROM V_CON_PARTIDA A
	INNER JOIN V_CON_PARTIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
	LEFT OUTER JOIN V_CON_PARTIDA_DETA_DOC_SUM C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.ANIO_PERIODO=C.ANIO_PERIODO AND B.MES_PERIODO=C.MES_PERIODO AND B.CORR_CLASE_PARTIDA=C.CORR_CLASE_PARTIDA AND B.CORR_PARTIDA=C.CORR_PARTIDA AND B.CORR_PARTIDA_DETA=C.CORR_PARTIDA_DETA
	LEFT OUTER JOIN V_CON_CATALOGO_CUENTA_AUXI F ON A.CORR_EMPRESA=F.CORR_EMPRESA AND B.CUENTA_CONTABLE=F.CUENTA_CONTABLE AND B.CORR_AUXILIAR=F.CORR_AUXILIAR
	LEFT OUTER JOIN V_CON_CENTRO_COSTO H ON B.CORR_EMPRESA=H.CORR_EMPRESA AND B.CORR_CENTRO_COSTO=H.CORR_CENTRO_COSTO
	INNER JOIN GEN_EMPRESA J ON A.CORR_EMPRESA=J.CORR_EMPRESA	
	INNER JOIN CON_PARAMETRO K ON A.CORR_EMPRESA=K.CORR_EMPRESA	
    WHERE A.CORR_EMPRESA=@CORR_EMPRESA
    AND (FECHA_PARTIDA>=@FECHA_INICIAL OR @FECHA_INICIAL IS NULL)
    AND (FECHA_PARTIDA<=@FECHA_FINAL OR @FECHA_FINAL IS NULL)
    AND (A.ANIO_PERIODO=@ANIO_PERIODO OR @ANIO_PERIODO=0)
    AND (A.MES_PERIODO=@MES_PERIODO OR @MES_PERIODO=0)
    AND (A.CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA OR @CORR_CLASE_PARTIDA=0)
    AND (A.CORR_PARTIDA=@CORR_PARTIDA OR @CORR_PARTIDA=0)
    AND (A.CORR_PARTIDA>=@CORR_PARTIDA_INICIAL OR @CORR_PARTIDA_INICIAL=0)
    AND (A.CORR_PARTIDA<=@CORR_PARTIDA_FINAL OR @CORR_PARTIDA_FINAL=0)
	AND (CASE WHEN J.CORR_MONEDA=@CORR_MONEDA THEN B.MONTO_CARGO ELSE B.MONTO_CARGO_FORANEA END<>0
		OR CASE WHEN J.CORR_MONEDA=@CORR_MONEDA THEN B.MONTO_ABONO ELSE B.MONTO_ABONO_FORANEA END<>0)
    ORDER BY CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,CORR_CLASE_PARTIDA,CORR_PARTIDA, CASE WHEN B.MONTO_CARGO>0 THEN 0 WHEN B.MONTO_ABONO>0 THEN 1 END, CORR_PARTIDA_DETA
		
	SELECT A.CORR_EMPRESA
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO
