
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_CON_GASTOS_PRESUPUESTO]
( 
  @CORR_EMPRESA INT,
  @ANIO_PERIODO INT,
  @MES_PERIODO INT,
  @CUENTA_DEPARTAMENTO VARCHAR(30)='',
  @CONSOLIDADO BIT
)
AS
	DECLARE @NOMBRE_CUENTA_DEPARTAMENTO VARCHAR(150)
BEGIN
	
    SELECT @NOMBRE_CUENTA_DEPARTAMENTO=NOMBRE_CUENTA
    FROM CON_CATALOGO_CUENTA
    WHERE CORR_EMPRESA=@CORR_EMPRESA
    AND CUENTA_CONTABLE=@CUENTA_DEPARTAMENTO
    
    SELECT @NOMBRE_CUENTA_DEPARTAMENTO=ISNULL(@NOMBRE_CUENTA_DEPARTAMENTO,'')
    
    SET NOCOUNT ON  
		
		SELECT QRY.CORR_EMPRESA
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE E.CUENTA_CONTABLE+' '+E.NOMBRE_CUENTA END CUENTA_MAYOR_2
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE F.CUENTA_CONTABLE+' '+F.NOMBRE_CUENTA END CUENTA_MAYOR_3
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE G.CUENTA_CONTABLE+' '+G.NOMBRE_CUENTA END CUENTA_MAYOR_4
		,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO+' '+@NOMBRE_CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE+' '+D.NOMBRE_CUENTA END CUENTA_DEPARTAMENTO
		,REPLACE(QRY.CUENTA_CONTABLE,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE END,'')+' '+C.NOMBRE_CUENTA CUENTA_CONTABLE
		,QRY.ANIO_PERIODO
		,@MES_PERIODO MES_PERIODO
		,UPPER(dbo.NOMBRE_MES(@MES_PERIODO)) NOMBRE_MES
		,SUM(QRY.TOTAL_MES) TOTAL_MES
		,SUM(QRY.TOTAL_ACUMULADO) TOTAL_ACUMULADO
		,SUM(ISNULL(CASE @MES_PERIODO 
					WHEN 1 THEN QRY.MONTO_PRESUPUESTO_1 
					WHEN 2 THEN QRY.MONTO_PRESUPUESTO_2 
					WHEN 3 THEN QRY.MONTO_PRESUPUESTO_3 
					WHEN 4 THEN QRY.MONTO_PRESUPUESTO_4 
					WHEN 5 THEN QRY.MONTO_PRESUPUESTO_5 
					WHEN 6 THEN QRY.MONTO_PRESUPUESTO_6 
					WHEN 7 THEN QRY.MONTO_PRESUPUESTO_7 
					WHEN 8 THEN QRY.MONTO_PRESUPUESTO_8 
					WHEN 9 THEN QRY.MONTO_PRESUPUESTO_9 
					WHEN 10 THEN QRY.MONTO_PRESUPUESTO_10 
					WHEN 11 THEN QRY.MONTO_PRESUPUESTO_11 
					WHEN 12 THEN QRY.MONTO_PRESUPUESTO_12 
					ELSE 0 END,0)) TOTAL_PRESUPUESTO_MES
		,SUM(ISNULL(CASE WHEN @MES_PERIODO>=1 THEN QRY.MONTO_PRESUPUESTO_1 ELSE 0 END +
					CASE WHEN @MES_PERIODO>=2 THEN QRY.MONTO_PRESUPUESTO_2 ELSE 0 END +
					CASE WHEN @MES_PERIODO>=3 THEN QRY.MONTO_PRESUPUESTO_3 ELSE 0 END +
					CASE WHEN @MES_PERIODO>=4 THEN QRY.MONTO_PRESUPUESTO_4 ELSE 0 END +
					CASE WHEN @MES_PERIODO>=5 THEN QRY.MONTO_PRESUPUESTO_5 ELSE 0 END +
					CASE WHEN @MES_PERIODO>=6 THEN QRY.MONTO_PRESUPUESTO_6 ELSE 0 END +
					CASE WHEN @MES_PERIODO>=7 THEN QRY.MONTO_PRESUPUESTO_7 ELSE 0 END +
					CASE WHEN @MES_PERIODO>=8 THEN QRY.MONTO_PRESUPUESTO_8 ELSE 0 END +
					CASE WHEN @MES_PERIODO>=9 THEN QRY.MONTO_PRESUPUESTO_9 ELSE 0 END +
					CASE WHEN @MES_PERIODO>=10 THEN QRY.MONTO_PRESUPUESTO_10 ELSE 0 END +
					CASE WHEN @MES_PERIODO>=11 THEN QRY.MONTO_PRESUPUESTO_11 ELSE 0 END +
					CASE WHEN @MES_PERIODO>=12 THEN QRY.MONTO_PRESUPUESTO_12 ELSE 0 END 
			,0)) TOTAL_PRESUPUESTO_ACUMULADO
		
	FROM (
			SELECT ISNULL(AA.CORR_EMPRESA,BB.CORR_EMPRESA) CORR_EMPRESA
				,ISNULL(AA.CUENTA_CONTABLE,BB.CUENTA_CONTABLE) CUENTA_CONTABLE
				,ISNULL(AA.CUENTA_DEPARTAMENTO,BB.CUENTA_MAYOR) CUENTA_DEPARTAMENTO
				,ISNULL(AA.ANIO_PERIODO,BB.ANIO_PERIODO) ANIO_PERIODO
				,ISNULL(AA.TOTAL_MES,0) TOTAL_MES
				,ISNULL(AA.TOTAL_ACUMULADO,0) TOTAL_ACUMULADO
				,ISNULL(BB.MONTO_PRESUPUESTO_1,0) MONTO_PRESUPUESTO_1
				,ISNULL(BB.MONTO_PRESUPUESTO_2,0) MONTO_PRESUPUESTO_2
				,ISNULL(BB.MONTO_PRESUPUESTO_3,0) MONTO_PRESUPUESTO_3
				,ISNULL(BB.MONTO_PRESUPUESTO_4,0) MONTO_PRESUPUESTO_4
				,ISNULL(BB.MONTO_PRESUPUESTO_5,0) MONTO_PRESUPUESTO_5
				,ISNULL(BB.MONTO_PRESUPUESTO_6,0) MONTO_PRESUPUESTO_6
				,ISNULL(BB.MONTO_PRESUPUESTO_7,0) MONTO_PRESUPUESTO_7
				,ISNULL(BB.MONTO_PRESUPUESTO_8,0) MONTO_PRESUPUESTO_8
				,ISNULL(BB.MONTO_PRESUPUESTO_9,0) MONTO_PRESUPUESTO_9
				,ISNULL(BB.MONTO_PRESUPUESTO_10,0) MONTO_PRESUPUESTO_10
				,ISNULL(BB.MONTO_PRESUPUESTO_11,0) MONTO_PRESUPUESTO_11
				,ISNULL(BB.MONTO_PRESUPUESTO_12,0) MONTO_PRESUPUESTO_12
			FROM
			(
				SELECT A.CORR_EMPRESA
				,C.CUENTA_CONTABLE
				,C.CUENTA_MAYOR CUENTA_DEPARTAMENTO
				,A.ANIO_PERIODO			
				,SUM(CASE WHEN A.MES_PERIODO=@MES_PERIODO THEN B.MONTO_CARGO-B.MONTO_ABONO ELSE 0 END) TOTAL_MES
				,SUM(B.MONTO_CARGO-B.MONTO_ABONO) TOTAL_ACUMULADO
				FROM CON_PARTIDA A
				INNER JOIN CON_PARTIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
				INNER JOIN CON_CATALOGO_CUENTA C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CUENTA_CONTABLE=C.CUENTA_CONTABLE
				WHERE A.CORR_EMPRESA=@CORR_EMPRESA				
				AND A.ANIO_PERIODO=@ANIO_PERIODO
				AND A.MES_PERIODO<=@MES_PERIODO
				AND A.ESTADO_PARTIDA='AP'
				AND C.CLASE_RUBRO='GA'				
				AND (B.CUENTA_CONTABLE LIKE @CUENTA_DEPARTAMENTO+'%' OR ISNULL(@CUENTA_DEPARTAMENTO,'')='')
				GROUP BY A.CORR_EMPRESA
				,C.CUENTA_CONTABLE
				,C.CUENTA_MAYOR
				,A.ANIO_PERIODO
			) AA
			FULL JOIN V_CON_CATALOGO_PRESUPUESTO BB ON AA.CORR_EMPRESA=BB.CORR_EMPRESA AND AA.CUENTA_CONTABLE=BB.CUENTA_CONTABLE 
				AND BB.ANIO_PERIODO=@ANIO_PERIODO
		) AS QRY
	INNER JOIN CON_CATALOGO_CUENTA C ON QRY.CORR_EMPRESA=C.CORR_EMPRESA AND QRY.CUENTA_CONTABLE=C.CUENTA_CONTABLE
	INNER JOIN CON_CATALOGO_CUENTA D ON QRY.CORR_EMPRESA=D.CORR_EMPRESA AND QRY.CUENTA_DEPARTAMENTO=D.CUENTA_CONTABLE	
	LEFT OUTER JOIN CON_CATALOGO_CUENTA E ON D.CORR_EMPRESA=E.CORR_EMPRESA AND D.CUENTA_MAYOR=E.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA F ON E.CORR_EMPRESA=F.CORR_EMPRESA AND E.CUENTA_MAYOR=F.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA G ON F.CORR_EMPRESA=G.CORR_EMPRESA AND F.CUENTA_MAYOR=G.CUENTA_CONTABLE	
	--LEFT OUTER JOIN CON_CATALOGO_PRESUPUESTO P ON QRY.CORR_EMPRESA=P.CORR_EMPRESA AND QRY.CUENTA_CONTABLE=P.CUENTA_CONTABLE AND P.ANIO_PERIODO=@ANIO_PERIODO	
	WHERE QRY.CORR_EMPRESA=@CORR_EMPRESA
	AND QRY.ANIO_PERIODO=@ANIO_PERIODO
	AND (QRY.CUENTA_CONTABLE LIKE @CUENTA_DEPARTAMENTO+'%' OR ISNULL(@CUENTA_DEPARTAMENTO,'')='')
    GROUP BY QRY.CORR_EMPRESA
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE E.CUENTA_CONTABLE+' '+E.NOMBRE_CUENTA END
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE F.CUENTA_CONTABLE+' '+F.NOMBRE_CUENTA END
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE G.CUENTA_CONTABLE+' '+G.NOMBRE_CUENTA END
		,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO+' '+@NOMBRE_CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE+' '+D.NOMBRE_CUENTA END
		,REPLACE(QRY.CUENTA_CONTABLE,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE END,'')+' '+C.NOMBRE_CUENTA
		,C.NOMBRE_CUENTA
		,QRY.ANIO_PERIODO
	ORDER BY REPLACE(QRY.CUENTA_CONTABLE,CASE WHEN @CONSOLIDADO=1 THEN @CUENTA_DEPARTAMENTO ELSE D.CUENTA_CONTABLE END,'')+' '+C.NOMBRE_CUENTA
	
	SELECT A.CORR_EMPRESA
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO
