SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_SEG_OPCION_SISTEMA]
(
	@TIPO_ACTUALIZA INT,
	@CODIGO_OPCION varchar(30) OUTPUT,
	@NOMBRE_OPCION varchar(100),
	@URL_OPCION VARCHAR(20),
	@IMAGEN_OPCION VARCHAR(20),
	@INDI_REFR_DATOS varchar(1) = NULL,
	@INDI_NECE_EMPR varchar(1) = NULL,
	@INDI_NECE_PERI_CONT varchar(1) = NULL,
	@INDI_VALI_PERI_CONT varchar(1) = NULL,
	@USUARIO_CREA varchar(30),
	@FECHA_CREA datetime,
	@ESTACION_CREA varchar(30),
	@USUARIO_ACTU varchar(30),
	@FECHA_ACTU datetime,
	@ESTACION_ACTU varchar(30),	
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	DECLARE @CODIGO_SUITE VARCHAR(30) ='AdminBA'
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN			
			INSERT INTO SEG_OPCION_SISTEMA
			(CODIGO_OPCION,NOMBRE_OPCION,URL_OPCION,IMAGEN_OPCION,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU)
			VALUES
			(@CODIGO_OPCION,@NOMBRE_OPCION,@URL_OPCION,@IMAGEN_OPCION,@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU)

			EXECUTE PRAL_MTTO_SEG_OPCION_SISTEMA_SUITE 
				@TIPO_ACTUALIZA,	
			    @CODIGO_OPCION,                               
			    @CODIGO_SUITE OUTPUT,              
			    @SYS_LOGIN_USUARIO,                           
			    @SYS_ESTACION,                                
			    @SYS_FILAS_AFECTADAS OUTPUT,
			    @SYS_NUMERO_ERROR OUTPUT,      
			    @SYS_MENSAJE_ERROR OUTPUT     
			
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE SEG_OPCION_SISTEMA SET
			NOMBRE_OPCION=@NOMBRE_OPCION,
			URL_OPCION=@URL_OPCION,
			IMAGEN_OPCION=@IMAGEN_OPCION,
			USUARIO_ACTU=@USUARIO_ACTU,
			FECHA_ACTU=@FECHA_ACTU,
			ESTACION_ACTU=@ESTACION_ACTU
			WHERE CODIGO_OPCION=@CODIGO_OPCION
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM SEG_OPCION_SISTEMA_SUITE
			WHERE CODIGO_OPCION=@CODIGO_OPCION

			DELETE FROM SEG_OPCION_SISTEMA
			WHERE CODIGO_OPCION=@CODIGO_OPCION
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
