SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_DATA_SEG_MENU_SISTEMA]
(
	@TIPO_CONSULTA int,
	@CODIGO_MENU varchar(10)=NULL,
	@LOGIN_SISTEMA varchar(30) = NULL,
	@CODIGO_SUITE varchar(30) = NULL,
	@CODIGO_SISTEMA varchar(30) = NULL,
	@OPCION_CONSULTA int=0,
	@IDIOMA varchar(30) = NULL
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN		
		SELECT * FROM V_SEG_MENU_SISTEMA
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN		
		SELECT * FROM V_SEG_MENU_SISTEMA		
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_SEG_MENU_SISTEMA	
		WHERE CODIGO_MENU=@CODIGO_MENU
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT CODIGO_MENU FROM V_SEG_MENU_SISTEMA	
		    WHERE CODIGO_MENU=@CODIGO_MENU
		END
	END

END
GO
