SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_BAN_CONCILIACION_FORZADA]
	@CORR_EMPRESA int,
	@CORR_CUENTA_BANCO int,
	@CORR_CONCILIACION int,
	@CORR_CONCILIACION_DETA int OUTPUT,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_CLASE_PARTIDA int,
	@CORR_PARTIDA int,
	@CORR_PARTIDA_DETA int,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
AS
	DECLARE @TEMP2 TABLE ( --Almacena los registros de la consulta de transacciones pendientes de conciliar por parte de contabilidad 
		CORR_EMPRESA int, 
		ANIO_PERIODO int,
		MES_PERIODO int,
		CORR_CLASE_PARTIDA int,
		CORR_PARTIDA int,
		NUMERO_DOCUMENTO varchar(25),
		FECHA_PARTIDA date,
		NOMBRE_CLASE_PARTIDA varchar(60),
		ESTADO_PARTIDA varchar(2),
		CORR_PARTIDA_DETA int,
		CUENTA_CONTABLE varchar(30),
		MONTO_CARGO decimal(12,2),
		MONTO_ABONO decimal(12,2),
		MONTO_CARGO_FORANEA decimal(12,2),
		MONTO_ABONO_FORANEA decimal(12,2),
		NOMBRE_TRAN varchar(1255),
		ESTA_CONCILIA bit	
	)
BEGIN
	SET NOCOUNT ON
	
	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0
	
	BEGIN TRY
	
		DECLARE @ESTADO_CONCILIACION VARCHAR(2)
		
		SELECT @ESTADO_CONCILIACION=ESTADO_CONCILIACION
		FROM BAN_CONCILIA_BANCARIA 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
		AND CORR_CONCILIACION=@CORR_CONCILIACION 
		
		IF @ESTADO_CONCILIACION IS NULL
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe esta conciliacion.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END ELSE
		IF @ESTADO_CONCILIACION <> 'DI'
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Esta conciliacion ya esta aplicada o anulada y no permite modificaciones.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END
		
		--Se verifica que no este conciliada que no tenga vinculacion con alguna partida contable
		IF NOT EXISTS ( SELECT 1 FROM BAN_CONCILIA_BANCARIA_DETA 
					WHERE CORR_EMPRESA=@CORR_EMPRESA
					AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
					AND CORR_CONCILIACION=@CORR_CONCILIACION 
					AND CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA
					AND (ANIO_PERIODO IS NULL
						OR MES_PERIODO IS NULL
						OR CORR_CLASE_PARTIDA IS NULL
						OR CORR_PARTIDA IS NULL
						OR CORR_PARTIDA_DETA IS NULL )
					)
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='Este movimiento no esta disponible para conciliacion.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		--Se consultan los registros de los detalles de partidas contables que no se han conciliado y que son correspondientes a esta cuenta bancaria
		INSERT INTO @TEMP2 
		EXEC PRAL_DATA_BAN_CONCILIA_BANCARIA_PENDIENTE 1, @CORR_EMPRESA, @CORR_CUENTA_BANCO, @CORR_CONCILIACION
			
		--Se verifica que esta partida_deta este entre las partidas pendientes de conciliar
		IF NOT EXISTS ( SELECT 1 FROM @TEMP2 
					WHERE CORR_EMPRESA=@CORR_EMPRESA 
					AND ANIO_PERIODO=@ANIO_PERIODO 
					AND MES_PERIODO=@MES_PERIODO 
					AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA 
					AND CORR_PARTIDA=@CORR_PARTIDA 
					AND CORR_PARTIDA_DETA=@CORR_PARTIDA_DETA
					AND ISNULL(ESTA_CONCILIA,0)=0)
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='Esta partida no puede utilizarse para esta conciliacion.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		--Se crea la vinculacion
		UPDATE BAN_CONCILIA_BANCARIA_DETA SET
		ANIO_PERIODO=@ANIO_PERIODO,
		MES_PERIODO=@MES_PERIODO,
		CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA,
		CORR_PARTIDA=@CORR_PARTIDA,
		CORR_PARTIDA_DETA=@CORR_PARTIDA_DETA 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
		AND CORR_CONCILIACION=@CORR_CONCILIACION 
		AND CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA 

		--Se borra el concilia_movi correpondiente al concilia_deta, ya que ahora estan conciliados
		DELETE FROM BAN_CONCILIA_BANCARIA_MOVI 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
		AND CORR_CONCILIACION=@CORR_CONCILIACION 
		AND CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA 
				
		--Se marca como que ya esta conciliada
		UPDATE CON_PARTIDA_DETA SET
		ESTA_CONCILIA=1
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND ANIO_PERIODO=@ANIO_PERIODO 
		AND MES_PERIODO=@MES_PERIODO 
		AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA 
		AND CORR_PARTIDA=@CORR_PARTIDA 
		AND CORR_PARTIDA_DETA=@CORR_PARTIDA_DETA 
				
		--Se borra el concilia_movi correpondiente al partida_deta, ya que ahora estan conciliados
		DELETE FROM BAN_CONCILIA_BANCARIA_MOVI 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
		AND CORR_CONCILIACION=@CORR_CONCILIACION 
		AND ANIO_PERIODO=@ANIO_PERIODO 
		AND MES_PERIODO=@MES_PERIODO 
		AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA 
		AND CORR_PARTIDA=@CORR_PARTIDA 
		AND CORR_PARTIDA_DETA=@CORR_PARTIDA_DETA 
		
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT>0
	  BEGIN
		ROLLBACK TRANSACTION
      END
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO

