SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE]
(
	@TIPO_ACTUALIZA INT	@CORR_EMPRESA int,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_TIPO_MOVIMIENTO int,
	@CORR_DOCUMENTO int OUTPUT,
	@CORR_CUENTA_BANCO int = NULL,
	@NUMERO_DOCUMENTO bigint = NULL,
	@FECHA_EMISION date = NULL,
	@NOMBRE_PARTIDA varchar(1000) = '',
	@CORR_PROVEEDOR int = null,
	@CORR_CLIENTE int = null,
	@CORR_EMPLEADO int = null,
	@NOMBRE_BENEFICIARIO varchar(255) = '',
	@MONTO_DOCUMENTO decimal(18,2) = 0,
	@ESTADO_DOCUMENTO varchar(2) = 'DI',
	@SOLICITADO_POR varchar(30) = '',
	@FECHA_SOLICITADO date = null,
	@FECHA_APLICADO date = null,
	@CANTIDAD_LETRAS varchar(255) = NULL,
	@USUARIO_CREA varchar(30),
	@FECHA_CREA datetime,
	@ESTACION_CREA varchar(50),
	@USUARIO_ACTU varchar(30),
	@FECHA_ACTU datetime,
	@ESTACION_ACTU varchar(50),
	@CORR_TIPO_CHEQUE int = NULL,
	@ANIO_PERIODO_CHEQUE int = NULL,
	@MES_PERIODO_CHEQUE int = NULL,
	@CORR_TIPO_MOVIMIENTO_CHEQUE int = NULL,
	@CORR_DOCUMENTO_CHEQUE int = NULL,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output,
	@GENERA_DETALLE BIT = 1,
	@CORR_MONEDA int=null,
	@FACTOR_CAMBIO decimal(16,6)=1,
	@OPERADOR varchar(2)='*'
)
AS
	DECLARE @MONTO_CARGO DECIMAL(12,2), @MONTO_ABONO DECIMAL(12,2),@CUENTA_CONTABLE_BANCO VARCHAR(30)
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		DECLARE @CLASE_TIPO_CHEQUE VARCHAR(3)
		IF @TIPO_ACTUALIZA IN (1,2)
		BEGIN
		    --Verificando el periodo contable
		    IF NOT EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE 
		                  WHERE CORR_EMPRESA=@CORR_EMPRESA
			              AND ANIO_PERIODO=@ANIO_PERIODO
			              AND MES_PERIODO=@MES_PERIODO)
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe el periodo contable seleccionado',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
			IF NOT EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
		                  WHERE CORR_EMPRESA=@CORR_EMPRESA
			              AND ANIO_PERIODO=@ANIO_PERIODO
			              AND MES_PERIODO=@MES_PERIODO
			              AND ESTADO_PERIODO_BAN='AB')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='El periodo contable NO esta abierto. No se permite ingresar o modificar documentos',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END							
			
			IF NOT EXISTS ( SELECT 1 FROM BAN_TIPO_MOVI_BANCARIO
							WHERE CORR_EMPRESA=@CORR_EMPRESA
							AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No ha seleccionado correctamente el tipo de movimiento bancario.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
			--Verificando la cuenta bancaria
			IF (@CORR_CUENTA_BANCO IS NULL
			   OR NOT EXISTS(SELECT 1 FROM BAN_CUENTA_BANCARIA
			                 WHERE CORR_EMPRESA=@CORR_EMPRESA
			                 AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO))
			BEGIN
				SELECT @CORR_CUENTA_BANCO=NULL, @GENERA_DETALLE=0
				--SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe la cuenta bancaria seleccionada',@SYS_FILAS_AFECTADAS=0
				--GOTO FINA
			END
			
			--Verificando la descripción de la partida contable
			IF LTRIM(RTRIM(ISNULL(@NOMBRE_PARTIDA,'')))=''
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Debe especificar un concepto para el documento a emitir',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
			--Verificando el monto del documento
			IF ISNULL(@MONTO_DOCUMENTO,0)<0
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='El monto del documento no puede ser menor que cero',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
			SELECT @ANIO_PERIODO_CHEQUE=NULL, @MES_PERIODO_CHEQUE=NULL, @CORR_TIPO_MOVIMIENTO_CHEQUE=NULL, @CORR_DOCUMENTO_CHEQUE=NULL
			SELECT @CANTIDAD_LETRAS=ISNULL(dbo.FN_NUMEROS_A_LETRAS(@MONTO_DOCUMENTO,0),'')
			
			IF NOT EXISTS ( SELECT 1 FROM BAN_TIPO_CHEQUE 
							WHERE CORR_EMPRESA=@CORR_EMPRESA
							AND CORR_TIPO_CHEQUE=@CORR_TIPO_CHEQUE )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No ha seleccionado correctamente el tipo de cheque.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
			SELECT @CLASE_TIPO_CHEQUE=ISNULL(CLASE_TIPO_CHEQUE,'OT')
			FROM BAN_TIPO_CHEQUE 
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_TIPO_CHEQUE=@CORR_TIPO_CHEQUE
				
			IF NOT EXISTS ( SELECT 1 FROM GEN_PROVEEDOR 
							WHERE CORR_EMPRESA=@CORR_EMPRESA 
							AND CORR_PROVEEDOR=@CORR_PROVEEDOR) AND @CLASE_TIPO_CHEQUE IN ('PR','OT')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No ha seleccionado correctamente el proveedor.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
				
			IF NOT EXISTS ( SELECT 1 FROM GEN_EMPLEADO 
							WHERE CORR_EMPRESA=@CORR_EMPRESA 
							AND CORR_EMPLEADO=@CORR_EMPLEADO ) AND @CLASE_TIPO_CHEQUE IN ('EM')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No ha seleccionado correctamente el empleado.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
				
			IF NOT EXISTS ( SELECT 1 FROM GEN_CLIENTE 
							WHERE CORR_EMPRESA=@CORR_EMPRESA 
							AND CORR_CLIENTE=@CORR_CLIENTE ) AND @CLASE_TIPO_CHEQUE IN ('CL')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No ha seleccionado correctamente el cliente.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END			
			
			--IF NOT EXISTS ( SELECT 1 FROM BAN_CUENTA_BANCARIA
			--			WHERE CORR_SUSCRIPCION=@CORR_SUSCRIPCION 
			--			AND CORR_CONFI_PAIS=@CORR_CONFI_PAIS 
			--			AND CORR_EMPRESA=@CORR_EMPRESA
			--			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO)
			--BEGIN
			--	SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No ha seleccionado correctamente la cuenta bancaria.',@SYS_FILAS_AFECTADAS=0
			--	GOTO FINA
			--END
		END
		
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @CORR_DOCUMENTO=ISNULL(MAX(CORR_DOCUMENTO),0)+1, @ESTADO_DOCUMENTO='DI'
			FROM BAN_SOLI_CHEQUE
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
			
			INSERT INTO BAN_SOLI_CHEQUE
			(CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,CORR_TIPO_MOVIMIENTO,CORR_DOCUMENTO,CORR_CUENTA_BANCO,NUMERO_DOCUMENTO,FECHA_EMISION,NOMBRE_PARTIDA,CORR_PROVEEDOR,NOMBRE_BENEFICIARIO,MONTO_DOCUMENTO,ESTADO_DOCUMENTO,SOLICITADO_POR,FECHA_SOLICITADO,FECHA_APLICADO,CANTIDAD_LETRAS,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU,CORR_TIPO_CHEQUE,ANIO_PERIODO_CHEQUE,MES_PERIODO_CHEQUE,CORR_TIPO_MOVIMIENTO_CHEQUE,CORR_DOCUMENTO_CHEQUE,CORR_MONEDA,FACTOR_CAMBIO,OPERADOR)
			VALUES
			(@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_EMPRESA,@ANIO_PERIODO,@MES_PERIODO,@CORR_TIPO_MOVIMIENTO,@CORR_DOCUMENTO,@CORR_CUENTA_BANCO,@NUMERO_DOCUMENTO,@FECHA_EMISION,@NOMBRE_PARTIDA,@CORR_PROVEEDOR,@NOMBRE_BENEFICIARIO,@MONTO_DOCUMENTO,@ESTADO_DOCUMENTO,@SOLICITADO_POR,@FECHA_SOLICITADO,@FECHA_APLICADO,@CANTIDAD_LETRAS,@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU,@CORR_TIPO_CHEQUE,@ANIO_PERIODO_CHEQUE,@MES_PERIODO_CHEQUE,@CORR_TIPO_MOVIMIENTO_CHEQUE,@CORR_DOCUMENTO_CHEQUE,@CORR_MONEDA,@FACTOR_CAMBIO,@OPERADOR)
			
			IF ISNULL(@GENERA_DETALLE,1)=1
			BEGIN
				EXEC PRAL_GENE_BAN_SOLI_CHEQUE_DETA
				@CORR_SUSCRIPCION,
				@CORR_CONFI_PAIS,
				@CORR_EMPRESA,
				@ANIO_PERIODO,
				@MES_PERIODO,
				@CORR_TIPO_MOVIMIENTO,
				@CORR_DOCUMENTO,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@SYS_FILAS_AFECTADAS output,
				@SYS_NUMERO_ERROR output,
				@SYS_MENSAJE_ERROR output
			END
						
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE BAN_SOLI_CHEQUE SET
			CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO,
			NUMERO_DOCUMENTO=@NUMERO_DOCUMENTO,
			FECHA_EMISION=@FECHA_EMISION,
			NOMBRE_PARTIDA=@NOMBRE_PARTIDA,
			CORR_PROVEEDOR=@CORR_PROVEEDOR,
			NOMBRE_BENEFICIARIO=@NOMBRE_BENEFICIARIO,
			MONTO_DOCUMENTO=@MONTO_DOCUMENTO,
			ESTADO_DOCUMENTO=@ESTADO_DOCUMENTO,
			SOLICITADO_POR=@SOLICITADO_POR,
			FECHA_SOLICITADO=@FECHA_SOLICITADO,
			FECHA_APLICADO=@FECHA_APLICADO,
			CANTIDAD_LETRAS=@CANTIDAD_LETRAS,
			--USUARIO_CREA=@USUARIO_CREA,
			--FECHA_CREA=@FECHA_CREA,
			--ESTACION_CREA=@ESTACION_CREA,
			USUARIO_ACTU=@USUARIO_ACTU,
			FECHA_ACTU=@FECHA_ACTU,
			ESTACION_ACTU=@ESTACION_ACTU,
			CORR_TIPO_CHEQUE=@CORR_TIPO_CHEQUE,
			ANIO_PERIODO_CHEQUE=@ANIO_PERIODO_CHEQUE,
			MES_PERIODO_CHEQUE=@MES_PERIODO_CHEQUE,
			CORR_TIPO_MOVIMIENTO_CHEQUE=@CORR_TIPO_MOVIMIENTO_CHEQUE,
			CORR_DOCUMENTO_CHEQUE=@CORR_DOCUMENTO_CHEQUE,
			CORR_MONEDA=@CORR_MONEDA,
			FACTOR_CAMBIO=@FACTOR_CAMBIO,
			OPERADOR=@OPERADOR
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			IF EXISTS ( SELECT 1 FROM BAN_DOCUMENTO A
						INNER JOIN BAN_SOLI_CHEQUE B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO_CHEQUE AND A.MES_PERIODO=B.MES_PERIODO_CHEQUE AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO_CHEQUE 
						WHERE B.CORR_SUSCRIPCION=@CORR_SUSCRIPCION 
						AND B.CORR_CONFI_PAIS=@CORR_CONFI_PAIS 
						AND B.CORR_EMPRESA=@CORR_EMPRESA 
						AND B.ANIO_PERIODO=@ANIO_PERIODO 
						AND B.MES_PERIODO=@MES_PERIODO 
						AND B.CORR_DOCUMENTO=@CORR_DOCUMENTO )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='No se puede eliminar porque existe un documento bancario asociado a esta solicitud.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
			IF EXISTS ( SELECT 1 FROM BAN_LIQUI_CAJA_CHICA 
						WHERE CORR_EMPRESA=@CORR_EMPRESA 
						AND ANIO_PERIODO_SOLI_CHEQUE=@ANIO_PERIODO 
						AND MES_PERIODO_SOLI_CHEQUE=@MES_PERIODO 
						AND CORR_TIPO_MOVIMIENTO_SOLI_CHEQUE=@CORR_TIPO_MOVIMIENTO 
						AND CORR_DOCUMENTO_SOLI_CHEQUE=@CORR_DOCUMENTO )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='No se puede eliminar porque existe una liquidacion de caja asociada a esta solicitud.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END	
			
			IF EXISTS ( SELECT 1 FROM COM_PAGO 
						WHERE CORR_EMPRESA=@CORR_EMPRESA 
						AND ANIO_PERIODO_SOLI_CHEQUE=@ANIO_PERIODO 
						AND MES_PERIODO_SOLI_CHEQUE=@MES_PERIODO 
						AND CORR_TIPO_MOVIMIENTO_SOLI_CHEQUE=@CORR_TIPO_MOVIMIENTO 
						AND CORR_DOCUMENTO_SOLI_CHEQUE=@CORR_DOCUMENTO )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='No se puede eliminar porque existe un pago por compras asociado a esta solicitud.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
			DELETE FROM BAN_SOLI_CHEQUE_DETA 
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			
			DELETE FROM BAN_SOLI_CHEQUE
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()
		
		-- bitacora omitida
FINA:
END
GO
