SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_COM_DOCUMENTO_TOTAL_IMPUESTO]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_DOCUMENTO INT OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0
	DECLARE @CLASE_DOCUMENTO CHAR(5)
	, @CORR_TIPO_DOC INT
	, @ESTADO_DOCUMENTO VARCHAR(2)
	, @PORC_PERCEPCION DECIMAL(14,2)
	, @PORC_RETENCION DECIMAL(14,2)
	, @NATURAL_JURIDICO VARCHAR(1)
	, @CLASE_RUBRO VARCHAR(3)
	, @MONTO_GRAVADO_SIN_IVA DECIMAL(18,2)
	, @MONTO_RUBRO_TOTAL DECIMAL(18,2)
	
	BEGIN TRY 
		SELECT @ESTADO_DOCUMENTO=ESTADO_DOCUMENTO, @CLASE_DOCUMENTO=CLASE_DOCUMENTO, @NATURAL_JURIDICO=B.TIPO_PERSONERIA
		FROM V_COM_DOCUMENTO A
		INNER JOIN V_COM_PROVEEDOR B
		ON A.CORR_PROVEEDOR=B.CORR_PROVEEDOR 
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.MES_PERIODO=@MES_PERIODO
		AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO
		
		IF @ESTADO_DOCUMENTO = 'DI'
		BEGIN
			IF @CLASE_DOCUMENTO IN ('FAC', 'CCF', 'FEX','NCR','CRT', 'INT', 'IMP', 'EXC', 'ESP','DCLE') 
			BEGIN
				EXECUTE PRAL_CALC_COM_PORC_RETE_PERC
					   @CORR_EMPRESA
					  ,@ANIO_PERIODO
					  ,@MES_PERIODO
					  ,@CORR_DOCUMENTO
					  ,@PORC_RETENCION OUTPUT
					  ,@PORC_PERCEPCION OUTPUT
					  ,0 
					  ,0 
					  
				DELETE A FROM COM_DOCUMENTO_TOTAL A
				INNER JOIN GEN_RUBRO B ON A.CORR_EMPRESA=B.CORR_EMPRESA  AND A.CORR_RUBRO=B.CORR_RUBRO 
				WHERE A.CORR_EMPRESA=@CORR_EMPRESA 
				AND A.ANIO_PERIODO=@ANIO_PERIODO 
				AND A.MES_PERIODO=@MES_PERIODO 
				AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO 
				AND B.ES_IMPUESTO=1
					
				
				--IMPUESTOS AL RUBRO GRAVADO
				MERGE COM_DOCUMENTO_TOTAL AS TARGET
				USING ( SELECT DISTINCT A.CORR_EMPRESA,A.ANIO_PERIODO,A.MES_PERIODO,
						A.CORR_DOCUMENTO,C.CORR_IMPUESTO, 0 MONTO_RUBRO, C.IMPUESTO_INCLUIDO
						--CASE WHEN C.IMPUESTO_INCLUIDO=1 THEN (A.MONTO_RUBRO)-((A.MONTO_RUBRO)/(1+(D.POR_IMPUESTO/100.00)))*D.SUMA_RESTA 
						--ELSE A.MONTO_RUBRO*(D.POR_IMPUESTO/100.00)*D.SUMA_RESTA END AS MONTO_RUBRO
						FROM V_COM_DOCUMENTO_TOTAL A
						INNER JOIN GEN_RUBRO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_RUBRO=B.CORR_RUBRO 
						INNER JOIN GEN_RUBRO_IMPUESTO C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_RUBRO=C.CORR_RUBRO 
						INNER JOIN GEN_RUBRO D ON C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CORR_IMPUESTO=D.CORR_RUBRO 
						--INNER JOIN GEN_EMPRESA E ON A.CORR_EMPRESA = E.CORR_EMPRESA
						--INNER JOIN V_GEN_PAIS F ON E.CORR_SUSCRIPCION = F.CORR_SUSCRIPCION AND E.CORR_PAIS = F.CORR_PAIS
						WHERE A.CORR_EMPRESA=@CORR_EMPRESA
						AND A.ANIO_PERIODO=@ANIO_PERIODO
						AND A.MES_PERIODO=@MES_PERIODO
						AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO
						AND B.ES_IMPUESTO<>1
						AND D.ES_IMPUESTO=1
						AND (D.CLASE_RUBRO NOT IN ('RET', 'PER', 'ISR') OR (D.CLASE_RUBRO='RET' AND @PORC_RETENCION<>0) OR (D.CLASE_RUBRO='PER' AND @PORC_PERCEPCION<>0) OR (D.CLASE_RUBRO='ISR' AND (@NATURAL_JURIDICO='N')))-- OR ISNULL(F.CODIGO_PAIS,'') NOT IN('ES','222'))))
						) AS SOURCE
				ON TARGET.CORR_EMPRESA=SOURCE.CORR_EMPRESA
				AND TARGET.ANIO_PERIODO=SOURCE.ANIO_PERIODO
				AND TARGET.MES_PERIODO=SOURCE.MES_PERIODO
				AND TARGET.CORR_DOCUMENTO=SOURCE.CORR_DOCUMENTO
				AND TARGET.CORR_RUBRO=SOURCE.CORR_IMPUESTO
				WHEN MATCHED 
					AND TARGET.CORR_EMPRESA=@CORR_EMPRESA 
					AND TARGET.ANIO_PERIODO=@ANIO_PERIODO 
					AND TARGET.MES_PERIODO=@MES_PERIODO 
					AND TARGET.CORR_DOCUMENTO=@CORR_DOCUMENTO 
					THEN UPDATE SET TARGET.MONTO_RUBRO=SOURCE.MONTO_RUBRO, TARGET.IMPUESTO_INCLUIDO=SOURCE.IMPUESTO_INCLUIDO
				WHEN NOT MATCHED BY TARGET 
					THEN INSERT (CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,
					CORR_DOCUMENTO,CORR_RUBRO,MONTO_RUBRO,IMPUESTO_INCLUIDO)
					VALUES (SOURCE.CORR_EMPRESA,SOURCE.ANIO_PERIODO,SOURCE.MES_PERIODO,
					SOURCE.CORR_DOCUMENTO,SOURCE.CORR_IMPUESTO,SOURCE.MONTO_RUBRO,SOURCE.IMPUESTO_INCLUIDO);				
				
				--IMPUESTOS ESPECIALES AL TIPO DE GASTO
				MERGE COM_DOCUMENTO_TOTAL AS TARGET
				USING ( SELECT A.CORR_EMPRESA,A.ANIO_PERIODO,A.MES_PERIODO,
						A.CORR_DOCUMENTO,C.CORR_RUBRO CORR_IMPUESTO, 0 MONTO_RUBRO, C.IMPUESTO_INCLUIDO
						--CASE WHEN C.IMPUESTO_INCLUIDO=1 THEN (A.MONTO_RUBRO)-((A.MONTO_RUBRO)/(1+(D.POR_IMPUESTO/100.00)))*D.SUMA_RESTA 
						--ELSE A.MONTO_RUBRO*(D.POR_IMPUESTO/100.00)*D.SUMA_RESTA END AS MONTO_RUBRO
						FROM V_COM_DOCUMENTO A
						INNER JOIN GEN_TIPO_GASTO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIPO_GASTO=B.CORR_TIPO_GASTO
						INNER JOIN GEN_TIPO_GASTO_IMPUESTO C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_TIPO_GASTO=C.CORR_TIPO_GASTO 
						INNER JOIN GEN_RUBRO D ON C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CORR_RUBRO=D.CORR_RUBRO 
						WHERE A.CORR_EMPRESA=@CORR_EMPRESA
						AND A.ANIO_PERIODO=@ANIO_PERIODO
						AND A.MES_PERIODO=@MES_PERIODO
						AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO
						AND D.ES_IMPUESTO=1
						AND (D.CLASE_RUBRO NOT IN ('RET', 'PER', 'ISR') OR (D.CLASE_RUBRO='RET' AND @PORC_RETENCION<>0) OR (D.CLASE_RUBRO='PER' AND @PORC_PERCEPCION<>0) OR (D.CLASE_RUBRO='ISR' AND @NATURAL_JURIDICO='N'))
						) AS SOURCE
				ON TARGET.CORR_EMPRESA=SOURCE.CORR_EMPRESA
				AND TARGET.ANIO_PERIODO=SOURCE.ANIO_PERIODO
				AND TARGET.MES_PERIODO=SOURCE.MES_PERIODO
				AND TARGET.CORR_DOCUMENTO=SOURCE.CORR_DOCUMENTO
				AND TARGET.CORR_RUBRO=SOURCE.CORR_IMPUESTO
				WHEN MATCHED 
					AND TARGET.CORR_EMPRESA=@CORR_EMPRESA 
					AND TARGET.ANIO_PERIODO=@ANIO_PERIODO 
					AND TARGET.MES_PERIODO=@MES_PERIODO 
					AND TARGET.CORR_DOCUMENTO=@CORR_DOCUMENTO 
					THEN 
					UPDATE SET TARGET.MONTO_RUBRO=SOURCE.MONTO_RUBRO, TARGET.IMPUESTO_INCLUIDO=SOURCE.IMPUESTO_INCLUIDO
				WHEN NOT MATCHED BY TARGET 
					THEN INSERT (CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,
					CORR_DOCUMENTO,CORR_RUBRO,MONTO_RUBRO,IMPUESTO_INCLUIDO)
					VALUES (SOURCE.CORR_EMPRESA,SOURCE.ANIO_PERIODO,SOURCE.MES_PERIODO,
					SOURCE.CORR_DOCUMENTO,SOURCE.CORR_IMPUESTO,SOURCE.MONTO_RUBRO,SOURCE.IMPUESTO_INCLUIDO);		
					
				
				--IMPUESTOS DEL ITEM		
				--MERGE COM_DOCUMENTO_TOTAL AS TARGET
				--USING ( SELECT A.CORR_EMPRESA
				--        ,A.ANIO_PERIODO_COM ANIO_PERIODO,A.MES_PERIODO_COM MES_PERIODO
				--        ,A.CORR_DOCUMENTO_COM CORR_DOCUMENTO,C.CORR_RUBRO CORR_IMPUESTO
				--		,D.POR_IMPUESTO, 0 MONTO_RUBRO, C.IMPUESTO_INCLUIDO,C.ORDEN_TOTAL
				--		FROM INV_RECEPCION_DETA A
				--		INNER JOIN INV_ITEM B ON A.CORR_SUSCRIPCION=B.CORR_SUSCRIPCION AND A.CORR_CONFI_PAIS=B.CORR_CONFI_PAIS AND A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIPO_ITEM=B.CORR_TIPO_ITEM AND A.CORR_ITEM=B.CORR_ITEM 
				--		INNER JOIN INV_ITEM_IMPUESTO C ON B.CORR_SUSCRIPCION=C.CORR_SUSCRIPCION AND B.CORR_CONFI_PAIS=C.CORR_CONFI_PAIS AND B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_TIPO_ITEM=C.CORR_TIPO_ITEM AND B.CORR_ITEM=C.CORR_ITEM 
				--		INNER JOIN GEN_RUBRO D ON C.CORR_SUSCRIPCION=D.CORR_SUSCRIPCION AND C.CORR_CONFI_PAIS=D.CORR_CONFI_PAIS AND C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CORR_RUBRO=D.CORR_RUBRO 						
				--		WHERE A.CORR_SUSCRIPCION=@CORR_SUSCRIPCION
				--		AND A.CORR_CONFI_PAIS=@CORR_CONFI_PAIS
				--		AND A.CORR_EMPRESA=@CORR_EMPRESA
				--		AND A.ANIO_PERIODO_COM=@ANIO_PERIODO
				--		AND A.MES_PERIODO_COM=@MES_PERIODO
				--		AND A.CORR_DOCUMENTO_COM=@CORR_DOCUMENTO					
				--		AND D.ES_IMPUESTO=1
				--		AND (D.CLASE_RUBRO NOT IN ('RET', 'PER') OR (D.CLASE_RUBRO='RET' AND @PORC_RETENCION<>0) OR (D.CLASE_RUBRO='PER' AND @PORC_PERCEPCION<>0))
				--		) AS SOURCE
				--ON TARGET.CORR_SUSCRIPCION=SOURCE.CORR_SUSCRIPCION
				--AND TARGET.CORR_CONFI_PAIS=SOURCE.CORR_CONFI_PAIS
				--AND TARGET.CORR_EMPRESA=SOURCE.CORR_EMPRESA
				--AND TARGET.ANIO_PERIODO=SOURCE.ANIO_PERIODO
				--AND TARGET.MES_PERIODO=SOURCE.MES_PERIODO
				--AND TARGET.CORR_DOCUMENTO=SOURCE.CORR_DOCUMENTO				
				--AND TARGET.CORR_RUBRO=SOURCE.CORR_IMPUESTO
				--WHEN MATCHED THEN				
				--UPDATE SET TARGET.MONTO_RUBRO=SOURCE.MONTO_RUBRO, TARGET.IMPUESTO_INCLUIDO=SOURCE.IMPUESTO_INCLUIDO, TARGET.ORDEN_TOTAL=SOURCE.ORDEN_TOTAL
				--WHEN NOT MATCHED BY TARGET 
				--	THEN INSERT (CORR_SUSCRIPCION,CORR_CONFI_PAIS,CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,
				--	CORR_DOCUMENTO,CORR_RUBRO,MONTO_RUBRO,IMPUESTO_INCLUIDO,ORDEN_TOTAL)
				--	VALUES (SOURCE.CORR_SUSCRIPCION,SOURCE.CORR_CONFI_PAIS,SOURCE.CORR_EMPRESA,SOURCE.ANIO_PERIODO,SOURCE.MES_PERIODO,
				--	SOURCE.CORR_DOCUMENTO,SOURCE.CORR_IMPUESTO,SOURCE.MONTO_RUBRO,SOURCE.IMPUESTO_INCLUIDO,SOURCE.ORDEN_TOTAL);
				--;
				
				--ITERACIONES POR CADA IMPUESTO QUE SE APLICA A ESTE DETALLE DE TOTALES		
				DECLARE @TEMP1 TABLE (CORR_IMPUESTO INT, IMPUESTO_INCLUIDO BIT, TIPO_APLICACION VARCHAR(3), ESTA_PROC INT)
				DECLARE @CONTADOR INT, @CANTIDAD_REGISTROS INT, @CORR_IMPUESTO INT, @IMPUESTO_INCLUIDO BIT, @TIPO_APLICACION VARCHAR(3)
				
				INSERT INTO @TEMP1 
				SELECT CORR_RUBRO AS CORR_IMPUESTO, IMPUESTO_INCLUIDO, TIPO_APLICACION, 0 ESTA_PROC
				FROM V_COM_DOCUMENTO_TOTAL  
				WHERE CORR_EMPRESA=@CORR_EMPRESA 
				AND ANIO_PERIODO=@ANIO_PERIODO 
				AND MES_PERIODO=@MES_PERIODO 
				AND CORR_DOCUMENTO=@CORR_DOCUMENTO 
				AND ES_IMPUESTO=1
				
				SELECT @CONTADOR=0, @CANTIDAD_REGISTROS=COUNT(*)
				FROM @TEMP1 
				
				WHILE (@CONTADOR<@CANTIDAD_REGISTROS )
				BEGIN
					SELECT TOP 1 @CORR_IMPUESTO=CORR_IMPUESTO, @IMPUESTO_INCLUIDO=IMPUESTO_INCLUIDO, @TIPO_APLICACION=TIPO_APLICACION 
					FROM @TEMP1 WHERE ESTA_PROC=0
					
					IF @TIPO_APLICACION='PVG' --PORCENTAJE VALOR GRAVADO
					BEGIN
						DECLARE @MONTO_SIN_IMPUESTOS_INCLUIDOS DECIMAL(12,4)
												
						--Dividimos el monto que se saco en la operacion anterior entre la suma de los porcentajes de todos los impuestos que estan incluidos para sacar en si el monto neto sin impuestos
						SELECT @MONTO_SIN_IMPUESTOS_INCLUIDOS=ISNULL(SUM(AA.MONTO_SIN_IMPUESTOS_INCLUIDOS),0)						
						FROM (SELECT  ISNULL(A.CORR_RUBRO,0) CORR_RUBRO,ISNULL(A.MONTO_RUBRO,0)/(1.0000+SUM(CASE WHEN B.IMPUESTO_INCLUIDO=1 THEN ((C.POR_IMPUESTO*E.SUMA_RESTA)/100.0000) ELSE 0.0000 END))	MONTO_SIN_IMPUESTOS_INCLUIDOS
							FROM COM_DOCUMENTO_TOTAL A
							INNER JOIN GEN_RUBRO_IMPUESTO B ON  A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_RUBRO=B.CORR_RUBRO 
							INNER JOIN V_COM_DOCUMENTO_TOTAL C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_IMPUESTO=C.CORR_RUBRO
							INNER JOIN GEN_RUBRO_IMPUESTO D ON  A.CORR_EMPRESA=D.CORR_EMPRESA AND A.CORR_RUBRO=D.CORR_RUBRO 
							INNER JOIN GEN_RUBRO E ON C.CORR_EMPRESA=E.CORR_EMPRESA AND C.CORR_RUBRO=E.CORR_RUBRO 
							WHERE A.CORR_EMPRESA=@CORR_EMPRESA 						 
							AND A.ANIO_PERIODO=@ANIO_PERIODO 
							AND A.MES_PERIODO=@MES_PERIODO 
							AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO 
							AND C.ANIO_PERIODO=@ANIO_PERIODO 
							AND C.MES_PERIODO=@MES_PERIODO 
							AND C.CORR_DOCUMENTO=@CORR_DOCUMENTO 
							AND D.CORR_IMPUESTO=@CORR_IMPUESTO
							AND C.ES_IMPUESTO=1
							AND C.TIPO_APLICACION='PVG'
							GROUP BY ISNULL(A.CORR_RUBRO,0),ISNULL(A.MONTO_RUBRO,0)
						) AA												
						
						--IF ISNULL(@MONTO_SIN_IMPUESTOS_INCLUIDOS,0)<=0 --Si el monto gravado es cero verifico si esta como impuesto especial en el item
						--BEGIN																			
						--	SELECT @MONTO_SIN_IMPUESTOS_INCLUIDOS=ISNULL(SUM(AA.MONTO_SIN_IMPUESTOS_INCLUIDOS),0)						
						--	FROM (SELECT  ISNULL(C.CORR_RUBRO,0) CORR_RUBRO,ISNULL(A.MONTO_TOTAL,0)/(1.0000+SUM(CASE WHEN C.IMPUESTO_INCLUIDO=1 THEN ((E.POR_IMPUESTO*E.SUMA_RESTA)/100.0000) ELSE 0.0000 END))	MONTO_SIN_IMPUESTOS_INCLUIDOS
						--		FROM INV_RECEPCION_DETA A
						--		INNER JOIN INV_ITEM B ON  A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIPO_ITEM=B.CORR_TIPO_ITEM AND A.CORR_ITEM=B.CORR_ITEM 
						--		INNER JOIN INV_ITEM_IMPUESTO C B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_TIPO_ITEM=C.CORR_TIPO_ITEM AND B.CORR_ITEM=C.CORR_ITEM 
						--		INNER JOIN GEN_RUBRO E ON C.CORR_EMPRESA=E.CORR_EMPRESA AND C.CORR_RUBRO=E.CORR_RUBRO 															
						--		WHERE A.CORR_EMPRESA=@CORR_EMPRESA 						 
						--		AND A.ANIO_PERIODO_COM=@ANIO_PERIODO
						--		AND A.MES_PERIODO_COM=@MES_PERIODO
						--		AND A.CORR_DOCUMENTO_COM=@CORR_DOCUMENTO
						--		AND C.CORR_RUBRO=@CORR_IMPUESTO								
						--		AND E.TIPO_APLICACION='PVG'
						--		GROUP BY ISNULL(C.CORR_RUBRO,0),ISNULL(A.MONTO_TOTAL,0)
						--	) AA												
						--END
						
						UPDATE COM_DOCUMENTO_TOTAL SET
						MONTO_RUBRO=@MONTO_SIN_IMPUESTOS_INCLUIDOS*(B.POR_IMPUESTO/100.00)
						FROM COM_DOCUMENTO_TOTAL A
						INNER JOIN GEN_RUBRO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_RUBRO=B.CORR_RUBRO 
						WHERE A.CORR_EMPRESA=@CORR_EMPRESA
						AND A.ANIO_PERIODO=@ANIO_PERIODO
						AND A.MES_PERIODO=@MES_PERIODO
						AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO 
						AND A.CORR_RUBRO=@CORR_IMPUESTO 						
					END
					
					IF @TIPO_APLICACION='MPC' --MONTO POR CANTIDAD
					BEGIN
						DECLARE @CANTIDAD_UNIDADES DECIMAL(12,4)
						
						SELECT @CANTIDAD_UNIDADES=A.CANTIDAD 
						FROM COM_DOCUMENTO A
						WHERE A.CORR_EMPRESA=@CORR_EMPRESA
						AND A.ANIO_PERIODO=@ANIO_PERIODO
						AND A.MES_PERIODO=@MES_PERIODO
						AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO
										
						UPDATE COM_DOCUMENTO_TOTAL SET
						MONTO_RUBRO=@CANTIDAD_UNIDADES*B.POR_IMPUESTO
						FROM COM_DOCUMENTO_TOTAL A
						INNER JOIN GEN_RUBRO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_RUBRO=B.CORR_RUBRO 
						WHERE A.CORR_EMPRESA=@CORR_EMPRESA
						AND A.ANIO_PERIODO=@ANIO_PERIODO
						AND A.MES_PERIODO=@MES_PERIODO
						AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO 
						AND A.CORR_RUBRO=@CORR_IMPUESTO
					END


					SELECT @CLASE_RUBRO=CLASE_RUBRO 
					FROM GEN_RUBRO
					WHERE CORR_EMPRESA=@CORR_EMPRESA
					AND CORR_RUBRO=@CORR_IMPUESTO

					--IF @TIPO_APLICACION = 'TAB' AND @CLASE_RUBRO='ISR'
					--BEGIN
					--	SELECT @MONTO_GRAVADO_SIN_IVA=ISNULL(A.MONTO_RUBRO - ISNULL(C.MONTO_RUBRO_INCLUIDO,0),0)
					--	FROM COM_DOCUMENTO_TOTAL A
					--	INNER JOIN GEN_RUBRO B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_RUBRO=B.CORR_RUBRO
					--	LEFT OUTER JOIN V_COM_DOCUMENTO_IMPUESTO_SUM C ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.ANIO_PERIODO = C.ANIO_PERIODO AND A.MES_PERIODO = C.MES_PERIODO AND A.CORR_DOCUMENTO = C.CORR_DOCUMENTO
					--	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					--	AND A.ANIO_PERIODO=@ANIO_PERIODO
					--	AND A.MES_PERIODO=@MES_PERIODO
					--	AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO
					--	AND B.CLASE_RUBRO='GRA'

					--	SELECT TOP 1 @MONTO_RUBRO_TOTAL=ISNULL(((@MONTO_GRAVADO_SIN_IVA-B.MONTO_EXCEDENTE)*(B.POR_RETENCION/100.0))+B.MONTO_RETENCION,0)
					--	FROM PLA_TABLA_RENTA A
					--	INNER JOIN PLA_TABLA_RENTA_DETA B ON A.CORR_SUSCRIPCION = B.CORR_SUSCRIPCION AND A.CORR_CONFI_PAIS = B.CORR_CONFI_PAIS AND A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TABLA = B.CORR_TABLA
					--	WHERE A.CORR_SUSCRIPCION=@CORR_SUSCRIPCION
					--	AND A.CORR_CONFI_PAIS=@CORR_CONFI_PAIS
					--	AND A.CORR_EMPRESA=@CORR_EMPRESA
					--	AND A.CLASE_RENTA ='OP'
					--	AND @MONTO_GRAVADO_SIN_IVA>=B.MONTO_INICIAL AND (@MONTO_GRAVADO_SIN_IVA<=B.MONTO_FINAL OR B.MONTO_FINAL=0)
			
					--	UPDATE COM_DOCUMENTO_TOTAL SET
					--	MONTO_RUBRO=@MONTO_RUBRO_TOTAL
					--	FROM COM_DOCUMENTO_TOTAL A
					--	WHERE A.CORR_SUSCRIPCION=@CORR_SUSCRIPCION
					--	AND A.CORR_CONFI_PAIS=@CORR_CONFI_PAIS
					--	AND A.CORR_EMPRESA=@CORR_EMPRESA
					--	AND A.ANIO_PERIODO=@ANIO_PERIODO
					--	AND A.MES_PERIODO=@MES_PERIODO
					--	AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO 
					--	AND A.CORR_RUBRO=@CORR_IMPUESTO
					--END

					UPDATE @TEMP1 SET
					ESTA_PROC=1
					WHERE CORR_IMPUESTO=@CORR_IMPUESTO
					SELECT @CONTADOR+=1
				END
				
			END
		END
		ELSE
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Este documento ya está aplicado o anulado',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
