SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_COM_DOCUMENTO_TOTAL]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_DOCUMENTO int OUTPUT,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0
	DECLARE @ESTADO_DOCUMENTO VARCHAR(2)
	, @CLASE_DOCUMENTO CHAR(5)
	, @CORR_TIPO_DOC INT
	, @TOTAL_PERCEPCION DECIMAL(14,2)
	, @TOTAL_RETENCION DECIMAL(14,2)
	, @MONTO_INGRESO_TOTAL DECIMAL(12,2)
	
	DECLARE @TEMP1 TABLE (CORR_RUBRO INT, ESTA_PROC INT)
	
	BEGIN TRY
	
		SELECT @ESTADO_DOCUMENTO=ESTADO_DOCUMENTO
		FROM COM_DOCUMENTO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.MES_PERIODO=@MES_PERIODO
		AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO
		
		IF @ESTADO_DOCUMENTO = 'DI'
		BEGIN
			SELECT @CLASE_DOCUMENTO=CLASE_DOCUMENTO, @CORR_TIPO_DOC=CORR_TIPO_DOC
			FROM V_COM_DOCUMENTO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
		
			--DETALLE DE SUMAS SEGUN CONFIGURACION DE RUBROS POR TIPO DE DOCUMENTO
			MERGE COM_DOCUMENTO_TOTAL AS TARGET
			USING ( SELECT A.CORR_EMPRESA,A.ANIO_PERIODO,A.MES_PERIODO,A.CORR_DOCUMENTO,
					B.CORR_RUBRO, B.ORDEN_TOTAL, B.PERMITE_EDITAR
					FROM COM_DOCUMENTO A
					INNER JOIN GEN_TIPO_DOCUMENTO_RUBRO B
					ON A.CORR_EMPRESA=B.CORR_EMPRESA 
					AND A.CORR_TIPO_DOC=B.CORR_TIPO_DOC 
					INNER JOIN GEN_RUBRO C
					ON (B.CORR_EMPRESA=C.CORR_EMPRESA 
					AND B.CORR_RUBRO=C.CORR_RUBRO ) 
					WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					AND A.ANIO_PERIODO=@ANIO_PERIODO
					AND A.MES_PERIODO=@MES_PERIODO
					AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO
					AND C.MUESTRA_TOTAL=1 ) AS SOURCE
			ON TARGET.CORR_EMPRESA=SOURCE.CORR_EMPRESA
			AND TARGET.ANIO_PERIODO=SOURCE.ANIO_PERIODO
			AND TARGET.MES_PERIODO=SOURCE.MES_PERIODO
			AND TARGET.CORR_DOCUMENTO=SOURCE.CORR_DOCUMENTO
			AND TARGET.CORR_RUBRO=SOURCE.CORR_RUBRO
			WHEN MATCHED
				AND TARGET.CORR_EMPRESA=@CORR_EMPRESA 
				AND TARGET.ANIO_PERIODO=@ANIO_PERIODO 
				AND TARGET.MES_PERIODO=@MES_PERIODO 
				AND TARGET.CORR_DOCUMENTO=@CORR_DOCUMENTO 
				THEN UPDATE SET TARGET.ORDEN_TOTAL=SOURCE.ORDEN_TOTAL, TARGET.PERMITE_EDITAR=SOURCE.PERMITE_EDITAR
			WHEN NOT MATCHED BY TARGET THEN	INSERT (CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,
			   CORR_DOCUMENTO,CORR_RUBRO,MONTO_RUBRO,ORDEN_TOTAL,PERMITE_EDITAR)
			   VALUES (SOURCE.CORR_EMPRESA,SOURCE.ANIO_PERIODO,SOURCE.MES_PERIODO,
			   SOURCE.CORR_DOCUMENTO,SOURCE.CORR_RUBRO,0,SOURCE.ORDEN_TOTAL,SOURCE.PERMITE_EDITAR)
			--WHEN NOT MATCHED BY SOURCE 
			--	AND TARGET.CORR_SUSCRIPCION=@CORR_SUSCRIPCION 
			--	AND TARGET.CORR_CONFI_PAIS=@CORR_CONFI_PAIS 
			--	AND TARGET.CORR_EMPRESA=@CORR_EMPRESA 
			--	AND TARGET.ANIO_PERIODO=@ANIO_PERIODO 
			--	AND TARGET.MES_PERIODO=@MES_PERIODO 
			--	AND TARGET.CORR_DOCUMENTO=@CORR_DOCUMENTO
			--	THEN DELETE
				;	
				
			--DETALLE DE SUMAS SEGUN CONFIGURACION DEL TIPO DE GASTO
			MERGE COM_DOCUMENTO_TOTAL AS TARGET
			USING ( SELECT A.CORR_EMPRESA,A.ANIO_PERIODO,A.MES_PERIODO,A.CORR_DOCUMENTO,
					B.CORR_RUBRO, B.ORDEN_TOTAL, ISNULL(B.PERMITE_EDITAR,1) PERMITE_EDITAR 
					FROM COM_DOCUMENTO A
					INNER JOIN GEN_TIPO_GASTO_IMPUESTO B
					ON A.CORR_EMPRESA=B.CORR_EMPRESA 
					AND A.CORR_TIPO_GASTO=B.CORR_TIPO_GASTO 
					INNER JOIN GEN_RUBRO C
					ON (B.CORR_EMPRESA=C.CORR_EMPRESA 
					AND B.CORR_RUBRO=C.CORR_RUBRO ) 
					WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					AND A.ANIO_PERIODO=@ANIO_PERIODO
					AND A.MES_PERIODO=@MES_PERIODO
					AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO
					--AND C.MUESTRA_TOTAL=1  --ESTA BANDERA 'MUESTRA TOTAL' TAMBIEN ESTA QUEMADA
					) AS SOURCE 
			ON TARGET.CORR_EMPRESA=SOURCE.CORR_EMPRESA
			AND TARGET.ANIO_PERIODO=SOURCE.ANIO_PERIODO
			AND TARGET.MES_PERIODO=SOURCE.MES_PERIODO
			AND TARGET.CORR_DOCUMENTO=SOURCE.CORR_DOCUMENTO
			AND TARGET.CORR_RUBRO=SOURCE.CORR_RUBRO
			WHEN MATCHED
				AND TARGET.CORR_EMPRESA=@CORR_EMPRESA 
				AND TARGET.ANIO_PERIODO=@ANIO_PERIODO 
				AND TARGET.MES_PERIODO=@MES_PERIODO 
				AND TARGET.CORR_DOCUMENTO=@CORR_DOCUMENTO 
				THEN UPDATE SET TARGET.ORDEN_TOTAL=SOURCE.ORDEN_TOTAL, TARGET.PERMITE_EDITAR=SOURCE.PERMITE_EDITAR				
			WHEN NOT MATCHED BY TARGET THEN	INSERT (CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,
			   CORR_DOCUMENTO,CORR_RUBRO,MONTO_RUBRO,ORDEN_TOTAL,PERMITE_EDITAR)
			   VALUES (SOURCE.CORR_EMPRESA,SOURCE.ANIO_PERIODO,SOURCE.MES_PERIODO,
			   SOURCE.CORR_DOCUMENTO,SOURCE.CORR_RUBRO,0,SOURCE.ORDEN_TOTAL,SOURCE.PERMITE_EDITAR)
			--WHEN NOT MATCHED BY SOURCE 
			--	AND TARGET.CORR_SUSCRIPCION=@CORR_SUSCRIPCION 
			--	AND TARGET.CORR_CONFI_PAIS=@CORR_CONFI_PAIS 
			--	AND TARGET.CORR_EMPRESA=@CORR_EMPRESA 
			--	AND TARGET.ANIO_PERIODO=@ANIO_PERIODO 
			--	AND TARGET.MES_PERIODO=@MES_PERIODO 
			--	AND TARGET.CORR_DOCUMENTO=@CORR_DOCUMENTO
			--	THEN DELETE
				;
		
			INSERT INTO @TEMP1
			SELECT A.CORR_RUBRO, ESTA_PROC=0
			FROM COM_DOCUMENTO_TOTAL A
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			
			DECLARE @CORR_RUBRO_TOTAL INT, @ES_IMPUESTO BIT, @MONTO_RUBRO_TOTAL DECIMAL(12,2)
			
			DECLARE @CANT_REGISTRO INT, @CONTADOR INT		
			
			SELECT @CONTADOR=0, @CANT_REGISTRO=COUNT(*) FROM @TEMP1 
			
			WHILE @CONTADOR<@CANT_REGISTRO
			BEGIN
				SELECT TOP 1 @CORR_RUBRO_TOTAL=CORR_RUBRO,@MONTO_RUBRO_TOTAL=0 FROM @TEMP1 WHERE ESTA_PROC=0
				
				
				SELECT @MONTO_RUBRO_TOTAL+=ISNULL(SUM(ROUND(ABS(B.MONTO_RUBRO),2)*C.SUMA_RESTA),0)						
				FROM GEN_RUBRO_SUMA A
				INNER JOIN COM_DOCUMENTO_TOTAL B
				ON A.CORR_EMPRESA=B.CORR_EMPRESA 
				AND A.CORR_SUMA=B.CORR_RUBRO 
				INNER JOIN GEN_RUBRO C
				ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_RUBRO=C.CORR_RUBRO 
				WHERE A.CORR_EMPRESA=@CORR_EMPRESA
				AND A.CORR_RUBRO=@CORR_RUBRO_TOTAL
				AND	B.CORR_EMPRESA=@CORR_EMPRESA
				AND B.ANIO_PERIODO=@ANIO_PERIODO
				AND B.MES_PERIODO=@MES_PERIODO
				AND B.CORR_DOCUMENTO=@CORR_DOCUMENTO
				
				UPDATE COM_DOCUMENTO_TOTAL SET MONTO_RUBRO=ISNULL(@MONTO_RUBRO_TOTAL,0)
				WHERE CORR_EMPRESA=@CORR_EMPRESA
				AND ANIO_PERIODO=@ANIO_PERIODO
				AND MES_PERIODO=@MES_PERIODO
				AND CORR_DOCUMENTO=@CORR_DOCUMENTO
				AND CORR_RUBRO=@CORR_RUBRO_TOTAL
				
				UPDATE @TEMP1 SET ESTA_PROC=1 WHERE CORR_RUBRO=@CORR_RUBRO_TOTAL
				
				SELECT @CONTADOR+=1
			END
			
			UPDATE COM_DOCUMENTO SET 
			TOTAL_DOCUMENTO=B.MONTO_RUBRO 
			FROM COM_DOCUMENTO A
			INNER JOIN V_COM_DOCUMENTO_TOTAL B
			ON A.CORR_EMPRESA=B.CORR_EMPRESA 
			AND A.ANIO_PERIODO=B.ANIO_PERIODO 
			AND A.MES_PERIODO=B.MES_PERIODO 
			AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO 
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.MES_PERIODO=@MES_PERIODO
			AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO
			AND B.CLASE_RUBRO='VTO' --VENTAS TOTALES
			
			UPDATE COM_DOCUMENTO SET 
			TOTAL_NETO=B.MONTO_RUBRO 
			FROM COM_DOCUMENTO A
		    INNER JOIN (SELECT TOP 1 C.CORR_EMPRESA,C.ANIO_PERIODO,C.MES_PERIODO,
						C.CORR_DOCUMENTO ,C.MONTO_RUBRO
						FROM V_COM_DOCUMENTO_TOTAL C
						WHERE C.CORR_EMPRESA=@CORR_EMPRESA
						AND C.ANIO_PERIODO=@ANIO_PERIODO
						AND C.MES_PERIODO=@MES_PERIODO
						AND C.CORR_DOCUMENTO=@CORR_DOCUMENTO
						AND C.CLASE_RUBRO='GRA') B
			ON A.CORR_EMPRESA=B.CORR_EMPRESA 
			AND A.ANIO_PERIODO=B.ANIO_PERIODO 
			AND A.MES_PERIODO=B.MES_PERIODO 
			AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO 
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.MES_PERIODO=@MES_PERIODO
			AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO			
			
			UPDATE COM_DOCUMENTO SET
			SALDO_DOCUMENTO=TOTAL_DOCUMENTO 
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
					
			
		END
		ELSE
		BEGIN
			IF @ESTADO_DOCUMENTO IN ('AN', 'AP')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Este documento ya está aplicado o anulado',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END ELSE
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30003,@SYS_MENSAJE_ERROR='Este documento no existe',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
		END
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
