SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_ESTADO_RESULTADOS]
( 
  @CORR_EMPRESA INT,
  @FECHA_FINAL DATE,
  @NIVEL SMALLINT,
  @PARTIDA_CIERRE BIT=0,
  @PARTIDA_LIQUIDACION BIT=0,
  @CORR_MONEDA INT=NULL,
  @FOLIADO BIT=0,
  @NUMERO_FOLIO INT=0,
  @MUESTRA_FIRMA BIT=0

)
AS	
	DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),
		CUENTA_MAYOR varchar(30),
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(12,2),
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),
		SALDO_FINAL	DECIMAL(12,2)
	)
	
	DECLARE @CORR_MONEDA_LOCAL INT, @CORR_MONEDA_FORANEA INT
	DECLARE @MOSTRAR_FECHA_IMPRESION BIT	
	
	DECLARE @NOMBRE_PUESTO1 VARCHAR(100),
	@DESCRIPCION_PUESTO1 VARCHAR(100),
	@NOMBRE_PUESTO2 VARCHAR(100),
	@DESCRIPCION_PUESTO2 VARCHAR(100),
	@NOMBRE_PUESTO3 VARCHAR(100),
	@DESCRIPCION_PUESTO3 VARCHAR(100),
	@DESCRIPCION_MONEDA VARCHAR(255)
BEGIN
    
    SET NOCOUNT ON
    
    DECLARE @ESTADO_RESULTADO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_MAYOR_4 VARCHAR(30),
		NOMBRE_CUENTA_MAYOR_4 VARCHAR(100),
		CUENTA_MAYOR_3 VARCHAR(30),
		NOMBRE_CUENTA_MAYOR_3 VARCHAR(100),
		CUENTA_MAYOR_2 VARCHAR(30),
		NOMBRE_CUENTA_MAYOR_2 VARCHAR(100),
		CUENTA_MAYOR_1 VARCHAR(30),
		NOMBRE_CUENTA_MAYOR_1 VARCHAR(100),
		CUENTA_CONTABLE VARCHAR(30),
		NOMBRE_CUENTA VARCHAR(100),
		SALDO_MES DECIMAL(18,2),
		SALDO_FINAL DECIMAL(18,2),
		NIVEL INT,
		CLASE_RUBRO VARCHAR(2),
		NOMBRE_PUESTO1 VARCHAR(100),
		DESCRIPCION_PUESTO1 VARCHAR(100),
		NOMBRE_PUESTO2 VARCHAR(100),
		DESCRIPCION_PUESTO2 VARCHAR(100),
		NOMBRE_PUESTO3 VARCHAR(100),
		DESCRIPCION_PUESTO3 VARCHAR(100),
		DESCRIPCION_MONEDA  VARCHAR(255),
		FOLIADO BIT,
		NUMERO_FOLIO INT,
		MOSTRAR_FECHA_IMPRESION BIT,
		MUESTRA_FIRMA BIT,
		FECHA_FINAL DATE
	)
	SELECT @CORR_MONEDA_LOCAL=CORR_MONEDA
	FROM CON_PARAMETRO
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	
	SET @CORR_MONEDA_FORANEA = NULL
	
	IF @CORR_MONEDA IS NULL
		SELECT @CORR_MONEDA=@CORR_MONEDA_LOCAL	
	
	
	IF @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL
	BEGIN
		--Obteniendo el saldo solo de las cuentas de ingresos y gastos
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL 
	@CORR_EMPRESA,
		@FECHA_FINAL,
		2,--OPCION_CONSULTA=Saldo de las cuentas contables de Ingresos y Gastos hasta la fecha de consulta
		0,--MAYORIZA=Mayoriza los saldo
		'',
		'',	
		1, --Aplicar el debe o haber de la cuenta
		@PARTIDA_CIERRE, --Incluir partidas de cierre
		@PARTIDA_LIQUIDACION, --Incluir partidas de liquidación
		@NIVEL --Hasta el nivel indicado
	END ELSE
	IF @CORR_MONEDA=@CORR_MONEDA_FORANEA
	BEGIN
		--Obteniendo el saldo solo de las cuentas de ingresos y gastos
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL_FORANEA
	@CORR_EMPRESA,
		@FECHA_FINAL,
		2,--OPCION_CONSULTA=Saldo de las cuentas contables de Ingresos y Gastos hasta la fecha de consulta
		0,--MAYORIZA=Mayoriza los saldo
		'',
		'',	
		1, --Aplicar el debe o haber de la cuenta
		@PARTIDA_CIERRE, --Incluir partidas de cierre
		@PARTIDA_LIQUIDACION, --Incluir partidas de liquidación
		@NIVEL --Hasta el nivel indicado
	END
    --Obteniendo las personas que firmarán en balance general
    SELECT @NOMBRE_PUESTO1=A.NOMBRE_PUESTO1,
	@DESCRIPCION_PUESTO1=A.DESCRIPCION_PUESTO1,
	@NOMBRE_PUESTO2=A.NOMBRE_PUESTO2,
	@DESCRIPCION_PUESTO2=A.DESCRIPCION_PUESTO2,
	@NOMBRE_PUESTO3=A.NOMBRE_PUESTO3,
	@DESCRIPCION_PUESTO3=A.DESCRIPCION_PUESTO3,
	@MOSTRAR_FECHA_IMPRESION=MOSTRAR_FECHA_IMPRESION	
	FROM CON_PARAMETRO A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
    
	
	--Obteniendo en que moneda esta el balance general
	SET @DESCRIPCION_MONEDA = ''
	INSERT INTO @ESTADO_RESULTADO
    SELECT @CORR_EMPRESA CORR_EMPRESA
	,ISNULL(G.PREFIJO,'')+F.CUENTA_CONTABLE CUENTA_MAYOR_4 
	,F.NOMBRE_CUENTA NOMBRE_CUENTA_MAYOR_4
	,ISNULL(G.PREFIJO,'')+E.CUENTA_CONTABLE CUENTA_MAYOR_3
	,E.NOMBRE_CUENTA NOMBRE_CUENTA_MAYOR_3
	,ISNULL(G.PREFIJO,'')+D.CUENTA_CONTABLE CUENTA_MAYOR_2
	,D.NOMBRE_CUENTA NOMBRE_CUENTA_MAYOR_2
	,ISNULL(G.PREFIJO,'')+C.CUENTA_CONTABLE CUENTA_MAYOR_1
	,C.NOMBRE_CUENTA NOMBRE_CUENTA_MAYOR_1
	,ISNULL(G.PREFIJO,'')+A.CUENTA_CONTABLE CUENTA_CONTABLE
	,B.NOMBRE_CUENTA
	,SUM(CASE WHEN B.ES_DEBE=1 THEN 1 ELSE -1 END * (ISNULL(A.CARGO_PERIODO,0)-ISNULL(A.ABONO_PERIODO,0))) SALDO_MES
	,SUM(A.SALDO_FINAL) SALDO_FINAL
	,B.NIVEL
	,B.CLASE_RUBRO
	,@NOMBRE_PUESTO1 NOMBRE_PUESTO1
	,@DESCRIPCION_PUESTO1 DESCRIPCION_PUESTO1
	,@NOMBRE_PUESTO2 NOMBRE_PUESTO2
	,@DESCRIPCION_PUESTO2 DESCRIPCION_PUESTO2
	,@NOMBRE_PUESTO3 NOMBRE_PUESTO3
	,@DESCRIPCION_PUESTO3 DESCRIPCION_PUESTO3
	,@DESCRIPCION_MONEDA DESCRIPCION_MONEDA		
	,@FOLIADO FOLIADO
	,@NUMERO_FOLIO NUMERO_FOLIO
	,CONVERT(BIT,ISNULL(@MOSTRAR_FECHA_IMPRESION,0)) MOSTRAR_FECHA_IMPRESION
	,@MUESTRA_FIRMA MUESTRA_FIRMA
	,@FECHA_FINAL FECHA_FINAL
	FROM @SALDO A
	INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
	INNER JOIN CON_CATALOGO_CUENTA C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CUENTA_MAYOR=C.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA D ON C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CUENTA_MAYOR=D.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA E ON D.CORR_EMPRESA=E.CORR_EMPRESA AND D.CUENTA_MAYOR=E.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA F ON E.CORR_EMPRESA=F.CORR_EMPRESA AND E.CUENTA_MAYOR=F.CUENTA_CONTABLE		
	INNER JOIN CON_PARAMETRO G ON A.CORR_EMPRESA=G.CORR_EMPRESA
	GROUP BY ISNULL(G.PREFIJO,'') , A.CUENTA_CONTABLE, B.NOMBRE_CUENTA, B.NIVEL, B.CLASE_RUBRO
	,F.CUENTA_CONTABLE,F.NOMBRE_CUENTA
	,E.CUENTA_CONTABLE,E.NOMBRE_CUENTA
	,D.CUENTA_CONTABLE,D.NOMBRE_CUENTA
	,C.CUENTA_CONTABLE,C.NOMBRE_CUENTA
	HAVING SUM(A.SALDO_FINAL)<>0 OR SUM(A.CARGO_PERIODO)<>0 OR SUM(A.ABONO_PERIODO)<>0
	ORDER BY CASE WHEN B.CLASE_RUBRO='IN' THEN 0 ELSE 1 END
	,ISNULL(G.PREFIJO,'')+F.CUENTA_CONTABLE
	,ISNULL(G.PREFIJO,'')+E.CUENTA_CONTABLE
	,ISNULL(G.PREFIJO,'')+D.CUENTA_CONTABLE
	,ISNULL(G.PREFIJO,'')+C.CUENTA_CONTABLE
	,ISNULL(G.PREFIJO,'')+A.CUENTA_CONTABLE

	IF NOT EXISTS(SELECT 1 FROM @ESTADO_RESULTADO)
	BEGIN
		INSERT INTO @ESTADO_RESULTADO
    SELECT @CORR_EMPRESA CORR_EMPRESA
		,'' CUENTA_MAYOR_4 
		,'' NOMBRE_CUENTA_MAYOR_4
		,'' CUENTA_MAYOR_3
		,'' NOMBRE_CUENTA_MAYOR_3
		,'' CUENTA_MAYOR_2
		,'' NOMBRE_CUENTA_MAYOR_2
		,'' CUENTA_MAYOR_1
		,'' NOMBRE_CUENTA_MAYOR_1
		,'' CUENTA_CONTABLE
		,'' NOMBRE_CUENTA
		,0 SALDO_MES
		,0 SALDO_FINAL
		,0 NIVEL
		,'' CLASE_RUBRO
		,@NOMBRE_PUESTO1 NOMBRE_PUESTO1
		,@DESCRIPCION_PUESTO1 DESCRIPCION_PUESTO1
		,@NOMBRE_PUESTO2 NOMBRE_PUESTO2
		,@DESCRIPCION_PUESTO2 DESCRIPCION_PUESTO2
		,@NOMBRE_PUESTO3 NOMBRE_PUESTO3
		,@DESCRIPCION_PUESTO3 DESCRIPCION_PUESTO3
		,@DESCRIPCION_MONEDA DESCRIPCION_MONEDA		
		,@FOLIADO FOLIADO
		,@NUMERO_FOLIO NUMERO_FOLIO
		,CONVERT(BIT,ISNULL(@MOSTRAR_FECHA_IMPRESION,0)) MOSTRAR_FECHA_IMPRESION
		,@MUESTRA_FIRMA MUESTRA_FIRMA
		,@FECHA_FINAL FECHA_FINAL
		
	END

	SELECT * FROM @ESTADO_RESULTADO


	SELECT A.CORR_EMPRESA 
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO

