SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_GENE_PARTIDA_LIQUIDACION]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
	DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE VARCHAR(30),
		CUENTA_MAYOR VARCHAR(30),
		CORR_AUXILIAR INT,
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(12,2),
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),
		SALDO_FINAL DECIMAL(12,2)
		PRIMARY KEY (CORR_EMPRESA, CUENTA_CONTABLE, CORR_AUXILIAR)
	)

	DECLARE @FECHA_CONSULTA DATE, @CORR_CLASE_PARTIDA INT, @CORR_PARTIDA INT, @NOMBRE_PARTIDA VARCHAR(255),
		@FECHA_CREA DATETIME, @CUENTA_CONTABLE_PERDIDA VARCHAR(30), @CUENTA_CONTABLE_GANANCIA VARCHAR(30), @DIF DECIMAL(12,2),
		@CORR_MONEDA INT, @FACTOR_CAMBIO DECIMAL(16,6), @OPERADOR VARCHAR(2)

	DECLARE @TEMPR TABLE (
		CORR_PARTIDA_DETA INT,
		CUENTA_CONTABLE VARCHAR(30),
		CORR_AUXILIAR INT,
		CORR_CENTRO_COSTO INT,
		NOMBRE_TRAN VARCHAR(255),
		MONTO_CARGO DECIMAL(18,2),
		MONTO_ABONO DECIMAL(18,2)
	)

	DECLARE @CORR_PARTIDA_DETA INT,
		@CUENTA_CONTABLE VARCHAR(30),
		@CORR_AUXILIAR INT,
		@CORR_CENTRO_COSTO INT,
		@NOMBRE_TRAN VARCHAR(255),
		@MONTO_CARGO DECIMAL(18,2),
		@MONTO_ABONO DECIMAL(18,2)

BEGIN
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = '', @SYS_FILAS_AFECTADAS = 0

	BEGIN TRY
		SELECT @FECHA_CONSULTA = CONVERT(DATE, LTRIM(RTRIM(CONVERT(VARCHAR, @ANIO_PERIODO))) + '-' + LTRIM(RTRIM(CONVERT(VARCHAR, @MES_PERIODO))) + '-31'),
			@NOMBRE_PARTIDA = 'LIQUIDACION ANUAL CUENTAS DE RESULTADO ' + CONVERT(VARCHAR(4), @ANIO_PERIODO),
			@FECHA_CREA = GETDATE(),
			@FACTOR_CAMBIO = 1,
			@OPERADOR = '*'

		SELECT TOP 1 @CORR_CLASE_PARTIDA = CORR_CLASE_PARTIDA
		FROM CON_CLASE_PARTIDA A
		WHERE A.CORR_EMPRESA = @CORR_EMPRESA
		  AND A.PARTIDA_CIERRE = 1

		SELECT TOP 1 @CORR_MONEDA = CORR_MONEDA
		FROM CON_PARAMETRO
		WHERE CORR_EMPRESA = @CORR_EMPRESA

		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL_AUXILIAR
			@CORR_EMPRESA,
			@FECHA_CONSULTA,
			2,
			0,
			NULL,
			NULL,
			1,
			0,
			0,
			0,
			NULL

		EXEC PRAL_MTTO_CON_PARTIDA
			1,
			@CORR_EMPRESA,
			@ANIO_PERIODO,
			@MES_PERIODO,
			@CORR_CLASE_PARTIDA,
			@CORR_PARTIDA OUTPUT,
			@FECHA_CONSULTA,
			0,
			@NOMBRE_PARTIDA,
			'DI',
			'LIQ',
			@CORR_MONEDA,
			@FACTOR_CAMBIO,
			@OPERADOR,
			@SYS_LOGIN_USUARIO,
			@FECHA_CREA,
			@SYS_ESTACION,
			@SYS_LOGIN_USUARIO,
			@FECHA_CREA,
			@SYS_ESTACION,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS OUTPUT,
			@SYS_NUMERO_ERROR OUTPUT,
			@SYS_MENSAJE_ERROR OUTPUT

		INSERT INTO @TEMPR
		(CORR_PARTIDA_DETA, CUENTA_CONTABLE, CORR_AUXILIAR, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
		SELECT ROW_NUMBER() OVER (ORDER BY CASE WHEN B.CLASE_RUBRO = 'IN' THEN 0 ELSE 1 END, A.CUENTA_CONTABLE) CORR_PARTIDA_DETA,
			A.CUENTA_CONTABLE,
			A.CORR_AUXILIAR,
			NULL CORR_CENTRO_COSTO,
			@NOMBRE_PARTIDA NOMBRE_TRAN,
			CASE WHEN ISNULL(A.ES_HABER, 0) = 1 AND ISNULL(A.SALDO_FINAL, 0) > 0 THEN ABS(ISNULL(A.SALDO_FINAL, 0)) ELSE CASE WHEN (ISNULL(A.ES_DEBE, 0) = 1 AND ISNULL(A.SALDO_FINAL, 0) < 0) THEN ABS(ISNULL(A.SALDO_FINAL, 0)) ELSE 0 END END MONTO_CARGO,
			CASE WHEN ISNULL(A.ES_DEBE, 0) = 1 AND ISNULL(A.SALDO_FINAL, 0) > 0 THEN ABS(ISNULL(A.SALDO_FINAL, 0)) ELSE CASE WHEN (ISNULL(A.ES_HABER, 0) = 1 AND ISNULL(A.SALDO_FINAL, 0) < 0) THEN ABS(ISNULL(A.SALDO_FINAL, 0)) ELSE 0 END END MONTO_ABONO
		FROM @SALDO A
		INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CUENTA_CONTABLE = B.CUENTA_CONTABLE
		WHERE A.SALDO_FINAL <> 0
		  AND B.ES_DETALLE = 1

		SELECT @CUENTA_CONTABLE_PERDIDA = A.CUENTA_CONTABLE_PERDIDA, @CUENTA_CONTABLE_GANANCIA = A.CUENTA_CONTABLE_GANANCIA
		FROM CON_PARAMETRO A
		WHERE A.CORR_EMPRESA = @CORR_EMPRESA

		SELECT @DIF = SUM(CASE WHEN ISNULL(A.ES_HABER, 0) = 1 THEN ISNULL(A.SALDO_FINAL, 0) ELSE 0 END)
		              - SUM(CASE WHEN ISNULL(A.ES_DEBE, 0) = 1 THEN ISNULL(A.SALDO_FINAL, 0) ELSE 0 END)
		FROM @SALDO A
		INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CUENTA_CONTABLE = B.CUENTA_CONTABLE
		WHERE A.SALDO_FINAL <> 0
		  AND B.ES_DETALLE = 1

		IF @DIF <> 0
		BEGIN
			INSERT INTO @TEMPR
			(CORR_PARTIDA_DETA, CUENTA_CONTABLE, CORR_AUXILIAR, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
			SELECT ISNULL(MAX(CORR_PARTIDA_DETA), 0) + 1 CORR_PARTIDA_DETA,
				CASE WHEN @DIF > 0 THEN @CUENTA_CONTABLE_GANANCIA ELSE @CUENTA_CONTABLE_PERDIDA END CUENTA_CONTABLE,
				NULL CORR_AUXILIAR,
				NULL CORR_CENTRO_COSTO,
				@NOMBRE_PARTIDA NOMBRE_TRAN,
				CASE WHEN @DIF < 0 THEN ABS(@DIF) ELSE 0 END MONTO_CARGO,
				CASE WHEN @DIF > 0 THEN ABS(@DIF) ELSE 0 END MONTO_ABONO
			FROM @TEMPR
		END

		WHILE EXISTS (SELECT 1 FROM @TEMPR)
		BEGIN
			SELECT TOP 1 @CORR_PARTIDA_DETA = CORR_PARTIDA_DETA,
				@CUENTA_CONTABLE = CUENTA_CONTABLE,
				@CORR_AUXILIAR = CORR_AUXILIAR,
				@CORR_CENTRO_COSTO = CORR_CENTRO_COSTO,
				@MONTO_CARGO = MONTO_CARGO,
				@MONTO_ABONO = MONTO_ABONO,
				@NOMBRE_TRAN = NOMBRE_TRAN
			FROM @TEMPR

			EXEC PRAL_MTTO_CON_PARTIDA_DETA
				1,
				@CORR_EMPRESA,
				@ANIO_PERIODO,
				@MES_PERIODO,
				@CORR_CLASE_PARTIDA,
				@CORR_PARTIDA,
				0,
				@CUENTA_CONTABLE,
				@CORR_CENTRO_COSTO,
				@MONTO_CARGO,
				@MONTO_ABONO,
				@NOMBRE_TRAN,
				0,
				0,
				@FACTOR_CAMBIO,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@SYS_FILAS_AFECTADAS OUTPUT,
				@SYS_NUMERO_ERROR OUTPUT,
				@SYS_MENSAJE_ERROR OUTPUT,
				@CORR_AUXILIAR

			DELETE FROM @TEMPR
			WHERE CORR_PARTIDA_DETA = @CORR_PARTIDA_DETA
		END

		SELECT @SYS_FILAS_AFECTADAS = @@ROWCOUNT
	END TRY
	BEGIN CATCH
		DECLARE @CORR_BITACORA INT, @SEVERITY_ERROR INT, @ESTADO_ERROR INT,
		        @ORIGEN_ERROR NVARCHAR(126), @LINEA_ERROR INT, @SYS_FECHA DATETIME

		SELECT @CORR_BITACORA = 0,
			@SYS_NUMERO_ERROR = ERROR_NUMBER(),
			@SEVERITY_ERROR = ERROR_SEVERITY(),
			@ESTADO_ERROR = ERROR_STATE(),
			@ORIGEN_ERROR = ERROR_PROCEDURE(),
			@LINEA_ERROR = ERROR_LINE(),
			@SYS_MENSAJE_ERROR = ERROR_MESSAGE(),
			@SYS_FECHA = GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1, @CORR_BITACORA OUTPUT, 'PM', @SYS_NUMERO_ERROR, @SEVERITY_ERROR, @ESTADO_ERROR, @ORIGEN_ERROR, @LINEA_ERROR, @SYS_MENSAJE_ERROR, @SYS_LOGIN_USUARIO, @SYS_FECHA, @SYS_ESTACION
	END CATCH
FINA:
END
GO
