SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_APLICAR_SOLICITUD]
(
		@CORR_EMPRESA int,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_TIPO_MOVIMIENTO int,
	@CORR_DOCUMENTO int OUTPUT,
	@CORR_CUENTA_BANCO int,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output,
	@GENERA_DETALLE BIT = 1
)
AS
	DECLARE @MONTO_CARGO DECIMAL(12,2), @MONTO_ABONO DECIMAL(12,2),@CUENTA_CONTABLE_BANCO VARCHAR(30)
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		DECLARE @CLASE_TIPO_CHEQUE VARCHAR(3), 
				@ESTADO_DOCUMENTO varchar(2), 
				@ANIO_PERIODO_CHEQUE int, 
				@MES_PERIODO_CHEQUE int, 
				@CORR_TIPO_MOVIMIENTO_CHEQUE int, 
				@CORR_DOCUMENTO_CHEQUE int, 
				@FECHA_EMISION date,
				@SOLICITADO_POR varchar(30), 
				@FECHA_SOLICITADO date,
				@NUMERO_DOCUMENTO bigint,
				@NOMBRE_PARTIDA varchar(1000),
				@CORR_PROVEEDOR int,
				@CORR_EMPLEADO int,
				@CORR_CLIENTE int,
				@NOMBRE_BENEFICIARIO varchar(255),
				@MONTO_DOCUMENTO decimal(18,2),
				@FECHA_APLICADO date,
				@CANTIDAD_LETRAS varchar(255),
				@CORR_TIPO_CHEQUE int,
				@USUARIO_ACTU varchar(30),
				@FECHA_ACTU datetime,
				@ESTACION_ACTU varchar(30),
				@CORR_MONEDA INT
				
	
		SELECT @ESTADO_DOCUMENTO=ESTADO_DOCUMENTO, @USUARIO_ACTU=@SYS_LOGIN_USUARIO,
				@FECHA_ACTU=GETDATE(),@ESTACION_ACTU=@SYS_ESTACION
		FROM BAN_SOLI_CHEQUE 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND ANIO_PERIODO=@ANIO_PERIODO 
		AND MES_PERIODO=@MES_PERIODO 
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO
		
		IF @ESTADO_DOCUMENTO <> 'SO'
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='No se puede autorizar esta solicitud.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END	
		
		--Verificando la cuenta bancaria
		IF (@CORR_CUENTA_BANCO IS NULL
		   OR NOT EXISTS(SELECT 1 FROM BAN_CUENTA_BANCARIA
		                 WHERE CORR_EMPRESA=@CORR_EMPRESA
		                 AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO))
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe la cuenta bancaria seleccionada',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END
		
		SELECT @CORR_TIPO_MOVIMIENTO_CHEQUE=CORR_TIPO_MOVIMIENTO
		FROM V_BAN_TIPO_MOVI_BANCARIO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CLASE_MOVIMIENTO='CHQ'	
		
		IF ISNULL(@CORR_TIPO_MOVIMIENTO_CHEQUE,'')=''
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='No está configurado el tipo de movimiento de cheque.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END						
		
		SELECT @ANIO_PERIODO_CHEQUE=YEAR(FECHA_EMISION),@MES_PERIODO_CHEQUE=MONTH(FECHA_EMISION),@FECHA_EMISION=FECHA_EMISION,
		@CORR_DOCUMENTO_CHEQUE=0,
		@NUMERO_DOCUMENTO=NUMERO_DOCUMENTO,@NOMBRE_PARTIDA=NOMBRE_PARTIDA,@CORR_PROVEEDOR=CORR_PROVEEDOR,@CORR_EMPLEADO=CORR_EMPLEADO,
		@CORR_CLIENTE=CORR_CLIENTE,@NOMBRE_BENEFICIARIO=NOMBRE_BENEFICIARIO,@MONTO_DOCUMENTO=MONTO_DOCUMENTO,@SOLICITADO_POR=SOLICITADO_POR,
		@FECHA_APLICADO=GETDATE(),@CANTIDAD_LETRAS=CANTIDAD_LETRAS,@CORR_TIPO_CHEQUE=CORR_TIPO_CHEQUE 
		FROM BAN_SOLI_CHEQUE 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND ANIO_PERIODO=@ANIO_PERIODO 
		AND MES_PERIODO=@MES_PERIODO 
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO	
		
		DECLARE @HECHO_POR VARCHAR(30)
		SELECT @HECHO_POR=NOMBRE_USUARIO 
		FROM SEG_USUARIO 
		WHERE LOGIN_SISTEMA=@SYS_LOGIN_USUARIO 
		
		--Validando la fecha del movimiento
		IF NOT dbo.BAN_ES_FECHA_VALIDA(@CORR_SUSCRIPCION, @CORR_CONFI_PAIS, @CORR_EMPRESA, @FECHA_EMISION) = 1
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No se permiten movimientos bancarios después de la fecha de cierre.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA		
		END
		
		SELECT @CORR_MONEDA=A.CORR_MONEDA
		FROM GEN_EMPRESA A
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
	
		EXEC PRAL_MTTO_BAN_DOCUMENTO 1, @CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_EMPRESA,@ANIO_PERIODO_CHEQUE,
		@MES_PERIODO_CHEQUE,@CORR_TIPO_MOVIMIENTO_CHEQUE,@CORR_DOCUMENTO_CHEQUE OUTPUT,@CORR_CUENTA_BANCO,@NUMERO_DOCUMENTO,@FECHA_EMISION,
		@NOMBRE_PARTIDA,@CORR_PROVEEDOR,@CORR_EMPLEADO,@CORR_CLIENTE,@NOMBRE_BENEFICIARIO,@MONTO_DOCUMENTO,'DI',0,
		@SOLICITADO_POR,@HECHO_POR,@HECHO_POR,NULL,NULL,@FECHA_APLICADO,@FECHA_APLICADO,NULL,@CANTIDAD_LETRAS,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU,
		@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU,NULL,NULL,@CORR_TIPO_CHEQUE,0,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,@SYS_LOGIN_USUARIO,@SYS_ESTACION,
		@SYS_FILAS_AFECTADAS OUTPUT,@SYS_NUMERO_ERROR OUTPUT,@SYS_MENSAJE_ERROR OUTPUT, 0, @CORR_MONEDA,1,'*'
		
		IF @SYS_NUMERO_ERROR = 0
		BEGIN
			DECLARE @TEMP1 TABLE (CORR_DOCUMENTO_DETA INT, CUENTA_CONTABLE VARCHAR(30), CORR_CENTRO_COSTO INT, NOMBRE_TRAN VARCHAR(1255), MONTO_CARGO DECIMAL(12,2), MONTO_ABONO DECIMAL(12,2), MONTO_CARGO_FORANEA DECIMAL(12,2), MONTO_ABONO_FORANEA DECIMAL(12,2),CORR_AUXILIAR INT, ESTA_PROC INT)
			DECLARE @CONTADOR INT, @CANTIDAD_REGISTROS INT, @CORR_DOCUMENTO_DETA INT, @CUENTA_CONTABLE VARCHAR(30), @CORR_CENTRO_COSTO INT, @NOMBRE_TRAN VARCHAR(1255),@CORR_AUXILIAR INT,@MONTO_CARGO_FORANEA DECIMAL(18,2),@MONTO_ABONO_FORANEA DECIMAL(18,2)
			
			INSERT INTO @TEMP1 
			SELECT CORR_DOCUMENTO_DETA,CUENTA_CONTABLE,CORR_CENTRO_COSTO,NOMBRE_TRAN,MONTO_CARGO,MONTO_ABONO,MONTO_CARGO_FORANEA,MONTO_ABONO_FORANEA,CORR_AUXILIAR,0 
			FROM BAN_SOLI_CHEQUE_DETA 
			WHERE CORR_EMPRESA=@CORR_EMPRESA 
			AND ANIO_PERIODO=@ANIO_PERIODO 
			AND MES_PERIODO=@MES_PERIODO 
			AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO 
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			
			SELECT @CONTADOR=0, @CANTIDAD_REGISTROS=COUNT(*) FROM @TEMP1	
			
			WHILE (@CONTADOR<@CANTIDAD_REGISTROS)
			BEGIN
				SELECT TOP 1 @CORR_DOCUMENTO_DETA=CORR_DOCUMENTO_DETA, @CUENTA_CONTABLE=CUENTA_CONTABLE, @CORR_CENTRO_COSTO=CORR_CENTRO_COSTO,@NOMBRE_TRAN=NOMBRE_TRAN,@MONTO_CARGO=MONTO_CARGO,@MONTO_ABONO=MONTO_ABONO,@CORR_AUXILIAR=CORR_AUXILIAR
				,@MONTO_CARGO_FORANEA=MONTO_CARGO_FORANEA,@MONTO_ABONO_FORANEA=MONTO_ABONO_FORANEA
				FROM @TEMP1 WHERE ESTA_PROC=0
				
				EXEC PRAL_MTTO_BAN_DOCUMENTO_DETA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_EMPRESA,@ANIO_PERIODO_CHEQUE,@MES_PERIODO_CHEQUE,@CORR_TIPO_MOVIMIENTO_CHEQUE,@CORR_DOCUMENTO_CHEQUE,0,@CUENTA_CONTABLE,@CORR_CENTRO_COSTO,@NOMBRE_TRAN,@MONTO_CARGO,@MONTO_ABONO,@CORR_AUXILIAR,@SYS_LOGIN_USUARIO,@SYS_ESTACION,@SYS_FILAS_AFECTADAS OUTPUT,@SYS_NUMERO_ERROR OUTPUT,@SYS_MENSAJE_ERROR OUTPUT,@MONTO_CARGO_FORANEA,@MONTO_ABONO_FORANEA
				IF @SYS_MENSAJE_ERROR = 0
				BEGIN
					SELECT @CONTADOR+=1
					UPDATE @TEMP1 SET ESTA_PROC=1
					WHERE CORR_DOCUMENTO_DETA=@CORR_DOCUMENTO_DETA
				END 
			END
			
			EXEC PRAL_MTTO_BAN_DOCUMENTO_APLICAR @CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_EMPRESA,@ANIO_PERIODO_CHEQUE,@MES_PERIODO_CHEQUE,@CORR_TIPO_MOVIMIENTO_CHEQUE,
			@CORR_DOCUMENTO_CHEQUE,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU,@SYS_LOGIN_USUARIO,@SYS_ESTACION,@SYS_FILAS_AFECTADAS OUTPUT,@SYS_NUMERO_ERROR OUTPUT,@SYS_MENSAJE_ERROR OUTPUT
			
			IF @SYS_NUMERO_ERROR = 0
			BEGIN
				UPDATE BAN_SOLI_CHEQUE SET
				ESTADO_DOCUMENTO='AP', FECHA_APLICADO=@FECHA_APLICADO, ANIO_PERIODO_CHEQUE=@ANIO_PERIODO_CHEQUE,
				MES_PERIODO_CHEQUE=@MES_PERIODO_CHEQUE, CORR_TIPO_MOVIMIENTO_CHEQUE=@CORR_TIPO_MOVIMIENTO_CHEQUE,CORR_DOCUMENTO_CHEQUE=@CORR_DOCUMENTO_CHEQUE,
				CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
				WHERE CORR_EMPRESA=@CORR_EMPRESA 
				AND ANIO_PERIODO=@ANIO_PERIODO 
				AND MES_PERIODO=@MES_PERIODO 
				AND CORR_DOCUMENTO=@CORR_DOCUMENTO 
				
				UPDATE COM_PAGO SET
				ANIO_PERIODO_CHEQUE=@ANIO_PERIODO_CHEQUE,
				MES_PERIODO_CHEQUE=@MES_PERIODO_CHEQUE,
				CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO_CHEQUE,
				CORR_DOCUMENTO_CHEQUE=@CORR_DOCUMENTO_CHEQUE 
				WHERE CORR_EMPRESA=@CORR_EMPRESA 
				AND ANIO_PERIODO_SOLI_CHEQUE=@ANIO_PERIODO 
				AND MES_PERIODO_SOLI_CHEQUE=@MES_PERIODO 
				AND CORR_TIPO_MOVIMIENTO_SOLI_CHEQUE=@CORR_TIPO_MOVIMIENTO 
				AND CORR_DOCUMENTO_SOLI_CHEQUE=@CORR_DOCUMENTO 
				
				UPDATE BAN_LIQUI_CAJA_CHICA SET
				ANIO_PERIODO_CHEQUE=@ANIO_PERIODO_CHEQUE,
				MES_PERIODO_CHEQUE=@MES_PERIODO_CHEQUE,
				CORR_TIPO_MOVIMIENTO_CHEQUE=@CORR_TIPO_MOVIMIENTO_CHEQUE,
				CORR_DOCUMENTO_CHEQUE=@CORR_DOCUMENTO_CHEQUE 
				WHERE CORR_EMPRESA=@CORR_EMPRESA 
				AND ANIO_PERIODO_SOLI_CHEQUE=@ANIO_PERIODO 
				AND MES_PERIODO_SOLI_CHEQUE=@MES_PERIODO 
				AND CORR_TIPO_MOVIMIENTO_SOLI_CHEQUE=@CORR_TIPO_MOVIMIENTO 
				AND CORR_DOCUMENTO_SOLI_CHEQUE=@CORR_DOCUMENTO 			
			END
			ELSE
			BEGIN
				--SE ELIMINA EL CHEQUE GENERADO
				DELETE FROM BAN_DOCUMENTO_DETA 
				WHERE CORR_EMPRESA=@CORR_EMPRESA
				AND ANIO_PERIODO=@ANIO_PERIODO_CHEQUE
				AND MES_PERIODO=@MES_PERIODO_CHEQUE
				AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO_CHEQUE
				AND CORR_DOCUMENTO=@CORR_DOCUMENTO_CHEQUE
				
				DELETE FROM BAN_DOCUMENTO
				WHERE CORR_EMPRESA=@CORR_EMPRESA
				AND ANIO_PERIODO=@ANIO_PERIODO_CHEQUE
				AND MES_PERIODO=@MES_PERIODO_CHEQUE
				AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO_CHEQUE
				AND CORR_DOCUMENTO=@CORR_DOCUMENTO_CHEQUE
		
			END				
		END		
		
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()
		
		-- bitacora omitida
FINA:
END

GO
