SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================================================
-- Procedimiento: dbo.PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO
-- Qué hace: entrega datos para PDF Formato corto del Descriptor de puesto.
-- Cómo:
--   1) Result set 1: encabezado (V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_IMPR).
--   2) Result set 2: encabezado/logos desde GEN_EMPRESA (GEN_PARAMETRO en Crystal).
--   3) Result set 3: funciones agregadas (V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_FUNCIONES_IMPR).
--   4) Result set 4: indicadores (V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_KPI_IMPR).
--   5) Result set 5: responsabilidades (V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_RESPONSABILIDAD_CARGO_IMPR;
--      vista filtra APLICA_DESCRIPTOR CORTO/AMBOS; SP filtra por descriptor).
-- Alcance: solo Formato corto. El Formato extenso tiene su propio SP y vistas _IMPR.
-- Uso API: SC_DESCRIPTOR_PUESTO/getPDFFormatoCorto → SGUEES-RPT SelectionHiring.
-- =============================================================================
CREATE OR ALTER PROCEDURE [dbo].[PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO]
(
	@CORR_EMPRESA INT,
	@CORR_DESCRIPTOR_PUESTO INT
)
AS
BEGIN
	SET NOCOUNT ON;

	-- Result set 1: encabezado del descriptor (1 fila).
	SELECT
		A.CORR_EMPRESA,
		A.CORR_DESCRIPTOR_PUESTO,
		A.CODIGO_DESCRIPTOR_PUESTO,
		A.FECHA_EMISION,
		A.FECHA_REVISION,
		A.OBJETIVO_PUESTO,
		A.NUM_PERSONAL_CARGO,
		A.CORR_PUESTO,
		A.NOMBRE_PUESTO,
		A.CORR_UNIDAD,
		A.NOMBRE_UNIDAD,
		A.CORR_PUESTO_REPORTA,
		A.NOMBRE_EMPLEADO_REPORTA,
		A.CORR_IMPACTO_ECONOMICO,
		A.DESCRIPCION_IMPACTO_ECONOMICO,
		A.RESPONSABLE,
		A.FORMATO,
		A.VERSION,
		A.CORR_ESTADO,
		A.NOMBRE_ESTADO,
		A.USUARIO_CREA,
		A.ESTACION_CREA,
		A.FECHA_CREA,
		A.USUARIO_ACTU,
		A.ESTACION_ACTU,
		A.FECHA_ACTU
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_IMPR A
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA
	  AND A.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO;

	-- Result set 2: logos (GEN_PARAMETRO en Crystal).
	SELECT
		A.CORR_EMPRESA,
		A.NOMBRE_EMPRESA,
		CAST('' AS VARCHAR(100)) AS PERIODO,
		A.LOGO_1 AS LOGO1,
		A.LOGO_2 AS LOGO2,
		CAST(N'Descriptor de Puesto - Formato corto' AS VARCHAR(150)) AS TITULO_REPORTE,
		CAST('' AS VARCHAR(100)) AS NOMBRE_SISTEMA,
		GETDATE() AS FECHA_IMPRESION
	FROM dbo.GEN_EMPRESA A
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA;

	-- Result set 3: funciones CLAVE y SECUNDARIA agregadas (1 fila).
	SELECT
		F.CORR_EMPRESA,
		F.CORR_DESCRIPTOR_PUESTO,
		F.LISTA_FUNCIONES_CLAVE,
		F.LISTA_FUNCIONES_SECUNDARIA
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_FUNCIONES_IMPR F
	WHERE F.CORR_EMPRESA = @CORR_EMPRESA
	  AND F.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO;

	-- Result set 4: indicadores de desempeño (1 fila por KPI).
	SELECT
		K.CORR_EMPRESA,
		K.CORR_DESCRIPTOR_PUESTO,
		K.CORR_KPI_FUNCION,
		K.NOMBRE_INDICADOR,
		K.META,
		K.CORR_FRECUENCIA,
		K.NOMBRE_FRECUENCIA
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_KPI_IMPR K
	WHERE K.CORR_EMPRESA = @CORR_EMPRESA
	  AND K.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY K.CORR_KPI_FUNCION;

	-- Result set 5: responsabilidades del cargo (subinforme; vista ya filtra CORTO/AMBOS).
	SELECT
		R.CORR_EMPRESA,
		R.CORR_DESCRIPTOR_PUESTO,
		R.CORR_RESPONSABILIDAD,
		R.NOMBRE_RESPONSABILIDAD,
		R.INFORMACION,
		R.APLICA_DESCRIPTOR
	FROM dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_RESPONSABILIDAD_CARGO_IMPR R
	WHERE R.CORR_EMPRESA = @CORR_EMPRESA
	  AND R.CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	ORDER BY R.CORR_RESPONSABILIDAD;
END
GO
