SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_IMPR_CON_INVENTARIO]
( 
  --@CORR_EMPRESA INT,
  @CORR_EMPRESAS VARCHAR(255), 
  @FECHA_FINAL DATE,
  @NIVEL SMALLINT,
  @PARTIDA_CIERRE BIT=0,
  @PARTIDA_LIQUIDACION BIT=0,
  @CORR_MONEDA INT=NULL,
  @FOLIADO BIT=0,
  @NUMERO_FOLIO INT=0,
  @CUENTA_A_CERO BIT=0,
  @MUESTRA_FIRMA BIT=0
)
AS	
	DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),
		CUENTA_MAYOR varchar(30),
		CORR_AUXILIAR INT,
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(18,2),
		CARGO_PERIODO DECIMAL(18,2),
		ABONO_PERIODO DECIMAL(18,2),
		SALDO_FINAL	DECIMAL(18,2)
	)
	DECLARE @SALDO_AUXILIAR_FORANEA TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),
		CUENTA_MAYOR varchar(30),
		CORR_AUXILIAR INT,
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(18,2),
		CARGO_PERIODO DECIMAL(18,2),
		ABONO_PERIODO DECIMAL(18,2),
		SALDO_FINAL	DECIMAL(18,2)
	)
	DECLARE @LIBRO_INVENTARIO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE VARCHAR(30),
		NOMBRE_CUENTA VARCHAR(100),
		CORR_AUXILIAR INT,
		NOMBRE_AUXILIAR VARCHAR(100),
		CODIGO_RUBRO VARCHAR(30),
		NOMBRE_RUBRO VARCHAR(100),
		SALDO_INICIAL DECIMAL(18,2),
		CARGO_PERIODO DECIMAL(18,2),
		ABONO_PERIODO DECIMAL(18,2),
		SALDO_FINAL DECIMAL(18,2),
		NIVEL INT,
		DESCRIPCION_MONEDA VARCHAR(255),
		FOLIADO BIT,
		NUMERO_FOLIO INT,
		DESCRIPCION_PUESTO2 VARCHAR(100),
		FECHA_FINAL DATE,
		NOMBRE_PAIS VARCHAR(100),
		MUESTRA_FIRMA BIT
	)

	DECLARE @CORR_MONEDA_LOCAL INT, @CORR_MONEDA_FORANEA INT	
	
	DECLARE @DESCRIPCION_MONEDA VARCHAR(255), @NOMBRE_PAIS VARCHAR(100),@PERDIDA_GANA DECIMAL(12,2), @CUENTA_PERDIDA_GANA VARCHAR(30)	
BEGIN
    
    SET NOCOUNT ON
    
    --SELECT @FECHA_FINAL=DATEADD(DAY,-1,@FECHA_FINAL)
		
	DECLARE @EMPRESAS TABLE (CORR_EMPRESA INT, ESTA_PROC BIT)
    DECLARE @CUENTAS_SALDO TABLE(INT,CORR_EMPRESA INT,CUENTA_MAYOR VARCHAR(30),SALDO_INICIAL DECIMAL(12,2),CARGO_PERIODO DECIMAL(12,2),ABONO_PERIODO DECIMAL(12,2),SALDO_FINAL DECIMAL(12,2))

    INSERT INTO @EMPRESAS
    SELECT SUBSTRING(A.Data,1,CHARINDEX('-',A.Data)-1)
	,SUBSTRING(A.Data,CHARINDEX('-',A.Data)+1,LEN(A.Data)-CHARINDEX('-',A.Data))
	,0 ESTA_PROC
    FROM dbo.Split(@CORR_EMPRESAS,',') A
    DECLARE @CORR_EMPRESA INT
    
    WHILE EXISTS (SELECT 1 FROM @EMPRESAS WHERE ESTA_PROC=0)
	BEGIN
		SELECT TOP 1 @CORR_EMPRESA=CORR_EMPRESA
		
		FROM @EMPRESAS
		WHERE ESTA_PROC=0
		
		SELECT @CORR_MONEDA_LOCAL=CORR_MONEDA
		FROM GEN_EMPRESA
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		
		SELECT @CORR_MONEDA_FORANEA=CORR_MONEDA_INTER
		FROM GEN_PARAMETRO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		
		IF @CORR_MONEDA IS NULL
			SELECT @CORR_MONEDA=@CORR_MONEDA_LOCAL	
		
		
		IF @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL
		BEGIN
			 --Obtener el saldo de todas las cuentas de un nivel hasta antes de la fecha de consulta
			INSERT INTO @SALDO
			EXEC PRAL_GENE_CON_SALDO_INICIAL_AUXILIAR 
			@CORR_EMPRESA,
			@FECHA_FINAL,
			0,--OPCION_CONSULTA= --Obtener el saldo de todas las cuentas de un nivel hasta antes de la fecha de consulta
			1,--MAYORIZA=Mayoriza los saldo
			NULL,
			NULL,
			1, --Aplicar el debe o haber de la cuenta
			@PARTIDA_CIERRE, --Incluir partidas de cierre
			@PARTIDA_LIQUIDACION, --Incluir partidas de liquidaciÃ³n
			@NIVEL --Hasta el nivel indicado

			INSERT INTO @SALDO_AUXILIAR_FORANEA
			EXEC PRAL_GENE_CON_SALDO_INICIAL_AUXILIAR_FORANEA
			@CORR_EMPRESA,
			@FECHA_FINAL,
			0,--OPCION_CONSULTA=Saldo de todas las cuentas contables hasta la fecha de consulta inclusive
			1,--MAYORIZA=Mayoriza los saldo
			'',--CUENTA_CONTABLE_INICIAL=Sin cuenta inicial
			NULL,--CUENTA AUXILIAR		
			0, --No aplicar el debe o haber de la cuenta solo sumar los cargos y restar los abonos
			0,--@PARTIDA_CIERRE
			0,--@PARTIDA_LIQUIDACION
			0 --Todos los niveles
		END ELSE
		IF @CORR_MONEDA=@CORR_MONEDA_FORANEA
		BEGIN
			 --Obtener el saldo de todas las cuentas de un nivel hasta antes de la fecha de consulta
			INSERT INTO @SALDO
			EXEC PRAL_GENE_CON_SALDO_INICIAL_AUXILIAR_FORANEA
			@CORR_EMPRESA,
			@FECHA_FINAL,
			0,--OPCION_CONSULTA= --Obtener el saldo de todas las cuentas de un nivel hasta antes de la fecha de consulta
			1,--MAYORIZA=Mayoriza los saldo
			NULL,
			NULL,
			1, --Aplicar el debe o haber de la cuenta
			@PARTIDA_CIERRE, --Incluir partidas de cierre
			@PARTIDA_LIQUIDACION, --Incluir partidas de liquidaciÃ³n
			@NIVEL --Hasta el nivel indicado
		END
			
		
		UPDATE @EMPRESAS SET
		ESTA_PROC=1
		WHERE CORR_EMPRESA=@CORR_EMPRESA
	END
    	
	SELECT TOP 1 @CORR_EMPRESA=CORR_EMPRESA
	FROM @EMPRESAS
	ORDER BY CORR_EMPRESA	
	
	SELECT TOP 1 @CORR_EMPRESA=CORR_EMPRESA
	FROM @EMPRESAS
	ORDER BY CORR_EMPRESA
	
	 --Obteniendo la perdida o ganancia
    SELECT @PERDIDA_GANA=ISNULL(SUM(CASE WHEN B.CLASE_RUBRO='IN' THEN A.SALDO_FINAL ELSE A.SALDO_FINAL*-1 END),0)
    FROM @SALDO A
    INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
    WHERE B.CLASE_RUBRO IN('IN','GA')
    AND B.NIVEL=1
    
    IF @PERDIDA_GANA>=0 --Si es Ganancia
    BEGIN
	    SELECT @CUENTA_PERDIDA_GANA=ISNULL(A.CUENTA_CONTABLE_GANANCIA,'')
	    FROM CON_PARAMETRO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
    END ELSE --Si es Perdida
    BEGIN
	    SELECT @CUENTA_PERDIDA_GANA=ISNULL(A.CUENTA_CONTABLE_PERDIDA,'')
	    FROM CON_PARAMETRO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
    END
    
    --Obteniendo la cuenta segÃºn el nivel del reporte
    SELECT @CUENTA_PERDIDA_GANA=SUBSTRING(@CUENTA_PERDIDA_GANA,1,A.NUMERO_CARACTERES)
    FROM CON_RUBRO_NIVEL A
    INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CODIGO_RUBRO=B.CODIGO_RUBRO
    WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	AND A.NIVEL=@NIVEL
	AND B.CUENTA_CONTABLE=@CUENTA_PERDIDA_GANA
    
    --Actualizando el saldo de la perdida o ganancia
    UPDATE @SALDO SET
    SALDO_FINAL=ISNULL(SALDO_FINAL,0)+@PERDIDA_GANA
    WHERE CORR_EMPRESA=@CORR_EMPRESA
	AND @CUENTA_PERDIDA_GANA LIKE CUENTA_CONTABLE+'%'

	SELECT @NOMBRE_PAIS=B.NOMBRE_PAIS
	FROM GEN_EMPRESA A
	INNER JOIN GEN_PAIS B ON A.CORR_PAIS=B.CORR_PAIS
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	
	--Obteniendo en que moneda esta el balance general
	SELECT @DESCRIPCION_MONEDA=LTRIM(RTRIM(UPPER(ISNULL(B.DESCRIPCION_MONEDA,''))))
	FROM GEN_TIPO_MONEDA B 
	AND B.CORR_MONEDA=@CORR_MONEDA
	
	--Insertando las cuentas que sus hijos no tienen cero
	INSERT INTO @CUENTAS_SALDO
	(CORR_EMPRESA,CUENTA_MAYOR,SALDO_INICIAL,CARGO_PERIODO,ABONO_PERIODO,SALDO_FINAL)
	SELECT A.CORR_EMPRESA,A.CUENTA_MAYOR
		,SUM(CASE WHEN A.SALDO_INICIAL<>0 THEN 1 ELSE 0 END) SALDO_INICIAL
		,SUM(CASE WHEN A.CARGO_PERIODO<>0 THEN 1 ELSE 0 END) CARGO_PERIODO
		,SUM(CASE WHEN A.ABONO_PERIODO<>0 THEN 1 ELSE 0 END) ABONO_PERIODO
		,SUM(CASE WHEN A.SALDO_FINAL<>0 THEN 1 ELSE 0 END) SALDO_FINAL
	FROM @SALDO A
	GROUP BY A.CORR_EMPRESA,A.CUENTA_MAYOR

    INSERT INTO @LIBRO_INVENTARIO
    SELECT @CORR_EMPRESA CORR_EMPRESA
    ,ISNULL(D.PREFIJO,'')+A.CUENTA_CONTABLE AS CUENTA_CONTABLE
    ,B.NOMBRE_CUENTA
    ,ISNULL(E.CORR_AUXILIAR,0) CORR_AUXILIAR
    ,E.NOMBRE_AUXILIAR
    ,B.CODIGO_RUBRO
    ,F.NOMBRE_RUBRO
    ,SUM(A.SALDO_INICIAL) SALDO_INICIAL
    ,SUM(A.CARGO_PERIODO) CARGO_PERIODO
    ,SUM(A.ABONO_PERIODO) ABONO_PERIODO
    ,SUM(A.SALDO_FINAL) SALDO_FINAL
    ,B.NIVEL
	,@DESCRIPCION_MONEDA DESCRIPCION_MONEDA	    
	,@FOLIADO FOLIADO
	,@NUMERO_FOLIO NUMERO_FOLIO
	,D.DESCRIPCION_PUESTO2
    ,@FECHA_FINAL FECHA_FINAL
    ,@NOMBRE_PAIS NOMBRE_PAIS
    ,@MUESTRA_FIRMA MUESTRA_FIRMA
	FROM @SALDO A
	INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE	
	LEFT OUTER JOIN @CUENTAS_SALDO C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_MAYOR
	LEFT OUTER JOIN CON_PARAMETRO D ON A.CORR_EMPRESA=D.CORR_EMPRESA
	LEFT OUTER JOIN CON_CATALOGO_CUENTA_AUXI E ON A.CORR_EMPRESA=E.CORR_EMPRESA AND A.CUENTA_CONTABLE=E.CUENTA_CONTABLE AND A.CORR_AUXILIAR=E.CORR_AUXILIAR	
	INNER JOIN CON_RUBRO F ON B.CORR_EMPRESA=F.CORR_EMPRESA AND B.CODIGO_RUBRO=F.CODIGO_RUBRO	
	WHERE ((
		(C.SALDO_INICIAL<>0
		OR C.CARGO_PERIODO<>0
		OR C.ABONO_PERIODO<>0
		OR C.SALDO_FINAL<>0) --	Que las cuentas de mayor tengan al menos una cuenta de detalle diferente de cero
		OR (C.CUENTA_MAYOR IS NULL --Es el ultimo nivel seleccionado y que sea diferente a cero
		    AND A.SALDO_FINAL<>0--(A.SALDO_INICIAL<>0
				--OR A.CARGO_PERIODO<>0 
				--OR A.ABONO_PERIODO<>0 
				--OR A.SALDO_FINAL<>0) 
			)
		)
	OR @CUENTA_A_CERO=1) --Mostrar todas las cuentas aunque esten a cero
	AND B.CLASE_RUBRO IN('AC','PA','PT','LI')
    GROUP BY ISNULL(D.PREFIJO,'')
	,A.CUENTA_CONTABLE
    ,B.NOMBRE_CUENTA
    ,B.NIVEL 
    ,E.CORR_AUXILIAR
    ,E.NOMBRE_AUXILIAR 
    ,B.CODIGO_RUBRO
    ,F.NOMBRE_RUBRO
    ,D.DESCRIPCION_PUESTO2
	ORDER BY A.CUENTA_CONTABLE
    

	SELECT 
		A.CORR_EMPRESA,
		A.CUENTA_CONTABLE,
		A.NOMBRE_CUENTA,
		A.CORR_AUXILIAR,
		A.NOMBRE_AUXILIAR,
		D.NOMBRE_MONEDA,
		D.NOMBRE_PAIS NOMBRE_PAIS_CUENTA,
		D.NOMBRE_TIPO_CUENTA_BANCO,
		C.CLASE_AUXILIAR,
		A.CODIGO_RUBRO,
		A.NOMBRE_RUBRO,
		B.SALDO_INICIAL,
		B.CARGO_PERIODO,
		B.ABONO_PERIODO,
		B.SALDO_FINAL,
		CASE WHEN (D.CORR_MONEDA <> @CORR_MONEDA_LOCAL OR E.CORR_MONEDA<> @CORR_MONEDA_LOCAL) THEN G.SALDO_FINAL ELSE B.SALDO_FINAL END SALDO_FINAL_AUXILIAR,
		--A.SALDO_FINAL SALDO_FINAL_AUXILIAR,
		A.NIVEL,
		A.DESCRIPCION_MONEDA,
		A.FOLIADO,
		A.NUMERO_FOLIO,
		A.DESCRIPCION_PUESTO2,
		A.FECHA_FINAL,
		A.NOMBRE_PAIS,
		A.MUESTRA_FIRMA,
		D.NOMBRE_CORTO_MONEDA NOMBRE_CORTO_MONEDA_CB,
		D.NOMBRE_CORTO_PAIS NOMBRE_CORTO_PAIS_CB,
		E.NOMBRE_TIPO_INVERSION,
		E.NOMBRE_INVERSION,
		E.NOMBRE_CORTO_PAIS,
		E.NOMBRE_CORTO_MONEDA
	FROM @LIBRO_INVENTARIO A
	INNER JOIN (SELECT CORR_EMPRESA,CUENTA_CONTABLE,
					SUM(SALDO_INICIAL) SALDO_INICIAL,
					SUM(CARGO_PERIODO) CARGO_PERIODO,
					SUM(ABONO_PERIODO) ABONO_PERIODO,
					SUM(SALDO_FINAL) SALDO_FINAL
				FROM @LIBRO_INVENTARIO
				GROUP BY CORR_EMPRESA,CUENTA_CONTABLE) B 
	ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA_AUXI C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_CONTABLE AND A.CORR_AUXILIAR=C.CORR_AUXILIAR
	LEFT OUTER JOIN V_BAN_CUENTA_BANCARIA D ON C.CORR_EMPRESA=D.CORR_EMPRESA AND C.CORR_CUENTA_BANCO=D.CORR_CUENTA_BANCO
	LEFT OUTER JOIN V_BAN_INVERSION E ON C.CORR_EMPRESA=E.CORR_EMPRESA AND C.CORR_INVERSION=E.CORR_INVERSION
	INNER JOIN @SALDO_AUXILIAR_FORANEA G ON A.CORR_EMPRESA=G.CORR_EMPRESA AND A.CUENTA_CONTABLE=G.CUENTA_CONTABLE AND A.CORR_AUXILIAR=G.CORR_AUXILIAR 
	WHERE A.SALDO_FINAL <> 0
   
	DECLARE @NOMBRE_EMPRESA VARCHAR(255)
    SELECT @NOMBRE_EMPRESA = dbo.StrConcat(A.NOMBRE_EMPRESA+', ')
	FROM GEN_EMPRESA A
	INNER JOIN @EMPRESAS B ON A.CORR_EMPRESA=B.CORR_EMPRESA
	SELECT A.CORR_EMPRESA
	,SUBSTRING(@NOMBRE_EMPRESA,1,LEN(@NOMBRE_EMPRESA)-1) NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	--INNER JOIN @EMPRESAS B ON A.CORR_EMPRESA=B.CORR_EMPRESA
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO
