SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_SOLI_COTIZACION_SOLICITAR]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO INT,
	@CORR_SOLI_COTIZACION int OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
	DECLARE @PROVEEDORES TABLE(CORR_EMPRESA INT,ANIO_PERIODO INT,CORR_SOLI_COTIZACION INT,CORR_PROVEEDOR INT,CORR_CONDICION_PAGO INT,CORR_FORMA_PAGO INT,DETALLE_FORMA_PAGO VARCHAR(250), PRIMARY KEY(CORR_EMPRESA,ANIO_PERIODO,CORR_SOLI_COTIZACION,CORR_PROVEEDOR))
	DECLARE @CORR_PROVEEDOR INT,@CORR_COTIZACION INT,@CORR_COTIZACION_DETA INT=0,@CORR_CONDICION_PAGO INT=0,@CORR_FORMA_PAGO INT,@DETALLE_FORMA_PAGO VARCHAR(250),
	@ANIO_PERIODO_BITACORA INT=YEAR(GETDATE()), @CORR_BITACORA_TRANS INT=0, @FECHA_BITACORA DATE=GETDATE(), @LLAVE_TRANSACCION VARCHAR(250),@REFERENCIA_TRANSACCION VARCHAR(500), 
	@USUARIO_CREA_TRANS VARCHAR(50), @ESTACION_CREA_TRANS VARCHAR(50), @FECHA_CREA_TRANS DATETIME,@USUARIO_ACTU_TRANS VARCHAR(50), @ESTACION_ACTU_TRANS VARCHAR(50),
	@FECHA_ACTU_TRANS DATETIME, @USUARIO_CREA_BITACORA VARCHAR(50),@ESTACION_CREA_BITACORA VARCHAR(50), @FECHA_CREA_BITACORA DATETIME=GETDATE(),
	@CODIGO_OPCION VARCHAR(150)='COM_SOLI_COTIZACION',@CLASE_BITACORA VARCHAR(3)='SO', @CLASE_SOLI_COTIZA VARCHAR(2),@ANIO_PERIODO_COTIZACION INT=YEAR(GETDATE())
BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF NOT EXISTS(SELECT 1 
				  FROM COM_SOLI_COTIZACION_DETA 
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND ANIO_PERIODO=@ANIO_PERIODO
				  AND CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Debe de agregar un item a la solicitud para solicitar la cotización..',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF NOT EXISTS(SELECT 1 
				  FROM COM_SOLI_COTIZACION_PROVEEDOR 
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND ANIO_PERIODO=@ANIO_PERIODO
				  AND CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Debe asignar un proveedor para solicitar la cotización..',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF NOT EXISTS(SELECT 1 
				  FROM COM_SOLI_COTIZACION 
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND ANIO_PERIODO=@ANIO_PERIODO
				  AND CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
				  AND ESTADO_SOLI_COTIZACION='DI'
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Debe estar en digitado la solicitud para solicitar la cotización..',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF EXISTS(SELECT 1 
				  FROM COM_SOLI_COTIZACION A
				  INNER JOIN COM_SOLI_COTIZACION_PROVEEDOR B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION = B.CORR_SOLI_COTIZACION
				  LEFT OUTER JOIN V_COM_PROVEEDOR_USUARIO_SUM C ON B.CORR_PROVEEDOR = C.CORR_PROVEEDOR
				  LEFT OUTER JOIN COM_TIPO_SOLI_COTIZA D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.CORR_TIPO_SOLI_COTIZA = D.CORR_TIPO_SOLI_COTIZA
				  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
				  AND A.ANIO_PERIODO=@ANIO_PERIODO
				  AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
				  AND A.ESTADO_SOLI_COTIZACION='DI'
				  AND ISNULL(C.CORREO_ELECTRONICO,'')=''
				  --AND ISNULL(D.CLASE_SOLI_COTIZA,'NO')='NO'
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30003,@SYS_MENSAJE_ERROR='El usuario del proveedor debe tener especificado un correo electrónico',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		------------------------------------------------------------------------
		-------------  BITACORA -------------- 
		SELECT @LLAVE_TRANSACCION='Año: '+CONVERT(VARCHAR,A.ANIO_PERIODO) COLLATE DATABASE_DEFAULT+' Correlativo No.: '+CONVERT(VARCHAR,A.CORR_SOLI_COTIZACION) COLLATE DATABASE_DEFAULT,
				@REFERENCIA_TRANSACCION= ' Fecha: '+ CONVERT(VARCHAR,A.FECHA_SOLI_COTIZACION) COLLATE DATABASE_DEFAULT 
										+', Departemento: '+A.NOMBRE_DEPTO COLLATE DATABASE_DEFAULT
										+', Proveedor: '+A.NOMBRE_PROVEEDOR COLLATE DATABASE_DEFAULT
										+', Observaciones: '+A.OBSERVACIONES COLLATE DATABASE_DEFAULT,
				@USUARIO_CREA_TRANS=A.USUARIO_CREA, @ESTACION_CREA_TRANS=A.ESTACION_CREA, @FECHA_CREA_TRANS=A.FECHA_CREA,
				@USUARIO_ACTU_TRANS=A.USUARIO_ACTU, @ESTACION_ACTU_TRANS=A.ESTACION_ACTU, @FECHA_ACTU_TRANS=A.FECHA_ACTU
		FROM V_COM_SOLI_COTIZACION A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

		INSERT INTO @PROVEEDORES
		(
		    CORR_EMPRESA,
		    ANIO_PERIODO,
		    CORR_SOLI_COTIZACION,
		    CORR_PROVEEDOR,
			CORR_CONDICION_PAGO,
			CORR_FORMA_PAGO,
			DETALLE_FORMA_PAGO
		)
		SELECT 
		A.CORR_EMPRESA,
		A.ANIO_PERIODO,
		A.CORR_SOLI_COTIZACION,
		A.CORR_PROVEEDOR,
		A.CORR_CONDICION_PAGO,
		A.CORR_FORMA_PAGO,
		A.DETALLE_FORMA_PAGO
		FROM COM_SOLI_COTIZACION_PROVEEDOR A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
		AND NOT EXISTS (SELECT * FROM COM_COTIZACION B
						WHERE B.CORR_EMPRESA=A.CORR_EMPRESA
						AND B.ANIO_PERIODO_SOLI_COTI=A.ANIO_PERIODO
						AND B.CORR_SOLI_COTIZACION=A.CORR_SOLI_COTIZACION
						AND B.CORR_PROVEEDOR=A.CORR_PROVEEDOR)

		SELECT @CLASE_SOLI_COTIZA = B.CLASE_SOLI_COTIZA
		FROM COM_SOLI_COTIZACION A
		INNER JOIN COM_TIPO_SOLI_COTIZA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_SOLI_COTIZA = B.CORR_TIPO_SOLI_COTIZA
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

		WHILE EXISTS(SELECT 1 FROM @PROVEEDORES)
		BEGIN
			SELECT TOP (1) @CORR_PROVEEDOR=CORR_PROVEEDOR
			,@CORR_CONDICION_PAGO=CORR_CONDICION_PAGO
			,@CORR_FORMA_PAGO=CORR_FORMA_PAGO
			,@DETALLE_FORMA_PAGO=DETALLE_FORMA_PAGO
			FROM @PROVEEDORES

			SELECT @CORR_COTIZACION=ISNULL(MAX(CORR_COTIZACION),0)+1
			FROM COM_COTIZACION
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO_COTIZACION

			INSERT INTO COM_COTIZACION
			(
			    CORR_EMPRESA,
			    ANIO_PERIODO,
			    CORR_COTIZACION,
			    FECHA_COTIZACION,
			    CORR_PROVEEDOR,
			    USUARIO_COTIZA,
			    OBSERVACIONES,
			    OBSERVACIONES_PROVEEDOR,
			    PLAZO_ENTREGA,
			    ESTADO_COTIZACION,
			    ANIO_PERIODO_SOLI_COTI,
			    CORR_SOLI_COTIZACION,
			    USUARIO_CREA,
			    FECHA_CREA,
			    ESTACION_CREA,
			    USUARIO_ACTU,
			    FECHA_ACTU,
			    ESTACION_ACTU,
				CORR_CONDICION_PAGO,
				CORR_FORMA_PAGO,
				DETALLE_FORMA_PAGO
			)
			SELECT A.CORR_EMPRESA,
			@ANIO_PERIODO_COTIZACION,
			@CORR_COTIZACION,
			GETDATE(),
			@CORR_PROVEEDOR,
			'',
			A.OBSERVACIONES,
			'',
			'',
			'DI',
			A.ANIO_PERIODO,
			A.CORR_SOLI_COTIZACION,
			@SYS_LOGIN_USUARIO,
			GETDATE(),
			@SYS_LOGIN_USUARIO,
			@SYS_LOGIN_USUARIO,
			GETDATE(),
			@SYS_LOGIN_USUARIO,
			@CORR_CONDICION_PAGO,
			@CORR_FORMA_PAGO,
			@DETALLE_FORMA_PAGO
			FROM COM_SOLI_COTIZACION A
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

			INSERT INTO COM_COTIZACION_DETA
			(
			    CORR_EMPRESA,
			    ANIO_PERIODO,
			    CORR_COTIZACION,
			    CORR_COTIZACION_DETA,
			    CODIGO_ITEM,
			    CANTIDAD,
			    CORR_UNIDAD_MEDIDA,
			    PRECIO_UNITARIO,
			    MONTO_SUBTOTAL,
			    OBSERVACIONES,
			    MARCA,
			    ESTADO_SOLI_COTIZACION,
			    USUARIO_CREA,
			    FECHA_CREA,
			    ESTACION_CREA,
			    USUARIO_ACTU,
			    FECHA_ACTU,
			    ESTACION_ACTU
			)
			SELECT A.CORR_EMPRESA,
			@ANIO_PERIODO_COTIZACION,
			@CORR_COTIZACION,
			@CORR_COTIZACION_DETA +ROW_NUMBER() OVER(PARTITION BY @CORR_EMPRESA,@CORR_COTIZACION ORDER BY @CORR_EMPRESA,@CORR_COTIZACION),
			A.CODIGO_ITEM,
			A.CANTIDAD,
			A.CORR_UNIDAD_MEDIDA,
			CASE WHEN @CLASE_SOLI_COTIZA = 'EX' THEN ISNULL(A.PRECIO_UNITARIO,0) ELSE 0 END,
			CASE WHEN @CLASE_SOLI_COTIZA = 'EX' THEN ISNULL(A.MONTO_SUBTOTAL,0) ELSE 0 END,
			A.OBSERVACIONES,
			'',
			'DI',
			@SYS_LOGIN_USUARIO,
			GETDATE(),
			@SYS_LOGIN_USUARIO,
			@SYS_LOGIN_USUARIO,
			GETDATE(),
			@SYS_LOGIN_USUARIO
			FROM COM_SOLI_COTIZACION_DETA A
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

			UPDATE COM_SOLI_COTIZACION SET 
			ESTADO_SOLI_COTIZACION='SO'
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

			UPDATE COM_SOLI_COTIZACION_DETA SET 
			ESTADO_SOLI_COTIZACION='SO'
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

			UPDATE COM_COTIZACION SET 
			ESTADO_COTIZACION='SO'
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO_COTIZACION
			AND CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

			UPDATE A SET
			ESTADO_SOLI_COTIZACION='SO'
			FROM COM_COTIZACION_DETA A
			INNER JOIN COM_COTIZACION B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO AND A.CORR_COTIZACION = B.CORR_COTIZACION
			WHERE B.CORR_EMPRESA=@CORR_EMPRESA
			AND B.ANIO_PERIODO=@ANIO_PERIODO_COTIZACION
			AND B.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

			IF @CLASE_SOLI_COTIZA = 'EX'
			BEGIN
				EXEC PRAL_MTTO_COM_COTIZACION_APLICAR 
				@CORR_EMPRESA,
				@ANIO_PERIODO_COTIZACION,
				@CORR_COTIZACION OUTPUT,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@SYS_FILAS_AFECTADAS OUTPUT,
				@SYS_NUMERO_ERROR OUTPUT,
				@SYS_MENSAJE_ERROR OUTPUT
			END

			DELETE FROM @PROVEEDORES
			WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR
		END

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

		--Executando el procedimiento de la bitacora
		EXECUTE PRAL_MTTO_COM_BITACORA
		1,--@TIPO_ACTUALIZA ,                               
		@CORR_EMPRESA ,      
		@ANIO_PERIODO_BITACORA,
		@CORR_BITACORA_TRANS  OUTPUT,
		@FECHA_BITACORA ,                    
		@CODIGO_OPCION,                               
		@CLASE_BITACORA ,                              
		@LLAVE_TRANSACCION ,                           
		@REFERENCIA_TRANSACCION ,                      
		@USUARIO_CREA_TRANS ,                          
		@ESTACION_CREA_TRANS,                         
		@FECHA_CREA_TRANS ,         
		@USUARIO_ACTU_TRANS ,                          
		@ESTACION_ACTU_TRANS ,                         
		@FECHA_ACTU_TRANS ,         
		@SYS_LOGIN_USUARIO, --@USUARIO_CREA_BITACORA
		@SYS_ESTACION, --@ESTACION_CREA_BITACORA                      
		@FECHA_CREA_BITACORA ,      
		@SYS_LOGIN_USUARIO,                           
		@SYS_ESTACION ,                                
		@SYS_FILAS_AFECTADAS OUTPUT,
		@SYS_NUMERO_ERROR  OUTPUT,      
		@SYS_MENSAJE_ERROR  OUTPUT

	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DATETIME,
		@CORR_SUSCRIPCION INT=3,
		@CORR_CONFI_PAIS INT=1

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		--EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
