SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_COM_DOCUMENTO_ELECTRONICO]
(
	@TIPO_CONSULTA INT,
	@CORR_EMPRESA INT=NULL,
	@CORR_DOCUMENTO INT=NULL,
	@CORR_PROVEEDOR INT=NULL,
	@OPCION_CONSULTA INT=0
)
AS
BEGIN

	SET NOCOUNT ON

	EXECUTE [e-AdminFE].dbo.PRAL_DATA_COM_JSON
	@TIPO_CONSULTA,  
	@CORR_EMPRESA,   
	@CORR_DOCUMENTO,
	@CORR_PROVEEDOR,
	@OPCION_CONSULTA 

END
GO
