SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_BAN_CONCILIA_BANCARIA_MOV_EXCEL]
(	
	@CORR_EMPRESA INT,
	@CORR_CUENTA_BANCO INT,
	@CORR_CONCILIACION INT OUTPUT,
	@CORR_BANCO INT,
	@BAN_CONCILIA_BANCARIA_MOV_EXCEL T_BAN_CONCILIACION_BANCARIA_MOV_EXCEL READONLY,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR VARCHAR(4000) OUTPUT
)
AS

	DECLARE @MOVIMIENTOS_EXCEL AS TABLE
	(
		CORR_EMPRESA INT,
		CORR_CUENTA_BANCO INT,
		CORR_CONCILIACION INT,
		CORR_DETA INT,
		FECHA_MOVIMIENTO DATE,
		NUMERO_REFERENCIA_BANCO VARCHAR(255),
		CODIGO_TIPO_MOVIMIENTO VARCHAR(10),
		NOMBRE_TIPO_MOVIMIENTO VARCHAR(100),
		MONTO_CARGO DECIMAL(18,2),
		MONTO_ABONO DECIMAL(18,2)
		PRIMARY KEY(CORR_EMPRESA,CORR_CUENTA_BANCO,CORR_CONCILIACION,CORR_DETA)
	)

	DECLARE @CORR_TIPO_MOVIMIENTO INT,
			@CORR_CONCILIACION_DETA INT =0,
			@FECHA_MOVIMIENTO DATE,
			@NUMERO_REFERENCIA_BANCO VARCHAR(255),
			@NOMBRE_TIPO_MOVIMIENTO VARCHAR(100),
			@CODIGO_MOVIMIENTO VARCHAR(10),
			@MONTO_CARGO DECIMAL(18,2),
			@MONTO_ABONO DECIMAL(18,2),
			@CORR_MOV_DETA INT,
			@CLASE_BANCO VARCHAR(5),
			@NOMBRE_TIPO_MOVIMIENTO_IMPO VARCHAR(1000)
			
BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		
		INSERT @MOVIMIENTOS_EXCEL
		(
		    CORR_EMPRESA,
		    CORR_CUENTA_BANCO,
		    CORR_CONCILIACION,
		    CORR_DETA,
		    FECHA_MOVIMIENTO,
		    NUMERO_REFERENCIA_BANCO,
			CODIGO_TIPO_MOVIMIENTO,
			NOMBRE_TIPO_MOVIMIENTO,
		    MONTO_CARGO,
		    MONTO_ABONO
		)
		SELECT @CORR_EMPRESA,
			   @CORR_CUENTA_BANCO,
			   @CORR_CONCILIACION,
			   CORR,
			   FECHA_MOVIMIENTO,
			   NUMERO_REFERENCIA_BANCO,
			   CODIGO_TIPO_MOVIMIENTO,
			   NOMBRE_TIPO_MOVIMIENTO,
			   MONTO_CARGO,
			   MONTO_ABONO
		FROM @BAN_CONCILIA_BANCARIA_MOV_EXCEL

		SELECT @CLASE_BANCO=CLASE_BANCO
		FROM GEN_BANCO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_BANCO=@CORR_BANCO

		IF @CLASE_BANCO ='AVANZ'
		BEGIN
			IF EXISTS (SELECT 1 FROM @MOVIMIENTOS_EXCEL A
					   WHERE NOT EXISTS(SELECT 1 FROM BAN_TIPO_MOVI_SEGUN_BANCO AA
										WHERE AA.CORR_BANCO=@CORR_BANCO 
										AND UPPER(AA.CODIGO_MOVIMIENTO)=UPPER(A.CODIGO_TIPO_MOVIMIENTO))
						)
			BEGIN
					SELECT @NOMBRE_TIPO_MOVIMIENTO_IMPO = dbo.StrConcat(DISTINCT A.CODIGO_TIPO_MOVIMIENTO+',') 
					FROM @MOVIMIENTOS_EXCEL A
					WHERE NOT EXISTS(SELECT 1 FROM BAN_TIPO_MOVI_SEGUN_BANCO AA
										WHERE AA.CORR_BANCO=@CORR_BANCO 
										AND UPPER(AA.CODIGO_MOVIMIENTO)=UPPER(A.CODIGO_TIPO_MOVIMIENTO))

				SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='El archivo contiene un tipo de movimiento según banco no válido. Por favor configurarlo. ['+@NOMBRE_TIPO_MOVIMIENTO_IMPO+']',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END ELSE
		IF @CLASE_BANCO IN('CREDO','LAFIS','PROME')
		BEGIN
			IF EXISTS (SELECT 1 FROM @MOVIMIENTOS_EXCEL A
					   WHERE NOT EXISTS(SELECT 1 FROM BAN_TIPO_MOVI_SEGUN_BANCO AA
										 WHERE AA.CORR_BANCO=@CORR_BANCO 
										 AND A.CODIGO_TIPO_MOVIMIENTO=AA.CODIGO_MOVIMIENTO))
			BEGIN

				SELECT @NOMBRE_TIPO_MOVIMIENTO_IMPO = dbo.StrConcat(DISTINCT A.CODIGO_TIPO_MOVIMIENTO+',') 
				FROM @MOVIMIENTOS_EXCEL A
				WHERE NOT EXISTS(SELECT 1 FROM BAN_TIPO_MOVI_SEGUN_BANCO AA
								WHERE AA.CORR_BANCO=@CORR_BANCO 
								AND UPPER(AA.CODIGO_MOVIMIENTO)=UPPER(A.CODIGO_TIPO_MOVIMIENTO))

				SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='El archivo contiene un tipo de movimiento según banco no válido. Por favor configurarlo. ['+@NOMBRE_TIPO_MOVIMIENTO_IMPO+']',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END

		IF EXISTS(SELECT 1 FROM BAN_CONCILIA_BANCARIA_DETA 
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
				  AND CORR_CONCILIACION=@CORR_CONCILIACION
				  AND (ISNULL(ANIO_PERIODO,0)<>0 AND ISNULL(MES_PERIODO,0)<>0 AND ISNULL(CORR_CLASE_PARTIDA,0)<>0 AND ISNULL(CORR_PARTIDA,0)<>0))
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='Ya existen registros conciliados no se puede cargar los movimiento.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		DELETE FROM BAN_CONCILIA_BANCARIA_DETA 
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
		AND CORR_CONCILIACION=@CORR_CONCILIACION
		AND (ISNULL(ANIO_PERIODO,0)=0 AND ISNULL(MES_PERIODO,0)=0 AND ISNULL(CORR_CLASE_PARTIDA,0)=0 AND ISNULL(CORR_PARTIDA,0)=0)

		WHILE EXISTS(SELECT 1 FROM @MOVIMIENTOS_EXCEL)
		BEGIN
			SELECT TOP 1 @FECHA_MOVIMIENTO=FECHA_MOVIMIENTO,
			--@NUMERO_REFERENCIA_BANCO=TRIM(CODIGO_TIPO_MOVIMIENTO + ' '+ CASE WHEN NOMBRE_TIPO_MOVIMIENTO LIKE '%'+NUMERO_REFERENCIA_BANCO+'%' THEN '' ELSE NUMERO_REFERENCIA_BANCO END) + ' ' + NOMBRE_TIPO_MOVIMIENTO,
			@NUMERO_REFERENCIA_BANCO=NUMERO_REFERENCIA_BANCO,
			@MONTO_CARGO=MONTO_CARGO,
			@MONTO_ABONO=MONTO_ABONO,
			@NOMBRE_TIPO_MOVIMIENTO=NOMBRE_TIPO_MOVIMIENTO,
			@CODIGO_MOVIMIENTO=CODIGO_TIPO_MOVIMIENTO,
			@CORR_MOV_DETA=CORR_DETA
			FROM @MOVIMIENTOS_EXCEL

			IF @CLASE_BANCO ='AVANZ'
			BEGIN
				SELECT @CORR_TIPO_MOVIMIENTO=A.CORR_TIPO_MOVIMIENTO
				FROM BAN_TIPO_MOVI_SEGUN_BANCO A
				INNER JOIN BAN_TIPO_MOVI_BANCARIO B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO
				WHERE UPPER(A.NOMBRE_MOVIMIENTO_SEGUN_BANCO) LIKE UPPER(@NOMBRE_TIPO_MOVIMIENTO)+'%'
				AND B.SUMA_RESTA=CASE WHEN @MONTO_CARGO <> 0 THEN -1 ELSE 1 END
			END ELSE
			IF @CLASE_BANCO IN('CREDO','LAFIS')
			BEGIN
				SELECT @CORR_TIPO_MOVIMIENTO=A.CORR_TIPO_MOVIMIENTO
				FROM BAN_TIPO_MOVI_SEGUN_BANCO A
				INNER JOIN BAN_TIPO_MOVI_BANCARIO B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO
				WHERE A.CODIGO_MOVIMIENTO=@CODIGO_MOVIMIENTO
				AND B.SUMA_RESTA=CASE WHEN @MONTO_CARGO <> 0 THEN -1 ELSE 1 END
			END ELSE
			IF @CLASE_BANCO ='PROME'
			BEGIN
				SELECT @CORR_TIPO_MOVIMIENTO=A.CORR_TIPO_MOVIMIENTO
				FROM BAN_TIPO_MOVI_SEGUN_BANCO A
				WHERE A.CODIGO_MOVIMIENTO=@CODIGO_MOVIMIENTO
			END

			EXEC PRAL_MTTO_BAN_CONCILIA_BANCARIA_DETA 
				1,                                     
			    @CORR_EMPRESA,                                       
			    @CORR_CUENTA_BANCO,                                  
			    @CORR_CONCILIACION,                                  
			    @CORR_CONCILIACION_DETA OUTPUT,
			    @FECHA_MOVIMIENTO,                        
			    @CORR_TIPO_MOVIMIENTO,                               
			    @NUMERO_REFERENCIA_BANCO,                           
			    @MONTO_CARGO,                                     
			    @MONTO_ABONO,                                     
			    0,                                       
			    0,                                        
			    0,                                 
			    0,                                       
			    0, 
				@CODIGO_MOVIMIENTO,
				@NOMBRE_TIPO_MOVIMIENTO,
			    @SYS_LOGIN_USUARIO,                                 
			    @SYS_ESTACION,                                      
			    @SYS_FILAS_AFECTADAS OUTPUT,      
			    @SYS_NUMERO_ERROR OUTPUT,            
			    @SYS_MENSAJE_ERROR OUTPUT  
				
			IF @SYS_NUMERO_ERROR<>0
			BEGIN
				SELECT @SYS_NUMERO_ERROR,@SYS_MENSAJE_ERROR,@SYS_FILAS_AFECTADAS
				GOTO FINA
			END
				
			DELETE FROM @MOVIMIENTOS_EXCEL
			WHERE CORR_DETA=@CORR_MOV_DETA
		END

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION
	END CATCH
FINA:
END
GO

