-- Qué hace: mantenimiento de persona natural para gen-empleado (Insert/Update/Delete).
-- Cómo lo hace: TIPO 1 crea GEN_PERSONA + GEN_EMPRESA_PERSONA + GEN_PERSONA_NATURAL;
--               TIPO 2 actualiza GEN_PERSONA_NATURAL; TIPO 3 elimina GEN_PERSONA_NATURAL
--               (bloquea si existe GEN_EMPLEADO vinculado).
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE OR ALTER PROCEDURE [dbo].[PRAL_MTTO_GEN_PERSONA_NATURAL]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@CORR_PERSONA BIGINT = NULL OUTPUT,
	@CORR_PERSONA_NATURAL BIGINT = NULL OUTPUT,
	@CODIGO_PERSONA VARCHAR(20) = NULL,
	@ACTIVO_PERSONA BIT = 1,
	@PRIMER_NOMBRE VARCHAR(50) = NULL,
	@SEGUNDO_NOMBRE VARCHAR(50) = NULL,
	@PRIMER_APELLIDO VARCHAR(50) = NULL,
	@SEGUNDO_APELLIDO VARCHAR(50) = NULL,
	@APELLIDO_CASADA VARCHAR(50) = NULL,
	@FOTO_URL VARCHAR(500) = NULL,
	@SEXO VARCHAR(25) = NULL,
	@ESTADO_CIVIL VARCHAR(25) = NULL,
	@NACIONALIDAD VARCHAR(25) = NULL,
	@EDAD INT = NULL,
	@FECHA_NACIMIENTO DATE = NULL,
	@ES_JUBILADO BIT = NULL,
	@POSEE_DISCAPACIDAD BIT = NULL,
	@TIPO_DISCAPACIDAD VARCHAR(250) = NULL,
	@CORR_RELIGION INT = NULL,
	@IGLESIA_CONGREGA VARCHAR(50) = NULL,
	@CARTA_PASTORAL VARCHAR(2) = NULL,
	@ES_EXTRANJERO BIT = NULL,
	@DOMICILIADO VARCHAR(2) = NULL,
	@CORR_PAIS_NACIMIENTO INT = NULL,
	@CORR_DEPTO_NACIMIENTO INT = NULL,
	@CORR_MUNICIPIO_NACIMIENTO INT = NULL,
	@CORR_DISTRITO_NACIMIENTO INT = NULL,
	@CORR_ORIGEN_INGRESO INT = NULL,
	@CORR_TIPO_CONTRIBUYENTE INT = NULL,
	@CORR_ACTIVIDAD_ECONOMICA INT = NULL,
	@SYS_LOGIN_USUARIO VARCHAR(50),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		@SYS_NUMERO_ERROR = 0,
		@SYS_MENSAJE_ERROR = N'',
		@SYS_FILAS_AFECTADAS = 0;

	DECLARE @FECHA_AUD DATETIME = GETDATE();

	BEGIN TRY
		IF @TIPO_ACTUALIZA NOT IN (1, 2, 3)
		BEGIN
			SELECT
				@SYS_NUMERO_ERROR = 30000,
				@SYS_MENSAJE_ERROR = N'TIPO_ACTUALIZA no válido. Use 1=Insert, 2=Update, 3=Delete.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF ISNULL(@CORR_EMPRESA, 0) <= 0
		BEGIN
			SELECT
				@SYS_NUMERO_ERROR = 30000,
				@SYS_MENSAJE_ERROR = N'CORR_EMPRESA es requerido.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		/* Validaciones de dominio (CHECKS de GEN_PERSONA_NATURAL). */
		IF @TIPO_ACTUALIZA IN (1, 2)
		BEGIN
			/* '' no pasa el CHECK: solo NULL o valor del dominio. */
			SET @SEXO = NULLIF(LTRIM(RTRIM(@SEXO)), N'');
			SET @ESTADO_CIVIL = NULLIF(LTRIM(RTRIM(@ESTADO_CIVIL)), N'');
			SET @CARTA_PASTORAL = NULLIF(LTRIM(RTRIM(@CARTA_PASTORAL)), N'');
			SET @DOMICILIADO = NULLIF(LTRIM(RTRIM(@DOMICILIADO)), N'');

			IF @SEXO IS NOT NULL
				AND @SEXO NOT IN (N'MASCULINO', N'FEMENINO')
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'SEXO inválido. Use MASCULINO o FEMENINO.',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF @ESTADO_CIVIL IS NOT NULL
				AND @ESTADO_CIVIL NOT IN (
					N'SOLTERO(A)', N'CASADO(A)', N'ACOMPAÑADO(A)', N'DIVORCIADO(A)', N'VIUDO(A)'
				)
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'ESTADO_CIVIL inválido.',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF @CARTA_PASTORAL IS NOT NULL
				AND @CARTA_PASTORAL NOT IN (N'SI', N'NO')
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'CARTA_PASTORAL inválida. Use SI o NO.',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF @DOMICILIADO IS NOT NULL
				AND @DOMICILIADO NOT IN (N'SI', N'NO')
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'DOMICILIADO inválido. Use SI o NO.',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		IF @TIPO_ACTUALIZA = 1
		BEGIN
			BEGIN TRANSACTION;

			SELECT @CORR_PERSONA = ISNULL(MAX(CORR_PERSONA), 0) + 1
			FROM dbo.GEN_PERSONA WITH (UPDLOCK, HOLDLOCK);

			IF NULLIF(LTRIM(RTRIM(@CODIGO_PERSONA)), N'') IS NULL
			BEGIN
				SET @CODIGO_PERSONA = CONVERT(VARCHAR(20), @CORR_PERSONA);
			END;

			INSERT INTO dbo.GEN_PERSONA
			(
				CORR_PERSONA,
				CODIGO_PERSONA,
				ACTIVO_PERSONA,
				USUARIO_CREA,
				ESTACION_CREA,
				FECHA_CREA,
				USUARIO_ACTU,
				ESTACION_ACTU,
				FECHA_ACTU
			)
			VALUES
			(
				@CORR_PERSONA,
				@CODIGO_PERSONA,
				ISNULL(@ACTIVO_PERSONA, 1),
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@FECHA_AUD,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@FECHA_AUD
			);

			INSERT INTO dbo.GEN_EMPRESA_PERSONA
			(
				CORR_EMPRESA,
				CORR_PERSONA,
				USUARIO_CREA,
				ESTACION_CREA,
				FECHA_CREA,
				USUARIO_ACTU,
				ESTACION_ACTU,
				FECHA_ACTU
			)
			VALUES
			(
				@CORR_EMPRESA,
				@CORR_PERSONA,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@FECHA_AUD,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@FECHA_AUD
			);

			SELECT @CORR_PERSONA_NATURAL = ISNULL(MAX(CORR_PERSONA_NATURAL), 0) + 1
			FROM dbo.GEN_PERSONA_NATURAL WITH (UPDLOCK, HOLDLOCK);

			INSERT INTO dbo.GEN_PERSONA_NATURAL
			(
				CORR_PERSONA,
				CORR_PERSONA_NATURAL,
				PRIMER_NOMBRE,
				SEGUNDO_NOMBRE,
				PRIMER_APELLIDO,
				SEGUNDO_APELLIDO,
				APELLIDO_CASADA,
				FOTO_URL,
				SEXO,
				ESTADO_CIVIL,
				NACIONALIDAD,
				EDAD,
				FECHA_NACIMIENTO,
				ES_JUBILADO,
				POSEE_DISCAPACIDAD,
				TIPO_DISCAPACIDAD,
				CORR_RELIGION,
				IGLESIA_CONGREGA,
				CARTA_PASTORAL,
				ES_EXTRANJERO,
				DOMICILIADO,
				CORR_PAIS_NACIMIENTO,
				CORR_DEPTO_NACIMIENTO,
				CORR_MUNICIPIO_NACIMIENTO,
				CORR_DISTRITO_NACIMIENTO,
				CORR_ORIGEN_INGRESO,
				CORR_TIPO_CONTRIBUYENTE,
				CORR_ACTIVIDAD_ECONOMICA,
				USUARIO_CREA,
				ESTACION_CREA,
				FECHA_CREA,
				USUARIO_ACTU,
				ESTACION_ACTU,
				FECHA_ACTU
			)
			VALUES
			(
				@CORR_PERSONA,
				@CORR_PERSONA_NATURAL,
				@PRIMER_NOMBRE,
				@SEGUNDO_NOMBRE,
				@PRIMER_APELLIDO,
				@SEGUNDO_APELLIDO,
				@APELLIDO_CASADA,
				@FOTO_URL,
				@SEXO,
				@ESTADO_CIVIL,
				@NACIONALIDAD,
				@EDAD,
				@FECHA_NACIMIENTO,
				ISNULL(@ES_JUBILADO, 0),
				ISNULL(@POSEE_DISCAPACIDAD, 0),
				@TIPO_DISCAPACIDAD,
				@CORR_RELIGION,
				@IGLESIA_CONGREGA,
				@CARTA_PASTORAL,
				ISNULL(@ES_EXTRANJERO, 0),
				@DOMICILIADO,
				@CORR_PAIS_NACIMIENTO,
				@CORR_DEPTO_NACIMIENTO,
				@CORR_MUNICIPIO_NACIMIENTO,
				@CORR_DISTRITO_NACIMIENTO,
				@CORR_ORIGEN_INGRESO,
				@CORR_TIPO_CONTRIBUYENTE,
				@CORR_ACTIVIDAD_ECONOMICA,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@FECHA_AUD,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@FECHA_AUD
			);

			COMMIT TRANSACTION;
			SET @SYS_FILAS_AFECTADAS = 3;
		END
		ELSE IF @TIPO_ACTUALIZA = 2
		BEGIN
			IF ISNULL(@CORR_PERSONA_NATURAL, 0) <= 0
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'CORR_PERSONA_NATURAL es requerido para actualizar.',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			UPDATE dbo.GEN_PERSONA_NATURAL
			SET
				PRIMER_NOMBRE = @PRIMER_NOMBRE,
				SEGUNDO_NOMBRE = @SEGUNDO_NOMBRE,
				PRIMER_APELLIDO = @PRIMER_APELLIDO,
				SEGUNDO_APELLIDO = @SEGUNDO_APELLIDO,
				APELLIDO_CASADA = @APELLIDO_CASADA,
				FOTO_URL = @FOTO_URL,
				SEXO = @SEXO,
				ESTADO_CIVIL = @ESTADO_CIVIL,
				NACIONALIDAD = @NACIONALIDAD,
				EDAD = @EDAD,
				FECHA_NACIMIENTO = @FECHA_NACIMIENTO,
				ES_JUBILADO = ISNULL(@ES_JUBILADO, 0),
				POSEE_DISCAPACIDAD = ISNULL(@POSEE_DISCAPACIDAD, 0),
				TIPO_DISCAPACIDAD = @TIPO_DISCAPACIDAD,
				CORR_RELIGION = @CORR_RELIGION,
				IGLESIA_CONGREGA = @IGLESIA_CONGREGA,
				CARTA_PASTORAL = @CARTA_PASTORAL,
				ES_EXTRANJERO = ISNULL(@ES_EXTRANJERO, 0),
				DOMICILIADO = @DOMICILIADO,
				CORR_PAIS_NACIMIENTO = @CORR_PAIS_NACIMIENTO,
				CORR_DEPTO_NACIMIENTO = @CORR_DEPTO_NACIMIENTO,
				CORR_MUNICIPIO_NACIMIENTO = @CORR_MUNICIPIO_NACIMIENTO,
				CORR_DISTRITO_NACIMIENTO = @CORR_DISTRITO_NACIMIENTO,
				CORR_ORIGEN_INGRESO = @CORR_ORIGEN_INGRESO,
				CORR_TIPO_CONTRIBUYENTE = @CORR_TIPO_CONTRIBUYENTE,
				CORR_ACTIVIDAD_ECONOMICA = @CORR_ACTIVIDAD_ECONOMICA,
				USUARIO_ACTU = @SYS_LOGIN_USUARIO,
				ESTACION_ACTU = @SYS_ESTACION,
				FECHA_ACTU = @FECHA_AUD
			WHERE CORR_PERSONA_NATURAL = @CORR_PERSONA_NATURAL;

			IF @@ROWCOUNT = 0
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'No se encontró GEN_PERSONA_NATURAL para actualizar.',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			SELECT @CORR_PERSONA = CORR_PERSONA
			FROM dbo.GEN_PERSONA_NATURAL
			WHERE CORR_PERSONA_NATURAL = @CORR_PERSONA_NATURAL;

			SET @SYS_FILAS_AFECTADAS = 1;
		END
		ELSE IF @TIPO_ACTUALIZA = 3
		BEGIN
			IF ISNULL(@CORR_PERSONA_NATURAL, 0) <= 0 AND ISNULL(@CORR_PERSONA, 0) <= 0
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'Debe indicar CORR_PERSONA_NATURAL o CORR_PERSONA para eliminar.',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF ISNULL(@CORR_PERSONA_NATURAL, 0) <= 0
			BEGIN
				SELECT @CORR_PERSONA_NATURAL = CORR_PERSONA_NATURAL
				FROM dbo.GEN_PERSONA_NATURAL
				WHERE CORR_PERSONA = @CORR_PERSONA;
			END;

			IF ISNULL(@CORR_PERSONA, 0) <= 0
			BEGIN
				SELECT @CORR_PERSONA = CORR_PERSONA
				FROM dbo.GEN_PERSONA_NATURAL
				WHERE CORR_PERSONA_NATURAL = @CORR_PERSONA_NATURAL;
			END;

			IF EXISTS (
				SELECT 1
				FROM dbo.GEN_EMPLEADO
				WHERE CORR_PERSONA = @CORR_PERSONA
			)
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'No se puede eliminar la persona natural porque tiene empleado vinculado.',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			DELETE FROM dbo.GEN_PERSONA_NATURAL
			WHERE CORR_PERSONA_NATURAL = @CORR_PERSONA_NATURAL;

			SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
		END;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION;
		END;

		SELECT
			@SYS_NUMERO_ERROR = ERROR_NUMBER(),
			@SYS_MENSAJE_ERROR = ERROR_MESSAGE(),
			@SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO
