SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_DOCUMENTO_APLICAR]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_DOCUMENTO int OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
	DECLARE
	@ANIO_PERIODO_BITACORA INT=YEAR(GETDATE()), @CORR_BITACORA_TRANS INT=0, @FECHA_BITACORA DATE=GETDATE(), @LLAVE_TRANSACCION VARCHAR(250),@REFERENCIA_TRANSACCION VARCHAR(500), 
	@USUARIO_CREA_TRANS VARCHAR(50), @ESTACION_CREA_TRANS VARCHAR(50), @FECHA_CREA_TRANS DATETIME,@USUARIO_ACTU_TRANS VARCHAR(50), @ESTACION_ACTU_TRANS VARCHAR(50),
	@FECHA_ACTU_TRANS DATETIME, @USUARIO_CREA_BITACORA VARCHAR(50),@ESTACION_CREA_BITACORA VARCHAR(50), @FECHA_CREA_BITACORA DATETIME=GETDATE(),
	@CODIGO_OPCION VARCHAR(150)='COM_DOCUMENTO',@CLASE_BITACORA VARCHAR(3)='AP'

	DECLARE @CORR_PROVEEDOR INT, @CODIGO_GENERACION VARCHAR(50), @NUMERO_DOCUMENTO varchar(150), @SERIE varchar(25)
BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF NOT EXISTS(SELECT 1 
				  FROM COM_DOCUMENTO 
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND ANIO_PERIODO=@ANIO_PERIODO
				  AND MES_PERIODO=@MES_PERIODO
				  AND CORR_DOCUMENTO=@CORR_DOCUMENTO
				  AND TOTAL_DOCUMENTO>0
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='El total del documento debe ser mayor a 0',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF NOT EXISTS(SELECT 1 
				  FROM COM_DOCUMENTO 
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND ANIO_PERIODO=@ANIO_PERIODO
				  AND MES_PERIODO=@MES_PERIODO
				  AND CORR_DOCUMENTO=@CORR_DOCUMENTO
				  AND ANIO_PERIODO_IVA<>0
				  AND MES_PERIODO_IVA<>0
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Debe seleccionar el mes a declarar IVA',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		SELECT @CORR_PROVEEDOR=A.CORR_PROVEEDOR, 
		@CODIGO_GENERACION=LTRIM(RTRIM(A.CODIGO_GENERACION)), 
		@NUMERO_DOCUMENTO=LTRIM(RTRIM(A.NUMERO_DOCUMENTO)), 
		@SERIE=A.SERIE
		FROM COM_DOCUMENTO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.MES_PERIODO=@MES_PERIODO
		AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO

		IF LEN(@CODIGO_GENERACION)>0
		BEGIN
			IF EXISTS(SELECT 1 
					  FROM COM_DOCUMENTO A
					  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					  AND A.CORR_PROVEEDOR=@CORR_PROVEEDOR
					  AND A.CODIGO_GENERACION=@CODIGO_GENERACION
					  AND NOT EXISTS(SELECT 1 FROM COM_DOCUMENTO B
									 WHERE A.CORR_EMPRESA=B.CORR_EMPRESA
									 AND A.ANIO_PERIODO=B.ANIO_PERIODO
									 AND A.MES_PERIODO=B.MES_PERIODO
									 AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO
									 AND A.CORR_EMPRESA=@CORR_EMPRESA
									 AND A.ANIO_PERIODO=@ANIO_PERIODO
									 AND A.MES_PERIODO=@MES_PERIODO
									 AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO)
					  )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30003,@SYS_MENSAJE_ERROR='El documento ya existe! no puede ser aplicado',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END ELSE
		BEGIN
			IF EXISTS(SELECT 1 
					  FROM COM_DOCUMENTO A
					  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					  AND A.CORR_PROVEEDOR=@CORR_PROVEEDOR
					  AND A.SERIE=@SERIE
					  AND A.NUMERO_DOCUMENTO=@NUMERO_DOCUMENTO
					  AND NOT EXISTS(SELECT 1 FROM COM_DOCUMENTO B
									 WHERE A.CORR_EMPRESA=B.CORR_EMPRESA
									 AND A.ANIO_PERIODO=B.ANIO_PERIODO
									 AND A.MES_PERIODO=B.MES_PERIODO
									 AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO
									 AND A.CORR_EMPRESA=@CORR_EMPRESA
									 AND A.ANIO_PERIODO=@ANIO_PERIODO
									 AND A.MES_PERIODO=@MES_PERIODO
									 AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO)
					  )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30003,@SYS_MENSAJE_ERROR='El documento ya existe! no puede ser aplicado',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END


		------------------------------------------------------------------------
		-------------  BITACORA -------------- 
		SELECT @LLAVE_TRANSACCION='Año: '+CONVERT(VARCHAR,A.ANIO_PERIODO) COLLATE DATABASE_DEFAULT+'Mes: '+CONVERT(VARCHAR,A.MES_PERIODO) COLLATE DATABASE_DEFAULT+' Correlativo No.: '+CONVERT(VARCHAR,A.CORR_DOCUMENTO) COLLATE DATABASE_DEFAULT,
				@REFERENCIA_TRANSACCION= ' Fecha: '+ CONVERT(VARCHAR,A.FECHA_DOCUMENTO) COLLATE DATABASE_DEFAULT
										+', Proveedor: '+A.NOMBRE_PROVEEDOR COLLATE DATABASE_DEFAULT
										+', Observaciones: '+A.DESCRIPCION_PARTIDA COLLATE DATABASE_DEFAULT,
				@USUARIO_CREA_TRANS=A.USUARIO_CREA, @ESTACION_CREA_TRANS=A.ESTACION_CREA, @FECHA_CREA_TRANS=A.FECHA_CREA,
				@USUARIO_ACTU_TRANS=A.USUARIO_ACTU, @ESTACION_ACTU_TRANS=A.ESTACION_ACTU, @FECHA_ACTU_TRANS=A.FECHA_ACTU
		FROM V_COM_DOCUMENTO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO

		UPDATE COM_DOCUMENTO SET 
		ESTADO_DOCUMENTO='AP'
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

		--Executando el procedimiento de la bitacora
		EXECUTE PRAL_MTTO_COM_BITACORA
		1,--@TIPO_ACTUALIZA ,                               
		@CORR_EMPRESA ,      
		@ANIO_PERIODO_BITACORA,
		@CORR_BITACORA_TRANS  OUTPUT,
		@FECHA_BITACORA ,                    
		@CODIGO_OPCION,                               
		@CLASE_BITACORA ,                              
		@LLAVE_TRANSACCION ,                           
		@REFERENCIA_TRANSACCION ,                      
		@USUARIO_CREA_TRANS ,                          
		@ESTACION_CREA_TRANS,                         
		@FECHA_CREA_TRANS ,         
		@USUARIO_ACTU_TRANS ,                          
		@ESTACION_ACTU_TRANS ,                         
		@FECHA_ACTU_TRANS ,         
		@SYS_LOGIN_USUARIO, --@USUARIO_CREA_BITACORA
		@SYS_ESTACION, --@ESTACION_CREA_BITACORA                      
		@FECHA_CREA_BITACORA ,      
		@SYS_LOGIN_USUARIO,                           
		@SYS_ESTACION ,                                
		@SYS_FILAS_AFECTADAS OUTPUT,
		@SYS_NUMERO_ERROR  OUTPUT,      
		@SYS_MENSAJE_ERROR  OUTPUT

	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DATETIME,
		@CORR_SUSCRIPCION INT=3,
		@CORR_CONFI_PAIS INT=1

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		--EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
