SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_CON_PARTIDA_MODELO]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA int,
	@CORR_CLASE_PARTIDA int,
	@CORR_PARTIDA int OUTPUT,
	@NUMERO_DOCUMENTO varchar(25),
	@NOMBRE_PARTIDA varchar(1000),	
	@ESTADO_PARTIDA varchar(2),
	@CLASE_PARTIDA VARCHAR(3)='NOR',
	@CORR_MONEDA INT=NULL,
	@FACTOR_CAMBIO DECIMAL(16,6)=NULL,
	@OPERADOR VARCHAR(2)=NULL,
	@USUARIO_CREA varchar(30),
	@FECHA_CREA datetime,
	@ESTACION_CREA varchar(50),
	@USUARIO_ACTU varchar(30),
	@FECHA_ACTU datetime,
	@ESTACION_ACTU varchar(50),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS

BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY

		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN										
			SELECT @CLASE_PARTIDA=ISNULL(@CLASE_PARTIDA,'NOR')
			
			SELECT @CORR_PARTIDA=ISNULL(MAX(CORR_PARTIDA),0)+1
			FROM CON_PARTIDA_MODELO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA						

			INSERT INTO CON_PARTIDA_MODELO
			(CORR_EMPRESA,CORR_CLASE_PARTIDA,CORR_PARTIDA,NUMERO_DOCUMENTO,NOMBRE_PARTIDA,ESTADO_PARTIDA,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU,CLASE_PARTIDA,CORR_MONEDA,FACTOR_CAMBIO,OPERADOR)
			VALUES
			(@CORR_EMPRESA,@CORR_CLASE_PARTIDA,@CORR_PARTIDA,@NUMERO_DOCUMENTO,@NOMBRE_PARTIDA,@ESTADO_PARTIDA,@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU,@CLASE_PARTIDA,@CORR_MONEDA,@FACTOR_CAMBIO,@OPERADOR)	
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE CON_PARTIDA_MODELO SET
			NUMERO_DOCUMENTO=@NUMERO_DOCUMENTO,
			NOMBRE_PARTIDA=@NOMBRE_PARTIDA,
			ESTADO_PARTIDA=@ESTADO_PARTIDA,
			USUARIO_ACTU=@USUARIO_ACTU,
			FECHA_ACTU=@FECHA_ACTU,
			ESTACION_ACTU=@ESTACION_ACTU,
			CORR_MONEDA=@CORR_MONEDA,
			FACTOR_CAMBIO=@FACTOR_CAMBIO,
			OPERADOR=@OPERADOR
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
			AND CORR_PARTIDA=@CORR_PARTIDA
			
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
	    
		    DELETE FROM CON_PARTIDA_DETA_MODELO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
			AND CORR_PARTIDA=@CORR_PARTIDA
		
			DELETE FROM CON_PARTIDA_MODELO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
			AND CORR_PARTIDA=@CORR_PARTIDA
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH
FINA:
END
GO
