SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPO_CON_CATALOGO_CUENTA]
(
	@CODIGO_RUBRO VARCHAR(30),
	@CORR_EMPRESA_ORIGEN SMALLINT,
	@CORR_SUSCRIPCION_DESTINO INT,
	@CORR_CONFI_PAIS_DESTINO INT,
	@CORR_EMPRESA_DESTINO INT)
AS
	DECLARE @CON_CATALOGO_CUENTA TABLE
	(
		CUENTA_CONTABLE varchar(30)
	)

	DECLARE @CUENTA_CONTABLE varchar(30),
	@NOMBRE_CUENTA	varchar(100),
	@ES_DEBE		bit,
	@ES_HABER		bit,
	@ES_DETALLE		bit,
	@NIVEL			SMALLINT,
	@CUENTA_MAYOR	VARCHAR(30)	
BEGIN
	--INSERT INTO @CON_CATALOGO_CUENTA
	--SELECT cuenta_contable 
	--FROM [e-contaTech].dbo.catalogo_cuentas
	--WHERE SUBSTRING(cuenta_contable,1,1)=@CODIGO_RUBRO
	--AND id_empresa=@CORR_EMPRESA_ORIGEN

	WHILE EXISTS(SELECT 1 FROM @CON_CATALOGO_CUENTA)
	BEGIN		
		SELECT TOP 1 @CUENTA_CONTABLE=CUENTA_CONTABLE 
		FROM @CON_CATALOGO_CUENTA 
		ORDER BY CUENTA_CONTABLE		

		--SELECT @NOMBRE_CUENTA=LTRIM(RTRIM(ISNULL(descripcion_cuenta,'')))
		--,@ES_DEBE=es_debe
		--,@ES_HABER=es_haber
		--,@ES_DETALLE=es_detalle
		--,@NIVEL=id_nivel
		--,@CUENTA_MAYOR=cuenta_mayor
		--FROM [e-contaTech].dbo.catalogo_cuentas
		--WHERE cuenta_contable=@CUENTA_CONTABLE
		--AND id_empresa=@CORR_EMPRESA_ORIGEN

		PRINT 'Procesando Cuenta '+@CUENTA_CONTABLE

		IF NOT EXISTS(SELECT 1 FROM CON_CATALOGO_CUENTA 
					  AND CORR_EMPRESA=@CORR_EMPRESA_DESTINO
					  AND CUENTA_CONTABLE=@CUENTA_CONTABLE)
		BEGIN
			EXEC PRAL_MTTO_CON_CATALOGO_CUENTA
			1,--@TIPO_ACTUALIZA,
			@CORR_SUSCRIPCION_DESTINO,
			@CORR_CONFI_PAIS_DESTINO,
			@CORR_EMPRESA_DESTINO,
			@CUENTA_CONTABLE,
			@NOMBRE_CUENTA,
			@ES_DEBE,
			@ES_HABER,
			@ES_DETALLE,
			@NIVEL,
			@CUENTA_MAYOR,
			@CODIGO_RUBRO,
			0,
			'ACT',
			0,
			'HIS',
			'e-coffeeTech',
			'e-coffeeTech',
			0,
			0,
			''
		END ELSE
		BEGIN
			IF LEN(@CUENTA_CONTABLE)>1
			BEGIN
				EXEC PRAL_MTTO_CON_CATALOGO_CUENTA
				2,--@TIPO_ACTUALIZA,
				@CORR_SUSCRIPCION_DESTINO,
				@CORR_CONFI_PAIS_DESTINO,
				@CORR_EMPRESA_DESTINO,
				@CUENTA_CONTABLE,
				@NOMBRE_CUENTA,
				@ES_DEBE,
				@ES_HABER,
				@ES_DETALLE,
				@NIVEL,
				@CUENTA_MAYOR,
				@CODIGO_RUBRO,
				0,
				'ACT',
				0,
				'HIS',
				'e-coffeeTech',
				'e-coffeeTech',
				0,
				0,
				''
			END
		END

		DELETE FROM @CON_CATALOGO_CUENTA
		WHERE CUENTA_CONTABLE=@CUENTA_CONTABLE
	END

END
GO
