SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_COM_CUADRO_COMPARATIVO]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
    @CORR_CUADRO_COMPARATIVO INT
)
AS
	DECLARE @ANALISIS_PROVEEDOR TABLE (
		CORR_EMPRESA INT,
		CORR_PROVEEDOR INT,
		CORRELATIVO INT,
		CORR_GRUPO INT,
		PRIMARY KEY (
		CORR_EMPRESA,
		CORR_PROVEEDOR
		)
	)

	DECLARE @ANALISIS_PROVEEDOR_GRUPO TABLE (
		CORR_EMPRESA INT,
		CORR_PROVEEDOR INT,
		NOMBRE_PROVEEDOR VARCHAR(150),
		CORRELATIVO INT,
		CORR_GRUPO INT,
		CORR_PROVEEDOR_GRUPO INT,
		PRIMARY KEY (
		CORR_EMPRESA,
		CORR_PROVEEDOR
		)
	)

	DECLARE @ANALISIS_ITEM TABLE (
		CORR_EMPRESA INT,
		CODIGO_ITEM VARCHAR(30),
		NOMBRE_ITEM VARCHAR(150)
		PRIMARY KEY (
		CORR_EMPRESA,
		CODIGO_ITEM 
		)
	)

	DECLARE @ANALISIS_COTIZACION TABLE(
		CORR_EMPRESA INT,
		ANIO_PERIODO INT,
		CORR_CUADRO_COMPARATIVO INT,
		CORR_COTIZACION INT,
		CORR_COTIZACION_DETA INT,
		SELECCION BIT,
		CODIGO_ITEM VARCHAR(30),
		MARCA VARCHAR(150),
		CORR_UNIDAD_MEDIDA INT,
		CANTIDAD_COTIZAR INT,
		PRECIO_UNITARIO DECIMAL(18,2),
		MONTO_SUBTOTAL DECIMAL(18,2),
		CORR_PROVEEDOR INT,
		MONTO_ASIGNADO DECIMAL(18,6)
		PRIMARY KEY (
		CORR_EMPRESA,
		ANIO_PERIODO,
		CORR_CUADRO_COMPARATIVO,
		CORR_COTIZACION,
		CORR_COTIZACION_DETA
		)
	)

	DECLARE @ANALISIS_PROVEEDOR_ITEM TABLE (
		CORR_EMPRESA INT,
		CORR_PROVEEDOR INT,
		NOMBRE_PROVEEDOR VARCHAR(150),
		CORRELATIVO INT,
		CORR_GRUPO INT,
		CORR_PROVEEDOR_GRUPO INT,
		CODIGO_ITEM VARCHAR(30),
		NOMBRE_ITEM VARCHAR(150)
	)

	DECLARE @ANALISIS_COTIZACION_CARGADO TABLE (
		CORR_EMPRESA INT,
		NOMBRE_PROVEEDOR_1 VARCHAR(150),
		NOMBRE_PROVEEDOR_2 VARCHAR(150),
		NOMBRE_PROVEEDOR_3 VARCHAR(150),
		CODIGO_ITEM VARCHAR(30),
		NOMBRE_ITEM VARCHAR(150),
		CANTIDAD_COTIZAR INT,
		CORR_UNIDAD_MEDIDA INT,
		SELECCION_1 BIT,
		SELECCION_2 BIT,
		SELECCION_3 BIT,
		PRECIO_UNITARIO_1 DECIMAL(18,2),
		PRECIO_UNITARIO_2 DECIMAL(18,2),
		PRECIO_UNITARIO_3 DECIMAL(18,2),
		MONTO_SUBTOTAL_1 DECIMAL(18,2),
		MONTO_SUBTOTAL_2 DECIMAL(18,2),
		MONTO_SUBTOTAL_3 DECIMAL(18,2),
		MARCA_1 VARCHAR(150),
		MARCA_2 VARCHAR(150),
		MARCA_3 VARCHAR(150),
		MONTO_ASIGNADO_1 DECIMAL(18,6),
		MONTO_ASIGNADO_2 DECIMAL(18,6),
		MONTO_ASIGNADO_3 DECIMAL(18,6),
		CORR_GRUPO INT
	)

	DECLARE @CONCATENACION TABLE (
		NOMBRE_PROVEEDOR_1 VARCHAR(150),
		NOMBRE_PROVEEDOR_2 VARCHAR(150),
		NOMBRE_PROVEEDOR_3 VARCHAR(150),
		CORR_GRUPO INT
	)

	DECLARE @ANALISIS_COTIZACION_CARGADO_COP TABLE (
		CORR_SUSCRIPCION INT,
		CORR_CONFI_PAIS INT,
		CORR_EMPRESA INT,
		NOMBRE_PROVEEDOR_1 VARCHAR(150),
		NOMBRE_PROVEEDOR_2 VARCHAR(150),
		NOMBRE_PROVEEDOR_3 VARCHAR(150),
		CODIGO_ITEM VARCHAR(30),
		NOMBRE_ITEM VARCHAR(150),
		CANTIDAD_COTIZAR DECIMAL(18,6),
		CORR_UNIDAD_MEDIDA INT,
		SELECCION_1 BIT,
		SELECCION_2 BIT,
		SELECCION_3 BIT,
		PRECIO_UNITARIO_1 DECIMAL(18,2),
		PRECIO_UNITARIO_2 DECIMAL(18,2),
		PRECIO_UNITARIO_3 DECIMAL(18,2),
		MONTO_DESCUENTO_1 DECIMAL(18,2),
		MONTO_DESCUENTO_2 DECIMAL(18,2),
		MONTO_DESCUENTO_3 DECIMAL(18,2),
		MONTO_IVA_1 DECIMAL(18,2),
		MONTO_IVA_2 DECIMAL(18,2),
		MONTO_IVA_3 DECIMAL(18,2),
		MONTO_SUBTOTAL_1 DECIMAL(18,2),
		MONTO_SUBTOTAL_2 DECIMAL(18,2),
		MONTO_SUBTOTAL_3 DECIMAL(18,2),
		MARCA_1 VARCHAR(150),
		MARCA_2 VARCHAR(150),
		MARCA_3 VARCHAR(150),
		MONTO_ASIGNADO_1 DECIMAL(18,6),
		MONTO_ASIGNADO_2 DECIMAL(18,6),
		MONTO_ASIGNADO_3 DECIMAL(18,6),
		CORR_GRUPO INT,
		CORR_MONEDA1 INT
	)

	DECLARE @FECHA_CUADRO_COMPARATIVO DATETIME,@NOMBRE_DEPARTAMENTO VARCHAR(150),@ES_MEJOR_PRECIO BIT,@TIENE_CREDITO_30_DIAS BIT,@TIENE_BUEN_SOPORTE_TECNICO BIT,@TIENE_BUENA_CALIDAD_PRODUCTO BIT
	,@TIENE_MEJOR_TIEMPO_ENTREGA BIT,@BRINDA_BUENA_EXPERIENCIA_PROVEEDOR BIT ,@ES_PROVEEDOR_UNICO BIT,@EXISTE_OTRA_RAZON BIT,@NOMBRE_OTRA_RAZON VARCHAR(255), @NOMBRE_USUARIO_CUADRO_COMPARATIVO VARCHAR(150)

BEGIN
  SET NOCOUNT ON

	SELECT @FECHA_CUADRO_COMPARATIVO=A.FECHA_CUADRO_COMPARATIVO
	,@NOMBRE_DEPARTAMENTO=B.NOMBRE_DEPTO
	,@ES_MEJOR_PRECIO=A.ES_MEJOR_PRECIO
	,@TIENE_CREDITO_30_DIAS=A.TIENE_CREDITO_30_DIAS
	,@TIENE_BUEN_SOPORTE_TECNICO=A.TIENE_BUEN_SOPORTE_TECNICO
	,@TIENE_BUENA_CALIDAD_PRODUCTO=A.TIENE_BUENA_CALIDAD_PRODUCTO
	,@TIENE_MEJOR_TIEMPO_ENTREGA=A.TIENE_MEJOR_TIEMPO_ENTREGA
	,@BRINDA_BUENA_EXPERIENCIA_PROVEEDOR=A.BRINDA_BUENA_EXPERIENCIA_PROVEEDOR
	,@ES_PROVEEDOR_UNICO=A.ES_PROVEEDOR_UNICO
	,@EXISTE_OTRA_RAZON=A.EXISTE_OTRA_RAZON
	,@NOMBRE_OTRA_RAZON=A.NOMBRE_OTRA_RAZON
	,@NOMBRE_USUARIO_CUADRO_COMPARATIVO=ISNULL(C.NOMBRE_USUARIO,ISNULL(D.NOMBRE_USUARIO,''))
	FROM COM_CUADRO_COMPARATIVO A
	INNER JOIN V_COM_CUADRO_COMPARATIVO_COTIZACION_SUM B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = B.CORR_CUADRO_COMPARATIVO
	LEFT OUTER JOIN V_SEG_USUARIO C ON A.USUARIO_CUADRO_COMPARATIVO=C.LOGIN_SISTEMA
	LEFT OUTER JOIN V_SEG_USUARIO_CLASS D ON A.USUARIO_CUADRO_COMPARATIVO COLLATE DATABASE_DEFAULT =D.LOGIN_SISTEMA COLLATE DATABASE_DEFAULT
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	AND A.ANIO_PERIODO=@ANIO_PERIODO
	AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO

	INSERT INTO @ANALISIS_PROVEEDOR
	(
		CORR_EMPRESA,
		CORR_PROVEEDOR,
		CORRELATIVO,
		CORR_GRUPO
	)
	SELECT DISTINCT 
		A.CORR_EMPRESA,
		D.CORR_PROVEEDOR,
		ROW_NUMBER() OVER(ORDER BY D.CORR_PROVEEDOR) GRUPO_PROVEEDOR,
		CASE WHEN ROW_NUMBER() OVER(ORDER BY D.CORR_PROVEEDOR) <=3 THEN 1 ELSE CASE WHEN ROW_NUMBER() OVER(ORDER BY D.CORR_PROVEEDOR) > 3 AND ROW_NUMBER() OVER(ORDER BY D.CORR_PROVEEDOR)<=6 THEN 2 END END
	FROM COM_CUADRO_COMPARATIVO A
	INNER JOIN COM_CUADRO_COMPARATIVO_DETA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = B.CORR_CUADRO_COMPARATIVO 
	INNER JOIN COM_COTIZACION_DETA C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO_COTIZACION = C.ANIO_PERIODO AND B.CORR_COTIZACION = C.CORR_COTIZACION AND B.CORR_COTIZACION_DETA = C.CORR_COTIZACION_DETA 
	INNER JOIN COM_COTIZACION D ON C.CORR_EMPRESA = D.CORR_EMPRESA AND C.ANIO_PERIODO = D.ANIO_PERIODO AND C.CORR_COTIZACION = D.CORR_COTIZACION
	INNER JOIN V_COM_PROVEEDOR E ON D.CORR_PROVEEDOR = E.CORR_PROVEEDOR
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA
	AND A.ANIO_PERIODO=@ANIO_PERIODO
	AND A.CORR_CUADRO_COMPARATIVO = @CORR_CUADRO_COMPARATIVO
	GROUP BY A.CORR_EMPRESA
	,D.CORR_PROVEEDOR

	INSERT INTO @ANALISIS_PROVEEDOR_GRUPO
	(
	    CORR_EMPRESA,
	    CORR_PROVEEDOR,
		NOMBRE_PROVEEDOR,
	    CORRELATIVO,
	    CORR_GRUPO,
	    CORR_PROVEEDOR_GRUPO
	)
	SELECT A.CORR_EMPRESA,
		A.CORR_PROVEEDOR,
		B.NOMBRE_PROVEEDOR,
		A.CORRELATIVO,
		A.CORR_GRUPO,
		ROW_NUMBER() OVER(PARTITION BY A.CORR_GRUPO ORDER BY A.CORR_GRUPO)
	FROM @ANALISIS_PROVEEDOR A
	INNER JOIN V_COM_PROVEEDOR B ON A.CORR_PROVEEDOR = B.CORR_PROVEEDOR


	INSERT INTO @ANALISIS_ITEM
	(
	    CORR_EMPRESA,
	    CODIGO_ITEM,
		NOMBRE_ITEM
	)
	SELECT DISTINCT A.CORR_EMPRESA
		,C.CODIGO_ITEM
		,G.INVDSC NOMBRE_ITEM
	FROM COM_CUADRO_COMPARATIVO A
	INNER JOIN COM_CUADRO_COMPARATIVO_DETA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = B.CORR_CUADRO_COMPARATIVO
	INNER JOIN COM_COTIZACION_DETA C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO_COTIZACION = C.ANIO_PERIODO AND B.CORR_COTIZACION = C.CORR_COTIZACION AND B.CORR_COTIZACION_DETA = C.CORR_COTIZACION_DETA
	INNER JOIN [CLASS_UEES].dbo.INVENTARIOS G ON G.INVCOD = C.CODIGO_ITEM COLLATE Modern_Spanish_CI_AS AND G.INVREG = 'E' AND G.INVSUC='001'
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA
	AND A.ANIO_PERIODO=@ANIO_PERIODO
	AND A.CORR_CUADRO_COMPARATIVO = @CORR_CUADRO_COMPARATIVO
	GROUP BY A.CORR_EMPRESA
	,A.ANIO_PERIODO
	,A.CORR_CUADRO_COMPARATIVO
	,C.CODIGO_ITEM
	,G.INVDSC

	INSERT INTO @ANALISIS_COTIZACION
	(
	    CORR_EMPRESA,
		ANIO_PERIODO,
	    CORR_CUADRO_COMPARATIVO,
	    CORR_COTIZACION,
	    CORR_COTIZACION_DETA,
	    SELECCION,
	    CODIGO_ITEM,
		MARCA,
	    CORR_UNIDAD_MEDIDA,
	    CANTIDAD_COTIZAR,
	    PRECIO_UNITARIO,
	    MONTO_SUBTOTAL,
		CORR_PROVEEDOR,
		MONTO_ASIGNADO
	)
	SELECT B.CORR_EMPRESA,
		B.ANIO_PERIODO,
	    B.CORR_CUADRO_COMPARATIVO,
	    B.CORR_COTIZACION,
	    B.CORR_COTIZACION_DETA,
	    B.SELECCION,
	    C.CODIGO_ITEM,
		C.MARCA,
	    C.CORR_UNIDAD_MEDIDA,
	    C.CANTIDAD,
	    C.PRECIO_UNITARIO,
	    C.MONTO_SUBTOTAL,
		D.CORR_PROVEEDOR,
		ISNULL(E.MONTO_ASIGNADO,0) MONTO_ASIGNADO
	FROM COM_CUADRO_COMPARATIVO A
	INNER JOIN COM_CUADRO_COMPARATIVO_DETA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = B.CORR_CUADRO_COMPARATIVO
	INNER JOIN COM_COTIZACION_DETA C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO_COTIZACION=C.ANIO_PERIODO AND B.CORR_COTIZACION = C.CORR_COTIZACION AND B.CORR_COTIZACION_DETA = C.CORR_COTIZACION_DETA
	INNER JOIN COM_COTIZACION D ON C.CORR_EMPRESA = D.CORR_EMPRESA AND C.ANIO_PERIODO=D.ANIO_PERIODO AND C.CORR_COTIZACION = D.CORR_COTIZACION
	LEFT OUTER JOIN V_COM_CUADRO_COMPARATIVO_TOTAL E ON A.CORR_EMPRESA = E.CORR_EMPRESA AND A.ANIO_PERIODO = E.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = E.CORR_CUADRO_COMPARATIVO AND D.CORR_PROVEEDOR = E.CORR_PROVEEDOR
	WHERE A.CORR_EMPRESA = @CORR_EMPRESA
	AND A.ANIO_PERIODO=@ANIO_PERIODO
	AND A.CORR_CUADRO_COMPARATIVO = @CORR_CUADRO_COMPARATIVO

	INSERT INTO @ANALISIS_PROVEEDOR_ITEM
	(
	    CORR_EMPRESA,
	    CORR_PROVEEDOR,
	    NOMBRE_PROVEEDOR,
	    CORRELATIVO,
	    CORR_GRUPO,
	    CORR_PROVEEDOR_GRUPO,
	    CODIGO_ITEM,
	    NOMBRE_ITEM
	)
	SELECT A.CORR_EMPRESA,
	    A.CORR_PROVEEDOR,
		A.NOMBRE_PROVEEDOR,
	    A.CORRELATIVO,
	    A.CORR_GRUPO,
	    A.CORR_PROVEEDOR_GRUPO,
		B.CODIGO_ITEM,
		B.NOMBRE_ITEM
	FROM @ANALISIS_PROVEEDOR_GRUPO A
	INNER JOIN @ANALISIS_ITEM B ON A.CORR_EMPRESA = B.CORR_EMPRESA 


	INSERT INTO @CONCATENACION
	(
	    NOMBRE_PROVEEDOR_1,
	    NOMBRE_PROVEEDOR_2,
	    NOMBRE_PROVEEDOR_3,
	    CORR_GRUPO
	)
	SELECT LTRIM(RTRIM(dbo.StrConcat(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 1  THEN  ISNULL(A.NOMBRE_PROVEEDOR,'') ELSE '' END+''))) NOMBRE_PROVEEDOR_1,
		LTRIM(RTRIM(dbo.StrConcat(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 2 THEN ISNULL(A.NOMBRE_PROVEEDOR,'') ELSE '' END+''))) NOMBRE_PROVEEDOR_2,
		LTRIM(RTRIM(dbo.StrConcat(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 3 THEN ISNULL(A.NOMBRE_PROVEEDOR,'') ELSE '' END+''))) NOMBRE_PROVEEDOR_3,
		A.CORR_GRUPO
	FROM @ANALISIS_PROVEEDOR_GRUPO A
	GROUP BY A.CORR_GRUPO

	INSERT INTO @ANALISIS_COTIZACION_CARGADO
	(
	    CORR_EMPRESA,
	    NOMBRE_PROVEEDOR_1,
	    NOMBRE_PROVEEDOR_2,
	    NOMBRE_PROVEEDOR_3,
		CODIGO_ITEM,
	    NOMBRE_ITEM,
	    CANTIDAD_COTIZAR,
	    CORR_UNIDAD_MEDIDA,
	    SELECCION_1,
		SELECCION_2,
		SELECCION_3,
	    PRECIO_UNITARIO_1,
	    PRECIO_UNITARIO_2,
	    PRECIO_UNITARIO_3,
	    MONTO_SUBTOTAL_1,
	    MONTO_SUBTOTAL_2,
	    MONTO_SUBTOTAL_3,
		MARCA_1,
		MARCA_2,
		MARCA_3,
		MONTO_ASIGNADO_1,
		MONTO_ASIGNADO_2,
		MONTO_ASIGNADO_3,
		CORR_GRUPO
	)
	SELECT 	A.CORR_EMPRESA,
		CASE WHEN A.CORR_PROVEEDOR_GRUPO = 1 THEN  A.NOMBRE_PROVEEDOR ELSE '' END NOMBRE_PROVEEDOR_1,
		CASE WHEN A.CORR_PROVEEDOR_GRUPO = 2 THEN ISNULL(A.NOMBRE_PROVEEDOR,'') ELSE '' END NOMBRE_PROVEEDOR_2,
		CASE WHEN A.CORR_PROVEEDOR_GRUPO = 3 THEN ISNULL(A.NOMBRE_PROVEEDOR,'') ELSE '' END NOMBRE_PROVEEDOR_3,
		A.CODIGO_ITEM,
		A.NOMBRE_ITEM,
		B.CANTIDAD_COTIZAR,
		B.CORR_UNIDAD_MEDIDA,
		LTRIM(RTRIM(CONVERT(BIT,ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 1  THEN ISNULL(B.SELECCION,0) ELSE 0 END),2)))) SELECCION_1,
		LTRIM(RTRIM(CONVERT(BIT,ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 2  THEN ISNULL(B.SELECCION,0) ELSE 0 END),2)))) SELECCION_2,
		LTRIM(RTRIM(CONVERT(BIT,ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 3  THEN ISNULL(B.SELECCION,0) ELSE 0 END),2)))) SELECCION_3,
		LTRIM(RTRIM(CONVERT(DECIMAL(18,2),ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 1  THEN ISNULL(B.PRECIO_UNITARIO,0) ELSE 0 END),2)))) PRECIO_UNITARIO_1,
		LTRIM(RTRIM(CONVERT(DECIMAL(18,2),ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 2  THEN ISNULL(B.PRECIO_UNITARIO,0) ELSE 0 END),2)))) PRECIO_UNITARIO_2,
		LTRIM(RTRIM(CONVERT(DECIMAL(18,2),ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 3  THEN ISNULL(B.PRECIO_UNITARIO,0) ELSE 0 END),2)))) PRECIO_UNITARIO_3,										   										   
		LTRIM(RTRIM(CONVERT(DECIMAL(18,2),ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 1  THEN ISNULL(B.MONTO_SUBTOTAL,0) ELSE 0 END),2)))) MONTO_SUBTOTAL_1,
		LTRIM(RTRIM(CONVERT(DECIMAL(18,2),ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 2  THEN ISNULL(B.MONTO_SUBTOTAL,0) ELSE 0 END),2)))) MONTO_SUBTOTAL_2,
		LTRIM(RTRIM(CONVERT(DECIMAL(18,2),ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 3  THEN ISNULL(B.MONTO_SUBTOTAL,0) ELSE 0 END),2)))) MONTO_SUBTOTAL_3,
		LTRIM(RTRIM(CONVERT(VARCHAR(150),CASE WHEN A.CORR_PROVEEDOR_GRUPO = 1  THEN ISNULL(B.MARCA,'') ELSE '' END))) MARCA_1,
		LTRIM(RTRIM(CONVERT(VARCHAR(150),CASE WHEN A.CORR_PROVEEDOR_GRUPO = 2  THEN ISNULL(B.MARCA,'') ELSE '' END))) MARCA_2,
		LTRIM(RTRIM(CONVERT(VARCHAR(150),CASE WHEN A.CORR_PROVEEDOR_GRUPO = 3  THEN ISNULL(B.MARCA,'') ELSE '' END))) MARCA_3,
		LTRIM(RTRIM(CONVERT(DECIMAL(18,2),ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 1  THEN ISNULL(B.MONTO_ASIGNADO,0) ELSE 0 END),2)))) MONTO_ASIGNADO_1,
		LTRIM(RTRIM(CONVERT(DECIMAL(18,2),ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 2  THEN ISNULL(B.MONTO_ASIGNADO,0) ELSE 0 END),2)))) MONTO_ASIGNADO_2,
		LTRIM(RTRIM(CONVERT(DECIMAL(18,2),ROUND(SUM(CASE WHEN A.CORR_PROVEEDOR_GRUPO = 3  THEN ISNULL(B.MONTO_ASIGNADO,0) ELSE 0 END),2)))) MONTO_ASIGNADO_3,
		A.CORR_GRUPO
	FROM @ANALISIS_PROVEEDOR_ITEM A
	LEFT OUTER JOIN @ANALISIS_COTIZACION B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CODIGO_ITEM = B.CODIGO_ITEM AND A.CORR_PROVEEDOR = B.CORR_PROVEEDOR
	GROUP BY A.CORR_EMPRESA
	,A.NOMBRE_PROVEEDOR
	,A.CORR_PROVEEDOR_GRUPO
	,A.CODIGO_ITEM
	,A.NOMBRE_ITEM
	,B.CANTIDAD_COTIZAR
	,B.CORR_UNIDAD_MEDIDA
	,B.SELECCION
	,A.CORR_GRUPO
	,B.MARCA

	INSERT INTO @ANALISIS_COTIZACION_CARGADO_COP
	(
	    CORR_EMPRESA,
	    NOMBRE_PROVEEDOR_1,
	    NOMBRE_PROVEEDOR_2,
	    NOMBRE_PROVEEDOR_3,
		CODIGO_ITEM,
	    NOMBRE_ITEM,
	    CANTIDAD_COTIZAR,
	    CORR_UNIDAD_MEDIDA,
	    SELECCION_1,
		SELECCION_2,
		SELECCION_3,
	    PRECIO_UNITARIO_1,
	    PRECIO_UNITARIO_2,
	    PRECIO_UNITARIO_3,
	    MONTO_SUBTOTAL_1,
	    MONTO_SUBTOTAL_2,
	    MONTO_SUBTOTAL_3,
		MARCA_1,
		MARCA_2,
		MARCA_3,
		MONTO_ASIGNADO_1,
		MONTO_ASIGNADO_2,
		MONTO_ASIGNADO_3,
		CORR_GRUPO
	)
	SELECT A.CORR_EMPRESA,
	    CASE A.NOMBRE_PROVEEDOR_1 WHEN '' THEN (CASE A.CORR_GRUPO WHEN 1 THEN B.NOMBRE_PROVEEDOR_1 ELSE '' END)ELSE A.NOMBRE_PROVEEDOR_1  END NOMBRE_PROVEEDOR_1,
	    CASE A.NOMBRE_PROVEEDOR_2 WHEN '' THEN (CASE A.CORR_GRUPO WHEN 1 THEN B.NOMBRE_PROVEEDOR_2 ELSE '' END)ELSE A.NOMBRE_PROVEEDOR_2 END NOMBRE_PROVEEDOR_2,
	    CASE A.NOMBRE_PROVEEDOR_3 WHEN '' THEN (CASE A.CORR_GRUPO WHEN 1 THEN B.NOMBRE_PROVEEDOR_3 ELSE '' END)ELSE A.NOMBRE_PROVEEDOR_3  END NOMBRE_PROVEEDOR_3,
	    A.CODIGO_ITEM,
		A.NOMBRE_ITEM,
	    A.CANTIDAD_COTIZAR,
	    A.CORR_UNIDAD_MEDIDA,
	    A.SELECCION_1,
		A.SELECCION_2,
		A.SELECCION_3,
	    SUM(A.PRECIO_UNITARIO_1) PRECIO_UNITARIO_1,
	    SUM(A.PRECIO_UNITARIO_2) PRECIO_UNITARIO_2,
	    SUM(A.PRECIO_UNITARIO_3) PRECIO_UNITARIO_3,
	    SUM(A.MONTO_SUBTOTAL_1)MONTO_SUBTOTAL_1,
	    SUM(A.MONTO_SUBTOTAL_2)MONTO_SUBTOTAL_2,
	    SUM(A.MONTO_SUBTOTAL_3)MONTO_SUBTOTAL_3,
		A.MARCA_1,
		A.MARCA_2,
		A.MARCA_3,
		SUM(A.MONTO_ASIGNADO_1)MONTO_ASIGNADO_1,
		SUM(A.MONTO_ASIGNADO_2)MONTO_ASIGNADO_2,
		SUM(A.MONTO_ASIGNADO_3)MONTO_ASIGNADO_3,
		A.CORR_GRUPO GRUPO_GENERAL
	FROM @ANALISIS_COTIZACION_CARGADO A
	LEFT OUTER JOIN @CONCATENACION B ON A.CORR_GRUPO = B.CORR_GRUPO
	WHERE A.CORR_GRUPO=1
	GROUP BY A.CORR_EMPRESA,
		A.CODIGO_ITEM,
		A.NOMBRE_ITEM,
	    A.CANTIDAD_COTIZAR,
	    A.CORR_UNIDAD_MEDIDA,
		A.CORR_GRUPO,
		A.NOMBRE_PROVEEDOR_1,
		A.NOMBRE_PROVEEDOR_2,
		A.NOMBRE_PROVEEDOR_3,
		B.NOMBRE_PROVEEDOR_1,
		B.NOMBRE_PROVEEDOR_2,
		B.NOMBRE_PROVEEDOR_3,
		A.SELECCION_1,
		A.SELECCION_2,
		A.SELECCION_3,
		A.MARCA_1,
		A.MARCA_2,
		A.MARCA_3

	INSERT INTO @ANALISIS_COTIZACION_CARGADO_COP
	(
	    CORR_EMPRESA,
	    NOMBRE_PROVEEDOR_1,
	    NOMBRE_PROVEEDOR_2,
	    NOMBRE_PROVEEDOR_3,
		CODIGO_ITEM,
	    NOMBRE_ITEM,
	    CANTIDAD_COTIZAR,
	    CORR_UNIDAD_MEDIDA,
	    SELECCION_1,
		SELECCION_2,
		SELECCION_3,
	    PRECIO_UNITARIO_1,
	    PRECIO_UNITARIO_2,
	    PRECIO_UNITARIO_3,
	    MONTO_SUBTOTAL_1,
	    MONTO_SUBTOTAL_2,
	    MONTO_SUBTOTAL_3,
		MARCA_1,
		MARCA_2,
		MARCA_3,
		MONTO_ASIGNADO_1,
		MONTO_ASIGNADO_2,
		MONTO_ASIGNADO_3,
		CORR_GRUPO
	)
	SELECT A.CORR_EMPRESA,
	    CASE A.NOMBRE_PROVEEDOR_1 WHEN '' THEN (CASE A.CORR_GRUPO WHEN 2 THEN B.NOMBRE_PROVEEDOR_1 ELSE '' END)ELSE A.NOMBRE_PROVEEDOR_1  END NOMBRE_PROVEEDOR_1,
	    CASE A.NOMBRE_PROVEEDOR_2 WHEN '' THEN (CASE A.CORR_GRUPO WHEN 2 THEN B.NOMBRE_PROVEEDOR_2 ELSE '' END)ELSE A.NOMBRE_PROVEEDOR_2 END NOMBRE_PROVEEDOR_2,
	    CASE A.NOMBRE_PROVEEDOR_3 WHEN '' THEN (CASE A.CORR_GRUPO WHEN 2 THEN B.NOMBRE_PROVEEDOR_3 ELSE '' END)ELSE A.NOMBRE_PROVEEDOR_3  END NOMBRE_PROVEEDOR_3,
	    A.CODIGO_ITEM,
		A.NOMBRE_ITEM,
	    A.CANTIDAD_COTIZAR,
	    A.CORR_UNIDAD_MEDIDA,
	    A.SELECCION_1,
		A.SELECCION_2,
		A.SELECCION_3,
	    A.PRECIO_UNITARIO_1,
	    A.PRECIO_UNITARIO_2,
	    A.PRECIO_UNITARIO_3,
	    A.MONTO_SUBTOTAL_1,
	    A.MONTO_SUBTOTAL_2,
	    A.MONTO_SUBTOTAL_3,
		A.MARCA_1,
		A.MARCA_2,
		A.MARCA_3,
		A.MONTO_ASIGNADO_1,
		A.MONTO_ASIGNADO_2,
		A.MONTO_ASIGNADO_3,
		A.CORR_GRUPO GRUPO_GENERAL
	FROM @ANALISIS_COTIZACION_CARGADO A
	LEFT OUTER JOIN @CONCATENACION B ON A.CORR_GRUPO = B.CORR_GRUPO
	WHERE A.CORR_GRUPO=2

	;WITH CTE_CUADRO_COMPARATIVO_IMPRIME (
		CORR_EMPRESA,
		NOMBRE_PROVEEDOR_1,
		NOMBRE_PROVEEDOR_2,
		NOMBRE_PROVEEDOR_3,
		CODIGO_ITEM,
		NOMBRE_ITEM,
		CANTIDAD_COTIZAR,
		CORR_UNIDAD_MEDIDA,
		NOMBRE_UNIDAD_MEDIDA,
		SELECCION_1,
		SELECCION_2,
		SELECCION_3,
		PRECIO_UNITARIO_1,
		PRECIO_UNITARIO_2,
		PRECIO_UNITARIO_3,
		MONTO_SUBTOTAL_1,
		MONTO_SUBTOTAL_2,
		MONTO_SUBTOTAL_3,
		MARCA_1,
		MARCA_2,
		MARCA_3,
		MONTO_ASIGNADO_1,
		MONTO_ASIGNADO_2,
		MONTO_ASIGNADO_3,
		GRUPO_GENERAL
	)
	AS
	(
		SELECT A.CORR_EMPRESA,
			A.NOMBRE_PROVEEDOR_1,
			A.NOMBRE_PROVEEDOR_2,
			A.NOMBRE_PROVEEDOR_3,
			A.CODIGO_ITEM,
			A.NOMBRE_ITEM,
			A.CANTIDAD_COTIZAR,
			A.CORR_UNIDAD_MEDIDA,
			B.NOMBRE_UNIDAD_MEDIDA,
			MAX(CONVERT(INT,A.SELECCION_1)) SELECCION_1,
			MAX(CONVERT(INT,A.SELECCION_2)) SELECCION_2,
			MAX(CONVERT(INT,A.SELECCION_3)) SELECCION_3,
			SUM(A.PRECIO_UNITARIO_1)PRECIO_UNITARIO_1,
			SUM(A.PRECIO_UNITARIO_2)PRECIO_UNITARIO_2,
			SUM(A.PRECIO_UNITARIO_3)PRECIO_UNITARIO_3,
			SUM(A.MONTO_SUBTOTAL_1)MONTO_SUBTOTAL_1,
			SUM(A.MONTO_SUBTOTAL_2)MONTO_SUBTOTAL_2,
			SUM(A.MONTO_SUBTOTAL_3)MONTO_SUBTOTAL_3,
			dbo.StrConcat(A.MARCA_1+' ')MARCA_1,
			dbo.StrConcat(A.MARCA_2+' ')MARCA_2,
			dbo.StrConcat(A.MARCA_3+' ')MARCA_3,
			SUM(A.MONTO_ASIGNADO_1)MONTO_ASIGNADO_1,
			SUM(A.MONTO_ASIGNADO_2)MONTO_ASIGNADO_2,
			SUM(A.MONTO_ASIGNADO_3)MONTO_ASIGNADO_3,
			A.CORR_GRUPO GRUPO_GENERAL
			FROM @ANALISIS_COTIZACION_CARGADO_COP A
		INNER JOIN COM_UNIDAD_MEDIDA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_UNIDAD_MEDIDA = B.CORR_UNIDAD_MEDIDA
		WHERE A.CANTIDAD_COTIZAR IS NOT NULL
		AND A.CORR_UNIDAD_MEDIDA IS NOT NULL
		GROUP BY A.CORR_EMPRESA,
					A.NOMBRE_PROVEEDOR_1,
					A.NOMBRE_PROVEEDOR_2,
					A.NOMBRE_PROVEEDOR_3,
					A.CODIGO_ITEM,
					A.NOMBRE_ITEM,
					A.CANTIDAD_COTIZAR,
					A.CORR_UNIDAD_MEDIDA,
					B.NOMBRE_UNIDAD_MEDIDA,
					A.CORR_GRUPO
					)


	SELECT A.CORR_EMPRESA
		,@FECHA_CUADRO_COMPARATIVO FECHA_CUADRO_COMPARATIVO
		,CONVERT(VARCHAR(4),@ANIO_PERIODO)+'-'+CONVERT(VARCHAR(15),@CORR_CUADRO_COMPARATIVO) NUMERO_CUADRO_COMPARATIVO
		,@NOMBRE_DEPARTAMENTO NOMBRE_DEPARTAMENTO
		,@ES_MEJOR_PRECIO ES_MEJOR_PRECIO
		,@TIENE_CREDITO_30_DIAS TIENE_CREDITO_30_DIAS
		,@TIENE_BUEN_SOPORTE_TECNICO TIENE_BUEN_SOPORTE_TECNICO
		,@TIENE_BUENA_CALIDAD_PRODUCTO TIENE_BUENA_CALIDAD_PRODUCTO
		,@TIENE_MEJOR_TIEMPO_ENTREGA TIENE_MEJOR_TIEMPO_ENTREGA
		,@BRINDA_BUENA_EXPERIENCIA_PROVEEDOR BRINDA_BUENA_EXPERIENCIA_PROVEEDOR
		,@ES_PROVEEDOR_UNICO ES_PROVEEDOR_UNICO 
		,@EXISTE_OTRA_RAZON EXISTE_OTRA_RAZON
		,@NOMBRE_OTRA_RAZON NOMBRE_OTRA_RAZON
		,A.NOMBRE_PROVEEDOR_1
		,A.NOMBRE_PROVEEDOR_2
		,A.NOMBRE_PROVEEDOR_3
		,A.CODIGO_ITEM
		,A.NOMBRE_ITEM
		,A.CANTIDAD_COTIZAR CANTIDAD
		,A.CORR_UNIDAD_MEDIDA
		,A.NOMBRE_UNIDAD_MEDIDA
		,CONVERT(BIT,A.SELECCION_1)SELECCION_1
		,CONVERT(BIT,A.SELECCION_2)SELECCION_2
		,CONVERT(BIT,A.SELECCION_3)SELECCION_3
		,A.PRECIO_UNITARIO_1
		,A.PRECIO_UNITARIO_2
		,A.PRECIO_UNITARIO_3
		,A.MONTO_SUBTOTAL_1
		,A.MONTO_SUBTOTAL_2
		,A.MONTO_SUBTOTAL_3
		,A.MARCA_1
		,A.MARCA_2
		,A.MARCA_3
		,A.MONTO_ASIGNADO_1
		,A.MONTO_ASIGNADO_2
		,A.MONTO_ASIGNADO_3
		,A.GRUPO_GENERAL
		,E.NOMBRE_EMPRESA
		--,E.LOGO_1 LOGO1
		,CASE WHEN ROW_NUMBER() OVER(ORDER BY A.CORR_EMPRESA)=1 THEN E.LOGO_1 ELSE NULL END LOGO1
		,'IMPRESIÓN CUADRO COMPARATIVO'TITULO_REPORTE
		,'Sistema Compras UEES'NOMBRE_SISTEMA
		,GETDATE() FECHA_IMPRESION
		,@NOMBRE_USUARIO_CUADRO_COMPARATIVO NOMBRE_USUARIO_CREA
		,H.FIRMA1
		,H.NOMBRE_FIRMA1
		,H.FECHA_FIRMA1
		,H.FIRMA2
		,H.NOMBRE_FIRMA2
		,H.FECHA_FIRMA2
		,H.FIRMA3
		,H.NOMBRE_FIRMA3
		,H.FECHA_FIRMA3
		,H.FIRMA4
		,H.NOMBRE_FIRMA4
		,H.FECHA_FIRMA4
	FROM CTE_CUADRO_COMPARATIVO_IMPRIME A
	INNER JOIN COM_PARAMETRO B ON A.CORR_EMPRESA = B.CORR_EMPRESA
	INNER JOIN GEN_EMPRESA E ON A.CORR_EMPRESA = E.CORR_EMPRESA
	LEFT OUTER JOIN V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_SUM H ON A.CORR_EMPRESA = H.CORR_EMPRESA AND @ANIO_PERIODO = H.ANIO_PERIODO AND @CORR_CUADRO_COMPARATIVO = H.CORR_CUADRO_COMPARATIVO


FINA:	

END
GO
