
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_GENE_CON_MOVIMIENTO_INICIAL_BANCOS]
(
	@CORR_EMPRESA int,	
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_CLASE_PARTIDA int,
	@CORR_PARTIDA int OUTPUT,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
	DECLARE @CORR_TIPO_MOVIMIENTO_SUMA INT
	DECLARE @CORR_TIPO_MOVIMIENTO_RESTA INT
	
	DECLARE @CON_PARTIDA_DETA TABLE
	(
	   CUENTA_CONTABLE VARCHAR(30),
	   CORR_CUENTA_BANCO INT NULL,
	   NOMBRE_TRAN VARCHAR(1255),
	   MONTO_CARGO DECIMAL(12,2),
	   MONTO_ABONO DECIMAL(12,2),
	   CORR_AUXILIAR INT NULL
	)
BEGIN
	
	SET NOCOUNT ON
	
	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0
	
	BEGIN TRY
	
		IF EXISTS ( SELECT 1 FROM CON_PARTIDA
					WHERE CORR_EMPRESA=@CORR_EMPRESA
					AND CLASE_PARTIDA='INI')
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Ya se generaron los saldos iniciales bancarios.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END
	
		SELECT @CORR_TIPO_MOVIMIENTO_SUMA=ISNULL(CORR_TIPO_MOVIMIENTO_SUMA,0), @CORR_TIPO_MOVIMIENTO_RESTA=ISNULL(CORR_TIPO_MOVIMIENTO_RESTA,0)
		FROM BAN_PARAMETRO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		
		IF EXISTS ( SELECT 1 FROM BAN_TIPO_MOVI_BANCARIO 
					WHERE CORR_EMPRESA=@CORR_EMPRESA
					AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO_SUMA )
		AND EXISTS (SELECT 1 FROM BAN_TIPO_MOVI_BANCARIO 
					WHERE CORR_EMPRESA=@CORR_EMPRESA
					AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO_RESTA )
		BEGIN
		
			DELETE A FROM BAN_MOVIMIENTO A
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.CORR_MOVIMIENTO=0
	
		    INSERT INTO BAN_MOVIMIENTO ( CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_CUENTA_BANCO, CORR_MOVIMIENTO, FECHA_MOVIMIENTO, 
		    CORR_TIPO_MOVIMIENTO, REFERENCIA, NOMBRE_BENEFICIARIO, DESCRIPCION_MOVIMIENTO, MONTO_CARGO, MONTO_ABONO, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
		    SELECT @ @ @CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, C.CORR_CUENTA_BANCO, 0, D.FECHA_PARTIDA, 
		    CASE WHEN ISNULL(SUM(A.MONTO_CARGO),0)>ISNULL(SUM(A.MONTO_ABONO),0) THEN @CORR_TIPO_MOVIMIENTO_SUMA ELSE @CORR_TIPO_MOVIMIENTO_RESTA END, 
		    '', '', A.NOMBRE_TRAN, 
		    CASE WHEN ISNULL(SUM(A.MONTO_CARGO),0)>ISNULL(SUM(A.MONTO_ABONO),0) THEN CASE WHEN C.CORR_MONEDA=E.CORR_MONEDA THEN ISNULL(SUM(A.MONTO_CARGO),0)-ISNULL(SUM(MONTO_ABONO),0) ELSE ISNULL(SUM(A.MONTO_CARGO_FORANEA),0)-ISNULL(SUM(MONTO_ABONO_FORANEA),0) END ELSE 0 END,
		    CASE WHEN ISNULL(SUM(A.MONTO_ABONO),0)>ISNULL(SUM(A.MONTO_CARGO),0) THEN CASE WHEN C.CORR_MONEDA=E.CORR_MONEDA THEN ISNULL(SUM(MONTO_ABONO),0)-ISNULL(SUM(A.MONTO_CARGO),0) ELSE ISNULL(SUM(MONTO_ABONO),0)-ISNULL(SUM(A.MONTO_CARGO),0) END ELSE 0 END,
		    @SYS_LOGIN_USUARIO, GETDATE(), @SYS_ESTACION
			FROM CON_PARTIDA_DETA A
			INNER JOIN CON_CATALOGO_CUENTA_AUXI B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE AND A.CORR_AUXILIAR=B.CORR_AUXILIAR AND 'CB'=B.CLASE_AUXILIAR
			INNER JOIN BAN_CUENTA_BANCARIA C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CORR_CUENTA_BANCO=C.CORR_CUENTA_BANCO
			INNER JOIN CON_PARTIDA D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.ANIO_PERIODO=D.ANIO_PERIODO AND A.MES_PERIODO=D.MES_PERIODO AND A.CORR_CLASE_PARTIDA=D.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=D.CORR_PARTIDA
			INNER JOIN GEN_EMPRESA E ON C.CORR_EMPRESA=E.CORR_EMPRESA 
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.MES_PERIODO=@MES_PERIODO
			AND A.CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
			AND A.CORR_PARTIDA=@CORR_PARTIDA
			GROUP BY C.CORR_CUENTA_BANCO, D.FECHA_PARTIDA, A.NOMBRE_TRAN, C.CORR_MONEDA, E.CORR_MONEDA
			
			UPDATE CON_PARTIDA SET
			CLASE_PARTIDA='INI'
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
			AND CORR_PARTIDA=@CORR_PARTIDA
		END ELSE
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='No se ha configurado correctamente los parametros de los movimientos bancarios iniciales.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END
			
		
		
	END TRY

	BEGIN CATCH
		--IF @@TRANCOUNT>0
		--BEGIN
		--	ROLLBACK TRANSACTION
		--END
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
