SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_SEG_USUARIO]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@LOGIN_SISTEMA VARCHAR(30) OUTPUT,
	@NOMBRE_USUARIO varchar(100),
	@CLAVE_USUARIO varbinary(max)=NULL,
	@CLAVE_USUARIO_SAL varbinary(max)=NULL,
	@CORREO_ELECTRONICO varchar(255),
	@TIPO_USUARIO int,
	@ESTADO_USUARIO int,
	@IDIOMA varchar(100)='es-SV',
	@CORR_EMPLEADO INT=NULL,
	@USUARIO_CREA varchar(30),
	@FECHA_CREA datetime,
	@ESTACION_CREA varchar(50),
	@USUARIO_ACTU varchar(30),
	@FECHA_ACTU datetime,
	@ESTACION_ACTU varchar(50),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	DECLARE  @POR_DEFECTO INT = 1
	SET NOCOUNT ON
	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY

		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN			
			IF EXISTS (SELECT 1 FROM SEG_USUARIO 
						WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA)
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Ya existe usuario con este login..',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			INSERT INTO SEG_USUARIO
			(LOGIN_SISTEMA,NOMBRE_USUARIO,CLAVE_USUARIO,CLAVE_USUARIO_SAL,CORREO_ELECTRONICO,TIPO_USUARIO,ESTADO_USUARIO,IDIOMA,USUARIO_CREA,FECHA_CREA,ESTACION_CREA)
			VALUES
			(@LOGIN_SISTEMA,@NOMBRE_USUARIO,@CLAVE_USUARIO,@CLAVE_USUARIO_SAL,@CORREO_ELECTRONICO,@TIPO_USUARIO,@ESTADO_USUARIO,@IDIOMA,@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA)

			EXECUTE PRAL_MTTO_SEG_USUARIO_EMPRESA
				@TIPO_ACTUALIZA,             
				@LOGIN_SISTEMA,        
				@CORR_EMPRESA OUTPUT,        
				@POR_DEFECTO,                
				@SYS_LOGIN_USUARIO,          
				@SYS_ESTACION,               
				@SYS_FILAS_AFECTADAS OUTPUT, 
				@SYS_NUMERO_ERROR OUTPUT,    
				@SYS_MENSAJE_ERROR OUTPUT 
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE SEG_USUARIO
			SET NOMBRE_USUARIO=@NOMBRE_USUARIO,			
			CORREO_ELECTRONICO=@CORREO_ELECTRONICO,
			TIPO_USUARIO=@TIPO_USUARIO,
			ESTADO_USUARIO=@ESTADO_USUARIO,
			IDIOMA=@IDIOMA,
			USUARIO_ACTU=@USUARIO_ACTU,
			FECHA_ACTU=@FECHA_ACTU,
			ESTACION_ACTU=@ESTACION_ACTU
			WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA 
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE SEG_USUARIO_FOTO
			WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA

		    DELETE SEG_USUARIO_OPCION
			WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA

			DELETE SEG_USUARIO_EMPRESA
			WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA

		    DELETE SEG_USUARIO
			WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA
		END

		EXEC PRAL_GENE_SEG_USUARIO_PROVEEDOR
			@LOGIN_SISTEMA,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS OUTPUT,
			@SYS_NUMERO_ERROR OUTPUT,
			@SYS_MENSAJE_ERROR OUTPUT

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

	END TRY
	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int           ,
		@SEVERITY_ERROR  int           ,
		@ESTADO_ERROR     int           ,
		@ORIGEN_ERROR nvarchar(126) ,
		@LINEA_ERROR      int	     ,
		@SYS_FECHA DateTime   

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION


	END CATCH;

FINA:
END

RETURN 0
GO
