SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- Procedimiento para obtener historial de claves recientes
CREATE PROCEDURE [dbo].[PRAL_DATA_SEG_USUARIO_VALIDAR_CLAVE_ANTERIOR]
(
	@LOGIN_SISTEMA varchar(30),
	@NUMERO_ULTIMAS_CLAVES int = 5  -- Ultimas 5 claves por defecto
)
AS
BEGIN
	SET NOCOUNT ON

	SELECT TOP (@NUMERO_ULTIMAS_CLAVES)
		LOGIN_SISTEMA,
		CLAVE_USUARIO,
		CLAVE_USUARIO_SAL,
		FECHA_CAMBIO
	FROM [dbo].[SEG_USUARIO_CLAVE_HISTORIAL]
	WHERE LOGIN_SISTEMA = @LOGIN_SISTEMA
	ORDER BY FECHA_CAMBIO DESC
END
GO

PRINT 'Procedimiento PRAL_DATA_SEG_USUARIO_VALIDAR_CLAVE_ANTERIOR creado exitosamente';
