SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_CON_LIBRO_IVA_VENTAS_CONSU_FINALES]
( 
  @CORR_EMPRESA INT,
  @CORR_TIENDA INT,
  @ANIO_PERIODO INT,
  @MES_PERIODO INT,
  @OPCION_CONSULTA INT
)
AS
	DECLARE @TEMP1 TABLE (
		CORR_EMPRESA INT,
		CORR_TIENDA INT,
		NIT_TIENDA VARCHAR(30),
		REGISTRO_FISCAL_TIENDA VARCHAR(30),
		ANIO_PERIODO INT,
		MES_PERIODO INT,
		FECHA_DOCUMENTO DATE,
		DESDE VARCHAR(50),
		HASTA VARCHAR(50),
		COMPROBANTE_LIQUIDACION VARCHAR(50),
		MANDANTE VARCHAR(50),		
		VENTAS_PROPIAS_EXENTA DECIMAL(12,2),	
		VENTAS_PROPIAS_NO_SUJETAS DECIMAL(12,2),
		VENTAS_PROPIAS_GRAVADA DECIMAL(12,2),	
		VENTAS_PROPIAS_GRAVADAS_EXPORTACION DECIMAL(12,2),
		VENTAS_PROPIAS_IVA DECIMAL(12,2),	
		VENTAS_TERCEROS_EXENTA DECIMAL(12,2),
		VENTAS_TERCEROS_NO_SUJETAS DECIMAL(12,2),
		VENTAS_TERCEROS_GRAVADA DECIMAL(12,2),
		VENTAS_TERCEROS_GRAVADAS_EXPORTACION DECIMAL(12,2),
		VENTAS_TERCEROS_IVA DECIMAL(12,2),
		VENTAS_TOTAL DECIMAL(12,2),
		CORR_RUTA_VENTA INT,
		NOMBRE_RUTA_VENTA VARCHAR(50),
		PRIMARY KEY (
			CORR_EMPRESA,
			CORR_TIENDA,
			ANIO_PERIODO,
			MES_PERIODO,
			DESDE,
			HASTA,
			CORR_RUTA_VENTA
		)
    )

	DECLARE @TEMP2 TABLE (
		CORR_EMPRESA INT,
		CORR_TIENDA INT,
		CORR_DOCUMENTO INT,
		NIT_TIENDA VARCHAR(30),
		REGISTRO_FISCAL_TIENDA VARCHAR(30),
		ANIO_PERIODO INT,
		MES_PERIODO INT,
		FECHA_DOCUMENTO DATE,
		NUMERO_DOCUMENTO INT,
		SERIE VARCHAR(25),
		COMPROBANTE_LIQUIDACION VARCHAR(50),
		MANDANTE VARCHAR(50),		
		VENTAS_PROPIAS_EXENTA DECIMAL(12,2),	
		VENTAS_PROPIAS_NO_SUJETAS DECIMAL(12,2),
		VENTAS_PROPIAS_GRAVADA DECIMAL(12,2),	
		VENTAS_PROPIAS_GRAVADAS_EXPORTACION DECIMAL(12,2),
		VENTAS_PROPIAS_IVA DECIMAL(12,2),	
		VENTAS_TERCEROS_EXENTA DECIMAL(12,2),
		VENTAS_TERCEROS_NO_SUJETAS DECIMAL(12,2),
		VENTAS_TERCEROS_GRAVADA DECIMAL(12,2),
		VENTAS_TERCEROS_GRAVADAS_EXPORTACION DECIMAL(12,2),
		VENTAS_TERCEROS_IVA DECIMAL(12,2),
		VENTAS_TOTAL DECIMAL(12,2),
		CORR_RUTA_VENTA INT,
		NOMBRE_RUTA_VENTA VARCHAR(50),
		PRIMARY KEY (
			CORR_EMPRESA,
			CORR_TIENDA,
			ANIO_PERIODO,
			MES_PERIODO,
			NUMERO_DOCUMENTO,
			SERIE,			
			CORR_DOCUMENTO
		)
	)

	DECLARE @TEMP3 TABLE (
		CORR_EMPRESA INT,
		CORR_TIENDA INT,
		CORR_DOCUMENTO INT,
		NIT_TIENDA VARCHAR(30),
		REGISTRO_FISCAL_TIENDA VARCHAR(30),
		ANIO_PERIODO INT,
		MES_PERIODO INT,
		FECHA_DOCUMENTO DATE,
		NUMERO_DOCUMENTO INT,
		SERIE VARCHAR(25),
		COMPROBANTE_LIQUIDACION VARCHAR(50),
		MANDANTE VARCHAR(50),		
		VENTAS_PROPIAS_EXENTA DECIMAL(12,2),	
		VENTAS_PROPIAS_NO_SUJETAS DECIMAL(12,2),
		VENTAS_PROPIAS_GRAVADA DECIMAL(12,2),	
		VENTAS_PROPIAS_GRAVADAS_EXPORTACION DECIMAL(12,2),
		VENTAS_PROPIAS_IVA DECIMAL(12,2),	
		VENTAS_TERCEROS_EXENTA DECIMAL(12,2),
		VENTAS_TERCEROS_NO_SUJETAS DECIMAL(12,2),
		VENTAS_TERCEROS_GRAVADA DECIMAL(12,2),
		VENTAS_TERCEROS_GRAVADAS_EXPORTACION DECIMAL(12,2),
		VENTAS_TERCEROS_IVA DECIMAL(12,2),
		VENTAS_TOTAL DECIMAL(12,2),
		CORR_RUTA_VENTA INT,
		NOMBRE_RUTA_VENTA VARCHAR(50),
		PRIMARY KEY (
			CORR_EMPRESA,
			CORR_TIENDA,
			ANIO_PERIODO,
			MES_PERIODO,
			SERIE,
			NUMERO_DOCUMENTO,
			CORR_DOCUMENTO
		)
	)
BEGIN

    SET NOCOUNT ON	

	INSERT INTO @TEMP2
    SELECT A.CORR_EMPRESA
	,A.CORR_TIENDA
	,ROW_NUMBER() OVER(PARTITION BY A.ANIO_PERIODO,A.MES_PERIODO,CASE WHEN ISNULL(A.NUMERO_CONTROL,'')<>'' THEN CONVERT(INT,SUBSTRING(A.NUMERO_CONTROL,17,15)) ELSE A.NUMERO_DOCUMENTO END,ISNULL(A.SERIE,'') 
				 ORDER BY A.ANIO_PERIODO,A.MES_PERIODO,CASE WHEN ISNULL(A.NUMERO_CONTROL,'')<>'' THEN CONVERT(INT,SUBSTRING(A.NUMERO_CONTROL,17,15)) ELSE A.NUMERO_DOCUMENTO END,ISNULL(A.SERIE,''))
	,D.NUMERO_NIT
	,D.NUMERO_NRC
	,A.ANIO_PERIODO
	,A.MES_PERIODO
	,A.FECHA_DOCUMENTO
	,CASE WHEN ISNULL(A.NUMERO_CONTROL,'')<>'' THEN CONVERT(INT,SUBSTRING(A.NUMERO_CONTROL,17,15)) ELSE A.NUMERO_DOCUMENTO END
	,ISNULL(A.SERIE,'')
	,F.NUMERO_COMPRO_LIQUIDA COMPROBANTE_LIQUIDACION
	,CASE WHEN ISNULL(F.CORR_PRODUCTORA,0)=0 THEN '' ELSE F.NOMBRE_PROVEEDOR END MANDANTE
    ,SUM(CASE WHEN C.CLASE_RUBRO='EXE' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)	  VENTAS_PROPIAS_EXENTA
    ,SUM(CASE WHEN C.CLASE_RUBRO='NSU' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)	  NO_SUJETO_VENTAS_PROPIAS
    ,SUM(CASE WHEN C.CLASE_RUBRO='GRA' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)+SUM(CASE WHEN C.CLASE_RUBRO='IVA' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)	  VENTAS_PROPIAS_GRAVADA
	,0 VENTAS_PROPIAS_GRAVADAS_EXPORTACION
    ,SUM(CASE WHEN C.CLASE_RUBRO='IVA' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)	  VENTAS_PROPIAS_IVA
	,0
	,0
	,0
	,0
	,0
    ,SUM(CASE WHEN C.CLASE_RUBRO='VTO' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)   VENTAS_TOTAL
	,A.CORR_RUTA_VENTA
	,E.NOMBRE_RUTA_VENTA
    FROM V_VEN_DOCUMENTO A
    INNER JOIN GEN_TIPO_DOCUMENTO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIPO_DOC=B.CORR_TIPO_DOC 
    INNER JOIN V_VEN_DOCUMENTO_TOTAL C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_TIENDA=C.CORR_TIENDA AND A.ANIO_PERIODO=C.ANIO_PERIODO AND A.MES_PERIODO=C.MES_PERIODO AND A.CORR_DOCUMENTO=C.CORR_DOCUMENTO 
    INNER JOIN GEN_EMPRESA D ON A.CORR_EMPRESA=D.CORR_EMPRESA 
	INNER JOIN VEN_RUTA_VENTA E ON A.CORR_EMPRESA = E.CORR_EMPRESA AND A.CORR_RUTA_VENTA = E.CORR_RUTA_VENTA
	LEFT OUTER JOIN V_VEN_COMPRO_LIQUIDA F ON A.CORR_EMPRESA=F.CORR_EMPRESA AND A.ANIO_PERIODO_LIQUIDA=F.ANIO_PERIODO AND A.MES_PERIODO_LIQUIDA=F.MES_PERIODO AND A.CORR_COMPRO_LIQUIDA=F.CORR_COMPRO_LIQUIDA
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
    AND (A.CORR_TIENDA=@CORR_TIENDA OR A.CORR_TIENDA IS NULL)
    AND YEAR(A.FECHA_DOCUMENTO)=@ANIO_PERIODO
    AND MONTH(A.FECHA_DOCUMENTO)=@MES_PERIODO
    AND B.LIBRO_IVA='VNC' --VENTAS NO CONTRIBUYENTES
	AND A.ESTADO_FACTURA='AP'
	AND EXISTS (SELECT 1 
				FROM VEN_DOCUMENTO_DETA AA
				INNER JOIN V_INV_TIPO_ITEM BB ON BB.CORR_EMPRESA = AA.CORR_EMPRESA AND BB.CORR_TIPO_ITEM = AA.CORR_TIPO_ITEM
				AND A.CORR_EMPRESA = AA.CORR_EMPRESA 
				AND A.CORR_TIENDA = AA.CORR_TIENDA 
				AND A.ANIO_PERIODO = AA.ANIO_PERIODO 
				AND A.MES_PERIODO = AA.MES_PERIODO 
				AND A.CORR_DOCUMENTO = AA.CORR_DOCUMENTO
				AND BB.ES_TERCERO = 0
				--AND BB.NOMBRE_TIPO_ITEM LIKE '%COMERCIAL%'
				)
    GROUP BY CASE
             WHEN ISNULL(F.CORR_PRODUCTORA, 0) = 0 THEN
             ''
             ELSE
             F.NOMBRE_PROVEEDOR
             END,
             A.CORR_EMPRESA,
             A.CORR_TIENDA,
             D.NUMERO_NIT,
             D.NUMERO_NRC,
             A.ANIO_PERIODO,
             A.MES_PERIODO,
             A.FECHA_DOCUMENTO,
             CASE WHEN ISNULL(A.NUMERO_CONTROL,'')<>'' THEN CONVERT(INT,SUBSTRING(A.NUMERO_CONTROL,17,15)) ELSE A.NUMERO_DOCUMENTO END,
             ISNULL(A.SERIE,''),
             F.NUMERO_COMPRO_LIQUIDA,
             A.CORR_RUTA_VENTA,
             E.NOMBRE_RUTA_VENTA
    ORDER BY A.FECHA_DOCUMENTO 

	--TERCEROS
	INSERT INTO @TEMP2
    SELECT A.CORR_EMPRESA
	,A.CORR_TIENDA
	,ROW_NUMBER() OVER( PARTITION BY A.ANIO_PERIODO,A.MES_PERIODO,CASE WHEN ISNULL(A.NUMERO_CONTROL,'')<>'' THEN CONVERT(INT,SUBSTRING(A.NUMERO_CONTROL,17,15)) ELSE A.NUMERO_DOCUMENTO END,ISNULL(A.SERIE,'') 
						ORDER BY A.ANIO_PERIODO,A.MES_PERIODO,CASE WHEN ISNULL(A.NUMERO_CONTROL,'')<>'' THEN CONVERT(INT,SUBSTRING(A.NUMERO_CONTROL,17,15)) ELSE A.NUMERO_DOCUMENTO END,ISNULL(A.SERIE,''))
	,D.NUMERO_NIT
	,D.NUMERO_NRC
	,A.ANIO_PERIODO
	,A.MES_PERIODO
	,A.FECHA_DOCUMENTO
	,CASE WHEN ISNULL(A.NUMERO_CONTROL,'')<>'' THEN CONVERT(INT,SUBSTRING(A.NUMERO_CONTROL,17,15)) ELSE A.NUMERO_DOCUMENTO END
	,ISNULL(A.SERIE,'')
	,F.NUMERO_COMPRO_LIQUIDA COMPROBANTE_LIQUIDACION
	,CASE WHEN ISNULL(F.CORR_PRODUCTORA,0)=0 THEN '' ELSE F.NOMBRE_PROVEEDOR END MANDANTE
    ,0																					
	,0
	,0
	,0
	,0
	,SUM(CASE WHEN C.CLASE_RUBRO='EXE' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)	  VENTAS_TERCEROS_EXENTA
    ,SUM(CASE WHEN C.CLASE_RUBRO='NSU' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)	  NO_SUJETO_VENTAS_TERCEROS_GRAVADA
    ,SUM(CASE WHEN C.CLASE_RUBRO='GRA' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)+SUM(CASE WHEN C.CLASE_RUBRO='IVA' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)	  VENTAS_TERCEROS_GRAVADA
	,0 VENTAS_TERCEROS_GRAVADAS_EXPORTACION
    ,SUM(CASE WHEN C.CLASE_RUBRO='IVA' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)	  VENTAS_TERCEROS_IVA
	,SUM(CASE WHEN C.CLASE_RUBRO='VTO' THEN C.MONTO_RUBRO*A.SUMA_RESTA ELSE 0 END)   VENTAS_TOTAL
	,A.CORR_RUTA_VENTA
	,E.NOMBRE_RUTA_VENTA
    FROM V_VEN_DOCUMENTO A
    INNER JOIN GEN_TIPO_DOCUMENTO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_TIPO_DOC=B.CORR_TIPO_DOC 
    INNER JOIN V_VEN_DOCUMENTO_TOTAL C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_TIENDA=C.CORR_TIENDA AND A.ANIO_PERIODO=C.ANIO_PERIODO AND A.MES_PERIODO=C.MES_PERIODO AND A.CORR_DOCUMENTO=C.CORR_DOCUMENTO 
    INNER JOIN GEN_EMPRESA D ON A.CORR_EMPRESA=D.CORR_EMPRESA 
	INNER JOIN VEN_RUTA_VENTA E ON A.CORR_EMPRESA = E.CORR_EMPRESA AND A.CORR_RUTA_VENTA = E.CORR_RUTA_VENTA
	LEFT OUTER JOIN V_VEN_COMPRO_LIQUIDA F ON A.CORR_EMPRESA=F.CORR_EMPRESA AND A.ANIO_PERIODO_LIQUIDA=F.ANIO_PERIODO AND A.MES_PERIODO_LIQUIDA=F.MES_PERIODO AND A.CORR_COMPRO_LIQUIDA=F.CORR_COMPRO_LIQUIDA
    WHERE A.CORR_EMPRESA=@CORR_EMPRESA
    AND (A.CORR_TIENDA=@CORR_TIENDA OR A.CORR_TIENDA IS NULL)
    AND YEAR(A.FECHA_DOCUMENTO)=@ANIO_PERIODO
    AND MONTH(A.FECHA_DOCUMENTO)=@MES_PERIODO
    AND B.LIBRO_IVA='VNC' --VENTAS NO CONTRIBUYENTES
	AND A.ESTADO_FACTURA='AP'
	AND EXISTS (SELECT 1 
				FROM VEN_DOCUMENTO_DETA AA
				INNER JOIN INV_TIPO_ITEM BB ON BB.CORR_EMPRESA = AA.CORR_EMPRESA AND BB.CORR_TIPO_ITEM = AA.CORR_TIPO_ITEM
				AND A.CORR_EMPRESA = AA.CORR_EMPRESA 
				AND A.CORR_TIENDA = AA.CORR_TIENDA 
				AND A.ANIO_PERIODO = AA.ANIO_PERIODO 
				AND A.MES_PERIODO = AA.MES_PERIODO 
				AND A.CORR_DOCUMENTO = AA.CORR_DOCUMENTO
				AND BB.ES_TERCERO = 1
				--AND BB.NOMBRE_TIPO_ITEM LIKE '%HUEVO%'
				)
    GROUP BY CASE
             WHEN ISNULL(F.CORR_PRODUCTORA, 0) = 0 THEN
             ''
             ELSE
             F.NOMBRE_PROVEEDOR
             END,
             A.CORR_EMPRESA,
             A.CORR_TIENDA,
             D.NUMERO_NIT,
             D.NUMERO_NRC,
             A.ANIO_PERIODO,
             A.MES_PERIODO,
             A.FECHA_DOCUMENTO,
             CASE WHEN ISNULL(A.NUMERO_CONTROL,'')<>'' THEN CONVERT(INT,SUBSTRING(A.NUMERO_CONTROL,17,15)) ELSE A.NUMERO_DOCUMENTO END,
             ISNULL(A.SERIE,''),
             F.NUMERO_COMPRO_LIQUIDA,
             A.CORR_RUTA_VENTA,
             E.NOMBRE_RUTA_VENTA
    ORDER BY A.FECHA_DOCUMENTO

	DECLARE @NUMERO_DOC INT, @SERIE_DOC VARCHAR(50), @ANIO_PERIODO_DOC INT, @MES_PERIODO_DOC INT

	SELECT TOP 1 @NUMERO_DOC=NUMERO_DOCUMENTO,
		@SERIE_DOC=SERIE,
		@ANIO_PERIODO_DOC=ANIO_PERIODO,
        @MES_PERIODO_DOC=MES_PERIODO
	FROM @TEMP2
	ORDER BY NUMERO_DOCUMENTO ASC

	WHILE EXISTS(SELECT 1 FROM @TEMP2)
	BEGIN
		WHILE EXISTS(SELECT 1 FROM @TEMP2 
					 WHERE CORR_EMPRESA=@CORR_EMPRESA
					 AND ANIO_PERIODO=@ANIO_PERIODO_DOC
					 AND MES_PERIODO=@MES_PERIODO_DOC
					 AND NUMERO_DOCUMENTO=@NUMERO_DOC
					 AND SERIE=@SERIE_DOC)
		BEGIN
			INSERT INTO @TEMP3
			(
				CORR_EMPRESA,
				CORR_TIENDA,
				CORR_DOCUMENTO,
				NIT_TIENDA,
				REGISTRO_FISCAL_TIENDA,
				ANIO_PERIODO,
				MES_PERIODO,
				FECHA_DOCUMENTO,
				NUMERO_DOCUMENTO,
				SERIE,
				COMPROBANTE_LIQUIDACION,
				MANDANTE,
				VENTAS_PROPIAS_EXENTA,
				VENTAS_PROPIAS_NO_SUJETAS,
				VENTAS_PROPIAS_GRAVADA,
				VENTAS_PROPIAS_GRAVADAS_EXPORTACION,
				VENTAS_PROPIAS_IVA,
				VENTAS_TERCEROS_EXENTA,
				VENTAS_TERCEROS_NO_SUJETAS,
				VENTAS_TERCEROS_GRAVADA,
				VENTAS_TERCEROS_GRAVADAS_EXPORTACION,
				VENTAS_TERCEROS_IVA,
				VENTAS_TOTAL,
				CORR_RUTA_VENTA,
				NOMBRE_RUTA_VENTA
			)
			SELECT 
                A.CORR_EMPRESA,
                A.CORR_TIENDA,
				A.CORR_DOCUMENTO,
                A.NIT_TIENDA NUMERO_NIT,
                A.REGISTRO_FISCAL_TIENDA NUMERO_NRC,
                A.ANIO_PERIODO,
                A.MES_PERIODO,
                A.FECHA_DOCUMENTO,
                A.NUMERO_DOCUMENTO,
                A.SERIE,
		        A.COMPROBANTE_LIQUIDACION,
		        A.MANDANTE,
                A.VENTAS_PROPIAS_EXENTA,
                A.VENTAS_PROPIAS_NO_SUJETAS NO_SUJETO_VENTAS_PROPIAS,
                A.VENTAS_PROPIAS_GRAVADA,
                A.VENTAS_PROPIAS_GRAVADAS_EXPORTACION,
                A.VENTAS_PROPIAS_IVA,
                A.VENTAS_TERCEROS_EXENTA VENTAS_TERCEROS_EXE,
                A.VENTAS_TERCEROS_NO_SUJETAS NO_SUJETO_VENTAS_TE,
                A.VENTAS_TERCEROS_GRAVADA VENTAS_TERCEROS_GRA,
                A.VENTAS_TERCEROS_GRAVADAS_EXPORTACION,
                A.VENTAS_TERCEROS_IVA,
                A.VENTAS_TOTAL,
                A.CORR_RUTA_VENTA,
                A.NOMBRE_RUTA_VENTA 
		    FROM @TEMP2 A
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO_DOC
			AND MES_PERIODO=@MES_PERIODO_DOC
			AND NUMERO_DOCUMENTO=@NUMERO_DOC
			AND SERIE=@SERIE_DOC

			DELETE FROM @TEMP2
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO_DOC
			AND MES_PERIODO=@MES_PERIODO_DOC
			AND NUMERO_DOCUMENTO=@NUMERO_DOC
			AND SERIE=@SERIE_DOC

			SELECT @NUMERO_DOC=@NUMERO_DOC+1
		END

		INSERT INTO @TEMP1
		(
			CORR_EMPRESA,
			CORR_TIENDA,
			NIT_TIENDA,
			REGISTRO_FISCAL_TIENDA,
			ANIO_PERIODO,
			MES_PERIODO,
			FECHA_DOCUMENTO,
			DESDE,
			HASTA,
			COMPROBANTE_LIQUIDACION,
			MANDANTE,
			VENTAS_PROPIAS_EXENTA,
			VENTAS_PROPIAS_NO_SUJETAS,
			VENTAS_PROPIAS_GRAVADA,
			VENTAS_PROPIAS_GRAVADAS_EXPORTACION,
			VENTAS_PROPIAS_IVA,
			VENTAS_TERCEROS_EXENTA,
			VENTAS_TERCEROS_NO_SUJETAS,
			VENTAS_TERCEROS_GRAVADA,
			VENTAS_TERCEROS_GRAVADAS_EXPORTACION,
			VENTAS_TERCEROS_IVA,
			VENTAS_TOTAL,
			CORR_RUTA_VENTA,
			NOMBRE_RUTA_VENTA
		)
		SELECT 
			A.CORR_EMPRESA,
			A.CORR_TIENDA,
			A.NIT_TIENDA NUMERO_NIT,
			A.REGISTRO_FISCAL_TIENDA NUMERO_NRC,
			A.ANIO_PERIODO,
			A.MES_PERIODO,
			A.FECHA_DOCUMENTO,
			A.SERIE+CONVERT(VARCHAR(50),MIN(A.NUMERO_DOCUMENTO)),
			A.SERIE+CONVERT(VARCHAR(50),MAX(A.NUMERO_DOCUMENTO)),
			A.COMPROBANTE_LIQUIDACION,
			A.MANDANTE,
			SUM(A.VENTAS_PROPIAS_EXENTA) VENTAS_PROPIAS_EXENTA,
			SUM(A.VENTAS_PROPIAS_NO_SUJETAS) NO_SUJETO_VENTAS_PROPIAS,
			SUM(A.VENTAS_PROPIAS_GRAVADA) VENTAS_PROPIAS_GRAVADA,
			SUM(A.VENTAS_PROPIAS_GRAVADAS_EXPORTACION) VENTAS_PROPIAS_GRAVADAS_EXPORTACION,
			SUM(A.VENTAS_PROPIAS_IVA) VENTAS_PROPIAS_IVA,
			SUM(A.VENTAS_TERCEROS_EXENTA) VENTAS_TERCEROS_EXE,
			SUM(A.VENTAS_TERCEROS_NO_SUJETAS) NO_SUJETO_VENTAS_TE,
			SUM(A.VENTAS_TERCEROS_GRAVADA) VENTAS_TERCEROS_GRA,
			SUM(A.VENTAS_TERCEROS_GRAVADAS_EXPORTACION) VENTAS_TERCEROS_GRAVADAS_EXPORTACION,
			SUM(A.VENTAS_TERCEROS_IVA) VENTAS_TERCEROS_IVA,
			SUM(A.VENTAS_TOTAL) VENTAS_TOTAL,
			A.CORR_RUTA_VENTA,
			A.NOMBRE_RUTA_VENTA 
		FROM @TEMP3 A
		GROUP BY 
                A.CORR_EMPRESA,
                A.CORR_TIENDA,
                A.NIT_TIENDA,
                A.REGISTRO_FISCAL_TIENDA,
                A.ANIO_PERIODO,
                A.MES_PERIODO,
                A.FECHA_DOCUMENTO,
                A.SERIE,
                A.COMPROBANTE_LIQUIDACION,
                A.MANDANTE,
                A.CORR_RUTA_VENTA,
                A.NOMBRE_RUTA_VENTA

		DELETE FROM @TEMP3

		IF EXISTS (SELECT 1 FROM @TEMP2)
		BEGIN
			SELECT TOP 1 @NUMERO_DOC=NUMERO_DOCUMENTO,
			@SERIE_DOC=SERIE,
			@ANIO_PERIODO_DOC=ANIO_PERIODO,
			@MES_PERIODO_DOC=MES_PERIODO
			FROM @TEMP2
			ORDER BY NUMERO_DOCUMENTO ASC
		END
	END	

	IF @OPCION_CONSULTA=1  --LIBRO_IVA_VENTAS_CONTRIBUYENTES
    BEGIN

		SELECT 
           A.CORR_EMPRESA,
           A.CORR_TIENDA,
           A.NIT_TIENDA NUMERO_NIT, 
           A.REGISTRO_FISCAL_TIENDA NUMERO_NRC,
           A.ANIO_PERIODO,
           A.MES_PERIODO,
           A.FECHA_DOCUMENTO,
           A.DESDE,
           A.HASTA,
		   A.COMPROBANTE_LIQUIDACION,
		   A.MANDANTE,
           A.VENTAS_PROPIAS_EXENTA,
           A.VENTAS_PROPIAS_NO_SUJETAS NO_SUJETO_VENTAS_PROPIAS,
           A.VENTAS_PROPIAS_GRAVADA,
           A.VENTAS_PROPIAS_GRAVADAS_EXPORTACION,
           A.VENTAS_PROPIAS_IVA,
           A.VENTAS_TERCEROS_EXENTA VENTAS_TERCEROS_EXE,
           A.VENTAS_TERCEROS_NO_SUJETAS NO_SUJETO_VENTAS_TE,
           A.VENTAS_TERCEROS_GRAVADA VENTAS_TERCEROS_GRA,
           A.VENTAS_TERCEROS_GRAVADAS_EXPORTACION,
           A.VENTAS_TERCEROS_IVA,
           A.VENTAS_TOTAL,
           A.CORR_RUTA_VENTA,
           A.NOMBRE_RUTA_VENTA 
		FROM @TEMP1 A
		ORDER BY A.FECHA_DOCUMENTO ASC,A.DESDE ASC
	END

	SELECT A.CORR_EMPRESA
		,A.NOMBRE_EMPRESA
		,'' PERIODO
		,A.LOGO_1 LOGO1
		,A.LOGO_2 LOGO2
		,'' TITULO_REPORTE
		,'' NOMBRE_SISTEMA
		,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO
