
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_BAN_SALDO_INICIAL]
(
 @CORR_EMPRESA INT,
 @FECHA_CONSULTA Date,
 @OPCION_CONSULTA INT=0,
 @CORR_CUENTA_BANCARIA INT=NULL
)
AS
DECLARE
    @ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@ANIO_PERIODO_ANTE INT,
	@MES_PERIODO_ANTE INT,
	@FECHA_INICIAL DATE
	
	DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CORR_CUENTA_BANCARIA INT,
		SALDO_INICIAL DECIMAL(12,2),
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),
		SALDO_FINAL	DECIMAL(12,2)
	)		
BEGIN

    SET NOCOUNT ON
    
	--Obtener el periodo
	SELECT @ANIO_PERIODO=YEAR(@FECHA_CONSULTA), @MES_PERIODO=MONTH(@FECHA_CONSULTA)	    	    

	IF @MES_PERIODO=1
	BEGIN
		SELECT @ANIO_PERIODO_ANTE=@ANIO_PERIODO-1,@MES_PERIODO_ANTE=12
	END ELSE
	BEGIN
		SELECT @ANIO_PERIODO_ANTE=@ANIO_PERIODO,@MES_PERIODO_ANTE=@MES_PERIODO-1
	END
	
	IF NOT EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
			  WHERE CORR_EMPRESA=@CORR_EMPRESA
			  AND ANIO_PERIODO=@ANIO_PERIODO_ANTE
			  AND MES_PERIODO=@MES_PERIODO_ANTE
			  AND ESTADO_PERIODO_BAN='CE')
	BEGIN
		IF EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
			  WHERE CORR_EMPRESA=@CORR_EMPRESA			  
			  AND ESTADO_PERIODO_BAN='CE'
			  AND (ANIO_PERIODO*100)+MES_PERIODO<(@ANIO_PERIODO*100)+@MES_PERIODO)
		BEGIN
			SELECT TOP 1 @ANIO_PERIODO=ANIO_PERIODO
			,@MES_PERIODO=MES_PERIODO
			FROM CON_PERIODO_CONTABLE
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ESTADO_PERIODO_BAN='CE'
			AND (ANIO_PERIODO*100)+MES_PERIODO<(@ANIO_PERIODO*100)+@MES_PERIODO
			ORDER BY ANIO_PERIODO DESC, MES_PERIODO DESC
			
			IF @MES_PERIODO=12
			BEGIN
				SELECT @ANIO_PERIODO=@ANIO_PERIODO+1,@MES_PERIODO=1
			END ELSE
			BEGIN
				SELECT @ANIO_PERIODO=@ANIO_PERIODO,@MES_PERIODO=@MES_PERIODO+1
			END
		END ELSE
		BEGIN
			IF EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
			  WHERE CORR_EMPRESA=@CORR_EMPRESA  
			  AND ESTADO_PERIODO_BAN='AB'
			  AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO)
		    BEGIN		    		    
				SELECT TOP 1 @ANIO_PERIODO=ANIO_PERIODO,@MES_PERIODO=MES_PERIODO			
				FROM CON_PERIODO_CONTABLE
				WHERE CORR_EMPRESA=@CORR_EMPRESA  
				AND ESTADO_PERIODO_BAN='AB'
				AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO
				ORDER BY ANIO_PERIODO ASC, MES_PERIODO ASC
			END ELSE
			BEGIN
			    SELECT TOP 1 @ANIO_PERIODO=ANIO_PERIODO,@MES_PERIODO=MES_PERIODO
				FROM BAN_DOCUMENTO
				WHERE CORR_EMPRESA=@CORR_EMPRESA
				AND ESTADO_DOCUMENTO='AP'
				AND (ANIO_PERIODO*100)+MES_PERIODO<=(@ANIO_PERIODO*100)+@MES_PERIODO
				ORDER BY ANIO_PERIODO ASC, MES_PERIODO ASC
			END
		END
	END
	
	--Obtener el saldo inicial de todas las cuentas hasta un nivel y hasta la fecha de consulta
	IF @OPCION_CONSULTA=0
	BEGIN	    	    
		--Carga el saldo historico segun el periodo
		INSERT INTO @SALDO
		(CORR_EMPRESA,
		CORR_CUENTA_BANCARIA,
		SALDO_INICIAL,
		CARGO_PERIODO,
		ABONO_PERIODO,
		SALDO_FINAL)    
		SELECT A.CORR_EMPRESA,
		A.CORR_CUENTA_BANCO,
		0 SALDO_INICIAL,
		0,0,0
		FROM BAN_CUENTA_BANCARIA A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND (A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCARIA OR @CORR_CUENTA_BANCARIA IS NULL)		
				
		SELECT @FECHA_INICIAL=CONVERT(DATE,CONVERT(VARCHAR,@ANIO_PERIODO)+'-'+CONVERT(VARCHAR,@MES_PERIODO)+'-1')
		
		--Actualizar cargos y abonos del periodo		
		UPDATE @SALDO SET
		CARGO_PERIODO=ISNULL(B.MONTO_CARGO,0),
		ABONO_PERIODO=ISNULL(B.MONTO_ABONO,0)
		FROM @SALDO A
		INNER JOIN (SELECT A.CORR_EMPRESA,
		            A.CORR_CUENTA_BANCO,SUM(A.MONTO_CARGO) MONTO_CARGO,SUM(A.MONTO_ABONO) MONTO_ABONO
					FROM BAN_MOVIMIENTO A					
					WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					AND A.FECHA_MOVIMIENTO>=@FECHA_INICIAL										
					AND A.FECHA_MOVIMIENTO<=@FECHA_CONSULTA					
					GROUP BY A.CORR_EMPRESA,A.CORR_CUENTA_BANCO				
		) B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CUENTA_BANCARIA=B.CORR_CUENTA_BANCO
	END
	
	UPDATE @SALDO SET 
	SALDO_INICIAL=ISNULL(SALDO_INICIAL,0), 
	SALDO_FINAL=ISNULL(SALDO_INICIAL,0)+ISNULL(CARGO_PERIODO,0)-ISNULL(ABONO_PERIODO,0),
	CARGO_PERIODO=ISNULL(CARGO_PERIODO,0),
	ABONO_PERIODO=ISNULL(ABONO_PERIODO,0)
	
	SELECT * FROM @SALDO
END
GO

