/* ============================================================================
   Procedimientos de Cierre y Apertura de Periodos Contables
   - @TIPO_PERIODO = código de módulo: CON, BAN, VEN, ACT, INV, PLA, COM
   - Cierre  : estado = 'CE' (Cerrado) + fecha de cierre = hoy
   - Apertura: estado = 'AB' (Abierto) + fecha de cierre = NULL
   ============================================================================ */
IF OBJECT_ID('dbo.PRAL_GENE_CON_PERIODO_CIERRE','P') IS NOT NULL
	DROP PROCEDURE dbo.PRAL_GENE_CON_PERIODO_CIERRE;
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_CON_PERIODO_CIERRE]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@TIPO_PERIODO VARCHAR(3),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON
	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0
	DECLARE @FECHA DATETIME = GETDATE()

	BEGIN TRY
		IF @TIPO_PERIODO NOT IN ('CON','BAN','VEN','ACT','INV','PLA','COM')
		BEGIN
			SELECT @SYS_NUMERO_ERROR=40001,@SYS_MENSAJE_ERROR='El módulo indicado no es válido.'
			GOTO FINA
		END

		IF NOT EXISTS(SELECT 1 FROM CON_PERIODO_CONTABLE
		              WHERE CORR_EMPRESA=@CORR_EMPRESA AND ANIO_PERIODO=@ANIO_PERIODO AND MES_PERIODO=@MES_PERIODO)
		BEGIN
			SELECT @SYS_NUMERO_ERROR=40002,@SYS_MENSAJE_ERROR='El periodo contable no existe.'
			GOTO FINA
		END

		UPDATE CON_PERIODO_CONTABLE
		SET ESTADO_PERIODO_CON = CASE WHEN @TIPO_PERIODO='CON' THEN 'CE' ELSE ESTADO_PERIODO_CON END,
		    FECHA_CIERRE_CON   = CASE WHEN @TIPO_PERIODO='CON' THEN @FECHA ELSE FECHA_CIERRE_CON END,
		    ESTADO_PERIODO_BAN = CASE WHEN @TIPO_PERIODO='BAN' THEN 'CE' ELSE ESTADO_PERIODO_BAN END,
		    FECHA_CIERRE_BAN   = CASE WHEN @TIPO_PERIODO='BAN' THEN @FECHA ELSE FECHA_CIERRE_BAN END,
		    ESTADO_PERIODO_VEN = CASE WHEN @TIPO_PERIODO='VEN' THEN 'CE' ELSE ESTADO_PERIODO_VEN END,
		    FECHA_CIERRE_VEN   = CASE WHEN @TIPO_PERIODO='VEN' THEN @FECHA ELSE FECHA_CIERRE_VEN END,
		    ESTADO_PERIODO_ACT = CASE WHEN @TIPO_PERIODO='ACT' THEN 'CE' ELSE ESTADO_PERIODO_ACT END,
		    FECHA_CIERRE_ACT   = CASE WHEN @TIPO_PERIODO='ACT' THEN @FECHA ELSE FECHA_CIERRE_ACT END,
		    ESTADO_PERIODO_INV = CASE WHEN @TIPO_PERIODO='INV' THEN 'CE' ELSE ESTADO_PERIODO_INV END,
		    FECHA_CIERRE_INV   = CASE WHEN @TIPO_PERIODO='INV' THEN @FECHA ELSE FECHA_CIERRE_INV END,
		    ESTADO_PERIODO_PLA = CASE WHEN @TIPO_PERIODO='PLA' THEN 'CE' ELSE ESTADO_PERIODO_PLA END,
		    FECHA_CIERRE_PLA   = CASE WHEN @TIPO_PERIODO='PLA' THEN @FECHA ELSE FECHA_CIERRE_PLA END,
		    ESTADO_PERIODO_COM = CASE WHEN @TIPO_PERIODO='COM' THEN 'CE' ELSE ESTADO_PERIODO_COM END,
		    FECHA_CIERRE_COM   = CASE WHEN @TIPO_PERIODO='COM' THEN @FECHA ELSE FECHA_CIERRE_COM END
		WHERE CORR_EMPRESA=@CORR_EMPRESA AND ANIO_PERIODO=@ANIO_PERIODO AND MES_PERIODO=@MES_PERIODO

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	END TRY
	BEGIN CATCH
		DECLARE @CORR_BITACORA int, @SEVERITY_ERROR int, @ESTADO_ERROR int,
		        @ORIGEN_ERROR nvarchar(126), @LINEA_ERROR int, @SYS_FECHA DateTime
		SELECT @CORR_BITACORA=0,@SYS_NUMERO_ERROR=ERROR_NUMBER(),@SEVERITY_ERROR=ERROR_SEVERITY(),
		       @ESTADO_ERROR=ERROR_STATE(),@ORIGEN_ERROR=ERROR_PROCEDURE(),@LINEA_ERROR=ERROR_LINE(),
		       @SYS_MENSAJE_ERROR=ERROR_MESSAGE(),@SYS_FECHA=GETDATE()
		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION
	END CATCH
	FINA:
END
GO
GO
