SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_CONCILIA_BANCARIA_DESAPLICAR]
	@CORR_EMPRESA int,
	@CORR_CUENTA_BANCO int,
	@CORR_CONCILIACION int OUTPUT,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
AS
BEGIN
	SET NOCOUNT ON
	
	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0
	
	BEGIN TRY
	
		DECLARE @ESTADO_CONCILIACION VARCHAR(2)

		SELECT @ESTADO_CONCILIACION=ESTADO_CONCILIACION
		FROM BAN_CONCILIA_BANCARIA 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
		AND CORR_CONCILIACION=@CORR_CONCILIACION
		
		IF @ESTADO_CONCILIACION IS NULL
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe esta conciliacion.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END ELSE
		IF @ESTADO_CONCILIACION = 'DI'
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Esta conciliacion ya en digitado.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END
		
		UPDATE BAN_CONCILIA_BANCARIA SET
		ESTADO_CONCILIACION='DI'
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
		AND CORR_CONCILIACION=@CORR_CONCILIACION
				
	END TRY
	BEGIN CATCH
		
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO

