SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_JSON_DOC]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA int,
	@CORR_DOCUMENTO int OUTPUT,
	@CORR_DOCUMENTO_DOC INT=NULL,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	EXEC [e-AdminFE].dbo.PRAL_MTTO_COM_JSON_DOC
	@TIPO_ACTUALIZA,
	@CORR_EMPRESA,
	@CORR_DOCUMENTO OUTPUT,
	@CORR_DOCUMENTO_DOC,
	@SYS_LOGIN_USUARIO,
	@SYS_ESTACION,
	@SYS_FILAS_AFECTADAS output,
	@SYS_NUMERO_ERROR output,
	@SYS_MENSAJE_ERROR OUTPUT
    
FINA:
END
GO
