SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_CON_PARTIDA_DETA]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_CLASE_PARTIDA INT,
	@CORR_PARTIDA INT,
	@CORR_PARTIDA_DETA INT OUTPUT,
	@CUENTA_CONTABLE VARCHAR(30),
	@CORR_CENTRO_COSTO INT = NULL,
	@MONTO_CARGO DECIMAL(18,4) = 0,
	@MONTO_ABONO DECIMAL(18,4) = 0,
	@NOMBRE_TRAN VARCHAR(1255) = '',
	@MONTO_CARGO_FORANEA DECIMAL(12,4) = NULL,
	@MONTO_ABONO_FORANEA DECIMAL(12,4) = NULL,
	@FACTOR_CAMBIO DECIMAL(12,6) = NULL,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT,
	@CORR_AUXILIAR INT = NULL
)
AS
BEGIN
	SET NOCOUNT ON
	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = '', @SYS_FILAS_AFECTADAS = 0

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1, 2)
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM CON_CATALOGO_CUENTA
				WHERE CORR_EMPRESA = @CORR_EMPRESA
				  AND CUENTA_CONTABLE = @CUENTA_CONTABLE
				  AND ES_DETALLE = 1
				  AND NO_HABILITADA = 0
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = 'Cuenta: ' + @CUENTA_CONTABLE + '. Seleccione una cuenta de detalle y que este habilitada.', @SYS_FILAS_AFECTADAS = 0
				GOTO FINA
			END

			IF NOT EXISTS (
				SELECT 1 FROM CON_CENTRO_COSTO
				WHERE CORR_EMPRESA = @CORR_EMPRESA
				  AND CORR_CENTRO_COSTO = @CORR_CENTRO_COSTO
			)
				SELECT @CORR_CENTRO_COSTO = NULL

			IF @MONTO_ABONO < 0 OR @MONTO_CARGO < 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = 'No introduzca montos negativos', @SYS_FILAS_AFECTADAS = 0
				GOTO FINA
			END

			IF @MONTO_ABONO > 0 AND @MONTO_CARGO > 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = 'Escriba al menos un monto igual que cero', @SYS_FILAS_AFECTADAS = 0
				GOTO FINA
			END

			IF NOT EXISTS (
				SELECT 1 FROM CON_CATALOGO_CUENTA_AUXI
				WHERE CORR_EMPRESA = @CORR_EMPRESA
				  AND CUENTA_CONTABLE = @CUENTA_CONTABLE
				  AND CORR_AUXILIAR = @CORR_AUXILIAR
			)
			BEGIN
				SELECT @CORR_AUXILIAR = NULL
				IF (
					SELECT COUNT(CORR_AUXILIAR)
					FROM CON_CATALOGO_CUENTA_AUXI
					WHERE CORR_EMPRESA = @CORR_EMPRESA
					  AND CUENTA_CONTABLE = @CUENTA_CONTABLE
				) = 1
				BEGIN
					SELECT TOP 1 @CORR_AUXILIAR = CORR_AUXILIAR
					FROM CON_CATALOGO_CUENTA_AUXI
					WHERE CORR_EMPRESA = @CORR_EMPRESA
					  AND CUENTA_CONTABLE = @CUENTA_CONTABLE
				END
			END
		END

		IF NOT EXISTS (
			SELECT 1 FROM CON_PARTIDA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
			  AND ANIO_PERIODO = @ANIO_PERIODO
			  AND MES_PERIODO = @MES_PERIODO
			  AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA
			  AND CORR_PARTIDA = @CORR_PARTIDA
			  AND ESTADO_PARTIDA = 'DI'
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = 'El documento no puede ser modificado o eliminado.', @SYS_FILAS_AFECTADAS = 0
			GOTO FINA
		END

		IF @TIPO_ACTUALIZA = 1
		BEGIN
			IF @CORR_PARTIDA_DETA IS NULL OR @CORR_PARTIDA_DETA = 0
			BEGIN
				SELECT @CORR_PARTIDA_DETA = ISNULL(MAX(CORR_PARTIDA_DETA), 0) + 1
				FROM CON_PARTIDA_DETA
				WHERE CORR_EMPRESA = @CORR_EMPRESA
				  AND ANIO_PERIODO = @ANIO_PERIODO
				  AND MES_PERIODO = @MES_PERIODO
				  AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA
				  AND CORR_PARTIDA = @CORR_PARTIDA
			END

			INSERT INTO CON_PARTIDA_DETA
			(CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_CLASE_PARTIDA, CORR_PARTIDA, CORR_PARTIDA_DETA, CUENTA_CONTABLE, CORR_CENTRO_COSTO, MONTO_CARGO, MONTO_ABONO, NOMBRE_TRAN, MONTO_CARGO_FORANEA, MONTO_ABONO_FORANEA, CORR_AUXILIAR, FACTOR_CAMBIO)
			VALUES
			(@CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, @CORR_CLASE_PARTIDA, @CORR_PARTIDA, @CORR_PARTIDA_DETA, @CUENTA_CONTABLE, @CORR_CENTRO_COSTO, @MONTO_CARGO, @MONTO_ABONO, @NOMBRE_TRAN, ISNULL(@MONTO_CARGO_FORANEA, 0), ISNULL(@MONTO_ABONO_FORANEA, 0), @CORR_AUXILIAR, ISNULL(@FACTOR_CAMBIO, 1))
		END

		SELECT @SYS_FILAS_AFECTADAS = @@ROWCOUNT
	END TRY
	BEGIN CATCH
		DECLARE @CORR_BITACORA INT, @SEVERITY_ERROR INT, @ESTADO_ERROR INT,
		        @ORIGEN_ERROR NVARCHAR(126), @LINEA_ERROR INT, @SYS_FECHA DATETIME
		SELECT @CORR_BITACORA = 0, @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SEVERITY_ERROR = ERROR_SEVERITY(),
		       @ESTADO_ERROR = ERROR_STATE(), @ORIGEN_ERROR = ERROR_PROCEDURE(), @LINEA_ERROR = ERROR_LINE(),
		       @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FECHA = GETDATE()
		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1, @CORR_BITACORA OUTPUT, 'PM', @SYS_NUMERO_ERROR, @SEVERITY_ERROR, @ESTADO_ERROR, @ORIGEN_ERROR, @LINEA_ERROR, @SYS_MENSAJE_ERROR, @SYS_LOGIN_USUARIO, @SYS_FECHA, @SYS_ESTACION
	END CATCH
FINA:
END
GO
