SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_DETA]
(
	@TIPO_ACTUALIZA INT	@CORR_EMPRESA int,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_TIPO_MOVIMIENTO int,
	@CORR_DOCUMENTO int,
	@CORR_DOCUMENTO_DETA int OUTPUT,
	@CUENTA_CONTABLE varchar(30),
	@CORR_CENTRO_COSTO int,
	@NOMBRE_TRAN varchar(255),
	@MONTO_CARGO decimal(12,2),
	@MONTO_ABONO decimal(12,2),
	@CORR_AUXILIAR INT=NULL,
	@MONTO_CARGO_FORANEA decimal(12,4)=NULL,
	@MONTO_ABONO_FORANEA decimal(12,4)=NULL,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @CORR_DOCUMENTO_DETA=ISNULL(MAX(CORR_DOCUMENTO_DETA),0)+1
			FROM BAN_SOLI_CHEQUE_DETA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO


			INSERT INTO BAN_SOLI_CHEQUE_DETA
			(CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,CORR_TIPO_MOVIMIENTO,CORR_DOCUMENTO,CORR_DOCUMENTO_DETA,CUENTA_CONTABLE,CORR_CENTRO_COSTO,NOMBRE_TRAN,MONTO_CARGO,MONTO_ABONO,CORR_AUXILIAR,MONTO_CARGO_FORANEA,MONTO_ABONO_FORANEA)
			VALUES
			(@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_EMPRESA,@ANIO_PERIODO,@MES_PERIODO,@CORR_TIPO_MOVIMIENTO,@CORR_DOCUMENTO,@CORR_DOCUMENTO_DETA,@CUENTA_CONTABLE,@CORR_CENTRO_COSTO,@NOMBRE_TRAN,@MONTO_CARGO,@MONTO_ABONO,@CORR_AUXILIAR,@MONTO_CARGO_FORANEA,@MONTO_ABONO_FORANEA)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE BAN_SOLI_CHEQUE_DETA SET
			CUENTA_CONTABLE=@CUENTA_CONTABLE,
			CORR_CENTRO_COSTO=@CORR_CENTRO_COSTO,
			NOMBRE_TRAN=@NOMBRE_TRAN,
			MONTO_CARGO=@MONTO_CARGO,
			MONTO_ABONO=@MONTO_ABONO,
			CORR_AUXILIAR=@CORR_AUXILIAR,
			MONTO_CARGO_FORANEA=@MONTO_CARGO_FORANEA,
			MONTO_ABONO_FORANEA=@MONTO_ABONO_FORANEA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			AND CORR_DOCUMENTO_DETA=@CORR_DOCUMENTO_DETA
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM BAN_SOLI_CHEQUE_DETA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			AND CORR_DOCUMENTO_DETA=@CORR_DOCUMENTO_DETA
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		-- bitacora omitida
FINA:
END
GO
