SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_BAN_ENTREGA_CHEQUES]
(
	@CORR_EMPRESA int,
	@FECHA_INICIAL DATE,
	@FECHA_FINAL DATE
)
AS
BEGIN
	SET NOCOUNT ON
	
	SELECT *
	FROM V_BAN_ENTREGA_CHEQUES A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	AND A.FECHA_ENTREGA>=@FECHA_INICIAL
	AND A.FECHA_ENTREGA<=@FECHA_FINAL
	ORDER BY A.CORR_EMPRESA,A.NUMERO_DOCUMENTO
	SELECT A.CORR_EMPRESA
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,LOGO_1 LOGO1
	,LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO

