
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_BAN_ESTADO_CUENTA_ACUMULADO]
(
	@CORR_EMPRESAS VARCHAR(255), 
	@FECHA_INICIAL DATE=NULL,
	@FECHA_FINAL DATE =NULL,
	@CORR_TIPO_MOVIMIENTO INT=NULL,
	@CORR_CUENTA_BANCO INT=NULL,
	@OPCION_CONSULTA INT=0
)
AS
	 DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CORR_CUENTA_BANCO INT,
		SALDO_INICIAL DECIMAL(12,2),
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),
		SALDO_FINAL	DECIMAL(12,2)
	)
BEGIN
	SET NOCOUNT ON		
	
	DECLARE @EMPRESAS TABLE (CORR_EMPRESA INT, ESTA_PROC BIT)
    INSERT INTO @EMPRESAS
    SELECT CONVERT(INT,A.Data) CORR_EMPRESA, 0 ESTA_PROC
    FROM dbo.Split(@CORR_EMPRESAS,',') A
    
	SELECT @FECHA_INICIAL=DATEADD(DAY,-1,@FECHA_INICIAL)
	
	DECLARE @CORR_EMPRESA INT
    
    WHILE EXISTS (SELECT 1 FROM @EMPRESAS WHERE ESTA_PROC=0)
	BEGIN
		SELECT TOP 1 @CORR_EMPRESA=CORR_EMPRESA
		FROM @EMPRESAS
		WHERE ESTA_PROC=0
		
		INSERT INTO @SALDO
		EXEC PRAL_GENE_BAN_SALDO_INICIAL
		@CORR_EMPRESA,
		@FECHA_INICIAL,
		@OPCION_CONSULTA,
		@CORR_CUENTA_BANCO
		
		UPDATE @EMPRESAS SET
		ESTA_PROC=1
		WHERE CORR_EMPRESA=@CORR_EMPRESA
	END 
	
	SELECT TOP 1 @CORR_EMPRESA=CORR_EMPRESA
	FROM @EMPRESAS
	ORDER BY CORR_EMPRESA

	SELECT @FECHA_INICIAL=DATEADD(DAY,1,@FECHA_INICIAL)
	
	SELECT A.CORR_EMPRESA,
	 E.NOMBRE_EMPRESA, A.CORR_CUENTA_BANCO, A.NOMBRE_BANCO, A.NOMBRE_CUENTA_BANCO NUMERO_CUENTA_BANCO, A.NOMBRE_CUENTA, A.NOMBRE_CUENTA_BANCO
	,ISNULL(B.SALDO_FINAL,0) SALDO_INICIAL, ISNULL(SUM(C.MONTO_CARGO),0)  MONTO_CARGO, ISNULL(SUM(C.MONTO_ABONO),0) MONTO_ABONO
	,ISNULL(B.SALDO_FINAL,0)+ISNULL(SUM(C.MONTO_CARGO),0)-ISNULL(SUM(C.MONTO_ABONO),0) SALDO_ACTUAL
	FROM V_BAN_CUENTA_BANCARIA A
	LEFT OUTER JOIN @SALDO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=B.CORR_CUENTA_BANCO
	LEFT OUTER JOIN V_BAN_MOVIMIENTO C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=C.CORR_CUENTA_BANCO
										  AND C.FECHA_MOVIMIENTO BETWEEN @FECHA_INICIAL AND @FECHA_FINAL
	INNER JOIN @EMPRESAS D ON A.CORR_EMPRESA=D.CORR_EMPRESA
	INNER JOIN V_GEN_EMPRESA E ON D.CORR_EMPRESA=E.CORR_EMPRESA
	WHERE (A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO OR @CORR_CUENTA_BANCO IS NULL)	
	AND (C.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO OR @CORR_CUENTA_BANCO IS NULL OR C.CORR_CUENTA_BANCO IS NULL)	
	AND (C.CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO OR @CORR_TIPO_MOVIMIENTO IS NULL OR C.CORR_TIPO_MOVIMIENTO IS NULL)
	GROUP BY A.CORR_EMPRESA,E.NOMBRE_EMPRESA,A.CORR_CUENTA_BANCO,A.NOMBRE_BANCO,A.NOMBRE_CUENTA
	,A.NOMBRE_CUENTA_BANCO
	,B.SALDO_INICIAL,B.CARGO_PERIODO,B.ABONO_PERIODO,B.SALDO_FINAL
	ORDER BY A.CORR_CUENTA_BANCO
	
	SELECT A.CORR_EMPRESA
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,LOGO_1 LOGO1
	,LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	
FINA:
END
GO
