SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE dbo.PRAL_MTTO_BAN_TIPO_MOVI_SEGUN_BANCO
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA int,
	@CORR_TIPO_MOVIMIENTO int,
	@CORR_BANCO int,
	@CODIGO_MOVIMIENTO varchar(10) OUTPUT,
	@NOMBRE_MOVIMIENTO_SEGUN_BANCO varchar(100),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1,2)
		BEGIN
			IF NOT EXISTS ( SELECT 1 FROM BAN_TIPO_MOVI_BANCARIO 
							WHERE CORR_EMPRESA=@CORR_EMPRESA 
							AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe este movimiento bancario.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			IF NOT EXISTS ( SELECT 1 FROM GEN_BANCO WHERE CORR_EMPRESA=@CORR_EMPRESA AND CORR_BANCO=@CORR_BANCO )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe el banco seleccionado.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			IF EXISTS ( SELECT 1 FROM BAN_TIPO_MOVI_SEGUN_BANCO
						WHERE CORR_EMPRESA=@CORR_EMPRESA 
						AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO 
						AND CORR_BANCO=@CORR_BANCO 
						AND CODIGO_MOVIMIENTO=@CODIGO_MOVIMIENTO )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='Ya esta en uso este codigo para un movimiento de este mismo banco.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			INSERT INTO BAN_TIPO_MOVI_SEGUN_BANCO
			(CORR_EMPRESA,CORR_TIPO_MOVIMIENTO,CORR_BANCO,CODIGO_MOVIMIENTO,NOMBRE_MOVIMIENTO_SEGUN_BANCO)
			VALUES
			(@CORR_EMPRESA,@CORR_TIPO_MOVIMIENTO,@CORR_BANCO,@CODIGO_MOVIMIENTO,@NOMBRE_MOVIMIENTO_SEGUN_BANCO)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE BAN_TIPO_MOVI_SEGUN_BANCO SET
			NOMBRE_MOVIMIENTO_SEGUN_BANCO=@NOMBRE_MOVIMIENTO_SEGUN_BANCO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
			AND CORR_BANCO=@CORR_BANCO
			AND CODIGO_MOVIMIENTO=@CODIGO_MOVIMIENTO
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM BAN_TIPO_MOVI_SEGUN_BANCO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
			AND CORR_BANCO=@CORR_BANCO
			AND CODIGO_MOVIMIENTO=@CODIGO_MOVIMIENTO
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO


