SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_NULLS ON;
GO
-- =============================================================================
-- Procedimiento: dbo.PRAL_IMPR_SC_REQUISICION_PERSONAL
-- Qué hace: datos para XtraReport rptRequisicionPersonal (1 fila).
-- Parámetros: @CORR_EMPRESA, @CORR_REQUISICION_PERSONAL
-- Consumo: SGUEES-RPT Layouts/SelectionHiring/ImprimirRequisicion.aspx
-- =============================================================================
CREATE OR ALTER PROCEDURE [dbo].[PRAL_IMPR_SC_REQUISICION_PERSONAL]
(
	@CORR_EMPRESA INT,
	@CORR_REQUISICION_PERSONAL INT
)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		R.CORR_EMPRESA,
		R.CORR_REQUISICION_PERSONAL,
		R.CANTIDAD_PLAZAS,
		ISNULL(P.NOMBRE_PUESTO, N'') AS NOMBRE_PUESTO,
		ISNULL(U.NOMBRE_UNIDAD, N'') AS NOMBRE_UNIDAD,
		R.SALARIO,
		ISNULL(R.HORARIO, N'') AS HORARIO,
		ISNULL(R.JUSTIFICACION, N'') AS JUSTIFICACION,
		ISNULL(R.CORR_EMPLEADO_SUSTITUTO, N'') AS TEXTO_SUSTITUTO,
		CASE
			WHEN ISNULL(TC.ES_PERMANENTE, 1) = 0 AND ISNULL(R.TIEMPO_CONTRATO, 0) > 0
				THEN CAST(R.TIEMPO_CONTRATO AS NVARCHAR(20)) + N' mes(es)'
			ELSE N''
		END AS TIEMPO_CONTRATO_TXT,
		CAST(NULL AS DATE) AS FECHA_DESDE,
		CAST(NULL AS DATE) AS FECHA_HASTA,
		/* Modalidad */
		CAST(CASE WHEN ISNULL(M.MODALIDAD_NOMBRE, N'') LIKE N'%Presencial%' THEN 1 ELSE 0 END AS BIT) AS CHK_PRESENCIAL,
		CAST(CASE
			WHEN ISNULL(M.MODALIDAD_NOMBRE, N'') LIKE N'%Teletrabajo%Total%'
			  OR (ISNULL(M.MODALIDAD_NOMBRE, N'') LIKE N'%Teletrabajo%' AND ISNULL(M.MODALIDAD_NOMBRE, N'') LIKE N'%Total%')
			THEN 1 ELSE 0 END AS BIT) AS CHK_TELETRABAJO_TOTAL,
		CAST(CASE
			WHEN ISNULL(M.MODALIDAD_NOMBRE, N'') LIKE N'%Teletrabajo%Parcial%'
			  OR (ISNULL(M.MODALIDAD_NOMBRE, N'') LIKE N'%Teletrabajo%' AND ISNULL(M.MODALIDAD_NOMBRE, N'') LIKE N'%Parcial%')
			  OR ISNULL(M.MODALIDAD_NOMBRE, N'') LIKE N'%Parcial%'
			THEN 1 ELSE 0 END AS BIT) AS CHK_TELETRABAJO_PARCIAL,
		/* Contratación */
		CAST(CASE WHEN ISNULL(TC.ES_PERMANENTE, 0) = 1 THEN 1 ELSE 0 END AS BIT) AS CHK_PERMANENTE,
		CAST(CASE WHEN ISNULL(TC.ES_PERMANENTE, 1) = 0 THEN 1 ELSE 0 END AS BIT) AS CHK_TEMPORAL,
		/* Vacante */
		CAST(CASE WHEN ISNULL(TV.NOMBRE_TIPO_VACANTE, N'') LIKE N'%Promoci%' THEN 1 ELSE 0 END AS BIT) AS CHK_PROMOCION,
		CAST(CASE WHEN ISNULL(TV.NOMBRE_TIPO_VACANTE, N'') LIKE N'%Transfer%' THEN 1 ELSE 0 END AS BIT) AS CHK_TRANSFERENCIA,
		CAST(CASE WHEN ISNULL(TV.NOMBRE_TIPO_VACANTE, N'') LIKE N'%Renuncia%' THEN 1 ELSE 0 END AS BIT) AS CHK_RENUNCIA,
		CAST(CASE
			WHEN ISNULL(TV.NOMBRE_TIPO_VACANTE, N'') LIKE N'%nueva%'
			  OR ISNULL(TV.NOMBRE_TIPO_VACANTE, N'') LIKE N'%creaci%'
			THEN 1 ELSE 0 END AS BIT) AS CHK_NUEVA_CREACION,
		CAST(CASE
			WHEN ISNULL(TV.NOMBRE_TIPO_VACANTE, N'') NOT LIKE N'%Promoci%'
			 AND ISNULL(TV.NOMBRE_TIPO_VACANTE, N'') NOT LIKE N'%Transfer%'
			 AND ISNULL(TV.NOMBRE_TIPO_VACANTE, N'') NOT LIKE N'%Renuncia%'
			 AND ISNULL(TV.NOMBRE_TIPO_VACANTE, N'') NOT LIKE N'%nueva%'
			 AND ISNULL(TV.NOMBRE_TIPO_VACANTE, N'') NOT LIKE N'%creaci%'
			 AND ISNULL(TV.NOMBRE_TIPO_VACANTE, N'') <> N''
			THEN 1 ELSE 0 END AS BIT) AS CHK_OTROS,
		/* Aprobaciones — placeholders (solo línea / nombre vacío por ahora) */
		CAST(N'' AS NVARCHAR(150)) AS NOMBRE_JEFE_INMEDIATO,
		CAST(NULL AS DATE) AS FECHA_JEFE_INMEDIATO,
		CAST(N'' AS NVARCHAR(150)) AS NOMBRE_DECANO_GERENTE,
		CAST(NULL AS DATE) AS FECHA_DECANO_GERENTE,
		CAST(N'' AS NVARCHAR(150)) AS NOMBRE_VRA,
		CAST(NULL AS DATE) AS FECHA_VRA,
		ISNULL(E.NOMBRE_EMPRESA, N'') AS NOMBRE_EMPRESA
	FROM dbo.SC_REQUISICION_PERSONAL AS R
	LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES AS U
		ON U.CORR_EMPRESA = R.CORR_EMPRESA
	   AND U.CORR_UNIDAD = R.CORR_UNIDAD
	LEFT JOIN dbo.PLA_PUESTO AS P
		ON P.CORR_EMPRESA = R.CORR_EMPRESA
	   AND P.CORR_PUESTO = R.CORR_PUESTO
	LEFT JOIN dbo.SC_TIPO_MODALIDAD AS M
		ON M.CORR_EMPRESA = R.CORR_EMPRESA
	   AND M.CORR_TIPO_MODALIDAD = R.CORR_TIPO_MODALIDAD
	LEFT JOIN dbo.SC_TIPO_CONTRATACION AS TC
		ON TC.CORR_EMPRESA = R.CORR_EMPRESA
	   AND TC.CORR_TIPO_CONTRATACION = R.CORR_TIPO_CONTRATACION
	LEFT JOIN dbo.SC_TIPO_VACANTE AS TV
		ON TV.CORR_EMPRESA = R.CORR_EMPRESA
	   AND TV.CORR_TIPO_VACANTE = R.CORR_TIPO_VACANTE
	LEFT JOIN dbo.GEN_EMPRESA AS E
		ON E.CORR_EMPRESA = R.CORR_EMPRESA
	WHERE R.CORR_EMPRESA = @CORR_EMPRESA
	  AND R.CORR_REQUISICION_PERSONAL = @CORR_REQUISICION_PERSONAL;
END;
GO
