
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_CON_BALANCE_SALDOS_AUXI]
( 
  @CORR_EMPRESA INT,
  @FECHA_INICIAL DATE,
  @FECHA_FINAL DATE,
  @CUENTA_CONTABLE varchar(30)=NULL,
  @CORR_AUXILIAR INT=NULL,
  @PARTIDA_CIERRE BIT=0,
  @PARTIDA_LIQUIDACION BIT=0,
  @CUENTA_A_CERO BIT=0,
  @CORR_CONFI_REPORTE INT=NULL,  
  @CORR_MONEDA INT=NULL
)
AS	
	DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),
		CUENTA_MAYOR varchar(30),
		CORR_AUXILIAR INT,
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(12,2),
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),
		SALDO_FINAL	DECIMAL(12,2)
	)
	
	DECLARE @CORR_MONEDA_LOCAL INT, @CORR_MONEDA_FORANEA INT
BEGIN
    
    SET NOCOUNT ON
        
	SELECT @FECHA_INICIAL=DATEADD(DAY,-1,@FECHA_INICIAL)	
	
	SELECT @CORR_MONEDA_LOCAL=CORR_MONEDA
	FROM GEN_EMPRESA
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	
	SELECT @CORR_MONEDA_FORANEA=CORR_MONEDA_INTER
	FROM GEN_PARAMETRO
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	
	IF @CORR_MONEDA IS NULL
		SELECT @CORR_MONEDA=@CORR_MONEDA_LOCAL	
	
	
	IF @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL
	BEGIN
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL_AUXILIAR 
		@CORR_EMPRESA,
		@FECHA_INICIAL,
		0,--OPCION_CONSULTA=Saldo de todas las cuentas contables hasta antes de la fecha de consulta
		0,--MAYORIZA=Mayoriza los saldo
		@CUENTA_CONTABLE,
		@CORR_AUXILIAR,		
		1, --Aplicar el debe o haber de la cuenta
		1, --Incluir partidas de cierre
		1, --Incluir partidas de liquidacion
		0, --Todos los niveles
		@CORR_CONFI_REPORTE
	END ELSE
	IF @CORR_MONEDA=@CORR_MONEDA_FORANEA
	BEGIN
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL_AUXILIAR_FORANEA
		@CORR_EMPRESA,
		@FECHA_INICIAL,
		0,--OPCION_CONSULTA=Saldo de todas las cuentas contables hasta antes de la fecha de consulta
		0,--MAYORIZA=Mayoriza los saldo
		@CUENTA_CONTABLE,
		@CORR_AUXILIAR,		
		1, --Aplicar el debe o haber de la cuenta
		1, --Incluir partidas de cierre
		1, --Incluir partidas de liquidacion
		0, --Todos los niveles
		@CORR_CONFI_REPORTE
	END
    SELECT @FECHA_INICIAL=DATEADD(DAY,1,@FECHA_INICIAL)	

	SELECT C.CORR_EMPRESA
		,C.CUENTA_CONTABLE
		,C.CORR_AUXILIAR
		,Z.NOMBRE_CUENTA
		,A.NOMBRE_AUXILIAR
		--,B.CORR_CENTRO_COSTO
		--,B.NOMBRE_CENTRO
		,ISNULL(K.SALDO_INICIAL,ISNULL(C.SALDO_FINAL,0)) SALDO_INICIAL
		,SUM(ISNULL(B.MONTO_CARGO,0)) MONTO_CARGO
		,SUM(ISNULL(B.MONTO_ABONO,0)) MONTO_ABONO				
		,ISNULL(K.SALDO_INICIAL,ISNULL(C.SALDO_FINAL,0))+((SUM(ISNULL(B.MONTO_CARGO,0))-SUM(ISNULL(B.MONTO_ABONO,0)))*(CASE WHEN ISNULL(C.ES_DEBE,1)=1 THEN 1 ELSE CASE WHEN ISNULL(C.ES_HABER,0)=1 THEN -1 ELSE 0 END END)) SALDO_FINAL
		,J.NOMBRE_MONEDA
		,J.DESCRIPCION_MONEDA
		,J.SIMBOLO SIMBOLO_MONEDA
	FROM @SALDO C
	INNER JOIN V_CON_CATALOGO_CUENTA Z ON C.CORR_EMPRESA=Z.CORR_EMPRESA AND C.CUENTA_CONTABLE=Z.CUENTA_CONTABLE
	LEFT OUTER JOIN V_CON_CATALOGO_CUENTA_AUXI A ON C.CORR_EMPRESA=A.CORR_EMPRESA AND C.CUENTA_CONTABLE=A.CUENTA_CONTABLE AND ISNULL(C.CORR_AUXILIAR,0)=ISNULL(A.CORR_AUXILIAR,0)
	LEFT OUTER JOIN (SELECT A.CORR_EMPRESA
					 ,A.ANIO_PERIODO
					 ,A.MES_PERIODO
					 ,A.CORR_CLASE_PARTIDA
					 ,A.NOMBRE_CORTO_CLASE NOMBRE_CLASE_PARTIDA						 
					 ,A.NUMERO_DOCUMENTO
					 ,A.CORR_PARTIDA
					 ,A.FECHA_PARTIDA
					 ,B.CORR_PARTIDA_DETA
					 ,B.CUENTA_CONTABLE	
					 ,B.CORR_AUXILIAR	
					 ,B.NOMBRE_CUENTA
					 ,B.CORR_CENTRO_COSTO
					 ,B.NOMBRE_CENTRO
					 ,CASE WHEN @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL THEN B.MONTO_CARGO ELSE B.MONTO_CARGO_FORANEA END MONTO_CARGO
					 ,CASE WHEN @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL THEN B.MONTO_ABONO ELSE B.MONTO_ABONO_FORANEA END MONTO_ABONO
					 ,B.NOMBRE_TRAN
					 FROM V_CON_PARTIDA A
					 INNER JOIN V_CON_PARTIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
					 WHERE A.CORR_EMPRESA=@CORR_EMPRESA	 
					 AND A.FECHA_PARTIDA>=@FECHA_INICIAL
					 AND A.FECHA_PARTIDA<=@FECHA_FINAL
					 AND (CONVERT(BIT,CASE WHEN A.CLASE_PARTIDA='CIE' THEN 1 ELSE 0 END)=@PARTIDA_CIERRE OR @PARTIDA_CIERRE=1)
					 AND (CONVERT(BIT,CASE WHEN A.CLASE_PARTIDA='LIQ' THEN 1 ELSE 0 END)=@PARTIDA_LIQUIDACION OR @PARTIDA_LIQUIDACION=1)
					 AND A.ESTADO_PARTIDA='AP' 
					 AND A.NOMBRE_CORTO_CLASE<>'APE'
					) B ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CUENTA_CONTABLE=C.CUENTA_CONTABLE AND ISNULL(B.CORR_AUXILIAR,0)=ISNULL(C.CORR_AUXILIAR,0)	
	LEFT OUTER JOIN CON_CONFI_REPORTE_DETA E ON C.CORR_EMPRESA=E.CORR_EMPRESA 
	AND (C.CUENTA_CONTABLE>=E.CUENTA_CONTABLE_INI OR ISNULL(E.CUENTA_CONTABLE_INI,'')='')
	AND (C.CUENTA_CONTABLE<=E.CUENTA_CONTABLE_FINA OR ISNULL(E.CUENTA_CONTABLE_FINA,'')='')	
	LEFT OUTER JOIN GEN_TIPO_MONEDA J ON @CORR_MONEDA=J.CORR_MONEDA
	LEFT OUTER JOIN(SELECT A.CORR_EMPRESA
					 ,A.CUENTA_CONTABLE
					 ,A.CORR_AUXILIAR
					 ,SUM(CASE WHEN @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL THEN A.SALDO_INICIAL ELSE A.SALDO_INICIAL_FORANEA END*A.ES_DEBE_HABER) SALDO_INICIAL
					FROM V_CON_PARTIDA_INICIAL A
					WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					AND A.ANIO_PERIODO=YEAR(@FECHA_INICIAL) 
					AND A.MES_PERIODO=MONTH(@FECHA_INICIAL)
					GROUP BY A.CORR_EMPRESA
					 ,A.CUENTA_CONTABLE
					 ,A.CORR_AUXILIAR
	) K ON C.CORR_EMPRESA=K.CORR_EMPRESA AND C.CUENTA_CONTABLE=K.CUENTA_CONTABLE AND ISNULL(C.CORR_AUXILIAR,0)=ISNULL(K.CORR_AUXILIAR,0)											
	AND ISNULL(C.CORR_EMPRESA,B.CORR_EMPRESA)=@CORR_EMPRESA	
	AND (ISNULL(C.CUENTA_CONTABLE,B.CUENTA_CONTABLE)=@CUENTA_CONTABLE OR ISNULL(@CUENTA_CONTABLE,'')='')
	AND (ISNULL(C.CORR_AUXILIAR,B.CORR_AUXILIAR)=@CORR_AUXILIAR OR ISNULL(@CORR_AUXILIAR,0)=0)
	AND (@CUENTA_A_CERO=1 OR (@CUENTA_A_CERO<>1 AND (CASE WHEN Z.ES_DETALLE=1 THEN ISNULL(K.SALDO_INICIAL,ISNULL(C.SALDO_FINAL,0)) ELSE 0 END<>0 OR B.MONTO_CARGO<>0 OR B.MONTO_ABONO<>0)))
	AND (E.CORR_CONFI_REPORTE=@CORR_CONFI_REPORTE OR @CORR_CONFI_REPORTE IS NULL)
	GROUP BY C.CORR_EMPRESA
		,C.CUENTA_CONTABLE
		,C.CORR_AUXILIAR
		,Z.NOMBRE_CUENTA
		,A.NOMBRE_AUXILIAR
		--,B.CORR_CENTRO_COSTO
		--,B.NOMBRE_CENTRO
		,ISNULL(K.SALDO_INICIAL,ISNULL(C.SALDO_FINAL,0))
		,ISNULL(C.SALDO_FINAL,0)
		,ISNULL(C.ES_DEBE,1)
		,ISNULL(C.ES_HABER,0)
		,J.NOMBRE_MONEDA
		,J.DESCRIPCION_MONEDA
		,J.SIMBOLO
	ORDER BY C.CORR_EMPRESA, C.CUENTA_CONTABLE, C.CORR_AUXILIAR
	
	SELECT A.CORR_EMPRESA 
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END

GO
