SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_SOLI_COTIZACION_ANULAR]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO INT,
	@CORR_SOLI_COTIZACION int OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
	DECLARE @ANIO_PERIODO_BITACORA INT=YEAR(GETDATE()), @CORR_BITACORA_TRANS INT=0, @FECHA_BITACORA DATE=GETDATE(), @LLAVE_TRANSACCION VARCHAR(250),@REFERENCIA_TRANSACCION VARCHAR(500), 
	@USUARIO_CREA_TRANS VARCHAR(50), @ESTACION_CREA_TRANS VARCHAR(50), @FECHA_CREA_TRANS DATETIME,@USUARIO_ACTU_TRANS VARCHAR(50), @ESTACION_ACTU_TRANS VARCHAR(50),
	@FECHA_ACTU_TRANS DATETIME, @USUARIO_CREA_BITACORA VARCHAR(50),@ESTACION_CREA_BITACORA VARCHAR(50), @FECHA_CREA_BITACORA DATETIME=GETDATE(),
	@CODIGO_OPCION VARCHAR(150)='COM_SOLI_COTIZACION',@CLASE_BITACORA VARCHAR(3)='AN'
BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY

		IF EXISTS(SELECT 1 FROM COM_CUADRO_COMPARATIVO_DETA A 
				  INNER JOIN COM_COTIZACION B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO_COTIZACION = B.ANIO_PERIODO AND A.CORR_COTIZACION = B.CORR_COTIZACION
				  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
				  AND B.ANIO_PERIODO_SOLI_COTI=@ANIO_PERIODO
				  AND B.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='No se permite anular una solicitud incluida en un cuadro comparativo.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		------------------------------------------------------------------------
		-------------  BITACORA -------------- 
		SELECT @LLAVE_TRANSACCION='Año: '+CONVERT(VARCHAR,A.ANIO_PERIODO) COLLATE DATABASE_DEFAULT+' Correlativo No.: '+CONVERT(VARCHAR,A.CORR_SOLI_COTIZACION) COLLATE DATABASE_DEFAULT,
				@REFERENCIA_TRANSACCION= ' Fecha: '+ CONVERT(VARCHAR,A.FECHA_SOLI_COTIZACION) COLLATE DATABASE_DEFAULT
										+', Departemento: '+A.NOMBRE_DEPTO COLLATE DATABASE_DEFAULT
										+', Proveedor: '+A.NOMBRE_PROVEEDOR COLLATE DATABASE_DEFAULT
										+', Observaciones: '+A.OBSERVACIONES COLLATE DATABASE_DEFAULT,
				@USUARIO_CREA_TRANS=A.USUARIO_CREA, @ESTACION_CREA_TRANS=A.ESTACION_CREA, @FECHA_CREA_TRANS=A.FECHA_CREA,
				@USUARIO_ACTU_TRANS=A.USUARIO_ACTU, @ESTACION_ACTU_TRANS=A.ESTACION_ACTU, @FECHA_ACTU_TRANS=A.FECHA_ACTU
		FROM V_COM_SOLI_COTIZACION A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

		UPDATE B SET
		B.ESTADO_COTIZACION='AN'
		FROM COM_SOLI_COTIZACION A
		INNER JOIN COM_COTIZACION B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO_SOLI_COTI AND A.CORR_SOLI_COTIZACION = B.CORR_SOLI_COTIZACION
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

		UPDATE C SET
		C.ESTADO_SOLI_COTIZACION='AN'
		FROM COM_SOLI_COTIZACION A
		INNER JOIN COM_COTIZACION B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO_SOLI_COTI AND A.CORR_SOLI_COTIZACION = B.CORR_SOLI_COTIZACION
		INNER JOIN COM_COTIZACION_DETA C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO = C.ANIO_PERIODO AND B.CORR_COTIZACION = C.CORR_COTIZACION
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

		UPDATE B SET
		B.ESTADO_SOLI_COTIZACION='AN'
		FROM COM_SOLI_COTIZACION A
		INNER JOIN COM_SOLI_COTIZACION_DETA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION = B.CORR_SOLI_COTIZACION 
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

		UPDATE A SET
		A.ESTADO_SOLI_COTIZACION='AN'
		,A.USUARIO_ACTU=@SYS_LOGIN_USUARIO
		,A.ESTACION_ACTU=@SYS_ESTACION
		,A.FECHA_ACTU=GETDATE()
		FROM COM_SOLI_COTIZACION A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION


		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

		--Executando el procedimiento de la bitacora
		EXECUTE PRAL_MTTO_COM_BITACORA
		1,--@TIPO_ACTUALIZA ,                              
		@CORR_EMPRESA ,
		@ANIO_PERIODO_BITACORA,
		@CORR_BITACORA_TRANS  OUTPUT,
		@FECHA_BITACORA ,                    
		@CODIGO_OPCION,                               
		@CLASE_BITACORA ,                              
		@LLAVE_TRANSACCION ,                           
		@REFERENCIA_TRANSACCION ,                      
		@USUARIO_CREA_TRANS ,                          
		@ESTACION_CREA_TRANS,                         
		@FECHA_CREA_TRANS ,         
		@USUARIO_ACTU_TRANS ,                          
		@ESTACION_ACTU_TRANS ,                         
		@FECHA_ACTU_TRANS ,         
		@SYS_LOGIN_USUARIO, --@USUARIO_CREA_BITACORA
		@SYS_ESTACION, --@ESTACION_CREA_BITACORA                      
		@FECHA_CREA_BITACORA ,      
		@SYS_LOGIN_USUARIO,                           
		@SYS_ESTACION ,                                
		@SYS_FILAS_AFECTADAS OUTPUT,
		@SYS_NUMERO_ERROR  OUTPUT,      
		@SYS_MENSAJE_ERROR  OUTPUT

	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DATETIME,
		@CORR_SUSCRIPCION INT=3,
		@CORR_CONFI_PAIS INT=1

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		--EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
