SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_LIBRO_DIARIO_AUXILIAR]
( 
  @CORR_EMPRESA INT,
  @FECHA_INICIAL DATE,
  @FECHA_FINAL DATE,
  @CUENTA_CONTABLE_INICIAL varchar(30)=NULL,
  @CUENTA_CONTABLE_FINAL varchar(30)=NULL,
  @PARTIDA_CIERRE BIT=0,
  @PARTIDA_LIQUIDACION BIT=0,
  @CUENTA_A_CERO BIT=0,
  @CORR_CONFI_REPORTE INT=NULL,
  @CONSOLIDADO BIT=0,
  @CORR_MONEDA INT=NULL,
  @FOLIADO BIT=0,
  @NUMERO_FOLIO INT=0,
  @CUENTA_ESPECIFICA varchar(30)=NULL
)
AS	
	DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),
		CUENTA_MAYOR varchar(30),
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(12,2),
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),
		SALDO_FINAL	DECIMAL(12,2)
	)
	
	DECLARE @CORR_MONEDA_LOCAL INT, @CORR_MONEDA_FORANEA INT
BEGIN
    
    SET NOCOUNT ON
        
	SELECT @FECHA_INICIAL=DATEADD(DAY,-1,@FECHA_INICIAL)	
	
	SELECT @CORR_MONEDA_LOCAL=CORR_MONEDA
	FROM CON_PARAMETRO
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	
	SET @CORR_MONEDA_FORANEA = NULL
	
	IF @CORR_MONEDA IS NULL
		SELECT @CORR_MONEDA=@CORR_MONEDA_LOCAL	
	
	
	IF @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL
	BEGIN
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL 
		@CORR_EMPRESA,
		@FECHA_INICIAL,
		0,--OPCION_CONSULTA=Saldo de todas las cuentas contables hasta antes de la fecha de consulta
		0,--MAYORIZA=Mayoriza los saldo
		@CUENTA_CONTABLE_INICIAL,
		@CUENTA_CONTABLE_FINAL,		
		1, --Aplicar el debe o haber de la cuenta
		1, --@PARTIDA_CIERRE, --Incluir partidas de cierre
		1, --@PARTIDA_LIQUIDACION, --Incluir partidas de liquidacion
		0, --Todos los niveles
		@CORR_CONFI_REPORTE
	END ELSE
	IF @CORR_MONEDA=@CORR_MONEDA_FORANEA
	BEGIN
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL_FORANEA
		@CORR_EMPRESA,
		@FECHA_INICIAL,
		0,--OPCION_CONSULTA=Saldo de todas las cuentas contables hasta antes de la fecha de consulta
		0,--MAYORIZA=Mayoriza los saldo
		@CUENTA_CONTABLE_INICIAL,
		@CUENTA_CONTABLE_FINAL,		
		1, --Aplicar el debe o haber de la cuenta
		1, --@PARTIDA_CIERRE, --Incluir partidas de cierre
		1, --@PARTIDA_LIQUIDACION, --Incluir partidas de liquidacion
		0, --Todos los niveles
		@CORR_CONFI_REPORTE
	END
        
	

	--Se reconstruyo la consulta para poder mostrar cuentas sin movimientos
	------------------------------------------------------------------------------------------------
	;WITH CTE_PARTIDAS AS (
	SELECT DISTINCT C.CORR_EMPRESA		
		,B.ANIO_PERIODO
		,B.MES_PERIODO
		,B.CORR_CLASE_PARTIDA
		,B.NOMBRE_CLASE_PARTIDA	
		,B.CORR_PARTIDA
		,B.NUMERO_DOCUMENTO
		,B.FECHA_PARTIDA
		,B.CORR_PARTIDA_DETA
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE G.CUENTA_CONTABLE+' '+G.NOMBRE_CUENTA END CUENTA_MAYOR_2
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE H.CUENTA_CONTABLE+' '+H.NOMBRE_CUENTA END CUENTA_MAYOR_3
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE I.CUENTA_CONTABLE+' '+I.NOMBRE_CUENTA END CUENTA_MAYOR_4
		,CASE WHEN @CONSOLIDADO=1 THEN '' ELSE F.CUENTA_CONTABLE+' '+F.NOMBRE_CUENTA END CUENTA_DEPARTAMENTO
		,C.CUENTA_CONTABLE
	
		,Z.NOMBRE_CUENTA
		,B.CORR_CENTRO_COSTO
		,B.NOMBRE_CENTRO
		,ISNULL(B.MONTO_CARGO,0) MONTO_CARGO
		,ISNULL(B.MONTO_ABONO,0) MONTO_ABONO
		,B.NOMBRE_TRAN
		,CASE WHEN Z.ES_DETALLE=1 THEN ISNULL(C.SALDO_FINAL,0) ELSE 0 END SALDO_INICIAL									  		
		,(CASE WHEN ROW_NUMBER() OVER(PARTITION BY C.CORR_EMPRESA,C.CUENTA_CONTABLE
									  ORDER BY C.CORR_EMPRESA, C.CUENTA_CONTABLE, B.FECHA_PARTIDA, B.CORR_CLASE_PARTIDA, B.CORR_PARTIDA,ISNULL(B.MONTO_CARGO,0),ISNULL(B.MONTO_ABONO,0))=1 THEN CASE WHEN Z.ES_DETALLE=1 THEN ISNULL(C.SALDO_FINAL,0) ELSE 0 END ELSE 0 END)+
		((ISNULL(B.MONTO_CARGO,0)-ISNULL(B.MONTO_ABONO,0))*(CASE WHEN ISNULL(C.ES_DEBE,1)=1 THEN 1 ELSE CASE WHEN ISNULL(C.ES_HABER,0)=1 THEN -1 ELSE 0 END END)) SALDO_FINAL
		,((ISNULL(B.MONTO_CARGO,0)-ISNULL(B.MONTO_ABONO,0))*(CASE WHEN ISNULL(C.ES_DEBE,1)=1 THEN 1 ELSE CASE WHEN ISNULL(C.ES_HABER,0)=1 THEN -1 ELSE 0 END END)) SALDO_FINAL_MES
		,(CASE WHEN ROW_NUMBER() OVER(PARTITION BY C.CORR_EMPRESA,C.CUENTA_CONTABLE
									  ORDER BY C.CORR_EMPRESA, C.CUENTA_CONTABLE, B.FECHA_PARTIDA, B.CORR_CLASE_PARTIDA, B.CORR_PARTIDA,ISNULL(B.MONTO_CARGO,0),ISNULL(B.MONTO_ABONO,0))=1 THEN CASE WHEN Z.ES_DETALLE=1 THEN ISNULL(C.SALDO_FINAL,0) ELSE 0 END ELSE 0 END)+
		((ISNULL(B.MONTO_CARGO,0)-ISNULL(B.MONTO_ABONO,0))) SALDO_FINAL_2
		,'' NOMBRE_MONEDA
		,'' DESCRIPCION_MONEDA
		,'' SIMBOLO_MONEDA
		,@FOLIADO FOLIADO
		,@NUMERO_FOLIO NUMERO_FOLIO
	FROM @SALDO C
	INNER JOIN V_CON_CATALOGO_CUENTA Z ON C.CORR_EMPRESA=Z.CORR_EMPRESA AND C.CUENTA_CONTABLE=Z.CUENTA_CONTABLE
	LEFT OUTER JOIN (SELECT A.CORR_EMPRESA
					 ,A.ANIO_PERIODO
					 ,A.MES_PERIODO
					 ,A.CORR_CLASE_PARTIDA
					 ,A.NOMBRE_CORTO_CLASE NOMBRE_CLASE_PARTIDA						 
					 ,A.NUMERO_DOCUMENTO
					 ,A.CORR_PARTIDA
					 ,A.FECHA_PARTIDA
					 ,B.CORR_PARTIDA_DETA
					 ,B.CUENTA_CONTABLE		
					 ,B.NOMBRE_CUENTA
					 ,B.CORR_CENTRO_COSTO
					 ,B.NOMBRE_CENTRO
					 ,CASE WHEN @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL THEN B.MONTO_CARGO ELSE B.MONTO_CARGO_FORANEA END MONTO_CARGO
					 ,CASE WHEN @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL THEN B.MONTO_ABONO ELSE B.MONTO_ABONO_FORANEA END MONTO_ABONO
					 ,B.NOMBRE_TRAN
					 FROM V_CON_PARTIDA A
					 INNER JOIN V_CON_PARTIDA_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA AND A.CORR_PARTIDA=B.CORR_PARTIDA
					 WHERE A.FECHA_PARTIDA>@FECHA_INICIAL
					 AND A.FECHA_PARTIDA<=@FECHA_FINAL
					 AND (CONVERT(BIT,CASE WHEN A.CLASE_PARTIDA='CIE' THEN 1 ELSE 0 END)=@PARTIDA_CIERRE OR @PARTIDA_CIERRE=1)
					 AND (CONVERT(BIT,CASE WHEN A.CLASE_PARTIDA='LIQ' THEN 1 ELSE 0 END)=@PARTIDA_LIQUIDACION OR @PARTIDA_LIQUIDACION=1)
					 AND A.ESTADO_PARTIDA='AP' 
					) B ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.CUENTA_CONTABLE=C.CUENTA_CONTABLE
	--LEFT OUTER JOIN V_CON_PARTIDA_DETA_DOC_SUM D ...
	--LEFT OUTER JOIN CON_CONFI_REPORTE_DETA E ON C.CORR_EMPRESA=E.CORR_EMPRESA 
	--AND (C.CUENTA_CONTABLE>=E.CUENTA_CONTABLE_INI OR ISNULL(E.CUENTA_CONTABLE_INI,'')='')
	--AND (C.CUENTA_CONTABLE<=E.CUENTA_CONTABLE_FINA OR ISNULL(E.CUENTA_CONTABLE_FINA,'')='')
	
	
	INNER JOIN CON_CATALOGO_CUENTA F ON Z.CORR_EMPRESA=F.CORR_EMPRESA AND Z.CUENTA_MAYOR=F.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA G ON F.CORR_EMPRESA=G.CORR_EMPRESA AND F.CUENTA_MAYOR=G.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA H ON G.CORR_EMPRESA=H.CORR_EMPRESA AND G.CUENTA_MAYOR=H.CUENTA_CONTABLE
	LEFT OUTER JOIN CON_CATALOGO_CUENTA I ON H.CORR_EMPRESA=I.CORR_EMPRESA AND H.CUENTA_MAYOR=I.CUENTA_CONTABLE
	WHERE ISNULL(C.CORR_EMPRESA,B.CORR_EMPRESA)=@CORR_EMPRESA	
	AND (ISNULL(C.CUENTA_CONTABLE,B.CUENTA_CONTABLE)>=@CUENTA_CONTABLE_INICIAL OR ISNULL(@CUENTA_CONTABLE_INICIAL,'')='')
	AND (ISNULL(C.CUENTA_CONTABLE,B.CUENTA_CONTABLE)<=@CUENTA_CONTABLE_FINAL OR ISNULL(@CUENTA_CONTABLE_FINAL,'')='')
	AND (ISNULL(C.CUENTA_CONTABLE,B.CUENTA_CONTABLE) LIKE '%'+@CUENTA_ESPECIFICA OR ISNULL(@CUENTA_ESPECIFICA,'')='')
	AND (@CUENTA_A_CERO=1 OR (@CUENTA_A_CERO<>1 AND (CASE WHEN Z.ES_DETALLE=1 THEN ISNULL(C.SALDO_FINAL,0) ELSE 0 END<>0 OR B.MONTO_CARGO<>0 OR B.MONTO_ABONO<>0)))
	--AND (E.CORR_CONFI_REPORTE=@CORR_CONFI_REPORTE OR @CORR_CONFI_REPORTE IS NULL)
	--ORDER BY C.CORR_EMPRESA, C.CUENTA_CONTABLE, B.FECHA_PARTIDA, B.CORR_CLASE_PARTIDA, B.CORR_PARTIDA,ISNULL(B.MONTO_CARGO,0),ISNULL(B.MONTO_ABONO,0)
	)

	SELECT C.* FROM CTE_PARTIDAS C
	LEFT OUTER JOIN CON_CONFI_REPORTE_DETA H ON C.CORR_EMPRESA=H.CORR_EMPRESA 
	AND H.CORR_CONFI_REPORTE=@CORR_CONFI_REPORTE
	WHERE (C.CUENTA_CONTABLE>=H.CUENTA_CONTABLE_INI OR ISNULL(H.CUENTA_CONTABLE_INI,'')='')
	AND (C.CUENTA_CONTABLE<=H.CUENTA_CONTABLE_FINA OR ISNULL(H.CUENTA_CONTABLE_FINA,'')='')
	ORDER BY C.CORR_EMPRESA, C.CUENTA_CONTABLE, C.FECHA_PARTIDA, C.CORR_CLASE_PARTIDA, C.CORR_PARTIDA,ISNULL(C.MONTO_CARGO,0),ISNULL(C.MONTO_ABONO,0)
	
	

	SELECT A.CORR_EMPRESA 
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO

