SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_BAN_TIPO_MOVI_SEGUN_BANCO]
(
	@TIPO_CONSULTA int,
	@CORR_EMPRESA int=NULL,
	@CORR_TIPO_MOVIMIENTO int=NULL,
	@CORR_BANCO int=NULL,
	@CODIGO_MOVIMIENTO varchar(10)=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		SELECT * FROM V_BAN_TIPO_MOVI_SEGUN_BANCO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		SELECT * FROM V_BAN_TIPO_MOVI_SEGUN_BANCO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
		AND CORR_BANCO=@CORR_BANCO
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_BAN_TIPO_MOVI_SEGUN_BANCO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO
		AND CORR_BANCO=@CORR_BANCO
		AND CODIGO_MOVIMIENTO=@CODIGO_MOVIMIENTO
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			--Para saber que tipo de movimiento le corresponde segun el codigo que manda el banco
			SELECT TOP 1 CORR_TIPO_MOVIMIENTO FROM V_BAN_TIPO_MOVI_SEGUN_BANCO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_BANCO=@CORR_BANCO
			AND CODIGO_MOVIMIENTO=@CODIGO_MOVIMIENTO
		END
	END

END
GO

