SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_SEG_OPCION_SISTEMA_SUITE]
(
	@TIPO_ACTUALIZA INT,
	@CODIGO_OPCION varchar(30),
	@CODIGO_SUITE varchar(30) OUTPUT,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			INSERT INTO SEG_OPCION_SISTEMA_SUITE
			(CODIGO_OPCION,CODIGO_SUITE)
			VALUES
			(@CODIGO_OPCION,@CODIGO_SUITE)
		END ELSE
		--IF @TIPO_ACTUALIZA=2 --Actualizar
		--BEGIN
		--	UPDATE SEG_OPCION_SISTEMA_SUITE SET
			
		--	WHERE CODIGO_OPCION=@CODIGO_OPCION
		--	AND CODIGO_SUITE=@CODIGO_SUITE
		--END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM SEG_OPCION_SISTEMA_SUITE
			WHERE CODIGO_OPCION=@CODIGO_OPCION
			AND CODIGO_SUITE=@CODIGO_SUITE
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
