SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================================================
-- Procedimiento: dbo.PRAL_MTTO_SC_CONTRATAR_CANDIDATO_A_EMPLEADO
-- Módulo:        Selección y Contratación -> General / Talento Humano
--
-- Qué hace:
--   Contrata a un candidato desde su expediente y movimiento de personal confirmado,
--   creando o reutilizando la persona general (GEN_PERSONA y GEN_PERSONA_NATURAL),
--   dando de alta al empleado (GEN_EMPLEADO) y asignando su plaza (GEN_EMPLEADO_PUESTO),
--   junto con la migración de todo su perfil curricular:
--     - Documentos de identidad (GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD)
--     - Contactos de teléfono y correo (GEN_PERSONA_CONTACTO)
--     - Domicilio (GEN_PERSONA_DOMICILIO)
--     - Contacto de emergencia (GEN_PERSONA_PARENTESCO_CONTACTO)
--     - Formación académica (GEN_PERSONA_FORMACION_ACADEMICA)
--     - Experiencia laboral (GEN_PERSONA_EXPERIENCIA_LABORAL)
--     - Habilidades / Competencias (GEN_PERSONA_COMPETENCIA)
--     - Idiomas (GEN_PERSONA_IDIOMAS)
--     - Referencias familiares (GEN_PERSONA_FAMILIAR)
--     - Familiares en UEES (GEN_PERSONA_FAMILIAR_UEES)
--     - Hijos (GEN_PERSONA_HIJOS)
--
-- Cómo lo hace:
--   1) Valida existencia de empresa, movimiento y confirmación previa de Talento Humano.
--   2) Recupera el candidato y expediente asociado a través de SC_MOVIMIENTO_REQUISICION.
--   3) Evalúa si la persona ya existe por DUI en GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
--      para reutilizar CORR_PERSONA y evitar duplicidad de registros en la institución.
--   4) Ejecuta una transacción atómica donde copia cada detalle hacia las tablas de GEN,
--      omitiendo columnas calculadas (NOMBRE_COMPLETO, PERIODO_*) y homologando valores
--      hacia las restricciones CHECK de BD.
--   5) Genera el registro de GEN_EMPLEADO y GEN_EMPLEADO_PUESTO con concurrencia segura
--      (UPDLOCK, HOLDLOCK).
--   6) Actualiza SC_MOVIMIENTO_PERSONAL.CORR_EMPLEADO y registra la bitácora del movimiento.
--
-- Exclusiones:
--   No gestiona GEN_PERSONA_USUARIO.
-- =============================================================================
CREATE OR ALTER PROCEDURE [dbo].[PRAL_MTTO_SC_CONTRATAR_CANDIDATO_A_EMPLEADO]
(
	@CORR_EMPRESA                 INT,
	@CORR_MOVIMIENTO_PERSONAL     INT,
	@SYS_LOGIN_USUARIO            VARCHAR(50),
	@SYS_ESTACION                 VARCHAR(50),
	@CORR_EMPLEADO                INT = NULL OUTPUT,
	@CORR_PERSONA                 BIGINT = NULL OUTPUT,
	@SYS_FILAS_AFECTADAS          INT = 0 OUTPUT,
	@SYS_NUMERO_ERROR             NUMERIC(38, 0) = 0 OUTPUT,
	@SYS_MENSAJE_ERROR            NVARCHAR(4000) = N'' OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	SET XACT_ABORT ON;

	SELECT
		@CORR_EMPLEADO = NULL,
		@CORR_PERSONA = NULL,
		@SYS_FILAS_AFECTADAS = 0,
		@SYS_NUMERO_ERROR = 0,
		@SYS_MENSAJE_ERROR = N'';

	DECLARE @FECHA_AUD DATETIME = GETDATE();

	-- Variables del movimiento y expediente
	DECLARE
		@CORR_EXPEDIENTE_CANDIDATO INT = NULL,
		@CORR_PERSONA_DATOS INT = NULL,
		@ESTADO_MOVIMIENTO VARCHAR(2) = NULL,
		@CONFIRMADO BIT = 0,
		@CORR_EMPLEADO_EXISTENTE INT = NULL,
		@FECHA_INGRESO DATE = NULL,
		@CORR_UNIDAD_PROPUESTA INT = NULL,
		@CORR_PUESTO_PROPUESTO INT = NULL,
		@SALARIO_PROPUESTO DECIMAL(18, 2) = NULL,
		@HORARIO_PROPUESTO NVARCHAR(250) = NULL,
		@CORR_TIPO_MODALIDAD_PROPUESTA INT = NULL,
		@CORR_TIPO_CONTRATACION INT = NULL,
		@TIPO_MOVIMIENTO VARCHAR(20) = NULL;

	-- Variables de persona natural
	DECLARE
		@CORR_PERSONA_NATURAL BIGINT = NULL,
		@CODIGO_PERSONA VARCHAR(20) = NULL,
		@DUI_ORIGINAL VARCHAR(50) = NULL,
		@DUI_DIGITOS VARCHAR(50) = NULL,
		@DUI_FORMATEADO VARCHAR(25) = NULL,
		@PASAPORTE_CANDIDATO VARCHAR(50) = NULL,
		@ISSS_CANDIDATO VARCHAR(50) = NULL,
		@AFP_CANDIDATO VARCHAR(50) = NULL,
		@NOMBRE_AFP_CANDIDATO VARCHAR(100) = NULL,
		@LICENCIA_CANDIDATO VARCHAR(50) = NULL,
		@CORREO_CANDIDATO VARCHAR(254) = NULL,
		@CELULAR_CANDIDATO VARCHAR(25) = NULL,
		@TELEFONO_CANDIDATO VARCHAR(25) = NULL,
		@DIRECCION_CANDIDATO VARCHAR(500) = NULL,
		@NOMBRE1 VARCHAR(50) = NULL,
		@NOMBRE2 VARCHAR(50) = NULL,
		@APELLIDO1 VARCHAR(50) = NULL,
		@APELLIDO2 VARCHAR(50) = NULL,
		@FECHA_NACIMIENTO DATE = NULL,
		@EDAD INT = NULL,
		@ESTADO_CIVIL VARCHAR(25) = NULL,
		@NACIONALIDAD VARCHAR(25) = NULL,
		@ES_JUBILADO BIT = 0,
		@POSEE_DISCAPACIDAD BIT = 0,
		@TIPO_DISCAPACIDAD VARCHAR(250) = NULL,
		@IGLESIA VARCHAR(250) = NULL,
		@FOTO_URL VARCHAR(500) = NULL,
		@EMERGENCIA_NOMBRE VARCHAR(150) = NULL,
		@EMERGENCIA_PARENTESCO VARCHAR(100) = NULL,
		@EMERGENCIA_TELEFONO VARCHAR(25) = NULL,
		@CODIGO_EMPLEADO_NUEVO VARCHAR(50) = NULL;

	BEGIN TRY
		-- =====================================================================
		-- 1. VALIDACIONES INICIALES DE PARÁMETROS
		-- =====================================================================
		IF ISNULL(@CORR_EMPRESA, 0) <= 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30001, @SYS_MENSAJE_ERROR = N'CORR_EMPRESA es requerido.';
			GOTO SALIDA;
		END;

		IF ISNULL(@CORR_MOVIMIENTO_PERSONAL, 0) <= 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30002, @SYS_MENSAJE_ERROR = N'CORR_MOVIMIENTO_PERSONAL es requerido.';
			GOTO SALIDA;
		END;

		-- =====================================================================
		-- 2. VALIDAR ESTADO DEL MOVIMIENTO
		-- =====================================================================
		SELECT
			@ESTADO_MOVIMIENTO = M.ESTADO_MOVIMIENTO,
			@CONFIRMADO = ISNULL(M.CONFIRMADO, 0),
			@CORR_EMPLEADO_EXISTENTE = M.CORR_EMPLEADO,
			@FECHA_INGRESO = ISNULL(M.FECHA_EFECTIVA, M.FECHA_INGRESO_PROPUESTA),
			@CORR_UNIDAD_PROPUESTA = M.CORR_UNIDAD_PROPUESTA,
			@CORR_PUESTO_PROPUESTO = M.CORR_PUESTO_PROPUESTO,
			@SALARIO_PROPUESTO = M.SALARIO_PROPUESTO,
			@HORARIO_PROPUESTO = M.HORARIO_PROPUESTO,
			@CORR_TIPO_MODALIDAD_PROPUESTA = M.CORR_TIPO_MODALIDAD_PROPUESTA,
			@TIPO_MOVIMIENTO = M.TIPO_MOVIMIENTO
		FROM dbo.SC_MOVIMIENTO_PERSONAL AS M
		WHERE M.CORR_EMPRESA = @CORR_EMPRESA
		  AND M.CORR_MOVIMIENTO_PERSONAL = @CORR_MOVIMIENTO_PERSONAL;

		IF @ESTADO_MOVIMIENTO IS NULL
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30003, @SYS_MENSAJE_ERROR = N'El movimiento de personal especificado no existe.';
			GOTO SALIDA;
		END;

		IF @CORR_EMPLEADO_EXISTENTE IS NOT NULL AND @CORR_EMPLEADO_EXISTENTE > 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30004, @SYS_MENSAJE_ERROR = N'El movimiento ya tiene un empleado asignado (' + CAST(@CORR_EMPLEADO_EXISTENTE AS NVARCHAR(20)) + N').';
			GOTO SALIDA;
		END;

		IF @CONFIRMADO = 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30005, @SYS_MENSAJE_ERROR = N'El movimiento de personal debe estar confirmado por Talento Humano antes de generar el empleado.';
			GOTO SALIDA;
		END;

		IF @ESTADO_MOVIMIENTO NOT IN ('AP')
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30006, @SYS_MENSAJE_ERROR = N'El movimiento debe estar en estado Aprobado (AP).';
			GOTO SALIDA;
		END;

		IF @FECHA_INGRESO IS NULL
			SET @FECHA_INGRESO = CAST(@FECHA_AUD AS DATE);

		-- =====================================================================
		-- 3. RESOLVER EXPEDIENTE Y PERSONA DEL CANDIDATO
		-- =====================================================================
		SELECT
			@CORR_EXPEDIENTE_CANDIDATO = RC.CORR_EXPEDIENTE_CANDIDATO,
			@CORR_TIPO_CONTRATACION = R.CORR_TIPO_CONTRATACION
		FROM dbo.SC_MOVIMIENTO_REQUISICION AS MR
		INNER JOIN dbo.SC_REQUISICION_CANDIDATO AS RC
			ON RC.CORR_EMPRESA = MR.CORR_EMPRESA
		   AND RC.CORR_REQUISICION_CANDIDATO = MR.CORR_REQUISICION_CANDIDATO
		INNER JOIN dbo.SC_REQUISICION_PERSONAL AS R
			ON R.CORR_EMPRESA = MR.CORR_EMPRESA
		   AND R.CORR_REQUISICION_PERSONAL = MR.CORR_REQUISICION_PERSONAL
		WHERE MR.CORR_EMPRESA = @CORR_EMPRESA
		  AND MR.CORR_MOVIMIENTO_PERSONAL = @CORR_MOVIMIENTO_PERSONAL;

		IF @CORR_EXPEDIENTE_CANDIDATO IS NULL
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30007, @SYS_MENSAJE_ERROR = N'No se encontró la requisición o el candidato vinculado al movimiento.';
			GOTO SALIDA;
		END;

		SELECT
			@CORR_PERSONA_DATOS = E.CORR_PERSONA_DATOS
		FROM dbo.SC_EXPEDIENTE_CANDIDATO AS E
		WHERE E.CORR_EMPRESA = @CORR_EMPRESA
		  AND E.CORR_EXPEDIENTE_CANDIDATO = @CORR_EXPEDIENTE_CANDIDATO;

		IF @CORR_PERSONA_DATOS IS NULL
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30008, @SYS_MENSAJE_ERROR = N'El expediente no tiene persona asociada en SC_PERSONA_DATOS.';
			GOTO SALIDA;
		END;

		-- Leer datos de SC_PERSONA_DATOS
		SELECT
			@NOMBRE1 = NULLIF(LTRIM(RTRIM(NOMBRE1)), ''),
			@NOMBRE2 = NULLIF(LTRIM(RTRIM(NOMBRE2)), ''),
			@APELLIDO1 = NULLIF(LTRIM(RTRIM(APELLIDO1)), ''),
			@APELLIDO2 = NULLIF(LTRIM(RTRIM(APELLIDO2)), ''),
			@FECHA_NACIMIENTO = FECHA_NACIMIENTO,
			@EDAD = EDAD,
			@ESTADO_CIVIL = CASE
				WHEN UPPER(ESTADO_CIVIL) LIKE '%SOLTER%' THEN 'SOLTERO(A)'
				WHEN UPPER(ESTADO_CIVIL) LIKE '%CASAD%' THEN 'CASADO(A)'
				WHEN UPPER(ESTADO_CIVIL) LIKE '%ACOMPA%' THEN 'ACOMPAÑADO(A)'
				WHEN UPPER(ESTADO_CIVIL) LIKE '%DIVORC%' THEN 'DIVORCIADO(A)'
				WHEN UPPER(ESTADO_CIVIL) LIKE '%VIUD%' THEN 'VIUDO(A)'
				ELSE NULL
			END,
			@NACIONALIDAD = NULLIF(LTRIM(RTRIM(NACIONALIDAD)), ''),
			@DUI_ORIGINAL = NULLIF(LTRIM(RTRIM(DUI)), ''),
			@PASAPORTE_CANDIDATO = NULLIF(LTRIM(RTRIM(PASAPORTE)), ''),
			@ISSS_CANDIDATO = NULLIF(LTRIM(RTRIM(ISSS)), ''),
			@AFP_CANDIDATO = NULLIF(LTRIM(RTRIM(AFP)), ''),
			@NOMBRE_AFP_CANDIDATO = NULLIF(LTRIM(RTRIM(NOMBRE_AFP)), ''),
			@LICENCIA_CANDIDATO = NULLIF(LTRIM(RTRIM(LICENCIA)), ''),
			@CORREO_CANDIDATO = NULLIF(LTRIM(RTRIM(CORREO)), ''),
			@CELULAR_CANDIDATO = NULLIF(LTRIM(RTRIM(CELULAR)), ''),
			@TELEFONO_CANDIDATO = NULLIF(LTRIM(RTRIM(TELEFONO)), ''),
			@DIRECCION_CANDIDATO = NULLIF(LTRIM(RTRIM(DIRECCION)), ''),
			@ES_JUBILADO = ISNULL(ES_JUBILADO, 0),
			@POSEE_DISCAPACIDAD = ISNULL(POSEE_DISCAPACIDAD, 0),
			@TIPO_DISCAPACIDAD = NULLIF(LTRIM(RTRIM(TIPO_DISCAPACIDAD)), ''),
			@IGLESIA = NULLIF(LTRIM(RTRIM(IGLESIA)), ''),
			@FOTO_URL = NULLIF(LTRIM(RTRIM(FOTO_URL)), ''),
			@EMERGENCIA_NOMBRE = NULLIF(LTRIM(RTRIM(EMERGENCIA_NOMBRE)), ''),
			@EMERGENCIA_PARENTESCO = NULLIF(LTRIM(RTRIM(EMERGENCIA_PARENTESCO)), ''),
			@EMERGENCIA_TELEFONO = NULLIF(LTRIM(RTRIM(EMERGENCIA_TELEFONO)), '')
		FROM dbo.SC_PERSONA_DATOS
		WHERE CORR_EMPRESA = @CORR_EMPRESA
		  AND CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;

		-- =====================================================================
		-- 3.1. VALIDACIÓN Y FORMATEO DE DUI (EXACTAMENTE 9 DÍGITOS NUMÉRICOS)
		-- =====================================================================
		SET @DUI_DIGITOS = REPLACE(REPLACE(ISNULL(@DUI_ORIGINAL, ''), '-', ''), ' ', '');

		IF @DUI_ORIGINAL IS NULL OR @DUI_DIGITOS = ''
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30009,
			       @SYS_MENSAJE_ERROR = N'El candidato no tiene un número de DUI registrado en su expediente.';
			GOTO SALIDA;
		END;

		-- Validar que contenga únicamente números y exactamente 9 dígitos
		IF @DUI_DIGITOS LIKE '%[^0-9]%' OR LEN(@DUI_DIGITOS) <> 9
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30010,
			       @SYS_MENSAJE_ERROR = CONCAT(N'El número de DUI no es válido ("', @DUI_ORIGINAL, N'"). Debe contener exactamente 9 dígitos numéricos.');
			GOTO SALIDA;
		END;

		-- Formatear siempre con el guion salvadoreño (8 dígitos - 1 verificador)
		SET @DUI_FORMATEADO = SUBSTRING(@DUI_DIGITOS, 1, 8) + '-' + SUBSTRING(@DUI_DIGITOS, 9, 1);

		-- =====================================================================
		-- INICIO DE TRANSACCIÓN ATÓMICA
		-- =====================================================================
		BEGIN TRANSACTION;

		-- =====================================================================
		-- 4. DETERMINAR SI EXISTE GEN_PERSONA (POR DUI) O CREAR UNO NUEVO
		-- =====================================================================
		SELECT TOP 1 @CORR_PERSONA = D.CORR_PERSONA
		FROM dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD AS D
		WHERE D.CORR_EMPRESA = @CORR_EMPRESA
		  AND D.CORR_TIPO_DOCUMENTO_IDENTIDAD = 1 -- DUI
		  AND REPLACE(REPLACE(D.VALOR_DOCUMENTO, '-', ''), ' ', '') = @DUI_DIGITOS;

		IF @CORR_PERSONA IS NOT NULL
		BEGIN
			-- Ya existía la persona; actualizar datos en GEN_PERSONA_NATURAL
			UPDATE dbo.GEN_PERSONA_NATURAL
			SET
				PRIMER_NOMBRE = ISNULL(@NOMBRE1, PRIMER_NOMBRE),
				SEGUNDO_NOMBRE = @NOMBRE2,
				PRIMER_APELLIDO = ISNULL(@APELLIDO1, PRIMER_APELLIDO),
				SEGUNDO_APELLIDO = @APELLIDO2,
				FECHA_NACIMIENTO = ISNULL(@FECHA_NACIMIENTO, FECHA_NACIMIENTO),
				EDAD = ISNULL(@EDAD, EDAD),
				ESTADO_CIVIL = ISNULL(@ESTADO_CIVIL, ESTADO_CIVIL),
				NACIONALIDAD = ISNULL(@NACIONALIDAD, NACIONALIDAD),
				ES_JUBILADO = @ES_JUBILADO,
				POSEE_DISCAPACIDAD = @POSEE_DISCAPACIDAD,
				TIPO_DISCAPACIDAD = @TIPO_DISCAPACIDAD,
				IGLESIA_CONGREGA = ISNULL(@IGLESIA, IGLESIA_CONGREGA),
				FOTO_URL = ISNULL(@FOTO_URL, FOTO_URL),
				USUARIO_ACTU = @SYS_LOGIN_USUARIO,
				ESTACION_ACTU = @SYS_ESTACION,
				FECHA_ACTU = @FECHA_AUD
			WHERE CORR_PERSONA = @CORR_PERSONA;
		END
		ELSE
		BEGIN
			-- Generar nuevo CORR_PERSONA
			SELECT @CORR_PERSONA = ISNULL(MAX(CORR_PERSONA), 0) + 1
			FROM dbo.GEN_PERSONA WITH (UPDLOCK, HOLDLOCK);

			SET @CODIGO_PERSONA = CONVERT(VARCHAR(20), @CORR_PERSONA);

			INSERT INTO dbo.GEN_PERSONA
			(
				CORR_PERSONA, CODIGO_PERSONA, ACTIVO_PERSONA,
				USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
			)
			VALUES
			(
				@CORR_PERSONA, @CODIGO_PERSONA, 1,
				@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
			);

			INSERT INTO dbo.GEN_EMPRESA_PERSONA
			(
				CORR_EMPRESA, CORR_PERSONA,
				USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
			)
			VALUES
			(
				@CORR_EMPRESA, @CORR_PERSONA,
				@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
			);

			SELECT @CORR_PERSONA_NATURAL = ISNULL(MAX(CORR_PERSONA_NATURAL), 0) + 1
			FROM dbo.GEN_PERSONA_NATURAL WITH (UPDLOCK, HOLDLOCK);

			-- Omitir NOMBRE_COMPLETO (columna calculada)
			INSERT INTO dbo.GEN_PERSONA_NATURAL
			(
				CORR_PERSONA, CORR_PERSONA_NATURAL,
				PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO,
				FOTO_URL, ESTADO_CIVIL, NACIONALIDAD, EDAD, FECHA_NACIMIENTO,
				ES_JUBILADO, POSEE_DISCAPACIDAD, TIPO_DISCAPACIDAD,
				IGLESIA_CONGREGA, DOMICILIADO,
				USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
			)
			VALUES
			(
				@CORR_PERSONA, @CORR_PERSONA_NATURAL,
				@NOMBRE1, @NOMBRE2, @APELLIDO1, @APELLIDO2,
				@FOTO_URL, @ESTADO_CIVIL, @NACIONALIDAD, @EDAD, @FECHA_NACIMIENTO,
				@ES_JUBILADO, @POSEE_DISCAPACIDAD, @TIPO_DISCAPACIDAD,
				@IGLESIA, 'SI',
				@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
			);
		END;

		-- =====================================================================
		-- 5. MIGRAR DOCUMENTOS DE IDENTIDAD (DUI, ISSS, NUP, AFP, PASAPORTE, LICENCIA)
		-- =====================================================================
		-- 5.1 DUI (CORR_TIPO_DOCUMENTO_IDENTIDAD = 1) con guion garantizado (########-#)
		IF EXISTS (
			SELECT 1 FROM dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA AND CORR_TIPO_DOCUMENTO_IDENTIDAD = 1
		)
		BEGIN
			UPDATE dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
			SET VALOR_DOCUMENTO = @DUI_FORMATEADO,
			    USUARIO_ACTU = @SYS_LOGIN_USUARIO,
			    ESTACION_ACTU = @SYS_ESTACION,
			    FECHA_ACTU = @FECHA_AUD
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA AND CORR_TIPO_DOCUMENTO_IDENTIDAD = 1;
		END
		ELSE
		BEGIN
			INSERT INTO dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
			(CORR_EMPRESA, CORR_PERSONA, CORR_TIPO_DOCUMENTO_IDENTIDAD, VALOR_DOCUMENTO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU)
			VALUES (@CORR_EMPRESA, @CORR_PERSONA, 1, @DUI_FORMATEADO, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD);
		END;

		-- 5.2 ISSS (CORR_TIPO_DOCUMENTO_IDENTIDAD = 4)
		IF @ISSS_CANDIDATO IS NOT NULL
		BEGIN
			IF EXISTS (
				SELECT 1 FROM dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA AND CORR_TIPO_DOCUMENTO_IDENTIDAD = 4
			)
			BEGIN
				UPDATE dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
				SET VALOR_DOCUMENTO = @ISSS_CANDIDATO,
				    USUARIO_ACTU = @SYS_LOGIN_USUARIO,
				    ESTACION_ACTU = @SYS_ESTACION,
				    FECHA_ACTU = @FECHA_AUD
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA AND CORR_TIPO_DOCUMENTO_IDENTIDAD = 4;
			END
			ELSE
			BEGIN
				INSERT INTO dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
				(CORR_EMPRESA, CORR_PERSONA, CORR_TIPO_DOCUMENTO_IDENTIDAD, VALOR_DOCUMENTO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU)
				VALUES (@CORR_EMPRESA, @CORR_PERSONA, 4, @ISSS_CANDIDATO, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD);
			END;
		END;

		-- 5.3 NUP (CORR_TIPO_DOCUMENTO_IDENTIDAD = 6): se guarda el número de afiliación / NUP si el candidato lo tiene
		IF @AFP_CANDIDATO IS NOT NULL
		BEGIN
			IF EXISTS (
				SELECT 1 FROM dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA AND CORR_TIPO_DOCUMENTO_IDENTIDAD = 6
			)
			BEGIN
				UPDATE dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
				SET VALOR_DOCUMENTO = @AFP_CANDIDATO,
				    USUARIO_ACTU = @SYS_LOGIN_USUARIO,
				    ESTACION_ACTU = @SYS_ESTACION,
				    FECHA_ACTU = @FECHA_AUD
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA AND CORR_TIPO_DOCUMENTO_IDENTIDAD = 6;
			END
			ELSE
			BEGIN
				INSERT INTO dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
				(CORR_EMPRESA, CORR_PERSONA, CORR_TIPO_DOCUMENTO_IDENTIDAD, VALOR_DOCUMENTO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU)
				VALUES (@CORR_EMPRESA, @CORR_PERSONA, 6, @AFP_CANDIDATO, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD);
			END;
		END;

		-- 5.4 AFP (CORR_TIPO_DOCUMENTO_IDENTIDAD = 7): se guarda el DUI formateado en el campo de AFP (para que aparezcan ambos)
		IF @DUI_FORMATEADO IS NOT NULL
		BEGIN
			IF EXISTS (
				SELECT 1 FROM dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA AND CORR_TIPO_DOCUMENTO_IDENTIDAD = 7
			)
			BEGIN
				UPDATE dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
				SET VALOR_DOCUMENTO = @DUI_FORMATEADO,
				    USUARIO_ACTU = @SYS_LOGIN_USUARIO,
				    ESTACION_ACTU = @SYS_ESTACION,
				    FECHA_ACTU = @FECHA_AUD
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA AND CORR_TIPO_DOCUMENTO_IDENTIDAD = 7;
			END
			ELSE
			BEGIN
				INSERT INTO dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
				(CORR_EMPRESA, CORR_PERSONA, CORR_TIPO_DOCUMENTO_IDENTIDAD, VALOR_DOCUMENTO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU)
				VALUES (@CORR_EMPRESA, @CORR_PERSONA, 7, @DUI_FORMATEADO, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD);
			END;
		END;

		IF @PASAPORTE_CANDIDATO IS NOT NULL AND NOT EXISTS (
			SELECT 1 FROM dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA AND CORR_TIPO_DOCUMENTO_IDENTIDAD = 9
		)
		BEGIN
			INSERT INTO dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
			(CORR_EMPRESA, CORR_PERSONA, CORR_TIPO_DOCUMENTO_IDENTIDAD, VALOR_DOCUMENTO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU)
			VALUES (@CORR_EMPRESA, @CORR_PERSONA, 9, @PASAPORTE_CANDIDATO, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD);
		END;

		IF @LICENCIA_CANDIDATO IS NOT NULL AND NOT EXISTS (
			SELECT 1 FROM dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA AND CORR_TIPO_DOCUMENTO_IDENTIDAD = 10
		)
		BEGIN
			INSERT INTO dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD
			(CORR_EMPRESA, CORR_PERSONA, CORR_TIPO_DOCUMENTO_IDENTIDAD, VALOR_DOCUMENTO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU)
			VALUES (@CORR_EMPRESA, @CORR_PERSONA, 10, @LICENCIA_CANDIDATO, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD);
		END;

		-- =====================================================================
		-- 6. MIGRAR CONTACTOS (CORREO, CELULAR, TELÉFONO)
		-- =====================================================================
		DECLARE @MAX_CONTACTO INT = ISNULL((SELECT MAX(CORR_CONTACTO) FROM dbo.GEN_PERSONA_CONTACTO WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA), 0);

		IF @CELULAR_CANDIDATO IS NOT NULL
		BEGIN
			SET @MAX_CONTACTO = @MAX_CONTACTO + 1;
			INSERT INTO dbo.GEN_PERSONA_CONTACTO
			(CORR_EMPRESA, CORR_PERSONA, CORR_CONTACTO, VALOR_CONTACTO, ACTIVO_CONTACTO, CORR_TIPO_CONTACTO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU)
			VALUES (@CORR_EMPRESA, @CORR_PERSONA, @MAX_CONTACTO, @CELULAR_CANDIDATO, 1, 1, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD);
		END;

		IF @TELEFONO_CANDIDATO IS NOT NULL AND @TELEFONO_CANDIDATO <> ISNULL(@CELULAR_CANDIDATO, '')
		BEGIN
			SET @MAX_CONTACTO = @MAX_CONTACTO + 1;
			INSERT INTO dbo.GEN_PERSONA_CONTACTO
			(CORR_EMPRESA, CORR_PERSONA, CORR_CONTACTO, VALOR_CONTACTO, ACTIVO_CONTACTO, CORR_TIPO_CONTACTO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU)
			VALUES (@CORR_EMPRESA, @CORR_PERSONA, @MAX_CONTACTO, @TELEFONO_CANDIDATO, 1, 1, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD);
		END;

		IF @CORREO_CANDIDATO IS NOT NULL
		BEGIN
			SET @MAX_CONTACTO = @MAX_CONTACTO + 1;
			INSERT INTO dbo.GEN_PERSONA_CONTACTO
			(CORR_EMPRESA, CORR_PERSONA, CORR_CONTACTO, VALOR_CONTACTO, ACTIVO_CONTACTO, CORR_TIPO_CONTACTO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU)
			VALUES (@CORR_EMPRESA, @CORR_PERSONA, @MAX_CONTACTO, @CORREO_CANDIDATO, 1, 3, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD);
		END;

		-- =====================================================================
		-- 7. MIGRAR DOMICILIO
		-- =====================================================================
		IF @DIRECCION_CANDIDATO IS NOT NULL
		BEGIN
			DECLARE @MAX_DOMICILIO INT = ISNULL((SELECT MAX(CORR_DOMICILIO) FROM dbo.GEN_PERSONA_DOMICILIO WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA), 0) + 1;

			INSERT INTO dbo.GEN_PERSONA_DOMICILIO
			(CORR_EMPRESA, CORR_PERSONA, CORR_DOMICILIO, DIRECCION, ACTIVO_DOMICILIO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU)
			VALUES (@CORR_EMPRESA, @CORR_PERSONA, @MAX_DOMICILIO, LEFT(@DIRECCION_CANDIDATO, 255), 1, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD);
		END;

		-- =====================================================================
		-- 8. MIGRAR CONTACTO DE EMERGENCIA
		-- =====================================================================
		IF @EMERGENCIA_NOMBRE IS NOT NULL
		BEGIN
			DECLARE @MAX_PARENTESCO_CONT INT = ISNULL((SELECT MAX(CORR_PARENTESCO_CONTACTO) FROM dbo.GEN_PERSONA_PARENTESCO_CONTACTO WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA), 0) + 1;

			INSERT INTO dbo.GEN_PERSONA_PARENTESCO_CONTACTO
			(
				CORR_EMPRESA, CORR_PERSONA, CORR_PARENTESCO_CONTACTO,
				NOMBRE_COMPLETO, VALOR_CONTACTO, PARENTESCO_CONTACTO_EMERGENCIA, ACTIVO_PARENTESCO_CONTACTO,
				USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
			)
			VALUES
			(
				@CORR_EMPRESA, @CORR_PERSONA, @MAX_PARENTESCO_CONT,
				LEFT(@EMERGENCIA_NOMBRE, 100), @EMERGENCIA_TELEFONO, 1, 1,
				@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
			);
		END;

		-- =====================================================================
		-- 9. MIGRAR FORMACIÓN ACADÉMICA (Omitiendo PERIODO_* calculadas)
		-- =====================================================================
		DECLARE @MAX_FORMACION INT = ISNULL((SELECT MAX(CORR_FORMACION_ACADEMICA) FROM dbo.GEN_PERSONA_FORMACION_ACADEMICA WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA), 0);

		INSERT INTO dbo.GEN_PERSONA_FORMACION_ACADEMICA
		(
			CORR_EMPRESA, CORR_PERSONA, CORR_FORMACION_ACADEMICA,
			TITULO, CENTRO_EDUCATIVO, NIVEL, DESDE, HASTA,
			USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
		)
		SELECT
			@CORR_EMPRESA,
			@CORR_PERSONA,
			@MAX_FORMACION + ROW_NUMBER() OVER (ORDER BY E.CORR_ESTUDIO),
			LEFT(ISNULL(E.TITULO, 'SIN TITULO'), 100),
			LEFT(E.INSTITUCION, 150),
			LEFT(E.NIVEL, 100),
			E.DESDE,
			E.HASTA,
			@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
		FROM dbo.SC_PERSONA_ESTUDIO AS E
		WHERE E.CORR_EMPRESA = @CORR_EMPRESA
		  AND E.CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;

		-- =====================================================================
		-- 10. MIGRAR EXPERIENCIA LABORAL (Omitiendo PERIODO_* calculadas)
		-- =====================================================================
		DECLARE @MAX_EXP INT = ISNULL((SELECT MAX(CORR_EXPERIENCIA_LABORAL) FROM dbo.GEN_PERSONA_EXPERIENCIA_LABORAL WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA), 0);

		INSERT INTO dbo.GEN_PERSONA_EXPERIENCIA_LABORAL
		(
			CORR_EMPRESA, CORR_PERSONA, CORR_EXPERIENCIA_LABORAL,
			LUGAR_TRABAJO, CARGO_DESEMPENADO, TELEFONO, JEFE_INMEDIATO,
			SALARIO_INICIAL, SALARIO_FINAL, FECHA_INICIO, FECHA_FIN, MOTIVO_SALIDA,
			USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
		)
		SELECT
			@CORR_EMPRESA,
			@CORR_PERSONA,
			@MAX_EXP + ROW_NUMBER() OVER (ORDER BY X.CORR_EXPERIENCIA_LABORAL),
			LEFT(X.EMPRESA, 150),
			LEFT(X.CARGO, 150),
			LEFT(X.TELEFONO, 25),
			LEFT(X.JEFE_INMEDIATO, 100),
			X.SALARIO_INICIAL,
			X.SALARIO_FINAL,
			X.FECHA_INICIO,
			X.FECHA_FIN,
			LEFT(X.MOTIVO_SALIDA, 500),
			@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
		FROM dbo.SC_PERSONA_EXPERIENCIA_LABORAL AS X
		WHERE X.CORR_EMPRESA = @CORR_EMPRESA
		  AND X.CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;

		-- =====================================================================
		-- 11. MIGRAR COMPETENCIAS / HABILIDADES (Homologando CHECK NIVEL_DOMINIO)
		-- =====================================================================
		DECLARE @MAX_COMP INT = ISNULL((SELECT MAX(CORR_COMPETENCIA) FROM dbo.GEN_PERSONA_COMPETENCIA WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA), 0);

		INSERT INTO dbo.GEN_PERSONA_COMPETENCIA
		(
			CORR_EMPRESA, CORR_PERSONA, CORR_COMPETENCIA,
			NOMBRE_COMPETENCIA, NIVEL_DOMINIO,
			USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
		)
		SELECT
			@CORR_EMPRESA,
			@CORR_PERSONA,
			@MAX_COMP + ROW_NUMBER() OVER (ORDER BY C.CORR_COMPETENCIA_TECNICA),
			LEFT(C.HERRAMIENTA, 100),
			CASE
				WHEN UPPER(LTRIM(RTRIM(C.NIVEL))) LIKE '%AVANZ%' THEN 'AVANZADO'
				WHEN UPPER(LTRIM(RTRIM(C.NIVEL))) LIKE '%INTERM%' THEN 'INTERMEDIO'
				ELSE 'BASICO'
			END,
			@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
		FROM dbo.SC_PERSONA_COMPETENCIAS_TECNICAS AS C
		WHERE C.CORR_EMPRESA = @CORR_EMPRESA
		  AND C.CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;

		-- =====================================================================
		-- 12. MIGRAR IDIOMAS (Homologando CHECK NIVEL_DOMINIO)
		-- =====================================================================
		DECLARE @MAX_IDIOMA INT = ISNULL((SELECT MAX(CORR_IDIOMA) FROM dbo.GEN_PERSONA_IDIOMAS WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA), 0);

		INSERT INTO dbo.GEN_PERSONA_IDIOMAS
		(
			CORR_EMPRESA, CORR_PERSONA, CORR_IDIOMA,
			NOMBRE_IDIOMA, NIVEL_DOMINIO,
			USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
		)
		SELECT
			@CORR_EMPRESA,
			@CORR_PERSONA,
			@MAX_IDIOMA + ROW_NUMBER() OVER (ORDER BY I.CORR_IDIOMA),
			LEFT(I.IDIOMA, 100),
			CASE
				WHEN UPPER(LTRIM(RTRIM(I.NIVEL))) LIKE '%AVANZ%' THEN 'AVANZADO'
				WHEN UPPER(LTRIM(RTRIM(I.NIVEL))) LIKE '%INTERM%' THEN 'INTERMEDIO'
				ELSE 'BASICO'
			END,
			@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
		FROM dbo.SC_PERSONA_IDIOMAS AS I
		WHERE I.CORR_EMPRESA = @CORR_EMPRESA
		  AND I.CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;

		-- =====================================================================
		-- 13. MIGRAR FAMILIARES, FAMILIARES EN UEES E HIJOS
		-- =====================================================================
		DECLARE @MAX_FAM INT = ISNULL((SELECT MAX(CORR_FAMILIAR) FROM dbo.GEN_PERSONA_FAMILIAR WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA), 0);

		INSERT INTO dbo.GEN_PERSONA_FAMILIAR
		(
			CORR_EMPRESA, CORR_PERSONA, CORR_FAMILIAR,
			NOMBRE_COMPLETO, DOMICILIO, FECHA_NACIMIENTO, OCUPACION,
			USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
		)
		SELECT
			@CORR_EMPRESA,
			@CORR_PERSONA,
			@MAX_FAM + ROW_NUMBER() OVER (ORDER BY F.CORR_FAMILIAR),
			LEFT(F.NOMBRE, 100),
			LEFT(F.DOMICILIO, 255),
			F.FECHA_NACIMIENTO,
			LEFT(F.OCUPACION, 150),
			@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
		FROM dbo.SC_PERSONA_FAMILIAR AS F
		WHERE F.CORR_EMPRESA = @CORR_EMPRESA
		  AND F.CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;

		DECLARE @MAX_FAM_UEES INT = ISNULL((SELECT MAX(CORR_FAMILIAR_UEES) FROM dbo.GEN_PERSONA_FAMILIAR_UEES WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA), 0);

		INSERT INTO dbo.GEN_PERSONA_FAMILIAR_UEES
		(
			CORR_EMPRESA, CORR_PERSONA, CORR_FAMILIAR_UEES,
			NOMBRE_COMPLETO, TELEFONO, LUGAR_TRABAJO,
			USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
		)
		SELECT
			@CORR_EMPRESA,
			@CORR_PERSONA,
			@MAX_FAM_UEES + ROW_NUMBER() OVER (ORDER BY FU.CORR_FAMILIAR_UEES),
			LEFT(FU.NOMBRE, 100),
			LEFT(FU.TELEFONO, 25),
			LEFT(FU.UNIDAD, 150),
			@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
		FROM dbo.SC_PERSONA_FAMILIAR_UEES AS FU
		WHERE FU.CORR_EMPRESA = @CORR_EMPRESA
		  AND FU.CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;

		DECLARE @MAX_HIJO INT = ISNULL((SELECT MAX(CORR_HIJO) FROM dbo.GEN_PERSONA_HIJOS WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA = @CORR_PERSONA), 0);

		INSERT INTO dbo.GEN_PERSONA_HIJOS
		(
			CORR_EMPRESA, CORR_PERSONA, CORR_HIJO,
			NOMBRE_COMPLETO, EDAD, SEXO, FECHA_NACIMIENTO,
			USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
		)
		SELECT
			@CORR_EMPRESA,
			@CORR_PERSONA,
			@MAX_HIJO + ROW_NUMBER() OVER (ORDER BY H.CORR_HIJO),
			LEFT(H.NOMBRE, 100),
			H.EDAD,
			CASE
				WHEN UPPER(LTRIM(RTRIM(H.SEXO))) IN ('FEMENINO', 'F') THEN 'FEMENINO'
				WHEN UPPER(LTRIM(RTRIM(H.SEXO))) IN ('MASCULINO', 'M') THEN 'MASCULINO'
				ELSE NULL
			END,
			H.FECHA_NACIMIENTO,
			@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
		FROM dbo.SC_PERSONA_HIJOS AS H
		WHERE H.CORR_EMPRESA = @CORR_EMPRESA
		  AND H.CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;

		-- =====================================================================
		-- 14. CREAR EMPLEADO (GEN_EMPLEADO)
		-- =====================================================================
		SELECT @CORR_EMPLEADO = ISNULL(MAX(CORR_EMPLEADO), 0) + 1
		FROM dbo.GEN_EMPLEADO WITH (UPDLOCK, HOLDLOCK)
		WHERE CORR_EMPRESA = @CORR_EMPRESA;

		SET @CODIGO_EMPLEADO_NUEVO = CONVERT(VARCHAR(50), @CORR_EMPLEADO);

		DECLARE @CORR_AFP_EMPLEADO INT = NULL;
		IF @NOMBRE_AFP_CANDIDATO IS NOT NULL
		BEGIN
			SELECT TOP 1 @CORR_AFP_EMPLEADO = CORR_AFP
			FROM dbo.PLA_AFP
			WHERE ACTIVO_AFP = 1
			  AND (
				@NOMBRE_AFP_CANDIDATO LIKE '%' + NOMBRE_CORTO_AFP + '%'
				OR @NOMBRE_AFP_CANDIDATO LIKE '%' + NOMBRE_AFP + '%'
			  );
		END;

		INSERT INTO dbo.GEN_EMPLEADO
		(
			CORR_EMPRESA, CORR_EMPLEADO, CORR_PERSONA, CODIGO_EMPLEADO,
			CORR_AFP,
			FECHA_INGRESO, ACTIVO_EMPLEADO,
			USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
		)
		VALUES
		(
			@CORR_EMPRESA, @CORR_EMPLEADO, @CORR_PERSONA, @CODIGO_EMPLEADO_NUEVO,
			@CORR_AFP_EMPLEADO,
			@FECHA_INGRESO, 1,
			@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
		);

		-- =====================================================================
		-- 15. ASIGNAR PUESTO Y CONDICIONES (GEN_EMPLEADO_PUESTO)
		-- =====================================================================
		IF @CORR_UNIDAD_PROPUESTA IS NOT NULL AND @CORR_PUESTO_PROPUESTO IS NOT NULL
		BEGIN
			INSERT INTO dbo.GEN_EMPLEADO_PUESTO
			(
				CORR_EMPRESA, CORR_EMPLEADO, CORR_UNIDAD, CORR_PUESTO,
				FECHA_INGRESO, SUELDO, HORARIO_LABORAL, CORR_TIPO_CONTRATACION, CORR_TIPO_MODALIDAD,
				USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
			)
			VALUES
			(
				@CORR_EMPRESA, @CORR_EMPLEADO, @CORR_UNIDAD_PROPUESTA, @CORR_PUESTO_PROPUESTO,
				@FECHA_INGRESO, @SALARIO_PROPUESTO, LEFT(@HORARIO_PROPUESTO, 300),
				ISNULL(@CORR_TIPO_CONTRATACION, CASE WHEN @TIPO_MOVIMIENTO = 'EVENTUAL' THEN 2 ELSE 1 END),
				@CORR_TIPO_MODALIDAD_PROPUESTA,
				@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD, @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
			);
		END;

		-- =====================================================================
		-- 16. ENLAZAR EMPLEADO A SC_MOVIMIENTO_PERSONAL Y REGISTRAR BITÁCORA
		-- =====================================================================
		UPDATE dbo.SC_MOVIMIENTO_PERSONAL
		SET
			CORR_EMPLEADO = @CORR_EMPLEADO,
			USUARIO_ACTU = @SYS_LOGIN_USUARIO,
			ESTACION_ACTU = @SYS_ESTACION,
			FECHA_ACTU = @FECHA_AUD
		WHERE CORR_EMPRESA = @CORR_EMPRESA
		  AND CORR_MOVIMIENTO_PERSONAL = @CORR_MOVIMIENTO_PERSONAL;

		INSERT INTO dbo.SC_MOVIMIENTO_PERSONAL_BITACORA
		(
			CORR_EMPRESA, CORR_MOVIMIENTO_PERSONAL, LOGIN_SISTEMA,
			ESTADO_DESTINO, COMENTARIO, FECHA_ACCION,
			USUARIO_CREA, ESTACION_CREA, FECHA_CREA
		)
		VALUES
		(
			@CORR_EMPRESA, @CORR_MOVIMIENTO_PERSONAL, @SYS_LOGIN_USUARIO,
			N'Contratado',
			CONCAT(N'Se contrató al candidato. Se generó el Empleado #', @CORR_EMPLEADO, N' y Persona #', @CORR_PERSONA),
			@FECHA_AUD,
			@SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA_AUD
		);

		-- =====================================================================
		-- CIERRE EXITOSO DE TRANSACCIÓN
		-- =====================================================================
		COMMIT TRANSACTION;
		SET @SYS_FILAS_AFECTADAS = 1;
		SET @SYS_NUMERO_ERROR = 0;
		SET @SYS_MENSAJE_ERROR = N'';

	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		SELECT
			@SYS_NUMERO_ERROR = ERROR_NUMBER(),
			@SYS_MENSAJE_ERROR = ERROR_MESSAGE(),
			@SYS_FILAS_AFECTADAS = 0,
			@CORR_EMPLEADO = NULL,
			@CORR_PERSONA = NULL;
	END CATCH;

SALIDA:
	RETURN;
END;
GO
