SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[PRAL_IMPR_BALANCE_COMPROBACION]
( 
  @CORR_EMPRESA INT,
  @FECHA_FINAL DATE,
  @NIVEL SMALLINT = 0,
  @PARTIDA_CIERRE BIT=0,
  @PARTIDA_LIQUIDACION BIT=0,
  @CORR_MONEDA INT=NULL,
  @FOLIADO BIT=0,
  @NUMERO_FOLIO INT=0,
  @CUENTA_A_CERO BIT=0
)
AS	
	DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),
		CUENTA_MAYOR varchar(30),
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(18,2),
		CARGO_PERIODO DECIMAL(18,2),
		ABONO_PERIODO DECIMAL(18,2),
		SALDO_FINAL	DECIMAL(18,2)
	)
	
	DECLARE @CORR_MONEDA_LOCAL INT, @CORR_MONEDA_FORANEA INT	
	
	DECLARE @DESCRIPCION_MONEDA VARCHAR(255)
BEGIN
    
    SET NOCOUNT ON
    
    --SELECT @FECHA_FINAL=DATEADD(DAY,-1,@FECHA_FINAL)
	
    DECLARE @CUENTAS_SALDO TABLE(CORR_EMPRESA INT,CUENTA_MAYOR VARCHAR(30),SALDO_INICIAL DECIMAL(12,2),CARGO_PERIODO DECIMAL(12,2),ABONO_PERIODO DECIMAL(12,2),SALDO_FINAL DECIMAL(12,2))
	SELECT @CORR_MONEDA_LOCAL=CORR_MONEDA
	FROM CON_PARAMETRO
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	
	SET @CORR_MONEDA_FORANEA = NULL
	
	IF @CORR_MONEDA IS NULL
		SELECT @CORR_MONEDA=@CORR_MONEDA_LOCAL	
			
	IF @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL
	BEGIN
		 --Obtener el saldo de todas las cuentas de un nivel hasta antes de la fecha de consulta
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL 
	@CORR_EMPRESA,
		@FECHA_FINAL,
		0,--OPCION_CONSULTA= --Obtener el saldo de todas las cuentas de un nivel hasta antes de la fecha de consulta
		1,--MAYORIZA=Mayoriza los saldo
		'',
		'',	
		1, --Aplicar el debe o haber de la cuenta
		@PARTIDA_CIERRE, --Incluir partidas de cierre
		@PARTIDA_LIQUIDACION, --Incluir partidas de liquidación
		@NIVEL --Hasta el nivel indicado
	END ELSE
	IF @CORR_MONEDA=@CORR_MONEDA_FORANEA
	BEGIN
		 --Obtener el saldo de todas las cuentas de un nivel hasta antes de la fecha de consulta
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL_FORANEA
	@CORR_EMPRESA,
		@FECHA_FINAL,
		0,--OPCION_CONSULTA= --Obtener el saldo de todas las cuentas de un nivel hasta antes de la fecha de consulta
		1,--MAYORIZA=Mayoriza los saldo
		'',
		'',	
		1, --Aplicar el debe o haber de la cuenta
		@PARTIDA_CIERRE, --Incluir partidas de cierre
		@PARTIDA_LIQUIDACION, --Incluir partidas de liquidación
		@NIVEL --Hasta el nivel indicado
	END
	--Obteniendo en que moneda esta el balance general
	SET @DESCRIPCION_MONEDA = ''
	
	--Insertando las cuentas que sus hijos no tienen cero
	INSERT INTO @CUENTAS_SALDO
	(CORR_EMPRESA,CUENTA_MAYOR,SALDO_INICIAL,CARGO_PERIODO,ABONO_PERIODO,SALDO_FINAL)
	SELECT A.CORR_EMPRESA,A.CUENTA_MAYOR
		,SUM(CASE WHEN A.SALDO_INICIAL<>0 THEN 1 ELSE 0 END) SALDO_INICIAL
		,SUM(CASE WHEN A.CARGO_PERIODO<>0 THEN 1 ELSE 0 END) CARGO_PERIODO
		,SUM(CASE WHEN A.ABONO_PERIODO<>0 THEN 1 ELSE 0 END) ABONO_PERIODO
		,SUM(CASE WHEN A.SALDO_FINAL<>0 THEN 1 ELSE 0 END) SALDO_FINAL
	FROM @SALDO A
	GROUP BY A.CORR_EMPRESA,A.CUENTA_MAYOR
    SELECT @CORR_EMPRESA CORR_EMPRESA
    ,ISNULL(D.PREFIJO,'')+A.CUENTA_CONTABLE AS CUENTA_CONTABLE
    ,B.NOMBRE_CUENTA
    ,SUM(A.SALDO_INICIAL) SALDO_INICIAL
    ,SUM(A.CARGO_PERIODO) CARGO_PERIODO
    ,SUM(A.ABONO_PERIODO) ABONO_PERIODO
    ,SUM(A.SALDO_FINAL) SALDO_FINAL
    ,B.NIVEL
	,@DESCRIPCION_MONEDA DESCRIPCION_MONEDA	    
	,@FOLIADO FOLIADO
	,@NUMERO_FOLIO NUMERO_FOLIO
	FROM @SALDO A
	INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE	
	LEFT OUTER JOIN @CUENTAS_SALDO C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CUENTA_CONTABLE=C.CUENTA_MAYOR
	LEFT OUTER JOIN CON_PARAMETRO D ON  A.CORR_EMPRESA=D.CORR_EMPRESA
	WHERE (
		(C.SALDO_INICIAL<>0
		OR C.CARGO_PERIODO<>0
		OR C.ABONO_PERIODO<>0
		OR C.SALDO_FINAL<>0) --	Que las cuentas de mayor tengan al menos una cuenta de detalle diferente de cero
		OR (C.CUENTA_MAYOR IS NULL --Es el ultimo nivel seleccionado y que sea diferente a cero
		    AND (A.SALDO_INICIAL<>0
				OR A.CARGO_PERIODO<>0 
				OR A.ABONO_PERIODO<>0 
				OR A.SALDO_FINAL<>0) 
			)
		)
	OR @CUENTA_A_CERO=1 --Mostrar todas las cuentas aunque esten a cero
    GROUP BY A.CORR_EMPRESA, ISNULL(D.PREFIJO,'')
	,A.CUENTA_CONTABLE
    ,B.NOMBRE_CUENTA
    ,B.NIVEL    
	ORDER BY A.CORR_EMPRESA, A.CUENTA_CONTABLE

	SELECT A.CORR_EMPRESA 
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO

