SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_GEN_DOCUMENTO_FISICO]
(
	@TIPO_ACTUALIZA INT,
	@CORR_SUSCRIPCION int,
    @CORR_CONFI_PAIS int,
	@CORR_EMPRESA INT,
	@CORR_DOCUMENTO INT OUTPUT,
	@NOMBRE_DOCUMENTO VARCHAR(150),
	@DESCRIPCION_DOCUMENTO VARCHAR(255)='',
	@CORR_TIPO_DOCUMENTO INT,
	@RUTA_DOCUMENTO VARCHAR(255),
	@NOMBRE_ARCHIVO VARCHAR(50),	
	@USUARIO_CREA VARCHAR(30)=NULL,
	@FECHA_CREA DATETIME=NULL,
	@ESTACION_CREA VARCHAR(50)=NULL,
	@USUARIO_ACTU VARCHAR(30)=NULL,
	@FECHA_ACTU DATETIME=NULL,
	@ESTACION_ACTU VARCHAR(50)=NULL,
	@CODIGO_SUITE VARCHAR(30)='e-Admin',
	@CORR_DOCUMENTO_DOC INT=0,
	@CORR_CLIENTE INT = 0,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN	
	SET NOCOUNT ON	
	
	EXEC [e-AdminFE].dbo.PRAL_MTTO_GEN_DOCUMENTO_FISICO
		@TIPO_ACTUALIZA,
		@CORR_SUSCRIPCION,
		@CORR_CONFI_PAIS,
		@CORR_EMPRESA,
		@CORR_DOCUMENTO OUTPUT,
		@NOMBRE_DOCUMENTO,
		@DESCRIPCION_DOCUMENTO,
		@CORR_TIPO_DOCUMENTO,
		@RUTA_DOCUMENTO,
		@NOMBRE_ARCHIVO,	
		@USUARIO_CREA,
		@FECHA_CREA,
		@ESTACION_CREA,
		@USUARIO_ACTU,
		@FECHA_ACTU,
		@ESTACION_ACTU,
		@CODIGO_SUITE,
		@CORR_DOCUMENTO_DOC,
		@CORR_CLIENTE,
		@SYS_LOGIN_USUARIO,
		@SYS_ESTACION,
		@SYS_FILAS_AFECTADAS OUTPUT,
		@SYS_NUMERO_ERROR OUTPUT,
		@SYS_MENSAJE_ERROR OUTPUT

FINA:
END
GO
