SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================================================
-- Qué hace: Fachada del flujo Descriptor de Puesto
--   (CODIGO_OPCION = SC_DESCRIPTOR_PUESTO / proceso 102).
--   NO inserta ni actualiza el contenido del descriptor: la API hace
--   Insert/Update de SC_DESCRIPTOR_PUESTO; este SP solo mueve el flujo
--   y sincroniza CORR_ESTADO / NOMBRE_ESTADO en la tabla del negocio.
-- Cómo lo hace:
--   1) Valida que exista el descriptor (ya creado por la API).
--   2) Detecta contexto/modo: NUEVO / BORRADOR / EN_FLUJO / VIGENCIA.
--   3) Valida que @OPERACION (1..6) aplique a ese modo.
--   4) Resuelve CORR_ACCION en SEG_FLUJO_PASO_ACCION_ESTADO
--      (salvo que venga @CORR_ACCION como override).
--   5) Si NUEVO + ENVIAR(2): primero GUARDAR (crea instancia) y luego ENVIAR.
--   6) Llama dbo.EjecutarFlujoProceso (motor generico).
--   7) Actualiza SC_DESCRIPTOR_PUESTO.CORR_ESTADO y NOMBRE_ESTADO.
--   8) Devuelve outputs para que la API/SPA parchee en memoria.
--
-- Catalogo @OPERACION:
--   1=GUARDAR  2=ENVIAR  3=APROBAR  4=OBSERVAR  5=INACTIVAR  6=REACTIVAR
--   REACTIVAR: Inactivo -> Borrador (RETORNA; debe reautorizarse).
--
-- Unidad (@CORR_UNIDAD_DOCUMENTO):
--   Obligatoria solo en modo NUEVO. Se pasa tal cual al motor.
--   En ejecuciones posteriores puede ir NULL (el motor usa la instancia).
-- =============================================================================
CREATE PROCEDURE [dbo].[PRAL_MTTO_SC_DESCRIPTOR_PUESTO_AUTORIZA]
(
	@CORR_EMPRESA INT = 1,
	@CORR_DESCRIPTOR_PUESTO INT,
	@CORR_UNIDAD_DOCUMENTO INT = NULL,
	@OPERACION INT = NULL,
	@CORR_ACCION INT = NULL,
	@LOGIN_SISTEMA VARCHAR(30),
	@OBSERVACION NVARCHAR(MAX),
	@CORR_ESTADO INT OUTPUT,
	@MENSAJE_ERROR VARCHAR(500) OUTPUT,
	@CORR_ACCION_USADA INT = NULL OUTPUT,
	@CORR_PASO_ACTUAL INT = NULL OUTPUT,
	@MODO VARCHAR(20) = NULL OUTPUT,
	@NOMBRE_ESTADO VARCHAR(100) = NULL OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @CODIGO_OPCION VARCHAR(50) = 'SC_DESCRIPTOR_PUESTO'
	DECLARE @EMPRESA INT = ISNULL(@CORR_EMPRESA, 1)
	DECLARE @ID_TIPO_DOCUMENTO INT
	DECLARE @ID_FLUJO INT
	DECLARE @ID_INSTANCIA INT
	DECLARE @ID_PASO_ACTUAL INT
	DECLARE @ID_ESTADO_ACTUAL INT
	DECLARE @ID_ACCION INT = @CORR_ACCION
	DECLARE @V_OPERACION INT = @OPERACION
	DECLARE @NOM_OP VARCHAR(20)
	DECLARE @ESTADO_TMP INT
	DECLARE @ERROR_TMP VARCHAR(500)
	DECLARE @ES_ESTADO_INICIAL BIT = 0
	DECLARE @ES_NUEVO BIT = 0
	DECLARE @ES_BORRADOR BIT = 0
	DECLARE @ES_VIGENCIA BIT = 0
	DECLARE @V_MODO VARCHAR(20)
	DECLARE @ACCION_GUARDAR INT
	DECLARE @UNIDAD_DOC INT = @CORR_UNIDAD_DOCUMENTO
	DECLARE @NOMBRE_PASO VARCHAR(200)
	DECLARE @V_NOMBRE_ESTADO VARCHAR(100)
	DECLARE @EST_INACTIVO INT
	DECLARE @EST_ACTIVO INT
	DECLARE @EST_BORRADOR INT
	DECLARE @PASO_BORRADOR INT

	SET @CORR_ESTADO = NULL
	SET @MENSAJE_ERROR = NULL
	SET @CORR_ACCION_USADA = NULL
	SET @CORR_PASO_ACTUAL = NULL
	SET @MODO = NULL
	SET @NOMBRE_ESTADO = NULL

	-- ======================================================
	-- Qué hace: Validar entradas y que el descriptor ya exista (API).
	-- Cómo: RETURN -1 si falta documento/login/observacion
	--        o el descriptor no esta en SC_DESCRIPTOR_PUESTO.
	-- ======================================================
	IF @CORR_DESCRIPTOR_PUESTO IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'Debe indicar @CORR_DESCRIPTOR_PUESTO.'
		RETURN -1
	END

	IF NOT EXISTS (
		SELECT 1 FROM dbo.SC_DESCRIPTOR_PUESTO
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
	)
	BEGIN
		SET @MENSAJE_ERROR = 'No existe el descriptor CORR_DESCRIPTOR_PUESTO=' + CAST(@CORR_DESCRIPTOR_PUESTO AS VARCHAR) + '.'
		RETURN -1
	END

	IF @LOGIN_SISTEMA IS NULL OR LTRIM(RTRIM(@LOGIN_SISTEMA)) = ''
	BEGIN
		SET @MENSAJE_ERROR = 'Debe indicar @LOGIN_SISTEMA.'
		RETURN -1
	END

	IF @OBSERVACION IS NULL OR LTRIM(RTRIM(@OBSERVACION)) = ''
	BEGIN
		SET @MENSAJE_ERROR = 'El comentario (@OBSERVACION) es obligatorio.'
		RETURN -1
	END

	IF @ID_ACCION IS NULL AND @V_OPERACION IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'Indique @OPERACION (1=GUARDAR,2=ENVIAR,3=APROBAR,4=OBSERVAR,5=INACTIVAR,6=REACTIVAR) o @CORR_ACCION.'
		RETURN -1
	END

	IF @ID_ACCION IS NULL AND @V_OPERACION NOT IN (1, 2, 3, 4, 5, 6)
	BEGIN
		SET @MENSAJE_ERROR = 'Operacion invalida: ' + CAST(ISNULL(@V_OPERACION, -1) AS VARCHAR)
			+ '. Use 1=GUARDAR, 2=ENVIAR, 3=APROBAR, 4=OBSERVAR, 5=INACTIVAR, 6=REACTIVAR.'
		RETURN -5
	END

	SET @NOM_OP = CASE @V_OPERACION
		WHEN 1 THEN 'GUARDAR'
		WHEN 2 THEN 'ENVIAR'
		WHEN 3 THEN 'APROBAR'
		WHEN 4 THEN 'OBSERVAR'
		WHEN 5 THEN 'INACTIVAR'
		WHEN 6 THEN 'REACTIVAR'
		ELSE CAST(ISNULL(@V_OPERACION, 0) AS VARCHAR(10))
	END

	-- ======================================================
	-- Qué hace: Resolver tipo documento, flujo defecto y estados
	--           Activo/Inactivo/Borrador usados por INACTIVAR/REACTIVAR.
	-- Cómo: Lee SEG_FLUJO_TIPO_DOCUMENTO / PROCESO / ESTADO / PASO.
	-- ======================================================
	SELECT @ID_TIPO_DOCUMENTO = CORR_TIPO_DOCUMENTO
	FROM dbo.SEG_FLUJO_TIPO_DOCUMENTO
	WHERE CORR_EMPRESA = @EMPRESA AND CODIGO_OPCION = @CODIGO_OPCION AND ACTIVO = 1

	IF @ID_TIPO_DOCUMENTO IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'No existe tipo de documento activo para SC_DESCRIPTOR_PUESTO.'
		RETURN -2
	END

	SELECT TOP 1 @ID_FLUJO = CORR_FLUJO_PROCESO
	FROM dbo.SEG_FLUJO_PROCESO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND ACTIVO = 1 AND ES_DEFECTO = 1

	IF @ID_FLUJO IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'No hay flujo defecto activo para descriptor de puesto.'
		RETURN -3
	END

	SELECT @EST_ACTIVO = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND NOMBRE_ESTADO = N'Activo' AND ACTIVO = 1

	SELECT @EST_INACTIVO = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND NOMBRE_ESTADO = N'Inactivo' AND ACTIVO = 1

	SELECT @EST_BORRADOR = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND NOMBRE_ESTADO = N'Borrador' AND ACTIVO = 1

	SELECT @PASO_BORRADOR = CORR_PASO
	FROM dbo.SEG_FLUJO_PASO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
	  AND UPPER(NOMBRE_PASO) = 'BORRADOR'

	-- ======================================================
	-- Qué hace: Detectar modo NUEVO / BORRADOR / VIGENCIA / EN_FLUJO.
	-- Cómo: Sin instancia activa => NUEVO.
	--       Paso Vigencia => VIGENCIA.
	--       Estado inicial o MANTIENE en orden 1 => BORRADOR.
	--       Resto => EN_FLUJO.
	-- ======================================================
	SELECT @ID_INSTANCIA = CORR_INSTANCIA,
	       @ID_PASO_ACTUAL = CORR_PASO_ACTUAL,
	       @ID_ESTADO_ACTUAL = CORR_ESTADO_ACTUAL
	FROM dbo.SEG_FLUJO_INSTANCIA
	WHERE CORR_EMPRESA = @EMPRESA
	  AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND CORR_DOCUMENTO = @CORR_DESCRIPTOR_PUESTO
	  AND ACTIVO = 1

	IF @ID_INSTANCIA IS NULL
	BEGIN
		SET @ES_NUEVO = 1
		SET @V_MODO = 'NUEVO'
		SELECT TOP 1 @ID_PASO_ACTUAL = CORR_PASO
		FROM dbo.SEG_FLUJO_PASO
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
		ORDER BY ORDEN
	END
	ELSE
	BEGIN
		SELECT @ES_ESTADO_INICIAL = ISNULL(E.ES_INICIAL, 0),
		       @NOMBRE_PASO = P.NOMBRE_PASO
		FROM dbo.SEG_FLUJO_ESTADO E
		INNER JOIN dbo.SEG_FLUJO_PASO P
			ON P.CORR_EMPRESA = @EMPRESA AND P.CORR_PASO = @ID_PASO_ACTUAL
		WHERE E.CORR_EMPRESA = @EMPRESA AND E.CORR_ESTADO = @ID_ESTADO_ACTUAL

		IF UPPER(ISNULL(@NOMBRE_PASO, '')) = 'VIGENCIA'
		BEGIN
			SET @ES_VIGENCIA = 1
			SET @V_MODO = 'VIGENCIA'
		END
		ELSE IF @ES_ESTADO_INICIAL = 1
			OR EXISTS (
				SELECT 1
				FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO A
				INNER JOIN dbo.SEG_FLUJO_PASO P
					ON P.CORR_EMPRESA = A.CORR_EMPRESA AND P.CORR_PASO = A.CORR_PASO
				WHERE A.CORR_EMPRESA = @EMPRESA AND A.CORR_FLUJO_PROCESO = @ID_FLUJO
				  AND A.CORR_PASO = @ID_PASO_ACTUAL AND A.CORR_TIPO_MOVIMIENTO = 4
				  AND A.PERMITIDO = 1 AND A.ACTIVO = 1 AND P.ORDEN = 1
			)
		BEGIN
			SET @ES_BORRADOR = 1
			SET @V_MODO = 'BORRADOR'
		END
		ELSE
			SET @V_MODO = 'EN_FLUJO'
	END

	SET @MODO = @V_MODO
	SET @CORR_PASO_ACTUAL = @ID_PASO_ACTUAL

	IF @ID_PASO_ACTUAL IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'El flujo descriptor no tiene paso inicial configurado.'
		RETURN -4
	END

	-- ======================================================
	-- Qué hace: Validar que @OPERACION aplique al modo actual.
	-- Cómo: Solo si NO hay override @CORR_ACCION.
	-- ======================================================
	IF @V_OPERACION IS NOT NULL AND @ID_ACCION IS NULL
	BEGIN
		IF @V_OPERACION = 1 -- GUARDAR
		BEGIN
			IF @V_MODO NOT IN ('NUEVO', 'BORRADOR')
			BEGIN
				SET @MENSAJE_ERROR = 'GUARDAR(1) solo aplica en Borrador/NUEVO (modo actual: ' + @V_MODO + ').'
				RETURN -11
			END
			IF @ES_NUEVO = 1 AND @UNIDAD_DOC IS NULL
			BEGIN
				SET @MENSAJE_ERROR = 'Al crear (GUARDAR=1) debe enviar @CORR_UNIDAD_DOCUMENTO (el motor la guarda en la instancia).'
				RETURN -8
			END
		END
		ELSE IF @V_OPERACION = 2 -- ENVIAR
		BEGIN
			IF @V_MODO NOT IN ('NUEVO', 'BORRADOR')
			BEGIN
				SET @MENSAJE_ERROR = 'ENVIAR(2) solo aplica en Borrador/NUEVO. Modo actual: ' + @V_MODO + '.'
				RETURN -12
			END
			IF @ES_NUEVO = 1 AND @UNIDAD_DOC IS NULL
			BEGIN
				SET @MENSAJE_ERROR = 'Al crear y ENVIAR(2) debe enviar @CORR_UNIDAD_DOCUMENTO (el motor la guarda en la instancia).'
				RETURN -8
			END
		END
		ELSE IF @V_OPERACION IN (3, 4) -- APROBAR / OBSERVAR
		BEGIN
			IF @ES_NUEVO = 1
			BEGIN
				SET @MENSAJE_ERROR = 'No hay instancia. Primero GUARDAR(1) o ENVIAR(2).'
				RETURN -13
			END
			IF @ES_BORRADOR = 1 AND @V_OPERACION = 3
			BEGIN
				SET @MENSAJE_ERROR = 'En Borrador use ENVIAR(2), no APROBAR(3).'
				RETURN -14
			END
			IF @ES_VIGENCIA = 1
			BEGIN
				SET @MENSAJE_ERROR = 'En Vigencia use INACTIVAR(5) o REACTIVAR(6), no APROBAR/OBSERVAR.'
				RETURN -16
			END
		END
		ELSE IF @V_OPERACION IN (5, 6) -- INACTIVAR / REACTIVAR
		BEGIN
			IF @ES_VIGENCIA = 0
			BEGIN
				SET @MENSAJE_ERROR = 'INACTIVAR(5)/REACTIVAR(6) solo aplica en paso Vigencia (modo: ' + @V_MODO + ').'
				RETURN -17
			END
			-- REACTIVAR solo desde Inactivo: vuelve a Borrador para nueva autorizacion.
			IF @V_OPERACION = 6 AND @ID_ESTADO_ACTUAL <> @EST_INACTIVO
			BEGIN
				SET @MENSAJE_ERROR = 'REACTIVAR(6) solo aplica cuando el descriptor esta Inactivo.'
				RETURN -18
			END
			-- INACTIVAR solo desde Activo.
			IF @V_OPERACION = 5 AND @ID_ESTADO_ACTUAL <> @EST_ACTIVO
			BEGIN
				SET @MENSAJE_ERROR = 'INACTIVAR(5) solo aplica cuando el descriptor esta Activo.'
				RETURN -19
			END
		END
	END

	-- ======================================================
	-- Qué hace: Resolver CORR_ACCION (valor de @CORR_ACCION_USADA).
	-- Cómo: Override @CORR_ACCION o busqueda por operacion/movimiento.
	-- ======================================================
	IF @ID_ACCION IS NULL
	BEGIN
		IF @V_OPERACION = 1 -- GUARDAR = MANTIENE
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 4
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION ASC
		ELSE IF @V_OPERACION = 2 -- ENVIAR = AVANZA
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 1
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION DESC
		ELSE IF @V_OPERACION = 3 -- APROBAR = AVANZA
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 1
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION ASC
		ELSE IF @V_OPERACION = 4 -- OBSERVAR = RETORNA
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 2
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION ASC
		ELSE IF @V_OPERACION = 5 -- INACTIVAR
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 4
			  AND CORR_ESTADO_DESTINO = @EST_INACTIVO
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION ASC
		ELSE IF @V_OPERACION = 6 -- REACTIVAR = RETORNA a Borrador (reautorizar)
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 2
			  AND CORR_ESTADO_DESTINO = @EST_BORRADOR
			  AND (@PASO_BORRADOR IS NULL OR CORR_PASO_DESTINO = @PASO_BORRADOR)
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION ASC

		IF @ID_ACCION IS NULL
		BEGIN
			SET @MENSAJE_ERROR = 'No hay accion para operacion ' + @NOM_OP + '(' + CAST(@V_OPERACION AS VARCHAR) + ')'
				+ ' en paso ' + CAST(@ID_PASO_ACTUAL AS VARCHAR)
				+ ' (modo ' + @V_MODO + ').'
			RETURN -7
		END
	END

	SET @CORR_ACCION_USADA = @ID_ACCION

	-- ======================================================
	-- Qué hace: Si NUEVO + ENVIAR(2), crear instancia antes de avanzar.
	-- Cómo: GUARDAR (MANTIENE) interno y luego ENVIAR.
	-- ======================================================
	IF @ES_NUEVO = 1 AND @V_OPERACION = 2
	BEGIN
		SELECT TOP 1 @ACCION_GUARDAR = CORR_ACCION
		FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
		  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 4
		  AND PERMITIDO = 1 AND ACTIVO = 1
		ORDER BY CORR_ACCION ASC

		IF @ACCION_GUARDAR IS NULL SET @ACCION_GUARDAR = 1

		EXEC dbo.EjecutarFlujoProceso
			@i_CORR_EMPRESA = @EMPRESA,
			@i_CODIGO_OPCION = @CODIGO_OPCION,
			@i_idDocumento = @CORR_DESCRIPTOR_PUESTO,
			@i_idUnidadDocumento = @UNIDAD_DOC,
			@i_idAccion = @ACCION_GUARDAR,
			@i_login = @LOGIN_SISTEMA,
			@i_Observacion = @OBSERVACION,
			@o_idEstadoDocumento = @ESTADO_TMP OUTPUT,
			@o_Error = @ERROR_TMP OUTPUT

		IF @ERROR_TMP IS NOT NULL
		BEGIN
			SET @CORR_ESTADO = @ESTADO_TMP
			SET @MENSAJE_ERROR = 'Error al crear (GUARDAR) previo a ENVIAR: ' + @ERROR_TMP
			RETURN -9
		END

		IF @ESTADO_TMP IS NOT NULL
		BEGIN
			SELECT @V_NOMBRE_ESTADO = LEFT(NOMBRE_ESTADO, 50)
			FROM dbo.SEG_FLUJO_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_ESTADO = @ESTADO_TMP

			UPDATE dbo.SC_DESCRIPTOR_PUESTO
			SET CORR_ESTADO = @ESTADO_TMP,
				NOMBRE_ESTADO = @V_NOMBRE_ESTADO,
				USUARIO_ACTU = @LOGIN_SISTEMA,
				ESTACION_ACTU = HOST_NAME(),
				FECHA_ACTU = GETDATE()
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO
		END
	END

	-- ======================================================
	-- Qué hace: Ejecutar la operacion principal en el motor.
	-- Cómo: Pasa @ID_ACCION a EjecutarFlujoProceso.
	-- ======================================================
	EXEC dbo.EjecutarFlujoProceso
		@i_CORR_EMPRESA = @EMPRESA,
		@i_CODIGO_OPCION = @CODIGO_OPCION,
		@i_idDocumento = @CORR_DESCRIPTOR_PUESTO,
		@i_idUnidadDocumento = @UNIDAD_DOC,
		@i_idAccion = @ID_ACCION,
		@i_login = @LOGIN_SISTEMA,
		@i_Observacion = @OBSERVACION,
		@o_idEstadoDocumento = @CORR_ESTADO OUTPUT,
		@o_Error = @MENSAJE_ERROR OUTPUT

	IF @MENSAJE_ERROR IS NOT NULL
		RETURN -10

	-- ======================================================
	-- Qué hace: Sincronizar estado del descriptor y refrescar outputs.
	-- Cómo: Copia CORR_ESTADO + NOMBRE_ESTADO a SC_DESCRIPTOR_PUESTO.
	-- ======================================================
	IF @CORR_ESTADO IS NOT NULL
	BEGIN
		SELECT @V_NOMBRE_ESTADO = LEFT(NOMBRE_ESTADO, 50)
		FROM dbo.SEG_FLUJO_ESTADO
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_ESTADO = @CORR_ESTADO

		UPDATE dbo.SC_DESCRIPTOR_PUESTO
		SET CORR_ESTADO = @CORR_ESTADO,
			NOMBRE_ESTADO = @V_NOMBRE_ESTADO,
			USUARIO_ACTU = @LOGIN_SISTEMA,
			ESTACION_ACTU = HOST_NAME(),
			FECHA_ACTU = GETDATE()
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_DESCRIPTOR_PUESTO = @CORR_DESCRIPTOR_PUESTO

		SET @NOMBRE_ESTADO = @V_NOMBRE_ESTADO
	END

	SELECT @CORR_PASO_ACTUAL = CORR_PASO_ACTUAL
	FROM dbo.SEG_FLUJO_INSTANCIA
	WHERE CORR_EMPRESA = @EMPRESA
	  AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND CORR_DOCUMENTO = @CORR_DESCRIPTOR_PUESTO
	  AND ACTIVO = 1

	RETURN 0
END
GO
