SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_SEG_CONFIG_OPCION]
(
	@TIPO_ACTUALIZA INT,
	@CODIGO_SISTEMA varchar(30),
	@CODIGO_MENU varchar(10),
	@CODIGO_OPCION varchar(30) OUTPUT,
	@ORDEN_SISTEMA int,
	@ORDEN_MENU int,
	@ORDEN_OPCION int,
	@USUARIO_CREA varchar(30),
	@FECHA_CREA datetime,
	@ESTACION_CREA varchar(30),
	@USUARIO_ACTU varchar(30),
	@FECHA_ACTU datetime,
	@ESTACION_ACTU varchar(30),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN				
			SELECT @ORDEN_OPCION=ISNULL(MAX(ORDEN_OPCION),0)+1
			FROM SEG_CONFIG_OPCION
			WHERE CODIGO_SISTEMA=@CODIGO_SISTEMA
			AND CODIGO_MENU=@CODIGO_MENU			
			
			INSERT INTO SEG_CONFIG_OPCION
			(CODIGO_SISTEMA,CODIGO_MENU,CODIGO_OPCION,ORDEN_SISTEMA,ORDEN_MENU,ORDEN_OPCION,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU)
			VALUES
			(@CODIGO_SISTEMA,@CODIGO_MENU,@CODIGO_OPCION,@ORDEN_SISTEMA,@ORDEN_MENU,@ORDEN_OPCION,@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE SEG_CONFIG_OPCION SET
			ORDEN_SISTEMA=@ORDEN_SISTEMA,
			ORDEN_MENU=@ORDEN_MENU,
			ORDEN_OPCION=@ORDEN_OPCION,			
			USUARIO_ACTU=@USUARIO_ACTU,
			FECHA_ACTU=@FECHA_ACTU,
			ESTACION_ACTU=@ESTACION_ACTU
			WHERE CODIGO_SISTEMA=@CODIGO_SISTEMA
			AND CODIGO_MENU=@CODIGO_MENU
			AND CODIGO_OPCION=@CODIGO_OPCION
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM SEG_CONFIG_OPCION
			WHERE CODIGO_SISTEMA=@CODIGO_SISTEMA
			AND CODIGO_MENU=@CODIGO_MENU
			AND CODIGO_OPCION=@CODIGO_OPCION
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
