SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_COM_DOCUMENTO_TOTAL_NCR_NDB]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_DOCUMENTO int OUTPUT,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY 

			DECLARE @ESTADO_DOCUMENTO VARCHAR(2)
			SELECT @ESTADO_DOCUMENTO=A.ESTADO_DOCUMENTO
			FROM COM_DOCUMENTO A
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.MES_PERIODO=@MES_PERIODO
			AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO

			IF NOT @ESTADO_DOCUMENTO = 'DI'
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000, @SYS_FILAS_AFECTADAS=0, @SYS_MENSAJE_ERROR='Este documento no permite mas modificaciones.'
				GOTO FINA				
			END

		DECLARE @ANIO_PERIODO_DOC INT,
				@MES_PERIODO_DOC INT,
				@CORR_DOCUMENTO_DOC INT,
				@MONTO_INGRESO DECIMAL(18,6)

		DECLARE @PORCENTAJE DECIMAL(18,8)=0
		DECLARE @RUBROS TABLE(CORR_EMPRESA INT,ANIO_PERIODO INT,MES_PERIODO INT,CORR_DOCUMENTO INT,CORR_RUBRO INT,MONTO_RUBRO DECIMAL(18,6),ORDEN_TOTAL INT)
		DECLARE @EXISTENTES TABLE(ANIO_PERIODO_DOC INT, MES_PERIODO_DOC INT, CORR_DOCUMENTO_DOC INT, MONTO_INGRESO DECIMAL(18,4))

		--Obtener las facturas relacionadas...
		INSERT INTO @EXISTENTES
		SELECT ANIO_PERIODO_DOC, MES_PERIODO_DOC, CORR_DOCUMENTO_DOC, MONTO_INGRESO
		FROM COM_DOCUMENTO_DETA_DOC
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
	    AND CORR_DOCUMENTO=@CORR_DOCUMENTO		

		DELETE FROM COM_DOCUMENTO_TOTAL
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO

		WHILE EXISTS(SELECT 1 FROM @EXISTENTES)
		BEGIN
			SELECT TOP (1) @MONTO_INGRESO=MONTO_INGRESO,@ANIO_PERIODO_DOC=ANIO_PERIODO_DOC, @MES_PERIODO_DOC=MES_PERIODO_DOC,@CORR_DOCUMENTO_DOC=CORR_DOCUMENTO_DOC
			FROM @EXISTENTES

			SELECT @PORCENTAJE=dbo.DIVIDIR(@MONTO_INGRESO,MONTO_RUBRO)
			FROM V_COM_DOCUMENTO_TOTAL
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO_DOC
			AND MES_PERIODO=@MES_PERIODO_DOC
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO_DOC
			AND CLASE_RUBRO IN('VTO')

			INSERT INTO @RUBROS
			SELECT 
			@CORR_EMPRESA CORR_EMPRESA,
			@ANIO_PERIODO ANIO_PERIODO,
			@MES_PERIODO MES_PERIODO,
			@CORR_DOCUMENTO CORR_DOCUMENTO,
			A.CORR_RUBRO,
			ROUND(MONTO_RUBRO*(@PORCENTAJE),2) MONTO_RUBRO,
			A.ORDEN_TOTAL
			FROM COM_DOCUMENTO_TOTAL A
			INNER JOIN COM_DOCUMENTO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO_DOC
			AND A.MES_PERIODO=@MES_PERIODO_DOC
			AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO_DOC

			DELETE FROM @EXISTENTES WHERE ANIO_PERIODO_DOC=@ANIO_PERIODO_DOC AND MES_PERIODO_DOC=@MES_PERIODO_DOC AND CORR_DOCUMENTO_DOC=@CORR_DOCUMENTO_DOC 
		END

	   --Verficar si existe el rubro, si no existe se ingresa....
		MERGE COM_DOCUMENTO_TOTAL AS TARGET
		USING ( 
					SELECT A.CORR_EMPRESA,A.ANIO_PERIODO,A.MES_PERIODO,A.CORR_DOCUMENTO,A.CORR_RUBRO,A.ORDEN_TOTAL,SUM(A.MONTO_RUBRO) MONTO_RUBRO
					FROM @RUBROS A
					GROUP BY  A.CORR_EMPRESA,A.ANIO_PERIODO,A.MES_PERIODO,A.CORR_DOCUMENTO,A.CORR_RUBRO,A.ORDEN_TOTAL
				) AS SOURCE
		ON TARGET.CORR_EMPRESA=SOURCE.CORR_EMPRESA
		AND TARGET.ANIO_PERIODO=SOURCE.ANIO_PERIODO
		AND TARGET.MES_PERIODO=SOURCE.MES_PERIODO
		AND TARGET.CORR_DOCUMENTO=SOURCE.CORR_DOCUMENTO
		AND TARGET.CORR_RUBRO=SOURCE.CORR_RUBRO
		WHEN NOT MATCHED BY TARGET THEN	INSERT (CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,
			CORR_DOCUMENTO,CORR_RUBRO,MONTO_RUBRO,ORDEN_TOTAL)
			VALUES (SOURCE.CORR_EMPRESA,SOURCE.ANIO_PERIODO,SOURCE.MES_PERIODO,
			SOURCE.CORR_DOCUMENTO,SOURCE.CORR_RUBRO,SOURCE.MONTO_RUBRO,SOURCE.ORDEN_TOTAL)
		;

	  --Actualizar los montos de la factura...
		UPDATE A SET A.TOTAL_DOCUMENTO=B.MONTO_RUBRO,A.SALDO_DOCUMENTO=B.MONTO_RUBRO,A.TOTAL_NETO=B.MONTO_RUBRO
		FROM COM_DOCUMENTO A
		INNER JOIN V_COM_DOCUMENTO_TOTAL B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.MES_PERIODO=@MES_PERIODO
		AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO
		AND B.CLASE_RUBRO IN('VTO')

	SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
