SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_PROVEEDOR_USUARIO]
(
	@TIPO_ACTUALIZA INT,
	@CORR_PROVEEDOR varchar(20),
	@LOGIN_SISTEMA varchar(30) OUTPUT,
	@USUARIO_CREA varchar(30),
	@FECHA_CREA datetime,
	@ESTACION_CREA varchar(50),
	@USUARIO_ACTU varchar(30),
	@FECHA_ACTU datetime,
	@ESTACION_ACTU varchar(50),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			INSERT INTO COM_PROVEEDOR_USUARIO
			(CORR_PROVEEDOR,LOGIN_SISTEMA,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU)
			VALUES
			(@CORR_PROVEEDOR,@LOGIN_SISTEMA,@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE COM_PROVEEDOR_USUARIO SET
			USUARIO_ACTU=@USUARIO_ACTU,
			FECHA_ACTU=@FECHA_ACTU,
			ESTACION_ACTU=@ESTACION_ACTU
			WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR
			AND LOGIN_SISTEMA=@LOGIN_SISTEMA
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM COM_PROVEEDOR_USUARIO
			WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR
			AND LOGIN_SISTEMA=@LOGIN_SISTEMA
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO
