SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_COM_CUADRO_COMPARATIVO_ORDEN_COMPRA]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
    @CORR_CUADRO_COMPARATIVO INT,
	@NUMERO_ORDEN INT
)
AS
	DECLARE @FECHA_CUADRO_COMPARATIVO DATETIME,@NOMBRE_DEPARTAMENTO VARCHAR(150),@ES_MEJOR_PRECIO BIT,@TIENE_CREDITO_30_DIAS BIT,@TIENE_BUEN_SOPORTE_TECNICO BIT,@TIENE_BUENA_CALIDAD_PRODUCTO BIT
	,@TIENE_MEJOR_TIEMPO_ENTREGA BIT,@BRINDA_BUENA_EXPERIENCIA_PROVEEDOR BIT ,@ES_PROVEEDOR_UNICO BIT,@EXISTE_OTRA_RAZON BIT,@NOMBRE_OTRA_RAZON VARCHAR(255), @NOMBRE_USUARIO_CUADRO_COMPARATIVO VARCHAR(150)
BEGIN
	SET NOCOUNT ON

	SELECT @FECHA_CUADRO_COMPARATIVO=A.FECHA_CUADRO_COMPARATIVO
	,@NOMBRE_DEPARTAMENTO=B.NOMBRE_DEPTO
	,@ES_MEJOR_PRECIO=A.ES_MEJOR_PRECIO
	,@TIENE_CREDITO_30_DIAS=A.TIENE_CREDITO_30_DIAS
	,@TIENE_BUEN_SOPORTE_TECNICO=A.TIENE_BUEN_SOPORTE_TECNICO
	,@TIENE_BUENA_CALIDAD_PRODUCTO=A.TIENE_BUENA_CALIDAD_PRODUCTO
	,@TIENE_MEJOR_TIEMPO_ENTREGA=A.TIENE_MEJOR_TIEMPO_ENTREGA
	,@BRINDA_BUENA_EXPERIENCIA_PROVEEDOR=A.BRINDA_BUENA_EXPERIENCIA_PROVEEDOR
	,@ES_PROVEEDOR_UNICO=A.ES_PROVEEDOR_UNICO
	,@EXISTE_OTRA_RAZON=A.EXISTE_OTRA_RAZON
	,@NOMBRE_OTRA_RAZON=A.NOMBRE_OTRA_RAZON
	,@NOMBRE_USUARIO_CUADRO_COMPARATIVO=ISNULL(C.NOMBRE_USUARIO,ISNULL(D.NOMBRE_USUARIO,''))
	FROM COM_CUADRO_COMPARATIVO A
	INNER JOIN V_COM_CUADRO_COMPARATIVO_COTIZACION_SUM B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = B.CORR_CUADRO_COMPARATIVO
	LEFT OUTER JOIN V_SEG_USUARIO C ON A.USUARIO_CUADRO_COMPARATIVO=C.LOGIN_SISTEMA
	LEFT OUTER JOIN V_SEG_USUARIO_CLASS D ON A.USUARIO_CUADRO_COMPARATIVO COLLATE DATABASE_DEFAULT =D.LOGIN_SISTEMA COLLATE DATABASE_DEFAULT
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	AND A.ANIO_PERIODO=@ANIO_PERIODO
	AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO


	;WITH CTE_SUMAS_ORDEN_COMPRA AS
	(
		SELECT A.ORDNUM NUMERO_ORDEN
		,SUM(A.ORDAMT) SUB_TOTAL
		,SUM(A.ORDIMP) TOTAL_IMPUESTO
		,SUM(A.ORDMIV) TOTAL_ORDEN
		,dbo.FN_NUMEROS_A_LETRAS(SUM(A.ORDMIV),0)TOTAL_EN_LETRAS
		,dbo.StrConcat(DISTINCT A.ORDOB1+'')OBSERVACIONES
		FROM [CLASS_UEES].dbo.ORDENCOMPRA A
		WHERE A.ORDNUM=@NUMERO_ORDEN
		GROUP BY A.ORDNUM
	)
	SELECT D.NOMBRE_EMPRESA
	,D.DIRECCION_EMPRESA
	,D.TELEFONO_1 TELEFONO_EMPRESA
	,D.NUMERO_NRC NUMERO_NRC_EMPRESA
	,D.NUMERO_NIT NUMERO_NIT_EMPRESA
	,B.ORDFAP FECHA_ORDEN_COMPRA
	,CONVERT(VARCHAR(25),B.ORDNUM) NUMERO_ORDEN_COMPRA
	,C.CODIGO_PROVEEDOR
	,C.NOMBRE_PROVEEDOR
	,C.DIRECCION_PROVEEDOR
	,C.NOMBRE_COMERCIAL
	,C.NOMBRE_ACTIVIDAD_ECONOMICA ACTIVIDAD_ECONOMICA
	,C.NOMBRE_CONTACTO CONTACTO
	,C.CORREO_ELECTRONICO_1 CORREO
	,C.TELEFONO_FIJO TELEFONO
	,B.ORDCPG CONDICION_PAGO
	,B.ORDCAN CANTIDAD
	,''NOMBRE_UNIDAD_MEDIDA
	,E.INVDSC NOMBRE_ITEM
	,B.ORDMUN PRECIO_UNITARIO
	,B.ORDAMT MONTO_SUBTOTAL
	,I.NUMERO_SOLI_COMPRA NUMERO_SOLI_COTIZACION
	,F.NOMBRE_DEPTO NOMBRE_DEPARTAMENTO
	,G.OBSERVACIONES
	,G.TOTAL_EN_LETRAS
	,G.SUB_TOTAL
	,G.TOTAL_IMPUESTO
	,G.TOTAL_ORDEN
	,D.LOGO_1 LOGO1
	,'ORDEN DE COMPRA'TITULO_REPORTE
	,'e-Admin Ver 1' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	,@NOMBRE_USUARIO_CUADRO_COMPARATIVO NOMBRE_USUARIO_CREA
	,H.FIRMA1
	,H.NOMBRE_FIRMA1
	,H.FECHA_FIRMA1
	,H.FIRMA2
	,H.NOMBRE_FIRMA2
	,H.FECHA_FIRMA2
	,H.FIRMA3
	,H.NOMBRE_FIRMA3
	,H.FECHA_FIRMA3
	,H.FIRMA4
	,H.NOMBRE_FIRMA4
	,H.FECHA_FIRMA4
	,A.CORR_FORMA_PAGO
	,A.CORR_CONDICION_PAGO
	,A.DETALLE_FORMA_PAGO
	,J.NOMBRE_CONDICION_PAGO
	,K.NOMBRE_FORMA_PAGO
	FROM COM_CUADRO_COMPARATIVO_ORDEN_COMPRA A
	INNER JOIN [CLASS_UEES].dbo.ORDENCOMPRA B ON A.NUMERO_ORDEN=B.ORDNUM
	INNER JOIN V_COM_PROVEEDOR C ON A.CORR_PROVEEDOR = C.CORR_PROVEEDOR
	INNER JOIN [e-AdminFE].dbo.GEN_EMPRESA D ON D.CORR_SUSCRIPCION=8 AND A.CORR_EMPRESA = D.CORR_EMPRESA
	INNER JOIN [CLASS_UEES].dbo.INVENTARIOS E ON E.INVCOD = B.ORDCOD AND E.INVREG = 'E' AND E.INVSUC='001'
	INNER JOIN V_COM_CUADRO_COMPARATIVO_COTIZACION_SUM F ON A.CORR_EMPRESA = F.CORR_EMPRESA AND A.ANIO_PERIODO = F.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = F.CORR_CUADRO_COMPARATIVO
	INNER JOIN CTE_SUMAS_ORDEN_COMPRA G ON A.NUMERO_ORDEN = G.NUMERO_ORDEN
	LEFT OUTER JOIN V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_SUM H ON A.CORR_EMPRESA = H.CORR_EMPRESA AND A.ANIO_PERIODO = H.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = H.CORR_CUADRO_COMPARATIVO
	LEFT OUTER JOIN V_COM_CUADRO_COMPARATIVO_SOLI_COTIZACION_SUM I ON A.CORR_EMPRESA=I.CORR_EMPRESA AND A.ANIO_PERIODO=I.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO=I.CORR_CUADRO_COMPARATIVO
	LEFT OUTER JOIN COM_CONDICION_PAGO J ON A.CORR_EMPRESA = J.CORR_EMPRESA AND A.CORR_CONDICION_PAGO = J.CORR_CONDICION_PAGO
	LEFT OUTER JOIN V_GEN_FORMA_PAGO K ON A.CORR_FORMA_PAGO = K.CORR_FORMA_PAGO
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	AND A.ANIO_PERIODO=@ANIO_PERIODO
	AND	A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
	AND A.NUMERO_ORDEN=@NUMERO_ORDEN

FINA:	
END
GO
