SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_GENE_CON_PARTIDA_MODELO]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_CLASE_PARTIDA INT,
	@CORR_PARTIDA INT OUTPUT,
	@FECHA_PARTIDA DATE,
	@USUARIO_CREA varchar(30),
	@FECHA_CREA datetime,
	@ESTACION_CREA varchar(50),
	@USUARIO_ACTU varchar(30),
	@FECHA_ACTU datetime,
	@ESTACION_ACTU varchar(50),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS

BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	DECLARE @NUMERO_DOCUMENTO VARCHAR(25),
			@NOMBRE_PARTIDA VARCHAR(1000),
			@CLASE_PARTIDA VARCHAR(3),
			@CORR_MONEDA INT,
			@FACTOR_CAMBIO DECIMAL(16,6),
			@OPERADOR VARCHAR(2),
			@CORR_PARTIDA_MODELO INT,
			@CORR_PARTIDA_NUEVA INT

	BEGIN TRY

		SELECT @CORR_PARTIDA_MODELO=@CORR_PARTIDA

		SELECT @NUMERO_DOCUMENTO=NUMERO_DOCUMENTO,
		@NOMBRE_PARTIDA=NOMBRE_PARTIDA,
		@CLASE_PARTIDA=CLASE_PARTIDA,
		@CORR_MONEDA=CORR_MONEDA,
		@FACTOR_CAMBIO=FACTOR_CAMBIO,
		@OPERADOR=OPERADOR
		FROM CON_PARTIDA_MODELO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
		AND CORR_PARTIDA=@CORR_PARTIDA_MODELO

		IF NOT EXISTS(SELECT 1 FROM CON_PARTIDA_MODELO
		              WHERE CORR_EMPRESA=@CORR_EMPRESA
		              AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
		              AND CORR_PARTIDA=@CORR_PARTIDA_MODELO)
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='La partida modelo no existe.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		SELECT @CORR_PARTIDA_NUEVA=ISNULL(MAX(CORR_PARTIDA),0)+1
		FROM CON_PARTIDA
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA

		INSERT INTO CON_PARTIDA
		(CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,CORR_CLASE_PARTIDA,CORR_PARTIDA,FECHA_PARTIDA,NUMERO_DOCUMENTO,NOMBRE_PARTIDA,ESTADO_PARTIDA,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU,CLASE_PARTIDA,CORR_MONEDA,FACTOR_CAMBIO,OPERADOR)
		VALUES
		(@CORR_EMPRESA,@ANIO_PERIODO,@MES_PERIODO,@CORR_CLASE_PARTIDA,@CORR_PARTIDA_NUEVA,@FECHA_PARTIDA,@NUMERO_DOCUMENTO,@NOMBRE_PARTIDA,'DI',@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU,@CLASE_PARTIDA,@CORR_MONEDA,@FACTOR_CAMBIO,@OPERADOR)

		INSERT INTO CON_PARTIDA_DETA
		(
		    CORR_EMPRESA,
		    ANIO_PERIODO,
		    MES_PERIODO,
		    CORR_CLASE_PARTIDA,
		    CORR_PARTIDA,
		    CORR_PARTIDA_DETA,
		    CUENTA_CONTABLE,
		    CORR_CENTRO_COSTO,
		    NOMBRE_TRAN,
		    MONTO_CARGO,
		    MONTO_ABONO,
		    ESTA_CONCILIA,
		    CORR_AUXILIAR,
		    MONTO_CARGO_FORANEA,
		    MONTO_ABONO_FORANEA
		)
		SELECT CORR_EMPRESA,
		@ANIO_PERIODO,
		@MES_PERIODO,
		CORR_CLASE_PARTIDA,
		@CORR_PARTIDA_NUEVA,
		CORR_PARTIDA_DETA,
		CUENTA_CONTABLE,
		CORR_CENTRO_COSTO,
		NOMBRE_TRAN,
		MONTO_CARGO,
		MONTO_ABONO,
		ESTA_CONCILIA,
		CORR_AUXILIAR,
		MONTO_CARGO_FORANEA,
		MONTO_ABONO_FORANEA
		FROM CON_PARTIDA_DETA_MODELO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA
		AND CORR_PARTIDA=@CORR_PARTIDA_MODELO

		SELECT @CORR_PARTIDA=@CORR_PARTIDA_NUEVA

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

	END TRY

	BEGIN CATCH
		DECLARE
			@CORR_BITACORA  int,
			@SEVERITY_ERROR  int,
			@ESTADO_ERROR     int,
			@ORIGEN_ERROR nvarchar(126),
			@LINEA_ERROR      int,
			@SYS_FECHA DateTime

			SELECT @CORR_BITACORA=0,
			@SYS_NUMERO_ERROR=ERROR_NUMBER(),
			@SEVERITY_ERROR=ERROR_SEVERITY(),
			@ESTADO_ERROR=ERROR_STATE(),
			@ORIGEN_ERROR=ERROR_PROCEDURE(),
			@LINEA_ERROR=ERROR_LINE(),
			@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
			@SYS_FECHA=GETDATE()

			EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH
FINA:
END
GO
