SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_SEG_TIPO_USUARIO_OPCION]
(
	@TIPO_CONSULTA int,
	@TIPO_USUARIO INT,
	@CODIGO_SISTEMA varchar(30)=NULL,
	@CODIGO_MENU varchar(10)=NULL,
	@CODIGO_OPCION varchar(30)=NULL,
	@CODIGO_SUITE varchar(30)='SCUEES',
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN		
			SELECT B.TIPO_USUARIO,
			A.CODIGO_SISTEMA,
			A.NOMBRE_SISTEMA,
			A.CODIGO_MENU,
			A.NOMBRE_MENU,
			A.CODIGO_OPCION,
			A.NOMBRE_OPCION,
			CONVERT(BIT,CASE WHEN B.TIPO_USUARIO IS NOT NULL THEN 1 ELSE 0 END) SELECCION,
			B.NUEVO,
			B.MODIFICAR,
			B.ELIMINAR,
			B.IMPRIMIR,
			B.USUARIO_CREA,
			B.FECHA_CREA,
			B.ESTACION_CREA,
			B.USUARIO_ACTU,
			B.FECHA_ACTU,
			B.ESTACION_ACTU
			FROM V_SEG_CONFIG_OPCION A
			LEFT OUTER JOIN SEG_TIPO_USUARIO_OPCION B ON A.CODIGO_SISTEMA = B.CODIGO_SISTEMA AND A.CODIGO_MENU = B.CODIGO_MENU AND A.CODIGO_OPCION=B.CODIGO_OPCION
				AND B.TIPO_USUARIO = @TIPO_USUARIO
			WHERE EXISTS(SELECT 1 FROM SEG_OPCION_SISTEMA_SUITE C
						 WHERE A.CODIGO_OPCION=C.CODIGO_OPCION
						 AND LTRIM(RTRIM(UPPER(CODIGO_SUITE)))=LTRIM(RTRIM(UPPER(@CODIGO_SUITE))))
			ORDER BY A.ORDEN_SISTEMA, A.ORDEN_MENU, A.ORDEN_OPCION
		END ELSE
		IF @OPCION_CONSULTA=1
		BEGIN		
			SELECT *
			FROM V_SEG_TIPO_USUARIO_OPCION A
			WHERE A.TIPO_USUARIO=@TIPO_USUARIO	    
			AND A.CODIGO_OPCION IN(SELECT CODIGO_OPCION 
			                     FROM SEG_OPCION_SISTEMA_SUITE
			                     WHERE LTRIM(RTRIM(UPPER(CODIGO_SUITE)))=LTRIM(RTRIM(UPPER(@CODIGO_SUITE))))
			ORDER BY ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION
		END ELSE
		IF @OPCION_CONSULTA=2
		BEGIN
			SELECT * FROM V_SEG_CONFIG_OPCION
			WHERE LTRIM(RTRIM(CODIGO_SISTEMA))+LTRIM(RTRIM(CODIGO_MENU))+LTRIM(RTRIM(CODIGO_OPCION)) 
			NOT IN(SELECT LTRIM(RTRIM(CODIGO_SISTEMA))+LTRIM(RTRIM(CODIGO_MENU))+LTRIM(RTRIM(CODIGO_OPCION)) 
					FROM SEG_TIPO_USUARIO_OPCION
					WHERE TIPO_USUARIO=@TIPO_USUARIO)
		    AND CODIGO_OPCION IN(SELECT CODIGO_OPCION 
			                     FROM SEG_OPCION_SISTEMA_SUITE
			                     WHERE LTRIM(RTRIM(UPPER(CODIGO_SUITE)))=LTRIM(RTRIM(UPPER(@CODIGO_SUITE))))
			ORDER BY ORDEN_SISTEMA,ORDEN_MENU,ORDEN_OPCION
		END ELSE		
		IF @OPCION_CONSULTA=3
		BEGIN		    
			SELECT A.CODIGO_SISTEMA codeSistema
			,A.CODIGO_MENU codeMenu
			,A.CODIGO_OPCION code
			,A.NOMBRE_OPCION 'text'
			,A.IMAGEN_OPCION icon
			,A.URL_OPCION 'path'
			,A.ORDEN_SISTEMA
			,A.ORDEN_MENU
			,A.ORDEN_OPCION
			FROM V_SEG_TIPO_USUARIO_OPCION A			
			WHERE TIPO_USUARIO=@TIPO_USUARIO					    
			AND (A.CODIGO_SISTEMA=@CODIGO_SISTEMA OR ISNULL(@CODIGO_SISTEMA,'')='')
			AND CODIGO_OPCION IN(SELECT CODIGO_OPCION 
			                     FROM SEG_OPCION_SISTEMA_SUITE
			                     WHERE LTRIM(RTRIM(UPPER(CODIGO_SUITE)))=LTRIM(RTRIM(UPPER(@CODIGO_SUITE))))
			ORDER BY A.ORDEN_SISTEMA DESC, A.ORDEN_MENU, A.ORDEN_OPCION
		END ELSE
		IF @OPCION_CONSULTA=4 --Sistemas con acceso al usuario
		BEGIN		
			SELECT 'SCUEES' codeSistema
			,'PROCESO' codeMenu
			,'Home' code
			,'Home' 'text'
			,'home' icon
			,'/home' 'path'
			,1 ORDEN_SISTEMA
			UNION ALL
			SELECT DISTINCT A.CODIGO_SISTEMA codeSistema
			,A.CODIGO_SISTEMA codeMenu
			,A.CODIGO_SISTEMA code
			,A.NOMBRE_SISTEMA 'text'
			,A.IMAGEN_SISTEMA icon
			,'' 'path'
			,A.ORDEN_SISTEMA+1
			FROM V_SEG_TIPO_USUARIO_OPCION A
			WHERE TIPO_USUARIO=@TIPO_USUARIO	    
			AND (A.CODIGO_SISTEMA=@CODIGO_SISTEMA OR ISNULL(@CODIGO_SISTEMA,'')='')
			AND A.CODIGO_OPCION IN(SELECT CODIGO_OPCION 
			                     FROM SEG_OPCION_SISTEMA_SUITE
			                     WHERE LTRIM(RTRIM(UPPER(CODIGO_SUITE)))=LTRIM(RTRIM(UPPER(@CODIGO_SUITE))))
			ORDER BY ORDEN_SISTEMA
		END ELSE
		IF @OPCION_CONSULTA=5 --Menus de los sistemas con acceso al usuario
		BEGIN							
			SELECT DISTINCT A.CODIGO_SISTEMA codeSistema
			,A.CODIGO_MENU codeMenu
			,A.CODIGO_MENU code
			,A.NOMBRE_MENU 'text'
			,A.IMAGEN_MENU icon
			,'' 'path'
			,A.ORDEN_SISTEMA
			,A.ORDEN_MENU
			FROM V_SEG_TIPO_USUARIO_OPCION A			
			WHERE TIPO_USUARIO=@TIPO_USUARIO
			AND (A.CODIGO_SISTEMA=@CODIGO_SISTEMA OR ISNULL(@CODIGO_SISTEMA,'')='')
			AND A.CODIGO_OPCION IN(SELECT CODIGO_OPCION 
			                     FROM SEG_OPCION_SISTEMA_SUITE
			                     WHERE LTRIM(RTRIM(UPPER(CODIGO_SUITE)))=LTRIM(RTRIM(UPPER(@CODIGO_SUITE))))
			ORDER BY ORDEN_SISTEMA, ORDEN_MENU
		END 
	END ELSE
	IF @TIPO_CONSULTA=2
	BEGIN
		SELECT CODIGO_OPCION, NOMBRE_OPCION FROM V_SEG_USUARIO_OPCION
	END ELSE
	IF @TIPO_CONSULTA=3
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			DECLARE @NOMBRE_SUITE VARCHAR(100)
			SELECT @NOMBRE_SUITE=NOMBRE_SUITE 
			FROM SEG_SUITE 
			WHERE CODIGO_SUITE=@CODIGO_SUITE
	
			SELECT *, @CODIGO_SUITE CODIGO_SUITE,
			@NOMBRE_SUITE NOMBRE_SUITE 
			FROM V_SEG_TIPO_USUARIO_OPCION
			WHERE TIPO_USUARIO=@TIPO_USUARIO
			AND CODIGO_SISTEMA=@CODIGO_SISTEMA
			AND CODIGO_MENU=@CODIGO_MENU
			AND CODIGO_OPCION=@CODIGO_OPCION
		END ELSE
		IF @OPCION_CONSULTA=1
		BEGIN
			SELECT B.TIPO_USUARIO,
			C.CODIGO_SISTEMA,
			C.NOMBRE_SISTEMA,
			C.CODIGO_MENU,
			C.NOMBRE_MENU,
			A.CODIGO_OPCION,
			C.NOMBRE_OPCION,
			CONVERT(BIT,CASE WHEN B.TIPO_USUARIO IS NOT NULL THEN 1 ELSE 0 END) SELECCION,
			B.NUEVO,
			B.MODIFICAR,
			B.ELIMINAR,
			B.IMPRIMIR,
			B.USUARIO_CREA,
			B.FECHA_CREA,
			B.ESTACION_CREA,
			B.USUARIO_ACTU,
			B.FECHA_ACTU,
			B.ESTACION_ACTU
			FROM SEG_OPCION_SISTEMA A
			LEFT OUTER JOIN SEG_TIPO_USUARIO_OPCION B ON B.TIPO_USUARIO = @TIPO_USUARIO AND A.CODIGO_OPCION=B.CODIGO_OPCION
			INNER JOIN V_SEG_CONFIG_OPCION C ON A.CODIGO_OPCION = C.CODIGO_OPCION
			WHERE A.CODIGO_OPCION IN(SELECT CODIGO_OPCION 
			                     FROM SEG_OPCION_SISTEMA_SUITE
			                     WHERE LTRIM(RTRIM(UPPER(CODIGO_SUITE)))=LTRIM(RTRIM(UPPER(@CODIGO_SUITE))))
			ORDER BY ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION
		END
	END ELSE
	IF @TIPO_CONSULTA=4
	BEGIN
		IF @OPCION_CONSULTA=0
			SELECT NOMBRE_OPCION FROM V_SEG_TIPO_USUARIO_OPCION
			WHERE TIPO_USUARIO=@TIPO_USUARIO
			AND CODIGO_SISTEMA=@CODIGO_SISTEMA
			AND CODIGO_MENU=@CODIGO_MENU
			AND CODIGO_OPCION=@CODIGO_OPCION
		ELSE
		IF @OPCION_CONSULTA=1
			SELECT NOMBRE_SISTEMA FROM V_SEG_TIPO_USUARIO_OPCION
			WHERE TIPO_USUARIO=@TIPO_USUARIO
			AND CODIGO_SISTEMA=@CODIGO_SISTEMA
			AND CODIGO_MENU=@CODIGO_MENU
			AND CODIGO_OPCION=@CODIGO_OPCION
	END
END
GO
