SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_IMPR_BALANCE_GENERAL]
( 
  @CORR_EMPRESA INT,
  @FECHA_FINAL DATE,
  @NIVEL SMALLINT,
  @PARTIDA_CIERRE BIT=0,
  @PARTIDA_LIQUIDACION BIT=0,
  @CORR_MONEDA INT=NULL,
  @FOLIADO BIT=0,
  @NUMERO_FOLIO INT=0
)
AS	
	DECLARE @SALDO TABLE
	(
		CORR_EMPRESA INT,
		CUENTA_CONTABLE varchar(30),
		CUENTA_MAYOR varchar(30),
		ES_DEBE BIT,
		ES_HABER BIT,
		SALDO_INICIAL DECIMAL(12,2),
		CARGO_PERIODO DECIMAL(12,2),
		ABONO_PERIODO DECIMAL(12,2),
		SALDO_FINAL	DECIMAL(12,2)
	)
	
	DECLARE @CORR_MONEDA_LOCAL INT, @CORR_MONEDA_FORANEA INT
	
	DECLARE @PERDIDA_GANA DECIMAL(12,2), @CUENTA_PERDIDA_GANA VARCHAR(30),
	@NOMBRE_PUESTO1 VARCHAR(100),
	@DESCRIPCION_PUESTO1 VARCHAR(100),
	@NOMBRE_PUESTO2 VARCHAR(100),
	@DESCRIPCION_PUESTO2 VARCHAR(100),
	@NOMBRE_PUESTO3 VARCHAR(100),
	@DESCRIPCION_PUESTO3 VARCHAR(100),
	@DESCRIPCION_MONEDA VARCHAR(255)
BEGIN
    
    SET NOCOUNT ON
	SELECT @CORR_MONEDA_LOCAL=CORR_MONEDA
	FROM CON_PARAMETRO
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	
	SET @CORR_MONEDA_FORANEA = NULL
	
	IF @CORR_MONEDA IS NULL
		SELECT @CORR_MONEDA=@CORR_MONEDA_LOCAL	
	
	
	IF @CORR_MONEDA=@CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL
	BEGIN
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL 
	@CORR_EMPRESA,
		@FECHA_FINAL,
		0,--OPCION_CONSULTA=Saldo de todas las cuentas contables hasta la fecha de consulta
		1,--MAYORIZA=Mayoriza los saldo
		'',
		'',	
		1, --Aplicar el debe o haber de la cuenta
		@PARTIDA_CIERRE, --Incluir partidas de cierre
		@PARTIDA_LIQUIDACION, --Incluir partidas de liquidación
		@NIVEL --Hasta el nivel indicado	
	END ELSE
	IF @CORR_MONEDA=@CORR_MONEDA_FORANEA
	BEGIN
		INSERT INTO @SALDO
		EXEC PRAL_GENE_CON_SALDO_INICIAL_FORANEA 
	@CORR_EMPRESA,
		@FECHA_FINAL,
		0,--OPCION_CONSULTA=Saldo de todas las cuentas contables hasta la fecha de consulta
		1,--MAYORIZA=Mayoriza los saldo
		'',
		'',	
		1, --Aplicar el debe o haber de la cuenta
		@PARTIDA_CIERRE, --Incluir partidas de cierre
		@PARTIDA_LIQUIDACION, --Incluir partidas de liquidación
		@NIVEL --Hasta el nivel indicado	
	END
    --Obteniendo la perdida o ganancia
    SELECT @PERDIDA_GANA=ISNULL(SUM(CASE WHEN B.CLASE_RUBRO='IN' THEN A.SALDO_FINAL ELSE A.SALDO_FINAL*-1 END),0)
    FROM @SALDO A
    INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
    WHERE B.CLASE_RUBRO IN('IN','GA')
    AND B.NIVEL=1
    
    IF @PERDIDA_GANA>=0 --Si es Ganancia
    BEGIN
	    SELECT @CUENTA_PERDIDA_GANA=ISNULL(A.CUENTA_CONTABLE_GANANCIA,'')
	    FROM CON_PARAMETRO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
    END ELSE --Si es Perdida
    BEGIN
	    SELECT @CUENTA_PERDIDA_GANA=ISNULL(A.CUENTA_CONTABLE_PERDIDA,'')
	    FROM CON_PARAMETRO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
    END
    
    --Obteniendo la cuenta según el nivel del reporte
    SELECT @CUENTA_PERDIDA_GANA=SUBSTRING(@CUENTA_PERDIDA_GANA,1,A.NUMERO_CARACTERES)
    FROM CON_RUBRO_NIVEL A
    INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CODIGO_RUBRO=B.CODIGO_RUBRO
    WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	AND A.NIVEL=@NIVEL
	AND B.CUENTA_CONTABLE=@CUENTA_PERDIDA_GANA
    
    --Actualizando el saldo de la perdida o ganancia
    UPDATE @SALDO SET
    SALDO_FINAL=ISNULL(SALDO_FINAL,0)+@PERDIDA_GANA
    WHERE CORR_EMPRESA=@CORR_EMPRESA
	AND @CUENTA_PERDIDA_GANA LIKE CUENTA_CONTABLE+'%'
    
    --Obteniendo las personas que firmarán en balance general
    SELECT @NOMBRE_PUESTO1=A.NOMBRE_PUESTO1,
	@DESCRIPCION_PUESTO1=A.DESCRIPCION_PUESTO1,
	@NOMBRE_PUESTO2=A.NOMBRE_PUESTO2,
	@DESCRIPCION_PUESTO2=A.DESCRIPCION_PUESTO2,
	@NOMBRE_PUESTO3=A.NOMBRE_PUESTO3,
	@DESCRIPCION_PUESTO3=A.DESCRIPCION_PUESTO3	
	FROM CON_PARAMETRO A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	
	--Obteniendo en que moneda esta el balance general
	SET @DESCRIPCION_MONEDA = ''
    SELECT @CORR_EMPRESA CORR_EMPRESA
    ,A.CUENTA_CONTABLE CUENTA_CONTABLE1
    ,A.NOMBRE_CUENTA+CASE A.NIVEL WHEN 1 THEN CHAR(13)+CHAR(13)+CHAR(13) WHEN 2 THEN CHAR(13)+CHAR(13) ELSE '' END NOMBRE_CUENTA1
    ,SUM(A.SALDO_FINAL) SALDO_FINAL1
    ,A.NIVEL NIVEL1
    ,B.CUENTA_CONTABLE CUENTA_CONTABLE2
    ,B.NOMBRE_CUENTA+CASE B.NIVEL WHEN 1 THEN CHAR(13)+CHAR(13)+CHAR(13) WHEN 2 THEN CHAR(13)+CHAR(13) ELSE '' END NOMBRE_CUENTA2
    ,SUM(B.SALDO_FINAL) SALDO_FINAL2
    ,B.NIVEL NIVEL2
    ,@NOMBRE_PUESTO1 NOMBRE_PUESTO1
	,@DESCRIPCION_PUESTO1 DESCRIPCION_PUESTO1
	,@NOMBRE_PUESTO2 NOMBRE_PUESTO2
	,@DESCRIPCION_PUESTO2 DESCRIPCION_PUESTO2
	,@NOMBRE_PUESTO3 NOMBRE_PUESTO3
	,@DESCRIPCION_PUESTO3 DESCRIPCION_PUESTO3
	,@DESCRIPCION_MONEDA DESCRIPCION_MONEDA	
	,@FOLIADO FOLIADO
	,@NUMERO_FOLIO NUMERO_FOLIO
	,@NIVEL NIVEL_MAXIMO
	,@FECHA_FINAL FECHA_FINAL
    FROM (  SELECT ROW_NUMBER() OVER(ORDER BY A.CORR_EMPRESA, A.CUENTA_CONTABLE) LINEA
			,A.CORR_EMPRESA
			,A.CUENTA_CONTABLE
			,B.NOMBRE_CUENTA
			,B.NIVEL
			,A.SALDO_FINAL
			FROM @SALDO A
			INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
			WHERE B.CLASE_RUBRO='AC'
			AND A.SALDO_FINAL<>0
		) A
		FULL JOIN (
			SELECT ROW_NUMBER() OVER(ORDER BY A.CORR_EMPRESA, A.CUENTA_CONTABLE) LINEA
			,A.CORR_EMPRESA
			,A.CUENTA_CONTABLE
			,B.NOMBRE_CUENTA
			,B.NIVEL
			,A.SALDO_FINAL
			FROM @SALDO A
			INNER JOIN CON_CATALOGO_CUENTA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CUENTA_CONTABLE=B.CUENTA_CONTABLE
			WHERE B.CLASE_RUBRO IN('PA','PT','LI')
			AND A.SALDO_FINAL<>0
		) B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.LINEA=B.LINEA
	GROUP BY A.CUENTA_CONTABLE,
			 A.NOMBRE_CUENTA,
			 A.NIVEL,
			 A.LINEA,
			 B.CUENTA_CONTABLE,
			 B.NOMBRE_CUENTA,
			 B.NIVEL,
			 B.LINEA	
	ORDER BY ISNULL(A.LINEA,B.LINEA)
	

	SELECT A.CORR_EMPRESA 
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,A.LOGO_1 LOGO1
	,A.LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO

