SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_CONCILIA_BANCARIA_MOVI]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA int,
	@CORR_CUENTA_BANCO int,
	@CORR_CONCILIACION int,
	@CORR_MOVIMIENTO int OUTPUT,
	@CORR_LINEA int,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_CLASE_PARTIDA int,
	@CORR_PARTIDA int,
	@CORR_PARTIDA_DETA int,
	@CORR_TIPO_MOVIMIENTO int,
	@CORR_CONCILIACION_DETA int,
	@MONTO_CARGO decimal(18,2),
	@MONTO_ABONO decimal(18,2),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1,2)
		BEGIN
			IF NOT EXISTS ( SELECT 1 FROM BAN_LINEA_TRABAJO_CONCILIACION 
							WHERE CORR_EMPRESA=@CORR_EMPRESA 
							AND CORR_LINEA=@CORR_LINEA )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='No ha seleccionado correctamente la Linea de Trabajo.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END
		IF @TIPO_ACTUALIZA IN (1,2,3)
		BEGIN
			--Verificando el estado
			DECLARE @ESTADO_CONCILIACION VARCHAR(2)
			SELECT @ESTADO_CONCILIACION=ESTADO_CONCILIACION
			FROM BAN_CONCILIA_BANCARIA 
			WHERE CORR_EMPRESA=@CORR_EMPRESA 
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO 
			AND CORR_CONCILIACION=@CORR_CONCILIACION 
			
			IF @ESTADO_CONCILIACION<>'DI'
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Esta conciliacion no puede ser modificada o eliminada.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @CORR_MOVIMIENTO=ISNULL(MAX(CORR_MOVIMIENTO),0)+1
			FROM BAN_CONCILIA_BANCARIA_MOVI
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION


			INSERT INTO BAN_CONCILIA_BANCARIA_MOVI
			(CORR_EMPRESA,CORR_CUENTA_BANCO,CORR_CONCILIACION,CORR_MOVIMIENTO,CORR_LINEA,ANIO_PERIODO,MES_PERIODO,CORR_CLASE_PARTIDA,CORR_PARTIDA,CORR_PARTIDA_DETA,CORR_TIPO_MOVIMIENTO,CORR_CONCILIACION_DETA,MONTO_CARGO,MONTO_ABONO)
			VALUES
			(@CORR_EMPRESA,@CORR_CUENTA_BANCO,@CORR_CONCILIACION,@CORR_MOVIMIENTO,@CORR_LINEA,@ANIO_PERIODO,@MES_PERIODO,@CORR_CLASE_PARTIDA,@CORR_PARTIDA,@CORR_PARTIDA_DETA,@CORR_TIPO_MOVIMIENTO,@CORR_CONCILIACION_DETA,@MONTO_CARGO,@MONTO_ABONO)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE BAN_CONCILIA_BANCARIA_MOVI SET
			CORR_LINEA=@CORR_LINEA,
			ANIO_PERIODO=@ANIO_PERIODO,
			MES_PERIODO=@MES_PERIODO,
			CORR_CLASE_PARTIDA=@CORR_CLASE_PARTIDA,
			CORR_PARTIDA=@CORR_PARTIDA,
			CORR_PARTIDA_DETA=@CORR_PARTIDA_DETA,
			CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO,
			CORR_CONCILIACION_DETA=@CORR_CONCILIACION_DETA,
			MONTO_CARGO=@MONTO_CARGO,
			MONTO_ABONO=@MONTO_ABONO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
			AND CORR_MOVIMIENTO=@CORR_MOVIMIENTO
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM BAN_CONCILIA_BANCARIA_MOVI
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND CORR_CONCILIACION=@CORR_CONCILIACION
			AND CORR_MOVIMIENTO=@CORR_MOVIMIENTO
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO

