SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================================================
-- Procedimiento: dbo.PRAL_MTTO_SC_REQUISICION_PERSONAL_AUTORIZA
-- Pantalla:      SC_REQUISICION / sc-requisicion-personal (tipo documento 101)
--
-- Qué hace:
--   Ejecuta una operación del flujo de la requisición de personal y sincroniza
--   CORR_ESTADO_REQUISICION en SC_REQUISICION_PERSONAL (catálogo de negocio 1..5).
--
-- Importante:
--   No crea ni edita el contenido de la requisición (unidad, puesto, etc.).
--   Solo mueve el flujo (EjecutarFlujoProceso) y actualiza el estado de negocio.
--
-- @OPERACION:
--   1 = GUARDAR   Queda en Borrador. Si es la primera vez, crea la instancia.
--   2 = ENVIAR    Envía a aprobación (Borrador/Devuelta → En Aprobación).
--   3 = APROBAR   Avanza o finaliza hacia Aprobada.
--   4 = DEVOLVER  Retorna (Devuelta).
--   5 = RECHAZAR  Finaliza hacia Rechazada.
--
-- Códigos RETURN:
--    0 = ok
--   -1 = datos / requisición inexistente
--   -2 = sin tipo documento
--   -3 = sin flujo defecto
--   -4 = sin paso inicial
--   -5 = OPERACION inválida
--   -7 = sin acción configurada
--   -8 = falta unidad al crear instancia
--   -9 = falló GUARDAR previo a ENVIAR
--  -10 = falló EjecutarFlujoProceso
--  -11..-16 = operación no aplica al modo actual
-- =============================================================================
CREATE OR ALTER PROCEDURE [dbo].[PRAL_MTTO_SC_REQUISICION_PERSONAL_AUTORIZA]
(
	@CORR_EMPRESA INT = 1,
	@CORR_REQUISICION_PERSONAL INT,
	@CORR_UNIDAD_DOCUMENTO INT = NULL,
	@OPERACION INT = NULL,
	@CORR_ACCION INT = NULL,
	@LOGIN_SISTEMA VARCHAR(30),
	@OBSERVACION NVARCHAR(MAX),
	@CORR_ESTADO INT OUTPUT,                 -- estado del motor (SEG_FLUJO_ESTADO)
	@MENSAJE_ERROR VARCHAR(500) OUTPUT,
	@CORR_ACCION_USADA INT = NULL OUTPUT,
	@CORR_PASO_ACTUAL INT = NULL OUTPUT,
	@MODO VARCHAR(20) = NULL OUTPUT,
	@NOMBRE_ESTADO VARCHAR(100) = NULL OUTPUT,
	@CORR_ESTADO_REQUISICION INT = NULL OUTPUT -- estado de negocio (1..5)
)
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @CODIGO_OPCION VARCHAR(50) = 'SC_REQUISICION'
	DECLARE @EMPRESA INT = ISNULL(@CORR_EMPRESA, 1)
	DECLARE @ID_TIPO_DOCUMENTO INT
	DECLARE @ID_FLUJO INT
	DECLARE @ID_INSTANCIA INT
	DECLARE @ID_PASO_ACTUAL INT
	DECLARE @ID_ESTADO_ACTUAL INT
	DECLARE @ID_ACCION INT = @CORR_ACCION
	DECLARE @V_OPERACION INT = @OPERACION
	DECLARE @NOM_OP VARCHAR(20)
	DECLARE @ESTADO_TMP INT
	DECLARE @ERROR_TMP VARCHAR(500)
	DECLARE @ES_ESTADO_INICIAL BIT = 0
	DECLARE @ES_NUEVO BIT = 0
	DECLARE @ES_BORRADOR BIT = 0
	DECLARE @ES_FINAL BIT = 0
	DECLARE @ES_DEVUELTA BIT = 0
	DECLARE @V_MODO VARCHAR(20)
	DECLARE @ACCION_GUARDAR INT
	DECLARE @UNIDAD_DOC INT = @CORR_UNIDAD_DOCUMENTO
	DECLARE @NOMBRE_PASO VARCHAR(200)
	DECLARE @V_NOMBRE_ESTADO VARCHAR(100)
	DECLARE @EST_APROBADA INT
	DECLARE @EST_RECHAZADA INT
	DECLARE @EST_DEVUELTA INT
	DECLARE @PASO_INICIAL INT
	DECLARE @ESTADO_NEGOCIO INT

	SET @CORR_ESTADO = NULL
	SET @MENSAJE_ERROR = NULL
	SET @CORR_ACCION_USADA = NULL
	SET @CORR_PASO_ACTUAL = NULL
	SET @MODO = NULL
	SET @NOMBRE_ESTADO = NULL
	SET @CORR_ESTADO_REQUISICION = NULL

	-- =========================================================================
	-- PASO 1 — Validar entrada
	-- =========================================================================
	IF @CORR_REQUISICION_PERSONAL IS NULL OR @CORR_REQUISICION_PERSONAL <= 0
	BEGIN
		SET @MENSAJE_ERROR = 'Debe indicar @CORR_REQUISICION_PERSONAL.'
		RETURN -1
	END

	IF NOT EXISTS (
		SELECT 1 FROM dbo.SC_REQUISICION_PERSONAL
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_REQUISICION_PERSONAL = @CORR_REQUISICION_PERSONAL
	)
	BEGIN
		SET @MENSAJE_ERROR = 'No existe la requisicion CORR_REQUISICION_PERSONAL='
			+ CAST(@CORR_REQUISICION_PERSONAL AS VARCHAR) + '.'
		RETURN -1
	END

	IF @LOGIN_SISTEMA IS NULL OR LTRIM(RTRIM(@LOGIN_SISTEMA)) = ''
	BEGIN
		SET @MENSAJE_ERROR = 'Debe indicar @LOGIN_SISTEMA.'
		RETURN -1
	END

	IF @OBSERVACION IS NULL OR LTRIM(RTRIM(@OBSERVACION)) = ''
	BEGIN
		SET @MENSAJE_ERROR = 'El comentario (@OBSERVACION) es obligatorio.'
		RETURN -1
	END

	IF @ID_ACCION IS NULL AND @V_OPERACION IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'Indique @OPERACION (1=GUARDAR,2=ENVIAR,3=APROBAR,4=DEVOLVER,5=RECHAZAR) o @CORR_ACCION.'
		RETURN -1
	END

	IF @ID_ACCION IS NULL AND @V_OPERACION NOT IN (1, 2, 3, 4, 5)
	BEGIN
		SET @MENSAJE_ERROR = 'Operacion invalida: ' + CAST(ISNULL(@V_OPERACION, -1) AS VARCHAR)
			+ '. Use 1=GUARDAR, 2=ENVIAR, 3=APROBAR, 4=DEVOLVER, 5=RECHAZAR.'
		RETURN -5
	END

	SET @NOM_OP = CASE @V_OPERACION
		WHEN 1 THEN 'GUARDAR'
		WHEN 2 THEN 'ENVIAR'
		WHEN 3 THEN 'APROBAR'
		WHEN 4 THEN 'DEVOLVER'
		WHEN 5 THEN 'RECHAZAR'
		ELSE CAST(ISNULL(@V_OPERACION, 0) AS VARCHAR(10))
	END

	-- Si no mandan unidad, tomar la de la requisición (necesaria al crear instancia).
	IF @UNIDAD_DOC IS NULL OR @UNIDAD_DOC <= 0
	BEGIN
		SELECT @UNIDAD_DOC = CORR_UNIDAD
		FROM dbo.SC_REQUISICION_PERSONAL
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_REQUISICION_PERSONAL = @CORR_REQUISICION_PERSONAL
	END

	-- =========================================================================
	-- PASO 2 — Configuración del flujo (CODIGO_OPCION = SC_REQUISICION)
	-- =========================================================================
	SELECT @ID_TIPO_DOCUMENTO = CORR_TIPO_DOCUMENTO
	FROM dbo.SEG_FLUJO_TIPO_DOCUMENTO
	WHERE CORR_EMPRESA = @EMPRESA AND CODIGO_OPCION = @CODIGO_OPCION AND ACTIVO = 1

	IF @ID_TIPO_DOCUMENTO IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'No existe tipo de documento activo para SC_REQUISICION.'
		RETURN -2
	END

	SELECT TOP 1 @ID_FLUJO = CORR_FLUJO_PROCESO
	FROM dbo.SEG_FLUJO_PROCESO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND ACTIVO = 1 AND ES_DEFECTO = 1

	IF @ID_FLUJO IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'No hay flujo defecto activo para requisicion de personal.'
		RETURN -3
	END

	SELECT TOP 1 @EST_APROBADA = CORR_ESTADO
	FROM dbo.SEG_FLUJO_ESTADO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND ACTIVO = 1 AND (NOMBRE_ESTADO = N'Aprobada' OR ES_FINAL = 1)
	ORDER BY CASE WHEN NOMBRE_ESTADO = N'Aprobada' THEN 0 ELSE 1 END, CORR_ESTADO

	SELECT TOP 1 @EST_RECHAZADA = CORR_ESTADO
	FROM dbo.SEG_FLUJO_ESTADO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND ACTIVO = 1 AND NOMBRE_ESTADO LIKE N'Rechaz%'
	ORDER BY CORR_ESTADO

	SELECT TOP 1 @EST_DEVUELTA = CORR_ESTADO
	FROM dbo.SEG_FLUJO_ESTADO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND ACTIVO = 1 AND NOMBRE_ESTADO LIKE N'Devuel%'
	ORDER BY CORR_ESTADO

	SELECT TOP 1 @PASO_INICIAL = CORR_PASO
	FROM dbo.SEG_FLUJO_PASO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
	ORDER BY ORDEN

	-- =========================================================================
	-- PASO 3 — Situación del documento
	-- =========================================================================
	SELECT @ID_INSTANCIA = CORR_INSTANCIA,
	       @ID_PASO_ACTUAL = CORR_PASO_ACTUAL,
	       @ID_ESTADO_ACTUAL = CORR_ESTADO_ACTUAL
	FROM dbo.SEG_FLUJO_INSTANCIA
	WHERE CORR_EMPRESA = @EMPRESA
	  AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND CORR_DOCUMENTO = @CORR_REQUISICION_PERSONAL
	  AND ACTIVO = 1

	IF @ID_INSTANCIA IS NULL
	BEGIN
		SET @ES_NUEVO = 1
		SET @V_MODO = 'NUEVO'
		SET @ID_PASO_ACTUAL = @PASO_INICIAL
	END
	ELSE
	BEGIN
		SELECT @ES_ESTADO_INICIAL = ISNULL(E.ES_INICIAL, 0),
		       @ES_FINAL = ISNULL(E.ES_FINAL, 0),
		       @NOMBRE_PASO = P.NOMBRE_PASO,
		       @V_NOMBRE_ESTADO = E.NOMBRE_ESTADO
		FROM dbo.SEG_FLUJO_ESTADO E
		INNER JOIN dbo.SEG_FLUJO_PASO P
			ON P.CORR_EMPRESA = @EMPRESA AND P.CORR_PASO = @ID_PASO_ACTUAL
		WHERE E.CORR_EMPRESA = @EMPRESA AND E.CORR_ESTADO = @ID_ESTADO_ACTUAL

		IF @EST_DEVUELTA IS NOT NULL AND @ID_ESTADO_ACTUAL = @EST_DEVUELTA
			SET @ES_DEVUELTA = 1
		ELSE IF @V_NOMBRE_ESTADO LIKE N'Devuel%'
			SET @ES_DEVUELTA = 1

		IF @ES_FINAL = 1
			SET @V_MODO = 'FINAL'
		ELSE IF @ES_ESTADO_INICIAL = 1
			OR @ES_DEVUELTA = 1
			OR EXISTS (
				SELECT 1
				FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO A
				INNER JOIN dbo.SEG_FLUJO_PASO P
					ON P.CORR_EMPRESA = A.CORR_EMPRESA AND P.CORR_PASO = A.CORR_PASO
				WHERE A.CORR_EMPRESA = @EMPRESA AND A.CORR_FLUJO_PROCESO = @ID_FLUJO
				  AND A.CORR_PASO = @ID_PASO_ACTUAL AND A.CORR_TIPO_MOVIMIENTO = 4
				  AND A.PERMITIDO = 1 AND A.ACTIVO = 1 AND P.ORDEN = 1
			)
		BEGIN
			SET @ES_BORRADOR = 1
			SET @V_MODO = 'BORRADOR'
		END
		ELSE
			SET @V_MODO = 'EN_FLUJO'
	END

	SET @MODO = @V_MODO
	SET @CORR_PASO_ACTUAL = @ID_PASO_ACTUAL

	IF @ID_PASO_ACTUAL IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'El flujo de requisicion no tiene paso inicial configurado.'
		RETURN -4
	END

	-- =========================================================================
	-- PASO 4 — Validar operación vs modo
	-- =========================================================================
	IF @V_OPERACION IS NOT NULL AND @ID_ACCION IS NULL
	BEGIN
		IF @V_OPERACION = 1 -- GUARDAR
		BEGIN
			IF @V_MODO NOT IN ('NUEVO', 'BORRADOR')
			BEGIN
				SET @MENSAJE_ERROR = 'GUARDAR(1) solo aplica en Borrador/NUEVO (modo actual: ' + @V_MODO + ').'
				RETURN -11
			END
			IF @ES_NUEVO = 1 AND (@UNIDAD_DOC IS NULL OR @UNIDAD_DOC <= 0)
			BEGIN
				SET @MENSAJE_ERROR = 'Al crear (GUARDAR=1) debe enviar @CORR_UNIDAD_DOCUMENTO.'
				RETURN -8
			END
		END
		ELSE IF @V_OPERACION = 2 -- ENVIAR
		BEGIN
			IF @V_MODO NOT IN ('NUEVO', 'BORRADOR')
			BEGIN
				SET @MENSAJE_ERROR = 'ENVIAR(2) solo aplica en Borrador/NUEVO/Devuelta. Modo actual: ' + @V_MODO + '.'
				RETURN -12
			END
			IF @ES_NUEVO = 1 AND (@UNIDAD_DOC IS NULL OR @UNIDAD_DOC <= 0)
			BEGIN
				SET @MENSAJE_ERROR = 'Al crear y ENVIAR(2) debe enviar @CORR_UNIDAD_DOCUMENTO.'
				RETURN -8
			END
		END
		ELSE IF @V_OPERACION IN (3, 4, 5) -- APROBAR / DEVOLVER / RECHAZAR
		BEGIN
			IF @ES_NUEVO = 1
			BEGIN
				SET @MENSAJE_ERROR = 'No hay instancia. Primero GUARDAR(1) o ENVIAR(2).'
				RETURN -13
			END
			IF @ES_BORRADOR = 1 AND @V_OPERACION = 3
			BEGIN
				SET @MENSAJE_ERROR = 'En Borrador use ENVIAR(2), no APROBAR(3).'
				RETURN -14
			END
			IF @V_MODO = 'FINAL'
			BEGIN
				SET @MENSAJE_ERROR = 'La requisicion ya finalizo el flujo (modo FINAL).'
				RETURN -16
			END
		END
	END

	-- =========================================================================
	-- PASO 5 — Resolver CORR_ACCION
	-- Movimientos: 1=AVANZA 2=RETORNA 3=FINALIZA 4=MANTIENE
	-- =========================================================================
	IF @ID_ACCION IS NULL
	BEGIN
		IF @V_OPERACION = 1 -- GUARDAR = MANTIENE
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 4
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION ASC
		ELSE IF @V_OPERACION = 2 -- ENVIAR = AVANZA
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 1
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION DESC
		ELSE IF @V_OPERACION = 3 -- APROBAR = FINALIZA(Aprobada) o AVANZA
		BEGIN
			IF @EST_APROBADA IS NOT NULL
				SELECT TOP 1 @ID_ACCION = CORR_ACCION
				FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
				WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
				  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 3
				  AND CORR_ESTADO_DESTINO = @EST_APROBADA
				  AND PERMITIDO = 1 AND ACTIVO = 1
				ORDER BY CORR_ACCION ASC

			IF @ID_ACCION IS NULL
				SELECT TOP 1 @ID_ACCION = CORR_ACCION
				FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
				WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
				  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 1
				  AND PERMITIDO = 1 AND ACTIVO = 1
				ORDER BY CORR_ACCION ASC

			IF @ID_ACCION IS NULL
				SELECT TOP 1 @ID_ACCION = CORR_ACCION
				FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
				WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
				  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 3
				  AND PERMITIDO = 1 AND ACTIVO = 1
				ORDER BY CORR_ACCION ASC
		END
		ELSE IF @V_OPERACION = 4 -- DEVOLVER = RETORNA
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 2
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION ASC
		ELSE IF @V_OPERACION = 5 -- RECHAZAR = FINALIZA(Rechazada)
		BEGIN
			IF @EST_RECHAZADA IS NOT NULL
				SELECT TOP 1 @ID_ACCION = CORR_ACCION
				FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
				WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
				  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 3
				  AND CORR_ESTADO_DESTINO = @EST_RECHAZADA
				  AND PERMITIDO = 1 AND ACTIVO = 1
				ORDER BY CORR_ACCION ASC

			IF @ID_ACCION IS NULL AND @EST_RECHAZADA IS NOT NULL
				SELECT TOP 1 @ID_ACCION = CORR_ACCION
				FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
				WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
				  AND CORR_PASO = @ID_PASO_ACTUAL
				  AND CORR_ESTADO_DESTINO = @EST_RECHAZADA
				  AND PERMITIDO = 1 AND ACTIVO = 1
				ORDER BY CORR_ACCION ASC
		END

		IF @ID_ACCION IS NULL
		BEGIN
			SET @MENSAJE_ERROR = 'No hay accion para operacion ' + @NOM_OP + '(' + CAST(@V_OPERACION AS VARCHAR) + ')'
				+ ' en paso ' + CAST(@ID_PASO_ACTUAL AS VARCHAR)
				+ ' (modo ' + @V_MODO + ').'
			RETURN -7
		END
	END

	SET @CORR_ACCION_USADA = @ID_ACCION

	-- =========================================================================
	-- PASO 6 — Primera vez + ENVIAR: crear instancia (GUARDAR) y luego avanzar
	-- =========================================================================
	IF @ES_NUEVO = 1 AND @V_OPERACION = 2
	BEGIN
		SELECT TOP 1 @ACCION_GUARDAR = CORR_ACCION
		FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
		  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 4
		  AND PERMITIDO = 1 AND ACTIVO = 1
		ORDER BY CORR_ACCION ASC

		IF @ACCION_GUARDAR IS NULL SET @ACCION_GUARDAR = 1

		EXEC dbo.EjecutarFlujoProceso
			@i_CORR_EMPRESA = @EMPRESA,
			@i_CODIGO_OPCION = @CODIGO_OPCION,
			@i_idDocumento = @CORR_REQUISICION_PERSONAL,
			@i_idUnidadDocumento = @UNIDAD_DOC,
			@i_idAccion = @ACCION_GUARDAR,
			@i_login = @LOGIN_SISTEMA,
			@i_Observacion = N'La requisición está en borrador.',
			@o_idEstadoDocumento = @ESTADO_TMP OUTPUT,
			@o_Error = @ERROR_TMP OUTPUT

		IF @ERROR_TMP IS NOT NULL
		BEGIN
			SET @CORR_ESTADO = @ESTADO_TMP
			SET @MENSAJE_ERROR = 'Error al crear (GUARDAR) previo a ENVIAR: ' + @ERROR_TMP
			RETURN -9
		END
	END

	-- =========================================================================
	-- PASO 7 — Ejecutar operación en el motor
	-- =========================================================================
	EXEC dbo.EjecutarFlujoProceso
		@i_CORR_EMPRESA = @EMPRESA,
		@i_CODIGO_OPCION = @CODIGO_OPCION,
		@i_idDocumento = @CORR_REQUISICION_PERSONAL,
		@i_idUnidadDocumento = @UNIDAD_DOC,
		@i_idAccion = @ID_ACCION,
		@i_login = @LOGIN_SISTEMA,
		@i_Observacion = @OBSERVACION,
		@o_idEstadoDocumento = @CORR_ESTADO OUTPUT,
		@o_Error = @MENSAJE_ERROR OUTPUT

	IF @MENSAJE_ERROR IS NOT NULL
		RETURN -10

	-- =========================================================================
	-- PASO 8 — Mapear estado del motor → CORR_ESTADO_REQUISICION (negocio)
	--   1 Borrador | 2 En Aprobación | 3 Devuelta | 4 Rechazada | 5 Aprobada
	-- =========================================================================
	IF @CORR_ESTADO IS NOT NULL
	BEGIN
		SELECT @V_NOMBRE_ESTADO = LEFT(NOMBRE_ESTADO, 100)
		FROM dbo.SEG_FLUJO_ESTADO
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_ESTADO = @CORR_ESTADO

		SET @ESTADO_NEGOCIO = CASE
			WHEN @V_NOMBRE_ESTADO = N'Aprobada' THEN 5
			WHEN @V_NOMBRE_ESTADO LIKE N'Rechaz%' THEN 4
			WHEN @V_NOMBRE_ESTADO LIKE N'Devuel%' THEN 3
			WHEN @V_NOMBRE_ESTADO LIKE N'%Aprobaci%' THEN 2
			WHEN @V_NOMBRE_ESTADO LIKE N'Borrador%' OR @V_NOMBRE_ESTADO = N'Borrador' THEN 1
			ELSE NULL
		END

		IF @ESTADO_NEGOCIO IS NULL
		BEGIN
			-- Fallback por flags del catálogo de flujo
			SELECT @ESTADO_NEGOCIO = CASE
				WHEN ES_FINAL = 1 AND @CORR_ESTADO = @EST_APROBADA THEN 5
				WHEN ES_FINAL = 1 AND @CORR_ESTADO = @EST_RECHAZADA THEN 4
				WHEN ES_INICIAL = 1 THEN 1
				ELSE 2
			END
			FROM dbo.SEG_FLUJO_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_ESTADO = @CORR_ESTADO
		END

		UPDATE dbo.SC_REQUISICION_PERSONAL
		SET CORR_ESTADO_REQUISICION = @ESTADO_NEGOCIO,
			FECHA_APROBACION = CASE
				WHEN @ESTADO_NEGOCIO = 5 THEN CAST(GETDATE() AS DATE)
				ELSE FECHA_APROBACION
			END,
			USUARIO_ACTU = @LOGIN_SISTEMA,
			ESTACION_ACTU = HOST_NAME(),
			FECHA_ACTU = GETDATE()
		WHERE CORR_EMPRESA = @EMPRESA
		  AND CORR_REQUISICION_PERSONAL = @CORR_REQUISICION_PERSONAL

		SET @NOMBRE_ESTADO = @V_NOMBRE_ESTADO
		SET @CORR_ESTADO_REQUISICION = @ESTADO_NEGOCIO
	END

	SELECT @CORR_PASO_ACTUAL = CORR_PASO_ACTUAL
	FROM dbo.SEG_FLUJO_INSTANCIA
	WHERE CORR_EMPRESA = @EMPRESA
	  AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND CORR_DOCUMENTO = @CORR_REQUISICION_PERSONAL
	  AND ACTIVO = 1

	RETURN 0
END
GO
