SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_BAN_CONCILIA_BANCARIA_PENDIENTE]
(
	@TIPO_CONSULTA int,
	@CORR_EMPRESA int=NULL,
	@CORR_CUENTA_BANCO int=NULL,
	@CORR_CONCILIACION int=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		IF EXISTS(SELECT 1 
				  FROM BAN_CUENTA_BANCARIA A
				  INNER JOIN CON_CATALOGO_CUENTA_AUXI B ON B.CORR_EMPRESA = A.CORR_EMPRESA AND B.CORR_CUENTA_BANCO = A.CORR_CUENTA_BANCO AND B.CUENTA_CONTABLE = A.CUENTA_CONTABLE
				  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
				  AND A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO)
		BEGIN
			SELECT B.CORR_EMPRESA 
			 , B.ANIO_PERIODO 
			 , B.MES_PERIODO 
			 , B.CORR_CLASE_PARTIDA 
			 , B.CORR_PARTIDA 
			 , B.NUMERO_DOCUMENTO 
			 , B.FECHA_PARTIDA 
			 , B.NOMBRE_CLASE_PARTIDA 
			 , B.ESTADO_PARTIDA 
			 , B.CORR_PARTIDA_DETA 
			 , C.CUENTA_CONTABLE
			 , B.MONTO_CARGO 
			 , B.MONTO_ABONO 
			 , B.MONTO_CARGO_FORANEA
			 , B.MONTO_ABONO_FORANEA
			 , B.NOMBRE_TRAN 
			 , B.ESTA_CONCILIA
			FROM BAN_CONCILIA_BANCARIA A
			INNER JOIN BAN_CUENTA_BANCARIA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=C.CORR_CUENTA_BANCO
			INNER JOIN CON_CATALOGO_CUENTA_AUXI G ON C.CORR_EMPRESA=G.CORR_EMPRESA AND C.CUENTA_CONTABLE=G.CUENTA_CONTABLE AND C.CORR_CUENTA_BANCO=G.CORR_CUENTA_BANCO
			INNER JOIN V_BAN_CONCILIA_PENDIENTE B ON G.CORR_EMPRESA=B.CORR_EMPRESA AND G.CUENTA_CONTABLE=B.CUENTA_CONTABLE AND G.CORR_AUXILIAR=B.CORR_AUXILIAR
			LEFT OUTER JOIN BAN_CONCILIA_BANCARIA_DETA D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=D.CORR_CUENTA_BANCO AND A.CORR_CONCILIACION=D.CORR_CONCILIACION
						AND B.CORR_EMPRESA=D.CORR_EMPRESA AND B.ANIO_PERIODO=D.ANIO_PERIODO AND B.MES_PERIODO=D.MES_PERIODO AND B.CORR_CLASE_PARTIDA=D.CORR_CLASE_PARTIDA AND B.CORR_PARTIDA=D.CORR_PARTIDA AND B.CORR_PARTIDA_DETA=D.CORR_PARTIDA_DETA		
			LEFT OUTER JOIN BAN_CONCILIA_BANCARIA_DETA F ON B.CORR_EMPRESA=F.CORR_EMPRESA AND B.ANIO_PERIODO=F.ANIO_PERIODO AND B.MES_PERIODO=F.MES_PERIODO AND B.CORR_CLASE_PARTIDA=F.CORR_CLASE_PARTIDA AND B.CORR_PARTIDA=F.CORR_PARTIDA AND B.CORR_PARTIDA_DETA=F.CORR_PARTIDA_DETA
			LEFT OUTER JOIN BAN_CONCILIA_BANCARIA E ON F.CORR_EMPRESA=E.CORR_EMPRESA AND F.CORR_CUENTA_BANCO=E.CORR_CUENTA_BANCO AND F.CORR_CONCILIACION=E.CORR_CONCILIACION
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND A.CORR_CONCILIACION=@CORR_CONCILIACION
			AND ((ISNULL(B.ESTA_CONCILIA,0)=0 AND B.FECHA_PARTIDA<=A.FECHA_CONCILIACION)
				OR (ISNULL(B.ESTA_CONCILIA,0)=1 AND (YEAR(B.FECHA_PARTIDA)*100)+MONTH(B.FECHA_PARTIDA)<=(YEAR(A.FECHA_CONCILIACION)*100)+MONTH(A.FECHA_CONCILIACION) AND ISNULL(D.CORR_PARTIDA_DETA,0)=0 
					AND (YEAR(A.FECHA_CONCILIACION)*100)+MONTH(A.FECHA_CONCILIACION)<(YEAR(E.FECHA_CONCILIACION)*100)+MONTH(E.FECHA_CONCILIACION)) 
				)

			AND NOT EXISTS(SELECT 1 FROM BAN_PARTIDA_DETA AA
						   INNER JOIN BAN_DOCUMENTO BB ON AA.CORR_EMPRESA=BB.CORR_EMPRESA AND AA.ANIO_PERIODO_DOC=BB.ANIO_PERIODO AND AA.MES_PERIODO_DOC=BB.MES_PERIODO AND AA.CORR_TIPO_MOVIMIENTO=BB.CORR_TIPO_MOVIMIENTO AND AA.CORR_DOCUMENTO=BB.CORR_DOCUMENTO
						   WHERE AA.CORR_EMPRESA=B.CORR_EMPRESA
						   AND AA.ANIO_PERIODO=B.ANIO_PERIODO
						   AND AA.MES_PERIODO=B.MES_PERIODO
						   AND AA.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA
						   AND AA.CORR_PARTIDA=B.CORR_PARTIDA
						   AND AA.CORR_PARTIDA_DETA=B.CORR_PARTIDA_DETA
						   AND BB.ESTADO_DOCUMENTO='AN'
						   AND BB.FECHA_ANULACION<=A.FECHA_CONCILIACION
						)
			AND B.ESTADO_PARTIDA='AP'
			AND (B.MONTO_ABONO+B.MONTO_CARGO)>0
			ORDER BY B.ANIO_PERIODO DESC, B.MES_PERIODO DESC, B.FECHA_PARTIDA DESC, B.NUMERO_DOCUMENTO ASC
		END ELSE
			SELECT B.CORR_EMPRESA 
			, B.ANIO_PERIODO 
			, B.MES_PERIODO 
			, B.CORR_CLASE_PARTIDA 
			, B.CORR_PARTIDA 
			, B.NUMERO_DOCUMENTO 
			, B.FECHA_PARTIDA 
			, B.NOMBRE_CLASE_PARTIDA 
			, B.ESTADO_PARTIDA 
			, B.CORR_PARTIDA_DETA 
			, C.CUENTA_CONTABLE
			, B.MONTO_CARGO 
			, B.MONTO_ABONO 
			, B.MONTO_CARGO_FORANEA
			, B.MONTO_ABONO_FORANEA
			, B.NOMBRE_TRAN 
			, B.ESTA_CONCILIA
			FROM BAN_CONCILIA_BANCARIA A
			INNER JOIN BAN_CUENTA_BANCARIA C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=C.CORR_CUENTA_BANCO
			INNER JOIN V_BAN_CONCILIA_PENDIENTE B ON C.CORR_EMPRESA=B.CORR_EMPRESA AND C.CUENTA_CONTABLE=B.CUENTA_CONTABLE
			LEFT OUTER JOIN BAN_CONCILIA_BANCARIA_DETA D ON A.CORR_EMPRESA=D.CORR_EMPRESA AND A.CORR_CUENTA_BANCO=D.CORR_CUENTA_BANCO AND A.CORR_CONCILIACION=D.CORR_CONCILIACION
						AND B.CORR_EMPRESA=D.CORR_EMPRESA AND B.ANIO_PERIODO=D.ANIO_PERIODO AND B.MES_PERIODO=D.MES_PERIODO AND B.CORR_CLASE_PARTIDA=D.CORR_CLASE_PARTIDA AND B.CORR_PARTIDA=D.CORR_PARTIDA AND B.CORR_PARTIDA_DETA=D.CORR_PARTIDA_DETA		

			LEFT OUTER JOIN BAN_CONCILIA_BANCARIA_DETA F ON B.CORR_EMPRESA=F.CORR_EMPRESA AND B.ANIO_PERIODO=F.ANIO_PERIODO AND B.MES_PERIODO=F.MES_PERIODO AND B.CORR_CLASE_PARTIDA=F.CORR_CLASE_PARTIDA AND B.CORR_PARTIDA=F.CORR_PARTIDA AND B.CORR_PARTIDA_DETA=F.CORR_PARTIDA_DETA
			LEFT OUTER JOIN BAN_CONCILIA_BANCARIA E ON F.CORR_EMPRESA=E.CORR_EMPRESA AND F.CORR_CUENTA_BANCO=E.CORR_CUENTA_BANCO AND F.CORR_CONCILIACION=E.CORR_CONCILIACION		
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO
			AND A.CORR_CONCILIACION=@CORR_CONCILIACION
			AND ((ISNULL(B.ESTA_CONCILIA,0)=0 AND B.FECHA_PARTIDA<=A.FECHA_CONCILIACION)
				OR (ISNULL(B.ESTA_CONCILIA,0)=1 AND (YEAR(B.FECHA_PARTIDA)*100)+MONTH(B.FECHA_PARTIDA)<=(YEAR(A.FECHA_CONCILIACION)*100)+MONTH(A.FECHA_CONCILIACION) AND ISNULL(D.CORR_PARTIDA_DETA,0)=0 
					AND (YEAR(A.FECHA_CONCILIACION)*100)+MONTH(A.FECHA_CONCILIACION)<(YEAR(E.FECHA_CONCILIACION)*100)+MONTH(E.FECHA_CONCILIACION)) 
				)
			AND NOT EXISTS(SELECT 1 FROM BAN_PARTIDA_DETA AA
						   INNER JOIN BAN_DOCUMENTO BB ON AA.CORR_EMPRESA=BB.CORR_EMPRESA AND AA.ANIO_PERIODO_DOC=BB.ANIO_PERIODO AND AA.MES_PERIODO_DOC=BB.MES_PERIODO AND AA.CORR_TIPO_MOVIMIENTO=BB.CORR_TIPO_MOVIMIENTO AND AA.CORR_DOCUMENTO=BB.CORR_DOCUMENTO
						   WHERE AA.CORR_EMPRESA=B.CORR_EMPRESA
						   AND AA.ANIO_PERIODO=B.ANIO_PERIODO
						   AND AA.MES_PERIODO=B.MES_PERIODO
						   AND AA.CORR_CLASE_PARTIDA=B.CORR_CLASE_PARTIDA
						   AND AA.CORR_PARTIDA=B.CORR_PARTIDA
						   AND AA.CORR_PARTIDA_DETA=B.CORR_PARTIDA_DETA
						   AND BB.ESTADO_DOCUMENTO='AN'
						   AND BB.FECHA_ANULACION<=A.FECHA_CONCILIACION
						)
			AND B.ESTADO_PARTIDA='AP'
			AND (B.MONTO_ABONO+B.MONTO_CARGO)>0
			ORDER BY B.ANIO_PERIODO DESC, B.MES_PERIODO DESC, B.FECHA_PARTIDA DESC, B.NUMERO_DOCUMENTO ASC
		END
	END 
GO

