
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_IMPR_BAN_CHEQUE_EMITIDOS]
(
	@CORR_EMPRESA int,
	@CORR_CUENTA_BANCO int=NULL,
	@FECHA_INICIAL DATE,
	@FECHA_FINAL DATE,
	@NUMERO_DOCUMENTO_INICIAL int=0,
	@NUMERO_DOCUMENTO_FINAL int=0
)
AS
BEGIN
	SET NOCOUNT ON
	

	IF @NUMERO_DOCUMENTO_INICIAL = 0 AND @NUMERO_DOCUMENTO_FINAL = 0 
	BEGIN
		SELECT *
		FROM V_BAN_CHEQUES_EMITIDOS A	
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND (A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO OR ISNULL(@CORR_CUENTA_BANCO,0)=0)
		AND A.FECHA_EMISION>=@FECHA_INICIAL
		AND A.FECHA_EMISION<=@FECHA_FINAL
		AND (A.NUMERO_DOCUMENTO>=@NUMERO_DOCUMENTO_INICIAL OR @NUMERO_DOCUMENTO_INICIAL=0)
		AND (A.NUMERO_DOCUMENTO<=@NUMERO_DOCUMENTO_FINAL OR @NUMERO_DOCUMENTO_FINAL=0)
		AND A.CLASE_MOVIMIENTO='CHQ'
		ORDER BY A.CORR_EMPRESA,A.NUMERO_DOCUMENTO
	END	
	ELSE
	BEGIN
		DECLARE @TEMP TABLE (
			NUMERO INT
		)
		DECLARE @CONTADOR INT
		SET @CONTADOR=@NUMERO_DOCUMENTO_INICIAL
		WHILE (@CONTADOR<=@NUMERO_DOCUMENTO_FINAL)
		BEGIN
			INSERT INTO @TEMP (NUMERO)
			VALUES (@CONTADOR)

			SET @CONTADOR=@CONTADOR+1
		END
SELECT @CORR_EMPRESA CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_TIPO_MOVIMIENTO, NOMBRE_TIPO_MOVIMIENTO, CLASE_MOVIMIENTO, CORR_DOCUMENTO, CORR_CUENTA_BANCO, ISNULL(NOMBRE_CUENTA_BANCO,'CHEQUE NO IMPRESO') NOMBRE_CUENTA_BANCO, NUMERO_DOCUMENTO, FECHA_EMISION, ISNULL(NOMBRE_PARTIDA,'CHEQUE NO IMPRESO') NOMBRE_PARTIDA, CORR_PROVEEDOR, NOMBRE_PROVEEDOR, CORR_EMPLEADO, CORR_CLIENTE, ISNULL(NOMBRE_BENEFICIARIO,T.NUMERO) NOMBRE_BENEFICIARIO, MONTO_DOCUMENTO, ESTADO_DOCUMENTO, NOMBRE_ESTADO_DOCUMENTO, ESTA_CONTABILIZADO, HECHO_POR, REVISADO_POR, APROBADO_POR, CONTADOR_REVISO, AUDITOR_REVISO, FECHA_GENERACION, FECHA_APROBADO, FECHA_IMPRESO, CANTIDAD_LETRAS, USUARIO_CREA, FECHA_CREA, ESTACION_CREA, USUARIO_ACTU, FECHA_ACTU, ESTACION_ACTU, CORR_MOVIMIENTO, CORR_MOVIMIENTO_DESTINO, CORR_TIPO_CHEQUE, NOMBRE_TIPO_CHEQUE, CLASE_TIPO_CHEQUE, CORR_CHEQUERA, SERIE_CHEQUE, CORR_CUENTA_BANCO_DESTINO, NUMERO_CUENTA_BANCO_DESTINO, NUMERO_CUENTA_DESTINO_TERCERO, MONTO_DESTINO, ANIO_PERIODO_CHEQUE, MES_PERIODO_CHEQUE, CORR_TIPO_MOVIMIENTO_CHEQUE, CORR_DOCUMENTO_CHEQUE, FECHA_ANULACION, CORR_MONEDA, NOMBRE_MONEDA, SIMBOLO, FACTOR_CAMBIO, OPERADOR
		, T.NUMERO
		FROM @TEMP T LEFT OUTER JOIN V_BAN_CHEQUES_EMITIDOS A ON T.NUMERO=A.NUMERO_DOCUMENTO AND A.CORR_EMPRESA=@CORR_EMPRESA
		AND (A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO OR ISNULL(@CORR_CUENTA_BANCO,0)=0)
		--AND A.FECHA_EMISION>=@FECHA_INICIAL
		--AND A.FECHA_EMISION<=@FECHA_FINAL
		AND (A.NUMERO_DOCUMENTO>=@NUMERO_DOCUMENTO_INICIAL OR @NUMERO_DOCUMENTO_INICIAL=0 OR T.NUMERO=0)
		AND (A.NUMERO_DOCUMENTO<=@NUMERO_DOCUMENTO_FINAL OR @NUMERO_DOCUMENTO_FINAL=0 OR T.NUMERO=0)
		AND A.CLASE_MOVIMIENTO='CHQ'
	
		--PARA GENERAR DATOS QUE NO ESTAN IMPRESOS**************
		--WHERE A.CORR_SUSCRIPCION=@CORR_SUSCRIPCION
		--AND A.CORR_CONFI_PAIS=@CORR_CONFI_PAIS
		--AND A.CORR_EMPRESA=@CORR_EMPRESA
		--AND (A.CORR_CUENTA_BANCO=@CORR_CUENTA_BANCO OR ISNULL(@CORR_CUENTA_BANCO,0)=0)
		--AND A.FECHA_EMISION>=@FECHA_INICIAL
		--AND A.FECHA_EMISION<=@FECHA_FINAL
		--AND (A.NUMERO_DOCUMENTO>=@NUMERO_DOCUMENTO_INICIAL OR @NUMERO_DOCUMENTO_INICIAL=0)
		--AND (A.NUMERO_DOCUMENTO<=@NUMERO_DOCUMENTO_FINAL OR @NUMERO_DOCUMENTO_FINAL=0)
		--AND A.CLASE_MOVIMIENTO='CHQ'
		ORDER BY A.CORR_EMPRESA,A.NUMERO_DOCUMENTO
	END
	SELECT A.CORR_EMPRESA
	,A.NOMBRE_EMPRESA
	,'' PERIODO
	,LOGO_1 LOGO1
	,LOGO_2 LOGO2
	,'' TITULO_REPORTE
	,'' NOMBRE_SISTEMA
	,GETDATE() FECHA_IMPRESION
	FROM GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA
END
GO

