SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_CANCELAR_SOLICITUD]
(
		@CORR_EMPRESA int,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_TIPO_MOVIMIENTO int,
	@CORR_DOCUMENTO int OUTPUT,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output,
	@GENERA_DETALLE BIT = 1
)
AS
	DECLARE @MONTO_CARGO DECIMAL(12,2), @MONTO_ABONO DECIMAL(12,2),@CUENTA_CONTABLE_BANCO VARCHAR(30)
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		DECLARE @CLASE_TIPO_CHEQUE VARCHAR(3), @ESTADO_DOCUMENTO varchar(2), @ANIO_PERIODO_CHEQUE int, @MES_PERIODO_CHEQUE int, @CORR_TIPO_MOVIMIENTO_CHEQUE int, @CORR_DOCUMENTO_CHEQUE int, @SOLICITADO_POR varchar(30), @FECHA_SOLICITADO date
	
		SELECT @ESTADO_DOCUMENTO=ESTADO_DOCUMENTO,
		@ANIO_PERIODO_CHEQUE=ANIO_PERIODO_CHEQUE,@MES_PERIODO_CHEQUE=MES_PERIODO_CHEQUE,@CORR_TIPO_MOVIMIENTO_CHEQUE=CORR_TIPO_MOVIMIENTO_CHEQUE,@CORR_DOCUMENTO_CHEQUE=CORR_DOCUMENTO_CHEQUE 
		FROM BAN_SOLI_CHEQUE 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND ANIO_PERIODO=@ANIO_PERIODO 
		AND MES_PERIODO=@MES_PERIODO 
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO 
		
		DECLARE @ESTADO_CHEQUE VARCHAR(2)
		SELECT @ESTADO_CHEQUE=ESTADO_DOCUMENTO 
		FROM BAN_DOCUMENTO 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND ANIO_PERIODO=@ANIO_PERIODO_CHEQUE  
		AND MES_PERIODO=@MES_PERIODO_CHEQUE 
		AND CORR_TIPO_MOVIMIENTO=@CORR_TIPO_MOVIMIENTO_CHEQUE
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO_CHEQUE 
		
		IF @ESTADO_CHEQUE IN ('AP','IM','AN')
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='No se puede cancelar esta solicitud, porque el cheque ya está aplicado, impreso o anulado.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END
		
		IF @ESTADO_DOCUMENTO <> 'SO'
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30001,@SYS_MENSAJE_ERROR='No se puede cancelar esta solicitud, porque no ha sido enviada o ya está autorizada.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END
		
		SELECT @SOLICITADO_POR=@SYS_LOGIN_USUARIO, @FECHA_SOLICITADO=GETDATE()
		
		UPDATE BAN_SOLI_CHEQUE SET
		ESTADO_DOCUMENTO='DI', FECHA_SOLICITADO=@FECHA_SOLICITADO, SOLICITADO_POR=@SOLICITADO_POR 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND ANIO_PERIODO=@ANIO_PERIODO 
		AND MES_PERIODO=@MES_PERIODO 
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO 
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()
		
		-- bitacora omitida
FINA:
END
GO
