SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_DATA_SEG_CONFIG_OPCION]
(
	@TIPO_CONSULTA int,
	@CODIGO_SISTEMA varchar(30)=NULL,
	@CODIGO_MENU varchar(10)=NULL,
	@CODIGO_OPCION varchar(30)=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		SELECT * FROM V_SEG_CONFIG_OPCION	    
		ORDER BY ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT * FROM V_SEG_CONFIG_OPCION	    
			ORDER BY ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION
		END ELSE
		IF @OPCION_CONSULTA=1
		BEGIN
			SELECT DISTINCT CODIGO_SISTEMA
			,NOMBRE_SISTEMA
			,ORDEN_SISTEMA
			FROM V_SEG_CONFIG_OPCION	    
			ORDER BY ORDEN_SISTEMA
		END
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_SEG_CONFIG_OPCION
		WHERE CODIGO_SISTEMA=@CODIGO_SISTEMA
		AND CODIGO_MENU=@CODIGO_MENU
		AND CODIGO_OPCION=@CODIGO_OPCION
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT NOMBRE_OPCION FROM V_SEG_CONFIG_OPCION
			WHERE CODIGO_SISTEMA=@CODIGO_SISTEMA
			AND CODIGO_MENU=@CODIGO_MENU
			AND CODIGO_OPCION=@CODIGO_OPCION
		END
	END

END
GO
