SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_CHEQUERA]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@CORR_CUENTA_BANCO INT,
	@CORR_CHEQUERA INT OUTPUT,
	@NUMERO_CHEQUE_INICIAL INT = 0,
	@NUMERO_CHEQUE_FINAL INT = 0,
	@NUMERO_CHEQUE_ACTUAL INT = 0,
	@SERIE_CHEQUE VARCHAR(10) = '',
	@ESTADO_CHEQUERA VARCHAR(2) = 'AC',
	@VALIDAR_PERMISO BIT = 0,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		@SYS_NUMERO_ERROR = 0,
		@SYS_MENSAJE_ERROR = N'',
		@SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1, 2)
		BEGIN
			IF ISNULL(@NUMERO_CHEQUE_INICIAL, 0) <= 0
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'El número de cheque inicial no puede ser menor o igual a cero',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF ISNULL(@NUMERO_CHEQUE_FINAL, 0) <= 0
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'El número de cheque final no puede ser menor o igual a cero',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF ISNULL(@NUMERO_CHEQUE_ACTUAL, 0) <= 0
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'El número de cheque actual no puede ser menor o igual a cero',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF ISNULL(@NUMERO_CHEQUE_INICIAL, 0) >= ISNULL(@NUMERO_CHEQUE_FINAL, 0)
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'El número de cheque inicial no puede ser mayor o igual al número final',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF (
				ISNULL(@NUMERO_CHEQUE_ACTUAL, 0) > ISNULL(@NUMERO_CHEQUE_FINAL, 0)
				OR ISNULL(@NUMERO_CHEQUE_ACTUAL, 0) < ISNULL(@NUMERO_CHEQUE_INICIAL, 0)
			)
			BEGIN
				SELECT
					@SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'El número de cheque actual debe estar entre el número inicial y el final',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF @VALIDAR_PERMISO = 1 AND @TIPO_ACTUALIZA = 2
			BEGIN
				IF EXISTS (
					SELECT 1
					FROM dbo.BAN_CUENTA_BANCARIA
					WHERE CORR_EMPRESA = @CORR_EMPRESA
						AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO
						AND ISNULL(NO_PERMITE_MODIFICAR, 0) = 1
				)
				BEGIN
					SELECT
						@SYS_NUMERO_ERROR = 30000,
						@SYS_MENSAJE_ERROR = N'No se permiten modificaciones a esta chequera',
						@SYS_FILAS_AFECTADAS = 0;
					GOTO FINA;
				END;
			END;
		END;

		IF @TIPO_ACTUALIZA = 1
		BEGIN
			SELECT @CORR_CHEQUERA = ISNULL(MAX(CORR_CHEQUERA), 0) + 1
			FROM dbo.BAN_CHEQUERA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO;

			SET @ESTADO_CHEQUERA = 'AC';

			INSERT INTO dbo.BAN_CHEQUERA
			(
				CORR_EMPRESA,
				CORR_CUENTA_BANCO,
				CORR_CHEQUERA,
				NUMERO_CHEQUE_INICIAL,
				NUMERO_CHEQUE_FINAL,
				NUMERO_CHEQUE_ACTUAL,
				SERIE_CHEQUE,
				ESTADO_CHEQUERA
			)
			VALUES
			(
				@CORR_EMPRESA,
				@CORR_CUENTA_BANCO,
				@CORR_CHEQUERA,
				@NUMERO_CHEQUE_INICIAL,
				@NUMERO_CHEQUE_FINAL,
				@NUMERO_CHEQUE_ACTUAL,
				@SERIE_CHEQUE,
				@ESTADO_CHEQUERA
			);
		END
		ELSE IF @TIPO_ACTUALIZA = 2
		BEGIN
			UPDATE dbo.BAN_CHEQUERA
			SET
				NUMERO_CHEQUE_INICIAL = @NUMERO_CHEQUE_INICIAL,
				NUMERO_CHEQUE_FINAL = @NUMERO_CHEQUE_FINAL,
				NUMERO_CHEQUE_ACTUAL = @NUMERO_CHEQUE_ACTUAL,
				SERIE_CHEQUE = @SERIE_CHEQUE,
				ESTADO_CHEQUERA = @ESTADO_CHEQUERA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO
				AND CORR_CHEQUERA = @CORR_CHEQUERA;
		END
		ELSE IF @TIPO_ACTUALIZA = 3
		BEGIN
			DELETE FROM dbo.BAN_CHEQUERA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO
				AND CORR_CHEQUERA = @CORR_CHEQUERA;
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT
			@SYS_NUMERO_ERROR = ERROR_NUMBER(),
			@SYS_MENSAJE_ERROR = ERROR_MESSAGE(),
			@SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO
