SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_SEG_USUARIO]
(
	@TIPO_CONSULTA int,	
	@LOGIN_SISTEMA varchar(30)=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1
	BEGIN
		SELECT A.LOGIN_SISTEMA, A.NOMBRE_USUARIO, NULL CLAVE_USUARIO, NULL CLAVE_USUARIO_SAL, A.CORREO_ELECTRONICO, A.TIPO_USUARIO, A.NOMBRE_TIPO_USUARIO, A.ESTADO_USUARIO, A.NOMBRE_ESTADO_USUARIO, A.IDIOMA, A.USUARIO_CREA, A.FECHA_CREA, A.ESTACION_CREA, A.USUARIO_ACTU, A.FECHA_ACTU, A.ESTACION_ACTU, A.CORR_EMPRESA, A.NOMBRE_EMPRESA, A.FOTO_PERFIL, A.FOTO_FIRMA
		FROM V_SEG_USUARIO A
	END ELSE
	IF @TIPO_CONSULTA=2
	BEGIN
		IF @OPCION_CONSULTA = 0
		BEGIN
			SELECT A.LOGIN_SISTEMA, A.NOMBRE_USUARIO 
		FROM V_SEG_USUARIO A
		END ELSE
		IF @OPCION_CONSULTA = 1
		BEGIN
			SELECT TOP 1 A.LOGIN_SISTEMA, A.NOMBRE_USUARIO
			FROM V_SEG_USUARIO A
			WHERE A.LOGIN_SISTEMA=@LOGIN_SISTEMA
		END ELSE
		IF @OPCION_CONSULTA = 2
		BEGIN
			SELECT A.LOGIN_SISTEMA, A.NOMBRE_USUARIO 
			FROM V_SEG_USUARIO_LOOKUP A
		END
	END ELSE
	IF @TIPO_CONSULTA=3
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT A.LOGIN_SISTEMA, A.NOMBRE_USUARIO, NULL CLAVE_USUARIO, NULL CLAVE_USUARIO_SAL, A.CORREO_ELECTRONICO, A.TIPO_USUARIO, A.NOMBRE_TIPO_USUARIO, A.ESTADO_USUARIO, A.NOMBRE_ESTADO_USUARIO, A.IDIOMA, A.USUARIO_CREA, A.FECHA_CREA, A.ESTACION_CREA, A.USUARIO_ACTU, A.FECHA_ACTU, A.ESTACION_ACTU, A.CORR_EMPRESA, A.NOMBRE_EMPRESA, A.FOTO_PERFIL, A.FOTO_FIRMA
			FROM V_SEG_USUARIO	A
			WHERE A.LOGIN_SISTEMA=@LOGIN_SISTEMA 
		END ELSE
		IF @OPCION_CONSULTA=1
		BEGIN
			SELECT A.* FROM V_SEG_USUARIO A
			WHERE A.LOGIN_SISTEMA=@LOGIN_SISTEMA
		END
	END ELSE
	IF @TIPO_CONSULTA=4
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT A.CLAVE_USUARIO FROM V_SEG_USUARIO A
			WHERE A.LOGIN_SISTEMA=@LOGIN_SISTEMA
		END ELSE
		IF @OPCION_CONSULTA=1
		BEGIN
			SELECT A.NOMBRE_USUARIO FROM V_SEG_USUARIO A
			WHERE A.LOGIN_SISTEMA=@LOGIN_SISTEMA
		END
	END
END
GO
