/*
  ACA_PROSPECTO_BECA — consulta administrativa de solicitudes de beca
  Pantalla: Académico → Consultas → Solicitudes de beca (/aca-prospecto-beca)

  Ejecutar:
    sqlcmd -S <srv> -d SGUEES -U <user> -P <pass> -f 65001 -i SGUEES-DB/Scripts/ACA_PROSPECTO_BECA.sql

  Qué hace: vistas de consulta para el listado por ciclo y el cuestionario
            contestado, más la tabla de bandas. La opción de menú queda
            junto a Prospectos.
  Cómo lo hace: solo BORRADOR y ENVIADA. No altera las vistas que ya usa
            el formulario del aspirante. Las bandas se aplican al leer
            estas vistas. No hay triggers.
*/
USE SGUEES;
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/* ==========================================================================
   ACA_PROSPECTO_BECA_BANDA
   Qué hace: puntaje por rango numérico. El catálogo de opciones no puede
             representar estas reglas.
   Cómo lo hace: PROMEDIO_BACHILLERATO es el promedio de primer y segundo
             año (PAES no entra). DEPENDIENTES es la pregunta numérica de
             personas a cargo. El límite superior es exclusivo.
   ========================================================================== */
IF OBJECT_ID(N'dbo.ACA_PROSPECTO_BECA_BANDA', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ACA_PROSPECTO_BECA_BANDA
    (
        CORR_BANDA     int            NOT NULL IDENTITY(1, 1),
        CODIGO_REGLA   varchar(30)    NOT NULL,
        VALOR_DESDE    decimal(10, 2) NOT NULL,
        VALOR_HASTA    decimal(10, 2) NOT NULL,
        PUNTAJE        decimal(10, 2) NOT NULL,
        ACTIVO         bit            NOT NULL CONSTRAINT DF_ACA_PROSPECTO_BECA_BANDA_ACTIVO DEFAULT (1),
        CORR_EMPRESA   int            NOT NULL,
        USUARIO_CREA   varchar(30)    NOT NULL,
        ESTACION_CREA  varchar(30)    NOT NULL,
        FECHA_CREA     datetime       NOT NULL CONSTRAINT DF_ACA_PROSPECTO_BECA_BANDA_FECHA DEFAULT (GETDATE()),
        CONSTRAINT PK_ACA_PROSPECTO_BECA_BANDA PRIMARY KEY (CORR_BANDA)
    );
END
GO

DELETE FROM dbo.ACA_PROSPECTO_BECA_BANDA
WHERE CODIGO_REGLA IN (N'PROMEDIO_BACHILLERATO', N'DEPENDIENTES');

INSERT INTO dbo.ACA_PROSPECTO_BECA_BANDA
    (CODIGO_REGLA, VALOR_DESDE, VALOR_HASTA, PUNTAJE, ACTIVO, CORR_EMPRESA, USUARIO_CREA, ESTACION_CREA)
VALUES
    (N'PROMEDIO_BACHILLERATO',  9.00, 10.01, 35, 1, 1, N'admin', N'SISTEMA'),
    (N'PROMEDIO_BACHILLERATO',  8.50,  9.00, 30, 1, 1, N'admin', N'SISTEMA'),
    (N'PROMEDIO_BACHILLERATO',  8.00,  8.50, 25, 1, 1, N'admin', N'SISTEMA'),
    (N'PROMEDIO_BACHILLERATO',  7.00,  8.00, 18, 1, 1, N'admin', N'SISTEMA'),
    (N'PROMEDIO_BACHILLERATO',  6.00,  7.00,  8, 1, 1, N'admin', N'SISTEMA'),
    (N'PROMEDIO_BACHILLERATO',  0.00,  6.00,  0, 1, 1, N'admin', N'SISTEMA'),
    (N'DEPENDIENTES',           0.00,  1.00,  5, 1, 1, N'admin', N'SISTEMA'),
    (N'DEPENDIENTES',           1.00,  3.00,  3, 1, 1, N'admin', N'SISTEMA'),
    (N'DEPENDIENTES',           3.00,  5.00,  1, 1, 1, N'admin', N'SISTEMA'),
    (N'DEPENDIENTES',           5.00, 1000.00, 0, 1, 1, N'admin', N'SISTEMA');
GO

/* ==========================================================================
   V_ACA_PROSPECTO_BECA_CONSULTA
   Qué hace: una fila por solicitud de beca en borrador o enviada, con los
             datos del prospecto y el resultado de la evaluación.
   Cómo lo hace: parte de ACA_PROSPECTO_BECA, trae persona, beca, ciclo y
             carrera del plan del prospecto. La API filtra por CORR_EMPRESA,
             ANIO y NUMERO_PERIODO.
   ========================================================================== */
CREATE OR ALTER VIEW dbo.V_ACA_PROSPECTO_BECA_CONSULTA
AS
SELECT
    PB.CORR_EMPRESA,
    PB.CORR_PROSPECTO_BECA,
    PB.CORR_PROSPECTO,
    P.CODIGO_PROSPECTO,
    LTRIM(RTRIM(PP.NOMBRES))
        + ' ' + LTRIM(RTRIM(PP.APELLIDO1))
        + ISNULL(' ' + NULLIF(LTRIM(RTRIM(PP.APELLIDO2)), ''), '') AS NOMBRE_COMPLETO,
    PP.DUI,
    CA.NOMBRE_CARRERA,
    PB.CORR_BECA,
    BT.CODIGO_BECA,
    BT.NOMBRE_BECA,
    PB.CORR_PERIODO_ACADEMICO,
    PA.ANIO,
    PA.NUMERO_PERIODO,
    CAST(PA.ANIO AS VARCHAR(4)) + '-' + RIGHT('0' + CAST(PA.NUMERO_PERIODO AS VARCHAR(2)), 2) AS CICLO,
    PB.ESTADO_BECA,
    CASE PB.ESTADO_BECA
        WHEN 'BORRADOR' THEN 'Borrador'
        WHEN 'ENVIADA' THEN 'Enviada'
        ELSE PB.ESTADO_BECA
    END AS ESTADO_BECA_TEXTO,
    CAST(ISNULL(PB.PUNTAJE_TOTAL, 0) - ISNULL(G.GUARDADO, 0) + ISNULL(C.CALCULADO, 0) AS decimal(10, 2)) AS PUNTAJE_TOTAL,
    CAST(ISNULL(PB.PORCENTAJE_TOTAL, 0) - ISNULL(G.GUARDADO, 0) + ISNULL(C.CALCULADO, 0) AS decimal(5, 2)) AS PORCENTAJE_TOTAL,
    CASE
        WHEN ISNULL(PB.PUNTAJE_TOTAL, 0) = ISNULL(PB.PUNTAJE_TOTAL, 0) - ISNULL(G.GUARDADO, 0) + ISNULL(C.CALCULADO, 0)
            THEN PB.RESULTADO_EVALUACION
        WHEN ISNULL(PB.PUNTAJE_TOTAL, 0) - ISNULL(G.GUARDADO, 0) + ISNULL(C.CALCULADO, 0) >= 85 THEN 'Potencialmente elegible'
        WHEN ISNULL(PB.PUNTAJE_TOTAL, 0) - ISNULL(G.GUARDADO, 0) + ISNULL(C.CALCULADO, 0) >= 70 THEN 'Potencialmente elegible'
        WHEN ISNULL(PB.PUNTAJE_TOTAL, 0) - ISNULL(G.GUARDADO, 0) + ISNULL(C.CALCULADO, 0) >= 55 THEN 'Elegibilidad condicionada'
        ELSE 'Baja viabilidad actual'
    END AS RESULTADO_EVALUACION,
    CASE
        WHEN ISNULL(PB.PUNTAJE_TOTAL, 0) = ISNULL(PB.PUNTAJE_TOTAL, 0) - ISNULL(G.GUARDADO, 0) + ISNULL(C.CALCULADO, 0)
            THEN PB.PRIORIDAD_EVALUACION
        WHEN ISNULL(PB.PUNTAJE_TOTAL, 0) - ISNULL(G.GUARDADO, 0) + ISNULL(C.CALCULADO, 0) >= 85 THEN 'ALTA'
        WHEN ISNULL(PB.PUNTAJE_TOTAL, 0) - ISNULL(G.GUARDADO, 0) + ISNULL(C.CALCULADO, 0) >= 70 THEN 'MEDIA'
        WHEN ISNULL(PB.PUNTAJE_TOTAL, 0) - ISNULL(G.GUARDADO, 0) + ISNULL(C.CALCULADO, 0) >= 55 THEN 'CONDICIONADA'
        ELSE 'BAJA'
    END AS PRIORIDAD_EVALUACION,
    PB.FECHA_SOLICITUD
FROM dbo.ACA_PROSPECTO_BECA AS PB
INNER JOIN dbo.ACA_PROSPECTO AS P
    ON P.CORR_PROSPECTO = PB.CORR_PROSPECTO
INNER JOIN dbo.ACA_BECA_TIPO AS BT
    ON BT.CORR_BECA = PB.CORR_BECA
INNER JOIN dbo.ACA_PERIODOS_ACADEMICOS AS PA
    ON PA.CORR_PERIODO_ACADEMICO = PB.CORR_PERIODO_ACADEMICO
LEFT JOIN dbo.ACA_PROSPECTO_PERSONA AS PP
    ON PP.CORR_PROSPECTO = PB.CORR_PROSPECTO
LEFT JOIN dbo.ACA_PLANES_ACADEMICOS AS PL
    ON PL.CORR_PLAN_ACADEMICO = P.CORR_PLAN_ACADEMICO
LEFT JOIN dbo.ACA_CARRERAS AS CA
    ON CA.CORR_CARRERA = PL.CORR_CARRERA
OUTER APPLY (
    SELECT ISNULL(SUM(R.PUNTAJE_OBTENIDO), 0) AS GUARDADO
    FROM dbo.ACA_PROSPECTO_BECA_RESPUESTA AS R
    INNER JOIN dbo.ACA_PROSPECTO_BECA_PREGUNTA AS P
        ON P.CORR_PREGUNTA_BECA = R.CORR_PREGUNTA_BECA
    WHERE R.CORR_PROSPECTO_BECA = PB.CORR_PROSPECTO_BECA
      AND P.CODIGO_PREGUNTA IN (
            N'SOC_DEPENDIENTES_ECONOMICOS',
            N'ACA_PROMEDIO_PRIMERO',
            N'ACA_PROMEDIO_SEGUNDO')
) AS G
OUTER APPLY (
    SELECT AVG(R.RESPUESTA_NUMERO) AS PROMEDIO
    FROM dbo.ACA_PROSPECTO_BECA_RESPUESTA AS R
    INNER JOIN dbo.ACA_PROSPECTO_BECA_PREGUNTA AS P
        ON P.CORR_PREGUNTA_BECA = R.CORR_PREGUNTA_BECA
    WHERE R.CORR_PROSPECTO_BECA = PB.CORR_PROSPECTO_BECA
      AND P.CODIGO_PREGUNTA IN (N'ACA_PROMEDIO_PRIMERO', N'ACA_PROMEDIO_SEGUNDO')
      AND R.RESPUESTA_NUMERO IS NOT NULL
) AS PR
OUTER APPLY (
    SELECT
        ISNULL((
            SELECT TOP (1) B.PUNTAJE
            FROM dbo.ACA_PROSPECTO_BECA_RESPUESTA AS R
            INNER JOIN dbo.ACA_PROSPECTO_BECA_PREGUNTA AS P
                ON P.CORR_PREGUNTA_BECA = R.CORR_PREGUNTA_BECA
            INNER JOIN dbo.ACA_PROSPECTO_BECA_BANDA AS B
                ON B.ACTIVO = 1
               AND B.CODIGO_REGLA = N'DEPENDIENTES'
               AND R.RESPUESTA_NUMERO >= B.VALOR_DESDE
               AND R.RESPUESTA_NUMERO < B.VALOR_HASTA
            WHERE R.CORR_PROSPECTO_BECA = PB.CORR_PROSPECTO_BECA
              AND P.CODIGO_PREGUNTA = N'SOC_DEPENDIENTES_ECONOMICOS'
        ), 0)
        + ISNULL((
            SELECT TOP (1) B.PUNTAJE
            FROM dbo.ACA_PROSPECTO_BECA_BANDA AS B
            WHERE B.ACTIVO = 1
              AND B.CODIGO_REGLA = N'PROMEDIO_BACHILLERATO'
              AND PR.PROMEDIO >= B.VALOR_DESDE
              AND PR.PROMEDIO < B.VALOR_HASTA
        ), 0) AS CALCULADO
) AS C
WHERE PB.ESTADO_BECA IN ('BORRADOR', 'ENVIADA')
  AND PA.CORR_AREA_ACADEMICA = 5;
GO

/* ==========================================================================
   V_ACA_PROSPECTO_BECA_RESPUESTA
   Qué hace: cada respuesta guardada del cuestionario, con su puntaje.
   Cómo lo hace: una fila por ACA_PROSPECTO_BECA_RESPUESTA (en opción
             múltiple hay una fila por opción marcada). La API filtra por
             CORR_EMPRESA y CORR_PROSPECTO_BECA.
   ========================================================================== */
CREATE OR ALTER VIEW dbo.V_ACA_PROSPECTO_BECA_RESPUESTA
AS
SELECT
    R.CORR_EMPRESA,
    R.CORR_PROSPECTO_BECA,
    R.CORR_RESPUESTA_BECA,
    S.ORDEN AS ORDEN_SECCION,
    S.NOMBRE_SECCION,
    P.ORDEN AS ORDEN_PREGUNTA,
    P.TEXTO_PREGUNTA,
    P.TIPO_RESPUESTA,
    CASE
        WHEN P.TIPO_RESPUESTA IN ('OPCION_UNICA', 'OPCION_MULTIPLE', 'SI_NO', 'ACEPTACION')
            THEN R.TEXTO_OPCION_HISTORICO
        WHEN P.TIPO_RESPUESTA = 'DOCUMENTO'
            THEN R.ARCHIVO_NOMBRE
        WHEN P.TIPO_RESPUESTA IN ('NUMERO', 'DECIMAL') AND R.RESPUESTA_NUMERO IS NOT NULL
            THEN CASE
                    WHEN R.RESPUESTA_NUMERO = FLOOR(R.RESPUESTA_NUMERO)
                        THEN CONVERT(VARCHAR(40), CONVERT(BIGINT, R.RESPUESTA_NUMERO))
                    ELSE CONVERT(VARCHAR(40), CONVERT(DECIMAL(18, 2), R.RESPUESTA_NUMERO))
                 END
        WHEN P.TIPO_RESPUESTA IN ('TEXTO', 'TEXTO_LARGO')
            THEN R.RESPUESTA_TEXTO
        WHEN R.RESPUESTA_FECHA IS NOT NULL
            THEN CONVERT(VARCHAR(10), R.RESPUESTA_FECHA, 103)
        ELSE COALESCE(R.TEXTO_OPCION_HISTORICO, R.RESPUESTA_TEXTO)
    END AS RESPUESTA,
    CAST(CASE
        WHEN P.CODIGO_PREGUNTA = N'SOC_DEPENDIENTES_ECONOMICOS' THEN ISNULL(DEP.PUNTAJE, 0)
        WHEN P.CODIGO_PREGUNTA IN (N'ACA_PROMEDIO_PRIMERO', N'ACA_PROMEDIO_SEGUNDO')
             AND P.CORR_PREGUNTA_BECA = PR.CORR_PREGUNTA_DESTINO THEN ISNULL(ACA.PUNTAJE, 0)
        WHEN P.CODIGO_PREGUNTA IN (N'ACA_PROMEDIO_PRIMERO', N'ACA_PROMEDIO_SEGUNDO') THEN 0
        ELSE R.PUNTAJE_OBTENIDO
    END AS decimal(10, 2)) AS PUNTAJE_OBTENIDO,
    CAST(CASE
        WHEN P.CODIGO_PREGUNTA = N'SOC_DEPENDIENTES_ECONOMICOS' THEN ISNULL(DEP.PUNTAJE, 0)
        WHEN P.CODIGO_PREGUNTA IN (N'ACA_PROMEDIO_PRIMERO', N'ACA_PROMEDIO_SEGUNDO')
             AND P.CORR_PREGUNTA_BECA = PR.CORR_PREGUNTA_DESTINO THEN ISNULL(ACA.PUNTAJE, 0)
        WHEN P.CODIGO_PREGUNTA IN (N'ACA_PROMEDIO_PRIMERO', N'ACA_PROMEDIO_SEGUNDO') THEN 0
        ELSE R.PORCENTAJE_APLICADO
    END AS decimal(10, 2)) AS PORCENTAJE_APLICADO
FROM dbo.ACA_PROSPECTO_BECA_RESPUESTA AS R
INNER JOIN dbo.ACA_PROSPECTO_BECA_PREGUNTA AS P
    ON P.CORR_PREGUNTA_BECA = R.CORR_PREGUNTA_BECA
INNER JOIN dbo.ACA_PROSPECTO_BECA_SECCION AS S
    ON S.CORR_SECCION_BECA = P.CORR_SECCION_BECA
INNER JOIN dbo.ACA_PROSPECTO_BECA AS PB
    ON PB.CORR_PROSPECTO_BECA = R.CORR_PROSPECTO_BECA
LEFT JOIN (
    SELECT
        R2.CORR_PROSPECTO_BECA,
        AVG(R2.RESPUESTA_NUMERO) AS PROMEDIO,
        MAX(R2.CORR_PREGUNTA_BECA) AS CORR_PREGUNTA_DESTINO
    FROM dbo.ACA_PROSPECTO_BECA_RESPUESTA AS R2
    INNER JOIN dbo.ACA_PROSPECTO_BECA_PREGUNTA AS P2
        ON P2.CORR_PREGUNTA_BECA = R2.CORR_PREGUNTA_BECA
    WHERE P2.CODIGO_PREGUNTA IN (N'ACA_PROMEDIO_PRIMERO', N'ACA_PROMEDIO_SEGUNDO')
      AND R2.RESPUESTA_NUMERO IS NOT NULL
    GROUP BY R2.CORR_PROSPECTO_BECA
) AS PR
    ON PR.CORR_PROSPECTO_BECA = R.CORR_PROSPECTO_BECA
OUTER APPLY (
    SELECT TOP (1) B.PUNTAJE
    FROM dbo.ACA_PROSPECTO_BECA_BANDA AS B
    WHERE B.ACTIVO = 1
      AND B.CODIGO_REGLA = N'DEPENDIENTES'
      AND P.CODIGO_PREGUNTA = N'SOC_DEPENDIENTES_ECONOMICOS'
      AND R.RESPUESTA_NUMERO >= B.VALOR_DESDE
      AND R.RESPUESTA_NUMERO < B.VALOR_HASTA
) AS DEP
OUTER APPLY (
    SELECT TOP (1) B.PUNTAJE
    FROM dbo.ACA_PROSPECTO_BECA_BANDA AS B
    WHERE B.ACTIVO = 1
      AND B.CODIGO_REGLA = N'PROMEDIO_BACHILLERATO'
      AND PR.PROMEDIO >= B.VALOR_DESDE
      AND PR.PROMEDIO < B.VALOR_HASTA
) AS ACA
WHERE PB.ESTADO_BECA IN ('BORRADOR', 'ENVIADA');
GO

/* ==========================================================================
   V_ACA_PROSPECTO_BECA_ARCHIVO
   Qué hace: archivos que el prospecto cargó en preguntas tipo documento.
   Cómo lo hace: la carpeta del servidor es {año}-{período}_{CORR_PROSPECTO_BECA}
             bajo \\192.168.1.8\admision\Documentacion Becas. ARCHIVO_RUTA guarda
             la ruta completa; la pantalla abre el archivo por la respuesta.
   ========================================================================== */
CREATE OR ALTER VIEW dbo.V_ACA_PROSPECTO_BECA_ARCHIVO
AS
SELECT
    R.CORR_EMPRESA,
    R.CORR_PROSPECTO_BECA,
    R.CORR_RESPUESTA_BECA,
    PA.ANIO,
    PA.NUMERO_PERIODO,
    CAST(PA.ANIO AS VARCHAR(4)) + '-' + CAST(PA.NUMERO_PERIODO AS VARCHAR(2))
        + '_' + CAST(PB.CORR_PROSPECTO_BECA AS VARCHAR(12)) AS CARPETA,
    S.ORDEN AS ORDEN_SECCION,
    S.NOMBRE_SECCION,
    P.ORDEN AS ORDEN_PREGUNTA,
    P.CORR_PREGUNTA_BECA,
    P.TEXTO_PREGUNTA,
    R.ARCHIVO_NOMBRE,
    R.ARCHIVO_RUTA
FROM dbo.ACA_PROSPECTO_BECA_RESPUESTA AS R
INNER JOIN dbo.ACA_PROSPECTO_BECA_PREGUNTA AS P
    ON P.CORR_PREGUNTA_BECA = R.CORR_PREGUNTA_BECA
INNER JOIN dbo.ACA_PROSPECTO_BECA_SECCION AS S
    ON S.CORR_SECCION_BECA = P.CORR_SECCION_BECA
INNER JOIN dbo.ACA_PROSPECTO_BECA AS PB
    ON PB.CORR_PROSPECTO_BECA = R.CORR_PROSPECTO_BECA
INNER JOIN dbo.ACA_PERIODOS_ACADEMICOS AS PA
    ON PA.CORR_PERIODO_ACADEMICO = PB.CORR_PERIODO_ACADEMICO
WHERE PB.ESTADO_BECA IN ('BORRADOR', 'ENVIADA')
  AND P.TIPO_RESPUESTA = 'DOCUMENTO'
  AND NULLIF(LTRIM(RTRIM(R.ARCHIVO_NOMBRE)), '') IS NOT NULL;
GO

PRINT N'Vistas de consulta de solicitudes de beca listas.';
GO

/* ==========================================================================
   Menú: Académico → Consultas → Solicitudes de beca
   ========================================================================== */
DECLARE @SISTEMA varchar(30) = 'ACADEMICS';
DECLARE @MENU    varchar(10) = 'CONSULTA';
DECLARE @SUITE   varchar(30) = 'SGUEES';
DECLARE @OPCION  varchar(30) = 'ACA_PROSPECTO_BECA';
DECLARE @USR     varchar(30) = 'admin';
DECLARE @EST     varchar(30) = 'SISTEMA';
DECLARE @HOY     datetime    = GETDATE();
DECLARE @ORDEN   int;

SELECT @ORDEN = ISNULL(MAX(ORDEN_OPCION), 0) + 1
FROM SEG_CONFIG_OPCION
WHERE CODIGO_SISTEMA = @SISTEMA
  AND CODIGO_MENU = @MENU
  AND CODIGO_OPCION <> @OPCION;

IF EXISTS (SELECT 1 FROM SEG_CONFIG_OPCION WHERE CODIGO_OPCION = @OPCION)
    SELECT @ORDEN = ORDEN_OPCION
    FROM SEG_CONFIG_OPCION
    WHERE CODIGO_OPCION = @OPCION;

MERGE SEG_OPCION_SISTEMA AS T
USING (SELECT @OPCION AS CODIGO, N'Solicitudes de beca' AS NOMBRE, N'/aca-prospecto-beca' AS URL) AS S
ON T.CODIGO_OPCION = S.CODIGO
WHEN MATCHED THEN
    UPDATE SET T.NOMBRE_OPCION = S.NOMBRE,
               T.URL_OPCION = S.URL,
               T.IMAGEN_OPCION = '',
               T.USUARIO_ACTU = @USR,
               T.FECHA_ACTU = @HOY,
               T.ESTACION_ACTU = @EST
WHEN NOT MATCHED THEN
    INSERT (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION, IMAGEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
    VALUES (S.CODIGO, S.NOMBRE, S.URL, '', @USR, @HOY, @EST);

INSERT INTO SEG_OPCION_SISTEMA_SUITE (CODIGO_OPCION, CODIGO_SUITE)
SELECT @OPCION, @SUITE
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_OPCION_SISTEMA_SUITE
    WHERE CODIGO_OPCION = @OPCION AND CODIGO_SUITE = @SUITE
);

DELETE FROM SEG_CONFIG_OPCION WHERE CODIGO_OPCION = @OPCION;

INSERT INTO SEG_CONFIG_OPCION
    (CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT @SISTEMA, @MENU, @OPCION, 0, C.ORDEN_MENU, @ORDEN, @USR, @HOY, @EST
FROM (
    SELECT TOP (1) ORDEN_MENU
    FROM SEG_CONFIG_OPCION
    WHERE CODIGO_SISTEMA = @SISTEMA AND CODIGO_MENU = @MENU
) AS C;

INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT U.LOGIN_SISTEMA, @SISTEMA, @MENU, @OPCION, 0, 0, 0, U.IMPRIMIR, @USR, @HOY, @EST
FROM SEG_USUARIO_OPCION AS U
WHERE U.CODIGO_OPCION = 'ACA_PROSPECTO'
  AND U.CODIGO_SISTEMA = @SISTEMA
  AND NOT EXISTS (
      SELECT 1 FROM SEG_USUARIO_OPCION AS X
      WHERE X.LOGIN_SISTEMA = U.LOGIN_SISTEMA
        AND X.CODIGO_SISTEMA = @SISTEMA
        AND X.CODIGO_MENU = @MENU
        AND X.CODIGO_OPCION = @OPCION
  );

PRINT N'Menú Solicitudes de beca configurado.';
GO

/* El puntaje de bandas se resuelve en las vistas de consulta. Sin triggers. */
DROP TRIGGER IF EXISTS dbo.TRG_ACA_PROSPECTO_BECA_RESPUESTA_BANDAS;
DROP TRIGGER IF EXISTS dbo.TRG_ACA_PROSPECTO_BECA_BANDAS;
DROP TRIGGER IF EXISTS dbo.TRG_ACA_PROSPECTO_BECA_SECCION_BANDAS;
DROP PROCEDURE IF EXISTS dbo.PR_ACA_PROSPECTO_BECA_APLICAR_BANDAS;
GO

PRINT N'Consulta de becas sin triggers de puntaje.';
GO
