param(
    [string]$SourceDir = "C:\Users\jonathan.avalos\OneDrive - Universidad Evangélica de El Salvador\Documentos\jonathan\PROEYECTOS\e-Admin\e-Admin.db\Stored Procedures",
    [string]$DestDir = "c:\Desarrollo GIT\SGUEES\SGUEES-DB\Stored Procedures"
)

function Adapt-SgueesSp {
    param([string]$Content, [switch]$BalanceMultiEmpresa)

    $c = $Content

    # Parametros de entrada e-Admin -> SGUEES
    $c = $c -replace '(?m)^\s*@CORR_SUSCRIPCION\s+int,\s*\r?\n', ''
    $c = $c -replace '(?m)^\s*@CORR_CONFI_PAIS\s+int,\s*\r?\n', ''
    $c = $c -replace '(?m)^\s*--@CORR_EMPRESA INT,\s*\r?\n', ''
    $c = $c -replace '(?m)^\s*@CORR_EMPRESAS VARCHAR\(255\),\s*\r?\n', ''

    if (-not ($c -match '@CORR_EMPRESA INT')) {
        $c = $c -replace '(?m)(CREATE PROCEDURE \[dbo\]\.\[[^\]]+\]\s*\(\s*\r?\n)', "`$1  @CORR_EMPRESA INT,`r`n"
    }

    # Variables tabla @SALDO
    $c = $c -replace '(?m)^\s*CORR_SUSCRIPCION int,\s*\r?\n', ''
    $c = $c -replace '(?m)^\s*CORR_CONFI_PAIS int,\s*\r?\n', ''

    # Joins compuestos e-Admin
    $patterns = @(
        @('A\.CORR_SUSCRIPCION=B\.CORR_SUSCRIPCION AND A\.CORR_CONFI_PAIS=B\.CORR_CONFI_PAIS AND A\.CORR_EMPRESA=B\.CORR_EMPRESA', 'A.CORR_EMPRESA=B.CORR_EMPRESA'),
        @('C\.CORR_SUSCRIPCION=Z\.CORR_SUSCRIPCION AND C\.CORR_CONFI_PAIS=Z\.CORR_CONFI_PAIS AND C\.CORR_EMPRESA=Z\.CORR_EMPRESA', 'C.CORR_EMPRESA=Z.CORR_EMPRESA'),
        @('B\.CORR_SUSCRIPCION=N1\.CORR_SUSCRIPCION AND B\.CORR_CONFI_PAIS=N1\.CORR_CONFI_PAIS AND B\.CORR_EMPRESA=N1\.CORR_EMPRESA', 'B.CORR_EMPRESA=N1.CORR_EMPRESA'),
        @('B\.CORR_SUSCRIPCION=N2\.CORR_SUSCRIPCION AND B\.CORR_CONFI_PAIS=N2\.CORR_CONFI_PAIS AND B\.CORR_EMPRESA=N2\.CORR_EMPRESA', 'B.CORR_EMPRESA=N2.CORR_EMPRESA'),
        @('B\.CORR_SUSCRIPCION=N3\.CORR_SUSCRIPCION AND B\.CORR_CONFI_PAIS=N3\.CORR_CONFI_PAIS AND B\.CORR_EMPRESA=N3\.CORR_EMPRESA', 'B.CORR_EMPRESA=N3.CORR_EMPRESA'),
        @('B\.CORR_SUSCRIPCION=N4\.CORR_SUSCRIPCION AND B\.CORR_CONFI_PAIS=N4\.CORR_CONFI_PAIS AND B\.CORR_EMPRESA=N4\.CORR_EMPRESA', 'B.CORR_EMPRESA=N4.CORR_EMPRESA'),
        @('B\.CORR_SUSCRIPCION=N5\.CORR_SUSCRIPCION AND B\.CORR_CONFI_PAIS=N5\.CORR_CONFI_PAIS AND B\.CORR_EMPRESA=N5\.CORR_EMPRESA', 'B.CORR_EMPRESA=N5.CORR_EMPRESA'),
        @('A\.CORR_SUSCRIPCION=B\.CORR_SUSCRIPCION AND A\.CORR_CONFI_PAIS=B\.CORR_CONFI_PAIS AND A\.CORR_EMPRESA=B\.CORR_EMPRESA', 'A.CORR_EMPRESA=B.CORR_EMPRESA'),
        @('A\.CORR_SUSCRIPCION=C\.CORR_SUSCRIPCION AND A\.CORR_CONFI_PAIS=C\.CORR_CONFI_PAIS AND A\.CORR_EMPRESA=C\.CORR_EMPRESA', 'A.CORR_EMPRESA=C.CORR_EMPRESA'),
        @('Z\.CORR_SUSCRIPCION=F\.CORR_SUSCRIPCION AND Z\.CORR_CONFI_PAIS=F\.CORR_CONFI_PAIS AND Z\.CORR_EMPRESA=F\.CORR_EMPRESA', 'Z.CORR_EMPRESA=F.CORR_EMPRESA'),
        @('F\.CORR_SUSCRIPCION=G\.CORR_SUSCRIPCION AND F\.CORR_CONFI_PAIS=G\.CORR_CONFI_PAIS AND F\.CORR_EMPRESA=G\.CORR_EMPRESA', 'F.CORR_EMPRESA=G.CORR_EMPRESA'),
        @('G\.CORR_SUSCRIPCION=H\.CORR_SUSCRIPCION AND G\.CORR_CONFI_PAIS=H\.CORR_CONFI_PAIS AND G\.CORR_EMPRESA=H\.CORR_EMPRESA', 'G.CORR_EMPRESA=H.CORR_EMPRESA'),
        @('H\.CORR_SUSCRIPCION=I\.CORR_SUSCRIPCION AND H\.CORR_CONFI_PAIS=I\.CORR_CONFI_PAIS AND H\.CORR_EMPRESA=I\.CORR_EMPRESA', 'H.CORR_EMPRESA=I.CORR_EMPRESA'),
        @('B\.CORR_SUSCRIPCION=K\.CORR_SUSCRIPCION AND B\.CORR_CONFI_PAIS=K\.CORR_CONFI_PAIS AND B\.CORR_EMPRESA=K\.CORR_EMPRESA', 'B.CORR_EMPRESA=K.CORR_EMPRESA'),
        @('C\.CORR_SUSCRIPCION=H\.CORR_SUSCRIPCION AND C\.CORR_CONFI_PAIS=H\.CORR_CONFI_PAIS AND C\.CORR_EMPRESA=H\.CORR_EMPRESA', 'C.CORR_EMPRESA=H.CORR_EMPRESA'),
        @('C\.CORR_SUSCRIPCION=J\.CORR_SUSCRIPCION AND @CORR_MONEDA=J\.CORR_MONEDA', '@CORR_MONEDA=J.CORR_MONEDA'),
        @('C\.CORR_SUSCRIPCION=J\.CORR_SUSCRIPCION AND @CORR_MONEDA=J\.CORR_MONEDA', '@CORR_MONEDA=J.CORR_MONEDA')
    )
    foreach ($p in $patterns) {
        $c = $c -replace $p[0], $p[1]
    }

    # WHERE / filtros empresa
    $c = $c -replace 'WHERE CORR_SUSCRIPCION=@CORR_SUSCRIPCION\s+AND CORR_CONFI_PAIS=@CORR_CONFI_PAIS\s+AND CORR_EMPRESA=@CORR_EMPRESA', 'WHERE CORR_EMPRESA=@CORR_EMPRESA'
    $c = $c -replace 'WHERE A\.CORR_SUSCRIPCION=@CORR_SUSCRIPCION\s+AND A\.CORR_CONFI_PAIS=@CORR_CONFI_PAIS\s+AND A\.CORR_EMPRESA=@CORR_EMPRESA', 'WHERE A.CORR_EMPRESA=@CORR_EMPRESA'
    $c = $c -replace 'AND A\.CORR_SUSCRIPCION=@CORR_SUSCRIPCION\s+AND A\.CORR_CONFI_PAIS=@CORR_CONFI_PAIS\s+AND A\.CORR_EMPRESA=@CORR_EMPRESA', 'AND A.CORR_EMPRESA=@CORR_EMPRESA'
    $c = $c -replace 'WHERE A\.CORR_SUSCRIPCION=@CORR_SUSCRIPCION\s*\r?\n\s*AND A\.CORR_CONFI_PAIS=@CORR_CONFI_PAIS\s*\r?\n\s*AND A\.CORR_EMPRESA=@CORR_EMPRESA', "WHERE A.CORR_EMPRESA=@CORR_EMPRESA"

    $c = $c -replace 'ISNULL\(C\.CORR_SUSCRIPCION,B\.CORR_SUSCRIPCION\)=@CORR_SUSCRIPCION\s+AND ISNULL\(C\.CORR_CONFI_PAIS,B\.CORR_CONFI_PAIS\)=@CORR_CONFI_PAIS\s+AND ISNULL\(C\.CORR_EMPRESA,B\.CORR_EMPRESA\)=@CORR_EMPRESA', 'ISNULL(C.CORR_EMPRESA,B.CORR_EMPRESA)=@CORR_EMPRESA'

    # EXEC saldo inicial
    $c = $c -replace '(?m)^\s*@CORR_SUSCRIPCION,\s*\r?\n\s*@CORR_CONFI_PAIS,\s*\r?\n\s*@CORR_EMPRESA,', '		@CORR_EMPRESA,'

    # SELECT encabezado empresa
    $c = $c -replace 'WHERE A\.CORR_SUSCRIPCION=@CORR_SUSCRIPCION\s+AND A\.CORR_CONFI_PAIS=@CORR_CONFI_PAIS\s+AND A\.CORR_EMPRESA=@CORR_EMPRESA', 'WHERE A.CORR_EMPRESA=@CORR_EMPRESA'

    # PARTITION BY / ORDER BY
    $c = $c -replace 'PARTITION BY C\.CORR_SUSCRIPCION,C\.CORR_CONFI_PAIS,C\.CORR_EMPRESA,C\.CUENTA_CONTABLE', 'PARTITION BY C.CORR_EMPRESA,C.CUENTA_CONTABLE'
    $c = $c -replace 'ORDER BY C\.CORR_SUSCRIPCION,C\.CORR_CONFI_PAIS,C\.CORR_EMPRESA, C\.CUENTA_CONTABLE', 'ORDER BY C.CORR_EMPRESA, C.CUENTA_CONTABLE'
    $c = $c -replace 'ORDER BY C\.CORR_SUSCRIPCION,C\.CORR_CONFI_PAIS,C\.CORR_EMPRESA, C\.CUENTA_CONTABLE', 'ORDER BY C.CORR_EMPRESA, C.CUENTA_CONTABLE'
    $c = $c -replace 'PARTITION BY A\.CORR_SUSCRIPCION,A\.CORR_CONFI_PAIS,A\.CORR_EMPRESA,B\.CUENTA_CONTABLE', 'PARTITION BY A.CORR_EMPRESA,B.CUENTA_CONTABLE'
    $c = $c -replace 'ORDER BY A\.CORR_SUSCRIPCION,A\.CORR_CONFI_PAIS,A\.CORR_EMPRESA, A\.CUENTA_CONTABLE', 'ORDER BY A.CORR_EMPRESA, A.CUENTA_CONTABLE'
    $c = $c -replace 'ORDER BY A\.CORR_SUSCRIPCION,A\.CORR_CONFI_PAIS,A\.CORR_EMPRESA, A\.CUENTA_CONTABLE', 'ORDER BY A.CORR_EMPRESA, A.CUENTA_CONTABLE'

    # SELECT listas con suscripcion
    $c = $c -replace '(?m)^\s*,A\.CORR_SUSCRIPCION\s*\r?\n\s*,A\.CORR_CONFI_PAIS\s*\r?\n', ''
    $c = $c -replace '(?m)^\s*SELECT DISTINCT C\.CORR_SUSCRIPCION\s*\r?\n\s*,C\.CORR_CONFI_PAIS\s*\r?\n', 'SELECT DISTINCT '

    if ($BalanceMultiEmpresa) {
        # Reemplazar bloque multi-empresa por empresa unica (placeholder - revisar manualmente si falla)
        $c = $c -replace '@CORR_EMPRESAS', 'CAST(@CORR_EMPRESA AS VARCHAR(20))'
    }

    return $c
}

$files = @(
    'dbo.PRAL_IMPR_LIBRO_DIARIO_AUXILIAR.sql',
    'dbo.PRAL_IMPR_LIBRO_DIARIO_MAYOR.sql',
    'dbo.PRAL_IMPR_BALANCE_COMPROBACION.sql',
    'dbo.PRAL_IMPR_BALANCE_GENERAL.sql',
    'dbo.PRAL_IMPR_ESTADO_RESULTADOS.sql',
    'dbo.PRAL_IMPR_BALANCE_GENERAL_VERTICAL.sql'
)

foreach ($f in $files) {
    $src = Join-Path $SourceDir $f
    $dst = Join-Path $DestDir $f
    if (-not (Test-Path $src)) {
        Write-Warning "No encontrado: $src"
        continue
    }
    $raw = Get-Content $src -Raw -Encoding UTF8
    $balance = $f -match 'BALANCE|ESTADO'
    $adapted = Adapt-SgueesSp -Content $raw -BalanceMultiEmpresa:$balance
    Set-Content -Path $dst -Value $adapted -Encoding UTF8
    Write-Host "Adaptado: $f"
}

Write-Host "Listo. Revise joins restantes con CORR_SUSCRIPCION en los archivos generados."
