/*
  Instancia remota SUEES (129) — solo lectura para migración de datos COM_*.
  No modifica la base SUEES en 129.
*/
SET NOCOUNT ON;
GO

MERGE dbo.SYS_INSTANCIA_REMOTA AS T
USING (
	SELECT
		N'SUEES_129' AS CODIGO_INSTANCIA,
		N'SUEES129' AS NOMBRE_LINKED_SERVER,
		N'SUEES legacy CSUEES — tablas COM_* para migración' AS DESCRIPCION,
		N'192.168.1.129' AS SERVIDOR,
		N'SUEES' AS NOMBRE_BASE_DATOS,
		N'sa' AS USUARIO_SQL,
		N'UEES.1234' AS CLAVE_SQL
) AS S
ON T.CODIGO_INSTANCIA = S.CODIGO_INSTANCIA
WHEN MATCHED THEN
	UPDATE SET
		NOMBRE_LINKED_SERVER = S.NOMBRE_LINKED_SERVER,
		DESCRIPCION = S.DESCRIPCION,
		SERVIDOR = S.SERVIDOR,
		NOMBRE_BASE_DATOS = S.NOMBRE_BASE_DATOS,
		USUARIO_SQL = S.USUARIO_SQL,
		CLAVE_SQL = S.CLAVE_SQL,
		ACTIVO = 1
WHEN NOT MATCHED THEN
	INSERT (
		CODIGO_INSTANCIA, NOMBRE_LINKED_SERVER, DESCRIPCION, SERVIDOR, NOMBRE_BASE_DATOS,
		USUARIO_SQL, CLAVE_SQL, ACTIVO
	)
	VALUES (
		S.CODIGO_INSTANCIA, S.NOMBRE_LINKED_SERVER, S.DESCRIPCION, S.SERVIDOR, S.NOMBRE_BASE_DATOS,
		S.USUARIO_SQL, S.CLAVE_SQL, 1
	);
GO

EXEC dbo.PRAL_ADMIN_SYNC_INSTANCIA_REMOTA
	@CODIGO_INSTANCIA = N'SUEES_129',
	@SYS_LOGIN_USUARIO = N'MIGRATE',
	@SYS_ESTACION = @@SERVERNAME;
GO

PRINT N'Verificación linked server SUEES129:';
SELECT TOP 1 TABLE_NAME
FROM SUEES129.SUEES.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = N'COM_PROVEEDOR';
GO
