SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/* ValidarToken: tipo de contratación + correo de invitación.
   SPA: CORR 0/null → mostrar todos; ES_PERMANENTE = 0 → ocultar paso 5.
   CORREO_INVITACION se precarga en el formulario público (el candidato verifica). */

CREATE OR ALTER PROCEDURE dbo.PRAL_DATA_SC_SOLICITUD_EMPLEO_PUBLICO_VALIDAR
    @TOKEN_HASH varchar(64)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    UPDATE dbo.SC_SOLICITUD_EMPLEO_TOKEN
       SET ESTADO_TOKEN = 'EXPIRADO'
     WHERE TOKEN_HASH = @TOKEN_HASH
       AND ESTADO_TOKEN = 'ENVIADO'
       AND FECHA_EXPIRACION < GETDATE();

    SELECT
        CAST(1 AS bit) AS VALIDO,
        T.FECHA_EXPIRACION,
        ISNULL(S.CORR_TIPO_CONTRATACION, 0) AS CORR_TIPO_CONTRATACION,
        TC.NOMBRE_TIPO_CONTRATACION,
        CAST(ISNULL(TC.ES_PERMANENTE, 0) AS bit) AS ES_PERMANENTE,
        /* Solicitud primero; si viene vacío, el correo al que se envió el token. */
        LTRIM(RTRIM(ISNULL(NULLIF(S.CORREO_INVITACION, ''), T.CORREO_DESTINO))) AS CORREO_INVITACION
    FROM dbo.SC_SOLICITUD_EMPLEO_TOKEN T
    INNER JOIN dbo.SC_SOLICITUD_EMPLEO S
        ON S.CORR_EMPRESA = T.CORR_EMPRESA
       AND S.CORR_SOLICITUD_EMPLEO = T.CORR_SOLICITUD_EMPLEO
    LEFT JOIN dbo.SC_TIPO_CONTRATACION TC
        ON TC.CORR_EMPRESA = S.CORR_EMPRESA
       AND TC.CORR_TIPO_CONTRATACION = S.CORR_TIPO_CONTRATACION
    WHERE T.TOKEN_HASH = @TOKEN_HASH
      AND T.ESTADO_TOKEN = 'ENVIADO'
      AND T.FECHA_EXPIRACION >= GETDATE()
      AND S.ACTIVO = 1
      AND S.CORR_PERSONA_DATOS IS NULL;
END;
GO
