/*
  SC_EXPEDIENTE_ENTREVISTA — TIPO_ENTREVISTA (varchar) → CORR_TIPO_ENTREVISTA (int FK)
  Ejecutar:
    sqlcmd -S <srv> -d SGUEES -U <user> -P <pass> -f 65001 -i SGUEES-DB/Scripts/ALTER_SC_EXPEDIENTE_ENTREVISTA_CORR_TIPO_ENTREVISTA.sql
*/

SET NOCOUNT ON;
GO

/* ========== 1) Agregar CORR_TIPO_ENTREVISTA si no existe ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_ENTREVISTA', N'CORR_TIPO_ENTREVISTA') IS NULL
BEGIN
  ALTER TABLE dbo.SC_EXPEDIENTE_ENTREVISTA
    ADD CORR_TIPO_ENTREVISTA INT NULL;
END
GO

/* ========== 2) Migrar valores textuales existentes (mejor esfuerzo) ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_ENTREVISTA', N'TIPO_ENTREVISTA') IS NOT NULL
   AND COL_LENGTH(N'dbo.SC_EXPEDIENTE_ENTREVISTA', N'CORR_TIPO_ENTREVISTA') IS NOT NULL
BEGIN
  UPDATE E
  SET E.CORR_TIPO_ENTREVISTA = T.CORR_TIPO_ENTREVISTA
  FROM dbo.SC_EXPEDIENTE_ENTREVISTA AS E
  INNER JOIN dbo.SC_TIPO_ENTREVISTA AS T
    ON T.CORR_EMPRESA = E.CORR_EMPRESA
   AND UPPER(LTRIM(RTRIM(T.TIPO_ENTREVISTA))) = UPPER(LTRIM(RTRIM(E.TIPO_ENTREVISTA)))
  WHERE E.CORR_TIPO_ENTREVISTA IS NULL
    AND NULLIF(LTRIM(RTRIM(E.TIPO_ENTREVISTA)), N'') IS NOT NULL;
END
GO

/* ========== 3) Quitar columna textual antigua ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_ENTREVISTA', N'TIPO_ENTREVISTA') IS NOT NULL
BEGIN
  ALTER TABLE dbo.SC_EXPEDIENTE_ENTREVISTA
    DROP COLUMN TIPO_ENTREVISTA;
END
GO

/* ========== 4) NOT NULL solo si no quedan nulos ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_ENTREVISTA', N'CORR_TIPO_ENTREVISTA') IS NOT NULL
   AND NOT EXISTS (
     SELECT 1
     FROM dbo.SC_EXPEDIENTE_ENTREVISTA
     WHERE CORR_TIPO_ENTREVISTA IS NULL
   )
BEGIN
  ALTER TABLE dbo.SC_EXPEDIENTE_ENTREVISTA
    ALTER COLUMN CORR_TIPO_ENTREVISTA INT NOT NULL;
END
ELSE
BEGIN
  PRINT N'AVISO: quedan filas con CORR_TIPO_ENTREVISTA NULL; la columna permanece nullable. Asigne un tipo válido y vuelva a ejecutar la sección NOT NULL.';
END
GO

/* ========== 5) FK a SC_TIPO_ENTREVISTA ========== */
IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = N'FK_SC_EXPEDIENTE_ENTREVISTA_TIPO'
)
BEGIN
  ALTER TABLE dbo.SC_EXPEDIENTE_ENTREVISTA WITH CHECK
    ADD CONSTRAINT FK_SC_EXPEDIENTE_ENTREVISTA_TIPO
    FOREIGN KEY (CORR_EMPRESA, CORR_TIPO_ENTREVISTA)
    REFERENCES dbo.SC_TIPO_ENTREVISTA (CORR_EMPRESA, CORR_TIPO_ENTREVISTA);
END
GO

/* ========== 6) Vista: CORR + texto/descripcion del catálogo ========== */
CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_ENTREVISTA
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_ENTREVISTA,
    X.CORR_SOLICITUD_EMPLEO,
    X.CORR_TIPO_ENTREVISTA,
    T.TIPO_ENTREVISTA,
    T.DESCRIPCION_ENTREVISTA,
    X.FECHA_ENTREVISTA,
    X.ENTREVISTADOR,
    X.ESTADO_ENTREVISTA,
    X.RESULTADO_ENTREVISTA,
    X.RESUMEN_ENTREVISTA,
    S.CORREO_INVITACION,
    S.NOMBRE AS NOMBRE_SOLICITUD,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_ENTREVISTA AS X
INNER JOIN dbo.SC_SOLICITUD_EMPLEO AS S
    ON S.CORR_EMPRESA = X.CORR_EMPRESA
   AND S.CORR_SOLICITUD_EMPLEO = X.CORR_SOLICITUD_EMPLEO
LEFT JOIN dbo.SC_TIPO_ENTREVISTA AS T
    ON T.CORR_EMPRESA = X.CORR_EMPRESA
   AND T.CORR_TIPO_ENTREVISTA = X.CORR_TIPO_ENTREVISTA;
GO

PRINT N'ALTER SC_EXPEDIENTE_ENTREVISTA → CORR_TIPO_ENTREVISTA listo.';
GO
