SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/*
  Agrega CORR_ESTADO_EXPEDIENTE a SC_EXPEDIENTE_CANDIDATO.
  1 = Borrador (default en insert)
  2 = Proceso de selección

  Ejecutar: sqlcmd -S <srv> -d SGUEES -U <user> -f 65001 -i ALTER_SC_EXPEDIENTE_CANDIDATO_ESTADO.sql
*/
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_CANDIDATO', N'CORR_ESTADO_EXPEDIENTE') IS NULL
BEGIN
    ALTER TABLE dbo.SC_EXPEDIENTE_CANDIDATO
        ADD CORR_ESTADO_EXPEDIENTE int NOT NULL
            CONSTRAINT DF_SC_EXPEDIENTE_CANDIDATO_ESTADO DEFAULT (1);

    PRINT N'Columna CORR_ESTADO_EXPEDIENTE agregada (default 1 = Borrador).';
END
ELSE
    PRINT N'Columna CORR_ESTADO_EXPEDIENTE ya existe.';
GO

UPDATE dbo.SC_EXPEDIENTE_CANDIDATO
SET CORR_ESTADO_EXPEDIENTE = 1
WHERE CORR_ESTADO_EXPEDIENTE IS NULL OR CORR_ESTADO_EXPEDIENTE <= 0;
GO

CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_CANDIDATO
AS
SELECT
    E.CORR_EMPRESA,
    E.CORR_EXPEDIENTE_CANDIDATO,
    E.CORR_PERSONA_DATOS,
    E.CORR_ESTADO_EXPEDIENTE,
    E.FECHA_GENERACION,
    E.ACTIVO,
    P.DUI AS DUI_PERSONA,
    LTRIM(RTRIM(
        CONCAT(
            ISNULL(P.NOMBRE1, ''),
            CASE WHEN NULLIF(LTRIM(RTRIM(P.NOMBRE2)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.NOMBRE2)) END,
            CASE WHEN NULLIF(LTRIM(RTRIM(P.APELLIDO1)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.APELLIDO1)) END,
            CASE WHEN NULLIF(LTRIM(RTRIM(P.APELLIDO2)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.APELLIDO2)) END
        )
    )) AS NOMBRE_PERSONA,
    E.USUARIO_CREA,
    E.ESTACION_CREA,
    E.FECHA_CREA,
    E.USUARIO_ACTU,
    E.ESTACION_ACTU,
    E.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_CANDIDATO AS E
LEFT JOIN dbo.SC_PERSONA_DATOS AS P
    ON P.CORR_EMPRESA = E.CORR_EMPRESA
   AND P.CORR_PERSONA_DATOS = E.CORR_PERSONA_DATOS;
GO

PRINT N'V_SC_EXPEDIENTE_CANDIDATO actualizada con CORR_ESTADO_EXPEDIENTE.';
GO
