/*
  Agrega ESTADO_* (bit) + columnas de auditoría donde falten
  en catálogos de Bancos (GEN/COM/BAN).
  Requiere SP PRAL_MTTO_CATALOGO_ESTADO_BIT (DEPLOY_SP_CATALOGO_ESTADO_BIT.sql).

  Ejecutar:
  sqlcmd -S <srv> -d SGUEES -U <user> -f 65001 -i ALTER_BANCO_ESTADO_CATALOGO_BIT.sql
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/* ========== helper: agregar columna si no existe ========== */
/* GEN_BANCO */
IF OBJECT_ID(N'dbo.GEN_BANCO', N'U') IS NOT NULL
BEGIN
	IF COL_LENGTH('dbo.GEN_BANCO', 'ESTADO_BANCO') IS NULL
		ALTER TABLE dbo.GEN_BANCO ADD ESTADO_BANCO bit NOT NULL CONSTRAINT DF_GEN_BANCO_ESTADO_BANCO DEFAULT (1);

	IF COL_LENGTH('dbo.GEN_BANCO', 'USUARIO_CREA') IS NULL
		ALTER TABLE dbo.GEN_BANCO ADD USUARIO_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.GEN_BANCO', 'FECHA_CREA') IS NULL
		ALTER TABLE dbo.GEN_BANCO ADD FECHA_CREA datetime NULL;
	IF COL_LENGTH('dbo.GEN_BANCO', 'ESTACION_CREA') IS NULL
		ALTER TABLE dbo.GEN_BANCO ADD ESTACION_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.GEN_BANCO', 'USUARIO_ACTU') IS NULL
		ALTER TABLE dbo.GEN_BANCO ADD USUARIO_ACTU varchar(30) NULL;
	IF COL_LENGTH('dbo.GEN_BANCO', 'FECHA_ACTU') IS NULL
		ALTER TABLE dbo.GEN_BANCO ADD FECHA_ACTU datetime NULL;
	IF COL_LENGTH('dbo.GEN_BANCO', 'ESTACION_ACTU') IS NULL
		ALTER TABLE dbo.GEN_BANCO ADD ESTACION_ACTU varchar(30) NULL;
END
GO

/* COM_BANCO */
IF OBJECT_ID(N'dbo.COM_BANCO', N'U') IS NOT NULL
BEGIN
	IF COL_LENGTH('dbo.COM_BANCO', 'ESTADO_BANCO') IS NULL
		ALTER TABLE dbo.COM_BANCO ADD ESTADO_BANCO bit NOT NULL CONSTRAINT DF_COM_BANCO_ESTADO_BANCO DEFAULT (1);

	IF COL_LENGTH('dbo.COM_BANCO', 'USUARIO_CREA') IS NULL
		ALTER TABLE dbo.COM_BANCO ADD USUARIO_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.COM_BANCO', 'FECHA_CREA') IS NULL
		ALTER TABLE dbo.COM_BANCO ADD FECHA_CREA datetime NULL;
	IF COL_LENGTH('dbo.COM_BANCO', 'ESTACION_CREA') IS NULL
		ALTER TABLE dbo.COM_BANCO ADD ESTACION_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.COM_BANCO', 'USUARIO_ACTU') IS NULL
		ALTER TABLE dbo.COM_BANCO ADD USUARIO_ACTU varchar(30) NULL;
	IF COL_LENGTH('dbo.COM_BANCO', 'FECHA_ACTU') IS NULL
		ALTER TABLE dbo.COM_BANCO ADD FECHA_ACTU datetime NULL;
	IF COL_LENGTH('dbo.COM_BANCO', 'ESTACION_ACTU') IS NULL
		ALTER TABLE dbo.COM_BANCO ADD ESTACION_ACTU varchar(30) NULL;
END
GO

/* BAN_LINEA_TRABAJO_CONCILIACION */
IF OBJECT_ID(N'dbo.BAN_LINEA_TRABAJO_CONCILIACION', N'U') IS NOT NULL
BEGIN
	IF COL_LENGTH('dbo.BAN_LINEA_TRABAJO_CONCILIACION', 'ESTADO_LINEA') IS NULL
		ALTER TABLE dbo.BAN_LINEA_TRABAJO_CONCILIACION ADD ESTADO_LINEA bit NOT NULL CONSTRAINT DF_BAN_LINEA_TRABAJO_CONCILIACION_ESTADO_LINEA DEFAULT (1);

	IF COL_LENGTH('dbo.BAN_LINEA_TRABAJO_CONCILIACION', 'USUARIO_CREA') IS NULL
		ALTER TABLE dbo.BAN_LINEA_TRABAJO_CONCILIACION ADD USUARIO_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_LINEA_TRABAJO_CONCILIACION', 'FECHA_CREA') IS NULL
		ALTER TABLE dbo.BAN_LINEA_TRABAJO_CONCILIACION ADD FECHA_CREA datetime NULL;
	IF COL_LENGTH('dbo.BAN_LINEA_TRABAJO_CONCILIACION', 'ESTACION_CREA') IS NULL
		ALTER TABLE dbo.BAN_LINEA_TRABAJO_CONCILIACION ADD ESTACION_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_LINEA_TRABAJO_CONCILIACION', 'USUARIO_ACTU') IS NULL
		ALTER TABLE dbo.BAN_LINEA_TRABAJO_CONCILIACION ADD USUARIO_ACTU varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_LINEA_TRABAJO_CONCILIACION', 'FECHA_ACTU') IS NULL
		ALTER TABLE dbo.BAN_LINEA_TRABAJO_CONCILIACION ADD FECHA_ACTU datetime NULL;
	IF COL_LENGTH('dbo.BAN_LINEA_TRABAJO_CONCILIACION', 'ESTACION_ACTU') IS NULL
		ALTER TABLE dbo.BAN_LINEA_TRABAJO_CONCILIACION ADD ESTACION_ACTU varchar(30) NULL;
END
GO

/* BAN_TIPO_CHEQUE */
IF OBJECT_ID(N'dbo.BAN_TIPO_CHEQUE', N'U') IS NOT NULL
BEGIN
	IF COL_LENGTH('dbo.BAN_TIPO_CHEQUE', 'ESTADO_TIPO_CHEQUE') IS NULL
		ALTER TABLE dbo.BAN_TIPO_CHEQUE ADD ESTADO_TIPO_CHEQUE bit NOT NULL CONSTRAINT DF_BAN_TIPO_CHEQUE_ESTADO_TIPO_CHEQUE DEFAULT (1);

	IF COL_LENGTH('dbo.BAN_TIPO_CHEQUE', 'USUARIO_CREA') IS NULL
		ALTER TABLE dbo.BAN_TIPO_CHEQUE ADD USUARIO_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_TIPO_CHEQUE', 'FECHA_CREA') IS NULL
		ALTER TABLE dbo.BAN_TIPO_CHEQUE ADD FECHA_CREA datetime NULL;
	IF COL_LENGTH('dbo.BAN_TIPO_CHEQUE', 'ESTACION_CREA') IS NULL
		ALTER TABLE dbo.BAN_TIPO_CHEQUE ADD ESTACION_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_TIPO_CHEQUE', 'USUARIO_ACTU') IS NULL
		ALTER TABLE dbo.BAN_TIPO_CHEQUE ADD USUARIO_ACTU varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_TIPO_CHEQUE', 'FECHA_ACTU') IS NULL
		ALTER TABLE dbo.BAN_TIPO_CHEQUE ADD FECHA_ACTU datetime NULL;
	IF COL_LENGTH('dbo.BAN_TIPO_CHEQUE', 'ESTACION_ACTU') IS NULL
		ALTER TABLE dbo.BAN_TIPO_CHEQUE ADD ESTACION_ACTU varchar(30) NULL;
END
GO

/* BAN_TIPO_MOVI_BANCARIO */
IF OBJECT_ID(N'dbo.BAN_TIPO_MOVI_BANCARIO', N'U') IS NOT NULL
BEGIN
	IF COL_LENGTH('dbo.BAN_TIPO_MOVI_BANCARIO', 'ESTADO_TIPO_MOVIMIENTO') IS NULL
		ALTER TABLE dbo.BAN_TIPO_MOVI_BANCARIO ADD ESTADO_TIPO_MOVIMIENTO bit NOT NULL CONSTRAINT DF_BAN_TIPO_MOVI_BANCARIO_ESTADO_TIPO_MOVIMIENTO DEFAULT (1);

	IF COL_LENGTH('dbo.BAN_TIPO_MOVI_BANCARIO', 'USUARIO_CREA') IS NULL
		ALTER TABLE dbo.BAN_TIPO_MOVI_BANCARIO ADD USUARIO_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_TIPO_MOVI_BANCARIO', 'FECHA_CREA') IS NULL
		ALTER TABLE dbo.BAN_TIPO_MOVI_BANCARIO ADD FECHA_CREA datetime NULL;
	IF COL_LENGTH('dbo.BAN_TIPO_MOVI_BANCARIO', 'ESTACION_CREA') IS NULL
		ALTER TABLE dbo.BAN_TIPO_MOVI_BANCARIO ADD ESTACION_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_TIPO_MOVI_BANCARIO', 'USUARIO_ACTU') IS NULL
		ALTER TABLE dbo.BAN_TIPO_MOVI_BANCARIO ADD USUARIO_ACTU varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_TIPO_MOVI_BANCARIO', 'FECHA_ACTU') IS NULL
		ALTER TABLE dbo.BAN_TIPO_MOVI_BANCARIO ADD FECHA_ACTU datetime NULL;
	IF COL_LENGTH('dbo.BAN_TIPO_MOVI_BANCARIO', 'ESTACION_ACTU') IS NULL
		ALTER TABLE dbo.BAN_TIPO_MOVI_BANCARIO ADD ESTACION_ACTU varchar(30) NULL;
END
GO

/* BAN_CUENTA_BANCARIA — bit aparte de ESTADO_CUENTA (varchar AC/IN) */
IF OBJECT_ID(N'dbo.BAN_CUENTA_BANCARIA', N'U') IS NOT NULL
BEGIN
	IF COL_LENGTH('dbo.BAN_CUENTA_BANCARIA', 'ESTADO_CUENTA_BANCARIA') IS NULL
		ALTER TABLE dbo.BAN_CUENTA_BANCARIA ADD ESTADO_CUENTA_BANCARIA bit NOT NULL CONSTRAINT DF_BAN_CUENTA_BANCARIA_ESTADO_CUENTA_BANCARIA DEFAULT (1);

	IF COL_LENGTH('dbo.BAN_CUENTA_BANCARIA', 'USUARIO_CREA') IS NULL
		ALTER TABLE dbo.BAN_CUENTA_BANCARIA ADD USUARIO_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_CUENTA_BANCARIA', 'FECHA_CREA') IS NULL
		ALTER TABLE dbo.BAN_CUENTA_BANCARIA ADD FECHA_CREA datetime NULL;
	IF COL_LENGTH('dbo.BAN_CUENTA_BANCARIA', 'ESTACION_CREA') IS NULL
		ALTER TABLE dbo.BAN_CUENTA_BANCARIA ADD ESTACION_CREA varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_CUENTA_BANCARIA', 'USUARIO_ACTU') IS NULL
		ALTER TABLE dbo.BAN_CUENTA_BANCARIA ADD USUARIO_ACTU varchar(30) NULL;
	IF COL_LENGTH('dbo.BAN_CUENTA_BANCARIA', 'FECHA_ACTU') IS NULL
		ALTER TABLE dbo.BAN_CUENTA_BANCARIA ADD FECHA_ACTU datetime NULL;
	IF COL_LENGTH('dbo.BAN_CUENTA_BANCARIA', 'ESTACION_ACTU') IS NULL
		ALTER TABLE dbo.BAN_CUENTA_BANCARIA ADD ESTACION_ACTU varchar(30) NULL;
END
GO

PRINT N'Columnas ESTADO_* / auditoría aplicadas. Actualizar vistas CREATE OR ALTER por separado o con el resto del script.';
GO
