/* =============================================================================
   ALTER — Snapshot de textos + CORR_EMPLEADO en SC_MOVIMIENTO_PERSONAL
   Guarda CORR (referencia) + textos (UI / histórico inmutable al cambiar catálogo).

   Ejecutar:
     sqlcmd -S <srv> -d SGUEES -U <user> -P <pass> -f 65001 -i ALTER_SC_MOVIMIENTO_PERSONAL_SNAPSHOT.sql
   ============================================================================= */
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

IF OBJECT_ID(N'dbo.SC_MOVIMIENTO_PERSONAL', N'U') IS NULL
BEGIN
    RAISERROR(N'No existe SC_MOVIMIENTO_PERSONAL. Ejecute primero SC_MOVIMIENTO_PERSONAL.sql.', 16, 1);
    RETURN;
END;
GO

IF COL_LENGTH(N'dbo.SC_MOVIMIENTO_PERSONAL', N'CORR_EMPLEADO') IS NULL
BEGIN
    ALTER TABLE dbo.SC_MOVIMIENTO_PERSONAL
        ADD CORR_EMPLEADO INT NULL;  /* referencia; sin FK */
END;
GO

IF COL_LENGTH(N'dbo.SC_MOVIMIENTO_PERSONAL', N'NOMBRE_UNIDAD_ACTUAL') IS NULL
BEGIN
    ALTER TABLE dbo.SC_MOVIMIENTO_PERSONAL
        ADD NOMBRE_UNIDAD_ACTUAL NVARCHAR(150) NULL;  /* CODIGO - NOMBRE */
END;
GO

IF COL_LENGTH(N'dbo.SC_MOVIMIENTO_PERSONAL', N'NOMBRE_PUESTO_ACTUAL') IS NULL
BEGIN
    ALTER TABLE dbo.SC_MOVIMIENTO_PERSONAL
        ADD NOMBRE_PUESTO_ACTUAL NVARCHAR(200) NULL;
END;
GO

IF COL_LENGTH(N'dbo.SC_MOVIMIENTO_PERSONAL', N'NOMBRE_MODALIDAD_ACTUAL') IS NULL
BEGIN
    ALTER TABLE dbo.SC_MOVIMIENTO_PERSONAL
        ADD NOMBRE_MODALIDAD_ACTUAL NVARCHAR(100) NULL;
END;
GO

IF COL_LENGTH(N'dbo.SC_MOVIMIENTO_PERSONAL', N'NOMBRE_UNIDAD_PROPUESTA') IS NULL
BEGIN
    ALTER TABLE dbo.SC_MOVIMIENTO_PERSONAL
        ADD NOMBRE_UNIDAD_PROPUESTA NVARCHAR(150) NULL;
END;
GO

IF COL_LENGTH(N'dbo.SC_MOVIMIENTO_PERSONAL', N'NOMBRE_PUESTO_PROPUESTO') IS NULL
BEGIN
    ALTER TABLE dbo.SC_MOVIMIENTO_PERSONAL
        ADD NOMBRE_PUESTO_PROPUESTO NVARCHAR(200) NULL;
END;
GO

IF COL_LENGTH(N'dbo.SC_MOVIMIENTO_PERSONAL', N'NOMBRE_MODALIDAD_PROPUESTA') IS NULL
BEGIN
    ALTER TABLE dbo.SC_MOVIMIENTO_PERSONAL
        ADD NOMBRE_MODALIDAD_PROPUESTA NVARCHAR(100) NULL;
END;
GO

/* Relleno inicial desde catálogo (solo filas sin snapshot). */
UPDATE M
SET
    M.NOMBRE_UNIDAD_ACTUAL = ISNULL(M.NOMBRE_UNIDAD_ACTUAL,
        CASE WHEN UA.CORR_UNIDAD IS NULL THEN NULL
             ELSE CAST(UA.CODIGO_UNIDAD + N' - ' + UA.NOMBRE_UNIDAD AS NVARCHAR(150)) END),
    M.NOMBRE_PUESTO_ACTUAL = ISNULL(M.NOMBRE_PUESTO_ACTUAL, PA.NOMBRE_PUESTO),
    M.NOMBRE_MODALIDAD_ACTUAL = ISNULL(M.NOMBRE_MODALIDAD_ACTUAL, MA.MODALIDAD_NOMBRE),
    M.NOMBRE_UNIDAD_PROPUESTA = ISNULL(M.NOMBRE_UNIDAD_PROPUESTA,
        CASE WHEN UP.CORR_UNIDAD IS NULL THEN NULL
             ELSE CAST(UP.CODIGO_UNIDAD + N' - ' + UP.NOMBRE_UNIDAD AS NVARCHAR(150)) END),
    M.NOMBRE_PUESTO_PROPUESTO = ISNULL(M.NOMBRE_PUESTO_PROPUESTO, PP.NOMBRE_PUESTO),
    M.NOMBRE_MODALIDAD_PROPUESTA = ISNULL(M.NOMBRE_MODALIDAD_PROPUESTA, MP.MODALIDAD_NOMBRE)
FROM dbo.SC_MOVIMIENTO_PERSONAL AS M
LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES AS UA
    ON UA.CORR_EMPRESA = M.CORR_EMPRESA AND UA.CORR_UNIDAD = M.CORR_UNIDAD_ACTUAL
LEFT JOIN dbo.PLA_PUESTO AS PA
    ON PA.CORR_EMPRESA = M.CORR_EMPRESA AND PA.CORR_PUESTO = M.CORR_PUESTO_ACTUAL
LEFT JOIN dbo.SC_TIPO_MODALIDAD AS MA
    ON MA.CORR_EMPRESA = M.CORR_EMPRESA AND MA.CORR_TIPO_MODALIDAD = M.CORR_TIPO_MODALIDAD_ACTUAL
LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES AS UP
    ON UP.CORR_EMPRESA = M.CORR_EMPRESA AND UP.CORR_UNIDAD = M.CORR_UNIDAD_PROPUESTA
LEFT JOIN dbo.PLA_PUESTO AS PP
    ON PP.CORR_EMPRESA = M.CORR_EMPRESA AND PP.CORR_PUESTO = M.CORR_PUESTO_PROPUESTO
LEFT JOIN dbo.SC_TIPO_MODALIDAD AS MP
    ON MP.CORR_EMPRESA = M.CORR_EMPRESA AND MP.CORR_TIPO_MODALIDAD = M.CORR_TIPO_MODALIDAD_PROPUESTA;
GO

CREATE OR ALTER VIEW dbo.V_SC_MOVIMIENTO_PERSONAL
AS
SELECT
    M.CORR_EMPRESA,
    M.CORR_MOVIMIENTO_PERSONAL,
    M.FECHA_ELABORACION,
    M.ORIGEN_MOVIMIENTO,
    M.TIPO_MOVIMIENTO,
    M.ESTADO_MOVIMIENTO,
    CAST(CASE M.ESTADO_MOVIMIENTO
        WHEN 'DI' THEN N'Borrador'
        WHEN 'SO' THEN N'Solicitado'
        WHEN 'OB' THEN N'Devuelto'
        WHEN 'AP' THEN N'Aprobado'
        WHEN 'DE' THEN N'Denegado'
        WHEN 'AN' THEN N'Anulado'
        ELSE M.ESTADO_MOVIMIENTO
    END AS NVARCHAR(40)) AS NOMBRE_ESTADO_MOVIMIENTO,
    CAST(CASE M.TIPO_MOVIMIENTO
        WHEN 'PERMANENTE' THEN N'Contratación permanente'
        WHEN 'EVENTUAL' THEN N'Contratación eventual'
        WHEN 'ASCENSO' THEN N'Ascenso'
        WHEN 'TRASLADO' THEN N'Traslado'
        ELSE M.TIPO_MOVIMIENTO
    END AS NVARCHAR(60)) AS NOMBRE_TIPO_MOVIMIENTO,
    CAST(CASE M.ORIGEN_MOVIMIENTO
        WHEN 'DIRECTO' THEN N'Desde cero'
        WHEN 'REQUISICION' THEN N'Desde requisición'
        ELSE M.ORIGEN_MOVIMIENTO
    END AS NVARCHAR(40)) AS NOMBRE_ORIGEN_MOVIMIENTO,
    M.CORR_EMPLEADO,
    M.NOMBRE_COMPLETO,
    M.NUMERO_ID,
    M.FECHA_INGRESO_PROPUESTA,
    M.FECHA_FINALIZACION,
    M.GERENCIA_ACTUAL,
    M.CORR_UNIDAD_ACTUAL,
    M.NOMBRE_UNIDAD_ACTUAL,
    M.CORR_PUESTO_ACTUAL,
    M.NOMBRE_PUESTO_ACTUAL,
    M.SALARIO_ACTUAL,
    M.CORR_TIPO_MODALIDAD_ACTUAL,
    M.NOMBRE_MODALIDAD_ACTUAL,
    M.HORARIO_ACTUAL,
    M.GERENCIA_PROPUESTA,
    M.CORR_UNIDAD_PROPUESTA,
    M.NOMBRE_UNIDAD_PROPUESTA,
    M.CORR_PUESTO_PROPUESTO,
    M.NOMBRE_PUESTO_PROPUESTO,
    M.SALARIO_PROPUESTO,
    M.CORR_TIPO_MODALIDAD_PROPUESTA,
    M.NOMBRE_MODALIDAD_PROPUESTA,
    M.HORARIO_PROPUESTO,
    M.JUSTIFICACION,
    M.FECHA_EFECTIVA,
    M.CONFIRMADO,
    CAST(CASE WHEN ISNULL(M.CONFIRMADO, 0) = 1 THEN N'Confirmado' ELSE N'En Evaluación' END AS NVARCHAR(40))
        AS NOMBRE_CONFIRMACION,
    M.USUARIO_CONFIRMA,
    M.FECHA_CONFIRMA,
    M.USUARIO_CREA,
    M.ESTACION_CREA,
    M.FECHA_CREA,
    M.USUARIO_ACTU,
    M.ESTACION_ACTU,
    M.FECHA_ACTU
FROM dbo.SC_MOVIMIENTO_PERSONAL AS M;
GO

PRINT N'OK: ALTER snapshot + V_SC_MOVIMIENTO_PERSONAL.';
GO
