/*
  SC_EXPEDIENTE_DOCUMENTO — TIPO_DOCUMENTO (varchar) → CORR_TIPO_DOCUMENTO_ADJUNTO (int FK)
  Catálogo: PLA_TIPO_DOCUMENTO_ADJUNTO
  Ejecutar:
    sqlcmd -S <srv> -d SGUEES -U <user> -P <pass> -f 65001 -i SGUEES-DB/Scripts/ALTER_SC_EXPEDIENTE_DOCUMENTO_CORR_TIPO_DOCUMENTO_ADJUNTO.sql
*/

SET NOCOUNT ON;
GO

/* ========== 1) Agregar CORR_TIPO_DOCUMENTO_ADJUNTO si no existe ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_DOCUMENTO', N'CORR_TIPO_DOCUMENTO_ADJUNTO') IS NULL
BEGIN
  ALTER TABLE dbo.SC_EXPEDIENTE_DOCUMENTO
    ADD CORR_TIPO_DOCUMENTO_ADJUNTO INT NULL;
END
GO

/* ========== 2) Migrar valores textuales existentes (mejor esfuerzo) ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_DOCUMENTO', N'TIPO_DOCUMENTO') IS NOT NULL
   AND COL_LENGTH(N'dbo.SC_EXPEDIENTE_DOCUMENTO', N'CORR_TIPO_DOCUMENTO_ADJUNTO') IS NOT NULL
BEGIN
  UPDATE D
  SET D.CORR_TIPO_DOCUMENTO_ADJUNTO = T.CORR_TIPO_DOCUMENTO_ADJUNTO
  FROM dbo.SC_EXPEDIENTE_DOCUMENTO AS D
  INNER JOIN dbo.PLA_TIPO_DOCUMENTO_ADJUNTO AS T
    ON T.CORR_EMPRESA = D.CORR_EMPRESA
   AND UPPER(LTRIM(RTRIM(T.TIPO_DOCUMENTO))) = UPPER(LTRIM(RTRIM(D.TIPO_DOCUMENTO)))
  WHERE D.CORR_TIPO_DOCUMENTO_ADJUNTO IS NULL
    AND NULLIF(LTRIM(RTRIM(D.TIPO_DOCUMENTO)), N'') IS NOT NULL;
END
GO

/* ========== 3) Quitar columna textual antigua ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_DOCUMENTO', N'TIPO_DOCUMENTO') IS NOT NULL
BEGIN
  ALTER TABLE dbo.SC_EXPEDIENTE_DOCUMENTO
    DROP COLUMN TIPO_DOCUMENTO;
END
GO

/* ========== 4) NOT NULL solo si no quedan nulos ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_DOCUMENTO', N'CORR_TIPO_DOCUMENTO_ADJUNTO') IS NOT NULL
   AND NOT EXISTS (
     SELECT 1
     FROM dbo.SC_EXPEDIENTE_DOCUMENTO
     WHERE CORR_TIPO_DOCUMENTO_ADJUNTO IS NULL
   )
BEGIN
  ALTER TABLE dbo.SC_EXPEDIENTE_DOCUMENTO
    ALTER COLUMN CORR_TIPO_DOCUMENTO_ADJUNTO INT NOT NULL;
END
ELSE
BEGIN
  PRINT N'AVISO: quedan filas con CORR_TIPO_DOCUMENTO_ADJUNTO NULL; la columna permanece nullable. Asigne un tipo válido y vuelva a ejecutar la sección NOT NULL.';
END
GO

/* ========== 5) FK a PLA_TIPO_DOCUMENTO_ADJUNTO ========== */
IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = N'FK_SC_EXPEDIENTE_DOCUMENTO_TIPO'
)
BEGIN
  ALTER TABLE dbo.SC_EXPEDIENTE_DOCUMENTO WITH CHECK
    ADD CONSTRAINT FK_SC_EXPEDIENTE_DOCUMENTO_TIPO
    FOREIGN KEY (CORR_EMPRESA, CORR_TIPO_DOCUMENTO_ADJUNTO)
    REFERENCES dbo.PLA_TIPO_DOCUMENTO_ADJUNTO (CORR_EMPRESA, CORR_TIPO_DOCUMENTO_ADJUNTO);
END
GO

/* ========== 6) Vista: CORR + tipo/descripcion del catálogo ========== */
CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_DOCUMENTO
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_DOCUMENTO,
    X.FECHA_CARGA,
    X.CORR_TIPO_DOCUMENTO_ADJUNTO,
    T.TIPO_DOCUMENTO,
    T.DESCRIPCION_DOCUMENTO,
    X.NOMBRE_ARCHIVO,
    X.RUTA_ARCHIVO,
    X.NOTAS,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_DOCUMENTO AS X
LEFT JOIN dbo.PLA_TIPO_DOCUMENTO_ADJUNTO AS T
    ON T.CORR_EMPRESA = X.CORR_EMPRESA
   AND T.CORR_TIPO_DOCUMENTO_ADJUNTO = X.CORR_TIPO_DOCUMENTO_ADJUNTO;
GO

PRINT N'ALTER SC_EXPEDIENTE_DOCUMENTO → CORR_TIPO_DOCUMENTO_ADJUNTO listo.';
GO
