/* ============================================================================
   ALTER — Agregar Activo + Auditoría a PLA_AFP y PLA_SEGURO_SOCIAL
   Ejecutar en SGUEES (permiso DDL). Idempotente: solo agrega columnas si no existen.
   Después ejecutar las vistas V_PLA_AFP / V_PLA_SEGURO_SOCIAL (o DEPLOY_PLA_AFP_SEGURO_SOCIAL.sql).
   ============================================================================ */
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* ---------- PLA_AFP ---------- */
IF COL_LENGTH('dbo.PLA_AFP', 'ACTIVO_AFP') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_AFP ADD [ACTIVO_AFP] [bit] NULL;
	PRINT N'PLA_AFP: agregado ACTIVO_AFP';
END
ELSE
	PRINT N'PLA_AFP: ACTIVO_AFP ya existe';
GO

IF COL_LENGTH('dbo.PLA_AFP', 'USUARIO_CREA') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_AFP ADD [USUARIO_CREA] [varchar](50) NULL;
	PRINT N'PLA_AFP: agregado USUARIO_CREA';
END
GO

IF COL_LENGTH('dbo.PLA_AFP', 'ESTACION_CREA') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_AFP ADD [ESTACION_CREA] [varchar](50) NULL;
	PRINT N'PLA_AFP: agregado ESTACION_CREA';
END
GO

IF COL_LENGTH('dbo.PLA_AFP', 'FECHA_CREA') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_AFP ADD [FECHA_CREA] [datetime] NULL;
	PRINT N'PLA_AFP: agregado FECHA_CREA';
END
GO

IF COL_LENGTH('dbo.PLA_AFP', 'USUARIO_ACTU') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_AFP ADD [USUARIO_ACTU] [varchar](50) NULL;
	PRINT N'PLA_AFP: agregado USUARIO_ACTU';
END
GO

IF COL_LENGTH('dbo.PLA_AFP', 'ESTACION_ACTU') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_AFP ADD [ESTACION_ACTU] [varchar](50) NULL;
	PRINT N'PLA_AFP: agregado ESTACION_ACTU';
END
GO

IF COL_LENGTH('dbo.PLA_AFP', 'FECHA_ACTU') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_AFP ADD [FECHA_ACTU] [datetime] NULL;
	PRINT N'PLA_AFP: agregado FECHA_ACTU';
END
GO

UPDATE dbo.PLA_AFP
SET ACTIVO_AFP = 1
WHERE ACTIVO_AFP IS NULL;
GO

/* ---------- PLA_SEGURO_SOCIAL ---------- */
IF COL_LENGTH('dbo.PLA_SEGURO_SOCIAL', 'ACTIVO_SEGURO_SOCIAL') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_SEGURO_SOCIAL ADD [ACTIVO_SEGURO_SOCIAL] [bit] NULL;
	PRINT N'PLA_SEGURO_SOCIAL: agregado ACTIVO_SEGURO_SOCIAL';
END
ELSE
	PRINT N'PLA_SEGURO_SOCIAL: ACTIVO_SEGURO_SOCIAL ya existe';
GO

IF COL_LENGTH('dbo.PLA_SEGURO_SOCIAL', 'USUARIO_CREA') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_SEGURO_SOCIAL ADD [USUARIO_CREA] [varchar](50) NULL;
	PRINT N'PLA_SEGURO_SOCIAL: agregado USUARIO_CREA';
END
GO

IF COL_LENGTH('dbo.PLA_SEGURO_SOCIAL', 'ESTACION_CREA') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_SEGURO_SOCIAL ADD [ESTACION_CREA] [varchar](50) NULL;
	PRINT N'PLA_SEGURO_SOCIAL: agregado ESTACION_CREA';
END
GO

IF COL_LENGTH('dbo.PLA_SEGURO_SOCIAL', 'FECHA_CREA') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_SEGURO_SOCIAL ADD [FECHA_CREA] [datetime] NULL;
	PRINT N'PLA_SEGURO_SOCIAL: agregado FECHA_CREA';
END
GO

IF COL_LENGTH('dbo.PLA_SEGURO_SOCIAL', 'USUARIO_ACTU') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_SEGURO_SOCIAL ADD [USUARIO_ACTU] [varchar](50) NULL;
	PRINT N'PLA_SEGURO_SOCIAL: agregado USUARIO_ACTU';
END
GO

IF COL_LENGTH('dbo.PLA_SEGURO_SOCIAL', 'ESTACION_ACTU') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_SEGURO_SOCIAL ADD [ESTACION_ACTU] [varchar](50) NULL;
	PRINT N'PLA_SEGURO_SOCIAL: agregado ESTACION_ACTU';
END
GO

IF COL_LENGTH('dbo.PLA_SEGURO_SOCIAL', 'FECHA_ACTU') IS NULL
BEGIN
	ALTER TABLE dbo.PLA_SEGURO_SOCIAL ADD [FECHA_ACTU] [datetime] NULL;
	PRINT N'PLA_SEGURO_SOCIAL: agregado FECHA_ACTU';
END
GO

UPDATE dbo.PLA_SEGURO_SOCIAL
SET ACTIVO_SEGURO_SOCIAL = 1
WHERE ACTIVO_SEGURO_SOCIAL IS NULL;
GO

PRINT N'ALTER Activo + Auditoría en PLA_AFP / PLA_SEGURO_SOCIAL completado.';
GO
