SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/*
  Reentrada del portal por token (vigencia HorasVigenciaToken):
  - ENVIADO: correo enviado, aún sin datos del participante.
  - EN_PROCESO: el participante ya guardó al menos una vez; el link sigue válido.
  - COMPLETADO: venció la vigencia y ya había datos (EN_PROCESO).
  - EXPIRADO: venció la vigencia sin haber guardado (seguía ENVIADO).
  - REVOCADO: sin cambio (RRHH generó otro token).

  Ejecutar con: sqlcmd ... -f 65001 -i ALTER_SC_SOLICITUD_EMPLEO_TOKEN_REENTRADA.sql
*/

/* Tokens COMPLETADO que aún están en ventana de vigencia → EN_PROCESO (reabrir link). */
UPDATE dbo.SC_SOLICITUD_EMPLEO_TOKEN
   SET ESTADO_TOKEN = 'EN_PROCESO'
 WHERE ESTADO_TOKEN = 'COMPLETADO'
   AND FECHA_EXPIRACION >= GETDATE();
GO

CREATE OR ALTER PROCEDURE dbo.PRAL_DATA_SC_SOLICITUD_EMPLEO_TOKEN
    @CORR_EMPRESA int,
    @CORR_SOLICITUD_EMPLEO int
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    /* Cierre por vigencia: sin datos → EXPIRADO; con datos → COMPLETADO. */
    UPDATE dbo.SC_SOLICITUD_EMPLEO_TOKEN
       SET ESTADO_TOKEN = CASE
            WHEN ESTADO_TOKEN = 'EN_PROCESO' THEN 'COMPLETADO'
            ELSE 'EXPIRADO'
       END
     WHERE CORR_EMPRESA = @CORR_EMPRESA
       AND CORR_SOLICITUD_EMPLEO = @CORR_SOLICITUD_EMPLEO
       AND ESTADO_TOKEN IN ('ENVIADO', 'EN_PROCESO')
       AND FECHA_EXPIRACION < GETDATE();

    SELECT
        CORR_EMPRESA,
        CORR_TOKEN,
        CORR_SOLICITUD_EMPLEO,
        CASE
            WHEN TOKEN_HASH IS NULL THEN NULL
            WHEN LEN(TOKEN_HASH) <= 12 THEN TOKEN_HASH
            ELSE LEFT(TOKEN_HASH, 8) + '...' + RIGHT(TOKEN_HASH, 4)
        END AS TOKEN_HASH,
        FECHA_GENERACION,
        FECHA_EXPIRACION,
        FECHA_UTILIZACION,
        ESTADO_TOKEN,
        CORREO_DESTINO
    FROM dbo.SC_SOLICITUD_EMPLEO_TOKEN
    WHERE CORR_EMPRESA = @CORR_EMPRESA
      AND CORR_SOLICITUD_EMPLEO = @CORR_SOLICITUD_EMPLEO
    ORDER BY CORR_TOKEN DESC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.PRAL_MTTO_SC_SOLICITUD_EMPLEO_TOKEN_GENERAR
    @CORR_EMPRESA int,
    @CORR_SOLICITUD_EMPLEO int,
    @TOKEN_HASH varchar(64),
    @FECHA_GENERACION datetime,
    @FECHA_EXPIRACION datetime,
    @CORREO_DESTINO varchar(254)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRANSACTION;

    IF NOT EXISTS (
        SELECT 1
        FROM dbo.SC_SOLICITUD_EMPLEO WITH (UPDLOCK, HOLDLOCK)
        WHERE CORR_EMPRESA = @CORR_EMPRESA
          AND CORR_SOLICITUD_EMPLEO = @CORR_SOLICITUD_EMPLEO
          AND ACTIVO = 1
    )
    BEGIN
        THROW 50001, N'La solicitud de empleo no existe o esta inactiva.', 1;
    END;

    UPDATE dbo.SC_SOLICITUD_EMPLEO_TOKEN
       SET ESTADO_TOKEN = CASE
            WHEN FECHA_EXPIRACION < @FECHA_GENERACION THEN
                CASE WHEN ESTADO_TOKEN = 'EN_PROCESO' THEN 'COMPLETADO' ELSE 'EXPIRADO' END
            ELSE 'REVOCADO'
       END
     WHERE CORR_EMPRESA = @CORR_EMPRESA
       AND CORR_SOLICITUD_EMPLEO = @CORR_SOLICITUD_EMPLEO
       AND ESTADO_TOKEN IN ('GENERADO', 'ENVIADO', 'EN_PROCESO');

    DECLARE @CORR_TOKEN int;

    SELECT @CORR_TOKEN = ISNULL(MAX(CORR_TOKEN), 0) + 1
    FROM dbo.SC_SOLICITUD_EMPLEO_TOKEN WITH (UPDLOCK, HOLDLOCK)
    WHERE CORR_EMPRESA = @CORR_EMPRESA;

    INSERT INTO dbo.SC_SOLICITUD_EMPLEO_TOKEN (
        CORR_EMPRESA,
        CORR_TOKEN,
        CORR_SOLICITUD_EMPLEO,
        TOKEN_HASH,
        FECHA_GENERACION,
        FECHA_EXPIRACION,
        FECHA_UTILIZACION,
        ESTADO_TOKEN,
        CORREO_DESTINO
    )
    VALUES (
        @CORR_EMPRESA,
        @CORR_TOKEN,
        @CORR_SOLICITUD_EMPLEO,
        @TOKEN_HASH,
        @FECHA_GENERACION,
        @FECHA_EXPIRACION,
        NULL,
        'GENERADO',
        @CORREO_DESTINO
    );

    COMMIT TRANSACTION;

    SELECT
        CORR_EMPRESA,
        CORR_TOKEN,
        CORR_SOLICITUD_EMPLEO,
        TOKEN_HASH,
        FECHA_GENERACION,
        FECHA_EXPIRACION,
        FECHA_UTILIZACION,
        ESTADO_TOKEN,
        CORREO_DESTINO
    FROM dbo.V_SC_SOLICITUD_EMPLEO_TOKEN
    WHERE CORR_EMPRESA = @CORR_EMPRESA
      AND CORR_TOKEN = @CORR_TOKEN;
END;
GO

CREATE OR ALTER PROCEDURE dbo.PRAL_DATA_SC_SOLICITUD_EMPLEO_PUBLICO_VALIDAR
    @TOKEN_HASH varchar(64)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    UPDATE dbo.SC_SOLICITUD_EMPLEO_TOKEN
       SET ESTADO_TOKEN = CASE
            WHEN ESTADO_TOKEN = 'EN_PROCESO' THEN 'COMPLETADO'
            ELSE 'EXPIRADO'
       END
     WHERE TOKEN_HASH = @TOKEN_HASH
       AND ESTADO_TOKEN IN ('ENVIADO', 'EN_PROCESO')
       AND FECHA_EXPIRACION < GETDATE();

    SELECT
        CAST(1 AS bit) AS VALIDO,
        T.CORR_EMPRESA,
        T.FECHA_EXPIRACION,
        T.ESTADO_TOKEN,
        CAST(CASE WHEN S.CORR_PERSONA_DATOS IS NOT NULL AND S.CORR_PERSONA_DATOS > 0 THEN 1 ELSE 0 END AS bit) AS YA_TIENE_DATOS,
        ISNULL(S.CORR_PERSONA_DATOS, 0) AS CORR_PERSONA_DATOS,
        ISNULL(S.CORR_TIPO_CONTRATACION, 0) AS CORR_TIPO_CONTRATACION,
        TC.NOMBRE_TIPO_CONTRATACION,
        CAST(ISNULL(TC.ES_PERMANENTE, 0) AS bit) AS ES_PERMANENTE,
        LTRIM(RTRIM(ISNULL(NULLIF(S.CORREO_INVITACION, ''), T.CORREO_DESTINO))) AS CORREO_INVITACION
    FROM dbo.SC_SOLICITUD_EMPLEO_TOKEN T
    INNER JOIN dbo.SC_SOLICITUD_EMPLEO S
        ON S.CORR_EMPRESA = T.CORR_EMPRESA
       AND S.CORR_SOLICITUD_EMPLEO = T.CORR_SOLICITUD_EMPLEO
    LEFT JOIN dbo.SC_TIPO_CONTRATACION TC
        ON TC.CORR_EMPRESA = S.CORR_EMPRESA
       AND TC.CORR_TIPO_CONTRATACION = S.CORR_TIPO_CONTRATACION
    WHERE T.TOKEN_HASH = @TOKEN_HASH
      AND T.ESTADO_TOKEN IN ('ENVIADO', 'EN_PROCESO')
      AND T.FECHA_EXPIRACION >= GETDATE()
      AND S.ACTIVO = 1;
END;
GO

CREATE OR ALTER PROCEDURE dbo.PRAL_MTTO_SC_SOLICITUD_EMPLEO_PUBLICO_COMPLETAR
    @TOKEN_HASH varchar(64),
    @NOMBRE1 varchar(50),
    @NOMBRE2 varchar(50) = NULL,
    @APELLIDO1 varchar(50),
    @APELLIDO2 varchar(50) = NULL,
    @FECHA_NACIMIENTO date,
    @EDAD int,
    @ESTADO_CIVIL varchar(50) = NULL,
    @NACIONALIDAD varchar(100) = NULL,
    @CORREO varchar(254),
    @CELULAR varchar(25),
    @TELEFONO varchar(25) = NULL,
    @DIRECCION varchar(500),
    @DUI varchar(25),
    @PASAPORTE varchar(50) = NULL,
    @ISSS varchar(50) = NULL,
    @AFP varchar(50) = NULL,
    @NOMBRE_AFP varchar(100) = NULL,
    @LICENCIA varchar(50) = NULL,
    @PLAZA_SOLICITADA varchar(250) = NULL,
    @PRETENSION_SALARIAL int,
    @DISPONIBILIDAD varchar(100) = NULL,
    @RELIGION varchar(100) = NULL,
    @IGLESIA varchar(250) = NULL,
    @DIRECCION_IGLESIA varchar(500) = NULL,
    @ES_CONTRIBUYENTE_CCF bit,
    @ES_JUBILADO bit,
    @POSEE_DISCAPACIDAD bit,
    @TIPO_DISCAPACIDAD varchar(250) = NULL,
    @EMERGENCIA_NOMBRE varchar(150),
    @EMERGENCIA_PARENTESCO varchar(100) = NULL,
    @EMERGENCIA_TELEFONO varchar(25),
    @TIENE_FAMILIARES_UEES bit,
    @DECLARA_VERDAD bit,
    @AUTORIZA_VERIFICACION bit,
    @FECHA_DECLARACION datetime,
    @FIRMA_ELECTRONICA varchar(250) = NULL,
    @FOTO_URL varchar(500) = NULL,
    /* Colecciones en XML (texto): SGUEES compatibility_level 100 no admite OPENJSON. */
    @FAMILIARES_DIRECTOS_XML nvarchar(max) = NULL,
    @HIJOS_XML nvarchar(max) = NULL,
    @ESTUDIOS_XML nvarchar(max) = NULL,
    @IDIOMAS_XML nvarchar(max) = NULL,
    @COMPETENCIAS_XML nvarchar(max) = NULL,
    @EXPERIENCIAS_XML nvarchar(max) = NULL,
    @FAMILIARES_UEES_XML nvarchar(max) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @CORR_EMPRESA int,
            @CORR_TOKEN int,
            @CORR_SOLICITUD_EMPLEO int,
            @CORR_PERSONA_DATOS int,
            @FECHA_AUDITORIA datetime = GETDATE(),
            @USUARIO_AUDITORIA varchar(30) = 'PORTAL_CANDIDATOS',
            @ESTACION_AUDITORIA varchar(50) = 'FORMULARIO_PUBLICO',
            @XML_FAMILIARES xml,
            @XML_HIJOS xml,
            @XML_ESTUDIOS xml,
            @XML_IDIOMAS xml,
            @XML_COMPETENCIAS xml,
            @XML_EXPERIENCIAS xml,
            @XML_FAMILIARES_UEES xml;

    BEGIN TRY
        BEGIN TRANSACTION;

        SET @XML_FAMILIARES = CAST(COALESCE(NULLIF(@FAMILIARES_DIRECTOS_XML, N''), N'<rows/>') AS xml);
        SET @XML_HIJOS = CAST(COALESCE(NULLIF(@HIJOS_XML, N''), N'<rows/>') AS xml);
        SET @XML_ESTUDIOS = CAST(COALESCE(NULLIF(@ESTUDIOS_XML, N''), N'<rows/>') AS xml);
        SET @XML_IDIOMAS = CAST(COALESCE(NULLIF(@IDIOMAS_XML, N''), N'<rows/>') AS xml);
        SET @XML_COMPETENCIAS = CAST(COALESCE(NULLIF(@COMPETENCIAS_XML, N''), N'<rows/>') AS xml);
        SET @XML_EXPERIENCIAS = CAST(COALESCE(NULLIF(@EXPERIENCIAS_XML, N''), N'<rows/>') AS xml);
        SET @XML_FAMILIARES_UEES = CAST(COALESCE(NULLIF(@FAMILIARES_UEES_XML, N''), N'<rows/>') AS xml);

        SELECT
            @CORR_EMPRESA = T.CORR_EMPRESA,
            @CORR_TOKEN = T.CORR_TOKEN,
            @CORR_SOLICITUD_EMPLEO = T.CORR_SOLICITUD_EMPLEO,
            @CORR_PERSONA_DATOS = S.CORR_PERSONA_DATOS
        FROM dbo.SC_SOLICITUD_EMPLEO_TOKEN T WITH (UPDLOCK, HOLDLOCK)
        INNER JOIN dbo.SC_SOLICITUD_EMPLEO S WITH (UPDLOCK, HOLDLOCK)
            ON S.CORR_EMPRESA = T.CORR_EMPRESA
           AND S.CORR_SOLICITUD_EMPLEO = T.CORR_SOLICITUD_EMPLEO
        WHERE T.TOKEN_HASH = @TOKEN_HASH
          AND T.ESTADO_TOKEN IN ('ENVIADO', 'EN_PROCESO')
          AND T.FECHA_EXPIRACION >= GETDATE()
          AND S.ACTIVO = 1;

        IF @CORR_TOKEN IS NULL
            THROW 50002, N'El enlace es invalido, expiro o ya no esta vigente.', 1;

        /* Primer guardado = INSERT; reentradas = UPDATE + reemplazo de colecciones. */
        IF @CORR_PERSONA_DATOS IS NULL OR @CORR_PERSONA_DATOS <= 0
        BEGIN
        SELECT @CORR_PERSONA_DATOS = ISNULL(MAX(CORR_PERSONA_DATOS), 0) + 1
        FROM dbo.SC_PERSONA_DATOS WITH (UPDLOCK, HOLDLOCK)
        WHERE CORR_EMPRESA = @CORR_EMPRESA;

        INSERT INTO dbo.SC_PERSONA_DATOS (
            CORR_EMPRESA, CORR_PERSONA_DATOS, NOMBRE1, NOMBRE2, APELLIDO1, APELLIDO2,
            FECHA_NACIMIENTO, EDAD, ESTADO_CIVIL, NACIONALIDAD, CORREO, CELULAR, TELEFONO,
            DIRECCION, DUI, PASAPORTE, ISSS, AFP, NOMBRE_AFP, LICENCIA, PLAZA_SOLICITADA,
            PRETENSION_SALARIAL, DISPONIBILIDAD, RELIGION, IGLESIA, DIRECCION_IGLESIA,
            ES_CONTRIBUYENTE_CCF, ES_JUBILADO, POSEE_DISCAPACIDAD, TIPO_DISCAPACIDAD,
            EMERGENCIA_NOMBRE, EMERGENCIA_PARENTESCO, EMERGENCIA_TELEFONO,
            TIENE_FAMILIARES_UEES, DECLARA_VERDAD, AUTORIZA_VERIFICACION,
            FECHA_DECLARACION, FIRMA_ELECTRONICA, FOTO_URL
        )
        VALUES (
            @CORR_EMPRESA, @CORR_PERSONA_DATOS, @NOMBRE1, NULLIF(LTRIM(RTRIM(@NOMBRE2)), ''),
            @APELLIDO1, NULLIF(LTRIM(RTRIM(@APELLIDO2)), ''), @FECHA_NACIMIENTO, ISNULL(@EDAD, 0),
            NULLIF(LTRIM(RTRIM(@ESTADO_CIVIL)), ''), NULLIF(LTRIM(RTRIM(@NACIONALIDAD)), ''),
            @CORREO, @CELULAR, NULLIF(LTRIM(RTRIM(@TELEFONO)), ''), @DIRECCION, @DUI,
            NULLIF(LTRIM(RTRIM(@PASAPORTE)), ''), NULLIF(LTRIM(RTRIM(@ISSS)), ''),
            NULLIF(LTRIM(RTRIM(@AFP)), ''), NULLIF(LTRIM(RTRIM(@NOMBRE_AFP)), ''),
            NULLIF(LTRIM(RTRIM(@LICENCIA)), ''), NULLIF(LTRIM(RTRIM(@PLAZA_SOLICITADA)), ''),
            ISNULL(@PRETENSION_SALARIAL, 0), NULLIF(LTRIM(RTRIM(@DISPONIBILIDAD)), ''),
            NULLIF(LTRIM(RTRIM(@RELIGION)), ''), NULLIF(LTRIM(RTRIM(@IGLESIA)), ''),
            NULLIF(LTRIM(RTRIM(@DIRECCION_IGLESIA)), ''), ISNULL(@ES_CONTRIBUYENTE_CCF, 0),
            ISNULL(@ES_JUBILADO, 0), ISNULL(@POSEE_DISCAPACIDAD, 0),
            NULLIF(LTRIM(RTRIM(@TIPO_DISCAPACIDAD)), ''), @EMERGENCIA_NOMBRE,
            NULLIF(LTRIM(RTRIM(@EMERGENCIA_PARENTESCO)), ''), @EMERGENCIA_TELEFONO,
            ISNULL(@TIENE_FAMILIARES_UEES, 0), ISNULL(@DECLARA_VERDAD, 0),
            ISNULL(@AUTORIZA_VERIFICACION, 0), @FECHA_DECLARACION,
            NULLIF(LTRIM(RTRIM(@FIRMA_ELECTRONICA)), ''),
            NULLIF(LTRIM(RTRIM(@FOTO_URL)), '')
        );
            UPDATE dbo.SC_SOLICITUD_EMPLEO
               SET CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS
             WHERE CORR_EMPRESA = @CORR_EMPRESA
               AND CORR_SOLICITUD_EMPLEO = @CORR_SOLICITUD_EMPLEO;
        END
        ELSE
        BEGIN
            UPDATE dbo.SC_PERSONA_DATOS
               SET NOMBRE1 = @NOMBRE1,
                   NOMBRE2 = NULLIF(LTRIM(RTRIM(@NOMBRE2)), ''),
                   APELLIDO1 = @APELLIDO1,
                   APELLIDO2 = NULLIF(LTRIM(RTRIM(@APELLIDO2)), ''),
                   FECHA_NACIMIENTO = @FECHA_NACIMIENTO,
                   EDAD = ISNULL(@EDAD, 0),
                   ESTADO_CIVIL = NULLIF(LTRIM(RTRIM(@ESTADO_CIVIL)), ''),
                   NACIONALIDAD = NULLIF(LTRIM(RTRIM(@NACIONALIDAD)), ''),
                   CORREO = @CORREO,
                   CELULAR = @CELULAR,
                   TELEFONO = NULLIF(LTRIM(RTRIM(@TELEFONO)), ''),
                   DIRECCION = @DIRECCION,
                   DUI = @DUI,
                   PASAPORTE = NULLIF(LTRIM(RTRIM(@PASAPORTE)), ''),
                   ISSS = NULLIF(LTRIM(RTRIM(@ISSS)), ''),
                   AFP = NULLIF(LTRIM(RTRIM(@AFP)), ''),
                   NOMBRE_AFP = NULLIF(LTRIM(RTRIM(@NOMBRE_AFP)), ''),
                   LICENCIA = NULLIF(LTRIM(RTRIM(@LICENCIA)), ''),
                   PLAZA_SOLICITADA = NULLIF(LTRIM(RTRIM(@PLAZA_SOLICITADA)), ''),
                   PRETENSION_SALARIAL = ISNULL(@PRETENSION_SALARIAL, 0),
                   DISPONIBILIDAD = NULLIF(LTRIM(RTRIM(@DISPONIBILIDAD)), ''),
                   RELIGION = NULLIF(LTRIM(RTRIM(@RELIGION)), ''),
                   IGLESIA = NULLIF(LTRIM(RTRIM(@IGLESIA)), ''),
                   DIRECCION_IGLESIA = NULLIF(LTRIM(RTRIM(@DIRECCION_IGLESIA)), ''),
                   ES_CONTRIBUYENTE_CCF = ISNULL(@ES_CONTRIBUYENTE_CCF, 0),
                   ES_JUBILADO = ISNULL(@ES_JUBILADO, 0),
                   POSEE_DISCAPACIDAD = ISNULL(@POSEE_DISCAPACIDAD, 0),
                   TIPO_DISCAPACIDAD = NULLIF(LTRIM(RTRIM(@TIPO_DISCAPACIDAD)), ''),
                   EMERGENCIA_NOMBRE = @EMERGENCIA_NOMBRE,
                   EMERGENCIA_PARENTESCO = NULLIF(LTRIM(RTRIM(@EMERGENCIA_PARENTESCO)), ''),
                   EMERGENCIA_TELEFONO = @EMERGENCIA_TELEFONO,
                   TIENE_FAMILIARES_UEES = ISNULL(@TIENE_FAMILIARES_UEES, 0),
                   DECLARA_VERDAD = ISNULL(@DECLARA_VERDAD, 0),
                   AUTORIZA_VERIFICACION = ISNULL(@AUTORIZA_VERIFICACION, 0),
                   FECHA_DECLARACION = @FECHA_DECLARACION,
                   FIRMA_ELECTRONICA = NULLIF(LTRIM(RTRIM(@FIRMA_ELECTRONICA)), ''),
                   FOTO_URL = COALESCE(NULLIF(LTRIM(RTRIM(@FOTO_URL)), ''), FOTO_URL)
             WHERE CORR_EMPRESA = @CORR_EMPRESA
               AND CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;

            DELETE FROM dbo.SC_PERSONA_FAMILIAR
             WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;
            DELETE FROM dbo.SC_PERSONA_HIJOS
             WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;
            DELETE FROM dbo.SC_PERSONA_ESTUDIO
             WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;
            DELETE FROM dbo.SC_PERSONA_IDIOMAS
             WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;
            DELETE FROM dbo.SC_PERSONA_COMPETENCIAS_TECNICAS
             WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;
            DELETE FROM dbo.SC_PERSONA_EXPERIENCIA_LABORAL
             WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;
            DELETE FROM dbo.SC_PERSONA_FAMILIAR_UEES
             WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;
        END;

        /* Formato XML: <rows><row ATTR="..." /></rows> — compatible con level 100. */
        INSERT INTO dbo.SC_PERSONA_FAMILIAR (
            CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_FAMILIAR, TIPO, NOMBRE,
            DOMICILIO, FECHA_NACIMIENTO, OCUPACION,
            USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
        )
        SELECT @CORR_EMPRESA, @CORR_PERSONA_DATOS,
               ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
               NULLIF(LTRIM(RTRIM(T.X.value('@TIPO', 'varchar(50)'))), ''),
               NULLIF(LTRIM(RTRIM(T.X.value('@NOMBRE', 'varchar(150)'))), ''),
               NULLIF(LTRIM(RTRIM(T.X.value('@DOMICILIO', 'varchar(500)'))), ''),
               T.X.value('@FECHA_NACIMIENTO', 'date'),
               NULLIF(LTRIM(RTRIM(T.X.value('@OCUPACION', 'varchar(150)'))), ''),
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA,
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA
        FROM @XML_FAMILIARES.nodes('/rows/row') AS T(X)
        WHERE NULLIF(LTRIM(RTRIM(T.X.value('@NOMBRE', 'varchar(150)'))), '') IS NOT NULL
           OR NULLIF(LTRIM(RTRIM(T.X.value('@DOMICILIO', 'varchar(500)'))), '') IS NOT NULL
           OR T.X.value('@FECHA_NACIMIENTO', 'date') IS NOT NULL
           OR NULLIF(LTRIM(RTRIM(T.X.value('@OCUPACION', 'varchar(150)'))), '') IS NOT NULL;

        INSERT INTO dbo.SC_PERSONA_HIJOS (
            CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_HIJO, NOMBRE, EDAD, SEXO,
            FECHA_NACIMIENTO,
            USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
        )
        SELECT @CORR_EMPRESA, @CORR_PERSONA_DATOS,
               ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
               NULLIF(LTRIM(RTRIM(T.X.value('@NOMBRE', 'varchar(150)'))), ''),
               T.X.value('@EDAD', 'int'),
               NULLIF(LTRIM(RTRIM(T.X.value('@SEXO', 'varchar(25)'))), ''),
               T.X.value('@FECHA_NACIMIENTO', 'date'),
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA,
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA
        FROM @XML_HIJOS.nodes('/rows/row') AS T(X)
        WHERE NULLIF(LTRIM(RTRIM(T.X.value('@NOMBRE', 'varchar(150)'))), '') IS NOT NULL;

        INSERT INTO dbo.SC_PERSONA_ESTUDIO (
            CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_ESTUDIO, NIVEL, INSTITUCION,
            DESDE, HASTA, TITULO,
            USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
        )
        SELECT @CORR_EMPRESA, @CORR_PERSONA_DATOS,
               ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
               NULLIF(LTRIM(RTRIM(T.X.value('@NIVEL', 'varchar(100)'))), ''),
               NULLIF(LTRIM(RTRIM(T.X.value('@INSTITUCION', 'varchar(250)'))), ''),
               T.X.value('@DESDE', 'date'),
               T.X.value('@HASTA', 'date'),
               NULLIF(LTRIM(RTRIM(T.X.value('@TITULO', 'varchar(250)'))), ''),
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA,
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA
        FROM @XML_ESTUDIOS.nodes('/rows/row') AS T(X)
        WHERE NULLIF(LTRIM(RTRIM(T.X.value('@NIVEL', 'varchar(100)'))), '') IS NOT NULL
           OR NULLIF(LTRIM(RTRIM(T.X.value('@INSTITUCION', 'varchar(250)'))), '') IS NOT NULL
           OR NULLIF(LTRIM(RTRIM(T.X.value('@TITULO', 'varchar(250)'))), '') IS NOT NULL;

        INSERT INTO dbo.SC_PERSONA_IDIOMAS (
            CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_IDIOMA, IDIOMA, NIVEL,
            USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
        )
        SELECT @CORR_EMPRESA, @CORR_PERSONA_DATOS,
               ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
               NULLIF(LTRIM(RTRIM(T.X.value('@IDIOMA', 'varchar(100)'))), ''),
               NULLIF(LTRIM(RTRIM(T.X.value('@NIVEL', 'varchar(100)'))), ''),
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA,
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA
        FROM @XML_IDIOMAS.nodes('/rows/row') AS T(X)
        WHERE NULLIF(LTRIM(RTRIM(T.X.value('@IDIOMA', 'varchar(100)'))), '') IS NOT NULL;

        INSERT INTO dbo.SC_PERSONA_COMPETENCIAS_TECNICAS (
            CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_COMPETENCIA_TECNICA,
            HERRAMIENTA, NIVEL,
            USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
        )
        SELECT @CORR_EMPRESA, @CORR_PERSONA_DATOS,
               ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
               NULLIF(LTRIM(RTRIM(T.X.value('@HERRAMIENTA', 'varchar(150)'))), ''),
               NULLIF(LTRIM(RTRIM(T.X.value('@NIVEL', 'varchar(100)'))), ''),
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA,
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA
        FROM @XML_COMPETENCIAS.nodes('/rows/row') AS T(X)
        WHERE NULLIF(LTRIM(RTRIM(T.X.value('@HERRAMIENTA', 'varchar(150)'))), '') IS NOT NULL;

        INSERT INTO dbo.SC_PERSONA_EXPERIENCIA_LABORAL (
            CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_EXPERIENCIA_LABORAL,
            EMPRESA, TELEFONO, CARGO, JEFE_INMEDIATO, FECHA_INICIO, FECHA_FIN,
            SALARIO_INICIAL, SALARIO_FINAL, MOTIVO_SALIDA,
            USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
        )
        SELECT @CORR_EMPRESA, @CORR_PERSONA_DATOS,
               ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
               NULLIF(LTRIM(RTRIM(T.X.value('@EMPRESA', 'varchar(250)'))), ''),
               NULLIF(LTRIM(RTRIM(T.X.value('@TELEFONO', 'varchar(25)'))), ''),
               NULLIF(LTRIM(RTRIM(T.X.value('@CARGO', 'varchar(150)'))), ''),
               NULLIF(LTRIM(RTRIM(T.X.value('@JEFE_INMEDIATO', 'varchar(150)'))), ''),
               T.X.value('@FECHA_INICIO', 'date'),
               T.X.value('@FECHA_FIN', 'date'),
               T.X.value('@SALARIO_INICIAL', 'decimal(18,2)'),
               T.X.value('@SALARIO_FINAL', 'decimal(18,2)'),
               NULLIF(LTRIM(RTRIM(T.X.value('@MOTIVO_SALIDA', 'varchar(500)'))), ''),
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA,
               @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA
        FROM @XML_EXPERIENCIAS.nodes('/rows/row') AS T(X)
        WHERE NULLIF(LTRIM(RTRIM(T.X.value('@EMPRESA', 'varchar(250)'))), '') IS NOT NULL
           OR NULLIF(LTRIM(RTRIM(T.X.value('@CARGO', 'varchar(150)'))), '') IS NOT NULL;

        IF ISNULL(@TIENE_FAMILIARES_UEES, 0) = 1
        BEGIN
            INSERT INTO dbo.SC_PERSONA_FAMILIAR_UEES (
                CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_FAMILIAR_UEES,
                NOMBRE, PARENTESCO, UNIDAD, TELEFONO,
                USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
            )
            SELECT @CORR_EMPRESA, @CORR_PERSONA_DATOS,
                   ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
                   NULLIF(LTRIM(RTRIM(T.X.value('@NOMBRE', 'varchar(150)'))), ''),
                   NULLIF(LTRIM(RTRIM(T.X.value('@PARENTESCO', 'varchar(100)'))), ''),
                   NULLIF(LTRIM(RTRIM(T.X.value('@UNIDAD', 'varchar(150)'))), ''),
                   NULLIF(LTRIM(RTRIM(T.X.value('@TELEFONO', 'varchar(25)'))), ''),
                   @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA,
                   @USUARIO_AUDITORIA, @ESTACION_AUDITORIA, @FECHA_AUDITORIA
            FROM @XML_FAMILIARES_UEES.nodes('/rows/row') AS T(X)
            WHERE NULLIF(LTRIM(RTRIM(T.X.value('@NOMBRE', 'varchar(150)'))), '') IS NOT NULL;
        END;

        /* EN_PROCESO = ya guardo; el link sigue valido hasta FECHA_EXPIRACION. */
        UPDATE dbo.SC_SOLICITUD_EMPLEO_TOKEN
           SET ESTADO_TOKEN = 'EN_PROCESO',
               FECHA_UTILIZACION = ISNULL(FECHA_UTILIZACION, @FECHA_AUDITORIA)
         WHERE CORR_EMPRESA = @CORR_EMPRESA
           AND CORR_TOKEN = @CORR_TOKEN;

        COMMIT TRANSACTION;

        SELECT @CORR_EMPRESA AS CORR_EMPRESA,
               @CORR_PERSONA_DATOS AS CORR_PERSONA_DATOS,
               CAST(1 AS bit) AS COMPLETADO;
    END TRY
    BEGIN CATCH
        DECLARE @NUMERO_ERROR int = ERROR_NUMBER(),
                @SEVERITY_ERROR int = ERROR_SEVERITY(),
                @ESTADO_ERROR int = ERROR_STATE(),
                @ORIGEN_ERROR nvarchar(126) = ERROR_PROCEDURE(),
                @LINEA_ERROR int = ERROR_LINE(),
                @MENSAJE_ERROR nvarchar(4000) = ERROR_MESSAGE(),
                @CORR_BITACORA numeric(38, 0) = 0;

        IF XACT_STATE() <> 0
            ROLLBACK TRANSACTION;

        IF @NUMERO_ERROR <> 50002
        BEGIN
            EXEC dbo.PRAL_MTTO_ADMIN_BITACORA_SISTEMA
                1, @CORR_BITACORA OUTPUT, 'PM', @NUMERO_ERROR, @SEVERITY_ERROR,
                @ESTADO_ERROR, @ORIGEN_ERROR, @LINEA_ERROR, @MENSAJE_ERROR,
                'PORTAL_CANDIDATOS', @FECHA_AUDITORIA, 'FORMULARIO_PUBLICO';
        END;

        THROW;
    END CATCH;
END;
GO
