/*
  Quita ESTADO_CUENTA (varchar AC/IN) de BAN_CUENTA_BANCARIA.
  Sustituido por ESTADO_CUENTA_BANCARIA (bit).
  Ejecutar después de actualizar V_BAN_CUENTA_BANCARIA.
*/
SET NOCOUNT ON;
GO

IF COL_LENGTH('dbo.BAN_CUENTA_BANCARIA', 'ESTADO_CUENTA') IS NOT NULL
BEGIN
	ALTER TABLE dbo.BAN_CUENTA_BANCARIA DROP COLUMN ESTADO_CUENTA;
	PRINT N'Columna ESTADO_CUENTA eliminada de BAN_CUENTA_BANCARIA.';
END
ELSE
	PRINT N'ESTADO_CUENTA ya no existe.';
GO
