/*
  SC_EXPEDIENTE_ENTREVISTA — agregar CORR_REQUISICION_PERSONAL (proceso individual por requisición)
  + V_SC_EXPEDIENTE_SOLICITUD explota 1 fila por requisición vinculada a la solicitud.

  Ejecutar:
    sqlcmd -S <srv> -d SGUEES -U <user> -P <pass> -f 65001 -i SGUEES-DB/Scripts/ALTER_SC_EXPEDIENTE_ENTREVISTA_CORR_REQUISICION.sql
*/

SET NOCOUNT ON;
GO

/* ========== 1) Columna CORR_REQUISICION_PERSONAL ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_ENTREVISTA', N'CORR_REQUISICION_PERSONAL') IS NULL
BEGIN
  ALTER TABLE dbo.SC_EXPEDIENTE_ENTREVISTA
    ADD CORR_REQUISICION_PERSONAL INT NULL;
END
GO

/* ========== 2) Migración: si la solicitud tiene exactamente 1 requisición, asignarla ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_ENTREVISTA', N'CORR_REQUISICION_PERSONAL') IS NOT NULL
BEGIN
  ;WITH UnicaReq AS (
    SELECT
      SR.CORR_EMPRESA,
      SR.CORR_SOLICITUD_EMPLEO,
      MIN(SR.CORR_REQUISICION_PERSONAL) AS CORR_REQUISICION_PERSONAL
    FROM dbo.SC_SOLICITUD_REQUISICION AS SR
    GROUP BY SR.CORR_EMPRESA, SR.CORR_SOLICITUD_EMPLEO
    HAVING COUNT(*) = 1
  )
  UPDATE E
  SET E.CORR_REQUISICION_PERSONAL = U.CORR_REQUISICION_PERSONAL
  FROM dbo.SC_EXPEDIENTE_ENTREVISTA AS E
  INNER JOIN UnicaReq AS U
    ON U.CORR_EMPRESA = E.CORR_EMPRESA
   AND U.CORR_SOLICITUD_EMPLEO = E.CORR_SOLICITUD_EMPLEO
  WHERE E.CORR_REQUISICION_PERSONAL IS NULL;
END
GO

/* ========== 3) NOT NULL solo si no quedan nulos ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_ENTREVISTA', N'CORR_REQUISICION_PERSONAL') IS NOT NULL
   AND NOT EXISTS (
     SELECT 1
     FROM dbo.SC_EXPEDIENTE_ENTREVISTA
     WHERE CORR_REQUISICION_PERSONAL IS NULL
   )
BEGIN
  ALTER TABLE dbo.SC_EXPEDIENTE_ENTREVISTA
    ALTER COLUMN CORR_REQUISICION_PERSONAL INT NOT NULL;
END
ELSE
BEGIN
  PRINT N'AVISO: quedan entrevistas sin CORR_REQUISICION_PERSONAL (solicitud con 0 o >1 requisiciones). Asigne manualmente o re-registre esas entrevistas.';
END
GO

/* ========== 4) FK a SC_REQUISICION_PERSONAL ========== */
IF NOT EXISTS (
  SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SC_EXPEDIENTE_ENTREVISTA_REQUISICION'
)
BEGIN
  ALTER TABLE dbo.SC_EXPEDIENTE_ENTREVISTA WITH CHECK
    ADD CONSTRAINT FK_SC_EXPEDIENTE_ENTREVISTA_REQUISICION
    FOREIGN KEY (CORR_EMPRESA, CORR_REQUISICION_PERSONAL)
    REFERENCES dbo.SC_REQUISICION_PERSONAL (CORR_EMPRESA, CORR_REQUISICION_PERSONAL);
END
GO

/* ========== 5) Índice de consulta por solicitud + requisición ========== */
IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = N'IX_SC_EXPEDIENTE_ENTREVISTA_SOL_REQ'
    AND object_id = OBJECT_ID(N'dbo.SC_EXPEDIENTE_ENTREVISTA')
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_SC_EXPEDIENTE_ENTREVISTA_SOL_REQ
    ON dbo.SC_EXPEDIENTE_ENTREVISTA (
      CORR_EMPRESA,
      CORR_EXPEDIENTE_CANDIDATO,
      CORR_SOLICITUD_EMPLEO,
      CORR_REQUISICION_PERSONAL
    );
END
GO

/* ========== 6) Vista entrevistas ========== */
CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_ENTREVISTA
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_ENTREVISTA,
    X.CORR_SOLICITUD_EMPLEO,
    X.CORR_REQUISICION_PERSONAL,
    X.CORR_TIPO_ENTREVISTA,
    T.TIPO_ENTREVISTA,
    T.DESCRIPCION_ENTREVISTA,
    X.FECHA_ENTREVISTA,
    X.ENTREVISTADOR,
    X.ESTADO_ENTREVISTA,
    X.RESULTADO_ENTREVISTA,
    X.RESUMEN_ENTREVISTA,
    S.CORREO_INVITACION,
    S.NOMBRE AS NOMBRE_SOLICITUD,
    R.NOMBRE_UNIDAD,
    R.NOMBRE_PUESTO,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_ENTREVISTA AS X
INNER JOIN dbo.SC_SOLICITUD_EMPLEO AS S
    ON S.CORR_EMPRESA = X.CORR_EMPRESA
   AND S.CORR_SOLICITUD_EMPLEO = X.CORR_SOLICITUD_EMPLEO
LEFT JOIN dbo.SC_TIPO_ENTREVISTA AS T
    ON T.CORR_EMPRESA = X.CORR_EMPRESA
   AND T.CORR_TIPO_ENTREVISTA = X.CORR_TIPO_ENTREVISTA
LEFT JOIN dbo.V_SC_REQUISICION_PERSONAL AS R
    ON R.CORR_EMPRESA = X.CORR_EMPRESA
   AND R.CORR_REQUISICION_PERSONAL = X.CORR_REQUISICION_PERSONAL;
GO

/* ========== 7) Vista solicitudes asociadas: 1 fila por requisición ========== */
CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_SOLICITUD
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_SOLICITUD,
    X.CORR_SOLICITUD_EMPLEO,
    SR.CORR_SOLICITUD_REQUISICION,
    SR.CORR_REQUISICION_PERSONAL,
    R.NOMBRE_UNIDAD,
    R.MODALIDAD_NOMBRE,
    R.SALARIO,
    S.FECHA_GENERACION AS FECHA_SOLICITUD,
    S.CORREO_INVITACION,
    S.DUI AS DUI_SOLICITUD,
    S.NOMBRE AS NOMBRE_SOLICITUD,
    S.CORR_TIPO_CONTRATACION,
    T.NOMBRE_TIPO_CONTRATACION,
    S.CORR_PERSONA_DATOS,
    S.ACTIVO AS ACTIVO_SOLICITUD,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_SOLICITUD AS X
INNER JOIN dbo.SC_SOLICITUD_EMPLEO AS S
    ON S.CORR_EMPRESA = X.CORR_EMPRESA
   AND S.CORR_SOLICITUD_EMPLEO = X.CORR_SOLICITUD_EMPLEO
LEFT JOIN dbo.SC_TIPO_CONTRATACION AS T
    ON T.CORR_EMPRESA = S.CORR_EMPRESA
   AND T.CORR_TIPO_CONTRATACION = S.CORR_TIPO_CONTRATACION
LEFT JOIN dbo.SC_SOLICITUD_REQUISICION AS SR
    ON SR.CORR_EMPRESA = X.CORR_EMPRESA
   AND SR.CORR_SOLICITUD_EMPLEO = X.CORR_SOLICITUD_EMPLEO
LEFT JOIN dbo.V_SC_REQUISICION_PERSONAL AS R
    ON R.CORR_EMPRESA = SR.CORR_EMPRESA
   AND R.CORR_REQUISICION_PERSONAL = SR.CORR_REQUISICION_PERSONAL;
GO

PRINT N'ALTER SC_EXPEDIENTE_ENTREVISTA / vistas (requisición) listos.';
GO
