SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/*
  Requisición personal: reemplaza NOMBRE_PUESTO_SOLICITADO (texto)
  por CORR_PUESTO (FK a PLA_PUESTO). Actualiza vistas dependientes.

  Ejecutar (UTF-8):
  sqlcmd -S <srv> -d SGUEES -U <user> -P <pwd> -f 65001 -i ALTER_SC_REQUISICION_PERSONAL_CORR_PUESTO.sql
*/

/* -------------------------------------------------------------------------- */
/* 1) Tabla SC_REQUISICION_PERSONAL                                           */
/* -------------------------------------------------------------------------- */
IF COL_LENGTH(N'dbo.SC_REQUISICION_PERSONAL', N'CORR_PUESTO') IS NULL
BEGIN
    ALTER TABLE dbo.SC_REQUISICION_PERSONAL
        ADD CORR_PUESTO INT NULL;
END;
GO

/* Best-effort: rellena CORR_PUESTO desde el descriptor vinculado. */
IF COL_LENGTH(N'dbo.SC_REQUISICION_PERSONAL', N'CORR_PUESTO') IS NOT NULL
   AND COL_LENGTH(N'dbo.SC_REQUISICION_PERSONAL', N'CORR_DESCRIPTOR_PUESTO') IS NOT NULL
   AND OBJECT_ID(N'dbo.SC_DESCRIPTOR_PUESTO', N'U') IS NOT NULL
BEGIN
    UPDATE R
    SET R.CORR_PUESTO = D.CORR_PUESTO
    FROM dbo.SC_REQUISICION_PERSONAL AS R
    INNER JOIN dbo.SC_DESCRIPTOR_PUESTO AS D
        ON D.CORR_EMPRESA = R.CORR_EMPRESA
       AND D.CORR_DESCRIPTOR_PUESTO = R.CORR_DESCRIPTOR_PUESTO
    WHERE R.CORR_PUESTO IS NULL
      AND D.CORR_PUESTO IS NOT NULL
      AND D.CORR_PUESTO > 0;
END;
GO

IF COL_LENGTH(N'dbo.SC_REQUISICION_PERSONAL', N'CORR_PUESTO') IS NOT NULL
   AND OBJECT_ID(N'dbo.PLA_PUESTO', N'U') IS NOT NULL
   AND NOT EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE name = N'FK_SC_REQUISICION_PERSONAL_PLA_PUESTO'
          AND parent_object_id = OBJECT_ID(N'dbo.SC_REQUISICION_PERSONAL')
    )
BEGIN
    ALTER TABLE dbo.SC_REQUISICION_PERSONAL WITH NOCHECK
        ADD CONSTRAINT FK_SC_REQUISICION_PERSONAL_PLA_PUESTO
        FOREIGN KEY (CORR_EMPRESA, CORR_PUESTO)
        REFERENCES dbo.PLA_PUESTO (CORR_EMPRESA, CORR_PUESTO);
END;
GO

IF COL_LENGTH(N'dbo.SC_REQUISICION_PERSONAL', N'NOMBRE_PUESTO_SOLICITADO') IS NOT NULL
BEGIN
    ALTER TABLE dbo.SC_REQUISICION_PERSONAL
        DROP COLUMN NOMBRE_PUESTO_SOLICITADO;
END;
GO

/* -------------------------------------------------------------------------- */
/* 2) Vista V_SC_REQUISICION_PERSONAL                                         */
/*    Nota: recrea la vista alineada al modelo API actual.                    */
/* -------------------------------------------------------------------------- */
CREATE OR ALTER VIEW dbo.V_SC_REQUISICION_PERSONAL
AS
SELECT
    R.CORR_EMPRESA,
    R.CORR_REQUISICION_PERSONAL,
    R.CORR_DESCRIPTOR_PUESTO,
    R.CORR_UNIDAD,
    U.NOMBRE_UNIDAD,
    R.CORR_PUESTO,
    P.NOMBRE_PUESTO,
    R.CORR_TIPO_MODALIDAD,
    M.MODALIDAD_NOMBRE,
    R.CORR_TIPO_CONTRATACION,
    TC.NOMBRE_TIPO_CONTRATACION,
    R.CORR_TIPO_VACANTE,
    TV.NOMBRE_TIPO_VACANTE,
    R.CANTIDAD_PLAZAS,
    R.PLAZAS_CUBIERTAS,
    R.FECHA_REQUISICION,
    R.JUSTIFICACION,
    R.CORR_EMPLEADO_SUSTITUTO,
    R.SALARIO,
    R.CORR_ESTADO_REQUISICION,
    R.FECHA_APROBACION,
    R.FECHA_CIERRE,
    R.TIEMPO_CONTRATO,
    R.HORARIO,
    R.USUARIO_CREA,
    R.ESTACION_CREA,
    R.FECHA_CREA,
    R.USUARIO_ACTU,
    R.ESTACION_ACTU,
    R.FECHA_ACTU
FROM dbo.SC_REQUISICION_PERSONAL AS R
LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES AS U
    ON U.CORR_EMPRESA = R.CORR_EMPRESA
   AND U.CORR_UNIDAD = R.CORR_UNIDAD
LEFT JOIN dbo.PLA_PUESTO AS P
    ON P.CORR_EMPRESA = R.CORR_EMPRESA
   AND P.CORR_PUESTO = R.CORR_PUESTO
LEFT JOIN dbo.SC_TIPO_MODALIDAD AS M
    ON M.CORR_EMPRESA = R.CORR_EMPRESA
   AND M.CORR_TIPO_MODALIDAD = R.CORR_TIPO_MODALIDAD
LEFT JOIN dbo.SC_TIPO_CONTRATACION AS TC
    ON TC.CORR_EMPRESA = R.CORR_EMPRESA
   AND TC.CORR_TIPO_CONTRATACION = R.CORR_TIPO_CONTRATACION
LEFT JOIN dbo.SC_TIPO_VACANTE AS TV
    ON TV.CORR_EMPRESA = R.CORR_EMPRESA
   AND TV.CORR_TIPO_VACANTE = R.CORR_TIPO_VACANTE;
GO

/* -------------------------------------------------------------------------- */
/* 3) Vista puente V_SC_SOLICITUD_REQUISICION                                 */
/* -------------------------------------------------------------------------- */
CREATE OR ALTER VIEW dbo.V_SC_SOLICITUD_REQUISICION
AS
SELECT
    L.CORR_EMPRESA,
    L.CORR_SOLICITUD_REQUISICION,
    L.CORR_SOLICITUD_EMPLEO,
    L.CORR_REQUISICION_PERSONAL,
    R.FECHA_REQUISICION,
    R.NOMBRE_UNIDAD,
    R.CORR_PUESTO,
    R.NOMBRE_PUESTO,
    R.MODALIDAD_NOMBRE,
    R.NOMBRE_TIPO_CONTRATACION,
    R.NOMBRE_TIPO_VACANTE,
    R.CANTIDAD_PLAZAS,
    R.PLAZAS_CUBIERTAS,
    R.SALARIO,
    R.TIEMPO_CONTRATO,
    R.HORARIO,
    R.JUSTIFICACION,
    R.CORR_EMPLEADO_SUSTITUTO,
    R.CORR_ESTADO_REQUISICION,
    R.FECHA_APROBACION,
    R.FECHA_CIERRE
FROM dbo.SC_SOLICITUD_REQUISICION AS L
INNER JOIN dbo.V_SC_REQUISICION_PERSONAL AS R
    ON R.CORR_EMPRESA = L.CORR_EMPRESA
   AND R.CORR_REQUISICION_PERSONAL = L.CORR_REQUISICION_PERSONAL;
GO

PRINT N'OK: SC_REQUISICION_PERSONAL + vistas actualizadas (CORR_PUESTO).';
GO
