/*
  SC_EXPEDIENTE_DOCUMENTO — quitar relación con SC_SOLICITUD_EMPLEO
  Los documentos pertenecen solo al expediente (CORR_EXPEDIENTE_CANDIDATO).

  Ejecutar:
  sqlcmd -S <srv> -d SGUEES -U <user> -f 65001 -i SGUEES-DB/Scripts/ALTER_SC_EXPEDIENTE_DOCUMENTO_DROP_SOLICITUD.sql
*/

SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.SC_EXPEDIENTE_DOCUMENTO', N'U') IS NULL
BEGIN
  RAISERROR(N'La tabla dbo.SC_EXPEDIENTE_DOCUMENTO no existe.', 16, 1);
  RETURN;
END
GO

/* ========== FK solicitud ========== */
IF EXISTS (
  SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SC_EXPEDIENTE_DOCUMENTO_SOLICITUD'
)
BEGIN
  ALTER TABLE [dbo].[SC_EXPEDIENTE_DOCUMENTO]
    DROP CONSTRAINT [FK_SC_EXPEDIENTE_DOCUMENTO_SOLICITUD];
  PRINT N'FK_SC_EXPEDIENTE_DOCUMENTO_SOLICITUD eliminada.';
END
GO

/* ========== Columna CORR_SOLICITUD_EMPLEO ========== */
IF COL_LENGTH(N'dbo.SC_EXPEDIENTE_DOCUMENTO', N'CORR_SOLICITUD_EMPLEO') IS NOT NULL
BEGIN
  ALTER TABLE [dbo].[SC_EXPEDIENTE_DOCUMENTO]
    DROP COLUMN [CORR_SOLICITUD_EMPLEO];
  PRINT N'Columna CORR_SOLICITUD_EMPLEO eliminada.';
END
GO

/* ========== Vista (sin join a solicitud) ========== */
CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_DOCUMENTO
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_DOCUMENTO,
    X.FECHA_CARGA,
    X.TIPO_DOCUMENTO,
    X.NOMBRE_ARCHIVO,
    X.RUTA_ARCHIVO,
    X.NOTAS,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_DOCUMENTO AS X;
GO

PRINT N'V_SC_EXPEDIENTE_DOCUMENTO actualizada (sin CORR_SOLICITUD_EMPLEO).';
GO
