/*
  Balance General — solo datos SGUEES (sin linked server CLASS).
  Elimina FN_CLASS_GASTOINGRESO y redeploy PRAL_IMPR_BALANCE_GENERAL.

  sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i DEPLOY_FIX_BALANCE_SIN_CLASS.sql
*/
SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.FN_CLASS_GASTOINGRESO', N'FN') IS NOT NULL
    DROP FUNCTION dbo.FN_CLASS_GASTOINGRESO;
GO

IF OBJECT_ID(N'dbo.PRAL_IMPR_BALANCE_GENERAL', N'P') IS NOT NULL
    DROP PROCEDURE dbo.PRAL_IMPR_BALANCE_GENERAL;
GO

:r "..\Stored Procedures\dbo.PRAL_IMPR_BALANCE_GENERAL.sql"
GO

PRINT N'PRAL_IMPR_BALANCE_GENERAL desplegado sin CLASS.';
GO
