/*
  Despliega tablas generales del módulo Banco (admin e-Admin -> SGUEES).
  Bancos: usa GEN_BANCO (ya existente por empresa). COM_BANCO no se usa.

  Uso:
    cd "c:\Desarrollo GIT\SGUEES\SGUEES-DB\Scripts"
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -i DEPLOY_BAN_TABLAS_GENERALES.sql
*/
SET NOCOUNT ON;
GO

IF OBJECT_ID('dbo.GEN_BANCO', 'U') IS NULL
BEGIN
    RAISERROR('GEN_BANCO no existe. Despliegue GEN_BANCO antes de continuar.', 16, 1);
    RETURN;
END
ELSE
    PRINT 'GEN_BANCO OK.';
GO

IF OBJECT_ID('dbo.BAN_LINEA_TRABAJO_CONCILIACION', 'U') IS NULL
BEGIN
    PRINT 'Creando BAN_LINEA_TRABAJO_CONCILIACION...';
    :r ..\Tables\dbo.BAN_LINEA_TRABAJO_CONCILIACION.sql
END
ELSE
    PRINT 'BAN_LINEA_TRABAJO_CONCILIACION OK.';
GO

IF OBJECT_ID('dbo.BAN_TIPO_CHEQUE', 'U') IS NULL
BEGIN
    PRINT 'Creando BAN_TIPO_CHEQUE...';
    :r ..\Tables\dbo.BAN_TIPO_CHEQUE.sql
END
ELSE
    PRINT 'BAN_TIPO_CHEQUE OK.';
GO

IF OBJECT_ID('dbo.BAN_TIPO_MOVI_BANCARIO', 'U') IS NULL
BEGIN
    PRINT 'Creando BAN_TIPO_MOVI_BANCARIO...';
    :r ..\Tables\dbo.BAN_TIPO_MOVI_BANCARIO.sql
END
ELSE
    PRINT 'BAN_TIPO_MOVI_BANCARIO OK.';
GO

IF OBJECT_ID('dbo.BAN_CUENTA_BANCARIA', 'U') IS NULL
BEGIN
    PRINT 'Creando BAN_CUENTA_BANCARIA...';
    :r ..\Tables\dbo.BAN_CUENTA_BANCARIA.sql
END
ELSE IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_BAN_CUENTA_BANCARIA_GEN_BANCO')
BEGIN
    PRINT 'Agregando FK_BAN_CUENTA_BANCARIA_GEN_BANCO...';
    ALTER TABLE dbo.BAN_CUENTA_BANCARIA
        ADD CONSTRAINT FK_BAN_CUENTA_BANCARIA_GEN_BANCO
        FOREIGN KEY (CORR_EMPRESA, CORR_BANCO) REFERENCES dbo.GEN_BANCO (CORR_EMPRESA, CORR_BANCO);
END
ELSE
    PRINT 'BAN_CUENTA_BANCARIA OK.';
GO

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME IN (
    'GEN_BANCO',
    'BAN_LINEA_TRABAJO_CONCILIACION',
    'BAN_TIPO_CHEQUE',
    'BAN_TIPO_MOVI_BANCARIO',
    'BAN_CUENTA_BANCARIA'
)
ORDER BY 1;
GO
