/* Deploy idempotente — vistas GEN_PROVEEDOR / GEN_EMPLEADO / GEN_CLIENTE (SGUEES) */
SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.GEN_CLIENTE', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[GEN_CLIENTE]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[CORR_CLIENTE] [int] NOT NULL,
		[CODIGO_CLIENTE] [varchar](50) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_GEN_CLIENTE_CODIGO] DEFAULT (N''),
		[NOMBRE_CLIENTE] [varchar](150) COLLATE Latin1_General_CS_AS NOT NULL,
		[NOMBRE_CONTACTO] [varchar](150) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_GEN_CLIENTE_CONTACTO] DEFAULT (N''),
		[DUI] [varchar](25) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_GEN_CLIENTE_DUI] DEFAULT (N''),
		[NIT] [varchar](25) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_GEN_CLIENTE_NIT] DEFAULT (N''),
		[TELEFONO_1] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_GEN_CLIENTE_TEL] DEFAULT (N''),
		[CORREO_ELECTRONICO] [varchar](255) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_GEN_CLIENTE_CORREO] DEFAULT (N''),
		[ESTA_ACTIVO] [bit] NOT NULL CONSTRAINT [DF_GEN_CLIENTE_ACTIVO] DEFAULT ((1)),
		[USUARIO_CREA] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
		[FECHA_CREA] [datetime] NOT NULL,
		[ESTACION_CREA] [varchar](50) COLLATE Latin1_General_CS_AS NOT NULL,
		[USUARIO_ACTU] [varchar](30) COLLATE Latin1_General_CS_AS NULL,
		[FECHA_ACTU] [datetime] NULL,
		[ESTACION_ACTU] [varchar](50) COLLATE Latin1_General_CS_AS NULL
	) ON [PRIMARY];

	ALTER TABLE [dbo].[GEN_CLIENTE]
		ADD CONSTRAINT [PK_GEN_CLIENTE]
		PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CLIENTE]) ON [PRIMARY];
END
GO

IF OBJECT_ID(N'dbo.V_GEN_PROVEEDOR', N'V') IS NOT NULL
	DROP VIEW [dbo].[V_GEN_PROVEEDOR];
GO
:r ..\Views\dbo.V_GEN_PROVEEDOR.sql

IF OBJECT_ID(N'dbo.V_GEN_EMPLEADO', N'V') IS NOT NULL
	DROP VIEW [dbo].[V_GEN_EMPLEADO];
GO
:r ..\Views\dbo.V_GEN_EMPLEADO.sql

IF OBJECT_ID(N'dbo.V_GEN_CLIENTE', N'V') IS NOT NULL
	DROP VIEW [dbo].[V_GEN_CLIENTE];
GO
:r ..\Views\dbo.V_GEN_CLIENTE.sql

PRINT N'DEPLOY_GEN_TERCEROS completado.';
GO
