/* Deploy idempotente — BAN_CHEQUERA (detalle cuentas bancarias) */
SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.BAN_CHEQUERA', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BAN_CHEQUERA]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[CORR_CUENTA_BANCO] [int] NOT NULL,
		[CORR_CHEQUERA] [int] NOT NULL,
		[NUMERO_CHEQUE_INICIAL] [int] NOT NULL,
		[NUMERO_CHEQUE_FINAL] [int] NOT NULL,
		[NUMERO_CHEQUE_ACTUAL] [int] NOT NULL,
		[SERIE_CHEQUE] [varchar] (10) COLLATE Latin1_General_CS_AS NOT NULL,
		[ESTADO_CHEQUERA] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL
	) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_CHEQUERA]
		ADD CONSTRAINT [PK_BAN_CHEQUERA]
		PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CHEQUERA]) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_CHEQUERA]
		ADD CONSTRAINT [FK_BAN_CHEQUERA_BAN_CUENTA_BANCARIA]
		FOREIGN KEY ([CORR_EMPRESA], [CORR_CUENTA_BANCO])
		REFERENCES [dbo].[BAN_CUENTA_BANCARIA] ([CORR_EMPRESA], [CORR_CUENTA_BANCO]);
END
GO

IF OBJECT_ID(N'dbo.V_BAN_CHEQUERA', N'V') IS NOT NULL
	DROP VIEW [dbo].[V_BAN_CHEQUERA];
GO

CREATE VIEW [dbo].[V_BAN_CHEQUERA]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_CUENTA_BANCO,
	B.NUMERO_CUENTA_BANCO,
	A.CORR_CHEQUERA,
	A.NUMERO_CHEQUE_INICIAL,
	A.NUMERO_CHEQUE_FINAL,
	A.NUMERO_CHEQUE_ACTUAL,
	A.SERIE_CHEQUE,
	A.ESTADO_CHEQUERA,
	B.CLASE_CHEQUE
FROM dbo.BAN_CHEQUERA A
INNER JOIN dbo.BAN_CUENTA_BANCARIA B
	ON A.CORR_EMPRESA = B.CORR_EMPRESA
	AND A.CORR_CUENTA_BANCO = B.CORR_CUENTA_BANCO;
GO

IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_CHEQUERA', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_CHEQUERA];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_CHEQUERA]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@CORR_CUENTA_BANCO INT,
	@CORR_CHEQUERA INT OUTPUT,
	@NUMERO_CHEQUE_INICIAL INT = 0,
	@NUMERO_CHEQUE_FINAL INT = 0,
	@NUMERO_CHEQUE_ACTUAL INT = 0,
	@SERIE_CHEQUE VARCHAR(10) = '',
	@ESTADO_CHEQUERA VARCHAR(2) = 'AC',
	@VALIDAR_PERMISO BIT = 0,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		@SYS_NUMERO_ERROR = 0,
		@SYS_MENSAJE_ERROR = N'',
		@SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1, 2)
		BEGIN
			IF ISNULL(@NUMERO_CHEQUE_INICIAL, 0) <= 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El número de cheque inicial no puede ser menor o igual a cero', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
			IF ISNULL(@NUMERO_CHEQUE_FINAL, 0) <= 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El número de cheque final no puede ser menor o igual a cero', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
			IF ISNULL(@NUMERO_CHEQUE_ACTUAL, 0) <= 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El número de cheque actual no puede ser menor o igual a cero', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
			IF ISNULL(@NUMERO_CHEQUE_INICIAL, 0) >= ISNULL(@NUMERO_CHEQUE_FINAL, 0)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El número de cheque inicial no puede ser mayor o igual al número final', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
			IF (ISNULL(@NUMERO_CHEQUE_ACTUAL, 0) > ISNULL(@NUMERO_CHEQUE_FINAL, 0) OR ISNULL(@NUMERO_CHEQUE_ACTUAL, 0) < ISNULL(@NUMERO_CHEQUE_INICIAL, 0))
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El número de cheque actual debe estar entre el número inicial y el final', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
			IF @VALIDAR_PERMISO = 1 AND @TIPO_ACTUALIZA = 2
			   AND EXISTS (
					SELECT 1 FROM dbo.BAN_CUENTA_BANCARIA
					WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO AND ISNULL(NO_PERMITE_MODIFICAR, 0) = 1
			   )
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No se permiten modificaciones a esta chequera', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		IF @TIPO_ACTUALIZA = 1
		BEGIN
			SELECT @CORR_CHEQUERA = ISNULL(MAX(CORR_CHEQUERA), 0) + 1
			FROM dbo.BAN_CHEQUERA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO;

			SET @ESTADO_CHEQUERA = 'AC';

			INSERT INTO dbo.BAN_CHEQUERA
			(CORR_EMPRESA, CORR_CUENTA_BANCO, CORR_CHEQUERA, NUMERO_CHEQUE_INICIAL, NUMERO_CHEQUE_FINAL, NUMERO_CHEQUE_ACTUAL, SERIE_CHEQUE, ESTADO_CHEQUERA)
			VALUES
			(@CORR_EMPRESA, @CORR_CUENTA_BANCO, @CORR_CHEQUERA, @NUMERO_CHEQUE_INICIAL, @NUMERO_CHEQUE_FINAL, @NUMERO_CHEQUE_ACTUAL, @SERIE_CHEQUE, @ESTADO_CHEQUERA);
		END
		ELSE IF @TIPO_ACTUALIZA = 2
		BEGIN
			UPDATE dbo.BAN_CHEQUERA
			SET NUMERO_CHEQUE_INICIAL = @NUMERO_CHEQUE_INICIAL,
				NUMERO_CHEQUE_FINAL = @NUMERO_CHEQUE_FINAL,
				NUMERO_CHEQUE_ACTUAL = @NUMERO_CHEQUE_ACTUAL,
				SERIE_CHEQUE = @SERIE_CHEQUE,
				ESTADO_CHEQUERA = @ESTADO_CHEQUERA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO AND CORR_CHEQUERA = @CORR_CHEQUERA;
		END
		ELSE IF @TIPO_ACTUALIZA = 3
		BEGIN
			DELETE FROM dbo.BAN_CHEQUERA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO AND CORR_CHEQUERA = @CORR_CHEQUERA;
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

PRINT N'BAN_CHEQUERA desplegado correctamente.';
GO
