/* Deploy idempotente — Contabilización bancaria (SGUEES) */
SET NOCOUNT ON;

/* ── Dependencia contabilidad: detalle partida ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_CON_PARTIDA_DETA', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_CON_PARTIDA_DETA];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_CON_PARTIDA_DETA]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_CLASE_PARTIDA INT,
	@CORR_PARTIDA INT,
	@CORR_PARTIDA_DETA INT OUTPUT,
	@CUENTA_CONTABLE VARCHAR(30),
	@CORR_CENTRO_COSTO INT = NULL,
	@MONTO_CARGO DECIMAL(18, 4) = 0,
	@MONTO_ABONO DECIMAL(18, 4) = 0,
	@NOMBRE_TRAN VARCHAR(1255) = '',
	@MONTO_CARGO_FORANEA DECIMAL(12, 4) = NULL,
	@MONTO_ABONO_FORANEA DECIMAL(12, 4) = NULL,
	@FACTOR_CAMBIO DECIMAL(12, 6) = NULL,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT,
	@CORR_AUXILIAR INT = NULL
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1, 2)
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM dbo.CON_CATALOGO_CUENTA
				WHERE CORR_EMPRESA = @CORR_EMPRESA
					AND CUENTA_CONTABLE = @CUENTA_CONTABLE
					AND ES_DETALLE = 1
					AND NO_HABILITADA = 0
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000,
					@SYS_MENSAJE_ERROR = N'Cuenta: ' + @CUENTA_CONTABLE + N'. Seleccione una cuenta de detalle habilitada.',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF NOT EXISTS (
				SELECT 1 FROM dbo.CON_CENTRO_COSTO
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CENTRO_COSTO = @CORR_CENTRO_COSTO
			)
				SET @CORR_CENTRO_COSTO = NULL;

			IF @MONTO_ABONO < 0 OR @MONTO_CARGO < 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No introduzca montos negativos', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF @MONTO_ABONO > 0 AND @MONTO_CARGO > 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Escriba al menos un monto igual que cero', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.CON_PARTIDA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA
				AND CORR_PARTIDA = @CORR_PARTIDA
				AND ESTADO_PARTIDA = 'DI'
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El documento no puede ser modificado o eliminado.', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF @TIPO_ACTUALIZA = 1
		BEGIN
			IF ISNULL(@CORR_PARTIDA_DETA, 0) = 0
			BEGIN
				SELECT @CORR_PARTIDA_DETA = ISNULL(MAX(CORR_PARTIDA_DETA), 0) + 1
				FROM dbo.CON_PARTIDA_DETA
				WHERE CORR_EMPRESA = @CORR_EMPRESA
					AND ANIO_PERIODO = @ANIO_PERIODO
					AND MES_PERIODO = @MES_PERIODO
					AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA
					AND CORR_PARTIDA = @CORR_PARTIDA;
			END;

			INSERT INTO dbo.CON_PARTIDA_DETA
			(
				CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_CLASE_PARTIDA, CORR_PARTIDA, CORR_PARTIDA_DETA,
				CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO,
				MONTO_CARGO_FORANEA, MONTO_ABONO_FORANEA, CORR_AUXILIAR
			)
			VALUES
			(
				@CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, @CORR_CLASE_PARTIDA, @CORR_PARTIDA, @CORR_PARTIDA_DETA,
				@CUENTA_CONTABLE, @CORR_CENTRO_COSTO, @NOMBRE_TRAN, @MONTO_CARGO, @MONTO_ABONO,
				ISNULL(@MONTO_CARGO_FORANEA, 0), ISNULL(@MONTO_ABONO_FORANEA, 0), @CORR_AUXILIAR
			);
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Parámetros bancarios por empresa ── */
IF OBJECT_ID(N'dbo.BAN_PARAMETRO', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BAN_PARAMETRO]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[CONTABILIZAR_LUEGO_DE_APLICAR] [bit] NOT NULL CONSTRAINT [DF_BAN_PARAM_APLICAR] DEFAULT ((1)),
		[CONTABILIZAR_LUEGO_DE_IMPRIMIR] [bit] NOT NULL CONSTRAINT [DF_BAN_PARAM_IMPRIMIR] DEFAULT ((1)),
		CONSTRAINT [PK_BAN_PARAMETRO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA])
	) ON [PRIMARY];
	PRINT N'Tabla BAN_PARAMETRO creada.';
END
ELSE
	PRINT N'Tabla BAN_PARAMETRO ya existe.';
GO

INSERT INTO dbo.BAN_PARAMETRO (CORR_EMPRESA, CONTABILIZAR_LUEGO_DE_APLICAR, CONTABILIZAR_LUEGO_DE_IMPRIMIR)
SELECT G.CORR_EMPRESA, 1, 1
FROM dbo.GEN_EMPRESA G
WHERE NOT EXISTS (SELECT 1 FROM dbo.BAN_PARAMETRO P WHERE P.CORR_EMPRESA = G.CORR_EMPRESA);
GO

/* ── Vínculo documento bancario ↔ partida contable ── */
IF OBJECT_ID(N'dbo.BAN_PARTIDA_DETA', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BAN_PARTIDA_DETA]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[ANIO_PERIODO] [int] NOT NULL,
		[MES_PERIODO] [int] NOT NULL,
		[CORR_CLASE_PARTIDA] [int] NOT NULL,
		[CORR_PARTIDA] [int] NOT NULL,
		[CORR_PARTIDA_DETA] [int] NOT NULL,
		[CORR_TIPO_MOVIMIENTO] [int] NOT NULL,
		[CORR_DOCUMENTO] [int] NOT NULL,
		[ANIO_PERIODO_DOC] [int] NOT NULL,
		[MES_PERIODO_DOC] [int] NOT NULL,
		CONSTRAINT [PK_BAN_PARTIDA_DETA]
			PRIMARY KEY CLUSTERED (
				[CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_CLASE_PARTIDA],
				[CORR_PARTIDA], [CORR_PARTIDA_DETA], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO],
				[ANIO_PERIODO_DOC], [MES_PERIODO_DOC]
			)
	) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_PARTIDA_DETA]
		ADD CONSTRAINT [FK_BAN_PARTIDA_DETA_CON_PARTIDA_DETA]
		FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_CLASE_PARTIDA], [CORR_PARTIDA], [CORR_PARTIDA_DETA])
		REFERENCES [dbo].[CON_PARTIDA_DETA] ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_CLASE_PARTIDA], [CORR_PARTIDA], [CORR_PARTIDA_DETA]);

	ALTER TABLE [dbo].[BAN_PARTIDA_DETA]
		ADD CONSTRAINT [FK_BAN_PARTIDA_DETA_BAN_DOCUMENTO]
		FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO_DOC], [MES_PERIODO_DOC], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO])
		REFERENCES [dbo].[BAN_DOCUMENTO] ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO]);

	PRINT N'Tabla BAN_PARTIDA_DETA creada.';
END
ELSE
	PRINT N'Tabla BAN_PARTIDA_DETA ya existe.';
GO

/* ── Contabilizar documento bancario ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_DOCUMENTO_CONTABILIZAR', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_CONTABILIZAR];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_CONTABILIZAR]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE
		@TIPO_ACTUALIZA INT,
		@MONTO_CARGO DECIMAL(18, 2),
		@MONTO_ABONO DECIMAL(18, 2),
		@DETALLE_DOCUMENTO NVARCHAR(255),
		@NOMBRE_TIPO_MOVIMIENTO VARCHAR(100),
		@CORR_CLASE_PARTIDA INT,
		@CORR_PARTIDA INT,
		@CORR_PARTIDA_DETA INT,
		@ANIO_PERIODO_CON INT,
		@MES_PERIODO_CON INT,
		@FECHA_PARTIDA DATE,
		@NUMERO_DOCUMENTO BIGINT,
		@NOMBRE_PARTIDA VARCHAR(1000),
		@ESTADO_DOCUMENTO VARCHAR(2),
		@ESTA_CONTABILIZADO BIT,
		@CORR_MONEDA INT,
		@FACTOR_CAMBIO DECIMAL(16, 6),
		@OPERADOR VARCHAR(2),
		@CORR_DOCUMENTO_DETA INT,
		@CUENTA_CONTABLE_DETA VARCHAR(30),
		@CORR_CENTRO_COSTO_DETA INT,
		@NOMBRE_TRAN_DETA VARCHAR(1255),
		@MONTO_CARGO_DETA DECIMAL(18, 2),
		@MONTO_ABONO_DETA DECIMAL(18, 2),
		@NUMERO_DOCUMENTO_STR VARCHAR(25);

	DECLARE @TEMP TABLE
	(
		CORR_DOCUMENTO_DETA INT NOT NULL,
		CUENTA_CONTABLE VARCHAR(30) NOT NULL,
		CORR_CENTRO_COSTO INT NULL,
		NOMBRE_TRAN VARCHAR(1255) NOT NULL,
		MONTO_CARGO DECIMAL(18, 2) NOT NULL,
		MONTO_ABONO DECIMAL(18, 2) NOT NULL,
		ESTA_PROC BIT NOT NULL DEFAULT (0)
	);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;
	SET @FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE());

	BEGIN TRY
		SELECT @NOMBRE_TIPO_MOVIMIENTO = NOMBRE_TIPO_MOVIMIENTO, @CORR_CLASE_PARTIDA = CORR_CLASE_PARTIDA
		FROM dbo.BAN_TIPO_MOVI_BANCARIO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO;

		SET @DETALLE_DOCUMENTO = @NOMBRE_TIPO_MOVIMIENTO + N' del Año ' + CONVERT(VARCHAR(10), @ANIO_PERIODO)
			+ N' Mes ' + CONVERT(VARCHAR(10), @MES_PERIODO)
			+ N' Correlativo No.' + CONVERT(VARCHAR(10), @CORR_DOCUMENTO);

		SELECT
			@ESTADO_DOCUMENTO = ESTADO_DOCUMENTO,
			@ESTA_CONTABILIZADO = ESTA_CONTABILIZADO,
			@FECHA_PARTIDA = FECHA_EMISION,
			@NUMERO_DOCUMENTO = NUMERO_DOCUMENTO,
			@NOMBRE_PARTIDA = NOMBRE_PARTIDA,
			@CORR_MONEDA = CORR_MONEDA,
			@FACTOR_CAMBIO = FACTOR_CAMBIO,
			@OPERADOR = OPERADOR,
			@ANIO_PERIODO_CON = ANIO_PERIODO,
			@MES_PERIODO_CON = MES_PERIODO
		FROM dbo.BAN_DOCUMENTO
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @ESTADO_DOCUMENTO NOT IN ('AP', 'IM') OR ISNULL(@ESTA_CONTABILIZADO, 0) <> 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000,
				@SYS_MENSAJE_ERROR = N'Este documento no está listo para contabilizar o ya fue contabilizado. ' + @DETALLE_DOCUMENTO,
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.CON_PERIODO_CONTABLE
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO_CON
				AND MES_PERIODO = @MES_PERIODO_CON
				AND ESTADO_PERIODO_CON = 'AB'
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30001,
				@SYS_MENSAJE_ERROR = N'El período contable no está abierto. ' + @DETALLE_DOCUMENTO + N' no se puede contabilizar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND CORR_DOCUMENTO = @CORR_DOCUMENTO
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30004,
				@SYS_MENSAJE_ERROR = N'El documento no tiene detalle contable. ' + @DETALLE_DOCUMENTO + N' no se puede contabilizar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT @MONTO_CARGO = SUM(MONTO_CARGO), @MONTO_ABONO = SUM(MONTO_ABONO)
		FROM dbo.BAN_DOCUMENTO_DETA
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF ISNULL(@MONTO_CARGO, 0) <> ISNULL(@MONTO_ABONO, 0)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000,
				@SYS_MENSAJE_ERROR = N'El detalle contable no está cuadrado. ' + @DETALLE_DOCUMENTO + N' no se puede contabilizar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SET @TIPO_ACTUALIZA = 1;
		SET @CORR_PARTIDA = 0;
		SET @NUMERO_DOCUMENTO_STR = LTRIM(RTRIM(CONVERT(VARCHAR(25), @NUMERO_DOCUMENTO)));

		BEGIN TRANSACTION BAN_DOCUMENTO_CONTABILIZAR;

		EXEC dbo.PRAL_MTTO_CON_PARTIDA
			@TIPO_ACTUALIZA,
			@CORR_EMPRESA,
			@ANIO_PERIODO_CON,
			@MES_PERIODO_CON,
			@CORR_CLASE_PARTIDA,
			@CORR_PARTIDA OUTPUT,
			@FECHA_PARTIDA,
			@NUMERO_DOCUMENTO_STR,
			@NOMBRE_PARTIDA,
			'DI',
			'NOR',
			@CORR_MONEDA,
			@FACTOR_CAMBIO,
			@OPERADOR,
			@USUARIO_ACTU,
			@FECHA_ACTU,
			@ESTACION_ACTU,
			@USUARIO_ACTU,
			@FECHA_ACTU,
			@ESTACION_ACTU,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS OUTPUT,
			@SYS_NUMERO_ERROR OUTPUT,
			@SYS_MENSAJE_ERROR OUTPUT,
			NULL;

		IF @SYS_NUMERO_ERROR <> 0
		BEGIN
			IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_CONTABILIZAR;
			SET @SYS_MENSAJE_ERROR = @DETALLE_DOCUMENTO + N' [' + @SYS_MENSAJE_ERROR + N']';
			GOTO FINA;
		END;

		INSERT INTO @TEMP (CORR_DOCUMENTO_DETA, CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
		SELECT
			A.CORR_DOCUMENTO_DETA,
			A.CUENTA_CONTABLE,
			B.CORR_CENTRO_COSTO,
			A.NOMBRE_TRAN,
			ISNULL(A.MONTO_CARGO, 0),
			ISNULL(A.MONTO_ABONO, 0)
		FROM dbo.BAN_DOCUMENTO_DETA A
		LEFT JOIN dbo.CON_CENTRO_COSTO B
			ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_CENTRO_COSTO = B.CORR_CENTRO_COSTO
		WHERE A.CORR_EMPRESA = @CORR_EMPRESA
			AND A.ANIO_PERIODO = @ANIO_PERIODO
			AND A.MES_PERIODO = @MES_PERIODO
			AND A.CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND A.CORR_DOCUMENTO = @CORR_DOCUMENTO;

		WHILE EXISTS (SELECT 1 FROM @TEMP WHERE ESTA_PROC = 0)
		BEGIN
			SELECT TOP 1
				@CORR_DOCUMENTO_DETA = CORR_DOCUMENTO_DETA,
				@CUENTA_CONTABLE_DETA = CUENTA_CONTABLE,
				@CORR_CENTRO_COSTO_DETA = CORR_CENTRO_COSTO,
				@NOMBRE_TRAN_DETA = NOMBRE_TRAN,
				@MONTO_CARGO_DETA = MONTO_CARGO,
				@MONTO_ABONO_DETA = MONTO_ABONO
			FROM @TEMP
			WHERE ESTA_PROC = 0;

			SET @CORR_PARTIDA_DETA = @CORR_DOCUMENTO_DETA;

			EXEC dbo.PRAL_MTTO_CON_PARTIDA_DETA
				1,
				@CORR_EMPRESA,
				@ANIO_PERIODO_CON,
				@MES_PERIODO_CON,
				@CORR_CLASE_PARTIDA,
				@CORR_PARTIDA,
				@CORR_PARTIDA_DETA OUTPUT,
				@CUENTA_CONTABLE_DETA,
				@CORR_CENTRO_COSTO_DETA,
				@MONTO_CARGO_DETA,
				@MONTO_ABONO_DETA,
				@NOMBRE_TRAN_DETA,
				NULL,
				NULL,
				NULL,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@SYS_FILAS_AFECTADAS OUTPUT,
				@SYS_NUMERO_ERROR OUTPUT,
				@SYS_MENSAJE_ERROR OUTPUT,
				NULL;

			IF @SYS_NUMERO_ERROR <> 0
			BEGIN
				IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_CONTABILIZAR;
				SET @SYS_MENSAJE_ERROR = @DETALLE_DOCUMENTO + N' [' + @SYS_MENSAJE_ERROR + N']';
				GOTO FINA;
			END;

			IF NOT EXISTS (
				SELECT 1 FROM dbo.BAN_PARTIDA_DETA
				WHERE CORR_EMPRESA = @CORR_EMPRESA
					AND ANIO_PERIODO = @ANIO_PERIODO_CON
					AND MES_PERIODO = @MES_PERIODO_CON
					AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA
					AND CORR_PARTIDA = @CORR_PARTIDA
					AND CORR_PARTIDA_DETA = @CORR_PARTIDA_DETA
					AND ANIO_PERIODO_DOC = @ANIO_PERIODO
					AND MES_PERIODO_DOC = @MES_PERIODO
					AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
					AND CORR_DOCUMENTO = @CORR_DOCUMENTO
			)
			BEGIN
				INSERT INTO dbo.BAN_PARTIDA_DETA
				(
					CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_CLASE_PARTIDA, CORR_PARTIDA, CORR_PARTIDA_DETA,
					ANIO_PERIODO_DOC, MES_PERIODO_DOC, CORR_TIPO_MOVIMIENTO, CORR_DOCUMENTO
				)
				VALUES
				(
					@CORR_EMPRESA, @ANIO_PERIODO_CON, @MES_PERIODO_CON, @CORR_CLASE_PARTIDA, @CORR_PARTIDA, @CORR_PARTIDA_DETA,
					@ANIO_PERIODO, @MES_PERIODO, @CORR_TIPO_MOVIMIENTO, @CORR_DOCUMENTO
				);
			END;

			UPDATE @TEMP SET ESTA_PROC = 1 WHERE CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA;
		END;

		EXEC dbo.PRAL_MTTO_CON_PARTIDA_APLICAR
			@CORR_EMPRESA,
			@ANIO_PERIODO_CON,
			@MES_PERIODO_CON,
			@CORR_CLASE_PARTIDA,
			@CORR_PARTIDA OUTPUT,
			@USUARIO_ACTU,
			@FECHA_ACTU,
			@ESTACION_ACTU,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS OUTPUT,
			@SYS_NUMERO_ERROR OUTPUT,
			@SYS_MENSAJE_ERROR OUTPUT;

		IF @SYS_NUMERO_ERROR <> 0
		BEGIN
			IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_CONTABILIZAR;
			SET @SYS_MENSAJE_ERROR = @DETALLE_DOCUMENTO + N' [' + @SYS_MENSAJE_ERROR + N']';
			GOTO FINA;
		END;

		UPDATE dbo.BAN_DOCUMENTO SET
			ESTA_CONTABILIZADO = 1,
			USUARIO_ACTU = @USUARIO_ACTU,
			FECHA_ACTU = @FECHA_ACTU,
			ESTACION_ACTU = @ESTACION_ACTU
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;

		IF @@TRANCOUNT > 0 COMMIT TRANSACTION BAN_DOCUMENTO_CONTABILIZAR;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_CONTABILIZAR;
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Aplicar documento (+ contabilizar movimientos no CHQ) ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_DOCUMENTO_APLICAR', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_APLICAR];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_APLICAR]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE
		@ESTADO VARCHAR(2),
		@ESTA_CONTABILIZADO BIT,
		@CLASE_MOVIMIENTO VARCHAR(3),
		@CONTABILIZAR BIT,
		@MONTO_CARGO DECIMAL(18, 2),
		@MONTO_ABONO DECIMAL(18, 2),
		@NOMBRE_TIPO_MOVIMIENTO VARCHAR(100),
		@DETALLE_DOCUMENTO NVARCHAR(255),
		@CUENTA_CONTABLE_BANCO VARCHAR(30),
		@CORR_MOVIMIENTO INT,
		@CORR_CUENTA_BANCO INT,
		@FECHA_MOVIMIENTO DATE,
		@NOMBRE_BENEFICIARIO VARCHAR(255),
		@DESCRIPCION_MOVIMIENTO VARCHAR(1000),
		@REFERENCIA VARCHAR(255),
		@CORR_DOCUMENTO_DETA INT,
		@MONTO_CARGO_DETA DECIMAL(12, 2),
		@MONTO_ABONO_DETA DECIMAL(12, 2),
		@DESCRIPCION_MOVIMIENTO_DETA VARCHAR(1255);

	DECLARE @MOVIMIENTOS TABLE
	(
		CORR_DOCUMENTO_DETA INT NOT NULL,
		MONTO_CARGO_DETA DECIMAL(12, 2) NOT NULL,
		MONTO_ABONO_DETA DECIMAL(12, 2) NOT NULL,
		DESCRIPCION_MOVIMIENTO_DETA VARCHAR(1255) NOT NULL
	);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;
	SET @FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE());

	BEGIN TRY
		SELECT @NOMBRE_TIPO_MOVIMIENTO = NOMBRE_TIPO_MOVIMIENTO, @CLASE_MOVIMIENTO = CLASE_MOVIMIENTO
		FROM dbo.BAN_TIPO_MOVI_BANCARIO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO;

		SET @DETALLE_DOCUMENTO = @NOMBRE_TIPO_MOVIMIENTO + N' del Año ' + CONVERT(VARCHAR(10), @ANIO_PERIODO)
			+ N' Mes ' + CONVERT(VARCHAR(10), @MES_PERIODO)
			+ N' Correlativo No.' + CONVERT(VARCHAR(10), @CORR_DOCUMENTO);

		SELECT
			@ESTADO = ESTADO_DOCUMENTO,
			@ESTA_CONTABILIZADO = ESTA_CONTABILIZADO,
			@CORR_CUENTA_BANCO = CORR_CUENTA_BANCO,
			@FECHA_MOVIMIENTO = FECHA_EMISION,
			@NOMBRE_BENEFICIARIO = ISNULL(NOMBRE_BENEFICIARIO, N''),
			@DESCRIPCION_MOVIMIENTO = NOMBRE_PARTIDA,
			@REFERENCIA = LTRIM(RTRIM(CONVERT(VARCHAR(25), NUMERO_DOCUMENTO)))
		FROM dbo.BAN_DOCUMENTO
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @ESTADO IN ('AP', 'IM', 'AN') OR ISNULL(@ESTA_CONTABILIZADO, 0) <> 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000,
				@SYS_MENSAJE_ERROR = N'Este documento ya está aplicado o anulado. ' + @DETALLE_DOCUMENTO + N' no se puede aplicar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.CON_PERIODO_CONTABLE
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND ISNULL(ESTADO_PERIODO_BAN, 'AB') = 'AB'
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30001,
				@SYS_MENSAJE_ERROR = N'El período bancario no está abierto. ' + @DETALLE_DOCUMENTO + N' no se puede aplicar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND CORR_DOCUMENTO = @CORR_DOCUMENTO
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30004,
				@SYS_MENSAJE_ERROR = N'El documento no tiene detalle contable. ' + @DETALLE_DOCUMENTO + N' no se puede aplicar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT @MONTO_CARGO = SUM(MONTO_CARGO), @MONTO_ABONO = SUM(MONTO_ABONO)
		FROM dbo.BAN_DOCUMENTO_DETA
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF ISNULL(@MONTO_CARGO, 0) <> ISNULL(@MONTO_ABONO, 0)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000,
				@SYS_MENSAJE_ERROR = N'El detalle contable no está cuadrado (cargo ≠ abono). ' + @DETALLE_DOCUMENTO + N' no se puede aplicar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT @CUENTA_CONTABLE_BANCO = CUENTA_CONTABLE
		FROM dbo.BAN_CUENTA_BANCARIA
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND CORR_DOCUMENTO = @CORR_DOCUMENTO
				AND CUENTA_CONTABLE = @CUENTA_CONTABLE_BANCO
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30005,
				@SYS_MENSAJE_ERROR = N'El documento no contiene la cuenta contable del banco. ' + @DETALLE_DOCUMENTO + N' no se puede aplicar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		INSERT INTO @MOVIMIENTOS (CORR_DOCUMENTO_DETA, MONTO_CARGO_DETA, MONTO_ABONO_DETA, DESCRIPCION_MOVIMIENTO_DETA)
		SELECT B.CORR_DOCUMENTO_DETA, ISNULL(B.MONTO_CARGO, 0), ISNULL(B.MONTO_ABONO, 0), B.NOMBRE_TRAN
		FROM dbo.BAN_DOCUMENTO_DETA B
		WHERE B.CORR_EMPRESA = @CORR_EMPRESA
			AND B.ANIO_PERIODO = @ANIO_PERIODO
			AND B.MES_PERIODO = @MES_PERIODO
			AND B.CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND B.CORR_DOCUMENTO = @CORR_DOCUMENTO
			AND B.CUENTA_CONTABLE = @CUENTA_CONTABLE_BANCO;

		SET @CORR_MOVIMIENTO = 0;
		BEGIN TRANSACTION BAN_DOCUMENTO_APLICAR;

		WHILE EXISTS (SELECT 1 FROM @MOVIMIENTOS)
		BEGIN
			SELECT TOP 1
				@CORR_DOCUMENTO_DETA = CORR_DOCUMENTO_DETA,
				@MONTO_CARGO_DETA = MONTO_CARGO_DETA,
				@MONTO_ABONO_DETA = MONTO_ABONO_DETA,
				@DESCRIPCION_MOVIMIENTO_DETA = DESCRIPCION_MOVIMIENTO_DETA
			FROM @MOVIMIENTOS;

			EXEC dbo.PRAL_MTTO_BAN_MOVIMIENTO
				1, @CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, @CORR_CUENTA_BANCO, @CORR_MOVIMIENTO OUTPUT,
				@FECHA_MOVIMIENTO, @CORR_TIPO_MOVIMIENTO, @REFERENCIA, @NOMBRE_BENEFICIARIO, @DESCRIPCION_MOVIMIENTO_DETA,
				@MONTO_CARGO_DETA, @MONTO_ABONO_DETA, @USUARIO_ACTU, @FECHA_ACTU, @ESTACION_ACTU,
				@USUARIO_ACTU, @FECHA_ACTU, @ESTACION_ACTU, @CORR_DOCUMENTO, @SYS_LOGIN_USUARIO, @SYS_ESTACION,
				@SYS_FILAS_AFECTADAS OUTPUT, @SYS_NUMERO_ERROR OUTPUT, @SYS_MENSAJE_ERROR OUTPUT,
				@CORR_DOCUMENTO_DETA, @ANIO_PERIODO, @MES_PERIODO;

			IF @SYS_NUMERO_ERROR <> 0
			BEGIN
				IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_APLICAR;
				SET @SYS_MENSAJE_ERROR = N'No se pudo generar el movimiento bancario. ' + @SYS_MENSAJE_ERROR;
				GOTO FINA;
			END;

			DELETE FROM @MOVIMIENTOS WHERE CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA;
		END;

		UPDATE dbo.BAN_DOCUMENTO SET
			ESTADO_DOCUMENTO = 'AP',
			CORR_MOVIMIENTO = @CORR_MOVIMIENTO,
			USUARIO_ACTU = @USUARIO_ACTU,
			FECHA_ACTU = @FECHA_ACTU,
			ESTACION_ACTU = @ESTACION_ACTU
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @CLASE_MOVIMIENTO <> 'CHQ'
		BEGIN
			SELECT @CONTABILIZAR = ISNULL(CONTABILIZAR_LUEGO_DE_APLICAR, 0)
			FROM dbo.BAN_PARAMETRO
			WHERE CORR_EMPRESA = @CORR_EMPRESA;

			IF ISNULL(@CONTABILIZAR, 0) = 1
			BEGIN
				EXEC dbo.PRAL_MTTO_BAN_DOCUMENTO_CONTABILIZAR
					@CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, @CORR_TIPO_MOVIMIENTO, @CORR_DOCUMENTO,
					@USUARIO_ACTU, @FECHA_ACTU, @ESTACION_ACTU, @SYS_LOGIN_USUARIO, @SYS_ESTACION,
					@SYS_FILAS_AFECTADAS OUTPUT, @SYS_NUMERO_ERROR OUTPUT, @SYS_MENSAJE_ERROR OUTPUT;

				IF @SYS_NUMERO_ERROR <> 0
				BEGIN
					IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_APLICAR;
					GOTO FINA;
				END;
			END;
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
		IF @@TRANCOUNT > 0 COMMIT TRANSACTION BAN_DOCUMENTO_APLICAR;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_APLICAR;
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Anular documento (+ contra-partida si contabilizado) ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_DOCUMENTO_ANULAR', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_ANULAR];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_ANULAR]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE
		@ESTADO VARCHAR(2),
		@ESTA_CONTABILIZADO BIT,
		@FECHA_ANULACION DATE,
		@NOMBRE_TIPO_MOVIMIENTO VARCHAR(100),
		@DETALLE_DOCUMENTO NVARCHAR(255),
		@CORR_CLASE_PARTIDA INT,
		@ANIO_PERIODO_CON INT,
		@MES_PERIODO_CON INT,
		@FECHA_PARTIDA DATE,
		@TIPO_ACTUALIZA INT,
		@CORR_PARTIDA INT,
		@CORR_PARTIDA_DETA INT,
		@NUMERO_DOCUMENTO BIGINT,
		@NOMBRE_PARTIDA VARCHAR(1000),
		@CORR_MONEDA INT,
		@FACTOR_CAMBIO DECIMAL(16, 6),
		@OPERADOR VARCHAR(2),
		@CORR_DOCUMENTO_DETA INT,
		@CUENTA_CONTABLE_DETA VARCHAR(30),
		@CORR_CENTRO_COSTO_DETA INT,
		@NOMBRE_TRAN_DETA VARCHAR(1255),
		@MONTO_CARGO_DETA DECIMAL(18, 2),
		@MONTO_ABONO_DETA DECIMAL(18, 2),
		@NUMERO_DOCUMENTO_STR VARCHAR(25);

	DECLARE @TEMP TABLE
	(
		CORR_DOCUMENTO_DETA INT NOT NULL,
		CUENTA_CONTABLE VARCHAR(30) NOT NULL,
		CORR_CENTRO_COSTO INT NULL,
		NOMBRE_TRAN VARCHAR(1255) NOT NULL,
		MONTO_CARGO DECIMAL(18, 2) NOT NULL,
		MONTO_ABONO DECIMAL(18, 2) NOT NULL,
		ESTA_PROC BIT NOT NULL DEFAULT (0)
	);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;
	SET @FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE());
	SET @FECHA_ANULACION = CAST(@FECHA_ACTU AS DATE);

	BEGIN TRY
		SELECT @NOMBRE_TIPO_MOVIMIENTO = NOMBRE_TIPO_MOVIMIENTO, @CORR_CLASE_PARTIDA = CORR_CLASE_PARTIDA
		FROM dbo.BAN_TIPO_MOVI_BANCARIO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO;

		SET @DETALLE_DOCUMENTO = @NOMBRE_TIPO_MOVIMIENTO + N' del Año ' + CONVERT(VARCHAR(10), @ANIO_PERIODO)
			+ N' Mes ' + CONVERT(VARCHAR(10), @MES_PERIODO)
			+ N' Correlativo No.' + CONVERT(VARCHAR(10), @CORR_DOCUMENTO);

		SELECT
			@ESTADO = ESTADO_DOCUMENTO,
			@ESTA_CONTABILIZADO = ESTA_CONTABILIZADO,
			@ANIO_PERIODO_CON = YEAR(@FECHA_ANULACION),
			@MES_PERIODO_CON = MONTH(@FECHA_ANULACION),
			@FECHA_PARTIDA = @FECHA_ANULACION
		FROM dbo.BAN_DOCUMENTO
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @ESTADO = 'AN'
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El documento ya está anulado', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF ISNULL(@ESTA_CONTABILIZADO, 0) = 1
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM dbo.CON_PERIODO_CONTABLE
				WHERE CORR_EMPRESA = @CORR_EMPRESA
					AND ANIO_PERIODO = @ANIO_PERIODO_CON
					AND MES_PERIODO = @MES_PERIODO_CON
					AND ESTADO_PERIODO_CON = 'AB'
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30002,
					@SYS_MENSAJE_ERROR = N'El período contable no está abierto. ' + @DETALLE_DOCUMENTO + N' no se puede anular.',
					@SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		BEGIN TRANSACTION BAN_DOCUMENTO_ANULAR;

		IF @ESTADO IN ('AP', 'IM')
		BEGIN
			DELETE FROM dbo.BAN_MOVIMIENTO
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ISNULL(ANIO_PERIODO_DOC, ANIO_PERIODO) = @ANIO_PERIODO
				AND ISNULL(MES_PERIODO_DOC, MES_PERIODO) = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND CORR_DOCUMENTO = @CORR_DOCUMENTO;
		END;

		IF ISNULL(@ESTA_CONTABILIZADO, 0) = 1
		BEGIN
			SELECT @TIPO_ACTUALIZA = 1, @CORR_PARTIDA = 0;

			SELECT
				@NUMERO_DOCUMENTO = NUMERO_DOCUMENTO,
				@NOMBRE_PARTIDA = N'ANULADO ' + NOMBRE_PARTIDA,
				@CORR_MONEDA = CORR_MONEDA,
				@FACTOR_CAMBIO = FACTOR_CAMBIO,
				@OPERADOR = OPERADOR
			FROM dbo.BAN_DOCUMENTO
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

			SET @NUMERO_DOCUMENTO_STR = LTRIM(RTRIM(CONVERT(VARCHAR(25), @NUMERO_DOCUMENTO)));

			EXEC dbo.PRAL_MTTO_CON_PARTIDA
				@TIPO_ACTUALIZA, @CORR_EMPRESA, @ANIO_PERIODO_CON, @MES_PERIODO_CON, @CORR_CLASE_PARTIDA, @CORR_PARTIDA OUTPUT,
				@FECHA_PARTIDA, @NUMERO_DOCUMENTO_STR, @NOMBRE_PARTIDA, 'DI', 'NOR',
				@CORR_MONEDA, @FACTOR_CAMBIO, @OPERADOR, @USUARIO_ACTU, @FECHA_ACTU, @ESTACION_ACTU,
				@USUARIO_ACTU, @FECHA_ACTU, @ESTACION_ACTU, @SYS_LOGIN_USUARIO, @SYS_ESTACION,
				@SYS_FILAS_AFECTADAS OUTPUT, @SYS_NUMERO_ERROR OUTPUT, @SYS_MENSAJE_ERROR OUTPUT, NULL;

			IF @SYS_NUMERO_ERROR <> 0
			BEGIN
				IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_ANULAR;
				SET @SYS_MENSAJE_ERROR = @DETALLE_DOCUMENTO + N' [' + @SYS_MENSAJE_ERROR + N']';
				GOTO FINA;
			END;

			INSERT INTO @TEMP (CORR_DOCUMENTO_DETA, CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
			SELECT
				A.CORR_DOCUMENTO_DETA,
				A.CUENTA_CONTABLE,
				B.CORR_CENTRO_COSTO,
				N'ANULADO ' + A.NOMBRE_TRAN,
				ISNULL(A.MONTO_ABONO, 0),
				ISNULL(A.MONTO_CARGO, 0)
			FROM dbo.BAN_DOCUMENTO_DETA A
			LEFT JOIN dbo.CON_CENTRO_COSTO B
				ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_CENTRO_COSTO = B.CORR_CENTRO_COSTO
			WHERE A.CORR_EMPRESA = @CORR_EMPRESA
				AND A.ANIO_PERIODO = @ANIO_PERIODO
				AND A.MES_PERIODO = @MES_PERIODO
				AND A.CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND A.CORR_DOCUMENTO = @CORR_DOCUMENTO;

			WHILE EXISTS (SELECT 1 FROM @TEMP WHERE ESTA_PROC = 0)
			BEGIN
				SELECT TOP 1
					@CORR_DOCUMENTO_DETA = CORR_DOCUMENTO_DETA,
					@CUENTA_CONTABLE_DETA = CUENTA_CONTABLE,
					@CORR_CENTRO_COSTO_DETA = CORR_CENTRO_COSTO,
					@NOMBRE_TRAN_DETA = NOMBRE_TRAN,
					@MONTO_CARGO_DETA = MONTO_CARGO,
					@MONTO_ABONO_DETA = MONTO_ABONO
				FROM @TEMP
				WHERE ESTA_PROC = 0;

				SET @CORR_PARTIDA_DETA = 0;

				EXEC dbo.PRAL_MTTO_CON_PARTIDA_DETA
					1, @CORR_EMPRESA, @ANIO_PERIODO_CON, @MES_PERIODO_CON, @CORR_CLASE_PARTIDA, @CORR_PARTIDA,
					@CORR_PARTIDA_DETA OUTPUT, @CUENTA_CONTABLE_DETA, @CORR_CENTRO_COSTO_DETA,
					@MONTO_CARGO_DETA, @MONTO_ABONO_DETA, @NOMBRE_TRAN_DETA,
					NULL, NULL, NULL, @SYS_LOGIN_USUARIO, @SYS_ESTACION,
					@SYS_FILAS_AFECTADAS OUTPUT, @SYS_NUMERO_ERROR OUTPUT, @SYS_MENSAJE_ERROR OUTPUT, NULL;

				IF @SYS_NUMERO_ERROR <> 0
				BEGIN
					IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_ANULAR;
					SET @SYS_MENSAJE_ERROR = @DETALLE_DOCUMENTO + N' [' + @SYS_MENSAJE_ERROR + N']';
					GOTO FINA;
				END;

				INSERT INTO dbo.BAN_PARTIDA_DETA
				(
					CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_CLASE_PARTIDA, CORR_PARTIDA, CORR_PARTIDA_DETA,
					ANIO_PERIODO_DOC, MES_PERIODO_DOC, CORR_TIPO_MOVIMIENTO, CORR_DOCUMENTO
				)
				VALUES
				(
					@CORR_EMPRESA, @ANIO_PERIODO_CON, @MES_PERIODO_CON, @CORR_CLASE_PARTIDA, @CORR_PARTIDA, @CORR_PARTIDA_DETA,
					@ANIO_PERIODO, @MES_PERIODO, @CORR_TIPO_MOVIMIENTO, @CORR_DOCUMENTO
				);

				UPDATE @TEMP SET ESTA_PROC = 1 WHERE CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA;
			END;

			EXEC dbo.PRAL_MTTO_CON_PARTIDA_APLICAR
				@CORR_EMPRESA, @ANIO_PERIODO_CON, @MES_PERIODO_CON, @CORR_CLASE_PARTIDA, @CORR_PARTIDA OUTPUT,
				@USUARIO_ACTU, @FECHA_ACTU, @ESTACION_ACTU, @SYS_LOGIN_USUARIO, @SYS_ESTACION,
				@SYS_FILAS_AFECTADAS OUTPUT, @SYS_NUMERO_ERROR OUTPUT, @SYS_MENSAJE_ERROR OUTPUT;

			IF @SYS_NUMERO_ERROR <> 0
			BEGIN
				IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_ANULAR;
				SET @SYS_MENSAJE_ERROR = @DETALLE_DOCUMENTO + N' [' + @SYS_MENSAJE_ERROR + N']';
				GOTO FINA;
			END;
		END;

		UPDATE dbo.BAN_DOCUMENTO SET
			ESTADO_DOCUMENTO = 'AN',
			FECHA_ANULACION = @FECHA_ANULACION,
			CORR_MOVIMIENTO = NULL,
			CORR_MOVIMIENTO_DESTINO = NULL,
			USUARIO_ACTU = @USUARIO_ACTU,
			FECHA_ACTU = @FECHA_ACTU,
			ESTACION_ACTU = @ESTACION_ACTU
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;

		IF @@TRANCOUNT > 0 COMMIT TRANSACTION BAN_DOCUMENTO_ANULAR;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_ANULAR;
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Imprimir cheque (+ contabilizar si aplica) ── */
IF OBJECT_ID(N'dbo.PRAL_IMPR_BAN_CHEQUE_IMPRIME', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_IMPR_BAN_CHEQUE_IMPRIME];
GO

CREATE PROCEDURE [dbo].[PRAL_IMPR_BAN_CHEQUE_IMPRIME]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@USUARIO_ACTU VARCHAR(30) = '',
	@FECHA_ACTU DATETIME = NULL,
	@ESTACION_ACTU VARCHAR(50) = '',
	@SYS_LOGIN_USUARIO VARCHAR(30) = '',
	@SYS_ESTACION VARCHAR(50) = '',
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE
		@ESTADO VARCHAR(2),
		@CLASE_MOV VARCHAR(3),
		@CORR_CUENTA INT,
		@CORR_CHEQUERA INT,
		@NUMERO_CHEQUE INT,
		@SERIE VARCHAR(10),
		@CORR_TIPO_CHEQUE INT,
		@CONTABILIZAR BIT;

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;
	SET @FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE());

	BEGIN TRY
		SELECT @ESTADO = A.ESTADO_DOCUMENTO, @CORR_CUENTA = A.CORR_CUENTA_BANCO,
			@CORR_TIPO_CHEQUE = A.CORR_TIPO_CHEQUE, @CLASE_MOV = B.CLASE_MOVIMIENTO
		FROM dbo.BAN_DOCUMENTO A
		INNER JOIN dbo.BAN_TIPO_MOVI_BANCARIO B
			ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO
		WHERE A.CORR_EMPRESA = @CORR_EMPRESA AND A.ANIO_PERIODO = @ANIO_PERIODO AND A.MES_PERIODO = @MES_PERIODO
			AND A.CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND A.CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @CLASE_MOV <> 'CHQ'
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Solo se pueden imprimir documentos tipo Cheque', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF @ESTADO NOT IN ('AP', 'IM')
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El cheque debe estar aplicado para imprimir', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT TOP 1 @CORR_CHEQUERA = CORR_CHEQUERA, @NUMERO_CHEQUE = NUMERO_CHEQUE_ACTUAL, @SERIE = SERIE_CHEQUE
		FROM dbo.BAN_CHEQUERA
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA AND ESTADO_CHEQUERA = 'AC'
		ORDER BY CORR_CHEQUERA;

		IF ISNULL(@CORR_CHEQUERA, 0) = 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No hay chequera activa para la cuenta bancaria', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		BEGIN TRANSACTION BAN_CHEQUE_IMPRIME;

		IF @ESTADO = 'AP'
		BEGIN
			IF EXISTS (
				SELECT 1 FROM dbo.BAN_DOCUMENTO
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA
					AND CORR_CHEQUERA = @CORR_CHEQUERA AND SERIE_CHEQUE = @SERIE AND NUMERO_DOCUMENTO = @NUMERO_CHEQUE
					AND NOT (ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
						AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO)
			)
			BEGIN
				IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_CHEQUE_IMPRIME;
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El número de cheque ya fue utilizado', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			UPDATE dbo.BAN_DOCUMENTO SET
				CORR_CHEQUERA = @CORR_CHEQUERA,
				NUMERO_DOCUMENTO = @NUMERO_CHEQUE,
				SERIE_CHEQUE = @SERIE,
				ESTADO_DOCUMENTO = 'IM',
				FECHA_IMPRESO = CAST(@FECHA_ACTU AS DATE),
				USUARIO_ACTU = @USUARIO_ACTU,
				FECHA_ACTU = @FECHA_ACTU,
				ESTACION_ACTU = @ESTACION_ACTU
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

			UPDATE M SET
				M.REFERENCIA = LTRIM(RTRIM(CONVERT(VARCHAR(25), D.SERIE_CHEQUE) + N' ' + CONVERT(VARCHAR(25), D.NUMERO_DOCUMENTO)))
			FROM dbo.BAN_MOVIMIENTO M
			INNER JOIN dbo.BAN_DOCUMENTO D
				ON M.CORR_EMPRESA = D.CORR_EMPRESA
				AND ISNULL(M.ANIO_PERIODO_DOC, M.ANIO_PERIODO) = D.ANIO_PERIODO
				AND ISNULL(M.MES_PERIODO_DOC, M.MES_PERIODO) = D.MES_PERIODO
				AND M.CORR_TIPO_MOVIMIENTO = D.CORR_TIPO_MOVIMIENTO
				AND M.CORR_DOCUMENTO = D.CORR_DOCUMENTO
			WHERE D.CORR_EMPRESA = @CORR_EMPRESA
				AND D.ANIO_PERIODO = @ANIO_PERIODO
				AND D.MES_PERIODO = @MES_PERIODO
				AND D.CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND D.CORR_DOCUMENTO = @CORR_DOCUMENTO;

			UPDATE dbo.BAN_CHEQUERA SET
				NUMERO_CHEQUE_ACTUAL = NUMERO_CHEQUE_ACTUAL + 1,
				ESTADO_CHEQUERA = CASE WHEN (NUMERO_CHEQUE_ACTUAL + 1) > NUMERO_CHEQUE_FINAL THEN 'IN' ELSE ESTADO_CHEQUERA END
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA AND CORR_CHEQUERA = @CORR_CHEQUERA
				AND NUMERO_CHEQUE_ACTUAL < NUMERO_CHEQUE_FINAL;
		END;

		SELECT @CONTABILIZAR = CONTABILIZAR_LUEGO_DE_IMPRIMIR
		FROM dbo.BAN_TIPO_CHEQUE
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_CHEQUE = @CORR_TIPO_CHEQUE;

		IF @CONTABILIZAR IS NULL
			SELECT @CONTABILIZAR = CONTABILIZAR_LUEGO_DE_IMPRIMIR
			FROM dbo.BAN_PARAMETRO
			WHERE CORR_EMPRESA = @CORR_EMPRESA;

		IF ISNULL(@CONTABILIZAR, 0) = 1
		BEGIN
			EXEC dbo.PRAL_MTTO_BAN_DOCUMENTO_CONTABILIZAR
				@CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, @CORR_TIPO_MOVIMIENTO, @CORR_DOCUMENTO,
				@USUARIO_ACTU, @FECHA_ACTU, @ESTACION_ACTU, @SYS_LOGIN_USUARIO, @SYS_ESTACION,
				@SYS_FILAS_AFECTADAS OUTPUT, @SYS_NUMERO_ERROR OUTPUT, @SYS_MENSAJE_ERROR OUTPUT;

			IF @SYS_NUMERO_ERROR <> 0
			BEGIN
				IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_CHEQUE_IMPRIME;
				GOTO FINA;
			END;
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
		IF @@TRANCOUNT > 0 COMMIT TRANSACTION BAN_CHEQUE_IMPRIME;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_CHEQUE_IMPRIME;
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Des-contabilizar documento bancario ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_DOCUMENTO_DESCONTABILIZAR', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_DESCONTABILIZAR];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_DESCONTABILIZAR]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE
		@ESTADO_DOCUMENTO VARCHAR(2),
		@ESTA_CONTABILIZADO BIT,
		@DETALLE_DOCUMENTO NVARCHAR(255),
		@NOMBRE_TIPO_MOVIMIENTO VARCHAR(100),
		@ANIO_PERIODO_CON INT,
		@MES_PERIODO_CON INT,
		@CORR_CLASE_PARTIDA INT,
		@CORR_PARTIDA INT,
		@ESTADO_PARTIDA VARCHAR(2);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;
	SET @FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE());

	BEGIN TRY
		SELECT @NOMBRE_TIPO_MOVIMIENTO = NOMBRE_TIPO_MOVIMIENTO
		FROM dbo.BAN_TIPO_MOVI_BANCARIO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO;

		SET @DETALLE_DOCUMENTO = @NOMBRE_TIPO_MOVIMIENTO + N' del Año ' + CONVERT(VARCHAR(10), @ANIO_PERIODO)
			+ N' Mes ' + CONVERT(VARCHAR(10), @MES_PERIODO)
			+ N' Correlativo No.' + CONVERT(VARCHAR(10), @CORR_DOCUMENTO);

		SELECT
			@ESTADO_DOCUMENTO = ESTADO_DOCUMENTO,
			@ESTA_CONTABILIZADO = ESTA_CONTABILIZADO,
			@ANIO_PERIODO_CON = ANIO_PERIODO,
			@MES_PERIODO_CON = MES_PERIODO
		FROM dbo.BAN_DOCUMENTO
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @ESTADO_DOCUMENTO NOT IN ('AP', 'IM') OR ISNULL(@ESTA_CONTABILIZADO, 0) = 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000,
				@SYS_MENSAJE_ERROR = N'Este documento no está contabilizado o no se puede des-contabilizar. ' + @DETALLE_DOCUMENTO,
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.CON_PERIODO_CONTABLE
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO_CON
				AND MES_PERIODO = @MES_PERIODO_CON
				AND ESTADO_PERIODO_CON = 'AB'
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30001,
				@SYS_MENSAJE_ERROR = N'El período contable no está abierto. ' + @DETALLE_DOCUMENTO + N' no se puede des-contabilizar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		BEGIN TRANSACTION BAN_DOCUMENTO_DESCONTABILIZAR;

		DECLARE curPartidas CURSOR LOCAL FAST_FORWARD FOR
			SELECT DISTINCT ANIO_PERIODO, MES_PERIODO, CORR_CLASE_PARTIDA, CORR_PARTIDA
			FROM dbo.BAN_PARTIDA_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO_DOC = @ANIO_PERIODO
				AND MES_PERIODO_DOC = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		OPEN curPartidas;
		FETCH NEXT FROM curPartidas INTO @ANIO_PERIODO_CON, @MES_PERIODO_CON, @CORR_CLASE_PARTIDA, @CORR_PARTIDA;

		WHILE @@FETCH_STATUS = 0
		BEGIN
			SELECT @ESTADO_PARTIDA = ESTADO_PARTIDA
			FROM dbo.CON_PARTIDA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO_CON
				AND MES_PERIODO = @MES_PERIODO_CON
				AND CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA
				AND CORR_PARTIDA = @CORR_PARTIDA;

			IF @ESTADO_PARTIDA = 'AP'
			BEGIN
				EXEC dbo.PRAL_MTTO_CON_PARTIDA_DESAPLICAR
					@CORR_EMPRESA,
					@ANIO_PERIODO_CON,
					@MES_PERIODO_CON,
					@CORR_CLASE_PARTIDA,
					@CORR_PARTIDA OUTPUT,
					@USUARIO_ACTU,
					@FECHA_ACTU,
					@ESTACION_ACTU,
					@SYS_LOGIN_USUARIO,
					@SYS_ESTACION,
					@SYS_FILAS_AFECTADAS OUTPUT,
					@SYS_NUMERO_ERROR OUTPUT,
					@SYS_MENSAJE_ERROR OUTPUT;

				IF @SYS_NUMERO_ERROR <> 0
				BEGIN
					IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_DESCONTABILIZAR;
					CLOSE curPartidas;
					DEALLOCATE curPartidas;
					SET @SYS_MENSAJE_ERROR = @DETALLE_DOCUMENTO + N' [' + @SYS_MENSAJE_ERROR + N']';
					GOTO FINA;
				END;
			END;

			IF @ESTADO_PARTIDA IN ('DI', 'AP')
			BEGIN
				EXEC dbo.PRAL_MTTO_CON_PARTIDA_ANULAR
					@CORR_EMPRESA,
					@ANIO_PERIODO_CON,
					@MES_PERIODO_CON,
					@CORR_CLASE_PARTIDA,
					@CORR_PARTIDA OUTPUT,
					@USUARIO_ACTU,
					@FECHA_ACTU,
					@ESTACION_ACTU,
					@SYS_LOGIN_USUARIO,
					@SYS_ESTACION,
					@SYS_FILAS_AFECTADAS OUTPUT,
					@SYS_NUMERO_ERROR OUTPUT,
					@SYS_MENSAJE_ERROR OUTPUT;

				IF @SYS_NUMERO_ERROR <> 0
				BEGIN
					IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_DESCONTABILIZAR;
					CLOSE curPartidas;
					DEALLOCATE curPartidas;
					SET @SYS_MENSAJE_ERROR = @DETALLE_DOCUMENTO + N' [' + @SYS_MENSAJE_ERROR + N']';
					GOTO FINA;
				END;
			END;

			FETCH NEXT FROM curPartidas INTO @ANIO_PERIODO_CON, @MES_PERIODO_CON, @CORR_CLASE_PARTIDA, @CORR_PARTIDA;
		END;

		CLOSE curPartidas;
		DEALLOCATE curPartidas;

		DELETE FROM dbo.BAN_PARTIDA_DETA
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO_DOC = @ANIO_PERIODO
			AND MES_PERIODO_DOC = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		UPDATE dbo.BAN_DOCUMENTO SET
			ESTA_CONTABILIZADO = 0,
			USUARIO_ACTU = @USUARIO_ACTU,
			FECHA_ACTU = @FECHA_ACTU,
			ESTACION_ACTU = @ESTACION_ACTU
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;

		IF @@TRANCOUNT > 0 COMMIT TRANSACTION BAN_DOCUMENTO_DESCONTABILIZAR;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_DESCONTABILIZAR;
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

PRINT N'DEPLOY_BAN_CONTABILIZAR completado.';
GO
