/* Deploy idempotente — BAN_MOVIMIENTO + Aplicar/Anular real + impresión cheque (SGUEES) */
SET NOCOUNT ON;

/* ── Columnas movimiento en encabezado ── */
IF COL_LENGTH(N'dbo.BAN_DOCUMENTO', N'CORR_MOVIMIENTO') IS NULL
BEGIN
	ALTER TABLE dbo.BAN_DOCUMENTO ADD CORR_MOVIMIENTO INT NULL;
	PRINT N'Columna BAN_DOCUMENTO.CORR_MOVIMIENTO agregada.';
END
GO

IF COL_LENGTH(N'dbo.BAN_DOCUMENTO', N'CORR_MOVIMIENTO_DESTINO') IS NULL
BEGIN
	ALTER TABLE dbo.BAN_DOCUMENTO ADD CORR_MOVIMIENTO_DESTINO INT NULL;
	PRINT N'Columna BAN_DOCUMENTO.CORR_MOVIMIENTO_DESTINO agregada.';
END
GO

IF COL_LENGTH(N'dbo.BAN_DOCUMENTO', N'CORR_CUENTA_BANCO_DESTINO') IS NULL
BEGIN
	ALTER TABLE dbo.BAN_DOCUMENTO ADD CORR_CUENTA_BANCO_DESTINO INT NULL;
	PRINT N'Columna BAN_DOCUMENTO.CORR_CUENTA_BANCO_DESTINO agregada.';
END
GO

IF COL_LENGTH(N'dbo.BAN_DOCUMENTO', N'NUMERO_CUENTA_DESTINO_TERCERO') IS NULL
BEGIN
	ALTER TABLE dbo.BAN_DOCUMENTO ADD NUMERO_CUENTA_DESTINO_TERCERO VARCHAR(50) NULL;
	PRINT N'Columna BAN_DOCUMENTO.NUMERO_CUENTA_DESTINO_TERCERO agregada.';
END
GO

IF COL_LENGTH(N'dbo.BAN_DOCUMENTO', N'MONTO_DESTINO') IS NULL
BEGIN
	ALTER TABLE dbo.BAN_DOCUMENTO ADD MONTO_DESTINO DECIMAL(18, 2) NULL CONSTRAINT DF_BAN_DOCUMENTO_MONTO_DESTINO DEFAULT ((0));
	PRINT N'Columna BAN_DOCUMENTO.MONTO_DESTINO agregada.';
END
GO

/* ── Tabla movimientos bancarios ── */
IF OBJECT_ID(N'dbo.BAN_MOVIMIENTO', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BAN_MOVIMIENTO]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[ANIO_PERIODO] [int] NOT NULL,
		[MES_PERIODO] [int] NOT NULL,
		[CORR_CUENTA_BANCO] [int] NOT NULL,
		[CORR_MOVIMIENTO] [int] NOT NULL,
		[FECHA_MOVIMIENTO] [date] NOT NULL,
		[CORR_TIPO_MOVIMIENTO] [int] NOT NULL,
		[REFERENCIA] [varchar](255) COLLATE Latin1_General_CS_AS NOT NULL,
		[NOMBRE_BENEFICIARIO] [varchar](255) COLLATE Latin1_General_CS_AS NOT NULL,
		[DESCRIPCION_MOVIMIENTO] [varchar](1000) COLLATE Latin1_General_CS_AS NOT NULL,
		[MONTO_CARGO] [decimal](12, 2) NOT NULL CONSTRAINT [DF_BAN_MOV_CARGO] DEFAULT ((0)),
		[MONTO_ABONO] [decimal](12, 2) NOT NULL CONSTRAINT [DF_BAN_MOV_ABONO] DEFAULT ((0)),
		[USUARIO_CREA] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
		[FECHA_CREA] [datetime] NOT NULL,
		[ESTACION_CREA] [varchar](50) COLLATE Latin1_General_CS_AS NOT NULL,
		[USUARIO_ACTU] [varchar](30) COLLATE Latin1_General_CS_AS NULL,
		[FECHA_ACTU] [datetime] NULL,
		[ESTACION_ACTU] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
		[CORR_DOCUMENTO] [int] NULL,
		[CORR_DOCUMENTO_DETA] [int] NULL,
		[ANIO_PERIODO_DOC] [int] NULL,
		[MES_PERIODO_DOC] [int] NULL
	) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_MOVIMIENTO]
		ADD CONSTRAINT [PK_BAN_MOVIMIENTO]
		PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_CUENTA_BANCO], [CORR_MOVIMIENTO]) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_MOVIMIENTO]
		ADD CONSTRAINT [FK_BAN_MOVIMIENTO_BAN_CUENTA_BANCARIA]
		FOREIGN KEY ([CORR_EMPRESA], [CORR_CUENTA_BANCO])
		REFERENCES [dbo].[BAN_CUENTA_BANCARIA] ([CORR_EMPRESA], [CORR_CUENTA_BANCO]);

	ALTER TABLE [dbo].[BAN_MOVIMIENTO]
		ADD CONSTRAINT [FK_BAN_MOVIMIENTO_BAN_TIPO_MOVI]
		FOREIGN KEY ([CORR_EMPRESA], [CORR_TIPO_MOVIMIENTO])
		REFERENCES [dbo].[BAN_TIPO_MOVI_BANCARIO] ([CORR_EMPRESA], [CORR_TIPO_MOVIMIENTO]);

	PRINT N'Tabla BAN_MOVIMIENTO creada.';
END
ELSE
	PRINT N'Tabla BAN_MOVIMIENTO ya existe.';
GO

/* ── Vista encabezado (CORR_MOVIMIENTO) ── */
IF OBJECT_ID(N'dbo.V_BAN_DOCUMENTO', N'V') IS NOT NULL
	DROP VIEW [dbo].[V_BAN_DOCUMENTO];
GO

CREATE VIEW [dbo].[V_BAN_DOCUMENTO]
AS
SELECT
	A.CORR_EMPRESA,
	A.ANIO_PERIODO,
	A.MES_PERIODO,
	A.CORR_TIPO_MOVIMIENTO,
	B.NOMBRE_TIPO_MOVIMIENTO,
	B.CLASE_MOVIMIENTO,
	A.CORR_DOCUMENTO,
	A.CORR_CUENTA_BANCO,
	C.NOMBRE_CUENTA_BANCO,
	C.NUMERO_CUENTA_BANCO,
	A.NUMERO_DOCUMENTO,
	A.FECHA_EMISION,
	A.NOMBRE_PARTIDA,
	ISNULL(A.CORR_PROVEEDOR, 0) CORR_PROVEEDOR,
	ISNULL(A.NOMBRE_BENEFICIARIO, '') NOMBRE_BENEFICIARIO,
	ISNULL(A.CORR_EMPLEADO, 0) CORR_EMPLEADO,
	ISNULL(A.CORR_CLIENTE, 0) CORR_CLIENTE,
	A.MONTO_DOCUMENTO,
	A.ESTADO_DOCUMENTO,
	CASE A.ESTADO_DOCUMENTO
		WHEN 'DI' THEN N'Digitado'
		WHEN 'AP' THEN N'Aplicado'
		WHEN 'IM' THEN N'Impreso'
		WHEN 'VA' THEN N'Validación'
		WHEN 'AN' THEN N'Anulado'
		WHEN 'SO' THEN N'Solicitando Autorización'
		ELSE N''
	END AS NOMBRE_ESTADO_DOCUMENTO,
	A.ESTA_CONTABILIZADO,
	A.CANTIDAD_LETRAS,
	A.USUARIO_CREA,
	A.FECHA_CREA,
	A.ESTACION_CREA,
	A.USUARIO_ACTU,
	A.FECHA_ACTU,
	A.ESTACION_ACTU,
	ISNULL(A.CORR_MOVIMIENTO, 0) CORR_MOVIMIENTO,
	ISNULL(A.CORR_MOVIMIENTO_DESTINO, 0) CORR_MOVIMIENTO_DESTINO,
	ISNULL(A.CORR_TIPO_CHEQUE, 0) CORR_TIPO_CHEQUE,
	ISNULL(E.CLASE_TIPO_CHEQUE, '') CLASE_TIPO_CHEQUE,
	ISNULL(E.NOMBRE_TIPO_CHEQUE, '') NOMBRE_TIPO_CHEQUE,
	ISNULL(A.CORR_CHEQUERA, 0) CORR_CHEQUERA,
	ISNULL(A.SERIE_CHEQUE, '') SERIE_CHEQUE,
	ISNULL(A.CORR_CUENTA_BANCO_DESTINO, 0) CORR_CUENTA_BANCO_DESTINO,
	ISNULL(F.NOMBRE_CUENTA_BANCO, '') NOMBRE_CUENTA_BANCO_DESTINO,
	ISNULL(A.NUMERO_CUENTA_DESTINO_TERCERO, '') NUMERO_CUENTA_DESTINO_TERCERO,
	ISNULL(A.MONTO_DESTINO, 0) MONTO_DESTINO,
	ISNULL(A.CORR_MONEDA, 0) CORR_MONEDA,
	ISNULL(A.FACTOR_CAMBIO, 1) FACTOR_CAMBIO,
	ISNULL(A.OPERADOR, '*') OPERADOR,
	A.FECHA_IMPRESO,
	A.FECHA_ANULACION
FROM dbo.BAN_DOCUMENTO A
INNER JOIN dbo.BAN_TIPO_MOVI_BANCARIO B
	ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO
INNER JOIN dbo.V_BAN_CUENTA_BANCARIA C
	ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CORR_CUENTA_BANCO = C.CORR_CUENTA_BANCO
LEFT JOIN dbo.V_BAN_TIPO_CHEQUE E
	ON A.CORR_EMPRESA = E.CORR_EMPRESA AND A.CORR_TIPO_CHEQUE = E.CORR_TIPO_CHEQUE
LEFT JOIN dbo.V_BAN_CUENTA_BANCARIA F
	ON A.CORR_EMPRESA = F.CORR_EMPRESA AND A.CORR_CUENTA_BANCO_DESTINO = F.CORR_CUENTA_BANCO;
GO

/* ── MTTO movimiento bancario ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_MOVIMIENTO', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_MOVIMIENTO];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_MOVIMIENTO]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_CUENTA_BANCO INT,
	@CORR_MOVIMIENTO INT OUTPUT,
	@FECHA_MOVIMIENTO DATE,
	@CORR_TIPO_MOVIMIENTO INT,
	@REFERENCIA VARCHAR(255),
	@NOMBRE_BENEFICIARIO VARCHAR(255),
	@DESCRIPCION_MOVIMIENTO VARCHAR(1000),
	@MONTO_CARGO DECIMAL(12, 2),
	@MONTO_ABONO DECIMAL(12, 2),
	@USUARIO_CREA VARCHAR(30),
	@FECHA_CREA DATETIME,
	@ESTACION_CREA VARCHAR(50),
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@CORR_DOCUMENTO INT = NULL,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT,
	@CORR_DOCUMENTO_DETA INT = NULL,
	@ANIO_PERIODO_DOC INT = 0,
	@MES_PERIODO_DOC INT = 0
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		IF ISNULL(@ANIO_PERIODO_DOC, 0) = 0
			SET @ANIO_PERIODO_DOC = @ANIO_PERIODO;
		IF ISNULL(@MES_PERIODO_DOC, 0) = 0
			SET @MES_PERIODO_DOC = @MES_PERIODO;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.CON_PERIODO_CONTABLE
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND ISNULL(ESTADO_PERIODO_BAN, 'AB') = 'AB'
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000,
				@SYS_MENSAJE_ERROR = N'El período bancario no está abierto.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF @TIPO_ACTUALIZA = 1
		BEGIN
			SELECT @CORR_MOVIMIENTO = ISNULL(MAX(CORR_MOVIMIENTO), 0) + 1
			FROM dbo.BAN_MOVIMIENTO
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO;

			INSERT INTO dbo.BAN_MOVIMIENTO
			(
				CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_CUENTA_BANCO, CORR_MOVIMIENTO,
				FECHA_MOVIMIENTO, CORR_TIPO_MOVIMIENTO, REFERENCIA, NOMBRE_BENEFICIARIO,
				DESCRIPCION_MOVIMIENTO, MONTO_CARGO, MONTO_ABONO,
				USUARIO_CREA, FECHA_CREA, ESTACION_CREA, USUARIO_ACTU, FECHA_ACTU, ESTACION_ACTU,
				CORR_DOCUMENTO, CORR_DOCUMENTO_DETA, ANIO_PERIODO_DOC, MES_PERIODO_DOC
			)
			VALUES
			(
				@CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, @CORR_CUENTA_BANCO, @CORR_MOVIMIENTO,
				@FECHA_MOVIMIENTO, @CORR_TIPO_MOVIMIENTO, @REFERENCIA, @NOMBRE_BENEFICIARIO,
				@DESCRIPCION_MOVIMIENTO, @MONTO_CARGO, @MONTO_ABONO,
				@USUARIO_CREA, @FECHA_CREA, @ESTACION_CREA, @USUARIO_ACTU, @FECHA_ACTU, @ESTACION_ACTU,
				@CORR_DOCUMENTO, @CORR_DOCUMENTO_DETA, @ANIO_PERIODO_DOC, @MES_PERIODO_DOC
			);
		END
		ELSE IF @TIPO_ACTUALIZA = 2
		BEGIN
			UPDATE dbo.BAN_MOVIMIENTO SET
				FECHA_MOVIMIENTO = @FECHA_MOVIMIENTO,
				CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO,
				REFERENCIA = @REFERENCIA,
				NOMBRE_BENEFICIARIO = @NOMBRE_BENEFICIARIO,
				DESCRIPCION_MOVIMIENTO = @DESCRIPCION_MOVIMIENTO,
				MONTO_CARGO = @MONTO_CARGO,
				MONTO_ABONO = @MONTO_ABONO,
				USUARIO_ACTU = @USUARIO_ACTU,
				FECHA_ACTU = @FECHA_ACTU,
				ESTACION_ACTU = @ESTACION_ACTU,
				CORR_DOCUMENTO = @CORR_DOCUMENTO,
				CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA,
				ANIO_PERIODO_DOC = @ANIO_PERIODO_DOC,
				MES_PERIODO_DOC = @MES_PERIODO_DOC
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO
				AND CORR_MOVIMIENTO = @CORR_MOVIMIENTO;
		END
		ELSE IF @TIPO_ACTUALIZA = 3
		BEGIN
			DELETE FROM dbo.BAN_MOVIMIENTO
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO
				AND CORR_MOVIMIENTO = @CORR_MOVIMIENTO;
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Aplicar documento (genera BAN_MOVIMIENTO) ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_DOCUMENTO_APLICAR', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_APLICAR];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_APLICAR]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE
		@ESTADO VARCHAR(2),
		@ESTA_CONTABILIZADO BIT,
		@MONTO_CARGO DECIMAL(18, 2),
		@MONTO_ABONO DECIMAL(18, 2),
		@NOMBRE_TIPO_MOVIMIENTO VARCHAR(100),
		@DETALLE_DOCUMENTO NVARCHAR(255),
		@CUENTA_CONTABLE_BANCO VARCHAR(30),
		@CORR_MOVIMIENTO INT,
		@CORR_CUENTA_BANCO INT,
		@FECHA_MOVIMIENTO DATE,
		@NOMBRE_BENEFICIARIO VARCHAR(255),
		@DESCRIPCION_MOVIMIENTO VARCHAR(1000),
		@REFERENCIA VARCHAR(255),
		@CORR_DOCUMENTO_DETA INT,
		@MONTO_CARGO_DETA DECIMAL(12, 2),
		@MONTO_ABONO_DETA DECIMAL(12, 2),
		@DESCRIPCION_MOVIMIENTO_DETA VARCHAR(1255);

	DECLARE @MOVIMIENTOS TABLE
	(
		CORR_DOCUMENTO_DETA INT NOT NULL,
		MONTO_CARGO_DETA DECIMAL(12, 2) NOT NULL,
		MONTO_ABONO_DETA DECIMAL(12, 2) NOT NULL,
		DESCRIPCION_MOVIMIENTO_DETA VARCHAR(1255) NOT NULL
	);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;
	SET @FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE());

	BEGIN TRY
		SELECT @NOMBRE_TIPO_MOVIMIENTO = NOMBRE_TIPO_MOVIMIENTO
		FROM dbo.BAN_TIPO_MOVI_BANCARIO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO;

		SET @DETALLE_DOCUMENTO = @NOMBRE_TIPO_MOVIMIENTO + N' del Año ' + CONVERT(VARCHAR(10), @ANIO_PERIODO)
			+ N' Mes ' + CONVERT(VARCHAR(10), @MES_PERIODO)
			+ N' Correlativo No.' + CONVERT(VARCHAR(10), @CORR_DOCUMENTO);

		SELECT
			@ESTADO = ESTADO_DOCUMENTO,
			@ESTA_CONTABILIZADO = ESTA_CONTABILIZADO,
			@CORR_CUENTA_BANCO = CORR_CUENTA_BANCO,
			@FECHA_MOVIMIENTO = FECHA_EMISION,
			@NOMBRE_BENEFICIARIO = ISNULL(NOMBRE_BENEFICIARIO, N''),
			@DESCRIPCION_MOVIMIENTO = NOMBRE_PARTIDA,
			@REFERENCIA = LTRIM(RTRIM(CONVERT(VARCHAR(25), NUMERO_DOCUMENTO)))
		FROM dbo.BAN_DOCUMENTO
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @ESTADO IN ('AP', 'IM', 'AN') OR ISNULL(@ESTA_CONTABILIZADO, 0) <> 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000,
				@SYS_MENSAJE_ERROR = N'Este documento ya está aplicado o anulado. ' + @DETALLE_DOCUMENTO + N' no se puede aplicar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.CON_PERIODO_CONTABLE
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND ISNULL(ESTADO_PERIODO_BAN, 'AB') = 'AB'
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30001,
				@SYS_MENSAJE_ERROR = N'El período bancario no está abierto. ' + @DETALLE_DOCUMENTO + N' no se puede aplicar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND CORR_DOCUMENTO = @CORR_DOCUMENTO
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30004,
				@SYS_MENSAJE_ERROR = N'El documento no tiene detalle contable. ' + @DETALLE_DOCUMENTO + N' no se puede aplicar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT @MONTO_CARGO = SUM(MONTO_CARGO), @MONTO_ABONO = SUM(MONTO_ABONO)
		FROM dbo.BAN_DOCUMENTO_DETA
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF ISNULL(@MONTO_CARGO, 0) <> ISNULL(@MONTO_ABONO, 0)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000,
				@SYS_MENSAJE_ERROR = N'El detalle contable no está cuadrado (cargo ≠ abono). ' + @DETALLE_DOCUMENTO + N' no se puede aplicar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT @CUENTA_CONTABLE_BANCO = CUENTA_CONTABLE
		FROM dbo.BAN_CUENTA_BANCARIA
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ANIO_PERIODO = @ANIO_PERIODO
				AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND CORR_DOCUMENTO = @CORR_DOCUMENTO
				AND CUENTA_CONTABLE = @CUENTA_CONTABLE_BANCO
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30005,
				@SYS_MENSAJE_ERROR = N'El documento no contiene la cuenta contable del banco. ' + @DETALLE_DOCUMENTO + N' no se puede aplicar.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		INSERT INTO @MOVIMIENTOS (CORR_DOCUMENTO_DETA, MONTO_CARGO_DETA, MONTO_ABONO_DETA, DESCRIPCION_MOVIMIENTO_DETA)
		SELECT B.CORR_DOCUMENTO_DETA, ISNULL(B.MONTO_CARGO, 0), ISNULL(B.MONTO_ABONO, 0), B.NOMBRE_TRAN
		FROM dbo.BAN_DOCUMENTO_DETA B
		WHERE B.CORR_EMPRESA = @CORR_EMPRESA
			AND B.ANIO_PERIODO = @ANIO_PERIODO
			AND B.MES_PERIODO = @MES_PERIODO
			AND B.CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND B.CORR_DOCUMENTO = @CORR_DOCUMENTO
			AND B.CUENTA_CONTABLE = @CUENTA_CONTABLE_BANCO;

		SET @CORR_MOVIMIENTO = 0;
		BEGIN TRANSACTION BAN_DOCUMENTO_APLICAR;

		WHILE EXISTS (SELECT 1 FROM @MOVIMIENTOS)
		BEGIN
			SELECT TOP 1
				@CORR_DOCUMENTO_DETA = CORR_DOCUMENTO_DETA,
				@MONTO_CARGO_DETA = MONTO_CARGO_DETA,
				@MONTO_ABONO_DETA = MONTO_ABONO_DETA,
				@DESCRIPCION_MOVIMIENTO_DETA = DESCRIPCION_MOVIMIENTO_DETA
			FROM @MOVIMIENTOS;

			EXEC dbo.PRAL_MTTO_BAN_MOVIMIENTO
				1,
				@CORR_EMPRESA,
				@ANIO_PERIODO,
				@MES_PERIODO,
				@CORR_CUENTA_BANCO,
				@CORR_MOVIMIENTO OUTPUT,
				@FECHA_MOVIMIENTO,
				@CORR_TIPO_MOVIMIENTO,
				@REFERENCIA,
				@NOMBRE_BENEFICIARIO,
				@DESCRIPCION_MOVIMIENTO_DETA,
				@MONTO_CARGO_DETA,
				@MONTO_ABONO_DETA,
				@USUARIO_ACTU,
				@FECHA_ACTU,
				@ESTACION_ACTU,
				@USUARIO_ACTU,
				@FECHA_ACTU,
				@ESTACION_ACTU,
				@CORR_DOCUMENTO,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@SYS_FILAS_AFECTADAS OUTPUT,
				@SYS_NUMERO_ERROR OUTPUT,
				@SYS_MENSAJE_ERROR OUTPUT,
				@CORR_DOCUMENTO_DETA,
				@ANIO_PERIODO,
				@MES_PERIODO;

			IF @SYS_NUMERO_ERROR <> 0
			BEGIN
				IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_APLICAR;
				SET @SYS_MENSAJE_ERROR = N'No se pudo generar el movimiento bancario. ' + @SYS_MENSAJE_ERROR;
				GOTO FINA;
			END;

			DELETE FROM @MOVIMIENTOS WHERE CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA;
		END;

		UPDATE dbo.BAN_DOCUMENTO SET
			ESTADO_DOCUMENTO = 'AP',
			CORR_MOVIMIENTO = @CORR_MOVIMIENTO,
			USUARIO_ACTU = @USUARIO_ACTU,
			FECHA_ACTU = @FECHA_ACTU,
			ESTACION_ACTU = @ESTACION_ACTU
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;

		IF @@TRANCOUNT > 0 COMMIT TRANSACTION BAN_DOCUMENTO_APLICAR;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_APLICAR;
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Anular documento (elimina movimientos si aplicado/impreso) ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_DOCUMENTO_ANULAR', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_ANULAR];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_ANULAR]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @ESTADO VARCHAR(2), @FECHA_ANULACION DATE;
	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;
	SET @FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE());
	SET @FECHA_ANULACION = CAST(@FECHA_ACTU AS DATE);

	BEGIN TRY
		SELECT @ESTADO = ESTADO_DOCUMENTO
		FROM dbo.BAN_DOCUMENTO
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @ESTADO = 'AN'
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El documento ya está anulado', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		BEGIN TRANSACTION BAN_DOCUMENTO_ANULAR;

		IF @ESTADO IN ('AP', 'IM')
		BEGIN
			DELETE FROM dbo.BAN_MOVIMIENTO
			WHERE CORR_EMPRESA = @CORR_EMPRESA
				AND ISNULL(ANIO_PERIODO_DOC, ANIO_PERIODO) = @ANIO_PERIODO
				AND ISNULL(MES_PERIODO_DOC, MES_PERIODO) = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND CORR_DOCUMENTO = @CORR_DOCUMENTO;
		END;

		UPDATE dbo.BAN_DOCUMENTO SET
			ESTADO_DOCUMENTO = 'AN',
			FECHA_ANULACION = @FECHA_ANULACION,
			CORR_MOVIMIENTO = NULL,
			CORR_MOVIMIENTO_DESTINO = NULL,
			USUARIO_ACTU = @USUARIO_ACTU,
			FECHA_ACTU = @FECHA_ACTU,
			ESTACION_ACTU = @ESTACION_ACTU
		WHERE CORR_EMPRESA = @CORR_EMPRESA
			AND ANIO_PERIODO = @ANIO_PERIODO
			AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;

		IF @@TRANCOUNT > 0 COMMIT TRANSACTION BAN_DOCUMENTO_ANULAR;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION BAN_DOCUMENTO_ANULAR;
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Vista datos impresión cheque ── */
IF OBJECT_ID(N'dbo.V_BAN_CHEQUE_IMPRIME', N'V') IS NOT NULL
	DROP VIEW [dbo].[V_BAN_CHEQUE_IMPRIME];
GO

CREATE VIEW [dbo].[V_BAN_CHEQUE_IMPRIME]
AS
SELECT
	A.CORR_EMPRESA,
	D.NOMBRE_EMPRESA,
	A.ANIO_PERIODO,
	A.MES_PERIODO,
	A.CORR_TIPO_MOVIMIENTO,
	A.NOMBRE_TIPO_MOVIMIENTO,
	A.CLASE_MOVIMIENTO,
	A.CORR_DOCUMENTO,
	A.CORR_CUENTA_BANCO,
	A.NOMBRE_CUENTA_BANCO,
	A.NUMERO_CUENTA_BANCO,
	A.NUMERO_DOCUMENTO,
	A.SERIE_CHEQUE,
	N'SAN SALVADOR, ' + LTRIM(RTRIM(CONVERT(VARCHAR(2), DAY(A.FECHA_EMISION)))) + N' DE '
		+ CASE MONTH(A.FECHA_EMISION)
			WHEN 1 THEN N'ENERO' WHEN 2 THEN N'FEBRERO' WHEN 3 THEN N'MARZO' WHEN 4 THEN N'ABRIL'
			WHEN 5 THEN N'MAYO' WHEN 6 THEN N'JUNIO' WHEN 7 THEN N'JULIO' WHEN 8 THEN N'AGOSTO'
			WHEN 9 THEN N'SEPTIEMBRE' WHEN 10 THEN N'OCTUBRE' WHEN 11 THEN N'NOVIEMBRE' WHEN 12 THEN N'DICIEMBRE'
			ELSE N'' END + N' DE ' + LTRIM(RTRIM(CONVERT(VARCHAR(4), YEAR(A.FECHA_EMISION)))) AS LUGAR_FECHA,
	A.FECHA_EMISION,
	A.NOMBRE_PARTIDA,
	A.CORR_PROVEEDOR,
	A.NOMBRE_BENEFICIARIO,
	A.MONTO_DOCUMENTO,
	A.ESTADO_DOCUMENTO,
	A.NOMBRE_ESTADO_DOCUMENTO,
	A.CANTIDAD_LETRAS,
	A.FECHA_IMPRESO,
	A.CORR_MOVIMIENTO,
	A.CORR_TIPO_CHEQUE,
	A.NOMBRE_TIPO_CHEQUE,
	A.CORR_CHEQUERA,
	B.CORR_DOCUMENTO_DETA,
	B.CUENTA_CONTABLE,
	ISNULL(C.NOMBRE_CUENTA, N'') NOMBRE_CUENTA,
	B.CORR_CENTRO_COSTO,
	N'CHQ #' + LTRIM(RTRIM(CONVERT(VARCHAR(20), A.NUMERO_DOCUMENTO))) + N' ' + B.NOMBRE_TRAN AS NOMBRE_TRAN,
	B.MONTO_CARGO,
	B.MONTO_ABONO,
	ISNULL(G.NOMBRE_MONEDA, N'') NOMBRE_MONEDA,
	ISNULL(G.SIMBOLO, N'') SIMBOLO_MONEDA
FROM dbo.V_BAN_DOCUMENTO A
INNER JOIN dbo.V_BAN_DOCUMENTO_DETA B
	ON A.CORR_EMPRESA = B.CORR_EMPRESA
	AND A.ANIO_PERIODO = B.ANIO_PERIODO
	AND A.MES_PERIODO = B.MES_PERIODO
	AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO
	AND A.CORR_DOCUMENTO = B.CORR_DOCUMENTO
INNER JOIN dbo.CON_CATALOGO_CUENTA C
	ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.CUENTA_CONTABLE = C.CUENTA_CONTABLE
INNER JOIN dbo.V_GEN_EMPRESA D
	ON A.CORR_EMPRESA = D.CORR_EMPRESA
LEFT JOIN dbo.GEN_TIPO_MONEDA G
	ON A.CORR_MONEDA = G.CORR_MONEDA
WHERE A.CLASE_MOVIMIENTO = 'CHQ';
GO

/* ── Imprimir cheque (actualiza referencia en movimiento) ── */
IF OBJECT_ID(N'dbo.PRAL_IMPR_BAN_CHEQUE_IMPRIME', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_IMPR_BAN_CHEQUE_IMPRIME];
GO

CREATE PROCEDURE [dbo].[PRAL_IMPR_BAN_CHEQUE_IMPRIME]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@USUARIO_ACTU VARCHAR(30) = '',
	@FECHA_ACTU DATETIME = NULL,
	@ESTACION_ACTU VARCHAR(50) = '',
	@SYS_LOGIN_USUARIO VARCHAR(30) = '',
	@SYS_ESTACION VARCHAR(50) = '',
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @ESTADO VARCHAR(2), @CLASE_MOV VARCHAR(3), @CORR_CUENTA INT, @CORR_CHEQUERA INT,
		@NUMERO_CHEQUE INT, @SERIE VARCHAR(10);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;
	SET @FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE());

	BEGIN TRY
		SELECT @ESTADO = A.ESTADO_DOCUMENTO, @CORR_CUENTA = A.CORR_CUENTA_BANCO, @CLASE_MOV = B.CLASE_MOVIMIENTO
		FROM dbo.BAN_DOCUMENTO A
		INNER JOIN dbo.BAN_TIPO_MOVI_BANCARIO B
			ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO
		WHERE A.CORR_EMPRESA = @CORR_EMPRESA AND A.ANIO_PERIODO = @ANIO_PERIODO AND A.MES_PERIODO = @MES_PERIODO
			AND A.CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND A.CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @CLASE_MOV <> 'CHQ'
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Solo se pueden imprimir documentos tipo Cheque', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF @ESTADO NOT IN ('AP', 'IM')
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El cheque debe estar aplicado para imprimir', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT TOP 1 @CORR_CHEQUERA = CORR_CHEQUERA, @NUMERO_CHEQUE = NUMERO_CHEQUE_ACTUAL, @SERIE = SERIE_CHEQUE
		FROM dbo.BAN_CHEQUERA
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA AND ESTADO_CHEQUERA = 'AC'
		ORDER BY CORR_CHEQUERA;

		IF ISNULL(@CORR_CHEQUERA, 0) = 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No hay chequera activa para la cuenta bancaria', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF @ESTADO = 'AP'
		BEGIN
			IF EXISTS (
				SELECT 1 FROM dbo.BAN_DOCUMENTO
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA
					AND CORR_CHEQUERA = @CORR_CHEQUERA AND SERIE_CHEQUE = @SERIE AND NUMERO_DOCUMENTO = @NUMERO_CHEQUE
					AND NOT (ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
						AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO)
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El número de cheque ya fue utilizado', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			UPDATE dbo.BAN_DOCUMENTO SET
				CORR_CHEQUERA = @CORR_CHEQUERA,
				NUMERO_DOCUMENTO = @NUMERO_CHEQUE,
				SERIE_CHEQUE = @SERIE,
				ESTADO_DOCUMENTO = 'IM',
				FECHA_IMPRESO = CAST(@FECHA_ACTU AS DATE),
				USUARIO_ACTU = @USUARIO_ACTU,
				FECHA_ACTU = @FECHA_ACTU,
				ESTACION_ACTU = @ESTACION_ACTU
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

			UPDATE M SET
				M.REFERENCIA = LTRIM(RTRIM(CONVERT(VARCHAR(25), D.SERIE_CHEQUE) + N' ' + CONVERT(VARCHAR(25), D.NUMERO_DOCUMENTO)))
			FROM dbo.BAN_MOVIMIENTO M
			INNER JOIN dbo.BAN_DOCUMENTO D
				ON M.CORR_EMPRESA = D.CORR_EMPRESA
				AND ISNULL(M.ANIO_PERIODO_DOC, M.ANIO_PERIODO) = D.ANIO_PERIODO
				AND ISNULL(M.MES_PERIODO_DOC, M.MES_PERIODO) = D.MES_PERIODO
				AND M.CORR_TIPO_MOVIMIENTO = D.CORR_TIPO_MOVIMIENTO
				AND M.CORR_DOCUMENTO = D.CORR_DOCUMENTO
			WHERE D.CORR_EMPRESA = @CORR_EMPRESA
				AND D.ANIO_PERIODO = @ANIO_PERIODO
				AND D.MES_PERIODO = @MES_PERIODO
				AND D.CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
				AND D.CORR_DOCUMENTO = @CORR_DOCUMENTO;

			UPDATE dbo.BAN_CHEQUERA SET
				NUMERO_CHEQUE_ACTUAL = NUMERO_CHEQUE_ACTUAL + 1,
				ESTADO_CHEQUERA = CASE WHEN (NUMERO_CHEQUE_ACTUAL + 1) > NUMERO_CHEQUE_FINAL THEN 'IN' ELSE ESTADO_CHEQUERA END
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA AND CORR_CHEQUERA = @CORR_CHEQUERA
				AND NUMERO_CHEQUE_ACTUAL < NUMERO_CHEQUE_FINAL;
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

PRINT N'DEPLOY_BAN_MOVIMIENTO completado.';
GO
