/*
  Despliega vistas V_COM_* faltantes en SGUEES (250).
  Corrige referencias linked server CLASS_UEES a 4 partes.

  sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i DEPLOY_COM_VIEWS_FALTANTES.sql
*/
SET NOCOUNT ON;
GO

PRINT N'=== Vistas Compras faltantes ===';
GO

-- Orden: dependencias primero (SUM / hijas), luego encabezados.

IF OBJECT_ID(N'dbo.V_COM_SOLI_COTIZACION_SOLI_COMPRA_SUM', N'V') IS NOT NULL DROP VIEW dbo.V_COM_SOLI_COTIZACION_SOLI_COMPRA_SUM;
IF OBJECT_ID(N'dbo.V_COM_SOLI_COTIZACION_PROVEEDOR_SUM', N'V') IS NOT NULL DROP VIEW dbo.V_COM_SOLI_COTIZACION_PROVEEDOR_SUM;
IF OBJECT_ID(N'dbo.V_COM_PROVEEDOR_USUARIO_SUM', N'V') IS NOT NULL DROP VIEW dbo.V_COM_PROVEEDOR_USUARIO_SUM;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_PROVEEDOR_SUM', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_PROVEEDOR_SUM;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_COTIZACION_SUM', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_COTIZACION_SUM;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_COTIZACION_NORMAL_SUM', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_COTIZACION_NORMAL_SUM;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_ORDEN_COMPRA_SUM', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_ORDEN_COMPRA_SUM;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_SOLI_COTIZACION_SUM', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_SOLI_COTIZACION_SUM;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_SUM', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_SUM;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_DETA_SUM', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_DETA_SUM;
IF OBJECT_ID(N'dbo.V_COM_ORDEN_COMPRA_TOTALES', N'V') IS NOT NULL DROP VIEW dbo.V_COM_ORDEN_COMPRA_TOTALES;
GO

:r "..\Views\dbo.V_COM_SOLI_COTIZACION_SOLI_COMPRA_SUM.sql"
GO
:r "..\Views\dbo.V_COM_SOLI_COTIZACION_PROVEEDOR_SUM.sql"
GO
:r "..\Views\dbo.V_COM_PROVEEDOR_USUARIO_SUM.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_PROVEEDOR_SUM.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_COTIZACION_SUM.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_COTIZACION_NORMAL_SUM.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_ORDEN_COMPRA_SUM.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_SOLI_COTIZACION_SUM.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_SUM.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_DETA_SUM.sql"
GO
:r "..\Views\dbo.V_COM_ORDEN_COMPRA_TOTALES.sql"
GO

-- Vistas con dependencias de SUM / otras V_COM_*
IF OBJECT_ID(N'dbo.V_COM_SOLI_COTIZACION_PROVEEDOR', N'V') IS NOT NULL DROP VIEW dbo.V_COM_SOLI_COTIZACION_PROVEEDOR;
IF OBJECT_ID(N'dbo.V_COM_SOLI_COTIZACION_DETA', N'V') IS NOT NULL DROP VIEW dbo.V_COM_SOLI_COTIZACION_DETA;
IF OBJECT_ID(N'dbo.V_COM_SOLI_COTIZACION', N'V') IS NOT NULL DROP VIEW dbo.V_COM_SOLI_COTIZACION;
IF OBJECT_ID(N'dbo.V_COM_SOLI_COTIZACION_IMPR', N'V') IS NOT NULL DROP VIEW dbo.V_COM_SOLI_COTIZACION_IMPR;
IF OBJECT_ID(N'dbo.V_COM_COTIZACION_DETA', N'V') IS NOT NULL DROP VIEW dbo.V_COM_COTIZACION_DETA;
IF OBJECT_ID(N'dbo.V_COM_COTIZACION', N'V') IS NOT NULL DROP VIEW dbo.V_COM_COTIZACION;
IF OBJECT_ID(N'dbo.V_COM_COTIZACION_APLICA_CORREO', N'V') IS NOT NULL DROP VIEW dbo.V_COM_COTIZACION_APLICA_CORREO;
IF OBJECT_ID(N'dbo.V_COM_COTIZACION_CORREO', N'V') IS NOT NULL DROP VIEW dbo.V_COM_COTIZACION_CORREO;
IF OBJECT_ID(N'dbo.V_COM_COTIZACION_CONSULTA', N'V') IS NOT NULL DROP VIEW dbo.V_COM_COTIZACION_CONSULTA;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_PROVEEDOR', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_PROVEEDOR;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_DETA', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_DETA;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_TOTAL', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_TOTAL;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_DOC', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_DOC;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_IMPR', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_IMPR;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_ORDEN_COMPRA', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_ORDEN_COMPRA;
IF OBJECT_ID(N'dbo.V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_CONSOLIDADAS', N'V') IS NOT NULL DROP VIEW dbo.V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_CONSOLIDADAS;
IF OBJECT_ID(N'dbo.V_COM_ORDEN_COMPRA_DETA', N'V') IS NOT NULL DROP VIEW dbo.V_COM_ORDEN_COMPRA_DETA;
IF OBJECT_ID(N'dbo.V_COM_ORDEN_COMPRA', N'V') IS NOT NULL DROP VIEW dbo.V_COM_ORDEN_COMPRA;
IF OBJECT_ID(N'dbo.V_COM_DOCUMENTO', N'V') IS NOT NULL DROP VIEW dbo.V_COM_DOCUMENTO;
IF OBJECT_ID(N'dbo.V_COM_DOCUMENTO_TOTAL_RESUMEN', N'V') IS NOT NULL DROP VIEW dbo.V_COM_DOCUMENTO_TOTAL_RESUMEN;
IF OBJECT_ID(N'dbo.V_COM_DOCUMENTO_TOTAL_RESUMEN_CONSOLIDADO', N'V') IS NOT NULL DROP VIEW dbo.V_COM_DOCUMENTO_TOTAL_RESUMEN_CONSOLIDADO;
IF OBJECT_ID(N'dbo.V_COM_JSON_DOC', N'V') IS NOT NULL DROP VIEW dbo.V_COM_JSON_DOC;
IF OBJECT_ID(N'dbo.V_COM_PROVEEDOR_COMPRAS_LOOKUP', N'V') IS NOT NULL DROP VIEW dbo.V_COM_PROVEEDOR_COMPRAS_LOOKUP;
GO

:r "..\Views\dbo.V_COM_SOLI_COTIZACION_PROVEEDOR.sql"
GO
:r "..\Views\dbo.V_COM_SOLI_COTIZACION_DETA.sql"
GO
:r "..\Views\dbo.V_COM_SOLI_COTIZACION.sql"
GO
:r "..\Views\dbo.V_COM_SOLI_COTIZACION_IMPR.sql"
GO
:r "..\Views\dbo.V_COM_COTIZACION_DETA.sql"
GO
:r "..\Views\dbo.V_COM_COTIZACION.sql"
GO
:r "..\Views\dbo.V_COM_COTIZACION_APLICA_CORREO.sql"
GO
:r "..\Views\dbo.V_COM_COTIZACION_CORREO.sql"
GO
:r "..\Views\dbo.V_COM_COTIZACION_CONSULTA.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_PROVEEDOR.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_DETA.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_TOTAL.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_DOC.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_IMPR.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_ORDEN_COMPRA.sql"
GO
:r "..\Views\dbo.V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_CONSOLIDADAS.sql"
GO
:r "..\Views\dbo.V_COM_ORDEN_COMPRA_DETA.sql"
GO
:r "..\Views\dbo.V_COM_ORDEN_COMPRA.sql"
GO
:r "..\Views\dbo.V_COM_DOCUMENTO.sql"
GO
:r "..\Views\dbo.V_COM_DOCUMENTO_TOTAL_RESUMEN.sql"
GO
:r "..\Views\dbo.V_COM_DOCUMENTO_TOTAL_RESUMEN_CONSOLIDADO.sql"
GO
:r "..\Views\dbo.V_COM_JSON_DOC.sql"
GO
:r "..\Views\dbo.V_COM_PROVEEDOR_COMPRAS_LOOKUP.sql"
GO

PRINT N'=== Verificación solicitud cotización ===';
SELECT COUNT(*) AS filas_vista FROM dbo.V_COM_SOLI_COTIZACION;
SELECT TOP 3 CORR_SOLI_COTIZACION, FECHA_SOLI_COTIZACION, NOMBRE_DEPTO, NOMBRE_ESTADO_SOLI_COTIZACION
FROM dbo.V_COM_SOLI_COTIZACION
ORDER BY FECHA_SOLI_COTIZACION DESC;
GO

PRINT N'=== DEPLOY_COM_VIEWS_FALTANTES completado ===';
GO
