/* =============================================================================
   DEPLOY — V_BAN_SOLI_CHEQUE adaptada al nuevo GEN_EMPLEADO
   Ejecutar en SGUEES (SSMS).
   Nota: PRAL_MTTO_BAN_SOLI_CHEQUE solo valida EXISTS(CORR_EMPRESA, CORR_EMPLEADO);
         no requiere cambio.
   ============================================================================= */

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: vista de solicitudes de cheque (beneficiario proveedor/empleado/cliente).
-- Cómo lo hace: proyecta BAN_SOLI_CHEQUE; el nombre de empleado sale de
--               GEN_PERSONA_NATURAL vía GEN_EMPLEADO (modelo nuevo).
CREATE OR ALTER VIEW [dbo].[V_BAN_SOLI_CHEQUE]
AS
SELECT
	A.CORR_EMPRESA,
	A.ANIO_PERIODO,
	A.MES_PERIODO,
	A.CORR_TIPO_MOVIMIENTO,
	B.NOMBRE_TIPO_MOVIMIENTO,
	A.CORR_DOCUMENTO,
	ISNULL(A.CORR_CUENTA_BANCO, 0) CORR_CUENTA_BANCO,
	ISNULL(C.NOMBRE_CUENTA_BANCO, N'') NOMBRE_CUENTA_BANCO,
	ISNULL(C.NUMERO_CUENTA_BANCO, N'') NUMERO_CUENTA_BANCO,
	A.NUMERO_DOCUMENTO,
	A.FECHA_EMISION,
	A.NOMBRE_PARTIDA,
	ISNULL(A.CORR_PROVEEDOR, 0) CORR_PROVEEDOR,
	ISNULL(D.NOMBRE_PROVEEDOR, ISNULL(PN.NOMBRE_COMPLETO, ISNULL(H.NOMBRE_CLIENTE, ISNULL(A.NOMBRE_BENEFICIARIO, N'')))) AS NOMBRE_PROVEEDOR,
	ISNULL(A.CORR_EMPLEADO, 0) CORR_EMPLEADO,
	ISNULL(A.CORR_CLIENTE, 0) CORR_CLIENTE,
	A.NOMBRE_BENEFICIARIO,
	A.MONTO_DOCUMENTO,
	A.ESTADO_DOCUMENTO,
	CASE A.ESTADO_DOCUMENTO
		WHEN 'DI' THEN N'Digitado'
		WHEN 'SO' THEN N'Solicitado'
		WHEN 'AP' THEN N'Aplicado'
		WHEN 'EM' THEN N'Emitido'
		ELSE N''
	END AS NOMBRE_ESTADO_DOCUMENTO,
	A.SOLICITADO_POR,
	A.FECHA_SOLICITADO,
	A.APLICADO_POR,
	A.FECHA_APLICADO,
	A.CANTIDAD_LETRAS,
	A.USUARIO_CREA,
	A.FECHA_CREA,
	A.ESTACION_CREA,
	A.USUARIO_ACTU,
	A.FECHA_ACTU,
	A.ESTACION_ACTU,
	ISNULL(A.CORR_TIPO_CHEQUE, 0) CORR_TIPO_CHEQUE,
	ISNULL(E.NOMBRE_TIPO_CHEQUE, N'') NOMBRE_TIPO_CHEQUE,
	ISNULL(E.CLASE_TIPO_CHEQUE, N'') CLASE_TIPO_CHEQUE,
	A.ANIO_PERIODO_CHEQUE,
	A.MES_PERIODO_CHEQUE,
	A.CORR_TIPO_MOVIMIENTO_CHEQUE,
	A.CORR_DOCUMENTO_CHEQUE,
	ISNULL(A.CORR_MONEDA, 0) CORR_MONEDA,
	ISNULL(I.NOMBRE_MONEDA, N'') NOMBRE_MONEDA,
	ISNULL(I.SIMBOLO, N'') SIMBOLO,
	ISNULL(A.FACTOR_CAMBIO, 1) FACTOR_CAMBIO,
	ISNULL(A.OPERADOR, '*') OPERADOR
FROM dbo.BAN_SOLI_CHEQUE A
INNER JOIN dbo.BAN_TIPO_MOVI_BANCARIO B
	ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO
LEFT JOIN dbo.V_BAN_CUENTA_BANCARIA C
	ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CORR_CUENTA_BANCO = C.CORR_CUENTA_BANCO
LEFT JOIN dbo.V_BAN_TIPO_CHEQUE E
	ON A.CORR_EMPRESA = E.CORR_EMPRESA AND A.CORR_TIPO_CHEQUE = E.CORR_TIPO_CHEQUE
LEFT JOIN dbo.GEN_PROVEEDOR D
	ON A.CORR_EMPRESA = D.CORR_EMPRESA AND A.CORR_PROVEEDOR = D.CORR_PROVEEDOR
LEFT JOIN dbo.GEN_EMPLEADO G
	ON A.CORR_EMPRESA = G.CORR_EMPRESA AND A.CORR_EMPLEADO = G.CORR_EMPLEADO
LEFT JOIN dbo.GEN_PERSONA_NATURAL PN
	ON PN.CORR_PERSONA = G.CORR_PERSONA
LEFT JOIN dbo.GEN_CLIENTE H
	ON A.CORR_EMPRESA = H.CORR_EMPRESA AND A.CORR_CLIENTE = H.CORR_CLIENTE
LEFT JOIN dbo.GEN_TIPO_MONEDA I
	ON A.CORR_MONEDA = I.CORR_MONEDA;
GO
