/*
  Despliega BAN_TIPO_MOVI_SEGUN_BANCO (tabla, vista, SP) — e-Admin -> SGUEES.
  Requiere: GEN_BANCO, BAN_TIPO_MOVI_BANCARIO.

  Uso:
    cd "C:\Desarrollo GIT\SGUEES\SGUEES-DB\Scripts"
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i DEPLOY_BAN_TIPO_MOVI_SEGUN_BANCO.sql
*/
SET NOCOUNT ON;
GO

IF OBJECT_ID('dbo.GEN_BANCO', 'U') IS NULL
BEGIN
    RAISERROR('GEN_BANCO no existe. Despliegue GEN_BANCO antes de continuar.', 16, 1);
    RETURN;
END
ELSE
    PRINT 'GEN_BANCO OK.';
GO

IF OBJECT_ID('dbo.BAN_TIPO_MOVI_BANCARIO', 'U') IS NULL
BEGIN
    RAISERROR('BAN_TIPO_MOVI_BANCARIO no existe. Ejecute DEPLOY_BAN_TABLAS_GENERALES.sql primero.', 16, 1);
    RETURN;
END
ELSE
    PRINT 'BAN_TIPO_MOVI_BANCARIO OK.';
GO

IF OBJECT_ID('dbo.BAN_TIPO_MOVI_SEGUN_BANCO', 'U') IS NULL
BEGIN
    PRINT 'Creando BAN_TIPO_MOVI_SEGUN_BANCO...';
    CREATE TABLE [dbo].[BAN_TIPO_MOVI_SEGUN_BANCO]
    (
        [CORR_EMPRESA] [int] NOT NULL,
        [CORR_TIPO_MOVIMIENTO] [int] NOT NULL,
        [CORR_BANCO] [int] NOT NULL,
        [CODIGO_MOVIMIENTO] [varchar] (10) COLLATE Latin1_General_CS_AS NOT NULL,
        [NOMBRE_MOVIMIENTO_SEGUN_BANCO] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL
    ) ON [PRIMARY];

    ALTER TABLE [dbo].[BAN_TIPO_MOVI_SEGUN_BANCO] ADD CONSTRAINT [PK_BAN_TIPO_MOVI_SEGUN_BANCO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_MOVIMIENTO], [CORR_BANCO], [CODIGO_MOVIMIENTO]) ON [PRIMARY];

    ALTER TABLE [dbo].[BAN_TIPO_MOVI_SEGUN_BANCO] ADD CONSTRAINT [FK_BAN_TIPO_MOVI_SEGUN_BANCO_BAN_TIPO_MOVI_BANCARIO] FOREIGN KEY ([CORR_EMPRESA], [CORR_TIPO_MOVIMIENTO]) REFERENCES [dbo].[BAN_TIPO_MOVI_BANCARIO] ([CORR_EMPRESA], [CORR_TIPO_MOVIMIENTO]);

    ALTER TABLE [dbo].[BAN_TIPO_MOVI_SEGUN_BANCO] ADD CONSTRAINT [FK_BAN_TIPO_MOVI_SEGUN_BANCO_GEN_BANCO] FOREIGN KEY ([CORR_EMPRESA], [CORR_BANCO]) REFERENCES [dbo].[GEN_BANCO] ([CORR_EMPRESA], [CORR_BANCO]);
END
ELSE
    PRINT 'BAN_TIPO_MOVI_SEGUN_BANCO OK.';
GO

IF OBJECT_ID('dbo.V_BAN_TIPO_MOVI_SEGUN_BANCO', 'V') IS NOT NULL
    DROP VIEW dbo.V_BAN_TIPO_MOVI_SEGUN_BANCO;
GO
:r ..\Views\dbo.V_BAN_TIPO_MOVI_SEGUN_BANCO.sql
GO
PRINT 'Vista V_BAN_TIPO_MOVI_SEGUN_BANCO desplegada.';
GO

IF OBJECT_ID(N'dbo.PRAL_DATA_BAN_TIPO_MOVI_SEGUN_BANCO', N'P') IS NOT NULL
    DROP PROCEDURE dbo.PRAL_DATA_BAN_TIPO_MOVI_SEGUN_BANCO;
GO
:r "..\Stored Procedures\dbo.PRAL_DATA_BAN_TIPO_MOVI_SEGUN_BANCO.sql"
GO
PRINT 'SP PRAL_DATA_BAN_TIPO_MOVI_SEGUN_BANCO desplegado.';
GO

IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_TIPO_MOVI_SEGUN_BANCO', N'P') IS NOT NULL
    DROP PROCEDURE dbo.PRAL_MTTO_BAN_TIPO_MOVI_SEGUN_BANCO;
GO
:r "..\Stored Procedures\dbo.PRAL_MTTO_BAN_TIPO_MOVI_SEGUN_BANCO.sql"
GO
PRINT 'SP PRAL_MTTO_BAN_TIPO_MOVI_SEGUN_BANCO desplegado.';
GO

SELECT OBJECT_NAME(object_id) AS objeto, type_desc
FROM sys.objects
WHERE name IN (
    'BAN_TIPO_MOVI_SEGUN_BANCO',
    'V_BAN_TIPO_MOVI_SEGUN_BANCO',
    'PRAL_DATA_BAN_TIPO_MOVI_SEGUN_BANCO',
    'PRAL_MTTO_BAN_TIPO_MOVI_SEGUN_BANCO'
)
ORDER BY 1;
GO

PRINT N'DEPLOY_BAN_TIPO_MOVI_SEGUN_BANCO — OK';
GO