/*
  Reportes bancarios oleada 1 — vistas + SPs (adaptados desde e-Admin).
  Requiere: BAN_DOCUMENTO, BAN_MOVIMIENTO, V_BAN_DOCUMENTO desplegados.

  Uso:
    cd "C:\Desarrollo GIT\SGUEES\SGUEES-DB\Scripts"
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i DEPLOY_BAN_REPORTES.sql
*/
SET NOCOUNT ON;
GO

PRINT N'=== Columnas entrega de cheques en BAN_DOCUMENTO ===';
IF COL_LENGTH(N'dbo.BAN_DOCUMENTO', N'ESTADO_ENTREGA') IS NULL
BEGIN
	ALTER TABLE dbo.BAN_DOCUMENTO ADD ESTADO_ENTREGA VARCHAR(2) NULL CONSTRAINT DF_BAN_DOC_ESTADO_ENTREGA DEFAULT ('EF');
	PRINT N'Columna ESTADO_ENTREGA agregada.';
END
GO

IF COL_LENGTH(N'dbo.BAN_DOCUMENTO', N'FECHA_ENTREGA') IS NULL
BEGIN
	ALTER TABLE dbo.BAN_DOCUMENTO ADD FECHA_ENTREGA DATE NULL;
	PRINT N'Columna FECHA_ENTREGA agregada.';
END
GO

IF COL_LENGTH(N'dbo.BAN_DOCUMENTO', N'NOMBRE_RECIBE') IS NULL
BEGIN
	ALTER TABLE dbo.BAN_DOCUMENTO ADD NOMBRE_RECIBE VARCHAR(255) NULL;
	PRINT N'Columna NOMBRE_RECIBE agregada.';
END
GO

PRINT N'=== Vistas reportes BAN ===';
IF OBJECT_ID(N'dbo.V_BAN_MOVIMIENTO', N'V') IS NOT NULL DROP VIEW dbo.V_BAN_MOVIMIENTO;
GO
:r ..\Views\dbo.V_BAN_MOVIMIENTO.sql
GO

IF OBJECT_ID(N'dbo.V_BAN_CHEQUES_EMITIDOS', N'V') IS NOT NULL DROP VIEW dbo.V_BAN_CHEQUES_EMITIDOS;
GO
:r ..\Views\dbo.V_BAN_CHEQUES_EMITIDOS.sql
GO

IF OBJECT_ID(N'dbo.V_BAN_ENTREGA_CHEQUES', N'V') IS NOT NULL DROP VIEW dbo.V_BAN_ENTREGA_CHEQUES;
GO
:r ..\Views\dbo.V_BAN_ENTREGA_CHEQUES.sql
GO

PRINT N'=== SP saldo inicial bancario ===';
IF OBJECT_ID(N'dbo.PRAL_GENE_BAN_SALDO_INICIAL', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_GENE_BAN_SALDO_INICIAL;
GO
:r "..\Stored Procedures\dbo.PRAL_GENE_BAN_SALDO_INICIAL.sql"
GO

PRINT N'=== SP impresion / consulta reportes BAN ===';
IF OBJECT_ID(N'dbo.PRAL_IMPR_BAN_CHEQUE_EMITIDOS', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_IMPR_BAN_CHEQUE_EMITIDOS;
GO
:r "..\Stored Procedures\dbo.PRAL_IMPR_BAN_CHEQUE_EMITIDOS.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_IMPR_BAN_ENTREGA_CHEQUES', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_IMPR_BAN_ENTREGA_CHEQUES;
GO
:r "..\Stored Procedures\dbo.PRAL_IMPR_BAN_ENTREGA_CHEQUES.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_IMPR_BAN_ESTADO_CUENTA', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_IMPR_BAN_ESTADO_CUENTA;
GO
:r "..\Stored Procedures\dbo.PRAL_IMPR_BAN_ESTADO_CUENTA.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_IMPR_BAN_ESTADO_CUENTA_ACUMULADO', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_IMPR_BAN_ESTADO_CUENTA_ACUMULADO;
GO
:r "..\Stored Procedures\dbo.PRAL_IMPR_BAN_ESTADO_CUENTA_ACUMULADO.sql"
GO

PRINT N'=== Objetos desplegados ===';
SELECT name, type_desc
FROM sys.objects
WHERE name IN (
	'V_BAN_MOVIMIENTO',
	'V_BAN_CHEQUES_EMITIDOS',
	'V_BAN_ENTREGA_CHEQUES',
	'PRAL_GENE_BAN_SALDO_INICIAL',
	'PRAL_IMPR_BAN_CHEQUE_EMITIDOS',
	'PRAL_IMPR_BAN_ENTREGA_CHEQUES',
	'PRAL_IMPR_BAN_ESTADO_CUENTA',
	'PRAL_IMPR_BAN_ESTADO_CUENTA_ACUMULADO'
)
ORDER BY name;
GO

PRINT N'DEPLOY_BAN_REPORTES completado.';
GO
