/* =============================================================================
   DEPLOY — Vistas/FNs/SP adaptados al nuevo GEN_EMPLEADO (persona + usuario)
   Ejecutar en SGUEES (SSMS). Orden: vistas base → organigrama → contab/impr → FNs → SP.
   ============================================================================= */

/* ---- Views\dbo.V_GEN_EMPLEADO.sql ---- */
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- QuÃ© hace: catÃ¡logo de empleados para lookups (misma forma que antes para API/SPA).
-- CÃ³mo lo hace: lee GEN_EMPLEADO nuevo + GEN_PERSONA_NATURAL (nombre) + GEN_PERSONA_USUARIO (login)
--               + puesto vigente desde GEN_EMPLEADO_PUESTO. Expone alias legacy
--               (NOMBRE_EMPLEADO, ESTADO_EMPLEADO, LOGIN_SISTEMA_WEB, etc.).
CREATE OR ALTER VIEW [dbo].[V_GEN_EMPLEADO]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_EMPLEADO,
	A.CORR_PERSONA,
	A.CODIGO_EMPLEADO,
	ISNULL(PN.NOMBRE_COMPLETO, N'') AS NOMBRE_EMPLEADO,
	ISNULL(PN.PRIMER_NOMBRE, N'') AS NOMBRE_1,
	ISNULL(PN.SEGUNDO_NOMBRE, N'') AS NOMBRE_2,
	ISNULL(PN.PRIMER_APELLIDO, N'') AS APELLIDO_1,
	ISNULL(PN.SEGUNDO_APELLIDO, N'') AS APELLIDO_2,
	ISNULL(PN.APELLIDO_CASADA, N'') AS APELLIDO_3,
	CAST(N'' AS VARCHAR(25)) AS DUI,
	CAST(N'' AS VARCHAR(25)) AS NIT,
	ISNULL(A.CORREO_INSTITUCIONAL, N'') AS CORREO_ELECTRONICO,
	ISNULL(A.TELEFONO_INSTITUCIONAL, N'') AS TELEFONO_1,
	CAST(0 AS INT) AS CORR_CENTRO_COSTO,
	CAST(0 AS INT) AS CORR_DEPARTAMENTO,
	ISNULL(EP.CORR_PUESTO, 0) AS CORR_PUESTO,
	CAST(CASE WHEN ISNULL(A.ACTIVO_EMPLEADO, 0) = 1 THEN N'1' ELSE N'0' END AS VARCHAR(2)) AS ESTADO_EMPLEADO,
	CASE WHEN ISNULL(A.ACTIVO_EMPLEADO, 0) = 1 THEN N'Activo' ELSE N'Inactivo' END AS NOMBRE_ESTADO_EMPLEADO,
	ISNULL(PU.LOGIN_SISTEMA, N'') AS LOGIN_SISTEMA,
	ISNULL(PU.LOGIN_SISTEMA, N'') AS LOGIN_SISTEMA_WEB,
	A.USUARIO_CREA,
	A.FECHA_CREA,
	A.ESTACION_CREA,
	A.USUARIO_ACTU,
	A.FECHA_ACTU,
	A.ESTACION_ACTU
FROM dbo.GEN_EMPLEADO A
LEFT JOIN dbo.GEN_PERSONA_NATURAL PN
	ON PN.CORR_PERSONA = A.CORR_PERSONA
OUTER APPLY
(
	SELECT TOP (1) U.LOGIN_SISTEMA
	FROM dbo.GEN_PERSONA_USUARIO U
	WHERE U.CORR_PERSONA = A.CORR_PERSONA
	ORDER BY U.LOGIN_SISTEMA
) PU
OUTER APPLY
(
	SELECT TOP (1) P.CORR_PUESTO
	FROM dbo.GEN_EMPLEADO_PUESTO P
	WHERE P.CORR_EMPRESA = A.CORR_EMPRESA
	  AND P.CORR_EMPLEADO = A.CORR_EMPLEADO
	ORDER BY
		P.FECHA_INGRESO DESC,
		P.FECHA_CREA DESC,
		P.CORR_PUESTO DESC
) EP
GO


/* ---- Views\dbo.V_GEN_EMPLEADO_DISPONIBLE.sql ---- */
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- QuÃ© hace: empleados con puesto/unidad para combos (organigrama / jefes).
-- CÃ³mo lo hace: GEN_EMPLEADO + GEN_EMPLEADO_PUESTO + unidad + PLA_PUESTO;
--               nombre y login desde persona (misma forma que V_GEN_EMPLEADO).
CREATE OR ALTER VIEW [dbo].[V_GEN_EMPLEADO_DISPONIBLE]
AS
SELECT
	GE.CORR_EMPRESA,
	GE.CORR_EMPLEADO,
	ISNULL(PN.NOMBRE_COMPLETO, N'') AS NOMBRE_EMPLEADO,
	PU.LOGIN_SISTEMA AS LOGIN_SISTEMA_WEB,
	EP.CORR_PUESTO,
	PP.NOMBRE_PUESTO,
	EP.CORR_UNIDAD AS CORR_UNIDAD_EMPLEADO,
	U.NOMBRE_UNIDAD AS UNIDAD_EMPLEADO,
	U.CODIGO_UNIDAD AS CODIGO_UNIDAD_EMPLEADO
FROM dbo.GEN_EMPLEADO GE
INNER JOIN dbo.GEN_EMPLEADO_PUESTO EP
	ON EP.CORR_EMPLEADO = GE.CORR_EMPLEADO
   AND EP.CORR_EMPRESA = GE.CORR_EMPRESA
INNER JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES U
	ON U.CORR_UNIDAD = EP.CORR_UNIDAD
   AND U.CORR_EMPRESA = EP.CORR_EMPRESA
LEFT JOIN dbo.PLA_PUESTO PP
	ON PP.CORR_PUESTO = EP.CORR_PUESTO
   AND PP.CORR_EMPRESA = EP.CORR_EMPRESA
LEFT JOIN dbo.GEN_PERSONA_NATURAL PN
	ON PN.CORR_PERSONA = GE.CORR_PERSONA
OUTER APPLY
(
	SELECT TOP (1) X.LOGIN_SISTEMA
	FROM dbo.GEN_PERSONA_USUARIO X
	WHERE X.CORR_PERSONA = GE.CORR_PERSONA
	ORDER BY X.LOGIN_SISTEMA
) PU
GO


/* ---- Views\dbo.V_GEN_EMPLEADO_DISPONIBLE_ACTOR.sql ---- */
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- QuÃ© hace: empleados disponibles para asignar a actores de flujo (por unidad).
-- CÃ³mo lo hace: empleado activo con login en GEN_PERSONA_USUARIO + puesto/unidad;
--               CROSS JOIN actores que requieren unidad y aÃºn no tienen asignaciÃ³n.
CREATE OR ALTER VIEW [dbo].[V_GEN_EMPLEADO_DISPONIBLE_ACTOR]
AS
SELECT
	GE.CORR_EMPLEADO,
	ISNULL(PN.NOMBRE_COMPLETO, N'') AS NOMBRE_EMPLEADO,
	PU.LOGIN_SISTEMA AS LOGIN_SISTEMA_WEB,
	EP.CORR_PUESTO,
	PP.NOMBRE_PUESTO,
	U.CORR_UNIDAD AS CORR_UNIDAD_EMPLEADO,
	U.NOMBRE_UNIDAD AS UNIDAD_EMPLEADO,
	U.CODIGO_UNIDAD AS CODIGO_UNIDAD_EMPLEADO,
	A.CORR_ACTOR,
	A.NOMBRE_ACTOR
FROM dbo.GEN_EMPLEADO GE
INNER JOIN dbo.GEN_EMPLEADO_PUESTO EP
	ON EP.CORR_EMPLEADO = GE.CORR_EMPLEADO
   AND EP.CORR_EMPRESA = GE.CORR_EMPRESA
INNER JOIN dbo.PLA_PUESTO PP
	ON PP.CORR_PUESTO = EP.CORR_PUESTO
   AND PP.CORR_EMPRESA = EP.CORR_EMPRESA
INNER JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES U
	ON U.CORR_UNIDAD = EP.CORR_UNIDAD
   AND U.CORR_EMPRESA = EP.CORR_EMPRESA
INNER JOIN dbo.GEN_PERSONA_USUARIO PU
	ON PU.CORR_PERSONA = GE.CORR_PERSONA
LEFT JOIN dbo.GEN_PERSONA_NATURAL PN
	ON PN.CORR_PERSONA = GE.CORR_PERSONA
CROSS JOIN dbo.SEG_FLUJO_ACTOR A
WHERE GE.CORR_EMPRESA = 1
  AND ISNULL(GE.ACTIVO_EMPLEADO, 0) = 1
  AND A.CORR_EMPRESA = 1
  AND A.ACTIVO = 1
  AND A.REQUIERE_UNIDAD = 1
  AND NOT EXISTS
  (
	SELECT 1
	FROM dbo.SEG_FLUJO_ACTOR_ASIGNACION ASIG
	WHERE ASIG.LOGIN_SISTEMA = PU.LOGIN_SISTEMA
	  AND ASIG.CORR_EMPRESA = GE.CORR_EMPRESA
	  AND ASIG.CORR_ACTOR = A.CORR_ACTOR
	  AND ASIG.CORR_UNIDAD = EP.CORR_UNIDAD
	  AND ASIG.ACTIVO = 1
  );
GO


/* ---- Views\dbo.V_SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES.sql ---- */
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- QuÃ© hace: jefes activos por unidad con nombre, login y puesto vigente.
-- CÃ³mo lo hace: SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES + GEN_EMPLEADO +
--               GEN_PERSONA_NATURAL / GEN_PERSONA_USUARIO + puesto mÃ¡s reciente.
CREATE OR ALTER VIEW [dbo].[V_SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES]
AS
SELECT
	J.CORR_EMPRESA,
	J.CORR_JEFE,
	J.CORR_UNIDAD,
	U.NOMBRE_UNIDAD,
	J.CORR_EMPLEADO,
	ISNULL(PN.NOMBRE_COMPLETO, N'') AS NOMBRE_EMPLEADO,
	PU.LOGIN_SISTEMA AS LOGIN_SISTEMA_WEB,
	J.FECHA_INICIO,
	J.FECHA_FIN,
	J.ACTIVO,
	EP.CORR_PUESTO,
	PP.NOMBRE_PUESTO
FROM dbo.SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES J
INNER JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES U
	ON U.CORR_UNIDAD = J.CORR_UNIDAD
   AND U.CORR_EMPRESA = J.CORR_EMPRESA
INNER JOIN dbo.GEN_EMPLEADO GE
	ON GE.CORR_EMPLEADO = J.CORR_EMPLEADO
   AND GE.CORR_EMPRESA = J.CORR_EMPRESA
LEFT JOIN dbo.GEN_PERSONA_NATURAL PN
	ON PN.CORR_PERSONA = GE.CORR_PERSONA
OUTER APPLY
(
	SELECT TOP (1) X.LOGIN_SISTEMA
	FROM dbo.GEN_PERSONA_USUARIO X
	WHERE X.CORR_PERSONA = GE.CORR_PERSONA
	ORDER BY X.LOGIN_SISTEMA
) PU
OUTER APPLY
(
	SELECT TOP (1) EPP.CORR_PUESTO
	FROM dbo.GEN_EMPLEADO_PUESTO EPP
	WHERE EPP.CORR_EMPRESA = J.CORR_EMPRESA
	  AND EPP.CORR_EMPLEADO = J.CORR_EMPLEADO
	ORDER BY
		EPP.FECHA_INGRESO DESC,
		EPP.FECHA_CREA DESC,
		EPP.CORR_PUESTO DESC
) EP
LEFT JOIN dbo.PLA_PUESTO PP
	ON PP.CORR_EMPRESA = J.CORR_EMPRESA
   AND PP.CORR_PUESTO = EP.CORR_PUESTO
WHERE J.ACTIVO = 1;
GO


/* ---- Views\dbo.V_CON_CENTRO_COSTO.sql ---- */
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: vista de lectura del mtto de centros de costo.
-- Cómo lo hace: proyecta CON_CENTRO_COSTO con tipo, estado, unidad, área, nivel y centro mayor.
CREATE OR ALTER VIEW [dbo].[V_CON_CENTRO_COSTO]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_CENTRO_COSTO,
	A.NOMBRE_CENTRO,
	ISNULL(A.CUENTA_CONTABLE, '') AS CUENTA_CONTABLE,
	CASE
		WHEN RTRIM(LTRIM(ISNULL(A.CODIGO_CENTRO_COSTO, ''))) = '' THEN CONVERT(VARCHAR(30), A.CORR_CENTRO_COSTO)
		ELSE ISNULL(A.CODIGO_CENTRO_COSTO, '')
	END AS CODIGO_CENTRO_COSTO,
	CAST(ISNULL(A.ES_DETALLE, 0) AS bit) AS ES_DETALLE,
	ISNULL(A.CORR_CENTRO_COSTO_MAYOR, 0) AS CORR_CENTRO_COSTO_MAYOR,
	ISNULL(M.NOMBRE_CENTRO, '') AS NOMBRE_CENTRO_COSTO_MAYOR,
	ISNULL(M.CODIGO_CENTRO_COSTO, '') AS CODIGO_CENTRO_COSTO_MAYOR,
	ISNULL(A.CORR_CENTRO_COSTO_NIVEL, 0) AS CORR_CENTRO_COSTO_NIVEL,
	ISNULL(N.NOMBRE_NIVEL, '') AS NOMBRE_NIVEL,
	ISNULL(N.NIVEL, 0) AS NIVEL,
	ISNULL(A.CORR_TIPO_CENTRO_COSTO, 0) AS CORR_TIPO_CENTRO_COSTO,
	ISNULL(C.NOMBRE_TIPO_CENTRO_COSTO, '') AS NOMBRE_TIPO_CENTRO_COSTO,
	ISNULL(C.CLASE_CENTRO_COSTO, 'CO') AS CLASE_CENTRO_COSTO,
	ISNULL(A.ESTADO_CENTRO_COSTO, '') AS ESTADO_CENTRO_COSTO,
	CAST(CASE WHEN ISNULL(A.ESTADO_CENTRO_COSTO, '') = 'AC' THEN 1 ELSE 0 END AS bit) AS ESTADO_CENTRO_COSTO_ACTIVO,
	CASE ISNULL(A.ESTADO_CENTRO_COSTO, '')
		WHEN 'AC' THEN 'Activo'
		WHEN 'IN' THEN 'Inactivo'
		ELSE ''
	END AS NOMBRE_ESTADO_CENTRO_COSTO,
	CASE
		WHEN A.CORR_CENTRO_COSTO = 0 THEN ''
		ELSE REPLICATE('0', CASE WHEN LEN(A.CORR_CENTRO_COSTO) <= 4 THEN 4 - LEN(A.CORR_CENTRO_COSTO) ELSE 0 END)
			+ CONVERT(VARCHAR(30), A.CORR_CENTRO_COSTO)
	END AS CORR_CENTRO_COSTO_REPLICADO,
	ISNULL(A.CORR_UNIDAD_NEGOCIO, 0) AS CORR_UNIDAD_NEGOCIO,
	ISNULL(D.NOMBRE_UNIDAD_NEGOCIO, '') AS NOMBRE_UNIDAD_NEGOCIO,
	CASE
		WHEN LEN(ISNULL(A.CODIGO_TERMINACION, '')) <= LEN(ISNULL(A.CODIGO_CENTRO_COSTO, ''))
			THEN SUBSTRING(A.CODIGO_CENTRO_COSTO, 1, LEN(A.CODIGO_CENTRO_COSTO) - LEN(A.CODIGO_TERMINACION))
		ELSE ''
	END AS CODIGO_UNIDAD_NEGOCIO,
	ISNULL(A.CORR_AREA_FUNCIONAL, 0) AS CORR_AREA_FUNCIONAL,
	ISNULL(E.NOMBRE_AREA_FUNCIONAL, '') AS NOMBRE_AREA_FUNCIONAL,
	ISNULL(A.CODIGO_TERMINACION, '') AS CODIGO_TERMINACION,
	ISNULL(A.CORR_EMPLEADO_JEFE, 0) AS CORR_EMPLEADO_JEFE,
	ISNULL(PN.NOMBRE_COMPLETO, '') AS NOMBRE_EMPLEADO,
	ISNULL(A.CORR_CLIENTE, 0) AS CORR_CLIENTE,
	A.FECHA_INICIAL,
	A.FECHA_FINAL
FROM dbo.CON_CENTRO_COSTO A
LEFT OUTER JOIN dbo.CON_TIPO_CENTRO_COSTO C
	ON A.CORR_EMPRESA = C.CORR_EMPRESA
	AND A.CORR_TIPO_CENTRO_COSTO = C.CORR_TIPO_CENTRO_COSTO
LEFT OUTER JOIN dbo.CON_UNIDAD_NEGOCIO D
	ON A.CORR_EMPRESA = D.CORR_EMPRESA
	AND A.CORR_UNIDAD_NEGOCIO = D.CORR_UNIDAD_NEGOCIO
LEFT OUTER JOIN dbo.CON_AREA_FUNCIONAL E
	ON A.CORR_EMPRESA = E.CORR_EMPRESA
	AND A.CORR_AREA_FUNCIONAL = E.CORR_AREA_FUNCIONAL
LEFT OUTER JOIN dbo.GEN_EMPLEADO F
	ON A.CORR_EMPRESA = F.CORR_EMPRESA
	AND A.CORR_EMPLEADO_JEFE = F.CORR_EMPLEADO
LEFT OUTER JOIN dbo.GEN_PERSONA_NATURAL PN
	ON PN.CORR_PERSONA = F.CORR_PERSONA
LEFT OUTER JOIN dbo.CON_CENTRO_COSTO_NIVEL N
	ON A.CORR_EMPRESA = N.CORR_EMPRESA
	AND A.CORR_CENTRO_COSTO_NIVEL = N.CORR_CENTRO_COSTO_NIVEL
LEFT OUTER JOIN dbo.CON_CENTRO_COSTO M
	ON A.CORR_EMPRESA = M.CORR_EMPRESA
	AND A.CORR_CENTRO_COSTO_MAYOR = M.CORR_CENTRO_COSTO
GO


/* ---- Views\dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_IMPR.sql ---- */
SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
-- =============================================================================
-- Vista: dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_IMPR
-- QuÃ© hace: encabezado del descriptor para impresiÃ³n Formato corto.
-- CÃ³mo: 1 fila por descriptor; fechas como texto dd/MM/yyyy; nombre del jefe
--       desde GEN_EMPLEADO + GEN_PERSONA_NATURAL. Funciones/KPIs en vistas _IMPR.
-- Uso: PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO (result set 1).
-- =============================================================================
CREATE OR ALTER VIEW [dbo].[V_SC_DESCRIPTOR_PUESTO_FORMATO_CORTO_IMPR]
AS
SELECT
  A.[CORR_EMPRESA],
  A.[CORR_DESCRIPTOR_PUESTO],
  -- CÃ³digo legible DES-#### sellado al crear el descriptor.
  A.[CODIGO_DESCRIPTOR_PUESTO],
  -- Fechas como texto dd/MM/yyyy: al pasar por DateTime de .NET, un DATE arrastra
  -- la hora 00:00:00 y Crystal la imprime. Formateadas aquÃ­ llegan limpias.
  CONVERT(VARCHAR(10), A.[FECHA_EMISION], 103) AS [FECHA_EMISION],
  CONVERT(VARCHAR(10), A.[FECHA_REVISION], 103) AS [FECHA_REVISION],
  A.[OBJETIVO_PUESTO],
  A.[NUM_PERSONAL_CARGO],
  A.[CORR_PUESTO],
  A.[NOMBRE_PUESTO],
  A.[CORR_UNIDAD],
  A.[NOMBRE_UNIDAD],
  A.[CORR_PUESTO_REPORTA],
  -- CORR_PUESTO_REPORTA guarda CORR_EMPLEADO del jefe (GEN_EMPLEADO).
  PN.[NOMBRE_COMPLETO] AS [NOMBRE_EMPLEADO_REPORTA],
  A.[CORR_IMPACTO_ECONOMICO],
  A.[DESCRIPCION_IMPACTO_ECONOMICO],
  A.[RESPONSABLE],
  A.[FORMATO],
  A.[VERSION],
  A.[CORR_ESTADO],
  A.[NOMBRE_ESTADO],
  A.[USUARIO_CREA],
  A.[ESTACION_CREA],
  A.[FECHA_CREA],
  A.[USUARIO_ACTU],
  A.[ESTACION_ACTU],
  A.[FECHA_ACTU]
FROM [dbo].[SC_DESCRIPTOR_PUESTO] A
LEFT JOIN [dbo].[GEN_EMPLEADO] E
  ON E.[CORR_EMPRESA] = A.[CORR_EMPRESA]
 AND E.[CORR_EMPLEADO] = A.[CORR_PUESTO_REPORTA]
LEFT JOIN [dbo].[GEN_PERSONA_NATURAL] PN
  ON PN.[CORR_PERSONA] = E.[CORR_PERSONA]
GO


/* ---- Views\dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_IMPR.sql ---- */
SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
-- =============================================================================
-- Vista: dbo.V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_IMPR
-- QuÃ© hace: encabezado del descriptor para impresiÃ³n Formato extenso.
-- CÃ³mo: 1 fila por descriptor; fechas como texto dd/MM/yyyy; nombre del jefe
--       desde GEN_EMPLEADO + GEN_PERSONA_NATURAL. Los demÃ¡s apartados en vistas _IMPR propias.
-- Uso: PRAL_IMPR_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO (result set 1).
-- =============================================================================
CREATE OR ALTER VIEW [dbo].[V_SC_DESCRIPTOR_PUESTO_FORMATO_EXTENSO_IMPR]
AS
SELECT
  A.[CORR_EMPRESA],
  A.[CORR_DESCRIPTOR_PUESTO],
  A.[CODIGO_DESCRIPTOR_PUESTO],
  CONVERT(VARCHAR(10), A.[FECHA_EMISION], 103) AS [FECHA_EMISION],
  CONVERT(VARCHAR(10), A.[FECHA_REVISION], 103) AS [FECHA_REVISION],
  A.[OBJETIVO_PUESTO],
  A.[NUM_PERSONAL_CARGO],
  A.[CORR_PUESTO],
  A.[NOMBRE_PUESTO],
  A.[CORR_UNIDAD],
  A.[NOMBRE_UNIDAD],
  A.[CORR_PUESTO_REPORTA],
  PN.[NOMBRE_COMPLETO] AS [NOMBRE_EMPLEADO_REPORTA],
  A.[CORR_IMPACTO_ECONOMICO],
  A.[DESCRIPCION_IMPACTO_ECONOMICO],
  A.[RESPONSABLE],
  A.[FORMATO],
  A.[VERSION],
  A.[CORR_ESTADO],
  A.[NOMBRE_ESTADO],
  A.[USUARIO_CREA],
  A.[ESTACION_CREA],
  A.[FECHA_CREA],
  A.[USUARIO_ACTU],
  A.[ESTACION_ACTU],
  A.[FECHA_ACTU]
FROM [dbo].[SC_DESCRIPTOR_PUESTO] A
LEFT JOIN [dbo].[GEN_EMPLEADO] E
  ON E.[CORR_EMPRESA] = A.[CORR_EMPRESA]
 AND E.[CORR_EMPLEADO] = A.[CORR_PUESTO_REPORTA]
LEFT JOIN [dbo].[GEN_PERSONA_NATURAL] PN
  ON PN.[CORR_PERSONA] = E.[CORR_PERSONA]
GO


/* ---- Programmability\Functions\dbo.SEG_FN_ObtenerLoginPorCodigoEmpleado.sql ---- */
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- QuÃ© hace: obtiene LOGIN del empleado activo por CORR_EMPLEADO.
-- CÃ³mo lo hace: GEN_EMPLEADO (ACTIVO) + GEN_PERSONA_USUARIO.
CREATE OR ALTER FUNCTION dbo.SEG_FN_ObtenerLoginPorCodigoEmpleado
(
	@CORR_EMPLEADO INT
)
RETURNS VARCHAR(30)
AS
BEGIN
	DECLARE @Login VARCHAR(30);

	SELECT TOP (1) @Login = PU.LOGIN_SISTEMA
	FROM dbo.GEN_EMPLEADO E
	INNER JOIN dbo.GEN_PERSONA_USUARIO PU
		ON PU.CORR_PERSONA = E.CORR_PERSONA
	WHERE E.CORR_EMPLEADO = @CORR_EMPLEADO
	  AND ISNULL(E.ACTIVO_EMPLEADO, 0) = 1
	ORDER BY PU.LOGIN_SISTEMA;

	RETURN @Login;
END
GO


/* ---- Programmability\Functions\dbo.SEG_FN_ObtenerJefeDeUnidad.sql ---- */
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- QuÃ© hace: LOGIN del jefe activo mÃ¡s reciente de una unidad.
-- CÃ³mo lo hace: jefes de organigrama + empleado activo + GEN_PERSONA_USUARIO.
CREATE OR ALTER FUNCTION dbo.SEG_FN_ObtenerJefeDeUnidad
(
	@CORR_UNIDAD INT
)
RETURNS VARCHAR(30)
AS
BEGIN
	DECLARE @Login VARCHAR(30);

	SELECT TOP (1) @Login = PU.LOGIN_SISTEMA
	FROM dbo.SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES J
	INNER JOIN dbo.GEN_EMPLEADO GE
		ON GE.CORR_EMPLEADO = J.CORR_EMPLEADO
	   AND GE.CORR_EMPRESA = J.CORR_EMPRESA
	INNER JOIN dbo.GEN_PERSONA_USUARIO PU
		ON PU.CORR_PERSONA = GE.CORR_PERSONA
	WHERE J.CORR_UNIDAD = @CORR_UNIDAD
	  AND J.ACTIVO = 1
	  AND (J.FECHA_FIN IS NULL OR J.FECHA_FIN >= CAST(GETDATE() AS DATE))
	  AND ISNULL(GE.ACTIVO_EMPLEADO, 0) = 1
	ORDER BY J.FECHA_INICIO DESC, PU.LOGIN_SISTEMA;

	RETURN @Login;
END
GO


/* ---- Programmability\Functions\dbo.SEG_FN_ObtenerJefesDeUnidad.sql ---- */
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- QuÃ© hace: todos los logins de jefes activos de una unidad (multi-actor).
-- CÃ³mo lo hace: misma regla que SEG_FN_ObtenerJefeDeUnidad, en forma tabular.
CREATE OR ALTER FUNCTION dbo.SEG_FN_ObtenerJefesDeUnidad
(
	@CORR_UNIDAD INT
)
RETURNS TABLE
AS
RETURN
(
	SELECT PU.LOGIN_SISTEMA AS LoginDestino
	FROM dbo.SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES J
	INNER JOIN dbo.GEN_EMPLEADO GE
		ON GE.CORR_EMPLEADO = J.CORR_EMPLEADO
	   AND GE.CORR_EMPRESA = J.CORR_EMPRESA
	INNER JOIN dbo.GEN_PERSONA_USUARIO PU
		ON PU.CORR_PERSONA = GE.CORR_PERSONA
	WHERE J.CORR_UNIDAD = @CORR_UNIDAD
	  AND J.ACTIVO = 1
	  AND (J.FECHA_FIN IS NULL OR J.FECHA_FIN >= CAST(GETDATE() AS DATE))
	  AND ISNULL(GE.ACTIVO_EMPLEADO, 0) = 1
);
GO


/* ---- Programmability\Procedures\dbo.PRAL_DATA_SC_UNIDADES_USUARIO.sql ---- */
SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
-- =============================================================================
-- QuÃ© hace: Devuelve las unidades del usuario por empresa (sin duplicar
--   unidad+puesto) a partir de:
--   1) Unidades y puesto en GEN_EMPLEADO_PUESTO (CORR_UNIDAD + CORR_PUESTO).
--   2) Unidades donde es jefe activo (SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES).
--   3) Unidades configuradas en SC_UNIDADES_USUARIO.
-- CÃ³mo lo hace: Filtra por @CORR_EMPRESA y @LOGIN_SISTEMA, resuelve el empleado
--   vÃ­a GEN_PERSONA_USUARIO (login ya no vive en GEN_EMPLEADO), une las tres
--   fuentes con UNION y enriquece con organigrama y PLA_PUESTO.
--   Si tiene puesto en esa unidad: muestra CORR_PUESTO y NOMBRE_PUESTO.
--   Si solo es jefe o configurada: CORR_PUESTO NULL y NOMBRE_PUESTO =
--   'No lo tiene por puesto de trabajo'.
-- Nota: No ejecutar CREATE en el servidor desde el agente; el DBA lo aplica.
-- =============================================================================
CREATE OR ALTER PROCEDURE [dbo].[PRAL_DATA_SC_UNIDADES_USUARIO]
(
	@CORR_EMPRESA INT,
	@LOGIN_SISTEMA VARCHAR(30)
)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @LOGIN VARCHAR(30) = LTRIM(RTRIM(@LOGIN_SISTEMA));
	DECLARE @MSG_SIN_PUESTO VARCHAR(80) = 'No lo tiene por puesto de trabajo';

	;WITH EmpleadoLogin AS
	(
		-- QuÃ© hace: localiza al empleado asociado al login en la empresa.
		-- CÃ³mo: GEN_EMPLEADO + GEN_PERSONA_USUARIO por LOGIN_SISTEMA.
		SELECT
			E.CORR_EMPRESA,
			E.CORR_EMPLEADO
		FROM dbo.GEN_EMPLEADO E
		INNER JOIN dbo.GEN_PERSONA_USUARIO PU
			ON PU.CORR_PERSONA = E.CORR_PERSONA
		WHERE E.CORR_EMPRESA = @CORR_EMPRESA
		  AND LTRIM(RTRIM(PU.LOGIN_SISTEMA)) = @LOGIN
	),
	UnidadesPorPuesto AS
	(
		-- QuÃ© hace: unidades y puesto donde el empleado trabaja.
		-- CÃ³mo: lee CORR_UNIDAD y CORR_PUESTO de GEN_EMPLEADO_PUESTO
		--       (ya no hay ESTADO_EMPLEADO_PUESTO).
		SELECT DISTINCT
			EP.CORR_EMPRESA,
			EP.CORR_UNIDAD,
			EP.CORR_PUESTO
		FROM dbo.GEN_EMPLEADO_PUESTO EP
		INNER JOIN EmpleadoLogin EL
			ON EL.CORR_EMPRESA = EP.CORR_EMPRESA
		   AND EL.CORR_EMPLEADO = EP.CORR_EMPLEADO
		WHERE EP.CORR_EMPRESA = @CORR_EMPRESA
	),
	UnidadesComoJefe AS
	(
		-- QuÃ© hace: unidades donde el empleado es jefe activo.
		-- CÃ³mo: SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES con ACTIVO = 1.
		--       Ejemplo: Coordinador de Desarrollo que ademÃ¡s es jefe de Subgerencia
		--       ve Subgerencia aunque su puesto no estÃ© ahÃ­.
		SELECT DISTINCT
			JU.CORR_EMPRESA,
			JU.CORR_UNIDAD
		FROM dbo.SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES JU
		INNER JOIN EmpleadoLogin EL
			ON EL.CORR_EMPRESA = JU.CORR_EMPRESA
		   AND EL.CORR_EMPLEADO = JU.CORR_EMPLEADO
		WHERE JU.CORR_EMPRESA = @CORR_EMPRESA
		  AND JU.ACTIVO = CONVERT(BIT, 1)
	),
	UnidadesConfiguradas AS
	(
		-- QuÃ© hace: unidades configuradas manualmente al usuario en la empresa.
		-- CÃ³mo: lee SC_UNIDADES_USUARIO por CORR_EMPRESA + LOGIN_SISTEMA.
		SELECT DISTINCT
			SU.CORR_EMPRESA,
			SU.CORR_UNIDAD
		FROM dbo.SC_UNIDADES_USUARIO SU
		WHERE SU.CORR_EMPRESA = @CORR_EMPRESA
		  AND LTRIM(RTRIM(SU.LOGIN_SISTEMA)) = @LOGIN
	),
	UnidadesUnion AS
	(
		-- QuÃ© hace: une las tres fuentes sin repetir unidad+puesto.
		-- CÃ³mo: filas de puesto traen CORR_PUESTO; jefe/config sin puesto en esa
		--       unidad salen con NULL. UNION elimina duplicados.
		SELECT CORR_EMPRESA, CORR_UNIDAD, CORR_PUESTO
		FROM UnidadesPorPuesto

		UNION

		SELECT J.CORR_EMPRESA, J.CORR_UNIDAD, CONVERT(INT, NULL)
		FROM UnidadesComoJefe J
		WHERE NOT EXISTS
		(
			SELECT 1
			FROM UnidadesPorPuesto P
			WHERE P.CORR_EMPRESA = J.CORR_EMPRESA
			  AND P.CORR_UNIDAD = J.CORR_UNIDAD
		)

		UNION

		SELECT C.CORR_EMPRESA, C.CORR_UNIDAD, CONVERT(INT, NULL)
		FROM UnidadesConfiguradas C
		WHERE NOT EXISTS
		(
			SELECT 1
			FROM UnidadesPorPuesto P
			WHERE P.CORR_EMPRESA = C.CORR_EMPRESA
			  AND P.CORR_UNIDAD = C.CORR_UNIDAD
		)
	)
	SELECT
		U.CORR_EMPRESA,
		U.CORR_UNIDAD,
		O.CODIGO_UNIDAD,
		O.NOMBRE_UNIDAD,
		U.CORR_PUESTO,
		CASE
			WHEN U.CORR_PUESTO IS NULL THEN @MSG_SIN_PUESTO
			ELSE ISNULL(P.NOMBRE_PUESTO, @MSG_SIN_PUESTO)
		END AS NOMBRE_PUESTO,
		@LOGIN AS LOGIN_SISTEMA,
		CONVERT(BIT, CASE WHEN U.CORR_PUESTO IS NOT NULL THEN 1 ELSE 0 END) AS ES_POR_PUESTO,
		CONVERT(BIT, CASE WHEN JF.CORR_UNIDAD IS NOT NULL THEN 1 ELSE 0 END) AS ES_JEFE_UNIDAD,
		CONVERT(BIT, CASE WHEN CF.CORR_UNIDAD IS NOT NULL THEN 1 ELSE 0 END) AS ES_CONFIGURADA
	FROM UnidadesUnion U
	LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES O
		ON O.CORR_EMPRESA = U.CORR_EMPRESA
	   AND O.CORR_UNIDAD = U.CORR_UNIDAD
	LEFT JOIN dbo.PLA_PUESTO P
		ON P.CORR_EMPRESA = U.CORR_EMPRESA
	   AND P.CORR_PUESTO = U.CORR_PUESTO
	LEFT JOIN UnidadesComoJefe JF
		ON JF.CORR_EMPRESA = U.CORR_EMPRESA
	   AND JF.CORR_UNIDAD = U.CORR_UNIDAD
	LEFT JOIN UnidadesConfiguradas CF
		ON CF.CORR_EMPRESA = U.CORR_EMPRESA
	   AND CF.CORR_UNIDAD = U.CORR_UNIDAD
	ORDER BY U.CORR_EMPRESA, O.CODIGO_UNIDAD, U.CORR_UNIDAD, U.CORR_PUESTO;
END
GO

/*
================================================================================
EJEMPLOS DE PRUEBA
================================================================================

-- Cesar Lopez (CORR_EMPLEADO=4): puesto en unidad 5 + jefe activo en 5 y 6
-- + config SC 1..8 â†’ 1..8 una vez; unidad 5 con NOMBRE_PUESTO real;
-- unidades solo jefe/config con NOMBRE_PUESTO = 'No lo tiene por puesto de trabajo'
EXEC dbo.PRAL_DATA_SC_UNIDADES_USUARIO
	@CORR_EMPRESA = 1,
	@LOGIN_SISTEMA = 'cesar.lopez';

-- Daniel Palacios: por puesto y/o jefe activo (sin SC_UNIDADES_USUARIO)
EXEC dbo.PRAL_DATA_SC_UNIDADES_USUARIO
	@CORR_EMPRESA = 1,
	@LOGIN_SISTEMA = 'dpalacios';

-- Solo configuraciÃ³n â†’ todas las filas con el mensaje (no tiene puesto ahÃ­)
EXEC dbo.PRAL_DATA_SC_UNIDADES_USUARIO
	@CORR_EMPRESA = 1,
	@LOGIN_SISTEMA = 'alexanderr';
*/

