/*
  Despliega vistas del módulo Banco (tablas generales).
  Uso:
    cd "c:\Desarrollo GIT\SGUEES\SGUEES-DB\Scripts"
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -i DEPLOY_BAN_VIEWS.sql
*/
SET NOCOUNT ON;
GO

IF OBJECT_ID('dbo.V_GEN_BANCO', 'V') IS NOT NULL DROP VIEW dbo.V_GEN_BANCO;
GO
:r ..\Views\dbo.V_GEN_BANCO.sql
GO

IF OBJECT_ID('dbo.V_BAN_LINEA_TRABAJO_CONCILIACION', 'V') IS NOT NULL DROP VIEW dbo.V_BAN_LINEA_TRABAJO_CONCILIACION;
GO
:r ..\Views\dbo.V_BAN_LINEA_TRABAJO_CONCILIACION.sql
GO

IF OBJECT_ID('dbo.V_BAN_TIPO_CHEQUE', 'V') IS NOT NULL DROP VIEW dbo.V_BAN_TIPO_CHEQUE;
GO
:r ..\Views\dbo.V_BAN_TIPO_CHEQUE.sql
GO

IF OBJECT_ID('dbo.V_BAN_TIPO_MOVI_BANCARIO', 'V') IS NOT NULL DROP VIEW dbo.V_BAN_TIPO_MOVI_BANCARIO;
GO
:r ..\Views\dbo.V_BAN_TIPO_MOVI_BANCARIO.sql
GO

IF OBJECT_ID('dbo.V_BAN_CUENTA_BANCARIA', 'V') IS NOT NULL DROP VIEW dbo.V_BAN_CUENTA_BANCARIA;
GO
:r ..\Views\dbo.V_BAN_CUENTA_BANCARIA.sql
GO

SELECT name FROM sys.views WHERE name LIKE 'V_%BAN%' OR name = 'V_GEN_BANCO' ORDER BY 1;
GO
