/* Deploy idempotente — BAN_SOLI_CHEQUE + BAN_SOLI_CHEQUE_DETA (SGUEES, sin suscripción/país) */
SET NOCOUNT ON;

/* ── Tabla encabezado ── */
IF OBJECT_ID(N'dbo.BAN_SOLI_CHEQUE', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BAN_SOLI_CHEQUE]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[ANIO_PERIODO] [int] NOT NULL,
		[MES_PERIODO] [int] NOT NULL,
		[CORR_TIPO_MOVIMIENTO] [int] NOT NULL,
		[CORR_DOCUMENTO] [int] NOT NULL,
		[CORR_CUENTA_BANCO] [int] NULL,
		[NUMERO_DOCUMENTO] [bigint] NOT NULL CONSTRAINT [DF_BAN_SOLI_CHEQUE_NUMERO] DEFAULT ((0)),
		[FECHA_EMISION] [date] NOT NULL,
		[NOMBRE_PARTIDA] [varchar](1000) COLLATE Latin1_General_CS_AS NOT NULL,
		[CORR_PROVEEDOR] [int] NULL,
		[CORR_EMPLEADO] [int] NULL,
		[CORR_CLIENTE] [int] NULL,
		[NOMBRE_BENEFICIARIO] [varchar](255) COLLATE Latin1_General_CS_AS NULL,
		[MONTO_DOCUMENTO] [decimal](18, 2) NOT NULL CONSTRAINT [DF_BAN_SOLI_CHEQUE_MONTO] DEFAULT ((0)),
		[ESTADO_DOCUMENTO] [varchar](2) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_BAN_SOLI_CHEQUE_ESTADO] DEFAULT ('DI'),
		[SOLICITADO_POR] [varchar](30) COLLATE Latin1_General_CS_AS NULL,
		[FECHA_SOLICITADO] [date] NULL,
		[APLICADO_POR] [varchar](30) COLLATE Latin1_General_CS_AS NULL,
		[FECHA_APLICADO] [date] NULL,
		[CANTIDAD_LETRAS] [varchar](255) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_BAN_SOLI_CHEQUE_LETRAS] DEFAULT (''),
		[USUARIO_CREA] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
		[FECHA_CREA] [datetime] NOT NULL,
		[ESTACION_CREA] [varchar](50) COLLATE Latin1_General_CS_AS NOT NULL,
		[USUARIO_ACTU] [varchar](30) COLLATE Latin1_General_CS_AS NULL,
		[FECHA_ACTU] [datetime] NULL,
		[ESTACION_ACTU] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
		[CORR_TIPO_CHEQUE] [int] NULL,
		[ANIO_PERIODO_CHEQUE] [int] NULL,
		[MES_PERIODO_CHEQUE] [int] NULL,
		[CORR_TIPO_MOVIMIENTO_CHEQUE] [int] NULL,
		[CORR_DOCUMENTO_CHEQUE] [int] NULL,
		[CORR_MONEDA] [int] NULL,
		[FACTOR_CAMBIO] [decimal](16, 6) NULL CONSTRAINT [DF_BAN_SOLI_CHEQUE_FC] DEFAULT ((1)),
		[OPERADOR] [varchar](2) COLLATE Latin1_General_CS_AS NULL CONSTRAINT [DF_BAN_SOLI_CHEQUE_OP] DEFAULT ('*')
	) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_SOLI_CHEQUE]
		ADD CONSTRAINT [PK_BAN_SOLI_CHEQUE]
		PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO]) ON [PRIMARY];
END
GO

IF OBJECT_ID(N'dbo.BAN_DOCUMENTO', N'U') IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_BAN_SOLI_CHEQUE_BAN_DOCUMENTO')
BEGIN
	ALTER TABLE [dbo].[BAN_SOLI_CHEQUE]
		ADD CONSTRAINT [FK_BAN_SOLI_CHEQUE_BAN_DOCUMENTO]
		FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO_CHEQUE], [MES_PERIODO_CHEQUE], [CORR_TIPO_MOVIMIENTO_CHEQUE], [CORR_DOCUMENTO_CHEQUE])
		REFERENCES [dbo].[BAN_DOCUMENTO] ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO]);
END
GO

/* ── Tabla detalle ── */
IF OBJECT_ID(N'dbo.BAN_SOLI_CHEQUE_DETA', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BAN_SOLI_CHEQUE_DETA]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[ANIO_PERIODO] [int] NOT NULL,
		[MES_PERIODO] [int] NOT NULL,
		[CORR_TIPO_MOVIMIENTO] [int] NOT NULL,
		[CORR_DOCUMENTO] [int] NOT NULL,
		[CORR_DOCUMENTO_DETA] [int] NOT NULL,
		[CUENTA_CONTABLE] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
		[CORR_CENTRO_COSTO] [int] NULL,
		[NOMBRE_TRAN] [varchar](1255) COLLATE Latin1_General_CS_AS NOT NULL,
		[MONTO_CARGO] [decimal](12, 2) NOT NULL CONSTRAINT [DF_BAN_SOLI_DETA_CARGO] DEFAULT ((0)),
		[MONTO_ABONO] [decimal](12, 2) NOT NULL CONSTRAINT [DF_BAN_SOLI_DETA_ABONO] DEFAULT ((0))
	) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_SOLI_CHEQUE_DETA]
		ADD CONSTRAINT [PK_BAN_SOLI_CHEQUE_DETA]
		PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO], [CORR_DOCUMENTO_DETA]) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_SOLI_CHEQUE_DETA]
		ADD CONSTRAINT [FK_BAN_SOLI_CHEQUE_DETA_BAN_SOLI_CHEQUE]
		FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO])
		REFERENCES [dbo].[BAN_SOLI_CHEQUE] ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO]);
END
GO

/* ── Vista encabezado (joins opcionales GEN_* según existan al desplegar) ── */
IF OBJECT_ID(N'dbo.V_BAN_SOLI_CHEQUE', N'V') IS NOT NULL
	DROP VIEW [dbo].[V_BAN_SOLI_CHEQUE];
GO

DECLARE @SqlViewSoli NVARCHAR(MAX);
DECLARE @JoinProveedor NVARCHAR(500) = N'';
DECLARE @JoinEmpleado NVARCHAR(500) = N'';
DECLARE @JoinCliente NVARCHAR(500) = N'';
DECLARE @JoinMoneda NVARCHAR(500) = N'';
DECLARE @ExprNombreProveedor NVARCHAR(1000) = N'ISNULL(A.NOMBRE_BENEFICIARIO, N'''')';
DECLARE @ExprNombreMoneda NVARCHAR(200) = N'N''''';
DECLARE @ExprSimbolo NVARCHAR(200) = N'N''''';

IF OBJECT_ID(N'dbo.GEN_PROVEEDOR', N'U') IS NOT NULL
	SET @JoinProveedor = N'
LEFT JOIN dbo.GEN_PROVEEDOR D
	ON A.CORR_EMPRESA = D.CORR_EMPRESA AND A.CORR_PROVEEDOR = D.CORR_PROVEEDOR';

IF OBJECT_ID(N'dbo.GEN_EMPLEADO', N'U') IS NOT NULL
	SET @JoinEmpleado = N'
LEFT JOIN dbo.GEN_EMPLEADO G
	ON A.CORR_EMPRESA = G.CORR_EMPRESA AND A.CORR_EMPLEADO = G.CORR_EMPLEADO';

IF OBJECT_ID(N'dbo.GEN_CLIENTE', N'U') IS NOT NULL
	SET @JoinCliente = N'
LEFT JOIN dbo.GEN_CLIENTE H
	ON A.CORR_EMPRESA = H.CORR_EMPRESA AND A.CORR_CLIENTE = H.CORR_CLIENTE';

IF OBJECT_ID(N'dbo.GEN_TIPO_MONEDA', N'U') IS NOT NULL
BEGIN
	SET @JoinMoneda = N'
LEFT JOIN dbo.GEN_TIPO_MONEDA I
	ON A.CORR_MONEDA = I.CORR_MONEDA';
	SET @ExprNombreMoneda = N'ISNULL(I.NOMBRE_MONEDA, N'''')';
	SET @ExprSimbolo = N'ISNULL(I.SIMBOLO, N'''')';
END

IF @JoinProveedor <> N'' OR @JoinEmpleado <> N'' OR @JoinCliente <> N''
BEGIN
	SET @ExprNombreProveedor = N'ISNULL('
		+ CASE WHEN @JoinProveedor <> N'' THEN N'D.NOMBRE_PROVEEDOR' ELSE N'NULL' END + N', ISNULL('
		+ CASE WHEN @JoinEmpleado <> N'' THEN N'G.NOMBRE_EMPLEADO' ELSE N'NULL' END + N', ISNULL('
		+ CASE WHEN @JoinCliente <> N'' THEN N'H.NOMBRE_CLIENTE' ELSE N'NULL' END + N', ISNULL(A.NOMBRE_BENEFICIARIO, N''''))))';
END

SET @SqlViewSoli = N'
CREATE VIEW [dbo].[V_BAN_SOLI_CHEQUE]
AS
SELECT
	A.CORR_EMPRESA,
	A.ANIO_PERIODO,
	A.MES_PERIODO,
	A.CORR_TIPO_MOVIMIENTO,
	B.NOMBRE_TIPO_MOVIMIENTO,
	A.CORR_DOCUMENTO,
	ISNULL(A.CORR_CUENTA_BANCO, 0) CORR_CUENTA_BANCO,
	ISNULL(C.NOMBRE_CUENTA_BANCO, N'''') NOMBRE_CUENTA_BANCO,
	ISNULL(C.NUMERO_CUENTA_BANCO, N'''') NUMERO_CUENTA_BANCO,
	A.NUMERO_DOCUMENTO,
	A.FECHA_EMISION,
	A.NOMBRE_PARTIDA,
	ISNULL(A.CORR_PROVEEDOR, 0) CORR_PROVEEDOR,
	' + @ExprNombreProveedor + N' AS NOMBRE_PROVEEDOR,
	ISNULL(A.CORR_EMPLEADO, 0) CORR_EMPLEADO,
	ISNULL(A.CORR_CLIENTE, 0) CORR_CLIENTE,
	A.NOMBRE_BENEFICIARIO,
	A.MONTO_DOCUMENTO,
	A.ESTADO_DOCUMENTO,
	CASE A.ESTADO_DOCUMENTO
		WHEN ''DI'' THEN N''Digitado''
		WHEN ''SO'' THEN N''Solicitado''
		WHEN ''AP'' THEN N''Aplicado''
		WHEN ''EM'' THEN N''Emitido''
		ELSE N''''
	END AS NOMBRE_ESTADO_DOCUMENTO,
	A.SOLICITADO_POR,
	A.FECHA_SOLICITADO,
	A.APLICADO_POR,
	A.FECHA_APLICADO,
	A.CANTIDAD_LETRAS,
	A.USUARIO_CREA,
	A.FECHA_CREA,
	A.ESTACION_CREA,
	A.USUARIO_ACTU,
	A.FECHA_ACTU,
	A.ESTACION_ACTU,
	ISNULL(A.CORR_TIPO_CHEQUE, 0) CORR_TIPO_CHEQUE,
	ISNULL(E.NOMBRE_TIPO_CHEQUE, N'''') NOMBRE_TIPO_CHEQUE,
	ISNULL(E.CLASE_TIPO_CHEQUE, N'''') CLASE_TIPO_CHEQUE,
	A.ANIO_PERIODO_CHEQUE,
	A.MES_PERIODO_CHEQUE,
	A.CORR_TIPO_MOVIMIENTO_CHEQUE,
	A.CORR_DOCUMENTO_CHEQUE,
	ISNULL(A.CORR_MONEDA, 0) CORR_MONEDA,
	' + @ExprNombreMoneda + N' NOMBRE_MONEDA,
	' + @ExprSimbolo + N' SIMBOLO,
	ISNULL(A.FACTOR_CAMBIO, 1) FACTOR_CAMBIO,
	ISNULL(A.OPERADOR, ''*'') OPERADOR
FROM dbo.BAN_SOLI_CHEQUE A
INNER JOIN dbo.BAN_TIPO_MOVI_BANCARIO B
	ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO
LEFT JOIN dbo.V_BAN_CUENTA_BANCARIA C
	ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CORR_CUENTA_BANCO = C.CORR_CUENTA_BANCO
LEFT JOIN dbo.V_BAN_TIPO_CHEQUE E
	ON A.CORR_EMPRESA = E.CORR_EMPRESA AND A.CORR_TIPO_CHEQUE = E.CORR_TIPO_CHEQUE'
	+ @JoinProveedor + @JoinEmpleado + @JoinCliente + @JoinMoneda + N';';

EXEC sp_executesql @SqlViewSoli;
GO

/* ── Vista detalle ── */
IF OBJECT_ID(N'dbo.V_BAN_SOLI_CHEQUE_DETA', N'V') IS NOT NULL
	DROP VIEW [dbo].[V_BAN_SOLI_CHEQUE_DETA];
GO

CREATE VIEW [dbo].[V_BAN_SOLI_CHEQUE_DETA]
AS
SELECT
	A.CORR_EMPRESA,
	A.ANIO_PERIODO,
	A.MES_PERIODO,
	A.CORR_TIPO_MOVIMIENTO,
	A.CORR_DOCUMENTO,
	A.CORR_DOCUMENTO_DETA,
	A.CUENTA_CONTABLE,
	ISNULL(C.NOMBRE_CUENTA, '') NOMBRE_CUENTA,
	ISNULL(A.CORR_CENTRO_COSTO, 0) CORR_CENTRO_COSTO,
	ISNULL(D.NOMBRE_CENTRO, '') NOMBRE_CENTRO,
	A.NOMBRE_TRAN,
	A.MONTO_CARGO,
	A.MONTO_ABONO
FROM dbo.BAN_SOLI_CHEQUE_DETA A
LEFT JOIN dbo.CON_CATALOGO_CUENTA C
	ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CUENTA_CONTABLE = C.CUENTA_CONTABLE
LEFT JOIN dbo.CON_CENTRO_COSTO D
	ON A.CORR_EMPRESA = D.CORR_EMPRESA AND A.CORR_CENTRO_COSTO = D.CORR_CENTRO_COSTO;
GO

/* ── MTTO encabezado ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_SOLI_CHEQUE', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT OUTPUT,
	@CORR_CUENTA_BANCO INT = NULL,
	@NUMERO_DOCUMENTO BIGINT = NULL,
	@FECHA_EMISION DATE = NULL,
	@NOMBRE_PARTIDA VARCHAR(1000) = '',
	@CORR_PROVEEDOR INT = NULL,
	@CORR_CLIENTE INT = NULL,
	@CORR_EMPLEADO INT = NULL,
	@NOMBRE_BENEFICIARIO VARCHAR(255) = '',
	@MONTO_DOCUMENTO DECIMAL(18, 2) = 0,
	@ESTADO_DOCUMENTO VARCHAR(2) = 'DI',
	@SOLICITADO_POR VARCHAR(30) = '',
	@FECHA_SOLICITADO DATE = NULL,
	@FECHA_APLICADO DATE = NULL,
	@CANTIDAD_LETRAS VARCHAR(255) = NULL,
	@USUARIO_CREA VARCHAR(30),
	@FECHA_CREA DATETIME,
	@ESTACION_CREA VARCHAR(50),
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@CORR_TIPO_CHEQUE INT = NULL,
	@ANIO_PERIODO_CHEQUE INT = NULL,
	@MES_PERIODO_CHEQUE INT = NULL,
	@CORR_TIPO_MOVIMIENTO_CHEQUE INT = NULL,
	@CORR_DOCUMENTO_CHEQUE INT = NULL,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT,
	@GENERA_DETALLE BIT = 1,
	@CORR_MONEDA INT = NULL,
	@FACTOR_CAMBIO DECIMAL(16, 6) = 1,
	@OPERADOR VARCHAR(2) = '*'
)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @CLASE_TIPO_CHEQUE VARCHAR(3);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1, 2)
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM dbo.CON_PERIODO_CONTABLE
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No existe el periodo contable seleccionado', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF NOT EXISTS (
				SELECT 1 FROM dbo.CON_PERIODO_CONTABLE
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
					AND ISNULL(ESTADO_PERIODO_BAN, 'AB') = 'AB'
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El periodo bancario no está abierto', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF NOT EXISTS (
				SELECT 1 FROM dbo.BAN_TIPO_MOVI_BANCARIO
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No ha seleccionado correctamente el tipo de movimiento bancario', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF @CORR_CUENTA_BANCO IS NULL OR NOT EXISTS (
				SELECT 1 FROM dbo.BAN_CUENTA_BANCARIA
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO
			)
			BEGIN
				SELECT @CORR_CUENTA_BANCO = NULL, @GENERA_DETALLE = 0;
			END;

			IF LTRIM(RTRIM(ISNULL(@NOMBRE_PARTIDA, ''))) = ''
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Debe especificar un concepto para el documento a emitir', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF ISNULL(@MONTO_DOCUMENTO, 0) < 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El monto del documento no puede ser menor que cero', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			SELECT @ANIO_PERIODO_CHEQUE = NULL, @MES_PERIODO_CHEQUE = NULL, @CORR_TIPO_MOVIMIENTO_CHEQUE = NULL, @CORR_DOCUMENTO_CHEQUE = NULL;

			DECLARE @NOMBRE_MONEDA VARCHAR(100) = N'DÓLARES';
			IF OBJECT_ID(N'dbo.GEN_TIPO_MONEDA', N'U') IS NOT NULL
			BEGIN
				SELECT @NOMBRE_MONEDA = ISNULL(M.NOMBRE_MONEDA, @NOMBRE_MONEDA)
				FROM dbo.GEN_TIPO_MONEDA M
				WHERE M.CORR_MONEDA = ISNULL(@CORR_MONEDA, 0);
			END;

			DECLARE @sFraccion VARCHAR(15) = '00' + LTRIM(CAST(CAST(((@MONTO_DOCUMENTO - CAST(@MONTO_DOCUMENTO AS INT)) * 100) AS INT) AS VARCHAR(15)));
			SELECT @CANTIDAD_LETRAS = dbo.FN_NUMEROS_A_LETRAS(@MONTO_DOCUMENTO, 1) + N' ' + @NOMBRE_MONEDA
				+ N' CON ' + SUBSTRING(@sFraccion, LEN(@sFraccion) - 1, 2) + N'/100';

			IF NOT EXISTS (
				SELECT 1 FROM dbo.BAN_TIPO_CHEQUE
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_CHEQUE = @CORR_TIPO_CHEQUE
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No ha seleccionado correctamente el tipo de cheque', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			SELECT @CLASE_TIPO_CHEQUE = ISNULL(CLASE_TIPO_CHEQUE, 'OT')
			FROM dbo.BAN_TIPO_CHEQUE
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_CHEQUE = @CORR_TIPO_CHEQUE;

			IF OBJECT_ID(N'dbo.GEN_PROVEEDOR', N'U') IS NOT NULL
				AND NOT EXISTS (
					SELECT 1 FROM dbo.GEN_PROVEEDOR
					WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_PROVEEDOR = @CORR_PROVEEDOR
				) AND @CLASE_TIPO_CHEQUE IN ('PR', 'OT')
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No ha seleccionado correctamente el proveedor', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF OBJECT_ID(N'dbo.GEN_EMPLEADO', N'U') IS NOT NULL
				AND NOT EXISTS (
					SELECT 1 FROM dbo.GEN_EMPLEADO
					WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_EMPLEADO = @CORR_EMPLEADO
				) AND @CLASE_TIPO_CHEQUE IN ('EM')
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No ha seleccionado correctamente el empleado', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF OBJECT_ID(N'dbo.GEN_CLIENTE', N'U') IS NOT NULL
				AND NOT EXISTS (
					SELECT 1 FROM dbo.GEN_CLIENTE
					WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CLIENTE = @CORR_CLIENTE
				) AND @CLASE_TIPO_CHEQUE IN ('CL')
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No ha seleccionado correctamente el cliente', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		IF @TIPO_ACTUALIZA IN (2, 3)
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM dbo.BAN_SOLI_CHEQUE
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
					AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
					AND ESTADO_DOCUMENTO = 'DI'
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'La solicitud no puede modificarse o eliminarse (estado distinto de Digitado)', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		IF @TIPO_ACTUALIZA = 1
		BEGIN
			SELECT @CORR_DOCUMENTO = ISNULL(MAX(CORR_DOCUMENTO), 0) + 1, @ESTADO_DOCUMENTO = 'DI'
			FROM dbo.BAN_SOLI_CHEQUE
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO;

			SET @FECHA_CREA = ISNULL(@FECHA_CREA, GETDATE());
			SET @USUARIO_ACTU = @USUARIO_CREA;
			SET @FECHA_ACTU = @FECHA_CREA;
			SET @ESTACION_ACTU = @ESTACION_CREA;

			INSERT INTO dbo.BAN_SOLI_CHEQUE
			(
				CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_TIPO_MOVIMIENTO, CORR_DOCUMENTO,
				CORR_CUENTA_BANCO, NUMERO_DOCUMENTO, FECHA_EMISION, NOMBRE_PARTIDA,
				CORR_PROVEEDOR, CORR_EMPLEADO, CORR_CLIENTE, NOMBRE_BENEFICIARIO,
				MONTO_DOCUMENTO, ESTADO_DOCUMENTO, SOLICITADO_POR, FECHA_SOLICITADO, FECHA_APLICADO,
				CANTIDAD_LETRAS, USUARIO_CREA, FECHA_CREA, ESTACION_CREA, USUARIO_ACTU, FECHA_ACTU, ESTACION_ACTU,
				CORR_TIPO_CHEQUE, ANIO_PERIODO_CHEQUE, MES_PERIODO_CHEQUE, CORR_TIPO_MOVIMIENTO_CHEQUE, CORR_DOCUMENTO_CHEQUE,
				CORR_MONEDA, FACTOR_CAMBIO, OPERADOR
			)
			VALUES
			(
				@CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, @CORR_TIPO_MOVIMIENTO, @CORR_DOCUMENTO,
				@CORR_CUENTA_BANCO, ISNULL(@NUMERO_DOCUMENTO, 0), @FECHA_EMISION, @NOMBRE_PARTIDA,
				@CORR_PROVEEDOR, @CORR_EMPLEADO, @CORR_CLIENTE, @NOMBRE_BENEFICIARIO,
				@MONTO_DOCUMENTO, @ESTADO_DOCUMENTO, @SOLICITADO_POR, @FECHA_SOLICITADO, @FECHA_APLICADO,
				@CANTIDAD_LETRAS, @USUARIO_CREA, @FECHA_CREA, @ESTACION_CREA, @USUARIO_ACTU, @FECHA_ACTU, @ESTACION_ACTU,
				@CORR_TIPO_CHEQUE, @ANIO_PERIODO_CHEQUE, @MES_PERIODO_CHEQUE, @CORR_TIPO_MOVIMIENTO_CHEQUE, @CORR_DOCUMENTO_CHEQUE,
				@CORR_MONEDA, @FACTOR_CAMBIO, @OPERADOR
			);

			IF ISNULL(@GENERA_DETALLE, 1) = 1 AND @CORR_CUENTA_BANCO IS NOT NULL
			BEGIN
				EXEC dbo.PRAL_GENE_BAN_SOLI_CHEQUE_DETA
					@CORR_EMPRESA = @CORR_EMPRESA,
					@ANIO_PERIODO = @ANIO_PERIODO,
					@MES_PERIODO = @MES_PERIODO,
					@CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO,
					@CORR_DOCUMENTO = @CORR_DOCUMENTO,
					@SYS_LOGIN_USUARIO = @SYS_LOGIN_USUARIO,
					@SYS_ESTACION = @SYS_ESTACION,
					@SYS_FILAS_AFECTADAS = @SYS_FILAS_AFECTADAS OUTPUT,
					@SYS_NUMERO_ERROR = @SYS_NUMERO_ERROR OUTPUT,
					@SYS_MENSAJE_ERROR = @SYS_MENSAJE_ERROR OUTPUT;

				IF @SYS_NUMERO_ERROR <> 0
				BEGIN
					DELETE FROM dbo.BAN_SOLI_CHEQUE_DETA
					WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
						AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

					DELETE FROM dbo.BAN_SOLI_CHEQUE
					WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
						AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

					GOTO FINA;
				END;
			END;
		END
		ELSE IF @TIPO_ACTUALIZA = 2
		BEGIN
			UPDATE dbo.BAN_SOLI_CHEQUE SET
				CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO,
				NUMERO_DOCUMENTO = @NUMERO_DOCUMENTO,
				FECHA_EMISION = @FECHA_EMISION,
				NOMBRE_PARTIDA = @NOMBRE_PARTIDA,
				CORR_PROVEEDOR = @CORR_PROVEEDOR,
				CORR_EMPLEADO = @CORR_EMPLEADO,
				CORR_CLIENTE = @CORR_CLIENTE,
				NOMBRE_BENEFICIARIO = @NOMBRE_BENEFICIARIO,
				MONTO_DOCUMENTO = @MONTO_DOCUMENTO,
				CANTIDAD_LETRAS = @CANTIDAD_LETRAS,
				USUARIO_ACTU = @USUARIO_ACTU,
				FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE()),
				ESTACION_ACTU = @ESTACION_ACTU,
				CORR_TIPO_CHEQUE = @CORR_TIPO_CHEQUE,
				CORR_MONEDA = @CORR_MONEDA,
				FACTOR_CAMBIO = @FACTOR_CAMBIO,
				OPERADOR = @OPERADOR
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;
		END
		ELSE IF @TIPO_ACTUALIZA = 3
		BEGIN
			IF EXISTS (
				SELECT 1 FROM dbo.BAN_DOCUMENTO A
				INNER JOIN dbo.BAN_SOLI_CHEQUE B
					ON A.CORR_EMPRESA = B.CORR_EMPRESA
					AND A.ANIO_PERIODO = B.ANIO_PERIODO_CHEQUE
					AND A.MES_PERIODO = B.MES_PERIODO_CHEQUE
					AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO_CHEQUE
					AND A.CORR_DOCUMENTO = B.CORR_DOCUMENTO_CHEQUE
				WHERE B.CORR_EMPRESA = @CORR_EMPRESA AND B.ANIO_PERIODO = @ANIO_PERIODO AND B.MES_PERIODO = @MES_PERIODO
					AND B.CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND B.CORR_DOCUMENTO = @CORR_DOCUMENTO
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30001, @SYS_MENSAJE_ERROR = N'No se puede eliminar porque existe un documento bancario asociado a esta solicitud', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF OBJECT_ID(N'dbo.BAN_LIQUI_CAJA_CHICA', N'U') IS NOT NULL
				AND EXISTS (
					SELECT 1 FROM dbo.BAN_LIQUI_CAJA_CHICA
					WHERE CORR_EMPRESA = @CORR_EMPRESA
						AND ANIO_PERIODO_SOLI_CHEQUE = @ANIO_PERIODO
						AND MES_PERIODO_SOLI_CHEQUE = @MES_PERIODO
						AND CORR_TIPO_MOVIMIENTO_SOLI_CHEQUE = @CORR_TIPO_MOVIMIENTO
						AND CORR_DOCUMENTO_SOLI_CHEQUE = @CORR_DOCUMENTO
				)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30001, @SYS_MENSAJE_ERROR = N'No se puede eliminar porque existe una liquidación de caja asociada a esta solicitud', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF OBJECT_ID(N'dbo.COM_PAGO', N'U') IS NOT NULL
				AND EXISTS (
					SELECT 1 FROM dbo.COM_PAGO
					WHERE CORR_EMPRESA = @CORR_EMPRESA
						AND ANIO_PERIODO_SOLI_CHEQUE = @ANIO_PERIODO
						AND MES_PERIODO_SOLI_CHEQUE = @MES_PERIODO
						AND CORR_TIPO_MOVIMIENTO_SOLI_CHEQUE = @CORR_TIPO_MOVIMIENTO
						AND CORR_DOCUMENTO_SOLI_CHEQUE = @CORR_DOCUMENTO
				)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30001, @SYS_MENSAJE_ERROR = N'No se puede eliminar porque existe un pago por compras asociado a esta solicitud', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			DELETE FROM dbo.BAN_SOLI_CHEQUE_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

			DELETE FROM dbo.BAN_SOLI_CHEQUE
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── MTTO detalle ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_SOLI_CHEQUE_DETA', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_DETA];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_DETA]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@CORR_DOCUMENTO_DETA INT OUTPUT,
	@CUENTA_CONTABLE VARCHAR(30),
	@CORR_CENTRO_COSTO INT = NULL,
	@NOMBRE_TRAN VARCHAR(1255),
	@MONTO_CARGO DECIMAL(12, 2) = 0,
	@MONTO_ABONO DECIMAL(12, 2) = 0,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1, 2, 3)
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM dbo.BAN_SOLI_CHEQUE
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
					AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
					AND ESTADO_DOCUMENTO = 'DI'
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'La solicitud no está en estado Digitado', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		IF @TIPO_ACTUALIZA IN (1, 2)
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM dbo.CON_CATALOGO_CUENTA
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CUENTA_CONTABLE = @CUENTA_CONTABLE
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No existe la cuenta contable', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		IF @TIPO_ACTUALIZA = 1
		BEGIN
			SELECT @CORR_DOCUMENTO_DETA = ISNULL(MAX(CORR_DOCUMENTO_DETA), 0) + 1
			FROM dbo.BAN_SOLI_CHEQUE_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

			INSERT INTO dbo.BAN_SOLI_CHEQUE_DETA
			(CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_TIPO_MOVIMIENTO, CORR_DOCUMENTO, CORR_DOCUMENTO_DETA,
			 CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
			VALUES
			(@CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, @CORR_TIPO_MOVIMIENTO, @CORR_DOCUMENTO, @CORR_DOCUMENTO_DETA,
			 @CUENTA_CONTABLE, @CORR_CENTRO_COSTO, @NOMBRE_TRAN, @MONTO_CARGO, @MONTO_ABONO);
		END
		ELSE IF @TIPO_ACTUALIZA = 2
		BEGIN
			UPDATE dbo.BAN_SOLI_CHEQUE_DETA SET
				CUENTA_CONTABLE = @CUENTA_CONTABLE,
				CORR_CENTRO_COSTO = @CORR_CENTRO_COSTO,
				NOMBRE_TRAN = @NOMBRE_TRAN,
				MONTO_CARGO = @MONTO_CARGO,
				MONTO_ABONO = @MONTO_ABONO
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
				AND CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA;
		END
		ELSE IF @TIPO_ACTUALIZA = 3
		BEGIN
			DELETE FROM dbo.BAN_SOLI_CHEQUE_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
				AND CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA;
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Generador automático detalle contable ── */
IF OBJECT_ID(N'dbo.PRAL_GENE_BAN_SOLI_CHEQUE_DETA', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_GENE_BAN_SOLI_CHEQUE_DETA];
GO

CREATE PROCEDURE [dbo].[PRAL_GENE_BAN_SOLI_CHEQUE_DETA]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE
		@CLASE_MOVIMIENTO VARCHAR(3),
		@SUMA_RESTA INT,
		@CORR_CUENTA_BANCO INT,
		@MONTO_DOCUMENTO DECIMAL(18, 2),
		@NOMBRE_BENEFICIARIO VARCHAR(255),
		@NOMBRE_PARTIDA VARCHAR(1000),
		@NOMBRE_TRAN VARCHAR(1255),
		@CLASE_TIPO_CHEQUE VARCHAR(2),
		@CORR_TIPO_CHEQUE INT,
		@CUENTA_CONTABLE_TIPO_CHEQUE VARCHAR(30),
		@CORR_DOCUMENTO_DETA INT,
		@CUENTA_CONTABLE VARCHAR(30),
		@CORR_CENTRO_COSTO INT,
		@MONTO_CARGO DECIMAL(12, 2),
		@MONTO_ABONO DECIMAL(12, 2);

	DECLARE @BAN_SOLI_CHEQUE_DETA TABLE
	(
		CUENTA_CONTABLE VARCHAR(30) NOT NULL,
		CORR_CENTRO_COSTO INT NULL,
		NOMBRE_TRAN VARCHAR(1255) NOT NULL,
		MONTO_CARGO DECIMAL(12, 2) NOT NULL,
		MONTO_ABONO DECIMAL(12, 2) NOT NULL
	);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		IF NOT EXISTS (
			SELECT 1 FROM dbo.BAN_SOLI_CHEQUE
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
				AND ESTADO_DOCUMENTO = 'DI'
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'La solicitud no está en estado Digitado', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF EXISTS (
			SELECT 1 FROM dbo.BAN_SOLI_CHEQUE_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'La solicitud ya tiene detalle contable', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT
			@CORR_CUENTA_BANCO = CORR_CUENTA_BANCO,
			@MONTO_DOCUMENTO = MONTO_DOCUMENTO,
			@NOMBRE_BENEFICIARIO = ISNULL(NOMBRE_BENEFICIARIO, ''),
			@NOMBRE_PARTIDA = ISNULL(NOMBRE_PARTIDA, ''),
			@CLASE_TIPO_CHEQUE = ISNULL(CLASE_TIPO_CHEQUE, ''),
			@CORR_TIPO_CHEQUE = ISNULL(CORR_TIPO_CHEQUE, 0)
		FROM dbo.V_BAN_SOLI_CHEQUE
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SELECT @CLASE_MOVIMIENTO = CLASE_MOVIMIENTO, @SUMA_RESTA = SUMA_RESTA
		FROM dbo.BAN_TIPO_MOVI_BANCARIO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO;

		SET @NOMBRE_TRAN = LTRIM(RTRIM(@NOMBRE_BENEFICIARIO + N' ' + @NOMBRE_PARTIDA));

		IF ISNULL(@MONTO_DOCUMENTO, 0) <= 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El monto del documento debe ser mayor a cero para generar detalle', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF @CLASE_MOVIMIENTO = 'CHQ'
		BEGIN
			IF ISNULL(@CORR_TIPO_CHEQUE, 0) = 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Debe seleccionar el tipo de cheque', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			SELECT @CUENTA_CONTABLE_TIPO_CHEQUE = ISNULL(CUENTA_CONTABLE, '')
			FROM dbo.BAN_TIPO_CHEQUE
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_CHEQUE = @CORR_TIPO_CHEQUE;

			INSERT INTO @BAN_SOLI_CHEQUE_DETA (CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
			SELECT A.CUENTA_CONTABLE, A.CORR_CENTRO_COSTO, @NOMBRE_TRAN, 0, @MONTO_DOCUMENTO
			FROM dbo.BAN_CUENTA_BANCARIA A
			WHERE A.CORR_EMPRESA = @CORR_EMPRESA AND A.CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO;

			IF @@ROWCOUNT = 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No se encontró la cuenta bancaria de la solicitud', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF LTRIM(RTRIM(ISNULL(@CUENTA_CONTABLE_TIPO_CHEQUE, ''))) <> ''
			BEGIN
				INSERT INTO @BAN_SOLI_CHEQUE_DETA (CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
				VALUES (@CUENTA_CONTABLE_TIPO_CHEQUE, NULL, @NOMBRE_TRAN, @MONTO_DOCUMENTO, 0);
			END;
		END
		ELSE
		BEGIN
			INSERT INTO @BAN_SOLI_CHEQUE_DETA (CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
			SELECT
				A.CUENTA_CONTABLE,
				A.CORR_CENTRO_COSTO,
				@NOMBRE_TRAN,
				CASE WHEN @SUMA_RESTA = 1 THEN @MONTO_DOCUMENTO ELSE 0 END,
				CASE WHEN @SUMA_RESTA = 1 THEN 0 ELSE @MONTO_DOCUMENTO END
			FROM dbo.BAN_CUENTA_BANCARIA A
			WHERE A.CORR_EMPRESA = @CORR_EMPRESA AND A.CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO;

			IF @@ROWCOUNT = 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No se encontró la cuenta bancaria de la solicitud', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		WHILE EXISTS (SELECT 1 FROM @BAN_SOLI_CHEQUE_DETA)
		BEGIN
			SELECT TOP 1
				@CORR_DOCUMENTO_DETA = 0,
				@CUENTA_CONTABLE = CUENTA_CONTABLE,
				@CORR_CENTRO_COSTO = CORR_CENTRO_COSTO,
				@NOMBRE_TRAN = NOMBRE_TRAN,
				@MONTO_CARGO = MONTO_CARGO,
				@MONTO_ABONO = MONTO_ABONO
			FROM @BAN_SOLI_CHEQUE_DETA
			ORDER BY CUENTA_CONTABLE, MONTO_CARGO DESC, MONTO_ABONO DESC;

			EXEC dbo.PRAL_MTTO_BAN_SOLI_CHEQUE_DETA
				@TIPO_ACTUALIZA = 1,
				@CORR_EMPRESA = @CORR_EMPRESA,
				@ANIO_PERIODO = @ANIO_PERIODO,
				@MES_PERIODO = @MES_PERIODO,
				@CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO,
				@CORR_DOCUMENTO = @CORR_DOCUMENTO,
				@CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA OUTPUT,
				@CUENTA_CONTABLE = @CUENTA_CONTABLE,
				@CORR_CENTRO_COSTO = @CORR_CENTRO_COSTO,
				@NOMBRE_TRAN = @NOMBRE_TRAN,
				@MONTO_CARGO = @MONTO_CARGO,
				@MONTO_ABONO = @MONTO_ABONO,
				@SYS_LOGIN_USUARIO = @SYS_LOGIN_USUARIO,
				@SYS_ESTACION = @SYS_ESTACION,
				@SYS_FILAS_AFECTADAS = @SYS_FILAS_AFECTADAS OUTPUT,
				@SYS_NUMERO_ERROR = @SYS_NUMERO_ERROR OUTPUT,
				@SYS_MENSAJE_ERROR = @SYS_MENSAJE_ERROR OUTPUT;

			IF @SYS_NUMERO_ERROR <> 0
				GOTO FINA;

			;WITH CTE AS
			(
				SELECT TOP 1 *
				FROM @BAN_SOLI_CHEQUE_DETA
				ORDER BY CUENTA_CONTABLE, MONTO_CARGO DESC, MONTO_ABONO DESC
			)
			DELETE FROM CTE;
		END;

		SET @SYS_FILAS_AFECTADAS = (
			SELECT COUNT(1) FROM dbo.BAN_SOLI_CHEQUE_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
		);
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Enviar solicitud (DI → SO) ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_SOLI_CHEQUE_ENVIAR_SOLICITUD', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_ENVIAR_SOLICITUD];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_ENVIAR_SOLICITUD]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @ESTADO_DOCUMENTO VARCHAR(2), @MONTO_CARGO DECIMAL(12, 2), @MONTO_ABONO DECIMAL(12, 2);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		SELECT @ESTADO_DOCUMENTO = ESTADO_DOCUMENTO
		FROM dbo.BAN_SOLI_CHEQUE
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @ESTADO_DOCUMENTO <> 'DI'
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30001, @SYS_MENSAJE_ERROR = N'No se puede enviar esta solicitud', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.BAN_SOLI_CHEQUE_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30004, @SYS_MENSAJE_ERROR = N'El documento no tiene detalle. No se puede solicitar', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT @MONTO_CARGO = SUM(MONTO_CARGO), @MONTO_ABONO = SUM(MONTO_ABONO)
		FROM dbo.BAN_SOLI_CHEQUE_DETA
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF ISNULL(@MONTO_CARGO, 0) <> ISNULL(@MONTO_ABONO, 0)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30002, @SYS_MENSAJE_ERROR = N'Documento no cuadrado. No se puede solicitar', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		UPDATE dbo.BAN_SOLI_CHEQUE SET
			ESTADO_DOCUMENTO = 'SO',
			FECHA_SOLICITADO = CAST(GETDATE() AS DATE),
			SOLICITADO_POR = @SYS_LOGIN_USUARIO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Cancelar solicitud (SO → DI) ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_SOLI_CHEQUE_CANCELAR_SOLICITUD', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_CANCELAR_SOLICITUD];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_CANCELAR_SOLICITUD]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE
		@ESTADO_DOCUMENTO VARCHAR(2),
		@ANIO_PERIODO_CHEQUE INT,
		@MES_PERIODO_CHEQUE INT,
		@CORR_TIPO_MOVIMIENTO_CHEQUE INT,
		@CORR_DOCUMENTO_CHEQUE INT,
		@ESTADO_CHEQUE VARCHAR(2);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		SELECT
			@ESTADO_DOCUMENTO = ESTADO_DOCUMENTO,
			@ANIO_PERIODO_CHEQUE = ANIO_PERIODO_CHEQUE,
			@MES_PERIODO_CHEQUE = MES_PERIODO_CHEQUE,
			@CORR_TIPO_MOVIMIENTO_CHEQUE = CORR_TIPO_MOVIMIENTO_CHEQUE,
			@CORR_DOCUMENTO_CHEQUE = CORR_DOCUMENTO_CHEQUE
		FROM dbo.BAN_SOLI_CHEQUE
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF ISNULL(@CORR_DOCUMENTO_CHEQUE, 0) > 0
		BEGIN
			SELECT @ESTADO_CHEQUE = ESTADO_DOCUMENTO
			FROM dbo.BAN_DOCUMENTO
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO_CHEQUE AND MES_PERIODO = @MES_PERIODO_CHEQUE
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO_CHEQUE AND CORR_DOCUMENTO = @CORR_DOCUMENTO_CHEQUE;

			IF @ESTADO_CHEQUE IN ('AP', 'IM', 'AN')
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30001, @SYS_MENSAJE_ERROR = N'No se puede cancelar esta solicitud, porque el cheque ya está aplicado, impreso o anulado', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		IF @ESTADO_DOCUMENTO <> 'SO'
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30001, @SYS_MENSAJE_ERROR = N'No se puede cancelar esta solicitud, porque no ha sido enviada o ya está autorizada', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		UPDATE dbo.BAN_SOLI_CHEQUE SET
			ESTADO_DOCUMENTO = 'DI',
			FECHA_SOLICITADO = NULL,
			SOLICITADO_POR = NULL
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Aplicar solicitud (SO → AP) ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_SOLI_CHEQUE_APLICAR_SOLICITUD', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_APLICAR_SOLICITUD];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_SOLI_CHEQUE_APLICAR_SOLICITUD]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT OUTPUT,
	@CORR_CUENTA_BANCO INT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE
		@ESTADO_DOCUMENTO VARCHAR(2),
		@ANIO_PERIODO_CHEQUE INT,
		@MES_PERIODO_CHEQUE INT,
		@CORR_TIPO_MOVIMIENTO_CHEQUE INT,
		@CORR_DOCUMENTO_CHEQUE INT,
		@FECHA_EMISION DATE,
		@NUMERO_DOCUMENTO BIGINT,
		@NOMBRE_PARTIDA VARCHAR(1000),
		@CORR_PROVEEDOR INT,
		@CORR_EMPLEADO INT,
		@CORR_CLIENTE INT,
		@NOMBRE_BENEFICIARIO VARCHAR(255),
		@MONTO_DOCUMENTO DECIMAL(18, 2),
		@FECHA_APLICADO DATE,
		@CANTIDAD_LETRAS VARCHAR(255),
		@CORR_TIPO_CHEQUE INT,
		@USUARIO_ACTU VARCHAR(30),
		@FECHA_ACTU DATETIME,
		@ESTACION_ACTU VARCHAR(50),
		@CORR_MONEDA INT,
		@CORR_DOCUMENTO_DETA INT,
		@SRC_DOCUMENTO_DETA INT,
		@CUENTA_CONTABLE VARCHAR(30),
		@CORR_CENTRO_COSTO INT,
		@NOMBRE_TRAN VARCHAR(1255),
		@MONTO_CARGO DECIMAL(12, 2),
		@MONTO_ABONO DECIMAL(12, 2);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;
	SET @USUARIO_ACTU = @SYS_LOGIN_USUARIO;
	SET @FECHA_ACTU = GETDATE();
	SET @ESTACION_ACTU = @SYS_ESTACION;
	SET @FECHA_APLICADO = CAST(GETDATE() AS DATE);

	BEGIN TRY
		SELECT @ESTADO_DOCUMENTO = ESTADO_DOCUMENTO
		FROM dbo.BAN_SOLI_CHEQUE
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @ESTADO_DOCUMENTO <> 'SO'
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30001, @SYS_MENSAJE_ERROR = N'No se puede autorizar esta solicitud', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF @CORR_CUENTA_BANCO IS NULL OR NOT EXISTS (
			SELECT 1 FROM dbo.BAN_CUENTA_BANCARIA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No existe la cuenta bancaria seleccionada', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT @CORR_TIPO_MOVIMIENTO_CHEQUE = CORR_TIPO_MOVIMIENTO
		FROM dbo.V_BAN_TIPO_MOVI_BANCARIO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CLASE_MOVIMIENTO = 'CHQ';

		IF ISNULL(@CORR_TIPO_MOVIMIENTO_CHEQUE, 0) = 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30002, @SYS_MENSAJE_ERROR = N'No está configurado el tipo de movimiento de cheque', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT
			@ANIO_PERIODO_CHEQUE = YEAR(FECHA_EMISION),
			@MES_PERIODO_CHEQUE = MONTH(FECHA_EMISION),
			@FECHA_EMISION = FECHA_EMISION,
			@CORR_DOCUMENTO_CHEQUE = 0,
			@NUMERO_DOCUMENTO = NUMERO_DOCUMENTO,
			@NOMBRE_PARTIDA = NOMBRE_PARTIDA,
			@CORR_PROVEEDOR = CORR_PROVEEDOR,
			@CORR_EMPLEADO = CORR_EMPLEADO,
			@CORR_CLIENTE = CORR_CLIENTE,
			@NOMBRE_BENEFICIARIO = NOMBRE_BENEFICIARIO,
			@MONTO_DOCUMENTO = MONTO_DOCUMENTO,
			@CANTIDAD_LETRAS = CANTIDAD_LETRAS,
			@CORR_TIPO_CHEQUE = CORR_TIPO_CHEQUE
		FROM dbo.BAN_SOLI_CHEQUE
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SELECT @CORR_MONEDA = CORR_MONEDA
		FROM dbo.CON_PARAMETRO
		WHERE CORR_EMPRESA = @CORR_EMPRESA;

		EXEC dbo.PRAL_MTTO_BAN_DOCUMENTO
			@TIPO_ACTUALIZA = 1,
			@CORR_EMPRESA = @CORR_EMPRESA,
			@ANIO_PERIODO = @ANIO_PERIODO_CHEQUE,
			@MES_PERIODO = @MES_PERIODO_CHEQUE,
			@CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO_CHEQUE,
			@CORR_DOCUMENTO = @CORR_DOCUMENTO_CHEQUE OUTPUT,
			@CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO,
			@NUMERO_DOCUMENTO = @NUMERO_DOCUMENTO,
			@FECHA_EMISION = @FECHA_EMISION,
			@NOMBRE_PARTIDA = @NOMBRE_PARTIDA,
			@CORR_PROVEEDOR = @CORR_PROVEEDOR,
			@CORR_EMPLEADO = @CORR_EMPLEADO,
			@CORR_CLIENTE = @CORR_CLIENTE,
			@NOMBRE_BENEFICIARIO = @NOMBRE_BENEFICIARIO,
			@MONTO_DOCUMENTO = @MONTO_DOCUMENTO,
			@ESTADO_DOCUMENTO = 'DI',
			@ESTA_CONTABILIZADO = 0,
			@CANTIDAD_LETRAS = @CANTIDAD_LETRAS,
			@USUARIO_CREA = @SYS_LOGIN_USUARIO,
			@FECHA_CREA = @FECHA_ACTU,
			@ESTACION_CREA = @SYS_ESTACION,
			@USUARIO_ACTU = @USUARIO_ACTU,
			@FECHA_ACTU = @FECHA_ACTU,
			@ESTACION_ACTU = @ESTACION_ACTU,
			@CORR_TIPO_CHEQUE = @CORR_TIPO_CHEQUE,
			@CORR_MONEDA = @CORR_MONEDA,
			@FACTOR_CAMBIO = 1,
			@OPERADOR = '*',
			@GENERA_DETALLE = 0,
			@SYS_LOGIN_USUARIO = @SYS_LOGIN_USUARIO,
			@SYS_ESTACION = @SYS_ESTACION,
			@SYS_FILAS_AFECTADAS = @SYS_FILAS_AFECTADAS OUTPUT,
			@SYS_NUMERO_ERROR = @SYS_NUMERO_ERROR OUTPUT,
			@SYS_MENSAJE_ERROR = @SYS_MENSAJE_ERROR OUTPUT;

		IF @SYS_NUMERO_ERROR <> 0
			GOTO FINA;

		DECLARE @TEMP1 TABLE
		(
			CORR_DOCUMENTO_DETA INT,
			CUENTA_CONTABLE VARCHAR(30),
			CORR_CENTRO_COSTO INT,
			NOMBRE_TRAN VARCHAR(1255),
			MONTO_CARGO DECIMAL(12, 2),
			MONTO_ABONO DECIMAL(12, 2),
			ESTA_PROC BIT NOT NULL DEFAULT 0
		);

		INSERT INTO @TEMP1 (CORR_DOCUMENTO_DETA, CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
		SELECT CORR_DOCUMENTO_DETA, CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO
		FROM dbo.BAN_SOLI_CHEQUE_DETA
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		WHILE EXISTS (SELECT 1 FROM @TEMP1 WHERE ESTA_PROC = 0)
		BEGIN
			SELECT TOP 1
				@SRC_DOCUMENTO_DETA = CORR_DOCUMENTO_DETA,
				@CUENTA_CONTABLE = CUENTA_CONTABLE,
				@CORR_CENTRO_COSTO = CORR_CENTRO_COSTO,
				@NOMBRE_TRAN = NOMBRE_TRAN,
				@MONTO_CARGO = MONTO_CARGO,
				@MONTO_ABONO = MONTO_ABONO
			FROM @TEMP1
			WHERE ESTA_PROC = 0
			ORDER BY CORR_DOCUMENTO_DETA;

			SET @CORR_DOCUMENTO_DETA = 0;

			EXEC dbo.PRAL_MTTO_BAN_DOCUMENTO_DETA
				@TIPO_ACTUALIZA = 1,
				@CORR_EMPRESA = @CORR_EMPRESA,
				@ANIO_PERIODO = @ANIO_PERIODO_CHEQUE,
				@MES_PERIODO = @MES_PERIODO_CHEQUE,
				@CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO_CHEQUE,
				@CORR_DOCUMENTO = @CORR_DOCUMENTO_CHEQUE,
				@CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA OUTPUT,
				@CUENTA_CONTABLE = @CUENTA_CONTABLE,
				@CORR_CENTRO_COSTO = @CORR_CENTRO_COSTO,
				@NOMBRE_TRAN = @NOMBRE_TRAN,
				@MONTO_CARGO = @MONTO_CARGO,
				@MONTO_ABONO = @MONTO_ABONO,
				@SYS_LOGIN_USUARIO = @SYS_LOGIN_USUARIO,
				@SYS_ESTACION = @SYS_ESTACION,
				@SYS_FILAS_AFECTADAS = @SYS_FILAS_AFECTADAS OUTPUT,
				@SYS_NUMERO_ERROR = @SYS_NUMERO_ERROR OUTPUT,
				@SYS_MENSAJE_ERROR = @SYS_MENSAJE_ERROR OUTPUT;

			IF @SYS_NUMERO_ERROR <> 0
			BEGIN
				DELETE FROM dbo.BAN_DOCUMENTO_DETA
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO_CHEQUE AND MES_PERIODO = @MES_PERIODO_CHEQUE
					AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO_CHEQUE AND CORR_DOCUMENTO = @CORR_DOCUMENTO_CHEQUE;

				DELETE FROM dbo.BAN_DOCUMENTO
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO_CHEQUE AND MES_PERIODO = @MES_PERIODO_CHEQUE
					AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO_CHEQUE AND CORR_DOCUMENTO = @CORR_DOCUMENTO_CHEQUE;

				GOTO FINA;
			END;

			UPDATE @TEMP1 SET ESTA_PROC = 1
			WHERE CORR_DOCUMENTO_DETA = @SRC_DOCUMENTO_DETA;
		END;

		EXEC dbo.PRAL_MTTO_BAN_DOCUMENTO_APLICAR
			@CORR_EMPRESA = @CORR_EMPRESA,
			@ANIO_PERIODO = @ANIO_PERIODO_CHEQUE,
			@MES_PERIODO = @MES_PERIODO_CHEQUE,
			@CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO_CHEQUE,
			@CORR_DOCUMENTO = @CORR_DOCUMENTO_CHEQUE,
			@USUARIO_ACTU = @USUARIO_ACTU,
			@FECHA_ACTU = @FECHA_ACTU,
			@ESTACION_ACTU = @ESTACION_ACTU,
			@SYS_LOGIN_USUARIO = @SYS_LOGIN_USUARIO,
			@SYS_ESTACION = @SYS_ESTACION,
			@SYS_FILAS_AFECTADAS = @SYS_FILAS_AFECTADAS OUTPUT,
			@SYS_NUMERO_ERROR = @SYS_NUMERO_ERROR OUTPUT,
			@SYS_MENSAJE_ERROR = @SYS_MENSAJE_ERROR OUTPUT;

		IF @SYS_NUMERO_ERROR <> 0
		BEGIN
			DELETE FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO_CHEQUE AND MES_PERIODO = @MES_PERIODO_CHEQUE
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO_CHEQUE AND CORR_DOCUMENTO = @CORR_DOCUMENTO_CHEQUE;

			DELETE FROM dbo.BAN_DOCUMENTO
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO_CHEQUE AND MES_PERIODO = @MES_PERIODO_CHEQUE
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO_CHEQUE AND CORR_DOCUMENTO = @CORR_DOCUMENTO_CHEQUE;

			GOTO FINA;
		END;

		UPDATE dbo.BAN_SOLI_CHEQUE SET
			ESTADO_DOCUMENTO = 'AP',
			FECHA_APLICADO = @FECHA_APLICADO,
			APLICADO_POR = @SYS_LOGIN_USUARIO,
			ANIO_PERIODO_CHEQUE = @ANIO_PERIODO_CHEQUE,
			MES_PERIODO_CHEQUE = @MES_PERIODO_CHEQUE,
			CORR_TIPO_MOVIMIENTO_CHEQUE = @CORR_TIPO_MOVIMIENTO_CHEQUE,
			CORR_DOCUMENTO_CHEQUE = @CORR_DOCUMENTO_CHEQUE,
			CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO,
			USUARIO_ACTU = @USUARIO_ACTU,
			FECHA_ACTU = @FECHA_ACTU,
			ESTACION_ACTU = @ESTACION_ACTU
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

PRINT N'DEPLOY_BAN_SOLI_CHEQUE completado.';
GO

:r MENU_BAN_SOLI_CHEQUE.sql
