/*

  Corrige Balance vs CLASS y Estado de Resultados (migracion CLASS -> SGUEES).

  Ejecutar desde la carpeta Scripts:

    cd "c:\Desarrollo GIT\SGUEES\SGUEES-DB\Scripts"
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -i DEPLOY_FIX_BALANCE_ER.sql



  Luego consultar reportes con FECHA_FINAL = 2026-05-31 (no junio: SALDO_INICIAL6 vacio).

*/

SET NOCOUNT ON;

PRINT '=== 1. Parametros contables ===';

GO

:r SETUP_CON_PARAMETRO.sql

GO



PRINT '=== 2. CLASE_RUBRO IN/GA en catalogo ===';

GO

:r FIX_CLASE_RUBRO_CATALOGO.sql

GO



PRINT '=== 3. FN_CLASS_GASTOINGRESO + PRAL_IMPR_BALANCE_GENERAL ===';

GO

:r FIX_BALANCE_PATRIMONIO_CLASS.sql

GO



PRINT '=== 4. SP saldos historicos (patrimonio sin duplicar 310801) ===';

GO

:r MIGRATE_CLASS_SALDO_HISTORICO.sql

GO



PRINT '=== 5. Limpiar resultado del periodo en HIS (3106/3108) ===';

DELETE FROM CON_CATALOGO_SALDO_HIS

WHERE CORR_EMPRESA = 1

  AND ANIO_PERIODO = 2026

  AND (

        LEFT(CUENTA_CONTABLE, 4) IN ('3106', '3108')

     OR CUENTA_CONTABLE IN ('3106', '3108', '310601', '310801')

  );

PRINT CAST(@@ROWCOUNT AS VARCHAR(10)) + ' filas patrimonio-periodo eliminadas de HIS.';

GO



PRINT '=== 6. Recargar HIS abril (apertura mayo) ===';

GO

:r FIX_RELOAD_HIS_MAYO.sql

GO



PRINT '=== 7. Validacion rapida ===';

DECLARE @FECHA DATE = '2026-05-31';



CREATE TABLE #S (

    CORR_EMPRESA INT, CUENTA_CONTABLE VARCHAR(30), CUENTA_MAYOR VARCHAR(30),

    ES_DEBE BIT, ES_HABER BIT, SALDO_INICIAL DECIMAL(18, 2),

    CARGO_PERIODO DECIMAL(18, 2), ABONO_PERIODO DECIMAL(18, 2), SALDO_FINAL DECIMAL(18, 2)

);

INSERT #S

EXEC dbo.PRAL_GENE_CON_SALDO_INICIAL

    @CORR_EMPRESA = 1, @FECHA_CONSULTA = @FECHA, @OPCION_CONSULTA = 0,

    @MAYORIZA = 1, @CUENTA_CONTABLE_INICIAL = '', @CUENTA_CONTABLE_FINAL = '',
    @APLICA_DEBE_HABE = 1, @PARTIDA_CIERRE = 0, @PARTIDA_LIQUIDACION = 0, @NIVEL = 3;



CREATE TABLE #ER (

    CORR_EMPRESA INT, CUENTA_CONTABLE VARCHAR(30), CUENTA_MAYOR VARCHAR(30),

    ES_DEBE BIT, ES_HABER BIT, SALDO_INICIAL DECIMAL(18, 2),

    CARGO_PERIODO DECIMAL(18, 2), ABONO_PERIODO DECIMAL(18, 2), SALDO_FINAL DECIMAL(18, 2)

);

INSERT #ER

EXEC dbo.PRAL_GENE_CON_SALDO_INICIAL

    @CORR_EMPRESA = 1, @FECHA_CONSULTA = @FECHA, @OPCION_CONSULTA = 2,

    @MAYORIZA = 0, @CUENTA_CONTABLE_INICIAL = '', @CUENTA_CONTABLE_FINAL = '',
    @APLICA_DEBE_HABE = 1, @PARTIDA_CIERRE = 0, @PARTIDA_LIQUIDACION = 0, @NIVEL = 3;



SELECT 'HIS IN/GA apertura mayo' AS CHECK_NAME, COUNT(*) AS CUENTAS, SUM(ABS(SALDO_INICIAL5)) AS SUM_SALDO

FROM CON_CATALOGO_SALDO_HIS

WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026

  AND CUENTA_CONTABLE IN (SELECT CUENTA_CONTABLE FROM CON_CATALOGO_CUENTA WHERE CORR_EMPRESA = 1 AND CLASE_RUBRO IN ('IN', 'GA') AND NIVEL = 3);



SELECT 'ER filas con movimiento' AS CHECK_NAME, COUNT(*) AS CUENTAS

FROM #ER

WHERE ABS(SALDO_FINAL) > 0.01 OR ABS(CARGO_PERIODO) > 0.01;



SELECT 'Balance ecuacion' AS CHECK_NAME,

       SUM(CASE WHEN C.CLASE_RUBRO = 'AC' AND C.NIVEL = 1 THEN S.SALDO_FINAL ELSE 0 END) AS ACTIVO,

       SUM(CASE WHEN C.CLASE_RUBRO IN ('PA', 'PT') AND C.NIVEL = 1 THEN S.SALDO_FINAL ELSE 0 END) AS PASIVO_PT,

       SUM(CASE WHEN C.CLASE_RUBRO = 'AC' AND C.NIVEL = 1 THEN S.SALDO_FINAL ELSE 0 END)

     - SUM(CASE WHEN C.CLASE_RUBRO IN ('PA', 'PT') AND C.NIVEL = 1 THEN S.SALDO_FINAL ELSE 0 END) AS DIFERENCIA

FROM #S S
INNER JOIN CON_CATALOGO_CUENTA C
    ON C.CORR_EMPRESA = 1
   AND C.CUENTA_CONTABLE = S.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT;



SELECT CUENTA_CONTABLE, SALDO_INICIAL5

FROM CON_CATALOGO_SALDO_HIS

WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026 AND CUENTA_CONTABLE LIKE '310%'

ORDER BY 1;



DROP TABLE #S;

DROP TABLE #ER;



PRINT '=== Listo. Use FECHA_FINAL = 2026-05-31 en Balance y Estado de Resultados ===';

GO


