/* Deploy idempotente — BAN_DOCUMENTO + BAN_DOCUMENTO_DETA (SGUEES, sin suscripción/país) */
SET NOCOUNT ON;

/* ── Columnas transferencia (cuenta destino) ── */
IF COL_LENGTH(N'dbo.BAN_DOCUMENTO', N'CORR_CUENTA_BANCO_DESTINO') IS NULL
BEGIN
	ALTER TABLE dbo.BAN_DOCUMENTO ADD CORR_CUENTA_BANCO_DESTINO INT NULL;
	PRINT N'Columna BAN_DOCUMENTO.CORR_CUENTA_BANCO_DESTINO agregada.';
END
GO

IF COL_LENGTH(N'dbo.BAN_DOCUMENTO', N'NUMERO_CUENTA_DESTINO_TERCERO') IS NULL
BEGIN
	ALTER TABLE dbo.BAN_DOCUMENTO ADD NUMERO_CUENTA_DESTINO_TERCERO VARCHAR(50) NULL;
	PRINT N'Columna BAN_DOCUMENTO.NUMERO_CUENTA_DESTINO_TERCERO agregada.';
END
GO

IF COL_LENGTH(N'dbo.BAN_DOCUMENTO', N'MONTO_DESTINO') IS NULL
BEGIN
	ALTER TABLE dbo.BAN_DOCUMENTO ADD MONTO_DESTINO DECIMAL(18, 2) NULL CONSTRAINT DF_BAN_DOCUMENTO_MONTO_DESTINO DEFAULT ((0));
	PRINT N'Columna BAN_DOCUMENTO.MONTO_DESTINO agregada.';
END
GO

/* ── Tabla encabezado ── */
IF OBJECT_ID(N'dbo.BAN_DOCUMENTO', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BAN_DOCUMENTO]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[ANIO_PERIODO] [int] NOT NULL,
		[MES_PERIODO] [int] NOT NULL,
		[CORR_TIPO_MOVIMIENTO] [int] NOT NULL,
		[CORR_DOCUMENTO] [int] NOT NULL,
		[CORR_CUENTA_BANCO] [int] NOT NULL,
		[NUMERO_DOCUMENTO] [bigint] NOT NULL CONSTRAINT [DF_BAN_DOCUMENTO_NUMERO] DEFAULT ((0)),
		[FECHA_EMISION] [date] NOT NULL,
		[NOMBRE_PARTIDA] [varchar](1000) COLLATE Latin1_General_CS_AS NOT NULL,
		[CORR_PROVEEDOR] [int] NULL,
		[CORR_EMPLEADO] [int] NULL,
		[CORR_CLIENTE] [int] NULL,
		[NOMBRE_BENEFICIARIO] [varchar](255) COLLATE Latin1_General_CS_AS NULL,
		[MONTO_DOCUMENTO] [decimal](18, 2) NOT NULL CONSTRAINT [DF_BAN_DOCUMENTO_MONTO] DEFAULT ((0)),
		[ESTADO_DOCUMENTO] [varchar](2) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_BAN_DOCUMENTO_ESTADO] DEFAULT ('DI'),
		[ESTA_CONTABILIZADO] [bit] NOT NULL CONSTRAINT [DF_BAN_DOCUMENTO_CONTAB] DEFAULT ((0)),
		[CANTIDAD_LETRAS] [varchar](255) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_BAN_DOCUMENTO_LETRAS] DEFAULT (''),
		[USUARIO_CREA] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
		[FECHA_CREA] [datetime] NOT NULL,
		[ESTACION_CREA] [varchar](50) COLLATE Latin1_General_CS_AS NOT NULL,
		[USUARIO_ACTU] [varchar](30) COLLATE Latin1_General_CS_AS NULL,
		[FECHA_ACTU] [datetime] NULL,
		[ESTACION_ACTU] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
		[CORR_TIPO_CHEQUE] [int] NULL,
		[CORR_CHEQUERA] [int] NULL,
		[SERIE_CHEQUE] [varchar](10) COLLATE Latin1_General_CS_AS NULL,
		[CORR_CUENTA_BANCO_DESTINO] [int] NULL,
		[NUMERO_CUENTA_DESTINO_TERCERO] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
		[MONTO_DESTINO] [decimal](18, 2) NULL CONSTRAINT [DF_BAN_DOCUMENTO_MONTO_DESTINO] DEFAULT ((0)),
		[CORR_MONEDA] [int] NULL,
		[FACTOR_CAMBIO] [decimal](16, 6) NULL CONSTRAINT [DF_BAN_DOCUMENTO_FC] DEFAULT ((1)),
		[OPERADOR] [varchar](2) COLLATE Latin1_General_CS_AS NULL CONSTRAINT [DF_BAN_DOCUMENTO_OP] DEFAULT ('*'),
		[FECHA_IMPRESO] [date] NULL,
		[FECHA_ANULACION] [date] NULL
	) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_DOCUMENTO]
		ADD CONSTRAINT [PK_BAN_DOCUMENTO]
		PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO]) ON [PRIMARY];
END
GO

/* ── Tabla detalle ── */
IF OBJECT_ID(N'dbo.BAN_DOCUMENTO_DETA', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BAN_DOCUMENTO_DETA]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[ANIO_PERIODO] [int] NOT NULL,
		[MES_PERIODO] [int] NOT NULL,
		[CORR_TIPO_MOVIMIENTO] [int] NOT NULL,
		[CORR_DOCUMENTO] [int] NOT NULL,
		[CORR_DOCUMENTO_DETA] [int] NOT NULL,
		[CUENTA_CONTABLE] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
		[CORR_CENTRO_COSTO] [int] NULL,
		[NOMBRE_TRAN] [varchar](1255) COLLATE Latin1_General_CS_AS NOT NULL,
		[MONTO_CARGO] [decimal](12, 2) NOT NULL CONSTRAINT [DF_BAN_DOC_DETA_CARGO] DEFAULT ((0)),
		[MONTO_ABONO] [decimal](12, 2) NOT NULL CONSTRAINT [DF_BAN_DOC_DETA_ABONO] DEFAULT ((0))
	) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_DOCUMENTO_DETA]
		ADD CONSTRAINT [PK_BAN_DOCUMENTO_DETA]
		PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO], [CORR_DOCUMENTO_DETA]) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_DOCUMENTO_DETA]
		ADD CONSTRAINT [FK_BAN_DOCUMENTO_DETA_BAN_DOCUMENTO]
		FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO])
		REFERENCES [dbo].[BAN_DOCUMENTO] ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_TIPO_MOVIMIENTO], [CORR_DOCUMENTO]);
END
GO

/* ── Vista encabezado ── */
IF OBJECT_ID(N'dbo.V_BAN_DOCUMENTO', N'V') IS NOT NULL
	DROP VIEW [dbo].[V_BAN_DOCUMENTO];
GO

CREATE VIEW [dbo].[V_BAN_DOCUMENTO]
AS
SELECT
	A.CORR_EMPRESA,
	A.ANIO_PERIODO,
	A.MES_PERIODO,
	A.CORR_TIPO_MOVIMIENTO,
	B.NOMBRE_TIPO_MOVIMIENTO,
	B.CLASE_MOVIMIENTO,
	A.CORR_DOCUMENTO,
	A.CORR_CUENTA_BANCO,
	C.NOMBRE_CUENTA_BANCO,
	C.NUMERO_CUENTA_BANCO,
	A.NUMERO_DOCUMENTO,
	A.FECHA_EMISION,
	A.NOMBRE_PARTIDA,
	ISNULL(A.CORR_PROVEEDOR, 0) CORR_PROVEEDOR,
	ISNULL(A.NOMBRE_BENEFICIARIO, '') NOMBRE_BENEFICIARIO,
	ISNULL(A.CORR_EMPLEADO, 0) CORR_EMPLEADO,
	ISNULL(A.CORR_CLIENTE, 0) CORR_CLIENTE,
	A.MONTO_DOCUMENTO,
	A.ESTADO_DOCUMENTO,
	CASE A.ESTADO_DOCUMENTO
		WHEN 'DI' THEN N'Digitado'
		WHEN 'AP' THEN N'Aplicado'
		WHEN 'IM' THEN N'Impreso'
		WHEN 'VA' THEN N'Validación'
		WHEN 'AN' THEN N'Anulado'
		WHEN 'SO' THEN N'Solicitando Autorización'
		ELSE N''
	END AS NOMBRE_ESTADO_DOCUMENTO,
	A.ESTA_CONTABILIZADO,
	A.CANTIDAD_LETRAS,
	A.USUARIO_CREA,
	A.FECHA_CREA,
	A.ESTACION_CREA,
	A.USUARIO_ACTU,
	A.FECHA_ACTU,
	A.ESTACION_ACTU,
	ISNULL(A.CORR_TIPO_CHEQUE, 0) CORR_TIPO_CHEQUE,
	ISNULL(E.CLASE_TIPO_CHEQUE, '') CLASE_TIPO_CHEQUE,
	ISNULL(E.NOMBRE_TIPO_CHEQUE, '') NOMBRE_TIPO_CHEQUE,
	ISNULL(A.CORR_CHEQUERA, 0) CORR_CHEQUERA,
	ISNULL(A.SERIE_CHEQUE, '') SERIE_CHEQUE,
	ISNULL(A.CORR_CUENTA_BANCO_DESTINO, 0) CORR_CUENTA_BANCO_DESTINO,
	ISNULL(F.NOMBRE_CUENTA_BANCO, '') NOMBRE_CUENTA_BANCO_DESTINO,
	ISNULL(A.NUMERO_CUENTA_DESTINO_TERCERO, '') NUMERO_CUENTA_DESTINO_TERCERO,
	ISNULL(A.MONTO_DESTINO, 0) MONTO_DESTINO,
	ISNULL(A.CORR_MONEDA, 0) CORR_MONEDA,
	ISNULL(A.FACTOR_CAMBIO, 1) FACTOR_CAMBIO,
	ISNULL(A.OPERADOR, '*') OPERADOR,
	A.FECHA_IMPRESO,
	A.FECHA_ANULACION
FROM dbo.BAN_DOCUMENTO A
INNER JOIN dbo.BAN_TIPO_MOVI_BANCARIO B
	ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO
INNER JOIN dbo.V_BAN_CUENTA_BANCARIA C
	ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CORR_CUENTA_BANCO = C.CORR_CUENTA_BANCO
LEFT JOIN dbo.V_BAN_TIPO_CHEQUE E
	ON A.CORR_EMPRESA = E.CORR_EMPRESA AND A.CORR_TIPO_CHEQUE = E.CORR_TIPO_CHEQUE
LEFT JOIN dbo.V_BAN_CUENTA_BANCARIA F
	ON A.CORR_EMPRESA = F.CORR_EMPRESA AND A.CORR_CUENTA_BANCO_DESTINO = F.CORR_CUENTA_BANCO;
GO

/* ── Vista detalle ── */
IF OBJECT_ID(N'dbo.V_BAN_DOCUMENTO_DETA', N'V') IS NOT NULL
	DROP VIEW [dbo].[V_BAN_DOCUMENTO_DETA];
GO

CREATE VIEW [dbo].[V_BAN_DOCUMENTO_DETA]
AS
SELECT
	A.CORR_EMPRESA,
	A.ANIO_PERIODO,
	A.MES_PERIODO,
	A.CORR_TIPO_MOVIMIENTO,
	A.CORR_DOCUMENTO,
	A.CORR_DOCUMENTO_DETA,
	A.CUENTA_CONTABLE,
	ISNULL(C.NOMBRE_CUENTA, '') NOMBRE_CUENTA,
	ISNULL(A.CORR_CENTRO_COSTO, 0) CORR_CENTRO_COSTO,
	ISNULL(D.NOMBRE_CENTRO, '') NOMBRE_CENTRO,
	A.NOMBRE_TRAN,
	A.MONTO_CARGO,
	A.MONTO_ABONO
FROM dbo.BAN_DOCUMENTO_DETA A
LEFT JOIN dbo.CON_CATALOGO_CUENTA C
	ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CUENTA_CONTABLE = C.CUENTA_CONTABLE
LEFT JOIN dbo.CON_CENTRO_COSTO D
	ON A.CORR_EMPRESA = D.CORR_EMPRESA AND A.CORR_CENTRO_COSTO = D.CORR_CENTRO_COSTO;
GO

/* ── MTTO encabezado ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_DOCUMENTO', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT = NULL,
	@CORR_DOCUMENTO INT OUTPUT,
	@CORR_CUENTA_BANCO INT = NULL,
	@NUMERO_DOCUMENTO BIGINT = 0,
	@FECHA_EMISION DATE = NULL,
	@NOMBRE_PARTIDA VARCHAR(1000) = '',
	@CORR_PROVEEDOR INT = NULL,
	@CORR_EMPLEADO INT = NULL,
	@CORR_CLIENTE INT = NULL,
	@NOMBRE_BENEFICIARIO VARCHAR(255) = NULL,
	@MONTO_DOCUMENTO DECIMAL(18, 2) = 0,
	@ESTADO_DOCUMENTO VARCHAR(2) = 'DI',
	@ESTA_CONTABILIZADO BIT = 0,
	@CANTIDAD_LETRAS VARCHAR(255) = '',
	@USUARIO_CREA VARCHAR(30) = '',
	@FECHA_CREA DATETIME = NULL,
	@ESTACION_CREA VARCHAR(50) = '',
	@USUARIO_ACTU VARCHAR(30) = NULL,
	@FECHA_ACTU DATETIME = NULL,
	@ESTACION_ACTU VARCHAR(50) = NULL,
	@CORR_TIPO_CHEQUE INT = NULL,
	@CORR_CHEQUERA INT = NULL,
	@SERIE_CHEQUE VARCHAR(10) = NULL,
	@CORR_CUENTA_BANCO_DESTINO INT = NULL,
	@NUMERO_CUENTA_DESTINO_TERCERO VARCHAR(50) = NULL,
	@MONTO_DESTINO DECIMAL(18, 2) = 0,
	@CORR_MONEDA INT = NULL,
	@FACTOR_CAMBIO DECIMAL(16, 6) = 1,
	@OPERADOR VARCHAR(2) = '*',
	@GENERA_DETALLE BIT = 1,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1, 2)
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM dbo.CON_PERIODO_CONTABLE
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No existe el periodo contable seleccionado', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF NOT EXISTS (
				SELECT 1 FROM dbo.CON_PERIODO_CONTABLE
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
					AND ISNULL(ESTADO_PERIODO_BAN, 'AB') = 'AB'
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El periodo bancario no está abierto', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF @CORR_TIPO_MOVIMIENTO IS NULL OR NOT EXISTS (
				SELECT 1 FROM dbo.BAN_TIPO_MOVI_BANCARIO
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No existe el tipo de movimiento seleccionado', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF @CORR_CUENTA_BANCO IS NULL OR NOT EXISTS (
				SELECT 1 FROM dbo.BAN_CUENTA_BANCARIA
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No existe la cuenta bancaria seleccionada', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF LTRIM(RTRIM(ISNULL(@NOMBRE_PARTIDA, ''))) = ''
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Debe especificar el concepto del documento', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF ISNULL(@MONTO_DOCUMENTO, 0) < 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El monto del documento no puede ser negativo', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			DECLARE @CLASE_MOVIMIENTO VARCHAR(10);
			SELECT @CLASE_MOVIMIENTO = CLASE_MOVIMIENTO
			FROM dbo.BAN_TIPO_MOVI_BANCARIO
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO;

			IF @CLASE_MOVIMIENTO = 'TPR'
			BEGIN
				IF ISNULL(@CORR_CUENTA_BANCO_DESTINO, 0) <= 0
				BEGIN
					SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Debe seleccionar la cuenta bancaria destino', @SYS_FILAS_AFECTADAS = 0;
					GOTO FINA;
				END;

				IF @CORR_CUENTA_BANCO_DESTINO = @CORR_CUENTA_BANCO
				BEGIN
					SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'La cuenta destino debe ser diferente a la cuenta origen', @SYS_FILAS_AFECTADAS = 0;
					GOTO FINA;
				END;

				IF NOT EXISTS (
					SELECT 1 FROM dbo.BAN_CUENTA_BANCARIA
					WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO_DESTINO
				)
				BEGIN
					SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No existe la cuenta bancaria destino seleccionada', @SYS_FILAS_AFECTADAS = 0;
					GOTO FINA;
				END;

				IF ISNULL(@NUMERO_CUENTA_DESTINO_TERCERO, '') = ''
				BEGIN
					SELECT @NUMERO_CUENTA_DESTINO_TERCERO = ISNULL(NUMERO_CUENTA_BANCO, '')
					FROM dbo.BAN_CUENTA_BANCARIA
					WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO_DESTINO;
				END;

				SET @MONTO_DESTINO = ISNULL(NULLIF(@MONTO_DESTINO, 0), @MONTO_DOCUMENTO);
			END
			ELSE IF @CLASE_MOVIMIENTO = 'TTE'
			BEGIN
				SET @CORR_CUENTA_BANCO_DESTINO = NULL;

				IF LTRIM(RTRIM(ISNULL(@NUMERO_CUENTA_DESTINO_TERCERO, ''))) = ''
				BEGIN
					SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Debe indicar la cuenta bancaria destino del tercero', @SYS_FILAS_AFECTADAS = 0;
					GOTO FINA;
				END;

				SET @MONTO_DESTINO = ISNULL(NULLIF(@MONTO_DESTINO, 0), @MONTO_DOCUMENTO);
			END
			ELSE
			BEGIN
				SET @CORR_CUENTA_BANCO_DESTINO = NULL;
				SET @NUMERO_CUENTA_DESTINO_TERCERO = NULL;
				SET @MONTO_DESTINO = 0;
			END;

			IF @CLASE_MOVIMIENTO IN ('TPR', 'TTE') AND ISNULL(@MONTO_DESTINO, 0) <= 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Debe indicar el monto destino', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			DECLARE @NOMBRE_MONEDA VARCHAR(100) = N'DÓLARES';
			IF OBJECT_ID(N'dbo.GEN_TIPO_MONEDA', N'U') IS NOT NULL
			BEGIN
				SELECT @NOMBRE_MONEDA = ISNULL(M.NOMBRE_MONEDA, @NOMBRE_MONEDA)
				FROM dbo.GEN_TIPO_MONEDA M
				WHERE M.CORR_MONEDA = ISNULL(@CORR_MONEDA, 0);
			END

			DECLARE @sFraccion VARCHAR(15) = '00' + LTRIM(CAST(CAST(((@MONTO_DOCUMENTO - CAST(@MONTO_DOCUMENTO AS INT)) * 100) AS INT) AS VARCHAR(15)));
			SELECT @CANTIDAD_LETRAS = dbo.FN_NUMEROS_A_LETRAS(@MONTO_DOCUMENTO, 1) + N' ' + @NOMBRE_MONEDA
				+ N' CON ' + SUBSTRING(@sFraccion, LEN(@sFraccion) - 1, 2) + N'/100';
		END;

		IF @TIPO_ACTUALIZA IN (2, 3)
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM dbo.BAN_DOCUMENTO
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
					AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
					AND ESTADO_DOCUMENTO = 'DI'
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El documento no puede modificarse o eliminarse (estado distinto de Digitado)', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		IF @TIPO_ACTUALIZA = 1
		BEGIN
			SELECT @CORR_DOCUMENTO = ISNULL(MAX(CORR_DOCUMENTO), 0) + 1
			FROM dbo.BAN_DOCUMENTO
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO;

			SET @ESTADO_DOCUMENTO = 'DI';
			SET @ESTA_CONTABILIZADO = 0;
			SET @FECHA_CREA = ISNULL(@FECHA_CREA, GETDATE());
			SET @USUARIO_ACTU = @USUARIO_CREA;
			SET @FECHA_ACTU = @FECHA_CREA;
			SET @ESTACION_ACTU = @ESTACION_CREA;

			INSERT INTO dbo.BAN_DOCUMENTO
			(
				CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_TIPO_MOVIMIENTO, CORR_DOCUMENTO,
				CORR_CUENTA_BANCO, NUMERO_DOCUMENTO, FECHA_EMISION, NOMBRE_PARTIDA,
				CORR_PROVEEDOR, CORR_EMPLEADO, CORR_CLIENTE, NOMBRE_BENEFICIARIO,
				MONTO_DOCUMENTO, ESTADO_DOCUMENTO, ESTA_CONTABILIZADO, CANTIDAD_LETRAS,
				USUARIO_CREA, FECHA_CREA, ESTACION_CREA, USUARIO_ACTU, FECHA_ACTU, ESTACION_ACTU,
				CORR_TIPO_CHEQUE, CORR_CHEQUERA, SERIE_CHEQUE, CORR_CUENTA_BANCO_DESTINO,
				NUMERO_CUENTA_DESTINO_TERCERO, MONTO_DESTINO, CORR_MONEDA, FACTOR_CAMBIO, OPERADOR
			)
			VALUES
			(
				@CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, @CORR_TIPO_MOVIMIENTO, @CORR_DOCUMENTO,
				@CORR_CUENTA_BANCO, ISNULL(@NUMERO_DOCUMENTO, 0), @FECHA_EMISION, @NOMBRE_PARTIDA,
				@CORR_PROVEEDOR, @CORR_EMPLEADO, @CORR_CLIENTE, @NOMBRE_BENEFICIARIO,
				@MONTO_DOCUMENTO, @ESTADO_DOCUMENTO, @ESTA_CONTABILIZADO, @CANTIDAD_LETRAS,
				@USUARIO_CREA, @FECHA_CREA, @ESTACION_CREA, @USUARIO_ACTU, @FECHA_ACTU, @ESTACION_ACTU,
				@CORR_TIPO_CHEQUE, @CORR_CHEQUERA, @SERIE_CHEQUE, @CORR_CUENTA_BANCO_DESTINO,
				@NUMERO_CUENTA_DESTINO_TERCERO, @MONTO_DESTINO, @CORR_MONEDA, @FACTOR_CAMBIO, @OPERADOR
			);

			IF ISNULL(@GENERA_DETALLE, 1) = 1
			BEGIN
				EXEC dbo.PRAL_GENE_BAN_DOCUMENTO_DETA
					@CORR_EMPRESA = @CORR_EMPRESA,
					@ANIO_PERIODO = @ANIO_PERIODO,
					@MES_PERIODO = @MES_PERIODO,
					@CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO,
					@CORR_DOCUMENTO = @CORR_DOCUMENTO,
					@SYS_LOGIN_USUARIO = @SYS_LOGIN_USUARIO,
					@SYS_ESTACION = @SYS_ESTACION,
					@SYS_FILAS_AFECTADAS = @SYS_FILAS_AFECTADAS OUTPUT,
					@SYS_NUMERO_ERROR = @SYS_NUMERO_ERROR OUTPUT,
					@SYS_MENSAJE_ERROR = @SYS_MENSAJE_ERROR OUTPUT;

				IF @SYS_NUMERO_ERROR <> 0
				BEGIN
					DELETE FROM dbo.BAN_DOCUMENTO_DETA
					WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
						AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

					DELETE FROM dbo.BAN_DOCUMENTO
					WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
						AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

					GOTO FINA;
				END;
			END;
		END
		ELSE IF @TIPO_ACTUALIZA = 2
		BEGIN
			UPDATE dbo.BAN_DOCUMENTO SET
				CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO,
				NUMERO_DOCUMENTO = @NUMERO_DOCUMENTO,
				FECHA_EMISION = @FECHA_EMISION,
				NOMBRE_PARTIDA = @NOMBRE_PARTIDA,
				CORR_PROVEEDOR = @CORR_PROVEEDOR,
				CORR_EMPLEADO = @CORR_EMPLEADO,
				CORR_CLIENTE = @CORR_CLIENTE,
				NOMBRE_BENEFICIARIO = @NOMBRE_BENEFICIARIO,
				MONTO_DOCUMENTO = @MONTO_DOCUMENTO,
				CANTIDAD_LETRAS = @CANTIDAD_LETRAS,
				USUARIO_ACTU = @USUARIO_ACTU,
				FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE()),
				ESTACION_ACTU = @ESTACION_ACTU,
				CORR_TIPO_CHEQUE = @CORR_TIPO_CHEQUE,
				CORR_CHEQUERA = @CORR_CHEQUERA,
				SERIE_CHEQUE = @SERIE_CHEQUE,
				CORR_CUENTA_BANCO_DESTINO = @CORR_CUENTA_BANCO_DESTINO,
				NUMERO_CUENTA_DESTINO_TERCERO = @NUMERO_CUENTA_DESTINO_TERCERO,
				MONTO_DESTINO = @MONTO_DESTINO,
				CORR_MONEDA = @CORR_MONEDA,
				FACTOR_CAMBIO = @FACTOR_CAMBIO,
				OPERADOR = @OPERADOR
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;
		END
		ELSE IF @TIPO_ACTUALIZA = 3
		BEGIN
			DELETE FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

			DELETE FROM dbo.BAN_DOCUMENTO
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── MTTO detalle ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_DOCUMENTO_DETA', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_DETA];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_DETA]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@CORR_DOCUMENTO_DETA INT OUTPUT,
	@CUENTA_CONTABLE VARCHAR(30),
	@CORR_CENTRO_COSTO INT = NULL,
	@NOMBRE_TRAN VARCHAR(1255),
	@MONTO_CARGO DECIMAL(12, 2) = 0,
	@MONTO_ABONO DECIMAL(12, 2) = 0,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		IF @TIPO_ACTUALIZA IN (1, 2, 3)
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM dbo.BAN_DOCUMENTO
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
					AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
					AND ESTADO_DOCUMENTO = 'DI'
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El documento no está en estado Digitado', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		IF @TIPO_ACTUALIZA IN (1, 2)
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM dbo.CON_CATALOGO_CUENTA
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CUENTA_CONTABLE = @CUENTA_CONTABLE
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No existe la cuenta contable', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		IF @TIPO_ACTUALIZA = 1
		BEGIN
			SELECT @CORR_DOCUMENTO_DETA = ISNULL(MAX(CORR_DOCUMENTO_DETA), 0) + 1
			FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

			INSERT INTO dbo.BAN_DOCUMENTO_DETA
			(CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_TIPO_MOVIMIENTO, CORR_DOCUMENTO, CORR_DOCUMENTO_DETA,
			 CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
			VALUES
			(@CORR_EMPRESA, @ANIO_PERIODO, @MES_PERIODO, @CORR_TIPO_MOVIMIENTO, @CORR_DOCUMENTO, @CORR_DOCUMENTO_DETA,
			 @CUENTA_CONTABLE, @CORR_CENTRO_COSTO, @NOMBRE_TRAN, @MONTO_CARGO, @MONTO_ABONO);
		END
		ELSE IF @TIPO_ACTUALIZA = 2
		BEGIN
			UPDATE dbo.BAN_DOCUMENTO_DETA SET
				CUENTA_CONTABLE = @CUENTA_CONTABLE,
				CORR_CENTRO_COSTO = @CORR_CENTRO_COSTO,
				NOMBRE_TRAN = @NOMBRE_TRAN,
				MONTO_CARGO = @MONTO_CARGO,
				MONTO_ABONO = @MONTO_ABONO
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
				AND CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA;
		END
		ELSE IF @TIPO_ACTUALIZA = 3
		BEGIN
			DELETE FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
				AND CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA;
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Generador automático detalle contable ── */
IF OBJECT_ID(N'dbo.PRAL_GENE_BAN_DOCUMENTO_DETA', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_GENE_BAN_DOCUMENTO_DETA];
GO

CREATE PROCEDURE [dbo].[PRAL_GENE_BAN_DOCUMENTO_DETA]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE
		@CLASE_MOVIMIENTO VARCHAR(3),
		@SUMA_RESTA INT,
		@CORR_CUENTA_BANCO INT,
		@MONTO_DOCUMENTO DECIMAL(18, 2),
		@NOMBRE_BENEFICIARIO VARCHAR(255),
		@NOMBRE_PARTIDA VARCHAR(1000),
		@NOMBRE_TRAN VARCHAR(1255),
		@CLASE_TIPO_CHEQUE VARCHAR(2),
		@CORR_TIPO_CHEQUE INT,
		@CUENTA_CONTABLE_TIPO_CHEQUE VARCHAR(30),
		@CORR_DOCUMENTO_DETA INT,
		@CUENTA_CONTABLE VARCHAR(30),
		@CORR_CENTRO_COSTO INT,
		@MONTO_CARGO DECIMAL(12, 2),
		@MONTO_ABONO DECIMAL(12, 2);

	DECLARE @BAN_DOCUMENTO_DETA TABLE
	(
		CUENTA_CONTABLE VARCHAR(30) NOT NULL,
		CORR_CENTRO_COSTO INT NULL,
		NOMBRE_TRAN VARCHAR(1255) NOT NULL,
		MONTO_CARGO DECIMAL(12, 2) NOT NULL,
		MONTO_ABONO DECIMAL(12, 2) NOT NULL
	);

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		IF NOT EXISTS (
			SELECT 1 FROM dbo.BAN_DOCUMENTO
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
				AND ESTADO_DOCUMENTO = 'DI'
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El documento no está en estado Digitado', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF EXISTS (
			SELECT 1 FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El documento ya tiene detalle contable', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT
			@CORR_CUENTA_BANCO = CORR_CUENTA_BANCO,
			@MONTO_DOCUMENTO = MONTO_DOCUMENTO,
			@NOMBRE_BENEFICIARIO = ISNULL(NOMBRE_BENEFICIARIO, ''),
			@NOMBRE_PARTIDA = ISNULL(NOMBRE_PARTIDA, ''),
			@CLASE_TIPO_CHEQUE = ISNULL(CLASE_TIPO_CHEQUE, ''),
			@CORR_TIPO_CHEQUE = ISNULL(CORR_TIPO_CHEQUE, 0)
		FROM dbo.V_BAN_DOCUMENTO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SELECT @CLASE_MOVIMIENTO = CLASE_MOVIMIENTO, @SUMA_RESTA = SUMA_RESTA
		FROM dbo.BAN_TIPO_MOVI_BANCARIO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO;

		SET @NOMBRE_TRAN = LTRIM(RTRIM(@NOMBRE_BENEFICIARIO + N' ' + @NOMBRE_PARTIDA));

		IF ISNULL(@MONTO_DOCUMENTO, 0) <= 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El monto del documento debe ser mayor a cero para generar detalle', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF @CLASE_MOVIMIENTO = 'CHQ'
		BEGIN
			IF ISNULL(@CORR_TIPO_CHEQUE, 0) = 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Debe seleccionar el tipo de cheque', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			SELECT @CUENTA_CONTABLE_TIPO_CHEQUE = ISNULL(CUENTA_CONTABLE, '')
			FROM dbo.BAN_TIPO_CHEQUE
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_TIPO_CHEQUE = @CORR_TIPO_CHEQUE;

			INSERT INTO @BAN_DOCUMENTO_DETA (CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
			SELECT A.CUENTA_CONTABLE, A.CORR_CENTRO_COSTO, @NOMBRE_TRAN, 0, @MONTO_DOCUMENTO
			FROM dbo.BAN_CUENTA_BANCARIA A
			WHERE A.CORR_EMPRESA = @CORR_EMPRESA AND A.CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO;

			IF @@ROWCOUNT = 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No se encontró la cuenta bancaria del documento', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			IF LTRIM(RTRIM(ISNULL(@CUENTA_CONTABLE_TIPO_CHEQUE, ''))) <> ''
			BEGIN
				INSERT INTO @BAN_DOCUMENTO_DETA (CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
				VALUES (@CUENTA_CONTABLE_TIPO_CHEQUE, NULL, @NOMBRE_TRAN, @MONTO_DOCUMENTO, 0);
			END;
		END
		ELSE
		BEGIN
			INSERT INTO @BAN_DOCUMENTO_DETA (CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN, MONTO_CARGO, MONTO_ABONO)
			SELECT
				A.CUENTA_CONTABLE,
				A.CORR_CENTRO_COSTO,
				@NOMBRE_TRAN,
				CASE WHEN @SUMA_RESTA = 1 THEN @MONTO_DOCUMENTO ELSE 0 END,
				CASE WHEN @SUMA_RESTA = 1 THEN 0 ELSE @MONTO_DOCUMENTO END
			FROM dbo.BAN_CUENTA_BANCARIA A
			WHERE A.CORR_EMPRESA = @CORR_EMPRESA AND A.CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO;

			IF @@ROWCOUNT = 0
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No se encontró la cuenta bancaria del documento', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;
		END;

		WHILE EXISTS (SELECT 1 FROM @BAN_DOCUMENTO_DETA)
		BEGIN
			SELECT TOP 1
				@CORR_DOCUMENTO_DETA = 0,
				@CUENTA_CONTABLE = CUENTA_CONTABLE,
				@CORR_CENTRO_COSTO = CORR_CENTRO_COSTO,
				@NOMBRE_TRAN = NOMBRE_TRAN,
				@MONTO_CARGO = MONTO_CARGO,
				@MONTO_ABONO = MONTO_ABONO
			FROM @BAN_DOCUMENTO_DETA
			ORDER BY CUENTA_CONTABLE, MONTO_CARGO DESC, MONTO_ABONO DESC;

			EXEC dbo.PRAL_MTTO_BAN_DOCUMENTO_DETA
				@TIPO_ACTUALIZA = 1,
				@CORR_EMPRESA = @CORR_EMPRESA,
				@ANIO_PERIODO = @ANIO_PERIODO,
				@MES_PERIODO = @MES_PERIODO,
				@CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO,
				@CORR_DOCUMENTO = @CORR_DOCUMENTO,
				@CORR_DOCUMENTO_DETA = @CORR_DOCUMENTO_DETA OUTPUT,
				@CUENTA_CONTABLE = @CUENTA_CONTABLE,
				@CORR_CENTRO_COSTO = @CORR_CENTRO_COSTO,
				@NOMBRE_TRAN = @NOMBRE_TRAN,
				@MONTO_CARGO = @MONTO_CARGO,
				@MONTO_ABONO = @MONTO_ABONO,
				@SYS_LOGIN_USUARIO = @SYS_LOGIN_USUARIO,
				@SYS_ESTACION = @SYS_ESTACION,
				@SYS_FILAS_AFECTADAS = @SYS_FILAS_AFECTADAS OUTPUT,
				@SYS_NUMERO_ERROR = @SYS_NUMERO_ERROR OUTPUT,
				@SYS_MENSAJE_ERROR = @SYS_MENSAJE_ERROR OUTPUT;

			IF @SYS_NUMERO_ERROR <> 0
				GOTO FINA;

			;WITH CTE AS
			(
				SELECT TOP 1 *
				FROM @BAN_DOCUMENTO_DETA
				ORDER BY CUENTA_CONTABLE, MONTO_CARGO DESC, MONTO_ABONO DESC
			)
			DELETE FROM CTE;
		END;

		SET @SYS_FILAS_AFECTADAS = (
			SELECT COUNT(1) FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
		);
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Aplicar documento ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_DOCUMENTO_APLICAR', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_APLICAR];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_APLICAR]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @ESTADO VARCHAR(2), @MONTO_CARGO DECIMAL(18, 2), @MONTO_ABONO DECIMAL(18, 2);
	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		SELECT @ESTADO = ESTADO_DOCUMENTO FROM dbo.BAN_DOCUMENTO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @ESTADO <> 'DI'
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Solo se pueden aplicar documentos en estado Digitado', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF NOT EXISTS (
			SELECT 1 FROM dbo.BAN_DOCUMENTO_DETA
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO
		)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El documento no tiene detalle contable', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT @MONTO_CARGO = SUM(MONTO_CARGO), @MONTO_ABONO = SUM(MONTO_ABONO)
		FROM dbo.BAN_DOCUMENTO_DETA
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF ISNULL(@MONTO_CARGO, 0) <> ISNULL(@MONTO_ABONO, 0)
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El detalle contable no está cuadrado (cargo ≠ abono)', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		UPDATE dbo.BAN_DOCUMENTO SET
			ESTADO_DOCUMENTO = 'AP',
			USUARIO_ACTU = @USUARIO_ACTU,
			FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE()),
			ESTACION_ACTU = @ESTACION_ACTU
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Anular documento ── */
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_DOCUMENTO_ANULAR', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_ANULAR];
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_BAN_DOCUMENTO_ANULAR]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @ESTADO VARCHAR(2);
	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		SELECT @ESTADO = ESTADO_DOCUMENTO FROM dbo.BAN_DOCUMENTO
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @ESTADO = 'AN'
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El documento ya está anulado', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		UPDATE dbo.BAN_DOCUMENTO SET
			ESTADO_DOCUMENTO = 'AN',
			FECHA_ANULACION = CAST(ISNULL(@FECHA_ACTU, GETDATE()) AS DATE),
			USUARIO_ACTU = @USUARIO_ACTU,
			FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE()),
			ESTACION_ACTU = @ESTACION_ACTU
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
			AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

/* ── Imprimir cheque ── */
IF OBJECT_ID(N'dbo.PRAL_IMPR_BAN_CHEQUE_IMPRIME', N'P') IS NOT NULL
	DROP PROCEDURE [dbo].[PRAL_IMPR_BAN_CHEQUE_IMPRIME];
GO

CREATE PROCEDURE [dbo].[PRAL_IMPR_BAN_CHEQUE_IMPRIME]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_MOVIMIENTO INT,
	@CORR_DOCUMENTO INT,
	@USUARIO_ACTU VARCHAR(30) = '',
	@FECHA_ACTU DATETIME = NULL,
	@ESTACION_ACTU VARCHAR(50) = '',
	@SYS_LOGIN_USUARIO VARCHAR(30) = '',
	@SYS_ESTACION VARCHAR(50) = '',
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @ESTADO VARCHAR(2), @CLASE_MOV VARCHAR(3), @CORR_CUENTA INT, @CORR_CHEQUERA INT,
		@NUMERO_CHEQUE INT, @SERIE VARCHAR(10), @CORR_TIPO_CHEQUE INT;

	SELECT @SYS_NUMERO_ERROR = 0, @SYS_MENSAJE_ERROR = N'', @SYS_FILAS_AFECTADAS = 0;
	SET @FECHA_ACTU = ISNULL(@FECHA_ACTU, GETDATE());

	BEGIN TRY
		SELECT @ESTADO = A.ESTADO_DOCUMENTO, @CORR_CUENTA = A.CORR_CUENTA_BANCO,
			@CORR_TIPO_CHEQUE = A.CORR_TIPO_CHEQUE, @CLASE_MOV = B.CLASE_MOVIMIENTO
		FROM dbo.BAN_DOCUMENTO A
		INNER JOIN dbo.BAN_TIPO_MOVI_BANCARIO B
			ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO
		WHERE A.CORR_EMPRESA = @CORR_EMPRESA AND A.ANIO_PERIODO = @ANIO_PERIODO AND A.MES_PERIODO = @MES_PERIODO
			AND A.CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND A.CORR_DOCUMENTO = @CORR_DOCUMENTO;

		IF @CLASE_MOV <> 'CHQ'
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'Solo se pueden imprimir documentos tipo Cheque', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF @ESTADO NOT IN ('AP', 'IM')
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El cheque debe estar aplicado para imprimir', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		SELECT TOP 1 @CORR_CHEQUERA = CORR_CHEQUERA, @NUMERO_CHEQUE = NUMERO_CHEQUE_ACTUAL, @SERIE = SERIE_CHEQUE
		FROM dbo.BAN_CHEQUERA
		WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA AND ESTADO_CHEQUERA = 'AC'
		ORDER BY CORR_CHEQUERA;

		IF ISNULL(@CORR_CHEQUERA, 0) = 0
		BEGIN
			SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'No hay chequera activa para la cuenta bancaria', @SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END;

		IF @ESTADO = 'AP'
		BEGIN
			IF EXISTS (
				SELECT 1 FROM dbo.BAN_DOCUMENTO
				WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA
					AND CORR_CHEQUERA = @CORR_CHEQUERA AND SERIE_CHEQUE = @SERIE AND NUMERO_DOCUMENTO = @NUMERO_CHEQUE
					AND NOT (ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
						AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO)
			)
			BEGIN
				SELECT @SYS_NUMERO_ERROR = 30000, @SYS_MENSAJE_ERROR = N'El número de cheque ya fue utilizado', @SYS_FILAS_AFECTADAS = 0;
				GOTO FINA;
			END;

			UPDATE dbo.BAN_DOCUMENTO SET
				CORR_CHEQUERA = @CORR_CHEQUERA,
				NUMERO_DOCUMENTO = @NUMERO_CHEQUE,
				SERIE_CHEQUE = @SERIE,
				ESTADO_DOCUMENTO = 'IM',
				FECHA_IMPRESO = CAST(@FECHA_ACTU AS DATE),
				USUARIO_ACTU = @USUARIO_ACTU,
				FECHA_ACTU = @FECHA_ACTU,
				ESTACION_ACTU = @ESTACION_ACTU
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO_PERIODO AND MES_PERIODO = @MES_PERIODO
				AND CORR_TIPO_MOVIMIENTO = @CORR_TIPO_MOVIMIENTO AND CORR_DOCUMENTO = @CORR_DOCUMENTO;

			UPDATE dbo.BAN_CHEQUERA SET NUMERO_CHEQUE_ACTUAL = NUMERO_CHEQUE_ACTUAL + 1
			WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_CUENTA_BANCO = @CORR_CUENTA AND CORR_CHEQUERA = @CORR_CHEQUERA
				AND NUMERO_CHEQUE_ACTUAL < NUMERO_CHEQUE_FINAL;
		END;

		SET @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
	END TRY
	BEGIN CATCH
		SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(), @SYS_MENSAJE_ERROR = ERROR_MESSAGE(), @SYS_FILAS_AFECTADAS = 0;
	END CATCH;

FINA:
END
GO

PRINT N'DEPLOY_BAN_DOCUMENTO completado.';
GO
