/* =============================================================================
   DEPLOY — V_GEN_EMPLEADO con DUI/NIT desde documentos de persona
   Ejecutar en SGUEES (SSMS) antes de usar la grilla gen-empleado.
   ============================================================================= */
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE OR ALTER VIEW [dbo].[V_GEN_EMPLEADO]
AS
SELECT
	A.CORR_EMPRESA,
	A.CORR_EMPLEADO,
	A.CORR_PERSONA,
	A.CODIGO_EMPLEADO,
	ISNULL(PN.NOMBRE_COMPLETO, N'') AS NOMBRE_EMPLEADO,
	ISNULL(PN.PRIMER_NOMBRE, N'') AS NOMBRE_1,
	ISNULL(PN.SEGUNDO_NOMBRE, N'') AS NOMBRE_2,
	ISNULL(PN.PRIMER_APELLIDO, N'') AS APELLIDO_1,
	ISNULL(PN.SEGUNDO_APELLIDO, N'') AS APELLIDO_2,
	ISNULL(PN.APELLIDO_CASADA, N'') AS APELLIDO_3,
	ISNULL(DOC_DUI.VALOR_DOCUMENTO, N'') AS DUI,
	ISNULL(DOC_NIT.VALOR_DOCUMENTO, N'') AS NIT,
	ISNULL(A.CORREO_INSTITUCIONAL, N'') AS CORREO_ELECTRONICO,
	ISNULL(A.CORREO_INSTITUCIONAL, N'') AS CORREO_INSTITUCIONAL,
	ISNULL(A.TELEFONO_INSTITUCIONAL, N'') AS TELEFONO_1,
	ISNULL(A.TELEFONO_INSTITUCIONAL, N'') AS TELEFONO_INSTITUCIONAL,
	A.FECHA_INGRESO,
	CAST(0 AS INT) AS CORR_CENTRO_COSTO,
	CAST(0 AS INT) AS CORR_DEPARTAMENTO,
	ISNULL(EP.CORR_PUESTO, 0) AS CORR_PUESTO,
	CAST(ISNULL(A.ACTIVO_EMPLEADO, 0) AS BIT) AS ACTIVO_EMPLEADO,
	CAST(CASE WHEN ISNULL(A.ACTIVO_EMPLEADO, 0) = 1 THEN N'1' ELSE N'0' END AS VARCHAR(2)) AS ESTADO_EMPLEADO,
	CASE WHEN ISNULL(A.ACTIVO_EMPLEADO, 0) = 1 THEN N'Activo' ELSE N'Inactivo' END AS NOMBRE_ESTADO_EMPLEADO,
	ISNULL(PU.LOGIN_SISTEMA, N'') AS LOGIN_SISTEMA,
	ISNULL(PU.LOGIN_SISTEMA, N'') AS LOGIN_SISTEMA_WEB,
	A.USUARIO_CREA,
	A.FECHA_CREA,
	A.ESTACION_CREA,
	A.USUARIO_ACTU,
	A.FECHA_ACTU,
	A.ESTACION_ACTU
FROM dbo.GEN_EMPLEADO A
LEFT JOIN dbo.GEN_PERSONA_NATURAL PN
	ON PN.CORR_PERSONA = A.CORR_PERSONA
OUTER APPLY
(
	SELECT TOP (1) U.LOGIN_SISTEMA
	FROM dbo.GEN_PERSONA_USUARIO U
	WHERE U.CORR_PERSONA = A.CORR_PERSONA
	ORDER BY U.LOGIN_SISTEMA
) PU
OUTER APPLY
(
	SELECT TOP (1) P.CORR_PUESTO
	FROM dbo.GEN_EMPLEADO_PUESTO P
	WHERE P.CORR_EMPRESA = A.CORR_EMPRESA
	  AND P.CORR_EMPLEADO = A.CORR_EMPLEADO
	ORDER BY
		P.FECHA_INGRESO DESC,
		P.FECHA_CREA DESC,
		P.CORR_PUESTO DESC
) EP
OUTER APPLY
(
	SELECT TOP (1) PD.VALOR_DOCUMENTO
	FROM dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD PD
	INNER JOIN dbo.GEN_TIPO_DOCUMENTO_IDENTIDAD TD
		ON TD.CORR_TIPO_DOCUMENTO_IDENTIDAD = PD.CORR_TIPO_DOCUMENTO_IDENTIDAD
	WHERE PD.CORR_PERSONA = A.CORR_PERSONA
	  AND PD.CORR_EMPRESA = A.CORR_EMPRESA
	  AND UPPER(LTRIM(RTRIM(TD.NOMBRE_CORTO))) = N'DUI'
	ORDER BY PD.FECHA_CREA DESC
) DOC_DUI
OUTER APPLY
(
	SELECT TOP (1) PD.VALOR_DOCUMENTO
	FROM dbo.GEN_PERSONA_TIPO_DOCUMENTO_IDENTIDAD PD
	INNER JOIN dbo.GEN_TIPO_DOCUMENTO_IDENTIDAD TD
		ON TD.CORR_TIPO_DOCUMENTO_IDENTIDAD = PD.CORR_TIPO_DOCUMENTO_IDENTIDAD
	WHERE PD.CORR_PERSONA = A.CORR_PERSONA
	  AND PD.CORR_EMPRESA = A.CORR_EMPRESA
	  AND UPPER(LTRIM(RTRIM(TD.NOMBRE_CORTO))) = N'NIT'
	ORDER BY PD.FECHA_CREA DESC
) DOC_NIT
GO

PRINT N'V_GEN_EMPLEADO actualizada (DUI/NIT/ACTIVO_EMPLEADO/FECHA_INGRESO).';
GO
