/*
  Conciliacion bancaria — tablas + vistas + SPs (adaptados desde e-Admin, CORR_EMPRESA only).
  Requiere: BAN_CUENTA_BANCARIA, BAN_LINEA_TRABAJO_CONCILIACION, V_BAN_CUENTA_BANCARIA,
            CON_PARTIDA/CON_PARTIDA_DETA, CON_CATALOGO_CUENTA_AUXI, BAN_PARTIDA_DETA (contabilizar).

  Uso:
    cd "C:\Desarrollo GIT\SGUEES\SGUEES-DB\Scripts"
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i DEPLOY_BAN_CONCILIA_BANCARIA.sql
*/
SET NOCOUNT ON;
GO

PRINT N'=== Tipo tabla Excel conciliacion ===';
IF TYPE_ID(N'dbo.T_BAN_CONCILIACION_BANCARIA_MOV_EXCEL') IS NULL
BEGIN
	CREATE TYPE [dbo].[T_BAN_CONCILIACION_BANCARIA_MOV_EXCEL] AS TABLE
	(
		[CORR] [int] NOT NULL,
		[NUMERO_REFERENCIA_BANCO] [varchar](255) COLLATE Latin1_General_CS_AS NOT NULL,
		[CODIGO_TIPO_MOVIMIENTO] [varchar](10) COLLATE Latin1_General_CS_AS NOT NULL,
		[NOMBRE_TIPO_MOVIMIENTO] [varchar](100) COLLATE Latin1_General_CS_AS NOT NULL,
		[FECHA_MOVIMIENTO] [datetime] NOT NULL,
		[MONTO_CARGO] [decimal](18, 2) NOT NULL,
		[MONTO_ABONO] [decimal](18, 2) NOT NULL,
		[SALDO] [decimal](18, 2) NOT NULL
	);
	PRINT N'Tipo T_BAN_CONCILIACION_BANCARIA_MOV_EXCEL creado.';
END
GO

PRINT N'=== Tabla BAN_CONCILIA_BANCARIA ===';
IF OBJECT_ID(N'dbo.BAN_CONCILIA_BANCARIA', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BAN_CONCILIA_BANCARIA]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[CORR_CUENTA_BANCO] [int] NOT NULL,
		[CORR_CONCILIACION] [int] NOT NULL,
		[FECHA_CONCILIACION] [date] NOT NULL,
		[SALDO_CUENTA_BANCO] [decimal](18, 2) NULL,
		[SALDO_CUENTA_CONTA] [decimal](18, 2) NULL,
		[ESTADO_CONCILIACION] [varchar](2) COLLATE Latin1_General_CS_AS NULL,
		[USUARIO_CREA] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
		[FECHA_CREA] [datetime] NOT NULL,
		[ESTACION_CREA] [varchar](50) COLLATE Latin1_General_CS_AS NOT NULL,
		[USUARIO_ACTU] [varchar](30) COLLATE Latin1_General_CS_AS NULL,
		[FECHA_ACTU] [datetime] NULL,
		[ESTACION_ACTU] [varchar](50) COLLATE Latin1_General_CS_AS NULL
	) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA]
		ADD CONSTRAINT [PK_BAN_CONCILIA_BANCARIA]
		PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION]) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA]
		ADD CONSTRAINT [FK_BAN_CONCILIA_BANCARIA_BAN_CUENTA_BANCARIA]
		FOREIGN KEY ([CORR_EMPRESA], [CORR_CUENTA_BANCO])
		REFERENCES [dbo].[BAN_CUENTA_BANCARIA] ([CORR_EMPRESA], [CORR_CUENTA_BANCO]);

	PRINT N'Tabla BAN_CONCILIA_BANCARIA creada.';
END
ELSE
	PRINT N'Tabla BAN_CONCILIA_BANCARIA ya existe.';
GO

PRINT N'=== Tabla BAN_CONCILIA_BANCARIA_DETA ===';
IF OBJECT_ID(N'dbo.BAN_CONCILIA_BANCARIA_DETA', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BAN_CONCILIA_BANCARIA_DETA]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[CORR_CUENTA_BANCO] [int] NOT NULL,
		[CORR_CONCILIACION] [int] NOT NULL,
		[CORR_CONCILIACION_DETA] [int] NOT NULL,
		[FECHA_MOVIMIENTO] [date] NOT NULL,
		[CORR_TIPO_MOVIMIENTO] [int] NOT NULL,
		[NUMERO_REFERENCIA_BANCO] [varchar](255) COLLATE Latin1_General_CS_AS NOT NULL,
		[MONTO_CARGO] [decimal](18, 2) NOT NULL,
		[MONTO_ABONO] [decimal](18, 2) NOT NULL,
		[ANIO_PERIODO] [int] NULL,
		[MES_PERIODO] [int] NULL,
		[CORR_CLASE_PARTIDA] [int] NULL,
		[CORR_PARTIDA] [int] NULL,
		[CORR_PARTIDA_DETA] [int] NULL,
		[CODIGO_TRANSACCION] [varchar](30) COLLATE Latin1_General_CS_AS NULL,
		[DESCRIPCION_TRANSACCION] [varchar](255) COLLATE Latin1_General_CS_AS NULL
	) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA_DETA]
		ADD CONSTRAINT [PK_BAN_CONCILIA_BANCARIA_DETA]
		PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION], [CORR_CONCILIACION_DETA]) ON [PRIMARY];

	CREATE NONCLUSTERED INDEX [IX_BAN_CONCILIA_BANCARIA_DETA_PARTIDA]
		ON [dbo].[BAN_CONCILIA_BANCARIA_DETA] ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_CLASE_PARTIDA], [CORR_PARTIDA], [CORR_PARTIDA_DETA])
		INCLUDE ([CORR_CUENTA_BANCO], [CORR_CONCILIACION]) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA_DETA]
		ADD CONSTRAINT [FK_BAN_CONCILIA_BANCARIA_DETA_BAN_CONCILIA_BANCARIA]
		FOREIGN KEY ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION])
		REFERENCES [dbo].[BAN_CONCILIA_BANCARIA] ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION]);

	PRINT N'Tabla BAN_CONCILIA_BANCARIA_DETA creada.';
END
ELSE
	PRINT N'Tabla BAN_CONCILIA_BANCARIA_DETA ya existe.';
GO

PRINT N'=== Tabla BAN_CONCILIA_BANCARIA_MOVI ===';
IF OBJECT_ID(N'dbo.BAN_CONCILIA_BANCARIA_MOVI', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BAN_CONCILIA_BANCARIA_MOVI]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[CORR_CUENTA_BANCO] [int] NOT NULL,
		[CORR_CONCILIACION] [int] NOT NULL,
		[CORR_MOVIMIENTO] [int] NOT NULL,
		[CORR_LINEA] [int] NOT NULL,
		[ANIO_PERIODO] [int] NULL,
		[MES_PERIODO] [int] NULL,
		[CORR_CLASE_PARTIDA] [int] NULL,
		[CORR_PARTIDA] [int] NULL,
		[CORR_PARTIDA_DETA] [int] NULL,
		[CORR_TIPO_MOVIMIENTO] [int] NULL,
		[CORR_CONCILIACION_DETA] [int] NULL,
		[MONTO_CARGO] [decimal](18, 2) NOT NULL,
		[MONTO_ABONO] [decimal](18, 2) NOT NULL
	) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA_MOVI]
		ADD CONSTRAINT [PK_BAN_CONCILIA_BANCARIA_MOVI]
		PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION], [CORR_MOVIMIENTO]) ON [PRIMARY];

	ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA_MOVI]
		ADD CONSTRAINT [FK_BAN_CONCILIA_BANCARIA_MOVI_BAN_CONCILIA_BANCARIA]
		FOREIGN KEY ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION])
		REFERENCES [dbo].[BAN_CONCILIA_BANCARIA] ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION]);

	ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA_MOVI]
		ADD CONSTRAINT [FK_BAN_CONCILIA_BANCARIA_MOVI_BAN_LINEA_TRABAJO_CONCILIACION]
		FOREIGN KEY ([CORR_EMPRESA], [CORR_LINEA])
		REFERENCES [dbo].[BAN_LINEA_TRABAJO_CONCILIACION] ([CORR_EMPRESA], [CORR_LINEA]);

	PRINT N'Tabla BAN_CONCILIA_BANCARIA_MOVI creada.';
END
ELSE
	PRINT N'Tabla BAN_CONCILIA_BANCARIA_MOVI ya existe.';
GO

PRINT N'=== Funcion NOMBRE_MES (requerida por V_BAN_CONCILIA_BANCARIA_IMPRIME) ===';
IF OBJECT_ID(N'dbo.NOMBRE_MES', N'FN') IS NULL
BEGIN
	EXEC(N'
CREATE FUNCTION [dbo].[NOMBRE_MES] (@MES INT)
RETURNS VARCHAR(255)
AS
BEGIN
	RETURN CASE @MES
		WHEN 1 THEN ''Enero'' WHEN 2 THEN ''Febrero'' WHEN 3 THEN ''Marzo'' WHEN 4 THEN ''Abril''
		WHEN 5 THEN ''Mayo'' WHEN 6 THEN ''Junio'' WHEN 7 THEN ''Julio'' WHEN 8 THEN ''Agosto''
		WHEN 9 THEN ''Septiembre'' WHEN 10 THEN ''Octubre'' WHEN 11 THEN ''Noviembre'' WHEN 12 THEN ''Diciembre''
		ELSE '''' END
END');
	PRINT N'Funcion NOMBRE_MES creada.';
END
GO

PRINT N'=== Vistas conciliacion BAN ===';
IF OBJECT_ID(N'dbo.V_BAN_CONCILIA_BANCARIA_MOVI_SUM', N'V') IS NOT NULL DROP VIEW dbo.V_BAN_CONCILIA_BANCARIA_MOVI_SUM;
GO
:r ..\Views\dbo.V_BAN_CONCILIA_BANCARIA_MOVI_SUM.sql
GO

IF OBJECT_ID(N'dbo.V_BAN_CONCILIA_PENDIENTE', N'V') IS NOT NULL DROP VIEW dbo.V_BAN_CONCILIA_PENDIENTE;
GO
:r ..\Views\dbo.V_BAN_CONCILIA_PENDIENTE.sql
GO

IF OBJECT_ID(N'dbo.V_BAN_CONCILIA_BANCARIA_DETA', N'V') IS NOT NULL DROP VIEW dbo.V_BAN_CONCILIA_BANCARIA_DETA;
GO
:r ..\Views\dbo.V_BAN_CONCILIA_BANCARIA_DETA.sql
GO

IF OBJECT_ID(N'dbo.V_BAN_CONCILIA_BANCARIA_MOVI', N'V') IS NOT NULL DROP VIEW dbo.V_BAN_CONCILIA_BANCARIA_MOVI;
GO
:r ..\Views\dbo.V_BAN_CONCILIA_BANCARIA_MOVI.sql
GO

IF OBJECT_ID(N'dbo.V_BAN_CONCILIA_BANCARIA', N'V') IS NOT NULL DROP VIEW dbo.V_BAN_CONCILIA_BANCARIA;
GO
:r ..\Views\dbo.V_BAN_CONCILIA_BANCARIA.sql
GO

IF OBJECT_ID(N'dbo.V_BAN_CONCILIA_BANCARIA_IMPRIME', N'V') IS NOT NULL DROP VIEW dbo.V_BAN_CONCILIA_BANCARIA_IMPRIME;
GO
:r ..\Views\dbo.V_BAN_CONCILIA_BANCARIA_IMPRIME.sql
GO

PRINT N'=== SP DATA conciliacion BAN ===';
IF OBJECT_ID(N'dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA;
GO
:r "..\Stored Procedures\dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_DETA', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_DETA;
GO
:r "..\Stored Procedures\dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_DETA.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_MOVI', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_MOVI;
GO
:r "..\Stored Procedures\dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_MOVI.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_PENDIENTE', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_PENDIENTE;
GO
:r "..\Stored Procedures\dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_PENDIENTE.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_RESUMEN', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_RESUMEN;
GO
:r "..\Stored Procedures\dbo.PRAL_DATA_BAN_CONCILIA_BANCARIA_RESUMEN.sql"
GO

PRINT N'=== SP GENE conciliacion BAN ===';
IF OBJECT_ID(N'dbo.PRAL_GENE_BAN_CONCILIACION_BANCARIA', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_GENE_BAN_CONCILIACION_BANCARIA;
GO
:r "..\Stored Procedures\dbo.PRAL_GENE_BAN_CONCILIACION_BANCARIA.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_GENE_BAN_CONCILIACION_BANCARIA_MOVI', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_GENE_BAN_CONCILIACION_BANCARIA_MOVI;
GO
:r "..\Stored Procedures\dbo.PRAL_GENE_BAN_CONCILIACION_BANCARIA_MOVI.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_GENE_BAN_CONCILIACION_FORZADA', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_GENE_BAN_CONCILIACION_FORZADA;
GO
:r "..\Stored Procedures\dbo.PRAL_GENE_BAN_CONCILIACION_FORZADA.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_GENE_BAN_CONCILIACION_REVERTIR', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_GENE_BAN_CONCILIACION_REVERTIR;
GO
:r "..\Stored Procedures\dbo.PRAL_GENE_BAN_CONCILIACION_REVERTIR.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_GENE_BAN_CONCILIA_BANCARIA_MOV_EXCEL', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_GENE_BAN_CONCILIA_BANCARIA_MOV_EXCEL;
GO
:r "..\Stored Procedures\dbo.PRAL_GENE_BAN_CONCILIA_BANCARIA_MOV_EXCEL.sql"
GO

PRINT N'=== SP IMPR conciliacion BAN ===';
IF OBJECT_ID(N'dbo.PRAL_IMPR_BAN_CONCILIA_BANCARIA', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_IMPR_BAN_CONCILIA_BANCARIA;
GO
:r "..\Stored Procedures\dbo.PRAL_IMPR_BAN_CONCILIA_BANCARIA.sql"
GO

PRINT N'=== SP MTTO conciliacion BAN ===';
IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA;
GO
:r "..\Stored Procedures\dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_APLICAR', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_APLICAR;
GO
:r "..\Stored Procedures\dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_APLICAR.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_DESAPLICAR', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_DESAPLICAR;
GO
:r "..\Stored Procedures\dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_DESAPLICAR.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_DETA', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_DETA;
GO
:r "..\Stored Procedures\dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_DETA.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_MARCAR', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_MARCAR;
GO
:r "..\Stored Procedures\dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_MARCAR.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_MOVI', N'P') IS NOT NULL DROP PROCEDURE dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_MOVI;
GO
:r "..\Stored Procedures\dbo.PRAL_MTTO_BAN_CONCILIA_BANCARIA_MOVI.sql"
GO

PRINT N'=== Objetos desplegados ===';
SELECT name, type_desc
FROM sys.objects
WHERE name IN (
	'BAN_CONCILIA_BANCARIA',
	'BAN_CONCILIA_BANCARIA_DETA',
	'BAN_CONCILIA_BANCARIA_MOVI',
	'V_BAN_CONCILIA_BANCARIA',
	'V_BAN_CONCILIA_BANCARIA_DETA',
	'V_BAN_CONCILIA_BANCARIA_MOVI',
	'V_BAN_CONCILIA_BANCARIA_MOVI_SUM',
	'V_BAN_CONCILIA_BANCARIA_IMPRIME',
	'V_BAN_CONCILIA_PENDIENTE',
	'PRAL_DATA_BAN_CONCILIA_BANCARIA',
	'PRAL_DATA_BAN_CONCILIA_BANCARIA_DETA',
	'PRAL_DATA_BAN_CONCILIA_BANCARIA_MOVI',
	'PRAL_DATA_BAN_CONCILIA_BANCARIA_PENDIENTE',
	'PRAL_DATA_BAN_CONCILIA_BANCARIA_RESUMEN',
	'PRAL_GENE_BAN_CONCILIACION_BANCARIA',
	'PRAL_GENE_BAN_CONCILIACION_BANCARIA_MOVI',
	'PRAL_GENE_BAN_CONCILIACION_FORZADA',
	'PRAL_GENE_BAN_CONCILIACION_REVERTIR',
	'PRAL_GENE_BAN_CONCILIA_BANCARIA_MOV_EXCEL',
	'PRAL_IMPR_BAN_CONCILIA_BANCARIA',
	'PRAL_MTTO_BAN_CONCILIA_BANCARIA',
	'PRAL_MTTO_BAN_CONCILIA_BANCARIA_APLICAR',
	'PRAL_MTTO_BAN_CONCILIA_BANCARIA_DESAPLICAR',
	'PRAL_MTTO_BAN_CONCILIA_BANCARIA_DETA',
	'PRAL_MTTO_BAN_CONCILIA_BANCARIA_MARCAR',
	'PRAL_MTTO_BAN_CONCILIA_BANCARIA_MOVI'
)
ORDER BY name;
GO

PRINT N'DEPLOY_BAN_CONCILIA_BANCARIA completado.';
GO
