/* ============================================================================
   Deploy vistas + menú — PLA_AFP y PLA_SEGURO_SOCIAL
   Ejecutar en SGUEES (lectura de estructura ya validada; CREATE OR ALTER VIEW).
   ============================================================================ */
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER VIEW [dbo].[V_PLA_AFP]
AS
SELECT
	A.CORR_AFP,
	A.NOMBRE_AFP,
	A.NOMBRE_CORTO_AFP,
	A.CODIGO_SGVPP,
	ISNULL(A.INCLUYE_SEPP, 0) AS INCLUYE_SEPP,
	ISNULL(A.ACTIVO_AFP, 1) AS ACTIVO_AFP,
	A.USUARIO_CREA,
	A.ESTACION_CREA,
	A.FECHA_CREA,
	A.USUARIO_ACTU,
	A.ESTACION_ACTU,
	A.FECHA_ACTU
FROM dbo.PLA_AFP AS A;
GO

CREATE OR ALTER VIEW [dbo].[V_PLA_SEGURO_SOCIAL]
AS
SELECT
	S.CORR_SEGURO_SOCIAL,
	S.NOMBRE_SEGURO_SOCIAL,
	S.NOMBRE_CORTO_SEGURO,
	ISNULL(S.ACTIVO_SEGURO_SOCIAL, 1) AS ACTIVO_SEGURO_SOCIAL,
	S.USUARIO_CREA,
	S.ESTACION_CREA,
	S.FECHA_CREA,
	S.USUARIO_ACTU,
	S.ESTACION_ACTU,
	S.FECHA_ACTU
FROM dbo.PLA_SEGURO_SOCIAL AS S;
GO

PRINT N'Vistas V_PLA_AFP y V_PLA_SEGURO_SOCIAL desplegadas.';
GO

/* ============================================================================
   Menú — AFP (PLA_AFP) y Seguro Social (PLA_SEGURO_SOCIAL)
   Idempotente. Ubica las opciones junto a PLA_NIVEL_ACADEMICO si existe.
   Alternativa rápida (LOGIN juanh / SUITE SGUEES):

EXEC dbo.PR_SEG_ASIGNAR_OPCION_MENU
  @CODIGO_SISTEMA = 'TALENTOHUMANO',
  @CODIGO_MENU = 'GENERAL',
  @CODIGO_OPCION = 'PLA_AFP',
  @NOMBRE_OPCION = 'AFP',
  @URL_OPCION = '/pla-afp',
  @LOGIN_ASIGNA = 'juanh',
  @LOGIN_SISTEMA = 'juanh',
  @CODIGO_SUITE = 'SGUEES',
  @ORDEN_SISTEMA = 0,
  @ORDEN_MENU = 1,
  @ORDEN_OPCION = 10,
  @NUEVO = 1,
  @MODIFICAR = 1,
  @ELIMINAR = 1,
  @IMPRIMIR = 1;

EXEC dbo.PR_SEG_ASIGNAR_OPCION_MENU
  @CODIGO_SISTEMA = 'TALENTOHUMANO',
  @CODIGO_MENU = 'GENERAL',
  @CODIGO_OPCION = 'PLA_SEGURO_SOCIAL',
  @NOMBRE_OPCION = 'Seguro Social',
  @URL_OPCION = '/pla-seguro-social',
  @LOGIN_ASIGNA = 'juanh',
  @LOGIN_SISTEMA = 'juanh',
  @CODIGO_SUITE = 'SGUEES',
  @ORDEN_SISTEMA = 0,
  @ORDEN_MENU = 1,
  @ORDEN_OPCION = 11,
  @NUEVO = 1,
  @MODIFICAR = 1,
  @ELIMINAR = 1,
  @IMPRIMIR = 1;
   ============================================================================ */

DECLARE @SISTEMA     varchar(30);
DECLARE @MENU        varchar(10);
DECLARE @SUITE       varchar(30) = 'SGUEES';
DECLARE @ORD_MENU    int;
DECLARE @ORD_OPCION  int;
DECLARE @LOGIN       varchar(30) = 'juanh';
DECLARE @USR         varchar(30) = 'juanh';
DECLARE @EST         varchar(30) = 'SISTEMA';
DECLARE @HOY         datetime    = GETDATE();

SELECT TOP (1)
    @SISTEMA = c.CODIGO_SISTEMA,
    @MENU = c.CODIGO_MENU,
    @ORD_MENU = c.ORDEN_MENU,
    @ORD_OPCION = ISNULL(c.ORDEN_OPCION, 0) + 1
FROM SEG_CONFIG_OPCION AS c
WHERE c.CODIGO_OPCION = N'PLA_NIVEL_ACADEMICO'
ORDER BY c.ORDEN_SISTEMA, c.ORDEN_MENU, c.ORDEN_OPCION;

IF @SISTEMA IS NULL
BEGIN
    SELECT TOP (1)
        @SISTEMA = c.CODIGO_SISTEMA,
        @MENU = c.CODIGO_MENU,
        @ORD_MENU = c.ORDEN_MENU,
        @ORD_OPCION = ISNULL(MAX(c2.ORDEN_OPCION), 0) + 1
    FROM SEG_CONFIG_OPCION AS c
    LEFT JOIN SEG_CONFIG_OPCION AS c2
        ON c2.CODIGO_SISTEMA = c.CODIGO_SISTEMA
       AND c2.CODIGO_MENU = c.CODIGO_MENU
    WHERE c.CODIGO_OPCION LIKE N'PLA_%'
    GROUP BY c.CODIGO_SISTEMA, c.CODIGO_MENU, c.ORDEN_MENU
    ORDER BY c.CODIGO_SISTEMA, c.ORDEN_MENU;
END;

IF @SISTEMA IS NULL OR @MENU IS NULL
BEGIN
    RAISERROR(N'No se pudo determinar CODIGO_SISTEMA/CODIGO_MENU para opciones PLA_*. Configure el menú manualmente.', 16, 1);
    RETURN;
END;

-- PLA_AFP
MERGE SEG_OPCION_SISTEMA AS T
USING (VALUES (N'PLA_AFP', N'AFP', N'/pla-afp')) AS S (CODIGO, NOMBRE, URL)
ON T.CODIGO_OPCION = S.CODIGO
WHEN MATCHED THEN
    UPDATE SET T.NOMBRE_OPCION = S.NOMBRE,
               T.URL_OPCION = S.URL,
               T.IMAGEN_OPCION = '',
               T.USUARIO_ACTU = @USR,
               T.FECHA_ACTU = @HOY,
               T.ESTACION_ACTU = @EST
WHEN NOT MATCHED THEN
    INSERT (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION, IMAGEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
    VALUES (S.CODIGO, S.NOMBRE, S.URL, '', @USR, @HOY, @EST);

INSERT INTO SEG_OPCION_SISTEMA_SUITE (CODIGO_OPCION, CODIGO_SUITE)
SELECT N'PLA_AFP', @SUITE
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_OPCION_SISTEMA_SUITE s
    WHERE s.CODIGO_OPCION = N'PLA_AFP' AND s.CODIGO_SUITE = @SUITE
);

DELETE FROM SEG_CONFIG_OPCION WHERE CODIGO_OPCION = N'PLA_AFP';

INSERT INTO SEG_CONFIG_OPCION
    (CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
VALUES (@SISTEMA, @MENU, N'PLA_AFP', 0, @ORD_MENU, @ORD_OPCION, @USR, @HOY, @EST);

INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT @LOGIN, @SISTEMA, @MENU, N'PLA_AFP', 1, 1, 1, 1, @USR, @HOY, @EST
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_USUARIO_OPCION u
    WHERE u.LOGIN_SISTEMA = @LOGIN
      AND u.CODIGO_SISTEMA = @SISTEMA
      AND u.CODIGO_MENU = @MENU
      AND u.CODIGO_OPCION = N'PLA_AFP'
);

SET @ORD_OPCION = @ORD_OPCION + 1;

-- PLA_SEGURO_SOCIAL
MERGE SEG_OPCION_SISTEMA AS T
USING (VALUES (N'PLA_SEGURO_SOCIAL', N'Seguro Social', N'/pla-seguro-social')) AS S (CODIGO, NOMBRE, URL)
ON T.CODIGO_OPCION = S.CODIGO
WHEN MATCHED THEN
    UPDATE SET T.NOMBRE_OPCION = S.NOMBRE,
               T.URL_OPCION = S.URL,
               T.IMAGEN_OPCION = '',
               T.USUARIO_ACTU = @USR,
               T.FECHA_ACTU = @HOY,
               T.ESTACION_ACTU = @EST
WHEN NOT MATCHED THEN
    INSERT (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION, IMAGEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
    VALUES (S.CODIGO, S.NOMBRE, S.URL, '', @USR, @HOY, @EST);

INSERT INTO SEG_OPCION_SISTEMA_SUITE (CODIGO_OPCION, CODIGO_SUITE)
SELECT N'PLA_SEGURO_SOCIAL', @SUITE
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_OPCION_SISTEMA_SUITE s
    WHERE s.CODIGO_OPCION = N'PLA_SEGURO_SOCIAL' AND s.CODIGO_SUITE = @SUITE
);

DELETE FROM SEG_CONFIG_OPCION WHERE CODIGO_OPCION = N'PLA_SEGURO_SOCIAL';

INSERT INTO SEG_CONFIG_OPCION
    (CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
VALUES (@SISTEMA, @MENU, N'PLA_SEGURO_SOCIAL', 0, @ORD_MENU, @ORD_OPCION, @USR, @HOY, @EST);

INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT @LOGIN, @SISTEMA, @MENU, N'PLA_SEGURO_SOCIAL', 1, 1, 1, 1, @USR, @HOY, @EST
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_USUARIO_OPCION u
    WHERE u.LOGIN_SISTEMA = @LOGIN
      AND u.CODIGO_SISTEMA = @SISTEMA
      AND u.CODIGO_MENU = @MENU
      AND u.CODIGO_OPCION = N'PLA_SEGURO_SOCIAL'
);

PRINT N'Menú PLA_AFP y PLA_SEGURO_SOCIAL configurado.';

SELECT c.CODIGO_SISTEMA, c.CODIGO_MENU, c.ORDEN_OPCION, c.CODIGO_OPCION, o.NOMBRE_OPCION, o.URL_OPCION
FROM SEG_CONFIG_OPCION c
INNER JOIN SEG_OPCION_SISTEMA o ON c.CODIGO_OPCION = o.CODIGO_OPCION
WHERE c.CODIGO_OPCION IN (N'PLA_AFP', N'PLA_SEGURO_SOCIAL')
ORDER BY c.CODIGO_SISTEMA, c.ORDEN_OPCION;
GO
