/* ============================================================================
   PRAL_MTTO_SEG_USUARIO_OPCION — alta con permisos completos
   Al insertar una opción al usuario, NUEVO/MODIFICAR/ELIMINAR/IMPRIMIR = 1
   ============================================================================
   Ejecutar:
     sqlcmd -S <servidor> -U <usuario> -d SGUEES -f 65001 -i FIX_PRAL_MTTO_SEG_USUARIO_OPCION_INSERT_PERMISOS.sql
   ============================================================================ */
SET NOCOUNT ON;
GO

ALTER PROCEDURE [dbo].[PRAL_MTTO_SEG_USUARIO_OPCION]
(
	@TIPO_ACTUALIZA INT,
	@LOGIN_SISTEMA varchar(30),
	@CODIGO_SISTEMA varchar(30),
	@CODIGO_MENU varchar(10),
	@CODIGO_OPCION varchar(50) OUTPUT,
	@NUEVO bit,
	@MODIFICAR bit,
	@ELIMINAR bit,
	@IMPRIMIR bit,
	@USUARIO_CREA varchar(30) = null,
	@FECHA_CREA DATETIME = null,
	@ESTACION_CREA varchar(50)= null,
	@USUARIO_ACTU varchar(30) = null,
	@FECHA_ACTU DATETIME = null,
	@ESTACION_ACTU varchar(50),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0


	IF NOT EXISTS(SELECT 1 FROM SEG_USUARIO_OPCION
				  WHERE CODIGO_SISTEMA=@CODIGO_SISTEMA
				  AND CODIGO_MENU=@CODIGO_MENU
				  AND CODIGO_OPCION=@CODIGO_OPCION
				  AND LOGIN_SISTEMA=@LOGIN_SISTEMA)
	BEGIN
		SELECT @TIPO_ACTUALIZA=1
	END


	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			/* Alta de opción: permisos completos por defecto */
			SELECT @NUEVO = 1, @MODIFICAR = 1, @ELIMINAR = 1, @IMPRIMIR = 1

			INSERT INTO SEG_USUARIO_OPCION
			(LOGIN_SISTEMA,CODIGO_SISTEMA,CODIGO_MENU,CODIGO_OPCION,NUEVO,MODIFICAR,ELIMINAR,IMPRIMIR,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU)
			VALUES
			(@LOGIN_SISTEMA,@CODIGO_SISTEMA,@CODIGO_MENU,@CODIGO_OPCION,@NUEVO,@MODIFICAR,@ELIMINAR,@IMPRIMIR,@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			IF @NUEVO=0 AND @MODIFICAR=0 AND @ELIMINAR=0 AND @IMPRIMIR=0
			BEGIN
				DELETE FROM SEG_USUARIO_OPCION
				WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA
				AND CODIGO_SISTEMA=@CODIGO_SISTEMA
				AND CODIGO_MENU=@CODIGO_MENU
				AND CODIGO_OPCION=@CODIGO_OPCION
			END ELSE
			BEGIN
				UPDATE SEG_USUARIO_OPCION SET
				NUEVO=@NUEVO,
				MODIFICAR=@MODIFICAR,
				ELIMINAR=@ELIMINAR,
				IMPRIMIR=@IMPRIMIR,
				USUARIO_ACTU=@USUARIO_ACTU,
				FECHA_ACTU=@FECHA_ACTU,
				ESTACION_ACTU=@ESTACION_ACTU
				WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA
				AND CODIGO_SISTEMA=@CODIGO_SISTEMA
				AND CODIGO_MENU=@CODIGO_MENU
				AND CODIGO_OPCION=@CODIGO_OPCION
			END


		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM SEG_USUARIO_OPCION
			WHERE LOGIN_SISTEMA=@LOGIN_SISTEMA
			AND CODIGO_SISTEMA=@CODIGO_SISTEMA
			AND CODIGO_MENU=@CODIGO_MENU
			AND CODIGO_OPCION=@CODIGO_OPCION
		END

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

	END TRY
	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		IF OBJECT_ID(N'dbo.ADMIN_BITACORA_SISTEMA', N'U') IS NOT NULL
		BEGIN
			EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION
		END

	END CATCH;
FINA:
END
GO

PRINT N'PRAL_MTTO_SEG_USUARIO_OPCION actualizado: insert con permisos completos.';
GO
