/* Corregir CUENTA_CONTABLE en BAN_CUENTA_BANCARIA — debe existir en CON_CATALOGO_CUENTA */
SET NOCOUNT ON;

DECLARE @CORR_EMPRESA INT = 1;

UPDATE dbo.BAN_CUENTA_BANCARIA
SET CUENTA_CONTABLE = N'110102010501',
	USUARIO_ACTU = N'system',
	FECHA_ACTU = GETDATE(),
	ESTACION_ACTU = N'deploy'
WHERE CORR_EMPRESA = @CORR_EMPRESA
  AND CORR_CUENTA_BANCO = 2; /* PROMERICA */

UPDATE dbo.BAN_CUENTA_BANCARIA
SET CUENTA_CONTABLE = N'110102010103',
	USUARIO_ACTU = N'system',
	FECHA_ACTU = GETDATE(),
	ESTACION_ACTU = N'deploy'
WHERE CORR_EMPRESA = @CORR_EMPRESA
  AND CORR_CUENTA_BANCO = 7; /* DAVIVIENDA */

UPDATE dbo.BAN_CUENTA_BANCARIA
SET CUENTA_CONTABLE = N'110102010106',
	USUARIO_ACTU = N'system',
	FECHA_ACTU = GETDATE(),
	ESTACION_ACTU = N'deploy'
WHERE CORR_EMPRESA = @CORR_EMPRESA
  AND CORR_CUENTA_BANCO IN (1, 3, 4, 8, 10); /* AGRICOLA, CUSCATLAN, CREDOMATIC, ATLANTIDA, HIPOTECARIO */

SELECT
	A.CORR_CUENTA_BANCO,
	V.NOMBRE_CUENTA_BANCO,
	A.CUENTA_CONTABLE,
	C.NOMBRE_CUENTA,
	CASE WHEN C.CUENTA_CONTABLE IS NULL THEN N'FALTA EN CATALOGO' ELSE N'OK' END AS ESTADO
FROM dbo.BAN_CUENTA_BANCARIA A
INNER JOIN dbo.V_BAN_CUENTA_BANCARIA V
	ON V.CORR_EMPRESA = A.CORR_EMPRESA AND V.CORR_CUENTA_BANCO = A.CORR_CUENTA_BANCO
LEFT JOIN dbo.CON_CATALOGO_CUENTA C
	ON C.CORR_EMPRESA = A.CORR_EMPRESA AND C.CUENTA_CONTABLE = A.CUENTA_CONTABLE
WHERE A.CORR_EMPRESA = @CORR_EMPRESA
ORDER BY A.CORR_CUENTA_BANCO;
GO
