/* Amplía ESTACION_* en SEG_TIPO_USUARIO_OPCION (hostname + IP supera 30 chars) */
SET NOCOUNT ON;
GO

IF COL_LENGTH('dbo.SEG_TIPO_USUARIO_OPCION', 'ESTACION_CREA') IS NOT NULL
BEGIN
	ALTER TABLE dbo.SEG_TIPO_USUARIO_OPCION ALTER COLUMN ESTACION_CREA varchar(50) NOT NULL;
END
GO

IF COL_LENGTH('dbo.SEG_TIPO_USUARIO_OPCION', 'ESTACION_ACTU') IS NOT NULL
BEGIN
	ALTER TABLE dbo.SEG_TIPO_USUARIO_OPCION ALTER COLUMN ESTACION_ACTU varchar(50) NOT NULL;
END
GO

PRINT N'SEG_TIPO_USUARIO_OPCION: ESTACION_CREA/ACTU ampliadas a varchar(50).';
GO
