/* Limpia duplicados en BAN_CUENTA_BANCARIA — deja 1 cuenta por banco.
   Conserva la que tenga chequeras; si no, la de menor CORR_CUENTA_BANCO. */
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

;WITH CuentasRank AS (
	SELECT
		c.CORR_EMPRESA,
		c.CORR_CUENTA_BANCO,
		c.CORR_BANCO,
		c.NUMERO_CUENTA_BANCO,
		ROW_NUMBER() OVER (
			PARTITION BY c.CORR_EMPRESA, c.CORR_BANCO
			ORDER BY
				CASE
					WHEN EXISTS (
						SELECT 1
						FROM dbo.BAN_CHEQUERA ch
						WHERE ch.CORR_EMPRESA = c.CORR_EMPRESA
							AND ch.CORR_CUENTA_BANCO = c.CORR_CUENTA_BANCO
					) THEN 0
					ELSE 1
				END,
				c.CORR_CUENTA_BANCO
		) AS rn
	FROM dbo.BAN_CUENTA_BANCARIA c
)
SELECT
	r.CORR_EMPRESA,
	r.CORR_CUENTA_BANCO,
	r.CORR_BANCO,
	r.NUMERO_CUENTA_BANCO,
	b.NOMBRE_BANCO
INTO #Eliminar
FROM CuentasRank r
LEFT JOIN dbo.V_GEN_BANCO b
	ON b.CORR_EMPRESA = r.CORR_EMPRESA
	AND b.CORR_BANCO = r.CORR_BANCO
WHERE r.rn > 1;

PRINT N'Cuentas a eliminar:';
SELECT * FROM #Eliminar ORDER BY CORR_BANCO, CORR_CUENTA_BANCO;

DELETE ch
FROM dbo.BAN_CHEQUERA ch
INNER JOIN #Eliminar e
	ON e.CORR_EMPRESA = ch.CORR_EMPRESA
	AND e.CORR_CUENTA_BANCO = ch.CORR_CUENTA_BANCO;

DELETE c
FROM dbo.BAN_CUENTA_BANCARIA c
INNER JOIN #Eliminar e
	ON e.CORR_EMPRESA = c.CORR_EMPRESA
	AND e.CORR_CUENTA_BANCO = c.CORR_CUENTA_BANCO;

PRINT N'Resultado final (1 por banco):';
SELECT
	c.CORR_EMPRESA,
	c.CORR_CUENTA_BANCO,
	c.CORR_BANCO,
	b.NOMBRE_BANCO,
	c.NUMERO_CUENTA_BANCO
FROM dbo.BAN_CUENTA_BANCARIA c
LEFT JOIN dbo.V_GEN_BANCO b
	ON b.CORR_EMPRESA = c.CORR_EMPRESA
	AND b.CORR_BANCO = c.CORR_BANCO
ORDER BY c.CORR_BANCO;

DROP TABLE #Eliminar;

COMMIT TRANSACTION;
GO
