/*
  Corrige CLASE_RUBRO en CON_RUBRO y CON_CATALOGO_CUENTA.
  El import CLASS dejó todo como 'AC'; SGUEES usa PA/PT/IN/GA/LI en reportes y SPs.
*/
SET NOCOUNT ON;

DECLARE @CORR_EMPRESA INT = 1;

UPDATE CON_RUBRO
SET CLASE_RUBRO = CASE CODIGO_RUBRO
    WHEN N'1' THEN 'AC'
    WHEN N'2' THEN 'PA'
    WHEN N'3' THEN 'PT'
    WHEN N'4' THEN 'GA'
    WHEN N'5' THEN 'IN'
    WHEN N'6' THEN 'LI'
    ELSE CLASE_RUBRO
END
WHERE CORR_EMPRESA = @CORR_EMPRESA;

UPDATE CON_CATALOGO_CUENTA
SET CLASE_RUBRO = CASE LEFT(CUENTA_CONTABLE, 1)
    WHEN '1' THEN 'AC'
    WHEN '2' THEN 'PA'
    WHEN '3' THEN 'PT'
    WHEN '4' THEN 'GA'
    WHEN '5' THEN 'IN'
    WHEN '6' THEN 'LI'
    ELSE CLASE_RUBRO
END
WHERE CORR_EMPRESA = @CORR_EMPRESA;

SELECT CLASE_RUBRO, COUNT(*) AS CUENTAS
FROM CON_CATALOGO_CUENTA
WHERE CORR_EMPRESA = @CORR_EMPRESA
GROUP BY CLASE_RUBRO
ORDER BY CLASE_RUBRO;

GO
