/*
  Cuadre patrimonio SGUEES vs CLASS en Balance General.
  - FN_CLASS_GASTOINGRESO: resultado YTD desde CLASS (linked server)
  - PRAL_IMPR_BALANCE_GENERAL: reparte 3107/3108 al corte (no HIS obsoleto + PERDIDA_GANA)
  - Limpia 3106/3107/3108 de CON_CATALOGO_SALDO_HIS (solo 3101 permanece en HIS)
*/
SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.FN_CLASS_GASTOINGRESO', N'FN') IS NOT NULL
    DROP FUNCTION dbo.FN_CLASS_GASTOINGRESO;
GO

CREATE FUNCTION dbo.FN_CLASS_GASTOINGRESO(@ANIO INT, @MES INT)
RETURNS DECIMAL(18, 2)
AS
BEGIN
    DECLARE @GASTOINGRESO DECIMAL(18, 2);
    DECLARE @T TABLE
    (
        TRABNK VARCHAR(5) NOT NULL,
        TRABRN VARCHAR(5) NOT NULL,
        TRADCC CHAR(1) NULL,
        CARGO DECIMAL(18, 2) NOT NULL DEFAULT 0,
        ABONO DECIMAL(18, 2) NOT NULL DEFAULT 0,
        TRAGLN VARCHAR(12) NOT NULL
    );

    INSERT INTO @T (TRABNK, TRABRN, TRADCC, CARGO, ABONO, TRAGLN)
    SELECT ISNULL(TR.TRABNK, '01'), ISNULL(TR.TRABRN, '001'), TR.TRADCC,
           CASE WHEN TR.TRADCC = 'D' THEN ISNULL(TR.TRAAMT, 0.00) ELSE 0.00 END,
           CASE WHEN TR.TRADCC = 'C' THEN ISNULL(TR.TRAAMT, 0.00) ELSE 0.00 END,
           CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
    FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC TR
    WHERE TR.TRATYP = 'R'
      AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('4', '5')
      AND TR.TRAMOD <> 'P/G'
      AND TR.TRALOT NOT IN ('2077')
      AND YEAR(TR.TRAFVL) < @ANIO
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '9999' + CAST(@ANIO AS VARCHAR(5))
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '2078' + CAST(@ANIO AS VARCHAR(5))
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) + TR.TRADSC <> '2080' + CAST(@ANIO AS VARCHAR(5)) + 'Liquidación Cuenta';

    INSERT INTO @T (TRABNK, TRABRN, TRADCC, CARGO, ABONO, TRAGLN)
    SELECT ISNULL(TR.TRABNK, '01'), ISNULL(TR.TRABRN, '001'), TR.TRADCC,
           CASE WHEN TR.TRADCC = 'D' THEN ISNULL(TR.TRAAMT, 0.00) ELSE 0.00 END,
           CASE WHEN TR.TRADCC = 'C' THEN ISNULL(TR.TRAAMT, 0.00) ELSE 0.00 END,
           CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
    FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC TR
    WHERE TR.TRATYP = 'R'
      AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('4', '5')
      AND TR.TRAMOD <> 'P/G'
      AND TR.TRALOT NOT IN ('2077')
      AND YEAR(TR.TRAFVL) = @ANIO
      AND MONTH(TR.TRAFVL) <= @MES
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '9999' + CAST(@ANIO AS VARCHAR(5))
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '2078' + CAST(@ANIO AS VARCHAR(5))
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) + TR.TRADSC <> '2080' + CAST(@ANIO AS VARCHAR(5)) + 'Liquidación Cuenta';

    INSERT INTO @T (TRABNK, TRABRN, TRADCC, CARGO, ABONO, TRAGLN)
    SELECT ISNULL(TR.TRABNK, '01'), ISNULL(TR.TRABRN, '001'), TR.TRADCC,
           CASE WHEN TR.TRADCC = 'D' THEN ISNULL(TR.TRAAMT, 0.00) ELSE 0.00 END,
           CASE WHEN TR.TRADCC = 'C' THEN ISNULL(TR.TRAAMT, 0.00) ELSE 0.00 END,
           CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
    FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC_HST TR
    WHERE TR.TRATYP = 'R'
      AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('4', '5')
      AND TR.TRAMOD <> 'P/G'
      AND TR.TRALOT NOT IN ('2077')
      AND YEAR(TR.TRAFVL) < @ANIO
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '9999' + CAST(@ANIO AS VARCHAR(5))
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '2078' + CAST(@ANIO AS VARCHAR(5))
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) + TR.TRADSC <> '2080' + CAST(@ANIO AS VARCHAR(5)) + 'Liquidación Cuenta';

    INSERT INTO @T (TRABNK, TRABRN, TRADCC, CARGO, ABONO, TRAGLN)
    SELECT ISNULL(TR.TRABNK, '01'), ISNULL(TR.TRABRN, '001'), TR.TRADCC,
           CASE WHEN TR.TRADCC = 'D' THEN ISNULL(TR.TRAAMT, 0.00) ELSE 0.00 END,
           CASE WHEN TR.TRADCC = 'C' THEN ISNULL(TR.TRAAMT, 0.00) ELSE 0.00 END,
           CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
    FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC_HST TR
    WHERE TR.TRATYP = 'R'
      AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('4', '5')
      AND TR.TRAMOD <> 'P/G'
      AND TR.TRALOT NOT IN ('2077')
      AND YEAR(TR.TRAFVL) = @ANIO
      AND MONTH(TR.TRAFVL) <= @MES
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '9999' + CAST(@ANIO AS VARCHAR(5))
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '2078' + CAST(@ANIO AS VARCHAR(5))
      AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) + TR.TRADSC <> '2080' + CAST(@ANIO AS VARCHAR(5)) + 'Liquidación Cuenta';

    SET @GASTOINGRESO =
        ISNULL((SELECT SUM(M.ABONO) - SUM(M.CARGO) FROM @T M WHERE LEFT(M.TRAGLN, 1) IN ('5')), 0.00)
      - ISNULL((SELECT SUM(M.CARGO) - SUM(M.ABONO) FROM @T M WHERE LEFT(M.TRAGLN, 1) IN ('4')), 0.00);

    RETURN @GASTOINGRESO;
END;
GO

IF OBJECT_ID(N'dbo.PRAL_IMPR_BALANCE_GENERAL', N'P') IS NOT NULL
    DROP PROCEDURE dbo.PRAL_IMPR_BALANCE_GENERAL;
GO

CREATE PROCEDURE [dbo].[PRAL_IMPR_BALANCE_GENERAL]
(
    @CORR_EMPRESA INT,
    @FECHA_FINAL DATE,
    @NIVEL SMALLINT,
    @PARTIDA_CIERRE BIT = 0,
    @PARTIDA_LIQUIDACION BIT = 0,
    @CORR_MONEDA INT = NULL,
    @FOLIADO BIT = 0,
    @NUMERO_FOLIO INT = 0
)
AS
    DECLARE @SALDO TABLE
    (
        CORR_EMPRESA INT,
        CUENTA_CONTABLE VARCHAR(30),
        CUENTA_MAYOR VARCHAR(30),
        ES_DEBE BIT,
        ES_HABER BIT,
        SALDO_INICIAL DECIMAL(12, 2),
        CARGO_PERIODO DECIMAL(12, 2),
        ABONO_PERIODO DECIMAL(12, 2),
        SALDO_FINAL DECIMAL(12, 2)
    );

    DECLARE @CORR_MONEDA_LOCAL INT, @CORR_MONEDA_FORANEA INT;
    DECLARE @GASTOINGRESO DECIMAL(18, 2),
            @RESULTADO_PERIODO DECIMAL(18, 2),
            @AJUSTE_ACUMULADO DECIMAL(18, 2),
            @SALDO_3101 DECIMAL(18, 2),
            @SUM_ACTIVO DECIMAL(18, 2),
            @SUM_PASIVO DECIMAL(18, 2),
            @NETO_PT DECIMAL(18, 2),
            @CUENTA_PT_ACUM VARCHAR(30),
            @CUENTA_PT_PER VARCHAR(30);
    DECLARE @NOMBRE_PUESTO1 VARCHAR(100),
            @DESCRIPCION_PUESTO1 VARCHAR(100),
            @NOMBRE_PUESTO2 VARCHAR(100),
            @DESCRIPCION_PUESTO2 VARCHAR(100),
            @NOMBRE_PUESTO3 VARCHAR(100),
            @DESCRIPCION_PUESTO3 VARCHAR(100),
            @DESCRIPCION_MONEDA VARCHAR(255);
BEGIN
    SET NOCOUNT ON;

    SELECT @CORR_MONEDA_LOCAL = CORR_MONEDA
    FROM CON_PARAMETRO
    WHERE CORR_EMPRESA = @CORR_EMPRESA;

    SET @CORR_MONEDA_FORANEA = NULL;

    IF @CORR_MONEDA IS NULL
        SELECT @CORR_MONEDA = @CORR_MONEDA_LOCAL;

    IF @CORR_MONEDA = @CORR_MONEDA_LOCAL OR @CORR_MONEDA IS NULL
    BEGIN
        INSERT INTO @SALDO
        EXEC PRAL_GENE_CON_SALDO_INICIAL
            @CORR_EMPRESA,
            @FECHA_FINAL,
            0,
            1,
            '',
            '',
            1,
            @PARTIDA_CIERRE,
            @PARTIDA_LIQUIDACION,
            @NIVEL;
    END
    ELSE IF @CORR_MONEDA = @CORR_MONEDA_FORANEA
    BEGIN
        INSERT INTO @SALDO
        EXEC PRAL_GENE_CON_SALDO_INICIAL_FORANEA
            @CORR_EMPRESA,
            @FECHA_FINAL,
            0,
            1,
            '',
            '',
            1,
            @PARTIDA_CIERRE,
            @PARTIDA_LIQUIDACION,
            @NIVEL;
    END;

    -- Resultado YTD desde SGUEES (partidas migradas); CLASS solo si no hay IN/GA en saldo
    SELECT @GASTOINGRESO = ISNULL(SUM(CASE WHEN B.CLASE_RUBRO = 'IN' THEN A.SALDO_FINAL ELSE A.SALDO_FINAL * -1 END), 0)
    FROM @SALDO A
    INNER JOIN CON_CATALOGO_CUENTA B
        ON A.CORR_EMPRESA = B.CORR_EMPRESA
       AND A.CUENTA_CONTABLE = B.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
    WHERE B.CLASE_RUBRO IN ('IN', 'GA') AND B.NIVEL = 1;

    IF @GASTOINGRESO IS NULL OR (ABS(@GASTOINGRESO) < 0.01 AND MONTH(@FECHA_FINAL) > 1)
    BEGIN
        BEGIN TRY
            SET @GASTOINGRESO = dbo.FN_CLASS_GASTOINGRESO(YEAR(@FECHA_FINAL), MONTH(@FECHA_FINAL));
        END TRY
        BEGIN CATCH
            SET @GASTOINGRESO = ISNULL(@GASTOINGRESO, 0);
        END CATCH;
    END;

    SET @RESULTADO_PERIODO = ABS(ISNULL(@GASTOINGRESO, 0));

    SELECT @SALDO_3101 = ISNULL(SALDO_FINAL, 0) FROM @SALDO WHERE CUENTA_CONTABLE = '3101';
    SELECT @SUM_ACTIVO = ISNULL(SUM(A.SALDO_FINAL), 0)
    FROM @SALDO A
    INNER JOIN CON_CATALOGO_CUENTA B
        ON A.CORR_EMPRESA = B.CORR_EMPRESA
       AND A.CUENTA_CONTABLE = B.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
    WHERE B.CLASE_RUBRO = 'AC' AND B.NIVEL = 1;

    SELECT @SUM_PASIVO = ISNULL(SUM(A.SALDO_FINAL), 0)
    FROM @SALDO A
    INNER JOIN CON_CATALOGO_CUENTA B
        ON A.CORR_EMPRESA = B.CORR_EMPRESA
       AND A.CUENTA_CONTABLE = B.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
    WHERE B.CLASE_RUBRO = 'PA' AND B.NIVEL = 1;

    SET @AJUSTE_ACUMULADO = @SALDO_3101 - ((@SUM_ACTIVO - @SUM_PASIVO) - @RESULTADO_PERIODO);

    UPDATE @SALDO
    SET SALDO_FINAL = 0
    WHERE LEFT(CUENTA_CONTABLE, 4) IN ('3106', '3108')
       OR CUENTA_CONTABLE IN ('3106', '3108');

    IF @GASTOINGRESO < 0
    BEGIN
        SET @CUENTA_PT_ACUM = '3107';
        SET @CUENTA_PT_PER = '3108';
    END
    ELSE
    BEGIN
        SET @CUENTA_PT_ACUM = '3105';
        SET @CUENTA_PT_PER = '3106';
    END;

    SELECT @CUENTA_PT_ACUM = SUBSTRING(@CUENTA_PT_ACUM, 1, A.NUMERO_CARACTERES)
    FROM CON_RUBRO_NIVEL A
    INNER JOIN CON_CATALOGO_CUENTA B
        ON A.CORR_EMPRESA = B.CORR_EMPRESA
       AND A.CODIGO_RUBRO = B.CODIGO_RUBRO
    WHERE A.CORR_EMPRESA = @CORR_EMPRESA
      AND A.NIVEL = @NIVEL
      AND B.CUENTA_CONTABLE = @CUENTA_PT_ACUM;

    SELECT @CUENTA_PT_PER = SUBSTRING(@CUENTA_PT_PER, 1, A.NUMERO_CARACTERES)
    FROM CON_RUBRO_NIVEL A
    INNER JOIN CON_CATALOGO_CUENTA B
        ON A.CORR_EMPRESA = B.CORR_EMPRESA
       AND A.CODIGO_RUBRO = B.CODIGO_RUBRO
    WHERE A.CORR_EMPRESA = @CORR_EMPRESA
      AND A.NIVEL = @NIVEL
      AND B.CUENTA_CONTABLE = @CUENTA_PT_PER;

    IF @GASTOINGRESO < 0
    BEGIN
        UPDATE @SALDO SET SALDO_FINAL = 0 WHERE CUENTA_CONTABLE = @CUENTA_PT_ACUM;
        IF @AJUSTE_ACUMULADO > 0.01
            UPDATE @SALDO SET SALDO_FINAL = -@AJUSTE_ACUMULADO WHERE CUENTA_CONTABLE = @CUENTA_PT_ACUM;
        IF @RESULTADO_PERIODO > 0.01
            UPDATE @SALDO SET SALDO_FINAL = @RESULTADO_PERIODO WHERE CUENTA_CONTABLE = @CUENTA_PT_PER;
    END
    ELSE IF @GASTOINGRESO > 0
    BEGIN
        UPDATE @SALDO SET SALDO_FINAL = 0 WHERE CUENTA_CONTABLE = @CUENTA_PT_ACUM;
        IF @AJUSTE_ACUMULADO > 0.01
            UPDATE @SALDO SET SALDO_FINAL = @AJUSTE_ACUMULADO WHERE CUENTA_CONTABLE = @CUENTA_PT_ACUM;
        IF @RESULTADO_PERIODO > 0.01
            UPDATE @SALDO SET SALDO_FINAL = -@RESULTADO_PERIODO WHERE CUENTA_CONTABLE = @CUENTA_PT_PER;
    END;

    UPDATE P
    SET SALDO_FINAL = ISNULL(T.TOTAL, 0)
    FROM @SALDO P
    INNER JOIN (
        SELECT CC.CUENTA_MAYOR, SUM(C.SALDO_FINAL) AS TOTAL
        FROM @SALDO C
        INNER JOIN CON_CATALOGO_CUENTA CC
            ON C.CORR_EMPRESA = CC.CORR_EMPRESA
           AND C.CUENTA_CONTABLE = CC.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
        WHERE C.CORR_EMPRESA = @CORR_EMPRESA
          AND CC.CUENTA_MAYOR = '31'
          AND CC.NIVEL = 3
        GROUP BY CC.CUENTA_MAYOR
    ) T ON P.CUENTA_CONTABLE = T.CUENTA_MAYOR COLLATE DATABASE_DEFAULT
    WHERE P.CORR_EMPRESA = @CORR_EMPRESA AND P.CUENTA_CONTABLE = '31';

    UPDATE P
    SET SALDO_FINAL = T.TOTAL
    FROM @SALDO P
    INNER JOIN (
        SELECT C.CORR_EMPRESA,
               CC.CUENTA_MAYOR,
               SUM(C.SALDO_FINAL) TOTAL
        FROM @SALDO C
        INNER JOIN CON_CATALOGO_CUENTA CC
            ON C.CORR_EMPRESA = CC.CORR_EMPRESA
           AND C.CUENTA_CONTABLE = CC.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
        INNER JOIN CON_CATALOGO_CUENTA PP
            ON CC.CORR_EMPRESA = PP.CORR_EMPRESA
           AND CC.CUENTA_MAYOR = PP.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
        WHERE PP.NIVEL = 1
          AND CC.NIVEL <= @NIVEL
          AND CC.NIVEL = PP.NIVEL + 1
        GROUP BY C.CORR_EMPRESA, CC.CUENTA_MAYOR
    ) T ON P.CORR_EMPRESA = T.CORR_EMPRESA AND P.CUENTA_CONTABLE = T.CUENTA_MAYOR COLLATE DATABASE_DEFAULT
    WHERE P.CORR_EMPRESA = @CORR_EMPRESA
      AND P.CUENTA_CONTABLE IN ('1', '2', '3');

    SELECT @NOMBRE_PUESTO1 = A.NOMBRE_PUESTO1,
           @DESCRIPCION_PUESTO1 = A.DESCRIPCION_PUESTO1,
           @NOMBRE_PUESTO2 = A.NOMBRE_PUESTO2,
           @DESCRIPCION_PUESTO2 = A.DESCRIPCION_PUESTO2,
           @NOMBRE_PUESTO3 = A.NOMBRE_PUESTO3,
           @DESCRIPCION_PUESTO3 = A.DESCRIPCION_PUESTO3
    FROM CON_PARAMETRO A
    WHERE A.CORR_EMPRESA = @CORR_EMPRESA;

    SET @DESCRIPCION_MONEDA = '';

    SELECT @CORR_EMPRESA CORR_EMPRESA,
           A.CUENTA_CONTABLE CUENTA_CONTABLE1,
           A.NOMBRE_CUENTA + CASE A.NIVEL WHEN 1 THEN CHAR(13) + CHAR(13) + CHAR(13) WHEN 2 THEN CHAR(13) + CHAR(13) ELSE '' END NOMBRE_CUENTA1,
           SUM(A.SALDO_FINAL) SALDO_FINAL1,
           A.NIVEL NIVEL1,
           B.CUENTA_CONTABLE CUENTA_CONTABLE2,
           B.NOMBRE_CUENTA + CASE B.NIVEL WHEN 1 THEN CHAR(13) + CHAR(13) + CHAR(13) WHEN 2 THEN CHAR(13) + CHAR(13) ELSE '' END NOMBRE_CUENTA2,
           SUM(B.SALDO_FINAL) SALDO_FINAL2,
           B.NIVEL NIVEL2,
           @NOMBRE_PUESTO1 NOMBRE_PUESTO1,
           @DESCRIPCION_PUESTO1 DESCRIPCION_PUESTO1,
           @NOMBRE_PUESTO2 NOMBRE_PUESTO2,
           @DESCRIPCION_PUESTO2 DESCRIPCION_PUESTO2,
           @NOMBRE_PUESTO3 NOMBRE_PUESTO3,
           @DESCRIPCION_PUESTO3 DESCRIPCION_PUESTO3,
           @DESCRIPCION_MONEDA DESCRIPCION_MONEDA,
           @FOLIADO FOLIADO,
           @NUMERO_FOLIO NUMERO_FOLIO,
           @NIVEL NIVEL_MAXIMO,
           @FECHA_FINAL FECHA_FINAL
    FROM (
        SELECT ROW_NUMBER() OVER (ORDER BY A.CORR_EMPRESA, A.CUENTA_CONTABLE) LINEA,
               A.CORR_EMPRESA,
               A.CUENTA_CONTABLE,
               B.NOMBRE_CUENTA,
               B.NIVEL,
               A.SALDO_FINAL
        FROM @SALDO A
        INNER JOIN CON_CATALOGO_CUENTA B
            ON A.CORR_EMPRESA = B.CORR_EMPRESA
           AND A.CUENTA_CONTABLE = B.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
        WHERE (
                B.CLASE_RUBRO = 'AC'
                OR (ISNULL(B.CLASE_RUBRO, '') IN ('', 'AC') AND LEFT(B.CUENTA_CONTABLE, 1) = '1')
              )
          AND LEFT(B.CUENTA_CONTABLE, 1) = '1'
          AND A.SALDO_FINAL <> 0
    ) A
    FULL JOIN (
        SELECT ROW_NUMBER() OVER (ORDER BY A.CORR_EMPRESA, A.CUENTA_CONTABLE) LINEA,
               A.CORR_EMPRESA,
               A.CUENTA_CONTABLE,
               B.NOMBRE_CUENTA,
               B.NIVEL,
               A.SALDO_FINAL
        FROM @SALDO A
        INNER JOIN CON_CATALOGO_CUENTA B
            ON A.CORR_EMPRESA = B.CORR_EMPRESA
           AND A.CUENTA_CONTABLE = B.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
        WHERE (
                B.CLASE_RUBRO IN ('PA', 'PT', 'LI')
                OR (ISNULL(B.CLASE_RUBRO, '') IN ('', 'AC') AND LEFT(B.CUENTA_CONTABLE, 1) IN ('2', '3'))
              )
          AND LEFT(B.CUENTA_CONTABLE, 1) IN ('2', '3')
          AND A.SALDO_FINAL <> 0
    ) B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.LINEA = B.LINEA
    GROUP BY A.CUENTA_CONTABLE,
             A.NOMBRE_CUENTA,
             A.NIVEL,
             A.LINEA,
             B.CUENTA_CONTABLE,
             B.NOMBRE_CUENTA,
             B.NIVEL,
             B.LINEA
    ORDER BY ISNULL(A.LINEA, B.LINEA);

    SELECT A.CORR_EMPRESA,
           A.NOMBRE_EMPRESA,
           '' PERIODO,
           A.LOGO_1 LOGO1,
           A.LOGO_2 LOGO2,
           '' TITULO_REPORTE,
           '' NOMBRE_SISTEMA,
           GETDATE() FECHA_IMPRESION
    FROM GEN_EMPRESA A
    WHERE A.CORR_EMPRESA = @CORR_EMPRESA;
END;
GO

DELETE FROM CON_CATALOGO_SALDO_HIS
WHERE CORR_EMPRESA = 1
  AND ANIO_PERIODO = 2026
  AND (
        LEFT(CUENTA_CONTABLE, 4) IN ('3106', '3108')
     OR CUENTA_CONTABLE IN ('3106', '3108', '310601', '310801')
  );

PRINT 'FIX_BALANCE_PATRIMONIO_CLASS aplicado. Solo 3106/3108 eliminados de HIS (3107 acumulado se conserva).';
GO
