/*
  Amplía columnas del TVP de importación Excel (error 8152 truncamiento).
  Uso:
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i FIX_BAN_CONCILIA_MOV_EXCEL_TVP.sql
*/
SET NOCOUNT ON;
GO

PRINT N'=== Recrear TVP T_BAN_CONCILIACION_BANCARIA_MOV_EXCEL (30/255) ===';

IF OBJECT_ID(N'dbo.PRAL_GENE_BAN_CONCILIA_BANCARIA_MOV_EXCEL', N'P') IS NOT NULL
	DROP PROCEDURE dbo.PRAL_GENE_BAN_CONCILIA_BANCARIA_MOV_EXCEL;
GO

IF TYPE_ID(N'dbo.T_BAN_CONCILIACION_BANCARIA_MOV_EXCEL') IS NOT NULL
	DROP TYPE dbo.T_BAN_CONCILIACION_BANCARIA_MOV_EXCEL;
GO

CREATE TYPE [dbo].[T_BAN_CONCILIACION_BANCARIA_MOV_EXCEL] AS TABLE
(
	[CORR] [int] NOT NULL,
	[NUMERO_REFERENCIA_BANCO] [varchar](255) COLLATE Latin1_General_CS_AS NOT NULL,
	[CODIGO_TIPO_MOVIMIENTO] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
	[NOMBRE_TIPO_MOVIMIENTO] [varchar](255) COLLATE Latin1_General_CS_AS NOT NULL,
	[FECHA_MOVIMIENTO] [datetime] NOT NULL,
	[MONTO_CARGO] [decimal](18, 2) NOT NULL,
	[MONTO_ABONO] [decimal](18, 2) NOT NULL,
	[SALDO] [decimal](18, 2) NOT NULL
);
GO

:r "..\Stored Procedures\dbo.PRAL_GENE_BAN_CONCILIA_BANCARIA_MOV_EXCEL.sql"
GO

PRINT N'=== FIX_BAN_CONCILIA_MOV_EXCEL_TVP completado ===';
GO
