/* ============================================================================
   PRAL_MTTO_SEG_TIPO_USUARIO_OPCION — propagación alta/baja
   - Al AGREGAR opción al tipo: inserta en usuarios del mismo TIPO_USUARIO
     (solo si existe en SEG_CONFIG_OPCION y el usuario no la tiene)
   - Al QUITAR opción del tipo (delete o permisos en cero): elimina la opción
     en SEG_USUARIO_OPCION de todos los usuarios de ese TIPO_USUARIO
   - Update de permisos del tipo: NO sobrescribe permisos del usuario
   ============================================================================
   Ejecutar:
     sqlcmd -S <servidor> -U <usuario> -d SGUEES -f 65001 -i FIX_PRAL_MTTO_SEG_TIPO_USUARIO_OPCION.sql
   ============================================================================ */
SET NOCOUNT ON;
GO

ALTER PROCEDURE [dbo].[PRAL_MTTO_SEG_TIPO_USUARIO_OPCION]
(
	@TIPO_ACTUALIZA INT,
	@TIPO_USUARIO INT,
	@CODIGO_SISTEMA varchar(30),
	@CODIGO_MENU varchar(10),
	@CODIGO_OPCION varchar(50) OUTPUT,
	@NUEVO bit,
	@MODIFICAR bit,
	@ELIMINAR bit,
	@IMPRIMIR bit,
	@USUARIO_CREA varchar(30) = null,
	@FECHA_CREA DATETIME = null,
	@ESTACION_CREA varchar(50)= null,
	@USUARIO_ACTU varchar(30) = null,
	@FECHA_ACTU DATETIME = null,
	@ESTACION_ACTU varchar(50),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	DECLARE @AUD_USUARIO varchar(30)
	DECLARE @AUD_ESTACION varchar(50)
	DECLARE @AUD_FECHA datetime

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	SELECT @AUD_USUARIO = ISNULL(@USUARIO_ACTU, ISNULL(@USUARIO_CREA, @SYS_LOGIN_USUARIO))
	SELECT @AUD_ESTACION = ISNULL(@ESTACION_ACTU, ISNULL(@ESTACION_CREA, @SYS_ESTACION))
	SELECT @AUD_FECHA = ISNULL(@FECHA_ACTU, ISNULL(@FECHA_CREA, GETDATE()))

	IF NOT EXISTS(SELECT 1 FROM SEG_TIPO_USUARIO_OPCION
				  WHERE CODIGO_SISTEMA=@CODIGO_SISTEMA
				  AND CODIGO_MENU=@CODIGO_MENU
				  AND CODIGO_OPCION=@CODIGO_OPCION
				  AND TIPO_USUARIO=@TIPO_USUARIO)
	BEGIN
		SELECT @TIPO_ACTUALIZA=1
	END

	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			/* Alta de opción: permisos completos por defecto */
			SELECT @NUEVO = 1, @MODIFICAR = 1, @ELIMINAR = 1, @IMPRIMIR = 1

			INSERT INTO SEG_TIPO_USUARIO_OPCION
			(TIPO_USUARIO,CODIGO_SISTEMA,CODIGO_MENU,CODIGO_OPCION,NUEVO,MODIFICAR,ELIMINAR,IMPRIMIR,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU)
			VALUES
			(@TIPO_USUARIO,@CODIGO_SISTEMA,@CODIGO_MENU,@CODIGO_OPCION,@NUEVO,@MODIFICAR,@ELIMINAR,@IMPRIMIR,@AUD_USUARIO,@AUD_FECHA,@AUD_ESTACION,@AUD_USUARIO,@AUD_FECHA,@AUD_ESTACION)

			INSERT INTO SEG_USUARIO_OPCION
			(LOGIN_SISTEMA,CODIGO_SISTEMA,CODIGO_MENU,CODIGO_OPCION,NUEVO,MODIFICAR,ELIMINAR,IMPRIMIR,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU)
			SELECT
				U.LOGIN_SISTEMA,
				@CODIGO_SISTEMA,
				@CODIGO_MENU,
				@CODIGO_OPCION,
				@NUEVO,
				@MODIFICAR,
				@ELIMINAR,
				@IMPRIMIR,
				@AUD_USUARIO,
				@AUD_FECHA,
				@AUD_ESTACION,
				@AUD_USUARIO,
				@AUD_FECHA,
				@AUD_ESTACION
			FROM SEG_USUARIO U
			WHERE U.TIPO_USUARIO = @TIPO_USUARIO
			AND EXISTS
			(
				SELECT 1
				FROM SEG_CONFIG_OPCION C
				WHERE C.CODIGO_SISTEMA = @CODIGO_SISTEMA
				AND C.CODIGO_MENU = @CODIGO_MENU
				AND C.CODIGO_OPCION = @CODIGO_OPCION
			)
			AND NOT EXISTS
			(
				SELECT 1
				FROM SEG_USUARIO_OPCION O
				WHERE O.LOGIN_SISTEMA = U.LOGIN_SISTEMA
				AND O.CODIGO_SISTEMA = @CODIGO_SISTEMA
				AND O.CODIGO_MENU = @CODIGO_MENU
				AND O.CODIGO_OPCION = @CODIGO_OPCION
			)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			IF @NUEVO=0 AND @MODIFICAR=0 AND @ELIMINAR=0 AND @IMPRIMIR=0
			BEGIN
				/* Propagar baja a usuarios del mismo tipo */
				DELETE O
				FROM SEG_USUARIO_OPCION O
				INNER JOIN SEG_USUARIO U ON U.LOGIN_SISTEMA = O.LOGIN_SISTEMA
				WHERE U.TIPO_USUARIO = @TIPO_USUARIO
				AND O.CODIGO_SISTEMA = @CODIGO_SISTEMA
				AND O.CODIGO_MENU = @CODIGO_MENU
				AND O.CODIGO_OPCION = @CODIGO_OPCION

				DELETE FROM SEG_TIPO_USUARIO_OPCION
				WHERE TIPO_USUARIO=@TIPO_USUARIO
				AND CODIGO_SISTEMA=@CODIGO_SISTEMA
				AND CODIGO_MENU=@CODIGO_MENU
				AND CODIGO_OPCION=@CODIGO_OPCION
			END ELSE
			BEGIN
				UPDATE SEG_TIPO_USUARIO_OPCION SET
				NUEVO=@NUEVO,
				MODIFICAR=@MODIFICAR,
				ELIMINAR=@ELIMINAR,
				IMPRIMIR=@IMPRIMIR,
				USUARIO_ACTU=@AUD_USUARIO,
				FECHA_ACTU=@AUD_FECHA,
				ESTACION_ACTU=@AUD_ESTACION
				WHERE TIPO_USUARIO=@TIPO_USUARIO
				AND CODIGO_SISTEMA=@CODIGO_SISTEMA
				AND CODIGO_MENU=@CODIGO_MENU
				AND CODIGO_OPCION=@CODIGO_OPCION
			END
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			/* Propagar baja a usuarios del mismo tipo */
			DELETE O
			FROM SEG_USUARIO_OPCION O
			INNER JOIN SEG_USUARIO U ON U.LOGIN_SISTEMA = O.LOGIN_SISTEMA
			WHERE U.TIPO_USUARIO = @TIPO_USUARIO
			AND O.CODIGO_SISTEMA = @CODIGO_SISTEMA
			AND O.CODIGO_MENU = @CODIGO_MENU
			AND O.CODIGO_OPCION = @CODIGO_OPCION

			DELETE FROM SEG_TIPO_USUARIO_OPCION
			WHERE TIPO_USUARIO=@TIPO_USUARIO
			AND CODIGO_SISTEMA=@CODIGO_SISTEMA
			AND CODIGO_MENU=@CODIGO_MENU
			AND CODIGO_OPCION=@CODIGO_OPCION
		END

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

	END TRY
	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		IF OBJECT_ID(N'dbo.ADMIN_BITACORA_SISTEMA', N'U') IS NOT NULL
		BEGIN
			EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION
		END

	END CATCH;
FINA:
END
GO

PRINT N'PRAL_MTTO_SEG_TIPO_USUARIO_OPCION actualizado (propagación alta/baja a usuarios del tipo).';
GO
