/* ESTACION_* en encabezado SEG_TIPO_USUARIO — ClientInfoHelper supera 30 caracteres */
SET NOCOUNT ON;
GO

IF COL_LENGTH('dbo.SEG_TIPO_USUARIO', 'ESTACION_CREA') IS NOT NULL
BEGIN
	ALTER TABLE dbo.SEG_TIPO_USUARIO ALTER COLUMN ESTACION_CREA varchar(50) NOT NULL;
END
GO

IF COL_LENGTH('dbo.SEG_TIPO_USUARIO', 'ESTACION_ACTU') IS NOT NULL
BEGIN
	ALTER TABLE dbo.SEG_TIPO_USUARIO ALTER COLUMN ESTACION_ACTU varchar(50) NOT NULL;
END
GO

PRINT N'SEG_TIPO_USUARIO: ESTACION_CREA/ACTU ampliadas a varchar(50).';
GO
