/*
  Cuadre patrimonio en Balance General — solo SGUEES (sin linked server CLASS).
  - Si Activo = Pasivo + Patrimonio en saldos, no recalcula 3105/3106.
  - Resultado del periodo desde cuentas IN/GA o 310601/310801 en SGUEES.
*/
SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.FN_CLASS_GASTOINGRESO', N'FN') IS NOT NULL
    DROP FUNCTION dbo.FN_CLASS_GASTOINGRESO;
GO

IF OBJECT_ID(N'dbo.PRAL_IMPR_BALANCE_GENERAL', N'P') IS NOT NULL
    DROP PROCEDURE dbo.PRAL_IMPR_BALANCE_GENERAL;
GO

:r "..\Stored Procedures\dbo.PRAL_IMPR_BALANCE_GENERAL.sql"
GO

DELETE FROM CON_CATALOGO_SALDO_HIS
WHERE CORR_EMPRESA = 1
  AND ANIO_PERIODO = 2026
  AND (
        LEFT(CUENTA_CONTABLE, 4) IN ('3106', '3108')
     OR CUENTA_CONTABLE IN ('3106', '3108', '310601', '310801')
  );

PRINT 'FIX_BALANCE_PATRIMONIO (sin CLASS) aplicado.';
GO
