/*
  Recarga saldos historicos (abril) y actualiza parametros contables.
  Ejecutar despues de desplegar MIGRATE_CLASS_SALDO_HISTORICO.sql corregido.
*/
SET NOCOUNT ON;

:r SETUP_CON_PARAMETRO.sql

DECLARE @E NUMERIC(38, 0), @M NVARCHAR(4000), @F INT;

EXEC dbo.PRAL_MIGR_CLASS_SALDO_HISTORICO
    @ANIO = 2026, @MES_CORTE = 4, @CIERRE = 0, @MODO = 'LIMPIAR',
    @SYS_NUMERO_ERROR = @E OUTPUT, @SYS_MENSAJE_ERROR = @M OUTPUT;

EXEC dbo.PRAL_MIGR_CLASS_SALDO_HISTORICO
    @ANIO = 2026, @MES_CORTE = 4, @CIERRE = 0, @MODO = 'MIGRAR',
    @SYS_NUMERO_ERROR = @E OUTPUT, @SYS_MENSAJE_ERROR = @M OUTPUT, @SYS_FILAS_AFECTADAS = @F OUTPUT;

IF ISNULL(@E, 0) <> 0
BEGIN
    RAISERROR(N'Error HIS: %s', 16, 1, @M);
    RETURN;
END;

PRINT @M;

SELECT COUNT(*) AS CUENTAS_HIS,
       SUM(CASE WHEN ABS(SALDO_INICIAL5) > 0.01 THEN 1 ELSE 0 END) AS CON_SALDO_MAYO_APERTURA
FROM CON_CATALOGO_SALDO_HIS
WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026;

SELECT CUENTA_CONTABLE, SALDO_INICIAL5
FROM CON_CATALOGO_SALDO_HIS
WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026
  AND CUENTA_CONTABLE LIKE '310%'
ORDER BY 1;

PRINT 'Use FECHA_FINAL = 2026-05-31 en Balance y Estado de Resultados.';
GO
