/* ============================================================================
   Alta de "Opciones del Sistema" en menú junto a Configuración de Opciones.
   Idempotente. Copia permisos de quien ya tiene SEG_CONFIG_OPCION.
   ============================================================================
   Ejecutar:
     sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i FIX_MENU_SEG_OPCION_SISTEMA.sql
   ============================================================================ */
SET NOCOUNT ON;

DECLARE @SUITE varchar(30) = 'SGUEES';
DECLARE @USR   varchar(30) = 'admin';
DECLARE @EST   varchar(30) = 'SISTEMA';
DECLARE @HOY   datetime    = GETDATE();

/* Catálogo */
MERGE SEG_OPCION_SISTEMA AS T
USING (VALUES (N'SEG_OPCION_SISTEMA', N'Opciones del Sistema', N'/seg-opcion-sistema')) AS S (CODIGO, NOMBRE, URL)
ON T.CODIGO_OPCION = S.CODIGO
WHEN MATCHED THEN
    UPDATE SET T.NOMBRE_OPCION = S.NOMBRE,
               T.URL_OPCION = S.URL,
               T.IMAGEN_OPCION = N'',
               T.USUARIO_ACTU = @USR,
               T.FECHA_ACTU = @HOY,
               T.ESTACION_ACTU = @EST
WHEN NOT MATCHED THEN
    INSERT (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION, IMAGEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
    VALUES (S.CODIGO, S.NOMBRE, S.URL, N'', @USR, @HOY, @EST);

INSERT INTO SEG_OPCION_SISTEMA_SUITE (CODIGO_OPCION, CODIGO_SUITE)
SELECT N'SEG_OPCION_SISTEMA', @SUITE
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_OPCION_SISTEMA_SUITE s
    WHERE s.CODIGO_OPCION = N'SEG_OPCION_SISTEMA' AND s.CODIGO_SUITE = @SUITE
);

/* Menú: misma ubicación que SEG_CONFIG_OPCION, orden justo antes */
INSERT INTO SEG_CONFIG_OPCION
    (CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT c.CODIGO_SISTEMA,
       c.CODIGO_MENU,
       N'SEG_OPCION_SISTEMA',
       c.ORDEN_SISTEMA,
       c.ORDEN_MENU,
       CASE WHEN c.ORDEN_OPCION > 1 THEN c.ORDEN_OPCION - 1 ELSE 1 END,
       @USR,
       @HOY,
       @EST
FROM SEG_CONFIG_OPCION c
WHERE c.CODIGO_OPCION = N'SEG_CONFIG_OPCION'
  AND NOT EXISTS (
      SELECT 1 FROM SEG_CONFIG_OPCION x
      WHERE x.CODIGO_SISTEMA = c.CODIGO_SISTEMA
        AND x.CODIGO_MENU = c.CODIGO_MENU
        AND x.CODIGO_OPCION = N'SEG_OPCION_SISTEMA'
  );

/* Permisos: mismo CRUD que Configuración de Opciones */
INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT u.LOGIN_SISTEMA,
       u.CODIGO_SISTEMA,
       u.CODIGO_MENU,
       N'SEG_OPCION_SISTEMA',
       u.NUEVO,
       u.MODIFICAR,
       u.ELIMINAR,
       u.IMPRIMIR,
       @USR,
       @HOY,
       @EST
FROM SEG_USUARIO_OPCION u
WHERE u.CODIGO_OPCION = N'SEG_CONFIG_OPCION'
  AND NOT EXISTS (
      SELECT 1 FROM SEG_USUARIO_OPCION x
      WHERE x.LOGIN_SISTEMA = u.LOGIN_SISTEMA
        AND x.CODIGO_SISTEMA = u.CODIGO_SISTEMA
        AND x.CODIGO_MENU = u.CODIGO_MENU
        AND x.CODIGO_OPCION = N'SEG_OPCION_SISTEMA'
  );

PRINT N'Opciones del Sistema registradas en menú y permisos.';

SELECT c.CODIGO_SISTEMA, c.CODIGO_MENU, c.ORDEN_OPCION, c.CODIGO_OPCION, o.NOMBRE_OPCION, o.URL_OPCION
FROM SEG_CONFIG_OPCION c
INNER JOIN SEG_OPCION_SISTEMA o ON c.CODIGO_OPCION = o.CODIGO_OPCION
WHERE c.CODIGO_OPCION IN (N'SEG_OPCION_SISTEMA', N'SEG_CONFIG_OPCION')
ORDER BY c.CODIGO_SISTEMA, c.CODIGO_MENU, c.ORDEN_OPCION;
