/*
  Sincroniza centros de costo y la relacion cuenta <-> centro desde CLASS.

  CLASS:
    - CENTRO_COSTOS.CCOCCN  -> SGUEES CON_CENTRO_COSTO.CODIGO_CENTRO_COSTO
    - TRANSAC.TRACCN        -> codigo de centro en cada movimiento
    - TRANSAC.TRAGLN        -> cuenta (via FN_CLASS_TRAGLN_TO_CUENTA)

  SGUEES:
    - CON_CENTRO_COSTO
    - CON_CATALOGO_CUENTA_CENTRO_COSTO (centros permitidos por cuenta)

  Uso:
    cd "c:\Desarrollo GIT\SGUEES\SGUEES-DB\Scripts"
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -i IMPORT_CLASS_CENTRO_COSTO_REL.sql
*/
SET NOCOUNT ON;

DECLARE @CORR_EMPRESA INT = 1;
DECLARE @NEXT_CC INT;

IF OBJECT_ID(N'dbo.FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO', N'FN') IS NOT NULL
    DROP FUNCTION dbo.FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO;
GO

CREATE FUNCTION dbo.FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO
(
    @CORR_EMPRESA INT,
    @TRACCN VARCHAR(30)
)
RETURNS INT
AS
BEGIN
    DECLARE @COD VARCHAR(30) = LTRIM(RTRIM(ISNULL(@TRACCN, '')));
    DECLARE @CORR INT;

    IF @COD = '' OR @COD = '0'
        SET @COD = '00';

    SELECT TOP 1 @CORR = CC.CORR_CENTRO_COSTO
    FROM CON_CENTRO_COSTO CC
    WHERE CC.CORR_EMPRESA = @CORR_EMPRESA
      AND CC.CODIGO_CENTRO_COSTO = @COD COLLATE DATABASE_DEFAULT;

    IF @CORR IS NULL
        SELECT TOP 1 @CORR = P.CORR_CENTRO_COSTO_DEF
        FROM CON_PARAMETRO P
        WHERE P.CORR_EMPRESA = @CORR_EMPRESA;

    IF @CORR IS NULL
        SELECT TOP 1 @CORR = CC.CORR_CENTRO_COSTO
        FROM CON_CENTRO_COSTO CC
        WHERE CC.CORR_EMPRESA = @CORR_EMPRESA
          AND CC.CODIGO_CENTRO_COSTO = '00';

    RETURN ISNULL(@CORR, 1);
END;
GO

PRINT '=== 1. Centros CLASS faltantes en SGUEES ===';
DECLARE @CORR_EMPRESA INT = 1;
DECLARE @NEXT_CC INT;

SELECT @NEXT_CC = ISNULL(MAX(CORR_CENTRO_COSTO), 0)
FROM CON_CENTRO_COSTO
WHERE CORR_EMPRESA = @CORR_EMPRESA;

;WITH CLASS_CC AS (
    SELECT LTRIM(RTRIM(C.CCOCCN)) AS CODIGO_CENTRO_COSTO,
           MAX(LTRIM(RTRIM(C.CCODSC))) AS NOMBRE_CENTRO
    FROM CLASS_UEES.CLASS_UEES.dbo.CENTRO_COSTOS C
    WHERE C.CCOBNK = '01'
      AND LTRIM(RTRIM(C.CCOCCN)) <> ''
    GROUP BY LTRIM(RTRIM(C.CCOCCN))
)
INSERT INTO CON_CENTRO_COSTO
(
    CORR_EMPRESA, CORR_CENTRO_COSTO, NOMBRE_CENTRO, CUENTA_CONTABLE,
    CODIGO_CENTRO_COSTO, CORR_TIPO_CENTRO_COSTO, ESTADO_CENTRO_COSTO,
    CORR_UNIDAD_NEGOCIO, CORR_AREA_FUNCIONAL, CODIGO_TERMINACION,
    CORR_EMPLEADO_JEFE, CORR_CLIENTE, FECHA_INICIAL, FECHA_FINAL
)
SELECT @CORR_EMPRESA,
       @NEXT_CC + ROW_NUMBER() OVER (ORDER BY N.CODIGO_CENTRO_COSTO),
       LEFT(N.NOMBRE_CENTRO, 100),
       '',
       N.CODIGO_CENTRO_COSTO,
       1,
       'AC',
       0,
       0,
       '',
       0,
       0,
       GETDATE(),
       '9999-12-31'
FROM CLASS_CC N
WHERE NOT EXISTS (
    SELECT 1
    FROM CON_CENTRO_COSTO S
    WHERE S.CORR_EMPRESA = @CORR_EMPRESA
      AND S.CODIGO_CENTRO_COSTO = N.CODIGO_CENTRO_COSTO COLLATE DATABASE_DEFAULT
);

PRINT CAST(@@ROWCOUNT AS VARCHAR(10)) + ' centros nuevos insertados desde CLASS.';

PRINT '=== 2. Relacion cuenta <-> centro desde movimientos CLASS ===';

SELECT DISTINCT
       dbo.FN_CLASS_TRAGLN_TO_CUENTA(
           CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))
           + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
       ) AS CUENTA_CONTABLE,
       LTRIM(RTRIM(TR.TRACCN)) AS TRACCN
INTO #PARES
FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC TR
WHERE TR.TRATYP = 'R'
  AND TR.TRABNK = '01'
  AND TR.TRABRN = '001'
  AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
  AND TR.TRAMOD <> 'P/G';

INSERT INTO #PARES
SELECT DISTINCT
       dbo.FN_CLASS_TRAGLN_TO_CUENTA(
           CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))
           + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
       ),
       LTRIM(RTRIM(TR.TRACCN))
FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC_HST TR
WHERE TR.TRATYP = 'R'
  AND TR.TRABNK = '01'
  AND TR.TRABRN = '001'
  AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
  AND TR.TRAMOD <> 'P/G';

DELETE P
FROM #PARES P
LEFT JOIN CON_CATALOGO_CUENTA C
    ON C.CORR_EMPRESA = @CORR_EMPRESA
   AND C.CUENTA_CONTABLE = P.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
WHERE C.CUENTA_CONTABLE IS NULL
   OR ISNULL(P.CUENTA_CONTABLE, '') = '';

-- Balance: siempre permitir centro 00 en cuentas 1/2/3
INSERT INTO #PARES (CUENTA_CONTABLE, TRACCN)
SELECT C.CUENTA_CONTABLE, '00'
FROM CON_CATALOGO_CUENTA C
WHERE C.CORR_EMPRESA = @CORR_EMPRESA
  AND LEFT(C.CUENTA_CONTABLE, 1) IN ('1', '2', '3')
  AND NOT EXISTS (
      SELECT 1 FROM #PARES P
      WHERE P.CUENTA_CONTABLE = C.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
        AND P.TRACCN = '00'
  );

DELETE FROM CON_CATALOGO_CUENTA_CENTRO_COSTO
WHERE CORR_EMPRESA = @CORR_EMPRESA;

INSERT INTO CON_CATALOGO_CUENTA_CENTRO_COSTO (CORR_EMPRESA, CUENTA_CONTABLE, CORR_CENTRO_COSTO)
SELECT DISTINCT
       @CORR_EMPRESA,
       P.CUENTA_CONTABLE,
       dbo.FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO(@CORR_EMPRESA, P.TRACCN)
FROM #PARES P
WHERE dbo.FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO(@CORR_EMPRESA, P.TRACCN) IS NOT NULL;

PRINT CAST(@@ROWCOUNT AS VARCHAR(10)) + ' relaciones cuenta-centro cargadas.';

SELECT COUNT(*) AS CENTROS_SGUEES FROM CON_CENTRO_COSTO WHERE CORR_EMPRESA = @CORR_EMPRESA;
SELECT COUNT(*) AS RELACIONES FROM CON_CATALOGO_CUENTA_CENTRO_COSTO WHERE CORR_EMPRESA = @CORR_EMPRESA;

SELECT TOP 15
       A.CUENTA_CONTABLE,
       C.NOMBRE_CUENTA,
       B.CODIGO_CENTRO_COSTO,
       B.NOMBRE_CENTRO
FROM CON_CATALOGO_CUENTA_CENTRO_COSTO A
INNER JOIN CON_CENTRO_COSTO B
    ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_CENTRO_COSTO = B.CORR_CENTRO_COSTO
INNER JOIN CON_CATALOGO_CUENTA C
    ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CUENTA_CONTABLE = C.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
WHERE A.CORR_EMPRESA = @CORR_EMPRESA
ORDER BY A.CUENTA_CONTABLE, B.CODIGO_CENTRO_COSTO;

DROP TABLE #PARES;
GO
