/*
  Relacion cuenta <-> centro desde CLASS.BALANCES (129) -> SGUEES (250).

  Origen (solo lectura): CLASS_UEES en 192.168.1.129 via linked server CLASS_UEES
  Destino (escritura):    CON_CENTRO_COSTO, CON_CATALOGO_CUENTA_CENTRO_COSTO

  Equivalente al SELECT legacy sobre BALANCES + CONCAT + CENTRO_COSTOS,
  adaptado al linked server del proyecto SGUEES.

  Requisitos:
    - SETUP_SYS_INSTANCIA_REMOTA.sql ejecutado (linked server CLASS_UEES activo)

  Uso:
    cd "C:\Desarrollo GIT\SGUEES\SGUEES-DB\Scripts"
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i IMPORT_CLASS_CENTRO_COSTO_FROM_BALANCES.sql

  Solo vista previa (no inserta): cambie @MODO = 'PREVIEW'
*/
SET NOCOUNT ON;

DECLARE @CORR_EMPRESA INT = 1;
DECLARE @MODO VARCHAR(10) = 'CARGAR';   -- PREVIEW | CARGAR
DECLARE @BANCO VARCHAR(2) = '01';       -- NULL = todos los bancos CLASS

IF NOT EXISTS (SELECT 1 FROM sys.servers WHERE name = N'CLASS_UEES' AND is_linked = 1)
BEGIN
	RAISERROR(N'Linked server CLASS_UEES no existe. Ejecute SETUP_SYS_INSTANCIA_REMOTA.sql', 16, 1);
	RETURN;
END;

IF OBJECT_ID(N'dbo.FN_CLASS_CONGLN_TO_CUENTA', N'FN') IS NOT NULL
	DROP FUNCTION dbo.FN_CLASS_CONGLN_TO_CUENTA;
GO

CREATE FUNCTION dbo.FN_CLASS_CONGLN_TO_CUENTA(@CONGLN VARCHAR(30))
RETURNS VARCHAR(30)
AS
BEGIN
	DECLARE @raw VARCHAR(30) = LTRIM(RTRIM(ISNULL(@CONGLN, '')));
	IF @raw = ''
		RETURN '';

	DECLARE @n VARCHAR(16);
	BEGIN TRY
		SET @n = CAST(REVERSE(CAST(REVERSE(@raw) AS DECIMAL(16))) AS VARCHAR(16));
	END TRY
	BEGIN CATCH
		RETURN '';
	END CATCH;

	DECLARE @len INT = LEN(@n);
	IF @len = 1
		RETURN @n;
	IF @len % 2 = 1
		RETURN @n + '0';
	RETURN @n;
END;
GO

DECLARE @CORR_EMPRESA INT = 1;
DECLARE @MODO VARCHAR(10) = 'CARGAR';
DECLARE @BANCO VARCHAR(2) = '01';

PRINT N'=== PREVIEW: BALANCES CLASS (129) ===';

;WITH CLASS_PARES AS (
	SELECT DISTINCT
		LTRIM(RTRIM(B.CGLCCN)) AS Centro_Costo,
		LTRIM(RTRIM(CC.CCODSC)) AS Nombre_Centro_Costo,
		dbo.FN_CLASS_CONGLN_TO_CUENTA(CAST(C.CONGLN AS VARCHAR(30))) AS Cuenta_Sin_Ceros,
		LTRIM(RTRIM(C.CONDSC)) AS Nombre_Cuenta
	FROM CLASS_UEES.CLASS_UEES.dbo.BALANCES B
	INNER JOIN CLASS_UEES.CLASS_UEES.dbo.CONCAT C
		ON B.CGLGLN = C.CONGLN
	INNER JOIN CLASS_UEES.CLASS_UEES.dbo.CENTRO_COSTOS CC
		ON B.CGLCCN = CC.CCOCCN
	WHERE LTRIM(RTRIM(B.CGLCCN)) <> '00'
	  AND (@BANCO IS NULL OR LTRIM(RTRIM(CC.CCOBNK)) = @BANCO)
)
SELECT TOP 50 *
FROM CLASS_PARES
WHERE ISNULL(Cuenta_Sin_Ceros, '') <> ''
ORDER BY Centro_Costo, Cuenta_Sin_Ceros;

SELECT COUNT(*) AS TOTAL_PARES_CLASS
FROM (
	SELECT DISTINCT
		LTRIM(RTRIM(B.CGLCCN)) AS Centro_Costo,
		dbo.FN_CLASS_CONGLN_TO_CUENTA(CAST(C.CONGLN AS VARCHAR(30))) AS Cuenta_Sin_Ceros
	FROM CLASS_UEES.CLASS_UEES.dbo.BALANCES B
	INNER JOIN CLASS_UEES.CLASS_UEES.dbo.CONCAT C ON B.CGLGLN = C.CONGLN
	WHERE LTRIM(RTRIM(B.CGLCCN)) <> '00'
) X
WHERE ISNULL(X.Cuenta_Sin_Ceros, '') <> '';

IF UPPER(@MODO) = 'PREVIEW'
BEGIN
	PRINT N'Modo PREVIEW: no se inserto nada en SGUEES.';
	RETURN;
END;

IF OBJECT_ID(N'dbo.FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO', N'FN') IS NULL
BEGIN
	RAISERROR(N'Falta FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO. Ejecute IMPORT_CLASS_CENTRO_COSTO_REL.sql primero.', 16, 1);
	RETURN;
END;

PRINT N'=== 1. Centros CLASS faltantes en CON_CENTRO_COSTO ===';

DECLARE @NEXT_CC INT;
SELECT @NEXT_CC = ISNULL(MAX(CORR_CENTRO_COSTO), 0)
FROM CON_CENTRO_COSTO
WHERE CORR_EMPRESA = @CORR_EMPRESA;

;WITH CLASS_CC AS (
	SELECT LTRIM(RTRIM(CC.CCOCCN)) AS CODIGO_CENTRO_COSTO,
		   MAX(LTRIM(RTRIM(CC.CCODSC))) AS NOMBRE_CENTRO
	FROM CLASS_UEES.CLASS_UEES.dbo.CENTRO_COSTOS CC
	WHERE (@BANCO IS NULL OR LTRIM(RTRIM(CC.CCOBNK)) = @BANCO)
	  AND LTRIM(RTRIM(CC.CCOCCN)) <> ''
	GROUP BY LTRIM(RTRIM(CC.CCOCCN))
)
INSERT INTO CON_CENTRO_COSTO
(
	CORR_EMPRESA, CORR_CENTRO_COSTO, NOMBRE_CENTRO, CUENTA_CONTABLE,
	CODIGO_CENTRO_COSTO, CORR_TIPO_CENTRO_COSTO, ESTADO_CENTRO_COSTO,
	CORR_UNIDAD_NEGOCIO, CORR_AREA_FUNCIONAL, CODIGO_TERMINACION,
	CORR_EMPLEADO_JEFE, CORR_CLIENTE, FECHA_INICIAL, FECHA_FINAL
)
SELECT @CORR_EMPRESA,
	   @NEXT_CC + ROW_NUMBER() OVER (ORDER BY N.CODIGO_CENTRO_COSTO),
	   LEFT(N.NOMBRE_CENTRO, 100),
	   '',
	   N.CODIGO_CENTRO_COSTO,
	   1,
	   'AC',
	   0, 0, '', 0, 0,
	   GETDATE(),
	   '9999-12-31'
FROM CLASS_CC N
WHERE NOT EXISTS (
	SELECT 1
	FROM CON_CENTRO_COSTO S
	WHERE S.CORR_EMPRESA = @CORR_EMPRESA
	  AND S.CODIGO_CENTRO_COSTO = N.CODIGO_CENTRO_COSTO COLLATE DATABASE_DEFAULT
);

PRINT CAST(@@ROWCOUNT AS VARCHAR(10)) + N' centros nuevos.';

PRINT N'=== 2. Relacion cuenta-centro desde BALANCES ===';

SELECT DISTINCT
	   P.Cuenta_Sin_Ceros AS CUENTA_CONTABLE,
	   P.Centro_Costo AS CODIGO_CENTRO_COSTO
INTO #PARES
FROM (
	SELECT DISTINCT
		LTRIM(RTRIM(B.CGLCCN)) AS Centro_Costo,
		dbo.FN_CLASS_CONGLN_TO_CUENTA(CAST(C.CONGLN AS VARCHAR(30))) AS Cuenta_Sin_Ceros
	FROM CLASS_UEES.CLASS_UEES.dbo.BALANCES B
	INNER JOIN CLASS_UEES.CLASS_UEES.dbo.CONCAT C ON B.CGLGLN = C.CONGLN
	WHERE LTRIM(RTRIM(B.CGLCCN)) <> '00'
) P
INNER JOIN CON_CATALOGO_CUENTA CAT
	ON CAT.CORR_EMPRESA = @CORR_EMPRESA
   AND CAT.CUENTA_CONTABLE = P.Cuenta_Sin_Ceros COLLATE DATABASE_DEFAULT
WHERE ISNULL(P.Cuenta_Sin_Ceros, '') <> '';

INSERT INTO #PARES (CUENTA_CONTABLE, CODIGO_CENTRO_COSTO)
SELECT C.CUENTA_CONTABLE, '00'
FROM CON_CATALOGO_CUENTA C
WHERE C.CORR_EMPRESA = @CORR_EMPRESA
  AND LEFT(C.CUENTA_CONTABLE, 1) IN ('1', '2', '3')
  AND NOT EXISTS (
	  SELECT 1 FROM #PARES P
	  WHERE P.CUENTA_CONTABLE = C.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
		AND P.CODIGO_CENTRO_COSTO = '00'
  );

DELETE FROM CON_CATALOGO_CUENTA_CENTRO_COSTO
WHERE CORR_EMPRESA = @CORR_EMPRESA;

INSERT INTO CON_CATALOGO_CUENTA_CENTRO_COSTO (CORR_EMPRESA, CUENTA_CONTABLE, CORR_CENTRO_COSTO)
SELECT DISTINCT
	   @CORR_EMPRESA,
	   P.CUENTA_CONTABLE,
	   dbo.FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO(@CORR_EMPRESA, P.CODIGO_CENTRO_COSTO)
FROM #PARES P
WHERE dbo.FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO(@CORR_EMPRESA, P.CODIGO_CENTRO_COSTO) IS NOT NULL;

PRINT CAST(@@ROWCOUNT AS VARCHAR(10)) + N' relaciones cuenta-centro cargadas desde BALANCES.';

SELECT COUNT(*) AS RELACIONES FROM CON_CATALOGO_CUENTA_CENTRO_COSTO WHERE CORR_EMPRESA = @CORR_EMPRESA;

SELECT TOP 20
	   A.CUENTA_CONTABLE,
	   C.NOMBRE_CUENTA,
	   B.CODIGO_CENTRO_COSTO,
	   B.NOMBRE_CENTRO
FROM CON_CATALOGO_CUENTA_CENTRO_COSTO A
INNER JOIN CON_CENTRO_COSTO B
	ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_CENTRO_COSTO = B.CORR_CENTRO_COSTO
INNER JOIN CON_CATALOGO_CUENTA C
	ON A.CORR_EMPRESA = C.CORR_EMPRESA AND A.CUENTA_CONTABLE = C.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
WHERE A.CORR_EMPRESA = @CORR_EMPRESA
ORDER BY A.CUENTA_CONTABLE, B.CODIGO_CENTRO_COSTO;

DROP TABLE #PARES;
GO
