-- Qué hace: carga inicial de GEN_ACTIVIDAD_ECONOMICA (código + nombre).
-- Cómo lo hace: inserta correlativo secuencial, CODIGO/NOMBRE, ACTIVO=1 y auditoría básica.
-- Nota: el código '46696' aparece 2 veces en el origen; se insertan ambos con CORR distinto.
-- Si la tabla ya tiene datos, ajusta el CORR o limpia antes de ejecutar.
SET NOCOUNT ON;

INSERT INTO dbo.GEN_ACTIVIDAD_ECONOMICA
(
    CORR_ACTIVIDAD_ECONOMICA,
    CODIGO_ACTIVIDAD_ECONOMICA,
    NOMBRE_ACTIVIDAD_ECONOMICA,
    ACTIVO_ACTIVIDAD_ECONOMICA,
    USUARIO_CREA,
    ESTACION_CREA,
    FECHA_CREA
)
VALUES
(1, '01111', N'Cultivo de cereales excepto arroz y para forrajes', 1, 'juanh', HOST_NAME(), GETDATE()),
(2, '01112', N'Cultivo de legumbres', 1, 'juanh', HOST_NAME(), GETDATE()),
(3, '01113', N'Cultivo de semillas oleaginosas', 1, 'juanh', HOST_NAME(), GETDATE()),
(4, '01114', N'Cultivo de plantas para la preparación de semillas', 1, 'juanh', HOST_NAME(), GETDATE()),
(5, '01119', N'Cultivo de otros cereales excepto arroz y forrajeros n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(6, '01120', N'Cultivo de arroz', 1, 'juanh', HOST_NAME(), GETDATE()),
(7, '01131', N'Cultivo de raíces y tubérculos', 1, 'juanh', HOST_NAME(), GETDATE()),
(8, '01132', N'Cultivo de brotes, bulbos, vegetales tubérculos y cultivos similares', 1, 'juanh', HOST_NAME(), GETDATE()),
(9, '01133', N'Cultivo horrícola de fruto', 1, 'juanh', HOST_NAME(), GETDATE()),
(10, '01134', N'Cultivo de hortalizas de hoja y otras hortalizas ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(11, '01140', N'Cultivo de caña de azúcar', 1, 'juanh', HOST_NAME(), GETDATE()),
(12, '01150', N'Cultivo de tabaco', 1, 'juanh', HOST_NAME(), GETDATE()),
(13, '01161', N'Cultivo de algodón', 1, 'juanh', HOST_NAME(), GETDATE()),
(14, '01162', N'Cultivo de fibras vegetales excepto algodón', 1, 'juanh', HOST_NAME(), GETDATE()),
(15, '01191', N'Cultivo de plantas no perennes para la producción de semillas y flores', 1, 'juanh', HOST_NAME(), GETDATE()),
(16, '01192', N'Cultivo de cereales y pastos para la alimentación animal', 1, 'juanh', HOST_NAME(), GETDATE()),
(17, '01199', N'Producción de cultivos no estacionales ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(18, '01220', N'Cultivo de frutas tropicales', 1, 'juanh', HOST_NAME(), GETDATE()),
(19, '01230', N'Cultivo de cítricos', 1, 'juanh', HOST_NAME(), GETDATE()),
(20, '01240', N'Cultivo de frutas de pepita y hueso', 1, 'juanh', HOST_NAME(), GETDATE()),
(21, '01251', N'Cultivo de frutas ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(22, '01252', N'Cultivo de otros frutos y nueces de árboles y arbustos', 1, 'juanh', HOST_NAME(), GETDATE()),
(23, '01260', N'Cultivo de frutos oleaginosos', 1, 'juanh', HOST_NAME(), GETDATE()),
(24, '01271', N'Cultivo de café', 1, 'juanh', HOST_NAME(), GETDATE()),
(25, '01272', N'Cultivo de plantas para la elaboración de bebidas excepto café', 1, 'juanh', HOST_NAME(), GETDATE()),
(26, '01281', N'Cultivo de especias y aromáticas', 1, 'juanh', HOST_NAME(), GETDATE()),
(27, '01282', N'Cultivo de plantas para la obtención de productos medicinales y farmacéuticos', 1, 'juanh', HOST_NAME(), GETDATE()),
(28, '01291', N'Cultivo de árboles de hule (caucho) para la obtención de látex', 1, 'juanh', HOST_NAME(), GETDATE()),
(29, '01292', N'Cultivo de plantas para la obtención de productos químicos y colorantes', 1, 'juanh', HOST_NAME(), GETDATE()),
(30, '01299', N'Producción de cultivos perennes ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(31, '01300', N'Propagación de plantas', 1, 'juanh', HOST_NAME(), GETDATE()),
(32, '01301', N'Cultivo de plantas y flores ornamentales', 1, 'juanh', HOST_NAME(), GETDATE()),
(33, '01410', N'Cría y engorde de ganado bovino', 1, 'juanh', HOST_NAME(), GETDATE()),
(34, '01420', N'Cría de caballos y otros equinos', 1, 'juanh', HOST_NAME(), GETDATE()),
(35, '01440', N'Cría de ovejas y cabras', 1, 'juanh', HOST_NAME(), GETDATE()),
(36, '01450', N'Cría de cerdos', 1, 'juanh', HOST_NAME(), GETDATE()),
(37, '01460', N'Cría de aves de corral y producción de huevos', 1, 'juanh', HOST_NAME(), GETDATE()),
(38, '01491', N'Cría de abejas apicultura para la obtención de miel y otros productos apícolas', 1, 'juanh', HOST_NAME(), GETDATE()),
(39, '01492', N'Cría de conejos', 1, 'juanh', HOST_NAME(), GETDATE()),
(40, '01493', N'Cría de iguanas y garrobos', 1, 'juanh', HOST_NAME(), GETDATE()),
(41, '01494', N'Cría de mariposas y otros insectos', 1, 'juanh', HOST_NAME(), GETDATE()),
(42, '01499', N'Cría y obtención de productos animales n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(43, '01500', N'Cultivo de productos agrícolas en combinación con la cría de animales', 1, 'juanh', HOST_NAME(), GETDATE()),
(44, '01611', N'Servicios de maquinaria agrícola', 1, 'juanh', HOST_NAME(), GETDATE()),
(45, '01612', N'Control de plagas', 1, 'juanh', HOST_NAME(), GETDATE()),
(46, '01613', N'Servicios de riego', 1, 'juanh', HOST_NAME(), GETDATE()),
(47, '01614', N'Servicios de contratación de mano de obra para la agricultura', 1, 'juanh', HOST_NAME(), GETDATE()),
(48, '01619', N'Servicios agrícolas ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(49, '01621', N'Actividades para mejorar la reproducción, el crecimiento y el rendimiento de los animales y sus productos', 1, 'juanh', HOST_NAME(), GETDATE()),
(50, '01622', N'Servicios de mano de obra pecuaria', 1, 'juanh', HOST_NAME(), GETDATE()),
(51, '01629', N'Servicios pecuarios ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(52, '01631', N'Labores post cosecha de preparación de los productos agrícolas para su comercialización o para la industria', 1, 'juanh', HOST_NAME(), GETDATE()),
(53, '01632', N'Servicio de beneficio de café', 1, 'juanh', HOST_NAME(), GETDATE()),
(54, '01633', N'Servicio de beneficiado de plantas textiles (incluye el beneficiado cuando este es realizado en la misma explotación agropecuaria)', 1, 'juanh', HOST_NAME(), GETDATE()),
(55, '01640', N'Tratamiento de semillas para la propagación', 1, 'juanh', HOST_NAME(), GETDATE()),
(56, '01700', N'Caza ordinaria y mediante trampas, repoblación de animales de caza y servicios conexos', 1, 'juanh', HOST_NAME(), GETDATE()),
(57, '02100', N'Silvicultura y otras actividades forestales', 1, 'juanh', HOST_NAME(), GETDATE()),
(58, '02200', N'Extracción de madera', 1, 'juanh', HOST_NAME(), GETDATE()),
(59, '02300', N'Recolección de productos diferentes a la madera', 1, 'juanh', HOST_NAME(), GETDATE()),
(60, '02400', N'Servicios de apoyo a la silvicultura', 1, 'juanh', HOST_NAME(), GETDATE()),
(61, '03110', N'Pesca marítima de altura y costera', 1, 'juanh', HOST_NAME(), GETDATE()),
(62, '03120', N'Pesca de agua dulce', 1, 'juanh', HOST_NAME(), GETDATE()),
(63, '03210', N'Acuicultura marítima', 1, 'juanh', HOST_NAME(), GETDATE()),
(64, '03220', N'Acuicultura de agua dulce', 1, 'juanh', HOST_NAME(), GETDATE()),
(65, '03300', N'Servicios de apoyo a la pesca y acuicultura', 1, 'juanh', HOST_NAME(), GETDATE()),
(66, '05100', N'Extracción de huila', 1, 'juanh', HOST_NAME(), GETDATE()),
(67, '05200', N'Extracción y aglomeración de lignito', 1, 'juanh', HOST_NAME(), GETDATE()),
(68, '06100', N'Extracción de petróleo crudo', 1, 'juanh', HOST_NAME(), GETDATE()),
(69, '06200', N'Extracción de gas natural', 1, 'juanh', HOST_NAME(), GETDATE()),
(70, '07100', N'Extracción de minerales de hierro', 1, 'juanh', HOST_NAME(), GETDATE()),
(71, '07210', N'Extracción de minerales de uranio y torio', 1, 'juanh', HOST_NAME(), GETDATE()),
(72, '07290', N'Extracción de minerales metalíferos no ferrosos', 1, 'juanh', HOST_NAME(), GETDATE()),
(73, '08100', N'Extracción de piedra, arena y arcilla', 1, 'juanh', HOST_NAME(), GETDATE()),
(74, '08910', N'Extracción de minerales para la fabricación de abonos y productos químicos', 1, 'juanh', HOST_NAME(), GETDATE()),
(75, '08920', N'Extracción y aglomeración de turba', 1, 'juanh', HOST_NAME(), GETDATE()),
(76, '08930', N'Extracción de sal', 1, 'juanh', HOST_NAME(), GETDATE()),
(77, '08990', N'Explotación de otras minas y canteras ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(78, '09100', N'Actividades de apoyo a la extracción de petróleo y gas natural', 1, 'juanh', HOST_NAME(), GETDATE()),
(79, '09900', N'Actividades de apoyo a la explotación de minas y canteras', 1, 'juanh', HOST_NAME(), GETDATE()),
(80, '10101', N'Servicio de rastros y mataderos de bovinos y porcinos', 1, 'juanh', HOST_NAME(), GETDATE()),
(81, '10102', N'Matanza y procesamiento de bovinos y porcinos', 1, 'juanh', HOST_NAME(), GETDATE()),
(82, '10103', N'Matanza y procesamientos de aves de corral', 1, 'juanh', HOST_NAME(), GETDATE()),
(83, '10104', N'Elaboración y conservación de embutidos y tripas naturales', 1, 'juanh', HOST_NAME(), GETDATE()),
(84, '10105', N'Servicios de conservación y empaque de carnes', 1, 'juanh', HOST_NAME(), GETDATE()),
(85, '10106', N'Elaboración de conservación de grasas y aceites animales', 1, 'juanh', HOST_NAME(), GETDATE()),
(86, '10107', N'Servicios de molienda de carne', 1, 'juanh', HOST_NAME(), GETDATE()),
(87, '10108', N'Elaboración de productos de carne ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(88, '10201', N'Procesamiento y conservación de pescado, crustáceos y moluscos', 1, 'juanh', HOST_NAME(), GETDATE()),
(89, '10209', N'Fabricación de productos de pescado ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(90, '10301', N'Elaboración de jugos de frutas y hortalizas', 1, 'juanh', HOST_NAME(), GETDATE()),
(91, '10302', N'Elaboración y envase de jaleas, mermeladas y frutas deshidratadas', 1, 'juanh', HOST_NAME(), GETDATE()),
(92, '10309', N'Elaboración de productos de frutas y hortalizas n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(93, '10401', N'Fabricación de aceites y grasas vegetales y animales comestibles', 1, 'juanh', HOST_NAME(), GETDATE()),
(94, '10402', N'Fabricación de aceites y grasas vegetales y animales no comestibles', 1, 'juanh', HOST_NAME(), GETDATE()),
(95, '10409', N'Servicio de maquilado de aceites', 1, 'juanh', HOST_NAME(), GETDATE()),
(96, '10501', N'Fabricación de productos lácteos excepto sorbetes y quesos sustitutos', 1, 'juanh', HOST_NAME(), GETDATE()),
(97, '10502', N'Fabricación de sorbetes y helados', 1, 'juanh', HOST_NAME(), GETDATE()),
(98, '10503', N'Fabricación de quesos', 1, 'juanh', HOST_NAME(), GETDATE()),
(99, '10611', N'Molienda de cereales', 1, 'juanh', HOST_NAME(), GETDATE()),
(100, '10612', N'Elaboración de cereales para el desayuno y similares', 1, 'juanh', HOST_NAME(), GETDATE()),
(101, '10613', N'Servicios de beneficiado de productos agrícolas ncp (excluye Beneficio de azúcar rama 1072 y beneficio de café rama 0163)', 1, 'juanh', HOST_NAME(), GETDATE()),
(102, '10621', N'Fabricación de almidón', 1, 'juanh', HOST_NAME(), GETDATE()),
(103, '10628', N'Servicio de molienda de maíz húmedo molino para nixtamal', 1, 'juanh', HOST_NAME(), GETDATE()),
(104, '10711', N'Elaboración de tortillas', 1, 'juanh', HOST_NAME(), GETDATE()),
(105, '10712', N'Fabricación de pan, galletas y barquillos', 1, 'juanh', HOST_NAME(), GETDATE()),
(106, '10713', N'Fabricación de repostería', 1, 'juanh', HOST_NAME(), GETDATE()),
(107, '10721', N'Ingenios azucareros', 1, 'juanh', HOST_NAME(), GETDATE()),
(108, '10722', N'Molienda de caña de azúcar para la elaboración de dulces', 1, 'juanh', HOST_NAME(), GETDATE()),
(109, '10723', N'Elaboración de jarabes de azúcar y otros similares', 1, 'juanh', HOST_NAME(), GETDATE()),
(110, '10724', N'Maquilado de azúcar de caña', 1, 'juanh', HOST_NAME(), GETDATE()),
(111, '10730', N'Fabricación de cacao, chocolates y productos de confitería', 1, 'juanh', HOST_NAME(), GETDATE()),
(112, '10740', N'Elaboración de macarrones, fideos, y productos farináceos similares', 1, 'juanh', HOST_NAME(), GETDATE()),
(113, '10750', N'Elaboración de comidas y platos preparados para la reventa en', 1, 'juanh', HOST_NAME(), GETDATE()),
(114, '10791', N'Elaboración de productos de café', 1, 'juanh', HOST_NAME(), GETDATE()),
(115, '10792', N'Elaboración de especies, sazonadores y condimentos', 1, 'juanh', HOST_NAME(), GETDATE()),
(116, '10793', N'Elaboración de sopas, cremas y consomé', 1, 'juanh', HOST_NAME(), GETDATE()),
(117, '10794', N'Fabricación de bocadillos tostados y/o fritos', 1, 'juanh', HOST_NAME(), GETDATE()),
(118, '10799', N'Elaboración de productos alimenticios ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(119, '10800', N'Elaboración de alimentos preparados para animales', 1, 'juanh', HOST_NAME(), GETDATE()),
(120, '11012', N'Fabricación de aguardiente y licores', 1, 'juanh', HOST_NAME(), GETDATE()),
(121, '11020', N'Elaboración de vinos', 1, 'juanh', HOST_NAME(), GETDATE()),
(122, '11030', N'Fabricación de cerveza', 1, 'juanh', HOST_NAME(), GETDATE()),
(123, '11041', N'Fabricación de aguas gaseosas', 1, 'juanh', HOST_NAME(), GETDATE()),
(124, '11042', N'Fabricación y envasado de agua', 1, 'juanh', HOST_NAME(), GETDATE()),
(125, '11043', N'Elaboración de refrescos', 1, 'juanh', HOST_NAME(), GETDATE()),
(126, '11048', N'Maquilado de aguas gaseosas', 1, 'juanh', HOST_NAME(), GETDATE()),
(127, '11049', N'Elaboración de bebidas no alcohólicas', 1, 'juanh', HOST_NAME(), GETDATE()),
(128, '12000', N'Elaboración de productos de tabaco', 1, 'juanh', HOST_NAME(), GETDATE()),
(129, '13111', N'Preparación de fibras textiles', 1, 'juanh', HOST_NAME(), GETDATE()),
(130, '13112', N'Fabricación de hilados', 1, 'juanh', HOST_NAME(), GETDATE()),
(131, '13120', N'Fabricación de telas', 1, 'juanh', HOST_NAME(), GETDATE()),
(132, '13130', N'Acabado de productos textiles', 1, 'juanh', HOST_NAME(), GETDATE()),
(133, '13910', N'Fabricación de tejidos de punto y ganchillo', 1, 'juanh', HOST_NAME(), GETDATE()),
(134, '13921', N'Fabricación de productos textiles para el hogar', 1, 'juanh', HOST_NAME(), GETDATE()),
(135, '13922', N'Sacos, bolsas y otros artículos textiles', 1, 'juanh', HOST_NAME(), GETDATE()),
(136, '13929', N'Fabricación de artículos confeccionados con materiales textiles, excepto prendas de vestir n.c.p', 1, 'juanh', HOST_NAME(), GETDATE()),
(137, '13930', N'Fabricación de tapices y alfombras', 1, 'juanh', HOST_NAME(), GETDATE()),
(138, '13941', N'Fabricación de cuerdas de henequén y otras fibras naturales (lazos, pitas)', 1, 'juanh', HOST_NAME(), GETDATE()),
(139, '13942', N'Fabricación de redes de diversos materiales', 1, 'juanh', HOST_NAME(), GETDATE()),
(140, '13948', N'Maquilado de productos trenzables de cualquier material (petates, sillas, etc.)', 1, 'juanh', HOST_NAME(), GETDATE()),
(141, '13991', N'Fabricación de adornos, etiquetas y otros artículos para prendas de vestir', 1, 'juanh', HOST_NAME(), GETDATE()),
(142, '13992', N'Servicio de bordados en artículos y prendas de tela', 1, 'juanh', HOST_NAME(), GETDATE()),
(143, '13999', N'Fabricación de productos textiles ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(144, '14101', N'Fabricación de ropa interior, para dormir y similares', 1, 'juanh', HOST_NAME(), GETDATE()),
(145, '14102', N'Fabricación de ropa para niños', 1, 'juanh', HOST_NAME(), GETDATE()),
(146, '14103', N'Fabricación de prendas de vestir para ambos sexos', 1, 'juanh', HOST_NAME(), GETDATE()),
(147, '14104', N'Confección de prendas a medida', 1, 'juanh', HOST_NAME(), GETDATE()),
(148, '14105', N'Fabricación de prendas de vestir para deportes', 1, 'juanh', HOST_NAME(), GETDATE()),
(149, '14106', N'Elaboración de artesanías de uso personal confeccionadas especialmente de materiales textiles', 1, 'juanh', HOST_NAME(), GETDATE()),
(150, '14108', N'Maquilado de prendas de vestir, accesorios y otros', 1, 'juanh', HOST_NAME(), GETDATE()),
(151, '14109', N'Fabricación de prendas y accesorios de vestir n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(152, '14200', N'Fabricación de artículos de piel', 1, 'juanh', HOST_NAME(), GETDATE()),
(153, '14301', N'Fabricación de calcetines, calcetas, medias (panty house) y otros similares', 1, 'juanh', HOST_NAME(), GETDATE()),
(154, '14302', N'Fabricación de ropa interior de tejido de punto', 1, 'juanh', HOST_NAME(), GETDATE()),
(155, '14309', N'Fabricación de prendas de vestir de tejido de punto ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(156, '15110', N'Curtido y adobo de cueros; adobo y teñido de pieles', 1, 'juanh', HOST_NAME(), GETDATE()),
(157, '15121', N'Fabricación de maletas, bolsos de mano y otros artículos de marroquinería', 1, 'juanh', HOST_NAME(), GETDATE()),
(158, '15122', N'Fabricación de monturas, accesorios y vainas talabartería', 1, 'juanh', HOST_NAME(), GETDATE()),
(159, '15123', N'Fabricación de artesanías principalmente de cuero natural y sintético', 1, 'juanh', HOST_NAME(), GETDATE()),
(160, '15128', N'Maquilado de artículos de cuero natural, sintético y de otros materiales', 1, 'juanh', HOST_NAME(), GETDATE()),
(161, '15201', N'Fabricación de calzado', 1, 'juanh', HOST_NAME(), GETDATE()),
(162, '15202', N'Fabricación de partes y accesorios de calzado', 1, 'juanh', HOST_NAME(), GETDATE()),
(163, '15208', N'Maquilado de partes y accesorios de calzado', 1, 'juanh', HOST_NAME(), GETDATE()),
(164, '16100', N'Aserradero y acepilladura de madera', 1, 'juanh', HOST_NAME(), GETDATE()),
(165, '16210', N'Fabricación de madera laminada, terciada, enchapada y contrachapada, paneles para la construcción', 1, 'juanh', HOST_NAME(), GETDATE()),
(166, '16220', N'Fabricación de partes y piezas de carpintería para edificios y construcciones', 1, 'juanh', HOST_NAME(), GETDATE()),
(167, '16230', N'Fabricación de envases y recipientes de madera', 1, 'juanh', HOST_NAME(), GETDATE()),
(168, '16292', N'Fabricación de artesanías de madera, semillas, materiales trenzables', 1, 'juanh', HOST_NAME(), GETDATE()),
(169, '16299', N'Fabricación de productos de madera, corcho, paja y materiales trenzables ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(170, '17010', N'Fabricación de pasta de madera, papel y cartón', 1, 'juanh', HOST_NAME(), GETDATE()),
(171, '17020', N'Fabricación de papel y cartón ondulado y envases de papel y cartón', 1, 'juanh', HOST_NAME(), GETDATE()),
(172, '17091', N'Fabricación de artículos de papel y cartón de uso personal y doméstico', 1, 'juanh', HOST_NAME(), GETDATE()),
(173, '17092', N'Fabricación de productos de papel ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(174, '18110', N'Impresión', 1, 'juanh', HOST_NAME(), GETDATE()),
(175, '18120', N'Servicios relacionados con la impresión', 1, 'juanh', HOST_NAME(), GETDATE()),
(176, '18200', N'Reproducción de grabaciones', 1, 'juanh', HOST_NAME(), GETDATE()),
(177, '19100', N'Fabricación de productos de hornos de coque', 1, 'juanh', HOST_NAME(), GETDATE()),
(178, '19201', N'Fabricación de combustible', 1, 'juanh', HOST_NAME(), GETDATE()),
(179, '19202', N'Fabricación de aceites y lubricantes', 1, 'juanh', HOST_NAME(), GETDATE()),
(180, '20111', N'Fabricación de materias primas para la fabricación de colorantes', 1, 'juanh', HOST_NAME(), GETDATE()),
(181, '20112', N'Fabricación de materiales curtientes', 1, 'juanh', HOST_NAME(), GETDATE()),
(182, '20113', N'Fabricación de gases industriales', 1, 'juanh', HOST_NAME(), GETDATE()),
(183, '20114', N'Fabricación de alcohol etílico', 1, 'juanh', HOST_NAME(), GETDATE()),
(184, '20119', N'Fabricación de sustancias químicas básicas', 1, 'juanh', HOST_NAME(), GETDATE()),
(185, '20120', N'Fabricación de abonos y fertilizantes', 1, 'juanh', HOST_NAME(), GETDATE()),
(186, '20130', N'Fabricación de plástico y caucho en formas primarias', 1, 'juanh', HOST_NAME(), GETDATE()),
(187, '20210', N'Fabricación de plaguicidas y otros productos químicos de uso agropecuario', 1, 'juanh', HOST_NAME(), GETDATE()),
(188, '20220', N'Fabricación de pinturas, barnices y productos de revestimiento similares; tintas de imprenta y masillas', 1, 'juanh', HOST_NAME(), GETDATE()),
(189, '20231', N'Fabricación de jabones, detergentes y similares para limpieza', 1, 'juanh', HOST_NAME(), GETDATE()),
(190, '20232', N'Fabricación de perfumes, cosméticos y productos de higiene y cuidado personal, incluyendo tintes, champú, etc.', 1, 'juanh', HOST_NAME(), GETDATE()),
(191, '20291', N'Fabricación de tintas y colores para escribir y pintar; fabricación de cintas para impresoras', 1, 'juanh', HOST_NAME(), GETDATE()),
(192, '20292', N'Fabricación de productos pirotécnicos, explosivos y municiones', 1, 'juanh', HOST_NAME(), GETDATE()),
(193, '20299', N'Fabricación de productos químicos n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(194, '20300', N'Fabricación de fibras artificiales', 1, 'juanh', HOST_NAME(), GETDATE()),
(195, '21001', N'Manufactura de productos farmacéuticos, sustancias químicas y productos botánicos', 1, 'juanh', HOST_NAME(), GETDATE()),
(196, '21008', N'Maquilado de medicamentos', 1, 'juanh', HOST_NAME(), GETDATE()),
(197, '22110', N'Fabricación de cubiertas y cámaras; renovación y recauchutado de cubiertas', 1, 'juanh', HOST_NAME(), GETDATE()),
(198, '22190', N'Fabricación de otros productos de caucho', 1, 'juanh', HOST_NAME(), GETDATE()),
(199, '22201', N'Fabricación de envases plásticos', 1, 'juanh', HOST_NAME(), GETDATE()),
(200, '22202', N'Fabricación de productos plásticos para uso personal o doméstico', 1, 'juanh', HOST_NAME(), GETDATE()),
(201, '22208', N'Maquila de plásticos', 1, 'juanh', HOST_NAME(), GETDATE()),
(202, '22209', N'Fabricación de productos plásticos n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(203, '23101', N'Fabricación de vidrio', 1, 'juanh', HOST_NAME(), GETDATE()),
(204, '23102', N'Fabricación de recipientes y envases de vidrio', 1, 'juanh', HOST_NAME(), GETDATE()),
(205, '23108', N'Servicio de maquilado', 1, 'juanh', HOST_NAME(), GETDATE()),
(206, '23109', N'Fabricación de productos de vidrio ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(207, '23910', N'Fabricación de productos refractarios', 1, 'juanh', HOST_NAME(), GETDATE()),
(208, '23920', N'Fabricación de productos de arcilla para la construcción', 1, 'juanh', HOST_NAME(), GETDATE()),
(209, '23931', N'Fabricación de productos de cerámica y porcelana no refractaria', 1, 'juanh', HOST_NAME(), GETDATE()),
(210, '23932', N'Fabricación de productos de cerámica y porcelana ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(211, '23940', N'Fabricación de cemento, cal y yeso', 1, 'juanh', HOST_NAME(), GETDATE()),
(212, '23950', N'Fabricación de artículos de hormigón, cemento y yeso', 1, 'juanh', HOST_NAME(), GETDATE()),
(213, '23960', N'Corte, tallado y acabado de la piedra', 1, 'juanh', HOST_NAME(), GETDATE()),
(214, '23990', N'Fabricación de productos minerales no metálicos ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(215, '24100', N'Industrias básicas de hierro y acero', 1, 'juanh', HOST_NAME(), GETDATE()),
(216, '24200', N'Fabricación de productos primarios de metales preciosos y metales no ferrosos', 1, 'juanh', HOST_NAME(), GETDATE()),
(217, '24310', N'Fundición de hierro y acero', 1, 'juanh', HOST_NAME(), GETDATE()),
(218, '24320', N'Fundición de metales no ferrosos', 1, 'juanh', HOST_NAME(), GETDATE()),
(219, '25111', N'Fabricación de productos metálicos para uso estructural', 1, 'juanh', HOST_NAME(), GETDATE()),
(220, '25118', N'Servicio de maquila para la fabricación de estructuras metálicas', 1, 'juanh', HOST_NAME(), GETDATE()),
(221, '25120', N'Fabricación de tanques, depósitos y recipientes de metal', 1, 'juanh', HOST_NAME(), GETDATE()),
(222, '25130', N'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central', 1, 'juanh', HOST_NAME(), GETDATE()),
(223, '25200', N'Fabricación de armas y municiones', 1, 'juanh', HOST_NAME(), GETDATE()),
(224, '25910', N'Forjado, prensado, estampado y laminado de metales; pulvimetalurgia', 1, 'juanh', HOST_NAME(), GETDATE()),
(225, '25920', N'Tratamiento y revestimiento de metales', 1, 'juanh', HOST_NAME(), GETDATE()),
(226, '25930', N'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería', 1, 'juanh', HOST_NAME(), GETDATE()),
(227, '25991', N'Fabricación de envases y artículos conexos de metal', 1, 'juanh', HOST_NAME(), GETDATE()),
(228, '25992', N'Fabricación de artículos metálicos de uso personal y/o doméstico', 1, 'juanh', HOST_NAME(), GETDATE()),
(229, '25999', N'Fabricación de productos elaborados de metal ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(230, '26100', N'Fabricación de componentes electrónicos', 1, 'juanh', HOST_NAME(), GETDATE()),
(231, '26200', N'Fabricación de computadoras y equipo conexo', 1, 'juanh', HOST_NAME(), GETDATE()),
(232, '26300', N'Fabricación de equipo de comunicaciones', 1, 'juanh', HOST_NAME(), GETDATE()),
(233, '26400', N'Fabricación de aparatos electrónicos de consumo para audio, video radio y televisión', 1, 'juanh', HOST_NAME(), GETDATE()),
(234, '26510', N'Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y de control de procesos industriales', 1, 'juanh', HOST_NAME(), GETDATE()),
(235, '26520', N'Fabricación de relojes y piezas de relojes', 1, 'juanh', HOST_NAME(), GETDATE()),
(236, '26600', N'Fabricación de equipo médico de irradiación y equipo electrónico de uso médico y terapéutico', 1, 'juanh', HOST_NAME(), GETDATE()),
(237, '26700', N'Fabricación de instrumentos de óptica y equipo fotográfico', 1, 'juanh', HOST_NAME(), GETDATE()),
(238, '26800', N'Fabricación de medios magnéticos y ópticos', 1, 'juanh', HOST_NAME(), GETDATE()),
(239, '27100', N'Fabricación de motores, generadores, transformadores eléctricos, aparatos de distribución y control de electricidad', 1, 'juanh', HOST_NAME(), GETDATE()),
(240, '27200', N'Fabricación de pilas, baterías y acumuladores', 1, 'juanh', HOST_NAME(), GETDATE()),
(241, '27310', N'Fabricación de cables de fibra óptica', 1, 'juanh', HOST_NAME(), GETDATE()),
(242, '27320', N'Fabricación de otros hilos y cables eléctricos', 1, 'juanh', HOST_NAME(), GETDATE()),
(243, '27330', N'Fabricación de dispositivos de cableados', 1, 'juanh', HOST_NAME(), GETDATE()),
(244, '27400', N'Fabricación de equipo eléctrico de iluminación', 1, 'juanh', HOST_NAME(), GETDATE()),
(245, '27500', N'Fabricación de aparatos de uso doméstico', 1, 'juanh', HOST_NAME(), GETDATE()),
(246, '27900', N'Fabricación de otros tipos de equipo eléctrico', 1, 'juanh', HOST_NAME(), GETDATE()),
(247, '28110', N'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas', 1, 'juanh', HOST_NAME(), GETDATE()),
(248, '28120', N'Fabricación de equipo hidráulico', 1, 'juanh', HOST_NAME(), GETDATE()),
(249, '28130', N'Fabricación de otras bombas, compresores, grifos y válvulas', 1, 'juanh', HOST_NAME(), GETDATE()),
(250, '28140', N'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión', 1, 'juanh', HOST_NAME(), GETDATE()),
(251, '28150', N'Fabricación de hornos y quemadores', 1, 'juanh', HOST_NAME(), GETDATE()),
(252, '28160', N'Fabricación de equipo de elevación y manipulación', 1, 'juanh', HOST_NAME(), GETDATE()),
(253, '28170', N'Fabricación de maquinaria y equipo de oficina', 1, 'juanh', HOST_NAME(), GETDATE()),
(254, '28180', N'Fabricación de herramientas manuales', 1, 'juanh', HOST_NAME(), GETDATE()),
(255, '28190', N'Fabricación de otros tipos de maquinaria de uso general', 1, 'juanh', HOST_NAME(), GETDATE()),
(256, '28210', N'Fabricación de maquinaria agropecuaria y forestal', 1, 'juanh', HOST_NAME(), GETDATE()),
(257, '28220', N'Fabricación de máquinas para conformar metales y maquinaria herramienta', 1, 'juanh', HOST_NAME(), GETDATE()),
(258, '28230', N'Fabricación de maquinaria metalúrgica', 1, 'juanh', HOST_NAME(), GETDATE()),
(259, '28240', N'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción', 1, 'juanh', HOST_NAME(), GETDATE()),
(260, '28250', N'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco', 1, 'juanh', HOST_NAME(), GETDATE()),
(261, '28260', N'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros', 1, 'juanh', HOST_NAME(), GETDATE()),
(262, '28291', N'Fabricación de máquinas para imprenta', 1, 'juanh', HOST_NAME(), GETDATE()),
(263, '28299', N'Fabricación de maquinaria de uso especial ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(264, '29100', N'Fabricación vehículos automotores', 1, 'juanh', HOST_NAME(), GETDATE()),
(265, '29200', N'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semiremolques', 1, 'juanh', HOST_NAME(), GETDATE()),
(266, '29300', N'Fabricación de partes, piezas y accesorios para vehículos automotores', 1, 'juanh', HOST_NAME(), GETDATE()),
(267, '30110', N'Fabricación de buques', 1, 'juanh', HOST_NAME(), GETDATE()),
(268, '30120', N'Construcción y reparación de embarcaciones de recreo', 1, 'juanh', HOST_NAME(), GETDATE()),
(269, '30200', N'Fabricación de locomotoras y de material rodante', 1, 'juanh', HOST_NAME(), GETDATE()),
(270, '30300', N'Fabricación de aeronaves y naves espaciales', 1, 'juanh', HOST_NAME(), GETDATE()),
(271, '30400', N'Fabricación de vehículos militares de combate', 1, 'juanh', HOST_NAME(), GETDATE()),
(272, '30910', N'Fabricación de motocicletas', 1, 'juanh', HOST_NAME(), GETDATE()),
(273, '30920', N'Fabricación de bicicletas y sillones de ruedas para inválidos', 1, 'juanh', HOST_NAME(), GETDATE()),
(274, '30990', N'Fabricación de equipo de transporte ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(275, '31001', N'Fabricación de colchones y somier', 1, 'juanh', HOST_NAME(), GETDATE()),
(276, '31002', N'Fabricación de muebles y otros productos de madera a medida', 1, 'juanh', HOST_NAME(), GETDATE()),
(277, '31008', N'Servicios de maquilado de muebles', 1, 'juanh', HOST_NAME(), GETDATE()),
(278, '31009', N'Fabricación de muebles ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(279, '32110', N'Fabricación de joyas platerías y joyerías', 1, 'juanh', HOST_NAME(), GETDATE()),
(280, '32120', N'Fabricación de joyas de imitación (fantasía) y artículos conexos', 1, 'juanh', HOST_NAME(), GETDATE()),
(281, '32200', N'Fabricación de instrumentos musicales', 1, 'juanh', HOST_NAME(), GETDATE()),
(282, '32301', N'Fabricación de artículos de deporte', 1, 'juanh', HOST_NAME(), GETDATE()),
(283, '32308', N'Servicio de maquila de productos deportivos', 1, 'juanh', HOST_NAME(), GETDATE()),
(284, '32401', N'Fabricación de juegos de mesa y de salón', 1, 'juanh', HOST_NAME(), GETDATE()),
(285, '32402', N'Servicio de maquilado de juguetes y juegos', 1, 'juanh', HOST_NAME(), GETDATE()),
(286, '32409', N'Fabricación de juegos y juguetes n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(287, '32500', N'Fabricación de instrumentos y materiales médicos y odontológicos', 1, 'juanh', HOST_NAME(), GETDATE()),
(288, '32901', N'Fabricación de lápices, bolígrafos, sellos y artículos de librería en general', 1, 'juanh', HOST_NAME(), GETDATE()),
(289, '32902', N'Fabricación de escobas, cepillos, pinceles y similares', 1, 'juanh', HOST_NAME(), GETDATE()),
(290, '32903', N'Fabricación de artesanías de materiales diversos', 1, 'juanh', HOST_NAME(), GETDATE()),
(291, '32904', N'Fabricación de artículos de uso personal y domésticos n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(292, '32905', N'Fabricación de accesorios para las confecciones y la marroquinería n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(293, '32908', N'Servicios de maquila ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(294, '32909', N'Fabricación de productos manufacturados n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(295, '33110', N'Reparación y mantenimiento de productos elaborados de metal', 1, 'juanh', HOST_NAME(), GETDATE()),
(296, '33120', N'Reparación y mantenimiento de maquinaria', 1, 'juanh', HOST_NAME(), GETDATE()),
(297, '33130', N'Reparación y mantenimiento de equipo electrónico y óptico', 1, 'juanh', HOST_NAME(), GETDATE()),
(298, '33140', N'Reparación y mantenimiento de equipo eléctrico', 1, 'juanh', HOST_NAME(), GETDATE()),
(299, '33150', N'Reparación y mantenimiento de equipo de transporte, excepto vehículos automotores', 1, 'juanh', HOST_NAME(), GETDATE()),
(300, '33190', N'Reparación y mantenimiento de equipos n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(301, '33200', N'Instalación de maquinaria y equipo industrial', 1, 'juanh', HOST_NAME(), GETDATE()),
(302, '35101', N'Generación de energía eléctrica', 1, 'juanh', HOST_NAME(), GETDATE()),
(303, '35102', N'Transmisión de energía eléctrica', 1, 'juanh', HOST_NAME(), GETDATE()),
(304, '35103', N'Distribución de energía eléctrica', 1, 'juanh', HOST_NAME(), GETDATE()),
(305, '35200', N'Fabricación de gas, distribución de combustibles gaseosos por tuberías', 1, 'juanh', HOST_NAME(), GETDATE()),
(306, '35300', N'Suministro de vapor y agua caliente', 1, 'juanh', HOST_NAME(), GETDATE()),
(307, '36000', N'Captación, tratamiento y suministro de agua', 1, 'juanh', HOST_NAME(), GETDATE()),
(308, '37000', N'Evacuación de aguas residuales (alcantarillado)', 1, 'juanh', HOST_NAME(), GETDATE()),
(309, '38110', N'Recolección y transporte de desechos sólidos proveniente de hogares y sector urbano', 1, 'juanh', HOST_NAME(), GETDATE()),
(310, '38120', N'Recolección de desechos peligrosos', 1, 'juanh', HOST_NAME(), GETDATE()),
(311, '38210', N'Tratamiento y eliminación de desechos inicuos', 1, 'juanh', HOST_NAME(), GETDATE()),
(312, '38220', N'Tratamiento y eliminación de desechos peligrosos', 1, 'juanh', HOST_NAME(), GETDATE()),
(313, '38301', N'Reciclaje de desperdicios y desechos textiles', 1, 'juanh', HOST_NAME(), GETDATE()),
(314, '38302', N'Reciclaje de desperdicios y desechos de plástico y caucho', 1, 'juanh', HOST_NAME(), GETDATE()),
(315, '38303', N'Reciclaje de desperdicios y desechos de vidrio', 1, 'juanh', HOST_NAME(), GETDATE()),
(316, '38304', N'Reciclaje de desperdicios y desechos de papel y cartón', 1, 'juanh', HOST_NAME(), GETDATE()),
(317, '38305', N'Reciclaje de desperdicios y desechos metálicos', 1, 'juanh', HOST_NAME(), GETDATE()),
(318, '38309', N'Reciclaje de desperdicios y desechos no metálicos n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(319, '39000', N'Actividades de Saneamiento y otros Servicios de Gestión de Desechos', 1, 'juanh', HOST_NAME(), GETDATE()),
(320, '41001', N'Construcción de edificios residenciales', 1, 'juanh', HOST_NAME(), GETDATE()),
(321, '41002', N'Construcción de edificios no residenciales', 1, 'juanh', HOST_NAME(), GETDATE()),
(322, '42100', N'Construcción de carreteras, calles y caminos', 1, 'juanh', HOST_NAME(), GETDATE()),
(323, '42200', N'Construcción de proyectos de servicio público', 1, 'juanh', HOST_NAME(), GETDATE()),
(324, '42900', N'Construcción de obras de ingeniería civil n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(325, '43110', N'Demolición', 1, 'juanh', HOST_NAME(), GETDATE()),
(326, '43120', N'Preparación de terreno', 1, 'juanh', HOST_NAME(), GETDATE()),
(327, '43210', N'Instalaciones eléctricas', 1, 'juanh', HOST_NAME(), GETDATE()),
(328, '43220', N'Instalación de fontanería, calefacción y aire acondicionado', 1, 'juanh', HOST_NAME(), GETDATE()),
(329, '43290', N'Otras instalaciones para obras de construcción', 1, 'juanh', HOST_NAME(), GETDATE()),
(330, '43300', N'Terminación y acabado de edificios', 1, 'juanh', HOST_NAME(), GETDATE()),
(331, '43900', N'Otras actividades especializadas de construcción', 1, 'juanh', HOST_NAME(), GETDATE()),
(332, '43901', N'Fabricación de techos y materiales diversos', 1, 'juanh', HOST_NAME(), GETDATE()),
(333, '45100', N'Venta de vehículos automotores', 1, 'juanh', HOST_NAME(), GETDATE()),
(334, '45201', N'Reparación mecánica de vehículos automotores', 1, 'juanh', HOST_NAME(), GETDATE()),
(335, '45202', N'Reparaciones eléctricas del automotor y recarga de baterías', 1, 'juanh', HOST_NAME(), GETDATE()),
(336, '45203', N'Enderezado y pintura de vehículos automotores', 1, 'juanh', HOST_NAME(), GETDATE()),
(337, '45204', N'Reparaciones de radiadores, escapes y silenciadores', 1, 'juanh', HOST_NAME(), GETDATE()),
(338, '45205', N'Reparación y reconstrucción de vías, stop y otros artículos de fibra de vidrio', 1, 'juanh', HOST_NAME(), GETDATE()),
(339, '45206', N'Reparación de llantas de vehículos automotores', 1, 'juanh', HOST_NAME(), GETDATE()),
(340, '45207', N'Polarizado de vehículos (mediante la adhesión de papel especial a los vidrios)', 1, 'juanh', HOST_NAME(), GETDATE()),
(341, '45208', N'Lavado y pasteado de vehículos (carwash)', 1, 'juanh', HOST_NAME(), GETDATE()),
(342, '45209', N'Reparaciones de vehículos n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(343, '45211', N'Remolque de vehículos automotores', 1, 'juanh', HOST_NAME(), GETDATE()),
(344, '45301', N'Venta de partes, piezas y accesorios nuevos para vehículos automotores', 1, 'juanh', HOST_NAME(), GETDATE()),
(345, '45302', N'Venta de partes, piezas y accesorios usados para vehículos automotores', 1, 'juanh', HOST_NAME(), GETDATE()),
(346, '45401', N'Venta de motocicletas', 1, 'juanh', HOST_NAME(), GETDATE()),
(347, '45402', N'Venta de repuestos, piezas y accesorios de motocicletas', 1, 'juanh', HOST_NAME(), GETDATE()),
(348, '45403', N'Mantenimiento y reparación de motocicletas', 1, 'juanh', HOST_NAME(), GETDATE()),
(349, '46100', N'Venta al por mayor a cambio de retribución o por contrata', 1, 'juanh', HOST_NAME(), GETDATE()),
(350, '46201', N'Venta al por mayor de materias primas agrícolas', 1, 'juanh', HOST_NAME(), GETDATE()),
(351, '46202', N'Venta al por mayor de productos de la silvicultura', 1, 'juanh', HOST_NAME(), GETDATE()),
(352, '46203', N'Venta al por mayor de productos pecuarios y de granja', 1, 'juanh', HOST_NAME(), GETDATE()),
(353, '46211', N'Venta de productos para uso agropecuario', 1, 'juanh', HOST_NAME(), GETDATE()),
(354, '46291', N'Venta al por mayor de granos básicos (cereales, leguminosas)', 1, 'juanh', HOST_NAME(), GETDATE()),
(355, '46292', N'Venta al por mayor de semillas mejoradas para cultivo', 1, 'juanh', HOST_NAME(), GETDATE()),
(356, '46293', N'Venta al por mayor de café oro y uva', 1, 'juanh', HOST_NAME(), GETDATE()),
(357, '46294', N'Venta al por mayor de caña de azúcar', 1, 'juanh', HOST_NAME(), GETDATE()),
(358, '46295', N'Venta al por mayor de flores, plantas y otros productos naturales', 1, 'juanh', HOST_NAME(), GETDATE()),
(359, '46296', N'Venta al por mayor de productos agrícolas', 1, 'juanh', HOST_NAME(), GETDATE()),
(360, '46297', N'Venta al por mayor de ganado bovino (vivo)', 1, 'juanh', HOST_NAME(), GETDATE()),
(361, '46298', N'Venta al por mayor de animales porcinos, ovinos, caprino, canículas, apícolas, avícolas vivos', 1, 'juanh', HOST_NAME(), GETDATE()),
(362, '46299', N'Venta de otras especies vivas del reino animal', 1, 'juanh', HOST_NAME(), GETDATE()),
(363, '46301', N'Venta al por mayor de alimentos', 1, 'juanh', HOST_NAME(), GETDATE()),
(364, '46302', N'Venta al por mayor de bebidas', 1, 'juanh', HOST_NAME(), GETDATE()),
(365, '46303', N'Venta al por mayor de tabaco', 1, 'juanh', HOST_NAME(), GETDATE()),
(366, '46371', N'Venta al por mayor de frutas, hortalizas (verduras), legumbres y tubérculos', 1, 'juanh', HOST_NAME(), GETDATE()),
(367, '46372', N'Venta al por mayor de pollos, gallinas destacadas, pavos y otras aves', 1, 'juanh', HOST_NAME(), GETDATE()),
(368, '46373', N'Venta al por mayor de carne bovina y porcina, productos de carne y embutidos', 1, 'juanh', HOST_NAME(), GETDATE()),
(369, '46374', N'Venta al por mayor de huevos', 1, 'juanh', HOST_NAME(), GETDATE()),
(370, '46375', N'Venta al por mayor de productos lácteos', 1, 'juanh', HOST_NAME(), GETDATE()),
(371, '46376', N'Venta al por mayor de productos farináceos de panadería (pan dulce, cakes, respostería, etc.)', 1, 'juanh', HOST_NAME(), GETDATE()),
(372, '46377', N'Venta al por mayor de pastas alimenticias, aceites y grasas comestibles vegetal y animal', 1, 'juanh', HOST_NAME(), GETDATE()),
(373, '46378', N'Venta al por mayor de sal comestible', 1, 'juanh', HOST_NAME(), GETDATE()),
(374, '46379', N'Venta al por mayor de azúcar', 1, 'juanh', HOST_NAME(), GETDATE()),
(375, '46391', N'Venta al por mayor de abarrotes (vinos, licores, productos alimenticios envasados, etc.)', 1, 'juanh', HOST_NAME(), GETDATE()),
(376, '46392', N'Venta al por mayor de aguas gaseosas', 1, 'juanh', HOST_NAME(), GETDATE()),
(377, '46393', N'Venta al por mayor de agua purificada', 1, 'juanh', HOST_NAME(), GETDATE()),
(378, '46394', N'Venta al por mayor de refrescos y otras bebidas, líquidas o en polvo', 1, 'juanh', HOST_NAME(), GETDATE()),
(379, '46395', N'Venta al por mayor de cerveza and licores', 1, 'juanh', HOST_NAME(), GETDATE()),
(380, '46396', N'Venta al por mayor de hielo', 1, 'juanh', HOST_NAME(), GETDATE()),
(381, '46411', N'Venta al por mayor de hilados, tejidos y productos textiles de mercería', 1, 'juanh', HOST_NAME(), GETDATE()),
(382, '46412', N'Venta al por mayor de artículos textiles excepto confecciones para el hogar', 1, 'juanh', HOST_NAME(), GETDATE()),
(383, '46413', N'Venta al por mayor de confecciones textiles para el hogar', 1, 'juanh', HOST_NAME(), GETDATE()),
(384, '46414', N'Venta al por mayor de prendas de vestir y accesorios de vestir', 1, 'juanh', HOST_NAME(), GETDATE()),
(385, '46415', N'Venta al por mayor de ropa usada', 1, 'juanh', HOST_NAME(), GETDATE()),
(386, '46416', N'Venta al por mayor de calzado', 1, 'juanh', HOST_NAME(), GETDATE()),
(387, '46417', N'Venta al por mayor de artículos de marroquinería y talabartería', 1, 'juanh', HOST_NAME(), GETDATE()),
(388, '46418', N'Venta al por mayor de artículos de peletería', 1, 'juanh', HOST_NAME(), GETDATE()),
(389, '46419', N'Venta al por mayor de otros artículos textiles n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(390, '46471', N'Venta al por mayor de instrumentos musicales', 1, 'juanh', HOST_NAME(), GETDATE()),
(391, '46472', N'Venta al por mayor de colchones, almohadas, cojines, etc.', 1, 'juanh', HOST_NAME(), GETDATE()),
(392, '46473', N'Venta al por mayor de artículos de aluminio para el hogar y para otros usos', 1, 'juanh', HOST_NAME(), GETDATE()),
(393, '46474', N'Venta al por mayor de depósitos y otros artículos plásticos para el hogar y otros usos, incluyendo los desechables de durapax y no desechables', 1, 'juanh', HOST_NAME(), GETDATE()),
(394, '46475', N'Venta al por mayor de cámaras fotográficas, accesorios y materiales', 1, 'juanh', HOST_NAME(), GETDATE()),
(395, '46482', N'Venta al por mayor de medicamentos, artículos y otros productos de uso veterinario', 1, 'juanh', HOST_NAME(), GETDATE()),
(396, '46483', N'Venta al por mayor de productos y artículos de belleza y de uso personal', 1, 'juanh', HOST_NAME(), GETDATE()),
(397, '46484', N'Venta de productos farmacéuticos y medicinales', 1, 'juanh', HOST_NAME(), GETDATE()),
(398, '46491', N'Venta al por mayor de productos medicinales, cosméticos, perfumería y productos de limpieza', 1, 'juanh', HOST_NAME(), GETDATE()),
(399, '46492', N'Venta al por mayor de relojes and artículos de joyería', 1, 'juanh', HOST_NAME(), GETDATE()),
(400, '46493', N'Venta al por mayor de electrodomésticos y artículos del hogar excepto bazar; artículos de iluminación', 1, 'juanh', HOST_NAME(), GETDATE()),
(401, '46494', N'Venta al por mayor de artículos de bazar y similares', 1, 'juanh', HOST_NAME(), GETDATE()),
(402, '46495', N'Venta al por mayor de artículos de óptica', 1, 'juanh', HOST_NAME(), GETDATE()),
(403, '46496', N'Venta al por mayor de revistas, periódicos, libros, artículos de librería y artículos de papel y cartón en general', 1, 'juanh', HOST_NAME(), GETDATE()),
(404, '46497', N'Venta de artículos deportivos, juguetes and rodados', 1, 'juanh', HOST_NAME(), GETDATE()),
(405, '46498', N'Venta al por mayor de productos usados para el hogar o el uso personal', 1, 'juanh', HOST_NAME(), GETDATE()),
(406, '46499', N'Venta al por mayor de enseres domésticos y de uso personal n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(407, '46500', N'Venta al por mayor de bicicletas, partes, accesorios y otros', 1, 'juanh', HOST_NAME(), GETDATE()),
(408, '46510', N'Venta al por mayor de computadoras, equipo periférico y programas informáticos', 1, 'juanh', HOST_NAME(), GETDATE()),
(409, '46520', N'Venta al por mayor de equipos de comunicación', 1, 'juanh', HOST_NAME(), GETDATE()),
(410, '46530', N'Venta al por mayor de maquinaria y equipo agropecuario, accesorios, partes y suministros', 1, 'juanh', HOST_NAME(), GETDATE()),
(411, '46590', N'Venta de equipos e instrumentos de uso profesional y científico y aparatos de medida y control', 1, 'juanh', HOST_NAME(), GETDATE()),
(412, '46591', N'Venta al por mayor de maquinaria equipo, accesorios y materiales para la industria de la madera y sus productos', 1, 'juanh', HOST_NAME(), GETDATE()),
(413, '46592', N'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria gráfica y del papel, cartón y productos de papel y cartón', 1, 'juanh', HOST_NAME(), GETDATE()),
(414, '46593', N'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria de productos químicos, plástico y caucho', 1, 'juanh', HOST_NAME(), GETDATE()),
(415, '46594', N'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria metálica y de sus productos', 1, 'juanh', HOST_NAME(), GETDATE()),
(416, '46595', N'Venta al por mayor de equipamiento para uso médico, odontológico, veterinario y servicios conexos', 1, 'juanh', HOST_NAME(), GETDATE()),
(417, '46596', N'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria de la alimentación', 1, 'juanh', HOST_NAME(), GETDATE()),
(418, '46597', N'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria textil, confecciones y cuero', 1, 'juanh', HOST_NAME(), GETDATE()),
(419, '46598', N'Venta al por mayor de maquinaria, equipo y accesorios para la construcción and explotación de minas y canteras', 1, 'juanh', HOST_NAME(), GETDATE()),
(420, '46599', N'Venta al por mayor de otro tipo de maquinaria y equipo con sus accesorios y partes', 1, 'juanh', HOST_NAME(), GETDATE()),
(421, '46610', N'Venta al por mayor de otros combustibles sólidos, líquidos, gaseosos y de productos conexos', 1, 'juanh', HOST_NAME(), GETDATE()),
(422, '46612', N'Venta al por mayor de combustibles para automotores, aviones, barcos, maquinaria y otros', 1, 'juanh', HOST_NAME(), GETDATE()),
(423, '46613', N'Venta al por mayor de lubricantes, grasas y otros aceites para automotores, maquinaria industrial, etc.', 1, 'juanh', HOST_NAME(), GETDATE()),
(424, '46614', N'Venta al por mayor de gas propano', 1, 'juanh', HOST_NAME(), GETDATE()),
(425, '46615', N'Venta al por mayor de leña y carbón', 1, 'juanh', HOST_NAME(), GETDATE()),
(426, '46620', N'Venta al por mayor de metales and minerales metalíferos', 1, 'juanh', HOST_NAME(), GETDATE()),
(427, '46631', N'Venta al por mayor de puertas, ventanas, vitrinas y similares', 1, 'juanh', HOST_NAME(), GETDATE()),
(428, '46632', N'Venta al por mayor de artículos de ferretería y pinturerías', 1, 'juanh', HOST_NAME(), GETDATE()),
(429, '46633', N'Vidrierías', 1, 'juanh', HOST_NAME(), GETDATE()),
(430, '46634', N'Venta al por mayor de maderas', 1, 'juanh', HOST_NAME(), GETDATE()),
(431, '46639', N'Venta al por mayor de materiales para la construcción n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(432, '46691', N'Venta al por mayor de sal industrial sin yodar', 1, 'juanh', HOST_NAME(), GETDATE()),
(433, '46692', N'Venta al por mayor de productos intermedios y desechos de origen textil', 1, 'juanh', HOST_NAME(), GETDATE()),
(434, '46693', N'Venta al por mayor de productos intermedios y desechos de origen metálico', 1, 'juanh', HOST_NAME(), GETDATE()),
(435, '46694', N'Venta al por mayor de productos intermedios y desechos de papel and cartón', 1, 'juanh', HOST_NAME(), GETDATE()),
(436, '46696', N'Venta al por mayor fertilizantes, abonos, agroquímicos y productos similares', 1, 'juanh', HOST_NAME(), GETDATE()),
(437, '46696', N'Venta al por mayor de productos intermedios y desechos de origen plástico', 1, 'juanh', HOST_NAME(), GETDATE()),
(438, '46697', N'Venta al por mayor de tintas para imprenta, productos curtientes y materias y productos colorantes', 1, 'juanh', HOST_NAME(), GETDATE()),
(439, '46698', N'Venta de productos intermedios y desechos de origen químico y de caucho', 1, 'juanh', HOST_NAME(), GETDATE()),
(440, '46699', N'Venta al por mayor de productos intermedios y desechos ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(441, '46701', N'Venta de algodón en oro', 1, 'juanh', HOST_NAME(), GETDATE()),
(442, '46900', N'Venta al por mayor de otros productos', 1, 'juanh', HOST_NAME(), GETDATE()),
(443, '46901', N'Venta al por mayor de cohetes y otros productos pirotécnicos', 1, 'juanh', HOST_NAME(), GETDATE()),
(444, '46902', N'Venta al por mayor de artículos diversos para consumo humano', 1, 'juanh', HOST_NAME(), GETDATE()),
(445, '46903', N'Venta al por mayor de armas de fuego, municiones y accesorios', 1, 'juanh', HOST_NAME(), GETDATE()),
(446, '46904', N'Venta al por mayor de toldos y tiendas de campaña de cualquier material', 1, 'juanh', HOST_NAME(), GETDATE()),
(447, '46905', N'Venta al por mayor de exhibidores publicitarios y rótulos', 1, 'juanh', HOST_NAME(), GETDATE()),
(448, '46906', N'Venta al por mayor de artículos promocionales diversos', 1, 'juanh', HOST_NAME(), GETDATE()),
(449, '47111', N'Venta en supermercados', 1, 'juanh', HOST_NAME(), GETDATE()),
(450, '47112', N'Venta en tiendas de artículos de primera necesidad', 1, 'juanh', HOST_NAME(), GETDATE()),
(451, '47119', N'Almacenes (venta de diversos artículos)', 1, 'juanh', HOST_NAME(), GETDATE()),
(452, '47190', N'Venta al por menor de otros productos en comercios no especializados', 1, 'juanh', HOST_NAME(), GETDATE()),
(453, '47199', N'Venta de establecimientos no especializados con surtido compuesto principalmente de alimentos, bebidas y tabaco', 1, 'juanh', HOST_NAME(), GETDATE()),
(454, '47211', N'Venta al por menor de frutas y hortalizas', 1, 'juanh', HOST_NAME(), GETDATE()),
(455, '47212', N'Venta al por menor de carnes, embutidos and productos de granja', 1, 'juanh', HOST_NAME(), GETDATE()),
(456, '47213', N'Venta al por menor de pescado y mariscos', 1, 'juanh', HOST_NAME(), GETDATE()),
(457, '47214', N'Venta al por menor de productos lácteos', 1, 'juanh', HOST_NAME(), GETDATE()),
(458, '47215', N'Venta al por menor de productos de panadería, repostería y galletas', 1, 'juanh', HOST_NAME(), GETDATE()),
(459, '47216', N'Venta al por menor de huevos', 1, 'juanh', HOST_NAME(), GETDATE()),
(460, '47217', N'Venta al por menor de carnes y productos cárnicos', 1, 'juanh', HOST_NAME(), GETDATE()),
(461, '47218', N'Venta al por menor de granos básicos y otros', 1, 'juanh', HOST_NAME(), GETDATE()),
(462, '47219', N'Venta al por menor de alimentos n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(463, '47221', N'Venta al por menor de hielo', 1, 'juanh', HOST_NAME(), GETDATE()),
(464, '47223', N'Venta de bebidas no alcohólicas, para su consumo fuera del establecimiento', 1, 'juanh', HOST_NAME(), GETDATE()),
(465, '47224', N'Venta de bebidas alcohólicas, para su consumo fuera del establecimiento', 1, 'juanh', HOST_NAME(), GETDATE()),
(466, '47225', N'Venta de bebidas alcohólicas para su consumo dentro del establecimiento', 1, 'juanh', HOST_NAME(), GETDATE()),
(467, '47230', N'Venta al por menor de tabaco', 1, 'juanh', HOST_NAME(), GETDATE()),
(468, '47300', N'Venta de combustibles, lubricantes y otros (gasolineras)', 1, 'juanh', HOST_NAME(), GETDATE()),
(469, '47411', N'Venta al por menor de computadoras y equipo periférico', 1, 'juanh', HOST_NAME(), GETDATE()),
(470, '47412', N'Venta de equipo y accesorios de telecomunicación', 1, 'juanh', HOST_NAME(), GETDATE()),
(471, '47420', N'Venta al por menor de equipo de audio y video', 1, 'juanh', HOST_NAME(), GETDATE()),
(472, '47510', N'Venta al por menor de hilados, tejidos y productos textiles de mercería; confecciones para el hogar y textiles n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(473, '47521', N'Venta al por menor de productos de madera', 1, 'juanh', HOST_NAME(), GETDATE()),
(474, '47522', N'Venta al por menor de artículos de ferretería', 1, 'juanh', HOST_NAME(), GETDATE()),
(475, '47523', N'Venta al por menor de productos de pinturerías', 1, 'juanh', HOST_NAME(), GETDATE()),
(476, '47524', N'Venta al por menor en vidrierías', 1, 'juanh', HOST_NAME(), GETDATE()),
(477, '47529', N'Venta al por menor de materiales de construcción y artículos conexos', 1, 'juanh', HOST_NAME(), GETDATE()),
(478, '47530', N'Venta al por menor de tapices, alfombras y revestimientos de paredes y pisos en comercios especializados', 1, 'juanh', HOST_NAME(), GETDATE()),
(479, '47591', N'Venta al por menor de muebles', 1, 'juanh', HOST_NAME(), GETDATE()),
(480, '47592', N'Venta al por menor de artículos de bazar', 1, 'juanh', HOST_NAME(), GETDATE()),
(481, '47593', N'Venta al por menor de aparatos electrodomésticos, repuestos y accesorios', 1, 'juanh', HOST_NAME(), GETDATE()),
(482, '47594', N'Venta al por menor de artículos eléctricos y de iluminación', 1, 'juanh', HOST_NAME(), GETDATE()),
(483, '47598', N'Venta al por menor de instrumentos musicales', 1, 'juanh', HOST_NAME(), GETDATE()),
(484, '47610', N'Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados', 1, 'juanh', HOST_NAME(), GETDATE()),
(485, '47620', N'Venta al por menor de discos láser, cassettes, cintas de vídeo y otros', 1, 'juanh', HOST_NAME(), GETDATE()),
(486, '47630', N'Venta al por menor de productos y equipos de deporte', 1, 'juanh', HOST_NAME(), GETDATE()),
(487, '47631', N'Venta al por menor de bicicletas, accesorios y repuestos', 1, 'juanh', HOST_NAME(), GETDATE()),
(488, '47640', N'Venta al por menor de juegos y juguetes en comercios especializados', 1, 'juanh', HOST_NAME(), GETDATE()),
(489, '47711', N'Venta al por menor de prendas de vestir y accesorios de vestir', 1, 'juanh', HOST_NAME(), GETDATE()),
(490, '47712', N'Venta al por menor de calzado', 1, 'juanh', HOST_NAME(), GETDATE()),
(491, '47713', N'Venta al por menor de artículos de peletería, marroquinería y tababartería', 1, 'juanh', HOST_NAME(), GETDATE()),
(492, '47721', N'Venta al por menor de medicamentos farmacéuticos y otros materiales y artículos de uso médico, odontológico y veterinario', 1, 'juanh', HOST_NAME(), GETDATE()),
(493, '47722', N'Venta al por menor de productos cosméticos y de tocador', 1, 'juanh', HOST_NAME(), GETDATE()),
(494, '47731', N'Venta al por menor de productos de joyería, bisutería, óptica, relojería', 1, 'juanh', HOST_NAME(), GETDATE()),
(495, '47732', N'Venta al por menor de plantas, semillas, animales y artículos conexos', 1, 'juanh', HOST_NAME(), GETDATE()),
(496, '47733', N'Venta al por menor de combustibles de uso doméstico (gas propano y gas licuado)', 1, 'juanh', HOST_NAME(), GETDATE()),
(497, '47734', N'Venta al por menor de artesanías, artículos cerámicos y recuerdos en general', 1, 'juanh', HOST_NAME(), GETDATE()),
(498, '47735', N'Venta al por menor de ataúdes, lápidas y cruces, trofeos, artículos religiosos en general', 1, 'juanh', HOST_NAME(), GETDATE()),
(499, '47736', N'Venta al por menor de armas de fuego, municiones y accesorios', 1, 'juanh', HOST_NAME(), GETDATE()),
(500, '47737', N'Venta al por menor de artículos de cohetería y pirotécnicos', 1, 'juanh', HOST_NAME(), GETDATE()),
(501, '47738', N'Venta al por menor de artículos desechables de uso personal and doméstico (servilletas, papel higiénico, pañales, toallas sanitarias, etc.)', 1, 'juanh', HOST_NAME(), GETDATE()),
(502, '47739', N'Venta al por menor de otros productos n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(503, '47741', N'Venta al por menor de artículos usados', 1, 'juanh', HOST_NAME(), GETDATE()),
(504, '47742', N'Venta al por menor de textiles y confecciones usados', 1, 'juanh', HOST_NAME(), GETDATE()),
(505, '47743', N'Venta al por menor de libros, revistas, papel and cartón usados', 1, 'juanh', HOST_NAME(), GETDATE()),
(506, '47749', N'Venta al por menor de productos usados n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(507, '47811', N'Venta al por menor de frutas, verduras y hortalizas', 1, 'juanh', HOST_NAME(), GETDATE()),
(508, '47814', N'Venta al por menor de productos lácteos', 1, 'juanh', HOST_NAME(), GETDATE()),
(509, '47815', N'Venta al por menor de productos de panadería, galletas y similares', 1, 'juanh', HOST_NAME(), GETDATE()),
(510, '47816', N'Venta al por menor de bebidas', 1, 'juanh', HOST_NAME(), GETDATE()),
(511, '47818', N'Venta al por menor en tiendas de mercado y puestos', 1, 'juanh', HOST_NAME(), GETDATE()),
(512, '47821', N'Venta al por menor de hilados, tejidos y productos textiles de mercería en puestos de mercados y ferias', 1, 'juanh', HOST_NAME(), GETDATE()),
(513, '47822', N'Venta al por menor de artículos textiles excepto confecciones para el hogar en puestos de mercados y ferias', 1, 'juanh', HOST_NAME(), GETDATE()),
(514, '47823', N'Venta al por menor de confecciones textiles para el hogar en puestos de mercados y ferias', 1, 'juanh', HOST_NAME(), GETDATE()),
(515, '47824', N'Venta al por menor de prendas de vestir, accesorios de vestir y similares en puestos de mercados y ferias', 1, 'juanh', HOST_NAME(), GETDATE()),
(516, '47825', N'Venta al por menor de ropa usada', 1, 'juanh', HOST_NAME(), GETDATE()),
(517, '47826', N'Venta al por menor de calzado, artículos de marroquinería y talabartería en puestos de mercados y ferias', 1, 'juanh', HOST_NAME(), GETDATE()),
(518, '47827', N'Venta al por menor de artículos de marroquinería y talabartería en puestos de mercados y ferias', 1, 'juanh', HOST_NAME(), GETDATE()),
(519, '47829', N'Venta al por menor de artículos textiles ncp en puestos de mercados y ferias', 1, 'juanh', HOST_NAME(), GETDATE()),
(520, '47891', N'Venta al por menor de animales, flores y productos conexos en puestos de feria y mercados', 1, 'juanh', HOST_NAME(), GETDATE()),
(521, '47892', N'Venta al por menor de productos medicinales, cosméticos, de tocador y de limpieza en puestos de ferias y mercados', 1, 'juanh', HOST_NAME(), GETDATE()),
(522, '47893', N'Venta al por menor de artículos de bazar en puestos de ferias y mercados', 1, 'juanh', HOST_NAME(), GETDATE()),
(523, '47894', N'Venta al por menor de artículos de papel, envases, libros, revistas y conexos en puestos de feria y mercados', 1, 'juanh', HOST_NAME(), GETDATE()),
(524, '47895', N'Venta al por menor de materiales de construcción, electrodomésticos, accesorios para autos y similares en puestos de feria y mercados', 1, 'juanh', HOST_NAME(), GETDATE()),
(525, '47896', N'Venta al por menor de equipos accesorios para las comunicaciones en puestos de feria y mercados', 1, 'juanh', HOST_NAME(), GETDATE()),
(526, '47899', N'Venta al por menor en puestos de ferias y mercados n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(527, '47910', N'Venta al por menor por correo o Internet', 1, 'juanh', HOST_NAME(), GETDATE()),
(528, '47990', N'Otros tipos de venta al por menor no realizada, en almacenes, puestos de venta o mercado', 1, 'juanh', HOST_NAME(), GETDATE()),
(529, '49110', N'Transporte interurbano de pasajeros por ferrocarril', 1, 'juanh', HOST_NAME(), GETDATE()),
(530, '49120', N'Transporte de carga por ferrocarril', 1, 'juanh', HOST_NAME(), GETDATE()),
(531, '49211', N'Transporte de pasajeros urbanos e interurbano mediante buses', 1, 'juanh', HOST_NAME(), GETDATE()),
(532, '49212', N'Transporte de pasajeros interdepartamental mediante microbuses', 1, 'juanh', HOST_NAME(), GETDATE()),
(533, '49213', N'Transporte de pasajeros urbanos e interurbano mediante microbuses', 1, 'juanh', HOST_NAME(), GETDATE()),
(534, '49214', N'Transporte de pasajeros interdepartamental mediante buses', 1, 'juanh', HOST_NAME(), GETDATE()),
(535, '49221', N'Transporte internacional de pasajeros', 1, 'juanh', HOST_NAME(), GETDATE()),
(536, '49222', N'Transporte de pasajeros mediante taxis y autos con chofer', 1, 'juanh', HOST_NAME(), GETDATE()),
(537, '49223', N'Transporte escolar', 1, 'juanh', HOST_NAME(), GETDATE()),
(538, '49225', N'Transporte de pasajeros para excursiones', 1, 'juanh', HOST_NAME(), GETDATE()),
(539, '49226', N'Servicios de transporte de personal', 1, 'juanh', HOST_NAME(), GETDATE()),
(540, '49229', N'Transporte de pasajeros por vía terrestre ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(541, '49231', N'Transporte de carga urbano', 1, 'juanh', HOST_NAME(), GETDATE()),
(542, '49232', N'Transporte nacional de carga', 1, 'juanh', HOST_NAME(), GETDATE()),
(543, '49233', N'Transporte de carga internacional', 1, 'juanh', HOST_NAME(), GETDATE()),
(544, '49234', N'Servicios de mudanza', 1, 'juanh', HOST_NAME(), GETDATE()),
(545, '49235', N'Alquiler de vehículos de carga con conductor', 1, 'juanh', HOST_NAME(), GETDATE()),
(546, '49300', N'Transporte por oleoducto o gasoducto', 1, 'juanh', HOST_NAME(), GETDATE()),
(547, '50110', N'Transporte de pasajeros marítimo y de cabotaje', 1, 'juanh', HOST_NAME(), GETDATE()),
(548, '50120', N'Transporte de carga marítimo y de cabotaje', 1, 'juanh', HOST_NAME(), GETDATE()),
(549, '50211', N'Transporte de pasajeros por vías de navegación interiores', 1, 'juanh', HOST_NAME(), GETDATE()),
(550, '50212', N'Alquiler de equipo de transporte de pasajeros por vías de navegación interior con conductor', 1, 'juanh', HOST_NAME(), GETDATE()),
(551, '50220', N'Transporte de carga por vías de navegación interiores', 1, 'juanh', HOST_NAME(), GETDATE()),
(552, '51100', N'Transporte aéreo de pasajeros', 1, 'juanh', HOST_NAME(), GETDATE()),
(553, '51201', N'Transporte de carga por vía aérea', 1, 'juanh', HOST_NAME(), GETDATE()),
(554, '51202', N'Alquiler de equipo de aerotransporte con operadores para el propósito de transportar carga', 1, 'juanh', HOST_NAME(), GETDATE()),
(555, '52101', N'Alquiler de instalaciones de almacenamiento en zonas francas', 1, 'juanh', HOST_NAME(), GETDATE()),
(556, '52102', N'Alquiler de silos para conservación y almacenamiento de granos', 1, 'juanh', HOST_NAME(), GETDATE()),
(557, '52103', N'Alquiler de instalaciones con refrigeración para almacenamiento y conservación de alimentos y otros productos', 1, 'juanh', HOST_NAME(), GETDATE()),
(558, '52109', N'Alquiler de bodegas para almacenamiento y depósito n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(559, '52211', N'Servicio de garaje y estacionamiento', 1, 'juanh', HOST_NAME(), GETDATE()),
(560, '52212', N'Servicios de terminales para el transporte por vía terrestre', 1, 'juanh', HOST_NAME(), GETDATE()),
(561, '52219', N'Servicios para el transporte por vía terrestre n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(562, '52220', N'Servicios para el transporte acuático', 1, 'juanh', HOST_NAME(), GETDATE()),
(563, '52230', N'Servicios para el transporte aéreo', 1, 'juanh', HOST_NAME(), GETDATE()),
(564, '52240', N'Manipulación de carga', 1, 'juanh', HOST_NAME(), GETDATE()),
(565, '52290', N'Servicios para el transporte ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(566, '52291', N'Agencias de tramitaciones aduanales', 1, 'juanh', HOST_NAME(), GETDATE()),
(567, '53100', N'Servicios de correo nacional', 1, 'juanh', HOST_NAME(), GETDATE()),
(568, '53200', N'Actividades de correo distintas a las actividades postales nacionales', 1, 'juanh', HOST_NAME(), GETDATE()),
(569, '53201', N'Agencia privada de correo y encomiendas', 1, 'juanh', HOST_NAME(), GETDATE()),
(570, '55101', N'Actividades de alojamiento para estancias cortas', 1, 'juanh', HOST_NAME(), GETDATE()),
(571, '55102', N'Hoteles', 1, 'juanh', HOST_NAME(), GETDATE()),
(572, '55200', N'Actividades de campamentos, parques de vehículos de recreo y parques de caravanas', 1, 'juanh', HOST_NAME(), GETDATE()),
(573, '55900', N'Alojamiento n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(574, '56101', N'Restaurantes', 1, 'juanh', HOST_NAME(), GETDATE()),
(575, '56106', N'Pupusería', 1, 'juanh', HOST_NAME(), GETDATE()),
(576, '56107', N'Actividades varias de restaurantes', 1, 'juanh', HOST_NAME(), GETDATE()),
(577, '56108', N'Comedores', 1, 'juanh', HOST_NAME(), GETDATE()),
(578, '56109', N'Merenderos ambulantes', 1, 'juanh', HOST_NAME(), GETDATE()),
(579, '56210', N'Preparación de comida para eventos especiales', 1, 'juanh', HOST_NAME(), GETDATE()),
(580, '56291', N'Servicios de provisión de comidas por contrato', 1, 'juanh', HOST_NAME(), GETDATE()),
(581, '56292', N'Servicios de concesión de cafetines y chalet en empresas e', 1, 'juanh', HOST_NAME(), GETDATE()),
(582, '56299', N'Servicios de preparación de comidas ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(583, '56301', N'Servicio de expendio de bebidas en salones y bares', 1, 'juanh', HOST_NAME(), GETDATE()),
(584, '56302', N'Servicio de expendio de bebidas en puestos callejeros, mercados y ferias', 1, 'juanh', HOST_NAME(), GETDATE()),
(585, '58110', N'Edición de libros, folletos, partituras y otras ediciones distintas a estas', 1, 'juanh', HOST_NAME(), GETDATE()),
(586, '58120', N'Edición de directorios y listas de correos', 1, 'juanh', HOST_NAME(), GETDATE()),
(587, '58130', N'Edición de periódicos, revistas y otras publicaciones periódicas', 1, 'juanh', HOST_NAME(), GETDATE()),
(588, '58190', N'Otras actividades de edición', 1, 'juanh', HOST_NAME(), GETDATE()),
(589, '58200', N'Edición de programas informáticos (software)', 1, 'juanh', HOST_NAME(), GETDATE()),
(590, '59110', N'Actividades de producción cinematográfica', 1, 'juanh', HOST_NAME(), GETDATE()),
(591, '59120', N'Actividades de post producción de películas, videos y programas de televisión', 1, 'juanh', HOST_NAME(), GETDATE()),
(592, '59130', N'Actividades de distribución de películas cinematográficas, videos y programas de televisión', 1, 'juanh', HOST_NAME(), GETDATE()),
(593, '59140', N'Actividades de exhibición de películas cinematográficas y cintas de video', 1, 'juanh', HOST_NAME(), GETDATE()),
(594, '59200', N'Actividades de edición y grabación de música', 1, 'juanh', HOST_NAME(), GETDATE()),
(595, '60100', N'Servicios de difusiones de radio', 1, 'juanh', HOST_NAME(), GETDATE()),
(596, '60201', N'Actividades de programación y difusión de televisión abierta', 1, 'juanh', HOST_NAME(), GETDATE()),
(597, '60202', N'Actividades de suscripción y difusión de televisión por cable y/o suscripción', 1, 'juanh', HOST_NAME(), GETDATE()),
(598, '60299', N'Servicios de televisión, incluye televisión por cable', 1, 'juanh', HOST_NAME(), GETDATE()),
(599, '60900', N'Programación y transmisión de radio y televisión', 1, 'juanh', HOST_NAME(), GETDATE()),
(600, '61101', N'Servicio de telefonía', 1, 'juanh', HOST_NAME(), GETDATE()),
(601, '61102', N'Servicio de Internet', 1, 'juanh', HOST_NAME(), GETDATE()),
(602, '61103', N'Servicio de telefonía fija', 1, 'juanh', HOST_NAME(), GETDATE()),
(603, '61109', N'Servicio de Internet n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(604, '61201', N'Servicios de telefonía celular', 1, 'juanh', HOST_NAME(), GETDATE()),
(605, '61202', N'Servicios de Internet inalámbrico', 1, 'juanh', HOST_NAME(), GETDATE()),
(606, '61209', N'Servicios de telecomunicaciones inalámbrico n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(607, '61301', N'Telecomunicaciones satelitales', 1, 'juanh', HOST_NAME(), GETDATE()),
(608, '61309', N'Comunicación vía satélite n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(609, '61900', N'Actividades de telecomunicación n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(610, '62010', N'Programación Informática', 1, 'juanh', HOST_NAME(), GETDATE()),
(611, '62020', N'Consultorías y gestión de servicios informáticos', 1, 'juanh', HOST_NAME(), GETDATE()),
(612, '62090', N'Otras actividades de tecnología de información y servicios de computadora', 1, 'juanh', HOST_NAME(), GETDATE()),
(613, '63110', N'Procesamiento de datos y actividades relacionadas', 1, 'juanh', HOST_NAME(), GETDATE()),
(614, '63120', N'Portales WEB', 1, 'juanh', HOST_NAME(), GETDATE()),
(615, '63910', N'Servicios de Agencias de Noticias', 1, 'juanh', HOST_NAME(), GETDATE()),
(616, '63990', N'Otros servicios de información n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(617, '64110', N'Servicios provistos por el Banco Central de El Salvador', 1, 'juanh', HOST_NAME(), GETDATE()),
(618, '64190', N'Bancos', 1, 'juanh', HOST_NAME(), GETDATE()),
(619, '64192', N'Entidades dedicadas al envío de remesas', 1, 'juanh', HOST_NAME(), GETDATE()),
(620, '64199', N'Otras entidades financieras', 1, 'juanh', HOST_NAME(), GETDATE()),
(621, '64200', N'Actividades de sociedades de cartera', 1, 'juanh', HOST_NAME(), GETDATE()),
(622, '64300', N'Fideicomisos, fondos y otras fuentes de financiamiento', 1, 'juanh', HOST_NAME(), GETDATE()),
(623, '64910', N'Arrendamientos financieros', 1, 'juanh', HOST_NAME(), GETDATE()),
(624, '64920', N'Asociaciones cooperativas de ahorro y crédito dedicadas a la intermediación financiera', 1, 'juanh', HOST_NAME(), GETDATE()),
(625, '64921', N'Instituciones emisoras de tarjetas de crédito y otros', 1, 'juanh', HOST_NAME(), GETDATE()),
(626, '64922', N'Tipos de crédito ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(627, '64928', N'Prestamistas y casas de empeño', 1, 'juanh', HOST_NAME(), GETDATE()),
(628, '64990', N'Actividades de servicios financieros, excepto la financiación de planes de seguros y de pensiones n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(629, '65110', N'Planes de seguros de vida', 1, 'juanh', HOST_NAME(), GETDATE()),
(630, '65120', N'Planes de seguro excepto de vida', 1, 'juanh', HOST_NAME(), GETDATE()),
(631, '65199', N'Seguros generales de todo tipo', 1, 'juanh', HOST_NAME(), GETDATE()),
(632, '65200', N'Planes se seguro', 1, 'juanh', HOST_NAME(), GETDATE()),
(633, '65300', N'Planes de pensiones', 1, 'juanh', HOST_NAME(), GETDATE()),
(634, '66110', N'Administración de mercados financieros (Bolsa de Valores)', 1, 'juanh', HOST_NAME(), GETDATE()),
(635, '66120', N'Actividades bursátiles (Corredores de Bolsa)', 1, 'juanh', HOST_NAME(), GETDATE()),
(636, '66190', N'Actividades auxiliares de la intermediación financiera ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(637, '66210', N'Evaluación de riesgos y daños', 1, 'juanh', HOST_NAME(), GETDATE()),
(638, '66220', N'Actividades de agentes y corredores de seguros', 1, 'juanh', HOST_NAME(), GETDATE()),
(639, '66290', N'Otras actividades auxiliaras de seguros y fondos de pensiones', 1, 'juanh', HOST_NAME(), GETDATE()),
(640, '66300', N'Actividades de administración de fondos', 1, 'juanh', HOST_NAME(), GETDATE()),
(641, '68101', N'Servicio de alquiler y venta de lotes en cementerios', 1, 'juanh', HOST_NAME(), GETDATE()),
(642, '68109', N'Actividades inmobiliarias realizadas con bienes propios o arrendados n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(643, '68200', N'Actividades Inmobiliarias Realizadas a Cambio de una Retribución o por Contrata', 1, 'juanh', HOST_NAME(), GETDATE()),
(644, '69100', N'Actividades jurídicas', 1, 'juanh', HOST_NAME(), GETDATE()),
(645, '69200', N'Actividades de contabilidad, teneduría de libros y auditoría; asesoramiento en materia de impuestos', 1, 'juanh', HOST_NAME(), GETDATE()),
(646, '70100', N'Actividades de oficinas centrales de sociedades de cartera', 1, 'juanh', HOST_NAME(), GETDATE()),
(647, '70200', N'Actividades de consultoría en gestión empresarial', 1, 'juanh', HOST_NAME(), GETDATE()),
(648, '71101', N'Servicios de arquitectura and planificación urbana y servicios conexos', 1, 'juanh', HOST_NAME(), GETDATE()),
(649, '71102', N'Servicios de ingeniería', 1, 'juanh', HOST_NAME(), GETDATE()),
(650, '71103', N'Servicios de agrimensura, topografía, cartografía, prospección y geofísica y servicios conexos', 1, 'juanh', HOST_NAME(), GETDATE()),
(651, '71200', N'Ensayos y análisis técnicos', 1, 'juanh', HOST_NAME(), GETDATE()),
(652, '72100', N'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería', 1, 'juanh', HOST_NAME(), GETDATE()),
(653, '72199', N'Investigaciones científicas', 1, 'juanh', HOST_NAME(), GETDATE()),
(654, '72200', N'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades científica y desarrollo', 1, 'juanh', HOST_NAME(), GETDATE()),
(655, '73100', N'Publicidad', 1, 'juanh', HOST_NAME(), GETDATE()),
(656, '73200', N'Investigación de mercados y realización de encuestas de opinión pública', 1, 'juanh', HOST_NAME(), GETDATE()),
(657, '74100', N'Actividades de diseño especializado', 1, 'juanh', HOST_NAME(), GETDATE()),
(658, '74200', N'Actividades de fotografía', 1, 'juanh', HOST_NAME(), GETDATE()),
(659, '74900', N'Servicios profesionales y científicos ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(660, '75000', N'Actividades veterinarias', 1, 'juanh', HOST_NAME(), GETDATE()),
(661, '77101', N'Alquiler de equipo de transporte terrestre', 1, 'juanh', HOST_NAME(), GETDATE()),
(662, '77102', N'Alquiler de equipo de transporte acuático', 1, 'juanh', HOST_NAME(), GETDATE()),
(663, '77103', N'Alquiler de equipo de transporte por vía aérea', 1, 'juanh', HOST_NAME(), GETDATE()),
(664, '77210', N'Alquiler y arrendamiento de equipo de recreo y deportivo', 1, 'juanh', HOST_NAME(), GETDATE()),
(665, '77220', N'Alquiler de cintas de video y discos', 1, 'juanh', HOST_NAME(), GETDATE()),
(666, '77290', N'Alquiler de otros efectos personales y enseres domésticos', 1, 'juanh', HOST_NAME(), GETDATE()),
(667, '77300', N'Alquiler de maquinaria y equipo', 1, 'juanh', HOST_NAME(), GETDATE()),
(668, '77400', N'Arrendamiento de productos de propiedad intelectual', 1, 'juanh', HOST_NAME(), GETDATE()),
(669, '78100', N'Obtención y dotación de personal', 1, 'juanh', HOST_NAME(), GETDATE()),
(670, '78200', N'Actividades de las agencias de trabajo temporal', 1, 'juanh', HOST_NAME(), GETDATE()),
(671, '78300', N'Dotación de recursos humanos y gestión; gestión de las funciones de recursos humanos', 1, 'juanh', HOST_NAME(), GETDATE()),
(672, '79110', N'Actividades de agencias de viajes y organizadores de viajes; actividades de asistencia a turistas', 1, 'juanh', HOST_NAME(), GETDATE()),
(673, '79120', N'Actividades de los operadores turísticos', 1, 'juanh', HOST_NAME(), GETDATE()),
(674, '79900', N'Otros servicios de reservas y actividades relacionadas', 1, 'juanh', HOST_NAME(), GETDATE()),
(675, '80100', N'Servicios de seguridad privados', 1, 'juanh', HOST_NAME(), GETDATE()),
(676, '80201', N'Actividades de servicios de sistemas de seguridad', 1, 'juanh', HOST_NAME(), GETDATE()),
(677, '80202', N'Actividades para la prestación de sistemas de seguridad', 1, 'juanh', HOST_NAME(), GETDATE()),
(678, '80300', N'Actividades de investigación', 1, 'juanh', HOST_NAME(), GETDATE()),
(679, '81100', N'Actividades combinadas de mantenimiento de edificios e instalaciones', 1, 'juanh', HOST_NAME(), GETDATE()),
(680, '81210', N'Limpieza general de edificios', 1, 'juanh', HOST_NAME(), GETDATE()),
(681, '81290', N'Otras actividades combinadas de mantenimiento de edificios e instalaciones ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(682, '81300', N'Servicio de jardinería', 1, 'juanh', HOST_NAME(), GETDATE()),
(683, '82110', N'Servicios administrativos de oficinas', 1, 'juanh', HOST_NAME(), GETDATE()),
(684, '82190', N'Servicio de fotocopiado y similares, excepto en imprentas', 1, 'juanh', HOST_NAME(), GETDATE()),
(685, '82200', N'Actividades de las centrales de llamadas (call center)', 1, 'juanh', HOST_NAME(), GETDATE()),
(686, '82300', N'Organización de convenciones y ferias de negocios', 1, 'juanh', HOST_NAME(), GETDATE()),
(687, '82910', N'Actividades de agencias de cobro y oficinas de crédito', 1, 'juanh', HOST_NAME(), GETDATE()),
(688, '82921', N'Servicios de envase y empaque de productos alimenticios', 1, 'juanh', HOST_NAME(), GETDATE()),
(689, '82922', N'Servicios de envase y empaque de productos medicinales', 1, 'juanh', HOST_NAME(), GETDATE()),
(690, '82929', N'Servicio de envase y empaque ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(691, '82990', N'Actividades de apoyo empresariales ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(692, '84110', N'Actividades de la Administración Pública en general', 1, 'juanh', HOST_NAME(), GETDATE()),
(693, '84111', N'Alcaldías Municipales', 1, 'juanh', HOST_NAME(), GETDATE()),
(694, '84120', N'Regulación de las actividades de prestación de servicios sanitarios, educativos, culturales y otros servicios sociales, excepto seguridad social', 1, 'juanh', HOST_NAME(), GETDATE()),
(695, '84130', N'Regulación y facilitación de la actividad económica', 1, 'juanh', HOST_NAME(), GETDATE()),
(696, '84210', N'Actividades de administración y funcionamiento del Ministerio de Relaciones Exteriores', 1, 'juanh', HOST_NAME(), GETDATE()),
(697, '84220', N'Actividades de defensa', 1, 'juanh', HOST_NAME(), GETDATE()),
(698, '84230', N'Actividades de mantenimiento del orden público y de seguridad', 1, 'juanh', HOST_NAME(), GETDATE()),
(699, '84300', N'Actividades de planes de seguridad social de afiliación obligatoria', 1, 'juanh', HOST_NAME(), GETDATE()),
(700, '85101', N'Guardería educativa', 1, 'juanh', HOST_NAME(), GETDATE()),
(701, '85102', N'Enseñanza preescolar o parvularia', 1, 'juanh', HOST_NAME(), GETDATE()),
(702, '85103', N'Enseñanza primaria', 1, 'juanh', HOST_NAME(), GETDATE()),
(703, '85104', N'Servicio de educación preescolar y primaria integrada', 1, 'juanh', HOST_NAME(), GETDATE()),
(704, '85211', N'Enseñanza secundaria tercer ciclo (7°, 8° y 9°)', 1, 'juanh', HOST_NAME(), GETDATE()),
(705, '85212', N'Enseñanza secundaria de formación general bachillerato', 1, 'juanh', HOST_NAME(), GETDATE()),
(706, '85221', N'Enseñanza secundaria de formación técnica y profesional', 1, 'juanh', HOST_NAME(), GETDATE()),
(707, '85222', N'Enseñanza secundaria de formación técnica y profesional integrada con enseñanza primaria', 1, 'juanh', HOST_NAME(), GETDATE()),
(708, '85301', N'Enseñanza superior universitaria', 1, 'juanh', HOST_NAME(), GETDATE()),
(709, '85302', N'Enseñanza superior no universitaria', 1, 'juanh', HOST_NAME(), GETDATE()),
(710, '85303', N'Enseñanza superior integrada a educación secundaria y/o primaria', 1, 'juanh', HOST_NAME(), GETDATE()),
(711, '85410', N'Education deportiva y recreativa', 1, 'juanh', HOST_NAME(), GETDATE()),
(712, '85420', N'Education cultural', 1, 'juanh', HOST_NAME(), GETDATE()),
(713, '85490', N'Otros tipos de enseñanza n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(714, '85499', N'Enseñanza formal', 1, 'juanh', HOST_NAME(), GETDATE()),
(715, '85500', N'Servicios de apoyo a la enseñanza', 1, 'juanh', HOST_NAME(), GETDATE()),
(716, '86100', N'Actividades de hospitales', 1, 'juanh', HOST_NAME(), GETDATE()),
(717, '86201', N'Clínicas médicas', 1, 'juanh', HOST_NAME(), GETDATE()),
(718, '86202', N'Servicios de Odontología', 1, 'juanh', HOST_NAME(), GETDATE()),
(719, '86203', N'Servicios médicos', 1, 'juanh', HOST_NAME(), GETDATE()),
(720, '86901', N'Servicios de análisis y estudios de diagnóstico', 1, 'juanh', HOST_NAME(), GETDATE()),
(721, '86902', N'Actividades de atención de la salud humana', 1, 'juanh', HOST_NAME(), GETDATE()),
(722, '86909', N'Otros Servicio relacionados con la salud ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(723, '87100', N'Residencias de ancianos con atención de enfermería', 1, 'juanh', HOST_NAME(), GETDATE()),
(724, '87200', N'Instituciones dedicadas al tratamiento del retraso mental, problemas de salud mental y el uso indebido de sustancias nocivas', 1, 'juanh', HOST_NAME(), GETDATE()),
(725, '87300', N'Instituciones dedicadas al cuidado de ancianos y discapacitados', 1, 'juanh', HOST_NAME(), GETDATE()),
(726, '87900', N'Actividades de asistencia a niños y jóvenes', 1, 'juanh', HOST_NAME(), GETDATE()),
(727, '87901', N'Otras actividades de atención en instituciones', 1, 'juanh', HOST_NAME(), GETDATE()),
(728, '88100', N'Actividades de asistencia sociales sin alojamiento para ancianos y discapacitados', 1, 'juanh', HOST_NAME(), GETDATE()),
(729, '88900', N'servicios sociales sin alojamiento ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(730, '90000', N'Actividades creativas artísticas y de esparcimiento', 1, 'juanh', HOST_NAME(), GETDATE()),
(731, '91010', N'Actividades de bibliotecas y archivos', 1, 'juanh', HOST_NAME(), GETDATE()),
(732, '91020', N'Actividades de museos y preservación de lugares y edificios históricos', 1, 'juanh', HOST_NAME(), GETDATE()),
(733, '91030', N'Actividades de jardines botánicos, zoológicos y de reservas naturales', 1, 'juanh', HOST_NAME(), GETDATE()),
(734, '92000', N'Actividades de juegos y apuestas', 1, 'juanh', HOST_NAME(), GETDATE()),
(735, '93110', N'Gestión de instalaciones deportivas', 1, 'juanh', HOST_NAME(), GETDATE()),
(736, '93120', N'Actividades de clubes deportivos', 1, 'juanh', HOST_NAME(), GETDATE()),
(737, '93190', N'Otras actividades deportivas', 1, 'juanh', HOST_NAME(), GETDATE()),
(738, '93210', N'Actividades de parques de atracciones y parques temáticos', 1, 'juanh', HOST_NAME(), GETDATE()),
(739, '93291', N'Discotecas y salas de baile', 1, 'juanh', HOST_NAME(), GETDATE()),
(740, '93298', N'Centros vacacionales', 1, 'juanh', HOST_NAME(), GETDATE()),
(741, '93299', N'Actividades de esparcimiento ncp', 1, 'juanh', HOST_NAME(), GETDATE()),
(742, '94110', N'Actividades de organizaciones empresariales y de empleadores', 1, 'juanh', HOST_NAME(), GETDATE()),
(743, '94120', N'Actividades de organizaciones profesionales', 1, 'juanh', HOST_NAME(), GETDATE()),
(744, '94200', N'Actividades de sindicatos', 1, 'juanh', HOST_NAME(), GETDATE()),
(745, '94910', N'Actividades de organizaciones religiosas', 1, 'juanh', HOST_NAME(), GETDATE()),
(746, '94920', N'Actividades de organizaciones políticas', 1, 'juanh', HOST_NAME(), GETDATE()),
(747, '94990', N'Actividades de asociaciones n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(748, '95110', N'Reparación de computadoras y equipo periférico', 1, 'juanh', HOST_NAME(), GETDATE()),
(749, '95120', N'Reparación de equipo de comunicación', 1, 'juanh', HOST_NAME(), GETDATE()),
(750, '95210', N'Reparación de aparatos electrónicos de consumo', 1, 'juanh', HOST_NAME(), GETDATE()),
(751, '95220', N'Reparación de aparatos doméstico y equipo de hogar y jardín', 1, 'juanh', HOST_NAME(), GETDATE()),
(752, '95230', N'Reparación de calzado y artículos de cuero', 1, 'juanh', HOST_NAME(), GETDATE()),
(753, '95240', N'Reparación de muebles y accesorios para el hogar', 1, 'juanh', HOST_NAME(), GETDATE()),
(754, '95291', N'Reparación de Instrumentos musicales', 1, 'juanh', HOST_NAME(), GETDATE()),
(755, '95292', N'Servicios de cerrajería y copiado de llaves', 1, 'juanh', HOST_NAME(), GETDATE()),
(756, '95293', N'Reparación de joyas y relojes', 1, 'juanh', HOST_NAME(), GETDATE()),
(757, '95294', N'Reparación de bicicletas, sillas de ruedas y rodados n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(758, '95299', N'Reparaciones de enseres personales n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(759, '96010', N'Lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco', 1, 'juanh', HOST_NAME(), GETDATE()),
(760, '96020', N'Peluquería y otros tratamientos de belleza', 1, 'juanh', HOST_NAME(), GETDATE()),
(761, '96030', N'Pompas fúnebres y actividades conexas', 1, 'juanh', HOST_NAME(), GETDATE()),
(762, '96091', N'Servicios de sauna y otros servicios para la estética corporal n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(763, '96092', N'Servicios n.c.p.', 1, 'juanh', HOST_NAME(), GETDATE()),
(764, '97000', N'Actividad de los hogares en calidad de empleadores de personal doméstico', 1, 'juanh', HOST_NAME(), GETDATE()),
(765, '98100', N'Actividades indiferenciadas de producción de bienes de los hogares privados para uso propio', 1, 'juanh', HOST_NAME(), GETDATE()),
(766, '98200', N'Actividades indiferenciadas de producción de servicios de los hogares privados para uso propio', 1, 'juanh', HOST_NAME(), GETDATE()),
(767, '99000', N'Actividades de organizaciones y órganos extraterritoriales', 1, 'juanh', HOST_NAME(), GETDATE()),
(768, '10001', N'Empleados', 1, 'juanh', HOST_NAME(), GETDATE()),
(769, '10002', N'Pensionado', 1, 'juanh', HOST_NAME(), GETDATE()),
(770, '10003', N'Estudiante', 1, 'juanh', HOST_NAME(), GETDATE()),
(771, '10004', N'Desempleado', 1, 'juanh', HOST_NAME(), GETDATE()),
(772, '10005', N'Otros', 1, 'juanh', HOST_NAME(), GETDATE()),
(773, '10006', N'Comerciante', 1, 'juanh', HOST_NAME(), GETDATE());

PRINT 'OK: 773 actividades económicas insertadas';
GO
