/* Tipo de cheque — Pago a Cliente (CL) — idempotente */
SET NOCOUNT ON;

DECLARE @CORR_EMPRESA INT = 1;

IF NOT EXISTS (
	SELECT 1
	FROM dbo.BAN_TIPO_CHEQUE
	WHERE CORR_EMPRESA = @CORR_EMPRESA
	  AND CLASE_TIPO_CHEQUE = N'CL'
)
BEGIN
	DECLARE @CORR_TIPO_CHEQUE INT =
		ISNULL((
			SELECT MAX(CORR_TIPO_CHEQUE)
			FROM dbo.BAN_TIPO_CHEQUE
			WHERE CORR_EMPRESA = @CORR_EMPRESA
		), 0) + 1;

	INSERT INTO dbo.BAN_TIPO_CHEQUE (
		CORR_EMPRESA,
		CORR_TIPO_CHEQUE,
		NOMBRE_TIPO_CHEQUE,
		CUENTA_CONTABLE,
		CLASE_TIPO_CHEQUE,
		CONTABILIZAR_LUEGO_DE_IMPRIMIR,
		ESTADO_TIPO_CHEQUE,
		USUARIO_CREA,
		FECHA_CREA,
		ESTACION_CREA,
		USUARIO_ACTU,
		FECHA_ACTU,
		ESTACION_ACTU
	)
	VALUES (
		@CORR_EMPRESA,
		@CORR_TIPO_CHEQUE,
		N'Pago a Cliente',
		N'1101010102',
		N'CL',
		0,
		1,
		N'system',
		GETDATE(),
		N'deploy',
		N'system',
		GETDATE(),
		N'deploy'
	);

	PRINT N'Tipo de cheque Pago a Cliente insertado (CORR_TIPO_CHEQUE=' + CAST(@CORR_TIPO_CHEQUE AS NVARCHAR(20)) + N').';
END
ELSE
BEGIN
	PRINT N'Tipo de cheque Pago a Cliente (CL) ya existe.';
END
GO
