/* Datos de prueba — Jose Jonathan Avalos Cuellar (PROVEEDOR / CLIENTE / EMPLEADO)
   + cuentas de gasto en GEN_EMPLEADO y BAN_TIPO_CHEQUE */
SET NOCOUNT ON;

DECLARE @CORR_EMPRESA INT = 1;
DECLARE @USUARIO VARCHAR(30) = 'system';
DECLARE @ESTACION VARCHAR(50) = 'deploy';
DECLARE @FECHA DATETIME = GETDATE();

DECLARE @CUENTA_GASTO_EMPLEADO VARCHAR(30) = '41010101';   /* SUELDOS Y SALARIOS */
DECLARE @CUENTA_GASTO_PROVEEDOR VARCHAR(30) = '41010103';  /* COMISIONES */
DECLARE @CUENTA_GASTO_CLIENTE VARCHAR(30) = '41020201';    /* REINTEGRO DE ARANCELES */

IF NOT EXISTS (
	SELECT 1 FROM dbo.CON_CATALOGO_CUENTA
	WHERE CORR_EMPRESA = @CORR_EMPRESA AND CUENTA_CONTABLE = @CUENTA_GASTO_EMPLEADO
)
BEGIN
	RAISERROR(N'No existe la cuenta %s en CON_CATALOGO_CUENTA.', 16, 1, @CUENTA_GASTO_EMPLEADO);
	RETURN;
END;

IF NOT EXISTS (
	SELECT 1 FROM dbo.GEN_PROVEEDOR
	WHERE CORR_EMPRESA = @CORR_EMPRESA
	  AND NOMBRE_PROVEEDOR = N'Jose Jonathan Avalos Cuellar (PROVEEDOR)'
)
BEGIN
	DECLARE @CORR_PROVEEDOR INT =
		ISNULL((SELECT MAX(CORR_PROVEEDOR) FROM dbo.GEN_PROVEEDOR WHERE CORR_EMPRESA = @CORR_EMPRESA), 0) + 1;

	INSERT INTO dbo.GEN_PROVEEDOR (
		CORR_EMPRESA, CORR_PROVEEDOR, CODIGO_PROVEEDOR, TIPO_PERSONERIA, NOMBRE_PROVEEDOR,
		PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, NOMBRE_COMERCIAL,
		CORR_TIPO_DIP, NUMERO_DIP, NUMERO_NRC, NUMERO_NIT, CORR_ACTIVIDAD_ECONOMICA,
		DIRECCION_PROVEEDOR, CORR_PAIS, CORR_DEPTO, CORR_MUNICIPIO, NOMBRE_CONTACTO,
		TELEFONO_FIJO, TELEFONO_MOVIL, CORREO_ELECTRONICO_1, CORREO_ELECTRONICO_2,
		CORR_FORMA_PAGO, CUENTA_BANCARIA, CORR_BANCO, ESTADO_PROVEEDOR, ESTADO_PROVEEDOR_WEB,
		USUARIO_CREA, FECHA_CREA, ESTACION_CREA, USUARIO_ACTU, FECHA_ACTU, ESTACION_ACTU, CORR_CONDICION_PAGO
	)
	VALUES (
		@CORR_EMPRESA, @CORR_PROVEEDOR, N'JAC-PRV', N'N', N'Jose Jonathan Avalos Cuellar (PROVEEDOR)',
		N'Jose', N'Jonathan', N'Avalos', N'Cuellar', N'Jose Jonathan Avalos Cuellar (PROVEEDOR)',
		0, N'', N'', N'', N'',
		N'', 0, 0, 0, N'Jose Jonathan Avalos Cuellar',
		N'', N'', N'javalos.proveedor@test.local', N'',
		0, N'', 0, N'A', N'',
		@USUARIO, @FECHA, @ESTACION, @USUARIO, @FECHA, @ESTACION, 0
	);

	IF @@ROWCOUNT > 0
		PRINT N'GEN_PROVEEDOR insertado (CORR_PROVEEDOR=' + CAST(@CORR_PROVEEDOR AS NVARCHAR(20)) + N').';
END
ELSE
	PRINT N'GEN_PROVEEDOR Jose Jonathan Avalos Cuellar (PROVEEDOR) ya existe.';

IF NOT EXISTS (
	SELECT 1 FROM dbo.GEN_CLIENTE
	WHERE CORR_EMPRESA = @CORR_EMPRESA
	  AND NOMBRE_CLIENTE = N'Jose Jonathan Avalos Cuellar (CLIENTE)'
)
BEGIN
	DECLARE @CORR_CLIENTE INT =
		ISNULL((SELECT MAX(CORR_CLIENTE) FROM dbo.GEN_CLIENTE WHERE CORR_EMPRESA = @CORR_EMPRESA), 0) + 1;

	INSERT INTO dbo.GEN_CLIENTE (
		CORR_EMPRESA, CORR_CLIENTE, CODIGO_CLIENTE, NOMBRE_CLIENTE, NOMBRE_CONTACTO,
		DUI, NIT, TELEFONO_1, CORREO_ELECTRONICO, ESTA_ACTIVO,
		USUARIO_CREA, FECHA_CREA, ESTACION_CREA, USUARIO_ACTU, FECHA_ACTU, ESTACION_ACTU
	)
	VALUES (
		@CORR_EMPRESA, @CORR_CLIENTE, N'JAC-CLI', N'Jose Jonathan Avalos Cuellar (CLIENTE)', N'Jose Jonathan Avalos Cuellar',
		N'', N'', N'', N'javalos.cliente@test.local', 1,
		@USUARIO, @FECHA, @ESTACION, @USUARIO, @FECHA, @ESTACION
	);

	PRINT N'GEN_CLIENTE insertado (CORR_CLIENTE=' + CAST(@CORR_CLIENTE AS NVARCHAR(20)) + N').';
END
ELSE
	PRINT N'GEN_CLIENTE Jose Jonathan Avalos Cuellar (CLIENTE) ya existe.';

IF NOT EXISTS (
	SELECT 1 FROM dbo.GEN_EMPLEADO
	WHERE CORR_EMPRESA = @CORR_EMPRESA
	  AND NOMBRE_EMPLEADO = N'Jose Jonathan Avalos Cuellar (EMPLEADO)'
)
BEGIN
	DECLARE @CORR_EMPLEADO INT =
		ISNULL((SELECT MAX(CORR_EMPLEADO) FROM dbo.GEN_EMPLEADO WHERE CORR_EMPRESA = @CORR_EMPRESA), 0) + 1;

	INSERT INTO dbo.GEN_EMPLEADO (
		CORR_EMPRESA, CORR_EMPLEADO, NOMBRE_EMPLEADO, NOMBRE_1, NOMBRE_2, APELLIDO_1, APELLIDO_2, APELLIDO_3,
		DUI, LUGAR_EXTIENDE_DUI, NIT, PASAPORTE, LICENCIA_CONDUCIR, CARNET_ELECTORAL, NUMERO_SEGURO_SOCIAL,
		NOMBRE_EMPLEADO_SEGURO, NUMERO_AFP, NOMBRE_EMPLEADO_AFP, LUGAR_NACIMIENTO, FECHA_NACIMIENTO, FECHA_INGRESO,
		FECHA_ULTIMA_INDEMNIZACION, FECHA_ULTIMA_VACACION, SEXO, ESTADO_CIVIL, TIPO_SANGRE, ESTATURA, PESO,
		DIRECCION_PARTICULAR, TELEFONO_1, TELEFONO_2, FAX, CORREO_ELECTRONICO, SITIO_WEB, TIPO_CUENTA_BANCO,
		CUENTA_BANCARIA, CUENTA_CONTABLE, SALARIO_MENSUAL, SALARIO_DIARIO, SALARIO_HORA, TITULO, MARCA_ENTRADA_SALIDA,
		NUMERO_TARJETA, ESTADO_EMPLEADO, USUARIO_CREA, FECHA_CREA, ESTACION_CREA, USUARIO_ACTU, FECHA_ACTU, ESTACION_ACTU,
		DEVENGA_DIA_CALENDARIO
	)
	SELECT
		CORR_EMPRESA,
		@CORR_EMPLEADO,
		N'Jose Jonathan Avalos Cuellar (EMPLEADO)',
		N'Jose', N'Jonathan', N'Avalos', N'Cuellar', N'',
		N'00000009-9', LUGAR_EXTIENDE_DUI, N'0000-000000-009-9', PASAPORTE, LICENCIA_CONDUCIR, CARNET_ELECTORAL, N'000000009',
		N'Jose Jonathan Avalos Cuellar (EMPLEADO)', N'000000009', N'Jose Jonathan Avalos Cuellar (EMPLEADO)', LUGAR_NACIMIENTO,
		FECHA_NACIMIENTO, FECHA_INGRESO, FECHA_ULTIMA_INDEMNIZACION, FECHA_ULTIMA_VACACION, SEXO, ESTADO_CIVIL, TIPO_SANGRE,
		ESTATURA, PESO, DIRECCION_PARTICULAR, TELEFONO_1, TELEFONO_2, FAX, N'javalos.empleado@test.local', SITIO_WEB,
		TIPO_CUENTA_BANCO, CUENTA_BANCARIA, @CUENTA_GASTO_EMPLEADO, 0, 0, 0, TITULO, MARCA_ENTRADA_SALIDA,
		N'000009', ESTADO_EMPLEADO, @USUARIO, @FECHA, @ESTACION, @USUARIO, @FECHA, @ESTACION, DEVENGA_DIA_CALENDARIO
	FROM dbo.GEN_EMPLEADO
	WHERE CORR_EMPRESA = @CORR_EMPRESA AND CORR_EMPLEADO = 2;

	IF @@ROWCOUNT > 0
		PRINT N'GEN_EMPLEADO insertado (CORR_EMPLEADO=' + CAST(@CORR_EMPLEADO AS NVARCHAR(20)) + N', CUENTA=' + @CUENTA_GASTO_EMPLEADO + N').';
END
ELSE
BEGIN
	UPDATE dbo.GEN_EMPLEADO
	SET CUENTA_CONTABLE = @CUENTA_GASTO_EMPLEADO,
		USUARIO_ACTU = @USUARIO,
		FECHA_ACTU = @FECHA,
		ESTACION_ACTU = @ESTACION
	WHERE CORR_EMPRESA = @CORR_EMPRESA
	  AND NOMBRE_EMPLEADO = N'Jose Jonathan Avalos Cuellar (EMPLEADO)';

	PRINT N'GEN_EMPLEADO Jose Jonathan Avalos Cuellar (EMPLEADO) ya existía; cuenta actualizada.';
END;

UPDATE dbo.BAN_TIPO_CHEQUE
SET CUENTA_CONTABLE = @CUENTA_GASTO_PROVEEDOR,
	USUARIO_ACTU = @USUARIO,
	FECHA_ACTU = @FECHA,
	ESTACION_ACTU = @ESTACION
WHERE CORR_EMPRESA = @CORR_EMPRESA AND CLASE_TIPO_CHEQUE = N'PR';

UPDATE dbo.BAN_TIPO_CHEQUE
SET CUENTA_CONTABLE = @CUENTA_GASTO_EMPLEADO,
	USUARIO_ACTU = @USUARIO,
	FECHA_ACTU = @FECHA,
	ESTACION_ACTU = @ESTACION
WHERE CORR_EMPRESA = @CORR_EMPRESA AND CLASE_TIPO_CHEQUE = N'EM';

UPDATE dbo.BAN_TIPO_CHEQUE
SET CUENTA_CONTABLE = @CUENTA_GASTO_CLIENTE,
	USUARIO_ACTU = @USUARIO,
	FECHA_ACTU = @FECHA,
	ESTACION_ACTU = @ESTACION
WHERE CORR_EMPRESA = @CORR_EMPRESA AND CLASE_TIPO_CHEQUE = N'CL';

PRINT N'BAN_TIPO_CHEQUE actualizado: PR=' + @CUENTA_GASTO_PROVEEDOR + N', EM=' + @CUENTA_GASTO_EMPLEADO + N', CL=' + @CUENTA_GASTO_CLIENTE + N'.';
GO
