/* ============================================================================
   Menú Generales — Bancos (GEN_BANCO)
   Mueve la opción de Bancos desde sistema BANCOS a GENERAL.
   Idempotente. Migra permisos de BAN_BANCO → GEN_BANCO.
   ============================================================================
   Ejecutar:
     sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i MENU_GEN_BANCO.sql
   ============================================================================ */
SET NOCOUNT ON;

DECLARE @SISTEMA_GEN varchar(30) = 'GENERAL';
DECLARE @SISTEMA_BAN varchar(30) = 'BANCOS';
DECLARE @MENU        varchar(10) = 'GENERAL';
DECLARE @SUITE       varchar(30) = 'SGUEES';
DECLARE @ORD_MENU    int         = 1;
DECLARE @ORD_OPCION  int         = 7;
DECLARE @LOGIN       varchar(30) = 'admin';
DECLARE @USR         varchar(30) = 'admin';
DECLARE @EST         varchar(30) = 'SISTEMA';
DECLARE @HOY         datetime    = GETDATE();

/* Opción GEN_BANCO */
MERGE SEG_OPCION_SISTEMA AS T
USING (VALUES (N'GEN_BANCO', N'Bancos', N'/gen-banco')) AS S (CODIGO, NOMBRE, URL)
ON T.CODIGO_OPCION = S.CODIGO
WHEN MATCHED THEN
    UPDATE SET T.NOMBRE_OPCION = S.NOMBRE,
               T.URL_OPCION = S.URL,
               T.IMAGEN_OPCION = '',
               T.USUARIO_ACTU = @USR,
               T.FECHA_ACTU = @HOY,
               T.ESTACION_ACTU = @EST
WHEN NOT MATCHED THEN
    INSERT (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION, IMAGEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
    VALUES (S.CODIGO, S.NOMBRE, S.URL, '', @USR, @HOY, @EST);

INSERT INTO SEG_OPCION_SISTEMA_SUITE (CODIGO_OPCION, CODIGO_SUITE)
SELECT N'GEN_BANCO', @SUITE
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_OPCION_SISTEMA_SUITE s
    WHERE s.CODIGO_OPCION = N'GEN_BANCO' AND s.CODIGO_SUITE = @SUITE
);

/* Quitar de menú Bancos */
DELETE FROM SEG_CONFIG_OPCION
WHERE CODIGO_SISTEMA = @SISTEMA_BAN
  AND CODIGO_OPCION IN (N'BAN_BANCO', N'GEN_BANCO');

/* Agregar a menú Generales */
DELETE FROM SEG_CONFIG_OPCION
WHERE CODIGO_SISTEMA = @SISTEMA_GEN
  AND CODIGO_MENU = @MENU
  AND CODIGO_OPCION = N'GEN_BANCO';

INSERT INTO SEG_CONFIG_OPCION
    (CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
VALUES (@SISTEMA_GEN, @MENU, N'GEN_BANCO', 0, @ORD_MENU, @ORD_OPCION, @USR, @HOY, @EST);

/* Migrar permisos usuario BAN_BANCO → GEN_BANCO en GENERAL */
INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT u.LOGIN_SISTEMA, @SISTEMA_GEN, @MENU, N'GEN_BANCO', u.NUEVO, u.MODIFICAR, u.ELIMINAR, u.IMPRIMIR, @USR, @HOY, @EST
FROM SEG_USUARIO_OPCION u
WHERE u.CODIGO_OPCION = N'BAN_BANCO'
  AND NOT EXISTS (
      SELECT 1 FROM SEG_USUARIO_OPCION x
      WHERE x.LOGIN_SISTEMA = u.LOGIN_SISTEMA
        AND x.CODIGO_SISTEMA = @SISTEMA_GEN
        AND x.CODIGO_MENU = @MENU
        AND x.CODIGO_OPCION = N'GEN_BANCO'
  );

UPDATE u
SET u.CODIGO_SISTEMA = @SISTEMA_GEN,
    u.CODIGO_MENU = @MENU,
    u.CODIGO_OPCION = N'GEN_BANCO',
    u.USUARIO_ACTU = @USR,
    u.FECHA_ACTU = @HOY,
    u.ESTACION_ACTU = @EST
FROM SEG_USUARIO_OPCION u
WHERE u.CODIGO_OPCION = N'BAN_BANCO'
  AND u.CODIGO_SISTEMA = @SISTEMA_BAN;

DELETE FROM SEG_USUARIO_OPCION
WHERE CODIGO_OPCION = N'BAN_BANCO'
  AND CODIGO_SISTEMA = @SISTEMA_BAN;

/* Permisos admin por defecto */
INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT @LOGIN, @SISTEMA_GEN, @MENU, N'GEN_BANCO', 1, 1, 1, 1, @USR, @HOY, @EST
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_USUARIO_OPCION u
    WHERE u.LOGIN_SISTEMA = @LOGIN
      AND u.CODIGO_SISTEMA = @SISTEMA_GEN
      AND u.CODIGO_MENU = @MENU
      AND u.CODIGO_OPCION = N'GEN_BANCO'
);

PRINT 'Menú Generales — Bancos (GEN_BANCO) configurado.';

SELECT c.CODIGO_SISTEMA, c.CODIGO_MENU, c.ORDEN_OPCION, c.CODIGO_OPCION, o.NOMBRE_OPCION, o.URL_OPCION
FROM SEG_CONFIG_OPCION c
INNER JOIN SEG_OPCION_SISTEMA o ON c.CODIGO_OPCION = o.CODIGO_OPCION
WHERE c.CODIGO_OPCION = N'GEN_BANCO'
ORDER BY c.CODIGO_SISTEMA, c.ORDEN_OPCION;
