/* Menú — Solicitud de Cheques (SGUEES) */

SET NOCOUNT ON;

DECLARE @SISTEMA     varchar(30) = 'BANCOS';
DECLARE @SUITE       varchar(30) = 'SGUEES';
DECLARE @MENU        varchar(10) = 'PROCESO';
DECLARE @ORD_SISTEMA int         = 4;
DECLARE @ORD_MENU    int         = 1;
DECLARE @LOGIN       varchar(30) = 'admin';
DECLARE @USR         varchar(30) = 'admin';
DECLARE @EST         varchar(30) = 'SISTEMA';
DECLARE @HOY         datetime    = GETDATE();

MERGE SEG_SISTEMA AS T
USING (VALUES (@SISTEMA, N'Caja y Bancos', 'money', 'BAN', 'Banking')) AS S
    (CODIGO_SISTEMA, NOMBRE_SISTEMA, IMAGEN_SISTEMA, PREFIJO, NOMBRE_MODULO)
ON T.CODIGO_SISTEMA = S.CODIGO_SISTEMA
WHEN MATCHED THEN
    UPDATE SET T.NOMBRE_SISTEMA = S.NOMBRE_SISTEMA,
               T.IMAGEN_SISTEMA = S.IMAGEN_SISTEMA,
               T.PREFIJO = S.PREFIJO,
               T.NOMBRE_MODULO = S.NOMBRE_MODULO
WHEN NOT MATCHED THEN
    INSERT (CODIGO_SISTEMA, NOMBRE_SISTEMA, IMAGEN_SISTEMA, PREFIJO, NOMBRE_MODULO)
    VALUES (S.CODIGO_SISTEMA, S.NOMBRE_SISTEMA, S.IMAGEN_SISTEMA, S.PREFIJO, S.NOMBRE_MODULO);

IF NOT EXISTS (SELECT 1 FROM SEG_MENU_SISTEMA WHERE CODIGO_MENU = @MENU)
BEGIN
    INSERT INTO SEG_MENU_SISTEMA (CODIGO_MENU, NOMBRE_MENU, IMAGEN_MENU)
    VALUES (@MENU, N'Procesos', 'process');
END
ELSE
BEGIN
    UPDATE SEG_MENU_SISTEMA SET NOMBRE_MENU = N'Procesos', IMAGEN_MENU = 'process'
    WHERE CODIGO_MENU = @MENU;
END;

DECLARE @Opciones TABLE (
    CODIGO varchar(30),
    NOMBRE nvarchar(100),
    URL    nvarchar(4000),
    ORD    int
);

INSERT INTO @Opciones (CODIGO, NOMBRE, URL, ORD) VALUES
    (N'BAN_SOLI_CHEQUE',          N'Solicitud de Cheques',           N'/ban-soli-cheque',          8),
    (N'BAN_SOLI_CHEQUE_AUTORIZA', N'Autorizar Solicitud de Cheques', N'/ban-soli-cheque-autoriza', 9);

MERGE SEG_OPCION_SISTEMA AS T
USING @Opciones AS S ON T.CODIGO_OPCION = S.CODIGO
WHEN MATCHED THEN
    UPDATE SET T.NOMBRE_OPCION = S.NOMBRE,
               T.URL_OPCION = S.URL,
               T.USUARIO_ACTU = @USR,
               T.FECHA_ACTU = @HOY,
               T.ESTACION_ACTU = @EST
WHEN NOT MATCHED THEN
    INSERT (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION, IMAGEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
    VALUES (S.CODIGO, S.NOMBRE, S.URL, '', @USR, @HOY, @EST);

INSERT INTO SEG_OPCION_SISTEMA_SUITE (CODIGO_OPCION, CODIGO_SUITE)
SELECT o.CODIGO, @SUITE FROM @Opciones o
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_OPCION_SISTEMA_SUITE s
    WHERE s.CODIGO_OPCION = o.CODIGO AND s.CODIGO_SUITE = @SUITE
);

DELETE FROM SEG_CONFIG_OPCION
WHERE CODIGO_SISTEMA = @SISTEMA
  AND CODIGO_MENU = @MENU
  AND CODIGO_OPCION IN (SELECT CODIGO FROM @Opciones);

INSERT INTO SEG_CONFIG_OPCION
    (CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT @SISTEMA, @MENU, o.CODIGO, @ORD_SISTEMA, @ORD_MENU, o.ORD, @USR, @HOY, @EST
FROM @Opciones o;

INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT @LOGIN, @SISTEMA, @MENU, o.CODIGO, 1, 1, 1, 1, @USR, @HOY, @EST
FROM @Opciones o
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_USUARIO_OPCION u
    WHERE u.LOGIN_SISTEMA = @LOGIN
      AND u.CODIGO_SISTEMA = @SISTEMA
      AND u.CODIGO_MENU = @MENU
      AND u.CODIGO_OPCION = o.CODIGO
);

UPDATE u
SET u.NUEVO = 1,
    u.MODIFICAR = 1,
    u.ELIMINAR = 1,
    u.IMPRIMIR = 1,
    u.CODIGO_MENU = @MENU,
    u.USUARIO_ACTU = @USR,
    u.FECHA_ACTU = @HOY,
    u.ESTACION_ACTU = @EST
FROM SEG_USUARIO_OPCION u
INNER JOIN @Opciones o ON o.CODIGO = u.CODIGO_OPCION
WHERE u.LOGIN_SISTEMA = @LOGIN
  AND u.CODIGO_SISTEMA = @SISTEMA;

INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT DISTINCT
    u.LOGIN_SISTEMA,
    @SISTEMA,
    @MENU,
    o.CODIGO,
    1, 1, 1, 1,
    @USR, @HOY, @EST
FROM SEG_USUARIO_OPCION u
CROSS JOIN @Opciones o
WHERE u.CODIGO_SISTEMA = @SISTEMA
  AND u.CODIGO_MENU = @MENU
  AND u.CODIGO_OPCION IN (N'BAN_CHEQUE', N'BAN_DOCUMENTO', N'BAN_SOLI_CHEQUE')
  AND NOT EXISTS (
      SELECT 1 FROM SEG_USUARIO_OPCION x
      WHERE x.LOGIN_SISTEMA = u.LOGIN_SISTEMA
        AND x.CODIGO_SISTEMA = @SISTEMA
        AND x.CODIGO_MENU = @MENU
        AND x.CODIGO_OPCION = o.CODIGO
  );

PRINT N'Menu BAN solicitud de cheques configurado.';
GO
