/* ============================================================================
   Menú — Tipo Documento Adjunto (PLA_TIPO_DOCUMENTO_ADJUNTO)
   Idempotente. Ubica la opción junto a PLA_TIPO_PUESTO si existe.
   ============================================================================
   Ejecutar:
     sqlcmd -S <servidor> -d SGUEES -U <user> -P <pass> -f 65001 -i MENU_PLA_TIPO_DOCUMENTO_ADJUNTO.sql
   ============================================================================ */
SET NOCOUNT ON;

DECLARE @SISTEMA     varchar(30);
DECLARE @MENU        varchar(10);
DECLARE @SUITE       varchar(30) = 'SGUEES';
DECLARE @ORD_MENU    int;
DECLARE @ORD_OPCION  int;
DECLARE @LOGIN       varchar(30) = 'admin';
DECLARE @USR         varchar(30) = 'admin';
DECLARE @EST         varchar(30) = 'SISTEMA';
DECLARE @HOY         datetime    = GETDATE();

SELECT TOP (1)
    @SISTEMA = c.CODIGO_SISTEMA,
    @MENU = c.CODIGO_MENU,
    @ORD_MENU = c.ORDEN_MENU,
    @ORD_OPCION = ISNULL(c.ORDEN_OPCION, 0) + 1
FROM SEG_CONFIG_OPCION AS c
WHERE c.CODIGO_OPCION = N'PLA_TIPO_PUESTO'
ORDER BY c.ORDEN_SISTEMA, c.ORDEN_MENU, c.ORDEN_OPCION;

IF @SISTEMA IS NULL
BEGIN
    SELECT TOP (1)
        @SISTEMA = c.CODIGO_SISTEMA,
        @MENU = c.CODIGO_MENU,
        @ORD_MENU = c.ORDEN_MENU,
        @ORD_OPCION = ISNULL(MAX(c2.ORDEN_OPCION), 0) + 1
    FROM SEG_CONFIG_OPCION AS c
    LEFT JOIN SEG_CONFIG_OPCION AS c2
        ON c2.CODIGO_SISTEMA = c.CODIGO_SISTEMA
       AND c2.CODIGO_MENU = c.CODIGO_MENU
    WHERE c.CODIGO_OPCION LIKE N'PLA_%'
    GROUP BY c.CODIGO_SISTEMA, c.CODIGO_MENU, c.ORDEN_MENU
    ORDER BY c.CODIGO_SISTEMA, c.ORDEN_MENU;
END;

IF @SISTEMA IS NULL OR @MENU IS NULL
BEGIN
    RAISERROR(N'No se pudo determinar CODIGO_SISTEMA/CODIGO_MENU para opciones PLA_*. Configure el menú manualmente.', 16, 1);
    RETURN;
END;

MERGE SEG_OPCION_SISTEMA AS T
USING (VALUES (N'PLA_TIPO_DOCUMENTO_ADJUNTO', N'Tipo Documento Adjunto', N'/pla-tipo-documento-adjunto')) AS S (CODIGO, NOMBRE, URL)
ON T.CODIGO_OPCION = S.CODIGO
WHEN MATCHED THEN
    UPDATE SET T.NOMBRE_OPCION = S.NOMBRE,
               T.URL_OPCION = S.URL,
               T.IMAGEN_OPCION = '',
               T.USUARIO_ACTU = @USR,
               T.FECHA_ACTU = @HOY,
               T.ESTACION_ACTU = @EST
WHEN NOT MATCHED THEN
    INSERT (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION, IMAGEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
    VALUES (S.CODIGO, S.NOMBRE, S.URL, '', @USR, @HOY, @EST);

INSERT INTO SEG_OPCION_SISTEMA_SUITE (CODIGO_OPCION, CODIGO_SUITE)
SELECT N'PLA_TIPO_DOCUMENTO_ADJUNTO', @SUITE
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_OPCION_SISTEMA_SUITE s
    WHERE s.CODIGO_OPCION = N'PLA_TIPO_DOCUMENTO_ADJUNTO' AND s.CODIGO_SUITE = @SUITE
);

DELETE FROM SEG_CONFIG_OPCION
WHERE CODIGO_OPCION = N'PLA_TIPO_DOCUMENTO_ADJUNTO';

INSERT INTO SEG_CONFIG_OPCION
    (CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
VALUES (@SISTEMA, @MENU, N'PLA_TIPO_DOCUMENTO_ADJUNTO', 0, @ORD_MENU, @ORD_OPCION, @USR, @HOY, @EST);

INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT @LOGIN, @SISTEMA, @MENU, N'PLA_TIPO_DOCUMENTO_ADJUNTO', 1, 1, 1, 1, @USR, @HOY, @EST
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_USUARIO_OPCION u
    WHERE u.LOGIN_SISTEMA = @LOGIN
      AND u.CODIGO_SISTEMA = @SISTEMA
      AND u.CODIGO_MENU = @MENU
      AND u.CODIGO_OPCION = N'PLA_TIPO_DOCUMENTO_ADJUNTO'
);

PRINT N'Menú — Tipo Documento Adjunto (PLA_TIPO_DOCUMENTO_ADJUNTO) configurado.';

SELECT c.CODIGO_SISTEMA, c.CODIGO_MENU, c.ORDEN_OPCION, c.CODIGO_OPCION, o.NOMBRE_OPCION, o.URL_OPCION
FROM SEG_CONFIG_OPCION c
INNER JOIN SEG_OPCION_SISTEMA o ON c.CODIGO_OPCION = o.CODIGO_OPCION
WHERE c.CODIGO_OPCION = N'PLA_TIPO_DOCUMENTO_ADJUNTO'
ORDER BY c.CODIGO_SISTEMA, c.ORDEN_OPCION;
