/* Opción de menú: Asistente IA (idempotente). Ejecutar en SGUEES con sqlcmd -f 65001 */
SET NOCOUNT ON;
DECLARE @SUITE varchar(30) = N'SGUEES';
DECLARE @USR varchar(30) = N'admin';
DECLARE @EST varchar(30) = N'SISTEMA';
DECLARE @HOY datetime = GETDATE();

IF NOT EXISTS (SELECT 1 FROM dbo.SEG_OPCION_SISTEMA WHERE CODIGO_OPCION = N'SGUEES_ASISTENTE')
BEGIN
	INSERT INTO dbo.SEG_OPCION_SISTEMA (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION, IMG_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
	VALUES (N'SGUEES_ASISTENTE', N'Asistente del sistema', N'/asistente', N'help', @USR, @HOY, @EST);
END
ELSE
BEGIN
	UPDATE dbo.SEG_OPCION_SISTEMA
	SET NOMBRE_OPCION = N'Asistente del sistema', URL_OPCION = N'/asistente', IMG_OPCION = N'help'
	WHERE CODIGO_OPCION = N'SGUEES_ASISTENTE';
END

IF NOT EXISTS (SELECT 1 FROM dbo.SEG_OPCION_SISTEMA_SUITE WHERE CODIGO_SUITE = @SUITE AND CODIGO_OPCION = N'SGUEES_ASISTENTE')
	INSERT INTO dbo.SEG_OPCION_SISTEMA_SUITE (CODIGO_SUITE, CODIGO_OPCION) VALUES (@SUITE, N'SGUEES_ASISTENTE');

IF NOT EXISTS (
	SELECT 1 FROM dbo.SEG_CONFIG_OPCION
	WHERE CODIGO_SISTEMA = N'GENERAL' AND CODIGO_MENU = N'GENERAL' AND CODIGO_OPCION = N'SGUEES_ASISTENTE'
)
	INSERT INTO dbo.SEG_CONFIG_OPCION (CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, ORDEN_MENU, ORDEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
	VALUES (N'GENERAL', N'GENERAL', N'SGUEES_ASISTENTE', 99, 99, @USR, @HOY, @EST);

IF NOT EXISTS (
	SELECT 1 FROM dbo.SEG_USUARIO_OPCION
	WHERE LOGIN_SISTEMA = @USR AND CODIGO_SUITE = @SUITE AND CODIGO_OPCION = N'SGUEES_ASISTENTE'
)
	INSERT INTO dbo.SEG_USUARIO_OPCION (LOGIN_SISTEMA, CODIGO_SUITE, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, PERMISO, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
	SELECT @USR, @SUITE, c.CODIGO_SISTEMA, c.CODIGO_MENU, c.CODIGO_OPCION, N'CRUDP', @USR, @HOY, @EST
	FROM dbo.SEG_CONFIG_OPCION c
	WHERE c.CODIGO_OPCION = N'SGUEES_ASISTENTE';

PRINT N'Menú Asistente IA listo. Cierre sesión y reingrese.';
