/* ============================================================================
   Menú Reportes Bancos — oleada 1 (4 reportes BAN_REPO)
   Idempotente. Permisos: NUEVO=consultar (R), IMPRIMIR=PDF (P)
   Ejecutar:
     sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i MENU_BANCOS_REPORTES.sql
   Tras ejecutar: cerrar sesión e ingresar de nuevo para refrescar menú.
   ============================================================================ */
SET NOCOUNT ON;

DECLARE @SISTEMA     varchar(30) = 'BANCOS';
DECLARE @SUITE       varchar(30) = 'SGUEES';
DECLARE @MENU        varchar(10) = 'REPORTE';
DECLARE @ORD_SISTEMA int         = 4;
DECLARE @ORD_MENU    int         = 3;
DECLARE @LOGIN       varchar(30) = 'admin';
DECLARE @USR         varchar(30) = 'admin';
DECLARE @EST         varchar(30) = 'SISTEMA';
DECLARE @HOY         datetime    = GETDATE();

MERGE SEG_MENU_SISTEMA AS T
USING (VALUES (@MENU, N'Reportes', 'chart')) AS S (CODIGO_MENU, NOMBRE_MENU, IMAGEN_MENU)
ON T.CODIGO_MENU = S.CODIGO_MENU
WHEN MATCHED THEN
    UPDATE SET T.NOMBRE_MENU = S.NOMBRE_MENU, T.IMAGEN_MENU = S.IMAGEN_MENU
WHEN NOT MATCHED THEN
    INSERT (CODIGO_MENU, NOMBRE_MENU, IMAGEN_MENU)
    VALUES (S.CODIGO_MENU, S.NOMBRE_MENU, S.IMAGEN_MENU);

DECLARE @Reportes TABLE (
    CODIGO varchar(30),
    NOMBRE nvarchar(100),
    URL    nvarchar(4000),
    ORD    int
);

INSERT INTO @Reportes (CODIGO, NOMBRE, URL, ORD) VALUES
    (N'BAN_REPO_CHEQUE_EMITIDOS',         N'Reporte de Cheques Emitidos',      N'/ban-reporte-cheque-emitidos',           1),
    (N'BAN_REPO_ESTADO_CUENTA',           N'Disponibilidad Bancaria Auxiliar', N'/ban-reporte-estado-cuenta',             2),
    (N'BAN_REPO_EST_CUENTA_ACUM',         N'Disponibilidad Bancaria',          N'/ban-reporte-estado-cuenta-acumulado',   3),
    (N'BAN_REPO_ENTREGA_CHEQUES',         N'Reporte de Cheques Entregados',    N'/ban-reporte-entrega-cheques',            4);

MERGE SEG_OPCION_SISTEMA AS T
USING @Reportes AS S ON T.CODIGO_OPCION = S.CODIGO
WHEN MATCHED THEN
    UPDATE SET T.NOMBRE_OPCION = S.NOMBRE,
               T.URL_OPCION = S.URL,
               T.IMAGEN_OPCION = '',
               T.USUARIO_ACTU = @USR,
               T.FECHA_ACTU = @HOY,
               T.ESTACION_ACTU = @EST
WHEN NOT MATCHED THEN
    INSERT (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION, IMAGEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
    VALUES (S.CODIGO, S.NOMBRE, S.URL, '', @USR, @HOY, @EST);

INSERT INTO SEG_OPCION_SISTEMA_SUITE (CODIGO_OPCION, CODIGO_SUITE)
SELECT r.CODIGO, @SUITE
FROM @Reportes r
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_OPCION_SISTEMA_SUITE s
    WHERE s.CODIGO_OPCION = r.CODIGO AND s.CODIGO_SUITE = @SUITE
);

DELETE FROM SEG_CONFIG_OPCION
WHERE CODIGO_SISTEMA = @SISTEMA
  AND CODIGO_MENU = @MENU
  AND CODIGO_OPCION IN (SELECT CODIGO FROM @Reportes);

INSERT INTO SEG_CONFIG_OPCION
    (CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT @SISTEMA, @MENU, r.CODIGO, @ORD_SISTEMA, @ORD_MENU, r.ORD, @USR, @HOY, @EST
FROM @Reportes r;

/* admin */
INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT @LOGIN, @SISTEMA, @MENU, r.CODIGO, 1, 0, 0, 1, @USR, @HOY, @EST
FROM @Reportes r
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_USUARIO_OPCION u
    WHERE u.LOGIN_SISTEMA = @LOGIN
      AND u.CODIGO_SISTEMA = @SISTEMA
      AND u.CODIGO_MENU = @MENU
      AND u.CODIGO_OPCION = r.CODIGO
);

UPDATE u
SET u.NUEVO = 1,
    u.MODIFICAR = 0,
    u.ELIMINAR = 0,
    u.IMPRIMIR = 1,
    u.CODIGO_MENU = @MENU,
    u.USUARIO_ACTU = @USR,
    u.FECHA_ACTU = @HOY,
    u.ESTACION_ACTU = @EST
FROM SEG_USUARIO_OPCION u
INNER JOIN @Reportes r ON r.CODIGO = u.CODIGO_OPCION
WHERE u.LOGIN_SISTEMA = @LOGIN
  AND u.CODIGO_SISTEMA = @SISTEMA;

/* Usuarios con acceso a procesos bancarios */
DECLARE @Logins TABLE (LOGIN_SISTEMA varchar(30));

INSERT INTO @Logins (LOGIN_SISTEMA)
SELECT DISTINCT LOGIN_SISTEMA
FROM SEG_USUARIO_OPCION
WHERE CODIGO_SISTEMA = @SISTEMA
  AND CODIGO_OPCION IN (N'BAN_CHEQUE', N'BAN_DOCUMENTO', N'BAN_CUENTA_BANCARIA');

INSERT INTO @Logins (LOGIN_SISTEMA)
SELECT @LOGIN
WHERE NOT EXISTS (SELECT 1 FROM @Logins l WHERE l.LOGIN_SISTEMA = @LOGIN);

INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT l.LOGIN_SISTEMA, @SISTEMA, @MENU, r.CODIGO, 1, 0, 0, 1, @USR, @HOY, @EST
FROM @Logins l
CROSS JOIN @Reportes r
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_USUARIO_OPCION u
    WHERE u.LOGIN_SISTEMA = l.LOGIN_SISTEMA
      AND u.CODIGO_OPCION = r.CODIGO
);

UPDATE u
SET u.CODIGO_MENU = @MENU,
    u.NUEVO = 1,
    u.IMPRIMIR = 1,
    u.USUARIO_ACTU = @USR,
    u.FECHA_ACTU = @HOY,
    u.ESTACION_ACTU = @EST
FROM SEG_USUARIO_OPCION u
INNER JOIN @Reportes r ON r.CODIGO = u.CODIGO_OPCION
WHERE u.CODIGO_SISTEMA = @SISTEMA;

PRINT N'Menú Reportes Bancos (4 opciones) configurado.';

SELECT c.CODIGO_MENU, c.ORDEN_OPCION, c.CODIGO_OPCION, o.NOMBRE_OPCION, o.URL_OPCION
FROM SEG_CONFIG_OPCION c
INNER JOIN SEG_OPCION_SISTEMA o ON c.CODIGO_OPCION = o.CODIGO_OPCION
WHERE c.CODIGO_SISTEMA = @SISTEMA AND c.CODIGO_MENU = @MENU
ORDER BY c.ORDEN_OPCION;
GO
