/* ============================================================================
   Menú Bancos — Parámetros Bancarios (BAN_PARAMETRO)
   Idempotente. Asigna permisos CRUD al usuario admin.
   ============================================================================ */
SET NOCOUNT ON;

DECLARE @SISTEMA     varchar(30) = 'BANCOS';
DECLARE @SUITE       varchar(30) = 'SGUEES';
DECLARE @MENU        varchar(10) = 'GENERAL';
DECLARE @ORD_SISTEMA int         = 4;
DECLARE @ORD_MENU    int         = 4;
DECLARE @ORD_OPCION  int         = 5;
DECLARE @LOGIN       varchar(30) = 'admin';
DECLARE @USR         varchar(30) = 'admin';
DECLARE @EST         varchar(30) = 'SISTEMA';
DECLARE @HOY         datetime    = GETDATE();
DECLARE @CODIGO      varchar(30) = 'BAN_PARAMETRO';

MERGE SEG_OPCION_SISTEMA AS T
USING (VALUES (@CODIGO, N'Parámetros Bancarios', N'/ban-parametro')) AS S
    (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION)
ON T.CODIGO_OPCION = S.CODIGO_OPCION
WHEN MATCHED THEN
    UPDATE SET T.NOMBRE_OPCION = S.NOMBRE_OPCION,
               T.URL_OPCION = S.URL_OPCION,
               T.IMAGEN_OPCION = '',
               T.USUARIO_ACTU = @USR,
               T.FECHA_ACTU = @HOY,
               T.ESTACION_ACTU = @EST
WHEN NOT MATCHED THEN
    INSERT (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION, IMAGEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
    VALUES (S.CODIGO_OPCION, S.NOMBRE_OPCION, S.URL_OPCION, '', @USR, @HOY, @EST);

INSERT INTO SEG_OPCION_SISTEMA_SUITE (CODIGO_OPCION, CODIGO_SUITE)
SELECT @CODIGO, @SUITE
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_OPCION_SISTEMA_SUITE s
    WHERE s.CODIGO_OPCION = @CODIGO AND s.CODIGO_SUITE = @SUITE
);

DELETE FROM SEG_CONFIG_OPCION
WHERE CODIGO_SISTEMA = @SISTEMA
  AND CODIGO_MENU = @MENU
  AND CODIGO_OPCION = @CODIGO;

INSERT INTO SEG_CONFIG_OPCION
    (CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
VALUES (@SISTEMA, @MENU, @CODIGO, @ORD_SISTEMA, @ORD_MENU, @ORD_OPCION, @USR, @HOY, @EST);

INSERT INTO SEG_USUARIO_OPCION
    (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)
SELECT @LOGIN, @SISTEMA, @MENU, @CODIGO, 1, 1, 1, 1, @USR, @HOY, @EST
WHERE NOT EXISTS (
    SELECT 1 FROM SEG_USUARIO_OPCION u
    WHERE u.LOGIN_SISTEMA = @LOGIN
      AND u.CODIGO_SISTEMA = @SISTEMA
      AND u.CODIGO_MENU = @MENU
      AND u.CODIGO_OPCION = @CODIGO
);

UPDATE u
SET u.NUEVO = 1,
    u.MODIFICAR = 1,
    u.ELIMINAR = 1,
    u.IMPRIMIR = 1,
    u.CODIGO_MENU = @MENU,
    u.USUARIO_ACTU = @USR,
    u.FECHA_ACTU = @HOY,
    u.ESTACION_ACTU = @EST
FROM SEG_USUARIO_OPCION u
WHERE u.LOGIN_SISTEMA = @LOGIN
  AND u.CODIGO_SISTEMA = @SISTEMA
  AND u.CODIGO_OPCION = @CODIGO;

PRINT N'Menú Parámetros Bancarios configurado para usuario admin.';
