/* ============================================================================

   Menú Reportes Contabilidad (oleada 1) — una opción por reporte

   - Pantalla unificada: Consultar (grid/Excel) + Imprimir PDF

   - Solo 5 pilotos con SP en SGUEES-DB; el resto se agrega por oleadas

   - Idempotente

   ============================================================================ */

SET NOCOUNT ON;

DECLARE @SISTEMA varchar(30) = 'CONTABILIDAD';

DECLARE @SUITE   varchar(30) = 'SGUEES';

DECLARE @MENU    varchar(10) = 'REPORTE';

DECLARE @ORD_MENU int        = 2;

DECLARE @USR     varchar(30) = 'admin';

DECLARE @EST     varchar(30) = 'SISTEMA';

DECLARE @HOY     datetime    = GETDATE();



MERGE SEG_MENU_SISTEMA AS T

USING (VALUES (@MENU, 'Reportes', '')) AS S (CODIGO_MENU, NOMBRE_MENU, IMAGEN_MENU)

ON T.CODIGO_MENU = S.CODIGO_MENU

WHEN MATCHED THEN UPDATE SET T.NOMBRE_MENU = S.NOMBRE_MENU, T.IMAGEN_MENU = S.IMAGEN_MENU

WHEN NOT MATCHED THEN INSERT (CODIGO_MENU, NOMBRE_MENU, IMAGEN_MENU) VALUES (S.CODIGO_MENU, S.NOMBRE_MENU, S.IMAGEN_MENU);



DECLARE @Reportes TABLE (CODIGO varchar(30), NOMBRE varchar(100), URL nvarchar(4000), ORD int);

INSERT INTO @Reportes (CODIGO, NOMBRE, URL, ORD) VALUES

  ('CON_REPO_GASTOS',               'Reporte de Gastos',            '/con-reporte-gastos',               1),

  ('CON_REPO_GASTOS_PRESUPUESTO',   'Gastos y Presupuesto',         '/con-reporte-gastos-presupuesto',   2),

  ('CON_REPO_LIBRO_DIARIO',         'Libro Diario',                 '/con-reporte-libro-diario',         3),

  ('CON_REPO_BALANCE_SALDOS_AUXI',  'Balance Saldos Auxiliares',    '/con-reporte-balance-saldos-auxi',  4),

  ('CON_REPO_CATALOGO_PRESUPUESTO', 'Reporte de Presupuesto',       '/con-reporte-catalogo-presupuesto', 5);



/* Quitar menú Consultas duplicado si se ejecutó script anterior */

DELETE FROM SEG_CONFIG_OPCION

WHERE CODIGO_SISTEMA = @SISTEMA AND CODIGO_MENU = 'CONSULTA'

  AND CODIGO_OPCION LIKE 'CON_CONS_%';



DELETE FROM SEG_USUARIO_OPCION

WHERE CODIGO_SISTEMA = @SISTEMA AND CODIGO_OPCION LIKE 'CON_CONS_%';



MERGE SEG_OPCION_SISTEMA AS T

USING @Reportes AS S ON T.CODIGO_OPCION = S.CODIGO

WHEN MATCHED THEN

  UPDATE SET T.NOMBRE_OPCION = S.NOMBRE, T.URL_OPCION = S.URL, T.IMAGEN_OPCION = '',

             T.USUARIO_ACTU = @USR, T.FECHA_ACTU = @HOY, T.ESTACION_ACTU = @EST

WHEN NOT MATCHED THEN

  INSERT (CODIGO_OPCION, NOMBRE_OPCION, URL_OPCION, IMAGEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)

  VALUES (S.CODIGO, S.NOMBRE, S.URL, '', @USR, @HOY, @EST);



INSERT INTO SEG_OPCION_SISTEMA_SUITE (CODIGO_OPCION, CODIGO_SUITE)

SELECT r.CODIGO, @SUITE FROM @Reportes r

WHERE NOT EXISTS (SELECT 1 FROM SEG_OPCION_SISTEMA_SUITE s WHERE s.CODIGO_OPCION = r.CODIGO AND s.CODIGO_SUITE = @SUITE);



DELETE FROM SEG_CONFIG_OPCION

WHERE CODIGO_SISTEMA = @SISTEMA AND CODIGO_MENU = @MENU

  AND CODIGO_OPCION IN (SELECT CODIGO FROM @Reportes);



INSERT INTO SEG_CONFIG_OPCION

  (CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, ORDEN_SISTEMA, ORDEN_MENU, ORDEN_OPCION, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)

SELECT @SISTEMA, @MENU, r.CODIGO, 2, @ORD_MENU, r.ORD, @USR, @HOY, @EST

FROM @Reportes r;



DECLARE @Logins TABLE (LOGIN_SISTEMA varchar(30));

INSERT INTO @Logins (LOGIN_SISTEMA)

SELECT DISTINCT LOGIN_SISTEMA FROM SEG_USUARIO_OPCION WHERE CODIGO_OPCION = 'CON_PARTIDA';



INSERT INTO SEG_USUARIO_OPCION

  (LOGIN_SISTEMA, CODIGO_SISTEMA, CODIGO_MENU, CODIGO_OPCION, NUEVO, MODIFICAR, ELIMINAR, IMPRIMIR, USUARIO_CREA, FECHA_CREA, ESTACION_CREA)

SELECT l.LOGIN_SISTEMA, @SISTEMA, @MENU, r.CODIGO, 1, 0, 0, 1, @USR, @HOY, @EST

FROM @Logins l CROSS JOIN @Reportes r

WHERE NOT EXISTS (

  SELECT 1 FROM SEG_USUARIO_OPCION u

  WHERE u.LOGIN_SISTEMA = l.LOGIN_SISTEMA AND u.CODIGO_OPCION = r.CODIGO

);



UPDATE u SET u.CODIGO_MENU = @MENU, u.IMPRIMIR = 1, u.USUARIO_ACTU = @USR, u.FECHA_ACTU = @HOY, u.ESTACION_ACTU = @EST

FROM SEG_USUARIO_OPCION u

INNER JOIN @Reportes r ON r.CODIGO = u.CODIGO_OPCION

WHERE u.CODIGO_SISTEMA = @SISTEMA;



PRINT 'Menú Reportes Contabilidad (5 pilotos, pantalla unificada) configurado.';



SELECT c.CODIGO_MENU, c.ORDEN_OPCION, c.CODIGO_OPCION, o.NOMBRE_OPCION, o.URL_OPCION

FROM SEG_CONFIG_OPCION c

INNER JOIN SEG_OPCION_SISTEMA o ON c.CODIGO_OPCION = o.CODIGO_OPCION

WHERE c.CODIGO_SISTEMA = @SISTEMA AND c.CODIGO_MENU = @MENU

ORDER BY c.ORDEN_OPCION;

