/*
  Orquestador: migracion CLASS -> SGUEES
  1) Des-aplica y anula partida APE junio 2026 (si existe)
  2) Carga CON_CATALOGO_SALDO_HIS hasta 30/04/2026 (balance + IN/GA)
  3) Periodos ene-abr CE, may AB
  4) Migra y aplica partidas mayo 2026

  Ejecutar en SGUEES (192.168.0.250) con linked server CLASS_UEES activo.

  Uso:
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -i MIGRATE_CLASS_RUN_ABRIL_MAYO.sql
*/
SET NOCOUNT ON;

DECLARE @E NUMERIC(38, 0);
DECLARE @M NVARCHAR(4000);
DECLARE @F INT;
DECLARE @CORR_PARTIDA INT;
DECLARE @CORR_CLASE_APE INT;
DECLARE @FECHA DATETIME = GETDATE();

PRINT '=== 1) Des-aplicar partida APE junio 2026 ===';

SELECT TOP 1 @CORR_CLASE_APE = CORR_CLASE_PARTIDA
FROM CON_CLASE_PARTIDA
WHERE CORR_EMPRESA = 1 AND NOMBRE_CORTO_CLASE = 'APE';

SELECT TOP 1 @CORR_PARTIDA = CORR_PARTIDA
FROM CON_PARTIDA
WHERE CORR_EMPRESA = 1
  AND ANIO_PERIODO = 2026
  AND MES_PERIODO = 6
  AND CORR_CLASE_PARTIDA = @CORR_CLASE_APE
  AND ESTADO_PARTIDA IN ('AP', 'DI');

IF @CORR_PARTIDA IS NOT NULL
BEGIN
    IF EXISTS (
        SELECT 1 FROM CON_PARTIDA
        WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026 AND MES_PERIODO = 6
          AND CORR_CLASE_PARTIDA = @CORR_CLASE_APE AND CORR_PARTIDA = @CORR_PARTIDA
          AND ESTADO_PARTIDA = 'AP'
    )
    BEGIN
        EXEC dbo.PRAL_MTTO_CON_PARTIDA_DESAPLICAR
            1, 2026, 6, @CORR_CLASE_APE, @CORR_PARTIDA OUTPUT,
            'MIGRACION', @FECHA, 'SQL', 'MIGRACION', 'SQL',
            @F OUTPUT, @E OUTPUT, @M OUTPUT;

        IF ISNULL(@E, 0) <> 0
            PRINT 'DESAPLICAR: ' + ISNULL(@M, '');
    END;

    EXEC dbo.PRAL_MTTO_CON_PARTIDA_ANULAR
        1, 2026, 6, @CORR_CLASE_APE, @CORR_PARTIDA OUTPUT,
        'MIGRACION', @FECHA, 'SQL', 'MIGRACION', 'SQL',
        @F OUTPUT, @E OUTPUT, @M OUTPUT;

    DELETE FROM CON_PARTIDA_DETA
    WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026 AND MES_PERIODO = 6
      AND CORR_CLASE_PARTIDA = @CORR_CLASE_APE AND CORR_PARTIDA = @CORR_PARTIDA;

    DELETE FROM CON_PARTIDA
    WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026 AND MES_PERIODO = 6
      AND CORR_CLASE_PARTIDA = @CORR_CLASE_APE AND CORR_PARTIDA = @CORR_PARTIDA;

    PRINT 'Partida APE junio eliminada.';
END
ELSE
    PRINT 'No hay partida APE junio.';

PRINT '=== 2) Periodos contables 2026 ===';

DECLARE @MES_IDX INT = 1;
WHILE @MES_IDX <= 12
BEGIN
    IF NOT EXISTS (SELECT 1 FROM CON_PERIODO_CONTABLE WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026 AND MES_PERIODO = @MES_IDX)
    BEGIN
        INSERT INTO CON_PERIODO_CONTABLE (CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, ESTADO_PERIODO_CON)
        VALUES (1, 2026, @MES_IDX, CASE WHEN @MES_IDX <= 4 THEN 'CE' WHEN @MES_IDX = 5 THEN 'AB' ELSE 'CE' END);
    END;
    SET @MES_IDX = @MES_IDX + 1;
END;

UPDATE CON_PERIODO_CONTABLE SET ESTADO_PERIODO_CON = 'CE'
WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026 AND MES_PERIODO BETWEEN 1 AND 4;

UPDATE CON_PERIODO_CONTABLE SET ESTADO_PERIODO_CON = 'AB'
WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026 AND MES_PERIODO = 5;

UPDATE CON_PERIODO_CONTABLE SET ESTADO_PERIODO_CON = 'AB'
WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026 AND MES_PERIODO = 6;

PRINT '=== 3) Saldos historicos CLASS hasta 30/04/2026 ===';

EXEC dbo.PRAL_MIGR_CLASS_SALDO_HISTORICO
    @ANIO = 2026,
    @MES_CORTE = 4,
    @CIERRE = 0,
    @MODO = 'LIMPIAR',
    @SYS_NUMERO_ERROR = @E OUTPUT,
    @SYS_MENSAJE_ERROR = @M OUTPUT,
    @SYS_FILAS_AFECTADAS = @F OUTPUT;

EXEC dbo.PRAL_MIGR_CLASS_SALDO_HISTORICO
    @ANIO = 2026,
    @MES_CORTE = 4,
    @CIERRE = 0,
    @MODO = 'MIGRAR',
    @SYS_NUMERO_ERROR = @E OUTPUT,
    @SYS_MENSAJE_ERROR = @M OUTPUT,
    @SYS_FILAS_AFECTADAS = @F OUTPUT;

IF ISNULL(@E, 0) <> 0
BEGIN
    RAISERROR(N'Error HIS: %s', 16, 1, @M);
    RETURN;
END;

DECLARE @CUENTAS_HIS INT = (SELECT COUNT(*) FROM CON_CATALOGO_SALDO_HIS WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026);
IF @CUENTAS_HIS = 0
BEGIN
    RAISERROR(N'CON_CATALOGO_SALDO_HIS quedo vacio. Revise PRAL_MIGR_CLASS_SALDO_HISTORICO.', 16, 1);
    RETURN;
END;

PRINT @M;

SELECT @CUENTAS_HIS AS CUENTAS_HIS,
       SUM(CASE WHEN ABS(SALDO_INICIAL5) > 0.01 THEN 1 ELSE 0 END) AS CON_SALDO_ABR
FROM CON_CATALOGO_SALDO_HIS
WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026;

PRINT '=== 4) Partidas mayo 2026 ===';

EXEC dbo.PRAL_MIGR_CLASS_PARTIDAS_MES
    @ANIO = 2026, @MES = 5, @CIERRE = 0, @MODO = 'LIMPIAR',
    @SYS_NUMERO_ERROR = @E OUTPUT, @SYS_MENSAJE_ERROR = @M OUTPUT, @SYS_FILAS_AFECTADAS = @F OUTPUT;

EXEC dbo.PRAL_MIGR_CLASS_PARTIDAS_MES
    @ANIO = 2026, @MES = 5, @CIERRE = 0, @MODO = 'MIGRAR',
    @SYS_NUMERO_ERROR = @E OUTPUT, @SYS_MENSAJE_ERROR = @M OUTPUT, @SYS_FILAS_AFECTADAS = @F OUTPUT;

IF ISNULL(@E, 0) <> 0
BEGIN
    RAISERROR(N'Error partidas mayo: %s', 16, 1, @M);
    RETURN;
END;

PRINT @M;

EXEC dbo.PRAL_MIGR_CLASS_PARTIDAS_MES
    @ANIO = 2026, @MES = 5, @CIERRE = 0, @MODO = 'APLICAR',
    @SYS_NUMERO_ERROR = @E OUTPUT, @SYS_MENSAJE_ERROR = @M OUTPUT, @SYS_FILAS_AFECTADAS = @F OUTPUT;

IF ISNULL(@E, 0) <> 0
BEGIN
    RAISERROR(N'Error aplicar mayo: %s', 16, 1, @M);
    RETURN;
END;

PRINT @M;

PRINT '=== 5) Validacion ===';

SELECT ESTADO_PARTIDA, COUNT(*) AS CANT
FROM CON_PARTIDA
WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = 2026 AND MES_PERIODO = 5
GROUP BY ESTADO_PARTIDA;

SELECT SUM(MONTO_CARGO) AS CARGOS, SUM(MONTO_ABONO) AS ABONOS
FROM CON_PARTIDA_DETA D
INNER JOIN CON_PARTIDA P
    ON D.CORR_EMPRESA = P.CORR_EMPRESA
   AND D.ANIO_PERIODO = P.ANIO_PERIODO
   AND D.MES_PERIODO = P.MES_PERIODO
   AND D.CORR_CLASE_PARTIDA = P.CORR_CLASE_PARTIDA
   AND D.CORR_PARTIDA = P.CORR_PARTIDA
WHERE P.CORR_EMPRESA = 1 AND P.ANIO_PERIODO = 2026 AND P.MES_PERIODO = 5
  AND P.ESTADO_PARTIDA = 'AP';

PRINT 'Balance General al 31/05/2026 (ejecutar reporte):';
EXEC dbo.PRAL_IMPR_BALANCE_GENERAL
    @CORR_EMPRESA = 1,
    @FECHA_FINAL = '2026-05-31',
    @NIVEL = 3,
    @PARTIDA_CIERRE = 0,
    @PARTIDA_LIQUIDACION = 0;

PRINT 'Estado Resultados al 31/05/2026:';
EXEC dbo.PRAL_IMPR_ESTADO_RESULTADOS
    @CORR_EMPRESA = 1,
    @FECHA_FINAL = '2026-05-31',
    @NIVEL = 3,
    @PARTIDA_CIERRE = 0,
    @PARTIDA_LIQUIDACION = 0;

PRINT '=== FIN MIGRACION ABRIL/MAYO ===';
GO
