/*
  Migración datos Compras: SUEES (129) -> SGUEES (250).
  SOLO LECTURA en 129. Escritura únicamente en SGUEES local.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

DECLARE @RemotePrefix NVARCHAR(200) = N'SUEES129.SUEES.dbo.';
DECLARE @Started DATETIME = GETDATE();
DECLARE @Msg NVARCHAR(4000);

IF NOT EXISTS (SELECT 1 FROM sys.servers WHERE name = N'SUEES129' AND is_linked = 1)
BEGIN
	RAISERROR(N'Linked server SUEES129 no existe. Ejecute ADD_SUEES129_INSTANCIA_REMOTA.sql', 16, 1);
	RETURN;
END

BEGIN TRY
	BEGIN TRAN;

	PRINT N'=== Deshabilitar FK COM_* (solo SGUEES) ===';
	DECLARE @fkSql NVARCHAR(MAX) = N'';
	SELECT @fkSql = @fkSql
		+ N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(f.parent_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(f.parent_object_id))
		+ N' NOCHECK CONSTRAINT ALL;'
	FROM sys.foreign_keys f
	WHERE OBJECT_NAME(f.parent_object_id) LIKE N'COM[_]%';

	IF @fkSql <> N''
		EXEC sys.sp_executesql @fkSql;

	PRINT N'=== Limpiar tablas COM_* locales (250) ===';
	DECLARE @del TABLE (Ord INT IDENTITY(1,1), TableName SYSNAME);
	INSERT INTO @del (TableName)
	VALUES
		(N'COM_BITACORA'),
		(N'COM_DOCUMENTO_DETA_DOC'),
		(N'COM_DOCUMENTO_TOTAL'),
		(N'COM_DOCUMENTO'),
		(N'COM_CUADRO_COMPARATIVO_AUTORIZACIONES'),
		(N'COM_CUADRO_COMPARATIVO_COMENTARIO'),
		(N'COM_CUADRO_COMPARATIVO_ORDEN_COMPRA'),
		(N'COM_CUADRO_COMPARATIVO_SOLI_COTIZACION'),
		(N'COM_CUADRO_COMPARATIVO_DOC'),
		(N'COM_CUADRO_COMPARATIVO_DETA'),
		(N'COM_CUADRO_COMPARATIVO'),
		(N'COM_COTIZACION_COMENTARIO'),
		(N'COM_COTIZACION_DETA_DOC'),
		(N'COM_COTIZACION_DOC'),
		(N'COM_COTIZACION_DETA'),
		(N'COM_COTIZACION'),
		(N'COM_SOLI_COTIZACION_PROVEEDOR'),
		(N'COM_SOLI_COTIZACION_DOC'),
		(N'COM_SOLI_COTIZACION_DETA_DOC'),
		(N'COM_SOLI_COTIZACION_DETA'),
		(N'COM_SOLI_COTIZACION'),
		(N'COM_PROVEEDOR_DOC'),
		(N'COM_PROVEEDOR_USUARIO'),
		(N'COM_DOCUMENTO_FISICO'),
		(N'COM_PROVEEDOR'),
		(N'COM_CUADRO_COMPARATIVO_CONFIG_AUTORIZACIONES'),
		(N'COM_PARAMETRO'),
		(N'COM_CONDICION_PAGO'),
		(N'COM_TIPO_SOLI_COTIZA'),
		(N'COM_TIPO_DOC_FISICO'),
		(N'COM_UNIDAD_MEDIDA'),
		(N'COM_BANCO');

	DECLARE @i INT = 1, @max INT = (SELECT MAX(Ord) FROM @del), @tbl SYSNAME, @delSql NVARCHAR(500);
	WHILE @i <= @max
	BEGIN
		SELECT @tbl = TableName FROM @del WHERE Ord = @i;
		IF OBJECT_ID(N'dbo.' + @tbl, N'U') IS NOT NULL
		BEGIN
			SET @delSql = N'DELETE FROM dbo.' + QUOTENAME(@tbl) + N';';
			EXEC sys.sp_executesql @delSql;
			SET @Msg = N'  Limpiado ' + @tbl;
			PRINT @Msg;
		END
		SET @i += 1;
	END

	IF OBJECT_ID(N'dbo.CLA_COM_PROVEEDOR_SECTOR', N'U') IS NOT NULL
	BEGIN
		DELETE FROM dbo.CLA_COM_PROVEEDOR_SECTOR;
		PRINT N'  Limpiado CLA_COM_PROVEEDOR_SECTOR';
	END

	PRINT N'=== Copiar datos 129 -> 250 ===';
	DECLARE @ins TABLE (Ord INT IDENTITY(1,1), TableName SYSNAME);
	INSERT INTO @ins (TableName)
	VALUES
		(N'COM_BANCO'),
		(N'COM_UNIDAD_MEDIDA'),
		(N'COM_TIPO_DOC_FISICO'),
		(N'COM_TIPO_SOLI_COTIZA'),
		(N'COM_CONDICION_PAGO'),
		(N'COM_PARAMETRO'),
		(N'COM_CUADRO_COMPARATIVO_CONFIG_AUTORIZACIONES'),
		(N'COM_PROVEEDOR'),
		(N'COM_PROVEEDOR_USUARIO'),
		(N'COM_DOCUMENTO_FISICO'),
		(N'COM_PROVEEDOR_DOC'),
		(N'COM_SOLI_COTIZACION'),
		(N'COM_SOLI_COTIZACION_DETA'),
		(N'COM_SOLI_COTIZACION_DETA_DOC'),
		(N'COM_SOLI_COTIZACION_DOC'),
		(N'COM_SOLI_COTIZACION_PROVEEDOR'),
		(N'COM_COTIZACION'),
		(N'COM_COTIZACION_DETA'),
		(N'COM_COTIZACION_DETA_DOC'),
		(N'COM_COTIZACION_DOC'),
		(N'COM_COTIZACION_COMENTARIO'),
		(N'COM_CUADRO_COMPARATIVO'),
		(N'COM_CUADRO_COMPARATIVO_DETA'),
		(N'COM_CUADRO_COMPARATIVO_DOC'),
		(N'COM_CUADRO_COMPARATIVO_AUTORIZACIONES'),
		(N'COM_CUADRO_COMPARATIVO_COMENTARIO'),
		(N'COM_CUADRO_COMPARATIVO_ORDEN_COMPRA'),
		(N'COM_CUADRO_COMPARATIVO_SOLI_COTIZACION'),
		(N'COM_DOCUMENTO'),
		(N'COM_DOCUMENTO_TOTAL'),
		(N'COM_DOCUMENTO_DETA_DOC'),
		(N'COM_BITACORA');

	SET @i = 1;
	SET @max = (SELECT MAX(Ord) FROM @ins);
	DECLARE @insSql NVARCHAR(MAX), @rows INT;

	WHILE @i <= @max
	BEGIN
		SELECT @tbl = TableName FROM @ins WHERE Ord = @i;
		IF OBJECT_ID(N'dbo.' + @tbl, N'U') IS NOT NULL
		BEGIN
			DECLARE @cols NVARCHAR(MAX);
			SELECT @cols = STUFF((
				SELECT N',' + QUOTENAME(c250.COLUMN_NAME)
				FROM INFORMATION_SCHEMA.COLUMNS c250
				INNER JOIN SUEES129.SUEES.INFORMATION_SCHEMA.COLUMNS c129
					ON c250.COLUMN_NAME COLLATE DATABASE_DEFAULT = c129.COLUMN_NAME COLLATE DATABASE_DEFAULT
				WHERE c250.TABLE_SCHEMA = N'dbo'
				  AND c129.TABLE_SCHEMA = N'dbo'
				  AND c250.TABLE_NAME = @tbl
				  AND c129.TABLE_NAME = @tbl
				ORDER BY c250.ORDINAL_POSITION
				FOR XML PATH(''), TYPE
			).value('.', 'NVARCHAR(MAX)'), 1, 1, N'');

			IF @cols IS NULL OR LEN(@cols) = 0
			BEGIN
				SET @Msg = N'  ' + @tbl + N': sin columnas comunes, omitido';
				PRINT @Msg;
			END
			ELSE
			BEGIN
				SET @insSql = N'
					INSERT INTO dbo.' + QUOTENAME(@tbl) + N' (' + @cols + N')
					SELECT ' + @cols + N'
					FROM ' + @RemotePrefix + QUOTENAME(@tbl) + N';';
				EXEC sys.sp_executesql @insSql;
				SET @rows = @@ROWCOUNT;
				SET @Msg = N'  ' + @tbl + N': ' + CAST(@rows AS NVARCHAR(20)) + N' filas';
				PRINT @Msg;
			END
		END
		SET @i += 1;
	END

	IF OBJECT_ID(N'dbo.CLA_COM_PROVEEDOR_SECTOR', N'U') IS NOT NULL
	   AND EXISTS (SELECT 1 FROM SUEES129.SUEES.INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'CLA_COM_PROVEEDOR_SECTOR')
	BEGIN
		INSERT INTO dbo.CLA_COM_PROVEEDOR_SECTOR (CORR_PROVEEDOR, CORR_SECTOR)
		SELECT CORR_PROVEEDOR, CORR_SECTOR
		FROM SUEES129.SUEES.dbo.CLA_COM_PROVEEDOR_SECTOR;
		SET @Msg = N'  CLA_COM_PROVEEDOR_SECTOR: ' + CAST(@@ROWCOUNT AS NVARCHAR(20)) + N' filas';
		PRINT @Msg;
	END

	PRINT N'=== Rehabilitar FK COM_* ===';
	SET @fkSql = N'';
	SELECT @fkSql = @fkSql
		+ N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(f.parent_object_id)) + N'.' + QUOTENAME(OBJECT_NAME(f.parent_object_id))
		+ N' WITH CHECK CHECK CONSTRAINT ALL;'
	FROM sys.foreign_keys f
	WHERE OBJECT_NAME(f.parent_object_id) LIKE N'COM[_]%';

	IF @fkSql <> N''
		EXEC sys.sp_executesql @fkSql;

	COMMIT TRAN;

	PRINT N'=== Validación conteos (129 vs 250) ===';
	DECLARE @cmp TABLE (TableName SYSNAME PRIMARY KEY);
	INSERT INTO @cmp (TableName)
	SELECT TableName FROM @ins
	UNION
	SELECT N'CLA_COM_PROVEEDOR_SECTOR'
	WHERE OBJECT_ID(N'dbo.CLA_COM_PROVEEDOR_SECTOR', N'U') IS NOT NULL;

	DECLARE @cmpSql NVARCHAR(MAX) = N'';
	SELECT @cmpSql = @cmpSql + N'
		SELECT ''' + c.TableName + N''' AS tabla,
			(SELECT COUNT(*) FROM ' + @RemotePrefix + QUOTENAME(c.TableName) + N') AS cnt_129,
			(SELECT COUNT(*) FROM dbo.' + QUOTENAME(c.TableName) + N') AS cnt_250
		UNION ALL'
	FROM @cmp c
	WHERE OBJECT_ID(N'dbo.' + c.TableName, N'U') IS NOT NULL
	   OR c.TableName = N'CLA_COM_PROVEEDOR_SECTOR';

	IF LEN(@cmpSql) > 0
	BEGIN
		SET @cmpSql = LEFT(@cmpSql, LEN(@cmpSql) - 10);
		EXEC sys.sp_executesql @cmpSql;
	END

	PRINT N'=== Migración COM_* completada en ' + CONVERT(NVARCHAR(30), DATEDIFF(SECOND, @Started, GETDATE())) + N' seg ===';
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0
		ROLLBACK TRAN;

	DECLARE @Err NVARCHAR(4000) = ERROR_MESSAGE();
	RAISERROR(N'Migración COM_* falló: %s', 16, 1, @Err);
END CATCH
GO
