/*
  Migra partidas contables de un mes desde CLASS_UEES (TRANSAC + TRANSAC_HST).

  Agrupa por fecha valor (TRAFVL) + lote (TRALOT), clase NOR, aplica partidas.

  Modos: PREVIEW | MIGRAR | APLICAR | LIMPIAR
*/
SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.PRAL_MIGR_CLASS_PARTIDAS_MES', N'P') IS NOT NULL
    DROP PROCEDURE dbo.PRAL_MIGR_CLASS_PARTIDAS_MES;
GO

CREATE PROCEDURE dbo.PRAL_MIGR_CLASS_PARTIDAS_MES
(
    @ANIO INT,
    @MES INT,
    @CIERRE INT = 0,
    @CORR_EMPRESA INT = 1,
    @MODO VARCHAR(10) = 'PREVIEW',
    @MAX_PARTIDAS INT = NULL,
    @SYS_LOGIN_USUARIO VARCHAR(30) = 'MIGRACION',
    @SYS_ESTACION VARCHAR(50) = 'SQL',
    @SYS_FILAS_AFECTADAS INT = NULL OUTPUT,
    @SYS_NUMERO_ERROR NUMERIC(38, 0) = NULL OUTPUT,
    @SYS_MENSAJE_ERROR NVARCHAR(4000) = NULL OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT @SYS_NUMERO_ERROR = 0,
           @SYS_MENSAJE_ERROR = N'',
           @SYS_FILAS_AFECTADAS = 0;

    DECLARE @MODO_U VARCHAR(10) = UPPER(LTRIM(RTRIM(ISNULL(@MODO, 'PREVIEW'))));
    DECLARE @CORR_CLASE_PARTIDA INT;
    DECLARE @CORR_MONEDA INT;
    DECLARE @CORR_CENTRO_COSTO INT;
    DECLARE @FECHA_CREA DATETIME = GETDATE();
    DECLARE @CORR_PARTIDA INT;
    DECLARE @GRP INT;
    DECLARE @FECHA_PARTIDA DATE;
    DECLARE @TRAASI VARCHAR(100);
    DECLARE @TRALOT VARCHAR(10);
    DECLARE @NOMBRE_PARTIDA VARCHAR(255);
    DECLARE @TOTAL_CARGO DECIMAL(18, 2);
    DECLARE @TOTAL_ABONO DECIMAL(18, 2);
    DECLARE @LINEAS INT;
    DECLARE @APLICADAS INT = 0;
    DECLARE @F INT;
    DECLARE @E NUMERIC(38, 0);
    DECLARE @M NVARCHAR(4000);
    DECLARE @NUMERO_DOCUMENTO VARCHAR(25);

    SELECT TOP 1 @CORR_CLASE_PARTIDA = CORR_CLASE_PARTIDA
    FROM CON_CLASE_PARTIDA
    WHERE CORR_EMPRESA = @CORR_EMPRESA
      AND NOMBRE_CORTO_CLASE = 'NOR';

    SELECT TOP 1 @CORR_MONEDA = CORR_MONEDA FROM CON_PARAMETRO WHERE CORR_EMPRESA = @CORR_EMPRESA;
    SELECT TOP 1 @CORR_CENTRO_COSTO = CORR_CENTRO_COSTO_DEF FROM CON_PARAMETRO WHERE CORR_EMPRESA = @CORR_EMPRESA;

    IF @MODO_U = 'LIMPIAR'
    BEGIN
        DELETE D
        FROM CON_PARTIDA_DETA D
        INNER JOIN CON_PARTIDA P
            ON D.CORR_EMPRESA = P.CORR_EMPRESA
           AND D.ANIO_PERIODO = P.ANIO_PERIODO
           AND D.MES_PERIODO = P.MES_PERIODO
           AND D.CORR_CLASE_PARTIDA = P.CORR_CLASE_PARTIDA
           AND D.CORR_PARTIDA = P.CORR_PARTIDA
        WHERE P.CORR_EMPRESA = @CORR_EMPRESA
          AND P.ANIO_PERIODO = @ANIO
          AND P.MES_PERIODO = @MES
          AND P.NOMBRE_PARTIDA LIKE N'MIGR CLASS%';

        DELETE FROM CON_PARTIDA
        WHERE CORR_EMPRESA = @CORR_EMPRESA
          AND ANIO_PERIODO = @ANIO
          AND MES_PERIODO = @MES
          AND NOMBRE_PARTIDA LIKE N'MIGR CLASS%';

        SELECT @SYS_FILAS_AFECTADAS = @@ROWCOUNT,
               @SYS_MENSAJE_ERROR = N'Partidas MIGR CLASS eliminadas en ' + CONVERT(VARCHAR(2), @MES) + N'/' + CONVERT(VARCHAR(4), @ANIO);
        GOTO FINA;
    END;

    SELECT CAST(NULL AS DATE) AS FECHA_PARTIDA,
           CAST(NULL AS VARCHAR(100)) AS TRAASI,
           CAST(NULL AS VARCHAR(10)) AS TRALOT,
           CAST(NULL AS VARCHAR(5)) AS TRADCC,
           CAST(NULL AS MONEY) AS CARGO,
           CAST(NULL AS MONEY) AS ABONO,
           CAST(NULL AS VARCHAR(16)) AS TRAGLN,
           CAST(NULL AS VARCHAR(255)) AS TRADSC,
           CAST(NULL AS VARCHAR(30)) AS TRACCN
    INTO #CLASS_MOV
    WHERE 1 = 0;

    IF @CIERRE = 0
    BEGIN
        INSERT INTO #CLASS_MOV
        SELECT CONVERT(DATE, TR.TRAFVL),
               CAST(TR.TRAASI AS VARCHAR(100)),
               CAST(TR.TRALOT AS VARCHAR(10)),
               TR.TRADCC,
               CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
               CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
               CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)))),
               LEFT(TR.TRADSC, 255),
               LTRIM(RTRIM(ISNULL(TR.TRACCN, '')))
        FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC TR
        WHERE TR.TRATYP = 'R'
          AND TR.TRABNK = '01'
          AND TR.TRABRN = '001'
          AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
          AND TR.TRAMOD <> 'P/G'
          AND TR.TRALOT NOT IN ('2077')
          AND YEAR(TR.TRAFVL) = @ANIO
          AND MONTH(TR.TRAFVL) = @MES
          AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '9999' + CAST(@ANIO AS VARCHAR(5))
          AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '2078' + CAST(@ANIO AS VARCHAR(5))
          AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) + TR.TRADSC <> '2080' + CAST(@ANIO AS VARCHAR(5)) + 'Liquidación Cuenta';

        INSERT INTO #CLASS_MOV
        SELECT CONVERT(DATE, TR.TRAFVL),
               CAST(TR.TRAASI AS VARCHAR(100)),
               CAST(TR.TRALOT AS VARCHAR(10)),
               TR.TRADCC,
               CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
               CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
               CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)))),
               LEFT(TR.TRADSC, 255),
               LTRIM(RTRIM(ISNULL(TR.TRACCN, '')))
        FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC_HST TR
        WHERE TR.TRATYP = 'R'
          AND TR.TRABNK = '01'
          AND TR.TRABRN = '001'
          AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
          AND TR.TRAMOD <> 'P/G'
          AND TR.TRALOT NOT IN ('2077')
          AND YEAR(TR.TRAFVL) = @ANIO
          AND MONTH(TR.TRAFVL) = @MES
          AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '9999' + CAST(@ANIO AS VARCHAR(5))
          AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '2078' + CAST(@ANIO AS VARCHAR(5))
          AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) + TR.TRADSC <> '2080' + CAST(@ANIO AS VARCHAR(5)) + 'Liquidación Cuenta';
    END
    ELSE
    BEGIN
        INSERT INTO #CLASS_MOV
        SELECT CONVERT(DATE, TR.TRAFVL),
               CAST(TR.TRAASI AS VARCHAR(100)),
               CAST(TR.TRALOT AS VARCHAR(10)),
               TR.TRADCC,
               CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
               CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
               CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)))),
               LEFT(TR.TRADSC, 255),
               LTRIM(RTRIM(ISNULL(TR.TRACCN, '')))
        FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC TR
        WHERE TR.TRATYP = 'R'
          AND TR.TRABNK = '01'
          AND TR.TRABRN = '001'
          AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
          AND TR.TRAMOD <> 'P/G'
          AND TR.TRALOT NOT IN ('2077')
          AND YEAR(TR.TRAFVL) = @ANIO
          AND MONTH(TR.TRAFVL) = @MES;

        INSERT INTO #CLASS_MOV
        SELECT CONVERT(DATE, TR.TRAFVL),
               CAST(TR.TRAASI AS VARCHAR(100)),
               CAST(TR.TRALOT AS VARCHAR(10)),
               TR.TRADCC,
               CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
               CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
               CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)))),
               LEFT(TR.TRADSC, 255),
               LTRIM(RTRIM(ISNULL(TR.TRACCN, '')))
        FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC_HST TR
        WHERE TR.TRATYP = 'R'
          AND TR.TRABNK = '01'
          AND TR.TRABRN = '001'
          AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
          AND TR.TRAMOD <> 'P/G'
          AND TR.TRALOT NOT IN ('2077')
          AND YEAR(TR.TRAFVL) = @ANIO
          AND MONTH(TR.TRAFVL) = @MES;
    END;

    SELECT M.TRAASI,
           dbo.FN_CLASS_TRAGLN_TO_CUENTA(M.TRAGLN) AS CUENTA_CONTABLE,
           dbo.FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO(@CORR_EMPRESA, M.TRACCN) AS CORR_CENTRO_COSTO,
           SUM(M.CARGO) AS MONTO_CARGO,
           SUM(M.ABONO) AS MONTO_ABONO,
           MIN(M.TRADSC) AS NOMBRE_TRAN
    INTO #DET
    FROM #CLASS_MOV M
    GROUP BY M.TRAASI,
             dbo.FN_CLASS_TRAGLN_TO_CUENTA(M.TRAGLN),
             dbo.FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO(@CORR_EMPRESA, M.TRACCN)
    HAVING SUM(M.CARGO) <> 0 OR SUM(M.ABONO) <> 0;

    SELECT M.TRAASI,
           MAX(M.FECHA_PARTIDA) AS FECHA_PARTIDA,
           MIN(M.TRALOT) AS TRALOT
    INTO #HDR
    FROM #CLASS_MOV M
    GROUP BY M.TRAASI;

    SELECT H.FECHA_PARTIDA,
           H.TRAASI,
           H.TRALOT,
           SUM(D.MONTO_CARGO) AS TOTAL_CARGO,
           SUM(D.MONTO_ABONO) AS TOTAL_ABONO,
           COUNT(*) AS LINEAS,
           MIN(D.NOMBRE_TRAN) AS NOMBRE_TRAN
    INTO #GRUPOS
    FROM #HDR H
    INNER JOIN #DET D ON D.TRAASI = H.TRAASI
    INNER JOIN CON_CATALOGO_CUENTA C
        ON C.CORR_EMPRESA = @CORR_EMPRESA
       AND C.CUENTA_CONTABLE = D.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
    GROUP BY H.FECHA_PARTIDA, H.TRAASI, H.TRALOT;

    SELECT ROW_NUMBER() OVER (ORDER BY G.FECHA_PARTIDA, G.TRAASI) AS GRP,
           G.FECHA_PARTIDA,
           G.TRAASI,
           G.TRALOT,
           G.TOTAL_CARGO,
           G.TOTAL_ABONO,
           G.LINEAS,
           G.NOMBRE_TRAN,
           ABS(ISNULL(G.TOTAL_CARGO, 0) - ISNULL(G.TOTAL_ABONO, 0)) AS DIFERENCIA
    INTO #PARTIDAS
    FROM #GRUPOS G;

    IF @MAX_PARTIDAS IS NOT NULL
        DELETE FROM #PARTIDAS WHERE GRP > @MAX_PARTIDAS;

    SELECT COUNT(*) AS LINEAS_CLASS,
           (SELECT COUNT(*) FROM #PARTIDAS) AS PARTIDAS,
           (SELECT COUNT(*) FROM #PARTIDAS WHERE DIFERENCIA > 0.01) AS PARTIDAS_DESCUADRE,
           (SELECT SUM(TOTAL_CARGO) FROM #PARTIDAS) AS SUMA_CARGOS,
           (SELECT SUM(TOTAL_ABONO) FROM #PARTIDAS) AS SUMA_ABONOS
    FROM #CLASS_MOV;

    IF EXISTS (SELECT 1 FROM #DET D LEFT JOIN CON_CATALOGO_CUENTA C ON C.CORR_EMPRESA=@CORR_EMPRESA AND C.CUENTA_CONTABLE=D.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT WHERE C.CUENTA_CONTABLE IS NULL)
    BEGIN
        SELECT TOP 20 D.CUENTA_CONTABLE, SUM(D.MONTO_CARGO) C, SUM(D.MONTO_ABONO) A
        FROM #DET D
        LEFT JOIN CON_CATALOGO_CUENTA C ON C.CORR_EMPRESA = @CORR_EMPRESA AND C.CUENTA_CONTABLE = D.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
        WHERE C.CUENTA_CONTABLE IS NULL
        GROUP BY D.CUENTA_CONTABLE;
    END;

    IF @MODO_U = 'PREVIEW'
    BEGIN
        SELECT * FROM #PARTIDAS ORDER BY GRP;

        SELECT TOP 20 * FROM #PARTIDAS WHERE DIFERENCIA > 0.01 ORDER BY DIFERENCIA DESC;

        SELECT @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
        GOTO FINA;
    END;

    IF @MODO_U = 'APLICAR'
    BEGIN
        DECLARE curA CURSOR LOCAL FAST_FORWARD FOR
            SELECT P.CORR_PARTIDA
            FROM CON_PARTIDA P
            WHERE P.CORR_EMPRESA = @CORR_EMPRESA
              AND P.ANIO_PERIODO = @ANIO
              AND P.MES_PERIODO = @MES
              AND P.CORR_CLASE_PARTIDA = @CORR_CLASE_PARTIDA
              AND P.NOMBRE_PARTIDA LIKE N'MIGR CLASS%'
              AND P.ESTADO_PARTIDA = 'DI'
            ORDER BY P.CORR_PARTIDA;

        OPEN curA;
        FETCH NEXT FROM curA INTO @CORR_PARTIDA;

        WHILE @@FETCH_STATUS = 0
        BEGIN
            EXEC dbo.PRAL_MTTO_CON_PARTIDA_APLICAR
                @CORR_EMPRESA,
                @ANIO,
                @MES,
                @CORR_CLASE_PARTIDA,
                @CORR_PARTIDA OUTPUT,
                @SYS_LOGIN_USUARIO,
                @FECHA_CREA,
                @SYS_ESTACION,
                @SYS_LOGIN_USUARIO,
                @SYS_ESTACION,
                @F OUTPUT,
                @E OUTPUT,
                @M OUTPUT;

            IF ISNULL(@E, 0) <> 0
            BEGIN
                CLOSE curA;
                DEALLOCATE curA;
                SELECT @SYS_NUMERO_ERROR = @E, @SYS_MENSAJE_ERROR = @M;
                GOTO FINA;
            END;

            SET @APLICADAS = @APLICADAS + 1;
            FETCH NEXT FROM curA INTO @CORR_PARTIDA;
        END;

        CLOSE curA;
        DEALLOCATE curA;

        SELECT @SYS_FILAS_AFECTADAS = @APLICADAS,
               @SYS_MENSAJE_ERROR = N'Partidas aplicadas: ' + CONVERT(VARCHAR(10), @APLICADAS);
        GOTO FINA;
    END;

    IF @MODO_U <> 'MIGRAR'
    BEGIN
        SELECT @SYS_NUMERO_ERROR = 30002,
               @SYS_MENSAJE_ERROR = N'Modo no valido. Use PREVIEW, MIGRAR, APLICAR o LIMPIAR.';
        GOTO FINA;
    END;

    IF EXISTS (SELECT 1 FROM #PARTIDAS WHERE DIFERENCIA > 0.01)
    BEGIN
        SELECT @SYS_NUMERO_ERROR = 30004,
               @SYS_MENSAJE_ERROR = N'Hay partidas descuadradas en CLASS. Revise PREVIEW.';
        GOTO FINA;
    END;

    IF @CORR_CLASE_PARTIDA IS NULL OR @CORR_MONEDA IS NULL
    BEGIN
        SELECT @SYS_NUMERO_ERROR = 30005,
               @SYS_MENSAJE_ERROR = N'Falta clase NOR o CON_PARAMETRO.';
        GOTO FINA;
    END;

    DECLARE curP CURSOR LOCAL FAST_FORWARD FOR
        SELECT GRP, FECHA_PARTIDA, TRAASI, TRALOT, TOTAL_CARGO, TOTAL_ABONO, LINEAS, NOMBRE_TRAN
        FROM #PARTIDAS
        ORDER BY GRP;

    OPEN curP;
    FETCH NEXT FROM curP INTO @GRP, @FECHA_PARTIDA, @TRAASI, @TRALOT, @TOTAL_CARGO, @TOTAL_ABONO, @LINEAS, @NOMBRE_PARTIDA;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @NOMBRE_PARTIDA = N'MIGR CLASS ' + CONVERT(VARCHAR(10), @FECHA_PARTIDA, 103)
            + N' ' + LEFT(@TRAASI, 80) + N' - ' + LEFT(ISNULL(@NOMBRE_PARTIDA, N''), 80);

        SET @NUMERO_DOCUMENTO = LEFT(@TRAASI, 25);

        BEGIN TRY
            BEGIN TRAN;

            SET @CORR_PARTIDA = 0;

            EXEC dbo.PRAL_MTTO_CON_PARTIDA
                1,
                @CORR_EMPRESA,
                @ANIO,
                @MES,
                @CORR_CLASE_PARTIDA,
                @CORR_PARTIDA OUTPUT,
                @FECHA_PARTIDA,
                @NUMERO_DOCUMENTO,
                @NOMBRE_PARTIDA,
                'DI',
                'NOR',
                @CORR_MONEDA,
                1,
                '*',
                @SYS_LOGIN_USUARIO,
                @FECHA_CREA,
                @SYS_ESTACION,
                @SYS_LOGIN_USUARIO,
                @FECHA_CREA,
                @SYS_ESTACION,
                @SYS_LOGIN_USUARIO,
                @SYS_ESTACION,
                @F OUTPUT,
                @E OUTPUT,
                @M OUTPUT;

            IF ISNULL(@E, 0) <> 0
            BEGIN
                ROLLBACK TRAN;
                CLOSE curP;
                DEALLOCATE curP;
                SELECT @SYS_NUMERO_ERROR = @E, @SYS_MENSAJE_ERROR = @M;
                GOTO FINA;
            END;

            INSERT INTO CON_PARTIDA_DETA
            (
                CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, CORR_CLASE_PARTIDA, CORR_PARTIDA,
                CORR_PARTIDA_DETA, CUENTA_CONTABLE, CORR_CENTRO_COSTO, NOMBRE_TRAN,
                MONTO_CARGO, MONTO_ABONO, MONTO_CARGO_FORANEA, MONTO_ABONO_FORANEA, CORR_AUXILIAR
            )
            SELECT @CORR_EMPRESA,
                   @ANIO,
                   @MES,
                   @CORR_CLASE_PARTIDA,
                   @CORR_PARTIDA,
                   ROW_NUMBER() OVER (ORDER BY D.CUENTA_CONTABLE, D.CORR_CENTRO_COSTO),
                   D.CUENTA_CONTABLE,
                   D.CORR_CENTRO_COSTO,
                   LEFT(ISNULL(D.NOMBRE_TRAN, N'MIGR CLASS'), 255),
                   D.MONTO_CARGO,
                   D.MONTO_ABONO,
                   0,
                   0,
                   NULL
            FROM #DET D
            WHERE D.TRAASI = @TRAASI
              AND (D.MONTO_CARGO <> 0 OR D.MONTO_ABONO <> 0);

            COMMIT TRAN;
            SET @APLICADAS = @APLICADAS + 1;
        END TRY
        BEGIN CATCH
            IF @@TRANCOUNT > 0 ROLLBACK TRAN;
            CLOSE curP;
            DEALLOCATE curP;
            SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(),
                   @SYS_MENSAJE_ERROR = ERROR_MESSAGE();
            GOTO FINA;
        END CATCH;

        FETCH NEXT FROM curP INTO @GRP, @FECHA_PARTIDA, @TRAASI, @TRALOT, @TOTAL_CARGO, @TOTAL_ABONO, @LINEAS, @NOMBRE_PARTIDA;
    END;

    CLOSE curP;
    DEALLOCATE curP;

    SELECT @SYS_FILAS_AFECTADAS = @APLICADAS,
           @SYS_MENSAJE_ERROR = N'Partidas creadas (DI): ' + CONVERT(VARCHAR(10), @APLICADAS)
               + N'. Ejecute @MODO=''APLICAR''.';

FINA:
    IF @MODO_U IN ('MIGRAR', 'APLICAR', 'LIMPIAR') AND ISNULL(@SYS_NUMERO_ERROR, 0) <> 0
        SELECT @SYS_NUMERO_ERROR AS SYS_NUMERO_ERROR, @SYS_MENSAJE_ERROR AS SYS_MENSAJE_ERROR;
    ELSE IF @MODO_U IN ('MIGRAR', 'APLICAR') AND ISNULL(@SYS_NUMERO_ERROR, 0) = 0
        SELECT @SYS_FILAS_AFECTADAS AS FILAS, @SYS_MENSAJE_ERROR AS MENSAJE;

    DROP TABLE IF EXISTS #CLASS_MOV;
    DROP TABLE IF EXISTS #DET;
    DROP TABLE IF EXISTS #HDR;
    DROP TABLE IF EXISTS #GRUPOS;
    DROP TABLE IF EXISTS #PARTIDAS;
END;
GO

PRINT 'PRAL_MIGR_CLASS_PARTIDAS_MES creado.';
GO
