/*
  Carga CON_CATALOGO_SALDO_HIS desde CLASS_UEES (snapshot al cierre de cada mes).

  Incluye:
    - Balance (activo, pasivo, patrimonio) con ajuste 3101/310501/310701/310601/310801
    - Ingresos y gastos (rubros 4 y 5) para Estado de Resultados

  Requisitos: FN_CLASS_TRAGLN_TO_CUENTA (MIGRATE_CLASS_SALDO_INICIAL_BALANCE_GENERAL.sql)
              Linked server CLASS_UEES, catalogo importado.

  @MES_CORTE = 4  -> llena SALDO_INICIAL2..5 (cierres ene, feb, mar, abr -> apertura feb..may)

  Modos: PREVIEW | MIGRAR | LIMPIAR
*/
SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.PRAL_MIGR_CLASS_SALDO_HISTORICO', N'P') IS NOT NULL
    DROP PROCEDURE dbo.PRAL_MIGR_CLASS_SALDO_HISTORICO;
GO

CREATE PROCEDURE dbo.PRAL_MIGR_CLASS_SALDO_HISTORICO
(
    @ANIO INT,
    @MES_CORTE INT = 4,
    @CIERRE INT = 0,
    @CORR_EMPRESA INT = 1,
    @MODO VARCHAR(10) = 'PREVIEW',
    @INCLUIR_CERO BIT = 0,
    @CARGAR_MESES_ANTERIORES BIT = 0,
    @SYS_LOGIN_USUARIO VARCHAR(30) = 'MIGRACION',
    @SYS_ESTACION VARCHAR(50) = 'SQL',
    @SYS_FILAS_AFECTADAS INT = NULL OUTPUT,
    @SYS_NUMERO_ERROR NUMERIC(38, 0) = NULL OUTPUT,
    @SYS_MENSAJE_ERROR NVARCHAR(4000) = NULL OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT @SYS_NUMERO_ERROR = 0,
           @SYS_MENSAJE_ERROR = N'',
           @SYS_FILAS_AFECTADAS = 0;

    DECLARE @MODO_U VARCHAR(10) = UPPER(LTRIM(RTRIM(ISNULL(@MODO, 'PREVIEW'))));
    DECLARE @MES_LOOP INT;
    DECLARE @COL_MES INT;
    DECLARE @GASTOINGRESO MONEY;
    DECLARE @SUM_ACTIVO DECIMAL(18, 2);
    DECLARE @SUM_PASIVO DECIMAL(18, 2);
    DECLARE @SALDO_3101_CLASS DECIMAL(18, 2);
    DECLARE @FONDO_3101 DECIMAL(18, 2);
    DECLARE @AJUSTE_ACUMULADO DECIMAL(18, 2);
    DECLARE @RESULTADO_PERIODO DECIMAL(18, 2);
    DECLARE @FECHA_CORTE DATE;
    DECLARE @CUENTAS INT;
    DECLARE @SQL NVARCHAR(MAX);

    IF @MODO_U = 'LIMPIAR'
    BEGIN
        DELETE FROM CON_CATALOGO_SALDO_HIS
        WHERE CORR_EMPRESA = @CORR_EMPRESA
          AND ANIO_PERIODO = @ANIO;

        SELECT @SYS_FILAS_AFECTADAS = @@ROWCOUNT,
               @SYS_MENSAJE_ERROR = N'Saldos historicos eliminados para ' + CONVERT(VARCHAR(4), @ANIO);
        GOTO FINA;
    END;

    IF @MES_CORTE < 1 OR @MES_CORTE > 11
    BEGIN
        SELECT @SYS_NUMERO_ERROR = 30001,
               @SYS_MENSAJE_ERROR = N'@MES_CORTE debe estar entre 1 y 11.';
        GOTO FINA;
    END;

    CREATE TABLE #HIS_ACC
    (
        CUENTA_CONTABLE VARCHAR(30) COLLATE Latin1_General_CS_AS NOT NULL,
        SALDO_INICIAL1 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SALDO_INICIAL2 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SALDO_INICIAL3 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SALDO_INICIAL4 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SALDO_INICIAL5 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SALDO_INICIAL6 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SALDO_INICIAL7 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SALDO_INICIAL8 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SALDO_INICIAL9 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SALDO_INICIAL10 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SALDO_INICIAL11 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        SALDO_INICIAL12 DECIMAL(12, 2) NOT NULL DEFAULT 0,
        CLASE_RUBRO VARCHAR(2) NULL
    );

    SET @MES_LOOP = CASE WHEN @CARGAR_MESES_ANTERIORES = 1 THEN 1 ELSE @MES_CORTE END;

    WHILE @MES_LOOP <= @MES_CORTE
    BEGIN
        SET @COL_MES = @MES_LOOP + 1;
        SET @FECHA_CORTE = EOMONTH(DATEFROMPARTS(@ANIO, @MES_LOOP, 1));

        SELECT CAST(NULL AS VARCHAR(5)) AS TRABNK,
               CAST(NULL AS VARCHAR(10)) AS TRABRN,
               CAST(NULL AS VARCHAR(5)) AS TRADCC,
               CAST(NULL AS MONEY) AS CARGO,
               CAST(NULL AS MONEY) AS ABONO,
               CAST(NULL AS VARCHAR(16)) AS TRAGLN
        INTO #TEMPMOV
        WHERE 1 = 0;

        IF @CIERRE = 0
        BEGIN
            INSERT INTO #TEMPMOV
            SELECT TR.TRABNK, TR.TRABRN, TR.TRADCC,
                   CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
                   CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
                   CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
            FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC TR
            WHERE TR.TRATYP = 'R'
              AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
              AND TR.TRAMOD <> 'P/G'
              AND TR.TRALOT NOT IN ('2077')
              AND YEAR(TR.TRAFVL) < @ANIO
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '9999' + CAST(@ANIO AS VARCHAR(5))
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '2078' + CAST(@ANIO AS VARCHAR(5))
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) + TR.TRADSC <> '2080' + CAST(@ANIO AS VARCHAR(5)) + 'Liquidación Cuenta';

            INSERT INTO #TEMPMOV
            SELECT TR.TRABNK, TR.TRABRN, TR.TRADCC,
                   CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
                   CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
                   CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
            FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC TR
            WHERE TR.TRATYP = 'R'
              AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
              AND TR.TRAMOD <> 'P/G'
              AND TR.TRALOT NOT IN ('2077')
              AND YEAR(TR.TRAFVL) = @ANIO
              AND MONTH(TR.TRAFVL) <= @MES_LOOP
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '9999' + CAST(@ANIO AS VARCHAR(5))
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '2078' + CAST(@ANIO AS VARCHAR(5))
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) + TR.TRADSC <> '2080' + CAST(@ANIO AS VARCHAR(5)) + 'Liquidación Cuenta';

            INSERT INTO #TEMPMOV
            SELECT TR.TRABNK, TR.TRABRN, TR.TRADCC,
                   CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
                   CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
                   CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
            FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC_HST TR
            WHERE TR.TRATYP = 'R'
              AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
              AND TR.TRAMOD <> 'P/G'
              AND TR.TRALOT NOT IN ('2077')
              AND YEAR(TR.TRAFVL) < @ANIO
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '9999' + CAST(@ANIO AS VARCHAR(5))
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '2078' + CAST(@ANIO AS VARCHAR(5))
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) + TR.TRADSC <> '2080' + CAST(@ANIO AS VARCHAR(5)) + 'Liquidación Cuenta';

            INSERT INTO #TEMPMOV
            SELECT TR.TRABNK, TR.TRABRN, TR.TRADCC,
                   CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
                   CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
                   CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
            FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC_HST TR
            WHERE TR.TRATYP = 'R'
              AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
              AND TR.TRAMOD <> 'P/G'
              AND TR.TRALOT NOT IN ('2077')
              AND YEAR(TR.TRAFVL) = @ANIO
              AND MONTH(TR.TRAFVL) <= @MES_LOOP
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '9999' + CAST(@ANIO AS VARCHAR(5))
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) <> '2078' + CAST(@ANIO AS VARCHAR(5))
              AND CAST(TR.TRALOT AS VARCHAR(5)) + CAST(YEAR(TR.TRAFVL) AS VARCHAR(5)) + TR.TRADSC <> '2080' + CAST(@ANIO AS VARCHAR(5)) + 'Liquidación Cuenta';
        END
        ELSE
        BEGIN
            INSERT INTO #TEMPMOV
            SELECT TR.TRABNK, TR.TRABRN, TR.TRADCC,
                   CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
                   CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
                   CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
            FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC TR
            WHERE TR.TRATYP = 'R'
              AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
              AND TR.TRAMOD <> 'P/G'
              AND TR.TRALOT NOT IN ('2077')
              AND YEAR(TR.TRAFVL) < @ANIO;

            INSERT INTO #TEMPMOV
            SELECT TR.TRABNK, TR.TRABRN, TR.TRADCC,
                   CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
                   CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
                   CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
            FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC TR
            WHERE TR.TRATYP = 'R'
              AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
              AND TR.TRAMOD <> 'P/G'
              AND TR.TRALOT NOT IN ('2077')
              AND YEAR(TR.TRAFVL) = @ANIO
              AND MONTH(TR.TRAFVL) <= @MES_LOOP;

            INSERT INTO #TEMPMOV
            SELECT TR.TRABNK, TR.TRABRN, TR.TRADCC,
                   CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
                   CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
                   CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
            FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC_HST TR
            WHERE TR.TRATYP = 'R'
              AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
              AND TR.TRAMOD <> 'P/G'
              AND TR.TRALOT NOT IN ('2077')
              AND YEAR(TR.TRAFVL) < @ANIO;

            INSERT INTO #TEMPMOV
            SELECT TR.TRABNK, TR.TRABRN, TR.TRADCC,
                   CASE WHEN TR.TRADCC = 'D' THEN TR.TRAAMT ELSE 0.00 END,
                   CASE WHEN TR.TRADCC = 'C' THEN TR.TRAAMT ELSE 0.00 END,
                   CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12)) + REPLICATE('0', 12 - LEN(CAST(LEFT(TR.TRAGLN, 4) AS VARCHAR(12))))
            FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC_HST TR
            WHERE TR.TRATYP = 'R'
              AND LEFT(CAST(TR.TRAGLN AS VARCHAR(25)), 1) IN ('1', '2', '3', '4', '5')
              AND TR.TRAMOD <> 'P/G'
              AND TR.TRALOT NOT IN ('2077')
              AND YEAR(TR.TRAFVL) = @ANIO
              AND MONTH(TR.TRAFVL) <= @MES_LOOP;
        END;

        SET @GASTOINGRESO =
            ISNULL((SELECT SUM(M.ABONO) - SUM(M.CARGO) FROM #TEMPMOV M WHERE LEFT(M.TRAGLN, 1) IN ('5')), 0.00)
          - ISNULL((SELECT SUM(M.CARGO) - SUM(M.ABONO) FROM #TEMPMOV M WHERE LEFT(M.TRAGLN, 1) IN ('4')), 0.00);

        IF @GASTOINGRESO > 0
            INSERT INTO #TEMPMOV (TRABNK, TRABRN, TRADCC, CARGO, ABONO, TRAGLN)
            SELECT '01', '001', 'C', 0.00, @GASTOINGRESO, '310600000000';
        ELSE IF @GASTOINGRESO < 0
            INSERT INTO #TEMPMOV (TRABNK, TRABRN, TRADCC, CARGO, ABONO, TRAGLN)
            SELECT '01', '001', 'C', @GASTOINGRESO, 0.00, '310800000000';

        SELECT M.TRAGLN,
               CASE
                   WHEN LEFT(M.TRAGLN, 1) IN ('1', '4') THEN SUM(ISNULL(M.CARGO, 0.00)) - SUM(ISNULL(M.ABONO, 0.00))
                   ELSE SUM(ISNULL(M.ABONO, 0.00)) - SUM(ISNULL(M.CARGO, 0.00))
               END AS SALDO_CLASS,
               LEFT(M.TRAGLN, 1) AS TIPO_CUENTA
        INTO #BALANCE_CLASS
        FROM #TEMPMOV M
        WHERE M.TRABNK = '01'
          AND M.TRABRN = '001'
        GROUP BY M.TRAGLN;

        SELECT B.TRAGLN AS TRAGLN_CLASS_12,
               B.SALDO_CLASS,
               B.TIPO_CUENTA,
               dbo.FN_CLASS_TRAGLN_TO_CUENTA(B.TRAGLN) AS CUENTA_SGUEES,
               MAP.CUENTA_CONTABLE,
               MAP.CLASE_RUBRO,
               CAST(CASE
                   WHEN MAP.CUENTA_CONTABLE IS NULL THEN NULL
                   WHEN MAP.ES_DEBE = 1 AND B.SALDO_CLASS >= 0 THEN B.SALDO_CLASS
                   WHEN MAP.ES_DEBE = 1 AND B.SALDO_CLASS < 0 THEN 0
                   WHEN MAP.ES_HABER = 1 AND B.SALDO_CLASS < 0 THEN ABS(B.SALDO_CLASS)
                   ELSE 0
               END AS DECIMAL(18, 2)) AS MONTO_CARGO,
               CAST(CASE
                   WHEN MAP.CUENTA_CONTABLE IS NULL THEN NULL
                   WHEN MAP.ES_HABER = 1 AND B.SALDO_CLASS >= 0 THEN B.SALDO_CLASS
                   WHEN MAP.ES_HABER = 1 AND B.SALDO_CLASS < 0 THEN 0
                   WHEN MAP.ES_DEBE = 1 AND B.SALDO_CLASS < 0 THEN ABS(B.SALDO_CLASS)
                   ELSE 0
               END AS DECIMAL(18, 2)) AS MONTO_ABONO
        INTO #MIGR
        FROM #BALANCE_CLASS B
        LEFT JOIN CON_CATALOGO_CUENTA MAP
            ON MAP.CORR_EMPRESA = @CORR_EMPRESA
           AND MAP.CUENTA_CONTABLE = dbo.FN_CLASS_TRAGLN_TO_CUENTA(B.TRAGLN) COLLATE DATABASE_DEFAULT
        WHERE (
                LEFT(B.TRAGLN, 1) IN ('1', '2', '3')
             OR B.TRAGLN LIKE '3106%'
             OR B.TRAGLN LIKE '3108%'
              )
          AND (@INCLUIR_CERO = 1 OR ISNULL(B.SALDO_CLASS, 0) <> 0);

        SELECT @SUM_ACTIVO = ISNULL(SUM(SALDO_CLASS), 0) FROM #BALANCE_CLASS WHERE LEFT(TRAGLN, 1) = '1';
        SELECT @SUM_PASIVO = ISNULL(SUM(SALDO_CLASS), 0) FROM #BALANCE_CLASS WHERE LEFT(TRAGLN, 1) = '2';
        SELECT @SALDO_3101_CLASS = ISNULL(SALDO_CLASS, 0) FROM #BALANCE_CLASS WHERE TRAGLN = '310100000000';

        SET @RESULTADO_PERIODO = ABS(ISNULL(@GASTOINGRESO, 0));
        SET @FONDO_3101 = @SALDO_3101_CLASS;
        SET @AJUSTE_ACUMULADO = @SALDO_3101_CLASS - ((@SUM_ACTIVO - @SUM_PASIVO) - @RESULTADO_PERIODO);

        DELETE FROM #MIGR WHERE LEFT(TRAGLN_CLASS_12, 1) = '3';

        INSERT INTO #MIGR
        (
            TRAGLN_CLASS_12, SALDO_CLASS, TIPO_CUENTA, CUENTA_SGUEES,
            CUENTA_CONTABLE, CLASE_RUBRO, MONTO_CARGO, MONTO_ABONO
        )
        SELECT P.TRAGLN_CLASS_12,
               P.SALDO_CLASS,
               '3',
               P.CUENTA_SGUEES,
               MAP.CUENTA_CONTABLE,
               MAP.CLASE_RUBRO,
               CAST(CASE
                   WHEN MAP.CUENTA_CONTABLE IS NULL THEN NULL
                   WHEN MAP.ES_DEBE = 1 AND P.SALDO_CLASS >= 0 THEN P.SALDO_CLASS
                   WHEN MAP.ES_DEBE = 1 AND P.SALDO_CLASS < 0 THEN 0
                   WHEN MAP.ES_HABER = 1 AND P.SALDO_CLASS < 0 THEN ABS(P.SALDO_CLASS)
                   ELSE 0
               END AS DECIMAL(18, 2)),
               CAST(CASE
                   WHEN MAP.CUENTA_CONTABLE IS NULL THEN NULL
                   WHEN MAP.ES_HABER = 1 AND P.SALDO_CLASS >= 0 THEN P.SALDO_CLASS
                   WHEN MAP.ES_HABER = 1 AND P.SALDO_CLASS < 0 THEN 0
                   WHEN MAP.ES_DEBE = 1 AND P.SALDO_CLASS < 0 THEN ABS(P.SALDO_CLASS)
                   ELSE 0
               END AS DECIMAL(18, 2))
        FROM (
            -- Fondo + acumulado en HIS. Resultado del periodo (310801/310601) lo calcula
            -- PRAL_IMPR_BALANCE_GENERAL desde cuentas IN/GA; no duplicar aqui.
            SELECT '310100000000' AS TRAGLN_CLASS_12, @FONDO_3101 AS SALDO_CLASS, '3101' AS CUENTA_SGUEES
            UNION ALL
            SELECT '310701000000', -@AJUSTE_ACUMULADO, '310701'
            WHERE @GASTOINGRESO < 0 AND @AJUSTE_ACUMULADO > 0.01
            UNION ALL
            SELECT '310501000000', @AJUSTE_ACUMULADO, '310501'
            WHERE @GASTOINGRESO >= 0 AND @AJUSTE_ACUMULADO > 0.01
        ) P
        LEFT JOIN CON_CATALOGO_CUENTA MAP
            ON MAP.CORR_EMPRESA = @CORR_EMPRESA
           AND MAP.CUENTA_CONTABLE = P.CUENTA_SGUEES COLLATE DATABASE_DEFAULT
        WHERE ABS(P.SALDO_CLASS) > 0.01;

        INSERT INTO #MIGR
        (
            TRAGLN_CLASS_12, SALDO_CLASS, TIPO_CUENTA, CUENTA_SGUEES,
            CUENTA_CONTABLE, CLASE_RUBRO, MONTO_CARGO, MONTO_ABONO
        )
        SELECT B.TRAGLN,
               B.SALDO_CLASS,
               B.TIPO_CUENTA,
               dbo.FN_CLASS_TRAGLN_TO_CUENTA(B.TRAGLN),
               MAP.CUENTA_CONTABLE,
               MAP.CLASE_RUBRO,
               CAST(CASE
                   WHEN MAP.ES_DEBE = 1 AND B.SALDO_CLASS >= 0 THEN B.SALDO_CLASS
                   WHEN MAP.ES_DEBE = 1 AND B.SALDO_CLASS < 0 THEN 0
                   WHEN MAP.ES_HABER = 1 AND B.SALDO_CLASS < 0 THEN ABS(B.SALDO_CLASS)
                   ELSE 0
               END AS DECIMAL(18, 2)),
               CAST(CASE
                   WHEN MAP.ES_HABER = 1 AND B.SALDO_CLASS >= 0 THEN B.SALDO_CLASS
                   WHEN MAP.ES_HABER = 1 AND B.SALDO_CLASS < 0 THEN 0
                   WHEN MAP.ES_DEBE = 1 AND B.SALDO_CLASS < 0 THEN ABS(B.SALDO_CLASS)
                   ELSE 0
               END AS DECIMAL(18, 2))
        FROM #BALANCE_CLASS B
        INNER JOIN CON_CATALOGO_CUENTA MAP
            ON MAP.CORR_EMPRESA = @CORR_EMPRESA
           AND MAP.CUENTA_CONTABLE = dbo.FN_CLASS_TRAGLN_TO_CUENTA(B.TRAGLN) COLLATE DATABASE_DEFAULT
        WHERE LEFT(B.TRAGLN, 1) IN ('4', '5')
          AND (@INCLUIR_CERO = 1 OR ISNULL(B.SALDO_CLASS, 0) <> 0);

        ;WITH MIGR_N3 AS (
            SELECT ISNULL(P3.CUENTA_CONTABLE, M.CUENTA_CONTABLE) AS CUENTA_CONTABLE,
                   MAX(M.CLASE_RUBRO) AS CLASE_RUBRO,
                   SUM(ISNULL(M.MONTO_CARGO, 0)) AS MONTO_CARGO,
                   SUM(ISNULL(M.MONTO_ABONO, 0)) AS MONTO_ABONO
            FROM #MIGR M
            INNER JOIN CON_CATALOGO_CUENTA C
                ON C.CORR_EMPRESA = @CORR_EMPRESA
               AND C.CUENTA_CONTABLE = M.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
            LEFT JOIN CON_CATALOGO_CUENTA P3
                ON P3.CORR_EMPRESA = @CORR_EMPRESA
               AND P3.NIVEL = 3
               AND M.CUENTA_CONTABLE LIKE P3.CUENTA_CONTABLE + '%' COLLATE Latin1_General_CS_AS
            WHERE M.CUENTA_CONTABLE IS NOT NULL
            GROUP BY ISNULL(P3.CUENTA_CONTABLE, M.CUENTA_CONTABLE)
        ),
        SNAPSHOT AS (
            SELECT CUENTA_CONTABLE,
                   CLASE_RUBRO,
                   CAST(ISNULL(MONTO_CARGO, 0) - ISNULL(MONTO_ABONO, 0) AS DECIMAL(12, 2)) AS SALDO_VAL
            FROM MIGR_N3
            WHERE ABS(ISNULL(MONTO_CARGO, 0) - ISNULL(MONTO_ABONO, 0)) > 0.01 OR @INCLUIR_CERO = 1
        )
        MERGE #HIS_ACC AS T
        USING SNAPSHOT AS S
            ON T.CUENTA_CONTABLE = S.CUENTA_CONTABLE COLLATE Latin1_General_CS_AS
        WHEN MATCHED THEN
            UPDATE SET
                SALDO_INICIAL1 = CASE WHEN @COL_MES = 1 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL1 END,
                SALDO_INICIAL2 = CASE WHEN @COL_MES = 2 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL2 END,
                SALDO_INICIAL3 = CASE WHEN @COL_MES = 3 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL3 END,
                SALDO_INICIAL4 = CASE WHEN @COL_MES = 4 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL4 END,
                SALDO_INICIAL5 = CASE WHEN @COL_MES = 5 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL5 END,
                SALDO_INICIAL6 = CASE WHEN @COL_MES = 6 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL6 END,
                SALDO_INICIAL7 = CASE WHEN @COL_MES = 7 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL7 END,
                SALDO_INICIAL8 = CASE WHEN @COL_MES = 8 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL8 END,
                SALDO_INICIAL9 = CASE WHEN @COL_MES = 9 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL9 END,
                SALDO_INICIAL10 = CASE WHEN @COL_MES = 10 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL10 END,
                SALDO_INICIAL11 = CASE WHEN @COL_MES = 11 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL11 END,
                SALDO_INICIAL12 = CASE WHEN @COL_MES = 12 THEN S.SALDO_VAL ELSE T.SALDO_INICIAL12 END,
                CLASE_RUBRO = ISNULL(T.CLASE_RUBRO, S.CLASE_RUBRO)
        WHEN NOT MATCHED BY TARGET THEN
            INSERT (CUENTA_CONTABLE, CLASE_RUBRO,
                    SALDO_INICIAL1, SALDO_INICIAL2, SALDO_INICIAL3, SALDO_INICIAL4, SALDO_INICIAL5,
                    SALDO_INICIAL6, SALDO_INICIAL7, SALDO_INICIAL8, SALDO_INICIAL9, SALDO_INICIAL10,
                    SALDO_INICIAL11, SALDO_INICIAL12)
            VALUES (
                S.CUENTA_CONTABLE, S.CLASE_RUBRO,
                CASE WHEN @COL_MES = 1 THEN S.SALDO_VAL ELSE 0 END,
                CASE WHEN @COL_MES = 2 THEN S.SALDO_VAL ELSE 0 END,
                CASE WHEN @COL_MES = 3 THEN S.SALDO_VAL ELSE 0 END,
                CASE WHEN @COL_MES = 4 THEN S.SALDO_VAL ELSE 0 END,
                CASE WHEN @COL_MES = 5 THEN S.SALDO_VAL ELSE 0 END,
                CASE WHEN @COL_MES = 6 THEN S.SALDO_VAL ELSE 0 END,
                CASE WHEN @COL_MES = 7 THEN S.SALDO_VAL ELSE 0 END,
                CASE WHEN @COL_MES = 8 THEN S.SALDO_VAL ELSE 0 END,
                CASE WHEN @COL_MES = 9 THEN S.SALDO_VAL ELSE 0 END,
                CASE WHEN @COL_MES = 10 THEN S.SALDO_VAL ELSE 0 END,
                CASE WHEN @COL_MES = 11 THEN S.SALDO_VAL ELSE 0 END,
                CASE WHEN @COL_MES = 12 THEN S.SALDO_VAL ELSE 0 END
            );

        DROP TABLE #TEMPMOV;
        DROP TABLE #BALANCE_CLASS;
        DROP TABLE #MIGR;

        SET @MES_LOOP = @MES_LOOP + 1;
    END;

    -------------------------------------------------------------------------
    -- Mayorizar HIS a cuentas padre (GENE no sube SALDO_INICIAL desde HIS sin APE)
    -------------------------------------------------------------------------
    MERGE #HIS_ACC AS T
    USING (
        SELECT P.CUENTA_CONTABLE,
               MAX(P.CLASE_RUBRO) AS CLASE_RUBRO,
               SUM(H.SALDO_INICIAL1) AS SALDO_INICIAL1,
               SUM(H.SALDO_INICIAL2) AS SALDO_INICIAL2,
               SUM(H.SALDO_INICIAL3) AS SALDO_INICIAL3,
               SUM(H.SALDO_INICIAL4) AS SALDO_INICIAL4,
               SUM(H.SALDO_INICIAL5) AS SALDO_INICIAL5,
               SUM(H.SALDO_INICIAL6) AS SALDO_INICIAL6,
               SUM(H.SALDO_INICIAL7) AS SALDO_INICIAL7,
               SUM(H.SALDO_INICIAL8) AS SALDO_INICIAL8,
               SUM(H.SALDO_INICIAL9) AS SALDO_INICIAL9,
               SUM(H.SALDO_INICIAL10) AS SALDO_INICIAL10,
               SUM(H.SALDO_INICIAL11) AS SALDO_INICIAL11,
               SUM(H.SALDO_INICIAL12) AS SALDO_INICIAL12
        FROM CON_CATALOGO_CUENTA P
        INNER JOIN #HIS_ACC H
            ON H.CUENTA_CONTABLE LIKE P.CUENTA_CONTABLE + '%' COLLATE Latin1_General_CS_AS
           AND H.CUENTA_CONTABLE <> P.CUENTA_CONTABLE
        INNER JOIN CON_CATALOGO_CUENTA HC
            ON HC.CORR_EMPRESA = @CORR_EMPRESA
           AND HC.CUENTA_CONTABLE = H.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
           AND HC.CUENTA_MAYOR = P.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
        WHERE P.CORR_EMPRESA = @CORR_EMPRESA
          AND P.NIVEL IN (1, 2)
        GROUP BY P.CUENTA_CONTABLE
    ) AS S
        ON T.CUENTA_CONTABLE = S.CUENTA_CONTABLE COLLATE Latin1_General_CS_AS
    WHEN MATCHED THEN
        UPDATE SET
            CLASE_RUBRO = ISNULL(T.CLASE_RUBRO, S.CLASE_RUBRO),
            SALDO_INICIAL1 = S.SALDO_INICIAL1,
            SALDO_INICIAL2 = S.SALDO_INICIAL2,
            SALDO_INICIAL3 = S.SALDO_INICIAL3,
            SALDO_INICIAL4 = S.SALDO_INICIAL4,
            SALDO_INICIAL5 = S.SALDO_INICIAL5,
            SALDO_INICIAL6 = S.SALDO_INICIAL6,
            SALDO_INICIAL7 = S.SALDO_INICIAL7,
            SALDO_INICIAL8 = S.SALDO_INICIAL8,
            SALDO_INICIAL9 = S.SALDO_INICIAL9,
            SALDO_INICIAL10 = S.SALDO_INICIAL10,
            SALDO_INICIAL11 = S.SALDO_INICIAL11,
            SALDO_INICIAL12 = S.SALDO_INICIAL12
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (
            CUENTA_CONTABLE, CLASE_RUBRO,
            SALDO_INICIAL1, SALDO_INICIAL2, SALDO_INICIAL3, SALDO_INICIAL4, SALDO_INICIAL5,
            SALDO_INICIAL6, SALDO_INICIAL7, SALDO_INICIAL8, SALDO_INICIAL9, SALDO_INICIAL10,
            SALDO_INICIAL11, SALDO_INICIAL12
        )
        VALUES (
            S.CUENTA_CONTABLE, S.CLASE_RUBRO,
            S.SALDO_INICIAL1, S.SALDO_INICIAL2, S.SALDO_INICIAL3, S.SALDO_INICIAL4, S.SALDO_INICIAL5,
            S.SALDO_INICIAL6, S.SALDO_INICIAL7, S.SALDO_INICIAL8, S.SALDO_INICIAL9, S.SALDO_INICIAL10,
            S.SALDO_INICIAL11, S.SALDO_INICIAL12
        );

    MERGE #HIS_ACC AS T
    USING (
        SELECT P.CUENTA_CONTABLE,
               MAX(P.CLASE_RUBRO) AS CLASE_RUBRO,
               SUM(H.SALDO_INICIAL1) AS SALDO_INICIAL1,
               SUM(H.SALDO_INICIAL2) AS SALDO_INICIAL2,
               SUM(H.SALDO_INICIAL3) AS SALDO_INICIAL3,
               SUM(H.SALDO_INICIAL4) AS SALDO_INICIAL4,
               SUM(H.SALDO_INICIAL5) AS SALDO_INICIAL5,
               SUM(H.SALDO_INICIAL6) AS SALDO_INICIAL6,
               SUM(H.SALDO_INICIAL7) AS SALDO_INICIAL7,
               SUM(H.SALDO_INICIAL8) AS SALDO_INICIAL8,
               SUM(H.SALDO_INICIAL9) AS SALDO_INICIAL9,
               SUM(H.SALDO_INICIAL10) AS SALDO_INICIAL10,
               SUM(H.SALDO_INICIAL11) AS SALDO_INICIAL11,
               SUM(H.SALDO_INICIAL12) AS SALDO_INICIAL12
        FROM CON_CATALOGO_CUENTA P
        INNER JOIN #HIS_ACC H
            ON H.CUENTA_CONTABLE <> P.CUENTA_CONTABLE COLLATE Latin1_General_CS_AS
        INNER JOIN CON_CATALOGO_CUENTA HC
            ON HC.CORR_EMPRESA = @CORR_EMPRESA
           AND HC.CUENTA_CONTABLE = H.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
           AND HC.CUENTA_MAYOR = P.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
        WHERE P.CORR_EMPRESA = @CORR_EMPRESA
          AND P.NIVEL = 1
        GROUP BY P.CUENTA_CONTABLE
    ) AS S
        ON T.CUENTA_CONTABLE = S.CUENTA_CONTABLE COLLATE Latin1_General_CS_AS
    WHEN MATCHED THEN
        UPDATE SET
            CLASE_RUBRO = ISNULL(T.CLASE_RUBRO, S.CLASE_RUBRO),
            SALDO_INICIAL1 = S.SALDO_INICIAL1,
            SALDO_INICIAL2 = S.SALDO_INICIAL2,
            SALDO_INICIAL3 = S.SALDO_INICIAL3,
            SALDO_INICIAL4 = S.SALDO_INICIAL4,
            SALDO_INICIAL5 = S.SALDO_INICIAL5,
            SALDO_INICIAL6 = S.SALDO_INICIAL6,
            SALDO_INICIAL7 = S.SALDO_INICIAL7,
            SALDO_INICIAL8 = S.SALDO_INICIAL8,
            SALDO_INICIAL9 = S.SALDO_INICIAL9,
            SALDO_INICIAL10 = S.SALDO_INICIAL10,
            SALDO_INICIAL11 = S.SALDO_INICIAL11,
            SALDO_INICIAL12 = S.SALDO_INICIAL12
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (
            CUENTA_CONTABLE, CLASE_RUBRO,
            SALDO_INICIAL1, SALDO_INICIAL2, SALDO_INICIAL3, SALDO_INICIAL4, SALDO_INICIAL5,
            SALDO_INICIAL6, SALDO_INICIAL7, SALDO_INICIAL8, SALDO_INICIAL9, SALDO_INICIAL10,
            SALDO_INICIAL11, SALDO_INICIAL12
        )
        VALUES (
            S.CUENTA_CONTABLE, S.CLASE_RUBRO,
            S.SALDO_INICIAL1, S.SALDO_INICIAL2, S.SALDO_INICIAL3, S.SALDO_INICIAL4, S.SALDO_INICIAL5,
            S.SALDO_INICIAL6, S.SALDO_INICIAL7, S.SALDO_INICIAL8, S.SALDO_INICIAL9, S.SALDO_INICIAL10,
            S.SALDO_INICIAL11, S.SALDO_INICIAL12
        );

    IF @MODO_U = 'PREVIEW'
    BEGIN
        SELECT @FECHA_CORTE AS FECHA_CORTE_ULTIMO_MES,
               @MES_CORTE AS MES_CORTE,
               COUNT(*) AS CUENTAS,
               SUM(CASE WHEN CLASE_RUBRO IN ('IN', 'GA') THEN 1 ELSE 0 END) AS CUENTAS_PYL,
               SUM(CASE WHEN CLASE_RUBRO IN ('AC', 'PA', 'PT') THEN 1 ELSE 0 END) AS CUENTAS_BALANCE
        FROM #HIS_ACC;

        SELECT TOP 100 * FROM #HIS_ACC ORDER BY CUENTA_CONTABLE;

        SELECT CUENTA_CONTABLE, SALDO_INICIAL5
        FROM #HIS_ACC
        WHERE ABS(SALDO_INICIAL5) > 0.01
        ORDER BY CUENTA_CONTABLE;

        SELECT @SYS_FILAS_AFECTADAS = @@ROWCOUNT;
        GOTO FINA;
    END;

    IF @MODO_U <> 'MIGRAR'
    BEGIN
        SELECT @SYS_NUMERO_ERROR = 30002,
               @SYS_MENSAJE_ERROR = N'Modo no valido. Use PREVIEW, MIGRAR o LIMPIAR.';
        GOTO FINA;
    END;

    IF EXISTS (
        SELECT 1
        FROM #HIS_ACC H
        LEFT JOIN CON_CATALOGO_CUENTA C
            ON C.CORR_EMPRESA = @CORR_EMPRESA
           AND C.CUENTA_CONTABLE = H.CUENTA_CONTABLE COLLATE DATABASE_DEFAULT
        WHERE C.CUENTA_CONTABLE IS NULL
    )
    BEGIN
        SELECT @SYS_NUMERO_ERROR = 30003,
               @SYS_MENSAJE_ERROR = N'Hay cuentas sin catalogo SGUEES.';
        GOTO FINA;
    END;

    BEGIN TRY
        BEGIN TRAN;

        DELETE FROM CON_CATALOGO_SALDO_HIS
        WHERE CORR_EMPRESA = @CORR_EMPRESA
          AND ANIO_PERIODO = @ANIO;

        INSERT INTO CON_CATALOGO_SALDO_HIS
        (
            CORR_EMPRESA, ANIO_PERIODO, CUENTA_CONTABLE,
            SALDO_INICIAL1, SALDO_INICIAL2, SALDO_INICIAL3, SALDO_INICIAL4, SALDO_INICIAL5,
            SALDO_INICIAL6, SALDO_INICIAL7, SALDO_INICIAL8, SALDO_INICIAL9, SALDO_INICIAL10,
            SALDO_INICIAL11, SALDO_INICIAL12, SALDO_FINAL12, CARGO_PERIODO, ABONO_PERIODO
        )
        SELECT @CORR_EMPRESA,
               @ANIO,
               CUENTA_CONTABLE,
               SALDO_INICIAL1, SALDO_INICIAL2, SALDO_INICIAL3, SALDO_INICIAL4, SALDO_INICIAL5,
               SALDO_INICIAL6, SALDO_INICIAL7, SALDO_INICIAL8, SALDO_INICIAL9, SALDO_INICIAL10,
               SALDO_INICIAL11, SALDO_INICIAL12,
               SALDO_INICIAL5,
               0,
               0
        FROM #HIS_ACC;

        SELECT @SYS_FILAS_AFECTADAS = @@ROWCOUNT,
               @SYS_MENSAJE_ERROR = N'Saldos historicos cargados: ' + CONVERT(VARCHAR(10), @@ROWCOUNT) + N' cuentas.';

        COMMIT TRAN;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRAN;
        SELECT @SYS_NUMERO_ERROR = ERROR_NUMBER(),
               @SYS_MENSAJE_ERROR = ERROR_MESSAGE();
    END CATCH;

FINA:
    IF @MODO_U IN ('MIGRAR', 'LIMPIAR') AND ISNULL(@SYS_NUMERO_ERROR, 0) <> 0
        SELECT @SYS_NUMERO_ERROR AS SYS_NUMERO_ERROR, @SYS_MENSAJE_ERROR AS SYS_MENSAJE_ERROR;
    ELSE IF @MODO_U = 'MIGRAR' AND ISNULL(@SYS_NUMERO_ERROR, 0) = 0
        SELECT @SYS_FILAS_AFECTADAS AS FILAS, @SYS_MENSAJE_ERROR AS MENSAJE;

    DROP TABLE IF EXISTS #HIS_ACC;
END;
GO

PRINT 'PRAL_MIGR_CLASS_SALDO_HISTORICO creado.';
GO
