/*
  PLA_TIPO_DOCUMENTO_ADJUNTO — tabla + vista (idempotente)
  Ejecutar:
    sqlcmd -S <srv> -d SGUEES -U <user> -P <pass> -f 65001 -i SGUEES-DB/Scripts/PLA_TIPO_DOCUMENTO_ADJUNTO.sql
*/

SET NOCOUNT ON;
GO

/* ========== TABLA ========== */
IF OBJECT_ID(N'dbo.PLA_TIPO_DOCUMENTO_ADJUNTO', N'U') IS NULL
BEGIN
  CREATE TABLE [dbo].[PLA_TIPO_DOCUMENTO_ADJUNTO] (
    [CORR_EMPRESA] [int] NOT NULL,
    [CORR_TIPO_DOCUMENTO_ADJUNTO] [int] NOT NULL,
    [TIPO_DOCUMENTO] [varchar](250) NULL,
    [DESCRIPCION_DOCUMENTO] [varchar](500) NULL,
    [USUARIO_CREA] [varchar](50) NULL,
    [ESTACION_CREA] [varchar](50) NULL,
    [FECHA_CREA] [datetime] NULL,
    [USUARIO_ACTU] [varchar](50) NULL,
    [ESTACION_ACTU] [varchar](50) NULL,
    [FECHA_ACTU] [datetime] NULL,
    CONSTRAINT [PK_PLA_TIPO_DOCUMENTO_ADJUNTO] PRIMARY KEY CLUSTERED (
      [CORR_EMPRESA],
      [CORR_TIPO_DOCUMENTO_ADJUNTO]
    )
  ) ON [PRIMARY];
END
GO

/* ========== VISTA ========== */
CREATE OR ALTER VIEW dbo.V_PLA_TIPO_DOCUMENTO_ADJUNTO
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_TIPO_DOCUMENTO_ADJUNTO,
    X.TIPO_DOCUMENTO,
    X.DESCRIPCION_DOCUMENTO,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.PLA_TIPO_DOCUMENTO_ADJUNTO AS X;
GO

PRINT N'PLA_TIPO_DOCUMENTO_ADJUNTO / V_PLA_TIPO_DOCUMENTO_ADJUNTO listos.';
GO
