SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

/* =============================================================================
   Procedimiento: dbo.PRAL_MTTO_SC_REQUISICION_PERSONAL_AUTORIZA
   Pantalla:      SC_REQUISICION_PERSONAL / sc-requisicion-personal

   Qué hace:
     Ejecuta una operación del flujo dla requisición de personal y sincroniza CORR_ESTADO_REQUISICION (1..5) con el motor SEG_FLUJO.

   Importante:
     - No edita el contenido dla requisición (persona, puestos, etc.).
     - Requiere tipo de documento activo con CODIGO_OPCION = SC_REQUISICION
       y un flujo defecto (misma estructura de niveles que SC_MOVIMIENTO_PERSONAL).
     - Unidad del circuito = puesto del creador (USUARIO_CREA), no CORR_UNIDAD del documento.

   @OPERACION:
     1 = GUARDAR   Queda en Borrador (1). Si es la primera vez, crea instancia.
     2 = ENVIAR    Borrador/Devuelto → En Aprobación (2).
     3 = APROBAR   N1 pasa a N2, N2 pasa a N3, N3 cierra en Aprobada (5 = Aprobado GG).
     4 = DEVOLVER  Retorna a Devuelta (3) en el nivel que actúa.
     5 = RECHAZAR  Finaliza en Rechazada JI/JU/GG (4).
     FECHA_APROBACION se setea al cerrar con Aprobado GG.

   Códigos RETURN: -1..-16 (-1..-16).

   Ejecutar:
     sqlcmd -S <servidor> -d SGUEES -U <user> -P <pass> -f 65001 -i PRAL_MTTO_SC_REQUISICION_PERSONAL_AUTORIZA.sql
   ============================================================================= */
CREATE OR ALTER PROCEDURE [dbo].[PRAL_MTTO_SC_REQUISICION_PERSONAL_AUTORIZA]
(
	@CORR_EMPRESA INT = 1,
	@CORR_REQUISICION_PERSONAL INT,
	@CORR_UNIDAD_DOCUMENTO INT = NULL,
	@OPERACION INT = NULL,
	@CORR_ACCION INT = NULL,
	@LOGIN_SISTEMA VARCHAR(30),
	@OBSERVACION NVARCHAR(MAX),
	@CORR_ESTADO INT OUTPUT,
	@MENSAJE_ERROR VARCHAR(500) OUTPUT,
	@CORR_ACCION_USADA INT = NULL OUTPUT,
	@CORR_PASO_ACTUAL INT = NULL OUTPUT,
	@MODO VARCHAR(20) = NULL OUTPUT,
	@NOMBRE_ESTADO VARCHAR(100) = NULL OUTPUT,
	@CORR_ESTADO_REQUISICION INT = NULL OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @CODIGO_OPCION VARCHAR(50) = 'SC_REQUISICION'
	DECLARE @EMPRESA INT = ISNULL(@CORR_EMPRESA, 1)
	DECLARE @ID_TIPO_DOCUMENTO INT
	DECLARE @ID_FLUJO INT
	DECLARE @ID_INSTANCIA INT
	DECLARE @ID_PASO_ACTUAL INT
	DECLARE @ID_ESTADO_ACTUAL INT
	DECLARE @ID_ACCION INT = @CORR_ACCION
	DECLARE @V_OPERACION INT = @OPERACION
	DECLARE @NOM_OP VARCHAR(20)
	DECLARE @ESTADO_TMP INT
	DECLARE @ERROR_TMP VARCHAR(500)
	DECLARE @ES_ESTADO_INICIAL BIT = 0
	DECLARE @ES_NUEVO BIT = 0
	DECLARE @ES_BORRADOR BIT = 0
	DECLARE @ES_FINAL BIT = 0
	DECLARE @ES_DEVUELTA BIT = 0
	DECLARE @V_MODO VARCHAR(20)
	DECLARE @ACCION_GUARDAR INT
	DECLARE @UNIDAD_DOC INT = @CORR_UNIDAD_DOCUMENTO
	DECLARE @V_NOMBRE_ESTADO VARCHAR(100)
	DECLARE @ES_FINAL_DESTINO BIT = 0
	DECLARE @EST_APROBADA INT
	DECLARE @EST_RECHAZADA INT
	DECLARE @EST_DEVUELTA INT
	DECLARE @PASO_INICIAL INT
	DECLARE @ESTADO_NEGOCIO INT
	DECLARE @LOGIN_DUENO VARCHAR(30)
	DECLARE @U INT
	DECLARE @D INT
	DECLARE @G INT
	DECLARE @NIVEL_U INT
	DECLARE @ACTIVO_U BIT
	DECLARE @TIENE_COORD BIT
	DECLARE @RUTA VARCHAR(20)
	DECLARE @PASO_CREAR INT
	DECLARE @PASO_N1 INT
	DECLARE @PASO_N2 INT
	DECLARE @PASO_N3 INT
	DECLARE @EST_JI INT
	DECLARE @EST_JU INT
	DECLARE @UNIDAD_MOTOR INT
	DECLARE @PASO_EJECUTADO INT
	DECLARE @NEXT_BIT INT
	DECLARE @FECHA_FIRMA DATETIME
	DECLARE @LOCK_RESULT INT

	SET @CORR_ESTADO = NULL
	SET @MENSAJE_ERROR = NULL
	SET @CORR_ACCION_USADA = NULL
	SET @CORR_PASO_ACTUAL = NULL
	SET @MODO = NULL
	SET @NOMBRE_ESTADO = NULL
	SET @CORR_ESTADO_REQUISICION = NULL

	IF @CORR_REQUISICION_PERSONAL IS NULL OR @CORR_REQUISICION_PERSONAL <= 0
	BEGIN
		SET @MENSAJE_ERROR = 'Debe indicar @CORR_REQUISICION_PERSONAL.'
		RETURN -1
	END

	IF NOT EXISTS (
		SELECT 1 FROM dbo.SC_REQUISICION_PERSONAL
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_REQUISICION_PERSONAL = @CORR_REQUISICION_PERSONAL
	)
	BEGIN
		SET @MENSAJE_ERROR = 'No existe la requisición CORR_REQUISICION_PERSONAL='
			+ CAST(@CORR_REQUISICION_PERSONAL AS VARCHAR) + '.'
		RETURN -1
	END

	IF @LOGIN_SISTEMA IS NULL OR LTRIM(RTRIM(@LOGIN_SISTEMA)) = ''
	BEGIN
		SET @MENSAJE_ERROR = 'Debe indicar @LOGIN_SISTEMA.'
		RETURN -1
	END

	IF @OBSERVACION IS NULL OR LTRIM(RTRIM(@OBSERVACION)) = ''
	BEGIN
		SET @OBSERVACION = CASE @V_OPERACION
			WHEN 1 THEN N'Se guardó la requisición en borrador.'
			WHEN 2 THEN N'Se envió la requisición de personal a aprobación.'
			WHEN 3 THEN N'Se aprobó la requisición.'
			WHEN 4 THEN N'Se devolvió la requisición.'
			WHEN 5 THEN N'Se rechazó la requisición.'
			ELSE N'Se registró una acción en el flujo de la requisición.'
		END
	END

	IF @ID_ACCION IS NULL AND @V_OPERACION IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'Indique @OPERACION (1=GUARDAR,2=ENVIAR,3=APROBAR,4=DEVOLVER,5=RECHAZAR) o @CORR_ACCION.'
		RETURN -1
	END

	IF @ID_ACCION IS NULL AND @V_OPERACION NOT IN (1, 2, 3, 4, 5)
	BEGIN
		SET @MENSAJE_ERROR = 'Operacion invalida: ' + CAST(ISNULL(@V_OPERACION, -1) AS VARCHAR)
			+ '. Use 1=GUARDAR, 2=ENVIAR, 3=APROBAR, 4=DEVOLVER, 5=RECHAZAR.'
		RETURN -5
	END

	SET @NOM_OP = CASE @V_OPERACION
		WHEN 1 THEN 'GUARDAR'
		WHEN 2 THEN 'ENVIAR'
		WHEN 3 THEN 'APROBAR'
		WHEN 4 THEN 'DEVOLVER'
		WHEN 5 THEN 'RECHAZAR'
		ELSE CAST(ISNULL(@V_OPERACION, 0) AS VARCHAR(10))
	END

	/* La API envía la unidad asignada al solicitante. No usar la unidad propuesta. */

	SELECT @ID_TIPO_DOCUMENTO = CORR_TIPO_DOCUMENTO
	FROM dbo.SEG_FLUJO_TIPO_DOCUMENTO
	WHERE CORR_EMPRESA = @EMPRESA AND CODIGO_OPCION = @CODIGO_OPCION AND ACTIVO = 1

	IF @ID_TIPO_DOCUMENTO IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'No existe tipo de documento activo para SC_REQUISICION. Configure SEG_FLUJO_TIPO_DOCUMENTO.'
		RETURN -2
	END

	SELECT TOP 1 @ID_FLUJO = CORR_FLUJO_PROCESO
	FROM dbo.SEG_FLUJO_PROCESO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND ACTIVO = 1 AND ES_DEFECTO = 1

	IF @ID_FLUJO IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'No hay flujo defecto activo para requisición de personal.'
		RETURN -3
	END

	/* Solo el cierre Aprobada / Aprobada GG. Aprobada JI no es final y no cuenta. */
	SELECT TOP 1 @EST_APROBADA = CORR_ESTADO
	FROM dbo.SEG_FLUJO_ESTADO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND ACTIVO = 1 AND ES_FINAL = 1
	  AND NOMBRE_ESTADO LIKE N'Aprobad%'
	ORDER BY CORR_ESTADO DESC

	SELECT TOP 1 @EST_RECHAZADA = CORR_ESTADO
	FROM dbo.SEG_FLUJO_ESTADO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND ACTIVO = 1 AND (NOMBRE_ESTADO LIKE N'Rechaz%' OR NOMBRE_ESTADO LIKE N'Deneg%')
	ORDER BY CORR_ESTADO

	SELECT TOP 1 @EST_DEVUELTA = CORR_ESTADO
	FROM dbo.SEG_FLUJO_ESTADO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND ACTIVO = 1 AND NOMBRE_ESTADO LIKE N'Devuel%'
	ORDER BY CORR_ESTADO

	SELECT TOP 1 @PASO_INICIAL = CORR_PASO
	FROM dbo.SEG_FLUJO_PASO
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
	ORDER BY ORDEN

	SELECT @ID_INSTANCIA = CORR_INSTANCIA,
	       @ID_PASO_ACTUAL = CORR_PASO_ACTUAL,
	       @ID_ESTADO_ACTUAL = CORR_ESTADO_ACTUAL
	FROM dbo.SEG_FLUJO_INSTANCIA
	WHERE CORR_EMPRESA = @EMPRESA
	  AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
	  AND CORR_DOCUMENTO = @CORR_REQUISICION_PERSONAL
	  AND ACTIVO = 1

	IF @ID_INSTANCIA IS NULL
	BEGIN
		SET @ES_NUEVO = 1
		SET @V_MODO = 'NUEVO'
		SET @ID_PASO_ACTUAL = @PASO_INICIAL
	END
	ELSE
	BEGIN
		SELECT @ES_ESTADO_INICIAL = ISNULL(E.ES_INICIAL, 0),
		       @ES_FINAL = ISNULL(E.ES_FINAL, 0),
		       @V_NOMBRE_ESTADO = E.NOMBRE_ESTADO
		FROM dbo.SEG_FLUJO_ESTADO E
		WHERE E.CORR_EMPRESA = @EMPRESA AND E.CORR_ESTADO = @ID_ESTADO_ACTUAL

		IF @EST_DEVUELTA IS NOT NULL AND @ID_ESTADO_ACTUAL = @EST_DEVUELTA
			SET @ES_DEVUELTA = 1
		ELSE IF @V_NOMBRE_ESTADO LIKE N'Devuel%'
			SET @ES_DEVUELTA = 1

		IF @ES_FINAL = 1
			SET @V_MODO = 'FINAL'
		ELSE IF @ES_ESTADO_INICIAL = 1 OR @ES_DEVUELTA = 1
		BEGIN
			SET @ES_BORRADOR = 1
			SET @V_MODO = 'BORRADOR'
		END
		ELSE
			SET @V_MODO = 'EN_FLUJO'
	END

	SET @MODO = @V_MODO
	SET @CORR_PASO_ACTUAL = @ID_PASO_ACTUAL

	IF @ID_PASO_ACTUAL IS NULL
	BEGIN
		SET @MENSAJE_ERROR = 'El flujo de requisición no tiene paso inicial configurado.'
		RETURN -4
	END

	IF @V_OPERACION IS NOT NULL AND @ID_ACCION IS NULL
	BEGIN
		IF @V_OPERACION = 1
		BEGIN
			IF @V_MODO NOT IN ('NUEVO', 'BORRADOR')
			BEGIN
				SET @MENSAJE_ERROR = 'GUARDAR(1) solo aplica en Borrador/NUEVO (modo actual: ' + @V_MODO + ').'
				RETURN -11
			END
			IF @ES_NUEVO = 1 AND (@UNIDAD_DOC IS NULL OR @UNIDAD_DOC <= 0)
			BEGIN
				SET @MENSAJE_ERROR = 'Al crear (GUARDAR=1) debe enviar @CORR_UNIDAD_DOCUMENTO (unidad asignada al solicitante).'
				RETURN -8
			END
		END
		ELSE IF @V_OPERACION = 2
		BEGIN
			IF @V_MODO NOT IN ('NUEVO', 'BORRADOR')
			BEGIN
				SET @MENSAJE_ERROR = 'ENVIAR(2) solo aplica en Borrador/Devuelto. Modo actual: ' + @V_MODO + '.'
				RETURN -12
			END
			IF @ES_NUEVO = 1 AND (@UNIDAD_DOC IS NULL OR @UNIDAD_DOC <= 0)
			BEGIN
				SET @MENSAJE_ERROR = 'Al crear y ENVIAR(2) debe enviar @CORR_UNIDAD_DOCUMENTO (unidad asignada al solicitante).'
				RETURN -8
			END
		END
		ELSE IF @V_OPERACION IN (3, 4, 5)
		BEGIN
			IF @ES_NUEVO = 1
			BEGIN
				SET @MENSAJE_ERROR = 'No hay instancia. Primero GUARDAR(1) o ENVIAR(2).'
				RETURN -13
			END
			IF @ES_BORRADOR = 1 AND @V_OPERACION = 3
			BEGIN
				SET @MENSAJE_ERROR = 'En Borrador use ENVIAR(2), no APROBAR(3).'
				RETURN -14
			END
			IF @V_MODO = 'FINAL'
			BEGIN
				SET @MENSAJE_ERROR = 'La requisición ya finalizo el flujo (modo FINAL).'
				RETURN -16
			END
		END
	END

	IF @ID_ACCION IS NULL
	BEGIN
		IF @V_OPERACION = 1
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 4
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION ASC
		ELSE IF @V_OPERACION = 2
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 1
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION DESC
		ELSE IF @V_OPERACION = 3
		BEGIN
			IF @EST_APROBADA IS NOT NULL
				SELECT TOP 1 @ID_ACCION = CORR_ACCION
				FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
				WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
				  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 3
				  AND CORR_ESTADO_DESTINO = @EST_APROBADA
				  AND PERMITIDO = 1 AND ACTIVO = 1
				ORDER BY CORR_ACCION ASC

			IF @ID_ACCION IS NULL
				SELECT TOP 1 @ID_ACCION = CORR_ACCION
				FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
				WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
				  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 1
				  AND PERMITIDO = 1 AND ACTIVO = 1
				ORDER BY CORR_ACCION ASC
		END
		ELSE IF @V_OPERACION = 4
			SELECT TOP 1 @ID_ACCION = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 2
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION ASC
		ELSE IF @V_OPERACION = 5
			SELECT TOP 1 @ID_ACCION = AE.CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO AS AE
			INNER JOIN dbo.SEG_FLUJO_ESTADO AS ED
				ON ED.CORR_EMPRESA = AE.CORR_EMPRESA AND ED.CORR_ESTADO = AE.CORR_ESTADO_DESTINO
			WHERE AE.CORR_EMPRESA = @EMPRESA AND AE.CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND AE.CORR_PASO = @ID_PASO_ACTUAL AND AE.CORR_TIPO_MOVIMIENTO = 3
			  AND (ED.NOMBRE_ESTADO LIKE N'Rechaz%' OR ED.NOMBRE_ESTADO LIKE N'Deneg%')
			  AND AE.PERMITIDO = 1 AND AE.ACTIVO = 1
			ORDER BY AE.CORR_ACCION ASC

		IF @ID_ACCION IS NULL
		BEGIN
			SET @MENSAJE_ERROR = 'No hay accion para operacion ' + @NOM_OP
				+ ' en paso ' + CAST(@ID_PASO_ACTUAL AS VARCHAR)
				+ ' (modo ' + @V_MODO + ').'
			RETURN -7
		END
	END

	SET @CORR_ACCION_USADA = @ID_ACCION
	SET @PASO_EJECUTADO = @ID_PASO_ACTUAL

	/* La ruta sale del puesto del creador del registro, no de CORR_UNIDAD del documento. */
	SET @LOGIN_DUENO = NULL
	SELECT @LOGIN_DUENO = USUARIO_CREA
	FROM dbo.SC_REQUISICION_PERSONAL
	WHERE CORR_EMPRESA = @EMPRESA AND CORR_REQUISICION_PERSONAL = @CORR_REQUISICION_PERSONAL
	IF @LOGIN_DUENO IS NULL OR LTRIM(RTRIM(@LOGIN_DUENO)) = ''
	BEGIN
		IF @ID_INSTANCIA IS NOT NULL
			SELECT @LOGIN_DUENO = USUARIO_CREA
			FROM dbo.SEG_FLUJO_INSTANCIA
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA
	END
	IF @LOGIN_DUENO IS NULL OR LTRIM(RTRIM(@LOGIN_DUENO)) = ''
		SET @LOGIN_DUENO = @LOGIN_SISTEMA

	SELECT TOP 1
		@U = EP.CORR_UNIDAD,
		@NIVEL_U = UN.CORR_NIVEL,
		@ACTIVO_U = UN.ACTIVO
	FROM dbo.GEN_PERSONA_USUARIO AS PU
	INNER JOIN dbo.GEN_EMPLEADO AS E
		ON E.CORR_PERSONA = PU.CORR_PERSONA AND E.CORR_EMPRESA = @EMPRESA
	INNER JOIN dbo.GEN_EMPLEADO_PUESTO AS EP
		ON EP.CORR_EMPRESA = E.CORR_EMPRESA AND EP.CORR_EMPLEADO = E.CORR_EMPLEADO
	INNER JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES AS UN
		ON UN.CORR_EMPRESA = EP.CORR_EMPRESA AND UN.CORR_UNIDAD = EP.CORR_UNIDAD
	WHERE LTRIM(RTRIM(PU.LOGIN_SISTEMA)) = LTRIM(RTRIM(@LOGIN_DUENO))
	ORDER BY CASE WHEN UN.ACTIVO = 1 THEN 0 ELSE 1 END, UN.CORR_NIVEL DESC, EP.CORR_UNIDAD DESC

	IF ISNULL(@U, 0) <= 0 AND ISNULL(@UNIDAD_DOC, 0) > 0
		SET @U = @UNIDAD_DOC

	IF @V_OPERACION IN (2, 3, 4, 5) AND ISNULL(@U, 0) <= 0
	BEGIN
		SET @MENSAJE_ERROR = 'No se encontró la unidad del puesto del solicitante.'
		RETURN -8
	END

	IF @V_OPERACION IN (2, 3, 4, 5)
	BEGIN
		;WITH CADENA AS (
			SELECT CORR_UNIDAD, CORR_UNIDAD_PADRE, CORR_NIVEL
			FROM dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_UNIDAD = @U
			UNION ALL
			SELECT P.CORR_UNIDAD, P.CORR_UNIDAD_PADRE, P.CORR_NIVEL
			FROM dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES AS P
			INNER JOIN CADENA AS C
				ON P.CORR_EMPRESA = @EMPRESA AND P.CORR_UNIDAD = C.CORR_UNIDAD_PADRE
		)
		SELECT
			@G = MAX(CASE WHEN CORR_NIVEL = 3 THEN CORR_UNIDAD END),
			@D = MAX(CASE WHEN CORR_NIVEL = 4 THEN CORR_UNIDAD END)
		FROM CADENA
		OPTION (MAXRECURSION 20)

		SET @TIENE_COORD = 0
		IF @D IS NOT NULL AND EXISTS (
			SELECT 1
			FROM dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES
			WHERE CORR_EMPRESA = @EMPRESA
			  AND CORR_UNIDAD_PADRE = @D
			  AND ACTIVO = 1
		)
			SET @TIENE_COORD = 1

		IF @NIVEL_U > 4 AND ISNULL(@ACTIVO_U, 0) = 1 AND @D IS NOT NULL
			SET @RUTA = 'COORD'
		ELSE IF @D IS NOT NULL AND @NIVEL_U = 4 AND @TIENE_COORD = 1
			SET @RUTA = 'DIRECTO'
		ELSE IF @D IS NOT NULL
			SET @RUTA = 'SIN_COORD'
		ELSE IF @G IS NOT NULL
			SET @RUTA = 'DIRECTO'
		ELSE
		BEGIN
			SET @MENSAJE_ERROR = 'No se encontró el nivel 3 (CORR_NIVEL = 3) sobre la unidad del puesto.'
			RETURN -8
		END

		SELECT @PASO_CREAR = CORR_PASO FROM dbo.SEG_FLUJO_PASO WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO AND ORDEN = 1
		SELECT @PASO_N1 = CORR_PASO FROM dbo.SEG_FLUJO_PASO WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO AND ORDEN = 2
		SELECT @PASO_N2 = CORR_PASO FROM dbo.SEG_FLUJO_PASO WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO AND ORDEN = 3
		SELECT @PASO_N3 = CORR_PASO FROM dbo.SEG_FLUJO_PASO WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO AND ORDEN = 4
		SELECT @EST_JI = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO AND NOMBRE_ESTADO = N'Aprobado JI'
		SELECT @EST_JU = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMPRESA AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO AND NOMBRE_ESTADO = N'Aprobado JU'

		IF @PASO_N1 IS NULL OR @PASO_N2 IS NULL OR @PASO_N3 IS NULL OR @EST_JI IS NULL OR @EST_JU IS NULL
		BEGIN
			SET @MENSAJE_ERROR = 'El flujo de requisición no tiene los tres niveles configurados.'
			RETURN -4
		END
	END

	SET @UNIDAD_MOTOR = CASE
		WHEN @ID_PASO_ACTUAL = @PASO_N3 THEN @G
		WHEN @ID_PASO_ACTUAL = @PASO_N2 AND @RUTA = 'SIN_COORD' THEN @D
		WHEN ISNULL(@ACTIVO_U, 0) = 0 AND @RUTA <> 'COORD' AND @D IS NOT NULL THEN @D
		ELSE @U
	END
	IF ISNULL(@UNIDAD_MOTOR, 0) <= 0 SET @UNIDAD_MOTOR = @U

	BEGIN TRY
		BEGIN TRAN

		IF @V_OPERACION IN (2, 3, 4, 5)
		BEGIN
			EXEC @LOCK_RESULT = sp_getapplock
				@Resource = 'SGUEES_FLUJO_101_REQUISICION',
				@LockMode = 'Exclusive',
				@LockOwner = 'Transaction',
				@LockTimeout = 15000
			IF @LOCK_RESULT < 0
			BEGIN
				ROLLBACK TRAN
				SET @MENSAJE_ERROR = 'El flujo de requisición está ocupado. Intente de nuevo.'
				RETURN -10
			END

			UPDATE dbo.SEG_FLUJO_PASO
			SET CORR_ACTOR_DESTINO = 2,
				CORR_UNIDAD_DESTINO = CASE WHEN @RUTA = 'COORD' THEN @U ELSE @D END
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_PASO = @PASO_CREAR

			UPDATE dbo.SEG_FLUJO_PASO
			SET CORR_ACTOR_DESTINO = 2,
				CORR_UNIDAD_DESTINO = @D
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_PASO = @PASO_N1

			UPDATE dbo.SEG_FLUJO_PASO
			SET CORR_ACTOR_DESTINO = 2,
				CORR_UNIDAD_DESTINO = @G,
				CORR_ACTOR_ORIGEN = CASE
					WHEN @RUTA = 'SIN_COORD' AND @PASO_EJECUTADO = @PASO_N2 THEN 2
					ELSE 3
				END
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_PASO = @PASO_N2

			IF @RUTA = 'DIRECTO' AND @V_OPERACION = 2
				UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO
				SET CORR_TIPO_NOTIFICACION = 5
				WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
				  AND CORR_PASO = @PASO_CREAR AND CORR_TIPO_MOVIMIENTO = 1 AND ACTIVO = 1
		END

		IF @ID_INSTANCIA IS NOT NULL AND @V_MODO = 'BORRADOR' AND ISNULL(@UNIDAD_MOTOR, 0) > 0
			UPDATE dbo.SEG_FLUJO_INSTANCIA
			SET CORR_UNIDAD_DOCUMENTO = @UNIDAD_MOTOR,
				USUARIO_ACTU = @LOGIN_SISTEMA,
				FECHA_ACTU = GETDATE()
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA

		IF @ES_NUEVO = 1 AND @V_OPERACION = 2
		BEGIN
			SELECT TOP 1 @ACCION_GUARDAR = CORR_ACCION
			FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @ID_PASO_ACTUAL AND CORR_TIPO_MOVIMIENTO = 4
			  AND PERMITIDO = 1 AND ACTIVO = 1
			ORDER BY CORR_ACCION ASC

			IF @ACCION_GUARDAR IS NULL SET @ACCION_GUARDAR = 1

			EXEC dbo.EjecutarFlujoProceso
				@i_CORR_EMPRESA = @EMPRESA,
				@i_CODIGO_OPCION = @CODIGO_OPCION,
				@i_idDocumento = @CORR_REQUISICION_PERSONAL,
				@i_idUnidadDocumento = @UNIDAD_MOTOR,
				@i_idAccion = @ACCION_GUARDAR,
				@i_login = @LOGIN_SISTEMA,
				@i_Observacion = N'La requisición de personal está en borrador.',
				@o_idEstadoDocumento = @ESTADO_TMP OUTPUT,
				@o_Error = @ERROR_TMP OUTPUT

			IF @ERROR_TMP IS NOT NULL
			BEGIN
				IF @@TRANCOUNT > 0 ROLLBACK TRAN
				SET @MENSAJE_ERROR = 'Error al crear (GUARDAR) previo a ENVIAR: ' + @ERROR_TMP
				RETURN -9
			END
		END

		EXEC dbo.EjecutarFlujoProceso
			@i_CORR_EMPRESA = @EMPRESA,
			@i_CODIGO_OPCION = @CODIGO_OPCION,
			@i_idDocumento = @CORR_REQUISICION_PERSONAL,
			@i_idUnidadDocumento = @UNIDAD_MOTOR,
			@i_idAccion = @ID_ACCION,
			@i_login = @LOGIN_SISTEMA,
			@i_Observacion = @OBSERVACION,
			@o_idEstadoDocumento = @CORR_ESTADO OUTPUT,
			@o_Error = @MENSAJE_ERROR OUTPUT

		IF @MENSAJE_ERROR IS NOT NULL
		BEGIN
			IF @@TRANCOUNT > 0 ROLLBACK TRAN
			RETURN -10
		END

		SELECT @ID_INSTANCIA = CORR_INSTANCIA,
		       @ID_PASO_ACTUAL = CORR_PASO_ACTUAL,
		       @ID_ESTADO_ACTUAL = CORR_ESTADO_ACTUAL
		FROM dbo.SEG_FLUJO_INSTANCIA
		WHERE CORR_EMPRESA = @EMPRESA
		  AND CORR_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
		  AND CORR_DOCUMENTO = @CORR_REQUISICION_PERSONAL
		  AND ACTIVO = 1

		IF @V_OPERACION = 2 AND @RUTA = 'DIRECTO' AND @ID_INSTANCIA IS NOT NULL
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM dbo.SEG_FLUJO_BITACORA
				WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA
				  AND CORR_PASO = @PASO_N1 AND CORR_ESTADO_NUEVO = @EST_JI
			)
			BEGIN
				SELECT @NEXT_BIT = ISNULL(MAX(CORR_BITACORA), 0) + 1
				FROM dbo.SEG_FLUJO_BITACORA WHERE CORR_EMPRESA = @EMPRESA
				INSERT INTO dbo.SEG_FLUJO_BITACORA (
					CORR_EMPRESA, CORR_BITACORA, CORR_INSTANCIA, CORR_PASO, TIPO_USUARIO,
					LOGIN_SISTEMA, COMENTARIO, CORR_ESTADO_ANTERIOR, CORR_ESTADO_NUEVO,
					CORR_UNIDAD_EJECUTOR, FECHA_ACCION, USUARIO_CREA, ESTACION_CREA, FECHA_CREA
				) VALUES (
					@EMPRESA, @NEXT_BIT, @ID_INSTANCIA, @PASO_N1, 2,
					@LOGIN_SISTEMA,
					N'[AUTO] Nivel 1 aprobado: el puesto está en la unidad del departamento. ' + @OBSERVACION,
					@ID_ESTADO_ACTUAL, @EST_JI,
					ISNULL(@D, @U), DATEADD(SECOND, -2, GETDATE()), @LOGIN_SISTEMA, 'SP_REQUISICION', GETDATE()
				)
			END

			IF NOT EXISTS (
				SELECT 1 FROM dbo.SEG_FLUJO_BITACORA
				WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA
				  AND CORR_PASO = @PASO_N2 AND CORR_ESTADO_NUEVO = @EST_JU
			)
			BEGIN
				SELECT @NEXT_BIT = ISNULL(MAX(CORR_BITACORA), 0) + 1
				FROM dbo.SEG_FLUJO_BITACORA WHERE CORR_EMPRESA = @EMPRESA
				INSERT INTO dbo.SEG_FLUJO_BITACORA (
					CORR_EMPRESA, CORR_BITACORA, CORR_INSTANCIA, CORR_PASO, TIPO_USUARIO,
					LOGIN_SISTEMA, COMENTARIO, CORR_ESTADO_ANTERIOR, CORR_ESTADO_NUEVO,
					CORR_UNIDAD_EJECUTOR, FECHA_ACCION, USUARIO_CREA, ESTACION_CREA, FECHA_CREA
				) VALUES (
					@EMPRESA, @NEXT_BIT, @ID_INSTANCIA, @PASO_N2, 2,
					@LOGIN_SISTEMA,
					N'[AUTO] Nivel 2 aprobado: el puesto está en la unidad del departamento. ' + @OBSERVACION,
					@EST_JI, @EST_JU,
					ISNULL(@D, @U), DATEADD(SECOND, -1, GETDATE()), @LOGIN_SISTEMA, 'SP_REQUISICION', GETDATE()
				)
			END

			UPDATE dbo.SEG_FLUJO_NOTIFICACION
			SET PROCESADO = 1, USUARIO_ACTU = @LOGIN_SISTEMA, FECHA_ACTU = GETDATE()
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA AND ISNULL(PROCESADO, 0) = 0

			UPDATE dbo.SEG_FLUJO_INSTANCIA
			SET CORR_PASO_ACTUAL = @PASO_N3,
				CORR_ESTADO_ACTUAL = @EST_JU,
				USUARIO_ACTU = @LOGIN_SISTEMA,
				FECHA_ACTU = GETDATE()
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA

			SET @CORR_ESTADO = @EST_JU
			SET @ID_PASO_ACTUAL = @PASO_N3

			IF NOT EXISTS (
				SELECT 1 FROM dbo.SEG_FN_ObtenerJefesDeUnidad(@G) WHERE LoginDestino IS NOT NULL
			)
			BEGIN
				ROLLBACK TRAN
				SET @MENSAJE_ERROR = 'No se encontraron destinatarios para el nivel 3.'
				RETURN -10
			END

			SELECT @NEXT_BIT = ISNULL(MAX(CORR_NOTIFICACION), 0)
			FROM dbo.SEG_FLUJO_NOTIFICACION WHERE CORR_EMPRESA = @EMPRESA

			INSERT INTO dbo.SEG_FLUJO_NOTIFICACION (
				CORR_EMPRESA, CORR_NOTIFICACION, CORR_INSTANCIA, CORR_PASO,
				LOGIN_SISTEMA_DESTINO, LOGIN_SISTEMA_ORIGEN, MENSAJE, URL,
				LEIDA, PROCESADO, FECHA_ENVIO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA
			)
			SELECT
				@EMPRESA,
				@NEXT_BIT + ROW_NUMBER() OVER (ORDER BY J.LoginDestino),
				@ID_INSTANCIA, @PASO_N3,
				J.LoginDestino, @LOGIN_SISTEMA, N'Tarea pendiente en el flujo.',
				N'/sc-requisicion-personal?corr=' + CAST(@CORR_REQUISICION_PERSONAL AS VARCHAR(20)),
				0, 0, GETDATE(), @LOGIN_SISTEMA, 'SP_REQUISICION', GETDATE()
			FROM dbo.SEG_FN_ObtenerJefesDeUnidad(@G) AS J
			WHERE J.LoginDestino IS NOT NULL
		END

		IF @V_OPERACION = 2 AND @RUTA = 'SIN_COORD' AND @ID_INSTANCIA IS NOT NULL AND @ID_PASO_ACTUAL = @PASO_N1
		BEGIN
			UPDATE dbo.SEG_FLUJO_INSTANCIA
			SET CORR_PASO_ACTUAL = @PASO_N2,
				CORR_ESTADO_ACTUAL = @EST_JI,
				USUARIO_ACTU = @LOGIN_SISTEMA,
				FECHA_ACTU = GETDATE()
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA

			UPDATE dbo.SEG_FLUJO_NOTIFICACION
			SET CORR_PASO = @PASO_N2
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA
			  AND CORR_PASO = @PASO_N1 AND ISNULL(PROCESADO, 0) = 0

			SET @CORR_ESTADO = @EST_JI
			SET @ID_PASO_ACTUAL = @PASO_N2
		END

		IF @V_OPERACION = 3 AND @RUTA = 'SIN_COORD' AND @PASO_EJECUTADO = @PASO_N2 AND @ID_INSTANCIA IS NOT NULL
		   AND NOT EXISTS (
				SELECT 1 FROM dbo.SEG_FLUJO_BITACORA
				WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA
				  AND CORR_PASO = @PASO_N1 AND CORR_ESTADO_NUEVO = @EST_JI
		   )
		BEGIN
			SELECT @FECHA_FIRMA = MIN(FECHA_ACCION)
			FROM dbo.SEG_FLUJO_BITACORA
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA
			  AND CORR_PASO = @PASO_N2 AND CORR_ESTADO_NUEVO = @EST_JU

			SELECT @NEXT_BIT = ISNULL(MAX(CORR_BITACORA), 0) + 1
			FROM dbo.SEG_FLUJO_BITACORA WHERE CORR_EMPRESA = @EMPRESA

			INSERT INTO dbo.SEG_FLUJO_BITACORA (
				CORR_EMPRESA, CORR_BITACORA, CORR_INSTANCIA, CORR_PASO, TIPO_USUARIO,
				LOGIN_SISTEMA, COMENTARIO, CORR_ESTADO_ANTERIOR, CORR_ESTADO_NUEVO,
				CORR_UNIDAD_EJECUTOR, FECHA_ACCION, USUARIO_CREA, ESTACION_CREA, FECHA_CREA
			) VALUES (
				@EMPRESA, @NEXT_BIT, @ID_INSTANCIA, @PASO_N1, 2,
				@LOGIN_SISTEMA, @OBSERVACION,
				NULL, @EST_JI,
				ISNULL(@D, @U), DATEADD(SECOND, -1, ISNULL(@FECHA_FIRMA, GETDATE())),
				@LOGIN_SISTEMA, 'SP_REQUISICION', GETDATE()
			)
		END

		IF @V_OPERACION IN (2, 3, 4, 5)
		BEGIN
			UPDATE dbo.SEG_FLUJO_PASO
			SET CORR_UNIDAD_DESTINO = NULL,
				CORR_ACTOR_DESTINO = 2
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_PASO IN (@PASO_CREAR, @PASO_N1)

			UPDATE dbo.SEG_FLUJO_PASO
			SET CORR_UNIDAD_DESTINO = NULL,
				CORR_ACTOR_DESTINO = 2,
				CORR_ACTOR_ORIGEN = 3
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_PASO = @PASO_N2

			UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO
			SET CORR_TIPO_NOTIFICACION = 2
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_FLUJO_PROCESO = @ID_FLUJO
			  AND CORR_PASO = @PASO_CREAR AND CORR_TIPO_MOVIMIENTO = 1 AND ACTIVO = 1
		END

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		IF XACT_STATE() <> 0 ROLLBACK TRAN
		IF @MENSAJE_ERROR IS NULL OR LTRIM(RTRIM(@MENSAJE_ERROR)) = ''
			SET @MENSAJE_ERROR = ERROR_MESSAGE()
		RETURN -10
	END CATCH

	IF @ID_INSTANCIA IS NOT NULL
	BEGIN
		SELECT @CORR_ESTADO = CORR_ESTADO_ACTUAL,
		       @CORR_PASO_ACTUAL = CORR_PASO_ACTUAL
		FROM dbo.SEG_FLUJO_INSTANCIA
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA AND ACTIVO = 1

		IF @CORR_ESTADO IS NULL
			SELECT @CORR_ESTADO = CORR_ESTADO_ACTUAL
			FROM dbo.SEG_FLUJO_INSTANCIA
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_INSTANCIA = @ID_INSTANCIA
	END

	IF @CORR_ESTADO IS NOT NULL
	BEGIN
		SELECT @V_NOMBRE_ESTADO = LEFT(NOMBRE_ESTADO, 100),
		       @ES_FINAL_DESTINO = ISNULL(ES_FINAL, 0)
		FROM dbo.SEG_FLUJO_ESTADO
		WHERE CORR_EMPRESA = @EMPRESA AND CORR_ESTADO = @CORR_ESTADO

		/* 1 Borrador | 2 En Aprobación (Aprobado JI/JU) | 3 Devuelta* | 4 Rechazada* | 5 Aprobado GG */
		SET @ESTADO_NEGOCIO = CASE
			WHEN @V_NOMBRE_ESTADO LIKE N'Rechaz%' OR @V_NOMBRE_ESTADO LIKE N'Deneg%' THEN 4
			WHEN @V_NOMBRE_ESTADO LIKE N'Devuel%' THEN 3
			WHEN @V_NOMBRE_ESTADO LIKE N'Borrador%' OR @V_NOMBRE_ESTADO LIKE N'Digit%' THEN 1
			WHEN @V_NOMBRE_ESTADO LIKE N'Aprobad%' AND @ES_FINAL_DESTINO = 1 THEN 5
			WHEN @V_NOMBRE_ESTADO LIKE N'%Aprobaci%'
			  OR @V_NOMBRE_ESTADO LIKE N'Solicit%'
			  OR @V_NOMBRE_ESTADO LIKE N'Aprobad%' THEN 2
			ELSE NULL
		END

		IF @ESTADO_NEGOCIO IS NULL
		BEGIN
			SELECT @ESTADO_NEGOCIO = CASE
				WHEN ES_FINAL = 1 AND @CORR_ESTADO = @EST_APROBADA THEN 5
				WHEN ES_FINAL = 1 THEN 4
				WHEN ES_INICIAL = 1 THEN 1
				ELSE 2
			END
			FROM dbo.SEG_FLUJO_ESTADO
			WHERE CORR_EMPRESA = @EMPRESA AND CORR_ESTADO = @CORR_ESTADO
		END

		UPDATE dbo.SC_REQUISICION_PERSONAL
		SET CORR_ESTADO_REQUISICION = @ESTADO_NEGOCIO,
			FECHA_APROBACION = CASE
				WHEN @ESTADO_NEGOCIO = 5 THEN CAST(GETDATE() AS DATE)
				ELSE FECHA_APROBACION
			END,
			USUARIO_ACTU = @LOGIN_SISTEMA,
			ESTACION_ACTU = HOST_NAME(),
			FECHA_ACTU = GETDATE()
		WHERE CORR_EMPRESA = @EMPRESA
		  AND CORR_REQUISICION_PERSONAL = @CORR_REQUISICION_PERSONAL

		SET @NOMBRE_ESTADO = @V_NOMBRE_ESTADO
		SET @CORR_ESTADO_REQUISICION = @ESTADO_NEGOCIO
	END

	RETURN 0
END

GO
PRINT N'OK: PRAL_MTTO_SC_REQUISICION_PERSONAL_AUTORIZA.';
GO