/*
  Preparación esquema SGUEES antes de migrar datos COM_* desde 129/SUEES.
  Solo modifica objetos en SGUEES (250). No toca el servidor 129.
*/
SET NOCOUNT ON;
GO

PRINT N'=== PREP migración Compras ===';

IF OBJECT_ID(N'dbo.COM_TIPO_DOC_FISICO', N'U') IS NULL
BEGIN
	PRINT N'Creando COM_TIPO_DOC_FISICO...';
	CREATE TABLE [dbo].[COM_TIPO_DOC_FISICO]
	(
		[CORR_EMPRESA] [int] NOT NULL,
		[CORR_TIPO_DOCUMENTO] [int] NOT NULL,
		[NOMBRE_TIPO_DOCUMENTO] [varchar](150) COLLATE Latin1_General_CS_AS NOT NULL,
		[NOMBRE_CORTO_TIPO_DOC] [varchar](50) COLLATE Latin1_General_CS_AS NOT NULL,
		[USUARIO_CREA] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
		[FECHA_CREA] [datetime] NOT NULL,
		[ESTACION_CREA] [varchar](50) COLLATE Latin1_General_CS_AS NOT NULL,
		[USUARIO_ACTU] [varchar](30) COLLATE Latin1_General_CS_AS NULL,
		[FECHA_ACTU] [datetime] NULL,
		[ESTACION_ACTU] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
		CONSTRAINT [PK_COM_TIPO_DOC_FISICO_COM] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_DOCUMENTO])
	);
END
GO

IF OBJECT_ID(N'dbo.CLA_COM_PROVEEDOR_SECTOR', N'U') IS NULL
BEGIN
	PRINT N'Creando CLA_COM_PROVEEDOR_SECTOR...';
	CREATE TABLE [dbo].[CLA_COM_PROVEEDOR_SECTOR]
	(
		[CORR_PROVEEDOR] [int] NOT NULL,
		[CORR_SECTOR] [int] NOT NULL,
		CONSTRAINT [PK_CLA_COM_PROVEEDOR_SECTOR] PRIMARY KEY CLUSTERED ([CORR_PROVEEDOR])
	);
END
GO

IF EXISTS (
	SELECT 1
	FROM sys.columns
	WHERE object_id = OBJECT_ID(N'dbo.COM_PROVEEDOR')
	  AND name = N'CORR_ACTIVIDAD_ECONOMICA'
	  AND system_type_id = 56
)
BEGIN
	PRINT N'Alter COM_PROVEEDOR.CORR_ACTIVIDAD_ECONOMICA -> varchar(10)...';
	ALTER TABLE dbo.COM_PROVEEDOR
	ALTER COLUMN CORR_ACTIVIDAD_ECONOMICA varchar(10) NOT NULL;
END
GO

IF OBJECT_ID(N'dbo.V_GEN_SECTOR', N'V') IS NOT NULL
	DROP VIEW dbo.V_GEN_SECTOR;
GO

CREATE VIEW dbo.V_GEN_SECTOR
AS
SELECT A.CORR_SECTOR, A.NOMBRE_SECTOR
FROM [EADMINFE].[e-AdminFE].dbo.GEN_SECTOR A
WHERE A.ESTADO_SECTOR = 'AC';
GO

PRINT N'=== PREP completado ===';
GO
