/*
  Recarga datos CLASS -> SGUEES (uso repetible).

  Que hace:
    1. Despliega SP/funciones de reportes y migracion (idempotente)
    2. LIMPIAR + MIGRAR CON_CATALOGO_SALDO_HIS desde CLASS
    3. Opcional: LIMPIAR + MIGRAR + APLICAR partidas del mes

  Requisitos:
    - Linked server CLASS_UEES activo
    - Ejecutar desde esta carpeta (Scripts) para que funcionen los :r

  Uso habitual (solo saldos historicos, ~4 min):
    cd "c:\Desarrollo GIT\SGUEES\SGUEES-DB\Scripts"
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -v ANIO=2026 -v MES_CORTE=4 -v RECARGAR_PARTIDAS=0 -i RECARGA_CLASS_SGUEES.sql

  Uso completo (HIS + partidas mayo, mas lento):
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -v ANIO=2026 -v MES_CORTE=4 -v MES_PARTIDAS=5 -v RECARGAR_PARTIDAS=1 -i RECARGA_CLASS_SGUEES.sql

  Reportes: FECHA_FINAL = ultimo dia del mes migrado (ej. 2026-05-31).
*/
SET NOCOUNT ON;

DECLARE @ANIO INT = TRY_CONVERT(INT, '$(ANIO)');
DECLARE @MES_CORTE INT = TRY_CONVERT(INT, '$(MES_CORTE)');
DECLARE @MES_PARTIDAS INT = TRY_CONVERT(INT, '$(MES_PARTIDAS)');
DECLARE @RECARGAR_PARTIDAS INT = TRY_CONVERT(INT, '$(RECARGAR_PARTIDAS)');
DECLARE @E NUMERIC(38, 0);
DECLARE @M NVARCHAR(4000);
DECLARE @F INT;

IF @ANIO IS NULL SET @ANIO = 2026;
IF @MES_CORTE IS NULL SET @MES_CORTE = 4;
IF @MES_PARTIDAS IS NULL SET @MES_PARTIDAS = 5;
IF @RECARGAR_PARTIDAS IS NULL SET @RECARGAR_PARTIDAS = 0;

PRINT '=== RECARGA CLASS -> SGUEES ===';
PRINT 'Anio: ' + CAST(@ANIO AS VARCHAR(4))
    + ' | HIS hasta mes: ' + CAST(@MES_CORTE AS VARCHAR(2))
    + ' | Partidas mes: ' + CASE WHEN @RECARGAR_PARTIDAS = 1 THEN CAST(@MES_PARTIDAS AS VARCHAR(2)) ELSE 'NO' END;
GO

PRINT '=== 1. Objetos SQL (parametros, SP balance, SP HIS) ===';
GO
:r SETUP_CON_PARAMETRO.sql
GO
:r FIX_CLASE_RUBRO_CATALOGO.sql
GO
:r FIX_BALANCE_PATRIMONIO_CLASS.sql
GO
:r MIGRATE_CLASS_SALDO_HISTORICO.sql
GO
:r IMPORT_CLASS_CENTRO_COSTO_REL.sql
GO
:r MIGRATE_CLASS_PARTIDAS_MES.sql
GO

DECLARE @ANIO INT = TRY_CONVERT(INT, '$(ANIO)');
DECLARE @MES_CORTE INT = TRY_CONVERT(INT, '$(MES_CORTE)');
DECLARE @MES_PARTIDAS INT = TRY_CONVERT(INT, '$(MES_PARTIDAS)');
DECLARE @RECARGAR_PARTIDAS INT = TRY_CONVERT(INT, '$(RECARGAR_PARTIDAS)');
DECLARE @E NUMERIC(38, 0);
DECLARE @M NVARCHAR(4000);
DECLARE @F INT;

IF @ANIO IS NULL SET @ANIO = 2026;
IF @MES_CORTE IS NULL SET @MES_CORTE = 4;
IF @MES_PARTIDAS IS NULL SET @MES_PARTIDAS = 5;
IF @RECARGAR_PARTIDAS IS NULL SET @RECARGAR_PARTIDAS = 0;

PRINT '=== 2. Limpiar resultado periodo en HIS (3106/3108) ===';
DELETE FROM CON_CATALOGO_SALDO_HIS
WHERE CORR_EMPRESA = 1
  AND ANIO_PERIODO = @ANIO
  AND (
        LEFT(CUENTA_CONTABLE, 4) IN ('3106', '3108')
     OR CUENTA_CONTABLE IN ('3106', '3108', '310601', '310801')
  );
PRINT CAST(@@ROWCOUNT AS VARCHAR(10)) + ' filas eliminadas (patrimonio periodo en HIS).';

PRINT '=== 3. CON_CATALOGO_SALDO_HIS: LIMPIAR + MIGRAR ===';
EXEC dbo.PRAL_MIGR_CLASS_SALDO_HISTORICO
    @ANIO = @ANIO, @MES_CORTE = @MES_CORTE, @CIERRE = 0, @MODO = 'LIMPIAR',
    @SYS_NUMERO_ERROR = @E OUTPUT, @SYS_MENSAJE_ERROR = @M OUTPUT;

EXEC dbo.PRAL_MIGR_CLASS_SALDO_HISTORICO
    @ANIO = @ANIO, @MES_CORTE = @MES_CORTE, @CIERRE = 0, @MODO = 'MIGRAR',
    @SYS_NUMERO_ERROR = @E OUTPUT, @SYS_MENSAJE_ERROR = @M OUTPUT, @SYS_FILAS_AFECTADAS = @F OUTPUT;

IF ISNULL(@E, 0) <> 0
BEGIN
    RAISERROR(N'Error HIS: %s', 16, 1, @M);
    RETURN;
END;
PRINT ISNULL(@M, N'HIS OK') + N' (' + CAST(@F AS VARCHAR(10)) + N' cuentas)';

IF @RECARGAR_PARTIDAS = 1
BEGIN
    PRINT '=== 4. Partidas mes ' + CAST(@MES_PARTIDAS AS VARCHAR(2)) + ': LIMPIAR + MIGRAR + APLICAR ===';

    IF OBJECT_ID(N'dbo.PRAL_MIGR_CLASS_PARTIDAS_MES', N'P') IS NULL
    BEGIN
        RAISERROR(N'Falta PRAL_MIGR_CLASS_PARTIDAS_MES. Ejecute MIGRATE_CLASS_PARTIDAS_MES.sql una vez.', 16, 1);
        RETURN;
    END;

    EXEC dbo.PRAL_MIGR_CLASS_PARTIDAS_MES
        @ANIO = @ANIO, @MES = @MES_PARTIDAS, @MODO = 'LIMPIAR',
        @SYS_NUMERO_ERROR = @E OUTPUT, @SYS_MENSAJE_ERROR = @M OUTPUT;

    EXEC dbo.PRAL_MIGR_CLASS_PARTIDAS_MES
        @ANIO = @ANIO, @MES = @MES_PARTIDAS, @MODO = 'MIGRAR',
        @SYS_NUMERO_ERROR = @E OUTPUT, @SYS_MENSAJE_ERROR = @M OUTPUT, @SYS_FILAS_AFECTADAS = @F OUTPUT;

    IF ISNULL(@E, 0) <> 0
    BEGIN
        RAISERROR(N'Error MIGRAR partidas: %s', 16, 1, @M);
        RETURN;
    END;

    EXEC dbo.PRAL_MIGR_CLASS_PARTIDAS_MES
        @ANIO = @ANIO, @MES = @MES_PARTIDAS, @MODO = 'APLICAR',
        @SYS_NUMERO_ERROR = @E OUTPUT, @SYS_MENSAJE_ERROR = @M OUTPUT;

    IF ISNULL(@E, 0) <> 0
    BEGIN
        RAISERROR(N'Error APLICAR partidas: %s', 16, 1, @M);
        RETURN;
    END;
    PRINT ISNULL(@M, N'Partidas aplicadas.');
END
ELSE
    PRINT '=== 4. Partidas: omitido (RECARGAR_PARTIDAS=0) ===';

PRINT '=== 5. Resumen patrimonio HIS (apertura mes ' + CAST(@MES_CORTE + 1 AS VARCHAR(2)) + ') ===';
SELECT CUENTA_CONTABLE, SALDO_INICIAL5
FROM CON_CATALOGO_SALDO_HIS
WHERE CORR_EMPRESA = 1 AND ANIO_PERIODO = @ANIO AND CUENTA_CONTABLE LIKE '310%'
ORDER BY 1;

DECLARE @FECHA DATE = EOMONTH(DATEFROMPARTS(@ANIO, @MES_CORTE + 1, 1));
PRINT 'Listo. Use FECHA_FINAL = ' + CONVERT(VARCHAR(10), @FECHA, 23) + ' en Balance y Estado de Resultados.';
GO
