SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/* Renombra CORR_CANDIDATO -> CORR_PERSONA_DATOS en tabla, padre, FK y vista. */

IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'CORR_CANDIDATO') IS NOT NULL
   AND COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'CORR_PERSONA_DATOS') IS NULL
BEGIN
    IF EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE name = N'FK_SC_SOLICITUD_EMPLEO_SC_PERSONA_DATOS'
    )
    BEGIN
        ALTER TABLE dbo.SC_SOLICITUD_EMPLEO
            DROP CONSTRAINT FK_SC_SOLICITUD_EMPLEO_SC_PERSONA_DATOS;
    END;

    EXEC sys.sp_rename
        @objname = N'dbo.SC_PERSONA_DATOS.CORR_CANDIDATO',
        @newname = N'CORR_PERSONA_DATOS',
        @objtype = N'COLUMN';
END;
GO

IF COL_LENGTH(N'dbo.SC_SOLICITUD_EMPLEO', N'CORR_CANDIDATO') IS NOT NULL
   AND COL_LENGTH(N'dbo.SC_SOLICITUD_EMPLEO', N'CORR_PERSONA_DATOS') IS NULL
BEGIN
    EXEC sys.sp_rename
        @objname = N'dbo.SC_SOLICITUD_EMPLEO.CORR_CANDIDATO',
        @newname = N'CORR_PERSONA_DATOS',
        @objtype = N'COLUMN';
END;
GO

IF OBJECT_ID(N'dbo.SC_PERSONA_DATOS', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'CORR_PERSONA_DATOS') IS NOT NULL
   AND NOT EXISTS (
        SELECT 1
        FROM sys.key_constraints
        WHERE [type] = N'PK'
          AND parent_object_id = OBJECT_ID(N'dbo.SC_PERSONA_DATOS')
    )
BEGIN
    ALTER TABLE dbo.SC_PERSONA_DATOS
        ADD CONSTRAINT PK_SC_PERSONA_DATOS
        PRIMARY KEY CLUSTERED (CORR_EMPRESA, CORR_PERSONA_DATOS);
END;
GO

IF OBJECT_ID(N'dbo.SC_SOLICITUD_EMPLEO', N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.SC_SOLICITUD_EMPLEO', N'CORR_PERSONA_DATOS') IS NOT NULL
   AND COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'CORR_PERSONA_DATOS') IS NOT NULL
   AND NOT EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE name = N'FK_SC_SOLICITUD_EMPLEO_SC_PERSONA_DATOS'
    )
BEGIN
    ALTER TABLE dbo.SC_SOLICITUD_EMPLEO WITH CHECK
        ADD CONSTRAINT FK_SC_SOLICITUD_EMPLEO_SC_PERSONA_DATOS
        FOREIGN KEY (CORR_EMPRESA, CORR_PERSONA_DATOS)
        REFERENCES dbo.SC_PERSONA_DATOS (CORR_EMPRESA, CORR_PERSONA_DATOS);
END;
GO

CREATE OR ALTER VIEW dbo.V_SC_SOLICITUD_EMPLEO
AS
SELECT
    CORR_EMPRESA,
    CORR_SOLICITUD_EMPLEO,
    FECHA_GENERACION,
    CORREO_INVITACION,
    CORR_PERSONA_DATOS,
    ACTIVO,
    USUARIO_CREA,
    ESTACION_CREA,
    FECHA_CREA,
    USUARIO_ACTU,
    ESTACION_ACTU,
    FECHA_ACTU
FROM dbo.SC_SOLICITUD_EMPLEO;
GO
