/*
  Migra TODAS las partidas contables de AGOSTO desde CLASS (129) -> SGUEES (250).

  Origen: CLASS_UEES.dbo.TRANSAC + TRANSAC_HST (solo lectura via linked server)
  Destino: CON_PARTIDA + CON_PARTIDA_DETA (clase NOR, nombre MIGR CLASS%)

  Ejecutar en SGUEES @ 192.168.0.250

  Preview (revisar conteos y descuadres):
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -v ANIO=2026 -v MODO=PREVIEW -i RUN_MIGR_CLASS_PARTIDAS_AGOSTO.sql

  Ejecutar migracion + aplicar:
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -v ANIO=2026 -v MODO=EJECUTAR -v APLICAR=1 -i RUN_MIGR_CLASS_PARTIDAS_AGOSTO.sql

  Solo crear en DI (sin aplicar):
    sqlcmd ... -v MODO=EJECUTAR -v APLICAR=0 ...
*/
SET NOCOUNT ON;
GO

PRINT N'=== SP migracion partidas ===';
GO
:r MIGRATE_CLASS_PARTIDAS_MES.sql
GO

DECLARE @ANIO INT = CAST('$(ANIO)' AS INT);
DECLARE @MES INT = CAST('$(MES)' AS INT);
DECLARE @MODO VARCHAR(10) = UPPER(LTRIM(RTRIM('$(MODO)')));
DECLARE @APLICAR INT = CAST('$(APLICAR)' AS INT);
DECLARE @CORR_EMPRESA INT = 1;
DECLARE @E NUMERIC(38, 0);
DECLARE @M NVARCHAR(4000);
DECLARE @F INT;

IF '$(ANIO)' = '$' + '(ANIO)' OR @ANIO = 0 SET @ANIO = 2026;
IF '$(MES)' = '$' + '(MES)' OR @MES = 0 SET @MES = 8;
IF '$(MODO)' = '$' + '(MODO)' OR @MODO = '' SET @MODO = 'PREVIEW';

PRINT N'=== Migracion partidas CLASS -> SGUEES ===';
PRINT N'Anio: ' + CAST(@ANIO AS VARCHAR(4)) + N' | Mes: ' + CAST(@MES AS VARCHAR(2)) + N' | Modo: ' + @MODO;

IF NOT EXISTS (SELECT 1 FROM sys.servers WHERE name = N'CLASS_UEES' AND is_linked = 1)
BEGIN
	RAISERROR(N'Linked server CLASS_UEES no existe. Ejecute SETUP_SYS_INSTANCIA_REMOTA.sql', 16, 1);
	RETURN;
END;

IF OBJECT_ID(N'dbo.FN_CLASS_TRAGLN_TO_CUENTA', N'FN') IS NULL
   OR OBJECT_ID(N'dbo.FN_CLASS_TRACCN_TO_CORR_CENTRO_COSTO', N'FN') IS NULL
BEGIN
	RAISERROR(N'Faltan funciones FN_CLASS_*. Ejecute MIGRATE_CLASS_SALDO_INICIAL_BALANCE_GENERAL.sql e IMPORT_CLASS_CENTRO_COSTO_REL.sql una vez.', 16, 1);
	RETURN;
END;

IF NOT EXISTS (
	SELECT 1
	FROM CLASS_UEES.CLASS_UEES.dbo.TRANSAC TR
	WHERE TR.TRATYP = 'R'
	  AND TR.TRABNK = '01'
	  AND YEAR(TR.TRAFVL) = @ANIO
	  AND MONTH(TR.TRAFVL) = @MES
)
BEGIN
	PRINT N'AVISO: no hay movimientos en TRANSAC para ese mes (revisar TRANSAC_HST o anio/mes).';
END;

IF NOT EXISTS (
	SELECT 1 FROM CON_PERIODO_CONTABLE
	WHERE CORR_EMPRESA = @CORR_EMPRESA AND ANIO_PERIODO = @ANIO AND MES_PERIODO = @MES
)
BEGIN
	INSERT INTO CON_PERIODO_CONTABLE (CORR_EMPRESA, ANIO_PERIODO, MES_PERIODO, ESTADO_PERIODO_CON)
	VALUES (@CORR_EMPRESA, @ANIO, @MES, 'AB');
	PRINT N'Periodo creado en AB.';
END
ELSE
BEGIN
	UPDATE CON_PERIODO_CONTABLE
	SET ESTADO_PERIODO_CON = 'AB'
	WHERE CORR_EMPRESA = @CORR_EMPRESA
	  AND ANIO_PERIODO = @ANIO
	  AND MES_PERIODO = @MES
	  AND ESTADO_PERIODO_CON <> 'AB';

	IF @@ROWCOUNT > 0
		PRINT N'Periodo ' + CAST(@MES AS VARCHAR(2)) + N'/' + CAST(@ANIO AS VARCHAR(4)) + N' abierto (AB).';
END;

PRINT N'=== 1) PREVIEW ===';
EXEC dbo.PRAL_MIGR_CLASS_PARTIDAS_MES
	@ANIO = @ANIO,
	@MES = @MES,
	@CIERRE = 0,
	@CORR_EMPRESA = @CORR_EMPRESA,
	@MODO = 'PREVIEW',
	@SYS_NUMERO_ERROR = @E OUTPUT,
	@SYS_MENSAJE_ERROR = @M OUTPUT,
	@SYS_FILAS_AFECTADAS = @F OUTPUT;

IF @MODO = 'PREVIEW'
BEGIN
	PRINT N'Preview listo. Si PARTIDAS_DESCUADRE = 0, ejecute con -v MODO=EJECUTAR';
	RETURN;
END;

IF @MODO NOT IN ('EJECUTAR', 'MIGRAR')
BEGIN
	RAISERROR(N'MODO invalido. Use PREVIEW o EJECUTAR.', 16, 1);
	RETURN;
END;

PRINT N'=== 2) LIMPIAR partidas MIGR CLASS previas ===';
EXEC dbo.PRAL_MIGR_CLASS_PARTIDAS_MES
	@ANIO = @ANIO,
	@MES = @MES,
	@CIERRE = 0,
	@CORR_EMPRESA = @CORR_EMPRESA,
	@MODO = 'LIMPIAR',
	@SYS_NUMERO_ERROR = @E OUTPUT,
	@SYS_MENSAJE_ERROR = @M OUTPUT,
	@SYS_FILAS_AFECTADAS = @F OUTPUT;

PRINT ISNULL(@M, N'');

PRINT N'=== 3) MIGRAR (crear partidas DI) ===';
EXEC dbo.PRAL_MIGR_CLASS_PARTIDAS_MES
	@ANIO = @ANIO,
	@MES = @MES,
	@CIERRE = 0,
	@CORR_EMPRESA = @CORR_EMPRESA,
	@MODO = 'MIGRAR',
	@SYS_NUMERO_ERROR = @E OUTPUT,
	@SYS_MENSAJE_ERROR = @M OUTPUT,
	@SYS_FILAS_AFECTADAS = @F OUTPUT;

IF ISNULL(@E, 0) <> 0
BEGIN
	RAISERROR(N'Error MIGRAR: %s', 16, 1, @M);
	RETURN;
END;

PRINT ISNULL(@M, N'MIGRAR OK');

IF @APLICAR = 1
BEGIN
	PRINT N'=== 4) APLICAR partidas ===';
	EXEC dbo.PRAL_MIGR_CLASS_PARTIDAS_MES
		@ANIO = @ANIO,
		@MES = @MES,
		@CIERRE = 0,
		@CORR_EMPRESA = @CORR_EMPRESA,
		@MODO = 'APLICAR',
		@SYS_NUMERO_ERROR = @E OUTPUT,
		@SYS_MENSAJE_ERROR = @M OUTPUT,
		@SYS_FILAS_AFECTADAS = @F OUTPUT;

	IF ISNULL(@E, 0) <> 0
	BEGIN
		RAISERROR(N'Error APLICAR: %s', 16, 1, @M);
		RETURN;
	END;

	PRINT ISNULL(@M, N'APLICAR OK');
END
ELSE
	PRINT N'APLICAR omitido (partidas quedaron en DI).';

PRINT N'=== 5) Validacion ===';

SELECT ESTADO_PARTIDA, COUNT(*) AS CANT
FROM CON_PARTIDA
WHERE CORR_EMPRESA = @CORR_EMPRESA
  AND ANIO_PERIODO = @ANIO
  AND MES_PERIODO = @MES
  AND NOMBRE_PARTIDA LIKE N'MIGR CLASS%'
GROUP BY ESTADO_PARTIDA;

SELECT
	SUM(D.MONTO_CARGO) AS CARGOS,
	SUM(D.MONTO_ABONO) AS ABONOS,
	ABS(SUM(D.MONTO_CARGO) - SUM(D.MONTO_ABONO)) AS DIFERENCIA
FROM CON_PARTIDA_DETA D
INNER JOIN CON_PARTIDA P
	ON D.CORR_EMPRESA = P.CORR_EMPRESA
   AND D.ANIO_PERIODO = P.ANIO_PERIODO
   AND D.MES_PERIODO = P.MES_PERIODO
   AND D.CORR_CLASE_PARTIDA = P.CORR_CLASE_PARTIDA
   AND D.CORR_PARTIDA = P.CORR_PARTIDA
WHERE P.CORR_EMPRESA = @CORR_EMPRESA
  AND P.ANIO_PERIODO = @ANIO
  AND P.MES_PERIODO = @MES
  AND P.NOMBRE_PARTIDA LIKE N'MIGR CLASS%';

DECLARE @FECHA_FIN DATE = EOMONTH(DATEFROMPARTS(@ANIO, @MES, 1));
PRINT N'Balance General al ' + CONVERT(VARCHAR(10), @FECHA_FIN, 23) + N':';
EXEC dbo.PRAL_IMPR_BALANCE_GENERAL
	@CORR_EMPRESA = @CORR_EMPRESA,
	@FECHA_FINAL = @FECHA_FIN,
	@NIVEL = 3,
	@PARTIDA_CIERRE = 0,
	@PARTIDA_LIQUIDACION = 0;

PRINT N'=== FIN migracion partidas agosto ===';
GO
