/* ============================================================================
   SC_EXPEDIENTE_CANDIDATO + SC_EXPEDIENTE_SOLICITUD
   Tablas, vistas y SP de asociacion solicitud <-> expediente.
   Idempotente (CREATE OR ALTER vistas/SP; tablas solo si no existen).
   ============================================================================
   Ejecutar:
     sqlcmd -S <servidor> -d SGUEES -U <user> -P <pass> -f 65001 -i SC_EXPEDIENTE_CANDIDATO.sql
   ============================================================================ */
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/* ---------- TABLAS ---------- */
IF OBJECT_ID(N'dbo.SC_EXPEDIENTE_CANDIDATO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_EXPEDIENTE_CANDIDATO (
        CORR_EMPRESA int NOT NULL,
        CORR_EXPEDIENTE_CANDIDATO int NOT NULL,
        CORR_PERSONA_DATOS int NOT NULL,
        CORR_ESTADO_EXPEDIENTE int NOT NULL CONSTRAINT DF_SC_EXPEDIENTE_CANDIDATO_ESTADO DEFAULT (1),
        FECHA_GENERACION datetime NOT NULL,
        ACTIVO bit NOT NULL CONSTRAINT DF_SC_EXPEDIENTE_CANDIDATO_ACTIVO DEFAULT (1),
        USUARIO_CREA varchar(50) NULL,
        ESTACION_CREA varchar(50) NULL,
        FECHA_CREA datetime NULL,
        USUARIO_ACTU varchar(50) NULL,
        ESTACION_ACTU varchar(50) NULL,
        FECHA_ACTU datetime NULL,
        CONSTRAINT PK_SC_EXPEDIENTE_CANDIDATO PRIMARY KEY CLUSTERED (CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO)
    );

    ALTER TABLE dbo.SC_EXPEDIENTE_CANDIDATO ADD CONSTRAINT FK_SC_EXPEDIENTE_CANDIDATO_GEN_EMPRESA
        FOREIGN KEY (CORR_EMPRESA) REFERENCES dbo.GEN_EMPRESA (CORR_EMPRESA);

    ALTER TABLE dbo.SC_EXPEDIENTE_CANDIDATO ADD CONSTRAINT FK_SC_EXPEDIENTE_CANDIDATO_SC_PERSONA_DATOS
        FOREIGN KEY (CORR_EMPRESA, CORR_PERSONA_DATOS)
        REFERENCES dbo.SC_PERSONA_DATOS (CORR_EMPRESA, CORR_PERSONA_DATOS);

    CREATE UNIQUE NONCLUSTERED INDEX UX_SC_EXPEDIENTE_CANDIDATO_PERSONA
        ON dbo.SC_EXPEDIENTE_CANDIDATO (CORR_EMPRESA, CORR_PERSONA_DATOS);

    PRINT N'Tabla SC_EXPEDIENTE_CANDIDATO creada.';
END
ELSE
    PRINT N'Tabla SC_EXPEDIENTE_CANDIDATO ya existe.';
GO

IF OBJECT_ID(N'dbo.SC_EXPEDIENTE_SOLICITUD', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_EXPEDIENTE_SOLICITUD (
        CORR_EMPRESA int NOT NULL,
        CORR_EXPEDIENTE_CANDIDATO int NOT NULL,
        CORR_EXPEDIENTE_SOLICITUD int NOT NULL,
        CORR_SOLICITUD_EMPLEO int NOT NULL,
        USUARIO_CREA varchar(50) NULL,
        ESTACION_CREA varchar(50) NULL,
        FECHA_CREA datetime NULL,
        USUARIO_ACTU varchar(50) NULL,
        ESTACION_ACTU varchar(50) NULL,
        FECHA_ACTU datetime NULL,
        CONSTRAINT PK_SC_EXPEDIENTE_SOLICITUD PRIMARY KEY CLUSTERED (
            CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO, CORR_EXPEDIENTE_SOLICITUD
        )
    );

    ALTER TABLE dbo.SC_EXPEDIENTE_SOLICITUD ADD CONSTRAINT FK_SC_EXPEDIENTE_SOLICITUD_EXPEDIENTE
        FOREIGN KEY (CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO)
        REFERENCES dbo.SC_EXPEDIENTE_CANDIDATO (CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO);

    ALTER TABLE dbo.SC_EXPEDIENTE_SOLICITUD ADD CONSTRAINT FK_SC_EXPEDIENTE_SOLICITUD_SOLICITUD
        FOREIGN KEY (CORR_EMPRESA, CORR_SOLICITUD_EMPLEO)
        REFERENCES dbo.SC_SOLICITUD_EMPLEO (CORR_EMPRESA, CORR_SOLICITUD_EMPLEO);

    CREATE UNIQUE NONCLUSTERED INDEX UX_SC_EXPEDIENTE_SOLICITUD_EXP_SOL
        ON dbo.SC_EXPEDIENTE_SOLICITUD (CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO, CORR_SOLICITUD_EMPLEO);

    PRINT N'Tabla SC_EXPEDIENTE_SOLICITUD creada.';
END
ELSE
    PRINT N'Tabla SC_EXPEDIENTE_SOLICITUD ya existe.';
GO

/* ---------- VISTAS ---------- */
CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_CANDIDATO
AS
SELECT
    E.CORR_EMPRESA,
    E.CORR_EXPEDIENTE_CANDIDATO,
    E.CORR_PERSONA_DATOS,
    E.CORR_ESTADO_EXPEDIENTE,
    E.FECHA_GENERACION,
    E.ACTIVO,
    P.DUI AS DUI_PERSONA,
    LTRIM(RTRIM(
        CONCAT(
            ISNULL(P.NOMBRE1, ''),
            CASE WHEN NULLIF(LTRIM(RTRIM(P.NOMBRE2)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.NOMBRE2)) END,
            CASE WHEN NULLIF(LTRIM(RTRIM(P.APELLIDO1)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.APELLIDO1)) END,
            CASE WHEN NULLIF(LTRIM(RTRIM(P.APELLIDO2)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.APELLIDO2)) END
        )
    )) AS NOMBRE_PERSONA,
    E.USUARIO_CREA,
    E.ESTACION_CREA,
    E.FECHA_CREA,
    E.USUARIO_ACTU,
    E.ESTACION_ACTU,
    E.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_CANDIDATO AS E
LEFT JOIN dbo.SC_PERSONA_DATOS AS P
    ON P.CORR_EMPRESA = E.CORR_EMPRESA
   AND P.CORR_PERSONA_DATOS = E.CORR_PERSONA_DATOS;
GO

CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_SOLICITUD
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_SOLICITUD,
    X.CORR_SOLICITUD_EMPLEO,
    S.FECHA_GENERACION AS FECHA_SOLICITUD,
    S.CORREO_INVITACION,
    S.DUI AS DUI_SOLICITUD,
    S.NOMBRE AS NOMBRE_SOLICITUD,
    S.CORR_TIPO_CONTRATACION,
    T.NOMBRE_TIPO_CONTRATACION,
    S.CORR_PERSONA_DATOS,
    S.ACTIVO AS ACTIVO_SOLICITUD,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_SOLICITUD AS X
INNER JOIN dbo.SC_SOLICITUD_EMPLEO AS S
    ON S.CORR_EMPRESA = X.CORR_EMPRESA
   AND S.CORR_SOLICITUD_EMPLEO = X.CORR_SOLICITUD_EMPLEO
LEFT JOIN dbo.SC_TIPO_CONTRATACION AS T
    ON T.CORR_EMPRESA = S.CORR_EMPRESA
   AND T.CORR_TIPO_CONTRATACION = S.CORR_TIPO_CONTRATACION;
GO

PRINT N'Vistas V_SC_EXPEDIENTE_CANDIDATO / V_SC_EXPEDIENTE_SOLICITUD listas.';
GO

/* ---------- SP ASOCIAR ---------- */
/*
  Codigos @SYS_NUMERO_ERROR:
    0    = exito
    4101 = solicitud invalida / sin persona
    4102 = DUI de solicitud no coincide con DUI de persona
    4103 = no existe expediente; se requiere confirmar creacion
    4104 = la solicitud ya esta asociada a ese expediente
   -1    = error no controlado
*/
CREATE OR ALTER PROCEDURE dbo.PRAL_MTTO_SC_EXPEDIENTE_ASOCIAR_SOLICITUD
    @CORR_EMPRESA int,
    @CORR_SOLICITUD_EMPLEO int,
    @CREAR_EXPEDIENTE bit = 0,
    @SOLO_CONSULTA bit = 0,
    @SYS_LOGIN_USUARIO varchar(50) = NULL,
    @SYS_ESTACION varchar(50) = NULL,
    @CORR_EXPEDIENTE_CANDIDATO int = NULL OUTPUT,
    @ESTADO varchar(30) = NULL OUTPUT,
    @SYS_FILAS_AFECTADAS int = 0 OUTPUT,
    @SYS_NUMERO_ERROR int = 0 OUTPUT,
    @SYS_MENSAJE_ERROR nvarchar(4000) = N'' OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE
        @CORR_PERSONA_DATOS int = 0,
        @DUI_SOLICITUD varchar(25) = NULL,
        @DUI_PERSONA varchar(25) = NULL,
        @DUI_SOL_NORM varchar(25) = NULL,
        @DUI_PER_NORM varchar(25) = NULL,
        @CORR_EXP int = 0,
        @CORR_DET int = 0,
        @FECHA datetime = GETDATE();

    SET @SYS_FILAS_AFECTADAS = 0;
    SET @SYS_NUMERO_ERROR = 0;
    SET @SYS_MENSAJE_ERROR = N'';
    SET @CORR_EXPEDIENTE_CANDIDATO = NULL;
    SET @ESTADO = NULL;

    BEGIN TRY
        IF ISNULL(@SOLO_CONSULTA, 0) = 0
            BEGIN TRANSACTION;

        IF ISNULL(@SOLO_CONSULTA, 0) = 1
        BEGIN
            SELECT
                @CORR_PERSONA_DATOS = ISNULL(S.CORR_PERSONA_DATOS, 0),
                @DUI_SOLICITUD = S.DUI
            FROM dbo.SC_SOLICITUD_EMPLEO AS S
            WHERE S.CORR_EMPRESA = @CORR_EMPRESA
              AND S.CORR_SOLICITUD_EMPLEO = @CORR_SOLICITUD_EMPLEO;
        END
        ELSE
        BEGIN
            SELECT
                @CORR_PERSONA_DATOS = ISNULL(S.CORR_PERSONA_DATOS, 0),
                @DUI_SOLICITUD = S.DUI
            FROM dbo.SC_SOLICITUD_EMPLEO AS S WITH (UPDLOCK, HOLDLOCK)
            WHERE S.CORR_EMPRESA = @CORR_EMPRESA
              AND S.CORR_SOLICITUD_EMPLEO = @CORR_SOLICITUD_EMPLEO;
        END;

        IF @@ROWCOUNT = 0 OR @CORR_PERSONA_DATOS <= 0
        BEGIN
            SET @ESTADO = N'SIN_PERSONA';
            SET @SYS_NUMERO_ERROR = 4101;
            SET @SYS_MENSAJE_ERROR = N'La solicitud no existe o no tiene persona asociada (CORR_PERSONA_DATOS).';
            IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
            RETURN;
        END;

        SELECT @DUI_PERSONA = P.DUI
        FROM dbo.SC_PERSONA_DATOS AS P
        WHERE P.CORR_EMPRESA = @CORR_EMPRESA
          AND P.CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;

        IF @DUI_PERSONA IS NULL
        BEGIN
            SET @ESTADO = N'SIN_PERSONA';
            SET @SYS_NUMERO_ERROR = 4101;
            SET @SYS_MENSAJE_ERROR = N'No se encontraron los datos de persona de la solicitud.';
            IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
            RETURN;
        END;

        SET @DUI_SOL_NORM = UPPER(REPLACE(REPLACE(LTRIM(RTRIM(ISNULL(@DUI_SOLICITUD, ''))), '-', ''), ' ', ''));
        SET @DUI_PER_NORM = UPPER(REPLACE(REPLACE(LTRIM(RTRIM(ISNULL(@DUI_PERSONA, ''))), '-', ''), ' ', ''));

        IF @DUI_SOL_NORM = N'' OR @DUI_PER_NORM = N'' OR @DUI_SOL_NORM <> @DUI_PER_NORM
        BEGIN
            SET @ESTADO = N'DUI_NO_COINCIDE';
            SET @SYS_NUMERO_ERROR = 4102;
            SET @SYS_MENSAJE_ERROR = N'El DUI de la solicitud no coincide con el DUI de la persona asociada.';
            IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
            RETURN;
        END;

        IF ISNULL(@SOLO_CONSULTA, 0) = 1
        BEGIN
            SELECT @CORR_EXP = E.CORR_EXPEDIENTE_CANDIDATO
            FROM dbo.SC_EXPEDIENTE_CANDIDATO AS E
            WHERE E.CORR_EMPRESA = @CORR_EMPRESA
              AND E.CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;
        END
        ELSE
        BEGIN
            SELECT @CORR_EXP = E.CORR_EXPEDIENTE_CANDIDATO
            FROM dbo.SC_EXPEDIENTE_CANDIDATO AS E WITH (UPDLOCK, HOLDLOCK)
            WHERE E.CORR_EMPRESA = @CORR_EMPRESA
              AND E.CORR_PERSONA_DATOS = @CORR_PERSONA_DATOS;
        END;

        IF ISNULL(@CORR_EXP, 0) = 0
        BEGIN
            /* Consulta o asociar sin confirmar creaciÃ³n */
            IF ISNULL(@SOLO_CONSULTA, 0) = 1 OR ISNULL(@CREAR_EXPEDIENTE, 0) = 0
            BEGIN
                SET @ESTADO = N'SIN_EXPEDIENTE';
                SET @SYS_NUMERO_ERROR = 4103;
                SET @SYS_MENSAJE_ERROR = N'No existe un expediente para esta persona. Â¿Desea crear el expediente y asociar la solicitud?';
                IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
                RETURN;
            END;

            SELECT @CORR_EXP = ISNULL(MAX(CORR_EXPEDIENTE_CANDIDATO), 0) + 1
            FROM dbo.SC_EXPEDIENTE_CANDIDATO WITH (UPDLOCK, HOLDLOCK)
            WHERE CORR_EMPRESA = @CORR_EMPRESA;

            INSERT INTO dbo.SC_EXPEDIENTE_CANDIDATO (
                CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO, CORR_PERSONA_DATOS,
                CORR_ESTADO_EXPEDIENTE, FECHA_GENERACION, ACTIVO,
                USUARIO_CREA, ESTACION_CREA, FECHA_CREA,
                USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
            )
            VALUES (
                @CORR_EMPRESA, @CORR_EXP, @CORR_PERSONA_DATOS,
                1, @FECHA, 1,
                @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA,
                @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA
            );

            SET @SYS_FILAS_AFECTADAS = @SYS_FILAS_AFECTADAS + 1;
        END;

        IF EXISTS (
            SELECT 1
            FROM dbo.SC_EXPEDIENTE_SOLICITUD AS X
            WHERE X.CORR_EMPRESA = @CORR_EMPRESA
              AND X.CORR_EXPEDIENTE_CANDIDATO = @CORR_EXP
              AND X.CORR_SOLICITUD_EMPLEO = @CORR_SOLICITUD_EMPLEO
        )
        BEGIN
            SET @CORR_EXPEDIENTE_CANDIDATO = @CORR_EXP;
            SET @ESTADO = N'YA_ASOCIADA';
            SET @SYS_NUMERO_ERROR = 4104;
            SET @SYS_MENSAJE_ERROR = N'La solicitud ya estÃ¡ asociada a este expediente de candidato.';
            IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
            RETURN;
        END;

        /* Consulta: expediente existe y la solicitud aÃºn no estÃ¡ asociada */
        IF ISNULL(@SOLO_CONSULTA, 0) = 1
        BEGIN
            SET @CORR_EXPEDIENTE_CANDIDATO = @CORR_EXP;
            SET @ESTADO = N'PUEDE_ASOCIAR';
            SET @SYS_NUMERO_ERROR = 0;
            SET @SYS_MENSAJE_ERROR = N'';
            RETURN;
        END;

        SELECT @CORR_DET = ISNULL(MAX(CORR_EXPEDIENTE_SOLICITUD), 0) + 1
        FROM dbo.SC_EXPEDIENTE_SOLICITUD WITH (UPDLOCK, HOLDLOCK)
        WHERE CORR_EMPRESA = @CORR_EMPRESA
          AND CORR_EXPEDIENTE_CANDIDATO = @CORR_EXP;

        INSERT INTO dbo.SC_EXPEDIENTE_SOLICITUD (
            CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO, CORR_EXPEDIENTE_SOLICITUD,
            CORR_SOLICITUD_EMPLEO,
            USUARIO_CREA, ESTACION_CREA, FECHA_CREA,
            USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
        )
        VALUES (
            @CORR_EMPRESA, @CORR_EXP, @CORR_DET,
            @CORR_SOLICITUD_EMPLEO,
            @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA,
            @SYS_LOGIN_USUARIO, @SYS_ESTACION, @FECHA
        );

        SET @SYS_FILAS_AFECTADAS = @SYS_FILAS_AFECTADAS + 1;
        SET @CORR_EXPEDIENTE_CANDIDATO = @CORR_EXP;
        SET @ESTADO = N'ASOCIADA';
        SET @SYS_NUMERO_ERROR = 0;
        SET @SYS_MENSAJE_ERROR = N'Solicitud asociada al expediente correctamente.';

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        SET @ESTADO = N'ERROR';
        SET @SYS_NUMERO_ERROR = -1;
        SET @SYS_MENSAJE_ERROR = ERROR_MESSAGE();
        SET @SYS_FILAS_AFECTADAS = 0;
        SET @CORR_EXPEDIENTE_CANDIDATO = NULL;
    END CATCH
END;
GO

PRINT N'SC_EXPEDIENTE_CANDIDATO — objetos de BD listos.';
GO

