/*
  SC_EXPEDIENTE_ENTREVISTA — tabla + vista (idempotente)
  Ejecutar:
  sqlcmd -S <srv> -d SGUEES -U <user> -f 65001 -i SGUEES-DB/Scripts/SC_EXPEDIENTE_ENTREVISTA.sql
*/

SET NOCOUNT ON;
GO

/* ========== TABLA ========== */
IF OBJECT_ID(N'dbo.SC_EXPEDIENTE_ENTREVISTA', N'U') IS NULL
BEGIN
  CREATE TABLE [dbo].[SC_EXPEDIENTE_ENTREVISTA] (
    [CORR_EMPRESA] [int] NOT NULL,
    [CORR_EXPEDIENTE_CANDIDATO] [int] NOT NULL,
    [CORR_EXPEDIENTE_ENTREVISTA] [int] NOT NULL,
    [CORR_SOLICITUD_EMPLEO] [int] NOT NULL,
    [TIPO_ENTREVISTA] [varchar](50) NOT NULL,
    [FECHA_ENTREVISTA] [datetime] NOT NULL,
    [ENTREVISTADOR] [varchar](150) NOT NULL,
    [ESTADO_ENTREVISTA] [varchar](50) NOT NULL,
    [RESULTADO_ENTREVISTA] [varchar](50) NULL,
    [RESUMEN_ENTREVISTA] [varchar](2000) NULL,
    [USUARIO_CREA] [varchar](50) NULL,
    [ESTACION_CREA] [varchar](50) NULL,
    [FECHA_CREA] [datetime] NULL,
    [USUARIO_ACTU] [varchar](50) NULL,
    [ESTACION_ACTU] [varchar](50) NULL,
    [FECHA_ACTU] [datetime] NULL,
    CONSTRAINT [PK_SC_EXPEDIENTE_ENTREVISTA] PRIMARY KEY CLUSTERED (
      [CORR_EMPRESA],
      [CORR_EXPEDIENTE_CANDIDATO],
      [CORR_EXPEDIENTE_ENTREVISTA]
    )
  ) ON [PRIMARY];
END
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SC_EXPEDIENTE_ENTREVISTA_EXPEDIENTE'
)
BEGIN
  ALTER TABLE [dbo].[SC_EXPEDIENTE_ENTREVISTA] ADD CONSTRAINT [FK_SC_EXPEDIENTE_ENTREVISTA_EXPEDIENTE]
    FOREIGN KEY ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO])
    REFERENCES [dbo].[SC_EXPEDIENTE_CANDIDATO] ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO]);
END
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SC_EXPEDIENTE_ENTREVISTA_SOLICITUD'
)
BEGIN
  ALTER TABLE [dbo].[SC_EXPEDIENTE_ENTREVISTA] ADD CONSTRAINT [FK_SC_EXPEDIENTE_ENTREVISTA_SOLICITUD]
    FOREIGN KEY ([CORR_EMPRESA], [CORR_SOLICITUD_EMPLEO])
    REFERENCES [dbo].[SC_SOLICITUD_EMPLEO] ([CORR_EMPRESA], [CORR_SOLICITUD_EMPLEO]);
END
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WHERE name = N'IX_SC_EXPEDIENTE_ENTREVISTA_SOLICITUD'
    AND object_id = OBJECT_ID(N'dbo.SC_EXPEDIENTE_ENTREVISTA')
)
BEGIN
  CREATE NONCLUSTERED INDEX [IX_SC_EXPEDIENTE_ENTREVISTA_SOLICITUD]
    ON [dbo].[SC_EXPEDIENTE_ENTREVISTA] ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO], [CORR_SOLICITUD_EMPLEO]);
END
GO

/* ========== VISTA ========== */
CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_ENTREVISTA
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_ENTREVISTA,
    X.CORR_SOLICITUD_EMPLEO,
    X.TIPO_ENTREVISTA,
    X.FECHA_ENTREVISTA,
    X.ENTREVISTADOR,
    X.ESTADO_ENTREVISTA,
    X.RESULTADO_ENTREVISTA,
    X.RESUMEN_ENTREVISTA,
    S.CORREO_INVITACION,
    S.NOMBRE AS NOMBRE_SOLICITUD,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_ENTREVISTA AS X
INNER JOIN dbo.SC_SOLICITUD_EMPLEO AS S
    ON S.CORR_EMPRESA = X.CORR_EMPRESA
   AND S.CORR_SOLICITUD_EMPLEO = X.CORR_SOLICITUD_EMPLEO;
GO

PRINT N'SC_EXPEDIENTE_ENTREVISTA / V_SC_EXPEDIENTE_ENTREVISTA listos.';
GO
