/* ============================================================================
   SC_EXPEDIENTE_CANDIDATO + SC_EXPEDIENTE_SOLICITUD
   Tablas, vistas y SP de asociacion solicitud <-> expediente.
   Idempotente (CREATE OR ALTER vistas/SP; tablas solo si no existen).
   ============================================================================
   Ejecutar:
     sqlcmd -S <servidor> -d SGUEES -U <user> -P <pass> -f 65001 -i SC_EXPEDIENTE_CANDIDATO.sql
   ============================================================================ */
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/* ---------- TABLAS ---------- */
IF OBJECT_ID(N'dbo.SC_EXPEDIENTE_CANDIDATO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_EXPEDIENTE_CANDIDATO (
        CORR_EMPRESA int NOT NULL,
        CORR_EXPEDIENTE_CANDIDATO int NOT NULL,
        CORR_PERSONA_DATOS int NOT NULL,
        CORR_ESTADO_EXPEDIENTE int NOT NULL CONSTRAINT DF_SC_EXPEDIENTE_CANDIDATO_ESTADO DEFAULT (1),
        FECHA_GENERACION datetime NOT NULL,
        ACTIVO bit NOT NULL CONSTRAINT DF_SC_EXPEDIENTE_CANDIDATO_ACTIVO DEFAULT (1),
        USUARIO_CREA varchar(50) NULL,
        ESTACION_CREA varchar(50) NULL,
        FECHA_CREA datetime NULL,
        USUARIO_ACTU varchar(50) NULL,
        ESTACION_ACTU varchar(50) NULL,
        FECHA_ACTU datetime NULL,
        CONSTRAINT PK_SC_EXPEDIENTE_CANDIDATO PRIMARY KEY CLUSTERED (CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO)
    );

    ALTER TABLE dbo.SC_EXPEDIENTE_CANDIDATO ADD CONSTRAINT FK_SC_EXPEDIENTE_CANDIDATO_GEN_EMPRESA
        FOREIGN KEY (CORR_EMPRESA) REFERENCES dbo.GEN_EMPRESA (CORR_EMPRESA);

    ALTER TABLE dbo.SC_EXPEDIENTE_CANDIDATO ADD CONSTRAINT FK_SC_EXPEDIENTE_CANDIDATO_SC_PERSONA_DATOS
        FOREIGN KEY (CORR_EMPRESA, CORR_PERSONA_DATOS)
        REFERENCES dbo.SC_PERSONA_DATOS (CORR_EMPRESA, CORR_PERSONA_DATOS);

    CREATE UNIQUE NONCLUSTERED INDEX UX_SC_EXPEDIENTE_CANDIDATO_PERSONA
        ON dbo.SC_EXPEDIENTE_CANDIDATO (CORR_EMPRESA, CORR_PERSONA_DATOS);

    PRINT N'Tabla SC_EXPEDIENTE_CANDIDATO creada.';
END
ELSE
    PRINT N'Tabla SC_EXPEDIENTE_CANDIDATO ya existe.';
GO

IF OBJECT_ID(N'dbo.SC_EXPEDIENTE_SOLICITUD', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_EXPEDIENTE_SOLICITUD (
        CORR_EMPRESA int NOT NULL,
        CORR_EXPEDIENTE_CANDIDATO int NOT NULL,
        CORR_EXPEDIENTE_SOLICITUD int NOT NULL,
        CORR_SOLICITUD_EMPLEO int NOT NULL,
        USUARIO_CREA varchar(50) NULL,
        ESTACION_CREA varchar(50) NULL,
        FECHA_CREA datetime NULL,
        USUARIO_ACTU varchar(50) NULL,
        ESTACION_ACTU varchar(50) NULL,
        FECHA_ACTU datetime NULL,
        CONSTRAINT PK_SC_EXPEDIENTE_SOLICITUD PRIMARY KEY CLUSTERED (
            CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO, CORR_EXPEDIENTE_SOLICITUD
        )
    );

    ALTER TABLE dbo.SC_EXPEDIENTE_SOLICITUD ADD CONSTRAINT FK_SC_EXPEDIENTE_SOLICITUD_EXPEDIENTE
        FOREIGN KEY (CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO)
        REFERENCES dbo.SC_EXPEDIENTE_CANDIDATO (CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO);

    ALTER TABLE dbo.SC_EXPEDIENTE_SOLICITUD ADD CONSTRAINT FK_SC_EXPEDIENTE_SOLICITUD_SOLICITUD
        FOREIGN KEY (CORR_EMPRESA, CORR_SOLICITUD_EMPLEO)
        REFERENCES dbo.SC_SOLICITUD_EMPLEO (CORR_EMPRESA, CORR_SOLICITUD_EMPLEO);

    CREATE UNIQUE NONCLUSTERED INDEX UX_SC_EXPEDIENTE_SOLICITUD_EXP_SOL
        ON dbo.SC_EXPEDIENTE_SOLICITUD (CORR_EMPRESA, CORR_EXPEDIENTE_CANDIDATO, CORR_SOLICITUD_EMPLEO);

    PRINT N'Tabla SC_EXPEDIENTE_SOLICITUD creada.';
END
ELSE
    PRINT N'Tabla SC_EXPEDIENTE_SOLICITUD ya existe.';
GO

/* ---------- VISTAS ---------- */
CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_CANDIDATO
AS
SELECT
    E.CORR_EMPRESA,
    E.CORR_EXPEDIENTE_CANDIDATO,
    E.CORR_PERSONA_DATOS,
    E.CORR_ESTADO_EXPEDIENTE,
    E.FECHA_GENERACION,
    E.ACTIVO,
    P.DUI AS DUI_PERSONA,
    LTRIM(RTRIM(
        CONCAT(
            ISNULL(P.NOMBRE1, ''),
            CASE WHEN NULLIF(LTRIM(RTRIM(P.NOMBRE2)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.NOMBRE2)) END,
            CASE WHEN NULLIF(LTRIM(RTRIM(P.APELLIDO1)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.APELLIDO1)) END,
            CASE WHEN NULLIF(LTRIM(RTRIM(P.APELLIDO2)), '') IS NULL THEN '' ELSE ' ' + LTRIM(RTRIM(P.APELLIDO2)) END
        )
    )) AS NOMBRE_PERSONA,
    E.USUARIO_CREA,
    E.ESTACION_CREA,
    E.FECHA_CREA,
    E.USUARIO_ACTU,
    E.ESTACION_ACTU,
    E.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_CANDIDATO AS E
LEFT JOIN dbo.SC_PERSONA_DATOS AS P
    ON P.CORR_EMPRESA = E.CORR_EMPRESA
   AND P.CORR_PERSONA_DATOS = E.CORR_PERSONA_DATOS;
GO

CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_SOLICITUD
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_EXPEDIENTE_CANDIDATO,
    X.CORR_EXPEDIENTE_SOLICITUD,
    X.CORR_SOLICITUD_EMPLEO,
    S.FECHA_GENERACION AS FECHA_SOLICITUD,
    S.CORREO_INVITACION,
    S.DUI AS DUI_SOLICITUD,
    S.NOMBRE AS NOMBRE_SOLICITUD,
    S.CORR_TIPO_CONTRATACION,
    T.NOMBRE_TIPO_CONTRATACION,
    S.CORR_PERSONA_DATOS,
    S.ACTIVO AS ACTIVO_SOLICITUD,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_EXPEDIENTE_SOLICITUD AS X
INNER JOIN dbo.SC_SOLICITUD_EMPLEO AS S
    ON S.CORR_EMPRESA = X.CORR_EMPRESA
   AND S.CORR_SOLICITUD_EMPLEO = X.CORR_SOLICITUD_EMPLEO
LEFT JOIN dbo.SC_TIPO_CONTRATACION AS T
    ON T.CORR_EMPRESA = S.CORR_EMPRESA
   AND T.CORR_TIPO_CONTRATACION = S.CORR_TIPO_CONTRATACION;
GO

PRINT N'Vistas V_SC_EXPEDIENTE_CANDIDATO / V_SC_EXPEDIENTE_SOLICITUD listas.';
GO

/* ---------- SP ASOCIAR ---------- */
/* Fuente de verdad del SP: Scripts/PRAL_MTTO_SC_EXPEDIENTE_ASOCIAR_SOLICITUD.sql (incluye 4105 DUI). */
PRINT N'SP asociar: ejecutar también PRAL_MTTO_SC_EXPEDIENTE_ASOCIAR_SOLICITUD.sql si este script es histórico.';
GO

PRINT N'SC_EXPEDIENTE_CANDIDATO — objetos de BD listos.';
GO

