/* =============================================================================
   SC_MOVIMIENTO_REQUISICION — puente movimiento ↔ requisición / candidato
   y alta del movimiento cuando la jefatura marca APLICA.

   Ejecutar:
     sqlcmd -S <servidor> -d SGUEES -U <user> -P <pass> -f 65001 -i SC_MOVIMIENTO_REQUISICION.sql
   ============================================================================= */
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

IF OBJECT_ID(N'dbo.SC_MOVIMIENTO_REQUISICION', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_MOVIMIENTO_REQUISICION
    (
        CORR_EMPRESA                 INT NOT NULL,
        CORR_MOVIMIENTO_PERSONAL     INT NOT NULL,
        CORR_REQUISICION_PERSONAL    INT NOT NULL,
        CORR_REQUISICION_CANDIDATO   INT NOT NULL,
        CONSTRAINT PK_SC_MOVIMIENTO_REQUISICION
            PRIMARY KEY CLUSTERED (CORR_EMPRESA, CORR_MOVIMIENTO_PERSONAL)
    );
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'UX_SC_MOVIMIENTO_REQUISICION_CANDIDATO'
      AND object_id = OBJECT_ID(N'dbo.SC_MOVIMIENTO_REQUISICION')
)
BEGIN
    CREATE UNIQUE INDEX UX_SC_MOVIMIENTO_REQUISICION_CANDIDATO
        ON dbo.SC_MOVIMIENTO_REQUISICION (CORR_EMPRESA, CORR_REQUISICION_CANDIDATO);
END;
GO

CREATE OR ALTER PROCEDURE dbo.PRAL_MTTO_SC_MOVIMIENTO_DESDE_REQUISICION
(
    @CORR_EMPRESA INT,
    @CORR_REQUISICION_PERSONAL INT,
    @CORR_REQUISICION_CANDIDATO INT,
    @LOGIN_SISTEMA VARCHAR(50),
    @ESTACION VARCHAR(50),
    @CORR_MOVIMIENTO_PERSONAL INT OUTPUT,
    @MENSAJE_ERROR NVARCHAR(500) OUTPUT
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    SET @CORR_MOVIMIENTO_PERSONAL = NULL;
    SET @MENSAJE_ERROR = NULL;

    IF EXISTS (
        SELECT 1
        FROM dbo.SC_MOVIMIENTO_REQUISICION
        WHERE CORR_EMPRESA = @CORR_EMPRESA
          AND CORR_REQUISICION_CANDIDATO = @CORR_REQUISICION_CANDIDATO
    )
    BEGIN
        SET @MENSAJE_ERROR = N'Este candidato ya tiene un movimiento de personal generado.';
        RETURN;
    END;

    DECLARE
        @NOMBRE NVARCHAR(250),
        @DOCUMENTO NVARCHAR(50),
        @CORR_UNIDAD INT,
        @CODIGO_UNIDAD NVARCHAR(50),
        @NOMBRE_UNIDAD NVARCHAR(200),
        @CORR_PUESTO INT,
        @NOMBRE_PUESTO NVARCHAR(200),
        @CORR_MODALIDAD INT,
        @NOMBRE_MODALIDAD NVARCHAR(100),
        @CORR_TIPO_CONTRATACION INT,
        @SALARIO DECIMAL(18, 2),
        @HORARIO NVARCHAR(250),
        @JUSTIFICACION NVARCHAR(1000),
        @GERENCIA NVARCHAR(200),
        @DISPLAY_UNIDAD NVARCHAR(150),
        @TIPO_MOVIMIENTO VARCHAR(20),
        @AHORA DATETIME = GETDATE();

    SELECT
        @NOMBRE = CAST(ISNULL(C.NOMBRE_PERSONA, N'') AS NVARCHAR(250)),
        @DOCUMENTO = CAST(ISNULL(C.DUI_PERSONA, N'') AS NVARCHAR(50))
    FROM dbo.V_SC_REQUISICION_PERSONAL_CANDIDATO AS C
    WHERE C.CORR_EMPRESA = @CORR_EMPRESA
      AND C.CORR_REQUISICION_CANDIDATO = @CORR_REQUISICION_CANDIDATO;

    IF @NOMBRE IS NULL OR LTRIM(RTRIM(@NOMBRE)) = N''
    BEGIN
        SET @MENSAJE_ERROR = N'No se encontró el candidato para generar el movimiento.';
        RETURN;
    END;

    SELECT
        @CORR_UNIDAD = R.CORR_UNIDAD,
        @CORR_PUESTO = R.CORR_PUESTO,
        @NOMBRE_PUESTO = CAST(ISNULL(P.NOMBRE_PUESTO, N'') AS NVARCHAR(200)),
        @CORR_MODALIDAD = R.CORR_TIPO_MODALIDAD,
        @NOMBRE_MODALIDAD = CAST(ISNULL(M.MODALIDAD_NOMBRE, N'') AS NVARCHAR(100)),
        @CORR_TIPO_CONTRATACION = R.CORR_TIPO_CONTRATACION,
        @SALARIO = R.SALARIO,
        @HORARIO = CAST(ISNULL(R.HORARIO, N'') AS NVARCHAR(250)),
        @JUSTIFICACION = CAST(ISNULL(R.JUSTIFICACION, N'') AS NVARCHAR(1000)),
        @CODIGO_UNIDAD = CAST(ISNULL(U.CODIGO_UNIDAD, N'') AS NVARCHAR(50)),
        @NOMBRE_UNIDAD = CAST(ISNULL(U.NOMBRE_UNIDAD, N'') AS NVARCHAR(200)),
        @GERENCIA = CAST(CASE
            WHEN PADRE.CORR_UNIDAD IS NULL THEN N''
            WHEN LTRIM(RTRIM(ISNULL(PADRE.CODIGO_UNIDAD, N''))) = N'' THEN ISNULL(PADRE.NOMBRE_UNIDAD, N'')
            ELSE LTRIM(RTRIM(PADRE.CODIGO_UNIDAD)) + N' - ' + ISNULL(PADRE.NOMBRE_UNIDAD, N'')
        END AS NVARCHAR(200))
    FROM dbo.SC_REQUISICION_PERSONAL AS R
    LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES AS U
        ON U.CORR_EMPRESA = R.CORR_EMPRESA
       AND U.CORR_UNIDAD = R.CORR_UNIDAD
    LEFT JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES AS PADRE
        ON PADRE.CORR_EMPRESA = U.CORR_EMPRESA
       AND PADRE.CORR_UNIDAD = U.CORR_UNIDAD_PADRE
    LEFT JOIN dbo.PLA_PUESTO AS P
        ON P.CORR_EMPRESA = R.CORR_EMPRESA
       AND P.CORR_PUESTO = R.CORR_PUESTO
    LEFT JOIN dbo.SC_TIPO_MODALIDAD AS M
        ON M.CORR_EMPRESA = R.CORR_EMPRESA
       AND M.CORR_TIPO_MODALIDAD = R.CORR_TIPO_MODALIDAD
    WHERE R.CORR_EMPRESA = @CORR_EMPRESA
      AND R.CORR_REQUISICION_PERSONAL = @CORR_REQUISICION_PERSONAL;

    IF @CORR_UNIDAD IS NULL
    BEGIN
        SET @MENSAJE_ERROR = N'No se encontró la requisición para generar el movimiento.';
        RETURN;
    END;

    SET @DISPLAY_UNIDAD = CASE
        WHEN LTRIM(RTRIM(ISNULL(@CODIGO_UNIDAD, N''))) = N'' THEN ISNULL(@NOMBRE_UNIDAD, N'')
        ELSE LTRIM(RTRIM(@CODIGO_UNIDAD)) + N' - ' + ISNULL(@NOMBRE_UNIDAD, N'')
    END;

    SET @TIPO_MOVIMIENTO = CASE
        WHEN @CORR_TIPO_CONTRATACION = 2 THEN 'EVENTUAL'
        ELSE 'PERMANENTE'
    END;

    BEGIN TRY
        BEGIN TRAN;

        SELECT @CORR_MOVIMIENTO_PERSONAL = ISNULL(MAX(CORR_MOVIMIENTO_PERSONAL), 0) + 1
        FROM dbo.SC_MOVIMIENTO_PERSONAL WITH (UPDLOCK, HOLDLOCK)
        WHERE CORR_EMPRESA = @CORR_EMPRESA;

        INSERT INTO dbo.SC_MOVIMIENTO_PERSONAL
        (
            CORR_EMPRESA, CORR_MOVIMIENTO_PERSONAL, FECHA_ELABORACION,
            ORIGEN_MOVIMIENTO, TIPO_MOVIMIENTO, ESTADO_MOVIMIENTO,
            CORR_EMPLEADO, NOMBRE_COMPLETO, NUMERO_ID,
            FECHA_INGRESO_PROPUESTA, FECHA_FINALIZACION,
            GERENCIA_ACTUAL, CORR_UNIDAD_ACTUAL, NOMBRE_UNIDAD_ACTUAL,
            CORR_PUESTO_ACTUAL, NOMBRE_PUESTO_ACTUAL, SALARIO_ACTUAL,
            CORR_TIPO_MODALIDAD_ACTUAL, NOMBRE_MODALIDAD_ACTUAL, HORARIO_ACTUAL,
            GERENCIA_PROPUESTA, CORR_UNIDAD_PROPUESTA, NOMBRE_UNIDAD_PROPUESTA,
            CORR_PUESTO_PROPUESTO, NOMBRE_PUESTO_PROPUESTO, SALARIO_PROPUESTO,
            CORR_TIPO_MODALIDAD_PROPUESTA, NOMBRE_MODALIDAD_PROPUESTA, HORARIO_PROPUESTO,
            JUSTIFICACION, FECHA_EFECTIVA, CONFIRMADO, USUARIO_CONFIRMA, FECHA_CONFIRMA,
            USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
        )
        VALUES
        (
            @CORR_EMPRESA, @CORR_MOVIMIENTO_PERSONAL, CAST(@AHORA AS DATE),
            'REQUISICION', @TIPO_MOVIMIENTO, 'AP',
            NULL, @NOMBRE, NULLIF(@DOCUMENTO, N''),
            NULL, NULL,
            NULL, NULL, NULL,
            NULL, NULL, NULL,
            NULL, NULL, NULL,
            NULLIF(@GERENCIA, N''), @CORR_UNIDAD, NULLIF(@DISPLAY_UNIDAD, N''),
            @CORR_PUESTO, NULLIF(@NOMBRE_PUESTO, N''), @SALARIO,
            @CORR_MODALIDAD, NULLIF(@NOMBRE_MODALIDAD, N''), NULLIF(@HORARIO, N''),
            NULLIF(@JUSTIFICACION, N''), NULL, 0, NULL, NULL,
            @LOGIN_SISTEMA, @ESTACION, @AHORA, @LOGIN_SISTEMA, @ESTACION, @AHORA
        );

        INSERT INTO dbo.SC_MOVIMIENTO_REQUISICION
        (
            CORR_EMPRESA, CORR_MOVIMIENTO_PERSONAL,
            CORR_REQUISICION_PERSONAL, CORR_REQUISICION_CANDIDATO
        )
        VALUES
        (
            @CORR_EMPRESA, @CORR_MOVIMIENTO_PERSONAL,
            @CORR_REQUISICION_PERSONAL, @CORR_REQUISICION_CANDIDATO
        );

        COMMIT TRAN;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRAN;
        SET @CORR_MOVIMIENTO_PERSONAL = NULL;
        SET @MENSAJE_ERROR = ERROR_MESSAGE();
    END CATCH;
END;
GO

PRINT N'OK: SC_MOVIMIENTO_REQUISICION + PRAL_MTTO_SC_MOVIMIENTO_DESDE_REQUISICION.';
GO
