SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/* =============================================================================
   Flujo 103 — movimiento de personal, tres niveles por la unidad del puesto.

   Oficial = SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES.ACTIVO = 1.
   Nivel 3 = ancestro con CORR_NIVEL = 3 (no una unidad fija).

   COORD    Puesto en una unidad activa de nivel mayor a 4 (coordinación).
            N1 jefe de esa unidad → N2 jefe del departamento (nivel 4) → N3.
   DIRECTO  Puesto en el departamento (nivel 4) y ese departamento tiene
            al menos un hijo ACTIVO. Al enviar se firman N1 y N2 y pasa a N3.
   SIN_COORD Departamento sin hijo activo. Una sola tarea al jefe del
            departamento: al aprobar quedan las firmas de N1 y de N2, y pasa a N3.

   Confirmar en pantalla solo cuando N3 deja el movimiento en AP (Aprobado GG).
   ============================================================================= */
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @EMP INT = 1;
DECLARE @TIPO INT;
DECLARE @FLUJO INT;
DECLARE @PASO_CREAR INT;
DECLARE @PASO_N1 INT;
DECLARE @PASO_N2 INT;
DECLARE @PASO_N3 INT;
DECLARE @EST_BORRADOR INT;
DECLARE @EST_EN_APROB INT;
DECLARE @EST_DEV_JI INT;
DECLARE @EST_APR_JI INT;
DECLARE @EST_REC_JI INT;
DECLARE @EST_APR_JU INT;
DECLARE @EST_DEV_JU INT;
DECLARE @EST_REC_JU INT;
DECLARE @EST_APR_GG INT;
DECLARE @EST_DEV_GG INT;
DECLARE @EST_REC_GG INT;
DECLARE @NUEVO_EST INT;
DECLARE @NUEVO_PASO INT;

SELECT @TIPO = CORR_TIPO_DOCUMENTO
FROM dbo.SEG_FLUJO_TIPO_DOCUMENTO
WHERE CORR_EMPRESA = @EMP
  AND CODIGO_OPCION = N'SC_MOVIMIENTO_PERSONAL'
  AND ACTIVO = 1;

SELECT @FLUJO = CORR_FLUJO_PROCESO
FROM dbo.SEG_FLUJO_PROCESO
WHERE CORR_EMPRESA = @EMP
  AND CORR_TIPO_DOCUMENTO = @TIPO
  AND ACTIVO = 1
  AND ES_DEFECTO = 1;

IF @TIPO IS NULL OR @FLUJO IS NULL
BEGIN
	RAISERROR(N'No hay tipo o flujo defecto para SC_MOVIMIENTO_PERSONAL.', 16, 1);
	RETURN;
END

BEGIN TRAN;

UPDATE dbo.SEG_FLUJO_ESTADO
SET NOMBRE_ESTADO = N'Aprobado JI',
	DESCRIPCION = N'Aprobado por el jefe inmediato (nivel 1). El circuito sigue.',
	ES_FINAL = 0,
	ES_INICIAL = 0,
	USUARIO_ACTU = N'SISTEMA',
	FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP
  AND CORR_TIPO_DOCUMENTO = @TIPO
  AND (NOMBRE_ESTADO IN (N'Aprobada JI', N'Aprobado JI'));

UPDATE dbo.SEG_FLUJO_ESTADO
SET NOMBRE_ESTADO = N'Aprobado GG',
	DESCRIPCION = N'Aprobado por gerencia general (nivel 3). Habilita Confirmar.',
	ES_FINAL = 1,
	ES_INICIAL = 0,
	USUARIO_ACTU = N'SISTEMA',
	FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP
  AND CORR_TIPO_DOCUMENTO = @TIPO
  AND (NOMBRE_ESTADO IN (N'Aprobada GG', N'Aprobado GG'));

UPDATE dbo.SEG_FLUJO_ESTADO
SET DESCRIPCION = N'Devuelto por el jefe inmediato (nivel 1).',
	ES_FINAL = 0,
	USUARIO_ACTU = N'SISTEMA',
	FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Devuelta JI';

UPDATE dbo.SEG_FLUJO_ESTADO
SET DESCRIPCION = N'Rechazado por gerencia general (nivel 3).',
	ES_FINAL = 1,
	USUARIO_ACTU = N'SISTEMA',
	FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Rechazada GG';

DECLARE @ALTAS TABLE (NOMBRE NVARCHAR(50), DESCRIPCION NVARCHAR(255), ES_FINAL BIT);
INSERT INTO @ALTAS (NOMBRE, DESCRIPCION, ES_FINAL) VALUES
	(N'Rechazada JI', N'Rechazado por el jefe inmediato (nivel 1).', 1),
	(N'Aprobado JU', N'Aprobado por el jefe de la unidad (nivel 2). El circuito sigue.', 0),
	(N'Devuelta JU', N'Devuelto por el jefe de la unidad (nivel 2).', 0),
	(N'Rechazada JU', N'Rechazado por el jefe de la unidad (nivel 2).', 1),
	(N'Devuelta GG', N'Devuelto por gerencia general (nivel 3).', 0);

DECLARE @NOM NVARCHAR(50), @DESC NVARCHAR(255), @FIN BIT;
DECLARE altas CURSOR LOCAL FAST_FORWARD FOR SELECT NOMBRE, DESCRIPCION, ES_FINAL FROM @ALTAS;
OPEN altas;
FETCH NEXT FROM altas INTO @NOM, @DESC, @FIN;
WHILE @@FETCH_STATUS = 0
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM dbo.SEG_FLUJO_ESTADO
		WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = @NOM
	)
	BEGIN
		SELECT @NUEVO_EST = ISNULL(MAX(CORR_ESTADO), 0) + 1 FROM dbo.SEG_FLUJO_ESTADO;
		INSERT INTO dbo.SEG_FLUJO_ESTADO (
			CORR_EMPRESA, CORR_ESTADO, CORR_TIPO_DOCUMENTO, NOMBRE_ESTADO, DESCRIPCION,
			ES_INICIAL, ES_FINAL, ACTIVO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA
		) VALUES (
			@EMP, @NUEVO_EST, @TIPO, @NOM, @DESC,
			0, @FIN, 1, N'SISTEMA', N'SCRIPT', GETDATE()
		);
	END
	ELSE
	BEGIN
		UPDATE dbo.SEG_FLUJO_ESTADO
		SET DESCRIPCION = @DESC, ES_FINAL = @FIN, ES_INICIAL = 0, ACTIVO = 1,
			USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
		WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = @NOM;
	END
	FETCH NEXT FROM altas INTO @NOM, @DESC, @FIN;
END
CLOSE altas;
DEALLOCATE altas;

SELECT @EST_BORRADOR = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Borrador';
SELECT @EST_EN_APROB = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO LIKE N'En Aprobaci%';
SELECT @EST_DEV_JI = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Devuelta JI';
SELECT @EST_APR_JI = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Aprobado JI';
SELECT @EST_REC_JI = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Rechazada JI';
SELECT @EST_APR_JU = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Aprobado JU';
SELECT @EST_DEV_JU = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Devuelta JU';
SELECT @EST_REC_JU = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Rechazada JU';
SELECT @EST_APR_GG = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Aprobado GG';
SELECT @EST_DEV_GG = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Devuelta GG';
SELECT @EST_REC_GG = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Rechazada GG';

IF @EST_BORRADOR IS NULL OR @EST_EN_APROB IS NULL OR @EST_DEV_JI IS NULL OR @EST_APR_JI IS NULL
	OR @EST_REC_JI IS NULL OR @EST_APR_JU IS NULL OR @EST_DEV_JU IS NULL OR @EST_REC_JU IS NULL
	OR @EST_APR_GG IS NULL OR @EST_DEV_GG IS NULL OR @EST_REC_GG IS NULL
BEGIN
	ROLLBACK TRAN;
	RAISERROR(N'Faltan estados del flujo 103.', 16, 1);
	RETURN;
END

SELECT @PASO_CREAR = CORR_PASO FROM dbo.SEG_FLUJO_PASO WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND ORDEN = 1;
SELECT @PASO_N1 = CORR_PASO FROM dbo.SEG_FLUJO_PASO WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND ORDEN = 2;

SELECT @PASO_N2 = CORR_PASO
FROM dbo.SEG_FLUJO_PASO
WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND NOMBRE_PASO = N'Aprobación jefe de unidad';

/* El índice único de ORDEN no permite dos pasos en 3. La gerencia pasa a 4 antes de crear el nivel 2. */
UPDATE dbo.SEG_FLUJO_PASO
SET ORDEN = 4,
	USUARIO_ACTU = N'SISTEMA',
	FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP
  AND CORR_FLUJO_PROCESO = @FLUJO
  AND ORDEN = 3
  AND (@PASO_N2 IS NULL OR CORR_PASO <> @PASO_N2);

IF @PASO_N2 IS NULL
BEGIN
	SELECT @NUEVO_PASO = ISNULL(MAX(CORR_PASO), 0) + 1 FROM dbo.SEG_FLUJO_PASO;
	INSERT INTO dbo.SEG_FLUJO_PASO (
		CORR_EMPRESA, CORR_PASO, CORR_FLUJO_PROCESO, ORDEN, NOMBRE_PASO,
		CORR_ACTOR_ORIGEN, CORR_ESTADO_ORIGEN, CORR_ACTOR_DESTINO, CORR_UNIDAD_DESTINO,
		PERMITE_AUTO_APROBACION, USUARIO_CREA, ESTACION_CREA, FECHA_CREA
	) VALUES (
		@EMP, @NUEVO_PASO, @FLUJO, 3, N'Aprobación jefe de unidad',
		3, NULL, 2, NULL,
		0, N'SISTEMA', N'SCRIPT', GETDATE()
	);
	SET @PASO_N2 = @NUEVO_PASO;
END

SELECT @PASO_N3 = CORR_PASO
FROM dbo.SEG_FLUJO_PASO
WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND ORDEN = 4;

UPDATE dbo.SEG_FLUJO_PASO
SET NOMBRE_PASO = N'Crear movimiento',
	CORR_ACTOR_ORIGEN = 1,
	CORR_ACTOR_DESTINO = 2,
	CORR_UNIDAD_DESTINO = NULL,
	CORR_ESTADO_ORIGEN = @EST_BORRADOR,
	PERMITE_AUTO_APROBACION = 0,
	ORDEN = 1,
	USUARIO_ACTU = N'SISTEMA',
	FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_PASO = @PASO_CREAR;

UPDATE dbo.SEG_FLUJO_PASO
SET NOMBRE_PASO = N'Aprobación jefe inmediato',
	CORR_ACTOR_ORIGEN = 2,
	CORR_ACTOR_DESTINO = 2,
	CORR_UNIDAD_DESTINO = NULL,
	CORR_ESTADO_ORIGEN = NULL,
	PERMITE_AUTO_APROBACION = 1,
	ORDEN = 2,
	USUARIO_ACTU = N'SISTEMA',
	FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_PASO = @PASO_N1;

UPDATE dbo.SEG_FLUJO_PASO
SET NOMBRE_PASO = N'Aprobación jefe de unidad',
	CORR_ACTOR_ORIGEN = 3,
	CORR_ACTOR_DESTINO = 2,
	CORR_UNIDAD_DESTINO = NULL,
	CORR_ESTADO_ORIGEN = NULL,
	PERMITE_AUTO_APROBACION = 0,
	ORDEN = 3,
	USUARIO_ACTU = N'SISTEMA',
	FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_PASO = @PASO_N2;

UPDATE dbo.SEG_FLUJO_PASO
SET NOMBRE_PASO = N'Aprobación gerencia general',
	CORR_ACTOR_ORIGEN = 2,
	CORR_ACTOR_DESTINO = 1,
	CORR_UNIDAD_DESTINO = NULL,
	CORR_ESTADO_ORIGEN = NULL,
	PERMITE_AUTO_APROBACION = 0,
	ORDEN = 4,
	USUARIO_ACTU = N'SISTEMA',
	FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_PASO = @PASO_N3;

/* Crear: guardar en borrador y enviar al nivel 1. */
UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO
SET CORR_ESTADO_DESTINO = @EST_BORRADOR, CORR_TIPO_MOVIMIENTO = 4, CORR_TIPO_NOTIFICACION = 5,
	CORR_PASO_DESTINO = @PASO_N1, PERMITIDO = 1, ACTIVO = 1
WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_CREAR AND CORR_ACCION = 1;

UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO
SET CORR_ESTADO_DESTINO = @EST_EN_APROB, CORR_TIPO_MOVIMIENTO = 1, CORR_TIPO_NOTIFICACION = 2,
	CORR_PASO_DESTINO = @PASO_N1, PERMITIDO = 1, ACTIVO = 1
WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_CREAR AND CORR_ACCION = 2;

/* Nivel 1 */
UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO
SET CORR_ESTADO_DESTINO = @EST_DEV_JI, CORR_TIPO_MOVIMIENTO = 2, CORR_TIPO_NOTIFICACION = 3,
	CORR_PASO_DESTINO = @PASO_CREAR, PERMITIDO = 1, ACTIVO = 1
WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N1 AND CORR_ACCION = 1;

UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO
SET CORR_ESTADO_DESTINO = @EST_APR_JI, CORR_TIPO_MOVIMIENTO = 1, CORR_TIPO_NOTIFICACION = 2,
	CORR_PASO_DESTINO = @PASO_N2, PERMITIDO = 1, ACTIVO = 1
WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N1 AND CORR_ACCION = 2;

IF NOT EXISTS (
	SELECT 1 FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N1 AND CORR_ACCION = 3
)
	INSERT INTO dbo.SEG_FLUJO_PASO_ACCION_ESTADO (
		CORR_EMPRESA, CORR_FLUJO_PROCESO, CORR_PASO, CORR_ACCION, CORR_ESTADO_DESTINO,
		PERMITIDO, CORR_TIPO_MOVIMIENTO, CORR_TIPO_NOTIFICACION, CORR_PASO_DESTINO, ACTIVO,
		USUARIO_CREA, ESTACION_CREA, FECHA_CREA
	) VALUES (
		@EMP, @FLUJO, @PASO_N1, 3, @EST_REC_JI,
		1, 3, 3, NULL, 1,
		N'SISTEMA', N'SCRIPT', GETDATE()
	);
ELSE
	UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO
	SET CORR_ESTADO_DESTINO = @EST_REC_JI, CORR_TIPO_MOVIMIENTO = 3, CORR_TIPO_NOTIFICACION = 3,
		CORR_PASO_DESTINO = NULL, PERMITIDO = 1, ACTIVO = 1
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N1 AND CORR_ACCION = 3;

/* Nivel 2 */
IF NOT EXISTS (
	SELECT 1 FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N2 AND CORR_ACCION = 1
)
	INSERT INTO dbo.SEG_FLUJO_PASO_ACCION_ESTADO (
		CORR_EMPRESA, CORR_FLUJO_PROCESO, CORR_PASO, CORR_ACCION, CORR_ESTADO_DESTINO,
		PERMITIDO, CORR_TIPO_MOVIMIENTO, CORR_TIPO_NOTIFICACION, CORR_PASO_DESTINO, ACTIVO,
		USUARIO_CREA, ESTACION_CREA, FECHA_CREA
	) VALUES
	(@EMP, @FLUJO, @PASO_N2, 1, @EST_DEV_JU, 1, 2, 3, @PASO_CREAR, 1, N'SISTEMA', N'SCRIPT', GETDATE()),
	(@EMP, @FLUJO, @PASO_N2, 2, @EST_APR_JU, 1, 1, 2, @PASO_N3, 1, N'SISTEMA', N'SCRIPT', GETDATE()),
	(@EMP, @FLUJO, @PASO_N2, 3, @EST_REC_JU, 1, 3, 3, NULL, 1, N'SISTEMA', N'SCRIPT', GETDATE());
ELSE
BEGIN
	UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO SET CORR_ESTADO_DESTINO = @EST_DEV_JU, CORR_TIPO_MOVIMIENTO = 2, CORR_TIPO_NOTIFICACION = 3, CORR_PASO_DESTINO = @PASO_CREAR, PERMITIDO = 1, ACTIVO = 1
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N2 AND CORR_ACCION = 1;
	UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO SET CORR_ESTADO_DESTINO = @EST_APR_JU, CORR_TIPO_MOVIMIENTO = 1, CORR_TIPO_NOTIFICACION = 2, CORR_PASO_DESTINO = @PASO_N3, PERMITIDO = 1, ACTIVO = 1
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N2 AND CORR_ACCION = 2;
	UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO SET CORR_ESTADO_DESTINO = @EST_REC_JU, CORR_TIPO_MOVIMIENTO = 3, CORR_TIPO_NOTIFICACION = 3, CORR_PASO_DESTINO = NULL, PERMITIDO = 1, ACTIVO = 1
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N2 AND CORR_ACCION = 3;
END

/* Nivel 3 */
UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO
SET CORR_ESTADO_DESTINO = @EST_REC_GG, CORR_TIPO_MOVIMIENTO = 3, CORR_TIPO_NOTIFICACION = 3,
	CORR_PASO_DESTINO = NULL, PERMITIDO = 1, ACTIVO = 1
WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N3 AND CORR_ACCION = 1;

UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO
SET CORR_ESTADO_DESTINO = @EST_APR_GG, CORR_TIPO_MOVIMIENTO = 3, CORR_TIPO_NOTIFICACION = 3,
	CORR_PASO_DESTINO = NULL, PERMITIDO = 1, ACTIVO = 1
WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N3 AND CORR_ACCION = 2;

IF NOT EXISTS (
	SELECT 1 FROM dbo.SEG_FLUJO_PASO_ACCION_ESTADO
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N3 AND CORR_ACCION = 3
)
	INSERT INTO dbo.SEG_FLUJO_PASO_ACCION_ESTADO (
		CORR_EMPRESA, CORR_FLUJO_PROCESO, CORR_PASO, CORR_ACCION, CORR_ESTADO_DESTINO,
		PERMITIDO, CORR_TIPO_MOVIMIENTO, CORR_TIPO_NOTIFICACION, CORR_PASO_DESTINO, ACTIVO,
		USUARIO_CREA, ESTACION_CREA, FECHA_CREA
	) VALUES (
		@EMP, @FLUJO, @PASO_N3, 3, @EST_DEV_GG,
		1, 2, 3, @PASO_CREAR, 1,
		N'SISTEMA', N'SCRIPT', GETDATE()
	);
ELSE
	UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO
	SET CORR_ESTADO_DESTINO = @EST_DEV_GG, CORR_TIPO_MOVIMIENTO = 2, CORR_TIPO_NOTIFICACION = 3,
		CORR_PASO_DESTINO = @PASO_CREAR, PERMITIDO = 1, ACTIVO = 1
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND CORR_PASO = @PASO_N3 AND CORR_ACCION = 3;

/* Borradores ya abiertos: la unidad del circuito es el puesto del solicitante, no la jefatura. */
UPDATE I
SET I.CORR_UNIDAD_DOCUMENTO = P.CORR_UNIDAD,
	I.USUARIO_ACTU = N'SISTEMA',
	I.FECHA_ACTU = GETDATE()
FROM dbo.SEG_FLUJO_INSTANCIA AS I
INNER JOIN dbo.SEG_FLUJO_PASO AS PA
	ON PA.CORR_EMPRESA = I.CORR_EMPRESA AND PA.CORR_PASO = I.CORR_PASO_ACTUAL AND PA.ORDEN = 1
INNER JOIN dbo.SEG_FLUJO_ESTADO AS ES
	ON ES.CORR_EMPRESA = I.CORR_EMPRESA AND ES.CORR_ESTADO = I.CORR_ESTADO_ACTUAL AND ES.ES_INICIAL = 1
CROSS APPLY (
	SELECT TOP 1 EP.CORR_UNIDAD
	FROM dbo.GEN_PERSONA_USUARIO AS PU
	INNER JOIN dbo.GEN_EMPLEADO AS E
		ON E.CORR_PERSONA = PU.CORR_PERSONA AND E.CORR_EMPRESA = I.CORR_EMPRESA
	INNER JOIN dbo.GEN_EMPLEADO_PUESTO AS EP
		ON EP.CORR_EMPRESA = E.CORR_EMPRESA AND EP.CORR_EMPLEADO = E.CORR_EMPLEADO
	INNER JOIN dbo.SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES AS UN
		ON UN.CORR_EMPRESA = EP.CORR_EMPRESA AND UN.CORR_UNIDAD = EP.CORR_UNIDAD
	WHERE LTRIM(RTRIM(PU.LOGIN_SISTEMA)) = LTRIM(RTRIM(I.USUARIO_CREA))
	ORDER BY CASE WHEN UN.ACTIVO = 1 THEN 0 ELSE 1 END, UN.CORR_NIVEL DESC, EP.CORR_UNIDAD DESC
) AS P
WHERE I.CORR_EMPRESA = @EMP
  AND I.CORR_TIPO_DOCUMENTO = @TIPO
  AND I.ACTIVO = 1
  AND ISNULL(P.CORR_UNIDAD, 0) > 0
  AND ISNULL(I.CORR_UNIDAD_DOCUMENTO, 0) <> P.CORR_UNIDAD;

COMMIT TRAN;

SELECT P.ORDEN, P.CORR_PASO, P.NOMBRE_PASO, P.CORR_ACTOR_ORIGEN, P.CORR_ACTOR_DESTINO, P.PERMITE_AUTO_APROBACION,
	A.CORR_ACCION, E.NOMBRE_ESTADO, A.CORR_TIPO_MOVIMIENTO, A.CORR_TIPO_NOTIFICACION, A.CORR_PASO_DESTINO
FROM dbo.SEG_FLUJO_PASO AS P
LEFT JOIN dbo.SEG_FLUJO_PASO_ACCION_ESTADO AS A
	ON A.CORR_EMPRESA = P.CORR_EMPRESA AND A.CORR_FLUJO_PROCESO = P.CORR_FLUJO_PROCESO AND A.CORR_PASO = P.CORR_PASO AND A.ACTIVO = 1
LEFT JOIN dbo.SEG_FLUJO_ESTADO AS E
	ON E.CORR_EMPRESA = A.CORR_EMPRESA AND E.CORR_ESTADO = A.CORR_ESTADO_DESTINO
WHERE P.CORR_EMPRESA = @EMP AND P.CORR_FLUJO_PROCESO = @FLUJO
ORDER BY P.ORDEN, A.CORR_ACCION;
GO
