SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

IF OBJECT_ID(N'dbo.SC_PERSONA_DATOS', N'U') IS NULL
    THROW 50000, N'No existe dbo.SC_PERSONA_DATOS. Ejecute primero los scripts de rename.', 1;
GO

/* Amplía el padre existente. NUP no forma parte del esquema. FOTO_URL se agregó en BD. */
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'NOMBRE1') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD NOMBRE1 varchar(50) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'NOMBRE2') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD NOMBRE2 varchar(50) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'APELLIDO1') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD APELLIDO1 varchar(50) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'APELLIDO2') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD APELLIDO2 varchar(50) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'FECHA_NACIMIENTO') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD FECHA_NACIMIENTO date NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'EDAD') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD EDAD int NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'ESTADO_CIVIL') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD ESTADO_CIVIL varchar(50) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'NACIONALIDAD') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD NACIONALIDAD varchar(100) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'CORREO') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD CORREO varchar(254) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'CELULAR') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD CELULAR varchar(25) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'TELEFONO') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD TELEFONO varchar(25) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'DIRECCION') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD DIRECCION varchar(500) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'DUI') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD DUI varchar(25) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'PASAPORTE') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD PASAPORTE varchar(50) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'ISSS') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD ISSS varchar(50) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'AFP') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD AFP varchar(50) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'NOMBRE_AFP') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD NOMBRE_AFP varchar(100) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'LICENCIA') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD LICENCIA varchar(50) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'PLAZA_SOLICITADA') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD PLAZA_SOLICITADA varchar(250) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'PRETENSION_SALARIAL') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD PRETENSION_SALARIAL int NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'DISPONIBILIDAD') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD DISPONIBILIDAD varchar(100) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'RELIGION') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD RELIGION varchar(100) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'IGLESIA') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD IGLESIA varchar(250) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'DIRECCION_IGLESIA') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD DIRECCION_IGLESIA varchar(500) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'ES_CONTRIBUYENTE_CCF') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD ES_CONTRIBUYENTE_CCF bit NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'ES_JUBILADO') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD ES_JUBILADO bit NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'POSEE_DISCAPACIDAD') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD POSEE_DISCAPACIDAD bit NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'TIPO_DISCAPACIDAD') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD TIPO_DISCAPACIDAD varchar(250) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'EMERGENCIA_NOMBRE') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD EMERGENCIA_NOMBRE varchar(150) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'EMERGENCIA_PARENTESCO') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD EMERGENCIA_PARENTESCO varchar(100) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'EMERGENCIA_TELEFONO') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD EMERGENCIA_TELEFONO varchar(25) NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'TIENE_FAMILIARES_UEES') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD TIENE_FAMILIARES_UEES bit NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'DECLARA_VERDAD') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD DECLARA_VERDAD bit NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'AUTORIZA_VERIFICACION') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD AUTORIZA_VERIFICACION bit NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'FECHA_DECLARACION') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD FECHA_DECLARACION datetime NULL;
IF COL_LENGTH(N'dbo.SC_PERSONA_DATOS', N'FIRMA_ELECTRONICA') IS NULL ALTER TABLE dbo.SC_PERSONA_DATOS ADD FIRMA_ELECTRONICA varchar(250) NULL;
GO

/* Normaliza obligatorios sin impedir la migración de registros históricos. */
UPDATE dbo.SC_PERSONA_DATOS
SET NOMBRE1 = ISNULL(NOMBRE1, ''),
    APELLIDO1 = ISNULL(APELLIDO1, ''),
    FECHA_NACIMIENTO = ISNULL(FECHA_NACIMIENTO, CONVERT(date, '19000101', 112)),
    EDAD = ISNULL(EDAD, 0),
    CORREO = ISNULL(CORREO, ''),
    CELULAR = ISNULL(CELULAR, ''),
    DIRECCION = ISNULL(DIRECCION, ''),
    DUI = ISNULL(DUI, ''),
    PRETENSION_SALARIAL = ISNULL(PRETENSION_SALARIAL, 0),
    ES_CONTRIBUYENTE_CCF = ISNULL(ES_CONTRIBUYENTE_CCF, 0),
    ES_JUBILADO = ISNULL(ES_JUBILADO, 0),
    POSEE_DISCAPACIDAD = ISNULL(POSEE_DISCAPACIDAD, 0),
    EMERGENCIA_NOMBRE = ISNULL(EMERGENCIA_NOMBRE, ''),
    EMERGENCIA_TELEFONO = ISNULL(EMERGENCIA_TELEFONO, ''),
    TIENE_FAMILIARES_UEES = ISNULL(TIENE_FAMILIARES_UEES, 0),
    DECLARA_VERDAD = ISNULL(DECLARA_VERDAD, 0),
    AUTORIZA_VERIFICACION = ISNULL(AUTORIZA_VERIFICACION, 0),
    FECHA_DECLARACION = ISNULL(FECHA_DECLARACION, CONVERT(datetime, '19000101', 112))
WHERE NOMBRE1 IS NULL OR APELLIDO1 IS NULL OR FECHA_NACIMIENTO IS NULL OR EDAD IS NULL
   OR CORREO IS NULL OR CELULAR IS NULL OR DIRECCION IS NULL OR DUI IS NULL
   OR PRETENSION_SALARIAL IS NULL OR ES_CONTRIBUYENTE_CCF IS NULL OR ES_JUBILADO IS NULL
   OR POSEE_DISCAPACIDAD IS NULL OR EMERGENCIA_NOMBRE IS NULL OR EMERGENCIA_TELEFONO IS NULL
   OR TIENE_FAMILIARES_UEES IS NULL OR DECLARA_VERDAD IS NULL
   OR AUTORIZA_VERIFICACION IS NULL OR FECHA_DECLARACION IS NULL;

ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN NOMBRE1 varchar(50) NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN APELLIDO1 varchar(50) NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN FECHA_NACIMIENTO date NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN EDAD int NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN CORREO varchar(254) NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN CELULAR varchar(25) NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN DIRECCION varchar(500) NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN DUI varchar(25) NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN PRETENSION_SALARIAL int NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN ES_CONTRIBUYENTE_CCF bit NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN ES_JUBILADO bit NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN POSEE_DISCAPACIDAD bit NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN EMERGENCIA_NOMBRE varchar(150) NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN EMERGENCIA_TELEFONO varchar(25) NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN TIENE_FAMILIARES_UEES bit NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN DECLARA_VERDAD bit NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN AUTORIZA_VERIFICACION bit NOT NULL;
ALTER TABLE dbo.SC_PERSONA_DATOS ALTER COLUMN FECHA_DECLARACION datetime NOT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'dbo.SC_PERSONA_DATOS') AND parent_column_id = COLUMNPROPERTY(OBJECT_ID(N'dbo.SC_PERSONA_DATOS'), N'EDAD', 'ColumnId'))
    ALTER TABLE dbo.SC_PERSONA_DATOS ADD CONSTRAINT DF_SC_PERSONA_DATOS_EDAD DEFAULT (0) FOR EDAD;
IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'dbo.SC_PERSONA_DATOS') AND parent_column_id = COLUMNPROPERTY(OBJECT_ID(N'dbo.SC_PERSONA_DATOS'), N'PRETENSION_SALARIAL', 'ColumnId'))
    ALTER TABLE dbo.SC_PERSONA_DATOS ADD CONSTRAINT DF_SC_PERSONA_DATOS_PRETENSION_SALARIAL DEFAULT (0) FOR PRETENSION_SALARIAL;
IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'dbo.SC_PERSONA_DATOS') AND parent_column_id = COLUMNPROPERTY(OBJECT_ID(N'dbo.SC_PERSONA_DATOS'), N'ES_CONTRIBUYENTE_CCF', 'ColumnId'))
    ALTER TABLE dbo.SC_PERSONA_DATOS ADD CONSTRAINT DF_SC_PERSONA_DATOS_ES_CONTRIBUYENTE_CCF DEFAULT (0) FOR ES_CONTRIBUYENTE_CCF;
IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'dbo.SC_PERSONA_DATOS') AND parent_column_id = COLUMNPROPERTY(OBJECT_ID(N'dbo.SC_PERSONA_DATOS'), N'ES_JUBILADO', 'ColumnId'))
    ALTER TABLE dbo.SC_PERSONA_DATOS ADD CONSTRAINT DF_SC_PERSONA_DATOS_ES_JUBILADO DEFAULT (0) FOR ES_JUBILADO;
IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'dbo.SC_PERSONA_DATOS') AND parent_column_id = COLUMNPROPERTY(OBJECT_ID(N'dbo.SC_PERSONA_DATOS'), N'POSEE_DISCAPACIDAD', 'ColumnId'))
    ALTER TABLE dbo.SC_PERSONA_DATOS ADD CONSTRAINT DF_SC_PERSONA_DATOS_POSEE_DISCAPACIDAD DEFAULT (0) FOR POSEE_DISCAPACIDAD;
IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'dbo.SC_PERSONA_DATOS') AND parent_column_id = COLUMNPROPERTY(OBJECT_ID(N'dbo.SC_PERSONA_DATOS'), N'TIENE_FAMILIARES_UEES', 'ColumnId'))
    ALTER TABLE dbo.SC_PERSONA_DATOS ADD CONSTRAINT DF_SC_PERSONA_DATOS_TIENE_FAMILIARES_UEES DEFAULT (0) FOR TIENE_FAMILIARES_UEES;
IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'dbo.SC_PERSONA_DATOS') AND parent_column_id = COLUMNPROPERTY(OBJECT_ID(N'dbo.SC_PERSONA_DATOS'), N'DECLARA_VERDAD', 'ColumnId'))
    ALTER TABLE dbo.SC_PERSONA_DATOS ADD CONSTRAINT DF_SC_PERSONA_DATOS_DECLARA_VERDAD DEFAULT (0) FOR DECLARA_VERDAD;
IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID(N'dbo.SC_PERSONA_DATOS') AND parent_column_id = COLUMNPROPERTY(OBJECT_ID(N'dbo.SC_PERSONA_DATOS'), N'AUTORIZA_VERIFICACION', 'ColumnId'))
    ALTER TABLE dbo.SC_PERSONA_DATOS ADD CONSTRAINT DF_SC_PERSONA_DATOS_AUTORIZA_VERIFICACION DEFAULT (0) FOR AUTORIZA_VERIFICACION;
GO

IF OBJECT_ID(N'dbo.SC_PERSONA_FAMILIAR', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_PERSONA_FAMILIAR (
        CORR_EMPRESA int NOT NULL, CORR_PERSONA_DATOS int NOT NULL, CORR_FAMILIAR int NOT NULL,
        TIPO varchar(50) NULL, NOMBRE varchar(150) NULL, DOMICILIO varchar(500) NULL,
        FECHA_NACIMIENTO date NULL, OCUPACION varchar(150) NULL,
        USUARIO_CREA varchar(30) NOT NULL, ESTACION_CREA varchar(50) NOT NULL, FECHA_CREA datetime NOT NULL,
        USUARIO_ACTU varchar(30) NOT NULL, ESTACION_ACTU varchar(50) NOT NULL, FECHA_ACTU datetime NOT NULL,
        CONSTRAINT PK_SC_PERSONA_FAMILIAR PRIMARY KEY CLUSTERED (CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_FAMILIAR),
        CONSTRAINT FK_SC_PERSONA_FAMILIAR_SC_PERSONA_DATOS FOREIGN KEY (CORR_EMPRESA, CORR_PERSONA_DATOS)
            REFERENCES dbo.SC_PERSONA_DATOS (CORR_EMPRESA, CORR_PERSONA_DATOS)
    );
END;

IF OBJECT_ID(N'dbo.SC_PERSONA_HIJOS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_PERSONA_HIJOS (
        CORR_EMPRESA int NOT NULL, CORR_PERSONA_DATOS int NOT NULL, CORR_HIJO int NOT NULL,
        NOMBRE varchar(150) NULL, EDAD int NULL, SEXO varchar(25) NULL, FECHA_NACIMIENTO date NULL,
        USUARIO_CREA varchar(30) NOT NULL, ESTACION_CREA varchar(50) NOT NULL, FECHA_CREA datetime NOT NULL,
        USUARIO_ACTU varchar(30) NOT NULL, ESTACION_ACTU varchar(50) NOT NULL, FECHA_ACTU datetime NOT NULL,
        CONSTRAINT PK_SC_PERSONA_HIJOS PRIMARY KEY CLUSTERED (CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_HIJO),
        CONSTRAINT FK_SC_PERSONA_HIJOS_SC_PERSONA_DATOS FOREIGN KEY (CORR_EMPRESA, CORR_PERSONA_DATOS)
            REFERENCES dbo.SC_PERSONA_DATOS (CORR_EMPRESA, CORR_PERSONA_DATOS)
    );
END;

IF OBJECT_ID(N'dbo.SC_PERSONA_ESTUDIO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_PERSONA_ESTUDIO (
        CORR_EMPRESA int NOT NULL, CORR_PERSONA_DATOS int NOT NULL, CORR_ESTUDIO int NOT NULL,
        NIVEL varchar(100) NULL, INSTITUCION varchar(250) NULL, DESDE date NULL, HASTA date NULL, TITULO varchar(250) NULL,
        USUARIO_CREA varchar(30) NOT NULL, ESTACION_CREA varchar(50) NOT NULL, FECHA_CREA datetime NOT NULL,
        USUARIO_ACTU varchar(30) NOT NULL, ESTACION_ACTU varchar(50) NOT NULL, FECHA_ACTU datetime NOT NULL,
        CONSTRAINT PK_SC_PERSONA_ESTUDIO PRIMARY KEY CLUSTERED (CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_ESTUDIO),
        CONSTRAINT FK_SC_PERSONA_ESTUDIO_SC_PERSONA_DATOS FOREIGN KEY (CORR_EMPRESA, CORR_PERSONA_DATOS)
            REFERENCES dbo.SC_PERSONA_DATOS (CORR_EMPRESA, CORR_PERSONA_DATOS)
    );
END;

IF OBJECT_ID(N'dbo.SC_PERSONA_IDIOMAS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_PERSONA_IDIOMAS (
        CORR_EMPRESA int NOT NULL, CORR_PERSONA_DATOS int NOT NULL, CORR_IDIOMA int NOT NULL,
        IDIOMA varchar(100) NULL, NIVEL varchar(100) NULL,
        USUARIO_CREA varchar(30) NOT NULL, ESTACION_CREA varchar(50) NOT NULL, FECHA_CREA datetime NOT NULL,
        USUARIO_ACTU varchar(30) NOT NULL, ESTACION_ACTU varchar(50) NOT NULL, FECHA_ACTU datetime NOT NULL,
        CONSTRAINT PK_SC_PERSONA_IDIOMAS PRIMARY KEY CLUSTERED (CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_IDIOMA),
        CONSTRAINT FK_SC_PERSONA_IDIOMAS_SC_PERSONA_DATOS FOREIGN KEY (CORR_EMPRESA, CORR_PERSONA_DATOS)
            REFERENCES dbo.SC_PERSONA_DATOS (CORR_EMPRESA, CORR_PERSONA_DATOS)
    );
END;

IF OBJECT_ID(N'dbo.SC_PERSONA_COMPETENCIAS_TECNICAS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_PERSONA_COMPETENCIAS_TECNICAS (
        CORR_EMPRESA int NOT NULL, CORR_PERSONA_DATOS int NOT NULL, CORR_COMPETENCIA_TECNICA int NOT NULL,
        HERRAMIENTA varchar(150) NULL, NIVEL varchar(100) NULL,
        USUARIO_CREA varchar(30) NOT NULL, ESTACION_CREA varchar(50) NOT NULL, FECHA_CREA datetime NOT NULL,
        USUARIO_ACTU varchar(30) NOT NULL, ESTACION_ACTU varchar(50) NOT NULL, FECHA_ACTU datetime NOT NULL,
        CONSTRAINT PK_SC_PERSONA_COMPETENCIAS_TECNICAS PRIMARY KEY CLUSTERED (CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_COMPETENCIA_TECNICA),
        CONSTRAINT FK_SC_PERSONA_COMPETENCIAS_TECNICAS_SC_PERSONA_DATOS FOREIGN KEY (CORR_EMPRESA, CORR_PERSONA_DATOS)
            REFERENCES dbo.SC_PERSONA_DATOS (CORR_EMPRESA, CORR_PERSONA_DATOS)
    );
END;

IF OBJECT_ID(N'dbo.SC_PERSONA_EXPERIENCIA_LABORAL', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_PERSONA_EXPERIENCIA_LABORAL (
        CORR_EMPRESA int NOT NULL, CORR_PERSONA_DATOS int NOT NULL, CORR_EXPERIENCIA_LABORAL int NOT NULL,
        EMPRESA varchar(250) NULL, TELEFONO varchar(25) NULL, CARGO varchar(150) NULL, JEFE_INMEDIATO varchar(150) NULL,
        FECHA_INICIO date NULL, FECHA_FIN date NULL, SALARIO_INICIAL decimal(18, 2) NULL,
        SALARIO_FINAL decimal(18, 2) NULL, MOTIVO_SALIDA varchar(500) NULL,
        USUARIO_CREA varchar(30) NOT NULL, ESTACION_CREA varchar(50) NOT NULL, FECHA_CREA datetime NOT NULL,
        USUARIO_ACTU varchar(30) NOT NULL, ESTACION_ACTU varchar(50) NOT NULL, FECHA_ACTU datetime NOT NULL,
        CONSTRAINT PK_SC_PERSONA_EXPERIENCIA_LABORAL PRIMARY KEY CLUSTERED (CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_EXPERIENCIA_LABORAL),
        CONSTRAINT FK_SC_PERSONA_EXPERIENCIA_LABORAL_SC_PERSONA_DATOS FOREIGN KEY (CORR_EMPRESA, CORR_PERSONA_DATOS)
            REFERENCES dbo.SC_PERSONA_DATOS (CORR_EMPRESA, CORR_PERSONA_DATOS)
    );
END;

IF OBJECT_ID(N'dbo.SC_PERSONA_FAMILIAR_UEES', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_PERSONA_FAMILIAR_UEES (
        CORR_EMPRESA int NOT NULL, CORR_PERSONA_DATOS int NOT NULL, CORR_FAMILIAR_UEES int NOT NULL,
        NOMBRE varchar(150) NULL, PARENTESCO varchar(100) NULL, UNIDAD varchar(150) NULL, TELEFONO varchar(25) NULL,
        USUARIO_CREA varchar(30) NOT NULL, ESTACION_CREA varchar(50) NOT NULL, FECHA_CREA datetime NOT NULL,
        USUARIO_ACTU varchar(30) NOT NULL, ESTACION_ACTU varchar(50) NOT NULL, FECHA_ACTU datetime NOT NULL,
        CONSTRAINT PK_SC_PERSONA_FAMILIAR_UEES PRIMARY KEY CLUSTERED (CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_FAMILIAR_UEES),
        CONSTRAINT FK_SC_PERSONA_FAMILIAR_UEES_SC_PERSONA_DATOS FOREIGN KEY (CORR_EMPRESA, CORR_PERSONA_DATOS)
            REFERENCES dbo.SC_PERSONA_DATOS (CORR_EMPRESA, CORR_PERSONA_DATOS)
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SC_PERSONA_FAMILIAR') AND name = N'IX_SC_PERSONA_FAMILIAR_PERSONA')
    CREATE NONCLUSTERED INDEX IX_SC_PERSONA_FAMILIAR_PERSONA ON dbo.SC_PERSONA_FAMILIAR (CORR_EMPRESA, CORR_PERSONA_DATOS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SC_PERSONA_HIJOS') AND name = N'IX_SC_PERSONA_HIJOS_PERSONA')
    CREATE NONCLUSTERED INDEX IX_SC_PERSONA_HIJOS_PERSONA ON dbo.SC_PERSONA_HIJOS (CORR_EMPRESA, CORR_PERSONA_DATOS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SC_PERSONA_ESTUDIO') AND name = N'IX_SC_PERSONA_ESTUDIO_PERSONA')
    CREATE NONCLUSTERED INDEX IX_SC_PERSONA_ESTUDIO_PERSONA ON dbo.SC_PERSONA_ESTUDIO (CORR_EMPRESA, CORR_PERSONA_DATOS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SC_PERSONA_IDIOMAS') AND name = N'IX_SC_PERSONA_IDIOMAS_PERSONA')
    CREATE NONCLUSTERED INDEX IX_SC_PERSONA_IDIOMAS_PERSONA ON dbo.SC_PERSONA_IDIOMAS (CORR_EMPRESA, CORR_PERSONA_DATOS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SC_PERSONA_COMPETENCIAS_TECNICAS') AND name = N'IX_SC_PERSONA_COMPETENCIAS_TECNICAS_PERSONA')
    CREATE NONCLUSTERED INDEX IX_SC_PERSONA_COMPETENCIAS_TECNICAS_PERSONA ON dbo.SC_PERSONA_COMPETENCIAS_TECNICAS (CORR_EMPRESA, CORR_PERSONA_DATOS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SC_PERSONA_EXPERIENCIA_LABORAL') AND name = N'IX_SC_PERSONA_EXPERIENCIA_LABORAL_PERSONA')
    CREATE NONCLUSTERED INDEX IX_SC_PERSONA_EXPERIENCIA_LABORAL_PERSONA ON dbo.SC_PERSONA_EXPERIENCIA_LABORAL (CORR_EMPRESA, CORR_PERSONA_DATOS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SC_PERSONA_FAMILIAR_UEES') AND name = N'IX_SC_PERSONA_FAMILIAR_UEES_PERSONA')
    CREATE NONCLUSTERED INDEX IX_SC_PERSONA_FAMILIAR_UEES_PERSONA ON dbo.SC_PERSONA_FAMILIAR_UEES (CORR_EMPRESA, CORR_PERSONA_DATOS);
GO

CREATE OR ALTER VIEW dbo.V_SC_PERSONA_DATOS AS
SELECT CORR_EMPRESA, CORR_PERSONA_DATOS, NOMBRE1, NOMBRE2, APELLIDO1, APELLIDO2,
       FECHA_NACIMIENTO, EDAD, ESTADO_CIVIL, NACIONALIDAD, CORREO, CELULAR, TELEFONO,
       DIRECCION, DUI, PASAPORTE, ISSS, AFP, NOMBRE_AFP, LICENCIA, PLAZA_SOLICITADA,
       PRETENSION_SALARIAL, DISPONIBILIDAD, RELIGION, IGLESIA, DIRECCION_IGLESIA,
       ES_CONTRIBUYENTE_CCF, ES_JUBILADO, POSEE_DISCAPACIDAD, TIPO_DISCAPACIDAD,
       EMERGENCIA_NOMBRE, EMERGENCIA_PARENTESCO, EMERGENCIA_TELEFONO,
       TIENE_FAMILIARES_UEES, DECLARA_VERDAD, AUTORIZA_VERIFICACION,
       FECHA_DECLARACION, FIRMA_ELECTRONICA, FOTO_URL
FROM dbo.SC_PERSONA_DATOS;
GO
CREATE OR ALTER VIEW dbo.V_SC_PERSONA_FAMILIAR AS
SELECT CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_FAMILIAR, TIPO, NOMBRE, DOMICILIO,
       FECHA_NACIMIENTO, OCUPACION, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
FROM dbo.SC_PERSONA_FAMILIAR;
GO
CREATE OR ALTER VIEW dbo.V_SC_PERSONA_HIJOS AS
SELECT CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_HIJO, NOMBRE, EDAD, SEXO,
       FECHA_NACIMIENTO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
FROM dbo.SC_PERSONA_HIJOS;
GO
CREATE OR ALTER VIEW dbo.V_SC_PERSONA_ESTUDIO AS
SELECT CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_ESTUDIO, NIVEL, INSTITUCION, DESDE,
       HASTA, TITULO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
FROM dbo.SC_PERSONA_ESTUDIO;
GO
CREATE OR ALTER VIEW dbo.V_SC_PERSONA_IDIOMAS AS
SELECT CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_IDIOMA, IDIOMA, NIVEL,
       USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
FROM dbo.SC_PERSONA_IDIOMAS;
GO
CREATE OR ALTER VIEW dbo.V_SC_PERSONA_COMPETENCIAS_TECNICAS AS
SELECT CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_COMPETENCIA_TECNICA, HERRAMIENTA,
       NIVEL, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
FROM dbo.SC_PERSONA_COMPETENCIAS_TECNICAS;
GO
CREATE OR ALTER VIEW dbo.V_SC_PERSONA_EXPERIENCIA_LABORAL AS
SELECT CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_EXPERIENCIA_LABORAL, EMPRESA, TELEFONO,
       CARGO, JEFE_INMEDIATO, FECHA_INICIO, FECHA_FIN, SALARIO_INICIAL, SALARIO_FINAL,
       MOTIVO_SALIDA, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
FROM dbo.SC_PERSONA_EXPERIENCIA_LABORAL;
GO
CREATE OR ALTER VIEW dbo.V_SC_PERSONA_FAMILIAR_UEES AS
SELECT CORR_EMPRESA, CORR_PERSONA_DATOS, CORR_FAMILIAR_UEES, NOMBRE, PARENTESCO,
       UNIDAD, TELEFONO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA, USUARIO_ACTU, ESTACION_ACTU, FECHA_ACTU
FROM dbo.SC_PERSONA_FAMILIAR_UEES;
GO
