SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/*
  Decisión de jefatura (solicitante) sobre un candidato en una requisición.
  El registro nace solo al decidir (APLICA / NO_APLICA).
  Ausencia de fila = Pendiente (LEFT JOIN en vistas).
  Ejecutar: sqlcmd -S <srv> -d SGUEES -U <user> -f 65001 -i SC_REQUISICION_CANDIDATO.sql
*/

IF OBJECT_ID(N'dbo.SC_REQUISICION_CANDIDATO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_REQUISICION_CANDIDATO
    (
        CORR_EMPRESA               INT            NOT NULL,
        CORR_REQUISICION_CANDIDATO INT            NOT NULL,
        CORR_REQUISICION_PERSONAL  INT            NOT NULL,
        CORR_SOLICITUD_EMPLEO      INT            NOT NULL,
        CORR_EXPEDIENTE_CANDIDATO  INT            NOT NULL,
        ESTADO_DECISION            VARCHAR(20)    NOT NULL,
        OBSERVACION_DECISION       NVARCHAR(2000) NULL,
        FECHA_DECISION             DATETIME       NOT NULL,
        USUARIO_DECISION           VARCHAR(50)    NOT NULL,
        USUARIO_CREA               VARCHAR(50)    NULL,
        ESTACION_CREA              VARCHAR(50)    NULL,
        FECHA_CREA                 DATETIME       NULL,
        USUARIO_ACTU               VARCHAR(50)    NULL,
        ESTACION_ACTU              VARCHAR(50)    NULL,
        FECHA_ACTU                 DATETIME       NULL,
        CONSTRAINT PK_SC_REQUISICION_CANDIDATO
            PRIMARY KEY (CORR_EMPRESA, CORR_REQUISICION_CANDIDATO),
        CONSTRAINT CK_SC_REQUISICION_CANDIDATO_ESTADO
            CHECK (ESTADO_DECISION IN ('APLICA', 'NO_APLICA'))
    );
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'UX_SC_REQUISICION_CANDIDATO_UNICA'
      AND object_id = OBJECT_ID(N'dbo.SC_REQUISICION_CANDIDATO')
)
BEGIN
    CREATE UNIQUE INDEX UX_SC_REQUISICION_CANDIDATO_UNICA
        ON dbo.SC_REQUISICION_CANDIDATO
        (
            CORR_EMPRESA,
            CORR_REQUISICION_PERSONAL,
            CORR_EXPEDIENTE_CANDIDATO
        );
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'IX_SC_REQUISICION_CANDIDATO_EXPEDIENTE'
      AND object_id = OBJECT_ID(N'dbo.SC_REQUISICION_CANDIDATO')
)
BEGIN
    CREATE INDEX IX_SC_REQUISICION_CANDIDATO_EXPEDIENTE
        ON dbo.SC_REQUISICION_CANDIDATO
        (
            CORR_EMPRESA,
            CORR_EXPEDIENTE_CANDIDATO,
            CORR_SOLICITUD_EMPLEO
        );
END;
GO

CREATE OR ALTER VIEW dbo.V_SC_REQUISICION_CANDIDATO
AS
SELECT
    RC.CORR_EMPRESA,
    RC.CORR_REQUISICION_CANDIDATO,
    RC.CORR_REQUISICION_PERSONAL,
    RC.CORR_SOLICITUD_EMPLEO,
    RC.CORR_EXPEDIENTE_CANDIDATO,
    RC.ESTADO_DECISION,
    RC.OBSERVACION_DECISION,
    RC.FECHA_DECISION,
    RC.USUARIO_DECISION,
    R.NOMBRE_UNIDAD,
    R.NOMBRE_PUESTO,
    R.MODALIDAD_NOMBRE,
    R.CORR_ESTADO_REQUISICION,
    RC.USUARIO_CREA,
    RC.ESTACION_CREA,
    RC.FECHA_CREA,
    RC.USUARIO_ACTU,
    RC.ESTACION_ACTU,
    RC.FECHA_ACTU
FROM dbo.SC_REQUISICION_CANDIDATO AS RC
INNER JOIN dbo.V_SC_REQUISICION_PERSONAL AS R
    ON R.CORR_EMPRESA = RC.CORR_EMPRESA
   AND R.CORR_REQUISICION_PERSONAL = RC.CORR_REQUISICION_PERSONAL;
GO

/*
  Postulaciones del expediente por solicitud: vínculos solicitud↔requisición
  con LEFT JOIN a la decisión (sin fila = Pendiente en UI).
*/
CREATE OR ALTER VIEW dbo.V_SC_EXPEDIENTE_CANDIDATO_POSTULACION
AS
SELECT
    ES.CORR_EMPRESA,
    ES.CORR_EXPEDIENTE_CANDIDATO,
    ES.CORR_EXPEDIENTE_SOLICITUD,
    ES.CORR_SOLICITUD_EMPLEO,
    SR.CORR_SOLICITUD_REQUISICION,
    SR.CORR_REQUISICION_PERSONAL,
    R.NOMBRE_UNIDAD,
    R.NOMBRE_PUESTO,
    R.MODALIDAD_NOMBRE,
    R.CORR_ESTADO_REQUISICION,
    RC.CORR_REQUISICION_CANDIDATO,
    CAST(ISNULL(RC.ESTADO_DECISION, N'PENDIENTE') AS VARCHAR(20)) AS ESTADO_DECISION,
    RC.OBSERVACION_DECISION,
    RC.FECHA_DECISION,
    RC.USUARIO_DECISION
FROM dbo.SC_EXPEDIENTE_SOLICITUD AS ES
INNER JOIN dbo.SC_SOLICITUD_REQUISICION AS SR
    ON SR.CORR_EMPRESA = ES.CORR_EMPRESA
   AND SR.CORR_SOLICITUD_EMPLEO = ES.CORR_SOLICITUD_EMPLEO
INNER JOIN dbo.V_SC_REQUISICION_PERSONAL AS R
    ON R.CORR_EMPRESA = SR.CORR_EMPRESA
   AND R.CORR_REQUISICION_PERSONAL = SR.CORR_REQUISICION_PERSONAL
LEFT JOIN dbo.SC_REQUISICION_CANDIDATO AS RC
    ON RC.CORR_EMPRESA = ES.CORR_EMPRESA
   AND RC.CORR_REQUISICION_PERSONAL = SR.CORR_REQUISICION_PERSONAL
   AND RC.CORR_EXPEDIENTE_CANDIDATO = ES.CORR_EXPEDIENTE_CANDIDATO
   AND RC.CORR_SOLICITUD_EMPLEO = ES.CORR_SOLICITUD_EMPLEO;
GO

CREATE OR ALTER VIEW dbo.V_SC_REQUISICION_PERSONAL_CANDIDATO
AS
SELECT
    SR.CORR_EMPRESA,
    SR.CORR_REQUISICION_PERSONAL,
    SR.CORR_SOLICITUD_EMPLEO,
    EC.CORR_EXPEDIENTE_CANDIDATO,
    EC.CORR_PERSONA_DATOS,
    EC.NOMBRE_PERSONA,
    EC.DUI_PERSONA,
    EC.FECHA_GENERACION,
    EC.CORR_ESTADO_EXPEDIENTE,
    RC.CORR_REQUISICION_CANDIDATO,
    CAST(ISNULL(RC.ESTADO_DECISION, N'PENDIENTE') AS VARCHAR(20)) AS ESTADO_DECISION,
    RC.OBSERVACION_DECISION,
    RC.FECHA_DECISION,
    RC.USUARIO_DECISION
FROM dbo.SC_SOLICITUD_REQUISICION AS SR
INNER JOIN dbo.SC_SOLICITUD_EMPLEO AS S
    ON S.CORR_EMPRESA = SR.CORR_EMPRESA
   AND S.CORR_SOLICITUD_EMPLEO = SR.CORR_SOLICITUD_EMPLEO
INNER JOIN dbo.SC_EXPEDIENTE_SOLICITUD AS ES
    ON ES.CORR_EMPRESA = S.CORR_EMPRESA
   AND ES.CORR_SOLICITUD_EMPLEO = S.CORR_SOLICITUD_EMPLEO
INNER JOIN dbo.V_SC_EXPEDIENTE_CANDIDATO AS EC
    ON EC.CORR_EMPRESA = ES.CORR_EMPRESA
   AND EC.CORR_EXPEDIENTE_CANDIDATO = ES.CORR_EXPEDIENTE_CANDIDATO
LEFT JOIN dbo.SC_REQUISICION_CANDIDATO AS RC
    ON RC.CORR_EMPRESA = SR.CORR_EMPRESA
   AND RC.CORR_REQUISICION_PERSONAL = SR.CORR_REQUISICION_PERSONAL
   AND RC.CORR_EXPEDIENTE_CANDIDATO = EC.CORR_EXPEDIENTE_CANDIDATO
   AND RC.CORR_SOLICITUD_EMPLEO = SR.CORR_SOLICITUD_EMPLEO
WHERE EC.CORR_ESTADO_EXPEDIENTE = 2
  AND EC.ACTIVO = 1
  AND S.ACTIVO = 1;
GO
