SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/* =============================================================================
   Flujo 101 — requisición de personal, tres niveles (espejo de movimiento 103).

   Oficial = SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES.ACTIVO = 1.
   Nivel 3 = ancestro con CORR_NIVEL = 3.
   Unidad del circuito = puesto del creador (USUARIO_CREA), no CORR_UNIDAD del documento.
   ============================================================================= */
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @EMP INT = 1;
DECLARE @TIPO INT;
DECLARE @FLUJO INT;
DECLARE @PASO_CREAR INT;
DECLARE @PASO_N1 INT;
DECLARE @PASO_N2 INT;
DECLARE @PASO_N3 INT;
DECLARE @EST_BORRADOR INT;
DECLARE @EST_EN_APROB INT;
DECLARE @EST_DEV_JI INT;
DECLARE @EST_APR_JI INT;
DECLARE @EST_REC_JI INT;
DECLARE @EST_APR_JU INT;
DECLARE @EST_DEV_JU INT;
DECLARE @EST_REC_JU INT;
DECLARE @EST_APR_GG INT;
DECLARE @EST_DEV_GG INT;
DECLARE @EST_REC_GG INT;
DECLARE @NUEVO_EST INT;
DECLARE @NUEVO_PASO INT;

SELECT @TIPO = CORR_TIPO_DOCUMENTO
FROM dbo.SEG_FLUJO_TIPO_DOCUMENTO
WHERE CORR_EMPRESA = @EMP
  AND CODIGO_OPCION = N'SC_REQUISICION'
  AND ACTIVO = 1;

SELECT @FLUJO = CORR_FLUJO_PROCESO
FROM dbo.SEG_FLUJO_PROCESO
WHERE CORR_EMPRESA = @EMP
  AND CORR_TIPO_DOCUMENTO = @TIPO
  AND ACTIVO = 1
  AND ES_DEFECTO = 1;

IF @TIPO IS NULL OR @FLUJO IS NULL
BEGIN
	RAISERROR(N'No hay tipo o flujo defecto para SC_REQUISICION.', 16, 1);
	RETURN;
END

BEGIN TRAN;

/* Renombrar estados legacy al set JI/JU/GG. */
UPDATE dbo.SEG_FLUJO_ESTADO
SET NOMBRE_ESTADO = N'Devuelta JI',
	DESCRIPCION = N'Devuelto por el jefe inmediato (nivel 1).',
	ES_FINAL = 0, ES_INICIAL = 0, ACTIVO = 1,
	USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO
  AND NOMBRE_ESTADO IN (N'Devuelta', N'Devuelta JI');

UPDATE dbo.SEG_FLUJO_ESTADO
SET NOMBRE_ESTADO = N'Rechazada GG',
	DESCRIPCION = N'Rechazado por gerencia general (nivel 3).',
	ES_FINAL = 1, ES_INICIAL = 0, ACTIVO = 1,
	USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO
  AND NOMBRE_ESTADO IN (N'Rechazada', N'Rechazada GG');

UPDATE dbo.SEG_FLUJO_ESTADO
SET NOMBRE_ESTADO = N'Aprobado GG',
	DESCRIPCION = N'Aprobado por gerencia general (nivel 3).',
	ES_FINAL = 1, ES_INICIAL = 0, ACTIVO = 1,
	USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO
  AND NOMBRE_ESTADO IN (N'Aprobada', N'Aprobado GG', N'Aprobada GG');

DECLARE @ALTAS TABLE (NOMBRE NVARCHAR(50), DESCRIPCION NVARCHAR(255), ES_FINAL BIT);
INSERT INTO @ALTAS (NOMBRE, DESCRIPCION, ES_FINAL) VALUES
	(N'Aprobado JI', N'Aprobado por el jefe inmediato (nivel 1). El circuito sigue.', 0),
	(N'Rechazada JI', N'Rechazado por el jefe inmediato (nivel 1).', 1),
	(N'Aprobado JU', N'Aprobado por el jefe de la unidad (nivel 2). El circuito sigue.', 0),
	(N'Devuelta JU', N'Devuelto por el jefe de la unidad (nivel 2).', 0),
	(N'Rechazada JU', N'Rechazado por el jefe de la unidad (nivel 2).', 1),
	(N'Devuelta GG', N'Devuelto por gerencia general (nivel 3).', 0);

DECLARE @NOM NVARCHAR(50), @DESC NVARCHAR(255), @FIN BIT;
DECLARE altas CURSOR LOCAL FAST_FORWARD FOR SELECT NOMBRE, DESCRIPCION, ES_FINAL FROM @ALTAS;
OPEN altas;
FETCH NEXT FROM altas INTO @NOM, @DESC, @FIN;
WHILE @@FETCH_STATUS = 0
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM dbo.SEG_FLUJO_ESTADO
		WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = @NOM
	)
	BEGIN
		SELECT @NUEVO_EST = ISNULL(MAX(CORR_ESTADO), 0) + 1 FROM dbo.SEG_FLUJO_ESTADO;
		INSERT INTO dbo.SEG_FLUJO_ESTADO (
			CORR_EMPRESA, CORR_ESTADO, CORR_TIPO_DOCUMENTO, NOMBRE_ESTADO, DESCRIPCION,
			ES_INICIAL, ES_FINAL, ACTIVO, USUARIO_CREA, ESTACION_CREA, FECHA_CREA
		) VALUES (
			@EMP, @NUEVO_EST, @TIPO, @NOM, @DESC,
			0, @FIN, 1, N'SISTEMA', N'SCRIPT', GETDATE()
		);
	END
	ELSE
		UPDATE dbo.SEG_FLUJO_ESTADO
		SET DESCRIPCION = @DESC, ES_FINAL = @FIN, ES_INICIAL = 0, ACTIVO = 1,
			USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
		WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = @NOM;

	FETCH NEXT FROM altas INTO @NOM, @DESC, @FIN;
END
CLOSE altas;
DEALLOCATE altas;

SELECT @EST_BORRADOR = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Borrador';
SELECT @EST_EN_APROB = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO LIKE N'En Aprobaci%';
SELECT @EST_DEV_JI = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Devuelta JI';
SELECT @EST_APR_JI = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Aprobado JI';
SELECT @EST_REC_JI = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Rechazada JI';
SELECT @EST_APR_JU = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Aprobado JU';
SELECT @EST_DEV_JU = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Devuelta JU';
SELECT @EST_REC_JU = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Rechazada JU';
SELECT @EST_APR_GG = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Aprobado GG';
SELECT @EST_DEV_GG = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Devuelta GG';
SELECT @EST_REC_GG = CORR_ESTADO FROM dbo.SEG_FLUJO_ESTADO WHERE CORR_EMPRESA = @EMP AND CORR_TIPO_DOCUMENTO = @TIPO AND NOMBRE_ESTADO = N'Rechazada GG';

IF @EST_BORRADOR IS NULL OR @EST_EN_APROB IS NULL OR @EST_DEV_JI IS NULL OR @EST_APR_JI IS NULL
	OR @EST_REC_JI IS NULL OR @EST_APR_JU IS NULL OR @EST_DEV_JU IS NULL OR @EST_REC_JU IS NULL
	OR @EST_APR_GG IS NULL OR @EST_DEV_GG IS NULL OR @EST_REC_GG IS NULL
BEGIN
	ROLLBACK TRAN;
	RAISERROR(N'Faltan estados del flujo 101.', 16, 1);
	RETURN;
END

SELECT @PASO_CREAR = CORR_PASO FROM dbo.SEG_FLUJO_PASO WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND ORDEN = 1;
SELECT @PASO_N1 = CORR_PASO FROM dbo.SEG_FLUJO_PASO WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND ORDEN = 2;

SELECT @PASO_N2 = CORR_PASO
FROM dbo.SEG_FLUJO_PASO
WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND NOMBRE_PASO = N'Aprobación jefe de unidad';

/* Liberar ORDEN 3 si el paso viejo de gerencia lo ocupa. */
UPDATE dbo.SEG_FLUJO_PASO
SET ORDEN = 4, USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP
  AND CORR_FLUJO_PROCESO = @FLUJO
  AND ORDEN = 3
  AND (@PASO_N2 IS NULL OR CORR_PASO <> @PASO_N2);

IF @PASO_N2 IS NULL AND EXISTS (
	SELECT 1 FROM dbo.SEG_FLUJO_PASO
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND ORDEN = 2
	  AND NOMBRE_PASO LIKE N'%gerencia%'
)
BEGIN
	/* Caso 2 pasos: el actual orden 2 pasa a ser N3; se inserta N1 y N2. */
	UPDATE dbo.SEG_FLUJO_PASO
	SET ORDEN = 4, USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND ORDEN = 2;

	SELECT @PASO_N3 = CORR_PASO
	FROM dbo.SEG_FLUJO_PASO
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND ORDEN = 4;

	SELECT @NUEVO_PASO = ISNULL(MAX(CORR_PASO), 0) + 1 FROM dbo.SEG_FLUJO_PASO;
	INSERT INTO dbo.SEG_FLUJO_PASO (
		CORR_EMPRESA, CORR_PASO, CORR_FLUJO_PROCESO, ORDEN, NOMBRE_PASO,
		CORR_ACTOR_ORIGEN, CORR_ESTADO_ORIGEN, CORR_ACTOR_DESTINO, CORR_UNIDAD_DESTINO,
		PERMITE_AUTO_APROBACION, USUARIO_CREA, ESTACION_CREA, FECHA_CREA
	) VALUES (
		@EMP, @NUEVO_PASO, @FLUJO, 2, N'Aprobación jefe inmediato',
		2, NULL, 2, NULL, 1, N'SISTEMA', N'SCRIPT', GETDATE()
	);
	SET @PASO_N1 = @NUEVO_PASO;

	SELECT @NUEVO_PASO = ISNULL(MAX(CORR_PASO), 0) + 1 FROM dbo.SEG_FLUJO_PASO;
	INSERT INTO dbo.SEG_FLUJO_PASO (
		CORR_EMPRESA, CORR_PASO, CORR_FLUJO_PROCESO, ORDEN, NOMBRE_PASO,
		CORR_ACTOR_ORIGEN, CORR_ESTADO_ORIGEN, CORR_ACTOR_DESTINO, CORR_UNIDAD_DESTINO,
		PERMITE_AUTO_APROBACION, USUARIO_CREA, ESTACION_CREA, FECHA_CREA
	) VALUES (
		@EMP, @NUEVO_PASO, @FLUJO, 3, N'Aprobación jefe de unidad',
		3, NULL, 2, NULL, 0, N'SISTEMA', N'SCRIPT', GETDATE()
	);
	SET @PASO_N2 = @NUEVO_PASO;
END
ELSE IF @PASO_N2 IS NULL
BEGIN
	SELECT @NUEVO_PASO = ISNULL(MAX(CORR_PASO), 0) + 1 FROM dbo.SEG_FLUJO_PASO;
	INSERT INTO dbo.SEG_FLUJO_PASO (
		CORR_EMPRESA, CORR_PASO, CORR_FLUJO_PROCESO, ORDEN, NOMBRE_PASO,
		CORR_ACTOR_ORIGEN, CORR_ESTADO_ORIGEN, CORR_ACTOR_DESTINO, CORR_UNIDAD_DESTINO,
		PERMITE_AUTO_APROBACION, USUARIO_CREA, ESTACION_CREA, FECHA_CREA
	) VALUES (
		@EMP, @NUEVO_PASO, @FLUJO, 3, N'Aprobación jefe de unidad',
		3, NULL, 2, NULL, 0, N'SISTEMA', N'SCRIPT', GETDATE()
	);
	SET @PASO_N2 = @NUEVO_PASO;
END

IF @PASO_N3 IS NULL
	SELECT @PASO_N3 = CORR_PASO
	FROM dbo.SEG_FLUJO_PASO
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND ORDEN = 4;

IF @PASO_N1 IS NULL
	SELECT @PASO_N1 = CORR_PASO
	FROM dbo.SEG_FLUJO_PASO
	WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO AND ORDEN = 2;

UPDATE dbo.SEG_FLUJO_PASO
SET NOMBRE_PASO = N'Crear solicitud de requisición',
	CORR_ACTOR_ORIGEN = 1,
	CORR_ACTOR_DESTINO = 2,
	CORR_UNIDAD_DESTINO = NULL,
	CORR_ESTADO_ORIGEN = @EST_BORRADOR,
	PERMITE_AUTO_APROBACION = 0,
	ORDEN = 1,
	USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_PASO = @PASO_CREAR;

UPDATE dbo.SEG_FLUJO_PASO
SET NOMBRE_PASO = N'Aprobación jefe inmediato',
	CORR_ACTOR_ORIGEN = 2,
	CORR_ACTOR_DESTINO = 2,
	CORR_UNIDAD_DESTINO = NULL,
	CORR_ESTADO_ORIGEN = NULL,
	PERMITE_AUTO_APROBACION = 1,
	ORDEN = 2,
	USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_PASO = @PASO_N1;

UPDATE dbo.SEG_FLUJO_PASO
SET NOMBRE_PASO = N'Aprobación jefe de unidad',
	CORR_ACTOR_ORIGEN = 3,
	CORR_ACTOR_DESTINO = 2,
	CORR_UNIDAD_DESTINO = NULL,
	CORR_ESTADO_ORIGEN = NULL,
	PERMITE_AUTO_APROBACION = 0,
	ORDEN = 3,
	USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_PASO = @PASO_N2;

UPDATE dbo.SEG_FLUJO_PASO
SET NOMBRE_PASO = N'Aprobación gerencia general',
	CORR_ACTOR_ORIGEN = 2,
	CORR_ACTOR_DESTINO = 1,
	CORR_UNIDAD_DESTINO = NULL,
	CORR_ESTADO_ORIGEN = NULL,
	PERMITE_AUTO_APROBACION = 0,
	ORDEN = 4,
	USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_PASO = @PASO_N3;

/* Recrear acciones: desactivar viejas e insertar/actualizar las del circuito N1/N2/N3. */
UPDATE dbo.SEG_FLUJO_PASO_ACCION_ESTADO
SET ACTIVO = 0, PERMITIDO = 0, USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
WHERE CORR_EMPRESA = @EMP AND CORR_FLUJO_PROCESO = @FLUJO;

DECLARE @ACC TABLE (
	PASO INT, ACCION INT, ESTADO INT, TIPO_MOV TINYINT, TIPO_NOTIF TINYINT, PASO_DEST INT NULL
);
INSERT INTO @ACC VALUES
	(@PASO_CREAR, 1, @EST_BORRADOR, 4, 5, @PASO_N1),
	(@PASO_CREAR, 2, @EST_EN_APROB, 1, 2, @PASO_N1),
	(@PASO_N1, 1, @EST_DEV_JI, 2, 3, @PASO_CREAR),
	(@PASO_N1, 2, @EST_APR_JI, 1, 2, @PASO_N2),
	(@PASO_N1, 3, @EST_REC_JI, 3, 3, NULL),
	(@PASO_N2, 1, @EST_DEV_JU, 2, 3, @PASO_CREAR),
	(@PASO_N2, 2, @EST_APR_JU, 1, 2, @PASO_N3),
	(@PASO_N2, 3, @EST_REC_JU, 3, 3, NULL),
	(@PASO_N3, 1, @EST_REC_GG, 3, 3, NULL),
	(@PASO_N3, 2, @EST_APR_GG, 3, 3, NULL),
	(@PASO_N3, 3, @EST_DEV_GG, 2, 3, @PASO_CREAR);

MERGE dbo.SEG_FLUJO_PASO_ACCION_ESTADO AS T
USING (
	SELECT @EMP AS CORR_EMPRESA, @FLUJO AS CORR_FLUJO_PROCESO,
		PASO AS CORR_PASO, ACCION AS CORR_ACCION, ESTADO AS CORR_ESTADO_DESTINO,
		TIPO_MOV AS CORR_TIPO_MOVIMIENTO, TIPO_NOTIF AS CORR_TIPO_NOTIFICACION, PASO_DEST AS CORR_PASO_DESTINO
	FROM @ACC
) AS S
ON T.CORR_EMPRESA = S.CORR_EMPRESA
 AND T.CORR_FLUJO_PROCESO = S.CORR_FLUJO_PROCESO
 AND T.CORR_PASO = S.CORR_PASO
 AND T.CORR_ACCION = S.CORR_ACCION
WHEN MATCHED THEN UPDATE SET
	CORR_ESTADO_DESTINO = S.CORR_ESTADO_DESTINO,
	CORR_TIPO_MOVIMIENTO = S.CORR_TIPO_MOVIMIENTO,
	CORR_TIPO_NOTIFICACION = S.CORR_TIPO_NOTIFICACION,
	CORR_PASO_DESTINO = S.CORR_PASO_DESTINO,
	PERMITIDO = 1, ACTIVO = 1,
	USUARIO_ACTU = N'SISTEMA', FECHA_ACTU = GETDATE()
WHEN NOT MATCHED THEN INSERT (
	CORR_EMPRESA, CORR_FLUJO_PROCESO, CORR_PASO, CORR_ACCION, CORR_ESTADO_DESTINO,
	PERMITIDO, CORR_TIPO_MOVIMIENTO, CORR_TIPO_NOTIFICACION, CORR_PASO_DESTINO, ACTIVO,
	USUARIO_CREA, ESTACION_CREA, FECHA_CREA
) VALUES (
	S.CORR_EMPRESA, S.CORR_FLUJO_PROCESO, S.CORR_PASO, S.CORR_ACCION, S.CORR_ESTADO_DESTINO,
	1, S.CORR_TIPO_MOVIMIENTO, S.CORR_TIPO_NOTIFICACION, S.CORR_PASO_DESTINO, 1,
	N'SISTEMA', N'SCRIPT', GETDATE()
);

COMMIT TRAN;

SELECT P.ORDEN, P.CORR_PASO, P.NOMBRE_PASO, P.CORR_ACTOR_ORIGEN, P.CORR_ACTOR_DESTINO, P.PERMITE_AUTO_APROBACION,
	A.CORR_ACCION, E.NOMBRE_ESTADO, A.CORR_TIPO_MOVIMIENTO, A.CORR_TIPO_NOTIFICACION, A.CORR_PASO_DESTINO
FROM dbo.SEG_FLUJO_PASO AS P
LEFT JOIN dbo.SEG_FLUJO_PASO_ACCION_ESTADO AS A
	ON A.CORR_EMPRESA = P.CORR_EMPRESA AND A.CORR_FLUJO_PROCESO = P.CORR_FLUJO_PROCESO
   AND A.CORR_PASO = P.CORR_PASO AND A.ACTIVO = 1
LEFT JOIN dbo.SEG_FLUJO_ESTADO AS E
	ON E.CORR_EMPRESA = A.CORR_EMPRESA AND E.CORR_ESTADO = A.CORR_ESTADO_DESTINO
WHERE P.CORR_EMPRESA = @EMP AND P.CORR_FLUJO_PROCESO = @FLUJO
ORDER BY P.ORDEN, A.CORR_ACCION;
GO
