SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/*
  Tabla puente: solicitud de empleo ↔ requisición de personal.
  Solo persiste CORR_REQUISICION_PERSONAL (+ FK solicitud); los textos van en la vista.
*/

IF OBJECT_ID(N'dbo.SC_SOLICITUD_REQUISICION', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SC_SOLICITUD_REQUISICION
    (
        CORR_EMPRESA               INT         NOT NULL,
        CORR_SOLICITUD_REQUISICION INT         NOT NULL,
        CORR_SOLICITUD_EMPLEO      INT         NOT NULL,
        CORR_REQUISICION_PERSONAL  INT         NOT NULL,
        USUARIO_CREA               VARCHAR(50) NULL,
        ESTACION_CREA              VARCHAR(50) NULL,
        FECHA_CREA                 DATETIME    NULL,
        USUARIO_ACTU               VARCHAR(50) NULL,
        ESTACION_ACTU              VARCHAR(50) NULL,
        FECHA_ACTU                 DATETIME    NULL,
        CONSTRAINT PK_SC_SOLICITUD_REQUISICION
            PRIMARY KEY (CORR_EMPRESA, CORR_SOLICITUD_REQUISICION)
    );
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'UX_SC_SOLICITUD_REQUISICION_UNICA'
      AND object_id = OBJECT_ID(N'dbo.SC_SOLICITUD_REQUISICION')
)
BEGIN
    CREATE UNIQUE INDEX UX_SC_SOLICITUD_REQUISICION_UNICA
        ON dbo.SC_SOLICITUD_REQUISICION (CORR_EMPRESA, CORR_SOLICITUD_EMPLEO, CORR_REQUISICION_PERSONAL);
END;
GO

CREATE OR ALTER VIEW dbo.V_SC_SOLICITUD_REQUISICION
AS
SELECT
    L.CORR_EMPRESA,
    L.CORR_SOLICITUD_REQUISICION,
    L.CORR_SOLICITUD_EMPLEO,
    L.CORR_REQUISICION_PERSONAL,
    R.FECHA_REQUISICION,
    R.NOMBRE_UNIDAD,
    R.CORR_PUESTO,
    R.NOMBRE_PUESTO,
    R.MODALIDAD_NOMBRE,
    R.NOMBRE_TIPO_CONTRATACION,
    R.NOMBRE_TIPO_VACANTE,
    R.CANTIDAD_PLAZAS,
    R.PLAZAS_CUBIERTAS,
    R.SALARIO,
    R.TIEMPO_CONTRATO,
    R.HORARIO,
    R.JUSTIFICACION,
    R.CORR_EMPLEADO_SUSTITUTO,
    R.CORR_ESTADO_REQUISICION,
    R.FECHA_APROBACION,
    R.FECHA_CIERRE
FROM dbo.SC_SOLICITUD_REQUISICION AS L
INNER JOIN dbo.V_SC_REQUISICION_PERSONAL AS R
    ON R.CORR_EMPRESA = L.CORR_EMPRESA
   AND R.CORR_REQUISICION_PERSONAL = L.CORR_REQUISICION_PERSONAL;
GO
