SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/*
  Vista V_SC_SOLICITUD_EMPLEO: JOIN a SC_TIPO_CONTRATACION.
  La tabla ya tiene CORR_TIPO_CONTRATACION; no se altera.
  ES_PERMANENTE y NOMBRE_TIPO_CONTRATACION se leen del catálogo (no se guardan en la solicitud).
*/

CREATE OR ALTER VIEW dbo.V_SC_SOLICITUD_EMPLEO
AS
SELECT
    S.CORR_EMPRESA,
    S.CORR_SOLICITUD_EMPLEO,
    S.FECHA_GENERACION,
    S.CORREO_INVITACION,
    S.DUI,
    S.NOMBRE,
    S.CORR_TIPO_CONTRATACION,
    T.NOMBRE_TIPO_CONTRATACION,
    CAST(ISNULL(T.ES_PERMANENTE, 0) AS bit) AS ES_PERMANENTE,
    S.CORR_PERSONA_DATOS,
    S.ACTIVO,
    S.USUARIO_CREA,
    S.ESTACION_CREA,
    S.FECHA_CREA,
    S.USUARIO_ACTU,
    S.ESTACION_ACTU,
    S.FECHA_ACTU
FROM dbo.SC_SOLICITUD_EMPLEO AS S
LEFT JOIN dbo.SC_TIPO_CONTRATACION AS T
    ON T.CORR_EMPRESA = S.CORR_EMPRESA
   AND T.CORR_TIPO_CONTRATACION = S.CORR_TIPO_CONTRATACION;
GO
