SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/* DUI en solicitud de empleo (registro RRHH). Sin SP — solo tabla + vista. */

IF COL_LENGTH(N'dbo.SC_SOLICITUD_EMPLEO', N'DUI') IS NULL
BEGIN
    ALTER TABLE dbo.SC_SOLICITUD_EMPLEO ADD DUI varchar(25) NULL;
END;
GO

CREATE OR ALTER VIEW dbo.V_SC_SOLICITUD_EMPLEO
AS
SELECT
    CORR_EMPRESA,
    CORR_SOLICITUD_EMPLEO,
    FECHA_GENERACION,
    CORREO_INVITACION,
    DUI,
    NOMBRE,
    CORR_PERSONA_DATOS,
    ACTIVO,
    USUARIO_CREA,
    ESTACION_CREA,
    FECHA_CREA,
    USUARIO_ACTU,
    ESTACION_ACTU,
    FECHA_ACTU
FROM dbo.SC_SOLICITUD_EMPLEO;
GO
