/*
  SC_TIPO_ENTREVISTA — tabla + vista (idempotente)
  Ejecutar:
    sqlcmd -S <srv> -d SGUEES -U <user> -P <pass> -f 65001 -i SGUEES-DB/Scripts/SC_TIPO_ENTREVISTA.sql
*/

SET NOCOUNT ON;
GO

/* ========== TABLA ========== */
IF OBJECT_ID(N'dbo.SC_TIPO_ENTREVISTA', N'U') IS NULL
BEGIN
  CREATE TABLE [dbo].[SC_TIPO_ENTREVISTA] (
    [CORR_EMPRESA] [int] NOT NULL,
    [CORR_TIPO_ENTREVISTA] [int] NOT NULL,
    [TIPO_ENTREVISTA] [varchar](250) NULL,
    [DESCRIPCION_ENTREVISTA] [varchar](500) NULL,
    [USUARIO_CREA] [varchar](50) NULL,
    [ESTACION_CREA] [varchar](50) NULL,
    [FECHA_CREA] [datetime] NULL,
    [USUARIO_ACTU] [varchar](50) NULL,
    [ESTACION_ACTU] [varchar](50) NULL,
    [FECHA_ACTU] [datetime] NULL,
    CONSTRAINT [PK_SC_TIPO_ENTREVISTA] PRIMARY KEY CLUSTERED (
      [CORR_EMPRESA],
      [CORR_TIPO_ENTREVISTA]
    )
  ) ON [PRIMARY];
END
GO

/* ========== VISTA ========== */
CREATE OR ALTER VIEW dbo.V_SC_TIPO_ENTREVISTA
AS
SELECT
    X.CORR_EMPRESA,
    X.CORR_TIPO_ENTREVISTA,
    X.TIPO_ENTREVISTA,
    X.DESCRIPCION_ENTREVISTA,
    X.USUARIO_CREA,
    X.ESTACION_CREA,
    X.FECHA_CREA,
    X.USUARIO_ACTU,
    X.ESTACION_ACTU,
    X.FECHA_ACTU
FROM dbo.SC_TIPO_ENTREVISTA AS X;
GO

PRINT N'SC_TIPO_ENTREVISTA / V_SC_TIPO_ENTREVISTA listos.';
GO
