/*
  Códigos movimiento según banco — PROMERICA (CORR_BANCO=8, CLASE_BANCO=PROME).
  Origen: plantilla DOCS/plantillas/ban-concilia-import-promerica.xlsx
  (Descripcion = CODIGO-Nombre; el parser extrae el código antes del primer '-').

  Uso:
    cd "C:\Desarrollo GIT\SGUEES\SGUEES-DB\Scripts"
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i SEED_BAN_TIPO_MOVI_SEGUN_BANCO_PROMERICA.sql
*/
SET NOCOUNT ON;
GO

DECLARE @CORR_EMPRESA INT = 1;
DECLARE @CORR_BANCO INT;

SELECT @CORR_BANCO = CORR_BANCO
FROM dbo.GEN_BANCO
WHERE CORR_EMPRESA = @CORR_EMPRESA
  AND CLASE_BANCO IN ('PROME', 'BPM');

IF @CORR_BANCO IS NULL
BEGIN
    RAISERROR(N'No se encontró banco Promerica (PROME/BPM) en GEN_BANCO.', 16, 1);
    RETURN;
END

PRINT N'=== SEED BAN_TIPO_MOVI_SEGUN_BANCO — Promerica ===';
PRINT N'CORR_EMPRESA=' + CAST(@CORR_EMPRESA AS NVARCHAR(10)) + N' CORR_BANCO=' + CAST(@CORR_BANCO AS NVARCHAR(10));
GO

DECLARE @CORR_EMPRESA INT = 1;
DECLARE @CORR_BANCO INT;

SELECT @CORR_BANCO = CORR_BANCO
FROM dbo.GEN_BANCO
WHERE CORR_EMPRESA = @CORR_EMPRESA
  AND CLASE_BANCO IN ('PROME', 'BPM');

DECLARE @Seed TABLE
(
    CODIGO_MOVIMIENTO VARCHAR(10) NOT NULL,
    NOMBRE_MOVIMIENTO_SEGUN_BANCO VARCHAR(100) NOT NULL,
    CORR_TIPO_MOVIMIENTO INT NOT NULL
);

INSERT INTO @Seed (CODIGO_MOVIMIENTO, NOMBRE_MOVIMIENTO_SEGUN_BANCO, CORR_TIPO_MOVIMIENTO)
VALUES
    (N'REM', N'Remesa deposito', 4),
    (N'NCR', N'Nota de cargo', 6),
    (N'TEF', N'Transferencia recibida', 2),
    (N'CK',  N'Emision de cheque', 1),
    (N'CHQ', N'Cheque', 1),
    (N'DEP', N'Deposito', 4),
    (N'ND',  N'Nota de debito', 6),
    (N'NA',  N'Nota de abono', 7),
    (N'TF',  N'Transferencia', 2),
    (N'TR',  N'Transferencia regional', 2);

DECLARE @inserted INT = 0;

INSERT INTO dbo.BAN_TIPO_MOVI_SEGUN_BANCO
(
    CORR_EMPRESA,
    CORR_TIPO_MOVIMIENTO,
    CORR_BANCO,
    CODIGO_MOVIMIENTO,
    NOMBRE_MOVIMIENTO_SEGUN_BANCO
)
SELECT
    @CORR_EMPRESA,
    S.CORR_TIPO_MOVIMIENTO,
    @CORR_BANCO,
    S.CODIGO_MOVIMIENTO,
    S.NOMBRE_MOVIMIENTO_SEGUN_BANCO
FROM @Seed S
WHERE NOT EXISTS
(
    SELECT 1
    FROM dbo.BAN_TIPO_MOVI_SEGUN_BANCO X
    WHERE X.CORR_EMPRESA = @CORR_EMPRESA
      AND X.CORR_BANCO = @CORR_BANCO
      AND X.CORR_TIPO_MOVIMIENTO = S.CORR_TIPO_MOVIMIENTO
      AND X.CODIGO_MOVIMIENTO = S.CODIGO_MOVIMIENTO
);

SET @inserted = @@ROWCOUNT;

SELECT
    A.CODIGO_MOVIMIENTO,
    A.NOMBRE_MOVIMIENTO_SEGUN_BANCO,
    A.CORR_TIPO_MOVIMIENTO,
    B.NOMBRE_TIPO_MOVIMIENTO
FROM dbo.BAN_TIPO_MOVI_SEGUN_BANCO A
INNER JOIN dbo.BAN_TIPO_MOVI_BANCARIO B
    ON A.CORR_EMPRESA = B.CORR_EMPRESA
   AND A.CORR_TIPO_MOVIMIENTO = B.CORR_TIPO_MOVIMIENTO
INNER JOIN dbo.GEN_BANCO GB
    ON A.CORR_EMPRESA = GB.CORR_EMPRESA
   AND A.CORR_BANCO = GB.CORR_BANCO
WHERE A.CORR_EMPRESA = @CORR_EMPRESA
  AND GB.CLASE_BANCO IN ('PROME', 'BPM')
ORDER BY A.CODIGO_MOVIMIENTO, A.CORR_TIPO_MOVIMIENTO;

PRINT N'Insertados: ' + CAST(@inserted AS NVARCHAR(10));
PRINT N'=== SEED Promerica OK ===';
GO
