/*
  Catálogo GEN_TIPO_MONEDA — monedas del sistema (legacy e-Admin).
  Requerido por: V_CON_PARAMETRO, V_BAN_CUENTA_BANCARIA, PRAL_MTTO_BAN_DOCUMENTO,
  CON_PARAMETRO GetMonedas, reportes contables.

  Ejecutar:
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i SETUP_GEN_TIPO_MONEDA.sql
*/
SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.GEN_TIPO_MONEDA', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[GEN_TIPO_MONEDA]
	(
		[CORR_MONEDA] [int] NOT NULL,
		[NOMBRE_MONEDA] [varchar](50) COLLATE Latin1_General_CS_AS NOT NULL,
		[DESCRIPCION_MONEDA] [varchar](150) COLLATE Latin1_General_CS_AS NULL,
		[SIMBOLO] [varchar](10) COLLATE Latin1_General_CS_AS NULL,
		[ESTADO_MONEDA] [bit] NOT NULL CONSTRAINT [DF_GEN_TIPO_MONEDA_ESTADO] DEFAULT ((1)),
		[USUARIO_CREA] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
		[ESTACION_CREA] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
		[FECHA_CREA] [datetime] NULL,
		[USUARIO_ACTU] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
		[ESTACION_ACTU] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
		[FECHA_ACTU] [datetime] NULL,
		CONSTRAINT [PK_GEN_TIPO_MONEDA] PRIMARY KEY CLUSTERED ([CORR_MONEDA])
	) ON [PRIMARY];

	PRINT N'Tabla GEN_TIPO_MONEDA creada.';
END
ELSE
	PRINT N'Tabla GEN_TIPO_MONEDA ya existe.';
GO

MERGE dbo.GEN_TIPO_MONEDA AS T
USING (
	VALUES
		(1, N'DOLAR', N'DOLARES ESTADOUNIDENSES', N'USD', 1),
		(2, N'COLON', N'COLONES SALVADORENOS', N'SVC', 1)
) AS S (CORR_MONEDA, NOMBRE_MONEDA, DESCRIPCION_MONEDA, SIMBOLO, ESTADO_MONEDA)
	ON T.CORR_MONEDA = S.CORR_MONEDA
WHEN NOT MATCHED BY TARGET THEN
	INSERT (CORR_MONEDA, NOMBRE_MONEDA, DESCRIPCION_MONEDA, SIMBOLO, ESTADO_MONEDA, USUARIO_CREA, FECHA_CREA)
	VALUES (S.CORR_MONEDA, S.NOMBRE_MONEDA, S.DESCRIPCION_MONEDA, S.SIMBOLO, S.ESTADO_MONEDA, N'SYSTEM', GETDATE())
WHEN MATCHED THEN
	UPDATE SET
		NOMBRE_MONEDA = S.NOMBRE_MONEDA,
		DESCRIPCION_MONEDA = S.DESCRIPCION_MONEDA,
		SIMBOLO = S.SIMBOLO,
		ESTADO_MONEDA = S.ESTADO_MONEDA;
GO

IF OBJECT_ID(N'dbo.V_CON_PARAMETRO', N'V') IS NOT NULL
BEGIN
	EXEC sp_refreshview N'dbo.V_CON_PARAMETRO';
	PRINT N'Vista V_CON_PARAMETRO actualizada.';
END
GO

IF OBJECT_ID(N'dbo.V_BAN_CUENTA_BANCARIA', N'V') IS NOT NULL
BEGIN
	EXEC sp_refreshview N'dbo.V_BAN_CUENTA_BANCARIA';
	PRINT N'Vista V_BAN_CUENTA_BANCARIA actualizada.';
END
GO

SELECT CORR_MONEDA, NOMBRE_MONEDA, DESCRIPCION_MONEDA, SIMBOLO, ESTADO_MONEDA
FROM dbo.GEN_TIPO_MONEDA
ORDER BY CORR_MONEDA;
GO
