/*
  Tabla de instancias remotas + sincronización de linked servers.
  Centraliza servidor, usuario, clave y base de datos (CLASS, e-AdminFE, etc.).

  Uso inicial:
    cd "C:\Desarrollo GIT\SGUEES\SGUEES-DB\Scripts"
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -f 65001 -i SETUP_SYS_INSTANCIA_REMOTA.sql

  Tras cambiar datos en SYS_INSTANCIA_REMOTA:
    EXEC dbo.PRAL_ADMIN_SYNC_INSTANCIA_REMOTA;
*/
SET NOCOUNT ON;
GO

PRINT N'=== SYS_INSTANCIA_REMOTA ===';

:r "..\Tables\dbo.SYS_INSTANCIA_REMOTA.sql"
GO

IF OBJECT_ID(N'dbo.V_SYS_INSTANCIA_REMOTA', N'V') IS NOT NULL
	DROP VIEW dbo.V_SYS_INSTANCIA_REMOTA;
GO
:r "..\Views\dbo.V_SYS_INSTANCIA_REMOTA.sql"
GO

IF OBJECT_ID(N'dbo.PRAL_ADMIN_SYNC_INSTANCIA_REMOTA', N'P') IS NOT NULL
	DROP PROCEDURE dbo.PRAL_ADMIN_SYNC_INSTANCIA_REMOTA;
GO
:r "..\Stored Procedures\dbo.PRAL_ADMIN_SYNC_INSTANCIA_REMOTA.sql"
GO

PRINT N'=== Datos iniciales (129) ===';

MERGE dbo.SYS_INSTANCIA_REMOTA AS T
USING (
	SELECT
		v.CODIGO_INSTANCIA,
		v.NOMBRE_LINKED_SERVER,
		v.DESCRIPCION,
		v.SERVIDOR,
		v.NOMBRE_BASE_DATOS,
		v.USUARIO_SQL,
		v.CLAVE_SQL
	FROM (VALUES
		(N'CLASS_UEES', N'CLASS_UEES', N'CLASS legacy — inventario, clientes/proveedores, órdenes', N'192.168.1.129', N'CLASS_UEES', N'sa', N'UEES.1234'),
		(N'EADMINFE', N'EADMINFE', N'e-AdminFE — tipos DIP, forma pago, documentos electrónicos', N'192.168.1.129', N'e-AdminFE', N'sa', N'UEES.1234')
	) v(CODIGO_INSTANCIA, NOMBRE_LINKED_SERVER, DESCRIPCION, SERVIDOR, NOMBRE_BASE_DATOS, USUARIO_SQL, CLAVE_SQL)
) AS S
ON T.CODIGO_INSTANCIA = S.CODIGO_INSTANCIA
WHEN MATCHED THEN
	UPDATE SET
		NOMBRE_LINKED_SERVER = S.NOMBRE_LINKED_SERVER,
		DESCRIPCION = S.DESCRIPCION,
		SERVIDOR = S.SERVIDOR,
		NOMBRE_BASE_DATOS = S.NOMBRE_BASE_DATOS,
		USUARIO_SQL = S.USUARIO_SQL,
		CLAVE_SQL = S.CLAVE_SQL,
		ACTIVO = 1
WHEN NOT MATCHED THEN
	INSERT (
		CODIGO_INSTANCIA, NOMBRE_LINKED_SERVER, DESCRIPCION, SERVIDOR, NOMBRE_BASE_DATOS,
		USUARIO_SQL, CLAVE_SQL, ACTIVO
	)
	VALUES (
		S.CODIGO_INSTANCIA, S.NOMBRE_LINKED_SERVER, S.DESCRIPCION, S.SERVIDOR, S.NOMBRE_BASE_DATOS,
		S.USUARIO_SQL, S.CLAVE_SQL, 1
	);
GO

PRINT N'=== Sincronizar linked servers ===';
EXEC dbo.PRAL_ADMIN_SYNC_INSTANCIA_REMOTA
	@SYS_LOGIN_USUARIO = 'SETUP',
	@SYS_ESTACION = @@SERVERNAME;
GO

PRINT N'=== Verificación ===';
SELECT CODIGO_INSTANCIA, NOMBRE_LINKED_SERVER, SERVIDOR, NOMBRE_BASE_DATOS, USUARIO_SQL, ACTIVO
FROM dbo.V_SYS_INSTANCIA_REMOTA;
GO

SELECT TOP 1 CLIIDU FROM CLASS_UEES.CLASS_UEES.dbo.CLIENTES;
SELECT TOP 1 CORR_TIPO_DIP FROM [EADMINFE].[e-AdminFE].dbo.GEN_TIPO_DIP;
GO

PRINT N'=== SETUP_SYS_INSTANCIA_REMOTA completado ===';
GO
