/*
  Parametros contables minimos para reportes (Libro Diario Mayor, Balance, etc.)
  Requerido por V_CON_PARTIDA_CUENTA_MAYOR y PRAL_IMPR_LIBRO_DIARIO_MAYOR (INNER JOIN CON_PARAMETRO).
*/
SET NOCOUNT ON;

DECLARE @CORR_EMPRESA INT = 1;

IF NOT EXISTS (SELECT 1 FROM CON_PARAMETRO WHERE CORR_EMPRESA = @CORR_EMPRESA)
BEGIN
    INSERT INTO CON_PARAMETRO
    (
        CORR_EMPRESA,
        NOMBRE_PUESTO1, DESCRIPCION_PUESTO1,
        NOMBRE_PUESTO2, DESCRIPCION_PUESTO2,
        NOMBRE_PUESTO3, DESCRIPCION_PUESTO3,
        NIVEL_CUENTA_MAYOR,
        CORR_CENTRO_COSTO_DEF,
        CORR_MONEDA,
        CUENTA_CONTABLE_PERDIDA,
        CUENTA_CONTABLE_GANANCIA,
        CUENTA_CONTABLE_IVA_DEBITO,
        CUENTA_CONTABLE_IVA_CREDITO,
        CUENTA_CONTABLE_IVA_RETENIDO,
        CUENTA_CONTABLE_IVA_PERCIBIDO,
        CUENTA_CONTABLE_RENTA,
        CUENTA_CONTABLE_CAJA,
        CUENTA_CONTABLE_CAJA_CHICA,
        APLICAR_DOC_CONTA,
        PERIODO_MOSTRAR,
        CARACTER_SEPARADOR,
        INCLUIR_PARTIDA_CIERRE,
        INCLUIR_PARTIDA_LIQUIDACION,
        MOSTRAR_FECHA_IMPRESION,
        PREFIJO
    )
    VALUES
    (
        @CORR_EMPRESA,
        N'', N'',
        N'', N'',
        N'', N'',
        3,
        1,
        1,
        N'310801',
        N'310601',
        N'2103',
        N'1103',
        N'210204',
        N'110302',
        N'2103',
        N'1101',
        N'1101',
        0,
        N'YY',
        N'-',
        0,
        0,
        0,
        N''
    );
END
ELSE
BEGIN
    UPDATE CON_PARAMETRO
    SET NIVEL_CUENTA_MAYOR = CASE WHEN ISNULL(NIVEL_CUENTA_MAYOR, 0) <= 0 THEN 3 ELSE NIVEL_CUENTA_MAYOR END,
        CORR_CENTRO_COSTO_DEF = ISNULL(CORR_CENTRO_COSTO_DEF, 1),
        CORR_MONEDA = CASE WHEN ISNULL(CORR_MONEDA, 0) <= 0 THEN 1 ELSE CORR_MONEDA END,
        CUENTA_CONTABLE_PERDIDA = CASE WHEN ISNULL(CUENTA_CONTABLE_PERDIDA, '') IN ('', '3108') THEN N'310801' ELSE CUENTA_CONTABLE_PERDIDA END,
        CUENTA_CONTABLE_GANANCIA = CASE WHEN ISNULL(CUENTA_CONTABLE_GANANCIA, '') IN ('', '3106') THEN N'310601' ELSE CUENTA_CONTABLE_GANANCIA END
    WHERE CORR_EMPRESA = @CORR_EMPRESA;
END

SELECT CORR_EMPRESA, NIVEL_CUENTA_MAYOR, CORR_MONEDA,
       CUENTA_CONTABLE_PERDIDA, CUENTA_CONTABLE_GANANCIA
FROM CON_PARAMETRO
WHERE CORR_EMPRESA = @CORR_EMPRESA;

GO
