/*
  Prueba importación Promerica — plantilla ban-concilia-import-promerica.xlsx
  Conciliación: empresa 1, cuenta 2, conciliación 1 (DI)
*/
SET NOCOUNT ON;

DECLARE @CORR_EMPRESA INT = 1;
DECLARE @CORR_CUENTA_BANCO INT = 2;
DECLARE @CORR_CONCILIACION INT = 1;
DECLARE @CORR_BANCO INT = 8;
DECLARE @SYS_LOGIN_USUARIO VARCHAR(30) = 'erp';
DECLARE @SYS_ESTACION VARCHAR(50) = 'CURSOR-TEST';
DECLARE @SYS_FILAS_AFECTADAS INT;
DECLARE @SYS_NUMERO_ERROR NUMERIC(38, 0);
DECLARE @SYS_MENSAJE_ERROR VARCHAR(4000);

DECLARE @IMPORT dbo.T_BAN_CONCILIACION_BANCARIA_MOV_EXCEL;

INSERT INTO @IMPORT
(
    CORR,
    NUMERO_REFERENCIA_BANCO,
    CODIGO_TIPO_MOVIMIENTO,
    NOMBRE_TIPO_MOVIMIENTO,
    FECHA_MOVIMIENTO,
    MONTO_CARGO,
    MONTO_ABONO,
    SALDO
)
VALUES
    (1, '8197067', 'REM', 'Remesa deposito', '20260115', 0.00, 1500.00, 0.00),
    (2, '8197068', 'NCR', 'Nota de cargo', '20260116', 250.50, 0.00, 0.00),
    (3, '8197069', 'TEF', 'Transferencia recibida', '20260117', 0.00, 3200.00, 0.00);

EXEC dbo.PRAL_GENE_BAN_CONCILIA_BANCARIA_MOV_EXCEL
    @CORR_EMPRESA = @CORR_EMPRESA,
    @CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO,
    @CORR_CONCILIACION = @CORR_CONCILIACION OUTPUT,
    @CORR_BANCO = @CORR_BANCO,
    @BAN_CONCILIA_BANCARIA_MOV_EXCEL = @IMPORT,
    @SYS_LOGIN_USUARIO = @SYS_LOGIN_USUARIO,
    @SYS_ESTACION = @SYS_ESTACION,
    @SYS_FILAS_AFECTADAS = @SYS_FILAS_AFECTADAS OUTPUT,
    @SYS_NUMERO_ERROR = @SYS_NUMERO_ERROR OUTPUT,
    @SYS_MENSAJE_ERROR = @SYS_MENSAJE_ERROR OUTPUT;

SELECT
    @CORR_CONCILIACION AS CORR_CONCILIACION,
    @SYS_NUMERO_ERROR AS SYS_NUMERO_ERROR,
    @SYS_MENSAJE_ERROR AS SYS_MENSAJE_ERROR,
    @SYS_FILAS_AFECTADAS AS SYS_FILAS_AFECTADAS;

IF @SYS_NUMERO_ERROR = 0
BEGIN
    SELECT
        D.CORR_CONCILIACION_DETA,
        D.FECHA_MOVIMIENTO,
        D.NUMERO_REFERENCIA_BANCO,
        D.CODIGO_TRANSACCION,
        D.DESCRIPCION_TRANSACCION,
        TM.NOMBRE_TIPO_MOVIMIENTO,
        D.MONTO_CARGO,
        D.MONTO_ABONO
    FROM dbo.BAN_CONCILIA_BANCARIA_DETA D
    LEFT JOIN dbo.BAN_TIPO_MOVI_BANCARIO TM
        ON D.CORR_EMPRESA = TM.CORR_EMPRESA
       AND D.CORR_TIPO_MOVIMIENTO = TM.CORR_TIPO_MOVIMIENTO
    WHERE D.CORR_EMPRESA = @CORR_EMPRESA
      AND D.CORR_CUENTA_BANCO = @CORR_CUENTA_BANCO
      AND D.CORR_CONCILIACION = @CORR_CONCILIACION
    ORDER BY D.CORR_CONCILIACION_DETA;
END
