/*
  Compara Balance y Estado de Resultados CLASS vs SGUEES en una fecha corte.
  Uso:
    sqlcmd -S 192.168.0.250 -U erp -d SGUEES -v ANIO=2026 -v MES=5 -i VALIDATE_CLASS_VS_SGUEES.sql
*/
SET NOCOUNT ON;

DECLARE @ANIO INT = TRY_CONVERT(INT, '$(ANIO)');
DECLARE @MES INT = TRY_CONVERT(INT, '$(MES)');
IF @ANIO IS NULL SET @ANIO = 2026;
IF @MES IS NULL SET @MES = 5;

DECLARE @FECHA DATE = EOMONTH(DATEFROMPARTS(@ANIO, @MES, 1));

PRINT '=== Corte: ' + CONVERT(VARCHAR(10), @FECHA, 103) + ' ===';

-- Totales SGUEES
CREATE TABLE #S (
    CORR_EMPRESA INT, CUENTA_CONTABLE VARCHAR(30), CUENTA_MAYOR VARCHAR(30),
    ES_DEBE BIT, ES_HABER BIT, SALDO_INICIAL DECIMAL(18, 2),
    CARGO_PERIODO DECIMAL(18, 2), ABONO_PERIODO DECIMAL(18, 2), SALDO_FINAL DECIMAL(18, 2)
);
INSERT #S
EXEC dbo.PRAL_GENE_CON_SALDO_INICIAL
    @CORR_EMPRESA = 1, @FECHA_CONSULTA = @FECHA, @OPCION_CONSULTA = 0,
    @MAYORIZA = 1, @APLICA_DEBE_HABE = 1, @PARTIDA_CIERRE = 0, @PARTIDA_LIQUIDACION = 0, @NIVEL = 3;

SELECT 'SGUEES Balance' AS ORIGEN,
       SUM(CASE WHEN C.CLASE_RUBRO = 'AC' AND S.CUENTA_CONTABLE = C.CUENTA_CONTABLE THEN S.SALDO_FINAL ELSE 0 END) AS ACTIVO,
       SUM(CASE WHEN C.CLASE_RUBRO = 'PA' AND S.CUENTA_CONTABLE = C.CUENTA_CONTABLE THEN S.SALDO_FINAL ELSE 0 END) AS PASIVO,
       SUM(CASE WHEN C.CLASE_RUBRO = 'PT' AND S.CUENTA_CONTABLE = C.CUENTA_CONTABLE THEN S.SALDO_FINAL ELSE 0 END) AS PATRIMONIO
FROM #S S
INNER JOIN CON_CATALOGO_CUENTA C ON C.CORR_EMPRESA = 1 AND C.CUENTA_CONTABLE = S.CUENTA_CONTABLE
WHERE C.NIVEL = 3;

CREATE TABLE #ER (
    CORR_EMPRESA INT, CUENTA_CONTABLE VARCHAR(30), CUENTA_MAYOR VARCHAR(30),
    ES_DEBE BIT, ES_HABER BIT, SALDO_INICIAL DECIMAL(18, 2),
    CARGO_PERIODO DECIMAL(18, 2), ABONO_PERIODO DECIMAL(18, 2), SALDO_FINAL DECIMAL(18, 2)
);
INSERT #ER
EXEC dbo.PRAL_GENE_CON_SALDO_INICIAL
    @CORR_EMPRESA = 1, @FECHA_CONSULTA = @FECHA, @OPCION_CONSULTA = 2,
    @MAYORIZA = 0, @APLICA_DEBE_HABE = 1, @PARTIDA_CIERRE = 0, @PARTIDA_LIQUIDACION = 0, @NIVEL = 3;

SELECT 'SGUEES ER acumulado' AS ORIGEN,
       SUM(CASE WHEN C.CLASE_RUBRO = 'IN' THEN S.SALDO_FINAL ELSE 0 END) AS INGRESOS,
       SUM(CASE WHEN C.CLASE_RUBRO = 'GA' THEN S.SALDO_FINAL ELSE 0 END) AS GASTOS,
       SUM(CASE WHEN C.CLASE_RUBRO = 'IN' THEN S.SALDO_FINAL ELSE -S.SALDO_FINAL END) AS RESULTADO_NETO
FROM #ER S
INNER JOIN CON_CATALOGO_CUENTA C ON C.CORR_EMPRESA = 1 AND C.CUENTA_CONTABLE = S.CUENTA_CONTABLE;

SELECT 'SGUEES ER detalle' AS TIPO, S.CUENTA_CONTABLE, C.NOMBRE_CUENTA, C.CLASE_RUBRO,
       S.SALDO_INICIAL, S.CARGO_PERIODO, S.ABONO_PERIODO, S.SALDO_FINAL
FROM #ER S
INNER JOIN CON_CATALOGO_CUENTA C ON C.CORR_EMPRESA = 1 AND C.CUENTA_CONTABLE = S.CUENTA_CONTABLE
WHERE ABS(S.SALDO_FINAL) > 0.01 OR ABS(S.CARGO_PERIODO) > 0.01
ORDER BY C.CLASE_RUBRO, S.CUENTA_CONTABLE;

PRINT 'Ejecute PREVIEW CLASS: EXEC PRAL_MIGR_CLASS_SALDO_INICIAL_BALANCE @ANIO=' + CAST(@ANIO AS VARCHAR(4))
    + ', @MES=' + CAST(@MES AS VARCHAR(2)) + ', @MODO=''PREVIEW'';';

DROP TABLE #S;
DROP TABLE #ER;
GO
