SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: LOGIN del jefe activo más reciente de una unidad.
-- Cómo lo hace: jefes de organigrama + empleado activo + GEN_PERSONA_USUARIO.
CREATE OR ALTER FUNCTION dbo.SEG_FN_ObtenerJefeDeUnidad
(
	@CORR_UNIDAD INT
)
RETURNS VARCHAR(30)
AS
BEGIN
	DECLARE @Login VARCHAR(30);

	SELECT TOP (1) @Login = PU.LOGIN_SISTEMA
	FROM dbo.SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES J
	INNER JOIN dbo.GEN_EMPLEADO GE
		ON GE.CORR_EMPLEADO = J.CORR_EMPLEADO
	   AND GE.CORR_EMPRESA = J.CORR_EMPRESA
	INNER JOIN dbo.GEN_PERSONA_USUARIO PU
		ON PU.CORR_PERSONA = GE.CORR_PERSONA
	WHERE J.CORR_UNIDAD = @CORR_UNIDAD
	  AND J.ACTIVO = 1
	  AND (J.FECHA_FIN IS NULL OR J.FECHA_FIN >= CAST(GETDATE() AS DATE))
	  AND ISNULL(GE.ACTIVO_EMPLEADO, 0) = 1
	ORDER BY J.FECHA_INICIO DESC, PU.LOGIN_SISTEMA;

	RETURN @Login;
END
GO
