SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: obtiene LOGIN del empleado activo por CORR_EMPLEADO.
-- Cómo lo hace: GEN_EMPLEADO (ACTIVO) + GEN_PERSONA_USUARIO.
CREATE OR ALTER FUNCTION dbo.SEG_FN_ObtenerLoginPorCodigoEmpleado
(
	@CORR_EMPLEADO INT
)
RETURNS VARCHAR(30)
AS
BEGIN
	DECLARE @Login VARCHAR(30);

	SELECT TOP (1) @Login = PU.LOGIN_SISTEMA
	FROM dbo.GEN_EMPLEADO E
	INNER JOIN dbo.GEN_PERSONA_USUARIO PU
		ON PU.CORR_PERSONA = E.CORR_PERSONA
	WHERE E.CORR_EMPLEADO = @CORR_EMPLEADO
	  AND ISNULL(E.ACTIVO_EMPLEADO, 0) = 1
	ORDER BY PU.LOGIN_SISTEMA;

	RETURN @Login;
END
GO
