SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[FN_NUMERO_DOC]
(
	@ANIO INT,
	@MES INT,
	@CORR INT,
	@NUMERO INT=NULL
)
RETURNS VARCHAR(9)
AS	
BEGIN	
	DECLARE @NUMERO_DOC VARCHAR(9),@UNIDAD INT=1

	SET @UNIDAD = CONVERT(VARCHAR,@UNIDAD) + CONVERT(VARCHAR,REPLICATE('0',ISNULL(@NUMERO,0)))

    SELECT @NUMERO_DOC=(((CONVERT(INT,SUBSTRING(LTRIM(RTRIM(CONVERT(VARCHAR,@ANIO))),3,2))*100)+@MES)*@UNIDAD)+@CORR

    RETURN @NUMERO_DOC
END
GO