SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Qué hace: todos los logins de jefes activos de una unidad (multi-actor).
-- Cómo lo hace: misma regla que SEG_FN_ObtenerJefeDeUnidad, en forma tabular.
CREATE OR ALTER FUNCTION dbo.SEG_FN_ObtenerJefesDeUnidad
(
	@CORR_UNIDAD INT
)
RETURNS TABLE
AS
RETURN
(
	SELECT PU.LOGIN_SISTEMA AS LoginDestino
	FROM dbo.SC_ORGANIGRAMA_ESTRUCTURAL_JEFES_UNIDADES J
	INNER JOIN dbo.GEN_EMPLEADO GE
		ON GE.CORR_EMPLEADO = J.CORR_EMPLEADO
	   AND GE.CORR_EMPRESA = J.CORR_EMPRESA
	INNER JOIN dbo.GEN_PERSONA_USUARIO PU
		ON PU.CORR_PERSONA = GE.CORR_PERSONA
	WHERE J.CORR_UNIDAD = @CORR_UNIDAD
	  AND J.ACTIVO = 1
	  AND (J.FECHA_FIN IS NULL OR J.FECHA_FIN >= CAST(GETDATE() AS DATE))
	  AND ISNULL(GE.ACTIVO_EMPLEADO, 0) = 1
);
GO
