//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgueesRpt.Layouts.SelectionHiring
{
	public partial class ImprimirRequisicion
	{
		protected global::System.Web.UI.WebControls.Literal litError;
		protected global::DevExpress.XtraReports.Web.ASPxWebDocumentViewer webDocumentViewer;
	}
}
