SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_DOCUMENTO_APLICAR]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_DOCUMENTO INT OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
	DECLARE
	@ANIO_PERIODO_BITACORA INT=YEAR(GETDATE()), @CORR_BITACORA_TRANS INT=0, @FECHA_BITACORA DATE=GETDATE(), @LLAVE_TRANSACCION VARCHAR(250),@REFERENCIA_TRANSACCION VARCHAR(500), 
	@USUARIO_CREA_TRANS VARCHAR(50), @ESTACION_CREA_TRANS VARCHAR(50), @FECHA_CREA_TRANS DATETIME,@USUARIO_ACTU_TRANS VARCHAR(50), @ESTACION_ACTU_TRANS VARCHAR(50),
	@FECHA_ACTU_TRANS DATETIME, @USUARIO_CREA_BITACORA VARCHAR(50),@ESTACION_CREA_BITACORA VARCHAR(50), @FECHA_CREA_BITACORA DATETIME=GETDATE(),
	@CODIGO_OPCION VARCHAR(150)='COM_DOCUMENTO',@CLASE_BITACORA VARCHAR(3)='AP'

	DECLARE @CORR_PROVEEDOR INT, @CODIGO_GENERACION VARCHAR(50), @NUMERO_DOCUMENTO VARCHAR(150), @SERIE VARCHAR(25),
	@ANIO_PERIODO_IVA INT, @MES_PERIODO_IVA INT, @ANIO_PERIODO_MAX INT, @MES_PERIODO_MAX INT
	DECLARE @MONTO_INTERNACION DECIMAL(18,2), @MONTO_IMPORTACION DECIMAL(18,2)
BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF NOT EXISTS(SELECT 1 FROM COM_DOCUMENTO 
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND ANIO_PERIODO=@ANIO_PERIODO
				  AND MES_PERIODO=@MES_PERIODO
				  AND CORR_DOCUMENTO=@CORR_DOCUMENTO
				  AND TOTAL_DOCUMENTO>0
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='El total del documento debe ser mayor a 0',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF EXISTS(SELECT 1 FROM COM_DOCUMENTO 
				  WHERE CORR_EMPRESA=1
				  AND ANIO_PERIODO=2025
				  AND MES_PERIODO=9
				  AND CORR_DOCUMENTO=13
				  AND ISNULL(CODIGO_GENERACION,'')='' 
				  AND ISNULL(NUMERO_DOCUMENTO,'')=''
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Debe asignar un numero de documento o codigo de generación',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		SELECT @ANIO_PERIODO_IVA=ISNULL(ANIO_PERIODO_IVA,0), 
		@MES_PERIODO_IVA=ISNULL(MES_PERIODO_IVA,0),
		@ANIO_PERIODO_MAX=YEAR(DATEADD(MONTH,3,FECHA_DOCUMENTO)), 
		@MES_PERIODO_MAX=MONTH(DATEADD(MONTH,3,FECHA_DOCUMENTO))
		FROM COM_DOCUMENTO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO

		IF (@ANIO_PERIODO_IVA*100)+@MES_PERIODO_IVA > (@ANIO_PERIODO_MAX*100)+@MES_PERIODO_MAX
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='No puede incluir en el libro de IVA de ' + dbo.NOMBRE_MES(@MES_PERIODO_IVA) + ' de ' + CONVERT(VARCHAR(4),@ANIO_PERIODO_IVA) + ' un documento con mas de 3 meses de antiguedad', @SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF (@ANIO_PERIODO_IVA=0 OR @MES_PERIODO_IVA=0 )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Debe seleccionar el mes a declarar IVA',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF EXISTS(SELECT 1 
				  FROM [e-AdminFE].dbo.COM_LIBRO_IVA A 
				  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
				  AND A.ANIO_PERIODO=@ANIO_PERIODO_IVA
				  AND A.MES_PERIODO=@MES_PERIODO_IVA
				  AND A.ESTADO_LIBRO_IVA='CE')
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30004,@SYS_MENSAJE_ERROR='El Libro de IVA de ' + dbo.NOMBRE_MES(@MES_PERIODO_IVA) + ' de ' + CONVERT(VARCHAR(4),@ANIO_PERIODO_IVA) + ' ya esta cerrado.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		SELECT @CORR_PROVEEDOR=A.CORR_PROVEEDOR, 
		@CODIGO_GENERACION=LTRIM(RTRIM(A.CODIGO_GENERACION)), 
		@NUMERO_DOCUMENTO=LTRIM(RTRIM(A.NUMERO_DOCUMENTO)), 
		@SERIE=A.SERIE
		FROM COM_DOCUMENTO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.MES_PERIODO=@MES_PERIODO
		AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO

		IF LEN(@CODIGO_GENERACION)>0
		BEGIN
			IF EXISTS(SELECT 1 
					  FROM COM_DOCUMENTO A
					  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					  AND A.CORR_PROVEEDOR=@CORR_PROVEEDOR
					  AND A.CODIGO_GENERACION=@CODIGO_GENERACION
					  AND NOT EXISTS(SELECT 1 FROM COM_DOCUMENTO B
									 WHERE A.CORR_EMPRESA=B.CORR_EMPRESA
									 AND A.ANIO_PERIODO=B.ANIO_PERIODO
									 AND A.MES_PERIODO=B.MES_PERIODO
									 AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO
									 AND A.CORR_EMPRESA=@CORR_EMPRESA
									 AND A.ANIO_PERIODO=@ANIO_PERIODO
									 AND A.MES_PERIODO=@MES_PERIODO
									 AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO)
					  )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30003,@SYS_MENSAJE_ERROR='El documento ya existe! no puede ser aplicado',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END ELSE
		BEGIN
			IF EXISTS(SELECT 1 
					  FROM COM_DOCUMENTO A
					  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					  AND A.CORR_PROVEEDOR=@CORR_PROVEEDOR
					  AND A.SERIE=@SERIE
					  AND A.NUMERO_DOCUMENTO=@NUMERO_DOCUMENTO
					  AND NOT EXISTS(SELECT 1 FROM COM_DOCUMENTO B
									 WHERE A.CORR_EMPRESA=B.CORR_EMPRESA
									 AND A.ANIO_PERIODO=B.ANIO_PERIODO
									 AND A.MES_PERIODO=B.MES_PERIODO
									 AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO
									 AND A.CORR_EMPRESA=@CORR_EMPRESA
									 AND A.ANIO_PERIODO=@ANIO_PERIODO
									 AND A.MES_PERIODO=@MES_PERIODO
									 AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO)
					  )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30003,@SYS_MENSAJE_ERROR='El documento ya existe! no puede ser aplicado',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END

		SELECT @MONTO_INTERNACION=SUM(CASE WHEN B.CLASE_RUBRO='INT' THEN A.MONTO_RUBRO ELSE 0 END),
		@MONTO_IMPORTACION=SUM(CASE WHEN B.CLASE_RUBRO='IMP' THEN A.MONTO_RUBRO ELSE 0 END)
		FROM COM_DOCUMENTO_TOTAL A
		INNER JOIN GEN_RUBRO B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.CORR_RUBRO = B.CORR_RUBRO
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.MES_PERIODO=@MES_PERIODO
		AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO

		IF (ISNULL(@MONTO_INTERNACION,0)<>0 AND ISNULL(@MONTO_IMPORTACION,0)<>0 )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='No puede incluirse internación e importación en un mismo documento',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		------------------------------------------------------------------------
		-------------  BITACORA -------------- 
		SELECT @LLAVE_TRANSACCION='Año: '+CONVERT(VARCHAR,A.ANIO_PERIODO) COLLATE DATABASE_DEFAULT+'Mes: '+CONVERT(VARCHAR,A.MES_PERIODO) COLLATE DATABASE_DEFAULT+' Correlativo No.: '+CONVERT(VARCHAR,A.CORR_DOCUMENTO) COLLATE DATABASE_DEFAULT,
				@REFERENCIA_TRANSACCION= ' Fecha: '+ CONVERT(VARCHAR,A.FECHA_DOCUMENTO) COLLATE DATABASE_DEFAULT
										+', Proveedor: '+A.NOMBRE_PROVEEDOR COLLATE DATABASE_DEFAULT
										+', Observaciones: '+A.DESCRIPCION_PARTIDA COLLATE DATABASE_DEFAULT,
				@USUARIO_CREA_TRANS=A.USUARIO_CREA, @ESTACION_CREA_TRANS=A.ESTACION_CREA, @FECHA_CREA_TRANS=A.FECHA_CREA,
				@USUARIO_ACTU_TRANS=A.USUARIO_ACTU, @ESTACION_ACTU_TRANS=A.ESTACION_ACTU, @FECHA_ACTU_TRANS=A.FECHA_ACTU
		FROM V_COM_DOCUMENTO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO

		UPDATE COM_DOCUMENTO SET 
		ESTADO_DOCUMENTO='AP'
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

		--Executando el procedimiento de la bitacora
		EXECUTE PRAL_MTTO_COM_BITACORA
		1,--@TIPO_ACTUALIZA ,                               
		@CORR_EMPRESA ,      
		@ANIO_PERIODO_BITACORA,
		@CORR_BITACORA_TRANS  OUTPUT,
		@FECHA_BITACORA ,                    
		@CODIGO_OPCION,                               
		@CLASE_BITACORA ,                              
		@LLAVE_TRANSACCION ,                           
		@REFERENCIA_TRANSACCION ,                      
		@USUARIO_CREA_TRANS ,                          
		@ESTACION_CREA_TRANS,                         
		@FECHA_CREA_TRANS ,         
		@USUARIO_ACTU_TRANS ,                          
		@ESTACION_ACTU_TRANS ,                         
		@FECHA_ACTU_TRANS ,         
		@SYS_LOGIN_USUARIO, --@USUARIO_CREA_BITACORA
		@SYS_ESTACION, --@ESTACION_CREA_BITACORA                      
		@FECHA_CREA_BITACORA ,      
		@SYS_LOGIN_USUARIO,                           
		@SYS_ESTACION ,                                
		@SYS_FILAS_AFECTADAS OUTPUT,
		@SYS_NUMERO_ERROR  OUTPUT,      
		@SYS_MENSAJE_ERROR  OUTPUT

	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DATETIME,
		@CORR_SUSCRIPCION INT=3,
		@CORR_CONFI_PAIS INT=1

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		--EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO