SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_ADMIN_BITACORA_SISTEMA]
(
@TIPO_ACTUALIZA INT,
@CORR_BITACORA numeric(38,0) OUTPUT,
@TIPO_BITACORA VARCHAR(2),
@NUMERO_ERROR INT,
@SEVERITY_ERROR INT,
@ESTADO_ERROR INT,
@ORIGEN_ERROR NVARCHAR(126),
@LINEA_ERROR INT,
@MENSAJE_ERROR NVARCHAR(4000),
@USUARIO_CREA VARCHAR(30),
@FECHA_CREA DATETIME,
@ESTACION_CREA VARCHAR(50)
)
AS
BEGIN
	SET NOCOUNT ON
	
	IF @TIPO_ACTUALIZA=1 --Adicionar
	BEGIN
		INSERT INTO ADMIN_BITACORA_SISTEMA
		(TIPO_BITACORA,NUMERO_ERROR,SEVERITY_ERROR,ESTADO_ERROR,ORIGEN_ERROR,LINEA_ERROR,MENSAJE_ERROR,USUARIO_CREA,FECHA_CREA,ESTACION_CREA)
		VALUES
		(@TIPO_BITACORA,@NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@MENSAJE_ERROR,@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA)	
	END ELSE
	IF @TIPO_ACTUALIZA=2 --Adicionar
	BEGIN
		UPDATE ADMIN_BITACORA_SISTEMA
		SET TIPO_BITACORA=@TIPO_BITACORA,
		NUMERO_ERROR=@NUMERO_ERROR,
		SEVERITY_ERROR=@SEVERITY_ERROR,
		ESTADO_ERROR=@ESTADO_ERROR,
		ORIGEN_ERROR=@ORIGEN_ERROR,
		LINEA_ERROR=@LINEA_ERROR,
		MENSAJE_ERROR=@MENSAJE_ERROR
		WHERE CORR_BITACORA=@CORR_BITACORA 
	END ELSE
	IF @TIPO_ACTUALIZA=3 --Adicionar
	BEGIN
		DELETE ADMIN_BITACORA_SISTEMA
		WHERE CORR_BITACORA=@CORR_BITACORA
	END
			
	SELECT @CORR_BITACORA= @@IDENTITY
END
RETURN 0
GO