SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_SEG_SISTEMA]
(
	@TIPO_ACTUALIZA INT,
	@CODIGO_SISTEMA varchar(30) OUTPUT,
	@NOMBRE_SISTEMA varchar(100),
	@IMAGEN_SISTEMA varchar(25),
	@PREFIJO varchar(10),
	@NOMBRE_MODULO varchar(150),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @CODIGO_SISTEMA=ISNULL(MAX(CODIGO_SISTEMA),0)+1
			FROM SEG_SISTEMA

			INSERT INTO SEG_SISTEMA
			(CODIGO_SISTEMA,NOMBRE_SISTEMA,IMAGEN_SISTEMA,PREFIJO,NOMBRE_MODULO)
			VALUES
			(@CODIGO_SISTEMA,@NOMBRE_SISTEMA,@IMAGEN_SISTEMA,@PREFIJO,@NOMBRE_MODULO)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE SEG_SISTEMA SET
			NOMBRE_SISTEMA=@NOMBRE_SISTEMA,
			IMAGEN_SISTEMA=@IMAGEN_SISTEMA,
			PREFIJO=@PREFIJO,
			NOMBRE_MODULO=@NOMBRE_MODULO
			WHERE CODIGO_SISTEMA=@CODIGO_SISTEMA
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM SEG_SISTEMA
			WHERE CODIGO_SISTEMA=@CODIGO_SISTEMA
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO