SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Alex Hernandez>
-- Create date: <15/07/2025>
-- Description:	<Anulacion de CR>
-- =============================================
CREATE PROCEDURE [dbo].[PRAL_GENE_COM_DOCUMENTO_ANULAR_CR]
@CORR_EMPRESA	INT,
@ANIO_PERIODO INT,
@MES_PERIODO INT,
@CORR_DOCUMENTO INT OUTPUT ,
@MOTIVO_ANULACION VARCHAR(700),
@SYS_LOGIN_USUARIO VARCHAR(30),
@SYS_ESTACION VARCHAR(50),
@SYS_FILAS_AFECTADAS INT OUTPUT,
@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
AS
DECLARE @USUARIO VARCHAR(50), @FECHA_DOC datetime
BEGIN
   SET NOCOUNT ON;
		
		SELECT  @FECHA_DOC=(FECHA_CR+1) FROM V_COM_DOCUMENTO_CR WHERE CORR_DOCUMENTO=@CORR_DOCUMENTO AND MES_PERIODO=@MES_PERIODO AND ANIO_PERIODO=@ANIO_PERIODO

		IF (  GETDATE() > @FECHA_DOC )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='NO SE PUEDE ANULAR UN COMPROBANTE DE RETENCION SI HAN TRANSCURRIDO MAS DE 24 HORAS DESDE LA CREACION',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
		BEGIN TRY
			
			SELECT @USUARIO= ISNULL(USRLOG,'admin') FROM INVC_USUARIOS WHERE USRUID=@SYS_LOGIN_USUARIO

			UPDATE A SET A.SCBESTADO='ANULADO',A.USUARIO_ANULA=@USUARIO,A.FECHA_ANULA=GETDATE()
			FROM SCR_COMPROBANTE A
			INNER JOIN dbo.SCR_DETALLE_COMPROBANTE B ON A.SCBSERIE=B.SCDBSERIE AND A.SCBNUMERO=B.SCDBNUMERO
			WHERE B.ANIO_PERIODO=@ANIO_PERIODO
			AND B.MES_PERIODO=@MES_PERIODO
			AND B.CORR_DOCUMENTO=@CORR_DOCUMENTO
			 
		END TRY

		BEGIN CATCH
			ROLLBACK TRANSACTION PRAL_GENE_COM_DOCUMENTO_CR;
			DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
			RAISERROR(@ErrorMsg, 16, 1);
	    END CATCH
	FINA:
END
	
	--select * from SUEES.dbo.SCR_COMPROBANTE where SCBNUMERO in (6753,6754)
	--SELECT * FROM SUEES.dbo.SJE_CORRELATIVOS

GO