SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_SOLI_COTIZACION_PROVEEDOR_ANULAR]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO INT,
	@CORR_SOLI_COTIZACION int,
	@CORR_PROVEEDOR INT OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		
		UPDATE A SET
		A.ESTADO_COTIZACION='AN'
		FROM COM_COTIZACION A 
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO_SOLI_COTI=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
		AND A.CORR_PROVEEDOR=@CORR_PROVEEDOR

		UPDATE B SET
		B.ESTADO_SOLI_COTIZACION='AN'
		FROM COM_COTIZACION A
		INNER JOIN COM_COTIZACION_DETA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO AND A.CORR_COTIZACION = B.CORR_COTIZACION
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO_SOLI_COTI=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
		AND A.CORR_PROVEEDOR=@CORR_PROVEEDOR

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DATETIME,
		@CORR_SUSCRIPCION INT=3,
		@CORR_CONFI_PAIS INT=1

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		--EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO