SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

/*
  Cambio de estado activo/inactivo (bit) para catálogos maestros SGUEES.
  No usar para documentos con estado varchar (DI/AP/AN).

  Lee el valor actual del campo estado y lo invierte (true → false, false → true).
  El API (repository) envía nombre de tabla, PK, campo estado y si filtra por empresa.
*/
CREATE PROCEDURE [dbo].[PRAL_MTTO_CATALOGO_ESTADO_BIT]
(
	@NOMBRE_TABLA SYSNAME,
	@CAMPO_PK SYSNAME,
	@CAMPO_ESTADO SYSNAME,
	@USA_EMPRESA BIT,
	@CORR_EMPRESA INT,
	@CORR_RELATIVO INT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38, 0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE
		@sql NVARCHAR(MAX),
		@params NVARCHAR(500);

	SELECT
		@SYS_NUMERO_ERROR = 0,
		@SYS_MENSAJE_ERROR = N'',
		@SYS_FILAS_AFECTADAS = 0;

	BEGIN TRY
		IF @CORR_RELATIVO IS NULL OR @CORR_RELATIVO <= 0
		BEGIN
			SELECT
				@SYS_NUMERO_ERROR = 30001,
				@SYS_MENSAJE_ERROR = N'Debe indicar el correlativo del registro.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END

		IF OBJECT_ID(QUOTENAME(@NOMBRE_TABLA), 'U') IS NULL
		   OR COL_LENGTH(@NOMBRE_TABLA, @CAMPO_PK) IS NULL
		   OR COL_LENGTH(@NOMBRE_TABLA, @CAMPO_ESTADO) IS NULL
		   OR COL_LENGTH(@NOMBRE_TABLA, 'USUARIO_ACTU') IS NULL
		   OR COL_LENGTH(@NOMBRE_TABLA, 'FECHA_ACTU') IS NULL
		   OR COL_LENGTH(@NOMBRE_TABLA, 'ESTACION_ACTU') IS NULL
		   OR (@USA_EMPRESA = 1 AND COL_LENGTH(@NOMBRE_TABLA, 'CORR_EMPRESA') IS NULL)
		BEGIN
			SELECT
				@SYS_NUMERO_ERROR = 30003,
				@SYS_MENSAJE_ERROR = N'La configuración del catálogo no coincide con la estructura de la tabla.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END

		IF @USA_EMPRESA = 1 AND (@CORR_EMPRESA IS NULL OR @CORR_EMPRESA <= 0)
		BEGIN
			SELECT
				@SYS_NUMERO_ERROR = 30004,
				@SYS_MENSAJE_ERROR = N'Debe indicar la empresa de sesión.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END

		SET @sql = N'
DECLARE @VALOR_ACTUAL BIT;

SELECT @VALOR_ACTUAL = T.' + QUOTENAME(@CAMPO_ESTADO) + N'
FROM ' + QUOTENAME(@NOMBRE_TABLA) + N' T
WHERE ' + CASE WHEN @USA_EMPRESA = 1 THEN N'T.CORR_EMPRESA = @CORR_EMPRESA AND ' ELSE N'' END
+ N'T.' + QUOTENAME(@CAMPO_PK) + N' = @CORR_RELATIVO;

IF @VALOR_ACTUAL IS NULL
BEGIN
	SELECT @SYS_NUMERO_ERROR_OUT = 30005, @SYS_MENSAJE_ERROR_OUT = N''No existe el registro a actualizar.'', @SYS_FILAS_AFECTADAS_OUT = 0;
	RETURN;
END

UPDATE T
SET
	T.' + QUOTENAME(@CAMPO_ESTADO) + N' = CASE WHEN @VALOR_ACTUAL = 1 THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT) END,
	T.USUARIO_ACTU = @SYS_LOGIN_USUARIO,
	T.FECHA_ACTU = GETDATE(),
	T.ESTACION_ACTU = @SYS_ESTACION
FROM ' + QUOTENAME(@NOMBRE_TABLA) + N' T
WHERE ' + CASE WHEN @USA_EMPRESA = 1 THEN N'T.CORR_EMPRESA = @CORR_EMPRESA AND ' ELSE N'' END
+ N'T.' + QUOTENAME(@CAMPO_PK) + N' = @CORR_RELATIVO;

SELECT @SYS_FILAS_AFECTADAS_OUT = @@ROWCOUNT;';

		SET @params = N'
@CORR_EMPRESA INT,
@CORR_RELATIVO INT,
@SYS_LOGIN_USUARIO VARCHAR(30),
@SYS_ESTACION VARCHAR(50),
@SYS_FILAS_AFECTADAS_OUT INT OUTPUT,
@SYS_NUMERO_ERROR_OUT NUMERIC(38,0) OUTPUT,
@SYS_MENSAJE_ERROR_OUT NVARCHAR(4000) OUTPUT';

		EXEC sp_executesql
			@sql,
			@params,
			@CORR_EMPRESA = @CORR_EMPRESA,
			@CORR_RELATIVO = @CORR_RELATIVO,
			@SYS_LOGIN_USUARIO = @SYS_LOGIN_USUARIO,
			@SYS_ESTACION = @SYS_ESTACION,
			@SYS_FILAS_AFECTADAS_OUT = @SYS_FILAS_AFECTADAS OUTPUT,
			@SYS_NUMERO_ERROR_OUT = @SYS_NUMERO_ERROR OUTPUT,
			@SYS_MENSAJE_ERROR_OUT = @SYS_MENSAJE_ERROR OUTPUT;

		IF @SYS_NUMERO_ERROR <> 0
		BEGIN
			GOTO FINA;
		END

		IF @SYS_FILAS_AFECTADAS = 0
		BEGIN
			SELECT
				@SYS_NUMERO_ERROR = 30006,
				@SYS_MENSAJE_ERROR = N'No se actualizó ningún registro.',
				@SYS_FILAS_AFECTADAS = 0;
			GOTO FINA;
		END
	END TRY
	BEGIN CATCH
		DECLARE
			@CORR_BITACORA INT,
			@SEVERITY_ERROR INT,
			@ESTADO_ERROR INT,
			@ORIGEN_ERROR NVARCHAR(126),
			@LINEA_ERROR INT,
			@SYS_FECHA DATETIME;

		SELECT
			@CORR_BITACORA = 0,
			@SYS_NUMERO_ERROR = ERROR_NUMBER(),
			@SEVERITY_ERROR = ERROR_SEVERITY(),
			@ESTADO_ERROR = ERROR_STATE(),
			@ORIGEN_ERROR = ERROR_PROCEDURE(),
			@LINEA_ERROR = ERROR_LINE(),
			@SYS_MENSAJE_ERROR = ERROR_MESSAGE(),
			@SYS_FECHA = GETDATE();

		EXEC dbo.PRAL_MTTO_ADMIN_BITACORA_SISTEMA
			1,
			@CORR_BITACORA OUTPUT,
			'PM',
			@SYS_NUMERO_ERROR,
			@SEVERITY_ERROR,
			@ESTADO_ERROR,
			@ORIGEN_ERROR,
			@LINEA_ERROR,
			@SYS_MENSAJE_ERROR,
			@SYS_LOGIN_USUARIO,
			@SYS_FECHA,
			@SYS_ESTACION;
	END CATCH;

FINA:
END
GO
