SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[PRAL_MTTO_SEG_MENU_SISTEMA]
(
	@TIPO_ACTUALIZA INT,
	@CODIGO_MENU varchar(10) OUTPUT,
	@NOMBRE_MENU varchar(100),
	@IMAGEN_MENU varchar(25),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @CODIGO_MENU=ISNULL(MAX(CODIGO_MENU),0)+1
			FROM SEG_MENU_SISTEMA

			INSERT INTO SEG_MENU_SISTEMA
			(CODIGO_MENU,NOMBRE_MENU,IMAGEN_MENU)
			VALUES
			(@CODIGO_MENU,@NOMBRE_MENU,@IMAGEN_MENU)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE SEG_MENU_SISTEMA SET
			NOMBRE_MENU=@NOMBRE_MENU,
			IMAGEN_MENU=@IMAGEN_MENU
			WHERE CODIGO_MENU=@CODIGO_MENU
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM SEG_MENU_SISTEMA
			WHERE CODIGO_MENU=@CODIGO_MENU
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO