SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_COM_COTIZACION]
(
	@TIPO_CONSULTA INT,
	@CORR_EMPRESA INT=NULL,
	@ANIO_PERIODO INT=NULL,
	@CORR_COTIZACION INT=NULL,
	@LOGIN_SISTEMA VARCHAR(30)=NULL,
	@OPCION_CONSULTA int=0,
	@PERIODO VARCHAR(250)=NULL,
	@FECHA_INICIAL DATE=NULL,
	@FECHA_FINAL DATE=NULL
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT A.*,B.USUARIO_CREA USUARIO_CREA_SOLI FROM V_COM_COTIZACION A
			INNER JOIN COM_SOLI_COTIZACION B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO_SOLI_COTI = B.ANIO_PERIODO AND A.CORR_SOLI_COTIZACION = B.CORR_SOLI_COTIZACION
			LEFT OUTER JOIN COM_TIPO_SOLI_COTIZA C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.CORR_TIPO_SOLI_COTIZA = C.CORR_TIPO_SOLI_COTIZA
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND ((A.CORR_PROVEEDOR IN(SELECT AA.CORR_PROVEEDOR
									FROM COM_PROVEEDOR_USUARIO AA
									WHERE AA.LOGIN_SISTEMA=@LOGIN_SISTEMA
									AND AA.CORR_PROVEEDOR=A.CORR_PROVEEDOR)
					AND A.ESTADO_COTIZACION IN('SO','AP')
					AND ISNULL(C.CLASE_SOLI_COTIZA,'NO') ='NO')
					OR NOT EXISTS(SELECT 1 FROM COM_PROVEEDOR_USUARIO A
									WHERE A.LOGIN_SISTEMA=@LOGIN_SISTEMA
					)
				)
			ORDER BY A.FECHA_COTIZACION DESC
		END ELSE
		IF @OPCION_CONSULTA=1
		BEGIN 
			SELECT * FROM V_COM_COTIZACION_CONSULTA A
			WHERE A.FECHA_COTIZACION>=@FECHA_INICIAL
			AND A.FECHA_COTIZACION<=@FECHA_FINAL
		END
		
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		SELECT * FROM V_COM_COTIZACION A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_COM_COTIZACION A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.CORR_COTIZACION=@CORR_COTIZACION
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT A.CORR_EMPRESA 
			FROM V_COM_COTIZACION A
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.CORR_COTIZACION=@CORR_COTIZACION
		END
	END

END
GO