SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_DATA_GEN_RUBRO]
(
	@TIPO_CONSULTA int,
	@CORR_EMPRESA int=NULL,
	@CORR_RUBRO int=NULL,
	@CLASE_RUBRO varchar(3)=NULL,
	@DESCRIPCION_RUBRO VARCHAR(100)=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		IF @OPCION_CONSULTA=0 
		BEGIN 
			SELECT * FROM V_GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
		END
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		IF @OPCION_CONSULTA=0 --TODOS LOS RUBROS
		BEGIN 
			SELECT * FROM V_GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
		END ELSE
		IF @OPCION_CONSULTA=1 --MUESTRA DETALLE
		BEGIN 
			SELECT * FROM V_GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND MUESTRA_DETALLE=1
		END ELSE
		IF @OPCION_CONSULTA=2 --SOLO IMPUESTOS
		BEGIN 
			SELECT * FROM V_GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ES_IMPUESTO=1
		END ELSE
		IF @OPCION_CONSULTA=3 --SEGUN CLASE CONSULTA
		BEGIN 
			SELECT * FROM V_GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CLASE_RUBRO=@CLASE_RUBRO	
		END ELSE
		IF @OPCION_CONSULTA=4 --CLASE ISR Y MUN
		BEGIN 
			SELECT * FROM V_GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CLASE_RUBRO IN ('ISR','MUN')
		END ELSE
		IF @OPCION_CONSULTA=5 --CLASE ISR
		BEGIN 
			SELECT * FROM V_GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CLASE_RUBRO = 'ISR'
		END
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_GEN_RUBRO
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_RUBRO=@CORR_RUBRO
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT * FROM V_GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_RUBRO=@CORR_RUBRO 
		END ELSE
		IF @OPCION_CONSULTA=1
		BEGIN
			SELECT CORR_RUBRO FROM V_GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CLASE_RUBRO='GRA'
		END ELSE
		IF @OPCION_CONSULTA=2 --Importación de Cartera de Clientes
		BEGIN
			SELECT CORR_RUBRO FROM V_GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND LTRIM(RTRIM(DESCRIPCION_RUBRO))=LTRIM(RTRIM(@DESCRIPCION_RUBRO))
		END ELSE
		IF @OPCION_CONSULTA=3--Porcentaje para el calculo del IVA en el detalle de COTIZACION
		BEGIN
			SELECT (POR_IMPUESTO/100.00)
			FROM GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CLASE_RUBRO='IVA'
		END ELSE
		IF @OPCION_CONSULTA=4
		BEGIN
			SELECT TOP 1 CORR_RUBRO FROM V_GEN_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CLASE_RUBRO='GRA'
		END
	END

END
GO