SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_BITACORA]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA int,
	@ANIO_PERIODO INT,
	@CORR_BITACORA int OUTPUT,
	@FECHA_BITACORA date,
	@CODIGO_OPCION varchar(30),
	@CLASE_BITACORA varchar(2),
	@LLAVE_TRANSACCION varchar(250),
	@REFERENCIA_TRANSACCION varchar(500),
	@USUARIO_CREA_TRANS varchar(50),
	@ESTACION_CREA_TRANS varchar(50),
	@FECHA_CREA_TRANS datetime,
	@USUARIO_ACTU_TRANS varchar(50),
	@ESTACION_ACTU_TRANS varchar(50),
	@FECHA_ACTU_TRANS datetime,
	@USUARIO_CREA_BITACORA varchar(50),
	@ESTACION_CREA_BITACORA varchar(50),
	@FECHA_CREA_BITACORA datetime,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @CORR_BITACORA=ISNULL(MAX(CORR_BITACORA),0)+1
			FROM COM_BITACORA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO


			INSERT INTO COM_BITACORA
			(CORR_EMPRESA,ANIO_PERIODO,CORR_BITACORA,FECHA_BITACORA,CODIGO_OPCION,CLASE_BITACORA,LLAVE_TRANSACCION,REFERENCIA_TRANSACCION,USUARIO_CREA_TRANS,ESTACION_CREA_TRANS,FECHA_CREA_TRANS,USUARIO_ACTU_TRANS,ESTACION_ACTU_TRANS,FECHA_ACTU_TRANS,USUARIO_CREA_BITACORA,ESTACION_CREA_BITACORA,FECHA_CREA_BITACORA)
			VALUES
			(@CORR_EMPRESA,@ANIO_PERIODO,@CORR_BITACORA,@FECHA_BITACORA,@CODIGO_OPCION,@CLASE_BITACORA,@LLAVE_TRANSACCION,@REFERENCIA_TRANSACCION,@USUARIO_CREA_TRANS,@ESTACION_CREA_TRANS,@FECHA_CREA_TRANS,@USUARIO_ACTU_TRANS,@ESTACION_ACTU_TRANS,@FECHA_ACTU_TRANS,@USUARIO_CREA_BITACORA,@ESTACION_CREA_BITACORA,@FECHA_CREA_BITACORA)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE COM_BITACORA SET
			FECHA_BITACORA=@FECHA_BITACORA,
			CODIGO_OPCION=@CODIGO_OPCION,
			CLASE_BITACORA=@CLASE_BITACORA,
			LLAVE_TRANSACCION=@LLAVE_TRANSACCION,
			REFERENCIA_TRANSACCION=@REFERENCIA_TRANSACCION,
			USUARIO_CREA_TRANS=@USUARIO_CREA_TRANS,
			ESTACION_CREA_TRANS=@ESTACION_CREA_TRANS,
			FECHA_CREA_TRANS=@FECHA_CREA_TRANS,
			USUARIO_ACTU_TRANS=@USUARIO_ACTU_TRANS,
			ESTACION_ACTU_TRANS=@ESTACION_ACTU_TRANS,
			FECHA_ACTU_TRANS=@FECHA_ACTU_TRANS,
			USUARIO_CREA_BITACORA=@USUARIO_CREA_BITACORA,
			ESTACION_CREA_BITACORA=@ESTACION_CREA_BITACORA,
			FECHA_CREA_BITACORA=@FECHA_CREA_BITACORA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_BITACORA=@CORR_BITACORA
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM COM_BITACORA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_BITACORA=@CORR_BITACORA
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO