SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_VALIDA_USUARIO_CLASS]
(
	@USUARIO VARCHAR(100),
	@CLAVE VARCHAR(100)
)
AS
BEGIN
	IF EXISTS (SELECT 1 FROM CLASS_UEES.dbo.USUARIOS WHERE USRUID=@USUARIO COLLATE Modern_Spanish_CI_AS AND CLASS_UEES.DBO.FNLEECLAVE(USRPWD)=@CLAVE COLLATE Modern_Spanish_CI_AS) AND EXISTS(SELECT 1 FROM dbo.SEG_USUARIO WHERE  LOGIN_SISTEMA=@USUARIO COLLATE Modern_Spanish_CI_AS) --AND @USUARIO='admin'
	BEGIN
		SELECT 1 AS RESULT
	END
	ELSE
	BEGIN
		SELECT 0 AS RESULT
	END 
END
GO