SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_SOLI_COTIZACION_DETA_ANULAR]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO INT,
	@CORR_SOLI_COTIZACION int,
	@CORR_SOLI_COTIZACION_DETA INT OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
	DECLARE @COM_SOLI_COTIZACION_PROVEEDOR TABLE
	(
		CORR_EMPRESA INT,
		ANIO_PERIODO INT,
		CORR_SOLI_COTIZACION INT,
		CORR_PROVEEDOR INT
	)
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		
		UPDATE D SET
		D.ESTADO_SOLI_COTIZACION='AN'
		FROM COM_SOLI_COTIZACION_DETA B
		INNER JOIN COM_COTIZACION C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO=C.ANIO_PERIODO_SOLI_COTI AND B.CORR_SOLI_COTIZACION = C.CORR_SOLI_COTIZACION
		INNER JOIN COM_COTIZACION_DETA D ON C.CORR_EMPRESA = D.CORR_EMPRESA AND C.ANIO_PERIODO = D.ANIO_PERIODO AND C.CORR_COTIZACION = D.CORR_COTIZACION
		WHERE B.CORR_EMPRESA=@CORR_EMPRESA
		AND B.ANIO_PERIODO=@ANIO_PERIODO
		AND B.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
		AND B.CORR_SOLI_COTIZACION_DETA=@CORR_SOLI_COTIZACION_DETA
		AND B.CODIGO_ITEM=D.CODIGO_ITEM

		INSERT INTO @COM_SOLI_COTIZACION_PROVEEDOR
		(
		    CORR_EMPRESA,
		    ANIO_PERIODO,
		    CORR_SOLI_COTIZACION,
		    CORR_PROVEEDOR
		)
		SELECT A.CORR_EMPRESA
		,A.ANIO_PERIODO
		,A.CORR_SOLI_COTIZACION
		,A.CORR_PROVEEDOR
		FROM COM_SOLI_COTIZACION_PROVEEDOR A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

		DECLARE @CORR_PROVEEDOR INT
		WHILE EXISTS(SELECT 1 FROM	@COM_SOLI_COTIZACION_PROVEEDOR)
		BEGIN
			SELECT @CORR_PROVEEDOR=CORR_PROVEEDOR 
			FROM @COM_SOLI_COTIZACION_PROVEEDOR
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION

			IF NOT EXISTS(SELECT 1 FROM COM_COTIZACION A
							INNER JOIN COM_COTIZACION_DETA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO = B.ANIO_PERIODO AND A.CORR_COTIZACION = B.CORR_COTIZACION
							WHERE A.CORR_EMPRESA=@CORR_EMPRESA
							AND A.ANIO_PERIODO_SOLI_COTI=@ANIO_PERIODO
							AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
							AND A.CORR_PROVEEDOR=@CORR_PROVEEDOR
							AND B.ESTADO_SOLI_COTIZACION<>'AN')
			BEGIN
				UPDATE A SET
				A.ESTADO_COTIZACION='AN'
				FROM COM_COTIZACION A
				WHERE A.CORR_EMPRESA=@CORR_EMPRESA
				AND A.ANIO_PERIODO_SOLI_COTI=@ANIO_PERIODO
				AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
				AND A.CORR_PROVEEDOR=@CORR_PROVEEDOR
			END

			DELETE FROM @COM_SOLI_COTIZACION_PROVEEDOR
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
			AND CORR_PROVEEDOR=@CORR_PROVEEDOR
		END

		UPDATE A SET
		A.ESTADO_SOLI_COTIZACION='AN'
		FROM COM_SOLI_COTIZACION_DETA A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
		AND A.CORR_SOLI_COTIZACION_DETA=@CORR_SOLI_COTIZACION_DETA

		IF NOT EXISTS(SELECT 1 FROM COM_SOLI_COTIZACION_DETA A
						WHERE A.CORR_EMPRESA=@CORR_EMPRESA
						AND A.ANIO_PERIODO=@ANIO_PERIODO
						AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
						AND A.ESTADO_SOLI_COTIZACION<>'AN')
		BEGIN
			UPDATE A SET
			A.ESTADO_SOLI_COTIZACION='AN'
			FROM COM_SOLI_COTIZACION A
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
		END

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DATETIME,
		@CORR_SUSCRIPCION INT=3,
		@CORR_CONFI_PAIS INT=1

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		--EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO