SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_SEG_USUARIO_PROVEEDOR]
(
	@LOGIN_SISTEMA VARCHAR(30),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	IF NOT EXISTS(SELECT 1 FROM SEG_USUARIO A
				  WHERE A.LOGIN_SISTEMA=@LOGIN_SISTEMA
				  AND A.TIPO_USUARIO=6)
	BEGIN
		GOTO FINA
	END 

	BEGIN TRY

		DELETE A FROM SEG_USUARIO_OPCION A
		WHERE A.LOGIN_SISTEMA=@LOGIN_SISTEMA
		
		INSERT INTO SEG_USUARIO_OPCION
		(
		    LOGIN_SISTEMA,
		    CODIGO_SISTEMA,
		    CODIGO_MENU,
		    CODIGO_OPCION,
		    NUEVO,
		    MODIFICAR,
		    ELIMINAR,
		    IMPRIMIR,
		    USUARIO_CREA,
		    FECHA_CREA,
		    ESTACION_CREA,
		    USUARIO_ACTU,
		    FECHA_ACTU,
		    ESTACION_ACTU
		)
		SELECT @LOGIN_SISTEMA LOGIN_SISTEMA,
		    A.CODIGO_SISTEMA,
		    A.CODIGO_MENU,
		    A.CODIGO_OPCION,
		    A.NUEVO,
		    A.MODIFICAR,
		    A.ELIMINAR,
		    A.IMPRIMIR,
		    @SYS_LOGIN_USUARIO USUARIO_CREA,
		    GETDATE() FECHA_CREA,
		    @SYS_ESTACION ESTACION_CREA,
		    @SYS_LOGIN_USUARIO USUARIO_ACTU,
		    GETDATE() FECHA_ACTU,
		    @SYS_ESTACION ESTACION_ACTU
		FROM SEG_TIPO_USUARIO_OPCION A
		WHERE A.TIPO_USUARIO=6 --Proveedor

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO