SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
-- Stored Procedure para verificar primer login
CREATE PROCEDURE [dbo].[PRAL_DATA_SEG_USUARIO_PRIMER_LOGIN]
    @LOGIN_SISTEMA VARCHAR(30),
    @ES_PRIMER_LOGIN BIT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    
    IF EXISTS (
        SELECT 1 
        FROM [dbo].[SEG_USUARIO_LOGIN_HISTORIAL] 
        WHERE [LOGIN_SISTEMA] = @LOGIN_SISTEMA 
          AND [EXITOSO] = 1
    )
        SET @ES_PRIMER_LOGIN = 0;
    ELSE
        SET @ES_PRIMER_LOGIN = 1;
END;
GO