SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_MTTO_CON_AREA_FUNCIONAL]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA int,
	@CORR_AREA_FUNCIONAL int OUTPUT,
	@NOMBRE_AREA_FUNCIONAL varchar(150),
	@CODIGO_AREA_FUNCIONAL varchar(30),
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @CORR_AREA_FUNCIONAL=ISNULL(MAX(CORR_AREA_FUNCIONAL),0)+1
			FROM CON_AREA_FUNCIONAL
			WHERE CORR_EMPRESA=@CORR_EMPRESA


			INSERT INTO CON_AREA_FUNCIONAL
			(CORR_EMPRESA,CORR_AREA_FUNCIONAL,NOMBRE_AREA_FUNCIONAL,CODIGO_AREA_FUNCIONAL)
			VALUES
			(@CORR_EMPRESA,@CORR_AREA_FUNCIONAL,@NOMBRE_AREA_FUNCIONAL,@CODIGO_AREA_FUNCIONAL)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE CON_AREA_FUNCIONAL SET
			NOMBRE_AREA_FUNCIONAL=@NOMBRE_AREA_FUNCIONAL,
			CODIGO_AREA_FUNCIONAL=@CODIGO_AREA_FUNCIONAL
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_AREA_FUNCIONAL=@CORR_AREA_FUNCIONAL
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM CON_AREA_FUNCIONAL
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_AREA_FUNCIONAL=@CORR_AREA_FUNCIONAL
		END
		
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO