SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_DOCUMENTO]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_TIPO_DOC INT,
	@CORR_DOCUMENTO INT OUTPUT,
	@NUMERO_DOCUMENTO VARCHAR(150),
	@FECHA_DOCUMENTO DATE,
	@FECHA_VENCIMIENTO DATE,
	@CORR_TIENDA INT,
	@CORR_PROVEEDOR INT,
	@NOMBRE_PROVEEDOR VARCHAR(150),
	@DESCRIPCION_PARTIDA VARCHAR(1000),
	@CORR_CONDICION_PAGO INT,
	@DIAS_CREDITO INT,
	@ESTADO_DOCUMENTO VARCHAR(2),
	@ESTA_CONTABILIZADO BIT,
	@TOTAL_DOCUMENTO DECIMAL(12,2),
	@TOTAL_NETO DECIMAL(12,2),
	@SALDO_DOCUMENTO DECIMAL(12,2),
	@CORR_TIPO_GASTO INT,
	@CANTIDAD DECIMAL(12,2) = NULL,
	@USUARIO_CREA VARCHAR(30),
	@FECHA_CREA DATETIME,
	@ESTACION_CREA VARCHAR(50),
	@USUARIO_ACTU VARCHAR(30),
	@FECHA_ACTU DATETIME,
	@ESTACION_ACTU VARCHAR(50),
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT,
	@GENERA_TOTALES BIT = 0,
	@CORR_MONEDA INT=NULL,
	@FACTOR_CAMBIO DECIMAL(16,6)=1,
	@OPERADOR VARCHAR(2)='*',
	@LLEVA_DISTRIBUCION BIT=NULL,
	@SERIE VARCHAR(25)=NULL,
	@NUMERO_UNICO BIGINT=NULL,
	@CODIGO_GENERACION VARCHAR(50)=NULL,
	@NUMERO_CONTROL VARCHAR(50)=NULL,
	@SELLO_RECEPCION VARCHAR(50)=NULL,
	@ANIO_PERIODO_IVA INT=NULL,
	@MES_PERIODO_IVA INT=NULL
)
AS	
	DECLARE @CORR_BITACORA_TRANS INT=0, @FECHA_BITACORA DATE=GETDATE(), @LLAVE_TRANSACCION VARCHAR(250),@REFERENCIA_TRANSACCION VARCHAR(500), 
	@USUARIO_CREA_TRANS VARCHAR(50), @ESTACION_CREA_TRANS VARCHAR(50), @FECHA_CREA_TRANS DATETIME,@USUARIO_ACTU_TRANS VARCHAR(50), @ESTACION_ACTU_TRANS VARCHAR(50),
	@FECHA_ACTU_TRANS DATETIME, @USUARIO_CREA_BITACORA VARCHAR(50),@ESTACION_CREA_BITACORA VARCHAR(50), @FECHA_CREA_BITACORA DATETIME=GETDATE(),
	@CODIGO_OPCION VARCHAR(150)='COM_DOCUMENTO',@CLASE_BITACORA VARCHAR(3)='EL',@ES_ELECTRONICO BIT

	DECLARE @CORR_EMPRESA_FE INT, @CORR_DOCUMENTO_FE INT, @CORR_DOCUMENTO_DOC INT
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY

		IF @TIPO_ACTUALIZA IN (1,2,3)
		BEGIN
			SELECT @ESTADO_DOCUMENTO=ESTADO_DOCUMENTO 
			FROM COM_DOCUMENTO 
			WHERE CORR_EMPRESA=@CORR_EMPRESA 
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			IF (ISNULL(@ESTADO_DOCUMENTO,'')='')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Este doc. compra no existe.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END			
			IF (@ESTADO_DOCUMENTO<>'DI')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Este doc. compra ya está aplicado o anulado, no permite modificarse.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END
		IF @TIPO_ACTUALIZA IN (1, 2) --VALIDACION PREVIA SI SE VA A ADICIONAR O ACTUALIZAR
		BEGIN
			SELECT @ES_ELECTRONICO=A.ES_ELECTRONICO
			FROM GEN_TIPO_DOCUMENTO A
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.CORR_TIPO_DOC=@CORR_TIPO_DOC

			IF NOT EXISTS ( SELECT 1 FROM GEN_TIPO_DOCUMENTO 
							WHERE CORR_EMPRESA=@CORR_EMPRESA
							AND CORR_TIPO_DOC=@CORR_TIPO_DOC  ) --SE VERIFICA QUE EXISTA EL TIPO DE DOCUMENTO SELECCIONADO
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe el Tipo de documento seleccionado.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
			
			IF NOT EXISTS (SELECT 1 FROM GEN_TIPO_GASTO
							WHERE CORR_EMPRESA=@CORR_EMPRESA
							AND CORR_TIPO_GASTO=@CORR_TIPO_GASTO ) --SE VERIFICA QUE EXISTA EL TIPO GASTO SELECCIONADO
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe el Tipo de Gasto seleccionado',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			IF NOT EXISTS ( SELECT 1 FROM V_COM_PROVEEDOR
							WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR ) --SE VERIFICA QUE EXISTA EL PROVEEDOR SELECCIONADO
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe el Proveedor seleccionado',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			IF NOT EXISTS (SELECT 1 FROM COM_CONDICION_PAGO
							WHERE CORR_EMPRESA=@CORR_EMPRESA
							AND CORR_CONDICION_PAGO=@CORR_CONDICION_PAGO ) --SE VERIFICA QUE EXISTA LA CONDICION DE PAGO SELECCIONADA
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='No existe la Condición de Pago seleccionada',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			IF EXISTS (SELECT 1 
					   FROM GEN_TIPO_DOCUMENTO A
					   WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					   AND A.CORR_TIPO_DOC=@CORR_TIPO_DOC
					   AND A.LIBRO_IVA<>'NIN'
					   AND ISNULL(@NUMERO_DOCUMENTO,'')='')
					   AND @ES_ELECTRONICO=0
				   
    		BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Debe ingresar el No. de Documento',@SYS_FILAS_AFECTADAS=0
				GOTO FINA 
			END

			IF EXISTS (SELECT 1
					   FROM COM_DOCUMENTO A
					   WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					   AND (A.ANIO_PERIODO<>@ANIO_PERIODO OR A.ANIO_PERIODO=@ANIO_PERIODO)
					   AND (A.MES_PERIODO<>@MES_PERIODO OR A.MES_PERIODO=@MES_PERIODO)
					   AND A.CORR_DOCUMENTO<>@CORR_DOCUMENTO
					   AND A.CORR_PROVEEDOR=@CORR_PROVEEDOR
					   AND A.NUMERO_DOCUMENTO=LTRIM(RTRIM(@NUMERO_DOCUMENTO))
					   AND A.SERIE=LTRIM(RTRIM(@SERIE)))AND @ES_ELECTRONICO=0
    		BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Ya existe un documento con la misma serie y numero de este proveedor',@SYS_FILAS_AFECTADAS=0
				GOTO FINA 
			END

			IF EXISTS(SELECT 1 FROM COM_DOCUMENTO 
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND ANIO_PERIODO=@ANIO_PERIODO
				  AND MES_PERIODO=@MES_PERIODO
				  AND CORR_DOCUMENTO=@CORR_DOCUMENTO
				  AND ISNULL(@CODIGO_GENERACION,'')='' 
				  AND ISNULL(@NUMERO_DOCUMENTO,'')=''
				  )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Debe asignar un numero de documento o codigo de generación',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			IF EXISTS(SELECT 1 FROM COM_DOCUMENTO 
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND CODIGO_GENERACION=ISNULL(@CODIGO_GENERACION,'')
				  AND ISNULL(@NUMERO_DOCUMENTO,'')=''
				  )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Ya existe un documento con este codigo de generación',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
						
		END
		
		IF @TIPO_ACTUALIZA IN (3)
		BEGIN
				 IF EXISTS( SELECT 1 FROM COM_DOCUMENTO A
						  INNER JOIN SCR_DETALLE_COMPROBANTE B ON A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO
						  WHERE CORR_EMPRESA=@CORR_EMPRESA
						  AND A.ANIO_PERIODO=@ANIO_PERIODO
						  AND A.MES_PERIODO=@MES_PERIODO
						  AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO) --SE VERIFICA QUE SI EXISTE COMPROBANTE DE RETENCION NO PUEDA ELIMINAR EL DOCUMENTO.
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Existe un comprobante de retención vinculado a este documento, no se puede eliminar',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END

		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			SELECT @CORR_DOCUMENTO=ISNULL(MAX(CORR_DOCUMENTO),0)+1
			,@ESTADO_DOCUMENTO='DI', @ESTA_CONTABILIZADO=0
			FROM COM_DOCUMENTO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO

			INSERT INTO COM_DOCUMENTO
			(CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,CORR_TIPO_DOC,CORR_DOCUMENTO,NUMERO_DOCUMENTO,FECHA_DOCUMENTO,FECHA_VENCIMIENTO,CORR_TIENDA,CORR_PROVEEDOR,NOMBRE_PROVEEDOR,DESCRIPCION_PARTIDA,CORR_CONDICION_PAGO,DIAS_CREDITO,ESTADO_DOCUMENTO,ESTA_CONTABILIZADO,TOTAL_DOCUMENTO,TOTAL_NETO,SALDO_DOCUMENTO,CORR_TIPO_GASTO,CANTIDAD,USUARIO_CREA,FECHA_CREA,ESTACION_CREA,USUARIO_ACTU,FECHA_ACTU,ESTACION_ACTU,SERIE
			,CORR_MONEDA,FACTOR_CAMBIO,OPERADOR,NUMERO_UNICO,CODIGO_GENERACION,NUMERO_CONTROL,SELLO_RECEPCION,ANIO_PERIODO_IVA,MES_PERIODO_IVA)
			VALUES
			(@CORR_EMPRESA,@ANIO_PERIODO,@MES_PERIODO,@CORR_TIPO_DOC,@CORR_DOCUMENTO,CASE WHEN @NUMERO_DOCUMENTO='' THEN @CODIGO_GENERACION WHEN @NUMERO_DOCUMENTO IS NULL THEN @CODIGO_GENERACION ELSE @NUMERO_DOCUMENTO END,@FECHA_DOCUMENTO,@FECHA_VENCIMIENTO,@CORR_TIENDA,@CORR_PROVEEDOR,@NOMBRE_PROVEEDOR,@DESCRIPCION_PARTIDA,@CORR_CONDICION_PAGO,@DIAS_CREDITO,@ESTADO_DOCUMENTO,@ESTA_CONTABILIZADO,@TOTAL_DOCUMENTO,@TOTAL_NETO,@SALDO_DOCUMENTO,@CORR_TIPO_GASTO,@CANTIDAD,@USUARIO_CREA,@FECHA_CREA,@ESTACION_CREA,@USUARIO_ACTU,@FECHA_ACTU,@ESTACION_ACTU,@SERIE
			,@CORR_MONEDA,@FACTOR_CAMBIO,@OPERADOR,@NUMERO_UNICO,@CODIGO_GENERACION,@NUMERO_CONTROL,@SELLO_RECEPCION,@ANIO_PERIODO_IVA,@MES_PERIODO_IVA)
			
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE COM_DOCUMENTO SET
			CORR_TIPO_DOC=@CORR_TIPO_DOC,
			NUMERO_DOCUMENTO=@NUMERO_DOCUMENTO,
			FECHA_DOCUMENTO=@FECHA_DOCUMENTO,
			FECHA_VENCIMIENTO=@FECHA_VENCIMIENTO,
			CORR_TIENDA=@CORR_TIENDA,
			CORR_PROVEEDOR=@CORR_PROVEEDOR,
			NOMBRE_PROVEEDOR=@NOMBRE_PROVEEDOR,
			DESCRIPCION_PARTIDA=@DESCRIPCION_PARTIDA,
			CORR_CONDICION_PAGO=@CORR_CONDICION_PAGO,
			DIAS_CREDITO=@DIAS_CREDITO,
			ESTADO_DOCUMENTO=@ESTADO_DOCUMENTO,
			ESTA_CONTABILIZADO=@ESTA_CONTABILIZADO,
			TOTAL_DOCUMENTO=@TOTAL_DOCUMENTO,
			TOTAL_NETO=@TOTAL_NETO,
			SALDO_DOCUMENTO=@SALDO_DOCUMENTO,
			CORR_TIPO_GASTO=@CORR_TIPO_GASTO,
			CANTIDAD=@CANTIDAD,
			CORR_MONEDA=@CORR_MONEDA,
			FACTOR_CAMBIO=@FACTOR_CAMBIO,
			OPERADOR=@OPERADOR,
			USUARIO_ACTU=@USUARIO_ACTU,
			FECHA_ACTU=@FECHA_ACTU,
			ESTACION_ACTU=@ESTACION_ACTU,
			SERIE=@SERIE,
			NUMERO_UNICO=@NUMERO_UNICO,
			CODIGO_GENERACION=@CODIGO_GENERACION,
			NUMERO_CONTROL=@NUMERO_CONTROL,
			SELLO_RECEPCION=@SELLO_RECEPCION,
			ANIO_PERIODO_IVA=@ANIO_PERIODO_IVA,
			MES_PERIODO_IVA=@MES_PERIODO_IVA
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN

			DELETE A FROM [e-AdminFE].dbo.ADM_COM_JSON A
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.MES_PERIODO=@MES_PERIODO
			AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO

			DELETE FROM COM_DOCUMENTO_TOTAL 
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			
			DELETE FROM COM_DOCUMENTO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO

		END
		
		--Se genera el rubro GRAVADO segun el tipo de documento, con el monto del TOTAL_NETO
		IF @TIPO_ACTUALIZA IN (1,2) AND @GENERA_TOTALES=1
		BEGIN
			DECLARE @CORR_RUBRO_GRAVADO INT
			SELECT TOP (1) @CORR_RUBRO_GRAVADO=B.CORR_RUBRO
			FROM GEN_TIPO_DOCUMENTO_RUBRO A
			INNER JOIN GEN_RUBRO B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CORR_RUBRO=B.CORR_RUBRO 
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.CORR_TIPO_DOC=@CORR_TIPO_DOC 
			AND B.CLASE_RUBRO='GRA'
			
			IF NOT @CORR_RUBRO_GRAVADO IS NULL
			BEGIN
				IF EXISTS ( SELECT 1 FROM COM_DOCUMENTO_TOTAL 
							WHERE CORR_EMPRESA=@CORR_EMPRESA 
							AND ANIO_PERIODO=@ANIO_PERIODO 
							AND MES_PERIODO=@MES_PERIODO 
							AND CORR_DOCUMENTO=@CORR_DOCUMENTO
							AND CORR_RUBRO=@CORR_RUBRO_GRAVADO )
				BEGIN
					EXEC PRAL_MTTO_COM_DOCUMENTO_TOTAL 
							2, --Actualiza
							@CORR_EMPRESA, 
							@ANIO_PERIODO,
							@MES_PERIODO,
							@CORR_DOCUMENTO,
							@CORR_RUBRO_GRAVADO OUTPUT,
							@TOTAL_NETO,
							@SYS_LOGIN_USUARIO,
							@SYS_ESTACION,
							@SYS_FILAS_AFECTADAS OUTPUT,
							@SYS_NUMERO_ERROR OUTPUT,
							@SYS_MENSAJE_ERROR OUTPUT
				END ELSE
				BEGIN
					EXEC PRAL_MTTO_COM_DOCUMENTO_TOTAL 
							1, --Inserta
							@CORR_EMPRESA, 
							@ANIO_PERIODO,
							@MES_PERIODO,
							@CORR_DOCUMENTO,
							@CORR_RUBRO_GRAVADO OUTPUT,
							@TOTAL_NETO,
							@SYS_LOGIN_USUARIO,
							@SYS_ESTACION,
							@SYS_FILAS_AFECTADAS OUTPUT,
							@SYS_NUMERO_ERROR OUTPUT,
							@SYS_MENSAJE_ERROR OUTPUT
				END
			END
		END
		
		IF @TIPO_ACTUALIZA IN (1) --Pendiente, que hacer cuando se Actualize si recalcular todo o dejarlo como esta
		BEGIN
			EXEC PRAL_GENE_COM_DOCUMENTO_TOTAL_IMPUESTO
			@CORR_EMPRESA,
			@ANIO_PERIODO,
			@MES_PERIODO,
			@CORR_DOCUMENTO OUTPUT,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS output,
			@SYS_NUMERO_ERROR output,
			@SYS_MENSAJE_ERROR output						
		END
		
		IF @TIPO_ACTUALIZA<>3 AND NOT EXISTS(SELECT 1 FROM GEN_TIPO_DOCUMENTO A
											 WHERE A.CORR_EMPRESA=@CORR_EMPRESA
											 AND A.CORR_TIPO_DOC=@CORR_TIPO_DOC
											 AND A.CLASE_DOCUMENTO='CRT')
		BEGIN
			EXEC PRAL_GENE_COM_DOCUMENTO_TOTAL
				@CORR_EMPRESA,
				@ANIO_PERIODO,
				@MES_PERIODO,
				@CORR_DOCUMENTO OUTPUT,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@SYS_FILAS_AFECTADAS output,
				@SYS_NUMERO_ERROR output,
				@SYS_MENSAJE_ERROR output
		END
		

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END

GO