SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_DOCUMENTO_TOTAL]
(
	@TIPO_ACTUALIZA INT,
	@CORR_EMPRESA int,
	@ANIO_PERIODO int,
	@MES_PERIODO int,
	@CORR_DOCUMENTO int,
	@CORR_RUBRO int OUTPUT,
	@MONTO_RUBRO money,
	@SYS_LOGIN_USUARIO Varchar(30),
	@SYS_ESTACION Varchar(50),
	@SYS_FILAS_AFECTADAS int output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
BEGIN
	
	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		DECLARE @ESTADO_DOCUMENTO VARCHAR(2), @MONTO DECIMAL(12,2), @CANTIDAD DECIMAL(12,2)
		
		IF @TIPO_ACTUALIZA IN (1,2,3)
		BEGIN
			SELECT @ESTADO_DOCUMENTO=ESTADO_DOCUMENTO 
			FROM COM_DOCUMENTO 
			WHERE CORR_EMPRESA=@CORR_EMPRESA 
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			IF (ISNULL(@ESTADO_DOCUMENTO,'')='')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Este doc. compra no existe.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END			
			IF (@ESTADO_DOCUMENTO<>'DI')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30000,@SYS_MENSAJE_ERROR='Este doc. compra ya está aplicado o anulado, no permite modificarse.',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END
		END
		
		IF @TIPO_ACTUALIZA=1 --Adicionar
		BEGIN
			
			INSERT INTO COM_DOCUMENTO_TOTAL
			(CORR_EMPRESA,ANIO_PERIODO,MES_PERIODO,CORR_DOCUMENTO,CORR_RUBRO,MONTO_RUBRO)
			VALUES
			(@CORR_EMPRESA,@ANIO_PERIODO,@MES_PERIODO,@CORR_DOCUMENTO,@CORR_RUBRO,@MONTO_RUBRO)
		END ELSE
		IF @TIPO_ACTUALIZA=2 --Actualizar
		BEGIN
			UPDATE COM_DOCUMENTO_TOTAL SET
			MONTO_RUBRO=@MONTO_RUBRO
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			AND CORR_RUBRO=@CORR_RUBRO
		END ELSE
		IF @TIPO_ACTUALIZA=3 --Eliminar
		BEGIN
			DELETE FROM COM_DOCUMENTO_TOTAL
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			AND CORR_RUBRO=@CORR_RUBRO
		END
		
		DECLARE @ES_IMPUESTO BIT 
		SELECT @ES_IMPUESTO=ES_IMPUESTO
		FROM V_COM_DOCUMENTO_TOTAL 
		WHERE CORR_EMPRESA=@CORR_EMPRESA 
		AND ANIO_PERIODO=@ANIO_PERIODO 
		AND MES_PERIODO=@MES_PERIODO 
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO 
		AND CORR_RUBRO=@CORR_RUBRO 
		
		--Si no es impuesto hay que calcular
		IF @ES_IMPUESTO=0
		BEGIN
			EXEC PRAL_GENE_COM_DOCUMENTO_TOTAL_IMPUESTO
				@CORR_EMPRESA,
				@ANIO_PERIODO,
				@MES_PERIODO,
				@CORR_DOCUMENTO OUTPUT,
				@SYS_LOGIN_USUARIO,
				@SYS_ESTACION,
				@SYS_FILAS_AFECTADAS output,
				@SYS_NUMERO_ERROR output,
				@SYS_MENSAJE_ERROR output
		END	
		
		EXEC PRAL_GENE_COM_DOCUMENTO_TOTAL
			@CORR_EMPRESA,
			@ANIO_PERIODO,
			@MES_PERIODO,
			@CORR_DOCUMENTO OUTPUT,
			@SYS_LOGIN_USUARIO,
			@SYS_ESTACION,
			@SYS_FILAS_AFECTADAS output,
			@SYS_NUMERO_ERROR output,
			@SYS_MENSAJE_ERROR output
			
		 
		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT
	
	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DateTime

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO