SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Alex Hernandez>
-- Create date: <15/07/2025>
-- Description:	<Generación de CR>
-- =============================================
CREATE PROCEDURE [dbo].[PRAL_GENE_COM_DOCUMENTO_CR]
@CORR_EMPRESA	INT,
@ANIO_PERIODO INT,
@MES_PERIODO INT,
@CORR_DOCUMENTO INT OUTPUT ,
@ES_NACIONAL BIT,
@ES_EXTRANJERO BIT,
@DESCRIPCION_DOCUMENTO VARCHAR(700),
@SYS_LOGIN_USUARIO VARCHAR(30),
@SYS_ESTACION VARCHAR(50),
@SYS_FILAS_AFECTADAS INT OUTPUT,
@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
AS
BEGIN
   SET NOCOUNT ON;
DECLARE
	@SCBSERIE VARCHAR(50),
	@SCBNUMERO [BIGINT] ,
	@SCBTIPDOCAFE VARCHAR(10),
	@SCBCUN NVARCHAR(20),
	@SCBTIP NVARCHAR(1),
	@SCBNAM [VARCHAR](100)= NULL,
	@SCBDIRECCION [VARCHAR](200)= NULL,
	@SCBDEPTO [VARCHAR](150)= '', --
	@SCBNIT [VARCHAR](20)= NULL,
	@SCBNCR [VARCHAR](20)= NULL,
	@SCBGIRO [VARCHAR](150)= NULL, 
	@SCBFECHA [DATETIME] = GETDATE(),
	@SCBOBSERVACION [VARCHAR](150),
	@SCBSUBTOTAL [NUMERIC](18, 2),
	@SCBIVARET [NUMERIC](18, 2),
	@SCBTOTAL [NUMERIC](18, 2),
	@TOTALNETO NUMERIC (18,2),
	@SCBESTADO [VARCHAR](50)='ENVIADO', --
	@SCBEXTRANJERO BIT,
	@SCBTIPOREC VARCHAR(50), --
	@USUARIO [NVARCHAR](50), 
	@ENVIADO BIT=1,
	@CORR_PROVEEDOR VARCHAR(20),
	@EXISTE_ACTIVIDAD_ECONO INT,
	@CORR_ACTIVIDAD_ECONO VARCHAR(20),
	@CORR_DEP VARCHAR(50),
	@CORR_MUN VARCHAR(50),
	@CORREO VARCHAR(100),
	@NIT VARCHAR(25),
	@NRC VARCHAR(20),
	@CORR_TIPO_DOC INT, 
	@TIPO_DOC_AFECTA VARCHAR(50),
	@SCDBDESCRIPCION [VARCHAR](500),
	@SCDBFECHAFACT DATETIME,
	@SCDBCANTIDAD [NUMERIC](18, 6)=1,
	@SCDBPRECUNIT [NUMERIC](18, 4),
	@SCDBPRECUNITCIVA [NUMERIC](18, 4),
	@SCDBPRECLINEA [NUMERIC](18, 2),
	@SCDBIDLINEA [BIGINT],
	@CORR_TIPO_ITEM INT=1, --
	@SCDBDOCAFECTADO VARCHAR(50)

		SET @SCBTIPOREC = CASE WHEN @ES_EXTRANJERO=1 THEN 'EXTRANJERO' ELSE 'PROVEEDORES' END

		SELECT 
		@SCDBDOCAFECTADO=NUMERO_DOCUMENTO, 
		@TOTALNETO= TOTAL_NETO, 
		@CORR_PROVEEDOR=CORR_PROVEEDOR,
		@CORR_DOCUMENTO=CORR_DOCUMENTO,
		@CORR_TIPO_DOC=A.CORR_TIPO_DOC,
		@TIPO_DOC_AFECTA= CASE WHEN B.CLASE_DOCUMENTO='FAC' THEN 'FA' ELSE B.CLASE_DOCUMENTO END
		FROM SUEES.dbo.COM_DOCUMENTO A 
		INNER JOIN GEN_TIPO_DOCUMENTO B ON A.CORR_TIPO_DOC=B.CORR_TIPO_DOC
		WHERE ANIO_PERIODO=@ANIO_PERIODO AND MES_PERIODO=@MES_PERIODO AND CORR_DOCUMENTO=@CORR_DOCUMENTO


		SELECT @USUARIO= ISNULL(USRLOG,'admin') FROM INVC_USUARIOS WHERE USRUID=@SYS_LOGIN_USUARIO

		SELECT @EXISTE_ACTIVIDAD_ECONO= CASE WHEN CORR_ACTIVIDAD_ECONOMICA='' THEN '' WHEN CORR_ACTIVIDAD_ECONOMICA='0' THEN '' ELSE 1 END, 
		@CORR_ACTIVIDAD_ECONO=CORR_ACTIVIDAD_ECONOMICA,
		@CORR_DEP=ISNULL(B.CODIGO_DEPTO,''),
		@CORR_MUN=ISNULL(B.CODIGO_MUNICIPIO,''), 
		@CORREO=ISNULL(CORREO_ELECTRONICO_1,''), 
		@NIT=ISNULL(NUMERO_NIT,''), 
		@NRC= CASE WHEN ISNULL(B.CODIGO_DEPTO,'')='00' THEN '' ELSE ISNULL(NUMERO_NRC,'') END,
		@SCBDEPTO=B.CODIGO_DEPTO
		FROM COM_DOCUMENTO A 
		INNER JOIN SUEES.dbo.COM_PROVEEDOR B ON B.CORR_PROVEEDOR = A.CORR_PROVEEDOR 
		WHERE ANIO_PERIODO=@ANIO_PERIODO AND MES_PERIODO=@MES_PERIODO AND CORR_DOCUMENTO=@CORR_DOCUMENTO

		BEGIN TRY  
			SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0
			

			IF (@TOTALNETO<100)
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='NO SE PUEDE GENERAR UN COMPROBANTE DE RETENCION SI EL MONTO GRAVADO ES MENOR QUE $100',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END 

			IF  EXISTS (SELECT 1 FROM SUEES.dbo.COM_DOCUMENTO A
						INNER JOIN SUEES.dbo.SCR_DETALLE_COMPROBANTE B ON A.ANIO_PERIODO=B.ANIO_PERIODO AND A.MES_PERIODO=B.MES_PERIODO AND A.CORR_DOCUMENTO=B.CORR_DOCUMENTO
						INNER JOIN SUEES.dbo.SCR_COMPROBANTE C ON B.SCDBSERIE=C.SCBSERIE AND B.SCDBNUMERO=C.SCBNUMERO
						WHERE  A.MES_PERIODO=@MES_PERIODO AND A.ANIO_PERIODO=@ANIO_PERIODO AND A.CORR_DOCUMENTO = @CORR_DOCUMENTO AND C.SCBESTADO !='ANULADO')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='ESTE DOCUMENTO YA POSEE UN COMPROBANTE DE RETENCION GENERADO',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			IF   (@CORR_TIPO_DOC IN (4,5,6))
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='NO SE PUEDE GENERAR UN COMPROBANTE DE RETENCION CON ESTE TIPO DE DOCUMENTO',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			IF  NOT EXISTS  (SELECT 1 FROM COM_DOCUMENTO A 
						     INNER JOIN SUEES.dbo.COM_PROVEEDOR B ON B.CORR_PROVEEDOR = A.CORR_PROVEEDOR 
							 WHERE A.MES_PERIODO=@MES_PERIODO AND A.ANIO_PERIODO=@ANIO_PERIODO AND A.CORR_DOCUMENTO = @CORR_DOCUMENTO )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='ES NECESARIO ACTUALIZAR LOS DATOS DEL PROVEEDOR PARA PODER GENERAR ESTE COMPROBANTE DE RETENCION',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END


			IF (ISNULL(@CORR_DEP,'')='')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='ES NECESARIO ACTUALIZAR EL DEPARTAMENTO DEL PROVEEDOR PARA PODER GENERAR ESTE COMPROBANTE DE RETENCION',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END


			IF (@CORR_MUN='')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='ES NECESARIO ACTUALIZAR EL MUNICIPIO DEL PROVEEDOR PARA PODER GENERAR ESTE COMPROBANTE DE RETENCION',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			IF (@CORREO='')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='ES NECESARIO ACTUALIZAR EL CORREO DEL PROVEEDOR PARA PODER GENERAR ESTE COMPROBANTE DE RETENCION',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			IF (@NIT='' )
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='ES NECESARIO ACTUALIZAR EL NIT DEL PROVEEDOR PARA PODER GENERAR ESTE COMPROBANTE DE RETENCION',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			IF (@NRC='' AND @CORR_DEP!='00')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='ES NECESARIO ACTUALIZAR EL NRC DEL PROVEEDOR PARA PODER GENERAR ESTE COMPROBANTE DE RETENCION',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			IF (@EXISTE_ACTIVIDAD_ECONO=0 AND @CORR_DEP!='00')
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='ES NECESARIO ACTUALIZAR LA ACTIVIDAD ECONOMICA DEL PROVEEDOR PARA PODER GENERAR ESTE COMPROBANTE DE RETENCION',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			IF NOT EXISTS( SELECT 1 FROM CLASS_UEES.dbo.CODIGOS WHERE CODREL='ACT_EMP   ' AND CODCOD LIKE '%H' AND CODCOD=@CORR_ACTIVIDAD_ECONO)
			BEGIN
				SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='ES NECESARIO ACTUALIZAR LA ACTIVIDAD ECONOMICA DEL PROVEEDOR PARA PODER GENERAR ESTE COMPROBANTE DE RETENCION',@SYS_FILAS_AFECTADAS=0
				GOTO FINA
			END

			BEGIN TRANSACTION  PRAL_GENE_COM_DOCUMENTO_CR
	
					UPDATE SUEES.dbo.SJE_CORRELATIVOS
					WITH (ROWLOCK)
					SET SJCCORRELATIVO = ISNULL(SJCCORRELATIVO, 0) + 1
					WHERE SJCTIPODOC = 2

					SELECT @SCBNUMERO = SJCCORRELATIVO , @SCBSERIE=SJCSERIE, @SCBTIPDOCAFE=@TIPO_DOC_AFECTA
					FROM SUEES.dbo.SJE_CORRELATIVOS ROWLOCK
					WHERE SJCTIPODOC = 2
					

					--SELECT @CORR_PROVEEDOR=CORR_PROVEEDOR,
					--@SCBOBSERVACION=@DESCRIPCION_DOCUMENTO, 
					--@SCBSUBTOTAL=TOTAL_DOCUMENTO,@SCBIVARET=(TOTAL_DOCUMENTO*0.1),
					--@SCBTOTAL=SALDO_DOCUMENTO, 
					--@ANIO_PERIODO=ANIO_PERIODO, 
					--@MES_PERIODO=MES_PERIODO,
					--@SCDBDOCAFECTADO=NUMERO_DOCUMENTO,
					--@SCDBFECHAFACT=FECHA_DOCUMENTO
					--FROM SUEES.dbo.COM_DOCUMENTO WHERE CORR_DOCUMENTO=RIGHT(@CORR_DOCUMENTO, 4) AND ANIO_PERIODO=@ANIO_PERIODO AND MES_PERIODO=@MES_PERIODO
					SELECT @CORR_PROVEEDOR=A.CORR_PROVEEDOR,
					@SCBOBSERVACION=@DESCRIPCION_DOCUMENTO, 
					@SCBSUBTOTAL=CASE WHEN C.CLASE_DOCUMENTO = 'FAC' AND B.IMPUESTO_INCLUIDO=1 THEN (B.MONTO_GRAVADO - MONTO_IVA) ELSE (B.MONTO_GRAVADO) END,
					@SCBIVARET=CASE WHEN C.CLASE_DOCUMENTO = 'FAC' AND B.IMPUESTO_INCLUIDO=1 THEN ((B.MONTO_GRAVADO - MONTO_IVA) * 0.01) ELSE (B.MONTO_GRAVADO * 0.01) END,
					@SCBTOTAL=CASE WHEN C.CLASE_DOCUMENTO = 'FAC' AND B.IMPUESTO_INCLUIDO=1 THEN (B.MONTO_GRAVADO - MONTO_IVA) ELSE (B.MONTO_GRAVADO) END,
					@ANIO_PERIODO=A.ANIO_PERIODO, 
					@MES_PERIODO=A.MES_PERIODO,
					@SCDBDOCAFECTADO=A.NUMERO_DOCUMENTO,
					@SCDBFECHAFACT=A.FECHA_DOCUMENTO,
					@SCDBPRECLINEA=CASE WHEN C.CLASE_DOCUMENTO = 'FAC' AND B.IMPUESTO_INCLUIDO=1 THEN (B.MONTO_GRAVADO - MONTO_IVA) ELSE (B.MONTO_GRAVADO) END,
					@SCDBPRECUNIT=CASE WHEN C.CLASE_DOCUMENTO = 'FAC' AND B.IMPUESTO_INCLUIDO=1 THEN (B.MONTO_GRAVADO - MONTO_IVA)  ELSE (B.MONTO_GRAVADO) END,
					@SCDBPRECUNITCIVA=CASE WHEN C.CLASE_DOCUMENTO = 'FAC' AND B.IMPUESTO_INCLUIDO=1 THEN (B.MONTO_GRAVADO) ELSE (B.MONTO_GRAVADO + MONTO_IVA) END
					FROM SUEES.dbo.COM_DOCUMENTO A 
					INNER JOIN dbo.V_COM_DOCUMENTO_TOTAL_RESUMEN_CONSOLIDADO B ON B.CORR_EMPRESA = A.CORR_EMPRESA AND B.ANIO_PERIODO = A.ANIO_PERIODO AND B.MES_PERIODO = A.MES_PERIODO AND B.CORR_DOCUMENTO = A.CORR_DOCUMENTO
					INNER JOIN dbo.GEN_TIPO_DOCUMENTO C ON A.CORR_EMPRESA=C.CORR_EMPRESA AND A.CORR_TIPO_DOC=C.CORR_TIPO_DOC
					WHERE A.CORR_DOCUMENTO=@CORR_DOCUMENTO
					AND A.ANIO_PERIODO=@ANIO_PERIODO 
					AND A.MES_PERIODO=@MES_PERIODO

					SELECT @SCBCUN=CODIGO_PROVEEDOR, 
					@SCBTIP=TIPO_PERSONERIA, 
					@SCBNAM=NOMBRE_PROVEEDOR, 
					@SCBDIRECCION=DIRECCION_PROVEEDOR, 
					@SCBNIT=NUMERO_NIT,
					@SCBNCR=CASE WHEN ISNULL(A.CODIGO_DEPTO,'')='00' THEN '' ELSE ISNULL(NUMERO_NRC,'') END,
					@SCBEXTRANJERO= @ES_EXTRANJERO, 
					@SCBGIRO=ISNULL(B.NOMBRE_ACTIVIDAD_ECONOMICA,'')
					FROM SUEES.DBO.COM_PROVEEDOR A 
					LEFT JOIN SUEES.dbo.V_COM_ACTIVIDAD_ECONOMICA B ON A.CORR_ACTIVIDAD_ECONOMICA=B.CORR_ACTIVIDAD_ECONOMICA COLLATE DATABASE_DEFAULT
					WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR

					--SET @SCDBPRECUNIT=@SCBSUBTOTAL
					--SET @SCDBPRECUNITCIVA= (@SCBSUBTOTAL*0.13)+@SCBSUBTOTAL
					--SET @SCDBPRECLINEA=@SCBSUBTOTAL

			
					 INSERT INTO SUEES.dbo.SCR_COMPROBANTE
				   ([SCBSERIE]
				   ,[SCBNUMERO]
				   ,SCBTIPDOCAFE
    			   ,SCBCUN
				   ,SCBTIP
				   ,[SCBNAM]
				   ,[SCBDIRECCION]
				   ,SCBDEPTO
				   ,[SCBNIT]
				   ,[SCBNCR]
				   ,[SCBGIRO]
				   ,[SCBFECHA]
				   ,[SCBOBSERVACION]
				   ,[SCBSUBTOTAL]
				   ,[SCBIVARET]
				   ,[SCBTOTAL]
				   ,[SCBESTADO]
				   ,SCBEXTRANJERO
				   ,SCBTIPOREC
				   ,ENVIADO
				   ,[USUARIO_CREA]
				   ,[FECHA_CREA]
				   ,FECHENVIOFE
				   ,USUARIO_ENVIA)
				   VALUES
				   (@SCBSERIE
				   ,@SCBNUMERO
				   ,@SCBTIPDOCAFE
				   ,@SCBCUN
  				   ,@SCBTIP
				   ,@SCBNAM
				   ,@SCBDIRECCION
				   ,@SCBDEPTO
				   ,@SCBNIT
				   ,@SCBNCR
				   ,@SCBGIRO
				   ,@SCBFECHA
				   ,@SCBOBSERVACION
				   ,@SCBSUBTOTAL
				   ,@SCBIVARET
				   ,@SCBTOTAL
				   ,'INGRESADO'
				   ,@SCBEXTRANJERO
				   ,@SCBTIPOREC
				   ,@ENVIADO
				   ,@USUARIO
				   ,@SCBFECHA
				   ,@SCBFECHA
				   ,@USUARIO

				   )      

				SET @SCDBPRECLINEA=ROUND(1*@SCDBPRECUNIT,2)
				  INSERT INTO SUEES.dbo.SCR_DETALLE_COMPROBANTE
						([SCDBSERIE]
						,[SCDBNUMERO]
						,[SCDBDESCRIPCION]
						,[SCDBFECHAFACT]
						,SCDBCANTIDAD
						,[SCDBPRECUNIT]
						,[SCDBPRECUNITCIVA]
						,[SCDBPRECLINEA]
						,CORR_TIPO_ITEM 
						,SCDBDOCAFECTADO
						,ANIO_PERIODO
						,MES_PERIODO
						,CORR_DOCUMENTO
						,USUARIO_CREA
						,FECHA_CREA
						)
				 VALUES
					   (@SCBSERIE,
						@SCBNUMERO, 
						@SCBOBSERVACION,
						@SCDBFECHAFACT,
						@SCDBCANTIDAD,
						@SCDBPRECUNIT,
						@SCDBPRECUNITCIVA,
						@SCDBPRECLINEA,
						@CORR_TIPO_ITEM,
						@SCDBDOCAFECTADO,
						@ANIO_PERIODO,
						@MES_PERIODO,
						@CORR_DOCUMENTO,
						@USUARIO,
						GETDATE()
						) 				
					
							
			COMMIT TRANSACTION PRAL_GENE_COM_DOCUMENTO_CR

			----------------------INICIO CALCULOS------------------------------------------------------------
			--DECLARE @TOTALLINEA AS NUMERIC(18,2)
	        
	  --      DECLARE @SJPCRIVARETPROV AS FLOAT
   --         DECLARE @SJPCRIVARETDIETA AS FLOAT
   --         DECLARE @SJPCRIVARETNODOM AS FLOAT
            
   --         --- PARAMETROS 
   --         SELECT @SJPCRIVARETPROV =[SJPCRIVARETPROV]/100,
   --                @SJPCRIVARETDIETA=[SJPCRIVARETDIETA]/100,
   --                @SJPCRIVARETNODOM=[SJPCRIVARETNODOM]/100
   --         FROM [SJE_PARAMETROS]
            
            
   --         --- LIMPIAR VARIABLES ---
   --         SELECT 	@SCBSUBTOTAL = 0.00,
	  --              @SCBIVARET = 0.00, 
	  --              @SCBTOTAL = 0.00
   
   --         --- CALCULA SUBTOTAL
   --        	SELECT @SCBSUBTOTAL = SUM(SCDBPRECLINEA) FROM SCR_DETALLE_COMPROBANTE
   --         WHERE SCDBSERIE = @SCBSERIE AND SCDBNUMERO = @SCBNUMERO GROUP BY SCDBSERIE,SCDBNUMERO

	        
	  --     IF @SCBTIPOREC='PROVEEDORES' BEGIN
   --           SELECT @SCBIVARET = ROUND(@SCBSUBTOTAL*@SJPCRIVARETPROV,2)	                      
	  --      END 
	  --      ELSE IF @SCBTIPOREC='DIETA' BEGIN
   --                 SELECT @SCBIVARET = ROUND(@SCBSUBTOTAL*@SJPCRIVARETDIETA,2)	                      
	  --      END 
	  --      ELSE IF @SCBTIPOREC='EXTRANJERO' BEGIN
   --                 SELECT @SCBIVARET = ROUND(@SCBSUBTOTAL*@SJPCRIVARETNODOM,2)	                      
	  --      END 
	  --      SET @SCBTOTAL = @SCBSUBTOTAL 
	        
	        
	
   --         UPDATE [SCR_COMPROBANTE]
   --         SET SCBTIPDOCAFE = @SCBTIPDOCAFE,
   --             [SCBOBSERVACION] = @SCBOBSERVACION,
 	 --           SCBNAM = @SCBNAM,
 	 --           SCBDIRECCION = @SCBDIRECCION,
 	 --           SCBDEPTO = @SCBDEPTO,
	  --          SCBNIT = @SCBNIT,
	  --          SCBNCR = @SCBNCR,
	  --          SCBGIRO = @SCBGIRO,
   --             [SCBSUBTOTAL] = @SCBSUBTOTAL,
   --             [SCBIVARET] = @SCBIVARET,
   --             [SCBTOTAL] = @SCBTOTAL,
   --             SCBEXTRANJERO = @SCBEXTRANJERO,
   --             SCBTIPOREC = @SCBTIPOREC,
   --             [USUARIO_ACTUALIZA] = @USUARIO,
   --             [FECHA_ACTUALIZA] = GETDATE()
   --             WHERE SCBSERIE = @SCBSERIE AND SCBNUMERO = @SCBNUMERO
				-------------------------------------------------------FIN CALCULOS------------------------------------------------------

			EXEC [e-AdminFE].dbo.PRAL_GENE_COM_DOCUMENTO_COMPRO_RETE_INDIV 8,1,1,@SCBSERIE,@SCBNUMERO		
		END TRY

		BEGIN CATCH
			ROLLBACK TRANSACTION PRAL_GENE_COM_DOCUMENTO_CR;
			DECLARE @ErrorMsg NVARCHAR(4000) = ERROR_MESSAGE();
			RAISERROR(@ErrorMsg, 16, 1);
	    END CATCH
	FINA:
END
	
	--select * from SUEES.dbo.SCR_COMPROBANTE where SCBNUMERO in (6753,6754)
	--SELECT * FROM SUEES.dbo.SJE_CORRELATIVOS

GO