SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_CALC_COM_PORC_RETE_PERC] ( 
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@MES_PERIODO INT,
	@CORR_DOCUMENTO INT,
	@PORC_RETENCION DECIMAL(12,2) = 0 OUTPUT,
	@PORC_PERCEPCION DECIMAL(12,2) = 0 OUTPUT,
	@TOTAL_RETENCION DECIMAL(14,2) = 0 OUTPUT,
	@TOTAL_PERCEPCION DECIMAL(14,2) = 0 OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON
	
	DECLARE  @CORR_TIPO_DOC INT
			, @TOTAL_MINIMO_APLICA_RETENCION DECIMAL(14,2)=500
			, @TOTAL_VENTA DECIMAL(14,2)
			, @TAMANO_VENDEDOR VARCHAR(2)=''
			, @CORR_PROVEEDOR INT
			, @TAMANO_CLIENTE VARCHAR(2)='P'
			, @CORR_RUBRO_PERCEPCION INT
			, @CORR_RUBRO_RETENCION INT
	
	SELECT @TOTAL_MINIMO_APLICA_RETENCION=TOTAL_MINIMO_APLICA_RETENCION
	FROM COM_PARAMETRO
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	
	SELECT @TOTAL_MINIMO_APLICA_RETENCION=ISNULL(NULL,100)
	
	SELECT @CORR_PROVEEDOR=CORR_PROVEEDOR, @CORR_TIPO_DOC=CORR_TIPO_DOC
	FROM V_COM_DOCUMENTO 
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	AND ANIO_PERIODO=@ANIO_PERIODO
	AND MES_PERIODO=@MES_PERIODO
	AND CORR_DOCUMENTO=@CORR_DOCUMENTO
	
	SELECT @TAMANO_CLIENTE=ISNULL(A.TAMANIO_EMPRESA,'') 
	FROM V_GEN_EMPRESA A
	WHERE A.CORR_EMPRESA=@CORR_EMPRESA 
	
	SELECT @TAMANO_VENDEDOR=ISNULL(SUBSTRING (A.NOMBRE_CLASE_TAMANIO, 1, 1),'') 
	FROM V_COM_PROVEEDOR A
	WHERE A.CORR_PROVEEDOR=@CORR_PROVEEDOR 
	
	--TAMANOS IGUALES
	IF (@TAMANO_VENDEDOR IN (@TAMANO_CLIENTE))
	BEGIN
		--NO HAY RETENCION NI PERCEPCION
		SELECT @PORC_RETENCION=0, @PORC_PERCEPCION=0, @TOTAL_RETENCION=0, @TOTAL_PERCEPCION=0
		GOTO FINA
	END ELSE	
	
	--VENDEDOR GRANDE, CLIENTE PEQUEÑO
	IF (@TAMANO_VENDEDOR IN ('G') AND @TAMANO_CLIENTE IN ('M','P'))
	BEGIN
		--HAY PERCEPCION
		SELECT @CORR_RUBRO_PERCEPCION=CORR_RUBRO 
		FROM V_GEN_TIPO_DOCUMENTO_RUBRO 
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_TIPO_DOC=@CORR_TIPO_DOC 
		AND CLASE_RUBRO='PER'
		
		IF (@CORR_RUBRO_PERCEPCION IS NULL)
		BEGIN
			--NO ESTA CONFIGURADO EL IMPUESTO PERCEPCION EN ESTE TIPO DOC.
			SELECT @PORC_RETENCION=0, @PORC_PERCEPCION=0, @TOTAL_RETENCION=0, @TOTAL_PERCEPCION=0
			GOTO FINA
		END		
		
		--TOTAL DE LA VENTA DE LOS RUBROS GRAVADOS QUE APLIQUEN AL IMPUESTO PERCEPCION
		SELECT @TOTAL_VENTA=SUM(ISNULL(A.MONTO_RUBRO,0))
		FROM V_COM_DOCUMENTO_TOTAL A
		INNER JOIN V_GEN_RUBRO_IMPUESTO B
		ON A.CORR_EMPRESA=B.CORR_EMPRESA
		AND A.CORR_RUBRO=B.CORR_RUBRO 
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.MES_PERIODO=@MES_PERIODO
		AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO 
		AND A.CLASE_RUBRO='GRA'
		AND B.CORR_IMPUESTO=@CORR_RUBRO_PERCEPCION 
		
		IF (@TOTAL_VENTA>=@TOTAL_MINIMO_APLICA_RETENCION) 
		BEGIN
			SELECT @PORC_PERCEPCION=(A.POR_IMPUESTO/100.00), @TOTAL_PERCEPCION=@TOTAL_VENTA*(A.POR_IMPUESTO/100.00)
			FROM V_GEN_RUBRO A
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.CORR_RUBRO=@CORR_RUBRO_PERCEPCION
		END ELSE
		BEGIN
			SELECT @PORC_RETENCION=0, @PORC_PERCEPCION=0, @TOTAL_RETENCION=0, @TOTAL_PERCEPCION=0
			GOTO FINA
		END				
		SELECT @PORC_RETENCION=0, @PORC_PERCEPCION=ISNULL(@PORC_PERCEPCION,1)
	END ELSE	
	--VENDEDOR PEQUEÑO, CLIENTE GRANDE
	IF (@TAMANO_VENDEDOR IN ('M','P') AND @TAMANO_CLIENTE IN ('G')) 
	BEGIN
		--HAY RETENCION
		SELECT @CORR_RUBRO_RETENCION=CORR_RUBRO 
		FROM V_GEN_TIPO_DOCUMENTO_RUBRO 
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_TIPO_DOC=@CORR_TIPO_DOC 
		AND CLASE_RUBRO='RET'	
		IF (@CORR_RUBRO_RETENCION IS NULL)
		BEGIN
			--NO ESTA CONFIGURADO EL IMPUESTO PERCEPCION EN ESTE TIPO DOC.
			SELECT @PORC_RETENCION=0, @PORC_PERCEPCION=0, @TOTAL_RETENCION=0, @TOTAL_PERCEPCION=0
			GOTO FINA
		END			
		--TOTAL DE LA VENTA DE LOS RUBROS GRAVADOS QUE APLIQUEN AL IMPUESTO PERCEPCION
		SELECT @TOTAL_VENTA=SUM(ISNULL(A.MONTO_RUBRO,0))
		FROM V_COM_DOCUMENTO_TOTAL A
		INNER JOIN V_GEN_RUBRO_IMPUESTO B
		ON A.CORR_EMPRESA=B.CORR_EMPRESA
		AND A.CORR_RUBRO=B.CORR_RUBRO 
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.MES_PERIODO=@MES_PERIODO
		AND A.CORR_DOCUMENTO=@CORR_DOCUMENTO 
		AND A.CLASE_RUBRO='GRA'
		AND B.CORR_IMPUESTO=@CORR_RUBRO_RETENCION 
		IF (@TOTAL_VENTA>=@TOTAL_MINIMO_APLICA_RETENCION) 
		BEGIN
			SELECT @PORC_RETENCION=A.POR_IMPUESTO, @TOTAL_RETENCION=@TOTAL_VENTA*(A.POR_IMPUESTO/100.00) 
			FROM V_GEN_RUBRO A
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.CORR_RUBRO=@CORR_RUBRO_RETENCION
		END ELSE
		BEGIN
			SELECT @PORC_RETENCION=0, @PORC_PERCEPCION=0, @TOTAL_RETENCION=0, @TOTAL_PERCEPCION=0
			GOTO FINA
		END		
	END ELSE
	BEGIN
		SELECT @PORC_RETENCION=0, @PORC_PERCEPCION=0, @TOTAL_RETENCION=0, @TOTAL_PERCEPCION=0
		GOTO FINA
	END
	
	FINA:
	SELECT    @PORC_RETENCION=ISNULL(@PORC_RETENCION,0)
			, @PORC_PERCEPCION=ISNULL(@PORC_PERCEPCION,0)
			, @TOTAL_RETENCION=ISNULL(@TOTAL_RETENCION,0)
			, @TOTAL_PERCEPCION=ISNULL(@TOTAL_PERCEPCION,0)
	RETURN	
	
END
GO