SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
-- Stored Procedure para insertar historial
CREATE OR ALTER PROCEDURE [dbo].[PRAL_MTTO_SEG_USUARIO_LOGIN_HISTORIAL]
    @LOGIN_SISTEMA VARCHAR(30),
    @IP_ADDRESS VARCHAR(50) = NULL,
    @NAVEGADOR VARCHAR(255) = NULL,
    @CODIGO_SUITE VARCHAR(20) = NULL,
    @EXITOSO BIT = 1,
    @MENSAJE VARCHAR(500) = NULL,
    @CORR_LOGIN INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    
    INSERT INTO [dbo].[SEG_USUARIO_LOGIN_HISTORIAL] (
        [LOGIN_SISTEMA],
        [FECHA_LOGIN],
        [IP_ADDRESS],
        [NAVEGADOR],
        [CODIGO_SUITE],
        [EXITOSO],
        [MENSAJE]
    )
    VALUES (
        @LOGIN_SISTEMA,
        GETDATE(),
        @IP_ADDRESS,
        @NAVEGADOR,
        @CODIGO_SUITE,
        @EXITOSO,
        @MENSAJE
    );
    
    SET @CORR_LOGIN = SCOPE_IDENTITY();
END;
GO