SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_DATA_COM_DOCUMENTO_DETA_DOC]
(
	@TIPO_CONSULTA int,
	@CORR_EMPRESA int=NULL,
	@ANIO_PERIODO int=NULL,
	@MES_PERIODO int=NULL,
	@CORR_DOCUMENTO int=NULL,
	@ANIO_PERIODO_DOC int=NULL,
	@MES_PERIODO_DOC int=NULL,
	@CORR_DOCUMENTO_DOC int=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		SELECT * FROM V_COM_DOCUMENTO_DETA_DOC
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO
		AND ANIO_PERIODO_DOC=@ANIO_PERIODO_DOC
		AND MES_PERIODO_DOC=@MES_PERIODO_DOC
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		SELECT * FROM V_COM_DOCUMENTO_DETA_DOC
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO
		AND ANIO_PERIODO_DOC=@ANIO_PERIODO_DOC
		AND MES_PERIODO_DOC=@MES_PERIODO_DOC
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_COM_DOCUMENTO_DETA_DOC
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND MES_PERIODO=@MES_PERIODO
		AND CORR_DOCUMENTO=@CORR_DOCUMENTO
		AND ANIO_PERIODO_DOC=@ANIO_PERIODO_DOC
		AND MES_PERIODO_DOC=@MES_PERIODO_DOC
		AND CORR_DOCUMENTO_DOC=@CORR_DOCUMENTO_DOC
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT CORR_EMPRESA FROM V_COM_DOCUMENTO_DETA_DOC
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND MES_PERIODO=@MES_PERIODO
			AND CORR_DOCUMENTO=@CORR_DOCUMENTO
			AND ANIO_PERIODO_DOC=@ANIO_PERIODO_DOC
			AND MES_PERIODO_DOC=@MES_PERIODO_DOC
			AND CORR_DOCUMENTO_DOC=@CORR_DOCUMENTO_DOC
		END
	END

END
GO