SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_DATA_CON_AREA_FUNCIONAL]
(
	@TIPO_CONSULTA int,
	@CORR_EMPRESA int=NULL,
	@CORR_AREA_FUNCIONAL int=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		SELECT * FROM V_CON_AREA_FUNCIONAL
		WHERE CORR_EMPRESA=@CORR_EMPRESA
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		SELECT * FROM V_CON_AREA_FUNCIONAL
		WHERE CORR_EMPRESA=@CORR_EMPRESA
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_CON_AREA_FUNCIONAL
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND CORR_AREA_FUNCIONAL=@CORR_AREA_FUNCIONAL
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT CORR_EMPRESA FROM V_CON_AREA_FUNCIONAL
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CORR_AREA_FUNCIONAL=@CORR_AREA_FUNCIONAL
		END
	END

END
GO