SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PRAL_DATA_SEG_SUITE]
(
	@TIPO_CONSULTA int,
	@CODIGO_SUITE varchar(30)=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		SELECT * FROM V_SEG_SUITE
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		SELECT * FROM V_SEG_SUITE
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_SEG_SUITE
		WHERE CODIGO_SUITE=@CODIGO_SUITE
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT CODIGO_SUITE FROM V_SEG_SUITE
			WHERE CODIGO_SUITE=@CODIGO_SUITE
		END
	END
END
GO