SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_COLUMNAS_UPD]
@TABLE_NAME varchar(250)
AS

SELECT T1.* 
FROM INFORMATION_SCHEMA.COLUMNS T1
WHERE NOT EXISTS(SELECT 1 FROM V_LLAVES T2 WHERE T1.COLUMN_NAME=T2.COLUMN_NAME AND TABLE_NAME=@TABLE_NAME)
AND TABLE_NAME=@TABLE_NAME
AND T1.COLUMN_NAME NOT IN('USUARIO_CREA','FECHA_CREA','ESTACION_CREA')
ORDER BY T1.ORDINAL_POSITION
GO