SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_COM_PROVEEDOR]
(
	@TIPO_CONSULTA int,
	@CORR_PROVEEDOR varchar(20)=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		SELECT * FROM V_COM_PROVEEDOR
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		SELECT * FROM V_COM_PROVEEDOR
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_COM_PROVEEDOR
		WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT NOMBRE_PROVEEDOR 
			FROM V_COM_PROVEEDOR
			WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR
		END
	END

END
GO