SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_CUADRO_COMPARATIVO_SOLICITAR]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO INT,
	@CORR_CUADRO_COMPARATIVO int OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
	DECLARE @MONTO_TOTAL DECIMAL(18,2)
	DECLARE @ANIO_PERIODO_BITACORA INT=YEAR(GETDATE()),@CORR_BITACORA_TRANS INT=0, @FECHA_BITACORA DATE=GETDATE(), @LLAVE_TRANSACCION VARCHAR(250),@REFERENCIA_TRANSACCION VARCHAR(500), 
	@USUARIO_CREA_TRANS VARCHAR(50), @ESTACION_CREA_TRANS VARCHAR(50), @FECHA_CREA_TRANS DATETIME,@USUARIO_ACTU_TRANS VARCHAR(50), @ESTACION_ACTU_TRANS VARCHAR(50),
	@FECHA_ACTU_TRANS DATETIME, @USUARIO_CREA_BITACORA VARCHAR(50),@ESTACION_CREA_BITACORA VARCHAR(50), @FECHA_CREA_BITACORA DATETIME=GETDATE(),
	@CODIGO_OPCION VARCHAR(150)='COM_CUADRO_COMPARATIVO',@CLASE_BITACORA VARCHAR(3)='SO'

BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY

		IF EXISTS(SELECT 1 FROM COM_CUADRO_COMPARATIVO A 
				  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
				  AND A.ANIO_PERIODO=@ANIO_PERIODO
				  AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
				  AND A.ESTADO_CUADRO_COMPARATIVO<>'DI'
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='el cuadro comparativo debe estar en digitado. no se permite solicitar cuadro comparativo.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF NOT EXISTS(SELECT 1 FROM COM_CUADRO_COMPARATIVO_DETA A 
				  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
				  AND A.ANIO_PERIODO=@ANIO_PERIODO
				  AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='No existen item en el detalle del cuadro comparativo. no se permite solicitar cuadro comparativo.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF NOT EXISTS(SELECT 1 FROM COM_CUADRO_COMPARATIVO_DETA A 
					  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					  AND A.ANIO_PERIODO=@ANIO_PERIODO
					  AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
					  AND ISNULL(A.SELECCION,0)=1
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='No existen item seleccionados en el detalle del cuadro comparativo. no se permite solicitar cuadro comparativo.',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		------------------------------------------------------------------------
		-------------  BITACORA -------------- 
		SELECT @LLAVE_TRANSACCION='Año: '+CONVERT(VARCHAR,A.ANIO_PERIODO) COLLATE DATABASE_DEFAULT+' Correlativo No.: '+CONVERT(VARCHAR,A.CORR_CUADRO_COMPARATIVO) COLLATE DATABASE_DEFAULT,
				@REFERENCIA_TRANSACCION= ' Fecha: '+ CONVERT(VARCHAR,A.FECHA_CUADRO_COMPARATIVO) COLLATE DATABASE_DEFAULT
										+', Proveedor: '+A.NOMBRE_PROVEEDOR COLLATE DATABASE_DEFAULT
										+', Observaciones: '+A.OBSERVACIONES COLLATE DATABASE_DEFAULT,
				@USUARIO_CREA_TRANS=A.USUARIO_CREA, @ESTACION_CREA_TRANS=A.ESTACION_CREA, @FECHA_CREA_TRANS=A.FECHA_CREA,
				@USUARIO_ACTU_TRANS=A.USUARIO_ACTU, @ESTACION_ACTU_TRANS=A.ESTACION_ACTU, @FECHA_ACTU_TRANS=A.FECHA_ACTU
		FROM V_COM_CUADRO_COMPARATIVO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO

		SELECT @MONTO_TOTAL=SUM(B.MONTO_SUBTOTAL)
		FROM COM_CUADRO_COMPARATIVO_DETA A
		INNER JOIN COM_COTIZACION_DETA B ON A.CORR_EMPRESA = B.CORR_EMPRESA AND A.ANIO_PERIODO_COTIZACION = B.ANIO_PERIODO AND A.CORR_COTIZACION = B.CORR_COTIZACION AND A.CORR_COTIZACION_DETA = B.CORR_COTIZACION_DETA
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
		AND A.SELECCION=1
		GROUP BY A.CORR_CUADRO_COMPARATIVO

		DELETE FROM COM_CUADRO_COMPARATIVO_AUTORIZACIONES
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO

		INSERT INTO COM_CUADRO_COMPARATIVO_AUTORIZACIONES
		(
		    CORR_EMPRESA,
			ANIO_PERIODO,
			CORR_CUADRO_COMPARATIVO,
			LOGIN_SISTEMA,
			NOMBRE_CARGO,
			MONTO_INICIAL,
			MONTO_FINAL,
			CLASE_AUTORIZACION,
			ORDEN_REVISION,
			PERMITE_MODIFICAR,
			ESTADO_AUTORIZACION,
			FECHA_AUTORIZACION
		)
		SELECT @CORR_EMPRESA
		,@ANIO_PERIODO
		,@CORR_CUADRO_COMPARATIVO
		,A.LOGIN_SISTEMA
		,A.NOMBRE_CARGO
		,A.MONTO_INICIAL
		,A.MONTO_FINAL
		,A.CLASE_AUTORIZACION
		,A.ORDEN_REVISION
		,A.PERMITE_MODIFICAR
		,'SO'
		,NULL
		FROM COM_CUADRO_COMPARATIVO_CONFIG_AUTORIZACIONES A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND (@MONTO_TOTAL>=A.MONTO_INICIAL OR A.MONTO_INICIAL=0)
		AND (@MONTO_TOTAL<=A.MONTO_FINAL OR A.MONTO_FINAL=0)
		AND A.ESTADO_AUTORIZA='AC'

		IF @@ERROR=0
		BEGIN
			UPDATE COM_CUADRO_COMPARATIVO SET 
			ESTADO_CUADRO_COMPARATIVO='SO',
			USUARIO_CUADRO_COMPARATIVO=@SYS_LOGIN_USUARIO,
			USUARIO_ACTU=@SYS_LOGIN_USUARIO,
			ESTACION_ACTU=@SYS_ESTACION,
			FECHA_ACTU=GETDATE()
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO
			AND CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
		END

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

		--Executando el procedimiento de la bitacora
		EXECUTE PRAL_MTTO_COM_BITACORA
		1,--@TIPO_ACTUALIZA ,                              
		@CORR_EMPRESA ,
		@ANIO_PERIODO_BITACORA,
		@CORR_BITACORA_TRANS  OUTPUT,
		@FECHA_BITACORA ,                    
		@CODIGO_OPCION,                               
		@CLASE_BITACORA ,                              
		@LLAVE_TRANSACCION ,                           
		@REFERENCIA_TRANSACCION ,                      
		@USUARIO_CREA_TRANS ,                          
		@ESTACION_CREA_TRANS,                         
		@FECHA_CREA_TRANS ,         
		@USUARIO_ACTU_TRANS ,                          
		@ESTACION_ACTU_TRANS ,                         
		@FECHA_ACTU_TRANS ,         
		@SYS_LOGIN_USUARIO, --@USUARIO_CREA_BITACORA
		@SYS_ESTACION, --@ESTACION_CREA_BITACORA                      
		@FECHA_CREA_BITACORA ,      
		@SYS_LOGIN_USUARIO,                           
		@SYS_ESTACION ,                                
		@SYS_FILAS_AFECTADAS OUTPUT,
		@SYS_NUMERO_ERROR  OUTPUT,      
		@SYS_MENSAJE_ERROR  OUTPUT

	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DATETIME,
		@CORR_SUSCRIPCION INT=3,
		@CORR_CONFI_PAIS INT=1

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		--EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO