SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_COM_CUADRO_COMPARATIVO]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@CORR_CUADRO_COMPARATIVO INT OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY



			;WITH CTE_PRECIOS_BAJOS AS (
			SELECT 
				B.CORR_EMPRESA,
				B.ANIO_PERIODO_SOLI_COTI,
				B.CORR_SOLI_COTIZACION,
				C.CORR_COTIZACION_DETA,
				MIN(C.PRECIO_UNITARIO) AS MIN_PRECIO
			FROM COM_CUADRO_COMPARATIVO_SOLI_COTIZACION A
			INNER JOIN COM_COTIZACION B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO_SOLI_COTI=B.ANIO_PERIODO_SOLI_COTI AND A.CORR_SOLI_COTIZACION=B.CORR_SOLI_COTIZACION
			INNER JOIN COM_COTIZACION_DETA C ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO = C.ANIO_PERIODO AND B.CORR_COTIZACION = C.CORR_COTIZACION
			WHERE A.CORR_EMPRESA = @CORR_EMPRESA
			AND A.ANIO_PERIODO = @ANIO_PERIODO
			AND A.CORR_CUADRO_COMPARATIVO = @CORR_CUADRO_COMPARATIVO
			GROUP BY 
				B.CORR_EMPRESA,
				B.ANIO_PERIODO_SOLI_COTI,
				B.CORR_SOLI_COTIZACION,
				C.CORR_COTIZACION_DETA
			)


			INSERT INTO dbo.COM_CUADRO_COMPARATIVO_DETA
			(
			    CORR_EMPRESA,
			    ANIO_PERIODO,
			    CORR_CUADRO_COMPARATIVO,
			    ANIO_PERIODO_COTIZACION,
			    CORR_COTIZACION,
			    CORR_COTIZACION_DETA,
			    SELECCION
			)
			SELECT
			A.CORR_EMPRESA,
			A.ANIO_PERIODO,
			A.CORR_CUADRO_COMPARATIVO,
			B.ANIO_PERIODO,
			B.CORR_COTIZACION,
			C.CORR_COTIZACION_DETA,
			1
			FROM dbo.COM_CUADRO_COMPARATIVO_SOLI_COTIZACION A
			INNER JOIN dbo.COM_COTIZACION B ON A.ANIO_PERIODO_SOLI_COTI=B.ANIO_PERIODO_SOLI_COTI AND A.CORR_SOLI_COTIZACION=B.CORR_SOLI_COTIZACION
			INNER JOIN dbo.COM_COTIZACION_DETA C ON C.CORR_EMPRESA = B.CORR_EMPRESA AND C.ANIO_PERIODO = B.ANIO_PERIODO AND C.CORR_COTIZACION = B.CORR_COTIZACION
			INNER JOIN CTE_PRECIOS_BAJOS D ON B.CORR_EMPRESA = C.CORR_EMPRESA AND B.ANIO_PERIODO_SOLI_COTI = D.ANIO_PERIODO_SOLI_COTI AND B.CORR_SOLI_COTIZACION = D.CORR_SOLI_COTIZACION AND C.CORR_COTIZACION_DETA = D.CORR_COTIZACION_DETA AND C.PRECIO_UNITARIO = D.MIN_PRECIO
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO

			INSERT INTO dbo.COM_CUADRO_COMPARATIVO_DETA
			(
			    CORR_EMPRESA,
			    ANIO_PERIODO,
			    CORR_CUADRO_COMPARATIVO,
			    ANIO_PERIODO_COTIZACION,
			    CORR_COTIZACION,
			    CORR_COTIZACION_DETA,
			    SELECCION
			)
			SELECT 
			A.CORR_EMPRESA,
			A.ANIO_PERIODO,
			A.CORR_CUADRO_COMPARATIVO,
			B.ANIO_PERIODO,
			B.CORR_COTIZACION,
			C.CORR_COTIZACION_DETA,
			0
			FROM dbo.COM_CUADRO_COMPARATIVO_SOLI_COTIZACION A
			INNER JOIN dbo.COM_COTIZACION B ON A.ANIO_PERIODO_SOLI_COTI=B.ANIO_PERIODO_SOLI_COTI AND A.CORR_SOLI_COTIZACION=B.CORR_SOLI_COTIZACION
			INNER JOIN dbo.COM_COTIZACION_DETA C ON C.CORR_EMPRESA = B.CORR_EMPRESA AND C.ANIO_PERIODO = B.ANIO_PERIODO AND C.CORR_COTIZACION = B.CORR_COTIZACION
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
			AND NOT EXISTS(SELECT 1 
						   FROM dbo.COM_CUADRO_COMPARATIVO_DETA D
						   WHERE C.CORR_EMPRESA=D.CORR_EMPRESA
						   AND C.ANIO_PERIODO=D.ANIO_PERIODO_COTIZACION
						   AND C.CORR_COTIZACION=D.CORR_COTIZACION
						   AND C.CORR_COTIZACION_DETA=D.CORR_COTIZACION_DETA
						   AND D.ANIO_PERIODO=@ANIO_PERIODO
						   AND D.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO)


		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DATETIME,
		@CORR_SUSCRIPCION INT=3,
		@CORR_CONFI_PAIS INT=1

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		--EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO