SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_DATA_SOLI_COMPRA_DISPONIBLE]
(
	@TIPO_CONSULTA int,
	@FECHA_INICIAL DATE=null,
	@FECHA_FINAL DATE=null,
	@ANIO_PERIODO_SOLI_COMPRA INT=NULL,
	@CORR_SOLI_COMPRA INT=NULL,
	@CORR_EMPRESA INT=NULL,
	@ANIO_PERIODO INT=NULL,
	@CORR_SOLI_COTIZACION INT=NULL,
	@OPCION_CONSULTA int=0
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT @CORR_EMPRESA CORR_EMPRESA
			,@ANIO_PERIODO ANIO_PERIODO
			,@CORR_SOLI_COTIZACION CORR_SOLI_COTIZACION
			,A.ANIO ANIO_PERIODO_SOLI_COMPRA
			,CONVERT(INT,A.IDSOLICITUD) AS CORR_SOLI_COMPRA
			,A.IDDEPTO CODIGO_DEPTO
			,B.CODDSC NOMBRE_DEPTO
			,A.USUARIOSOLI USUARIO_SOLI
			,A.JUSTIFICACION OBSERVACIONES
			,A.FECHASOLICITUD FECHA_SOLICITUD_COMPRA
			,A.ESTADOSOLI USUARIO_SOLI
			,A.USUARIO_CREA
			,A.FECHA_CREA
			,A.USUARIO_ACTUALIZA
			,A.FECHA_ACTUALIZA
			,A.USUARIO_AUTORIZA
			,A.FECHA_AUTORIZA
			,A.USUARIO_APROBAR
			,A.FECHA_APROBAR
			,A.CALIFICACION
			,A.MOTIVOANUL
			FROM [SUEES].dbo.INVC_ENCA_SOLICITUDESCOMPRA A
			INNER JOIN [CLASS_UEES].dbo.CODIGOS B ON B.CODCOD = A.IDDEPTO COLLATE Modern_Spanish_CI_AS AND B.CODREL = 'DPTOS'
			WHERE (
				(CONVERT(DATE,A.FECHASOLICITUD)>=@FECHA_INICIAL AND CONVERT(DATE,A.FECHASOLICITUD)<=@FECHA_FINAL AND ISNULL(@CORR_SOLI_COMPRA,0)=0)
				OR 
				(A.ANIO=@ANIO_PERIODO_SOLI_COMPRA AND CONVERT(INT,A.IDSOLICITUD)=@CORR_SOLI_COMPRA)
			)
			AND A.ESTADOSOLI='APROBADA'
			ORDER BY A.ANIO,CONVERT(INT,A.IDSOLICITUD)
		END ELSE
		IF @OPCION_CONSULTA=1
		BEGIN
			SELECT CONVERT(BIT,1) SELECCION
			,A.INVCOD CODIGO_ITEM
			,B.INVDSC NOMBRE_ITEM
			,A.CANTAPRO CANTIDAD
			,CONVERT(INT,0) CORR_UNIDAD_MEDIDA
			,UPPER(dbo.FN_UNIDAD(B.INVDSC)) NOMBRE_UNIDAD_MEDIDA
			,A.CANTAPRO CANTIDAD_PEDIR
			,'DI' ESTADO_SOLI_COTIZACION
			,A.OBSERVAPRODU OBSERVACIONES
			FROM [SUEES].dbo.INVC_DETA_SOLICITUDESCOMPRA A
			INNER JOIN [CLASS_UEES].dbo.INVENTARIOS B ON B.INVCOD = A.INVCOD COLLATE Modern_Spanish_CI_AS AND B.INVREG = 'E' AND B.INVSUC='001'
			WHERE A.ANIO=@ANIO_PERIODO_SOLI_COMPRA
			AND A.IDSOLICITUD=@CORR_SOLI_COMPRA
			AND NOT EXISTS(SELECT 1 
						   FROM COM_SOLI_COTIZACION_DETA D
						   WHERE A.ANIO=D.ANIO_PERIODO
						   AND A.IDSOLICITUD=D.CORR_SOLI_COMPRA
						   AND A.INVCOD=D.CODIGO_ITEM COLLATE Modern_Spanish_CI_AS
						   AND A.ANIO=@ANIO_PERIODO_SOLI_COMPRA
						   AND D.ANIO_PERIODO=@ANIO_PERIODO
						   AND D.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZACION
						   )
		END
	END 
END
GO