SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--USE [SCUEES]
--GO
--/****** Object:  StoredProcedure [dbo].[PRAL_DATA_COM_COTIZACION]    Script Date: 4/12/2024 12:50:41 ******/
CREATE PROCEDURE [dbo].[PRAL_DATA_COM_ORDEN_COMPRA]
(
	@TIPO_CONSULTA INT,
	@CORR_EMPRESA INT=NULL,
	@ANIO_PERIODO INT=NULL,
	@CORR_CUADRO_COMPARATIVO INT=NULL,
	@LOGIN_SISTEMA VARCHAR(30)=NULL,
	@OPCION_CONSULTA int=0,
	@FECHA_INICIAL DATE=NULL,
	@FECHA_FINAL DATE=NULL
)
AS
BEGIN
	SET NOCOUNT ON

	IF @TIPO_CONSULTA=1 --Todos los campos, todos los registrosl (Mtto)
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT DISTINCT
			 A.CORR_EMPRESA
			 ,A.ANIO_PERIODO
			 ,A.CORR_CUADRO_COMPARATIVO
			,B.ORDFAP FECHA_ORDEN_COMPRA
			,CONVERT(INT,B.ORDNUM) NUMERO_ORDEN_COMPRA
			,C.CODIGO_PROVEEDOR
			,C.NOMBRE_PROVEEDOR
			,C.DIRECCION_PROVEEDOR
			,C.NOMBRE_COMERCIAL
			,C.NOMBRE_ACTIVIDAD_ECONOMICA ACTIVIDAD_ECONOMICA
			,C.NOMBRE_CONTACTO
			,C.CORREO_ELECTRONICO_1 CORREO_ELECTRONICO_PROVEEDOR
			,C.TELEFONO_FIJO TELEFONO_PROVEEDOR
			,B.ORDCPG CONDICION_PAGO
			,F.NUMERO_COTIZACION NUMERO_SOLI_COTIZACION
			,F.NOMBRE_DEPTO NOMBRE_DEPARTAMENTO
			,G.OBSERVACIONES
			,G.TOTAL_EN_LETRAS
			,G.SUB_TOTAL
			,G.TOTAL_IMPUESTO
			,G.TOTAL_ORDEN
			,F.USUARIO_CREA USUARIO_CREA_SOLI
			,H.AUTORIZACIONES_REALIZADAS
			,A.CORR_FORMA_PAGO
			,A.CORR_CONDICION_PAGO
			,A.DETALLE_FORMA_PAGO
			,I.NOMBRE_CONDICION_PAGO
			,J.NOMBRE_FORMA_PAGO
			,B.ORDSTO ESTADO_ORDEN_COMPRA
			,CASE B.ORDSTO 
			WHEN 'P' THEN 'Pendiente de Compra'
			WHEN 'A' THEN 'Anulado'
			ELSE '' END NOMBRE_ESTADO_ORDEN_COMPRA
			FROM COM_CUADRO_COMPARATIVO_ORDEN_COMPRA A
			INNER JOIN CLASS_UEES.dbo.ORDENCOMPRA B ON A.NUMERO_ORDEN=B.ORDNUM
			INNER JOIN V_COM_PROVEEDOR C ON A.CORR_PROVEEDOR = C.CORR_PROVEEDOR
			INNER JOIN V_COM_CUADRO_COMPARATIVO_COTIZACION_SUM F ON A.CORR_EMPRESA = F.CORR_EMPRESA AND A.ANIO_PERIODO = F.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = F.CORR_CUADRO_COMPARATIVO
			INNER JOIN V_COM_ORDEN_COMPRA_TOTALES G ON A.NUMERO_ORDEN = G.NUMERO_ORDEN
			INNER JOIN V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_CONSOLIDADAS H ON A.CORR_EMPRESA = H.CORR_EMPRESA AND A.ANIO_PERIODO = H.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = H.CORR_CUADRO_COMPARATIVO
			LEFT OUTER JOIN COM_CONDICION_PAGO I ON A.CORR_EMPRESA = I.CORR_EMPRESA AND A.CORR_CONDICION_PAGO = I.CORR_CONDICION_PAGO
			LEFT OUTER JOIN V_GEN_FORMA_PAGO J ON A.CORR_FORMA_PAGO = J.CORR_FORMA_PAGO
			WHERE CONVERT(DATE,B.ORDFAP)>=@FECHA_INICIAL
			AND CONVERT(DATE,B.ORDFAP)<=@FECHA_FINAL
			AND NOT EXISTS(SELECT 1 FROM COM_PROVEEDOR_USUARIO A
									WHERE A.LOGIN_SISTEMA=@LOGIN_SISTEMA)
			ORDER BY NUMERO_ORDEN_COMPRA DESC
		END ELSE
		IF @OPCION_CONSULTA=1
		BEGIN 
			SELECT DISTINCT
			 A.CORR_EMPRESA
			 ,A.ANIO_PERIODO
			 ,A.CORR_CUADRO_COMPARATIVO
			,B.ORDFAP FECHA_ORDEN_COMPRA
			,CONVERT(INT,B.ORDNUM) NUMERO_ORDEN_COMPRA
			,C.CODIGO_PROVEEDOR
			,C.NOMBRE_PROVEEDOR
			,C.DIRECCION_PROVEEDOR
			,C.NOMBRE_COMERCIAL
			,C.NOMBRE_ACTIVIDAD_ECONOMICA ACTIVIDAD_ECONOMICA
			,C.NOMBRE_CONTACTO
			,C.CORREO_ELECTRONICO_1 CORREO_ELECTRONICO_PROVEEDOR
			,C.TELEFONO_FIJO TELEFONO_PROVEEDOR
			,B.ORDCPG CONDICION_PAGO
			,F.NUMERO_COTIZACION NUMERO_SOLI_COTIZACION
			,F.NOMBRE_DEPTO NOMBRE_DEPARTAMENTO
			,G.OBSERVACIONES
			,G.TOTAL_EN_LETRAS
			,G.SUB_TOTAL
			,G.TOTAL_IMPUESTO
			,G.TOTAL_ORDEN
			,F.USUARIO_CREA USUARIO_CREA_SOLI
			,H.AUTORIZACIONES_REALIZADAS
			,A.CORR_FORMA_PAGO
			,A.CORR_CONDICION_PAGO
			,A.DETALLE_FORMA_PAGO
			,I.NOMBRE_CONDICION_PAGO
			,J.NOMBRE_FORMA_PAGO
			,B.ORDSTO ESTADO_ORDEN_COMPRA
			,CASE B.ORDSTO 
			WHEN 'P' THEN 'Pendiente de Compra'
			WHEN 'A' THEN 'Anulado'
			ELSE '' END NOMBRE_ESTADO_ORDEN_COMPRA
			FROM COM_CUADRO_COMPARATIVO_ORDEN_COMPRA A
			INNER JOIN CLASS_UEES.dbo.ORDENCOMPRA B ON A.NUMERO_ORDEN=B.ORDNUM
			INNER JOIN V_COM_PROVEEDOR C ON A.CORR_PROVEEDOR = C.CORR_PROVEEDOR
			INNER JOIN V_COM_CUADRO_COMPARATIVO_COTIZACION_NORMAL_SUM F ON A.CORR_EMPRESA = F.CORR_EMPRESA AND A.ANIO_PERIODO = F.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = F.CORR_CUADRO_COMPARATIVO
			INNER JOIN V_COM_ORDEN_COMPRA_TOTALES G ON A.NUMERO_ORDEN = G.NUMERO_ORDEN
			INNER JOIN V_COM_CUADRO_COMPARATIVO_AUTORIZACIONES_CONSOLIDADAS H ON A.CORR_EMPRESA = H.CORR_EMPRESA AND A.ANIO_PERIODO = H.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO = H.CORR_CUADRO_COMPARATIVO
			LEFT OUTER JOIN COM_CONDICION_PAGO I ON A.CORR_EMPRESA = I.CORR_EMPRESA AND A.CORR_CONDICION_PAGO = I.CORR_CONDICION_PAGO
			LEFT OUTER JOIN V_GEN_FORMA_PAGO J ON A.CORR_FORMA_PAGO = J.CORR_FORMA_PAGO
			WHERE CONVERT(DATE,B.ORDFAP)>=@FECHA_INICIAL
			AND CONVERT(DATE,B.ORDFAP)<=@FECHA_FINAL
			AND (A.CORR_PROVEEDOR IN(SELECT A.CORR_PROVEEDOR
									FROM COM_PROVEEDOR_USUARIO AA
									WHERE AA.LOGIN_SISTEMA=@LOGIN_SISTEMA
									AND AA.CORR_PROVEEDOR=A.CORR_PROVEEDOR))
			ORDER BY NUMERO_ORDEN_COMPRA DESC
		END
		
	END ELSE
	IF @TIPO_CONSULTA=2 --Algunos campos, todos los registrosl (Combos)
	BEGIN
		SELECT * FROM V_COM_ORDEN_COMPRA A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
	END ELSE
	IF @TIPO_CONSULTA=3 --Todos los campos, un solo registro
	BEGIN
		SELECT * FROM V_COM_ORDEN_COMPRA A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.CORR_CUADRO_COMPARATIVO=CORR_CUADRO_COMPARATIVO
	END ELSE
	IF @TIPO_CONSULTA=4 --Un campo, un solo registro
	BEGIN
		IF @OPCION_CONSULTA=0
		BEGIN
			SELECT A.CORR_EMPRESA 
			FROM V_COM_ORDEN_COMPRA A
			WHERE A.CORR_EMPRESA=@CORR_EMPRESA
			AND A.CORR_CUADRO_COMPARATIVO=CORR_CUADRO_COMPARATIVO
		END
	END

END
GO