SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_MTTO_COM_COTIZACION_APLICAR]
(
	@CORR_EMPRESA int,
	@ANIO_PERIODO INT,
	@CORR_COTIZACION int OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT output,
	@SYS_NUMERO_ERROR numeric(38,0) output,
	@SYS_MENSAJE_ERROR nvarchar(4000) output
)
AS
	DECLARE @ANIO_PERIODO_SOLI_COTI INT, @CORR_SOLI_COTIZA INT
	DECLARE @ANIO_PERIODO_BITACORA INT=YEAR(GETDATE()),@CORR_BITACORA_TRANS INT=0, @FECHA_BITACORA DATE=GETDATE(), @LLAVE_TRANSACCION VARCHAR(250),@REFERENCIA_TRANSACCION VARCHAR(500), 
	@USUARIO_CREA_TRANS VARCHAR(50), @ESTACION_CREA_TRANS VARCHAR(50), @FECHA_CREA_TRANS DATETIME,@USUARIO_ACTU_TRANS VARCHAR(50), @ESTACION_ACTU_TRANS VARCHAR(50),
	@FECHA_ACTU_TRANS DATETIME, @USUARIO_CREA_BITACORA VARCHAR(50),@ESTACION_CREA_BITACORA VARCHAR(50), @FECHA_CREA_BITACORA DATETIME=GETDATE(),
	@CODIGO_OPCION VARCHAR(150)='COM_COTIZACION',@CLASE_BITACORA VARCHAR(3)='AP'
BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		IF NOT EXISTS(SELECT 1 
				  FROM COM_COTIZACION_DETA 
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND ANIO_PERIODO=@ANIO_PERIODO
				  AND CORR_COTIZACION=@CORR_COTIZACION
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Debe de agregar un item a la cotización para finalizarla..',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		IF NOT EXISTS(SELECT 1 
				  FROM COM_COTIZACION 
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND ANIO_PERIODO=@ANIO_PERIODO
				  AND CORR_COTIZACION=@CORR_COTIZACION
				  AND ESTADO_COTIZACION='SO'
				  )
		BEGIN
			SELECT @SYS_NUMERO_ERROR=30002,@SYS_MENSAJE_ERROR='Debe estar en solicitado la solicitud para poder aplicar la cotización..',@SYS_FILAS_AFECTADAS=0
			GOTO FINA
		END

		------------------------------------------------------------------------
		-------------  BITACORA -------------- 
		SELECT @LLAVE_TRANSACCION='Año: ' + CONVERT(VARCHAR,A.ANIO_PERIODO) COLLATE DATABASE_DEFAULT+' Correlativo No.: '+CONVERT(VARCHAR,A.CORR_COTIZACION) COLLATE DATABASE_DEFAULT,
				@REFERENCIA_TRANSACCION= ' Fecha: ' COLLATE DATABASE_DEFAULT+ CONVERT(VARCHAR,A.FECHA_COTIZACION) COLLATE DATABASE_DEFAULT
										+', Proveedor: '+A.NOMBRE_PROVEEDOR COLLATE DATABASE_DEFAULT
										+', Observaciones: '+A.OBSERVACIONES COLLATE DATABASE_DEFAULT,
				@USUARIO_CREA_TRANS=A.USUARIO_CREA, @ESTACION_CREA_TRANS=A.ESTACION_CREA, @FECHA_CREA_TRANS=A.FECHA_CREA,
				@USUARIO_ACTU_TRANS=A.USUARIO_ACTU, @ESTACION_ACTU_TRANS=A.ESTACION_ACTU, @FECHA_ACTU_TRANS=A.FECHA_ACTU
		FROM V_COM_COTIZACION A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_COTIZACION=@CORR_COTIZACION

		UPDATE COM_COTIZACION SET 
		ESTADO_COTIZACION='AP',
		USUARIO_COTIZA=@SYS_LOGIN_USUARIO
		,USUARIO_ACTU=@SYS_LOGIN_USUARIO
		,ESTACION_ACTU=@SYS_ESTACION
		,FECHA_ACTU=GETDATE()
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND CORR_COTIZACION=@CORR_COTIZACION

		SELECT @ANIO_PERIODO_SOLI_COTI=ANIO_PERIODO_SOLI_COTI
		,@CORR_SOLI_COTIZA=CORR_SOLI_COTIZACION
		FROM COM_COTIZACION
		WHERE CORR_EMPRESA=@CORR_EMPRESA
		AND ANIO_PERIODO=@ANIO_PERIODO
		AND CORR_COTIZACION=@CORR_COTIZACION

		IF NOT EXISTS(SELECT 1 
					  FROM COM_COTIZACION A
					  WHERE A.CORR_EMPRESA=@CORR_EMPRESA
					  AND A.ANIO_PERIODO_SOLI_COTI=@ANIO_PERIODO_SOLI_COTI
					  AND A.CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZA
					  AND A.ESTADO_COTIZACION<>'AP'
					  )
		BEGIN
			UPDATE COM_SOLI_COTIZACION_DETA SET
			ESTADO_SOLI_COTIZACION='AP'
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO_SOLI_COTI
			AND CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZA

		    UPDATE COM_SOLI_COTIZACION SET
			ESTADO_SOLI_COTIZACION='AP'
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND ANIO_PERIODO=@ANIO_PERIODO_SOLI_COTI
			AND CORR_SOLI_COTIZACION=@CORR_SOLI_COTIZA
		END

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

		--Executando el procedimiento de la bitacora
		EXECUTE PRAL_MTTO_COM_BITACORA
		1,--@TIPO_ACTUALIZA ,                              
		@CORR_EMPRESA ,  
		@ANIO_PERIODO_BITACORA,
		@CORR_BITACORA_TRANS  OUTPUT,
		@FECHA_BITACORA ,                    
		@CODIGO_OPCION,                               
		@CLASE_BITACORA ,                              
		@LLAVE_TRANSACCION ,                           
		@REFERENCIA_TRANSACCION ,                      
		@USUARIO_CREA_TRANS ,                          
		@ESTACION_CREA_TRANS,                         
		@FECHA_CREA_TRANS ,         
		@USUARIO_ACTU_TRANS ,                          
		@ESTACION_ACTU_TRANS ,                         
		@FECHA_ACTU_TRANS ,         
		@SYS_LOGIN_USUARIO, --@USUARIO_CREA_BITACORA
		@SYS_ESTACION, --@ESTACION_CREA_BITACORA                      
		@FECHA_CREA_BITACORA ,      
		@SYS_LOGIN_USUARIO,                           
		@SYS_ESTACION ,                                
		@SYS_FILAS_AFECTADAS OUTPUT,
		@SYS_NUMERO_ERROR  OUTPUT,      
		@SYS_MENSAJE_ERROR  OUTPUT

	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DATETIME,
		@CORR_SUSCRIPCION INT=3,
		@CORR_CONFI_PAIS INT=1

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		--EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO