SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRAL_GENE_COM_ORDEN_COMPRA]
(
	@CORR_EMPRESA INT,
	@ANIO_PERIODO INT,
	@CORR_CUADRO_COMPARATIVO INT OUTPUT,
	@SYS_LOGIN_USUARIO VARCHAR(30),
	@SYS_ESTACION VARCHAR(50),
	@SYS_FILAS_AFECTADAS INT OUTPUT,
	@SYS_NUMERO_ERROR NUMERIC(38,0) OUTPUT,
	@SYS_MENSAJE_ERROR NVARCHAR(4000) OUTPUT
)
AS
	---VARIABLES PARA PROCEDIMIENTO DE LA ORDEN
	DECLARE @COMPANIA VARCHAR(2),@ACCION VARCHAR(1),@ARTICULO VARCHAR(30),@NUMERO_ORDEN NUMERIC(18,0)=NULL,@UBICACION VARCHAR(10),@STATUS VARCHAR(3)
	,@TIPO_DESCUENTO VARCHAR(1),@CONDICION_PAGO VARCHAR(150),@CANT_PAQUETES NUMERIC(18,0),@UNID_PAQUETES NUMERIC(18,0),@CANT_RECIBIDO NUMERIC(18,0),@MONTO_UNITARIO NUMERIC(18,2)
	,@IMP_VENTAS NUMERIC(18,2),@DESCUENTO_LINEA NUMERIC(18,2),@DESCUENTO_GENERAL NUMERIC(18,2),@RESOLUCION VARCHAR(150),@FECHA_RESOLUCION DATETIME,@MONEDA VARCHAR(3)
	,@OBSERVACION VARCHAR(2000),@OC_RELACION NUMERIC(18,0)=0,@FECHA_VALOR DATETIME,@MONTO_OC NUMERIC(18,2),@MONEDA_PAGO VARCHAR(3),@USUARIO_ORDEN VARCHAR(50)

	--VARIABLES PARA BITACORA
	DECLARE @ANIO_PERIODO_BITACORA INT=YEAR(GETDATE()),@CORR_BITACORA_TRANS INT=0, @FECHA_BITACORA DATE=GETDATE(), @LLAVE_TRANSACCION VARCHAR(250),@REFERENCIA_TRANSACCION VARCHAR(500), 
	@USUARIO_CREA_TRANS VARCHAR(50), @ESTACION_CREA_TRANS VARCHAR(50), @FECHA_CREA_TRANS DATETIME,@USUARIO_ACTU_TRANS VARCHAR(50), @ESTACION_ACTU_TRANS VARCHAR(50),
	@FECHA_ACTU_TRANS DATETIME, @USUARIO_CREA_BITACORA VARCHAR(50),@ESTACION_CREA_BITACORA VARCHAR(50), @FECHA_CREA_BITACORA DATETIME=GETDATE(),
	@CODIGO_OPCION VARCHAR(150)='COM_CUADRO_COMPARATIVO',@CLASE_BITACORA VARCHAR(3)='AU',
	@REFERENCIA_TRANSACCION_ORDEN VARCHAR(500)

	DECLARE @CORR_PROVEEDOR INT,@CODIGO_PROVEEDOR VARCHAR(25),@IDPREORDEN BIGINT,/*@ANIO_PERIODO_SOLI_COTI INT,@CORR_SOLI_COTIZACION INT,*/@MENSAJE VARCHAR(1000),@ORDEN_RETORNO VARCHAR(150)
	,@CORR_CONDICION_PAGO INT,@CORR_FORMA_PAGO INT,@DETALLE_FORMA_PAGO VARCHAR(250)
	DECLARE @PROVEEDORES TABLE(CORR_PROVEEDOR INT,CODIGO_PROVEEDOR VARCHAR(25),/*ANIO_PERIODO_SOLI_COTI INT,CORR_SOLI_COTIZACION INT,*/ OBSERVACION VARCHAR(2000),CORR_CONDICION_PAGO INT,CORR_FORMA_PAGO INT,DETALLE_FORMA_PAGO VARCHAR(250))
	DECLARE @ORDE_COMPRA TABLE(CODIGO_ITEM VARCHAR(30),CANTIDAD DECIMAL(18,2),UNIDAD_PAQUETE VARCHAR(30),PRECIO_UNITARIO DECIMAL(18,2),VALOR_IVA DECIMAL(18,2),FECHA_VALOR DATE,MONTO_TOTAL DECIMAL(18,2),USUARIO_ORDEN VARCHAR(50))
	DECLARE @MONTO_TOTAL_ORDEN_COMPRA DECIMAL(18,6)
BEGIN

	SET NOCOUNT ON

	SELECT @SYS_NUMERO_ERROR=0,@SYS_MENSAJE_ERROR='',@SYS_FILAS_AFECTADAS=0

	BEGIN TRY
		------------------------------------------------------------------------
		-------------  BITACORA -------------- 
		SELECT @LLAVE_TRANSACCION='Año: '+CONVERT(VARCHAR,A.ANIO_PERIODO)+' Correlativo No.: '+CONVERT(VARCHAR,A.CORR_CUADRO_COMPARATIVO) ,
			   @REFERENCIA_TRANSACCION= ' Fecha: '+ CONVERT(VARCHAR,A.FECHA_CUADRO_COMPARATIVO)
			   						+', Proveedor: '+A.NOMBRE_PROVEEDOR
			   						+', Observaciones: '+A.OBSERVACIONES,
			   @USUARIO_CREA_TRANS=A.USUARIO_CREA, @ESTACION_CREA_TRANS=A.ESTACION_CREA, @FECHA_CREA_TRANS=A.FECHA_CREA,
			   @USUARIO_ACTU_TRANS=A.USUARIO_ACTU, @ESTACION_ACTU_TRANS=A.ESTACION_ACTU, @FECHA_ACTU_TRANS=A.FECHA_ACTU
		FROM V_COM_CUADRO_COMPARATIVO A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO

		INSERT INTO	@PROVEEDORES
		(
			CORR_PROVEEDOR,
			CODIGO_PROVEEDOR,
			OBSERVACION,
			CORR_CONDICION_PAGO,
			CORR_FORMA_PAGO,
			DETALLE_FORMA_PAGO
		)
		SELECT DISTINCT D.CORR_PROVEEDOR,E.CLICUN CODIGO_PROVEEDOR,ISNULL(A.OBSERVACIONES,'')
		,D.CORR_CONDICION_PAGO,D.CORR_FORMA_PAGO,D.DETALLE_FORMA_PAGO
		FROM COM_CUADRO_COMPARATIVO A
		INNER JOIN COM_CUADRO_COMPARATIVO_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO=B.CORR_CUADRO_COMPARATIVO
		INNER JOIN COM_COTIZACION_DETA C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.ANIO_PERIODO_COTIZACION=C.ANIO_PERIODO AND B.CORR_COTIZACION=C.CORR_COTIZACION AND B.CORR_COTIZACION_DETA=C.CORR_COTIZACION_DETA
		INNER JOIN COM_COTIZACION D ON D.CORR_EMPRESA = C.CORR_EMPRESA AND D.ANIO_PERIODO = C.ANIO_PERIODO AND D.CORR_COTIZACION = C.CORR_COTIZACION
		INNER JOIN [CLASS_UEES].dbo.CLIENTES E ON E.CLIIDU = D.CORR_PROVEEDOR
		WHERE A.ANIO_PERIODO=@ANIO_PERIODO
		AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
		AND B.SELECCION=1
		AND ISNULL(C.MONTO_SUBTOTAL,0)>0

		WHILE EXISTS(SELECT 1 FROM @PROVEEDORES)
		BEGIN
			SELECT TOP 1 @CORR_PROVEEDOR=CORR_PROVEEDOR
			,@CODIGO_PROVEEDOR=CODIGO_PROVEEDOR
			,@OBSERVACION=OBSERVACION
			,@CORR_CONDICION_PAGO=CORR_CONDICION_PAGO
			,@CORR_FORMA_PAGO=CORR_FORMA_PAGO
			,@DETALLE_FORMA_PAGO=DETALLE_FORMA_PAGO
			FROM @PROVEEDORES

			INSERT INTO @ORDE_COMPRA
			(
			    CODIGO_ITEM,
			    CANTIDAD,
			    UNIDAD_PAQUETE,
			    PRECIO_UNITARIO,
			    VALOR_IVA,
			    FECHA_VALOR,
			    MONTO_TOTAL,
				USUARIO_ORDEN
			)
			SELECT C.CODIGO_ITEM,
			SUM(C.CANTIDAD) CANTIDAD,
			'1',
			CONVERT(DECIMAL(18,2),ROUND(SUM(C.MONTO_SUBTOTAL)/SUM(C.CANTIDAD),2)),--C.PRECIO_UNITARIO,
			0.0,
			GETDATE(),
			SUM(C.MONTO_SUBTOTAL) MONTO_SUBTOTAL,
			MAX(A.USUARIO_CUADRO_COMPARATIVO)
			FROM COM_CUADRO_COMPARATIVO A
			INNER JOIN COM_CUADRO_COMPARATIVO_DETA B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.ANIO_PERIODO=B.ANIO_PERIODO AND A.CORR_CUADRO_COMPARATIVO=B.CORR_CUADRO_COMPARATIVO
			INNER JOIN COM_COTIZACION_DETA C ON B.CORR_EMPRESA=C.CORR_EMPRESA AND B.ANIO_PERIODO_COTIZACION=C.ANIO_PERIODO AND B.CORR_COTIZACION=C.CORR_COTIZACION AND B.CORR_COTIZACION_DETA=C.CORR_COTIZACION_DETA
			INNER JOIN COM_COTIZACION D ON D.CORR_EMPRESA = C.CORR_EMPRESA AND D.ANIO_PERIODO = C.ANIO_PERIODO AND D.CORR_COTIZACION = C.CORR_COTIZACION
			INNER JOIN COM_SOLI_COTIZACION E ON E.CORR_EMPRESA = D.CORR_EMPRESA AND E.ANIO_PERIODO = D.ANIO_PERIODO_SOLI_COTI AND E.CORR_SOLI_COTIZACION = D.CORR_SOLI_COTIZACION
			WHERE A.ANIO_PERIODO=@ANIO_PERIODO
			AND A.CORR_CUADRO_COMPARATIVO=@CORR_CUADRO_COMPARATIVO
			AND B.SELECCION=1
			AND D.CORR_PROVEEDOR=@CORR_PROVEEDOR
			AND ISNULL(C.MONTO_SUBTOTAL,0)>0
			GROUP BY C.CODIGO_ITEM

			SELECT @NUMERO_ORDEN=NULL,@ORDEN_RETORNO=NULL

			--Obtenes el total de todos los detalles dela orden de compra
			SELECT @MONTO_TOTAL_ORDEN_COMPRA=SUM(MONTO_TOTAL)
			FROM @ORDE_COMPRA

			WHILE EXISTS(SELECT 1 FROM @ORDE_COMPRA)
			BEGIN
				SELECT @CONDICION_PAGO='CRÉDITO 30 DÍAS'
				SELECT @CONDICION_PAGO=NOMBRE_CONDICION_PAGO
				FROM COM_CONDICION_PAGO
				WHERE CORR_EMPRESA=@CORR_EMPRESA
				AND CORR_CONDICION_PAGO=@CORR_CONDICION_PAGO

				SELECT TOP 1 @COMPANIA='01',@ACCION='I',@ARTICULO=CODIGO_ITEM,@UBICACION='001',@STATUS='P',@TIPO_DESCUENTO='M'
				,@CANT_PAQUETES=CANTIDAD,@UNID_PAQUETES=1,@CANT_RECIBIDO=0,@MONTO_UNITARIO=PRECIO_UNITARIO,@IMP_VENTAS=0,@DESCUENTO_LINEA=0,@DESCUENTO_GENERAL=0
				,@FECHA_RESOLUCION=GETDATE(),@MONEDA='USD',@OC_RELACION=0,@FECHA_VALOR=GETDATE(),@MONTO_OC=MONTO_TOTAL
				,@MONEDA_PAGO='USD',@NUMERO_ORDEN=@ORDEN_RETORNO,@RESOLUCION='',@USUARIO_ORDEN=USUARIO_ORDEN
				FROM @ORDE_COMPRA

				EXECUTE CLASS_UEES.dbo.STPR_INVENTARIOS_MANTENIMIENTO_ORDEN_COMPRA 
				@COMPANIA,
				@ACCION,
				@ARTICULO,
				@NUMERO_ORDEN,
				@UBICACION,
				@CODIGO_PROVEEDOR, --@PROVEEDOR
				@STATUS,
				@TIPO_DESCUENTO,
				@CONDICION_PAGO,
				@CANT_PAQUETES,
				@UNID_PAQUETES,
				@CANT_RECIBIDO,
				@MONTO_UNITARIO,
				@IMP_VENTAS,
				@DESCUENTO_LINEA,
				@DESCUENTO_GENERAL,
				@RESOLUCION,
				@FECHA_RESOLUCION,
				@MONEDA,
				@OBSERVACION,
				@MONEDA_PAGO,
				@OC_RELACION,
				@FECHA_VALOR,
				@USUARIO_ORDEN,
				@MONTO_OC,
				@MENSAJE OUTPUT,
				@ORDEN_RETORNO OUTPUT;

				SET @NUMERO_ORDEN=@ORDEN_RETORNO


				DELETE FROM @ORDE_COMPRA 
				WHERE CODIGO_ITEM=@ARTICULO

			END

			--- RELACION ENTRE EL CUADRO COMPARATIVO Y ORDEN DE COMPRA
			INSERT INTO COM_CUADRO_COMPARATIVO_ORDEN_COMPRA
			(CORR_EMPRESA,ANIO_PERIODO,CORR_CUADRO_COMPARATIVO,NUMERO_ORDEN,CORR_PROVEEDOR,MONTO_TOTAL_ORDEN,CORR_CONDICION_PAGO,CORR_FORMA_PAGO,DETALLE_FORMA_PAGO)
			SELECT @CORR_EMPRESA,@ANIO_PERIODO,@CORR_CUADRO_COMPARATIVO,@NUMERO_ORDEN,@CORR_PROVEEDOR,@MONTO_TOTAL_ORDEN_COMPRA,@CORR_CONDICION_PAGO,@CORR_FORMA_PAGO,@DETALLE_FORMA_PAGO

			DELETE FROM @PROVEEDORES 
			WHERE CORR_PROVEEDOR=@CORR_PROVEEDOR

			SELECT @REFERENCIA_TRANSACCION_ORDEN='Orden No.' + CONVERT(VARCHAR(25),@NUMERO_ORDEN) + ' '+ @REFERENCIA_TRANSACCION

			--Executando el procedimiento de la bitacora
			EXECUTE PRAL_MTTO_COM_BITACORA
			1,--@TIPO_ACTUALIZA,                              
			@CORR_EMPRESA,
			@ANIO_PERIODO_BITACORA,
			@CORR_BITACORA_TRANS  OUTPUT,
			@FECHA_BITACORA,              
			@CODIGO_OPCION,                               
			@CLASE_BITACORA,                              
			@LLAVE_TRANSACCION,                      
			@REFERENCIA_TRANSACCION_ORDEN,
			@USUARIO_CREA_TRANS, 
			@ESTACION_CREA_TRANS,                         
			@FECHA_CREA_TRANS,       
			@USUARIO_ACTU_TRANS,                          
			@ESTACION_ACTU_TRANS,                         
			@FECHA_ACTU_TRANS,         
			@SYS_LOGIN_USUARIO, --@USUARIO_CREA_BITACORA
			@SYS_ESTACION, --@ESTACION_CREA_BITACORA                      
			@FECHA_CREA_BITACORA,      
			@SYS_LOGIN_USUARIO,                           
			@SYS_ESTACION,                           
			@SYS_FILAS_AFECTADAS OUTPUT,
			@SYS_NUMERO_ERROR  OUTPUT,      
			@SYS_MENSAJE_ERROR  OUTPUT
		END

		SELECT @SYS_FILAS_AFECTADAS=@@ROWCOUNT

	END TRY

	BEGIN CATCH
		DECLARE
		@CORR_BITACORA  int,
		@SEVERITY_ERROR  int,
		@ESTADO_ERROR     int,
		@ORIGEN_ERROR nvarchar(126),
		@LINEA_ERROR      int,
		@SYS_FECHA DATETIME,
		@CORR_SUSCRIPCION INT=3,
		@CORR_CONFI_PAIS INT=1

		SELECT @CORR_BITACORA=0,
		@SYS_NUMERO_ERROR=ERROR_NUMBER(),
		@SEVERITY_ERROR=ERROR_SEVERITY(),
		@ESTADO_ERROR=ERROR_STATE(),
		@ORIGEN_ERROR=ERROR_PROCEDURE(),
		@LINEA_ERROR=ERROR_LINE(),
		@SYS_MENSAJE_ERROR=ERROR_MESSAGE(),
		@SYS_FECHA=GETDATE()

		--EXEC PRAL_MTTO_ADMIN_BITACORA_SISTEMA 1,@CORR_SUSCRIPCION,@CORR_CONFI_PAIS,@CORR_BITACORA output,'PM',@SYS_NUMERO_ERROR,@SEVERITY_ERROR,@ESTADO_ERROR,@ORIGEN_ERROR,@LINEA_ERROR,@SYS_MENSAJE_ERROR,@SYS_LOGIN_USUARIO,@SYS_FECHA,@SYS_ESTACION

	END CATCH;
FINA:
END
GO