export interface ComSoliCotizacion {
	CORR_EMPRESA: number;
	ANIO_PERIODO: number;
	CORR_SOLI_COTIZACION: number;
  NUMERO_SOLI_COTIZACION: string;
	FECHA_SOLI_COTIZACION: Date;
	FECHA_LIMITE_COTIZACION: Date;
	CODIGO_DEPTO: string;
  NOMBRE_DEPTO: string;
  FECHA_SOLICITUD_COMPRA: Date;
	USUARIO_SOLI: string;
	OBSERVACIONES: string;
	ESTADO_SOLI_COTIZACION: string;
  NOMBRE_ESTADO_SOLI_COTIZACION: string;
	USUARIO_CREA: string;
	FECHA_CREA: Date;
	ESTACION_CREA: string;
	USUARIO_ACTU: string;
	FECHA_ACTU: Date;
	ESTACION_ACTU: string;
  NUMERO_SOLI_COMPRA: string;
	NOMBRE_PROVEEDOR: string;
  CORR_TIPO_SOLI_COTIZA: number;
	NOMBRE_TIPO_SOLI_COTIZA: string;
  CLASE_SOLI_COTIZA: string;
}
