CREATE DATABASE [SGUEES]
GO

ALTER DATABASE [SGUEES]
  SET
    ANSI_NULL_DEFAULT OFF,
    ANSI_NULLS OFF,
    ANSI_PADDING OFF,
    ANSI_WARNINGS OFF,
    ARITHABORT OFF,
    AUTO_CLOSE OFF,
    AUTO_CREATE_STATISTICS ON,
    AUTO_SHRINK OFF,
    AUTO_UPDATE_STATISTICS ON,
    AUTO_UPDATE_STATISTICS_ASYNC OFF,
    COMPATIBILITY_LEVEL = 100,
    CONCAT_NULL_YIELDS_NULL OFF,
    CURSOR_CLOSE_ON_COMMIT OFF,
    CURSOR_DEFAULT GLOBAL,
    DATE_CORRELATION_OPTIMIZATION OFF,
    DB_CHAINING OFF,
    HONOR_BROKER_PRIORITY OFF,
    MULTI_USER,
    NUMERIC_ROUNDABORT OFF,
    PAGE_VERIFY CHECKSUM,
    PARAMETERIZATION SIMPLE,
    QUOTED_IDENTIFIER OFF,
    READ_COMMITTED_SNAPSHOT OFF,
    RECOVERY FULL,
    RECURSIVE_TRIGGERS OFF,
    TRUSTWORTHY OFF
    WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE [SGUEES]
  COLLATE Latin1_General_CS_AS
GO

ALTER DATABASE [SGUEES]
  SET DISABLE_BROKER
GO

ALTER DATABASE [SGUEES]
  SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER AUTHORIZATION ON DATABASE :: [SGUEES] TO [sa]
GO

GRANT CONNECT TO [dbo]
GO

GRANT CONNECT TO [radius]
GO

GRANT CONNECT TO [ssr]
GO

GRANT CONNECT TO [usr_transporte]
GO

GRANT CONNECT TO [webmaster]
GO