CREATE TABLE [dbo].[PLA_PUESTO]
(
	[CORR_EMPRESA] [int] NOT NULL,
	[CORR_PUESTO] [int] NOT NULL,
	[CODIGO_PUESTO] [varchar](15) NULL,
	[NOMBRE_PUESTO] [varchar](100) NULL,
	[CORR_TIPO_PUESTO] [int] NULL,
	[ACTIVO_PUESTO] [bit] NULL,
	[APROBACION_PUESTO] [bit] NULL,
	[MISION_PUESTO] [varchar](255) NULL,
	[OTROS_ASPECTOS] [varchar](255) NULL,
	[USUARIO_CREA] [varchar](50) NULL,
	[ESTACION_CREA] [varchar](50) NULL,
	[FECHA_CREA] [datetime] NULL,
	[USUARIO_ACTU] [varchar](50) NULL,
	[ESTACION_ACTU] [varchar](50) NULL,
	[FECHA_ACTU] [datetime] NULL,
	CONSTRAINT [PK_PLA_PUESTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA] ASC, [CORR_PUESTO] ASC)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLA_PUESTO] ADD CONSTRAINT [DF__PLA_PUEST__ACTIV__1E7C0804] DEFAULT ((1)) FOR [ACTIVO_PUESTO]
GO
ALTER TABLE [dbo].[PLA_PUESTO] ADD CONSTRAINT [DF__PLA_PUEST__APROB__1F702C3D] DEFAULT ((0)) FOR [APROBACION_PUESTO]
GO
ALTER TABLE [dbo].[PLA_PUESTO] ADD CONSTRAINT [FK_PLA_PUESTO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO
ALTER TABLE [dbo].[PLA_PUESTO] ADD CONSTRAINT [FK_PLA_PUESTO_PLA_TIPO_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_TIPO_PUESTO]) REFERENCES [dbo].[PLA_TIPO_PUESTO] ([CORR_EMPRESA], [CORR_TIPO_PUESTO])
GO
-- Sin CHECK.
-- Sin índices adicionales.
-- Sin triggers.
GO
