CREATE TABLE [dbo].[CON_CONFI_REPORTE_DETA]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CONFI_REPORTE] [int] NOT NULL,
[CORR_CONFI_DETA] [int] NOT NULL,
[CUENTA_CONTABLE_INI] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE_FINA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CONFI_REPORTE_DETA] ADD CONSTRAINT [PK_CON_CONFI_REPORTE_DETA] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [CORR_CONFI_REPORTE], [CORR_CONFI_DETA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CONFI_REPORTE_DETA] ADD CONSTRAINT [FK_CON_CONFI_REPORTE_DETA_CON_CONFI_REPORTE] FOREIGN KEY ([CORR_EMPRESA], [CORR_CONFI_REPORTE]) REFERENCES [dbo].[CON_CONFI_REPORTE] ([CORR_EMPRESA], [CORR_CONFI_REPORTE])
GO
ALTER TABLE [dbo].[CON_CONFI_REPORTE_DETA] ADD CONSTRAINT [FK_CON_CONFI_REPORTE_DETA_CON_CATALOGO_CUENTA1] FOREIGN KEY ([CORR_EMPRESA], [CUENTA_CONTABLE_FINA]) REFERENCES [dbo].[CON_CATALOGO_CUENTA] ([CORR_EMPRESA], [CUENTA_CONTABLE])
GO
ALTER TABLE [dbo].[CON_CONFI_REPORTE_DETA] ADD CONSTRAINT [FK_CON_CONFI_REPORTE_DETA_CON_CATALOGO_CUENTA] FOREIGN KEY ([CORR_EMPRESA], [CUENTA_CONTABLE_INI]) REFERENCES [dbo].[CON_CATALOGO_CUENTA] ([CORR_EMPRESA], [CUENTA_CONTABLE])
GO
