CREATE TABLE [dbo].[SEG_MENU_SISTEMA]
(
[CODIGO_MENU] [varchar] (10) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_MENU] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[IMAGEN_MENU] [varchar] (25) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_MENU_SISTEMA] ADD CONSTRAINT [PK_SEG_MENU_SISTEMA] PRIMARY KEY CLUSTERED ([CODIGO_MENU]) ON [PRIMARY]
GO
