CREATE TABLE [dbo].[GEN_TIENDA] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_TIENDA] [int] NOT NULL,
  [NOMBRE_TIENDA] [varchar](150) NOT NULL,
  [CODIGO_UBICACION] [varchar](30) NULL,
  [CORR_CENTRO_BENEFICIO] [int] NULL,
  [CORR_CENTRO_COSTO] [int] NULL,
  CONSTRAINT [PK_GEN_TIENDA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIENDA])
)
ON [PRIMARY]
GO