CREATE TABLE [dbo].[ADMIN_BITACORA_SISTEMA]
(
[CORR_BITACORA] [numeric] (38, 0) NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[TIPO_BITACORA] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL,
[NUMERO_ERROR] [int] NULL,
[SEVERITY_ERROR] [int] NULL,
[ESTADO_ERROR] [int] NULL,
[ORIGEN_ERROR] [nvarchar] (126) COLLATE Latin1_General_CS_AS NULL,
[LINEA_ERROR] [int] NULL,
[MENSAJE_ERROR] [nvarchar] (4000) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADMIN_BITACORA_SISTEMA] ADD CONSTRAINT [PK_ADMIN_BITACORA_SISTEMA] PRIMARY KEY CLUSTERED ([CORR_BITACORA]) ON [PRIMARY]
GO
