CREATE TABLE [dbo].[COM_DOCUMENTO_DETA_DOC]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[MES_PERIODO] [int] NOT NULL,
[CORR_DOCUMENTO] [int] NOT NULL,
[ANIO_PERIODO_DOC] [int] NOT NULL,
[MES_PERIODO_DOC] [int] NOT NULL,
[CORR_DOCUMENTO_DOC] [int] NOT NULL,
[MONTO_DOCUMENTO] [decimal] (14, 2) NULL,
[MONTO_INICIAL] [decimal] (14, 2) NULL,
[MONTO_INGRESO] [decimal] (14, 2) NULL,
[MONTO_FINAL] [decimal] (14, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_DOCUMENTO_DETA_DOC] ADD CONSTRAINT [PK_COM_DOCUMENTO_DETA_DOC] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_DOCUMENTO], [ANIO_PERIODO_DOC], [MES_PERIODO_DOC], [CORR_DOCUMENTO_DOC]) ON [PRIMARY]
GO
