CREATE TABLE [dbo].[CON_UNIDAD_NEGOCIO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_UNIDAD_NEGOCIO] [int] NOT NULL,
  [NOMBRE_UNIDAD_NEGOCIO] [varchar](150) NULL,
  [CODIGO_UNIDAD_NEGOCIO] [varchar](30) NULL,
  [CLASE_UNIDAD_NEGOCIO] [varchar](2) NULL,
  CONSTRAINT [PK_CON_UNIDAD_NEGOCIO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_UNIDAD_NEGOCIO])
)
ON [PRIMARY]
GO