CREATE TABLE [dbo].[SEG_OPCION_SISTEMA_SUITE]
(
[CODIGO_OPCION] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_SUITE] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_OPCION_SISTEMA_SUITE] ADD CONSTRAINT [PK_SEG_OPCION_SISTEMA_SUITE] PRIMARY KEY CLUSTERED ([CODIGO_OPCION], [CODIGO_SUITE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_OPCION_SISTEMA_SUITE] ADD CONSTRAINT [FK_SEG_OPCION_SISTEMA_SUITE_SEG_OPCION_SISTEMA] FOREIGN KEY ([CODIGO_OPCION]) REFERENCES [dbo].[SEG_OPCION_SISTEMA] ([CODIGO_OPCION])
GO
ALTER TABLE [dbo].[SEG_OPCION_SISTEMA_SUITE] ADD CONSTRAINT [FK_SEG_OPCION_SISTEMA_SUITE_SEG_SUITE] FOREIGN KEY ([CODIGO_SUITE]) REFERENCES [dbo].[SEG_SUITE] ([CODIGO_SUITE])
GO
