CREATE TABLE [dbo].[COM_PARAMETRO]
(
[CORR_EMPRESA] [int] NOT NULL,
[GERENTE_COMPRAS] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[GERENTE_CONTABILIDAD] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[GERENTE_GENERAL] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[RECTOR] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[URL_DOCUMENTO] [varchar] (255) COLLATE Latin1_General_CS_AS NULL,
[CORREO_REMITENTE] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_REMITENTE] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[CONTRASENA_REMITENTE] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[SERVIDOR_CORREO] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[PUERTO_CORREO] [int] NULL,
[USA_SSL_CORREO] [bit] NULL,
[NOMBRE_USUARIO_COPIAR] [varchar] (255) COLLATE Latin1_General_CS_AS NULL,
[CORREO_ELECTRONICO_COPIAR] [varchar] (255) COLLATE Latin1_General_CS_AS NULL,
[TOTAL_MINIMO_APLICA_RETENCION] [decimal] (18, 6) NULL,
[USUARIO_FE] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[CLAVE_FE] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[CODIGO_SUITE_FE] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_PARAMETRO] ADD CONSTRAINT [PK_COM_PARAMETRO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA]) ON [PRIMARY]
GO
