CREATE TABLE [dbo].[SC_PERSONA_EXPERIENCIA_LABORAL] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_PERSONA_DATOS] [int] NOT NULL,
  [CORR_EXPERIENCIA_LABORAL] [int] NOT NULL,
  [EMPRESA] [varchar](250) NULL,
  [TELEFONO] [varchar](25) NULL,
  [CARGO] [varchar](150) NULL,
  [JEFE_INMEDIATO] [varchar](150) NULL,
  [FECHA_INICIO] [date] NULL,
  [FECHA_FIN] [date] NULL,
  [SALARIO_INICIAL] [decimal](18, 2) NULL,
  [SALARIO_FINAL] [decimal](18, 2) NULL,
  [MOTIVO_SALIDA] [varchar](500) NULL,
  [USUARIO_CREA] [varchar](30) NOT NULL,
  [ESTACION_CREA] [varchar](50) NOT NULL,
  [FECHA_CREA] [datetime] NOT NULL,
  [USUARIO_ACTU] [varchar](30) NOT NULL,
  [ESTACION_ACTU] [varchar](50) NOT NULL,
  [FECHA_ACTU] [datetime] NOT NULL,
  CONSTRAINT [PK_SC_PERSONA_EXPERIENCIA_LABORAL] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_PERSONA_DATOS], [CORR_EXPERIENCIA_LABORAL]),
  CONSTRAINT [FK_SC_PERSONA_EXPERIENCIA_LABORAL_SC_PERSONA_DATOS] FOREIGN KEY ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
    REFERENCES [dbo].[SC_PERSONA_DATOS] ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
)
ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_SC_PERSONA_EXPERIENCIA_LABORAL_PERSONA]
  ON [dbo].[SC_PERSONA_EXPERIENCIA_LABORAL] ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
GO
