CREATE TABLE [dbo].[PLA_PUESTO_SALARIO]
(
	[CORR_EMPRESA] [int] NOT NULL,
	[CORR_PUESTO_SALARIO] [int] NOT NULL,
	[SALARIO_INICIAL] [decimal](12, 2) NULL,
	[SALARIO_ACTUAL] [decimal](12, 2) NULL,
	[SALARIO_FINAL] [decimal](12, 2) NULL,
	[CORR_UNIDAD] [int] NULL,
	[CORR_PUESTO] [int] NULL,
	[ACTIVO_PUESTO_SALARIO] [bit] NULL,
	[FECHA_INGRESO] [date] NULL,
	[USUARIO_CREA] [varchar](50) NULL,
	[ESTACION_CREA] [varchar](50) NULL,
	[FECHA_CREA] [datetime] NULL,
	[USUARIO_ACTU] [varchar](50) NULL,
	[ESTACION_ACTU] [varchar](50) NULL,
	[FECHA_ACTU] [datetime] NULL,
	CONSTRAINT [PK_PLA_PUESTO_SALARIO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA] ASC, [CORR_PUESTO_SALARIO] ASC)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLA_PUESTO_SALARIO] ADD CONSTRAINT [DF__PLA_PUEST__ACTIV__2EB26FCD] DEFAULT ((1)) FOR [ACTIVO_PUESTO_SALARIO]
GO
ALTER TABLE [dbo].[PLA_PUESTO_SALARIO] ADD CONSTRAINT [FK_PLA_PUESTO_SALARIO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO
ALTER TABLE [dbo].[PLA_PUESTO_SALARIO] ADD CONSTRAINT [FK_PLA_PUESTO_SALARIO_PLA_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_PUESTO]) REFERENCES [dbo].[PLA_PUESTO] ([CORR_EMPRESA], [CORR_PUESTO])
GO
-- Sin CHECK.
-- Sin índices adicionales.
-- Sin triggers.
GO
