CREATE TABLE [dbo].[SEG_USUARIO_CENTRO_COSTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [LOGIN_SISTEMA] [varchar](30) NOT NULL,
  [CORR_CENTRO_COSTO] [int] NOT NULL,
  CONSTRAINT [PK_SEG_USUARIO_CENTRO_COSTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [LOGIN_SISTEMA], [CORR_CENTRO_COSTO])
)
ON [PRIMARY]
GO