CREATE TABLE [dbo].[PLA_NIVEL_ACADEMICO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_NIVEL_ACADEMICO] [int] NOT NULL,
  [NOMBRE_NIVEL_ACADEMICO] [varchar](150) NULL,
  [ESTADO_NIVEL_ACADEMICO] [bit] NULL,
  [USUARIO_CREA] [varchar](30) NULL,
  [FECHA_CREA] [datetime] NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [USUARIO_ACTU] [varchar](30) NULL,
  [FECHA_ACTU] [datetime] NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  CONSTRAINT [PK_PLA_NIVEL_ACADEMICO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_NIVEL_ACADEMICO])
)
ON [PRIMARY]
GO
