CREATE TABLE [dbo].[ADMIN_TIPO_BITACORA]
(
[TIPO_BITACORA] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_TIPO_BITACORA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADMIN_TIPO_BITACORA] ADD CONSTRAINT [PK_ADMIN_TIPO_BITACORA] PRIMARY KEY CLUSTERED ([TIPO_BITACORA]) ON [PRIMARY]
GO
