CREATE TABLE [dbo].[PLA_TIPO_PUESTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_TIPO_PUESTO] [int] NOT NULL,
  [NOMBRE_TIPO_PUESTO] [varchar](100) NULL,
  [ESTADO_TIPO_PUESTO] [bit] NULL,
  [USUARIO_CREA] [varchar](30) NULL,
  [FECHA_CREA] [datetime] NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [USUARIO_ACTU] [varchar](30) NULL,
  [FECHA_ACTU] [datetime] NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  CONSTRAINT [PK_PLA_TIPO_PUESTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_PUESTO])
)
ON [PRIMARY]
GO
