CREATE TABLE [dbo].[GEN_DEPTO] (
  [CORR_PAIS] [int] NOT NULL,
  [CORR_DEPTO] [int] NOT NULL,
  [NOMBRE_DEPTO] [varchar](100) NULL,
  [CODIGO_DEPTO] [varchar](10) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_GEN_DEPTO] PRIMARY KEY CLUSTERED ([CORR_PAIS], [CORR_DEPTO])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[GEN_DEPTO] ADD CONSTRAINT [FK_GEN_DEPTO_GEN_PAIS] FOREIGN KEY ([CORR_PAIS]) REFERENCES [dbo].[GEN_PAIS] ([CORR_PAIS])
GO
