CREATE TABLE [dbo].[SC_TIPO_ENTREVISTA] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_TIPO_ENTREVISTA] [int] NOT NULL,
  [TIPO_ENTREVISTA] [varchar](250) NULL,
  [DESCRIPCION_ENTREVISTA] [varchar](500) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_TIPO_ENTREVISTA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_ENTREVISTA])
)
ON [PRIMARY]
GO
