CREATE TABLE [dbo].[COM_TIPO_SOLI_COTIZA]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_TIPO_SOLI_COTIZA] [int] NOT NULL,
[NOMBRE_TIPO_SOLI_COTIZA] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[CLASE_SOLI_COTIZA] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_TIPO_SOLI_COTIZA] ADD CONSTRAINT [PK_COM_TIPO_SOLI_COTIZA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_SOLI_COTIZA]) ON [PRIMARY]
GO
