CREATE TABLE [dbo].[SC_REQUERIMIENTO_ORGANIZACIONAL] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_REQUERIMIENTO_ORGANIZACIONAL] [int] NOT NULL,
  [DESCRIPCION] [varchar](150) NULL,
  [ESTADO_REQUERIMIENTO_ORGANIZACIONAL] [bit] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_REQUERIMIENTO_ORGANIZACIONAL] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_REQUERIMIENTO_ORGANIZACIONAL])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SC_REQUERIMIENTO_ORGANIZACIONAL] ADD CONSTRAINT [FK_SC_REQUERIMIENTO_ORGANIZACIONAL_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO
