CREATE TABLE [dbo].[SC_PERSONA_COMPETENCIAS_TECNICAS] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_PERSONA_DATOS] [int] NOT NULL,
  [CORR_COMPETENCIA_TECNICA] [int] NOT NULL,
  [HERRAMIENTA] [varchar](150) NULL,
  [NIVEL] [varchar](100) NULL,
  [USUARIO_CREA] [varchar](30) NOT NULL,
  [ESTACION_CREA] [varchar](50) NOT NULL,
  [FECHA_CREA] [datetime] NOT NULL,
  [USUARIO_ACTU] [varchar](30) NOT NULL,
  [ESTACION_ACTU] [varchar](50) NOT NULL,
  [FECHA_ACTU] [datetime] NOT NULL,
  CONSTRAINT [PK_SC_PERSONA_COMPETENCIAS_TECNICAS] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_PERSONA_DATOS], [CORR_COMPETENCIA_TECNICA]),
  CONSTRAINT [FK_SC_PERSONA_COMPETENCIAS_TECNICAS_SC_PERSONA_DATOS] FOREIGN KEY ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
    REFERENCES [dbo].[SC_PERSONA_DATOS] ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
)
ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_SC_PERSONA_COMPETENCIAS_TECNICAS_PERSONA]
  ON [dbo].[SC_PERSONA_COMPETENCIAS_TECNICAS] ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
GO
