CREATE TABLE [dbo].[COM_DOCUMENTO_FISICO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_DOCUMENTO] [int] NOT NULL,
[NOMBRE_DOCUMENTO] [varchar] (150) COLLATE Latin1_General_CS_AS NOT NULL,
[DESCRIPCION_DOCUMENTO] [varchar] (255) COLLATE Latin1_General_CS_AS NULL,
[CORR_TIPO_DOCUMENTO] [int] NOT NULL,
[RUTA_DOCUMENTO] [varchar] (255) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_ARCHIVO] [varchar] (150) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_CREA] [datetime] NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_DOCUMENTO_FISICO] ADD CONSTRAINT [PK_COM_DOCUMENTO_FISICO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DOCUMENTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_DOCUMENTO_FISICO] ADD CONSTRAINT [FK_COM_DOCUMENTO_FISICO_COM_TIPO_DOC_FISICO] FOREIGN KEY ([CORR_EMPRESA], [CORR_TIPO_DOCUMENTO]) REFERENCES [dbo].[COM_TIPO_DOC_FISICO] ([CORR_EMPRESA], [CORR_TIPO_DOCUMENTO])
GO
