CREATE TABLE [dbo].[COM_TIPO_DOC_FISICO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_TIPO_DOCUMENTO] [int] NOT NULL,
[NOMBRE_TIPO_DOCUMENTO] [varchar] (150) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_CORTO_TIPO_DOC] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_TIPO_DOC_FISICO] ADD CONSTRAINT [PK_COM_TIPO_DOC_FISICO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_DOCUMENTO]) ON [PRIMARY]
GO
