CREATE TABLE [dbo].[CON_CONFI_REPORTE]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CONFI_REPORTE] [int] NOT NULL,
[NOMBRE_REPORTE] [varchar] (150) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CONFI_REPORTE] ADD CONSTRAINT [PK_CON_CONFI_REPORTE] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [CORR_CONFI_REPORTE]) ON [PRIMARY]
GO
