CREATE TABLE [dbo].[CON_AREA_FUNCIONAL] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_AREA_FUNCIONAL] [int] NOT NULL,
  [NOMBRE_AREA_FUNCIONAL] [varchar](150) NULL,
  [CODIGO_AREA_FUNCIONAL] [varchar](30) NULL,
  CONSTRAINT [PK_CON_AREA_FUNCIONAL] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_AREA_FUNCIONAL])
)
ON [PRIMARY]
GO