CREATE TABLE [dbo].[BAN_LINEA_TRABAJO_CONCILIACION]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_LINEA] [int] NOT NULL,
[NOMBRE_LINEA_TRABAJO] [varchar] (150) COLLATE Latin1_General_CS_AS NOT NULL,
[AUMENTA_DISMINUYE] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_LINEA_TRABAJO_CONCILIACION] ADD CONSTRAINT [PK_BAN_LINEA_TRABAJO_CONCILIACION] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_LINEA]) ON [PRIMARY]
GO
