CREATE TABLE [dbo].[BAN_TIPO_CHEQUE]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_TIPO_CHEQUE] [int] NOT NULL,
[NOMBRE_TIPO_CHEQUE] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[CLASE_TIPO_CHEQUE] [varchar] (2) COLLATE Latin1_General_CS_AS NULL,
[CONTABILIZAR_LUEGO_DE_IMPRIMIR] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_TIPO_CHEQUE] ADD CONSTRAINT [PK_BAN_TIPO_CHEQUE] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_CHEQUE]) ON [PRIMARY]
GO
