CREATE TABLE [dbo].[SC_DESCRIPTOR_RESPONSABILIDAD_CARGO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_RESPONSABILIDAD] [int] NOT NULL,
  [NOMBRE_RESPONSABILIDAD] [varchar](150) NULL,
  [ESTADO_RESPONSABILIDAD] [bit] NULL,
  [USUARIO_CREA] [varchar](30) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](30) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_RESPONSABILIDAD_CARGO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_RESPONSABILIDAD])
)
ON [PRIMARY]
GO
