CREATE TABLE [dbo].[COM_COTIZACION_COMENTARIO]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_COTIZACION] [int] NOT NULL,
[CORR_COMENTARIO] [int] NOT NULL,
[CLASE_COMENTARIO] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL,
[COMENTARIO] [varchar] (max) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_COTIZACION_COMENTARIO] ADD CONSTRAINT [PK_COM_COTIZACION_COMENTARIO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_COTIZACION], [CORR_COMENTARIO]) ON [PRIMARY]
GO
