CREATE TABLE [dbo].[SEG_USUARIO]
(
[LOGIN_SISTEMA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_USUARIO] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[CLAVE_USUARIO] [varbinary] (max) NOT NULL,
[CLAVE_USUARIO_SAL] [varbinary] (max) NOT NULL,
[CORREO_ELECTRONICO] [varchar] (255) COLLATE Latin1_General_CS_AS NOT NULL,
[TIPO_USUARIO] [int] NOT NULL,
[ESTADO_USUARIO] [int] NOT NULL,
[IDIOMA] [varchar] (10) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_AD] [varchar] (100) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_USUARIO] ADD CONSTRAINT [PK_SEG_USUARIO] PRIMARY KEY CLUSTERED ([LOGIN_SISTEMA]) ON [PRIMARY]
GO
