CREATE TABLE [dbo].[CON_CATALOGO_PRESUPUESTO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CUENTA_CONTABLE] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[MONTO_PRESUPUESTO_1] [decimal] (12, 2) NOT NULL,
[MONTO_PRESUPUESTO_2] [decimal] (12, 2) NOT NULL,
[MONTO_PRESUPUESTO_3] [decimal] (12, 2) NOT NULL,
[MONTO_PRESUPUESTO_4] [decimal] (12, 2) NOT NULL,
[MONTO_PRESUPUESTO_5] [decimal] (12, 2) NOT NULL,
[MONTO_PRESUPUESTO_6] [decimal] (12, 2) NOT NULL,
[MONTO_PRESUPUESTO_7] [decimal] (12, 2) NOT NULL,
[MONTO_PRESUPUESTO_8] [decimal] (12, 2) NOT NULL,
[MONTO_PRESUPUESTO_9] [decimal] (12, 2) NOT NULL,
[MONTO_PRESUPUESTO_10] [decimal] (12, 2) NOT NULL,
[MONTO_PRESUPUESTO_11] [decimal] (12, 2) NOT NULL,
[MONTO_PRESUPUESTO_12] [decimal] (12, 2) NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CATALOGO_PRESUPUESTO] ADD CONSTRAINT [PK_CON_CATALOGO_PRESUPUESTO] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [CUENTA_CONTABLE], [ANIO_PERIODO]) ON [PRIMARY]
GO
