CREATE TABLE [dbo].[GEN_SECCION]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_DIVISION] [int] NOT NULL,
[CORR_GERENCIA] [int] NOT NULL,
[CORR_DEPARTAMENTO] [int] NOT NULL,
[CORR_SECCION] [int] NOT NULL,
[NOMBRE_SECCION] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_SECCION] [varchar] (3) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_SECCION] ADD CONSTRAINT [PK_CON_SECCION] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [CORR_DIVISION], [CORR_GERENCIA], [CORR_DEPARTAMENTO], [CORR_SECCION]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_SECCION] ADD CONSTRAINT [UX_CON_SECCION] UNIQUE NONCLUSTERED  ([CORR_EMPRESA], [CORR_DIVISION], [CORR_GERENCIA], [CORR_DEPARTAMENTO], [CODIGO_SECCION]) ON [PRIMARY]
GO
