CREATE TABLE [dbo].[GEN_DEPARTAMENTO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_DIVISION] [int] NOT NULL,
[CORR_GERENCIA] [int] NOT NULL,
[CORR_DEPARTAMENTO] [int] NOT NULL,
[NOMBRE_DEPARTAMENTO] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_DEPARTAMENTO] [varchar] (3) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_DEPARTAMENTO] ADD CONSTRAINT [PK_CON_DEPARTAMENTO] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [CORR_DIVISION], [CORR_GERENCIA], [CORR_DEPARTAMENTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_DEPARTAMENTO] ADD CONSTRAINT [UX_CON_DEPARTAMENTO] UNIQUE NONCLUSTERED  ([CORR_EMPRESA], [CORR_DIVISION], [CORR_GERENCIA], [CODIGO_DEPARTAMENTO]) ON [PRIMARY]
GO
