CREATE TABLE [dbo].[SC_DESCRIPTOR_PUESTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [FECHA_EMISION] [date] NULL,
  [FECHA_REVISION] [date] NULL,
  [OBJETIVO_PUESTO] [varchar](255) NULL,
  [NUM_PERSONAL_CARGO] [int] NULL,
  [CORR_PUESTO] [int] NULL,
  [NOMBRE_PUESTO] [varchar](100) NULL,
  [CORR_UNIDAD] [int] NULL,
  [NOMBRE_UNIDAD] [varchar](100) NULL,
  [CORR_PUESTO_REPORTA] [int] NULL,
  [CORR_IMPACTO_ECONOMICO] [int] NULL,
  [DESCRIPCION_IMPACTO_ECONOMICO] [varchar](150) NULL,
  [CORR_INDUCCION] [int] NULL,
  [NOMBRE_INDUCCION] [varchar](200) NULL,
  [SEMANAS_INDUCCION] [int] NULL,
  [RESPONSABLE] [varchar](100) NULL,
  [FORMATO] [varchar](50) NULL,
  [VERSION] [int] NULL,
  [ESTADO_DESCRIPTOR] [varchar](50) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_PUESTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO]),
  CONSTRAINT [CK__SC_DESCRI__FORMA__40313633] CHECK ([FORMATO]='EXTENSO' OR [FORMATO]='CORTO'),
  CONSTRAINT [CK__SC_DESCRI__ESTAD__41255A6C] CHECK ([ESTADO_DESCRIPTOR]='INACTIVO' OR [ESTADO_DESCRIPTOR]='ACTIVO' OR [ESTADO_DESCRIPTOR]='REVISADO' OR [ESTADO_DESCRIPTOR]='ENVIADO' OR [ESTADO_DESCRIPTOR]='BORRADOR'),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA])
    REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_PLA_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_PUESTO])
    REFERENCES [dbo].[PLA_PUESTO] ([CORR_EMPRESA], [CORR_PUESTO]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES] FOREIGN KEY ([CORR_EMPRESA], [CORR_UNIDAD])
    REFERENCES [dbo].[SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES] ([CORR_EMPRESA], [CORR_UNIDAD]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_SC_DESCRIPTOR_IMPACTO_ECONOMICO] FOREIGN KEY ([CORR_EMPRESA], [CORR_IMPACTO_ECONOMICO])
    REFERENCES [dbo].[SC_IMPACTO_ECONOMICO] ([CORR_EMPRESA], [CORR_IMPACTO_ECONOMICO]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_SC_INDUCCION] FOREIGN KEY ([CORR_EMPRESA], [CORR_INDUCCION])
    REFERENCES [dbo].[SC_INDUCCION] ([CORR_EMPRESA], [CORR_INDUCCION])
)
ON [PRIMARY]
GO
