CREATE TABLE [dbo].[BAN_CUENTA_BANCARIA]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CUENTA_BANCO] [int] NOT NULL,
[NUMERO_CUENTA_BANCO] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[CORR_BANCO] [int] NOT NULL,
[CUENTA_CONTABLE] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[NOMBRE_REPORTE] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[TIPO_CUENTA_BANCO] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL,
[CORR_CENTRO_COSTO] [int] NULL,
[CORR_MONEDA] [int] NOT NULL,
[CODIGO_EMPRESARIAL] [varchar] (25) COLLATE Latin1_General_CS_AS NULL,
[CODIGO_EMPRESARIAL_PROV] [varchar] (25) COLLATE Latin1_General_CS_AS NULL,
[NO_PERMITE_MODIFICAR] [bit] NOT NULL CONSTRAINT [DF_BAN_CUENTA_BANCARIA_NO_PERMITE_MODIFICAR] DEFAULT ((0)),
[VALIDAR_SALDO] [bit] NULL,
[PAGA_PLANILLA] [bit] NULL,
[VALIDA_FECHA] [bit] NULL,
[NOMBRE_CUENTA] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[NO_PERMITE_CHEQUES] [bit] NULL,
[ESTADO_CUENTA_BANCARIA] [bit] NOT NULL CONSTRAINT [DF_BAN_CUENTA_BANCARIA_ESTADO_CUENTA_BANCARIA] DEFAULT ((1)),
[USA_TRANSACIONES_UNI] [bit] NULL,
[CLASE_CHEQUE] [varchar] (2) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_CREA] [datetime] NULL,
[ESTACION_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_CUENTA_BANCARIA] ADD CONSTRAINT [PK_BAN_CUENTA_BANCARIA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CUENTA_BANCO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_CUENTA_BANCARIA] ADD CONSTRAINT [FK_BAN_CUENTA_BANCARIA_GEN_BANCO] FOREIGN KEY ([CORR_EMPRESA], [CORR_BANCO]) REFERENCES [dbo].[GEN_BANCO] ([CORR_EMPRESA], [CORR_BANCO])
GO
