CREATE TABLE [dbo].[SC_TIPO_PLAZA] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_TIPO_PLAZA] [int] NOT NULL,
  [NOMBRE_TIPO_PLAZA] [varchar](250) NULL,
  [CANTIDAD_DIAS_GESTION] [int] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_TIPO_PLAZA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_PLAZA])
)
ON [PRIMARY]
GO