CREATE TABLE [dbo].[SC_PERFIL_PUESTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_PERFIL_PUESTO] [int] NOT NULL,
  [EDAD_MINIMA] [tinyint] NULL,
  [EDAD_MAXIMA] [tinyint] NULL,
  [SEXO] [varchar](25) NULL,
  [ESTADO_FAMILIAR] [varchar](25) NULL,
  [LICENCIA] [bit] NULL,
  [CORR_DISPONIBILIDAD_HORARIO] [int] NULL,
  [NOMBRE_DISPONIBILIDAD_HORARIO] [varchar](150) NULL,
  [CORR_TIPO_MODALIDAD] [int] NULL,
  [NOMBRE_MODALIDAD] [varchar](100) NULL,
  [OTROS] [varchar](150) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_PERFIL_PUESTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO], [CORR_PERFIL_PUESTO]),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA])
    REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_SC_DESCRIPTOR_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO])
    REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO]),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_SC_DISPONIBILIDAD_HORARIO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DISPONIBILIDAD_HORARIO])
    REFERENCES [dbo].[SC_DISPONIBILIDAD_HORARIO] ([CORR_EMPRESA], [CORR_DISPONIBILIDAD_HORARIO]),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_SC_TIPO_MODALIDAD] FOREIGN KEY ([CORR_EMPRESA], [CORR_TIPO_MODALIDAD])
    REFERENCES [dbo].[SC_TIPO_MODALIDAD] ([CORR_EMPRESA], [CORR_TIPO_MODALIDAD]),
  CONSTRAINT [CK_SC_PERFIL_PUESTO_SEXO] CHECK ([SEXO] IN ('MASCULINO', 'FEMENINO', 'INDIFERENTE')),
  CONSTRAINT [CK_SC_PERFIL_PUESTO_ESTADO_FAMILIAR] CHECK ([ESTADO_FAMILIAR] IN ('CASADO', 'SOLTERO', 'INDIFERENTE', 'OTRO'))
)
ON [PRIMARY]
GO
