CREATE TABLE [dbo].[CON_CATALOGO_SALDO_HIS]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CUENTA_CONTABLE] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[SALDO_INICIAL1] [decimal] (12, 2) NOT NULL,
[SALDO_INICIAL2] [decimal] (12, 2) NOT NULL,
[SALDO_INICIAL3] [decimal] (12, 2) NOT NULL,
[SALDO_INICIAL4] [decimal] (12, 2) NOT NULL,
[SALDO_INICIAL5] [decimal] (12, 2) NOT NULL,
[SALDO_INICIAL6] [decimal] (12, 2) NOT NULL,
[SALDO_INICIAL7] [decimal] (12, 2) NOT NULL,
[SALDO_INICIAL8] [decimal] (12, 2) NOT NULL,
[SALDO_INICIAL9] [decimal] (12, 2) NOT NULL,
[SALDO_INICIAL10] [decimal] (12, 2) NOT NULL,
[SALDO_INICIAL11] [decimal] (12, 2) NOT NULL,
[SALDO_INICIAL12] [decimal] (12, 2) NOT NULL,
[SALDO_FINAL12] [decimal] (12, 2) NOT NULL,
[CARGO_PERIODO] [decimal] (12, 2) NOT NULL,
[ABONO_PERIODO] [decimal] (12, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CATALOGO_SALDO_HIS] ADD CONSTRAINT [PK_CON_CATALOGO_SALDO_HIS] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [ANIO_PERIODO], [CUENTA_CONTABLE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CATALOGO_SALDO_HIS] ADD CONSTRAINT [FK_CON_CATALOGO_SALDO_HIS_CON_CATALOGO_CUENTA] FOREIGN KEY ([CORR_EMPRESA], [CUENTA_CONTABLE]) REFERENCES [dbo].[CON_CATALOGO_CUENTA] ([CORR_EMPRESA], [CUENTA_CONTABLE])
GO
