CREATE TABLE [dbo].[SC_UNIDADES_TIPO_USUARIO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_UNIDAD] [int] NOT NULL,
  [TIPO_USUARIO] [int] NOT NULL,
  [ACTIVO] [bit] NULL CONSTRAINT [DF__SC_UNIDAD__ACTIV__14FCBF6B] DEFAULT ((1)),
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_UNIDADES_TIPO_USUARIO] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA],
    [CORR_UNIDAD],
    [TIPO_USUARIO]
  )
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SC_UNIDADES_TIPO_USUARIO] ADD CONSTRAINT [FK_SC_UNIDADES_TIPO_USUARIO_GEN_EMPRESA]
  FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO

ALTER TABLE [dbo].[SC_UNIDADES_TIPO_USUARIO] ADD CONSTRAINT [FK_SC_UNIDADES_TIPO_USUARIO_SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES]
  FOREIGN KEY ([CORR_EMPRESA], [CORR_UNIDAD])
  REFERENCES [dbo].[SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES] ([CORR_EMPRESA], [CORR_UNIDAD])
GO

ALTER TABLE [dbo].[SC_UNIDADES_TIPO_USUARIO] ADD CONSTRAINT [FK_SC_UNIDADES_TIPO_USUARIO_SEG_TIPO_USUARIO]
  FOREIGN KEY ([TIPO_USUARIO]) REFERENCES [dbo].[SEG_TIPO_USUARIO] ([TIPO_USUARIO])
GO
