CREATE TABLE [dbo].[SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_PERFIL_PUESTO] [int] NOT NULL,
  [CORR_COMPETENCIAS_CONDUCTUALES] [int] NOT NULL,
  [CODIGO_TIPO_PUESTO] [varchar](30) NULL,
  [NOMBRE_COMPETENCIAS_CONDUCTUALES] [varchar](150) NULL,
  [DESCRIPCION] [varchar](500) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_PERFIL_PUESTO],
    [CORR_COMPETENCIAS_CONDUCTUALES]
  ),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA])
    REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES_SC_DESCRIPTOR_PUESTO] FOREIGN KEY (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO]
  ) REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO]
  ),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES_SC_PERFIL_PUESTO] FOREIGN KEY (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_PERFIL_PUESTO]
  ) REFERENCES [dbo].[SC_PERFIL_PUESTO] (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_PERFIL_PUESTO]
  ),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_COMPETENCIAS_CONDUCTUALES_SC_COMPETENCIAS_CONDUCTUALES] FOREIGN KEY (
    [CORR_EMPRESA],
    [CORR_COMPETENCIAS_CONDUCTUALES]
  ) REFERENCES [dbo].[SC_COMPETENCIAS_CONDUCTUALES] (
    [CORR_EMPRESA],
    [CORR_COMPETENCIAS_CONDUCTUALES]
  )
)
ON [PRIMARY]
GO
