CREATE TABLE [dbo].[SC_PERFIL_PUESTO_EXPERIENCIA] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_PERFIL_PUESTO] [int] NOT NULL,
  [CORR_EXPERIENCIA] [int] NOT NULL,
  [REQUISITO] [varchar](255) NULL,
  [TIPO_REQUERIDO] [varchar](25) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_PERFIL_PUESTO_EXPERIENCIA] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_PERFIL_PUESTO],
    [CORR_EXPERIENCIA]
  ),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_EXPERIENCIA_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA])
    REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_EXPERIENCIA_SC_PERFIL_PUESTO] FOREIGN KEY (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_PERFIL_PUESTO]
  ) REFERENCES [dbo].[SC_PERFIL_PUESTO] (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_PERFIL_PUESTO]
  ),
  CONSTRAINT [CK_SC_PERFIL_PUESTO_EXPERIENCIA_TIPO_REQUERIDO] CHECK (
    [TIPO_REQUERIDO] IN ('SI', 'NO', 'DESEABLE')
  )
)
ON [PRIMARY]
GO
