CREATE TABLE [dbo].[SC_DESCRIPTOR_RELACION_LABORAL] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_RELACION_LABORAL] [int] NOT NULL,
  [TIPO_RELACION] [char](1) NULL,
  [PUESTO_AREA] [varchar](255) NULL,
  [MOTIVO_RELACION] [varchar](500) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_RELACION_LABORAL] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO], [CORR_RELACION_LABORAL]),
  CONSTRAINT [FK_SC_DESCRIPTOR_RELACION_LABORAL_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA])
    REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]),
  CONSTRAINT [FK_SC_DESCRIPTOR_RELACION_LABORAL_SC_DESCRIPTOR_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO])
    REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO])
)
ON [PRIMARY]
GO
