CREATE TABLE [dbo].[GEN_TIPO_DOCUMENTO_RUBRO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_TIPO_DOC] [int] NOT NULL,
[CORR_RUBRO] [int] NOT NULL,
[ORDEN_TOTAL] [int] NOT NULL,
[PERMITE_EDITAR] [bit] NOT NULL,
[ES_PRINCIPAL] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_TIPO_DOCUMENTO_RUBRO] ADD CONSTRAINT [PK_GEN_TIPO_DOCUMENTO_RUBRO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_DOC], [CORR_RUBRO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_TIPO_DOCUMENTO_RUBRO] ADD CONSTRAINT [FK_GEN_TIPO_DOCUMENTO_RUBRO_GEN_RUBRO] FOREIGN KEY ([CORR_EMPRESA], [CORR_RUBRO]) REFERENCES [dbo].[GEN_RUBRO] ([CORR_EMPRESA], [CORR_RUBRO])
GO
ALTER TABLE [dbo].[GEN_TIPO_DOCUMENTO_RUBRO] ADD CONSTRAINT [FK_GEN_TIPO_DOCUMENTO_RUBRO_GEN_TIPO_DOCUMENTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_TIPO_DOC]) REFERENCES [dbo].[GEN_TIPO_DOCUMENTO] ([CORR_EMPRESA], [CORR_TIPO_DOC])
GO
