CREATE TABLE [dbo].[SC_PERSONA_FAMILIAR_UEES] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_PERSONA_DATOS] [int] NOT NULL,
  [CORR_FAMILIAR_UEES] [int] NOT NULL,
  [NOMBRE] [varchar](150) NULL,
  [PARENTESCO] [varchar](100) NULL,
  [UNIDAD] [varchar](150) NULL,
  [TELEFONO] [varchar](25) NULL,
  [USUARIO_CREA] [varchar](30) NOT NULL,
  [ESTACION_CREA] [varchar](50) NOT NULL,
  [FECHA_CREA] [datetime] NOT NULL,
  [USUARIO_ACTU] [varchar](30) NOT NULL,
  [ESTACION_ACTU] [varchar](50) NOT NULL,
  [FECHA_ACTU] [datetime] NOT NULL,
  CONSTRAINT [PK_SC_PERSONA_FAMILIAR_UEES] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_PERSONA_DATOS], [CORR_FAMILIAR_UEES]),
  CONSTRAINT [FK_SC_PERSONA_FAMILIAR_UEES_SC_PERSONA_DATOS] FOREIGN KEY ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
    REFERENCES [dbo].[SC_PERSONA_DATOS] ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
)
ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_SC_PERSONA_FAMILIAR_UEES_PERSONA]
  ON [dbo].[SC_PERSONA_FAMILIAR_UEES] ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
GO
