CREATE TABLE [dbo].[COM_CUADRO_COMPARATIVO_SOLI_COTIZACION]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_CUADRO_COMPARATIVO] [int] NOT NULL,
[ANIO_PERIODO_SOLI_COTI] [int] NOT NULL,
[CORR_SOLI_COTIZACION] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_CUADRO_COMPARATIVO_SOLI_COTIZACION] ADD CONSTRAINT [PK_COM_CUADRO_COMPARATIVO_SOLI_COTIZACION] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_CUADRO_COMPARATIVO], [ANIO_PERIODO_SOLI_COTI], [CORR_SOLI_COTIZACION]) ON [PRIMARY]
GO
