CREATE TABLE [dbo].[SC_DESCRIPTOR_PUESTO_INDUCCION] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_INDUCCION] [int] NOT NULL,
  [NOMBRE_INDUCCION] [varchar](100) NULL,
  [TIEMPO_INDUCCION] [int] NULL,
  [UNIDAD_TIEMPO] [varchar](15) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_PUESTO_INDUCCION] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_INDUCCION]
  ),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_INDUCCION_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA])
    REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_INDUCCION_SC_DESCRIPTOR_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO])
    REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_INDUCCION_SC_INDUCCION] FOREIGN KEY ([CORR_EMPRESA], [CORR_INDUCCION])
    REFERENCES [dbo].[SC_INDUCCION] ([CORR_EMPRESA], [CORR_INDUCCION])
)
ON [PRIMARY]
GO
