CREATE TABLE [dbo].[COM_COTIZACION]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_COTIZACION] [int] NOT NULL,
[FECHA_COTIZACION] [date] NOT NULL,
[CORR_PROVEEDOR] [int] NOT NULL,
[USUARIO_COTIZA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[OBSERVACIONES] [varchar] (1000) COLLATE Latin1_General_CS_AS NOT NULL,
[OBSERVACIONES_PROVEEDOR] [varchar] (1000) COLLATE Latin1_General_CS_AS NOT NULL,
[PLAZO_ENTREGA] [varchar] (150) COLLATE Latin1_General_CS_AS NOT NULL,
[ESTADO_COTIZACION] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL,
[ANIO_PERIODO_SOLI_COTI] [int] NOT NULL,
[CORR_SOLI_COTIZACION] [int] NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[CORR_CONDICION_PAGO] [int] NULL,
[CORR_FORMA_PAGO] [int] NULL,
[DETALLE_FORMA_PAGO] [varchar] (250) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_COTIZACION] ADD CONSTRAINT [PK_COM_COTIZACION] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_COTIZACION]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_COTIZACION] ADD CONSTRAINT [FK_COM_COTIZACION_COM_SOLI_COTIZACION] FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO_SOLI_COTI], [CORR_SOLI_COTIZACION]) REFERENCES [dbo].[COM_SOLI_COTIZACION] ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_SOLI_COTIZACION])
GO
