CREATE TABLE [dbo].[GEN_MUNICIPIO] (
  [CORR_PAIS] [int] NOT NULL,
  [CORR_DEPTO] [int] NOT NULL,
  [CORR_MUNICIPIO] [int] NOT NULL,
  [NOMBRE_MUNICIPIO] [varchar](100) NULL,
  [CODIGO_MUNICIPIO] [varchar](10) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_GEN_MUNICIPIO] PRIMARY KEY CLUSTERED ([CORR_PAIS], [CORR_DEPTO], [CORR_MUNICIPIO])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[GEN_MUNICIPIO] ADD CONSTRAINT [FK_GEN_MUNICIPIO_GEN_DEPTO] FOREIGN KEY ([CORR_PAIS], [CORR_DEPTO]) REFERENCES [dbo].[GEN_DEPTO] ([CORR_PAIS], [CORR_DEPTO])
GO
