CREATE TABLE [dbo].[BAN_TIPO_CHEQUE]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_TIPO_CHEQUE] [int] NOT NULL,
[NOMBRE_TIPO_CHEQUE] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[CLASE_TIPO_CHEQUE] [varchar] (2) COLLATE Latin1_General_CS_AS NULL,
[CONTABILIZAR_LUEGO_DE_IMPRIMIR] [bit] NULL,
[ESTADO_TIPO_CHEQUE] [bit] NOT NULL CONSTRAINT [DF_BAN_TIPO_CHEQUE_ESTADO_TIPO_CHEQUE] DEFAULT ((1)),
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_CREA] [datetime] NULL,
[ESTACION_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_TIPO_CHEQUE] ADD CONSTRAINT [PK_BAN_TIPO_CHEQUE] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_CHEQUE]) ON [PRIMARY]
GO
