CREATE TABLE [dbo].[SC_DESCRIPTOR_FUNCION_ACTIVIDAD] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_FUNCION] [int] NOT NULL,
  [CORR_ACTIVIDAD] [int] NOT NULL,
  [NOMBRE_ACTIVIDAD] [varchar](255) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_FUNCION_ACTIVIDAD] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO], [CORR_FUNCION], [CORR_ACTIVIDAD]),
  CONSTRAINT [FK_SC_DESCRIPTOR_FUNCION_ACTIVIDAD_SC_DESCRIPTOR_FUNCION] FOREIGN KEY ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO], [CORR_FUNCION])
    REFERENCES [dbo].[SC_DESCRIPTOR_FUNCION] ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO], [CORR_FUNCION])
)
ON [PRIMARY]
GO
