CREATE TABLE [dbo].[SC_DESCRIPTOR_IMPACTO_ECONOMICO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_IMPACTO_ECONOMICO] [int] NOT NULL,
  [DESCRIPCION] [varchar](150) NULL,
  [ESTADO_IMPACTO_ECONOMICO] [bit] NULL,
  [USUARIO_CREA] [varchar](30) NULL,
  [FECHA_CREA] [datetime] NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [USUARIO_ACTU] [varchar](30) NULL,
  [FECHA_ACTU] [datetime] NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_IMPACTO_ECONOMICO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_IMPACTO_ECONOMICO])
)
ON [PRIMARY]
GO
