IF OBJECT_ID(N'dbo.SYS_INSTANCIA_REMOTA', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[SYS_INSTANCIA_REMOTA]
	(
		[CODIGO_INSTANCIA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
		[NOMBRE_LINKED_SERVER] [varchar] (128) COLLATE Latin1_General_CS_AS NOT NULL,
		[DESCRIPCION] [nvarchar] (200) COLLATE Latin1_General_CS_AS NOT NULL,
		[SERVIDOR] [varchar] (128) COLLATE Latin1_General_CS_AS NOT NULL,
		[NOMBRE_BASE_DATOS] [varchar] (128) COLLATE Latin1_General_CS_AS NOT NULL,
		[USUARIO_SQL] [varchar] (128) COLLATE Latin1_General_CS_AS NOT NULL,
		[CLAVE_SQL] [varchar] (256) COLLATE Latin1_General_CS_AS NOT NULL,
		[PROVEEDOR_OLEDB] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_SYS_INSTANCIA_REMOTA_PROVEEDOR] DEFAULT ('MSOLEDBSQL'),
		[TRUST_SERVER_CERTIFICATE] [bit] NOT NULL CONSTRAINT [DF_SYS_INSTANCIA_REMOTA_TRUST_CERT] DEFAULT ((1)),
		[RPC_HABILITADO] [bit] NOT NULL CONSTRAINT [DF_SYS_INSTANCIA_REMOTA_RPC] DEFAULT ((1)),
		[ACTIVO] [bit] NOT NULL CONSTRAINT [DF_SYS_INSTANCIA_REMOTA_ACTIVO] DEFAULT ((1)),
		[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
		[FECHA_ACTU] [datetime] NULL,
		[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
		CONSTRAINT [PK_SYS_INSTANCIA_REMOTA] PRIMARY KEY CLUSTERED ([CODIGO_INSTANCIA])
	);

	CREATE UNIQUE NONCLUSTERED INDEX [UX_SYS_INSTANCIA_REMOTA_LINKED_SERVER]
		ON [dbo].[SYS_INSTANCIA_REMOTA] ([NOMBRE_LINKED_SERVER]);
END
GO
