CREATE TABLE [dbo].[COM_PROVEEDOR_USUARIO]
(
[CORR_PROVEEDOR] [int] NOT NULL,
[LOGIN_SISTEMA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_PROVEEDOR_USUARIO] ADD CONSTRAINT [PK_COM_PROVEEDOR_USUARIO] PRIMARY KEY CLUSTERED ([CORR_PROVEEDOR], [LOGIN_SISTEMA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_PROVEEDOR_USUARIO] ADD CONSTRAINT [FK_COM_PROVEEDOR_USUARIO_COM_PROVEEDOR] FOREIGN KEY ([CORR_PROVEEDOR]) REFERENCES [dbo].[COM_PROVEEDOR] ([CORR_PROVEEDOR])
GO
