CREATE TABLE [dbo].[COM_CUADRO_COMPARATIVO_CONFIG_AUTORIZACIONES]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CONFIGURACION] [int] NOT NULL,
[LOGIN_SISTEMA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_CARGO] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[MONTO_INICIAL] [decimal] (18, 2) NULL,
[MONTO_FINAL] [decimal] (18, 2) NULL,
[CLASE_AUTORIZACION] [varchar] (5) COLLATE Latin1_General_CS_AS NULL,
[ORDEN_REVISION] [int] NULL,
[PERMITE_MODIFICAR] [bit] NULL,
[ESTADO_AUTORIZA] [varchar] (2) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_CUADRO_COMPARATIVO_CONFIG_AUTORIZACIONES] ADD CONSTRAINT [PK_COM_CUADRO_COMPARATIVO_CONFIG_AUTORIZACIONES] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CONFIGURACION]) ON [PRIMARY]
GO
