CREATE TABLE [dbo].[CON_RUBRO_NIVEL] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CODIGO_RUBRO] [varchar](30) NOT NULL,
  [NIVEL] [smallint] NOT NULL,
  [NUMERO_CARACTERES] [smallint] NOT NULL,
  CONSTRAINT [PK_CON_RUBRO_NIVEL] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CODIGO_RUBRO], [NIVEL])
)
ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE TRIGGER [td_CON_RUBRO_NIVEL] ON [dbo].[CON_RUBRO_NIVEL] 
FOR DELETE
AS
	DECLARE
	@numrows  int,
	@numnull  int,
	@errno    int,
	@errmsg   varchar(255),
	@CORR_EMPRESA smallint,
	@CODIGO_RUBRO varchar(30),
	@NIVEL int,
	@NUMERO_CARACTERES int,
	@TAMANO_CUENTA int
BEGIN

	SELECT  @numrows = @@rowcount
	IF @numrows = 0
	RETURN

	IF @numrows > 1
	BEGIN
		SELECT @errno  = 30002,
		@errmsg = 'No se Puede Eliminar Mas de un Registro a la Vez'
		GOTO ERROR
	END

	SELECT @CORR_EMPRESA=CORR_EMPRESA,
		@CODIGO_RUBRO=CODIGO_RUBRO,
		@NUMERO_CARACTERES=NUMERO_CARACTERES,
		@TAMANO_CUENTA=DATALENGTH(CODIGO_RUBRO),
		@NIVEL=NIVEL
	FROM deleted

	IF EXISTS(SELECT 1 FROM CON_RUBRO_NIVEL
			WHERE CODIGO_RUBRO=@CODIGO_RUBRO
			AND NIVEL>@NIVEL
			AND CORR_EMPRESA=@CORR_EMPRESA)
	BEGIN
		SELECT @errno  = 30020,
		@errmsg = 'Existe Nivel de Rubro Posterior a Nivel '+LTRIM(RTRIM(str(@NIVEL)))
		GOTO ERROR
	END

	IF EXISTS(SELECT 1 FROM CON_CATALOGO_CUENTA
			WHERE SUBSTRING(CUENTA_CONTABLE,1,@TAMANO_CUENTA)=@CODIGO_RUBRO
			AND DATALENGTH(CUENTA_CONTABLE)=@NUMERO_CARACTERES 
			AND CORR_EMPRESA=@CORR_EMPRESA)
	BEGIN
		SELECT @errno  = 30010,
		@errmsg = 'Existe(n) Cuenta(s) en Catalogo Contable definida(s) con largo de cuenta de '+LTRIM(RTRIM(str(@NUMERO_CARACTERES)))+' caracter(es)'
		GOTO ERROR
	END

	DECLARE DETA_RUBR CURSOR
	FOR SELECT CODIGO_RUBRO
	FROM CON_RUBRO
	WHERE CODIGO_RUBRO<>@CODIGO_RUBRO
	AND CORR_EMPRESA=@CORR_EMPRESA

	OPEN DETA_RUBR 
	FETCH DETA_RUBR INTO @CODIGO_RUBRO
	WHILE (@@FETCH_STATUS=0)
	BEGIN
		IF EXISTS(SELECT 1 FROM CON_RUBRO_NIVEL
         	    WHERE CORR_EMPRESA=@CORR_EMPRESA
        	    AND CODIGO_RUBRO=@CODIGO_RUBRO
        	    AND NIVEL=@NIVEL)
		BEGIN
			DELETE FROM CON_RUBRO_NIVEL
			WHERE CORR_EMPRESA=@CORR_EMPRESA
			AND CODIGO_RUBRO=@CODIGO_RUBRO
			AND NIVEL=@NIVEL
		END          
		FETCH DETA_RUBR INTO @CODIGO_RUBRO
	END
	CLOSE DETA_RUBR
	DEALLOCATE DETA_RUBR

RETURN

/*  Errors handling  */

ERROR:
	RAISERROR (@errmsg, 16, 1)
	ROLLBACK TRANSACTION
END
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE TRIGGER [ti_CON_RUBRO_NIVEL] ON [dbo].[CON_RUBRO_NIVEL] 
FOR INSERT
AS
	DECLARE
	@numrows  int,
	@numnull  int,
	@errno    int,
	@errmsg   varchar(255),
	@CORR_EMPRESA smallint,
	@CODIGO_RUBRO varchar(30),
	@NUMERO_CARACTERES tinyint,
	@NIVEL int,
	@TAMANO_CUENTA int
BEGIN

	SELECT  @numrows = @@rowcount
	IF @numrows = 0
	RETURN

	IF @numrows > 1
	BEGIN
		SELECT @errno  = 30000,
		@errmsg = 'No se Puede Insertar Mas de un Registro a la Vez'
		GOTO ERROR
	END

	SELECT @CORR_EMPRESA=CORR_EMPRESA,
		@CODIGO_RUBRO=CODIGO_RUBRO,
		@NUMERO_CARACTERES=NUMERO_CARACTERES,
		@NIVEL=NIVEL,
		@TAMANO_CUENTA=DATALENGTH(CODIGO_RUBRO)
	FROM inserted

	IF (@NIVEL > 1)
	BEGIN
		IF NOT EXISTS(SELECT 1 FROM CON_RUBRO_NIVEL
                 WHERE CODIGO_RUBRO=@CODIGO_RUBRO
                 AND NIVEL=@NIVEL-1
                 AND CORR_EMPRESA=@CORR_EMPRESA)
		BEGIN
			SELECT @errno  = 30020,
			@errmsg = 'No Existe Nivel de Rubro Anterior a Nivel '+LTRIM(RTRIM(STR(@NIVEL)))
			GOTO ERROR
		END

		IF EXISTS(SELECT 1 FROM CON_RUBRO_NIVEL A
					INNER JOIN inserted B ON  A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CODIGO_RUBRO=B.CODIGO_RUBRO
					WHERE A.NIVEL<>B.NIVEL
					AND A.CODIGO_RUBRO=@CODIGO_RUBRO
					AND A.NUMERO_CARACTERES=@NUMERO_CARACTERES             
					)
		BEGIN
			SELECT @errno  = 30021,
			@errmsg = 'Ya Existe Nivel de Rubro con Numero de Carateres '+LTRIM(RTRIM(STR(@NUMERO_CARACTERES)))
			GOTO ERROR
		END
	END

	DECLARE DETA_RUBR CURSOR
	FOR SELECT CODIGO_RUBRO
		FROM CON_RUBRO
		WHERE CODIGO_RUBRO<>@CODIGO_RUBRO
		AND CORR_EMPRESA=@CORR_EMPRESA
	
	OPEN DETA_RUBR
	FETCH DETA_RUBR INTO @CODIGO_RUBRO
	WHILE (@@FETCH_STATUS=0)
	BEGIN
		IF NOT EXISTS(SELECT 1 FROM CON_RUBRO_NIVEL
         	    WHERE CORR_EMPRESA=@CORR_EMPRESA
        	    AND CODIGO_RUBRO=@CODIGO_RUBRO
        	    AND NIVEL=@NIVEL)
		BEGIN
			INSERT INTO CON_RUBRO_NIVEL
			(CORR_EMPRESA,CODIGO_RUBRO,NIVEL,NUMERO_CARACTERES)
			VALUES(@CORR_EMPRESA,@CODIGO_RUBRO,@NIVEL,@NUMERO_CARACTERES)
		END
		FETCH DETA_RUBR INTO @CODIGO_RUBRO
	END
	CLOSE DETA_RUBR
	DEALLOCATE DETA_RUBR

RETURN

/*  Errors handling  */

ERROR:
	RAISERROR (@errmsg, 16, 1)
	ROLLBACK TRANSACTION
END
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE TRIGGER [tu_CON_RUBRO_NIVEL] ON [dbo].[CON_RUBRO_NIVEL] 
FOR UPDATE
AS
	DECLARE
	@numrows  int,
	@numnull  int,
	@errno    int,
	@errmsg   varchar(255),
	@CORR_EMPRESA int,
	@CODIGO_RUBRO varchar(30),
	@NIVEL int,
	@NUMERO_CARACTERES_NUEVO int,
	@NUMERO_CARACTERES_ANTERIOR int,
	@TAMANO_CUENTA int
BEGIN
	SELECT @numrows = @@rowcount
	IF @numrows = 0
	RETURN

	IF @numrows > 1
	BEGIN
		SELECT @errno  = 30001,
		@errmsg = 'No se Puede Actualizar Mas de un Registro a la Vez'
		GOTO ERROR
	END

	IF UPDATE(NUMERO_CARACTERES)
	BEGIN
		SELECT @CORR_EMPRESA=A.CORR_EMPRESA,
		@CODIGO_RUBRO=A.CODIGO_RUBRO,
		@NUMERO_CARACTERES_NUEVO=A.NUMERO_CARACTERES,
		@NUMERO_CARACTERES_ANTERIOR=B.NUMERO_CARACTERES,
		@TAMANO_CUENTA=DATALENGTH(A.CODIGO_RUBRO),
		@NIVEL=A.NIVEL
		FROM inserted A
		INNER JOIN deleted B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CODIGO_RUBRO=B.CODIGO_RUBRO

		IF (@NUMERO_CARACTERES_ANTERIOR<>@NUMERO_CARACTERES_NUEVO)
		BEGIN
			IF EXISTS(SELECT 1 FROM CON_RUBRO_NIVEL A
						INNER JOIN inserted B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CODIGO_RUBRO=B.CODIGO_RUBRO 
						WHERE B.CORR_EMPRESA=@CORR_EMPRESA 
						AND A.NIVEL>B.NIVEL
						AND A.NUMERO_CARACTERES<B.NUMERO_CARACTERES)
 			BEGIN
				SELECT @errno  = 30022,
				@errmsg = 'Numero de carateres Invalido '+LTRIM(RTRIM(STR(@NUMERO_CARACTERES_NUEVO)))
				GOTO ERROR
			END

			IF EXISTS(SELECT 1 from CON_RUBRO_NIVEL A
						INNER JOIN inserted B ON A.CORR_EMPRESA=B.CORR_EMPRESA AND A.CODIGO_RUBRO=B.CODIGO_RUBRO
						WHERE A.CORR_EMPRESA=@CORR_EMPRESA
						AND A.CODIGO_RUBRO=@CODIGO_RUBRO						
						AND A.NUMERO_CARACTERES=@NUMERO_CARACTERES_NUEVO					
						AND A.NIVEL<>B.NIVEL)
 			BEGIN
				SELECT @errno  = 30021,
				@errmsg = 'Existe Nivel de Rubro con numero de carateres '+LTRIM(RTRIM(STR(@NUMERO_CARACTERES_NUEVO)))
				GOTO ERROR
			END

			--IF EXISTS(SELECT 1 from CON_CATALOGO_CUENTA
			--		WHERE subSTRing(CUENTA_CONTABLE,1,@TAMANO_CUENTA)=@CODIGO_RUBRO
			--		AND DATALENGTH(CUENTA_CONTABLE)=@NUMERO_CARACTERES_ANTERIOR
			--		AND CORR_EMPRESA=@CORR_EMPRESA
			--BEGIN
 		--		SELECT @errno  = 30010,
			--	@errmsg = 'Existe(n) Cuenta(s) en Catalogo Contable definida(s) con largo de cuenta de '+LTRIM(RTRIM(STR(@NUMERO_CARACTERES_ANTERIOR)))+' caracter(es)'
			--	GOTO ERROR
	 	--	END

			DECLARE DETA_RUBR CURSOR
			FOR
			SELECT CODIGO_RUBRO
			FROM CON_RUBRO
			WHERE CODIGO_RUBRO<>@CODIGO_RUBRO
			AND CORR_EMPRESA=@CORR_EMPRESA
			
			OPEN DETA_RUBR
			FETCH DETA_RUBR INTO @CODIGO_RUBRO
			WHILE (@@FETCH_STATUS=0)
			BEGIN
				IF EXISTS(SELECT 1 from CON_RUBRO_NIVEL
         				WHERE CORR_EMPRESA=@CORR_EMPRESA
        				AND CODIGO_RUBRO=@CODIGO_RUBRO
        				AND NIVEL=@NIVEL)
				BEGIN
	       			UPDATE CON_RUBRO_NIVEL SET 
					NUMERO_CARACTERES=@NUMERO_CARACTERES_NUEVO
					WHERE CORR_EMPRESA=@CORR_EMPRESA
					AND CODIGO_RUBRO=@CODIGO_RUBRO
					AND NIVEL=@NIVEL
				END
				FETCH DETA_RUBR INTO @CODIGO_RUBRO
			END
			CLOSE DETA_RUBR
			DEALLOCATE DETA_RUBR
		END
	END

RETURN

/*  Errors hANDling  */

ERROR:
	RAISERROR (@errmsg, 16, 1)
	ROLLBACK TRANSACTION

END
GO