CREATE TABLE [dbo].[SC_FRECUENCIA] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_FRECUENCIA] [int] NOT NULL,
  [NOMBRE_FRECUENCIA] [varchar](50) NULL,
  [ESTADO_FRECUENCIA] [bit] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_FRECUENCIA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_FRECUENCIA])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SC_FRECUENCIA] ADD CONSTRAINT [FK_SC_FRECUENCIA_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO
