CREATE TABLE [dbo].[PLA_CARGO_CON_CENTRO_COSTO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CARGO] [int] NOT NULL,
[CORR_CENTRO_COSTO] [int] NOT NULL,
[CANTIDAD_MAXIMA_EMPLEADOS] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLA_CARGO_CON_CENTRO_COSTO] ADD CONSTRAINT [PK_PLA_CARGO_CON_CENTRO_COSTO] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [CORR_CARGO], [CORR_CENTRO_COSTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLA_CARGO_CON_CENTRO_COSTO] ADD CONSTRAINT [FK_PLA_CARGO_CON_CENTRO_COSTO_PLA_CARGO] FOREIGN KEY ([CORR_EMPRESA], [CORR_CARGO]) REFERENCES [dbo].[PLA_CARGO] ([CORR_EMPRESA], [CORR_CARGO])
GO
ALTER TABLE [dbo].[PLA_CARGO_CON_CENTRO_COSTO] ADD CONSTRAINT [FK_PLA_CARGO_CON_CENTRO_COSTO_CON_CENTRO_COSTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_CENTRO_COSTO]) REFERENCES [dbo].[CON_CENTRO_COSTO] ([CORR_EMPRESA], [CORR_CENTRO_COSTO])
GO
