CREATE TABLE [dbo].[PLA_NIVEL_ACADEMICO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_NIVEL_ACADEMICO] [int] NOT NULL,
  [NOMBRE_NIVEL_ACADEMICO] [varchar](150) NULL,
  [ESTADO_NIVEL_ACADEMICO] [bit] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_PLA_NIVEL_ACADEMICO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_NIVEL_ACADEMICO])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[PLA_NIVEL_ACADEMICO] ADD CONSTRAINT [FK_PLA_NIVEL_ACADEMICO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO
