CREATE TABLE [dbo].[SC_UNIDADES_USUARIO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_UNIDAD] [int] NOT NULL,
  [LOGIN_SISTEMA] [varchar](30) NOT NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_UNIDADES_USUARIO] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA],
    [CORR_UNIDAD],
    [LOGIN_SISTEMA]
  )
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SC_UNIDADES_USUARIO] ADD CONSTRAINT [FK_SC_UNIDADES_USUARIO_GEN_EMPRESA]
  FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO

ALTER TABLE [dbo].[SC_UNIDADES_USUARIO] ADD CONSTRAINT [FK_SC_UNIDADES_USUARIO_SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES]
  FOREIGN KEY ([CORR_EMPRESA], [CORR_UNIDAD])
  REFERENCES [dbo].[SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES] ([CORR_EMPRESA], [CORR_UNIDAD])
GO

ALTER TABLE [dbo].[SC_UNIDADES_USUARIO] ADD CONSTRAINT [FK_SC_UNIDADES_USUARIO_SEG_USUARIO]
  FOREIGN KEY ([LOGIN_SISTEMA]) REFERENCES [dbo].[SEG_USUARIO] ([LOGIN_SISTEMA])
GO
