CREATE TABLE [dbo].[COM_COTIZACION_DOC]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_COTIZACION] [int] NOT NULL,
[CORR_DOCUMENTO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_COTIZACION_DOC] ADD CONSTRAINT [PK_COM_COTIZACION_DOC] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_COTIZACION], [CORR_DOCUMENTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_COTIZACION_DOC] ADD CONSTRAINT [FK_COM_COTIZACION_DOC_COM_COTIZACION] FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_COTIZACION]) REFERENCES [dbo].[COM_COTIZACION] ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_COTIZACION])
GO
ALTER TABLE [dbo].[COM_COTIZACION_DOC] ADD CONSTRAINT [FK_COM_COTIZACION_DOC_COM_DOCUMENTO_FISICO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DOCUMENTO]) REFERENCES [dbo].[COM_DOCUMENTO_FISICO] ([CORR_EMPRESA], [CORR_DOCUMENTO])
GO
