CREATE TABLE [dbo].[SC_EXPEDIENTE_CANDIDATO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_EXPEDIENTE_CANDIDATO] [int] NOT NULL,
  [CORR_PERSONA_DATOS] [int] NOT NULL,
  [FECHA_GENERACION] [datetime] NOT NULL,
  [ACTIVO] [bit] NOT NULL CONSTRAINT [DF_SC_EXPEDIENTE_CANDIDATO_ACTIVO] DEFAULT (1),
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_EXPEDIENTE_CANDIDATO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SC_EXPEDIENTE_CANDIDATO] ADD CONSTRAINT [FK_SC_EXPEDIENTE_CANDIDATO_GEN_EMPRESA]
  FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO

ALTER TABLE [dbo].[SC_EXPEDIENTE_CANDIDATO] ADD CONSTRAINT [FK_SC_EXPEDIENTE_CANDIDATO_SC_PERSONA_DATOS]
  FOREIGN KEY ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
  REFERENCES [dbo].[SC_PERSONA_DATOS] ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_SC_EXPEDIENTE_CANDIDATO_PERSONA]
  ON [dbo].[SC_EXPEDIENTE_CANDIDATO] ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
GO
