CREATE TABLE [dbo].[COM_SOLI_COTIZACION]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_SOLI_COTIZACION] [int] NOT NULL,
[FECHA_SOLI_COTIZACION] [date] NOT NULL,
[FECHA_LIMITE_COTIZACION] [date] NOT NULL,
[CODIGO_DEPTO] [varchar] (10) COLLATE Latin1_General_CS_AS NOT NULL,
[ANIO_PERIODO_SOLI_COMPRA] [int] NULL,
[CORR_SOLI_COMPRA] [int] NULL,
[USUARIO_SOLI] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[OBSERVACIONES] [varchar] (1000) COLLATE Latin1_General_CS_AS NOT NULL,
[ESTADO_SOLI_COTIZACION] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[CORR_TIPO_SOLI_COTIZA] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_SOLI_COTIZACION] ADD CONSTRAINT [PK_COM_SOLI_COTIZACION] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_SOLI_COTIZACION]) ON [PRIMARY]
GO
