CREATE TABLE [dbo].[GEN_PARAMETRO_SMTP]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_PARAMETRO_SMTP] [int] NOT NULL,
[CORREO_REMITENTE] [varchar] (255) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_REMITENTE] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[CONTRASENA_REMITENTE] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[SERVIDOR_CORREO] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[PUERTO_CORREO] [int] NULL,
[USA_SSL_CORREO] [bit] NULL,
[USUARIO_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[FECHA_CREA] [datetime] NULL,
[USUARIO_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_PARAMETRO_SMTP] ADD CONSTRAINT [PK_GEN_PARAMETRO_SMTP] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_PARAMETRO_SMTP]) ON [PRIMARY]
GO
