CREATE TABLE [dbo].[SC_DESCRIPTOR_KPI_FUNCION] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_KPI_FUNCION] [int] NOT NULL,
  [NOMBRE_INDICADOR] [varchar](255) NULL,
  [CORR_FRECUENCIA] [int] NULL,
  [META] [int] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_KPI_FUNCION] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO], [CORR_KPI_FUNCION]),
  CONSTRAINT [FK_SC_DESCRIPTOR_KPI_FUNCION_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA])
    REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]),
  CONSTRAINT [FK_SC_DESCRIPTOR_KPI_FUNCION_SC_DESCRIPTOR_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO])
    REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO]),
  CONSTRAINT [FK_SC_DESCRIPTOR_KPI_FUNCION_SC_FRECUENCIA] FOREIGN KEY ([CORR_EMPRESA], [CORR_FRECUENCIA])
    REFERENCES [dbo].[SC_FRECUENCIA] ([CORR_EMPRESA], [CORR_FRECUENCIA])
)
ON [PRIMARY]
GO
