CREATE TABLE [dbo].[COM_CUADRO_COMPARATIVO]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_CUADRO_COMPARATIVO] [int] NOT NULL,
[FECHA_CUADRO_COMPARATIVO] [date] NULL,
[ESTADO_CUADRO_COMPARATIVO] [varchar] (2) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_CUADRO_COMPARATIVO] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[OBSERVACIONES] [varchar] (1000) COLLATE Latin1_General_CS_AS NULL,
[ES_MEJOR_PRECIO] [bit] NOT NULL,
[TIENE_CREDITO_30_DIAS] [bit] NOT NULL,
[TIENE_BUEN_SOPORTE_TECNICO] [bit] NOT NULL,
[TIENE_BUENA_CALIDAD_PRODUCTO] [bit] NOT NULL,
[TIENE_MEJOR_TIEMPO_ENTREGA] [bit] NOT NULL,
[BRINDA_BUENA_EXPERIENCIA_PROVEEDOR] [bit] NOT NULL,
[ES_PROVEEDOR_UNICO] [bit] NOT NULL,
[EXISTE_OTRA_RAZON] [bit] NOT NULL,
[NOMBRE_OTRA_RAZON] [varchar] (255) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_CREA] [datetime] NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_CUADRO_COMPARATIVO] ADD CONSTRAINT [PK_COM_CUADRO_COMPARATIVO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_CUADRO_COMPARATIVO]) ON [PRIMARY]
GO
