CREATE TABLE [dbo].[SEG_USUARIO_EMPRESA_TIENDA] (
  [LOGIN_SISTEMA] [varchar](30) NOT NULL,
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_TIENDA] [int] NOT NULL,
  [POR_DEFECTO] [int] NOT NULL,
  CONSTRAINT [PK_SEG_USUARIO_EMPRESA_TIENDA] PRIMARY KEY CLUSTERED ([LOGIN_SISTEMA], [CORR_EMPRESA], [CORR_TIENDA])
)
ON [PRIMARY]
GO