CREATE TABLE [dbo].[CON_PARTIDA_MODELO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CLASE_PARTIDA] [int] NOT NULL,
[CORR_PARTIDA] [int] NOT NULL,
[NUMERO_DOCUMENTO] [varchar] (25) COLLATE Latin1_General_CS_AS NULL,
[NOMBRE_PARTIDA] [varchar] (1000) COLLATE Latin1_General_CS_AS NULL,
[ESTADO_PARTIDA] [varchar] (2) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[CLASE_PARTIDA] [varchar] (3) COLLATE Latin1_General_CS_AS NULL CONSTRAINT [DF_CON_PARTIDA_MODELO_CLASE_PARTIDA] DEFAULT ('NOR'),
[CORR_MONEDA] [int] NULL,
[FACTOR_CAMBIO] [decimal] (16, 6) NULL,
[OPERADOR] [varchar] (2) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA_MODELO] ADD CONSTRAINT [PK_CON_PARTIDA_MODELO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CLASE_PARTIDA], [CORR_PARTIDA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA_MODELO] ADD CONSTRAINT [FK_CON_PARTIDA_MODELO_CON_CLASE_PARTIDA] FOREIGN KEY ([CORR_EMPRESA], [CORR_CLASE_PARTIDA]) REFERENCES [dbo].[CON_CLASE_PARTIDA] ([CORR_EMPRESA], [CORR_CLASE_PARTIDA])
GO
