-- Tabla para almacenar historial de contrasenas y evitar reutilizacion
CREATE TABLE [dbo].[SEG_USUARIO_CLAVE_HISTORIAL]
(
    [CORR_CLAVE] [int] IDENTITY(1,1) NOT NULL,
    [LOGIN_SISTEMA] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
    [CLAVE_USUARIO] [varbinary](max) NOT NULL,
    [CLAVE_USUARIO_SAL] [varbinary](max) NOT NULL,
    [FECHA_CAMBIO] [datetime] NOT NULL DEFAULT GETDATE(),
    [USUARIO_ACTU] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
    [ESTACION_ACTU] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
    CONSTRAINT [PK_SEG_USUARIO_CLAVE_HISTORIAL] PRIMARY KEY CLUSTERED ([CORR_CLAVE]),
    CONSTRAINT [FK_SEG_USUARIO_CLAVE_HISTORIAL_SEG_USUARIO] FOREIGN KEY ([LOGIN_SISTEMA]) 
        REFERENCES [dbo].[SEG_USUARIO]([LOGIN_SISTEMA])
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

-- Indice para busquedas rapidas por usuario y fecha
CREATE NONCLUSTERED INDEX [IX_SEG_USUARIO_CLAVE_HISTORIAL_LOGIN_FECHA]
ON [dbo].[SEG_USUARIO_CLAVE_HISTORIAL] ([LOGIN_SISTEMA], [FECHA_CAMBIO] DESC)
GO

PRINT 'Tabla SEG_USUARIO_CLAVE_HISTORIAL creada exitosamente';
