CREATE TABLE [dbo].[GEN_TIPO_MONEDA] (
  [CORR_MONEDA] [int] NOT NULL,
  [NOMBRE_MONEDA] [varchar](50) COLLATE Latin1_General_CS_AS NOT NULL,
  [DESCRIPCION_MONEDA] [varchar](150) COLLATE Latin1_General_CS_AS NULL,
  [SIMBOLO] [varchar](10) COLLATE Latin1_General_CS_AS NULL,
  [ESTADO_MONEDA] [bit] NOT NULL CONSTRAINT [DF_GEN_TIPO_MONEDA_ESTADO] DEFAULT ((1)),
  [USUARIO_CREA] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
  [ESTACION_CREA] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
  [ESTACION_ACTU] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_GEN_TIPO_MONEDA] PRIMARY KEY CLUSTERED ([CORR_MONEDA])
)
ON [PRIMARY]
GO
