CREATE TABLE [dbo].[PLA_PUESTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_PUESTO] [int] NOT NULL,
  [NOMBRE_PUESTO] [varchar](100) NULL,
  [CORR_GERENCIA] [int] NULL,
  [CORR_NIVEL_ACADEMICO] [int] NULL,
  [CORR_TIPO_PUESTO] [int] NULL,
  [ESTADO_PUESTO] [bit] NULL,
  [APROBACION_PUESTO] [bit] NULL,
  [SALARIO_INICIAL] [decimal](12, 2) NULL,
  [SALARIO_FINAL] [decimal](12, 2) NULL,
  [USUARIO_VALIDA] [varchar](30) NULL,
  [USUARIO_AUTORIZA] [varchar](30) NULL,
  [MISION_PUESTO] [varchar](255) NULL,
  [OTROS_ASPECTOS] [varchar](255) NULL,
  [CODIGO_PUESTO] [varchar](30) NULL,
  [CODIGO_FORMATO] [varchar](30) NULL,
  [VERSION_FORMATO] [varchar](30) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_PLA_PUESTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_PUESTO])
)
ON [PRIMARY]
GO
