CREATE TABLE [dbo].[CON_CATALOGO_SALDO_FORANEA]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[MES_PERIODO] [int] NOT NULL,
[CUENTA_CONTABLE] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CORR_CENTRO_COSTO] [int] NOT NULL,
[SALDO_INICIAL] [decimal] (12, 2) NULL,
[CARGO_PERIODO] [decimal] (12, 2) NULL,
[ABONO_PERIODO] [decimal] (12, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CATALOGO_SALDO_FORANEA] ADD CONSTRAINT [PK_CON_CATALOGO_SALDO_FORANEA] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CUENTA_CONTABLE], [CORR_CENTRO_COSTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CATALOGO_SALDO_FORANEA] ADD CONSTRAINT [FK_CON_CATALOGO_SALDO_FORANEA_CON_CATALOGO_CUENTA] FOREIGN KEY ([CORR_EMPRESA], [CUENTA_CONTABLE]) REFERENCES [dbo].[CON_CATALOGO_CUENTA] ([CORR_EMPRESA], [CUENTA_CONTABLE])
GO
