CREATE TABLE [dbo].[BAN_CHEQUERA]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CUENTA_BANCO] [int] NOT NULL,
[CORR_CHEQUERA] [int] NOT NULL,
[NUMERO_CHEQUE_INICIAL] [int] NOT NULL,
[NUMERO_CHEQUE_FINAL] [int] NOT NULL,
[NUMERO_CHEQUE_ACTUAL] [int] NOT NULL,
[SERIE_CHEQUE] [varchar] (10) COLLATE Latin1_General_CS_AS NOT NULL,
[ESTADO_CHEQUERA] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_CHEQUERA] ADD CONSTRAINT [PK_BAN_CHEQUERA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CHEQUERA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_CHEQUERA] ADD CONSTRAINT [FK_BAN_CHEQUERA_BAN_CUENTA_BANCARIA] FOREIGN KEY ([CORR_EMPRESA], [CORR_CUENTA_BANCO]) REFERENCES [dbo].[BAN_CUENTA_BANCARIA] ([CORR_EMPRESA], [CORR_CUENTA_BANCO])
GO
