CREATE TABLE [dbo].[COM_CONDICION_PAGO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CONDICION_PAGO] [int] NOT NULL,
[NOMBRE_CONDICION_PAGO] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[DIAS_CREDITO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_CONDICION_PAGO] ADD CONSTRAINT [PK_GEN_CONDICION_PAGO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CONDICION_PAGO]) ON [PRIMARY]
GO
