CREATE TABLE [dbo].[GEN_DIVISION]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_DIVISION] [int] NOT NULL,
[NOMBRE_DIVISION] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_DIVISION] [varchar] (3) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_DIVISION] ADD CONSTRAINT [PK_CON_DIVISION] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [CORR_DIVISION]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_DIVISION] ADD CONSTRAINT [UK_CON_DIVISION] UNIQUE NONCLUSTERED  ([CORR_EMPRESA], [CODIGO_DIVISION]) ON [PRIMARY]
GO
