CREATE TABLE [dbo].[GEN_RUBRO_IMPUESTO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_RUBRO] [int] NOT NULL,
[CORR_IMPUESTO] [int] NOT NULL,
[IMPUESTO_INCLUIDO] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_RUBRO_IMPUESTO] ADD CONSTRAINT [PK_VEN_RUBRO_IMPUESTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_RUBRO], [CORR_IMPUESTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_RUBRO_IMPUESTO] ADD CONSTRAINT [FK_GEN_RUBRO_IMPUESTO_GEN_RUBRO] FOREIGN KEY ([CORR_EMPRESA], [CORR_RUBRO]) REFERENCES [dbo].[GEN_RUBRO] ([CORR_EMPRESA], [CORR_RUBRO])
GO
