CREATE TABLE [dbo].[SC_PERFIL_PUESTO_EDUCACION] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_PERFIL_PUESTO] [int] NOT NULL,
  [CORR_EDUCACION] [int] NOT NULL,
  [REQUISITO] [varchar](255) NULL,
  [ESPECIFICACIONES] [varchar](255) NULL,
  [TIPO_REQUERIDO] [varchar](25) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_PERFIL_PUESTO_EDUCACION] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_PERFIL_PUESTO],
    [CORR_EDUCACION]
  ),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_EDUCACION_SC_PERFIL_PUESTO] FOREIGN KEY (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_PERFIL_PUESTO]
  ) REFERENCES [dbo].[SC_PERFIL_PUESTO] (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_PERFIL_PUESTO]
  ),
  CONSTRAINT [CK_SC_PERFIL_PUESTO_EDUCACION_TIPO_REQUERIDO] CHECK (
    [TIPO_REQUERIDO] IN ('SI', 'NO', 'DESEABLE')
  )
)
ON [PRIMARY]
GO
