CREATE TABLE [dbo].[SC_DESCRIPTOR_RIESGO_PUESTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_RIESGO_PUESTO] [int] NOT NULL,
  [NOMBRE_RIESGO_PUESTO] [varchar](150) NULL,
  [ESTADO_RIESGO_PUESTO] [bit] NULL,
  [USUARIO_CREA] [varchar](30) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](30) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_RIESGO_PUESTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_RIESGO_PUESTO])
)
ON [PRIMARY]
GO
