CREATE TABLE [dbo].[SEG_TIPO_USUARIO_OPCION]
(
[TIPO_USUARIO] [int] NOT NULL,
[CODIGO_SISTEMA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_MENU] [varchar] (10) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_OPCION] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[NUEVO] [bit] NOT NULL,
[MODIFICAR] [bit] NOT NULL,
[ELIMINAR] [bit] NOT NULL,
[IMPRIMIR] [bit] NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_ACTU] [datetime] NOT NULL,
[ESTACION_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_TIPO_USUARIO_OPCION] ADD CONSTRAINT [PK_SEG_TIPO_USUARIO_OPCION] PRIMARY KEY CLUSTERED ([TIPO_USUARIO], [CODIGO_SISTEMA], [CODIGO_MENU], [CODIGO_OPCION]) ON [PRIMARY]
GO
