CREATE TABLE [dbo].[BAN_TIPO_MOVI_SEGUN_BANCO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_TIPO_MOVIMIENTO] [int] NOT NULL,
[CORR_BANCO] [int] NOT NULL,
[CODIGO_MOVIMIENTO] [varchar] (10) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_MOVIMIENTO_SEGUN_BANCO] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_TIPO_MOVI_SEGUN_BANCO] ADD CONSTRAINT [PK_BAN_TIPO_MOVI_SEGUN_BANCO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_MOVIMIENTO], [CORR_BANCO], [CODIGO_MOVIMIENTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_TIPO_MOVI_SEGUN_BANCO] ADD CONSTRAINT [FK_BAN_TIPO_MOVI_SEGUN_BANCO_BAN_TIPO_MOVI_BANCARIO] FOREIGN KEY ([CORR_EMPRESA], [CORR_TIPO_MOVIMIENTO]) REFERENCES [dbo].[BAN_TIPO_MOVI_BANCARIO] ([CORR_EMPRESA], [CORR_TIPO_MOVIMIENTO])
GO
ALTER TABLE [dbo].[BAN_TIPO_MOVI_SEGUN_BANCO] ADD CONSTRAINT [FK_BAN_TIPO_MOVI_SEGUN_BANCO_GEN_BANCO] FOREIGN KEY ([CORR_EMPRESA], [CORR_BANCO]) REFERENCES [dbo].[GEN_BANCO] ([CORR_EMPRESA], [CORR_BANCO])
GO
