CREATE TABLE [dbo].[CON_CATALOGO_SALDO_HIS_CC] (
  [CORR_EMPRESA] [int] NOT NULL,
  [ANIO_PERIODO] [int] NOT NULL,
  [CUENTA_CONTABLE] [varchar](30) NOT NULL,
  [CORR_CENTRO_COSTO] [int] NOT NULL,
  [SALDO_INICIAL1] [decimal](12, 2) NOT NULL,
  [SALDO_INICIAL2] [decimal](12, 2) NOT NULL,
  [SALDO_INICIAL3] [decimal](12, 2) NOT NULL,
  [SALDO_INICIAL4] [decimal](12, 2) NOT NULL,
  [SALDO_INICIAL5] [decimal](12, 2) NOT NULL,
  [SALDO_INICIAL6] [decimal](12, 2) NOT NULL,
  [SALDO_INICIAL7] [decimal](12, 2) NOT NULL,
  [SALDO_INICIAL8] [decimal](12, 2) NOT NULL,
  [SALDO_INICIAL9] [decimal](12, 2) NOT NULL,
  [SALDO_INICIAL10] [decimal](12, 2) NOT NULL,
  [SALDO_INICIAL11] [decimal](12, 2) NOT NULL,
  [SALDO_INICIAL12] [decimal](12, 2) NOT NULL,
  [SALDO_FINAL12] [decimal](12, 2) NOT NULL,
  [CARGO_PERIODO] [decimal](12, 2) NOT NULL,
  [ABONO_PERIODO] [decimal](12, 2) NOT NULL,
  CONSTRAINT [PK_CON_CATALOGO_SALDO_HIS_CC] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CUENTA_CONTABLE], [CORR_CENTRO_COSTO])
)
ON [PRIMARY]
GO