CREATE TABLE [dbo].[CON_CATALOGO_SALDO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [ANIO_PERIODO] [int] NOT NULL,
  [MES_PERIODO] [int] NOT NULL,
  [CUENTA_CONTABLE] [varchar](30) NOT NULL,
  [CORR_CENTRO_COSTO] [int] NOT NULL,
  [SALDO_INICIAL] [decimal](12, 2) NULL,
  [CARGO_PERIODO] [decimal](12, 2) NULL,
  [ABONO_PERIODO] [decimal](12, 2) NULL,
  CONSTRAINT [PK_CON_CATALOGO_SALDO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CUENTA_CONTABLE], [CORR_CENTRO_COSTO])
)
ON [PRIMARY]
GO