CREATE TABLE [dbo].[SC_DESCRIPTOR_PUESTO_RIESGO_PUESTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_RIESGO] [int] NOT NULL,
  [NOMBRE_RIESGO_PUESTO] [varchar](150) NULL,
  [INFORMACION] [varchar](255) NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NULL,
  [CORR_RIESGO_PUESTO] [int] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_PUESTO_RIESGO_PUESTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DESCRIPTOR_RIESGO]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_RIESGO_PUESTO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA])
    REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_RIESGO_PUESTO_SC_DESCRIPTOR_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO])
    REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_RIESGO_PUESTO_SC_RIESGO_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_RIESGO_PUESTO])
    REFERENCES [dbo].[SC_RIESGO_PUESTO] ([CORR_EMPRESA], [CORR_RIESGO_PUESTO])
)
ON [PRIMARY]
GO
