CREATE TABLE [dbo].[PLA_TIPO_DOCUMENTO_ADJUNTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_TIPO_DOCUMENTO_ADJUNTO] [int] NOT NULL,
  [TIPO_DOCUMENTO] [varchar](250) NULL,
  [DESCRIPCION_DOCUMENTO] [varchar](500) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_PLA_TIPO_DOCUMENTO_ADJUNTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_DOCUMENTO_ADJUNTO])
)
ON [PRIMARY]
GO
