CREATE TABLE [dbo].[SC_REQUERIMIENTO_ORGANIZACIONAL] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_REQUERIMIENTO_ORGANIZACIONAL] [int] NOT NULL,
  [DESCRIPCION] [varchar](200) NULL,
  [ESTADO_REQUERIMIENTO_ORGANIZACIONAL] [bit] NULL,
  [USUARIO_CREA] [varchar](30) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](30) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_REQUERIMIENTO_ORGANIZACIONAL] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_REQUERIMIENTO_ORGANIZACIONAL])
)
ON [PRIMARY]
GO
