CREATE TABLE [dbo].[SEG_CONFIG_OPCION]
(
[CODIGO_SISTEMA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_MENU] [varchar] (10) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_OPCION] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[ORDEN_SISTEMA] [int] NOT NULL,
[ORDEN_MENU] [int] NOT NULL,
[ORDEN_OPCION] [int] NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_CONFIG_OPCION] ADD CONSTRAINT [PK_SEG_CONFIG_OPCION] PRIMARY KEY CLUSTERED ([CODIGO_SISTEMA], [CODIGO_MENU], [CODIGO_OPCION]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_CONFIG_OPCION] ADD CONSTRAINT [FK_SEG_CONFIG_OPCION_SEG_MENU_SISTEMA] FOREIGN KEY ([CODIGO_MENU]) REFERENCES [dbo].[SEG_MENU_SISTEMA] ([CODIGO_MENU])
GO
ALTER TABLE [dbo].[SEG_CONFIG_OPCION] ADD CONSTRAINT [FK_SEG_CONFIG_OPCION_SEG_OPCION_SISTEMA] FOREIGN KEY ([CODIGO_OPCION]) REFERENCES [dbo].[SEG_OPCION_SISTEMA] ([CODIGO_OPCION])
GO
ALTER TABLE [dbo].[SEG_CONFIG_OPCION] ADD CONSTRAINT [FK_SEG_CONFIG_OPCION_SEG_SISTEMA] FOREIGN KEY ([CODIGO_SISTEMA]) REFERENCES [dbo].[SEG_SISTEMA] ([CODIGO_SISTEMA])
GO
