CREATE TABLE [dbo].[SC_DESCRIPTOR_PUESTO_REQUERIMIENTO_ORGANIZACIONAL] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_REQUERIMIENTO_ORGANIZACIONAL] [int] NOT NULL,
  [DESCRIPCION] [varchar](150) NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NULL,
  [CORR_REQUERIMIENTO_ORGANIZACIONAL] [int] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_PUESTO_REQUERIMIENTO_ORGANIZACIONAL] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DESCRIPTOR_REQUERIMIENTO_ORGANIZACIONAL]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_REQUERIMIENTO_ORGANIZACIONAL_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA])
    REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_REQUERIMIENTO_ORGANIZACIONAL_SC_DESCRIPTOR_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO])
    REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_REQUERIMIENTO_ORGANIZACIONAL_SC_REQUERIMIENTO_ORGANIZACIONAL] FOREIGN KEY ([CORR_EMPRESA], [CORR_REQUERIMIENTO_ORGANIZACIONAL])
    REFERENCES [dbo].[SC_REQUERIMIENTO_ORGANIZACIONAL] ([CORR_EMPRESA], [CORR_REQUERIMIENTO_ORGANIZACIONAL])
)
ON [PRIMARY]
GO
