CREATE TABLE [dbo].[COM_CUADRO_COMPARATIVO_DETA]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_CUADRO_COMPARATIVO] [int] NOT NULL,
[ANIO_PERIODO_COTIZACION] [int] NOT NULL,
[CORR_COTIZACION] [int] NOT NULL,
[CORR_COTIZACION_DETA] [int] NOT NULL,
[SELECCION] [bit] NULL,
[OBSERVACIONES] [varchar] (1000) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_CUADRO_COMPARATIVO_DETA] ADD CONSTRAINT [PK_COM_CUADRO_COMPARATIVO_DETA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_CUADRO_COMPARATIVO], [ANIO_PERIODO_COTIZACION], [CORR_COTIZACION], [CORR_COTIZACION_DETA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_CUADRO_COMPARATIVO_DETA] ADD CONSTRAINT [FK_COM_CUADRO_COMPARATIVO_DETA_COM_COTIZACION_DETA] FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO_COTIZACION], [CORR_COTIZACION], [CORR_COTIZACION_DETA]) REFERENCES [dbo].[COM_COTIZACION_DETA] ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_COTIZACION], [CORR_COTIZACION_DETA])
GO
ALTER TABLE [dbo].[COM_CUADRO_COMPARATIVO_DETA] ADD CONSTRAINT [FK_COM_CUADRO_COMPARATIVO_DETA_COM_CUADRO_COMPARATIVO] FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_CUADRO_COMPARATIVO]) REFERENCES [dbo].[COM_CUADRO_COMPARATIVO] ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_CUADRO_COMPARATIVO])
GO
