CREATE TABLE [dbo].[SC_INDUCCION] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_INDUCCION] [int] NOT NULL,
  [NOMBRE_INDUCCION] [varchar](200) NULL,
  [SEMANAS_INDUCCION] [int] NULL,
  [ESTADO_INDUCCION] [bit] NULL,
  [USUARIO_CREA] [varchar](30) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](30) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_INDUCCION] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_INDUCCION])
)
ON [PRIMARY]
GO
