CREATE TABLE [dbo].[BAN_CONCILIA_BANCARIA_DETA]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CUENTA_BANCO] [int] NOT NULL,
[CORR_CONCILIACION] [int] NOT NULL,
[CORR_CONCILIACION_DETA] [int] NOT NULL,
[FECHA_MOVIMIENTO] [date] NOT NULL,
[CORR_TIPO_MOVIMIENTO] [int] NOT NULL,
[NUMERO_REFERENCIA_BANCO] [varchar] (255) COLLATE Latin1_General_CS_AS NOT NULL,
[MONTO_CARGO] [decimal] (18, 2) NOT NULL,
[MONTO_ABONO] [decimal] (18, 2) NOT NULL,
[ANIO_PERIODO] [int] NULL,
[MES_PERIODO] [int] NULL,
[CORR_CLASE_PARTIDA] [int] NULL,
[CORR_PARTIDA] [int] NULL,
[CORR_PARTIDA_DETA] [int] NULL,
[CODIGO_TRANSACCION] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[DESCRIPCION_TRANSACCION] [varchar] (255) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA_DETA] ADD CONSTRAINT [PK_BAN_CONCILIA_BANCARIA_DETA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION], [CORR_CONCILIACION_DETA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_BAN_CONCILIA_BANCARIA_DETA_PARTIDA] ON [dbo].[BAN_CONCILIA_BANCARIA_DETA] ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_CLASE_PARTIDA], [CORR_PARTIDA], [CORR_PARTIDA_DETA]) INCLUDE ([CORR_CUENTA_BANCO], [CORR_CONCILIACION]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA_DETA] ADD CONSTRAINT [FK_BAN_CONCILIA_BANCARIA_DETA_BAN_CONCILIA_BANCARIA] FOREIGN KEY ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION]) REFERENCES [dbo].[BAN_CONCILIA_BANCARIA] ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION])
GO
