CREATE TABLE [dbo].[CON_CENTRO_COSTO_PRESUPUESTO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CENTRO_COSTO] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[MES_PERIODO] [int] NOT NULL,
[MONTO_PRESUPUESTO] [decimal] (12, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CENTRO_COSTO_PRESUPUESTO] ADD CONSTRAINT [PK_CON_CENTRO_COSTO_PRESUPUESTO] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [CORR_CENTRO_COSTO], [ANIO_PERIODO], [MES_PERIODO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CENTRO_COSTO_PRESUPUESTO] ADD CONSTRAINT [FK_CON_CENTRO_COSTO_PRESUPUESTO_CON_CENTRO_COSTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_CENTRO_COSTO]) REFERENCES [dbo].[CON_CENTRO_COSTO] ([CORR_EMPRESA], [CORR_CENTRO_COSTO])
GO
