CREATE TABLE [dbo].[SEG_TIPO_USUARIO]
(
[TIPO_USUARIO] [int] NOT NULL,
[NOMBRE_TIPO_USUARIO] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_ACTU] [datetime] NOT NULL,
[ESTACION_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_TIPO_USUARIO] ADD CONSTRAINT [PK_SEG_TIPO_USUARIO] PRIMARY KEY CLUSTERED ([TIPO_USUARIO]) ON [PRIMARY]
GO
