CREATE TABLE [dbo].[SEG_USUARIO_OPCION]
(
[LOGIN_SISTEMA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_SISTEMA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_MENU] [varchar] (10) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_OPCION] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[NUEVO] [bit] NOT NULL,
[MODIFICAR] [bit] NOT NULL,
[ELIMINAR] [bit] NOT NULL,
[IMPRIMIR] [bit] NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_USUARIO_OPCION] ADD CONSTRAINT [PK_SEG_USUARIO_OPCION] PRIMARY KEY CLUSTERED ([LOGIN_SISTEMA], [CODIGO_SISTEMA], [CODIGO_MENU], [CODIGO_OPCION]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_USUARIO_OPCION] ADD CONSTRAINT [FK_SEG_USUARIO_OPCION_SEG_CONFIG_OPCION] FOREIGN KEY ([CODIGO_SISTEMA], [CODIGO_MENU], [CODIGO_OPCION]) REFERENCES [dbo].[SEG_CONFIG_OPCION] ([CODIGO_SISTEMA], [CODIGO_MENU], [CODIGO_OPCION])
GO
ALTER TABLE [dbo].[SEG_USUARIO_OPCION] ADD CONSTRAINT [FK_SEG_USUARIO_OPCION_SEG_USUARIO] FOREIGN KEY ([LOGIN_SISTEMA]) REFERENCES [dbo].[SEG_USUARIO] ([LOGIN_SISTEMA])
GO
