CREATE TABLE [dbo].[COM_SOLI_COTIZACION_DETA]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_SOLI_COTIZACION] [int] NOT NULL,
[CORR_SOLI_COTIZACION_DETA] [int] NOT NULL,
[ANIO_PERIODO_SOLI_COMPRA] [int] NULL,
[CORR_SOLI_COMPRA] [int] NULL,
[CODIGO_ITEM] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CANTIDAD] [decimal] (18, 2) NOT NULL,
[CORR_UNIDAD_MEDIDA] [int] NOT NULL,
[OBSERVACIONES] [varchar] (1000) COLLATE Latin1_General_CS_AS NOT NULL,
[ESTADO_SOLI_COTIZACION] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[PRECIO_UNITARIO] [decimal] (18, 6) NULL,
[MONTO_SUBTOTAL] [decimal] (18, 6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_SOLI_COTIZACION_DETA] ADD CONSTRAINT [PK_COM_SOLI_COTIZACION_DETA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_SOLI_COTIZACION], [CORR_SOLI_COTIZACION_DETA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_SOLI_COTIZACION_DETA] ADD CONSTRAINT [FK_COM_SOLI_COTIZACION_DETA_COM_SOLI_COTIZACION] FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_SOLI_COTIZACION]) REFERENCES [dbo].[COM_SOLI_COTIZACION] ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_SOLI_COTIZACION])
GO
