CREATE TABLE [dbo].[SC_DESCRIPTOR_PUESTO_EMPLEADO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_EMPLEADO] [int] NOT NULL,
  [FECHA_INGRESO] [date] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_PUESTO_EMPLEADO] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA] ASC,
    [CORR_DESCRIPTOR_PUESTO] ASC,
    [CORR_EMPLEADO] ASC
  )
);
-- Sin CHECK.
-- Sin defaults.
ALTER TABLE [dbo].[SC_DESCRIPTOR_PUESTO_EMPLEADO] ADD CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_EMPLEADO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]);
ALTER TABLE [dbo].[SC_DESCRIPTOR_PUESTO_EMPLEADO] ADD CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_EMPLEADO_SC_DESCRIPTOR_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO]) REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO]);
ALTER TABLE [dbo].[SC_DESCRIPTOR_PUESTO_EMPLEADO] ADD CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_EMPLEADO_GEN_EMPLEADO] FOREIGN KEY ([CORR_EMPRESA], [CORR_EMPLEADO]) REFERENCES [dbo].[GEN_EMPLEADO] ([CORR_EMPRESA], [CORR_EMPLEADO]);
-- Sin índices adicionales.
-- Sin triggers.
GO
