CREATE TABLE [dbo].[CON_PARTIDA]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[MES_PERIODO] [int] NOT NULL,
[CORR_CLASE_PARTIDA] [int] NOT NULL,
[CORR_PARTIDA] [int] NOT NULL,
[FECHA_PARTIDA] [date] NOT NULL,
[NUMERO_DOCUMENTO] [varchar] (25) COLLATE Latin1_General_CS_AS NULL,
[NOMBRE_PARTIDA] [varchar] (1000) COLLATE Latin1_General_CS_AS NULL,
[ESTADO_PARTIDA] [varchar] (2) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL,
[CLASE_PARTIDA] [varchar] (3) COLLATE Latin1_General_CS_AS NULL CONSTRAINT [DF_CON_PARTIDA_CLASE_PARTIDA] DEFAULT ('NOR'),
[CORR_MONEDA] [int] NULL,
[FACTOR_CAMBIO] [decimal] (16, 6) NULL,
[OPERADOR] [varchar] (2) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA] ADD CONSTRAINT [PK_CON_PARTIDA_ENCA] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_CLASE_PARTIDA], [CORR_PARTIDA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA] ADD CONSTRAINT [FK_CON_PARTIDA_CON_PERIODO_CONTABLE] FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO]) REFERENCES [dbo].[CON_PERIODO_CONTABLE] ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO])
GO
ALTER TABLE [dbo].[CON_PARTIDA] ADD CONSTRAINT [FK_CON_PARTIDA_CON_CLASE_PARTIDA] FOREIGN KEY ([CORR_EMPRESA], [CORR_CLASE_PARTIDA]) REFERENCES [dbo].[CON_CLASE_PARTIDA] ([CORR_EMPRESA], [CORR_CLASE_PARTIDA])
GO
