CREATE TABLE [dbo].[SEG_USUARIO_FOTO]
(
[LOGIN_SISTEMA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CLASE_FOTO] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL,
[FOTO] [image] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_USUARIO_FOTO] ADD CONSTRAINT [PK_SEG_USUARIO_FOTO] PRIMARY KEY CLUSTERED ([LOGIN_SISTEMA], [CLASE_FOTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_USUARIO_FOTO] ADD CONSTRAINT [FK_SEG_USUARIO_FOTO_SEG_USUARIO] FOREIGN KEY ([LOGIN_SISTEMA]) REFERENCES [dbo].[SEG_USUARIO] ([LOGIN_SISTEMA])
GO
