CREATE TABLE [dbo].[CON_PERIODO_CONTABLE] (
  [CORR_EMPRESA] [int] NOT NULL,
  [ANIO_PERIODO] [int] NOT NULL,
  [MES_PERIODO] [int] NOT NULL,
  [ESTADO_PERIODO_CON] [varchar](2) NOT NULL,
  [ESTADO_PERIODO_BAN] [varchar](2) NULL,
  [ESTADO_PERIODO_VEN] [varchar](2) NULL,
  [ESTADO_PERIODO_ACT] [varchar](2) NULL,
  [ESTADO_PERIODO_INV] [varchar](2) NULL,
  [ESTADO_PERIODO_PLA] [varchar](2) NULL,
  [ESTADO_PERIODO_COM] [varchar](2) NULL,
  [FECHA_CIERRE_CON] [date] NULL,
  [FECHA_CIERRE_BAN] [date] NULL,
  [FECHA_CIERRE_VEN] [date] NULL,
  [FECHA_CIERRE_ACT] [date] NULL,
  [FECHA_CIERRE_INV] [date] NULL,
  [FECHA_CIERRE_PLA] [date] NULL,
  [FECHA_CIERRE_COM] [date] NULL,
  CONSTRAINT [PK_CON_PERIODO_CONTABLE] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO])
)
ON [PRIMARY]
GO