CREATE TABLE [dbo].[GEN_EMPRESA]
(
[CORR_EMPRESA] [int] NOT NULL,
[NOMBRE_EMPRESA] [varchar] (100) COLLATE Latin1_General_CS_AS NULL,
[LOGO_1] [image] NULL,
[LOGO_2] [image] NULL,
[TAMANIO_EMPRESA] [varchar] (2) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_EMPRESA] ADD CONSTRAINT [PK_GEN_EMPRESA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA]) ON [PRIMARY]
GO
