CREATE TABLE [dbo].[PLA_DEPARTAMENTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DEPARTAMENTO] [int] NOT NULL,
  [NOMBRE_DEPARTAMENTO] [varchar](150) NOT NULL,
  [CORR_CENTRO_COSTO] [int] NULL,
  [CODIGO_DEPARTAMENTO] [varchar](15) NULL,
  [CLASE_DEPARTAMENTO] [varchar](2) NULL,
  [CORR_EMPLEADO_JEFE] [int] NULL,
  CONSTRAINT [PK_PLA_DEPARTAMENTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DEPARTAMENTO])
)
ON [PRIMARY]
GO