CREATE TABLE [dbo].[CON_CENTRO_COSTO_CONFIG_REVISION]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CENTRO_COSTO] [int] NOT NULL,
[LOGIN_SISTEMA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[ORDEN_REVISION] [int] NULL,
[PERMITE_APLICAR] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CENTRO_COSTO_CONFIG_REVISION] ADD CONSTRAINT [PK_CON_CENTRO_COSTO_CONFIG_REVISION] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [CORR_CENTRO_COSTO], [LOGIN_SISTEMA]) ON [PRIMARY]
GO
