CREATE TABLE [dbo].[SEG_SISTEMA]
(
[CODIGO_SISTEMA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_SISTEMA] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[IMAGEN_SISTEMA] [varchar] (25) COLLATE Latin1_General_CS_AS NULL,
[PREFIJO] [varchar] (10) COLLATE Latin1_General_CS_AS NULL,
[NOMBRE_MODULO] [varchar] (150) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_SISTEMA] ADD CONSTRAINT [PK_SEG_SISTEMA] PRIMARY KEY CLUSTERED ([CODIGO_SISTEMA]) ON [PRIMARY]
GO
