-- Qué hace: script de documentación de GEN_PERSONA_PARENTESCO_CONTACTO (ya existente en BD).
-- Cómo lo hace: refleja columnas, PK, defaults, FK e índices consultados en SQL Server (sin crear/alterar la tabla).
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
Tabla: dbo.GEN_PERSONA_PARENTESCO_CONTACTO
Fuente: estructura leída desde SGUEES (solo documentación; no ejecutar CREATE TABLE en producción).
Sin CHECK. Sin índices adicionales. Sin columnas calculadas. Sin triggers.
*/
CREATE TABLE [dbo].[GEN_PERSONA_PARENTESCO_CONTACTO]
(
	[CORR_EMPRESA] [int] NOT NULL,
	[CORR_PERSONA] [bigint] NOT NULL,
	[CORR_PARENTESCO_CONTACTO] [int] NOT NULL,
	[NOMBRE_COMPLETO] [varchar](100) NULL,
	[CORR_PARENTESCO] [int] NULL,
	[CORR_TIPO_CONTACTO] [int] NULL,
	[VALOR_CONTACTO] [varchar](max) NULL,
	[DIRECCION] [varchar](255) NULL,
	[ES_EXTRANJERO] [bit] NULL,
	[PARENTESCO_CONTACTO_EMERGENCIA] [bit] NULL,
	[ACTIVO_PARENTESCO_CONTACTO] [bit] NULL,
	[USUARIO_CREA] [varchar](50) NULL,
	[ESTACION_CREA] [varchar](50) NULL,
	[FECHA_CREA] [datetime] NULL,
	[USUARIO_ACTU] [varchar](50) NULL,
	[ESTACION_ACTU] [varchar](50) NULL,
	[FECHA_ACTU] [datetime] NULL,
	CONSTRAINT [PK_GEN_PERSONA_PARENTESCO_CONTACTO] PRIMARY KEY CLUSTERED
	(
		[CORR_EMPRESA] ASC,
		[CORR_PERSONA] ASC,
		[CORR_PARENTESCO_CONTACTO] ASC
	)
);
GO

-- ES_EXTRANJERO: sin default.
ALTER TABLE [dbo].[GEN_PERSONA_PARENTESCO_CONTACTO] ADD CONSTRAINT [DF__GEN_PERSO__PAREN__71A9618D] DEFAULT ((0)) FOR [PARENTESCO_CONTACTO_EMERGENCIA]
GO

ALTER TABLE [dbo].[GEN_PERSONA_PARENTESCO_CONTACTO] ADD CONSTRAINT [DF__GEN_PERSO__ACTIV__729D85C6] DEFAULT ((1)) FOR [ACTIVO_PARENTESCO_CONTACTO]
GO

ALTER TABLE [dbo].[GEN_PERSONA_PARENTESCO_CONTACTO] ADD CONSTRAINT [FK_GEN_PERSONA_PARENTESCO_CONTACTO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO

ALTER TABLE [dbo].[GEN_PERSONA_PARENTESCO_CONTACTO] ADD CONSTRAINT [FK_GEN_PERSONA_PARENTESCO_CONTACTO_GEN_PERSONA] FOREIGN KEY ([CORR_PERSONA]) REFERENCES [dbo].[GEN_PERSONA] ([CORR_PERSONA])
GO

ALTER TABLE [dbo].[GEN_PERSONA_PARENTESCO_CONTACTO] ADD CONSTRAINT [FK_GEN_PERSONA_PARENTESCO_CONTACTO_GEN_PARENTESCO] FOREIGN KEY ([CORR_PARENTESCO]) REFERENCES [dbo].[GEN_PARENTESCO] ([CORR_PARENTESCO])
GO

ALTER TABLE [dbo].[GEN_PERSONA_PARENTESCO_CONTACTO] ADD CONSTRAINT [FK_GEN_PERSONA_PARENTESCO_CONTACTO_GEN_TIPO_CONTACTO] FOREIGN KEY ([CORR_TIPO_CONTACTO]) REFERENCES [dbo].[GEN_TIPO_CONTACTO] ([CORR_TIPO_CONTACTO])
GO
