CREATE TABLE [dbo].[COM_BANCO]
(
[CORR_BANCO] [int] NOT NULL,
[NOMBRE_BANCO] [varchar] (60) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_BANCO_CORTO] [varchar] (15) COLLATE Latin1_General_CS_AS NULL,
[CLASE_BANCO] [varchar] (5) COLLATE Latin1_General_CS_AS NULL,
[CODIGO_TRANSACION_UNI] [varchar] (5) COLLATE Latin1_General_CS_AS NULL,
[ESTADO_BANCO] [bit] NOT NULL CONSTRAINT [DF_COM_BANCO_ESTADO_BANCO] DEFAULT ((1)),
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_CREA] [datetime] NULL,
[ESTACION_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_BANCO] ADD CONSTRAINT [PK_COM_BANCO] PRIMARY KEY CLUSTERED ([CORR_BANCO]) ON [PRIMARY]
GO
