CREATE TABLE [dbo].[COM_PROVEEDOR_DOC]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_PROVEEDOR] [int] NOT NULL,
[CORR_DOCUMENTO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_PROVEEDOR_DOC] ADD CONSTRAINT [PK_COM_PROVEEDOR_DOC] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_PROVEEDOR], [CORR_DOCUMENTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_PROVEEDOR_DOC] ADD CONSTRAINT [FK_COM_PROVEEDOR_DOC_COM_DOCUMENTO_FISICO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DOCUMENTO]) REFERENCES [dbo].[COM_DOCUMENTO_FISICO] ([CORR_EMPRESA], [CORR_DOCUMENTO])
GO
ALTER TABLE [dbo].[COM_PROVEEDOR_DOC] ADD CONSTRAINT [FK_COM_PROVEEDOR_DOC_COM_PROVEEDOR] FOREIGN KEY ([CORR_PROVEEDOR]) REFERENCES [dbo].[COM_PROVEEDOR] ([CORR_PROVEEDOR])
GO
