CREATE TABLE [dbo].[CON_RUBRO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CODIGO_RUBRO] [varchar](30) NOT NULL,
  [NOMBRE_RUBRO] [varchar](100) NOT NULL,
  [ES_DEBE] [bit] NOT NULL,
  [ES_HABER] [bit] NOT NULL,
  [CLASE_RUBRO] [varchar](2) NULL,
  CONSTRAINT [PK_CON_RUBRO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CODIGO_RUBRO])
)
ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE TRIGGER [ti_CON_RUBRO] ON [dbo].[CON_RUBRO] 
FOR INSERT
AS
	DECLARE
	@numrows  int,
	@numnull  int,
	@errno    int,
	@errmsg   varchar(255),
	@CORR_EMPRESA int,
	@CODIGO_RUBRO varchar(30),
	@NOMBRE_RUBRO varchar(100),
	@TAMANO_CUENTA int,
	@ES_DEBE bit,
	@ES_HABER bit
BEGIN
	SELECT  @numrows = @@rowcount
	IF @numrows = 0
	RETURN

	IF @numrows > 1
	BEGIN
		SELECT @errno  = 30001,
		@errmsg = 'No se Puede Actualizar Mas de un Registro a la Vez'
		GOTO ERROR
	END

	SELECT @CORR_EMPRESA=CORR_EMPRESA,
	@CODIGO_RUBRO=CODIGO_RUBRO,
	@NOMBRE_RUBRO=NOMBRE_RUBRO,
	@TAMANO_CUENTA=DATALENGTH(CODIGO_RUBRO),
	@ES_DEBE=ES_DEBE,
	@ES_HABER=ES_HABER
	FROM inserted

	IF (SELECT COUNT(1) FROM CON_RUBRO 
				WHERE SUBSTRING(CODIGO_RUBRO,1,1)=SUBSTRING(@CODIGO_RUBRO,1,1) 
				AND CORR_EMPRESA=@CORR_EMPRESA)>1
	BEGIN
		SELECT @errno  = 30001,
		@errmsg = 'Rubro Invalido. Verifique'
		GOTO ERROR
	END

	INSERT INTO CON_RUBRO_NIVEL
	(CORR_EMPRESA,CODIGO_RUBRO,NIVEL,NUMERO_CARACTERES)
	VALUES(@CORR_EMPRESA,@CODIGO_RUBRO,1,@TAMANO_CUENTA)

	INSERT INTO CON_CATALOGO_CUENTA
	(CORR_EMPRESA,CUENTA_CONTABLE,NOMBRE_CUENTA,ES_DEBE,ES_HABER,ES_DETALLE,NIVEL,CUENTA_MAYOR,CODIGO_RUBRO,NO_HABILITADA)
	VALUES(@CORR_EMPRESA,@CODIGO_RUBRO,@NOMBRE_RUBRO,@ES_DEBE,@ES_HABER,0,1,NULL,@CODIGO_RUBRO,0)

RETURN

/*  Errors handling  */

ERROR:
	RAISERROR (@errmsg, 16, 1)
	ROLLBACK TRANSACTION
END
GO