CREATE TABLE [dbo].[CON_CATALOGO_CUENTA_CENTRO_COSTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CUENTA_CONTABLE] [varchar](30) NOT NULL,
  [CORR_CENTRO_COSTO] [int] NOT NULL,
  CONSTRAINT [PK_CON_CATALOGO_CUENTA_CENTRO_COSTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CUENTA_CONTABLE], [CORR_CENTRO_COSTO])
)
ON [PRIMARY]
GO