CREATE TABLE [dbo].[SEG_PARAMETRO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CANTIDA_MESES_EXPIRA_CONTRASEÑA] [int] NULL,
  CONSTRAINT [PK_SEG_PARAMETRO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA])
)
ON [PRIMARY]
GO