CREATE TABLE [dbo].[GEN_TIPO_GASTO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_TIPO_GASTO] [int] NOT NULL,
[NOMBRE_TIPO_GASTO] [varchar] (150) COLLATE Latin1_General_CS_AS NOT NULL,
[ES_SERVICIO] [bit] NOT NULL,
[ES_INTANGIBLE] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_TIPO_GASTO] ADD CONSTRAINT [PK_GEN_TIPO_GASTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_GASTO]) ON [PRIMARY]
GO
