CREATE TABLE [dbo].[CON_PARTIDA_DETA_MODELO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CLASE_PARTIDA] [int] NOT NULL,
[CORR_PARTIDA] [int] NOT NULL,
[CORR_PARTIDA_DETA] [int] NOT NULL,
[CUENTA_CONTABLE] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CORR_CENTRO_COSTO] [int] NULL,
[NOMBRE_TRAN] [varchar] (1255) COLLATE Latin1_General_CS_AS NOT NULL,
[MONTO_CARGO] [decimal] (12, 2) NOT NULL,
[MONTO_ABONO] [decimal] (12, 2) NOT NULL,
[ESTA_CONCILIA] [bit] NULL,
[CORR_AUXILIAR] [int] NULL,
[MONTO_CARGO_FORANEA] [decimal] (12, 2) NULL,
[MONTO_ABONO_FORANEA] [decimal] (12, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA_DETA_MODELO] ADD CONSTRAINT [PK_CON_PARTIDA_DETA_MODELO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CLASE_PARTIDA], [CORR_PARTIDA], [CORR_PARTIDA_DETA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA_DETA_MODELO] ADD CONSTRAINT [FK_CON_PARTIDA_DETA_MODELO_CON_PARTIDA_MODELO] FOREIGN KEY ([CORR_EMPRESA], [CORR_CLASE_PARTIDA], [CORR_PARTIDA]) REFERENCES [dbo].[CON_PARTIDA_MODELO] ([CORR_EMPRESA], [CORR_CLASE_PARTIDA], [CORR_PARTIDA])
GO
ALTER TABLE [dbo].[CON_PARTIDA_DETA_MODELO] ADD CONSTRAINT [FK_CON_PARTIDA_DETA_MODELO_CON_CATALOGO_CUENTA] FOREIGN KEY ([CORR_EMPRESA], [CUENTA_CONTABLE]) REFERENCES [dbo].[CON_CATALOGO_CUENTA] ([CORR_EMPRESA], [CUENTA_CONTABLE])
GO
ALTER TABLE [dbo].[CON_PARTIDA_DETA_MODELO] ADD CONSTRAINT [FK_CON_PARTIDA_DETA_MODELO_CON_CENTRO_COSTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_CENTRO_COSTO]) REFERENCES [dbo].[CON_CENTRO_COSTO] ([CORR_EMPRESA], [CORR_CENTRO_COSTO])
GO
