-- Crear tabla de historial de logins para detectar primer acceso
CREATE TABLE [dbo].[SEG_USUARIO_LOGIN_HISTORIAL]
(
    [CORR_LOGIN] [int] IDENTITY(1,1) NOT NULL,
    [LOGIN_SISTEMA] [varchar](30) COLLATE Latin1_General_CS_AS NOT NULL,
    [FECHA_LOGIN] [datetime] NOT NULL,
    [IP_ADDRESS] [varchar](50) COLLATE Latin1_General_CS_AS NULL,
    [NAVEGADOR] [varchar](255) COLLATE Latin1_General_CS_AS NULL,
    [CODIGO_SUITE] [varchar](20) COLLATE Latin1_General_CS_AS NULL,
    [EXITOSO] [bit] NOT NULL DEFAULT 1,
    [MENSAJE] [varchar](500) COLLATE Latin1_General_CS_AS NULL,
    CONSTRAINT [PK_SEG_USUARIO_LOGIN_HISTORIAL] PRIMARY KEY CLUSTERED ([CORR_LOGIN]),
    CONSTRAINT [FK_SEG_USUARIO_LOGIN_HISTORIAL_SEG_USUARIO] FOREIGN KEY ([LOGIN_SISTEMA]) 
        REFERENCES [dbo].[SEG_USUARIO] ([LOGIN_SISTEMA])
) ON [PRIMARY]
GO

-- Crear índice para búsquedas rápidas por usuario
CREATE NONCLUSTERED INDEX [IX_SEG_USUARIO_LOGIN_HISTORIAL_LOGIN_SISTEMA] 
ON [dbo].[SEG_USUARIO_LOGIN_HISTORIAL] ([LOGIN_SISTEMA], [FECHA_LOGIN] DESC)
GO

PRINT 'Tabla SEG_USUARIO_LOGIN_HISTORIAL creada exitosamente';
