CREATE TABLE [dbo].[COM_BANCO]
(
[CORR_BANCO] [int] NOT NULL,
[NOMBRE_BANCO] [varchar] (60) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_BANCO_CORTO] [varchar] (15) COLLATE Latin1_General_CS_AS NULL,
[CLASE_BANCO] [varchar] (5) COLLATE Latin1_General_CS_AS NULL,
[CODIGO_TRANSACION_UNI] [varchar] (5) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_BANCO] ADD CONSTRAINT [PK_COM_BANCO] PRIMARY KEY CLUSTERED ([CORR_BANCO]) ON [PRIMARY]
GO
