CREATE TABLE [dbo].[SC_COMPETENCIAS_TECNICAS] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_COMPETENCIAS_TECNICAS] [int] NOT NULL,
  [CORR_COMPETENCIAS_TECNICAS_PADRE] [int] NULL,
  [CODIGO_COMPETENCIAS_TECNICAS] [varchar](30) NULL,
  [NOMBRE_COMPETENCIAS_TECNICAS] [varchar](150) NULL,
  [DESCRIPCION] [varchar](500) NULL,
  [NIVEL] [varchar](50) NULL CHECK ([NIVEL] IN ('NIV1', 'NIV2', 'NIV3')),
  [ESTADO_COMPETENCIAS_TECNICAS] [bit] NULL,
  [USUARIO_CREA] [varchar](30) NULL,
  [FECHA_CREA] [datetime] NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [USUARIO_ACTU] [varchar](30) NULL,
  [FECHA_ACTU] [datetime] NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  CONSTRAINT [PK_SC_COMPETENCIAS_TECNICAS] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_COMPETENCIAS_TECNICAS])
)
ON [PRIMARY]
GO
