CREATE TABLE [dbo].[GEN_RUBRO_SUMA]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_RUBRO] [int] NOT NULL,
[CORR_SUMA] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_RUBRO_SUMA] ADD CONSTRAINT [PK_GEN_RUBRO_SUMA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_RUBRO], [CORR_SUMA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_RUBRO_SUMA] ADD CONSTRAINT [FK_GEN_RUBRO_SUMA_GEN_RUBRO] FOREIGN KEY ([CORR_EMPRESA], [CORR_RUBRO]) REFERENCES [dbo].[GEN_RUBRO] ([CORR_EMPRESA], [CORR_RUBRO])
GO
