CREATE TABLE [dbo].[COM_CUADRO_COMPARATIVO_ORDEN_COMPRA]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_CUADRO_COMPARATIVO] [int] NOT NULL,
[NUMERO_ORDEN] [int] NOT NULL,
[CORR_PROVEEDOR] [int] NOT NULL,
[MONTO_TOTAL_ORDEN] [decimal] (18, 6) NULL,
[CORR_CONDICION_PAGO] [int] NULL,
[CORR_FORMA_PAGO] [int] NULL,
[DETALLE_FORMA_PAGO] [varchar] (250) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_CUADRO_COMPARATIVO_ORDEN_COMPRA] ADD CONSTRAINT [PK_COM_CUADRO_COMPARATIVO_ORDEN_COMPRA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_CUADRO_COMPARATIVO], [NUMERO_ORDEN], [CORR_PROVEEDOR]) ON [PRIMARY]
GO
