CREATE TABLE [dbo].[SC_DISPONIBILIDAD_HORARIO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DISPONIBILIDAD_HORARIO] [int] NOT NULL,
  [NOMBRE_DISPONIBILIDAD_HORARIO] [varchar](150) NULL,
  [ESTADO_DISPONIBILIDAD_HORARIO] [bit] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DISPONIBILIDAD_HORARIO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DISPONIBILIDAD_HORARIO])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SC_DISPONIBILIDAD_HORARIO] ADD CONSTRAINT [FK_SC_DISPONIBILIDAD_HORARIO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO
