CREATE TABLE [dbo].[CON_PARAMETRO]
(
[CORR_EMPRESA] [int] NOT NULL,
[NOMBRE_PUESTO1] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[DESCRIPCION_PUESTO1] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_PUESTO2] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[DESCRIPCION_PUESTO2] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_PUESTO3] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[DESCRIPCION_PUESTO3] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[NIVEL_CUENTA_MAYOR] [smallint] NOT NULL,
[CORR_CENTRO_COSTO_DEF] [int] NULL,
[CORR_MONEDA] [int] NOT NULL,
[CUENTA_CONTABLE_PERDIDA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE_GANANCIA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE_IVA_DEBITO] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE_IVA_CREDITO] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE_IVA_RETENIDO] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE_IVA_PERCIBIDO] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE_RENTA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE_CAJA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE_CAJA_CHICA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[APLICAR_DOC_CONTA] [bit] NOT NULL,
[PERIODO_MOSTRAR] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL CONSTRAINT [DF_CON_PARAMETRO_PERIODO_MOSTRAR] DEFAULT ('YY'),
[CARACTER_SEPARADOR] [varchar] (5) COLLATE Latin1_General_CS_AS NULL,
[CUENTA_CONTABLE_CAMBIO_DIFERENCIAL] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[CORR_CLASE_PARTIDA_DEFAULT] [int] NULL,
[OCULTA_CLASE_PARTIDA_BANCOS] [bit] NULL,
[INCLUIR_PARTIDA_LIQUIDACION] [bit] NULL,
[INCLUIR_PARTIDA_CIERRE] [bit] NULL,
[USA_AUXILIARES] [bit] NULL,
[MOSTRAR_FECHA_IMPRESION] [bit] NULL,
[PREFIJO] [varchar] (10) COLLATE Latin1_General_CS_AS NULL,
[CUENTA_CONTABLE_CAMBIO_DIF_GASTO] [varchar] (30) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARAMETRO] ADD CONSTRAINT [PK_CON_PARAMETRO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA]) ON [PRIMARY]
GO
