CREATE TABLE [dbo].[COM_UNIDAD_MEDIDA]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_UNIDAD_MEDIDA] [int] NOT NULL,
[NOMBRE_UNIDAD_MEDIDA] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_CORTO] [varchar] (5) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_UNIDAD_MEDIDA] ADD CONSTRAINT [PK_COM_UNIDAD_MEDIDA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_UNIDAD_MEDIDA]) ON [PRIMARY]
GO
