CREATE TABLE [dbo].[GEN_TIPO_GASTO_IMPUESTO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_TIPO_GASTO] [int] NOT NULL,
[CORR_RUBRO] [int] NOT NULL,
[IMPUESTO_INCLUIDO] [bit] NOT NULL,
[ORDEN_TOTAL] [int] NOT NULL,
[PERMITE_EDITAR] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_TIPO_GASTO_IMPUESTO] ADD CONSTRAINT [PK_GEN_TIPO_GASTO_IMPUESTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_GASTO], [CORR_RUBRO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_TIPO_GASTO_IMPUESTO] ADD CONSTRAINT [FK_GEN_TIPO_GASTO_IMPUESTO_GEN_TIPO_GASTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_TIPO_GASTO]) REFERENCES [dbo].[GEN_TIPO_GASTO] ([CORR_EMPRESA], [CORR_TIPO_GASTO])
GO
