/* SC_EXPEDIENTE_DOCUMENTO — documentos del expediente de candidato */
IF OBJECT_ID(N'dbo.SC_EXPEDIENTE_DOCUMENTO', N'U') IS NULL
BEGIN
  CREATE TABLE [dbo].[SC_EXPEDIENTE_DOCUMENTO] (
    [CORR_EMPRESA] [int] NOT NULL,
    [CORR_EXPEDIENTE_CANDIDATO] [int] NOT NULL,
    [CORR_EXPEDIENTE_DOCUMENTO] [int] NOT NULL,
    [CORR_SOLICITUD_EMPLEO] [int] NOT NULL,
    [FECHA_CARGA] [datetime] NOT NULL,
    [TIPO_DOCUMENTO] [varchar](80) NOT NULL,
    [NOMBRE_ARCHIVO] [varchar](260) NOT NULL,
    [RUTA_ARCHIVO] [varchar](500) NOT NULL,
    [NOTAS] [varchar](1000) NULL,
    [USUARIO_CREA] [varchar](50) NULL,
    [ESTACION_CREA] [varchar](50) NULL,
    [FECHA_CREA] [datetime] NULL,
    [USUARIO_ACTU] [varchar](50) NULL,
    [ESTACION_ACTU] [varchar](50) NULL,
    [FECHA_ACTU] [datetime] NULL,
    CONSTRAINT [PK_SC_EXPEDIENTE_DOCUMENTO] PRIMARY KEY CLUSTERED (
      [CORR_EMPRESA],
      [CORR_EXPEDIENTE_CANDIDATO],
      [CORR_EXPEDIENTE_DOCUMENTO]
    )
  ) ON [PRIMARY];
END
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SC_EXPEDIENTE_DOCUMENTO_EXPEDIENTE'
)
BEGIN
  ALTER TABLE [dbo].[SC_EXPEDIENTE_DOCUMENTO] ADD CONSTRAINT [FK_SC_EXPEDIENTE_DOCUMENTO_EXPEDIENTE]
    FOREIGN KEY ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO])
    REFERENCES [dbo].[SC_EXPEDIENTE_CANDIDATO] ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO]);
END
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SC_EXPEDIENTE_DOCUMENTO_SOLICITUD'
)
BEGIN
  ALTER TABLE [dbo].[SC_EXPEDIENTE_DOCUMENTO] ADD CONSTRAINT [FK_SC_EXPEDIENTE_DOCUMENTO_SOLICITUD]
    FOREIGN KEY ([CORR_EMPRESA], [CORR_SOLICITUD_EMPLEO])
    REFERENCES [dbo].[SC_SOLICITUD_EMPLEO] ([CORR_EMPRESA], [CORR_SOLICITUD_EMPLEO]);
END
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WHERE name = N'IX_SC_EXPEDIENTE_DOCUMENTO_EXPEDIENTE'
    AND object_id = OBJECT_ID(N'dbo.SC_EXPEDIENTE_DOCUMENTO')
)
BEGIN
  CREATE NONCLUSTERED INDEX [IX_SC_EXPEDIENTE_DOCUMENTO_EXPEDIENTE]
    ON [dbo].[SC_EXPEDIENTE_DOCUMENTO] ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO]);
END
GO
