CREATE TABLE [dbo].[CON_CLASE_PARTIDA] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_CLASE_PARTIDA] [int] NOT NULL,
  [NOMBRE_CLASE_PARTIDA] [varchar](60) NOT NULL,
  [NOMBRE_CORTO_CLASE] [varchar](10) NOT NULL,
  [CORR_LINEA_AUMENTA] [int] NULL,
  [CORR_LINEA_DISMINUYE] [int] NULL,
  [ACEPTA_MODIFICACION] [bit] NOT NULL,
  [PARTIDA_CIERRE] [bit] NULL,
  [NOMBRE_REPORTE] [varchar](150) NULL,
  [CODIGO_ODS] [varchar](5) NULL,
  CONSTRAINT [PK_CON_CLASE_PARTIDA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CLASE_PARTIDA])
)
ON [PRIMARY]
GO