CREATE TABLE [dbo].[SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_PERFIL_PUESTO_COMPETENCIAS_TECNICAS] [int] NOT NULL,
  [NOMBRE_COMPETENCIAS_TECNICAS] [varchar](150) NULL,
  [DESCRIPCION] [varchar](500) NULL,
  [NIVEL_DOMINIO] [varchar](50) NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NULL,
  [CORR_PERFIL_PUESTO] [int] NULL,
  [CORR_COMPETENCIAS_TECNICAS] [int] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA],
    [CORR_PERFIL_PUESTO_COMPETENCIAS_TECNICAS]
  ),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS_SC_DESCRIPTOR_PUESTO] FOREIGN KEY (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO]
  ) REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO]
  ),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS_SC_PERFIL_PUESTO] FOREIGN KEY (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_PERFIL_PUESTO]
  ) REFERENCES [dbo].[SC_PERFIL_PUESTO] (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_PERFIL_PUESTO]
  ),
  CONSTRAINT [FK_SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS_SC_COMPETENCIAS_TECNICAS] FOREIGN KEY (
    [CORR_EMPRESA],
    [CORR_COMPETENCIAS_TECNICAS]
  ) REFERENCES [dbo].[SC_COMPETENCIAS_TECNICAS] (
    [CORR_EMPRESA],
    [CORR_COMPETENCIAS_TECNICAS]
  ),
  CONSTRAINT [CK_SC_PERFIL_PUESTO_COMPETENCIAS_TECNICAS_NIVEL_DOMINIO] CHECK (
    [NIVEL_DOMINIO] IN ('BASICO', 'INTERMEDIO', 'AVANZADO')
  )
)
ON [PRIMARY]
GO
