CREATE TABLE [dbo].[COM_SOLI_COTIZACION_DETA_DOC]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_SOLI_COTIZACION] [int] NOT NULL,
[CORR_SOLI_COTIZACION_DETA] [int] NOT NULL,
[CORR_DOCUMENTO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_SOLI_COTIZACION_DETA_DOC] ADD CONSTRAINT [PK_COM_SOLI_COTIZACION_DETA_DOC] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_SOLI_COTIZACION], [CORR_SOLI_COTIZACION_DETA], [CORR_DOCUMENTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_SOLI_COTIZACION_DETA_DOC] ADD CONSTRAINT [FK_COM_SOLI_COTIZACION_DETA_DOC_COM_DOCUMENTO_FISICO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DOCUMENTO]) REFERENCES [dbo].[COM_DOCUMENTO_FISICO] ([CORR_EMPRESA], [CORR_DOCUMENTO])
GO
ALTER TABLE [dbo].[COM_SOLI_COTIZACION_DETA_DOC] ADD CONSTRAINT [FK_COM_SOLI_COTIZACION_DETA_DOC_COM_SOLI_COTIZACION_DETA] FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_SOLI_COTIZACION], [CORR_SOLI_COTIZACION_DETA]) REFERENCES [dbo].[COM_SOLI_COTIZACION_DETA] ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_SOLI_COTIZACION], [CORR_SOLI_COTIZACION_DETA])
GO
