CREATE TABLE [dbo].[CON_CENTRO_COSTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_CENTRO_COSTO] [int] NOT NULL,
  [NOMBRE_CENTRO] [varchar](100) NOT NULL,
  [CUENTA_CONTABLE] [varchar](30) NULL,
  [CODIGO_CENTRO_COSTO] [varchar](30) NULL,
  [CORR_TIPO_CENTRO_COSTO] [int] NULL,
  [ESTADO_CENTRO_COSTO] [varchar](2) NULL,
  [CORR_UNIDAD_NEGOCIO] [int] NULL,
  [CORR_AREA_FUNCIONAL] [int] NULL,
  [CODIGO_TERMINACION] [varchar](30) NULL,
  [CORR_EMPLEADO_JEFE] [int] NULL,
  [CORR_CLIENTE] [int] NULL,
  [FECHA_INICIAL] [date] NULL,
  [FECHA_FINAL] [date] NULL,
  CONSTRAINT [PK_CON_CENTRO_COSTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CENTRO_COSTO])
)
ON [PRIMARY]
GO