CREATE TABLE [dbo].[SC_EXPEDIENTE_SOLICITUD] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_EXPEDIENTE_CANDIDATO] [int] NOT NULL,
  [CORR_EXPEDIENTE_SOLICITUD] [int] NOT NULL,
  [CORR_SOLICITUD_EMPLEO] [int] NOT NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_EXPEDIENTE_SOLICITUD] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA],
    [CORR_EXPEDIENTE_CANDIDATO],
    [CORR_EXPEDIENTE_SOLICITUD]
  )
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SC_EXPEDIENTE_SOLICITUD] ADD CONSTRAINT [FK_SC_EXPEDIENTE_SOLICITUD_EXPEDIENTE]
  FOREIGN KEY ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO])
  REFERENCES [dbo].[SC_EXPEDIENTE_CANDIDATO] ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO])
GO

ALTER TABLE [dbo].[SC_EXPEDIENTE_SOLICITUD] ADD CONSTRAINT [FK_SC_EXPEDIENTE_SOLICITUD_SOLICITUD]
  FOREIGN KEY ([CORR_EMPRESA], [CORR_SOLICITUD_EMPLEO])
  REFERENCES [dbo].[SC_SOLICITUD_EMPLEO] ([CORR_EMPRESA], [CORR_SOLICITUD_EMPLEO])
GO

/* Misma solicitud no puede repetirse dentro del mismo expediente (sí puede estar en N expedientes). */
CREATE UNIQUE NONCLUSTERED INDEX [UX_SC_EXPEDIENTE_SOLICITUD_EXP_SOL]
  ON [dbo].[SC_EXPEDIENTE_SOLICITUD] ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO], [CORR_SOLICITUD_EMPLEO])
GO
