CREATE TABLE [dbo].[SC_IMPACTO_ECONOMICO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_IMPACTO_ECONOMICO] [int] NOT NULL,
  [DESCRIPCION] [varchar](150) NULL,
  [ESTADO_IMPACTO_ECONOMICO] [bit] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_IMPACTO_ECONOMICO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_IMPACTO_ECONOMICO])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SC_IMPACTO_ECONOMICO] ADD CONSTRAINT [FK_SC_IMPACTO_ECONOMICO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO
