CREATE TABLE [dbo].[COM_SOLI_COTIZACION_PROVEEDOR]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_SOLI_COTIZACION] [int] NOT NULL,
[CORR_PROVEEDOR] [int] NOT NULL,
[CORR_CONDICION_PAGO] [int] NULL,
[CORR_FORMA_PAGO] [int] NULL,
[DETALLE_FORMA_PAGO] [varchar] (250) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_CREA] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FECHA_CREA] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_SOLI_COTIZACION_PROVEEDOR] ADD CONSTRAINT [PK_COM_SOLI_COTIZACION_PROVEEDOR] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_SOLI_COTIZACION], [CORR_PROVEEDOR]) ON [PRIMARY]
GO
