CREATE TABLE [dbo].[CON_CATALOGO_CUENTA_AUXI]
(
[CORR_EMPRESA] [int] NOT NULL,
[CUENTA_CONTABLE] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CORR_AUXILIAR] [int] NOT NULL,
[NOMBRE_AUXILIAR] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[CLASE_AUXILIAR] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL,
[CORR_CUENTA_BANCO] [int] NULL,
[CORR_CLIENTE] [int] NULL,
[CORR_PROVEEDOR] [int] NULL,
[CORR_EMPLEADO] [int] NULL,
[CORR_CAJA] [int] NULL,
[CORR_CONFI_PAIS_INTER] [int] NULL,
[CORR_EMPRESA_INTER] [int] NULL,
[CORR_INVERSION] [int] NULL,
[CORR_RUTA_VENTA] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_CATALOGO_CUENTA_AUXI] ADD CONSTRAINT [PK_CON_CATALOGO_CUENTA_AUXI] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CUENTA_CONTABLE], [CORR_AUXILIAR]) ON [PRIMARY]
GO
