CREATE TABLE [dbo].[GEN_GERENCIA]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_DIVISION] [int] NOT NULL,
[CORR_GERENCIA] [int] NOT NULL,
[NOMBRE_GERENCIA] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[CODIGO_GERENCIA] [varchar] (3) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_GERENCIA] ADD CONSTRAINT [PK_CON_GERENCIA] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [CORR_DIVISION], [CORR_GERENCIA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_GERENCIA] ADD CONSTRAINT [UK_CON_GERENCIA] UNIQUE NONCLUSTERED  ([CORR_EMPRESA], [CORR_DIVISION], [CODIGO_GERENCIA]) ON [PRIMARY]
GO
