CREATE TABLE [dbo].[SC_PERSONA_ESTUDIO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_PERSONA_DATOS] [int] NOT NULL,
  [CORR_ESTUDIO] [int] NOT NULL,
  [NIVEL] [varchar](100) NULL,
  [INSTITUCION] [varchar](250) NULL,
  [DESDE] [date] NULL,
  [HASTA] [date] NULL,
  [TITULO] [varchar](250) NULL,
  [USUARIO_CREA] [varchar](30) NOT NULL,
  [ESTACION_CREA] [varchar](50) NOT NULL,
  [FECHA_CREA] [datetime] NOT NULL,
  [USUARIO_ACTU] [varchar](30) NOT NULL,
  [ESTACION_ACTU] [varchar](50) NOT NULL,
  [FECHA_ACTU] [datetime] NOT NULL,
  CONSTRAINT [PK_SC_PERSONA_ESTUDIO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_PERSONA_DATOS], [CORR_ESTUDIO]),
  CONSTRAINT [FK_SC_PERSONA_ESTUDIO_SC_PERSONA_DATOS] FOREIGN KEY ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
    REFERENCES [dbo].[SC_PERSONA_DATOS] ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
)
ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_SC_PERSONA_ESTUDIO_PERSONA]
  ON [dbo].[SC_PERSONA_ESTUDIO] ([CORR_EMPRESA], [CORR_PERSONA_DATOS])
GO
