CREATE TABLE [dbo].[COM_CUADRO_COMPARATIVO_DOC]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_CUADRO_COMPARATIVO] [int] NOT NULL,
[CORR_DOCUMENTO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_CUADRO_COMPARATIVO_DOC] ADD CONSTRAINT [PK_COM_CUADRO_COMPARATIVO_DOC] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_CUADRO_COMPARATIVO], [CORR_DOCUMENTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_CUADRO_COMPARATIVO_DOC] ADD CONSTRAINT [FK_COM_CUADRO_COMPARATIVO_DOC_COM_CUADRO_COMPARATIVO] FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_CUADRO_COMPARATIVO]) REFERENCES [dbo].[COM_CUADRO_COMPARATIVO] ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_CUADRO_COMPARATIVO])
GO
ALTER TABLE [dbo].[COM_CUADRO_COMPARATIVO_DOC] ADD CONSTRAINT [FK_COM_CUADRO_COMPARATIVO_DOC_COM_DOCUMENTO_FISICO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DOCUMENTO]) REFERENCES [dbo].[COM_DOCUMENTO_FISICO] ([CORR_EMPRESA], [CORR_DOCUMENTO])
GO
