CREATE TABLE [dbo].[GEN_TIPO_DOCUMENTO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_TIPO_DOC] [int] NOT NULL,
[NOMBRE_TIPO_DOC] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_CORTO_TIPO_DOC] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[USAR_VENTAS] [bit] NOT NULL,
[USAR_COMPRAS] [bit] NOT NULL,
[CLASE_DOCUMENTO] [varchar] (5) COLLATE Latin1_General_CS_AS NULL,
[SUMA_RESTA] [int] NULL,
[LIBRO_IVA] [varchar] (3) COLLATE Latin1_General_CS_AS NULL,
[ES_ELECTRONICO] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_TIPO_DOCUMENTO] ADD CONSTRAINT [PK_GEN_TIPO_DOCUMENTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_DOC]) ON [PRIMARY]
GO
