CREATE TABLE [dbo].[SC_DESCRIPTOR_FUNCION] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_FUNCION] [int] NOT NULL,
  [NOMBRE_FUNCION] [varchar](255) NULL,
  [TIPO_FUNCION] [varchar](12) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_FUNCION] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO], [CORR_FUNCION]),
  CONSTRAINT [CK_SC_DESCRIPTOR_FUNCION_TIPO_FUNCION] CHECK ([TIPO_FUNCION] = N'CLAVE' OR [TIPO_FUNCION] = N'SECUNDARIA'),
  CONSTRAINT [FK_SC_DESCRIPTOR_FUNCION_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA])
    REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]),
  CONSTRAINT [FK_SC_DESCRIPTOR_FUNCION_SC_DESCRIPTOR_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO])
    REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO])
)
ON [PRIMARY]
GO
