CREATE TABLE [dbo].[SC_TIPO_VACANTE] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_TIPO_VACANTE] [int] NOT NULL,
  [NOMBRE_TIPO_VACANTE] [varchar](250) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_TIPO_VACANTE] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_VACANTE])
)
ON [PRIMARY]
GO