CREATE TABLE [dbo].[SC_DESCRIPTOR_PUESTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_PUESTO] [int] NULL,
  [CORR_UNIDAD] [int] NULL,
  [FECHA_EMISION] [date] NULL,
  [CORR_PUESTO_REPORTA] [int] NULL,
  [FECHA_REVISION] [date] NULL,
  [NUM_PERSONAL_CARGO] [int] NULL,
  [OBJETIVO_PUESTO] [varchar](255) NULL,
  [CORR_IMPACTO_ECONOMICO] [int] NULL,
  [CORR_INDUCCION] [int] NULL,
  [RESPONSABLE] [varchar](100) NULL,
  [FORMATO] [varchar](50) NULL,
  [VERSION] [int] NULL,
  [ESTADO_DESCRIPTOR] [varchar](50) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_PUESTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO])
)
ON [PRIMARY]
GO
