CREATE TABLE [dbo].[BAN_CONCILIA_BANCARIA]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CUENTA_BANCO] [int] NOT NULL,
[CORR_CONCILIACION] [int] NOT NULL,
[FECHA_CONCILIACION] [date] NOT NULL,
[SALDO_CUENTA_BANCO] [decimal] (18, 2) NULL,
[SALDO_CUENTA_CONTA] [decimal] (18, 2) NULL,
[ESTADO_CONCILIACION] [varchar] (2) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA] ADD CONSTRAINT [PK_BAN_CONCILIA_BANCARIA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA] ADD CONSTRAINT [FK_BAN_CONCILIA_BANCARIA_BAN_CUENTA_BANCARIA] FOREIGN KEY ([CORR_EMPRESA], [CORR_CUENTA_BANCO]) REFERENCES [dbo].[BAN_CUENTA_BANCARIA] ([CORR_EMPRESA], [CORR_CUENTA_BANCO])
GO
