CREATE TABLE [dbo].[GEN_RUBRO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_RUBRO] [int] NOT NULL,
[NOMBRE_RUBRO] [varchar] (25) COLLATE Latin1_General_CS_AS NOT NULL,
[DESCRIPCION_RUBRO] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[ES_IMPUESTO] [bit] NOT NULL,
[POR_IMPUESTO] [decimal] (12, 2) NOT NULL,
[MUESTRA_DETALLE] [bit] NOT NULL,
[MUESTRA_TOTAL] [bit] NOT NULL,
[SUMA_RESTA] [int] NOT NULL,
[CLASE_RUBRO] [varchar] (3) COLLATE Latin1_General_CS_AS NULL,
[TIPO_APLICACION] [varchar] (3) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_RUBRO] ADD CONSTRAINT [PK_GEN_RUBRO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_RUBRO]) ON [PRIMARY]
GO
