CREATE TABLE [dbo].[PLA_DEPARTAMENTO_CENTRO_COSTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_CENTRO_COSTO] [int] NOT NULL,
  [CORR_DEPARTAMENTO] [int] NOT NULL,
  CONSTRAINT [PK_PLA_DEPARTAMENTO_CENTRO_COSTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CENTRO_COSTO], [CORR_DEPARTAMENTO])
)
ON [PRIMARY]
GO