CREATE TABLE [dbo].[GEN_EMPLEADO_PUESTO_HISTORIAL]
(
	[CORR_EMPRESA] [int] NOT NULL,
	[CORR_EMPLEADO_PUESTO_HISTORIAL] [int] NOT NULL,
	[FECHA_INICIO] [date] NULL,
	[FECHA_FIN] [date] NULL,
	[CORR_EMPLEADO] [int] NULL,
	[CORR_UNIDAD] [int] NULL,
	[CORR_PUESTO] [int] NULL,
	[SUELDO] [decimal](12, 2) NULL,
	[HORARIO_LABORAL] [varchar](300) NULL,
	[CORR_TIPO_CONTRATACION] [int] NULL,
	[CORR_TIPO_MODALIDAD] [int] NULL,
	[USUARIO_CREA] [varchar](50) NULL,
	[ESTACION_CREA] [varchar](50) NULL,
	[FECHA_CREA] [datetime] NULL,
	[USUARIO_ACTU] [varchar](50) NULL,
	[ESTACION_ACTU] [varchar](50) NULL,
	[FECHA_ACTU] [datetime] NULL,
	CONSTRAINT [PK_GEN_EMPLEADO_PUESTO_HISTORIAL] PRIMARY KEY CLUSTERED
	(
		[CORR_EMPRESA] ASC,
		[CORR_EMPLEADO_PUESTO_HISTORIAL] ASC
	)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GEN_EMPLEADO_PUESTO_HISTORIAL] ADD CONSTRAINT [FK_GEN_EMPLEADO_PUESTO_HISTORIAL_GEN_EMPLEADO] FOREIGN KEY ([CORR_EMPRESA], [CORR_EMPLEADO]) REFERENCES [dbo].[GEN_EMPLEADO] ([CORR_EMPRESA], [CORR_EMPLEADO])
GO
ALTER TABLE [dbo].[GEN_EMPLEADO_PUESTO_HISTORIAL] ADD CONSTRAINT [FK_GEN_EMPLEADO_PUESTO_HISTORIAL_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO
ALTER TABLE [dbo].[GEN_EMPLEADO_PUESTO_HISTORIAL] ADD CONSTRAINT [FK_GEN_EMPLEADO_PUESTO_HISTORIAL_PLA_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_PUESTO]) REFERENCES [dbo].[PLA_PUESTO] ([CORR_EMPRESA], [CORR_PUESTO])
GO
ALTER TABLE [dbo].[GEN_EMPLEADO_PUESTO_HISTORIAL] ADD CONSTRAINT [FK_GEN_EMPLEADO_PUESTO_HISTORIAL_SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES] FOREIGN KEY ([CORR_EMPRESA], [CORR_UNIDAD]) REFERENCES [dbo].[SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES] ([CORR_EMPRESA], [CORR_UNIDAD])
GO
ALTER TABLE [dbo].[GEN_EMPLEADO_PUESTO_HISTORIAL] ADD CONSTRAINT [FK_GEN_EMPLEADO_PUESTO_HISTORIAL_SC_TIPO_CONTRATACION] FOREIGN KEY ([CORR_EMPRESA], [CORR_TIPO_CONTRATACION]) REFERENCES [dbo].[SC_TIPO_CONTRATACION] ([CORR_EMPRESA], [CORR_TIPO_CONTRATACION])
GO
ALTER TABLE [dbo].[GEN_EMPLEADO_PUESTO_HISTORIAL] ADD CONSTRAINT [FK_GEN_EMPLEADO_PUESTO_HISTORIAL_SC_TIPO_MODALIDAD] FOREIGN KEY ([CORR_EMPRESA], [CORR_TIPO_MODALIDAD]) REFERENCES [dbo].[SC_TIPO_MODALIDAD] ([CORR_EMPRESA], [CORR_TIPO_MODALIDAD])
GO
-- Sin CHECK.
-- Sin DEFAULT.
-- Sin índices adicionales.
-- Sin triggers.
GO
