CREATE TABLE [dbo].[CON_CATALOGO_CUENTA_ODS]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_ODS] [int] NOT NULL,
[CUENTA_CONTABLE] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CORR_AUXILIAR] [int] NULL,
[CORR_CENTRO_COSTO] [int] NULL,
[CUENTA_CONTABLE_ODS] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_CUENTA_ODS] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[CORR_AUXILIAR_ODS] [int] NULL,
[NOMBRE_AUXILIAR_ODS] [varchar] (100) COLLATE Latin1_General_CS_AS NULL,
[CORR_CENTRO_COSTO_ODS] [int] NULL,
[NOMBRE_CENTRO_COSTO_ODS] [varchar] (100) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[CON_CATALOGO_CUENTA_ODS] ADD 
CONSTRAINT [PK_CON_CATALOGO_CUENTA_ODS_1] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [CORR_ODS]) ON [PRIMARY]
GO
