IF OBJECT_ID(N'dbo.CLA_COM_PROVEEDOR_SECTOR', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[CLA_COM_PROVEEDOR_SECTOR]
	(
		[CORR_PROVEEDOR] [int] NOT NULL,
		[CORR_SECTOR] [int] NOT NULL,
		CONSTRAINT [PK_CLA_COM_PROVEEDOR_SECTOR] PRIMARY KEY CLUSTERED ([CORR_PROVEEDOR])
	);
END
GO
