CREATE TABLE [dbo].[CON_TIPO_CENTRO_COSTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_TIPO_CENTRO_COSTO] [int] NOT NULL,
  [NOMBRE_TIPO_CENTRO_COSTO] [varchar](150) NULL,
  [CLASE_CENTRO_COSTO] [varchar](3) NULL,
  CONSTRAINT [PK_CON_TIPO_CENTRO_COSTO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_CENTRO_COSTO])
)
ON [PRIMARY]
GO