CREATE TABLE [dbo].[CON_PARTIDA_DETA]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[MES_PERIODO] [int] NOT NULL,
[CORR_CLASE_PARTIDA] [int] NOT NULL,
[CORR_PARTIDA] [int] NOT NULL,
[CORR_PARTIDA_DETA] [int] NOT NULL,
[CUENTA_CONTABLE] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CORR_CENTRO_COSTO] [int] NULL,
[NOMBRE_TRAN] [varchar] (1255) COLLATE Latin1_General_CS_AS NOT NULL,
[MONTO_CARGO] [decimal] (12, 2) NOT NULL,
[MONTO_ABONO] [decimal] (12, 2) NOT NULL,
[ESTA_CONCILIA] [bit] NULL,
[CORR_AUXILIAR] [int] NULL,
[MONTO_CARGO_FORANEA] [decimal] (12, 2) NULL,
[MONTO_ABONO_FORANEA] [decimal] (12, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA_DETA] ADD CONSTRAINT [PK_CON_PARTIDA_DETA] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_CLASE_PARTIDA], [CORR_PARTIDA], [CORR_PARTIDA_DETA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA_DETA] ADD CONSTRAINT [FK_CON_PARTIDA_DETA_CON_CATALOGO_CUENTA] FOREIGN KEY ([CORR_EMPRESA], [CUENTA_CONTABLE]) REFERENCES [dbo].[CON_CATALOGO_CUENTA] ([CORR_EMPRESA], [CUENTA_CONTABLE])
GO
ALTER TABLE [dbo].[CON_PARTIDA_DETA] ADD CONSTRAINT [FK_CON_PARTIDA_DETA_CON_CENTRO_COSTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_CENTRO_COSTO]) REFERENCES [dbo].[CON_CENTRO_COSTO] ([CORR_EMPRESA], [CORR_CENTRO_COSTO])
GO
ALTER TABLE [dbo].[CON_PARTIDA_DETA] ADD CONSTRAINT [FK_CON_PARTIDA_DETA_CON_PARTIDA] FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_CLASE_PARTIDA], [CORR_PARTIDA]) REFERENCES [dbo].[CON_PARTIDA] ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_CLASE_PARTIDA], [CORR_PARTIDA])
GO
