-- Documentación de la tabla ya existente. No ejecutar CREATE en producción.
CREATE TABLE [dbo].[SC_DESCRIPTOR_PUESTO_FIRMAS] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_FIRMAS] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NULL,
  [NOMBRE_COMPLETO] [varchar](100) NULL,
  [TIPO_JEFE] [varchar](50) NULL,
  [TIPO_ACTOR] [varchar](50) NULL,
  [FECHA_FIRMA] [date] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_PUESTO_FIRMAS] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA] ASC,
    [CORR_FIRMAS] ASC
  )
);
-- Sin CHECK.
-- Sin defaults.
ALTER TABLE [dbo].[SC_DESCRIPTOR_PUESTO_FIRMAS] ADD CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_FIRMAS_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]);
ALTER TABLE [dbo].[SC_DESCRIPTOR_PUESTO_FIRMAS] ADD CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_FIRMAS_SC_DESCRIPTOR_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO]) REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO]);
-- Sin índices adicionales.
-- Sin triggers.
GO
