CREATE TABLE [dbo].[GEN_DIVISION] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DIVISION] [int] NOT NULL,
  [NOMBRE_DIVISION] [varchar](100) NULL,
  [CODIGO_DIVISION] [varchar](10) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_GEN_DIVISION] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_DIVISION])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[GEN_DIVISION] ADD CONSTRAINT [FK_GEN_DIVISION_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO

ALTER TABLE [dbo].[GEN_DIVISION] ADD CONSTRAINT [UK_GEN_DIVISION] UNIQUE NONCLUSTERED ([CORR_EMPRESA], [CODIGO_DIVISION])
GO
