CREATE TABLE [dbo].[CON_CATALOGO_CUENTA] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CUENTA_CONTABLE] [varchar](30) NOT NULL,
  [NOMBRE_CUENTA] [varchar](100) NOT NULL,
  [ES_DEBE] [bit] NOT NULL,
  [ES_HABER] [bit] NOT NULL,
  [ES_DETALLE] [bit] NOT NULL,
  [NIVEL] [smallint] NOT NULL,
  [CUENTA_MAYOR] [varchar](30) NULL,
  [CODIGO_RUBRO] [varchar](30) NOT NULL,
  [NO_HABILITADA] [bit] NOT NULL,
  [CLASE_RUBRO] [varchar](2) NULL,
  [ES_LIQUIDADORA] [bit] NULL,
  [CLASE_VALUACION] [varchar](3) NULL,
  CONSTRAINT [PK_CON_CATALOGO_CUENTA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CUENTA_CONTABLE])
)
ON [PRIMARY]
GO

CREATE INDEX [CUENTA_MAYOR_INDEX-20190319-095321]
  ON [dbo].[CON_CATALOGO_CUENTA] ([CUENTA_MAYOR])
  ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE TRIGGER [td_CON_CATALOGO_CUENTA] ON [dbo].[CON_CATALOGO_CUENTA] 
FOR DELETE
AS
	DECLARE
	@numrows  int,
	@numnull  int,
	@errno    int,
	@errmsg   varchar(255),
	@CORR_EMPRESA int,
	@CODIGO_RUBRO varchar(30),
	@CUENTA_CONTABLE varchar(30),
	@NUMERO_CARACTERES int,
	@NIVEL int
BEGIN
	SELECT  @numrows = @@rowcount
	IF @numrows = 0
	RETURN

	IF @numrows > 1
	BEGIN
		SELECT @errno  = 30000,
		@errmsg = 'No se Puede Eliminar Mas de un Registro a la Vez'
		GOTO ERROR
	END
	
	SELECT @CORR_EMPRESA=CORR_EMPRESA,
	@CODIGO_RUBRO=SUBSTRING(A.CUENTA_CONTABLE,1,1),
	@CUENTA_CONTABLE=CUENTA_CONTABLE,
	@NUMERO_CARACTERES=DATALENGTH(A.CUENTA_CONTABLE),	
	@NIVEL=NIVEL
	FROM deleted A			
	
	--Determinar si hay subcuentas
	IF EXISTS(SELECT 1 FROM CON_CATALOGO_CUENTA
			  WHERE CORR_EMPRESA=@CORR_EMPRESA
			  AND SUBSTRING(CUENTA_CONTABLE,1,@NUMERO_CARACTERES)=@CUENTA_CONTABLE
			  AND NIVEL>@NIVEL)
	BEGIN
		SELECT @errno  = 30050,
		@errmsg = 'Existen SubCuentas no Puede Eliminarse'
		GOTO ERROR
	END
	
	--Eliminar la cuenta de la tabla de historicos
	DELETE FROM CON_CATALOGO_SALDO_HIS
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	AND CUENTA_CONTABLE=@CUENTA_CONTABLE
	
	--Eliminar la cuenta del saldo
	DELETE FROM CON_CATALOGO_SALDO
	WHERE CORR_EMPRESA=@CORR_EMPRESA
	AND CUENTA_CONTABLE=@CUENTA_CONTABLE
	
RETURN

/*  ERRORs hANDling  */

ERROR:
	RAISERROR (@errmsg, 16, 1)
	ROLLBACK TRANSACTION
END
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE TRIGGER [ti_CON_CATALOGO_CUENTA] ON [dbo].[CON_CATALOGO_CUENTA]
FOR INSERT
AS
	DECLARE
	@numrows  int,
	@numnull  int,
	@errno    int,
	@errmsg   varchar(255),
	@CORR_EMPRESA int,
	@CODIGO_RUBRO varchar(30),
	@CUENTA_CONTABLE varchar(20),
	@NUMERO_CARACTERES int,
	@NIVEL int,
	@CUENTA_MAYOR varchar(20),
	@NUMERO_CARACTERES_MAYOR int,
	@ES_DEBE bit,
	@ES_HABER bit	
BEGIN
	SELECT  @numrows = @@rowcount
	IF @numrows = 0
	RETURN

	IF @numrows > 1
	BEGIN
		SELECT @errno  = 30000,
		@errmsg = 'No se Puede Insertar Mas de un Registro a la Vez'
		GOTO ERROR
	END

	SELECT @CORR_EMPRESA=CORR_EMPRESA,
	@CODIGO_RUBRO=SUBSTRING(CUENTA_CONTABLE,1,1),
	@CUENTA_CONTABLE=CUENTA_CONTABLE,
	@NUMERO_CARACTERES=LEN(CUENTA_CONTABLE)		
	FROM inserted
	
	IF NOT EXISTS(SELECT 1 FROM CON_RUBRO_NIVEL 
				WHERE CODIGO_RUBRO=@CODIGO_RUBRO
				AND NUMERO_CARACTERES=@NUMERO_CARACTERES 
				AND CORR_EMPRESA=@CORR_EMPRESA)
	BEGIN
		SELECT @errno  = 30020,
		@errmsg = 'NO Existe un Nivel Para la Cantidad de Caracteres de la Cuenta. Verifique el Tamano de la Cuenta'
		GOTO ERROR
	END 
		
	SELECT @NIVEL=NIVEL
	FROM CON_RUBRO_NIVEL
	WHERE CODIGO_RUBRO=@CODIGO_RUBRO
	AND NUMERO_CARACTERES=@NUMERO_CARACTERES
	AND CORR_EMPRESA=@CORR_EMPRESA
		
	IF (@NIVEL > 1)
	BEGIN
		IF NOT EXISTS(SELECT 1 FROM CON_RUBRO_NIVEL
							WHERE CODIGO_RUBRO=@CODIGO_RUBRO
							AND NIVEL=@NIVEL-1 
							AND CORR_EMPRESA=@CORR_EMPRESA
					  )
		BEGIN
			SELECT @errno  = 30030,
			@errmsg = 'ERROR en Tabla Niveles por Rubro. No existe Nivel Anterior'
			GOTO ERROR
		END
		
		SELECT @NUMERO_CARACTERES_MAYOR=A.NUMERO_CARACTERES
		FROM CON_RUBRO_NIVEL A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA
		AND A.CODIGO_RUBRO=@CODIGO_RUBRO
		AND A.NIVEL=@NIVEL-1			
		
		--Obteniendo cuenta de mayor
		IF NOT EXISTS(SELECT 1 FROM CON_CATALOGO_CUENTA A
				  WHERE A.CORR_EMPRESA=@CORR_EMPRESA		  
				  AND A.CUENTA_CONTABLE=SUBSTRING(@CUENTA_CONTABLE,1,@NUMERO_CARACTERES_MAYOR))				  
				  
		BEGIN
			SELECT @errno  = 30030,
			@errmsg = 'No Existe cuenta de Mayor.'
			GOTO ERROR
		END
		
		SELECT @CUENTA_MAYOR=CUENTA_CONTABLE
		FROM CON_CATALOGO_CUENTA A
		WHERE A.CORR_EMPRESA=@CORR_EMPRESA				  
		AND A.CUENTA_CONTABLE=SUBSTRING(@CUENTA_CONTABLE,1,@NUMERO_CARACTERES_MAYOR)
		
		--Verificando que la cuenta de mayor NO sea de detalle
		IF EXISTS(SELECT 1 FROM CON_CATALOGO_CUENTA
				  WHERE CORR_EMPRESA=@CORR_EMPRESA
				  AND CUENTA_CONTABLE=@CUENTA_MAYOR
				  AND ISNULL(ES_DETALLE,0)=1)
		BEGIN
			SELECT @errno  = 30030,
			@errmsg = 'Cuenta de Mayor es de Detalle'
			GOTO ERROR
		END				
	END	

RETURN

/*  ERRORS HANDLING  */

ERROR:
	RAISERROR (@errmsg, 16, 1)
	ROLLBACK TRANSACTION
END
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE TRIGGER [tu_CON_CATALOGO_CUENTA] ON [dbo].[CON_CATALOGO_CUENTA] 
FOR UPDATE 
AS
	DECLARE
	@numrows  int,
	@numnull  int,
	@errno    int,
	@errmsg   varchar(255),
	@CORR_EMPRESA INT,	
	@CUENTA_CONTABLE varchar(30),
	@NUMERO_CARACTERES int,
	@NIVEL int,	
	@ES_DETALLE BIT
BEGIN
	SELECT  @numrows = @@rowcount
	IF @numrows = 0
	RETURN

	IF @numrows > 1
	BEGIN
		SELECT @errno  = 30000,
		@errmsg = 'No se Puede Actualizar Más de un Registro a la Vez'
		GOTO ERROR
	END

	SELECT @CORR_EMPRESA=CORR_EMPRESA,
	@ES_DETALLE=ES_DETALLE,
	@CUENTA_CONTABLE=CUENTA_CONTABLE,
	@NIVEL=NIVEL
	FROM inserted
	
	--Evaluando que no se ponga como general una cuenta con movimientos y una de detalle con subcuentas
	IF UPDATE(ES_DETALLE)
	BEGIN
		IF @ES_DETALLE=0
		BEGIN
			IF EXISTS(SELECT 1 FROM CON_PARTIDA_DETA 
					WHERE CORR_EMPRESA=@CORR_EMPRESA
					AND CUENTA_CONTABLE=@CUENTA_CONTABLE)
			BEGIN
				SELECT @errno  = 30050,
				@errmsg = 'Existen Comprobantes Contables no puede ser General'
				GOTO ERROR
			END
		END ELSE
		BEGIN			
			--Determinar si hay subcuentas
			IF EXISTS(SELECT 1 FROM CON_CATALOGO_CUENTA
			  WHERE CORR_EMPRESA=@CORR_EMPRESA
			  AND SUBSTRING(CUENTA_CONTABLE,1,@NUMERO_CARACTERES)=@CUENTA_CONTABLE
			  AND NIVEL>@NIVEL)
			BEGIN
				SELECT @errno  = 30050,
				@errmsg = 'Existen SubCuentas no Puede Ser de Detalle'
				GOTO ERROR
			END			
		END						
	END		

RETURN

/*  ERRORs HANDLING  */

ERROR:
	RAISERROR (@errmsg, 16, 1)
	ROLLBACK TRANSACTION
END
GO