CREATE TABLE [dbo].[GEN_UNIDADES_PUESTO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_UNIDAD] [int] NOT NULL,
  [CORR_PUESTO] [int] NOT NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NOT NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_GEN_UNIDADES_PUESTO] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA],
    [CORR_UNIDAD],
    [CORR_PUESTO]
  )
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[GEN_UNIDADES_PUESTO] ADD CONSTRAINT [FK_GEN_UNIDADES_PUESTO_UNIDADES]
  FOREIGN KEY ([CORR_EMPRESA], [CORR_UNIDAD])
  REFERENCES [dbo].[SC_ORGANIGRAMA_ESTRUCTURAL_UNIDADES] ([CORR_EMPRESA], [CORR_UNIDAD])
GO

ALTER TABLE [dbo].[GEN_UNIDADES_PUESTO] ADD CONSTRAINT [FK_GEN_UNIDADES_PUESTO_PUESTO]
  FOREIGN KEY ([CORR_EMPRESA], [CORR_PUESTO])
  REFERENCES [dbo].[PLA_PUESTO] ([CORR_EMPRESA], [CORR_PUESTO])
GO
