CREATE TABLE [dbo].[GEN_GERENCIA] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_GERENCIA] [int] NOT NULL,
  [NOMBRE_GERENCIA] [varchar](100) NULL,
  [CODIGO_GERENCIA] [varchar](10) NULL,
  [CORR_DIVISION] [int] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_GEN_GERENCIA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_GERENCIA])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[GEN_GERENCIA] ADD CONSTRAINT [FK_GEN_GERENCIA_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO

ALTER TABLE [dbo].[GEN_GERENCIA] ADD CONSTRAINT [FK_GEN_GERENCIA_GEN_DIVISION] FOREIGN KEY ([CORR_EMPRESA], [CORR_DIVISION]) REFERENCES [dbo].[GEN_DIVISION] ([CORR_EMPRESA], [CORR_DIVISION])
GO
