CREATE TABLE [dbo].[SC_DESCRIPTOR_PUESTO_RESPONSABILIDAD_CARGO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_DESCRIPTOR_PUESTO] [int] NOT NULL,
  [CORR_RESPONSABILIDAD] [int] NOT NULL,
  [NOMBRE_RESPONSABILIDAD] [varchar](150) NULL,
  [INFORMACION] [varchar](255) NULL,
  [APLICA_DESCRIPTOR] [varchar](50) NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_DESCRIPTOR_PUESTO_RESPONSABILIDAD_CARGO] PRIMARY KEY CLUSTERED (
    [CORR_EMPRESA],
    [CORR_DESCRIPTOR_PUESTO],
    [CORR_RESPONSABILIDAD]
  ),
  CONSTRAINT [CK__SC_DESCRI__APLIC__548D349B] CHECK ([APLICA_DESCRIPTOR]='AMBOS' OR [APLICA_DESCRIPTOR]='EXTENSO' OR [APLICA_DESCRIPTOR]='CORTO'),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_RESPONSABILIDAD_CARGO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA])
    REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_RESPONSABILIDAD_CARGO_SC_DESCRIPTOR_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO])
    REFERENCES [dbo].[SC_DESCRIPTOR_PUESTO] ([CORR_EMPRESA], [CORR_DESCRIPTOR_PUESTO]),
  CONSTRAINT [FK_SC_DESCRIPTOR_PUESTO_RESPONSABILIDAD_CARGO_SC_RESPONSABILIDAD_CARGO] FOREIGN KEY ([CORR_EMPRESA], [CORR_RESPONSABILIDAD])
    REFERENCES [dbo].[SC_RESPONSABILIDAD_CARGO] ([CORR_EMPRESA], [CORR_RESPONSABILIDAD])
)
ON [PRIMARY]
GO
