CREATE TABLE [dbo].[SC_COMPETENCIAS_CONDUCTUALES] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_COMPETENCIAS_CONDUCTUALES] [int] NOT NULL,
  [CORR_TIPO_PUESTO] [int] NULL,
  [NOMBRE_COMPETENCIAS_CONDUCTUALES] [varchar](150) NULL,
  [DESCRIPCION] [varchar](500) NULL,
  [ESTADO_COMPETENCIAS_CONDUCTUALES] [bit] NULL CONSTRAINT [DF_SC_COMPETENCIAS_CONDUCTUALES_ESTADO] DEFAULT ((1)),
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_COMPETENCIAS_CONDUCTUALES] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_COMPETENCIAS_CONDUCTUALES])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SC_COMPETENCIAS_CONDUCTUALES] ADD CONSTRAINT [FK_SC_COMPETENCIAS_CONDUCTUALES_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO

ALTER TABLE [dbo].[SC_COMPETENCIAS_CONDUCTUALES] ADD CONSTRAINT [FK_SC_COMPETENCIAS_CONDUCTUALES_PLA_TIPO_PUESTO] FOREIGN KEY ([CORR_EMPRESA], [CORR_TIPO_PUESTO]) REFERENCES [dbo].[PLA_TIPO_PUESTO] ([CORR_EMPRESA], [CORR_TIPO_PUESTO])
GO
