CREATE TABLE [dbo].[BAN_TIPO_MOVI_BANCARIO]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_TIPO_MOVIMIENTO] [int] NOT NULL,
[NOMBRE_TIPO_MOVIMIENTO] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_TIPO_CORTO] [varchar] (5) COLLATE Latin1_General_CS_AS NOT NULL,
[CORR_LINEA] [int] NOT NULL,
[CORR_CLASE_PARTIDA] [int] NOT NULL,
[USA_CHEQUE_PROPIO] [bit] NOT NULL,
[SUMA_RESTA] [int] NOT NULL,
[CLASE_MOVIMIENTO] [varchar] (3) COLLATE Latin1_General_CS_AS NOT NULL,
[CUENTA_CONTABLE_GASTO] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[NOMBRE_REPORTE] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_TIPO_MOVI_BANCARIO] ADD CONSTRAINT [PK_BAN_TIPO_MOVI_BANCARIO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_TIPO_MOVIMIENTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_TIPO_MOVI_BANCARIO] ADD CONSTRAINT [FK_BAN_TIPO_MOVI_BANCARIO_CON_CLASE_PARTIDA] FOREIGN KEY ([CORR_EMPRESA], [CORR_CLASE_PARTIDA]) REFERENCES [dbo].[CON_CLASE_PARTIDA] ([CORR_EMPRESA], [CORR_CLASE_PARTIDA])
GO
ALTER TABLE [dbo].[BAN_TIPO_MOVI_BANCARIO] ADD CONSTRAINT [FK_BAN_TIPO_MOVI_BANCARIO_BAN_LINEA_TRABAJO_CONCILIACION] FOREIGN KEY ([CORR_EMPRESA], [CORR_LINEA]) REFERENCES [dbo].[BAN_LINEA_TRABAJO_CONCILIACION] ([CORR_EMPRESA], [CORR_LINEA])
GO
