CREATE TABLE [dbo].[SEG_SUITE]
(
[CODIGO_SUITE] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_SUITE] [varchar] (100) COLLATE Latin1_General_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEG_SUITE] ADD CONSTRAINT [PK_SEG_SUITE] PRIMARY KEY CLUSTERED ([CODIGO_SUITE]) ON [PRIMARY]
GO
