CREATE TABLE [dbo].[COM_CUADRO_COMPARATIVO_AUTORIZACIONES]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_CUADRO_COMPARATIVO] [int] NOT NULL,
[LOGIN_SISTEMA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[NOMBRE_CARGO] [varchar] (150) COLLATE Latin1_General_CS_AS NULL,
[MONTO_INICIAL] [decimal] (18, 2) NULL,
[MONTO_FINAL] [decimal] (18, 2) NULL,
[CLASE_AUTORIZACION] [varchar] (5) COLLATE Latin1_General_CS_AS NULL,
[ORDEN_REVISION] [int] NULL,
[PERMITE_MODIFICAR] [bit] NULL,
[ESTADO_AUTORIZACION] [varchar] (5) COLLATE Latin1_General_CS_AS NULL,
[FECHA_AUTORIZACION] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_CUADRO_COMPARATIVO_AUTORIZACIONES] ADD CONSTRAINT [PK_COM_CUADRO_COMPARATIVO_AUTORIZACIONES] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_CUADRO_COMPARATIVO], [LOGIN_SISTEMA]) ON [PRIMARY]
GO
