CREATE TABLE [dbo].[CON_PARTIDA_PLA]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[MES_PERIODO] [int] NOT NULL,
[CORR_CLASE_PARTIDA] [int] NOT NULL,
[CORR_PARTIDA] [int] NOT NULL,
[FECHA_PARTIDA] [date] NOT NULL,
[NUMERO_DOCUMENTO] [varchar] (25) COLLATE Latin1_General_CS_AS NULL,
[NOMBRE_PARTIDA] [varchar] (255) COLLATE Latin1_General_CS_AS NULL,
[ESTADO_PARTIDA] [varchar] (2) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA] [datetime] NOT NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[USUARIO_ACTU] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[FECHA_ACTU] [datetime] NULL,
[ESTACION_ACTU] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA_PLA] ADD CONSTRAINT [PK_CON_PARTIDA_ENCA_PLA] PRIMARY KEY CLUSTERED  ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_CLASE_PARTIDA], [CORR_PARTIDA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA_PLA] ADD CONSTRAINT [FK_CON_PARTIDA_PLA_CON_PERIODO_CONTABLE] FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO]) REFERENCES [dbo].[CON_PERIODO_CONTABLE] ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO])
GO
ALTER TABLE [dbo].[CON_PARTIDA_PLA] ADD CONSTRAINT [FK_CON_PARTIDA_PLA_CON_CLASE_PARTIDA] FOREIGN KEY ([CORR_EMPRESA], [CORR_CLASE_PARTIDA]) REFERENCES [dbo].[CON_CLASE_PARTIDA] ([CORR_EMPRESA], [CORR_CLASE_PARTIDA])
GO
