CREATE TABLE [dbo].[COM_DOCUMENTO_TOTAL]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[MES_PERIODO] [int] NOT NULL,
[CORR_DOCUMENTO] [int] NOT NULL,
[CORR_RUBRO] [int] NOT NULL,
[MONTO_RUBRO] [money] NOT NULL,
[IMPUESTO_INCLUIDO] [int] NULL,
[ORDEN_TOTAL] [int] NULL,
[PERMITE_EDITAR] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_DOCUMENTO_TOTAL] ADD CONSTRAINT [PK_COM_DOCUMENTO_TOTAL] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_DOCUMENTO], [CORR_RUBRO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_DOCUMENTO_TOTAL] ADD CONSTRAINT [FK_COM_DOCUMENTO_TOTAL_COM_DOCUMENTO] FOREIGN KEY ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_DOCUMENTO]) REFERENCES [dbo].[COM_DOCUMENTO] ([CORR_EMPRESA], [ANIO_PERIODO], [MES_PERIODO], [CORR_DOCUMENTO])
GO
