CREATE TABLE [dbo].[CON_PARTIDA_BITACORA]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_PARTIDA_BITACORA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[MES_PERIODO] [int] NOT NULL,
[CORR_CLASE_PARTIDA] [int] NOT NULL,
[CORR_PARTIDA] [int] NOT NULL,
[TIPO_EVENTO] [varchar] (20) COLLATE Latin1_General_CS_AS NULL,
[FECHA_EVENTO] [datetime] NULL,
[ESTADO_ANTERIOR] [varchar] (2) COLLATE Latin1_General_CS_AS NULL,
[ESTADO_NUEVO] [varchar] (2) COLLATE Latin1_General_CS_AS NULL,
[OBSERVACION] [varchar] (255) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_CREA] [varchar] (30) COLLATE Latin1_General_CS_AS NULL,
[ESTACION_CREA] [varchar] (50) COLLATE Latin1_General_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA_BITACORA] ADD CONSTRAINT [PK_CON_PARTIDA_BITACORA] PRIMARY KEY CLUSTERED
(
	[CORR_EMPRESA],
	[ANIO_PERIODO],
	[MES_PERIODO],
	[CORR_CLASE_PARTIDA],
	[CORR_PARTIDA],
	[CORR_PARTIDA_BITACORA]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CON_PARTIDA_BITACORA] ADD CONSTRAINT [CK_CON_PARTIDA_BITACORA_TIPO_EVENTO] CHECK
(
	[TIPO_EVENTO] = 'INGRESAR'
	OR [TIPO_EVENTO] = 'ACTUALIZAR'
	OR [TIPO_EVENTO] = 'APLICAR'
	OR [TIPO_EVENTO] = 'DESAPLICAR'
	OR [TIPO_EVENTO] = 'ANULAR'
)
GO
ALTER TABLE [dbo].[CON_PARTIDA_BITACORA] ADD CONSTRAINT [FK_CON_PARTIDA_BITACORA_GEN_EMPRESA]
	FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO
ALTER TABLE [dbo].[CON_PARTIDA_BITACORA] ADD CONSTRAINT [FK_CON_PARTIDA_BITACORA_CON_PARTIDA]
	FOREIGN KEY
	(
		[CORR_EMPRESA],
		[ANIO_PERIODO],
		[MES_PERIODO],
		[CORR_CLASE_PARTIDA],
		[CORR_PARTIDA]
	)
	REFERENCES [dbo].[CON_PARTIDA]
	(
		[CORR_EMPRESA],
		[ANIO_PERIODO],
		[MES_PERIODO],
		[CORR_CLASE_PARTIDA],
		[CORR_PARTIDA]
	)
GO
