CREATE TABLE [dbo].[SC_RESPONSABILIDAD_CARGO] (
  [CORR_EMPRESA] [int] NOT NULL,
  [CORR_RESPONSABILIDAD] [int] NOT NULL,
  [NOMBRE_RESPONSABILIDAD] [varchar](150) NULL,
  [ESTADO_RESPONSABILIDAD] [bit] NULL,
  [USUARIO_CREA] [varchar](50) NULL,
  [ESTACION_CREA] [varchar](50) NULL,
  [FECHA_CREA] [datetime] NULL,
  [USUARIO_ACTU] [varchar](50) NULL,
  [ESTACION_ACTU] [varchar](50) NULL,
  [FECHA_ACTU] [datetime] NULL,
  CONSTRAINT [PK_SC_RESPONSABILIDAD_CARGO] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_RESPONSABILIDAD])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SC_RESPONSABILIDAD_CARGO] ADD CONSTRAINT [FK_SC_RESPONSABILIDAD_CARGO_GEN_EMPRESA] FOREIGN KEY ([CORR_EMPRESA]) REFERENCES [dbo].[GEN_EMPRESA] ([CORR_EMPRESA])
GO
