CREATE TABLE [dbo].[BAN_CONCILIA_BANCARIA_MOVI]
(
[CORR_EMPRESA] [int] NOT NULL,
[CORR_CUENTA_BANCO] [int] NOT NULL,
[CORR_CONCILIACION] [int] NOT NULL,
[CORR_MOVIMIENTO] [int] NOT NULL,
[CORR_LINEA] [int] NOT NULL,
[ANIO_PERIODO] [int] NULL,
[MES_PERIODO] [int] NULL,
[CORR_CLASE_PARTIDA] [int] NULL,
[CORR_PARTIDA] [int] NULL,
[CORR_PARTIDA_DETA] [int] NULL,
[CORR_TIPO_MOVIMIENTO] [int] NULL,
[CORR_CONCILIACION_DETA] [int] NULL,
[MONTO_CARGO] [decimal] (18, 2) NOT NULL,
[MONTO_ABONO] [decimal] (18, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA_MOVI] ADD CONSTRAINT [PK_BAN_CONCILIA_BANCARIA_MOVI] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION], [CORR_MOVIMIENTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA_MOVI] ADD CONSTRAINT [FK_BAN_CONCILIA_BANCARIA_MOVI_BAN_CONCILIA_BANCARIA] FOREIGN KEY ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION]) REFERENCES [dbo].[BAN_CONCILIA_BANCARIA] ([CORR_EMPRESA], [CORR_CUENTA_BANCO], [CORR_CONCILIACION])
GO
ALTER TABLE [dbo].[BAN_CONCILIA_BANCARIA_MOVI] ADD CONSTRAINT [FK_BAN_CONCILIA_BANCARIA_MOVI_BAN_LINEA_TRABAJO_CONCILIACION] FOREIGN KEY ([CORR_EMPRESA], [CORR_LINEA]) REFERENCES [dbo].[BAN_LINEA_TRABAJO_CONCILIACION] ([CORR_EMPRESA], [CORR_LINEA])
GO
