CREATE TABLE [dbo].[COM_BITACORA]
(
[CORR_EMPRESA] [int] NOT NULL,
[ANIO_PERIODO] [int] NOT NULL,
[CORR_BITACORA] [int] NOT NULL,
[FECHA_BITACORA] [date] NOT NULL,
[CODIGO_OPCION] [varchar] (30) COLLATE Latin1_General_CS_AS NOT NULL,
[CLASE_BITACORA] [varchar] (2) COLLATE Latin1_General_CS_AS NOT NULL,
[LLAVE_TRANSACCION] [varchar] (250) COLLATE Latin1_General_CS_AS NOT NULL,
[REFERENCIA_TRANSACCION] [varchar] (500) COLLATE Latin1_General_CS_AS NULL,
[USUARIO_CREA_TRANS] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[ESTACION_CREA_TRANS] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA_TRANS] [datetime] NOT NULL,
[USUARIO_ACTU_TRANS] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[ESTACION_ACTU_TRANS] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_ACTU_TRANS] [datetime] NOT NULL,
[USUARIO_CREA_BITACORA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[ESTACION_CREA_BITACORA] [varchar] (50) COLLATE Latin1_General_CS_AS NOT NULL,
[FECHA_CREA_BITACORA] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_BITACORA] ADD CONSTRAINT [PK_COM_BITACORA] PRIMARY KEY CLUSTERED ([CORR_EMPRESA], [ANIO_PERIODO], [CORR_BITACORA]) ON [PRIMARY]
GO
