/* SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO — adjuntos de una entrevista (1..N) */
IF OBJECT_ID(N'dbo.SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO', N'U') IS NULL
BEGIN
  CREATE TABLE [dbo].[SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO] (
    [CORR_EMPRESA] [int] NOT NULL,
    [CORR_EXPEDIENTE_CANDIDATO] [int] NOT NULL,
    [CORR_EXPEDIENTE_ENTREVISTA] [int] NOT NULL,
    [CORR_ENTREVISTA_DOCUMENTO] [int] NOT NULL,
    [FECHA_CARGA] [datetime] NOT NULL,
    [NOMBRE_ARCHIVO] [varchar](260) NOT NULL,
    [RUTA_ARCHIVO] [varchar](500) NOT NULL,
    [NOTAS] [varchar](1000) NULL,
    [USUARIO_CREA] [varchar](50) NULL,
    [ESTACION_CREA] [varchar](50) NULL,
    [FECHA_CREA] [datetime] NULL,
    [USUARIO_ACTU] [varchar](50) NULL,
    [ESTACION_ACTU] [varchar](50) NULL,
    [FECHA_ACTU] [datetime] NULL,
    CONSTRAINT [PK_SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO] PRIMARY KEY CLUSTERED (
      [CORR_EMPRESA],
      [CORR_EXPEDIENTE_CANDIDATO],
      [CORR_EXPEDIENTE_ENTREVISTA],
      [CORR_ENTREVISTA_DOCUMENTO]
    )
  ) ON [PRIMARY];
END
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO_ENTREVISTA'
)
BEGIN
  ALTER TABLE [dbo].[SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO]
    ADD CONSTRAINT [FK_SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO_ENTREVISTA]
    FOREIGN KEY ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO], [CORR_EXPEDIENTE_ENTREVISTA])
    REFERENCES [dbo].[SC_EXPEDIENTE_ENTREVISTA] ([CORR_EMPRESA], [CORR_EXPEDIENTE_CANDIDATO], [CORR_EXPEDIENTE_ENTREVISTA])
    ON DELETE CASCADE;
END
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE name = N'IX_SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO_ENTREVISTA'
    AND object_id = OBJECT_ID(N'dbo.SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO')
)
BEGIN
  CREATE NONCLUSTERED INDEX [IX_SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO_ENTREVISTA]
    ON [dbo].[SC_EXPEDIENTE_ENTREVISTA_DOCUMENTO] (
      [CORR_EMPRESA],
      [CORR_EXPEDIENTE_CANDIDATO],
      [CORR_EXPEDIENTE_ENTREVISTA]
    );
END
GO
